@@ HEAD @@
import Base
import ../../src/obj.bend as O
import ../../types/fulu_obj.bend as T
import ../compact/found.bend as FD
import ../compact/arith.bend as A
import ../../proofs/nat_order.bend as Order
import ./spec_fixed.bend as FX
import ./vspec.bend as VS
import ./vbuf.bend as VB
import ./vfix.bend as VF
import ./vbrt.bend as VR
import ./vua.bend as UA
import ./vuw.bend as UW
import ./vuw1.bend as UB1
import ./vuw2.bend as UB2
import ./vuw3.bend as UB3
import ./vuwd.bend as UWD
@IMPORTS
# GENERATED by word_vector_writer_laws (codegen). Do not edit.
# @WHAT at any byte position X = 4 q + r, in the tight, data-only form of vuwd's b20_any
# (see codegen/proofs/var/word_vector_writer_laws.py).

@@ vec_text @@

# ---- ${p}: T.${C}, ${N} words ----

def PX_${p}(+r: Nat, +dd: Nat, +D: FD.array__Tree<U32>, +q: Nat, ${WP}) -> FD.array__Tree<U32>:
  match r:
    case 0n: VF.updv(${L}, dd, D, q)
    case 1n: UW.SWc(1, ${L}, dd, D, q, 0)
    case 2n: UW.SWc(2, ${L}, dd, D, q, 0)
    case 3n: UW.SWc(3, ${L}, dd, D, q, 0)
    case 4n+t: D

def ${p}x_perfect(+r: Nat, +dd: Nat, +D: FD.array__Tree<U32>, +q: Nat, ${WP}, ${PF})
    -> {FD.array__perfect(U32, dd, ${PX('r')}) == True{} : Bool}:
  match r:
    case 0n: VF.updv_perfect(${L}, dd, D, q, pf)
    case 1n: UW.swc_perfect(1, ${L}, dd, D, q, 0, pf)
    case 2n: UW.swc_perfect(2, ${L}, dd, D, q, 0, pf)
    case 3n: UW.swc_perfect(3, ${L}, dd, D, q, 0, pf)
    case 4n+ +t: pf

# T.${p}_put at any byte position X = 4 q + r.
def ${p}_any(+dd: Nat, +D: FD.array__Tree<U32>, +X: U32, +q: Nat, +r: Nat, ${WP}, ${E_},
    ${HD}, ${HL}, ${PF}, ${HZ})
    -> ${RT('r')}:
  match r:
    case 0n: ${AL}(dd, D, X, q, FD.logic__subst(Nat, z => {U32.to_nat(X) == z : Nat}, Nat.add(A.quad(q), 0n), A.quad(q), FD.nat__add_zero(A.quad(q)), e), hd, pf,
      FD.logic__subst(Nat, z => {Nat.is_le(z, VB.pw(dd)) == True{} : Bool}, Nat.add(q, ${N}n), Nat.add(${N}n, q), FD.nat__add_comm(q, ${N}n), hl), ${W})
@@ vec_text_2 @@
    case 4n+ +t: Empty.absurd(${RT('4n+t')}, FD.nat__lt_zero_absurd(t, hr))

# Its bytes: the words' limbs at X, when the ${m} bytes there were zero.
def ${p}_any_bytes(+dd: Nat, +D: FD.array__Tree<U32>, +X: U32, +q: Nat, +r: Nat, ${WP}, ${E_},
    ${HD}, ${HL}, ${PF}, ${HZ})
    -> ${BY('r', 'Nat.add(A.quad(q), r)')}:
  match r:
    case 0n:
      %Equal.sym(Nat, Nat.add(A.quad(q), 0n), A.quad(q), FD.nat__add_zero(A.quad(q))) : ${BY('0n', '_')}
      UW.updv_bytes(${L}, dd, D, q, pf, hl)
@@ b256_text @@
,
    +hd: {Nat.is_lt(dd, 29n) == True{} : Bool}, +hl: {Nat.is_le(Nat.add(q, UWD.NWN(Nat.add(r, 256n))), VB.pw(dd)) == True{} : Bool},
    +pf: {FD.array__perfect(U32, dd, D) == True{} : Bool}, +pfB: {FD.array__perfect(U32, dB, TB) == True{} : Bool},
    +hdB: {Nat.is_lt(dB, 31n) == True{} : Bool}, +hrB: {Nat.is_le(64n, VB.pw(dB)) == True{} : Bool},
    +hz: {VS.bt(256n, VS.bdr(Nat.add(A.quad(q), r), UA.BYT(D))) == UW.ZB(256n) : +List<U32>}
@@ b256_text_TKS @@

# ---- b256: T.b256_putk over the O.Words of 256 bytes held in TB ----

# The first k words of L from word i, as a list of its slots.
def TKS(+k: Nat, +i: Nat, +L: List<&2, U32>) -> List<&2, U32>:
  match k:
    case 0n: []
    case 1n+p: Con{FD.flat__nthc(L, i), TKS(p, 1n+i, L)}

law tks:
  for +k: Nat
  for +i: Nat
  for +L: List<&2, U32>
  for +h: {Nat.is_le(Nat.add(i, k), VB.len(L)) == True{} : Bool}
  {VS.wtake(k, VB.wdr(i, L)) == TKS(k, i, L) : List<&2, U32>}
def tks(k, i, L, h):
  match k:
    case 0n: {==}
    case 1n+ +p:
      +hi = FD.nat__le_lt_trans(i, Nat.add(i, p), VB.len(L), Order.below_sum(i, p),
        FD.nat__succ_le_lt(Nat.add(i, p), VB.len(L), FD.logic__subst(Nat, z => {Nat.is_le(z, VB.len(L)) == True{} : Bool}, Nat.add(i, 1n+p), 1n+Nat.add(i, p), FD.nat__add_succ(i, p), h)))
      %Equal.sym(List<&2, U32>, VB.wdr(i, L), Con{FD.flat__nthc(L, i), VB.wdr(1n+i, L)}, UW.wdr_con(L, i, hi)) :
        {VS.wtake(1n+p, _) == TKS(1n+p, i, L) : List<&2, U32>}
      Equal.cong(List<&2, U32>, List<&2, U32>, z => Con{FD.flat__nthc(L, i), z}, VS.wtake(p, VB.wdr(1n+i, L)), TKS(p, 1n+i, L),
        tks(p, 1n+i, L, FD.logic__subst(Nat, z => {Nat.is_le(z, VB.len(L)) == True{} : Bool}, Nat.add(i, 1n+p), Nat.add(1n+i, p), FD.nat__add_succ(i, p), h)))

def wl_b256(+dB: Nat, +TB: FD.array__Tree<U32>, +pfB: {FD.array__perfect(U32, dB, TB) == True{} : Bool}, +hrB: {Nat.is_le(64n, VB.pw(dB)) == True{} : Bool})
    -> {VW.WL_b256(TB) == ${WS} : List<&2, U32>}:
  Equal.sym(List<&2, U32>, ${WS}, VW.WL_b256(TB),
    tks(64n, 0n, UW.SLW(TB), FD.logic__subst(Nat, z => {Nat.is_le(64n, z) == True{} : Bool}, VB.pw(dB), VB.len(UW.SLW(TB)), Equal.sym(Nat, VB.len(UW.SLW(TB)), VB.pw(dB), FD.array__slots_length(U32, dB, TB, pfB)), hrB)))


# Its storage check holds on a valid storage tree (the runtime's T.b256_valid).
def b256_valid_ok(+dB: Nat, +TB: FD.array__Tree<U32>, +pfB: {FD.array__perfect(U32, dB, TB) == True{} : Bool},
    +hdB: {Nat.is_lt(dB, 31n) == True{} : Bool}, +hrB: {Nat.is_le(64n, VB.pw(dB)) == True{} : Bool})
    -> {T.b256_valid(O.Words{FD.array__thaw(U32, TB), 256}) == (O.Words{FD.array__thaw(U32, TB), 256}, True{}) : O.Words & Bool}:
  VBE.words_ok_b(dB, TB, 256, 256, 256, 9n, pfB, hdB, {==}, {==}, {==}, {==}, hrB, {==}, 1, {==})

def PX_b256(+r: Nat, +dd: Nat, +D: FD.array__Tree<U32>, +q: Nat, +TB: FD.array__Tree<U32>) -> FD.array__Tree<U32>:
  match r:
    case 0n: VF.updv(${WS}, dd, D, q)
    case 1n: UW.SWc(1, ${WS}, dd, D, q, 0)
    case 2n: UW.SWc(2, ${WS}, dd, D, q, 0)
    case 3n: UW.SWc(3, ${WS}, dd, D, q, 0)
    case 4n+t: D

def b256x_perfect(+r: Nat, +dd: Nat, +D: FD.array__Tree<U32>, +q: Nat, +TB: FD.array__Tree<U32>, +pf: {FD.array__perfect(U32, dd, D) == True{} : Bool})
    -> {FD.array__perfect(U32, dd, ${PX('r')}) == True{} : Bool}:
  match r:
    case 0n: VF.updv_perfect(${WS}, dd, D, q, pf)
    case 1n: UW.swc_perfect(1, ${WS}, dd, D, q, 0, pf)
    case 2n: UW.swc_perfect(2, ${WS}, dd, D, q, 0, pf)
    case 3n: UW.swc_perfect(3, ${WS}, dd, D, q, 0, pf)
    case 4n+ +t: pf

# T.b256_putk at any byte position X = 4 q + r (its validity check, then its copy).
def b256_any(${P})
    -> ${RT('r')}:
  match r:
    case 0n:
      %wl_b256(dB, TB, pfB, hrB) : {T.b256_putk(${TH.format('D')}, X, ${OBJ}) == (${TH.format('VF.updv(_, dd, D, q)')}, (${OBJ}, 0)) : Array<U32> & (O.Words & U32)}
      VW.wput_b256(dd, D, X, q, FD.logic__subst(Nat, z => {U32.to_nat(X) == z : Nat}, Nat.add(A.quad(q), 0n), A.quad(q), FD.nat__add_zero(A.quad(q)), e), hd, pf,
        FD.logic__subst(Nat, z => {Nat.is_le(z, VB.pw(dd)) == True{} : Bool}, Nat.add(q, 64n), Nat.add(64n, q), FD.nat__add_comm(q, 64n), hl), dB, TB, pfB, hdB, hrB)
@@ b256_text_b256_any_bytes @@
    case 4n+ +t: Empty.absurd(${RT('4n+t')}, FD.nat__lt_zero_absurd(t, hr))

# Its bytes: the 256 bytes of TB's first 64 words at X, when the bytes there were zero.
def b256_any_bytes(${P})
    -> ${BY('r', 'Nat.add(A.quad(q), r)')}:
  match r:
    case 0n:
      +eL = ${EL}
      %Equal.sym(Nat, Nat.add(A.quad(q), 0n), A.quad(q), FD.nat__add_zero(A.quad(q))) : ${BY('0n', '_')}
      UW.updv_bytes(${WS}, dd, D, q, pf, FD.logic__subst(Nat, z => {Nat.is_le(Nat.add(q, z), VB.pw(dd)) == True{} : Bool}, 64n, VB.len(${WS}),
        Equal.sym(Nat, VB.len(${WS}), 64n, Equal.trans(Nat, VB.len(${WS}), List.length(&2, U32, ${WS}), 64n, Equal.sym(Nat, List.length(&2, U32, ${WS}), VB.len(${WS}), VR.len_eq(${WS})), eL)), hl))
@@ b256_text_2 @@
    case ${s}n:
      +eL = ${EL}
      UB${s}.swcb(${WS}, dd, D, q, pf,
      FD.logic__subst(Nat, z => {Nat.is_lt(Nat.add(q, z), VB.pw(dd)) == True{} : Bool}, 64n, List.length(&2, U32, ${WS}), Equal.sym(Nat, List.length(&2, U32, ${WS}), 64n, eL),
        FD.logic__subst(Nat, z => {Nat.is_lt(z, VB.pw(dd)) == True{} : Bool}, Nat.add(64n, q), Nat.add(q, 64n), FD.nat__add_comm(64n, q), ${lq})),
      FD.logic__subst(Nat, z => {VS.bt(A.quad(z), VS.bdr(Nat.add(A.quad(q), ${s}n), UA.BYT(D))) == UW.ZB(A.quad(z)) : +List<U32>}, 64n, List.length(&2, U32, ${WS}), Equal.sym(Nat, List.length(&2, U32, ${WS}), 64n, eL), hz))
@@ gpart_text @@

# T.${p}_put at a word-aligned position 4 P: its word OR-ed into a zero word, the run VF.updv.
def gput0_${p}(+dd: Nat, +D: FD.array__Tree<U32>, +pos: U32, +P: Nat, +e: {U32.to_nat(pos) == A.quad(P) : Nat},
    +hdd: {Nat.is_lt(dd, 29n) == True{} : Bool}, ${PF}, +hb: {Nat.is_le(Nat.add(1n, P), VB.pw(dd)) == True{} : Bool}, +w0: U32,
    +hz: {VS.bt(4n, VS.bdr(Nat.add(A.quad(P), 0n), UA.BYT(D))) == UW.ZB(4n) : +List<U32>})
    -> {T.${p}_put(${TH.format('D')}, pos, T.${C}{w0}) == ${RHS0} : Array<U32>}:
  +eq = VF.al_q(pos, P, e)
  +hP = UWD.le_q(P, 0n, VB.pw(dd), FD.logic__subst(Nat, z => {Nat.is_le(z, VB.pw(dd)) == True{} : Bool}, Nat.add(1n, P), Nat.add(P, 1n), FD.nat__add_comm(1n, P), hb))
  +eq0 = VB.add_at(U32.shrn(pos, 2n), 0, P, dd, eq, FD.nat__lt_trans(dd, 29n, 32n, hdd, {==}), hP)
  +hz0 = UW.zslot_g(dd, D, P, 0n, 4n, 0n, 0n, pf, hz, {==}, {==}, hP)
  %Equal.sym(U32, U32.and(pos, 3), 0, VF.al_3(pos, P, e)) :
    {T.${p}_pwd(U32.is_eq(_, 0), _, ${TH.format('D')}, U32.shrn(pos, 2n), w0) == ${RHS0} : Array<U32>}
  Equal.trans(Array<U32>, O.or_word(${TH.format('D')}, U32.add(U32.shrn(pos, 2n), 0), w0), ${TH.format('UW.ORW(dd, D, P, w0)')}, ${RHS0},
    UW.orw_rt(dd, D, U32.add(U32.shrn(pos, 2n), 0), P, w0, eq0, FD.nat__lt_trans(dd, 29n, 32n, hdd, {==}), hP, pf),
    Equal.cong(FD.array__Tree<U32>, Array<U32>, z => ${TH.format('z')}, UW.ORW(dd, D, P, w0), FD.array__upd(U32, dd, D, P, w0), UW.orw_zero(dd, D, P, w0, hz0)))

@@ gpart_text_gputu @@

# T.${p}_put at byte ${s} of word i (its last word's carry out is zero): the open model SWo.
def gputu${s}_${p}(+dd: Nat, +U: FD.array__Tree<U32>, +pos: U32, +i: Nat, ${WP},
    +e: {U32.to_nat(pos) == Nat.add(A.quad(i), ${s}n) : Nat}, +hd: {Nat.is_lt(dd, 31n) == True{} : Bool},
    +hl: {Nat.is_le(${N}n+i, VB.pw(dd)) == True{} : Bool}, +pf: {FD.array__perfect(U32, dd, U) == True{} : Bool}, ${VT},
    +hz: {VS.bt(${Wn}n, VS.bdr(Nat.add(A.quad(i), ${s}n), UA.BYT(U))) == UW.ZB(${Wn}n) : +List<U32>})
    -> {T.${p}_put(${TH.format('U')}, pos, T.${C}{${W}}) == ${RHS} : Array<U32>}:
  +e3 = UW.ua_3(pos, i, ${s}n, ${s}, {==}, e, {==})
  +eq = UW.ua_q(pos, i, ${s}n, e, {==})
  +hd32 = FD.nat__lt_trans(dd, 31n, 32n, hd, {==})
  +hi0 = FD.nat__lt_le_trans(i, ${N}n+i, VB.pw(dd), FD.nat__le_lt_succ(i, ${N - 1}n+i, Order.left_below_sum(${N - 1}n, i)), hl)
  +eq0 = VB.add_at(${q}, 0, i, dd, eq, hd32, hi0)
  +D1 = UW.ORW(dd, U, i, ${v0})
  +pf1 = UW.orw_perfect(dd, U, i, ${v0}, pf)
  +hc = UWB.tzc${s}1(${wl}, vt)
@@ gpart_text_2 @@
  %Equal.sym(U32, U32.and(pos, 3), ${s}, e3) : {T.${p}_pwd(U32.is_eq(_, 0), U32.and(pos, 3), ${TH.format('U')}, ${q}, ${W}) == ${RHS} : Array<U32>}
  %Equal.sym(U32, U32.and(pos, 3), ${s}, e3) : {T.${p}_pwd(U32.is_eq(${s}, 0), _, ${TH.format('U')}, ${q}, ${W}) == ${RHS} : Array<U32>}
  %Equal.sym(Array<U32>, O.or_word(${TH.format('U')}, U32.add(${q}, 0), ${v0}), ${TH.format('D1')}, UW.orw_rt(dd, U, U32.add(${q}, 0), i, ${v0}, eq0, hd32, hi0, pf)) :
    {O.or_skip(_, U32.add(${q}, 1), ${carry}) == ${RHS} : Array<U32>}
  %Equal.sym(Array<U32>, O.or_skip(${TH.format('D1')}, U32.add(${q}, 1), ${carry}), ${TH.format('D1')}, UW.orskip0(dd, D1, U32.add(${q}, 1), ${carry}, hc)) :
    {_ == ${RHS} : Array<U32>}
  Equal.cong(U32, Array<U32>, z => ${TH.format('UW.ORW(dd, U, i, z)')}, ${v0}, U32.or(O.shl_bytes(w0, ${s}), 0), Equal.sym(U32, U32.or(${v0}, 0), ${v0}, UWB.or0r(${v0})))

@@ gpart_text_3 @@
  +hL = FD.nat__succ_le_lt(${N - 1}n+i, VB.pw(dd), hl)
  +eqL = FD.logic__subst(Nat, z => {U32.to_nat(U32.add(${q}, ${N - 1})) == z : Nat}, Nat.add(${N - 1}n, i), ${IDXL}, {==}, VB.add_at(${q}, ${N - 1}, i, dd, eq, hd32, hL))
  +hLx = FD.logic__subst(Nat, z => {Nat.is_lt(z, VB.pw(dd)) == True{} : Bool}, ${N - 1}n+i, ${IDXL}, {==}, hL)
  +pfS = UW.swo_perfect(${s}, ${MID}, dd, D1, 1n+i, ${C_}, pf1)
  +eL = UW.orw_rt(dd, SW1, U32.add(${q}, ${N - 1}), ${IDXL}, ${VL}, eqL, hd32, hLx, pfS)
  %Equal.sym(U32, U32.and(pos, 3), ${s}, e3) : {T.${p}_pwd(U32.is_eq(_, 0), U32.and(pos, 3), ${TH.format('U')}, ${q}, ${W}) == ${RHS} : Array<U32>}
  %Equal.sym(U32, U32.and(pos, 3), ${s}, e3) : {T.${p}_pwd(U32.is_eq(${s}, 0), _, ${TH.format('U')}, ${q}, ${W}) == ${RHS} : Array<U32>}
  %Equal.sym(Array<U32>, O.or_word(${TH.format('U')}, U32.add(${q}, 0), ${v0}), ${TH.format('D1')}, UW.orw_rt(dd, U, U32.add(${q}, 0), i, ${v0}, eq0, hd32, hi0, pf)) :
    {O.or_skip(O.or_word(UW.RS2(${s}, ${MID}, ${JSM}, _, ${q}, w0), U32.add(${q}, ${N - 1}), ${VL}), U32.add(${q}, ${N}), ${carry}) == ${RHS} : Array<U32>}
  %Equal.sym(Array<U32>, UW.RS2(${s}, ${MID}, ${JSM}, ${TH.format('D1')}, ${q}, w0), ${TH.format('SW1')}, rs) :
    {O.or_skip(O.or_word(_, U32.add(${q}, ${N - 1}), ${VL}), U32.add(${q}, ${N}), ${carry}) == ${RHS} : Array<U32>}
  %Equal.sym(Array<U32>, O.or_word(${TH.format('SW1')}, U32.add(${q}, ${N - 1}), ${VL}), ${TH.format(T1)}, eL) :
    {O.or_skip(_, U32.add(${q}, ${N}), ${carry}) == ${RHS} : Array<U32>}
  %Equal.sym(Array<U32>, O.or_skip(${TH.format(T1)}, U32.add(${q}, ${N}), ${carry}), ${TH.format(T1)}, UW.orskip0(dd, ${T1}, U32.add(${q}, ${N}), ${carry}, hc)) :
    {_ == ${RHS} : Array<U32>}
  Equal.cong(FD.array__Tree<U32>, Array<U32>, z => ${TH.format('z')}, ${T1}, UW.SWo(${s}, ${REST}, dd, ${Dm}, 1n+i, ${C_}),
    Equal.trans(FD.array__Tree<U32>, ${T1}, ${T2}, UW.SWo(${s}, ${REST}, dd, ${Dm}, 1n+i, ${C_}),
      Equal.cong(U32, FD.array__Tree<U32>, z => UW.ORW(dd, UW.SWo(${s}, ${MID}, dd, UW.ORW(dd, U, i, z), 1n+i, ${C_}), ${IDXL}, ${VL}), ${v0}, U32.or(O.shl_bytes(w0, ${s}), 0),
        Equal.sym(U32, U32.or(${v0}, 0), ${v0}, UWB.or0r(${v0}))),
      Equal.trans(FD.array__Tree<U32>, ${T2}, UW.SWo(${s}, ${APPL}, dd, ${Dm}, 1n+i, ${C_}), UW.SWo(${s}, ${REST}, dd, ${Dm}, 1n+i, ${C_}),
        Equal.sym(FD.array__Tree<U32>, UW.SWo(${s}, ${APPL}, dd, ${Dm}, 1n+i, ${C_}), ${T2}, UW.swo_app(${s}, ${MID}, [${wl}], dd, ${Dm}, 1n+i, ${C_})),
        Equal.cong(List<&2, U32>, FD.array__Tree<U32>, z => UW.SWo(${s}, z, dd, ${Dm}, 1n+i, ${C_}), ${APPL}, ${REST}, {==}))))

@@ gpart_text_PX_ @@

# ---- ${p} at any byte position X = 4 q + r ----

def PX_${p}(+r: Nat, +dd: Nat, +D: FD.array__Tree<U32>, +q: Nat, ${WP}) -> FD.array__Tree<U32>:
  match r:
    case 0n: VF.updv(${L}, dd, D, q)
    case 1n: UW.SWo(1, ${L}, dd, D, q, 0)
    case 2n: UW.SWo(2, ${L}, dd, D, q, 0)
    case 3n: UW.SWo(3, ${L}, dd, D, q, 0)
    case 4n+t: D

def ${p}x_perfect(+r: Nat, +dd: Nat, +D: FD.array__Tree<U32>, +q: Nat, ${WP}, ${PF})
    -> {FD.array__perfect(U32, dd, ${PX('r')}) == True{} : Bool}:
  match r:
    case 0n: VF.updv_perfect(${L}, dd, D, q, pf)
    case 1n: UW.swo_perfect(1, ${L}, dd, D, q, 0, pf)
    case 2n: UW.swo_perfect(2, ${L}, dd, D, q, 0, pf)
    case 3n: UW.swo_perfect(3, ${L}, dd, D, q, 0, pf)
    case 4n+ +t: pf

# T.${p}_put at any byte position X = 4 q + r (${m} bytes; its last word's bytes 1..3 are zero).
def ${p}_any(+dd: Nat, +D: FD.array__Tree<U32>, +X: U32, +q: Nat, +r: Nat, ${WP}, ${E_},
    ${HD}, ${HL}, ${PF}, ${VT}, ${HZ})
    -> ${RT('r')}:
  match r:
    case 0n: gput0_${p}(dd, D, X, q, FD.logic__subst(Nat, z => {U32.to_nat(X) == z : Nat}, Nat.add(A.quad(q), 0n), A.quad(q), FD.nat__add_zero(A.quad(q)), e), hd, pf,
      ${hlq}, ${W}, hz)
@@ gwords_text @@
,
    +hd: {Nat.is_lt(dd, 29n) == True{} : Bool}, +hl: {Nat.is_le(Nat.add(q, UWD.NWN(Nat.add(r, ${S}n))), VB.pw(dd)) == True{} : Bool},
    +pf: {FD.array__perfect(U32, dd, D) == True{} : Bool}, +pfB: {FD.array__perfect(U32, dB, TB) == True{} : Bool},
    +hdB: {Nat.is_lt(dB, 31n) == True{} : Bool}, +hrB: {Nat.is_le(${W}n, VB.pw(dB)) == True{} : Bool},
    +hz: {VS.bt(${S}n, VS.bdr(Nat.add(A.quad(q), r), UA.BYT(D))) == UW.ZB(${S}n) : +List<U32>}
@@ gwords_text_gwput_ @@

# T.${p}_putk at a word-aligned position 4 P: its validity check, then its unrolled copy of the
# storage's first ${W} words, the run VF.updv.
def gwput_${p}(+dd: Nat, +D: FD.array__Tree<U32>, +pos: U32, +P: Nat, +e: {U32.to_nat(pos) == A.quad(P) : Nat},
    +hdd: {Nat.is_lt(dd, 29n) == True{} : Bool}, +pf: {FD.array__perfect(U32, dd, D) == True{} : Bool},
    +hb: {Nat.is_le(Nat.add(${W}n, P), VB.pw(dd)) == True{} : Bool}, +dB: Nat, +TB: FD.array__Tree<U32>,
    +pfB: {FD.array__perfect(U32, dB, TB) == True{} : Bool}, +hdB: {Nat.is_lt(dB, 31n) == True{} : Bool},
    +hrB: {Nat.is_le(${W}n, VB.pw(dB)) == True{} : Bool})
    -> {T.${p}_putk(FD.array__thaw(U32, D), pos, ${OBJ}) == ${RHS0} : ${TY}}:
  +hd32 = VB.lt32(dd, FD.nat__lt_trans(dd, 29n, 31n, hdd, {==}))
  +hB32 = VB.lt32(dB, hdB)
  %Equal.sym(O.Words & Bool, T.${p}_valid(${OBJ}), (${OBJ}, True{}),
      VBE.words_ok_b(dB, TB, ${S}, ${S}, ${S}, ${kw}n, pfB, hdB, {==}, {==}, {==}, {==}, hrB, {==}, ${unit}, {==})) :
    {T.${p}_pk(FD.array__thaw(U32, D), pos, _) == ${RHS0} : ${TY}}
  %Equal.sym(U32, U32.and(pos, 3), 0, VF.al_3(pos, P, e)) :
    {T.${p}_pk_ok(T.${p}_pw(U32.is_eq(_, 0), FD.array__thaw(U32, D), pos, FD.array__thaw(U32, TB), ${S})) == ${RHS0} : ${TY}}
@@ gwords_text_wl_ @@

def wl_${p}(+dB: Nat, +TB: FD.array__Tree<U32>, +pfB: {FD.array__perfect(U32, dB, TB) == True{} : Bool}, +hrB: {Nat.is_le(${W}n, VB.pw(dB)) == True{} : Bool})
    -> {WL_${p}(TB) == ${WS} : List<&2, U32>}:
  Equal.sym(List<&2, U32>, ${WS}, WL_${p}(TB),
    VWB.tks(${W}n, 0n, UW.SLW(TB), FD.logic__subst(Nat, z => {Nat.is_le(${W}n, z) == True{} : Bool}, VB.pw(dB), VB.len(UW.SLW(TB)), Equal.sym(Nat, VB.len(UW.SLW(TB)), VB.pw(dB), FD.array__slots_length(U32, dB, TB, pfB)), hrB)))


# Its storage check holds on a valid storage tree (the runtime's T.${p}_valid).
def ${p}_valid_ok(+dB: Nat, +TB: FD.array__Tree<U32>, +pfB: {FD.array__perfect(U32, dB, TB) == True{} : Bool},
    +hdB: {Nat.is_lt(dB, 31n) == True{} : Bool}, +hrB: {Nat.is_le(${W}n, VB.pw(dB)) == True{} : Bool})
    -> {T.${p}_valid(O.Words{FD.array__thaw(U32, TB), ${S}}) == (O.Words{FD.array__thaw(U32, TB), ${S}}, True{}) : O.Words & Bool}:
  VBE.words_ok_b(dB, TB, ${S}, ${S}, ${S}, ${kw}n, pfB, hdB, {==}, {==}, {==}, {==}, hrB, {==}, ${unit}, {==})

def PX_${p}(+r: Nat, +dd: Nat, +D: FD.array__Tree<U32>, +q: Nat, +TB: FD.array__Tree<U32>) -> FD.array__Tree<U32>:
  match r:
    case 0n: VF.updv(${WS}, dd, D, q)
    case 1n: UW.SWc(1, ${WS}, dd, D, q, 0)
    case 2n: UW.SWc(2, ${WS}, dd, D, q, 0)
    case 3n: UW.SWc(3, ${WS}, dd, D, q, 0)
    case 4n+t: D

def ${p}x_perfect(+r: Nat, +dd: Nat, +D: FD.array__Tree<U32>, +q: Nat, +TB: FD.array__Tree<U32>, +pf: {FD.array__perfect(U32, dd, D) == True{} : Bool})
    -> {FD.array__perfect(U32, dd, ${PX('r')}) == True{} : Bool}:
  match r:
    case 0n: VF.updv_perfect(${WS}, dd, D, q, pf)
    case 1n: UW.swc_perfect(1, ${WS}, dd, D, q, 0, pf)
    case 2n: UW.swc_perfect(2, ${WS}, dd, D, q, 0, pf)
    case 3n: UW.swc_perfect(3, ${WS}, dd, D, q, 0, pf)
    case 4n+ +t: pf

# T.${p}_putk at any byte position X = 4 q + r (its validity check, then its copy).
def ${p}_any(${P})
    -> ${RT('r')}:
  match r:
    case 0n:
      %wl_${p}(dB, TB, pfB, hrB) : {T.${p}_putk(${TH.format('D')}, X, ${OBJ}) == (${TH.format('VF.updv(_, dd, D, q)')}, (${OBJ}, 0)) : ${TY}}
      gwput_${p}(dd, D, X, q, FD.logic__subst(Nat, z => {U32.to_nat(X) == z : Nat}, Nat.add(A.quad(q), 0n), A.quad(q), FD.nat__add_zero(A.quad(q)), e), hd, pf,
        FD.logic__subst(Nat, z => {Nat.is_le(z, VB.pw(dd)) == True{} : Bool}, Nat.add(q, ${W}n), Nat.add(${W}n, q), FD.nat__add_comm(q, ${W}n), hl), dB, TB, pfB, hdB, hrB)
@@ gwords_text_2 @@
    case 4n+ +t: Empty.absurd(${RT('4n+t')}, FD.nat__lt_zero_absurd(t, hr))

# Its bytes: the ${S} bytes of TB's first ${W} words at X, when the bytes there were zero.
def ${p}_any_bytes(${P})
    -> ${BY('r', 'Nat.add(A.quad(q), r)')}:
  match r:
    case 0n:
      +eL = ${EL}
      %Equal.sym(Nat, Nat.add(A.quad(q), 0n), A.quad(q), FD.nat__add_zero(A.quad(q))) : ${BY('0n', '_')}
      UW.updv_bytes(${WS}, dd, D, q, pf, FD.logic__subst(Nat, z => {Nat.is_le(Nat.add(q, z), VB.pw(dd)) == True{} : Bool}, ${W}n, VB.len(${WS}),
        Equal.sym(Nat, VB.len(${WS}), ${W}n, Equal.trans(Nat, VB.len(${WS}), List.length(&2, U32, ${WS}), ${W}n, Equal.sym(Nat, List.length(&2, U32, ${WS}), VB.len(${WS}), VR.len_eq(${WS})), eL)), hl))
@@ gwords_text_3 @@
    case ${s}n:
      +eL = ${EL}
      UB${s}.swcb(${WS}, dd, D, q, pf,
        FD.logic__subst(Nat, z => {Nat.is_lt(Nat.add(q, z), VB.pw(dd)) == True{} : Bool}, ${W}n, List.length(&2, U32, ${WS}), Equal.sym(Nat, List.length(&2, U32, ${WS}), ${W}n, eL),
          FD.logic__subst(Nat, z => {Nat.is_lt(z, VB.pw(dd)) == True{} : Bool}, Nat.add(${W}n, q), Nat.add(q, ${W}n), FD.nat__add_comm(${W}n, q), ${lq})),
        FD.logic__subst(Nat, z => {VS.bt(A.quad(z), VS.bdr(Nat.add(A.quad(q), ${s}n), UA.BYT(D))) == UW.ZB(A.quad(z)) : +List<U32>}, ${W}n, List.length(&2, U32, ${WS}), Equal.sym(Nat, List.length(&2, U32, ${WS}), ${W}n, eL), hz))
@@ _sc_closed_facts @@

def DK2(-A: Data, -B: Data, +p: DK.P2(A, B)) -> A:
  (+a, +b) = p
  a

def DK3(-A: Data, -B: Data, +p: DK.P2(A, B)) -> B:
  (+a, +b) = p
  b

# The closed facts on 24576 = 4 * 6144 and the pubkeys' storage check, each decided once.
def sc_eK() -> {${NB} == A.quad(6144n) : Nat}: FD.nat__eq_from_is_eq(${NB}, A.quad(6144n), {==})
def sc_eT() -> {Nat.add(${NB}, 48n) == 24624n : Nat}: FD.nat__eq_from_is_eq(Nat.add(${NB}, 48n), 24624n, {==})
def sc_hy() -> {Nat.is_le(VC.YL(24576), VB.pw(15n)) == True{} : Bool}: {==}
def sc_hlo() -> {Nat.is_le(U32.to_nat(24576), U32.to_nat(24576)) == True{} : Bool}: FD.nat__eq_le(U32.to_nat(24576), U32.to_nat(24576), {==})
def sc_hu() -> {O.unit_ok(48, 24576) == True{} : Bool}: {==}
def sc_nw() -> {6144n == VC.NW(24576) : Nat}: FD.nat__eq_from_is_eq(6144n, VC.NW(24576), {==})
def sc_hsrc(+dB: Nat, +hrB: {Nat.is_le(6144n, VB.pw(dB)) == True{} : Bool}) -> {Nat.is_le(VC.NW(24576), VB.pw(dB)) == True{} : Bool}:
  FD.logic__subst(Nat, z => {Nat.is_le(z, VB.pw(dB)) == True{} : Bool}, 6144n, VC.NW(24576), sc_nw(), hrB)
def sc_hroom(+dB: Nat, +hrB: {Nat.is_le(6144n, VB.pw(dB)) == True{} : Bool}) -> {Nat.is_le(Nat.add(VC.NW(24576), 0n), VB.pw(dB)) == True{} : Bool}:
  FD.logic__subst(Nat, z => {Nat.is_le(z, VB.pw(dB)) == True{} : Bool}, VC.NW(24576), Nat.add(VC.NW(24576), 0n),
    Equal.sym(Nat, Nat.add(VC.NW(24576), 0n), VC.NW(24576), FD.nat__add_zero(VC.NW(24576))), sc_hsrc(dB, hrB))
def sc_hv(+dB: Nat, +TB: FD.array__Tree<U32>, +pfB: {FD.array__perfect(U32, dB, TB) == True{} : Bool},
    +hdB: {Nat.is_lt(dB, 31n) == True{} : Bool}, +hrB: {Nat.is_le(6144n, VB.pw(dB)) == True{} : Bool})
    -> {T.v512_b48_valid(${WO}) == (${WO}, True{}) : O.Words & Bool}:
  VBE.words_ok_b(dB, TB, 24576, 24576, 24576, 15n, pfB, hdB, {==}, sc_hy(), sc_hlo(), sc_hlo(), sc_hroom(dB, hrB), {==}, 48, sc_hu())


@@ _sc_valid_and_model @@
# Its storage check holds on a valid pubkeys tree (the runtime's T.SyncCommittee_valid).
def SyncCommittee_valid_ok(+dB: Nat, +TB: FD.array__Tree<U32>, ${AP}, +pfB: {FD.array__perfect(U32, dB, TB) == True{} : Bool},
    +hdB: {Nat.is_lt(dB, 31n) == True{} : Bool}, +hrB: {Nat.is_le(6144n, VB.pw(dB)) == True{} : Bool})
    -> {T.SyncCommittee_valid(${OBJ}) == (${OBJ}, True{}) : T.SyncCommittee & Bool}:
  %Equal.sym(O.Words & Bool, T.v512_b48_valid(${WO}), (${WO}, True{}), sc_hv(dB, TB, pfB, hdB, hrB)) :
    {T.SyncCommittee_va0(${AGG}, True{}, _) == (${OBJ}, True{}) : T.SyncCommittee & Bool}
  {==}

def PX_SyncCommittee(+r: Nat, +dd: Nat, +D: FD.array__Tree<U32>, +q: Nat, +TB: FD.array__Tree<U32>, ${AP}) -> FD.array__Tree<U32>:
  V_b48.PX_b48(r, dd, UWD.PWM(r, dd, D, q, TB, 24576), Nat.add(6144n, q), ${A_})

def SyncCommitteex_perfect(+r: Nat, +dd: Nat, +D: FD.array__Tree<U32>, +q: Nat, +TB: FD.array__Tree<U32>, ${AP}, +pf: {FD.array__perfect(U32, dd, D) == True{} : Bool})
    -> {FD.array__perfect(U32, dd, ${PX('r')}) == True{} : Bool}:
  V_b48.b48x_perfect(r, dd, UWD.PWM(r, dd, D, q, TB, 24576), Nat.add(6144n, q), ${A_}, UWD.pwm_perfect(r, dd, D, q, TB, 24576, pf))


@@ _sc_runtime_pieces @@
# The runtime, over any byte count n and models PW (after the pubkeys) and PXt (after the aggregate).
def sc_rt(+D: FD.array__Tree<U32>, +X: U32, +TB: FD.array__Tree<U32>, ${AP}, +n: U32, +PW: FD.array__Tree<U32>, +PXt: FD.array__Tree<U32>,
    +hv: {T.v512_b48_valid(${WOv}) == (${WOv}, True{}) : O.Words & Bool},
    +pw1: {O.put_words(${TD}, U32.add(X, 0), ${WOv}) == (${TH.format('PW')}, ${WOv}) : Array<U32> & O.Words},
    +g48: {T.b48_put(${TH.format('PW')}, U32.add(X, 24576), ${AGG}) == ${TH.format('PXt')} : Array<U32>})
    -> {T.SyncCommittee_putk(${TD}, X, ${OBJv}) == (${TH.format('PXt')}, (${OBJv}, 0)) : ${TY}}:
  %Equal.sym(O.Words & Bool, T.v512_b48_valid(${WOv}), (${WOv}, True{}), hv) :
    {T.SyncCommittee_pw0(X, 0, ${AGG}, T.v512_b48_pk(${TD}, U32.add(X, 0), _)) == (${TH.format('PXt')}, (${OBJv}, 0)) : ${TY}}
  %Equal.sym(Array<U32> & O.Words, O.put_words(${TD}, U32.add(X, 0), ${WOv}), (${TH.format('PW')}, ${WOv}), pw1) :
    {T.SyncCommittee_pw0(X, 0, ${AGG}, T.v512_b48_pk_ok(_)) == (${TH.format('PXt')}, (${OBJv}, 0)) : ${TY}}
  %Equal.sym(Array<U32>, T.b48_put(${TH.format('PW')}, U32.add(X, 24576), ${AGG}), ${TH.format('PXt')}, g48) :
    {(_, (${OBJv}, 0)) == (${TH.format('PXt')}, (${OBJv}, 0)) : ${TY}}
  {==}

# A splice of the 48 aggregate bytes over the 48 zeros after the pubkeys' bytes.
def sc_cat(+n: Nat, +L: ${LB}, +K: Nat, ${AP}, +eL: {${LEN('VS.bt(n, L)')} == n : Nat}, +eK: {n == K : Nat})
    -> {UW.SPL(List.append(&2, U32, VS.bt(n, L), UW.ZB(48n)), K, ${Y48}) == List.append(&2, U32, VS.bt(n, L), ${Y48}) : ${LB}}:
  +DT = VS.bt(n, L)
  +Zl = List.append(&2, U32, DT, UW.ZB(48n))
  +eL2 = Equal.trans(Nat, ${LEN('DT')}, n, K, eL, eK)
  +e0 = FD.logic__subst(Nat, z => {VS.bt(Nat.add(z, 0n), Zl) == List.append(&2, U32, DT, VS.bt(0n, UW.ZB(48n))) : ${LB}}, ${LEN('DT')}, K, eL2, UW.bt_app_len(DT, 0n, UW.ZB(48n)))
  +e1 = FD.logic__subst(Nat, z => {VS.bt(z, Zl) == List.append(&2, U32, DT, VS.bt(0n, UW.ZB(48n))) : ${LB}}, Nat.add(K, 0n), K, FD.nat__add_zero(K), e0)
  +e2 = FD.logic__subst(Nat, z => {VS.bdr(Nat.add(z, 48n), Zl) == VS.bdr(48n, UW.ZB(48n)) : ${LB}}, ${LEN('DT')}, K, eL2, UW.bdr_app_len(DT, 48n, UW.ZB(48n)))
  %Equal.sym(${LB}, VS.bt(K, Zl), List.append(&2, U32, DT, VS.bt(0n, UW.ZB(48n))), e1) :
    {List.append(&2, U32, _, List.append(&2, U32, ${Y48}, VS.bdr(Nat.add(K, 48n), Zl))) == List.append(&2, U32, DT, ${Y48}) : ${LB}}
  %Equal.sym(${LB}, VS.bdr(Nat.add(K, 48n), Zl), VS.bdr(48n, UW.ZB(48n)), e2) :
    {List.append(&2, U32, List.append(&2, U32, DT, Nil{}), List.append(&2, U32, ${Y48}, _)) == List.append(&2, U32, DT, ${Y48}) : ${LB}}
  %Equal.sym(${LB}, List.append(&2, U32, DT, Nil{}), DT, VS.app_nil(DT)) :
    {List.append(&2, U32, _, List.append(&2, U32, ${Y48}, Nil{})) == List.append(&2, U32, DT, ${Y48}) : ${LB}}
  {==}


@@ sc_text @@
,
    +hd: {Nat.is_lt(dd, 29n) == True{} : Bool}, +hl: {Nat.is_le(Nat.add(q, UWD.NWN(Nat.add(r, 24624n))), VB.pw(dd)) == True{} : Bool},
    +pf: {FD.array__perfect(U32, dd, D) == True{} : Bool}, +pfB: {FD.array__perfect(U32, dB, TB) == True{} : Bool},
    +hdB: {Nat.is_lt(dB, 31n) == True{} : Bool}, +hrB: {Nat.is_le(6144n, VB.pw(dB)) == True{} : Bool},
    +hz: {VS.bt(24624n, VS.bdr(Nat.add(A.quad(q), r), UA.BYT(D))) == UW.ZB(24624n) : +List<U32>}
@@ B4_ALIGNED @@

# T.b4_put at a word-aligned position 4 P: the store of its word.
def put_b4(+dd: Nat, +D: FD.array__Tree<U32>, +pos: U32, +P: Nat, +e: {U32.to_nat(pos) == A.quad(P) : Nat},
    +hdd: {Nat.is_lt(dd, 29n) == True{} : Bool}, +pf: {FD.array__perfect(U32, dd, D) == True{} : Bool},
    +hb: {Nat.is_le(Nat.add(1n, P), VB.pw(dd)) == True{} : Bool}, +x0: U32)
    -> {T.b4_put(FD.array__thaw(U32, D), pos, T.Bytes4{x0}) == FD.array__thaw(U32, VF.updv([x0], dd, D, P)) : Array<U32>}:
  %Equal.sym(U32, U32.and(pos, 3), 0, VF.al_3(pos, P, e)) :
    {T.b4_pwd(U32.is_eq(_, 0), _, FD.array__thaw(U32, D), U32.shrn(pos, 2n), x0) == FD.array__thaw(U32, VF.updv([x0], dd, D, P)) : Array<U32>}
  %Equal.sym(Array<U32>, Array.set(U32, FD.array__thaw(U32, D), U32.add(U32.shrn(pos, 2n), 0), x0), FD.array__thaw(U32, FD.array__upd(U32, dd, D, P, x0)), VB.set_at(dd, D, U32.shrn(pos, 2n), 0, P, x0, VF.al_q(pos, P, e), VB.lt32(dd, FD.nat__lt_trans(dd, 29n, 31n, hdd, {==})), VF.in_lt(0n, 1n, P, VB.pw(dd), {==}, hb), pf)) :
    {_ == FD.array__thaw(U32, VF.updv([x0], dd, D, P)) : Array<U32>}
  {==}

@@ pwords_text @@
,
    +hd: {Nat.is_lt(dd, 29n) == True{} : Bool}, +hl: {Nat.is_le(Nat.add(q, UWD.NWN(Nat.add(r, ${NS}))), VB.pw(dd)) == True{} : Bool},
    +pf: {FD.array__perfect(U32, dd, D) == True{} : Bool}, +pfB: {FD.array__perfect(U32, dB, TB) == True{} : Bool},
    +hdB: {Nat.is_lt(dB, 31n) == True{} : Bool}, +hrB: {Nat.is_le(${NWS}, VB.pw(dB)) == True{} : Bool},
    +hz: {VS.bt(${NS}, VS.bdr(${X0}, UA.BYT(D))) == UW.ZB(${NS}) : ${LB}}
@@ body @@

def DK2(-A: Data, -B: Data, +p: DK.P2(A, B)) -> A:
  (+a, +b) = p
  a

def DK3(-A: Data, -B: Data, +p: DK.P2(A, B)) -> B:
  (+a, +b) = p
  b

def PX_${p}(+r: Nat, +dd: Nat, +D: FD.array__Tree<U32>, +q: Nat, +TB: FD.array__Tree<U32>) -> FD.array__Tree<U32>: UWD.PWM(r, dd, D, q, TB, ${S})

def ${p}x_perfect(+r: Nat, +dd: Nat, +D: FD.array__Tree<U32>, +q: Nat, +TB: FD.array__Tree<U32>, +pf: {FD.array__perfect(U32, dd, D) == True{} : Bool})
    -> {FD.array__perfect(U32, dd, ${PX('r')}) == True{} : Bool}:
  UWD.pwm_perfect(r, dd, D, q, TB, ${S}, pf)

# NWN(s + 4 K) = K + NWN(s).
def nwk(+s: Nat, +n: U32, +K: Nat, +eK: {U32.to_nat(n) == A.quad(K) : Nat}) -> {UWD.NWN(Nat.add(s, U32.to_nat(n))) == Nat.add(K, UWD.NWN(s)) : Nat}:
  %Equal.sym(Nat, U32.to_nat(n), A.quad(K), eK) : {UWD.NWN(Nat.add(s, _)) == Nat.add(K, UWD.NWN(s)) : Nat}
  %FD.nat__add_comm(A.quad(K), s) : {UWD.NWN(_) == Nat.add(K, UWD.NWN(s)) : Nat}
  VRX.nwn_quad(K, s)

# The runtime, from the storage check and the put_words fact.
def rt(+D: FD.array__Tree<U32>, +X: U32, +TB: FD.array__Tree<U32>, +n: U32, +PW: FD.array__Tree<U32>,
    +hv: {T.${p}_valid(${WOn}) == (${WOn}, True{}) : O.Words & Bool},
    +w: {O.put_words(${TD}, X, ${WOn}) == (${TH.format('PW')}, ${WOn}) : Array<U32> & O.Words})
    -> {T.${p}_putk(${TD}, X, ${WOn}) == (${TH.format('PW')}, (${WOn}, 0)) : ${TY}}:
  %Equal.sym(O.Words & Bool, T.${p}_valid(${WOn}), (${WOn}, True{}), hv) : {T.${p}_pk(${TD}, X, _) == (${TH.format('PW')}, (${WOn}, 0)) : ${TY}}
  %Equal.sym(Array<U32> & O.Words, O.put_words(${TD}, X, ${WOn}), (${TH.format('PW')}, ${WOn}), w) : {T.${p}_pk_ok(_) == (${TH.format('PW')}, (${WOn}, 0)) : ${TY}}
  {==}

# The core over a symbolic byte count n = 4 K.
def core(+dd: Nat, +D: FD.array__Tree<U32>, +X: U32, +q: Nat, +r: Nat, +dB: Nat, +TB: FD.array__Tree<U32>, +n: U32, +K: Nat, ${E_},
    +hd: {Nat.is_lt(dd, 29n) == True{} : Bool}, +pf: {FD.array__perfect(U32, dd, D) == True{} : Bool}, +pfB: {FD.array__perfect(U32, dB, TB) == True{} : Bool},
    +hdB: {Nat.is_lt(dB, 31n) == True{} : Bool}, +hv: {T.${p}_valid(${WOn}) == (${WOn}, True{}) : O.Words & Bool},
    +hy: {Nat.is_le(VC.YL(n), VB.pw(${kw}n)) == True{} : Bool}, +hsrc: {Nat.is_le(VC.NW(n), VB.pw(dB)) == True{} : Bool},
    +eK: {U32.to_nat(n) == A.quad(K) : Nat}, +eW: {VC.NW(n) == K : Nat},
    +hl: {Nat.is_le(Nat.add(q, UWD.NWN(Nat.add(r, U32.to_nat(n)))), VB.pw(dd)) == True{} : Bool}, +hz: ${HZn('U32.to_nat(n)')})
    -> DK.P2(${RTn}, ${BYn}):
  match r:
    case 0n:
      +h0 = FD.logic__subst(Nat, z => {Nat.is_le(Nat.add(q, z), VB.pw(dd)) == True{} : Bool}, UWD.NWN(Nat.add(0n, U32.to_nat(n))), VC.NW(n),
        Equal.trans(Nat, UWD.NWN(Nat.add(0n, U32.to_nat(n))), Nat.add(K, 0n), VC.NW(n), nwk(0n, n, K, eK), Equal.trans(Nat, Nat.add(K, 0n), K, VC.NW(n), FD.nat__add_zero(K), Equal.sym(Nat, VC.NW(n), K, eW))), hl)
      +hdst = FD.logic__subst(Nat, z => {Nat.is_le(z, VB.pw(dd)) == True{} : Bool}, Nat.add(q, VC.NW(n)), Nat.add(VC.NW(n), q), FD.nat__add_comm(q, VC.NW(n)), h0)
      +hz0 = FD.logic__subst(Nat, z => ${HZ0.replace('A.quad(VC.NW(n))', 'z')}, U32.to_nat(n), A.quad(VC.NW(n)), Equal.trans(Nat, U32.to_nat(n), A.quad(K), A.quad(VC.NW(n)), eK, Equal.cong(Nat, Nat, z => A.quad(z), K, VC.NW(n), Equal.sym(Nat, VC.NW(n), K, eW))), hz)
      +w = UWD.pwn2(dd, dB, D, TB, X, q, n, ${kw}n, pf, pfB, FD.nat__lt_trans(dd, 29n, 31n, hd, {==}), hdB, UW.ua_3(X, q, 0n, 0, {==}, e, {==}), UW.ua_q(X, q, 0n, e, {==}), {==}, hy,
        FD.logic__subst(Nat, z => {Nat.is_le(z, VB.pw(dB)) == True{} : Bool}, VC.NW(n), Nat.add(VC.NW(n), 0n), Equal.sym(Nat, Nat.add(VC.NW(n), 0n), VC.NW(n), FD.nat__add_zero(VC.NW(n))), hsrc),
        hdst, hz0, U32.is_eq(n, 0), {==})
      %eW : DK.P2(${RTn.replace('(r,', '(0n,')}, ${BYn.replace('(r,', '(0n,').replace(X0, 'Nat.add(A.quad(q), 0n)').replace('VS.wtake(K,', 'VS.wtake(_,')})
      %Equal.sym(Nat, Nat.add(A.quad(q), 0n), A.quad(q), FD.nat__add_zero(A.quad(q))) : DK.P2(${RTn.replace('(r,', '(0n,')}, ${BYn.replace('(r,', '(0n,').replace(X0, '_').replace('VS.wtake(K,', 'VS.wtake(VC.NW(n),')})
      (rt(D, X, TB, n, UWD.PWM(0n, dd, D, q, TB, n), hv, w), UW.mone_bytes(VC.NW(n), 0n, q, dd, D, dB, TB, pf, pfB, hdst, hsrc))
@CASES
    case 4n+ +t: Empty.absurd(DK.P2(${RTn.replace('(r,', '(4n+t,')}, ${BYn.replace('(r,', '(4n+t,').replace(X0, 'Nat.add(A.quad(q), 4n+t)')}), FD.nat__lt_zero_absurd(t, hr))

# The size's facts over its power of two (S = 2^${E}, W = 2^${E - 2}): the words compare as U32 words
# (u32__pow2u), the counts as symbolic powers (never a closed Nat literal of the size).
def ${p}_ew() -> {FD.u32__pow2u(${E}n) == ${S} : U32}: {==}
def ${p}_eS() -> {${NS} == VB.pw(${E}n) : Nat}:
  FD.logic__subst(U32, z => {U32.to_nat(z) == VB.pw(${E}n) : Nat}, FD.u32__pow2u(${E}n), ${S}, ${p}_ew(), FD.u32__pow2u_value(${E}n, {==}))
def ${p}_eww() -> {FD.u32__pow2u(${E - 2}n) == VC.nwu(${S}) : U32}: {==}
def ${p}_eW() -> {U32.to_nat(VC.nwu(${S})) == VB.pw(${E - 2}n) : Nat}:
  FD.logic__subst(U32, z => {U32.to_nat(z) == VB.pw(${E - 2}n) : Nat}, FD.u32__pow2u(${E - 2}n), VC.nwu(${S}), ${p}_eww(), FD.u32__pow2u_value(${E - 2}n, {==}))
def ${p}_eQ() -> {VB.pw(${E}n) == A.quad(VB.pw(${E - 2}n)) : Nat}: {==}
def ${p}_eK() -> {${NS} == A.quad(${NWS}) : Nat}:
  Equal.trans(Nat, ${NS}, VB.pw(${E}n), A.quad(${NWS}), ${p}_eS(),
    Equal.trans(Nat, VB.pw(${E}n), A.quad(VB.pw(${E - 2}n)), A.quad(${NWS}), ${p}_eQ(),
      Equal.cong(Nat, Nat, z => A.quad(z), VB.pw(${E - 2}n), ${NWS}, Equal.sym(Nat, ${NWS}, VB.pw(${E - 2}n), ${p}_eW()))))
def ${p}_yl() -> {Nat.add(31n, ${NS}) == VC.YL(${S}) : Nat}: {==}
def ${p}_hy() -> {Nat.is_le(VC.YL(${S}), VB.pw(${kw}n)) == True{} : Bool}:
  %${p}_yl() : {Nat.is_le(_, VB.pw(${kw}n)) == True{} : Bool}
  FD.logic__subst(Nat, z => {Nat.is_le(Nat.add(31n, z), VB.pw(${kw}n)) == True{} : Bool}, VB.pw(${E}n), ${NS}, Equal.sym(Nat, ${NS}, VB.pw(${E}n), ${p}_eS()),
    VRX.yl_pow(${E}n, ${kw}n, {==}, {==}))

# Its storage check holds on a valid storage tree (the runtime's T.${p}_valid).
def ${p}_valid_ok(+dB: Nat, +TB: FD.array__Tree<U32>, +pfB: {FD.array__perfect(U32, dB, TB) == True{} : Bool},
    +hdB: {Nat.is_lt(dB, 31n) == True{} : Bool}, +hrB: {Nat.is_le(${NWS}, VB.pw(dB)) == True{} : Bool})
    -> {T.${p}_valid(O.Words{FD.array__thaw(U32, TB), ${S}}) == (O.Words{FD.array__thaw(U32, TB), ${S}}, True{}) : O.Words & Bool}:
  +hroom = FD.logic__subst(Nat, z => {Nat.is_le(z, VB.pw(dB)) == True{} : Bool}, ${NWS}, Nat.add(${NWS}, 0n), Equal.sym(Nat, Nat.add(${NWS}, 0n), ${NWS}, FD.nat__add_zero(${NWS})), hrB)
  VBE.words_ok_b(dB, TB, ${S}, ${S}, ${S}, ${kw}n, pfB, hdB, {==}, ${p}_hy(), FD.nat__eq_le(U32.to_nat(${S}), U32.to_nat(${S}), {==}),
    FD.nat__eq_le(U32.to_nat(${S}), U32.to_nat(${S}), {==}), hroom, {==}, ${unit}, {==})

# The instance at n = ${S} (K = VC.NW(${S})).
def at(${P})
    -> DK.P2(${RT}, ${BY}):
  core(dd, D, X, q, r, dB, TB, ${S}, ${NWS}, e, hr, hd, pf, pfB, hdB, ${p}_valid_ok(dB, TB, pfB, hdB, hrB), ${p}_hy(), hrB, ${p}_eK(), {==}, hl, hz)

# T.${p}_putk at any byte position X = 4 q + r.
def ${p}_any(${P})
    -> ${RT}:
  DK2(${RT}, ${BY}, at(${ARGS}))

# Its bytes: the ${S} bytes of TB's first ${W} words (VC.NW(${S})) at X, when the bytes there were zero.
def ${p}_any_bytes(${P})
    -> ${BY}:
  DK3(${RT}, ${BY}, at(${ARGS}))

@@ gwords_text_lines @@
  %Equal.sym(Array<U32>, Array.set(U32, ${pre}, U32.add(U32.shrn(pos, 2n), ${j}), VB.slot(TB, ${j}n)), ${post},
      VB.set_at(dd, VF.updv(WP${j}_${p}(TB), dd, D, P), U32.shrn(pos, 2n), ${j}, P, VB.slot(TB, ${j}n), VF.al_q(pos, P, e), hd32,
        VF.in_lt(${j}n, ${W}n, P, VB.pw(dd), {==}, hb), VF.updv_perfect(WP${j}_${p}(TB), dd, D, P, pf))) :
    {T.${p}_pk_ok(T.${p}_pal(${S}, ${nxt})) == ${RHS0} : ${TY}}