#!/usr/bin/env python3
"""proofs/obj/bits_view.bend: the bits of a bit list after one bit is set.

The runtime sets bit i of a bit list by merging a one-bit mask into word i >> 5 (O.bit_merge(v, w, M.shl_by(1, i & 31))) and writing the word back.
The spec's view of the list is its first k bits (BK.btk(k, BK.bitsof(slots))). This file shows, for every word, bit position and value:

    wset_i(x, i, v): the bits of the merged word are the bits of x with bit (i & 31) replaced by v        (one case per value of i & 31)
    bs_set(W, q, k, ...): the bits of the words with word q replaced by a word whose bits are those of W[q] with bit k replaced
                          are the bits of W with bit 32 q + k replaced
    bt_set(n, L, i, v): the first n bits of L with bit i replaced are the first n bits of L, bit i replaced, for i < n

    close_thaw / at_close / view_close: the push's close of the next word (O.bits_close, docs/CRASH_HUNT.md R5-01) as the tree close_t;
                          it keeps word n >> 5 and the first n + 1 bits

codegen/proofs/collections/collection_api_laws.py's `..._api_view_set` of the bit lists composes them (proofs/obj/coll_bits.bend). The word-level case split is the one of
bit_rw_go (coll_bits.bend): the five low bits of i are literal, the mask is then a literal word and its bits are the unit list of the position.

    python3 codegen/proofs/collections/bit_list_set_view.py            # write
    python3 codegen/proofs/collections/bit_list_set_view.py --check    # nonzero exit if the output is stale
"""
import sys as _sys
import pathlib as _pathlib
_sys.path.insert(0, str(_pathlib.Path(__file__).resolve().parents[3]))  # the repository root: `codegen` is importable when this file runs as a script
import sys

from codegen.core.repository_paths import ROOT  # noqa: E402
from codegen.core.law_module_helpers import run_single  # noqa: E402
OUT = ROOT / 'proofs/obj/bits_view.bend'

HEAD = '''import Base
import ../../src/obj.bend as O
import ../../src/merkle_fast.bend as M
import ../compact/found.bend as F
import ./u32bits.bend as UB
import ./bits_leaf.bend as BLf
import ./bitlist_pack.bend as BK
import ./bitlist_obj_light.bend as BO
import ./u32split.bend as USP
import ./words_spec.bend as WS
import ./words_rw.bend as WR
import ../nat_order.bend as Order
import ./vu32.bend as VU
import ./vvlu.bend as VVU
import ./dk.bend as DK
import ./mtree_run.bend as MR
import ./words_win.bend as WW
import ./vbitenc.bend as VBT
import ./vspec.bend as VS
import ./vdepth.bend as VD
import ../compact/reads.bend as RD

# GENERATED by bit_list_set_view (codegen). Do not edit.
# The bits of a bit list after one bit is set (the runtime's bit_merge of the word, the storage written back): lemmas on the bits of a word and of
# a list of words. See codegen/proofs/collections/bit_list_set_view.py.

# the list with item k replaced (no change past its end): the spec's bit setter
def lset(xs: +List<Bool>, +k: Nat, v: Bool) -> +List<Bool>:
  match xs:
    case Nil{}: []
    case Con{h, t}:
      match k:
        case 0n: Con{v, t}
        case 1n+p: Con{h, lset(t, p, v)}

# the pointwise or, and and-not, of two lists (the shorter ends them)
def zor(xs: +List<Bool>, ys: +List<Bool>) -> +List<Bool>:
  match xs ys:
    case Con{x, xt} Con{y, yt}: Con{Bool.or(x, y), zor(xt, yt)}
    case _ _: []

def zan(xs: +List<Bool>, ys: +List<Bool>) -> +List<Bool>:
  match xs ys:
    case Con{x, xt} Con{y, yt}: Con{Bool.and(x, Bool.not(y)), zan(xt, yt)}
    case _ _: []

# n bits, all zero but bit k
def falses(+n: Nat) -> +List<Bool>:
  match n:
    case 0n: []
    case 1n+p: Con{False{}, falses(p)}

def unit(+n: Nat, +k: Nat) -> +List<Bool>:
  match n k:
    case 0n _: []
    case 1n+p 0n: Con{True{}, falses(p)}
    case 1n+p 1n+j: Con{False{}, unit(p, j)}

def len_(+xs: +List<Bool>) -> Nat: List.length(&2, Bool, xs)

# a word's bits are as many as the word's width
def wlen(+n: Nat, +w: Word(n)) -> {len_(BLf.word_bits(n, w)) == n : Nat}:
  match n w:
    case 0n WNil{}: {==}
    case 1n+p WCon{+x, +s}:
      %Equal.sym(Nat, len_(BLf.word_bits(p, s)), p, wlen(p, s)) : {1n+_ == 1n+p : Nat}
      {==}

def wlen_u(+x: U32) -> {len_(BLf.wbits(x)) == 32n : Nat}:
  match x:
    case U32{+w}: wlen(32n, w)

# or / and-not of the bits of two words are the bits of the or / and-not
def wbo(+n: Nat, +a: Word(n), +m: Word(n)) -> {BLf.word_bits(n, Word.or(n, a, m)) == zor(BLf.word_bits(n, a), BLf.word_bits(n, m)) : +List<Bool>}:
  match n a m:
    case 0n WNil{} WNil{}: {==}
    case 1n+p WCon{+x, +s} WCon{+y, +t}:
      %Equal.sym(+List<Bool>, BLf.word_bits(p, Word.or(p, s, t)), zor(BLf.word_bits(p, s), BLf.word_bits(p, t)), wbo(p, s, t)) :
        {Con{Bool.or(x, y), _} == Con{Bool.or(x, y), zor(BLf.word_bits(p, s), BLf.word_bits(p, t))} : +List<Bool>}
      {==}

def wba(+n: Nat, +a: Word(n), +m: Word(n)) -> {BLf.word_bits(n, Word.and(n, a, Word.not(n, m))) == zan(BLf.word_bits(n, a), BLf.word_bits(n, m)) : +List<Bool>}:
  match n a m:
    case 0n WNil{} WNil{}: {==}
    case 1n+p WCon{+x, +s} WCon{+y, +t}:
      %Equal.sym(+List<Bool>, BLf.word_bits(p, Word.and(p, s, Word.not(p, t))), zan(BLf.word_bits(p, s), BLf.word_bits(p, t)), wba(p, s, t)) :
        {Con{Bool.and(x, Bool.not(y)), _} == Con{Bool.and(x, Bool.not(y)), zan(BLf.word_bits(p, s), BLf.word_bits(p, t))} : +List<Bool>}
      {==}

# or-ing with no bit, and and-not-ing no bit, change nothing
def zor_f(+t: +List<Bool>) -> {zor(t, falses(len_(t))) == t : +List<Bool>}:
  match t:
    case Nil{}: {==}
    case Con{+h, +r}:
      %Equal.sym(Bool, Bool.or(h, False{}), h, UB.bor_false(h)) : {Con{_, zor(r, falses(len_(r)))} == Con{h, r} : +List<Bool>}
      %Equal.sym(+List<Bool>, zor(r, falses(len_(r))), r, zor_f(r)) : {Con{h, _} == Con{h, r} : +List<Bool>}
      {==}

def zan_f(+t: +List<Bool>) -> {zan(t, falses(len_(t))) == t : +List<Bool>}:
  match t:
    case Nil{}: {==}
    case Con{+h, +r}:
      %Equal.sym(Bool, Bool.and(h, True{}), h, UB.band_true(h)) : {Con{_, zan(r, falses(len_(r)))} == Con{h, r} : +List<Bool>}
      %Equal.sym(+List<Bool>, zan(r, falses(len_(r))), r, zan_f(r)) : {Con{h, _} == Con{h, r} : +List<Bool>}
      {==}

# or-ing a unit list sets that bit, and-not-ing it clears it
def zor_unit(+L: +List<Bool>, +k: Nat) -> {zor(L, unit(len_(L), k)) == lset(L, k, True{}) : +List<Bool>}:
  match L k:
    case Nil{} _: {==}
    case Con{+h, +t} 0n:
      %Equal.sym(Bool, Bool.or(h, True{}), True{}, UB.bor_true(h)) : {Con{_, zor(t, falses(len_(t)))} == Con{True{}, t} : +List<Bool>}
      %Equal.sym(+List<Bool>, zor(t, falses(len_(t))), t, zor_f(t)) : {Con{True{}, _} == Con{True{}, t} : +List<Bool>}
      {==}
    case Con{+h, +t} 1n+j:
      %Equal.sym(Bool, Bool.or(h, False{}), h, UB.bor_false(h)) : {Con{_, zor(t, unit(len_(t), j))} == Con{h, lset(t, j, True{})} : +List<Bool>}
      %Equal.sym(+List<Bool>, zor(t, unit(len_(t), j)), lset(t, j, True{}), zor_unit(t, j)) : {Con{h, _} == Con{h, lset(t, j, True{})} : +List<Bool>}
      {==}

def zan_unit(+L: +List<Bool>, +k: Nat) -> {zan(L, unit(len_(L), k)) == lset(L, k, False{}) : +List<Bool>}:
  match L k:
    case Nil{} _: {==}
    case Con{+h, +t} 0n:
      %Equal.sym(Bool, Bool.and(h, False{}), False{}, UB.band_false(h)) : {Con{_, zan(t, falses(len_(t)))} == Con{False{}, t} : +List<Bool>}
      %Equal.sym(+List<Bool>, zan(t, falses(len_(t))), t, zan_f(t)) : {Con{False{}, _} == Con{False{}, t} : +List<Bool>}
      {==}
    case Con{+h, +t} 1n+j:
      %Equal.sym(Bool, Bool.and(h, True{}), h, UB.band_true(h)) : {Con{_, zan(t, unit(len_(t), j))} == Con{h, lset(t, j, False{})} : +List<Bool>}
      %Equal.sym(+List<Bool>, zan(t, unit(len_(t), j)), lset(t, j, False{}), zan_unit(t, j)) : {Con{h, _} == Con{h, lset(t, j, False{})} : +List<Bool>}
      {==}

# the merged word: the bits of x with bit k replaced, when the mask's bits are the unit list of k
def wmerge(+v: Bool, +x: U32, +m: U32, +k: Nat, +hm: {BLf.wbits(m) == unit(32n, k) : +List<Bool>})
    -> {BLf.wbits(O.bit_merge(v, x, m)) == lset(BLf.wbits(x), k, v) : +List<Bool>}:
  match v x m:
    case True{} U32{+a} U32{+b}:
      %Equal.sym(+List<Bool>, BLf.word_bits(32n, Word.or(32n, a, b)), zor(BLf.word_bits(32n, a), BLf.word_bits(32n, b)), wbo(32n, a, b)) : {_ == lset(BLf.word_bits(32n, a), k, True{}) : +List<Bool>}
      %Equal.sym(+List<Bool>, BLf.word_bits(32n, b), unit(32n, k), hm) : {zor(BLf.word_bits(32n, a), _) == lset(BLf.word_bits(32n, a), k, True{}) : +List<Bool>}
      %Equal.sym(Nat, 32n, len_(BLf.word_bits(32n, a)), Equal.sym(Nat, len_(BLf.word_bits(32n, a)), 32n, wlen(32n, a))) : {zor(BLf.word_bits(32n, a), unit(_, k)) == lset(BLf.word_bits(32n, a), k, True{}) : +List<Bool>}
      zor_unit(BLf.word_bits(32n, a), k)
    case False{} U32{+a} U32{+b}:
      %Equal.sym(+List<Bool>, BLf.word_bits(32n, Word.and(32n, a, Word.not(32n, b))), zan(BLf.word_bits(32n, a), BLf.word_bits(32n, b)), wba(32n, a, b)) : {_ == lset(BLf.word_bits(32n, a), k, False{}) : +List<Bool>}
      %Equal.sym(+List<Bool>, BLf.word_bits(32n, b), unit(32n, k), hm) : {zan(BLf.word_bits(32n, a), _) == lset(BLf.word_bits(32n, a), k, False{}) : +List<Bool>}
      %Equal.sym(Nat, 32n, len_(BLf.word_bits(32n, a)), Equal.sym(Nat, len_(BLf.word_bits(32n, a)), 32n, wlen(32n, a))) : {zan(BLf.word_bits(32n, a), unit(_, k)) == lset(BLf.word_bits(32n, a), k, False{}) : +List<Bool>}
      zan_unit(BLf.word_bits(32n, a), k)

# ---- the bits of a list of words ----
# setting an item inside the first list, and past it
def lset_app_l(+L1: +List<Bool>, +L2: +List<Bool>, +k: Nat, +v: Bool, +hk: {Nat.is_lt(k, len_(L1)) == True{} : Bool})
    -> {lset(List.append(&2, Bool, L1, L2), k, v) == List.append(&2, Bool, lset(L1, k, v), L2) : +List<Bool>}:
  match L1 k:
    case Nil{} _: Empty.absurd({lset(List.append(&2, Bool, Nil{}, L2), k, v) == List.append(&2, Bool, lset(Nil{}, k, v), L2) : +List<Bool>}, F.nat__lt_zero_absurd(k, hk))
    case Con{+h, +t} 0n: {==}
    case Con{+h, +t} 1n+j:
      %Equal.sym(+List<Bool>, lset(List.append(&2, Bool, t, L2), j, v), List.append(&2, Bool, lset(t, j, v), L2), lset_app_l(t, L2, j, v, hk)) :
        {Con{h, _} == Con{h, List.append(&2, Bool, lset(t, j, v), L2)} : +List<Bool>}
      {==}

def lset_app_r(+L1: +List<Bool>, +L2: +List<Bool>, +j: Nat, +v: Bool)
    -> {lset(List.append(&2, Bool, L1, L2), Nat.add(len_(L1), j), v) == List.append(&2, Bool, L1, lset(L2, j, v)) : +List<Bool>}:
  match L1:
    case Nil{}: {==}
    case Con{+h, +t}:
      %Equal.sym(+List<Bool>, lset(List.append(&2, Bool, t, L2), Nat.add(len_(t), j), v), List.append(&2, Bool, t, lset(L2, j, v)), lset_app_r(t, L2, j, v)) :
        {Con{h, _} == Con{h, List.append(&2, Bool, t, lset(L2, j, v))} : +List<Bool>}
      {==}

# the same after a whole word: its bits are 32
def lset_app_w(+x: U32, +L2: +List<Bool>, +j: Nat, +v: Bool)
    -> {lset(List.append(&2, Bool, BLf.wbits(x), L2), Nat.add(32n, j), v) == List.append(&2, Bool, BLf.wbits(x), lset(L2, j, v)) : +List<Bool>}:
  %Equal.sym(Nat, 32n, len_(BLf.wbits(x)), Equal.sym(Nat, len_(BLf.wbits(x)), 32n, wlen_u(x))) : {lset(List.append(&2, Bool, BLf.wbits(x), L2), Nat.add(_, j), v) == List.append(&2, Bool, BLf.wbits(x), lset(L2, j, v)) : +List<Bool>}
  lset_app_r(BLf.wbits(x), L2, j, v)

# the bits of the words with word q replaced, when the new word's bits are the old word's with bit k replaced, are the old bits with bit 32 q + k replaced
def bs_set(+W: List<&2, U32>, +q: Nat, +w2: U32, +k: Nat, +v: Bool, +hk: {Nat.is_lt(k, 32n) == True{} : Bool}, +hq: {Nat.is_lt(q, F.spec_common__length(U32, W)) == True{} : Bool},
    +hw: {BLf.wbits(w2) == lset(BLf.wbits(WR.at(W, q)), k, v) : +List<Bool>})
    -> {BK.bitsof(F.spec_common__update(U32, W, q, w2)) == lset(BK.bitsof(W), Nat.add(WS.e32(q), k), v) : +List<Bool>}:
  match W q:
    case Nil{} _: Empty.absurd({BK.bitsof(F.spec_common__update(U32, Nil{}, q, w2)) == lset(BK.bitsof(Nil{}), Nat.add(WS.e32(q), k), v) : +List<Bool>}, F.nat__lt_zero_absurd(q, hq))
    case Con{+x, +r} 0n:
      %Equal.sym(+List<Bool>, BLf.wbits(w2), lset(BLf.wbits(x), k, v), hw) : {List.append(&2, Bool, _, BK.bitsof(r)) == lset(BK.bitsof(Con{x, r}), Nat.add(WS.e32(0n), k), v) : +List<Bool>}
      %Equal.sym(+List<Bool>, lset(List.append(&2, Bool, BLf.wbits(x), BK.bitsof(r)), k, v), List.append(&2, Bool, lset(BLf.wbits(x), k, v), BK.bitsof(r)),
          lset_app_l(BLf.wbits(x), BK.bitsof(r), k, v, F.logic__subst(Nat, z => {Nat.is_lt(k, z) == True{} : Bool}, 32n, len_(BLf.wbits(x)), Equal.sym(Nat, len_(BLf.wbits(x)), 32n, wlen_u(x)), hk))) :
        {List.append(&2, Bool, lset(BLf.wbits(x), k, v), BK.bitsof(r)) == _ : +List<Bool>}
      {==}
    case Con{+x, +r} 1n+p:
      %Equal.sym(+List<Bool>, BK.bitsof(F.spec_common__update(U32, r, p, w2)), lset(BK.bitsof(r), Nat.add(WS.e32(p), k), v), bs_set(r, p, w2, k, v, hk, hq, hw)) :
        {List.append(&2, Bool, BLf.wbits(x), _) == lset(BK.bitsof(Con{x, r}), Nat.add(WS.e32(1n+p), k), v) : +List<Bool>}
      %Equal.sym(+List<Bool>, lset(List.append(&2, Bool, BLf.wbits(x), BK.bitsof(r)), Nat.add(32n, Nat.add(WS.e32(p), k)), v), List.append(&2, Bool, BLf.wbits(x), lset(BK.bitsof(r), Nat.add(WS.e32(p), k), v)),
          lset_app_w(x, BK.bitsof(r), Nat.add(WS.e32(p), k), v)) :
        {List.append(&2, Bool, BLf.wbits(x), lset(BK.bitsof(r), Nat.add(WS.e32(p), k), v)) == _ : +List<Bool>}
      {==}

# the first n bits, with bit i < n replaced
def bt_set(+n: Nat, +L: +List<Bool>, +i: Nat, +v: Bool, +hi: {Nat.is_lt(i, n) == True{} : Bool})
    -> {BK.btk(n, lset(L, i, v)) == lset(BK.btk(n, L), i, v) : +List<Bool>}:
  match n L i:
    case 0n _ _: Empty.absurd({BK.btk(0n, lset(L, i, v)) == lset(BK.btk(0n, L), i, v) : +List<Bool>}, F.nat__lt_zero_absurd(i, hi))
    case 1n+p Nil{} _: {==}
    case 1n+p Con{+h, +t} 0n: {==}
    case 1n+p Con{+h, +t} 1n+j:
      %Equal.sym(+List<Bool>, BK.btk(p, lset(t, j, v)), lset(BK.btk(p, t), j, v), bt_set(p, t, j, v, hi)) : {Con{h, _} == Con{h, lset(BK.btk(p, t), j, v)} : +List<Bool>}
      {==}

# the bit list's bits, of a storage tree
def bview_thaw(+t: F.array__Tree<U32>, +n: U32) -> {BO.bview(O.Bits{F.array__thaw(U32, t), n}) == BK.btk(U32.to_nat(n), BK.bitsof(F.array__slots(U32, t))) : +List<Bool>}:
  %Equal.sym(F.array__Tree<U32>, F.array__freeze(U32, F.array__thaw(U32, t)), t, F.array__freeze_thaw(U32, t)) :
    {BK.btk(U32.to_nat(n), BK.bitsof(F.array__slots(U32, _))) == BK.btk(U32.to_nat(n), BK.bitsof(F.array__slots(U32, t))) : +List<Bool>}
  {==}
'''


def wpat(bits, tail='WNil{}'):
    s_ = tail
    for b in reversed(bits):
        s_ = 'WCon{%s, %s}' % (b, s_)
    return s_


def dispatcher():
    L = ['', '# the runtime\'s merge of bit i & 31 (mask 1 << (i & 31)): the bits of the word with that bit replaced; a case per value of the five low bits of i',
         'def wset_i(+x: U32, +i: U32, +v: Bool) -> {BLf.wbits(O.bit_merge(v, x, M.shl_by(1, U32.and(i, 31)))) == lset(BLf.wbits(x), U32.to_nat(U32.and(i, 31)), v) : +List<Bool>}:',
         '  match i:']
    for K in range(32):
        lits = ['True{}' if (K >> b) & 1 else 'False{}' for b in range(5)]
        L.append('    case U32{%s}:' % wpat(lits, '+r'))
        kk = 'U32{%s}' % wpat(lits, '_')
        L.append('      %%Equal.sym(Word(27n), Word.and(27n, r, Word.zero(27n)), Word.zero(27n), UB.wand_zero(27n, r)) : {BLf.wbits(O.bit_merge(v, x, M.shl_by(1, %s))) == lset(BLf.wbits(x), U32.to_nat(%s), v) : +List<Bool>}'
                 % (kk, kk))
        L.append('      wmerge(v, x, M.shl_by(1, U32{%s}), %dn, {==})' % (wpat(lits, 'Word.zero(27n)'), K))
    L.append('')
    L.append('# the bit position is below 32')
    L.append('def lt32(+i: U32) -> {Nat.is_lt(U32.to_nat(U32.and(i, 31)), 32n) == True{} : Bool}:')
    L.append('  match i:')
    for K in range(32):
        lits = ['True{}' if (K >> b) & 1 else 'False{}' for b in range(5)]
        L.append('    case U32{%s}:' % wpat(lits, '+r'))
        kk = 'U32{%s}' % wpat(lits, '_')
        L.append('      %%Equal.sym(Word(27n), Word.and(27n, r, Word.zero(27n)), Word.zero(27n), UB.wand_zero(27n, r)) : {Nat.is_lt(U32.to_nat(%s), 32n) == True{} : Bool}' % kk)
        L.append('      {==}')
    return '\n'.join(L) + '\n'


VIEW_SET = r"""
# the bits of the bit list after bit i is set: the bits before with bit i replaced (the runtime's merge, written back to word i >> 5)
def view_set(+d: Nat, +t: F.array__Tree<U32>, +n: U32, +i: U32, +q: Nat, +v: Bool, +pf: {F.array__perfect(U32, d, t) == True{} : Bool},
    +hg: {U32.is_lt(i, n) == True{} : Bool}, +hq: {U32.to_nat(U32.shrn(i, 5n)) == q : Nat}, +hk: {Nat.is_lt(q, F.spec_common__pow2(d)) == True{} : Bool})
    -> {BO.bview(O.Bits{F.array__thaw(U32, F.array__upd(U32, d, t, q, O.bit_merge(v, WR.at(F.array__slots(U32, t), q), M.shl_by(1, U32.and(i, 31))))), n}) == lset(BO.bview(O.Bits{F.array__thaw(U32, t), n}), U32.to_nat(i), v) : +List<Bool>}:
  +W = F.array__slots(U32, t)
  +hq1 = F.logic__subst(Nat, z => {Nat.is_lt(q, z) == True{} : Bool}, F.spec_common__pow2(d), F.spec_common__length(U32, W), Equal.sym(Nat, F.spec_common__length(U32, W), F.spec_common__pow2(d), F.array__slots_length(U32, d, t, pf)), hk)
  +k = U32.to_nat(U32.and(i, 31))
  +ha = Equal.trans(Nat, Nat.add(WS.e32(q), k), Nat.add(k, WS.e32(q)), U32.to_nat(i), F.nat__add_comm(WS.e32(q), k),
    Equal.trans(Nat, Nat.add(k, WS.e32(q)), Nat.add(k, Nat.double(Nat.double(Nat.double(Nat.double(Nat.double(U32.to_nat(U32.shrn(i, 5n)))))))), U32.to_nat(i),
      Equal.cong(Nat, Nat, z => Nat.add(k, Nat.double(Nat.double(Nat.double(Nat.double(Nat.double(z)))))), q, U32.to_nat(U32.shrn(i, 5n)), Equal.sym(Nat, U32.to_nat(U32.shrn(i, 5n)), q, hq)),
      Equal.sym(Nat, U32.to_nat(i), Nat.add(k, Nat.double(Nat.double(Nat.double(Nat.double(Nat.double(U32.to_nat(U32.shrn(i, 5n)))))))), USP.split5(i))))
  +hl = F.logic__subst(Bool, z => {z == True{} : Bool}, U32.is_lt(i, n), Nat.is_lt(U32.to_nat(i), U32.to_nat(n)), F.u32__is_lt_nat(i, n), hg)
  +hlt = F.logic__subst(Nat, z => {Nat.is_lt(z, U32.to_nat(n)) == True{} : Bool}, U32.to_nat(i), Nat.add(WS.e32(q), k), Equal.sym(Nat, Nat.add(WS.e32(q), k), U32.to_nat(i), ha), hl)
  Equal.trans(+List<Bool>, BO.bview(O.Bits{F.array__thaw(U32, F.array__upd(U32, d, t, q, O.bit_merge(v, WR.at(W, q), M.shl_by(1, U32.and(i, 31))))), n}),
    BK.btk(U32.to_nat(n), lset(BK.bitsof(W), Nat.add(WS.e32(q), k), v)), lset(BO.bview(O.Bits{F.array__thaw(U32, t), n}), U32.to_nat(i), v),
    Equal.trans(+List<Bool>, BO.bview(O.Bits{F.array__thaw(U32, F.array__upd(U32, d, t, q, O.bit_merge(v, WR.at(W, q), M.shl_by(1, U32.and(i, 31))))), n}),
      BK.btk(U32.to_nat(n), BK.bitsof(F.spec_common__update(U32, W, q, O.bit_merge(v, WR.at(W, q), M.shl_by(1, U32.and(i, 31)))))), BK.btk(U32.to_nat(n), lset(BK.bitsof(W), Nat.add(WS.e32(q), k), v)),
      Equal.trans(+List<Bool>, BO.bview(O.Bits{F.array__thaw(U32, F.array__upd(U32, d, t, q, O.bit_merge(v, WR.at(W, q), M.shl_by(1, U32.and(i, 31))))), n}),
        BK.btk(U32.to_nat(n), BK.bitsof(F.array__slots(U32, F.array__upd(U32, d, t, q, O.bit_merge(v, WR.at(W, q), M.shl_by(1, U32.and(i, 31))))))),
        BK.btk(U32.to_nat(n), BK.bitsof(F.spec_common__update(U32, W, q, O.bit_merge(v, WR.at(W, q), M.shl_by(1, U32.and(i, 31)))))),
        bview_thaw(F.array__upd(U32, d, t, q, O.bit_merge(v, WR.at(W, q), M.shl_by(1, U32.and(i, 31)))), n),
        Equal.cong(List<&2, U32>, +List<Bool>, z => BK.btk(U32.to_nat(n), BK.bitsof(z)), F.array__slots(U32, F.array__upd(U32, d, t, q, O.bit_merge(v, WR.at(W, q), M.shl_by(1, U32.and(i, 31))))),
          F.spec_common__update(U32, W, q, O.bit_merge(v, WR.at(W, q), M.shl_by(1, U32.and(i, 31)))), F.array__upd_slots(U32, d, t, q, O.bit_merge(v, WR.at(W, q), M.shl_by(1, U32.and(i, 31))), hk, pf))),
      Equal.cong(+List<Bool>, +List<Bool>, z => BK.btk(U32.to_nat(n), z), BK.bitsof(F.spec_common__update(U32, W, q, O.bit_merge(v, WR.at(W, q), M.shl_by(1, U32.and(i, 31))))), lset(BK.bitsof(W), Nat.add(WS.e32(q), k), v),
        bs_set(W, q, O.bit_merge(v, WR.at(W, q), M.shl_by(1, U32.and(i, 31))), k, v, lt32(i), hq1, wset_i(WR.at(W, q), i, v)))),
    Equal.trans(+List<Bool>, BK.btk(U32.to_nat(n), lset(BK.bitsof(W), Nat.add(WS.e32(q), k), v)), lset(BK.btk(U32.to_nat(n), BK.bitsof(W)), Nat.add(WS.e32(q), k), v), lset(BO.bview(O.Bits{F.array__thaw(U32, t), n}), U32.to_nat(i), v),
      bt_set(U32.to_nat(n), BK.bitsof(W), Nat.add(WS.e32(q), k), v, hlt),
      Equal.trans(+List<Bool>, lset(BK.btk(U32.to_nat(n), BK.bitsof(W)), Nat.add(WS.e32(q), k), v), lset(BK.btk(U32.to_nat(n), BK.bitsof(W)), U32.to_nat(i), v), lset(BO.bview(O.Bits{F.array__thaw(U32, t), n}), U32.to_nat(i), v),
        Equal.cong(Nat, +List<Bool>, z => lset(BK.btk(U32.to_nat(n), BK.bitsof(W)), z, v), Nat.add(WS.e32(q), k), U32.to_nat(i), ha),
        Equal.sym(+List<Bool>, lset(BO.bview(O.Bits{F.array__thaw(U32, t), n}), U32.to_nat(i), v), lset(BK.btk(U32.to_nat(n), BK.bitsof(W)), U32.to_nat(i), v),
          Equal.cong(+List<Bool>, +List<Bool>, z => lset(z, U32.to_nat(i), v), BO.bview(O.Bits{F.array__thaw(U32, t), n}), BK.btk(U32.to_nat(n), BK.bitsof(W)), bview_thaw(t, n))))))
"""

VIEW_APPEND = r'''
# ---- appending a bit: the new bit is bit n of the bits before, with the list one bit longer ----
def lenapp(+A: +List<Bool>, +B: +List<Bool>) -> {len_(List.append(&2, Bool, A, B)) == Nat.add(len_(A), len_(B)) : Nat}:
  match A:
    case Nil{}: {==}
    case Con{+x, +r}: Equal.cong(Nat, Nat, z => 1n+z, len_(List.append(&2, Bool, r, B)), Nat.add(len_(r), len_(B)), lenapp(r, B))

# the bits of a list of words: 32 per word
def lenb(+W: List<&2, U32>) -> {len_(BK.bitsof(W)) == WS.e32(F.spec_common__length(U32, W)) : Nat}:
  match W:
    case Nil{}: {==}
    case Con{+x, +r}:
      Equal.trans(Nat, len_(List.append(&2, Bool, BLf.wbits(x), BK.bitsof(r))), Nat.add(32n, len_(BK.bitsof(r))), WS.e32(1n+F.spec_common__length(U32, r)),
        Equal.trans(Nat, len_(List.append(&2, Bool, BLf.wbits(x), BK.bitsof(r))), Nat.add(len_(BLf.wbits(x)), len_(BK.bitsof(r))), Nat.add(32n, len_(BK.bitsof(r))), lenapp(BLf.wbits(x), BK.bitsof(r)),
          Equal.cong(Nat, Nat, z => Nat.add(z, len_(BK.bitsof(r))), len_(BLf.wbits(x)), 32n, wlen_u(x))),
        Equal.cong(Nat, Nat, z => Nat.add(32n, z), len_(BK.bitsof(r)), WS.e32(F.spec_common__length(U32, r)), lenb(r)))

def e32_le(+a: Nat, +b: Nat, +h: {Nat.is_le(a, b) == True{} : Bool}) -> {Nat.is_le(WS.e32(a), WS.e32(b)) == True{} : Bool}:
  match a b:
    case 0n _: F.nat__zero_le(WS.e32(b))
    case 1n+ +p 0n: Empty.absurd({Nat.is_le(WS.e32(1n+p), WS.e32(0n)) == True{} : Bool}, F.logic__false_true(h))
    case 1n+ +p 1n+ +s: Order.add_left(32n, WS.e32(p), WS.e32(s), e32_le(p, s, h))

# position n of a list of at least n + 1 bits: replacing it in the first n + 1 bits appends the new bit to the first n
def btk_snoc(+K: Nat, +B: +List<Bool>, +v: Bool, +h: {Nat.is_lt(K, len_(B)) == True{} : Bool})
    -> {lset(BK.btk(1n+K, B), K, v) == List.append(&2, Bool, BK.btk(K, B), [v]) : +List<Bool>}:
  match K B:
    case _ Nil{}: Empty.absurd({lset(BK.btk(1n+K, Nil{}), K, v) == List.append(&2, Bool, BK.btk(K, Nil{}), [v]) : +List<Bool>}, F.nat__lt_zero_absurd(K, h))
    case 0n Con{+b, +r}: {==}
    case 1n+ +p Con{+b, +r}:
      %Equal.sym(+List<Bool>, lset(BK.btk(1n+p, r), p, v), List.append(&2, Bool, BK.btk(p, r), [v]), btk_snoc(p, r, v, h)) :
        {Con{b, _} == Con{b, List.append(&2, Bool, BK.btk(p, r), [v])} : +List<Bool>}
      {==}

# the new position is inside the storage: n < 32 * (the words)
def kbound(+d: Nat, +t: F.array__Tree<U32>, +n: U32, +q: Nat, +pf: {F.array__perfect(U32, d, t) == True{} : Bool},
    +hq: {U32.to_nat(U32.shrn(n, 5n)) == q : Nat}, +hk: {Nat.is_lt(q, F.spec_common__pow2(d)) == True{} : Bool})
    -> {Nat.is_lt(U32.to_nat(n), len_(BK.bitsof(F.array__slots(U32, t)))) == True{} : Bool}:
  +W = F.array__slots(U32, t)
  +hq1 = F.logic__subst(Nat, z => {Nat.is_lt(q, z) == True{} : Bool}, F.spec_common__pow2(d), F.spec_common__length(U32, W), Equal.sym(Nat, F.spec_common__length(U32, W), F.spec_common__pow2(d), F.array__slots_length(U32, d, t, pf)), hk)
  +k = U32.to_nat(U32.and(n, 31))
  +ha = Equal.trans(Nat, Nat.add(k, WS.e32(q)), Nat.add(k, Nat.double(Nat.double(Nat.double(Nat.double(Nat.double(U32.to_nat(U32.shrn(n, 5n)))))))), U32.to_nat(n),
    Equal.cong(Nat, Nat, z => Nat.add(k, Nat.double(Nat.double(Nat.double(Nat.double(Nat.double(z)))))), q, U32.to_nat(U32.shrn(n, 5n)), Equal.sym(Nat, U32.to_nat(U32.shrn(n, 5n)), q, hq)),
    Equal.sym(Nat, U32.to_nat(n), Nat.add(k, Nat.double(Nat.double(Nat.double(Nat.double(Nat.double(U32.to_nat(U32.shrn(n, 5n)))))))), USP.split5(n)))
  +h1 = F.nat__lt_succ_le_succ(q, F.spec_common__length(U32, W), hq1)
  +h2 = e32_le(1n+q, F.spec_common__length(U32, W), h1)
  +h3 = Order.add_right(1n+k, 32n, WS.e32(q), F.nat__lt_succ_le_succ(k, 32n, lt32(n)))
  F.logic__subst(Nat, z => {Nat.is_lt(U32.to_nat(n), z) == True{} : Bool}, WS.e32(F.spec_common__length(U32, W)), len_(BK.bitsof(W)), Equal.sym(Nat, len_(BK.bitsof(W)), WS.e32(F.spec_common__length(U32, W)), lenb(W)),
    F.nat__lt_le_trans(U32.to_nat(n), WS.e32(1n+q), WS.e32(F.spec_common__length(U32, W)), F.logic__subst(Nat, z => {Nat.is_lt(z, WS.e32(1n+q)) == True{} : Bool}, Nat.add(k, WS.e32(q)), U32.to_nat(n), ha, F.nat__succ_le_lt(Nat.add(k, WS.e32(q)), WS.e32(1n+q), h3)), h2))

# a count below the limit c plus one is within it: the guard `n < c` of the appends (docs/CRASH_HUNT.md CH-04) as `n + 1 <= c`
def lt_le1(+n: U32, +c: U32, +ha: {U32.is_lt(n, c) == True{} : Bool}) -> {U32.is_le(U32.add(n, 1), c) == True{} : Bool}:
  +hl = F.logic__subst(Bool, z => {z == True{} : Bool}, U32.is_lt(n, c), Nat.is_lt(U32.to_nat(n), U32.to_nat(c)), F.u32__is_lt_nat(n, c), ha)
  +hs = F.nat__lt_succ_le_succ(U32.to_nat(n), U32.to_nat(c), hl)
  +e = VVU.addk(n, 1, c, hs)
  +hc = F.logic__subst(Nat, z => {Nat.is_le(z, U32.to_nat(c)) == True{} : Bool}, 1n+U32.to_nat(n), U32.to_nat(U32.add(n, 1)), Equal.sym(Nat, U32.to_nat(U32.add(n, 1)), 1n+U32.to_nat(n), e), hs)
  F.logic__subst(Bool, z => {z == True{} : Bool}, Nat.is_le(U32.to_nat(U32.add(n, 1)), U32.to_nat(c)), U32.is_le(U32.add(n, 1), c), Equal.sym(Bool, U32.is_le(U32.add(n, 1), c), Nat.is_le(U32.to_nat(U32.add(n, 1)), U32.to_nat(c)), VU.le_u32(U32.add(n, 1), c)), hc)

# the new length is the old one and one more (no wrap: n < n + 1, and the sum is within the bound c)
def n1(+n: U32, +c: U32, +hg: {U32.is_lt(n, U32.add(n, 1)) == True{} : Bool}, +ha: {U32.is_le(U32.add(n, 1), c) == True{} : Bool})
    -> {U32.to_nat(U32.add(n, 1)) == 1n+U32.to_nat(n) : Nat}:
  +hl = F.logic__subst(Bool, z => {z == True{} : Bool}, U32.is_lt(n, U32.add(n, 1)), Nat.is_lt(U32.to_nat(n), U32.to_nat(U32.add(n, 1))), F.u32__is_lt_nat(n, U32.add(n, 1)), hg)
  +hc = F.logic__subst(Bool, z => {z == True{} : Bool}, U32.is_le(U32.add(n, 1), c), Nat.is_le(U32.to_nat(U32.add(n, 1)), U32.to_nat(c)), VU.le_u32(U32.add(n, 1), c), ha)
  VVU.addk(n, 1, c, F.nat__le_trans(Nat.add(U32.to_nat(1), U32.to_nat(n)), U32.to_nat(U32.add(n, 1)), U32.to_nat(c), F.nat__lt_succ_le_succ(U32.to_nat(n), U32.to_nat(U32.add(n, 1)), hl), hc))

# the bits of the bit list after the bit n is appended (the room is there: the word n >> 5 of the storage): the bits before, and the new bit
def view_snoc(+d: Nat, +t: F.array__Tree<U32>, +n: U32, +N1: U32, +q: Nat, +v: Bool, +pf: {F.array__perfect(U32, d, t) == True{} : Bool},
    +hN: {U32.to_nat(N1) == 1n+U32.to_nat(n) : Nat}, +hg: {U32.is_lt(n, N1) == True{} : Bool}, +hq: {U32.to_nat(U32.shrn(n, 5n)) == q : Nat}, +hk: {Nat.is_lt(q, F.spec_common__pow2(d)) == True{} : Bool})
    -> {BO.bview(O.Bits{F.array__thaw(U32, F.array__upd(U32, d, t, q, O.bit_merge(v, WR.at(F.array__slots(U32, t), q), M.shl_by(1, U32.and(n, 31))))), N1}) == List.append(&2, Bool, BO.bview(O.Bits{F.array__thaw(U32, t), n}), [v]) : +List<Bool>}:
  Equal.trans(+List<Bool>, BO.bview(O.Bits{F.array__thaw(U32, F.array__upd(U32, d, t, q, O.bit_merge(v, WR.at(F.array__slots(U32, t), q), M.shl_by(1, U32.and(n, 31))))), N1}),
    lset(BO.bview(O.Bits{F.array__thaw(U32, t), N1}), U32.to_nat(n), v), List.append(&2, Bool, BO.bview(O.Bits{F.array__thaw(U32, t), n}), [v]),
    view_set(d, t, N1, n, q, v, pf, hg, hq, hk),
    Equal.trans(+List<Bool>, lset(BO.bview(O.Bits{F.array__thaw(U32, t), N1}), U32.to_nat(n), v), lset(BK.btk(1n+U32.to_nat(n), BK.bitsof(F.array__slots(U32, t))), U32.to_nat(n), v), List.append(&2, Bool, BO.bview(O.Bits{F.array__thaw(U32, t), n}), [v]),
      Equal.trans(+List<Bool>, lset(BO.bview(O.Bits{F.array__thaw(U32, t), N1}), U32.to_nat(n), v), lset(BK.btk(U32.to_nat(N1), BK.bitsof(F.array__slots(U32, t))), U32.to_nat(n), v), lset(BK.btk(1n+U32.to_nat(n), BK.bitsof(F.array__slots(U32, t))), U32.to_nat(n), v),
        Equal.cong(+List<Bool>, +List<Bool>, z => lset(z, U32.to_nat(n), v), BO.bview(O.Bits{F.array__thaw(U32, t), N1}), BK.btk(U32.to_nat(N1), BK.bitsof(F.array__slots(U32, t))), bview_thaw(t, N1)),
        Equal.cong(Nat, +List<Bool>, z => lset(BK.btk(z, BK.bitsof(F.array__slots(U32, t))), U32.to_nat(n), v), U32.to_nat(N1), 1n+U32.to_nat(n), hN)),
      Equal.trans(+List<Bool>, lset(BK.btk(1n+U32.to_nat(n), BK.bitsof(F.array__slots(U32, t))), U32.to_nat(n), v), List.append(&2, Bool, BK.btk(U32.to_nat(n), BK.bitsof(F.array__slots(U32, t))), [v]), List.append(&2, Bool, BO.bview(O.Bits{F.array__thaw(U32, t), n}), [v]),
        btk_snoc(U32.to_nat(n), BK.bitsof(F.array__slots(U32, t)), v, kbound(d, t, n, q, pf, hq, hk)),
        Equal.cong(+List<Bool>, +List<Bool>, z => List.append(&2, Bool, z, [v]), BK.btk(U32.to_nat(n), BK.bitsof(F.array__slots(U32, t))), BO.bview(O.Bits{F.array__thaw(U32, t), n}),
          Equal.sym(+List<Bool>, BO.bview(O.Bits{F.array__thaw(U32, t), n}), BK.btk(U32.to_nat(n), BK.bitsof(F.array__slots(U32, t))), bview_thaw(t, n))))))
'''


VIEW_GROW = r'''
# ---- appending a bit when the storage is reallocated: the grown tree keeps the old words, so the bits before are the old bits ----
# the bits k .. of A and B: the first m words from the index j agree (A and B are the same lists, the index moves)
def Hi(+m: Nat, +j: Nat, A: List<&2, U32>, B: List<&2, U32>) -> Data:
  match m:
    case 0n: {True{} == True{} : Bool}
    case 1n+p: DK.P2({MR.wd(A, j) == MR.wd(B, j) : U32}, Hi(p, 1n+j, A, B))

def hi_shift(+p: Nat, +j: Nat, +x: U32, r: List<&2, U32>, +y: U32, s: List<&2, U32>, +h: Hi(p, 1n+j, Con{x, r}, Con{y, s})) -> Hi(p, j, r, s):
  match p:
    case 0n: {==}
    case 1n+ +q:
      (+e, +h2) = h
      (e, hi_shift(q, 1n+j, x, r, y, s, h2))

# the first k bits of a list followed by another: those of the first when k is within it, and all of it then the first j of the other
def btk_short(+L: +List<Bool>, +R: +List<Bool>, +k: Nat, +h: {Nat.is_le(k, len_(L)) == True{} : Bool})
    -> {BK.btk(k, List.append(&2, Bool, L, R)) == BK.btk(k, L) : +List<Bool>}:
  match L k:
    case Nil{} 0n: {==}
    case Nil{} 1n+ +j: Empty.absurd({BK.btk(1n+j, List.append(&2, Bool, Nil{}, R)) == BK.btk(1n+j, Nil{}) : +List<Bool>}, F.logic__false_true(h))
    case Con{+b, +l} 0n: {==}
    case Con{+b, +l} 1n+ +j:
      %Equal.sym(+List<Bool>, BK.btk(j, List.append(&2, Bool, l, R)), BK.btk(j, l), btk_short(l, R, j, h)) :
        {Con{b, _} == Con{b, BK.btk(j, l)} : +List<Bool>}
      {==}

def btk_long(+L: +List<Bool>, +R: +List<Bool>, +j: Nat)
    -> {BK.btk(Nat.add(len_(L), j), List.append(&2, Bool, L, R)) == List.append(&2, Bool, L, BK.btk(j, R)) : +List<Bool>}:
  match L:
    case Nil{}: {==}
    case Con{+b, +l}:
      %Equal.sym(+List<Bool>, BK.btk(Nat.add(len_(l), j), List.append(&2, Bool, l, R)), List.append(&2, Bool, l, BK.btk(j, R)), btk_long(l, R, j)) :
        {Con{b, _} == Con{b, List.append(&2, Bool, l, BK.btk(j, R))} : +List<Bool>}
      {==}

# the first 32 q + r bits (r <= 32) of the bits of two lists of words that agree on their first q + 1 words
def btk_Hq(+q: Nat, +r: Nat, A: List<&2, U32>, B: List<&2, U32>, +hr: {Nat.is_le(r, 32n) == True{} : Bool},
    +hA: {Nat.is_le(1n+q, F.spec_common__length(U32, A)) == True{} : Bool}, +hB: {Nat.is_le(1n+q, F.spec_common__length(U32, B)) == True{} : Bool}, +H: Hi(1n+q, 0n, A, B))
    -> {BK.btk(Nat.add(WS.e32(q), r), BK.bitsof(A)) == BK.btk(Nat.add(WS.e32(q), r), BK.bitsof(B)) : +List<Bool>}:
  match q A B:
    case _ Nil{} _: Empty.absurd({BK.btk(Nat.add(WS.e32(q), r), BK.bitsof(Nil{})) == BK.btk(Nat.add(WS.e32(q), r), BK.bitsof(B)) : +List<Bool>}, F.logic__false_true(hA))
    case _ Con{+x, +rx} Nil{}: Empty.absurd({BK.btk(Nat.add(WS.e32(q), r), BK.bitsof(Con{x, rx})) == BK.btk(Nat.add(WS.e32(q), r), BK.bitsof(Nil{})) : +List<Bool>}, F.logic__false_true(hB))
    case 0n Con{+x, +rx} Con{+y, +ry}:
      (+e, +h1) = H
      +hx = F.logic__subst(Nat, z => {Nat.is_le(r, z) == True{} : Bool}, 32n, len_(BLf.wbits(x)), Equal.sym(Nat, len_(BLf.wbits(x)), 32n, wlen_u(x)), hr)
      +hy = F.logic__subst(Nat, z => {Nat.is_le(r, z) == True{} : Bool}, 32n, len_(BLf.wbits(y)), Equal.sym(Nat, len_(BLf.wbits(y)), 32n, wlen_u(y)), hr)
      Equal.trans(+List<Bool>, BK.btk(r, List.append(&2, Bool, BLf.wbits(x), BK.bitsof(rx))), BK.btk(r, BLf.wbits(x)), BK.btk(r, List.append(&2, Bool, BLf.wbits(y), BK.bitsof(ry))),
        btk_short(BLf.wbits(x), BK.bitsof(rx), r, hx),
        Equal.trans(+List<Bool>, BK.btk(r, BLf.wbits(x)), BK.btk(r, BLf.wbits(y)), BK.btk(r, List.append(&2, Bool, BLf.wbits(y), BK.bitsof(ry))),
          Equal.cong(U32, +List<Bool>, z => BK.btk(r, BLf.wbits(z)), x, y, e),
          Equal.sym(+List<Bool>, BK.btk(r, List.append(&2, Bool, BLf.wbits(y), BK.bitsof(ry))), BK.btk(r, BLf.wbits(y)), btk_short(BLf.wbits(y), BK.bitsof(ry), r, hy))))
    case 1n+ +q1 Con{+x, +rx} Con{+y, +ry}:
      (+e, +h1) = H
      +ih = btk_Hq(q1, r, rx, ry, hr, hA, hB, hi_shift(1n+q1, 0n, x, rx, y, ry, h1))
      Equal.trans(+List<Bool>, BK.btk(Nat.add(WS.e32(1n+q1), r), List.append(&2, Bool, BLf.wbits(x), BK.bitsof(rx))), List.append(&2, Bool, BLf.wbits(x), BK.btk(Nat.add(WS.e32(q1), r), BK.bitsof(rx))),
        BK.btk(Nat.add(WS.e32(1n+q1), r), List.append(&2, Bool, BLf.wbits(y), BK.bitsof(ry))),
        Equal.trans(+List<Bool>, BK.btk(Nat.add(WS.e32(1n+q1), r), List.append(&2, Bool, BLf.wbits(x), BK.bitsof(rx))), BK.btk(Nat.add(len_(BLf.wbits(x)), Nat.add(WS.e32(q1), r)), List.append(&2, Bool, BLf.wbits(x), BK.bitsof(rx))),
          List.append(&2, Bool, BLf.wbits(x), BK.btk(Nat.add(WS.e32(q1), r), BK.bitsof(rx))),
          Equal.cong(Nat, +List<Bool>, z => BK.btk(Nat.add(z, Nat.add(WS.e32(q1), r)), List.append(&2, Bool, BLf.wbits(x), BK.bitsof(rx))), 32n, len_(BLf.wbits(x)), Equal.sym(Nat, len_(BLf.wbits(x)), 32n, wlen_u(x))),
          btk_long(BLf.wbits(x), BK.bitsof(rx), Nat.add(WS.e32(q1), r))),
        Equal.trans(+List<Bool>, List.append(&2, Bool, BLf.wbits(x), BK.btk(Nat.add(WS.e32(q1), r), BK.bitsof(rx))), List.append(&2, Bool, BLf.wbits(y), BK.btk(Nat.add(WS.e32(q1), r), BK.bitsof(ry))),
          BK.btk(Nat.add(WS.e32(1n+q1), r), List.append(&2, Bool, BLf.wbits(y), BK.bitsof(ry))),
          Equal.trans(+List<Bool>, List.append(&2, Bool, BLf.wbits(x), BK.btk(Nat.add(WS.e32(q1), r), BK.bitsof(rx))), List.append(&2, Bool, BLf.wbits(x), BK.btk(Nat.add(WS.e32(q1), r), BK.bitsof(ry))), List.append(&2, Bool, BLf.wbits(y), BK.btk(Nat.add(WS.e32(q1), r), BK.bitsof(ry))),
            Equal.cong(+List<Bool>, +List<Bool>, z => List.append(&2, Bool, BLf.wbits(x), z), BK.btk(Nat.add(WS.e32(q1), r), BK.bitsof(rx)), BK.btk(Nat.add(WS.e32(q1), r), BK.bitsof(ry)), ih),
            Equal.cong(U32, +List<Bool>, z => List.append(&2, Bool, BLf.wbits(z), BK.btk(Nat.add(WS.e32(q1), r), BK.bitsof(ry))), x, y, e)),
          Equal.sym(+List<Bool>, BK.btk(Nat.add(WS.e32(1n+q1), r), List.append(&2, Bool, BLf.wbits(y), BK.bitsof(ry))), List.append(&2, Bool, BLf.wbits(y), BK.btk(Nat.add(WS.e32(q1), r), BK.bitsof(ry))),
            Equal.trans(+List<Bool>, BK.btk(Nat.add(WS.e32(1n+q1), r), List.append(&2, Bool, BLf.wbits(y), BK.bitsof(ry))), BK.btk(Nat.add(len_(BLf.wbits(y)), Nat.add(WS.e32(q1), r)), List.append(&2, Bool, BLf.wbits(y), BK.bitsof(ry))),
              List.append(&2, Bool, BLf.wbits(y), BK.btk(Nat.add(WS.e32(q1), r), BK.bitsof(ry))),
              Equal.cong(Nat, +List<Bool>, z => BK.btk(Nat.add(z, Nat.add(WS.e32(q1), r)), List.append(&2, Bool, BLf.wbits(y), BK.bitsof(ry))), 32n, len_(BLf.wbits(y)), Equal.sym(Nat, len_(BLf.wbits(y)), 32n, wlen_u(y))),
              btk_long(BLf.wbits(y), BK.bitsof(ry), Nat.add(WS.e32(q1), r))))))

# the words of the copy (K + 1 words copied from t into T2) agree with t's on the words j .. j + m - 1 <= K
def hi_cpy(+m: Nat, +j: Nat, +K: Nat, +d2: Nat, +t: F.array__Tree<U32>, +T2: F.array__Tree<U32>, +hj: {Nat.is_le(Nat.add(j, m), 1n+K) == True{} : Bool},
    +b2: {Nat.is_le(Nat.add(0n, 1n+K), F.spec_common__pow2(d2)) == True{} : Bool}, +pf2: {F.array__perfect(U32, d2, T2) == True{} : Bool})
    -> Hi(m, j, F.array__slots(U32, WR.cpy(d2, t, K, 0n, T2)), F.array__slots(U32, t)):
  match m:
    case 0n: {==}
    case 1n+ +p:
      +hj1 = F.logic__subst(Nat, z => {Nat.is_le(z, 1n+K) == True{} : Bool}, Nat.add(j, 1n+p), Nat.add(1n+j, p), WW.add_shift_plain(j, p), hj)
      +hjK = F.nat__le_trans(j, Nat.add(j, p), K, Order.below_sum(j, p), hj1)
      (WW.wd_cpy_in(K, j, d2, t, 0n, T2, hjK, b2, pf2), hi_cpy(p, 1n+j, K, d2, t, T2, hj1, b2, pf2))

# the new position n is below the bits of the first q + 1 words
def nlt(+n: U32, +q: Nat, +hq: {U32.to_nat(U32.shrn(n, 5n)) == q : Nat}) -> {Nat.is_lt(U32.to_nat(n), WS.e32(1n+q)) == True{} : Bool}:
  +k = U32.to_nat(U32.and(n, 31))
  +ha = Equal.trans(Nat, Nat.add(k, WS.e32(q)), Nat.add(k, Nat.double(Nat.double(Nat.double(Nat.double(Nat.double(U32.to_nat(U32.shrn(n, 5n)))))))), U32.to_nat(n),
    Equal.cong(Nat, Nat, z => Nat.add(k, Nat.double(Nat.double(Nat.double(Nat.double(Nat.double(z)))))), q, U32.to_nat(U32.shrn(n, 5n)), Equal.sym(Nat, U32.to_nat(U32.shrn(n, 5n)), q, hq)),
    Equal.sym(Nat, U32.to_nat(n), Nat.add(k, Nat.double(Nat.double(Nat.double(Nat.double(Nat.double(U32.to_nat(U32.shrn(n, 5n)))))))), USP.split5(n)))
  +h3 = Order.add_right(1n+k, 32n, WS.e32(q), F.nat__lt_succ_le_succ(k, 32n, lt32(n)))
  F.logic__subst(Nat, z => {Nat.is_lt(z, WS.e32(1n+q)) == True{} : Bool}, Nat.add(k, WS.e32(q)), U32.to_nat(n), ha, F.nat__succ_le_lt(Nat.add(k, WS.e32(q)), WS.e32(1n+q), h3))

# the position n is 32 q + (its low five bits)
def nsplit(+n: U32, +q: Nat, +hq: {U32.to_nat(U32.shrn(n, 5n)) == q : Nat}) -> {Nat.add(WS.e32(q), U32.to_nat(U32.and(n, 31))) == U32.to_nat(n) : Nat}:
  +k = U32.to_nat(U32.and(n, 31))
  Equal.trans(Nat, Nat.add(WS.e32(q), k), Nat.add(k, WS.e32(q)), U32.to_nat(n), F.nat__add_comm(WS.e32(q), k),
    Equal.trans(Nat, Nat.add(k, WS.e32(q)), Nat.add(k, Nat.double(Nat.double(Nat.double(Nat.double(Nat.double(U32.to_nat(U32.shrn(n, 5n)))))))), U32.to_nat(n),
      Equal.cong(Nat, Nat, z => Nat.add(k, Nat.double(Nat.double(Nat.double(Nat.double(Nat.double(z)))))), q, U32.to_nat(U32.shrn(n, 5n)), Equal.sym(Nat, U32.to_nat(U32.shrn(n, 5n)), q, hq)),
      Equal.sym(Nat, U32.to_nat(n), Nat.add(k, Nat.double(Nat.double(Nat.double(Nat.double(Nat.double(U32.to_nat(U32.shrn(n, 5n)))))))), USP.split5(n))))

# the bits after the bit n is appended into the reallocated storage G (the copy of the first K + 1 words of t into a tree of zeros, depth d2): the bits before, and the new bit
def view_snoc_grow(+d: Nat, +d2: Nat, +t: F.array__Tree<U32>, +K: Nat, +n: U32, +N1: U32, +q: Nat, +v: Bool, +pf: {F.array__perfect(U32, d, t) == True{} : Bool},
    +b1: {Nat.is_le(Nat.add(0n, 1n+K), F.spec_common__pow2(d)) == True{} : Bool}, +b2: {Nat.is_le(Nat.add(0n, 1n+K), F.spec_common__pow2(d2)) == True{} : Bool},
    +hN: {U32.to_nat(N1) == 1n+U32.to_nat(n) : Nat}, +hg: {U32.is_lt(n, N1) == True{} : Bool}, +hq: {U32.to_nat(U32.shrn(n, 5n)) == q : Nat},
    +hk: {Nat.is_lt(q, F.spec_common__pow2(d2)) == True{} : Bool}, +hcov: {Nat.is_le(q, K) == True{} : Bool})
    -> {BO.bview(O.Bits{F.array__thaw(U32, F.array__upd(U32, d2, WR.cpy(d2, t, K, 0n, F.array__trep(U32, d2, 0)), q, O.bit_merge(v, WR.at(F.array__slots(U32, WR.cpy(d2, t, K, 0n, F.array__trep(U32, d2, 0))), q), M.shl_by(1, U32.and(n, 31))))), N1}) == List.append(&2, Bool, BO.bview(O.Bits{F.array__thaw(U32, t), n}), [v]) : +List<Bool>}:
  +pfG = WR.cpy_perfect(d2, t, K, 0n, F.array__trep(U32, d2, 0), F.array__trep_perfect(U32, d2, 0))
  +G = WR.cpy(d2, t, K, 0n, F.array__trep(U32, d2, 0))
  +hq1 = F.nat__le_trans(1n+q, 1n+K, F.spec_common__pow2(d), Order.add_left(1n, q, K, hcov), b1)
  +hq2 = F.nat__le_trans(1n+q, 1n+K, F.spec_common__pow2(d2), Order.add_left(1n, q, K, hcov), b2)
  +hA = F.logic__subst(Nat, z => {Nat.is_le(1n+q, z) == True{} : Bool}, F.spec_common__pow2(d2), F.spec_common__length(U32, F.array__slots(U32, G)), Equal.sym(Nat, F.spec_common__length(U32, F.array__slots(U32, G)), F.spec_common__pow2(d2), F.array__slots_length(U32, d2, G, pfG)), hq2)
  +hB = F.logic__subst(Nat, z => {Nat.is_le(1n+q, z) == True{} : Bool}, F.spec_common__pow2(d), F.spec_common__length(U32, F.array__slots(U32, t)), Equal.sym(Nat, F.spec_common__length(U32, F.array__slots(U32, t)), F.spec_common__pow2(d), F.array__slots_length(U32, d, t, pf)), hq1)
  +H = hi_cpy(1n+q, 0n, K, d2, t, F.array__trep(U32, d2, 0), Order.add_left(1n, q, K, hcov), b2, F.array__trep_perfect(U32, d2, 0))
  +ns = nsplit(n, q, hq)
  +hr = F.nat__lt_le(U32.to_nat(U32.and(n, 31)), 32n, lt32(n))
  +e3 = Equal.trans(+List<Bool>, BK.btk(U32.to_nat(n), BK.bitsof(F.array__slots(U32, G))), BK.btk(Nat.add(WS.e32(q), U32.to_nat(U32.and(n, 31))), BK.bitsof(F.array__slots(U32, G))), BK.btk(U32.to_nat(n), BK.bitsof(F.array__slots(U32, t))),
    Equal.cong(Nat, +List<Bool>, z => BK.btk(z, BK.bitsof(F.array__slots(U32, G))), U32.to_nat(n), Nat.add(WS.e32(q), U32.to_nat(U32.and(n, 31))), Equal.sym(Nat, Nat.add(WS.e32(q), U32.to_nat(U32.and(n, 31))), U32.to_nat(n), ns)),
    Equal.trans(+List<Bool>, BK.btk(Nat.add(WS.e32(q), U32.to_nat(U32.and(n, 31))), BK.bitsof(F.array__slots(U32, G))), BK.btk(Nat.add(WS.e32(q), U32.to_nat(U32.and(n, 31))), BK.bitsof(F.array__slots(U32, t))), BK.btk(U32.to_nat(n), BK.bitsof(F.array__slots(U32, t))),
      btk_Hq(q, U32.to_nat(U32.and(n, 31)), F.array__slots(U32, G), F.array__slots(U32, t), hr, hA, hB, H),
      Equal.cong(Nat, +List<Bool>, z => BK.btk(z, BK.bitsof(F.array__slots(U32, t))), Nat.add(WS.e32(q), U32.to_nat(U32.and(n, 31))), U32.to_nat(n), ns)))
  Equal.trans(+List<Bool>, BO.bview(O.Bits{F.array__thaw(U32, F.array__upd(U32, d2, G, q, O.bit_merge(v, WR.at(F.array__slots(U32, G), q), M.shl_by(1, U32.and(n, 31))))), N1}),
    lset(BO.bview(O.Bits{F.array__thaw(U32, G), N1}), U32.to_nat(n), v), List.append(&2, Bool, BO.bview(O.Bits{F.array__thaw(U32, t), n}), [v]),
    view_set(d2, G, N1, n, q, v, pfG, hg, hq, hk),
    Equal.trans(+List<Bool>, lset(BO.bview(O.Bits{F.array__thaw(U32, G), N1}), U32.to_nat(n), v), lset(BK.btk(1n+U32.to_nat(n), BK.bitsof(F.array__slots(U32, G))), U32.to_nat(n), v), List.append(&2, Bool, BO.bview(O.Bits{F.array__thaw(U32, t), n}), [v]),
      Equal.trans(+List<Bool>, lset(BO.bview(O.Bits{F.array__thaw(U32, G), N1}), U32.to_nat(n), v), lset(BK.btk(U32.to_nat(N1), BK.bitsof(F.array__slots(U32, G))), U32.to_nat(n), v), lset(BK.btk(1n+U32.to_nat(n), BK.bitsof(F.array__slots(U32, G))), U32.to_nat(n), v),
        Equal.cong(+List<Bool>, +List<Bool>, z => lset(z, U32.to_nat(n), v), BO.bview(O.Bits{F.array__thaw(U32, G), N1}), BK.btk(U32.to_nat(N1), BK.bitsof(F.array__slots(U32, G))), bview_thaw(G, N1)),
        Equal.cong(Nat, +List<Bool>, z => lset(BK.btk(z, BK.bitsof(F.array__slots(U32, G))), U32.to_nat(n), v), U32.to_nat(N1), 1n+U32.to_nat(n), hN)),
      Equal.trans(+List<Bool>, lset(BK.btk(1n+U32.to_nat(n), BK.bitsof(F.array__slots(U32, G))), U32.to_nat(n), v), List.append(&2, Bool, BK.btk(U32.to_nat(n), BK.bitsof(F.array__slots(U32, G))), [v]), List.append(&2, Bool, BO.bview(O.Bits{F.array__thaw(U32, t), n}), [v]),
        btk_snoc(U32.to_nat(n), BK.bitsof(F.array__slots(U32, G)), v, kbound(d2, G, n, q, pfG, hq, hk)),
        Equal.trans(+List<Bool>, List.append(&2, Bool, BK.btk(U32.to_nat(n), BK.bitsof(F.array__slots(U32, G))), [v]), List.append(&2, Bool, BK.btk(U32.to_nat(n), BK.bitsof(F.array__slots(U32, t))), [v]), List.append(&2, Bool, BO.bview(O.Bits{F.array__thaw(U32, t), n}), [v]),
          Equal.cong(+List<Bool>, +List<Bool>, z => List.append(&2, Bool, z, [v]), BK.btk(U32.to_nat(n), BK.bitsof(F.array__slots(U32, G))), BK.btk(U32.to_nat(n), BK.bitsof(F.array__slots(U32, t))), e3),
          Equal.cong(+List<Bool>, +List<Bool>, z => List.append(&2, Bool, z, [v]), BK.btk(U32.to_nat(n), BK.bitsof(F.array__slots(U32, t))), BO.bview(O.Bits{F.array__thaw(U32, t), n}),
            Equal.sym(+List<Bool>, BO.bview(O.Bits{F.array__thaw(U32, t), n}), BK.btk(U32.to_nat(n), BK.bitsof(F.array__slots(U32, t))), bview_thaw(t, n)))))))

# ---- the word count of the grown storage covers the word of the new bit: q = n >> 5 <= K = (bits_nbytes(n + 1) + 3) >> 2 ----
# (the byte count is ceil((n + 1) / 8); the grown copy keeps K + 1 words, so the word q of the new bit is among them)
def x8_add(+a: Nat, +b: Nat) -> {VS.x8(Nat.add(a, b)) == Nat.add(VS.x8(a), VS.x8(b)) : Nat}:
  match a:
    case 0n: {==}
    case 1n+ +p: Equal.cong(Nat, Nat, z => 8n+z, VS.x8(Nat.add(p, b)), Nat.add(VS.x8(p), VS.x8(b)), x8_add(p, b))

def x8_le(+a: Nat, +b: Nat, +h: {Nat.is_le(a, b) == True{} : Bool}) -> {Nat.is_le(VS.x8(a), VS.x8(b)) == True{} : Bool}:
  match a b:
    case 0n _: F.nat__zero_le(VS.x8(b))
    case 1n+ +p 0n: Empty.absurd({Nat.is_le(VS.x8(1n+p), VS.x8(0n)) == True{} : Bool}, F.logic__false_true(h))
    case 1n+ +p 1n+ +s: Order.add_left(8n, VS.x8(p), VS.x8(s), x8_le(p, s, h))

# eight times the quadruple is 32 times
def x8_quad(+k: Nat) -> {VS.x8(Nat.double(Nat.double(k))) == WS.e32(k) : Nat}:
  match k:
    case 0n: {==}
    case 1n+ +p: Equal.cong(Nat, Nat, z => 32n+z, VS.x8(Nat.double(Nat.double(p))), WS.e32(p), x8_quad(p))

# 32 a <= 32 M + 31 gives a <= M
def e32_rev(+a: Nat, +M: Nat, +h: {Nat.is_le(WS.e32(a), Nat.add(WS.e32(M), 31n)) == True{} : Bool}) -> {Nat.is_le(a, M) == True{} : Bool}:
  match a M:
    case 0n _: F.nat__zero_le(M)
    case 1n+ +p 0n: Empty.absurd({Nat.is_le(1n+p, 0n) == True{} : Bool}, F.logic__false_true(h))
    case 1n+ +p 1n+ +c: e32_rev(p, c, h)

# 3 + a <= 3 + b gives a <= b
def cancel3(+a: Nat, +b: Nat, +h: {Nat.is_le(Nat.add(3n, a), Nat.add(3n, b)) == True{} : Bool}) -> {Nat.is_le(a, b) == True{} : Bool}: h

# a remainder b <= 7 is below eight times its carry (b + 7) >> 3
def b_x8(+b: Nat, +hb: {Nat.is_le(b, 7n) == True{} : Bool}) -> {Nat.is_le(b, VS.x8(VD.s_rng(3n, Nat.add(b, 7n)))) == True{} : Bool}:
  match b:
    case 0n: {==}
    case 1n: {==}
    case 2n: {==}
    case 3n: {==}
    case 4n: {==}
    case 5n: {==}
    case 6n: {==}
    case 7n: {==}
    case 8n+ +p: Empty.absurd({Nat.is_le(8n+p, VS.x8(VD.s_rng(3n, Nat.add(8n+p, 7n)))) == True{} : Bool}, F.logic__false_true(hb))

# n + 1 bits within the bound c, and c + 8 within 2^kb (checked once on the schema limit), is the premise of the byte-count lemmas
def hk_of(+N1: U32, +c: U32, +kb: Nat, +ha: {U32.is_le(N1, c) == True{} : Bool}, +hc: {Nat.is_le(Nat.add(U32.to_nat(c), 8n), O.pow2n(kb)) == True{} : Bool}) -> VBT.HK(N1, kb):
  +hn = F.logic__subst(Bool, z => {z == True{} : Bool}, U32.is_le(N1, c), Nat.is_le(U32.to_nat(N1), U32.to_nat(c)), VU.le_u32(N1, c), ha)
  F.nat__le_trans(Nat.add(U32.to_nat(N1), 8n), Nat.add(U32.to_nat(c), 8n), O.pow2n(kb), Order.add_right(U32.to_nat(N1), U32.to_nat(c), 8n, hn), hc)

# the word count K of the grown storage: N1 <= 32 K, from the byte count ceil(N1 / 8) <= 4 K
def kcov_n1(+N1: U32, +kb: Nat, +hkb: {Nat.is_lt(kb, 33n) == True{} : Bool}, +hK: VBT.HK(N1, kb))
    -> {Nat.is_le(U32.to_nat(N1), WS.e32(U32.to_nat(U32.shrn(U32.add(O.bits_nbytes(N1), 3), 2n)))) == True{} : Bool}:
  +A = VBT.AK(N1)
  +B = VBT.BKk(N1)
  +s = VD.s_rng(3n, Nat.add(B, 7n))
  +NB = U32.to_nat(O.bits_nbytes(N1))
  +X = U32.add(O.bits_nbytes(N1), 3)
  +K2 = U32.to_nat(U32.shrn(X, 2n))
  +e3 = VBT.E3(N1, kb, hkb, hK)
  +hB7 = RD.and_le(N1, 7)
  +hnb = F.logic__subst(Nat, z => {Nat.is_le(z, Nat.add(U32.to_nat(N1), 1n)) == True{} : Bool}, Nat.add(A, s), NB, Equal.sym(Nat, NB, Nat.add(A, s), e3),
    F.nat__le_trans(Nat.add(A, s), Nat.add(U32.to_nat(N1), s), Nat.add(U32.to_nat(N1), 1n), Order.add_right(A, U32.to_nat(N1), s, VBT.lAK(N1)),
      Order.add_left(U32.to_nat(N1), s, 1n, VBT.rs7(B, hB7))))
  +hs0 = F.nat__le_trans(Nat.add(NB, 3n), Nat.add(Nat.add(U32.to_nat(N1), 1n), 3n), Nat.add(U32.to_nat(N1), 7n), Order.add_right(NB, Nat.add(U32.to_nat(N1), 1n), 3n, hnb),
    F.logic__subst(Nat, z => {Nat.is_le(z, Nat.add(U32.to_nat(N1), 7n)) == True{} : Bool}, Nat.add(U32.to_nat(N1), Nat.add(1n, 3n)), Nat.add(Nat.add(U32.to_nat(N1), 1n), 3n),
      Equal.sym(Nat, Nat.add(Nat.add(U32.to_nat(N1), 1n), 3n), Nat.add(U32.to_nat(N1), Nat.add(1n, 3n)), F.nat__add_assoc(U32.to_nat(N1), 1n, 3n)),
      Order.add_left(U32.to_nat(N1), 4n, 7n, {==})))
  +eX = VBT.sadd33(O.bits_nbytes(N1), 3, N1, kb, hkb, hK, hs0)
  +sp = USP.split2(X)
  +h1 = F.logic__subst(Nat, z => {Nat.is_le(z, Nat.add(3n, Nat.double(Nat.double(K2)))) == True{} : Bool}, Nat.add(U32.to_nat(U32.and(X, 3)), Nat.double(Nat.double(K2))), Nat.add(NB, 3n),
    Equal.trans(Nat, Nat.add(U32.to_nat(U32.and(X, 3)), Nat.double(Nat.double(K2))), U32.to_nat(X), Nat.add(NB, 3n), Equal.sym(Nat, U32.to_nat(X), Nat.add(U32.to_nat(U32.and(X, 3)), Nat.double(Nat.double(K2))), sp), eX),
    Order.add_right(U32.to_nat(U32.and(X, 3)), 3n, Nat.double(Nat.double(K2)), RD.and_le(X, 3)))
  +h2 = F.logic__subst(Nat, z => {Nat.is_le(z, Nat.add(3n, Nat.double(Nat.double(K2)))) == True{} : Bool}, Nat.add(NB, 3n), Nat.add(3n, NB), F.nat__add_comm(NB, 3n), h1)
  +h3 = cancel3(NB, Nat.double(Nat.double(K2)), h2)
  +hxa = F.logic__subst(Nat, z => {Nat.is_le(z, Nat.add(VS.x8(A), VS.x8(s))) == True{} : Bool}, Nat.add(VS.x8(A), B), U32.to_nat(N1), Equal.sym(Nat, U32.to_nat(N1), Nat.add(VS.x8(A), B), VBT.E1(N1)),
    Order.add_left(VS.x8(A), B, VS.x8(s), b_x8(B, hB7)))
  +hxb = Equal.trans(Nat, Nat.add(VS.x8(A), VS.x8(s)), VS.x8(Nat.add(A, s)), VS.x8(NB), Equal.sym(Nat, VS.x8(Nat.add(A, s)), Nat.add(VS.x8(A), VS.x8(s)), x8_add(A, s)),
    Equal.cong(Nat, Nat, z => VS.x8(z), Nat.add(A, s), NB, Equal.sym(Nat, NB, Nat.add(A, s), e3)))
  +hxc = F.logic__subst(Nat, z => {Nat.is_le(U32.to_nat(N1), z) == True{} : Bool}, Nat.add(VS.x8(A), VS.x8(s)), VS.x8(NB), hxb, hxa)
  +hxe = F.nat__le_trans(U32.to_nat(N1), VS.x8(NB), VS.x8(Nat.double(Nat.double(K2))), hxc, x8_le(NB, Nat.double(Nat.double(K2)), h3))
  F.logic__subst(Nat, z => {Nat.is_le(U32.to_nat(N1), z) == True{} : Bool}, VS.x8(Nat.double(Nat.double(K2))), WS.e32(K2), x8_quad(K2), hxe)

# q <= K: the new bit's word is within the words kept
def kcov(+n: U32, +N1: U32, +q: Nat, +kb: Nat, +hkb: {Nat.is_lt(kb, 33n) == True{} : Bool}, +hK: VBT.HK(N1, kb),
    +hN: {U32.to_nat(N1) == 1n+U32.to_nat(n) : Nat}, +hq: {U32.to_nat(U32.shrn(n, 5n)) == q : Nat})
    -> {Nat.is_le(q, U32.to_nat(U32.shrn(U32.add(O.bits_nbytes(N1), 3), 2n))) == True{} : Bool}:
  +K2 = U32.to_nat(U32.shrn(U32.add(O.bits_nbytes(N1), 3), 2n))
  +ha = F.logic__subst(Nat, z => {Nat.is_le(WS.e32(q), z) == True{} : Bool}, Nat.add(WS.e32(q), U32.to_nat(U32.and(n, 31))), U32.to_nat(n), nsplit(n, q, hq), Order.below_sum(WS.e32(q), U32.to_nat(U32.and(n, 31))))
  +hb = F.logic__subst(Nat, z => {Nat.is_le(U32.to_nat(n), z) == True{} : Bool}, 1n+U32.to_nat(n), U32.to_nat(N1), Equal.sym(Nat, U32.to_nat(N1), 1n+U32.to_nat(n), hN), Order.left_below_sum(1n, U32.to_nat(n)))
  +hc = F.nat__le_trans(WS.e32(q), U32.to_nat(N1), WS.e32(K2), F.nat__le_trans(WS.e32(q), U32.to_nat(n), U32.to_nat(N1), ha, hb), kcov_n1(N1, kb, hkb, hK))
  e32_rev(q, K2, F.nat__le_trans(WS.e32(q), WS.e32(K2), Nat.add(WS.e32(K2), 31n), hc, F.nat__le_add_right(WS.e32(K2), 31n)))
'''


VIEW_CLOSE = r'''
# ---- the push closes the next word (docs/CRASH_HUNT.md R5-01): O.bits_close(n, b) writes word j = (n >> 5) + 1 back, zero when n & 31 = 31,
# when j is inside the storage. close_t is the storage tree after it; it keeps the words 0 .. n >> 5, so the bits up to n + 1 are unchanged ----
def close_g(inside: Bool, +d: Nat, +T: F.array__Tree<U32>, +n: U32) -> F.array__Tree<U32>:
  match inside:
    case True{}: F.array__upd(U32, d, T, U32.to_nat((U32.shrn(n, 5n) + 1 : U32)), O.app_old31(WR.at(F.array__slots(U32, T), U32.to_nat((U32.shrn(n, 5n) + 1 : U32))), U32.and(n, 31)))
    case False{}: T

def close_t(+d: Nat, +T: F.array__Tree<U32>, +n: U32) -> F.array__Tree<U32>: close_g(U32.is_lt((U32.shrn(n, 5n) + 1 : U32), F.u32__pow2u(d)), d, T, n)

# the next word inside the storage, as a Nat
def guard_lt(+d: Nat, +n: U32, +hd: {Nat.is_lt(d, 32n) == True{} : Bool}, +e: {U32.is_lt((U32.shrn(n, 5n) + 1 : U32), F.u32__pow2u(d)) == True{} : Bool})
    -> {Nat.is_lt(U32.to_nat((U32.shrn(n, 5n) + 1 : U32)), F.spec_common__pow2(d)) == True{} : Bool}:
  +hl = F.logic__subst(Bool, z => {z == True{} : Bool}, U32.is_lt((U32.shrn(n, 5n) + 1 : U32), F.u32__pow2u(d)), Nat.is_lt(U32.to_nat((U32.shrn(n, 5n) + 1 : U32)), U32.to_nat(F.u32__pow2u(d))),
    F.u32__is_lt_nat((U32.shrn(n, 5n) + 1 : U32), F.u32__pow2u(d)), e)
  F.logic__subst(Nat, z => {Nat.is_lt(U32.to_nat((U32.shrn(n, 5n) + 1 : U32)), z) == True{} : Bool}, U32.to_nat(F.u32__pow2u(d)), F.spec_common__pow2(d), F.u32__pow2u_value(d, hd), hl)

# the next word is word q + 1 (no wrap: q is below 2^d, d < 32)
def nowrap(+n: U32, +q: Nat, +d: Nat, +hd: {Nat.is_lt(d, 32n) == True{} : Bool}, +hq: {U32.to_nat(U32.shrn(n, 5n)) == q : Nat}, +hk: {Nat.is_lt(q, F.spec_common__pow2(d)) == True{} : Bool})
    -> {U32.to_nat((U32.shrn(n, 5n) + 1 : U32)) == 1n+q : Nat}:
  +h0 = F.nat__lt_succ_le_succ(q, F.spec_common__pow2(d), hk)
  +h1 = F.logic__subst(Nat, z => {Nat.is_le(1n+z, F.spec_common__pow2(d)) == True{} : Bool}, q, U32.to_nat(U32.shrn(n, 5n)), Equal.sym(Nat, U32.to_nat(U32.shrn(n, 5n)), q, hq), h0)
  +h2 = F.logic__subst(Nat, z => {Nat.is_le(1n+U32.to_nat(U32.shrn(n, 5n)), z) == True{} : Bool}, F.spec_common__pow2(d), U32.to_nat(F.u32__pow2u(d)),
    Equal.sym(Nat, U32.to_nat(F.u32__pow2u(d)), F.spec_common__pow2(d), F.u32__pow2u_value(d, hd)), h1)
  Equal.trans(Nat, U32.to_nat((U32.shrn(n, 5n) + 1 : U32)), 1n+U32.to_nat(U32.shrn(n, 5n)), 1n+q, VVU.addk(U32.shrn(n, 5n), 1, F.u32__pow2u(d), h2),
    F.nat__succ_cong(U32.to_nat(U32.shrn(n, 5n)), q, hq))

def succ_ne(+q: Nat) -> {Nat.is_eq(1n+q, q) == False{} : Bool}:
  match q:
    case 0n: {==}
    case 1n+p: succ_ne(p)

# the storage after the close: the runtime's close of the thawed tree is the thaw of close_t
def close_thaw_g(inside: Bool, +d: Nat, +T: F.array__Tree<U32>, +n: U32, +N1: U32, +e: {U32.is_lt((U32.shrn(n, 5n) + 1 : U32), F.u32__pow2u(d)) == inside : Bool},
    +hd: {Nat.is_lt(d, 32n) == True{} : Bool}, +pf: {F.array__perfect(U32, d, T) == True{} : Bool})
    -> {O.bits_close_if(inside, n, O.Bits{F.array__thaw(U32, T), N1}) == O.Bits{F.array__thaw(U32, close_g(inside, d, T, n)), N1} : O.Bits}:
  match inside:
    case True{}:
      +J = (U32.shrn(n, 5n) + 1 : U32)
      +hJ = guard_lt(d, n, hd, e)
      %Equal.sym(O.Bits & U32, O.bits_word(O.Bits{F.array__thaw(U32, T), N1}, J), (O.Bits{F.array__thaw(U32, T), N1}, WR.at(F.array__slots(U32, T), U32.to_nat(J))), WR.bword_thaw(d, T, N1, J, U32.to_nat(J), hd, {==}, hJ, pf)) :
        {O.bits_close_go(n, _) == O.Bits{F.array__thaw(U32, close_g(True{}, d, T, n)), N1} : O.Bits}
      %Equal.sym(O.Bits, O.bits_setw(O.Bits{F.array__thaw(U32, T), N1}, J, O.app_old31(WR.at(F.array__slots(U32, T), U32.to_nat(J)), U32.and(n, 31))),
          O.Bits{F.array__thaw(U32, F.array__upd(U32, d, T, U32.to_nat(J), O.app_old31(WR.at(F.array__slots(U32, T), U32.to_nat(J)), U32.and(n, 31)))), N1},
          WR.bsetw_thaw(d, T, N1, J, U32.to_nat(J), O.app_old31(WR.at(F.array__slots(U32, T), U32.to_nat(J)), U32.and(n, 31)), hd, {==}, hJ, pf)) :
        {_ == O.Bits{F.array__thaw(U32, close_g(True{}, d, T, n)), N1} : O.Bits}
      {==}
    case False{}: {==}

def close_thaw(+d: Nat, +T: F.array__Tree<U32>, +n: U32, +N1: U32, +hd: {Nat.is_lt(d, 32n) == True{} : Bool}, +pf: {F.array__perfect(U32, d, T) == True{} : Bool})
    -> {O.bits_close(n, O.Bits{F.array__thaw(U32, T), N1}) == O.Bits{F.array__thaw(U32, close_t(d, T, n)), N1} : O.Bits}:
  %Equal.sym(Array<U32> & U32, Array.size(U32, F.array__thaw(U32, T)), (F.array__thaw(U32, T), F.u32__pow2u(d)), F.array__size_thaw(U32, d, T, pf)) :
    {O.bits_close_sz(n, N1, _) == O.Bits{F.array__thaw(U32, close_t(d, T, n)), N1} : O.Bits}
  close_thaw_g(U32.is_lt((U32.shrn(n, 5n) + 1 : U32), F.u32__pow2u(d)), d, T, n, N1, {==}, hd, pf)

def close_perfect_g(inside: Bool, +d: Nat, +T: F.array__Tree<U32>, +n: U32, +pf: {F.array__perfect(U32, d, T) == True{} : Bool})
    -> {F.array__perfect(U32, d, close_g(inside, d, T, n)) == True{} : Bool}:
  match inside:
    case True{}: F.array__upd_perfect(U32, d, T, U32.to_nat((U32.shrn(n, 5n) + 1 : U32)), O.app_old31(WR.at(F.array__slots(U32, T), U32.to_nat((U32.shrn(n, 5n) + 1 : U32))), U32.and(n, 31)), pf)
    case False{}: pf

def close_perfect(+d: Nat, +T: F.array__Tree<U32>, +n: U32, +pf: {F.array__perfect(U32, d, T) == True{} : Bool}) -> {F.array__perfect(U32, d, close_t(d, T, n)) == True{} : Bool}:
  close_perfect_g(U32.is_lt((U32.shrn(n, 5n) + 1 : U32), F.u32__pow2u(d)), d, T, n, pf)

# word q of the storage is unchanged by the close
def at_close_g(inside: Bool, +d: Nat, +T: F.array__Tree<U32>, +n: U32, +q: Nat, +e: {U32.is_lt((U32.shrn(n, 5n) + 1 : U32), F.u32__pow2u(d)) == inside : Bool},
    +hd: {Nat.is_lt(d, 32n) == True{} : Bool}, +nw: {U32.to_nat((U32.shrn(n, 5n) + 1 : U32)) == 1n+q : Nat}, +pf: {F.array__perfect(U32, d, T) == True{} : Bool})
    -> {WR.at(F.array__slots(U32, close_g(inside, d, T, n)), q) == WR.at(F.array__slots(U32, T), q) : U32}:
  match inside:
    case True{}:
      +ne = F.logic__subst(Nat, z => {Nat.is_eq(z, q) == False{} : Bool}, 1n+q, U32.to_nat((U32.shrn(n, 5n) + 1 : U32)), Equal.sym(Nat, U32.to_nat((U32.shrn(n, 5n) + 1 : U32)), 1n+q, nw), succ_ne(q))
      WR.at_upd_other(d, T, U32.to_nat((U32.shrn(n, 5n) + 1 : U32)), q, O.app_old31(WR.at(F.array__slots(U32, T), U32.to_nat((U32.shrn(n, 5n) + 1 : U32))), U32.and(n, 31)), ne, guard_lt(d, n, hd, e), pf)
    case False{}: {==}

def at_close(+d: Nat, +T: F.array__Tree<U32>, +n: U32, +q: Nat, +hd: {Nat.is_lt(d, 32n) == True{} : Bool}, +nw: {U32.to_nat((U32.shrn(n, 5n) + 1 : U32)) == 1n+q : Nat},
    +pf: {F.array__perfect(U32, d, T) == True{} : Bool}) -> {WR.at(F.array__slots(U32, close_t(d, T, n)), q) == WR.at(F.array__slots(U32, T), q) : U32}:
  at_close_g(U32.is_lt((U32.shrn(n, 5n) + 1 : U32), F.u32__pow2u(d)), d, T, n, q, {==}, hd, nw, pf)

# the first 32 q + r bits (r <= 32) do not see word q + 1
def btk_upd(+q: Nat, +r: Nat, +W: List<&2, U32>, +x: U32, +hr: {Nat.is_le(r, 32n) == True{} : Bool})
    -> {BK.btk(Nat.add(WS.e32(q), r), BK.bitsof(F.spec_common__update(U32, W, 1n+q, x))) == BK.btk(Nat.add(WS.e32(q), r), BK.bitsof(W)) : +List<Bool>}:
  match q W:
    case _ Nil{}: {==}
    case 0n Con{+y, +ry}:
      +hy = F.logic__subst(Nat, z => {Nat.is_le(r, z) == True{} : Bool}, 32n, len_(BLf.wbits(y)), Equal.sym(Nat, len_(BLf.wbits(y)), 32n, wlen_u(y)), hr)
      Equal.trans(+List<Bool>, BK.btk(r, List.append(&2, Bool, BLf.wbits(y), BK.bitsof(F.spec_common__update(U32, ry, 0n, x)))), BK.btk(r, BLf.wbits(y)), BK.btk(r, List.append(&2, Bool, BLf.wbits(y), BK.bitsof(ry))),
        btk_short(BLf.wbits(y), BK.bitsof(F.spec_common__update(U32, ry, 0n, x)), r, hy),
        Equal.sym(+List<Bool>, BK.btk(r, List.append(&2, Bool, BLf.wbits(y), BK.bitsof(ry))), BK.btk(r, BLf.wbits(y)), btk_short(BLf.wbits(y), BK.bitsof(ry), r, hy)))
    case 1n+ +q1 Con{+y, +ry}:
      +j = Nat.add(WS.e32(q1), r)
      +U = BK.bitsof(F.spec_common__update(U32, ry, 1n+q1, x))
      +ih = btk_upd(q1, r, ry, x, hr)
      +el = Equal.sym(Nat, len_(BLf.wbits(y)), 32n, wlen_u(y))
      +a1 = Equal.trans(+List<Bool>, BK.btk(Nat.add(WS.e32(1n+q1), r), List.append(&2, Bool, BLf.wbits(y), U)), BK.btk(Nat.add(len_(BLf.wbits(y)), j), List.append(&2, Bool, BLf.wbits(y), U)),
        List.append(&2, Bool, BLf.wbits(y), BK.btk(j, U)),
        Equal.cong(Nat, +List<Bool>, z => BK.btk(Nat.add(z, j), List.append(&2, Bool, BLf.wbits(y), U)), 32n, len_(BLf.wbits(y)), el),
        btk_long(BLf.wbits(y), U, j))
      +a3 = Equal.trans(+List<Bool>, BK.btk(Nat.add(WS.e32(1n+q1), r), List.append(&2, Bool, BLf.wbits(y), BK.bitsof(ry))), BK.btk(Nat.add(len_(BLf.wbits(y)), j), List.append(&2, Bool, BLf.wbits(y), BK.bitsof(ry))),
        List.append(&2, Bool, BLf.wbits(y), BK.btk(j, BK.bitsof(ry))),
        Equal.cong(Nat, +List<Bool>, z => BK.btk(Nat.add(z, j), List.append(&2, Bool, BLf.wbits(y), BK.bitsof(ry))), 32n, len_(BLf.wbits(y)), el),
        btk_long(BLf.wbits(y), BK.bitsof(ry), j))
      Equal.trans(+List<Bool>, BK.btk(Nat.add(WS.e32(1n+q1), r), List.append(&2, Bool, BLf.wbits(y), U)), List.append(&2, Bool, BLf.wbits(y), BK.btk(j, U)),
        BK.btk(Nat.add(WS.e32(1n+q1), r), List.append(&2, Bool, BLf.wbits(y), BK.bitsof(ry))), a1,
        Equal.trans(+List<Bool>, List.append(&2, Bool, BLf.wbits(y), BK.btk(j, U)), List.append(&2, Bool, BLf.wbits(y), BK.btk(j, BK.bitsof(ry))),
          BK.btk(Nat.add(WS.e32(1n+q1), r), List.append(&2, Bool, BLf.wbits(y), BK.bitsof(ry))),
          Equal.cong(+List<Bool>, +List<Bool>, z => List.append(&2, Bool, BLf.wbits(y), z), BK.btk(j, U), BK.btk(j, BK.bitsof(ry)), ih),
          Equal.sym(+List<Bool>, BK.btk(Nat.add(WS.e32(1n+q1), r), List.append(&2, Bool, BLf.wbits(y), BK.bitsof(ry))), List.append(&2, Bool, BLf.wbits(y), BK.btk(j, BK.bitsof(ry))), a3)))

# the bits of the bit list (n + 1 bits) after the close are the bits before it
def view_close_g(inside: Bool, +d: Nat, +T: F.array__Tree<U32>, +n: U32, +q: Nat, +N1: U32, +e: {U32.is_lt((U32.shrn(n, 5n) + 1 : U32), F.u32__pow2u(d)) == inside : Bool},
    +hd: {Nat.is_lt(d, 32n) == True{} : Bool}, +hq: {U32.to_nat(U32.shrn(n, 5n)) == q : Nat}, +hN: {U32.to_nat(N1) == 1n+U32.to_nat(n) : Nat},
    +nw: {U32.to_nat((U32.shrn(n, 5n) + 1 : U32)) == 1n+q : Nat}, +pf: {F.array__perfect(U32, d, T) == True{} : Bool})
    -> {BO.bview(O.Bits{F.array__thaw(U32, close_g(inside, d, T, n)), N1}) == BO.bview(O.Bits{F.array__thaw(U32, T), N1}) : +List<Bool>}:
  match inside:
    case True{}:
      +J = U32.to_nat((U32.shrn(n, 5n) + 1 : U32))
      +X = O.app_old31(WR.at(F.array__slots(U32, T), J), U32.and(n, 31))
      +U = F.array__upd(U32, d, T, J, X)
      +k = U32.to_nat(U32.and(n, 31))
      +hN2 = Equal.trans(Nat, U32.to_nat(N1), 1n+Nat.add(WS.e32(q), k), Nat.add(WS.e32(q), 1n+k),
        Equal.trans(Nat, U32.to_nat(N1), 1n+U32.to_nat(n), 1n+Nat.add(WS.e32(q), k), hN, F.nat__succ_cong(U32.to_nat(n), Nat.add(WS.e32(q), k), Equal.sym(Nat, Nat.add(WS.e32(q), k), U32.to_nat(n), nsplit(n, q, hq)))),
        Equal.sym(Nat, Nat.add(WS.e32(q), 1n+k), 1n+Nat.add(WS.e32(q), k), F.nat__add_succ(WS.e32(q), k)))
      %Equal.sym(+List<Bool>, BO.bview(O.Bits{F.array__thaw(U32, U), N1}), BK.btk(U32.to_nat(N1), BK.bitsof(F.array__slots(U32, U))), bview_thaw(U, N1)) :
        {_ == BO.bview(O.Bits{F.array__thaw(U32, T), N1}) : +List<Bool>}
      %Equal.sym(+List<Bool>, BO.bview(O.Bits{F.array__thaw(U32, T), N1}), BK.btk(U32.to_nat(N1), BK.bitsof(F.array__slots(U32, T))), bview_thaw(T, N1)) :
        {BK.btk(U32.to_nat(N1), BK.bitsof(F.array__slots(U32, U))) == _ : +List<Bool>}
      %Equal.sym(List<&2, U32>, F.array__slots(U32, U), F.spec_common__update(U32, F.array__slots(U32, T), J, X), F.array__upd_slots(U32, d, T, J, X, guard_lt(d, n, hd, e), pf)) :
        {BK.btk(U32.to_nat(N1), BK.bitsof(_)) == BK.btk(U32.to_nat(N1), BK.bitsof(F.array__slots(U32, T))) : +List<Bool>}
      %Equal.sym(Nat, J, 1n+q, nw) :
        {BK.btk(U32.to_nat(N1), BK.bitsof(F.spec_common__update(U32, F.array__slots(U32, T), _, X))) == BK.btk(U32.to_nat(N1), BK.bitsof(F.array__slots(U32, T))) : +List<Bool>}
      %Equal.sym(Nat, U32.to_nat(N1), Nat.add(WS.e32(q), 1n+k), hN2) :
        {BK.btk(_, BK.bitsof(F.spec_common__update(U32, F.array__slots(U32, T), 1n+q, X))) == BK.btk(_, BK.bitsof(F.array__slots(U32, T))) : +List<Bool>}
      btk_upd(q, 1n+k, F.array__slots(U32, T), X, F.nat__lt_succ_le_succ(k, 32n, lt32(n)))
    case False{}: {==}

def view_close(+d: Nat, +T: F.array__Tree<U32>, +n: U32, +q: Nat, +N1: U32, +hd: {Nat.is_lt(d, 32n) == True{} : Bool}, +hq: {U32.to_nat(U32.shrn(n, 5n)) == q : Nat},
    +hN: {U32.to_nat(N1) == 1n+U32.to_nat(n) : Nat}, +nw: {U32.to_nat((U32.shrn(n, 5n) + 1 : U32)) == 1n+q : Nat}, +pf: {F.array__perfect(U32, d, T) == True{} : Bool})
    -> {BO.bview(O.Bits{F.array__thaw(U32, close_t(d, T, n)), N1}) == BO.bview(O.Bits{F.array__thaw(U32, T), N1}) : +List<Bool>}:
  view_close_g(U32.is_lt((U32.shrn(n, 5n) + 1 : U32), F.u32__pow2u(d)), d, T, n, q, N1, {==}, hd, hq, hN, nw, pf)
'''


def text():
    return HEAD + dispatcher() + VIEW_SET + VIEW_APPEND + VIEW_GROW + VIEW_CLOSE


def main():
    run_single('bit_list_set_view', OUT, text(), '--check' in sys.argv)


if __name__ == '__main__':
    main()
