#!/usr/bin/env python3
"""proofs/obj/bits_view.bend: the bits of a bit list after one bit is set.

The runtime sets bit i of a bit list by merging a one-bit mask into word i >> 5 (O.bit_merge(v, w, M.shl_by(1, i & 31))) and writing the word back.
The spec's view of the list is its first k bits (BK.btk(k, BK.bitsof(slots))). This file shows, for every word, bit position and value:

    wset_i(x, i, v): the bits of the merged word are the bits of x with bit (i & 31) replaced by v        (one case per value of i & 31)
    bs_set(W, q, k, ...): the bits of the words with word q replaced by a word whose bits are those of W[q] with bit k replaced
                          are the bits of W with bit 32 q + k replaced
    bt_set(n, L, i, v): the first n bits of L with bit i replaced are the first n bits of L, bit i replaced, for i < n

codegen/proofs/collections/coll_laws.py's `..._api_view_set` of the bit lists composes them (proofs/obj/coll_bits.bend). The word-level case split is the one of
bit_rw_go (coll_bits.bend): the five low bits of i are literal, the mask is then a literal word and its bits are the unit list of the position.

    python3 codegen/proofs/collections/bits_view.py            # write
    python3 codegen/proofs/collections/bits_view.py --check    # nonzero exit if the output is stale
"""
import sys as _sys
import pathlib as _pathlib
_sys.path.insert(0, str(_pathlib.Path(__file__).resolve().parents[3]))  # the repository root: `codegen` is importable when this file runs as a script
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / 'proofs/obj/bits_view.bend'

HEAD = '''import Base
import ../../src/obj.bend as O
import ../../src/merkle_fast.bend as M
import ../compact/found.bend as F
import ./u32bits.bend as UB
import ./bits_leaf.bend as BLf
import ./bitlist_pack.bend as BK
import ./bitlist_obj_light.bend as BO
import ./u32split.bend as USP
import ./words_spec.bend as WS
import ./words_rw.bend as WR

# GENERATED by codegen/proofs/collections/bits_view.py. Do not edit.
# The bits of a bit list after one bit is set (the runtime's bit_merge of the word, the storage written back): lemmas on the bits of a word and of
# a list of words. See codegen/proofs/collections/bits_view.py.

# the list with item k replaced (no change past its end): the spec's bit setter
def lset(xs: +List<Bool>, +k: Nat, v: Bool) -> +List<Bool>:
  match xs:
    case Nil{}: []
    case Con{h, t}:
      match k:
        case 0n: Con{v, t}
        case 1n+p: Con{h, lset(t, p, v)}

# the pointwise or, and and-not, of two lists (the shorter ends them)
def zor(xs: +List<Bool>, ys: +List<Bool>) -> +List<Bool>:
  match xs ys:
    case Con{x, xt} Con{y, yt}: Con{Bool.or(x, y), zor(xt, yt)}
    case _ _: []

def zan(xs: +List<Bool>, ys: +List<Bool>) -> +List<Bool>:
  match xs ys:
    case Con{x, xt} Con{y, yt}: Con{Bool.and(x, Bool.not(y)), zan(xt, yt)}
    case _ _: []

# n bits, all zero but bit k
def falses(+n: Nat) -> +List<Bool>:
  match n:
    case 0n: []
    case 1n+p: Con{False{}, falses(p)}

def unit(+n: Nat, +k: Nat) -> +List<Bool>:
  match n k:
    case 0n _: []
    case 1n+p 0n: Con{True{}, falses(p)}
    case 1n+p 1n+j: Con{False{}, unit(p, j)}

def len_(+xs: +List<Bool>) -> Nat: List.length(&2, Bool, xs)

# a word's bits are as many as the word's width
def wlen(+n: Nat, +w: Word(n)) -> {len_(BLf.word_bits(n, w)) == n : Nat}:
  match n w:
    case 0n WNil{}: {==}
    case 1n+p WCon{+x, +s}:
      %Equal.sym(Nat, len_(BLf.word_bits(p, s)), p, wlen(p, s)) : {1n+_ == 1n+p : Nat}
      {==}

def wlen_u(+x: U32) -> {len_(BLf.wbits(x)) == 32n : Nat}:
  match x:
    case U32{+w}: wlen(32n, w)

# or / and-not of the bits of two words are the bits of the or / and-not
def wbo(+n: Nat, +a: Word(n), +m: Word(n)) -> {BLf.word_bits(n, Word.or(n, a, m)) == zor(BLf.word_bits(n, a), BLf.word_bits(n, m)) : +List<Bool>}:
  match n a m:
    case 0n WNil{} WNil{}: {==}
    case 1n+p WCon{+x, +s} WCon{+y, +t}:
      %Equal.sym(+List<Bool>, BLf.word_bits(p, Word.or(p, s, t)), zor(BLf.word_bits(p, s), BLf.word_bits(p, t)), wbo(p, s, t)) :
        {Con{Bool.or(x, y), _} == Con{Bool.or(x, y), zor(BLf.word_bits(p, s), BLf.word_bits(p, t))} : +List<Bool>}
      {==}

def wba(+n: Nat, +a: Word(n), +m: Word(n)) -> {BLf.word_bits(n, Word.and(n, a, Word.not(n, m))) == zan(BLf.word_bits(n, a), BLf.word_bits(n, m)) : +List<Bool>}:
  match n a m:
    case 0n WNil{} WNil{}: {==}
    case 1n+p WCon{+x, +s} WCon{+y, +t}:
      %Equal.sym(+List<Bool>, BLf.word_bits(p, Word.and(p, s, Word.not(p, t))), zan(BLf.word_bits(p, s), BLf.word_bits(p, t)), wba(p, s, t)) :
        {Con{Bool.and(x, Bool.not(y)), _} == Con{Bool.and(x, Bool.not(y)), zan(BLf.word_bits(p, s), BLf.word_bits(p, t))} : +List<Bool>}
      {==}

# or-ing with no bit, and and-not-ing no bit, change nothing
def zor_f(+t: +List<Bool>) -> {zor(t, falses(len_(t))) == t : +List<Bool>}:
  match t:
    case Nil{}: {==}
    case Con{+h, +r}:
      %Equal.sym(Bool, Bool.or(h, False{}), h, UB.bor_false(h)) : {Con{_, zor(r, falses(len_(r)))} == Con{h, r} : +List<Bool>}
      %Equal.sym(+List<Bool>, zor(r, falses(len_(r))), r, zor_f(r)) : {Con{h, _} == Con{h, r} : +List<Bool>}
      {==}

def zan_f(+t: +List<Bool>) -> {zan(t, falses(len_(t))) == t : +List<Bool>}:
  match t:
    case Nil{}: {==}
    case Con{+h, +r}:
      %Equal.sym(Bool, Bool.and(h, True{}), h, UB.band_true(h)) : {Con{_, zan(r, falses(len_(r)))} == Con{h, r} : +List<Bool>}
      %Equal.sym(+List<Bool>, zan(r, falses(len_(r))), r, zan_f(r)) : {Con{h, _} == Con{h, r} : +List<Bool>}
      {==}

# or-ing a unit list sets that bit, and-not-ing it clears it
def zor_unit(+L: +List<Bool>, +k: Nat) -> {zor(L, unit(len_(L), k)) == lset(L, k, True{}) : +List<Bool>}:
  match L k:
    case Nil{} _: {==}
    case Con{+h, +t} 0n:
      %Equal.sym(Bool, Bool.or(h, True{}), True{}, UB.bor_true(h)) : {Con{_, zor(t, falses(len_(t)))} == Con{True{}, t} : +List<Bool>}
      %Equal.sym(+List<Bool>, zor(t, falses(len_(t))), t, zor_f(t)) : {Con{True{}, _} == Con{True{}, t} : +List<Bool>}
      {==}
    case Con{+h, +t} 1n+j:
      %Equal.sym(Bool, Bool.or(h, False{}), h, UB.bor_false(h)) : {Con{_, zor(t, unit(len_(t), j))} == Con{h, lset(t, j, True{})} : +List<Bool>}
      %Equal.sym(+List<Bool>, zor(t, unit(len_(t), j)), lset(t, j, True{}), zor_unit(t, j)) : {Con{h, _} == Con{h, lset(t, j, True{})} : +List<Bool>}
      {==}

def zan_unit(+L: +List<Bool>, +k: Nat) -> {zan(L, unit(len_(L), k)) == lset(L, k, False{}) : +List<Bool>}:
  match L k:
    case Nil{} _: {==}
    case Con{+h, +t} 0n:
      %Equal.sym(Bool, Bool.and(h, False{}), False{}, UB.band_false(h)) : {Con{_, zan(t, falses(len_(t)))} == Con{False{}, t} : +List<Bool>}
      %Equal.sym(+List<Bool>, zan(t, falses(len_(t))), t, zan_f(t)) : {Con{False{}, _} == Con{False{}, t} : +List<Bool>}
      {==}
    case Con{+h, +t} 1n+j:
      %Equal.sym(Bool, Bool.and(h, True{}), h, UB.band_true(h)) : {Con{_, zan(t, unit(len_(t), j))} == Con{h, lset(t, j, False{})} : +List<Bool>}
      %Equal.sym(+List<Bool>, zan(t, unit(len_(t), j)), lset(t, j, False{}), zan_unit(t, j)) : {Con{h, _} == Con{h, lset(t, j, False{})} : +List<Bool>}
      {==}

# the merged word: the bits of x with bit k replaced, when the mask's bits are the unit list of k
def wmerge(+v: Bool, +x: U32, +m: U32, +k: Nat, +hm: {BLf.wbits(m) == unit(32n, k) : +List<Bool>})
    -> {BLf.wbits(O.bit_merge(v, x, m)) == lset(BLf.wbits(x), k, v) : +List<Bool>}:
  match v x m:
    case True{} U32{+a} U32{+b}:
      %Equal.sym(+List<Bool>, BLf.word_bits(32n, Word.or(32n, a, b)), zor(BLf.word_bits(32n, a), BLf.word_bits(32n, b)), wbo(32n, a, b)) : {_ == lset(BLf.word_bits(32n, a), k, True{}) : +List<Bool>}
      %Equal.sym(+List<Bool>, BLf.word_bits(32n, b), unit(32n, k), hm) : {zor(BLf.word_bits(32n, a), _) == lset(BLf.word_bits(32n, a), k, True{}) : +List<Bool>}
      %Equal.sym(Nat, 32n, len_(BLf.word_bits(32n, a)), Equal.sym(Nat, len_(BLf.word_bits(32n, a)), 32n, wlen(32n, a))) : {zor(BLf.word_bits(32n, a), unit(_, k)) == lset(BLf.word_bits(32n, a), k, True{}) : +List<Bool>}
      zor_unit(BLf.word_bits(32n, a), k)
    case False{} U32{+a} U32{+b}:
      %Equal.sym(+List<Bool>, BLf.word_bits(32n, Word.and(32n, a, Word.not(32n, b))), zan(BLf.word_bits(32n, a), BLf.word_bits(32n, b)), wba(32n, a, b)) : {_ == lset(BLf.word_bits(32n, a), k, False{}) : +List<Bool>}
      %Equal.sym(+List<Bool>, BLf.word_bits(32n, b), unit(32n, k), hm) : {zan(BLf.word_bits(32n, a), _) == lset(BLf.word_bits(32n, a), k, False{}) : +List<Bool>}
      %Equal.sym(Nat, 32n, len_(BLf.word_bits(32n, a)), Equal.sym(Nat, len_(BLf.word_bits(32n, a)), 32n, wlen(32n, a))) : {zan(BLf.word_bits(32n, a), unit(_, k)) == lset(BLf.word_bits(32n, a), k, False{}) : +List<Bool>}
      zan_unit(BLf.word_bits(32n, a), k)

# ---- the bits of a list of words ----
# setting an item inside the first list, and past it
def lset_app_l(+L1: +List<Bool>, +L2: +List<Bool>, +k: Nat, +v: Bool, +hk: {Nat.is_lt(k, len_(L1)) == True{} : Bool})
    -> {lset(List.append(&2, Bool, L1, L2), k, v) == List.append(&2, Bool, lset(L1, k, v), L2) : +List<Bool>}:
  match L1 k:
    case Nil{} _: Empty.absurd({lset(List.append(&2, Bool, Nil{}, L2), k, v) == List.append(&2, Bool, lset(Nil{}, k, v), L2) : +List<Bool>}, F.nat__lt_zero_absurd(k, hk))
    case Con{+h, +t} 0n: {==}
    case Con{+h, +t} 1n+j:
      %Equal.sym(+List<Bool>, lset(List.append(&2, Bool, t, L2), j, v), List.append(&2, Bool, lset(t, j, v), L2), lset_app_l(t, L2, j, v, hk)) :
        {Con{h, _} == Con{h, List.append(&2, Bool, lset(t, j, v), L2)} : +List<Bool>}
      {==}

def lset_app_r(+L1: +List<Bool>, +L2: +List<Bool>, +j: Nat, +v: Bool)
    -> {lset(List.append(&2, Bool, L1, L2), Nat.add(len_(L1), j), v) == List.append(&2, Bool, L1, lset(L2, j, v)) : +List<Bool>}:
  match L1:
    case Nil{}: {==}
    case Con{+h, +t}:
      %Equal.sym(+List<Bool>, lset(List.append(&2, Bool, t, L2), Nat.add(len_(t), j), v), List.append(&2, Bool, t, lset(L2, j, v)), lset_app_r(t, L2, j, v)) :
        {Con{h, _} == Con{h, List.append(&2, Bool, t, lset(L2, j, v))} : +List<Bool>}
      {==}

# the same after a whole word: its bits are 32
def lset_app_w(+x: U32, +L2: +List<Bool>, +j: Nat, +v: Bool)
    -> {lset(List.append(&2, Bool, BLf.wbits(x), L2), Nat.add(32n, j), v) == List.append(&2, Bool, BLf.wbits(x), lset(L2, j, v)) : +List<Bool>}:
  %Equal.sym(Nat, 32n, len_(BLf.wbits(x)), Equal.sym(Nat, len_(BLf.wbits(x)), 32n, wlen_u(x))) : {lset(List.append(&2, Bool, BLf.wbits(x), L2), Nat.add(_, j), v) == List.append(&2, Bool, BLf.wbits(x), lset(L2, j, v)) : +List<Bool>}
  lset_app_r(BLf.wbits(x), L2, j, v)

# the bits of the words with word q replaced, when the new word's bits are the old word's with bit k replaced, are the old bits with bit 32 q + k replaced
def bs_set(+W: List<&2, U32>, +q: Nat, +w2: U32, +k: Nat, +v: Bool, +hk: {Nat.is_lt(k, 32n) == True{} : Bool}, +hq: {Nat.is_lt(q, F.spec_common__length(U32, W)) == True{} : Bool},
    +hw: {BLf.wbits(w2) == lset(BLf.wbits(WR.at(W, q)), k, v) : +List<Bool>})
    -> {BK.bitsof(F.spec_common__update(U32, W, q, w2)) == lset(BK.bitsof(W), Nat.add(WS.e32(q), k), v) : +List<Bool>}:
  match W q:
    case Nil{} _: Empty.absurd({BK.bitsof(F.spec_common__update(U32, Nil{}, q, w2)) == lset(BK.bitsof(Nil{}), Nat.add(WS.e32(q), k), v) : +List<Bool>}, F.nat__lt_zero_absurd(q, hq))
    case Con{+x, +r} 0n:
      %Equal.sym(+List<Bool>, BLf.wbits(w2), lset(BLf.wbits(x), k, v), hw) : {List.append(&2, Bool, _, BK.bitsof(r)) == lset(BK.bitsof(Con{x, r}), Nat.add(WS.e32(0n), k), v) : +List<Bool>}
      %Equal.sym(+List<Bool>, lset(List.append(&2, Bool, BLf.wbits(x), BK.bitsof(r)), k, v), List.append(&2, Bool, lset(BLf.wbits(x), k, v), BK.bitsof(r)),
          lset_app_l(BLf.wbits(x), BK.bitsof(r), k, v, F.logic__subst(Nat, z => {Nat.is_lt(k, z) == True{} : Bool}, 32n, len_(BLf.wbits(x)), Equal.sym(Nat, len_(BLf.wbits(x)), 32n, wlen_u(x)), hk))) :
        {List.append(&2, Bool, lset(BLf.wbits(x), k, v), BK.bitsof(r)) == _ : +List<Bool>}
      {==}
    case Con{+x, +r} 1n+p:
      %Equal.sym(+List<Bool>, BK.bitsof(F.spec_common__update(U32, r, p, w2)), lset(BK.bitsof(r), Nat.add(WS.e32(p), k), v), bs_set(r, p, w2, k, v, hk, hq, hw)) :
        {List.append(&2, Bool, BLf.wbits(x), _) == lset(BK.bitsof(Con{x, r}), Nat.add(WS.e32(1n+p), k), v) : +List<Bool>}
      %Equal.sym(+List<Bool>, lset(List.append(&2, Bool, BLf.wbits(x), BK.bitsof(r)), Nat.add(32n, Nat.add(WS.e32(p), k)), v), List.append(&2, Bool, BLf.wbits(x), lset(BK.bitsof(r), Nat.add(WS.e32(p), k), v)),
          lset_app_w(x, BK.bitsof(r), Nat.add(WS.e32(p), k), v)) :
        {List.append(&2, Bool, BLf.wbits(x), lset(BK.bitsof(r), Nat.add(WS.e32(p), k), v)) == _ : +List<Bool>}
      {==}

# the first n bits, with bit i < n replaced
def bt_set(+n: Nat, +L: +List<Bool>, +i: Nat, +v: Bool, +hi: {Nat.is_lt(i, n) == True{} : Bool})
    -> {BK.btk(n, lset(L, i, v)) == lset(BK.btk(n, L), i, v) : +List<Bool>}:
  match n L i:
    case 0n _ _: Empty.absurd({BK.btk(0n, lset(L, i, v)) == lset(BK.btk(0n, L), i, v) : +List<Bool>}, F.nat__lt_zero_absurd(i, hi))
    case 1n+p Nil{} _: {==}
    case 1n+p Con{+h, +t} 0n: {==}
    case 1n+p Con{+h, +t} 1n+j:
      %Equal.sym(+List<Bool>, BK.btk(p, lset(t, j, v)), lset(BK.btk(p, t), j, v), bt_set(p, t, j, v, hi)) : {Con{h, _} == Con{h, lset(BK.btk(p, t), j, v)} : +List<Bool>}
      {==}

# the bit list's bits, of a storage tree
def bview_thaw(+t: F.array__Tree<U32>, +n: U32) -> {BO.bview(O.Bits{F.array__thaw(U32, t), n}) == BK.btk(U32.to_nat(n), BK.bitsof(F.array__slots(U32, t))) : +List<Bool>}:
  %Equal.sym(F.array__Tree<U32>, F.array__freeze(U32, F.array__thaw(U32, t)), t, F.array__freeze_thaw(U32, t)) :
    {BK.btk(U32.to_nat(n), BK.bitsof(F.array__slots(U32, _))) == BK.btk(U32.to_nat(n), BK.bitsof(F.array__slots(U32, t))) : +List<Bool>}
  {==}
'''


def wpat(bits, tail='WNil{}'):
    s_ = tail
    for b in reversed(bits):
        s_ = 'WCon{%s, %s}' % (b, s_)
    return s_


def dispatcher():
    L = ['', '# the runtime\'s merge of bit i & 31 (mask 1 << (i & 31)): the bits of the word with that bit replaced; a case per value of the five low bits of i',
         'def wset_i(+x: U32, +i: U32, +v: Bool) -> {BLf.wbits(O.bit_merge(v, x, M.shl_by(1, U32.and(i, 31)))) == lset(BLf.wbits(x), U32.to_nat(U32.and(i, 31)), v) : +List<Bool>}:',
         '  match i:']
    for K in range(32):
        lits = ['True{}' if (K >> b) & 1 else 'False{}' for b in range(5)]
        L.append('    case U32{%s}:' % wpat(lits, '+r'))
        kk = 'U32{%s}' % wpat(lits, '_')
        L.append('      %%Equal.sym(Word(27n), Word.and(27n, r, Word.zero(27n)), Word.zero(27n), UB.wand_zero(27n, r)) : {BLf.wbits(O.bit_merge(v, x, M.shl_by(1, %s))) == lset(BLf.wbits(x), U32.to_nat(%s), v) : +List<Bool>}'
                 % (kk, kk))
        L.append('      wmerge(v, x, M.shl_by(1, U32{%s}), %dn, {==})' % (wpat(lits, 'Word.zero(27n)'), K))
    L.append('')
    L.append('# the bit position is below 32')
    L.append('def lt32(+i: U32) -> {Nat.is_lt(U32.to_nat(U32.and(i, 31)), 32n) == True{} : Bool}:')
    L.append('  match i:')
    for K in range(32):
        lits = ['True{}' if (K >> b) & 1 else 'False{}' for b in range(5)]
        L.append('    case U32{%s}:' % wpat(lits, '+r'))
        kk = 'U32{%s}' % wpat(lits, '_')
        L.append('      %%Equal.sym(Word(27n), Word.and(27n, r, Word.zero(27n)), Word.zero(27n), UB.wand_zero(27n, r)) : {Nat.is_lt(U32.to_nat(%s), 32n) == True{} : Bool}' % kk)
        L.append('      {==}')
    return '\n'.join(L) + '\n'


VIEW_SET = r"""
# the bits of the bit list after bit i is set: the bits before with bit i replaced (the runtime's merge, written back to word i >> 5)
def view_set(+d: Nat, +t: F.array__Tree<U32>, +n: U32, +i: U32, +q: Nat, +v: Bool, +pf: {F.array__perfect(U32, d, t) == True{} : Bool},
    +hg: {U32.is_lt(i, n) == True{} : Bool}, +hq: {U32.to_nat(U32.shrn(i, 5n)) == q : Nat}, +hk: {Nat.is_lt(q, F.spec_common__pow2(d)) == True{} : Bool})
    -> {BO.bview(O.Bits{F.array__thaw(U32, F.array__upd(U32, d, t, q, O.bit_merge(v, WR.at(F.array__slots(U32, t), q), M.shl_by(1, U32.and(i, 31))))), n}) == lset(BO.bview(O.Bits{F.array__thaw(U32, t), n}), U32.to_nat(i), v) : +List<Bool>}:
  +W = F.array__slots(U32, t)
  +hq1 = F.logic__subst(Nat, z => {Nat.is_lt(q, z) == True{} : Bool}, F.spec_common__pow2(d), F.spec_common__length(U32, W), Equal.sym(Nat, F.spec_common__length(U32, W), F.spec_common__pow2(d), F.array__slots_length(U32, d, t, pf)), hk)
  +k = U32.to_nat(U32.and(i, 31))
  +ha = Equal.trans(Nat, Nat.add(WS.e32(q), k), Nat.add(k, WS.e32(q)), U32.to_nat(i), F.nat__add_comm(WS.e32(q), k),
    Equal.trans(Nat, Nat.add(k, WS.e32(q)), Nat.add(k, Nat.double(Nat.double(Nat.double(Nat.double(Nat.double(U32.to_nat(U32.shrn(i, 5n)))))))), U32.to_nat(i),
      Equal.cong(Nat, Nat, z => Nat.add(k, Nat.double(Nat.double(Nat.double(Nat.double(Nat.double(z)))))), q, U32.to_nat(U32.shrn(i, 5n)), Equal.sym(Nat, U32.to_nat(U32.shrn(i, 5n)), q, hq)),
      Equal.sym(Nat, U32.to_nat(i), Nat.add(k, Nat.double(Nat.double(Nat.double(Nat.double(Nat.double(U32.to_nat(U32.shrn(i, 5n)))))))), USP.split5(i))))
  +hl = F.logic__subst(Bool, z => {z == True{} : Bool}, U32.is_lt(i, n), Nat.is_lt(U32.to_nat(i), U32.to_nat(n)), F.u32__is_lt_nat(i, n), hg)
  +hlt = F.logic__subst(Nat, z => {Nat.is_lt(z, U32.to_nat(n)) == True{} : Bool}, U32.to_nat(i), Nat.add(WS.e32(q), k), Equal.sym(Nat, Nat.add(WS.e32(q), k), U32.to_nat(i), ha), hl)
  Equal.trans(+List<Bool>, BO.bview(O.Bits{F.array__thaw(U32, F.array__upd(U32, d, t, q, O.bit_merge(v, WR.at(W, q), M.shl_by(1, U32.and(i, 31))))), n}),
    BK.btk(U32.to_nat(n), lset(BK.bitsof(W), Nat.add(WS.e32(q), k), v)), lset(BO.bview(O.Bits{F.array__thaw(U32, t), n}), U32.to_nat(i), v),
    Equal.trans(+List<Bool>, BO.bview(O.Bits{F.array__thaw(U32, F.array__upd(U32, d, t, q, O.bit_merge(v, WR.at(W, q), M.shl_by(1, U32.and(i, 31))))), n}),
      BK.btk(U32.to_nat(n), BK.bitsof(F.spec_common__update(U32, W, q, O.bit_merge(v, WR.at(W, q), M.shl_by(1, U32.and(i, 31)))))), BK.btk(U32.to_nat(n), lset(BK.bitsof(W), Nat.add(WS.e32(q), k), v)),
      Equal.trans(+List<Bool>, BO.bview(O.Bits{F.array__thaw(U32, F.array__upd(U32, d, t, q, O.bit_merge(v, WR.at(W, q), M.shl_by(1, U32.and(i, 31))))), n}),
        BK.btk(U32.to_nat(n), BK.bitsof(F.array__slots(U32, F.array__upd(U32, d, t, q, O.bit_merge(v, WR.at(W, q), M.shl_by(1, U32.and(i, 31))))))),
        BK.btk(U32.to_nat(n), BK.bitsof(F.spec_common__update(U32, W, q, O.bit_merge(v, WR.at(W, q), M.shl_by(1, U32.and(i, 31)))))),
        bview_thaw(F.array__upd(U32, d, t, q, O.bit_merge(v, WR.at(W, q), M.shl_by(1, U32.and(i, 31)))), n),
        Equal.cong(List<&2, U32>, +List<Bool>, z => BK.btk(U32.to_nat(n), BK.bitsof(z)), F.array__slots(U32, F.array__upd(U32, d, t, q, O.bit_merge(v, WR.at(W, q), M.shl_by(1, U32.and(i, 31))))),
          F.spec_common__update(U32, W, q, O.bit_merge(v, WR.at(W, q), M.shl_by(1, U32.and(i, 31)))), F.array__upd_slots(U32, d, t, q, O.bit_merge(v, WR.at(W, q), M.shl_by(1, U32.and(i, 31))), hk, pf))),
      Equal.cong(+List<Bool>, +List<Bool>, z => BK.btk(U32.to_nat(n), z), BK.bitsof(F.spec_common__update(U32, W, q, O.bit_merge(v, WR.at(W, q), M.shl_by(1, U32.and(i, 31))))), lset(BK.bitsof(W), Nat.add(WS.e32(q), k), v),
        bs_set(W, q, O.bit_merge(v, WR.at(W, q), M.shl_by(1, U32.and(i, 31))), k, v, lt32(i), hq1, wset_i(WR.at(W, q), i, v)))),
    Equal.trans(+List<Bool>, BK.btk(U32.to_nat(n), lset(BK.bitsof(W), Nat.add(WS.e32(q), k), v)), lset(BK.btk(U32.to_nat(n), BK.bitsof(W)), Nat.add(WS.e32(q), k), v), lset(BO.bview(O.Bits{F.array__thaw(U32, t), n}), U32.to_nat(i), v),
      bt_set(U32.to_nat(n), BK.bitsof(W), Nat.add(WS.e32(q), k), v, hlt),
      Equal.trans(+List<Bool>, lset(BK.btk(U32.to_nat(n), BK.bitsof(W)), Nat.add(WS.e32(q), k), v), lset(BK.btk(U32.to_nat(n), BK.bitsof(W)), U32.to_nat(i), v), lset(BO.bview(O.Bits{F.array__thaw(U32, t), n}), U32.to_nat(i), v),
        Equal.cong(Nat, +List<Bool>, z => lset(BK.btk(U32.to_nat(n), BK.bitsof(W)), z, v), Nat.add(WS.e32(q), k), U32.to_nat(i), ha),
        Equal.sym(+List<Bool>, lset(BO.bview(O.Bits{F.array__thaw(U32, t), n}), U32.to_nat(i), v), lset(BK.btk(U32.to_nat(n), BK.bitsof(W)), U32.to_nat(i), v),
          Equal.cong(+List<Bool>, +List<Bool>, z => lset(z, U32.to_nat(i), v), BO.bview(O.Bits{F.array__thaw(U32, t), n}), BK.btk(U32.to_nat(n), BK.bitsof(W)), bview_thaw(t, n))))))
"""


def text():
    return HEAD + dispatcher() + VIEW_SET


def main():
    t = text()
    if '--check' in sys.argv:
        if not OUT.exists() or OUT.read_text() != t:
            print('stale: bits_view.bend')
            sys.exit(1)
        print('bits_view: up to date')
        return
    if not OUT.exists() or OUT.read_text() != t:
        OUT.write_text(t)
    print('bits_view: proofs/obj/bits_view.bend')


if __name__ == '__main__':
    main()
