#!/usr/bin/env python3
"""Setter laws composed with the root and encode bridges: e2e/<Name>_e2e_set_generated.bend.

proofs/obj/prep_setters.bend (codegen/proofs/collections/rep_laws.py) proves, for every field setter set_f of the
Fulu containers listed there, that it keeps the representation invariant: from rep_X(o, s) (and,
for a field with its own invariant, that invariant of the new value v) follows
rep_X(set_f(o, v), s). rep_X(o, Spec.X()) is exactly the premise of X's root bridge
(<Name>_e2e_root: the object's root is API.hash_tree_root of its view), and for a few names the
only premise of the encode bridge (<Name>_e2e_encode). So each setter law composes with those
bridges into a checked statement about an object mutated through the API:

    <Name>_e2e_set_<f>_root(h, o, v, r[, rv]):
        root(set_f(o, v)) == API.hash_tree_root(Spec.X(), view(set_f(o, v)))
    <Name>_e2e_set_<f>_encode(o, v, r[, rv])       (when the encode bridge's only premise is rep)
        Some(encode(set_f(o, v))) == API.serialize(Spec.X(), view(set_f(o, v)))

under rep_X(o, Spec.X()) (and rv). Each proof is the bridge applied to set_f(o, v) and the setter
law. A composition is emitted exactly when the bridge's premises are the object and rep (the
root bridge of every container here; the encode bridge of the containers without storage
premises); an encode bridge with storage premises (hs*, hc*, ...) needs them of set_f(o, v), which
no setter law states, so none is emitted for it (docs/PREMISES.md).

    python3 codegen/proofs/collections/e2e_setters.py            # write
    python3 codegen/proofs/collections/e2e_setters.py --check    # nonzero exit if any output is stale or orphaned
"""
import sys as _sys
import pathlib as _pathlib
_sys.path.insert(0, str(_pathlib.Path(__file__).resolve().parents[3]))  # the repository root: `codegen` is importable when this file runs as a script
import json
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
E2E = ROOT / 'e2e'
LAWS = ROOT / 'proofs/obj/prep_setters.bend'
TYPES = ROOT / 'types'
HEADER = '# GENERATED by codegen/proofs/collections/e2e_setters.py. Do not edit.'
LAW = re.compile(r'^law (\w+)_set_(\w+)_rep:\n((?:  .*\n)+)', re.M)
IMPORT = re.compile(r'^import (\S+) as (\w+)\s*$', re.M)
VAR_O = re.compile(r'(?<![\w.])o(?![\w.])')
VAR_S = re.compile(r'(?<![\w.])s(?![\w.])')


def imports(path):
    """{alias: root-relative path} of a .bend file"""
    out = {}
    for m in IMPORT.finditer(path.read_text()):
        out[m.group(2)] = os.path.normpath(os.path.join(os.path.relpath(path.parent, ROOT), m.group(1)))
    return out


def split_params(s):
    out, depth, cur = [], 0, ''
    for ch in s:
        if ch in '({[<':
            depth += 1
        elif ch in ')}]>':
            depth -= 1
        if ch == ',' and depth == 0:
            out.append(cur.strip())
            cur = ''
            continue
        cur += ch
    if cur.strip():
        out.append(cur.strip())
    return out


def signature(path, name):
    """(params, conclusion) of the one-line bridge `def name(params) -> {conclusion}:`"""
    lines = path.read_text().split('\n')
    start = [i for i, l in enumerate(lines) if l.startswith('def %s(' % name)]
    if len(start) != 1:
        sys.exit('e2e_setters: %s: def %s not found once' % (path.name, name))
    sig = []
    for l in lines[start[0]:]:
        sig.append(l.strip())
        if l.rstrip().endswith(':'):
            break
    m = re.match(r'def %s\((.*)\)\s*-> (\{.*\}):$' % re.escape(name), ' '.join(sig), re.S)
    return split_params(m.group(1)), m.group(2)


def bridge_file(man, name, law):
    for f, es in man['files'].items():
        for e in es:
            if law in e['laws']:
                return E2E / f
    return None


LAW_FILES = [ROOT / 'proofs/obj/prep_setters.bend', ROOT / 'proofs/obj/prep_setters_g1.bend', ROOT / 'proofs/obj/prep_setters_g2.bend']


def setter_laws():
    """[(law file, {container: {field: (binders [(mode, name, type)], setter expression, rep module path)}})]"""
    out = []
    for lf in LAW_FILES:
        li = imports(lf)
        d = {}
        for m in LAW.finditer(lf.read_text()):
            x, f, body = m.group(1), m.group(2), m.group(3)
            lines = [l.strip() for l in body.split('\n') if l.strip()]
            binders = []
            for l in lines[:-1]:
                b = re.match(r'for ([+-]?)(\w+): (.*)$', l)
                binders.append((b.group(1), b.group(2), b.group(3)))
            concl = lines[-1]
            mm = re.match(r'(\w+)\.rep_%s\((.*), s\)$' % x, concl)
            assert mm, concl
            names = [b[1] for b in binders]
            assert names[:4] == ['o', 's', 'v', 'r'] and names[4:] in ([], ['rv']), (x, f, names)
            d.setdefault(x, {})[f] = (binders, mm.group(2), li[mm.group(1)])
        out.append((lf, d))
    return out


def tree(e):
    """a rp invariant's leaf expression as a tree of DK.P2 pairs"""
    m = re.match(r'(\w+\.)?P2\(', e)
    if m and e.endswith(')'):
        a, b = split_params(e[m.end():-1])
        return ('P2', tree(a), tree(b))
    return ('L', e)


def destructure(t, name, lines, ind, rv_for):
    """lines that take proof `name` of tree t apart; returns the expression rebuilding it with the leaf
    rv_for(leaf) (None: keep) replaced"""
    if t[0] == 'L':
        r = rv_for(t[1])
        return r if r else name
    a, b = name + 'a', name + 'b'
    lines.append('%s(+%s, +%s) = %s' % (ind, a, b, name))
    return '(%s, %s)' % (destructure(t[1], a, lines, ind, rv_for), destructure(t[2], b, lines, ind, rv_for))


BUILTIN = {'U32', 'Bool', 'Nat', 'List', 'Maybe', 'Array', 'Pair', 'Equal', 'Base', 'Word', 'Some', 'None', 'True', 'False'}


def qualify(text, mod_imps, mod_alias, mod_defs, ren):
    """text of a module requalified for the output: A.x with A an import of the module -> ren[A].x,
    a bare name the module defines -> mod_alias.name"""
    def sub(m):
        a, rest = m.group(1), m.group(2)
        if rest is not None:
            return ren.get(a, a) + '.' + rest
        return mod_alias + '.' + a if a in mod_defs else a
    return re.sub(r'(?<![\w.])([A-Za-z_]\w*)(?:\.([A-Za-z_]\w*))?', lambda m: sub(m) if (m.group(2) is not None and m.group(1) in mod_imps) or (m.group(2) is None and m.group(1) in mod_defs) else m.group(0), text)


def items(expr):
    """the elements of S.Sequence{S.Items{e0, S.Items{e1, .. S.EmptyItems{}}}}"""
    assert expr.startswith('S.Sequence{') and expr.endswith('}'), expr[:80]
    cur = expr[len('S.Sequence{'):-1]
    out = []
    while cur != 'S.EmptyItems{}':
        assert cur.startswith('S.Items{') and cur.endswith('}'), cur[:80]
        h, t = split_params(cur[len('S.Items{'):-1])
        out.append(h)
        cur = t
    return out


def view_block(path, fn):
    """(block lines, leaf line index, leaf expression) of `def fn(o: ...)` in path"""
    lines = path.read_text().split('\n')
    i = [k for k, l in enumerate(lines) if l.startswith('def %s(o: ' % fn)]
    assert len(i) == 1, (path, fn)
    j = i[0] + 1
    while j < len(lines) and lines[j].startswith(' '):
        j += 1
    blk = lines[i[0]:j]
    leaf = max(k for k, l in enumerate(blk) if 'S.Sequence{' in l)
    return blk, leaf, blk[leaf][blk[leaf].index('S.Sequence{'):].strip()


def fields_of(deftext, x):
    """[field name] of the record type x in order, the group records (x_g<k>) expanded"""
    m = re.search(r'^type %s is \w+:\n  %s\{(.*)\}$' % (x, x), deftext, re.M)
    out = []
    for fd in split_params(m.group(1)):
        n, t = [a.strip() for a in fd.split(':', 1)]
        if re.fullmatch(r'%s_g\d+' % x, t):
            out += fields_of(deftext, t)
        else:
            out.append(n)
    return out


def containers():
    """[(name, type, def file)]: the names whose def file has field setters for its own record type"""
    out = []
    for f in sorted(TYPES.glob('*_def_generated.bend')):
        t = f.read_text()
        for x in sorted(set(re.findall(r'^def (\w+)_set_\w+\(o: (\w+), ', t, re.M))):
            if x[0] == x[1] and not re.search(r'_g\d+$', x[0]) and re.search(r'^type %s is ' % x[0], t, re.M):
                out.append((f.name[:-len('_def_generated.bend')], x[0], f))
    return out


def merge(imps, new, suffix):
    """add the imports `new` to `imps`; an alias taken by another path is renamed alias_<suffix>.
    Returns the renaming to apply to the text written against `new`."""
    ren = {}
    for a, p in new.items():
        have = [k for k, q in imps.items() if q == p]
        if have:
            if have[0] != a:
                ren[a] = have[0]
            continue
        b = a
        if b in imps and imps[b] != p:
            b = a + '_' + suffix
            assert b not in imps or imps[b] == p, (a, p)
        imps[b] = p
        if b != a:
            ren[a] = b
    return ren


def rename(text, ren):
    for a, b in ren.items():
        text = re.sub(r'(?<![\w.])%s\.' % re.escape(a), b + '.', text)
    return text


def rel(p):
    r = os.path.relpath(ROOT / p, E2E)
    return r if r.startswith('.') else './' + r


def build(n, x, deff, laws, man):
    imps = {'VS': 'proofs/obj/value_set.bend'}
    dren = merge(imps, imports(deff), 'd')
    d_alias = [a for a, q in imps.items() if q == os.path.relpath(deff, ROOT)]
    if not d_alias:
        imps[n + '_d'] = os.path.relpath(deff, ROOT)
        d_alias = [n + '_d']
    DA = d_alias[0]
    deftext = deff.read_text()
    ddefs = set(re.findall(r'^(?:def|type) (\w+)', deftext, re.M))
    fields = fields_of(deftext, x)
    rb = bridge_file(man, n, n + '_e2e_root')
    if rb is None:
        return None, 0
    params, concl = signature(rb, n + '_e2e_root')
    rmap_r = merge(imps, imports(rb), 'r')
    concl = rename(concl, rmap_r)
    imps['R'] = os.path.relpath(rb, ROOT)
    m = re.search(r'API\.hash_tree_root\(((?:\w+\.)?\w+\(\)), (\w+)\.(v_\w+)\(o\)\)', concl)
    spec, va, vfn = m.groups()
    vpath = ROOT / imps[va]
    vimps = imports(vpath)
    vren = merge(imps, vimps, 'v')
    vdefs = set(re.findall(r'^(?:def|type) (\w+)', vpath.read_text(), re.M))
    blk, leaf, expr = view_block(vpath, vfn)
    els = items(expr)
    assert len(els) == len(fields), (n, len(els), len(fields))
    params = [rename(p, rmap_r) for p in params]
    view = lambda t: '%s.%s(%s)' % (va, vfn, t)
    # the setter-keeps-rep laws: the file whose rep module is the one the root bridge's rep premise names
    lw, lren = {}, {}
    rep_p = [p for p in params if p.startswith('+rep:')]
    if rep_p:
        rpath = imps[re.match(r'\+rep: (\w+)\.rep_', rep_p[0]).group(1)]
        for lf, ls in laws:
            if x in ls and all(v[2] == rpath for v in ls[x].values()):
                lw = ls[x]
                imps['PS'] = os.path.relpath(lf, ROOT)
                lren = merge(imps, imports(lf), 'l')
                break
    # an rp_X premise (a Data container whose fields carry range invariants): its definition
    rp_p = [p for p in params if p.startswith('+rp:')]
    rp = None
    if rp_p:
        ra, rfn = re.match(r'\+rp: (\w+)\.(rp_\w+)\(o\)$', rp_p[0]).groups()
        rpath = ROOT / imps[ra]
        rimps, rdefs = imports(rpath), set(re.findall(r'^(?:def|type) (\w+)', rpath.read_text(), re.M))
        rren = merge(imps, rimps, 'p')
        lines = rpath.read_text().split('\n')
        i0 = [k for k, l in enumerate(lines) if l.startswith('def %s(o: ' % rfn)][0]
        j = i0 + 1
        while j < len(lines) and lines[j].startswith(' '):
            j += 1
        rblk = [qualify(l, rimps, ra, rdefs, rren) for l in lines[i0 + 1:j]]
        cut = rblk[-1].index('}: ') + 3
        rp = {'call': lambda t: '%s.%s(%s)' % (ra, rfn, t), 'head': rblk[:-1], 'case': rblk[-1][:cut - 1],
              'tree': tree(rblk[-1][cut:].strip()), 'ind': ' ' * (len(rblk[-1]) - len(rblk[-1].lstrip()) + 2)}
    # the proof skeleton: the view's own matches on o, the leaf closed by computation
    skel = [qualify(l, vimps, va, vdefs, vren) for l in blk[1:leaf]]
    skel.append(blk[leaf][:blk[leaf].index('S.Sequence{')] + '{==}')
    defs, counts = [], {'view': 0, 'root': 0, 'encode': 0, 'checked': 0}
    ob = [p for p in params if re.match(r'[+-]?o:', p)][0]
    otype = ob.split(':', 1)[1].strip()
    omode = '+' if ob.startswith('+') else ''
    kinds = [('root', params, concl, 'R')]
    eb = bridge_file(man, n, n + '_e2e_encode')
    if eb is not None:
        ep, ec = signature(eb, n + '_e2e_encode')
        imps['N'] = os.path.relpath(eb, ROOT)
        rmap_e = merge(imps, imports(eb), 'e')
        kinds.append(('encode', [rename(p, rmap_e) for p in ep], rename(ec, rmap_e), 'N'))

    def rp_lemma(f, k, checked, g, wt):
        """N_set_f_rp: the setter keeps rp_X (a checked setter: given its guard and rp of the new value)"""
        lines = []
        leaves = []
        def rv_for(leaf):
            if re.search(r'(?<![\w.])x%d(?![\w.])' % k, leaf):
                leaves.append(leaf)
                return 'rv'
            return None
        rebuilt = destructure(rp['tree'], 'r', lines, rp['ind'], rv_for)
        if leaves and not checked:
            return None    # a plain setter of a field with its own invariant: not in the generated API
        name = '%s_set_%s_rp' % (n, f)
        setx = '%s.%s_set_%s(o, w)' % (DA, x, f)
        body = rp['head'] + [rp['case']] + lines + [rp['ind'] + rebuilt]
        if checked:
            assert len(leaves) == 1, (n, f, leaves)
            rvt = re.sub(r'(?<![\w.])x%d(?![\w.])' % k, 'w', leaves[0])
            go = '%s.%s_set_%s_go(o, w)' % (DA, x, f)
            defs.append('def %s_go(+o: %s, +w: %s, +r: %s, +rv: %s)\n    -> %s:\n%s' % (
                name, otype, wt, rp['call']('o'), rvt, rp['call'](go), '\n'.join(body)))
            defs.append('def %s(+o: %s, +w: %s, +hg: {%s == True{} : Bool}, +r: %s, +rv: %s)\n    -> %s:\n  %%Equal.sym(Bool, %s, True{}, hg) : %s\n  %s_go(o, w, r, rv)' % (
                name, otype, wt, g, rp['call']('o'), rvt, rp['call']('Pair.fst(%s, Bool, %s)' % (otype, setx)), g,
                rp['call']('Pair.fst(%s, Bool, %s.%s_put_%s(_, o, w))' % (otype, DA, x, f)), name))
        else:
            defs.append('def %s(+o: %s, +w: %s, +r: %s)\n    -> %s:\n%s' % (name, otype, wt, rp['call']('o'), rp['call'](setx), '\n'.join(body)))
        return name

    for k, f in enumerate(fields):
        el = els[k]
        vs = set(re.findall(r'(?<![\w.])x(\d+)(?![\w.])', el))
        assert vs == {str(k)}, (n, f, el)
        fv = qualify(re.sub(r'(?<![\w.])x%d(?![\w.])' % k, 'w', el), vimps, va, vdefs, vren)
        fs = 'VS.field_set(%s, %dn, %s)' % (view('o'), k, fv)
        vl = '%s_e2e_set_%s_view' % (n, f)
        sm = re.search(r'^def %s_set_%s\(o: %s, (\+?)v: (.+?)\) -> %s:' % (x, f, x, x), deftext, re.M)
        checked = None
        if not sm:   # a range-checked setter: X_set_f(o, v) = X_put_f(guard, o, v) -> X & Bool
            sm = re.search(r'^def %s_set_%s\(o: %s, (\+?)v: (.+?)\) -> %s & Bool: %s_put_%s\((.*), o, v\)$' % (x, f, x, x, x, f), deftext, re.M)
            assert sm, (n, f)
            checked = re.sub(r'(?<![\w.])v(?![\w.])', 'w', sm.group(3))
        wm = '+' if checked else sm.group(1)
        wt = qualify(sm.group(2), imports(deff), DA, ddefs, dren)
        setx = '%s.%s_set_%s(o, w)' % (DA, x, f)
        if checked:
            g = checked
            obj_after = 'Pair.fst(%s, Bool, %s)' % (otype, setx)
            put = lambda b: '%s.%s_put_%s(%s, o, w)' % (DA, x, f, b)
            defs.append('def %s_set_%s_flag_case(b: Bool, -o: %s, -w: %s) -> {Pair.snd(%s, Bool, %s) == b : Bool}:\n  match b:\n    case True{}: {==}\n    case False{}: {==}'
                        % (n, f, otype, wt, otype, put('b')))
            defs.append('def %s_e2e_set_%s_flag(-o: %s, +w: %s) -> {Pair.snd(%s, Bool, %s) == %s : Bool}:\n  %s_set_%s_flag_case(%s, o, w)'
                        % (n, f, otype, wt, otype, setx, g, n, f, g))
            defs.append('def %s_e2e_set_%s_rejected(-o: %s, +w: %s, +hg: {%s == False{} : Bool}) -> {%s == (o, False{}) : %s & Bool}:\n  %%Equal.sym(Bool, %s, False{}, hg) : {%s == (o, False{}) : %s & Bool}\n  {==}'
                        % (n, f, otype, wt, g, setx, otype, g, put('_'), otype))
            go = '%s.%s_set_%s_go(o, w)' % (DA, x, f)
            assert re.search(r'^def %s_set_%s_go\(o: %s, \+v: ' % (x, f, x), deftext, re.M), (n, f)
            defs.append('def %s_go(%so: %s, +w: %s)\n    -> {%s == %s : S.Value}:\n%s' % (
                vl, omode, otype, wt, view(go), fs, '\n'.join(skel)))
            defs.append('def %s(%so: %s, +w: %s, +hg: {%s == True{} : Bool})\n    -> {%s == %s : S.Value}:\n  %%Equal.sym(Bool, %s, True{}, hg) : {%s == %s : S.Value}\n  %s_go(o, w)' % (
                vl, omode, otype, wt, g, view(obj_after), fs, g, view('Pair.fst(%s, Bool, %s)' % (otype, put('_'))), fs, vl))
            counts['checked'] += 3
        else:
            obj_after = setx
            defs.append('def %s(%so: %s, %sw: %s)\n    -> {%s == %s : S.Value}:\n%s' % (
                vl, omode, otype, wm, wt, view(setx), fs, '\n'.join(skel)))
        counts['view'] += 1
        rpl = rp_lemma(f, k, bool(checked), checked, wt) if rp else None
        for kind, ps, cc, al in kinds:
            pn = [re.match(r'[+-]?(\w+)', p).group(1) for p in ps]
            law = lw.get(f)
            if pn in (['h', 'o'], ['o']) and not checked:
                extra, rargs = [], ''
            elif pn in (['h', 'o', 'rep'], ['o', 'rep']) and law and not checked:
                binders, lsetx, _ = law
                extra = []
                for mode, b, t in binders[3:]:
                    extra.append('%s%s: %s' % (mode, b, re.sub(r'(?<![\w.])v(?![\w.])', 'w', rename(VAR_S.sub(spec, t), lren))))
                largs = ', '.join(spec if b[1] == 's' else ('w' if b[1] == 'v' else b[1]) for b in binders)
                rargs = ', PS.%s_set_%s_rep(%s)' % (x, f, largs)
            elif pn in (['h', 'o', 'rep'], ['o', 'rep']) and checked and lw.get(f + '_go'):
                binders, lsetx, _ = lw[f + '_go']
                hyps = [(b, re.sub(r'(?<![\w.])v(?![\w.])', 'w', rename(VAR_S.sub(spec, t), lren))) for mode, b, t in binders[3:]]
                extra = ['+hg: {%s == True{} : Bool}' % checked] + ['+%s: %s' % h for h in hyps]
                rname = '%s_set_%s_rep' % (n, f)
                if not any(d.startswith('def %s(' % rname) for d in defs):
                    reps = rename(VAR_S.sub(spec, binders[3][2]), lren)   # REP(o, SPEC)
                    tgt = lambda e: re.sub(r'\(o, ', '(%s, ' % e, reps, count=1)
                    largs = ', '.join(spec if b[1] == 's' else ('w' if b[1] == 'v' else b[1]) for b in binders)
                    defs.append('def %s(-o: %s, +w: %s, %s)\n    -> %s:\n  %%Equal.sym(Bool, %s, True{}, hg) : %s\n  PS.%s_set_%s_go_rep(%s)' % (
                        rname, otype, wt, ', '.join(extra), tgt('Pair.fst(%s, Bool, %s)' % (otype, setx)), checked,
                        tgt('Pair.fst(%s, Bool, %s.%s_put_%s(_, o, w))' % (otype, DA, x, f)), x, f, largs))
                rargs = ', %s(o, w, hg, %s)' % (rname, ', '.join(h[0] for h in hyps))
            elif pn in (['h', 'o', 'rp'], ['o', 'rp']) and rpl:
                rpt = [p for p in ps if p.startswith('+rp:')][0].split(':', 1)[1].strip()
                assert rpt == rp['call']('o'), (n, rpt)
                if checked:
                    rvt = re.search(r'\+rv: (.*)\)$', [d for d in defs if d.startswith('def %s(' % rpl)][0].split('\n')[0]).group(1)
                    extra = ['+hg: {%s == True{} : Bool}' % checked, '+rp: %s' % rpt, '+rv: %s' % rvt]
                    rargs = ', %s(o, w, hg, rp, rv)' % rpl
                else:
                    extra = ['+rp: %s' % rpt]
                    rargs = ', %s(o, w, rp)' % rpl
            else:
                continue
            lhs, rhs = cc[1:-1].split(' == API.', 1)
            api, ty = rhs.rsplit(' : ', 1)
            api = 'API.' + api
            want = '%s(%s, %s)' % (api.split('(', 1)[0], spec, view('o'))
            assert api == want, (api, want)
            L = VAR_O.sub(lambda _: obj_after, lhs)
            fn = api.split('(', 1)[0]
            head = ['h: B.Buf'] if 'h' in pn else []
            sig = head + ['%so: %s' % (omode, otype), '%sw: %s' % (wm, wt)] + extra
            call = '%s.%s_e2e_%s(%s%s%s)' % (al, n, kind, 'h, ' if 'h' in pn else '', obj_after, rargs)
            vlc = '%s(o, w%s)' % (vl, ', hg' if checked else '')
            defs.append('def %s_e2e_set_%s_%s(%s)\n    -> {%s == %s(%s, %s) : %s}:\n  %%%s : {%s == %s(%s, _) : %s}\n  %s' % (
                n, f, kind, ', '.join(sig), L, fn, spec, fs, ty, vlc, L, fn, spec, ty, call))
            counts[kind] += 1
    body = '\n\n'.join(defs)
    used = [a for a in imps if re.search(r'(?<![\w.])%s\.' % re.escape(a), body)]
    lines = ['import Base'] + ['import %s as %s' % (rel(imps[a]), a) for a in sorted(used)]
    lines += ['', HEADER,
              '# %s: for each field setter set_f, the spec-value law view(set_f(o, w)) == field_set(view(o), k, view_f(w))' % n,
              '# (proofs/obj/value_set.bend: the value with field k replaced), and that law composed with the root',
              '# bridge (and the encode bridge where it applies): the root (encoding) of set_f(o, w) is the spec',
              '# root (encoding) of the value with field f replaced. Under rep, through the setter law of',
              '# proofs/obj/prep_setters.bend (set_f keeps rep), when the bridge has that premise.', '']
    return '\n'.join(lines) + body + '\n', counts


def outputs():
    man = json.loads((E2E / 'manifest.json').read_text())
    laws = setter_laws()
    outs, tot = {}, {'view': 0, 'root': 0, 'encode': 0, 'checked': 0}
    for n, x, deff in containers():
        t, c = build(n, x, deff, laws, man)
        if t:
            outs[E2E / ('%s_e2e_set_generated.bend' % n)] = t
            for k in tot:
                tot[k] += c[k]
    return outs, tot


def main():
    check = '--check' in sys.argv
    outs, tot = outputs()
    stale = []
    for p, t in outs.items():
        if not p.exists() or p.read_text() != t:
            stale.append(p.name)
            if not check:
                p.write_text(t)
    have = {p.name for p in E2E.glob('*_e2e_set_generated.bend')}
    for o in sorted(have - {p.name for p in outs}):
        if check:
            stale.append(o + ' (orphan)')
        else:
            (E2E / o).unlink()
    ndefs = sum(t.count('\ndef ') for t in outs.values())
    if check:
        if stale:
            print('stale: ' + ', '.join(stale))
            sys.exit(1)
        print('e2e_setters: %d files up to date (%d view, %d root, %d encode statements)' % (len(outs), tot['view'], tot['root'], tot['encode']))
    else:
        print('e2e_setters: wrote %d of %d files (%d view, %d root, %d encode statements)' % (len(stale), len(outs), tot['view'], tot['root'], tot['encode']))


if __name__ == '__main__':
    main()
