#!/usr/bin/env python3
"""proofs/obj/encset_b_<list>.bend: the encode of a byte list or the list of uint8 after one byte is written.

The encode bridge (proofs/obj/encx_<list>.bend) says: for the window MW{dw, T, N} with OKT(dw, T, N) the spec encode of VAL = W.VALw(T, 0, N) is the bytes ENC (encx_spec).
Setting byte i writes the word q = i >> 2 with the byte merged in: T2 = array__upd(dw, T, q, O.merge_word(at(slots T, q), v, i & 3, 1)) (view_bytes.bend's view_set / view_set_u8).
This file proves, symbolically:

    <c>_okt_set            OKT(dw, T, N) and i < N give OKT(dw, T2, N): the perfect tree, the room and the limit are unchanged; the zero tail of the word N >> 2 is the old
                           one when q != N >> 2 (the slot is not written), and when q = N >> 2 the offset i & 3 is below the r = N & 3 bytes in use, so
                           tz_merge.bend's tz_merge keeps it
    <c>_vall_set           VAL(MW{dw, T2, N}) == bytes_set / field_set of VAL(MW{dw, T, N}) at i (the window's bytes are the bytes of the slots: wv_bt / vv_bt; then view_bytes.bend)
    <c>_written            the written mirror's object is words_setw of the old one (words_rw.bend's setw_thaw)
    <c>_api_encode_set     the composed statement: the spec encode of the set value is ENC of the written mirror (encx_spec on MW{dw, T2, N})

    python3 codegen/proofs/collections/encset_b.py            # write
    python3 codegen/proofs/collections/encset_b.py --check    # nonzero exit if the output is stale
"""
import sys as _sys
import pathlib as _pathlib
_sys.path.insert(0, str(_pathlib.Path(__file__).resolve().parents[3]))  # the repository root: `codegen` is importable when this file runs as a script
import re
import sys

from codegen.core.paths import ROOT  # noqa: E402
from codegen.proofs.collections import encset_w as EW  # noqa: E402

OBJ = ROOT / 'proofs/obj'
BASE = OBJ / 'encset_b_base.bend'
LISTS = (('bl32', 'b'), ('bl256', 'b'), ('l1099511627776_u8', 'u8'))

BASE_TEXT = '''import Base
import ../../types/schema.bend as S
import ../../types/primitive.bend as P
import ../compact/found.bend as F
import ../compact/arith.bend as A
import ../../src/obj.bend as O
import ./vspec.bend as VS
import ./spec_fixed.bend as FX
import ./words_spec.bend as WS
import ./words_obj_light.bend as WO
import ./packed_bytes_light.bend as PB
import ./vbitenc.bend as VBT
import ./encset_w_base.bend as EB

# GENERATED by encset_b (codegen). Do not edit.
# Lemmas shared by the encode-after-set laws of the byte lists (proofs/obj/encset_b_<list>.bend): see codegen/proofs/collections/encset_b.py.

# quad q < quad P gives q < P
def qlt_rev(+q: Nat, +P: Nat, +h: {Nat.is_lt(A.quad(q), A.quad(P)) == True{} : Bool}) -> {Nat.is_lt(q, P) == True{} : Bool}:
  match q P:
    case 0n 0n: Empty.absurd({Nat.is_lt(0n, 0n) == True{} : Bool}, F.logic__false_true(h))
    case 0n 1n+ +s: {==}
    case 1n+ +p 0n: Empty.absurd({Nat.is_lt(1n+p, 0n) == True{} : Bool}, F.logic__false_true(h))
    case 1n+ +p 1n+ +s: qlt_rev(p, s, h)

# X + s < X + r gives s < r
def lt_cancel(+X: Nat, +s: Nat, +r: Nat, +h: {Nat.is_lt(Nat.add(X, s), Nat.add(X, r)) == True{} : Bool}) -> {Nat.is_lt(s, r) == True{} : Bool}:
  match X:
    case 0n: h
    case 1n+ +p: lt_cancel(p, s, r, h)

# the window's bytes of a tree are the bytes of its slots
def wv_bt(+X: F.array__Tree<U32>, +N: U32) -> {WO.wview(O.Words{F.array__thaw(U32, X), N}) == VS.bt(U32.to_nat(N), FX.limbs(F.array__slots(U32, X))) : +List<U32>}:
  %Equal.sym(F.array__Tree<U32>, F.array__freeze(U32, F.array__thaw(U32, X)), X, F.array__freeze_thaw(U32, X)) :
    {WS.btake(U32.to_nat(N), FX.limbs(F.array__slots(U32, _))) == VS.bt(U32.to_nat(N), FX.limbs(F.array__slots(U32, X))) : +List<U32>}
  VBT.btake_bt(U32.to_nat(N), FX.limbs(F.array__slots(U32, X)))

def vv_bt(+X: F.array__Tree<U32>, +N: U32) -> {PB.vview1(O.Words{F.array__thaw(U32, X), N}) == S.Sequence{PB.it1(U32.to_nat(N), VS.bt(U32.to_nat(N), FX.limbs(F.array__slots(U32, X))))} : S.Value}:
  %Equal.sym(F.array__Tree<U32>, F.array__freeze(U32, F.array__thaw(U32, X)), X, F.array__freeze_thaw(U32, X)) :
    {S.Sequence{PB.it1(U32.to_nat(N), WS.btake(U32.to_nat(N), FX.limbs(F.array__slots(U32, _))))} == S.Sequence{PB.it1(U32.to_nat(N), VS.bt(U32.to_nat(N), FX.limbs(F.array__slots(U32, X))))} : S.Value}
  Equal.cong(+List<U32>, S.Value, z => S.Sequence{PB.it1(U32.to_nat(N), z)}, WS.btake(U32.to_nat(N), FX.limbs(F.array__slots(U32, X))), VS.bt(U32.to_nat(N), FX.limbs(F.array__slots(U32, X))),
    VBT.btake_bt(U32.to_nat(N), FX.limbs(F.array__slots(U32, X))))
'''


def text(c, kind):
    f = EW.facts(c)
    cj = f['cj']
    n = len(cj)
    NW = 'O.merge_word(WR.at(F.array__slots(U32, T), q), v, U32.and(i, 3), 1)'
    T2 = 'F.array__upd(U32, dw, T, q, %s)' % NW
    sub = lambda s_, t_: re.sub(r'(?<![\w.])T(?![\w.])', t_, s_)
    pre = ('+dw: Nat, +T: F.array__Tree<U32>, +N: U32, +i: U32, +q: Nat, +v: U32, +h: {E.OKT(dw, T, N) == True{} : Bool}, +hv: {U32.is_le(v, 255) == True{} : Bool}, '
           '+hs: {Nat.is_lt(U32.to_nat(i), U32.to_nat(N)) == True{} : Bool}, +hq: {U32.to_nat(U32.shrn(i, 2n)) == q : Nat}')
    args = 'dw, T, N, i, q, v, h, hv, hs, hq'
    rest = lambda k: cj[k] if k == n - 1 else 'Bool.and(%s, %s)' % (cj[k], rest(k + 1))
    ik = {'pf': [k for k in range(n) if 'array__perfect' in cj[k]][0], 'tz': [k for k in range(n) if 'tail_zero' in cj[k]][0],
          'hd': [k for k in range(n) if 'is_lt(dw, 28n)' in cj[k]][0], 'hn': [k for k in range(n) if 'A.quad(VB.pw(dw))' in cj[k]][0]}
    UV = 'S.UnsignedValue{P.UInt{v, 0, 0, 0, 0, 0, 0, 0}}'
    L = []

    def common():
        out = []
        prf = ['h']
        for k in range(1, n):
            prf.append('EB.and_r(%s, %s, %s)' % (cj[k - 1], rest(k), prf[k - 1]))
        for k in range(n):
            out.append('  +r%d = %s' % (k, prf[k]))
        for k in range(n):
            out.append('  +p%d = %s' % (k, 'r%d' % k if k == n - 1 else 'EB.and_l(%s, %s, r%d)' % (cj[k], rest(k + 1), k)))
        out.append('  +J = U32.to_nat(i)')
        out.append('  +sp = USP.split2(i)')
        out.append('  +s = U32.to_nat(U32.and(i, 3))')
        # q = i >> 2 < 2^dw: quad q <= i < N <= quad (2^dw)
        out.append('  +eq = Equal.cong(Nat, Nat, z => A.quad(z), U32.to_nat(U32.shrn(i, 2n)), q, hq)')
        out.append('  +hqi = F.logic__subst(Nat, z => {Nat.is_le(A.quad(q), z) == True{} : Bool}, Nat.add(s, A.quad(U32.to_nat(U32.shrn(i, 2n)))), J, Equal.sym(Nat, J, Nat.add(s, A.quad(U32.to_nat(U32.shrn(i, 2n)))), sp),'
                   ' F.logic__subst(Nat, z => {Nat.is_le(A.quad(q), Nat.add(s, z)) == True{} : Bool}, A.quad(q), A.quad(U32.to_nat(U32.shrn(i, 2n))), Equal.sym(Nat, A.quad(U32.to_nat(U32.shrn(i, 2n))), A.quad(q), eq), Order.left_below_sum(s, A.quad(q))))')
        out.append('  +hqk = F.nat__lt_le_trans(A.quad(q), U32.to_nat(N), A.quad(VB.pw(dw)), F.nat__le_lt_trans(A.quad(q), J, U32.to_nat(N), hqi, hs), p%d)' % ik['hn'])
        out.append('  +hk = EB2.qlt_rev(q, VB.pw(dw), hqk)')
        out.append('  +pf2 = F.array__upd_perfect(U32, dw, T, q, %s, p%d)' % (NW, ik['pf']))
        return out

    L.append('# ---- the premises of the encode bridge for the written mirror ----')
    # the tail: the slot of the word N >> 2, by the cases of whether it is the written word
    TZG = 'O.tail_zero(U32.and(N, 3), VB.slot(%s, VYS.QL(N))) == True{} : Bool' % T2
    L.append('def %s_tz_f(+eb: {Nat.is_eq(q, VYS.QL(N)) == False{} : Bool}, %s)\n    -> {%s}:' % (c, pre, TZG))
    L += common()
    L.append('  +hat = WR.at_upd_other(dw, T, q, VYS.QL(N), %s, eb, hk, p%d)' % (NW, ik['pf']))
    L.append('  +e1 = Equal.trans(U32, VB.slot(%s, VYS.QL(N)), WR.at(F.array__slots(U32, %s), VYS.QL(N)), VB.slot(T, VYS.QL(N)),'
             ' WW.wd_at(F.array__slots(U32, %s), VYS.QL(N)), Equal.trans(U32, WR.at(F.array__slots(U32, %s), VYS.QL(N)), WR.at(F.array__slots(U32, T), VYS.QL(N)), VB.slot(T, VYS.QL(N)), hat, Equal.sym(U32, VB.slot(T, VYS.QL(N)), WR.at(F.array__slots(U32, T), VYS.QL(N)), WW.wd_at(F.array__slots(U32, T), VYS.QL(N)))))' % (T2, T2, T2, T2))
    L.append('  F.logic__subst(U32, z => {O.tail_zero(U32.and(N, 3), z) == True{} : Bool}, VB.slot(T, VYS.QL(N)), VB.slot(%s, VYS.QL(N)), Equal.sym(U32, VB.slot(%s, VYS.QL(N)), VB.slot(T, VYS.QL(N)), e1), p%d)' % (T2, T2, ik['tz']))
    L.append('')
    L.append('def %s_tz_t(+eb: {Nat.is_eq(q, VYS.QL(N)) == True{} : Bool}, %s)\n    -> {%s}:' % (c, pre, TZG))
    L += common()
    L.append('  +eQ = F.nat__eq_from_is_eq(q, VYS.QL(N), eb)')
    L.append('  +r_ = U32.to_nat(U32.and(N, 3))')
    L.append('  +spN = USP.split2(N)')
    L.append('  +hX = F.logic__subst(Nat, z => {Nat.is_lt(J, Nat.add(r_, A.quad(z))) == True{} : Bool}, VYS.QL(N), U32.to_nat(U32.shrn(i, 2n)), Equal.trans(Nat, VYS.QL(N), q, U32.to_nat(U32.shrn(i, 2n)), Equal.sym(Nat, q, VYS.QL(N), eQ), Equal.sym(Nat, U32.to_nat(U32.shrn(i, 2n)), q, hq)),'
             ' F.logic__subst(Nat, z => {Nat.is_lt(J, z) == True{} : Bool}, U32.to_nat(N), Nat.add(r_, A.quad(VYS.QL(N))), spN, hs))')
    L.append('  +hY = F.logic__subst(Nat, z => {Nat.is_lt(z, Nat.add(r_, A.quad(U32.to_nat(U32.shrn(i, 2n))))) == True{} : Bool}, J, Nat.add(s, A.quad(U32.to_nat(U32.shrn(i, 2n)))), sp, hX)')
    L.append('  +hlt = EB2.lt_cancel(A.quad(U32.to_nat(U32.shrn(i, 2n))), s, r_, F.logic__subst(Nat, z => {Nat.is_lt(Nat.add(s, A.quad(U32.to_nat(U32.shrn(i, 2n)))), z) == True{} : Bool}, Nat.add(r_, A.quad(U32.to_nat(U32.shrn(i, 2n)))), Nat.add(A.quad(U32.to_nat(U32.shrn(i, 2n))), r_), F.nat__add_comm(r_, A.quad(U32.to_nat(U32.shrn(i, 2n)))),'
             ' F.logic__subst(Nat, z => {Nat.is_lt(z, Nat.add(r_, A.quad(U32.to_nat(U32.shrn(i, 2n))))) == True{} : Bool}, Nat.add(s, A.quad(U32.to_nat(U32.shrn(i, 2n)))), Nat.add(A.quad(U32.to_nat(U32.shrn(i, 2n))), s), F.nat__add_comm(s, A.quad(U32.to_nat(U32.shrn(i, 2n)))), hY)))')
    L.append('  +hsb = F.logic__subst(Nat, z => {Nat.is_le(z, r_) == True{} : Bool}, 1n+s, Nat.add(s, U32.to_nat(1)), Equal.sym(Nat, Nat.add(s, 1n), 1n+s, EB.add_one(s)), F.nat__lt_succ_le_succ(s, r_, hlt))')
    L.append('  +old = F.logic__subst(U32, z => {O.tail_zero(U32.and(N, 3), z) == True{} : Bool}, VB.slot(T, VYS.QL(N)), WR.at(F.array__slots(U32, T), q),'
             ' Equal.trans(U32, VB.slot(T, VYS.QL(N)), VB.slot(T, q), WR.at(F.array__slots(U32, T), q), Equal.cong(Nat, U32, z => VB.slot(T, z), VYS.QL(N), q, Equal.sym(Nat, q, VYS.QL(N), eQ)), WW.wd_at(F.array__slots(U32, T), q)), p%d)' % ik['tz'])
    L.append('  +new = TZ.tz_merge(U32.and(N, 3), U32.and(i, 3), 1, WR.at(F.array__slots(U32, T), q), v, hsb, RD.and_le(N, 3), {==}, {==}, old)')
    L.append('  +at2 = WR.at_upd_same(dw, T, q, %s, hk, p%d)' % (NW, ik['pf']))
    L.append('  +e2 = Equal.trans(U32, VB.slot(%s, VYS.QL(N)), VB.slot(%s, q), %s, Equal.cong(Nat, U32, z => VB.slot(%s, z), VYS.QL(N), q, Equal.sym(Nat, q, VYS.QL(N), eQ)), Equal.trans(U32, VB.slot(%s, q), WR.at(F.array__slots(U32, %s), q), %s, WW.wd_at(F.array__slots(U32, %s), q), at2))' % (T2, T2, NW, T2, T2, T2, NW, T2))
    L.append('  F.logic__subst(U32, z => {O.tail_zero(U32.and(N, 3), z) == True{} : Bool}, %s, VB.slot(%s, VYS.QL(N)), Equal.sym(U32, VB.slot(%s, VYS.QL(N)), %s, e2), new)' % (NW, T2, T2, NW))
    L.append('')
    L.append('def %s_tz_go(+b: Bool, +eb: {Nat.is_eq(q, VYS.QL(N)) == b : Bool}, %s)\n    -> {%s}:' % (c, pre, TZG))
    L.append('  match b:')
    L.append('    case False{}: %s_tz_f(eb, %s)' % (c, args))
    L.append('    case True{}: %s_tz_t(eb, %s)' % (c, args))
    L.append('')
    L.append('def %s_okt_set(%s)\n    -> {E.OKT(dw, %s, N) == True{} : Bool}:' % (c, pre, T2))
    L += common()
    L.append('  +tz2 = %s_tz_go(Nat.is_eq(q, VYS.QL(N)), {==}, %s)' % (c, args))
    prf = {ik['pf']: 'pf2', ik['tz']: 'tz2'}

    def chain(k):
        if k == n - 1:
            return prf.get(k, 'p%d' % k)
        return 'EB.and_i(%s, %s, %s, %s)' % (sub(cj[k], T2), sub(rest(k + 1), T2), prf.get(k, 'p%d' % k), chain(k + 1))
    L.append('  ' + chain(0))
    L.append('')
    L.append('# ---- the value of the written mirror: the old value with byte i replaced ----')
    if kind == 'b':
        tgt = 'VSE.bytes_set(W.VALw(T, 0n, N), U32.to_nat(i), v)'
        wrap = lambda x: 'S.BytesValue{%s}' % x
        vs = 'VW.view_set(dw, T, N, i, q, v, hv, hq, hk, p%d)' % ik['pf']
        lem = 'EB2.wv_bt'
        old_form = 'S.BytesValue{VS.bt(U32.to_nat(N), FX.limbs(F.array__slots(U32, T)))}'
        vw = lambda t_: 'S.BytesValue{WO.wview(O.Words{F.array__thaw(U32, %s), N})}' % t_
    else:
        tgt = 'VSE.field_set(W.VALw(T, 0n, N), U32.to_nat(i), %s)' % UV
        wrap = None
        vs = 'VW.view_set_u8(dw, T, N, i, q, v, hv, hq, hk, p%d)' % ik['pf']
        lem = 'EB2.vv_bt'
        old_form = 'S.Sequence{PB.it1(U32.to_nat(N), VS.bt(U32.to_nat(N), FX.limbs(F.array__slots(U32, T))))}'
        vw = lambda t_: 'PB.vview1(O.Words{F.array__thaw(U32, %s), N})' % t_
    L.append('def %s_vall_set(%s)\n    -> {W.VALw(%s, 0n, N) == %s : S.Value}:' % (c, pre, T2, tgt))
    L += common()
    NEWF = (lambda t_: 'S.BytesValue{VS.bt(U32.to_nat(N), FX.limbs(F.array__slots(U32, %s)))}' % t_) if kind == 'b' else (lambda t_: 'S.Sequence{PB.it1(U32.to_nat(N), VS.bt(U32.to_nat(N), FX.limbs(F.array__slots(U32, %s))))}' % t_)
    if kind == 'b':
        e_new = 'Equal.cong(+List<U32>, S.Value, z => S.BytesValue{z}, VS.bt(U32.to_nat(N), FX.limbs(F.array__slots(U32, %s))), WO.wview(O.Words{F.array__thaw(U32, %s), N}), Equal.sym(+List<U32>, WO.wview(O.Words{F.array__thaw(U32, %s), N}), VS.bt(U32.to_nat(N), FX.limbs(F.array__slots(U32, %s))), %s(%s, N)))' % (T2, T2, T2, T2, lem, T2)
        e_old = 'Equal.cong(+List<U32>, S.Value, z => VSE.bytes_set(S.BytesValue{z}, U32.to_nat(i), v), WO.wview(O.Words{F.array__thaw(U32, T), N}), VS.bt(U32.to_nat(N), FX.limbs(F.array__slots(U32, T))), %s(T, N))' % lem
        L.append('  +e1 = Equal.trans(S.Value, %s, %s, %s, %s,' % (NEWF(T2), vw(T2), 'VSE.bytes_set(%s, U32.to_nat(i), v)' % NEWF('T'), e_new))
        L.append('    Equal.trans(S.Value, %s, VSE.bytes_set(%s, U32.to_nat(i), v), VSE.bytes_set(%s, U32.to_nat(i), v), %s, %s))' % (vw(T2), vw('T'), NEWF('T'), vs, e_old))
    else:
        e_new = 'Equal.sym(S.Value, %s, %s, %s(%s, N))' % (vw(T2), NEWF(T2), lem, T2)
        e_old = 'Equal.cong(S.Value, S.Value, z => VSE.field_set(z, U32.to_nat(i), %s), %s, %s, %s(T, N))' % (UV, vw('T'), NEWF('T'), lem)
        L.append('  +e1 = Equal.trans(S.Value, %s, %s, VSE.field_set(%s, U32.to_nat(i), %s), %s,' % (NEWF(T2), vw(T2), NEWF('T'), UV, e_new))
        L.append('    Equal.trans(S.Value, %s, VSE.field_set(%s, U32.to_nat(i), %s), VSE.field_set(%s, U32.to_nat(i), %s), %s, %s))' % (vw(T2), vw('T'), UV, NEWF('T'), UV, vs, e_old))
    L.append('  e1')
    L.append('')
    L.append('# ---- the written object: the mirror of the updated tree is the runtime\'s word write of the old one ----')
    L.append('def %s_written(+dw: Nat, +T: F.array__Tree<U32>, +N: U32, +i: U32, +q: Nat, +v: U32, +hd: {Nat.is_lt(dw, 32n) == True{} : Bool}, +pf: {F.array__perfect(U32, dw, T) == True{} : Bool}, '
             '+hq: {U32.to_nat(U32.shrn(i, 2n)) == q : Nat}, +hk: {Nat.is_lt(q, F.spec_common__pow2(dw)) == True{} : Bool})\n'
             '    -> {E.TH(E.MW{dw, %s, N}) == O.words_setw(E.TH(E.MW{dw, T, N}), U32.shrn(i, 2n), %s) : O.Words}:' % (c, T2, NW))
    L.append('  Equal.sym(O.Words, O.words_setw(O.Words{F.array__thaw(U32, T), N}, U32.shrn(i, 2n), %s), E.TH(E.MW{dw, %s, N}), WR.setw_thaw(dw, T, N, U32.shrn(i, 2n), q, %s, hd, hq, hk, pf))' % (NW, T2, NW))
    L.append('')
    L.append('# ---- the composed statement: the spec encode of the set value is the bytes of the written mirror ----')
    L.append('def %s_api_encode_set(%s)\n    -> {Codec.parts(%s, %s) == Some{[S.Variable{E.ENC(E.MW{dw, %s, N})}]} : Maybe<&2, +List<S.Part>>}:' % (c, pre, tgt.replace('W.VALw(T, 0n, N)', 'E.VAL(E.MW{dw, T, N})'), f['schema'], T2))
    L.append('  %%%s_vall_set(%s) :' % (c, args))
    L.append('    {Codec.parts(_, %s) == Some{[S.Variable{E.ENC(E.MW{dw, %s, N})}]} : Maybe<&2, +List<S.Part>>}' % (f['schema'], T2))
    L.append('  E.encx_spec(E.MW{dw, %s, N}, %s_okt_set(%s))' % (T2, c, args))
    body = '\n'.join(L)
    fixed = {'S': '../../types/schema.bend', 'P': '../../types/primitive.bend', 'F': '../compact/found.bend', 'FD': '../compact/found.bend', 'A': '../compact/arith.bend', 'RD': '../compact/reads.bend',
             'O': '../../src/obj.bend', 'VS': './vspec.bend', 'VSE': './value_set.bend', 'VB': './vbuf.bend', 'FX': './spec_fixed.bend', 'WS': './words_spec.bend', 'WO': './words_obj_light.bend',
             'PB': './packed_bytes_light.bend', 'WR': './words_rw.bend', 'WW': './words_win.bend', 'VW': './view_bytes.bend', 'USP': './u32split.bend', 'Order': '../nat_order.bend',
             'VYS': './vbytes.bend', 'TZ': './tz_merge.bend', 'EB': './encset_w_base.bend', 'EB2': './encset_b_base.bend', 'Codec': '../../spec/codec.bend', 'Spec': '../../spec/fulu_schemas.bend',
             'E': './encx_%s.bend' % c, 'W': f['W']}
    head = ['import Base'] + ['import %s as %s' % (pth, a) for a, pth in fixed.items()]
    head += ['', '# GENERATED by encset_b (codegen). Do not edit.',
             '# The encode of the list %s after one byte is written, stated per element: see codegen/proofs/collections/encset_b.py.' % c, '']
    return '\n'.join(head) + '\n' + body + '\n'


def out_path(c):
    return OBJ / ('encset_b_%s.bend' % c)


def main():
    outs = [(BASE, BASE_TEXT)] + [(out_path(c), text(c, k)) for c, k in LISTS]
    stale = False
    for o, t in outs:
        if '--check' in sys.argv:
            if not o.exists() or o.read_text() != t:
                print('stale: %s' % o.name)
                stale = True
            continue
        if not o.exists() or o.read_text() != t:
            o.write_text(t)
        print('encset_b: proofs/obj/%s' % o.name)
    if '--check' in sys.argv:
        if stale:
            sys.exit(1)
        print('encset_b: up to date')


if __name__ == '__main__':
    main()
