#!/usr/bin/env python3
"""proofs/obj/encset_r_<list>.bend: the runtime's set of a uint16 list, and its composed encode.

encset_h_<list>.bend states the encode of a mutated list at tree level: the halfword at byte offset s = 0 or 2 of the word q (with 2 j = 4 q + s and 2 j + 2 <= N as
premises). Here the premises are derived from the runtime's own call, set(Words{thaw T, N}, i, v), which writes the halfword at the byte position p = i * 2
(O.words_write(w, p, v, 2): word p >> 2, offset p & 3):

    <c>_set_eq              set(o, i, v) is (words_write(o, i * 2, v, 2), True) when i is below the count N / 2 and v <= 65535
    <c>_set_obj_<s>         for the offset s = (i * 2) & 3 = 0 or 2: the result is the mirror's object over T2 (words_rw.bend's word_thaw / setw_thaw)
    <c>_api_set_encode_<s>  the composed statement: from OKT(dw, T, N), i < N / 2 and v <= 65535, the spec encode of the value with item i replaced by the element v is
                            ENC of the written mirror. The room 2 i + 2 <= N comes from CHKw (N = 2 (N / 2)), the word q = (i * 2) >> 2 and 2 i = 4 q + s from the product
                            (vu32.bend's mul_lt32, u32split.bend's split2); the element value v16of(v & 255, (v >> 8) & 255) is v (v16_rt.bend).

The offset is the premise hps: (i * 2) & 3 is the literal s; it is 0 for an even i and 2 for an odd one.

    python3 codegen/proofs/collections/encset_r.py            # write
    python3 codegen/proofs/collections/encset_r.py --check    # nonzero exit if the output is stale
"""
import sys as _sys
import pathlib as _pathlib
_sys.path.insert(0, str(_pathlib.Path(__file__).resolve().parents[3]))  # the repository root: `codegen` is importable when this file runs as a script
import re
from codegen.core.paths import ROOT  # noqa: E402
from codegen.core.shared_laws import run_each  # noqa: E402
from codegen.proofs.collections import encset_w as EW  # noqa: E402

OBJ = ROOT / 'proofs/obj'
BASE = OBJ / 'encset_r_base.bend'
LISTS = ('l1024_u16', 'l123_u16', 'l128_u16')

BASE_TEXT = '''import Base
import ../../src/obj.bend as O
import ../compact/found.bend as F
import ./words_rw.bend as WR
import ./vbuf.bend as VB
import ./vu32.bend as VU
import ./halfword16.bend as HW

# GENERATED by encset_r (codegen). Do not edit.
# Lemmas shared by the runtime-level laws of the uint16 lists (proofs/obj/encset_r_<list>.bend): see codegen/proofs/collections/encset_r.py.

def mul2_double(+j: Nat) -> {Nat.mul(j, 2n) == Nat.double(j) : Nat}:
  match j:
    case 0n: {==}
    case 1n+ +p: Equal.cong(Nat, Nat, z => 2n+z, Nat.mul(p, 2n), Nat.double(p), mul2_double(p))

def lt_u32(+a: Nat, +n: U32, h: {Nat.is_lt(a, U32.to_nat(n)) == True{} : Bool}) -> {Nat.is_lt(a, F.spec_common__pow2(32n)) == True{} : Bool}:
  F.nat__lt_trans(a, U32.to_nat(n), F.spec_common__pow2(32n), h, VB.u32_lt(n))

# the byte position i * 2 does not wrap when 2 i is below the (32-bit) length N
def mul2_u32(+i: U32, +n: U32, h: {Nat.is_lt(Nat.double(U32.to_nat(i)), U32.to_nat(n)) == True{} : Bool}) -> {U32.to_nat(U32.mul(i, 2)) == Nat.double(U32.to_nat(i)) : Nat}:
  Equal.trans(Nat, U32.to_nat(U32.mul(i, 2)), Nat.mul(U32.to_nat(i), 2n), Nat.double(U32.to_nat(i)),
    VU.mul_lt32(i, 2, F.logic__subst(Nat, z => {Nat.is_lt(z, F.spec_common__pow2(32n)) == True{} : Bool}, Nat.double(U32.to_nat(i)), Nat.mul(U32.to_nat(i), 2n),
      Equal.sym(Nat, Nat.mul(U32.to_nat(i), 2n), Nat.double(U32.to_nat(i)), mul2_double(U32.to_nat(i))), lt_u32(Nat.double(U32.to_nat(i)), n, h))),
    mul2_double(U32.to_nat(i)))

# a halfword written at the byte position p: the word p >> 2 gets the merged halfword (the word read, merged, written back)
def ww_obj(+d: Nat, +t: F.array__Tree<U32>, +n: U32, +p: U32, +x: U32, +q: Nat, +hd: {Nat.is_lt(d, 32n) == True{} : Bool}, +hq: {U32.to_nat(U32.shrn(p, 2n)) == q : Nat},
    +hk: {Nat.is_lt(q, F.spec_common__pow2(d)) == True{} : Bool}, +pf: {F.array__perfect(U32, d, t) == True{} : Bool})
    -> {O.words_write(O.Words{F.array__thaw(U32, t), n}, p, x, 2) == O.Words{F.array__thaw(U32, F.array__upd(U32, d, t, q, O.merge_word(WR.at(F.array__slots(U32, t), q), x, U32.and(p, 3), 2))), n} : O.Words}:
  %Equal.sym(O.Words & U32, O.words_word(O.Words{F.array__thaw(U32, t), n}, U32.shrn(p, 2n)), (O.Words{F.array__thaw(U32, t), n}, WR.at(F.array__slots(U32, t), q)), WR.word_thaw(d, t, n, U32.shrn(p, 2n), q, hd, hq, hk, pf)) :
    {O.put_in(U32.shrn(p, 2n), x, U32.and(p, 3), 2, _) == O.Words{F.array__thaw(U32, F.array__upd(U32, d, t, q, O.merge_word(WR.at(F.array__slots(U32, t), q), x, U32.and(p, 3), 2))), n} : O.Words}
  WR.setw_thaw(d, t, n, U32.shrn(p, 2n), q, O.merge_word(WR.at(F.array__slots(U32, t), q), x, U32.and(p, 3), 2), hd, hq, hk, pf)
'''


def tr(a, b, c, e1, e2):
    return 'Equal.trans(U32, %s, %s, %s, %s, %s)' % (a, b, c, e1, e2)


def base_extra():
    """Read-back lemmas on O.words_byte_at over the mirror of a tree and over the mirror after one halfword is written."""
    OW = lambda t: 'O.Words{F.array__thaw(U32, %s), n}' % t
    AT = lambda t, q: 'WR.at(F.array__slots(U32, %s), %s)' % (t, q)
    RD = lambda x, r='U32.and(p, 3)': 'U32.and(O.shr_bytes(%s, %s), 65535)' % (x, r)
    ST = '+d: Nat, +t: F.array__Tree<U32>, +n: U32, +p: U32'
    CK = lambda q: ('+hd: {Nat.is_lt(d, 32n) == True{} : Bool}, +hq: {U32.to_nat(U32.shrn(p, 2n)) == %s : Nat}, '
                    '+hk: {Nat.is_lt(%s, F.spec_common__pow2(d)) == True{} : Bool}, +pf: {F.array__perfect(U32, d, t) == True{} : Bool}' % (q, q))
    PAIR = 'O.Words & U32'
    L = []
    L.append('# the element at byte position p of the mirror of t: the halfword of its word l = p >> 2')
    L.append('def ba_obj(%s, +l: Nat, +hd: {Nat.is_lt(d, 32n) == True{} : Bool}, +hq: {U32.to_nat(U32.shrn(p, 2n)) == l : Nat}, '
             '+hk: {Nat.is_lt(l, F.spec_common__pow2(d)) == True{} : Bool}, +pf: {F.array__perfect(U32, d, t) == True{} : Bool})\n'
             '    -> {O.words_byte_at(%s, p, 2) == (%s, %s) : %s}:' % (ST, OW('t'), OW('t'), RD(AT('t', 'l')), PAIR))
    L.append('  %%Equal.sym(%s, O.words_word(%s, U32.shrn(p, 2n)), (%s, %s), WR.word_thaw(d, t, n, U32.shrn(p, 2n), l, hd, hq, hk, pf)) :' % (PAIR, OW('t'), OW('t'), AT('t', 'l')))
    L.append('    {O.read_at(p, 2, _) == (%s, %s) : %s}' % (OW('t'), RD(AT('t', 'l')), PAIR))
    L.append('  {==}')
    L.append('')
    # another word of the written tree
    X = '+x: U32'
    TX = 'F.array__upd(U32, d, t, q, x)'
    L.append('# an element in another word than the written one is read from the old tree')
    L.append('def ba_other_dw(%s, +q: Nat, +l: Nat, %s, +hd: {Nat.is_lt(d, 32n) == True{} : Bool}, +hq: {U32.to_nat(U32.shrn(p, 2n)) == l : Nat}, '
             '+hkq: {Nat.is_lt(q, F.spec_common__pow2(d)) == True{} : Bool}, +hkl: {Nat.is_lt(l, F.spec_common__pow2(d)) == True{} : Bool}, '
             '+pf: {F.array__perfect(U32, d, t) == True{} : Bool}, +ne: {Nat.is_eq(q, l) == False{} : Bool})\n'
             '    -> {O.words_byte_at(%s, p, 2) == (%s, %s) : %s}:' % (ST, X, OW(TX), OW(TX), RD(AT('t', 'l')), PAIR))
    L.append('  +b = ba_obj(d, %s, n, p, l, hd, hq, hkl, F.array__upd_perfect(U32, d, t, q, x, pf))' % TX)
    L.append('  +e = WR.at_upd_other(d, t, q, l, x, ne, hkq, pf)')
    L.append('  Equal.trans(%s, O.words_byte_at(%s, p, 2), (%s, %s), (%s, %s), b,' % (PAIR, OW(TX), OW(TX), RD(AT(TX, 'l')), OW(TX), RD(AT('t', 'l'))))
    L.append('    Equal.cong(U32, %s, z => (%s, z), %s, %s, Equal.cong(U32, U32, z => %s, %s, %s, e)))' % (PAIR, OW(TX), RD(AT(TX, 'l')), RD(AT('t', 'l')), RD('z'), AT(TX, 'l'), AT('t', 'l')))
    L.append('')
    for s in (0, 2):
        r = 2 - s
        MW = 'O.merge_word(%s, v, %d, 2)' % (AT('t', 'q'), s)
        T2 = 'F.array__upd(U32, d, t, q, %s)' % MW
        base = '%s, +v: U32, +q: Nat, %s' % (ST, CK('q'))
        pre_b = ('  +b = ba_obj(d, %s, n, p, q, hd, hq, hk, F.array__upd_perfect(U32, d, t, q, %s, pf))\n'
                 '  +e1 = WR.at_upd_same(d, t, q, %s, hk, pf)\n'
                 '  +c1 = Equal.cong(U32, U32, z => %s, %s, %s, e1)' % (T2, MW, MW, RD('z'), AT(T2, 'q'), MW))
        X0 = RD(AT(T2, 'q'))
        X1 = RD(MW)
        # read the written halfword back
        L.append('# the halfword written at offset %d reads back as v' % s)
        L.append('def ba_same_s%d(%s, +hps: {U32.and(p, 3) == %d : U32}, +hv: {U32.is_le(v, 65535) == True{} : Bool})\n'
                 '    -> {O.words_byte_at(%s, p, 2) == (%s, v) : %s}:' % (s, base, s, OW(T2), OW(T2), PAIR))
        L.append(pre_b)
        X2 = RD(MW, str(s))
        X3 = 'U32.and(v, 65535)'
        L.append('  +c2 = Equal.cong(U32, U32, z => %s, U32.and(p, 3), %d, hps)' % (RD(MW, 'z'), s))
        L.append('  +c3 = HW.hw16_rw_%d_%d(%s, v)' % (s, s, AT('t', 'q')))
        L.append('  +c4 = HW.and16_le(v, hv)')
        chain = tr(X0, X3, 'v', tr(X0, X2, X3, tr(X0, X1, X2, 'c1', 'c2'), 'c3'), 'c4')
        L.append('  Equal.trans(%s, O.words_byte_at(%s, p, 2), (%s, %s), (%s, v), b,' % (PAIR, OW(T2), OW(T2), X0, OW(T2)))
        L.append('    Equal.cong(U32, %s, z => (%s, z), %s, v, %s))' % (PAIR, OW(T2), X0, chain))
        L.append('')
        # an element of the same word at the other offset is unchanged
        L.append('# the other halfword of the same word (offset %d) is unchanged by a halfword written at offset %d' % (r, s))
        L.append('def ba_other_sw_s%d(%s, +hps: {U32.and(p, 3) == %d : U32})\n'
                 '    -> {O.words_byte_at(%s, p, 2) == (%s, %s) : %s}:' % (s, base, r, OW(T2), OW(T2), RD(AT('t', 'q')), PAIR))
        L.append(pre_b)
        Y2 = RD(MW, str(r))
        Y3 = RD(AT('t', 'q'), str(r))
        Y4 = RD(AT('t', 'q'))
        L.append('  +c2 = Equal.cong(U32, U32, z => %s, U32.and(p, 3), %d, hps)' % (RD(MW, 'z'), r))
        L.append('  +c3 = HW.hw16_rw_%d_%d(%s, v)' % (s, r, AT('t', 'q')))
        L.append('  +c4 = Equal.cong(U32, U32, z => %s, %d, U32.and(p, 3), Equal.sym(U32, U32.and(p, 3), %d, hps))' % (RD(AT('t', 'q'), 'z'), r, r))
        chain = tr(X0, Y3, Y4, tr(X0, Y2, Y3, tr(X0, X1, Y2, 'c1', 'c2'), 'c3'), 'c4')
        L.append('  Equal.trans(%s, O.words_byte_at(%s, p, 2), (%s, %s), (%s, %s), b,' % (PAIR, OW(T2), OW(T2), X0, OW(T2), Y4))
        L.append('    Equal.cong(U32, %s, z => (%s, z), %s, %s, %s))' % (PAIR, OW(T2), X0, Y4, chain))
        L.append('')
    return '\n'.join(L)


def text(c):
    f = EW.facts(c)
    cj = f['cj']
    n = len(cj)
    rest = lambda k: cj[k] if k == n - 1 else 'Bool.and(%s, %s)' % (cj[k], rest(k + 1))
    ik = {'pf': [k for k in range(n) if 'array__perfect' in cj[k]][0], 'd28': [k for k in range(n) if 'is_lt(dw, 28n)' in cj[k]][0],
          'ch': [k for k in range(n) if 'CHKw' in cj[k]][0], 'hn': [k for k in range(n) if 'A.quad(VB.pw(dw))' in cj[k]][0]}
    DEF = 'DEF'
    UV = 'S.UnsignedValue{P.UInt{v, 0, 0, 0, 0, 0, 0, 0}}'
    LO = 'U32.and(v, 255)'
    HI = 'U32.and(U32.shrn(v, 8n), 255)'
    UVL = 'S.UnsignedValue{P.UInt{PM.v16of(%s, %s), 0, 0, 0, 0, 0, 0, 0}}' % (LO, HI)
    P2 = '(i * 2 : U32)'
    QQ = 'U32.to_nat(U32.shrn(%s, 2n))' % P2
    OT = 'O.Words{F.array__thaw(U32, T), N}'
    pre = ('+dw: Nat, +T: F.array__Tree<U32>, +N: U32, +i: U32, +v: U32, +h: {E.OKT(dw, T, N) == True{} : Bool}, +hg: {U32.is_lt(i, U32.div(N, 2)) == True{} : Bool}, '
           '+hv: {U32.is_le(v, 65535) == True{} : Bool}')
    L = []
    L.append('def %s_set_eq(+T: F.array__Tree<U32>, +N: U32, +i: U32, +v: U32, +hg: {U32.is_lt(i, U32.div(N, 2)) == True{} : Bool}, +hv: {U32.is_le(v, 65535) == True{} : Bool})\n'
             '    -> {%s.%s_set(%s, i, v) == (O.words_write(%s, %s, v, 2), True{}) : O.Words & Bool}:' % (c, DEF, c, OT, OT, P2))
    L.append('  %%Equal.sym(Bool, U32.is_lt(i, U32.div(N, 2)), True{}, hg) : {%s.%s_put_at(Bool.and(_, U32.is_le(v, 65535)), %s, i, v) == (O.words_write(%s, %s, v, 2), True{}) : O.Words & Bool}' % (DEF, c, OT, OT, P2))
    L.append('  %%Equal.sym(Bool, U32.is_le(v, 65535), True{}, hv) : {%s.%s_put_at(_, %s, i, v) == (O.words_write(%s, %s, v, 2), True{}) : O.Words & Bool}' % (DEF, c, OT, OT, P2))
    L.append('  {==}')
    L.append('')
    def rp_lines():
        out = []
        prf = ['h']
        for k in range(1, n):
            prf.append('EB.and_r(%s, %s, %s)' % (cj[k - 1], rest(k), prf[k - 1]))
        for k in range(n):
            out.append('  +r%d = %s' % (k, prf[k]))
        for k in range(n):
            out.append('  +p%d = %s' % (k, 'r%d' % k if k == n - 1 else 'EB.and_l(%s, %s, r%d)' % (cj[k], rest(k + 1), k)))
        return out

    def core_lines():
        out = []
        out.append('  +J = U32.to_nat(i)')
        out.append('  +q = %s' % QQ)
        out.append('  +eL = W.eLc(T, 0n, 0, N, p%d)' % ik['ch'])
        out.append('  +hlt = F.logic__subst(Bool, z => {z == True{} : Bool}, U32.is_lt(i, U32.div(N, 2)), Nat.is_lt(J, W.CQ(N)), F.u32__is_lt_nat(i, U32.div(N, 2)), hg)')
        out.append('  +hm = VI.mono(1n+J, W.CQ(N), F.nat__lt_succ_le_succ(J, W.CQ(N), hlt))')
        out.append('  +hs = F.logic__subst(Nat, z => {Nat.is_le(z, U32.to_nat(N)) == True{} : Bool}, Nat.double(1n+J), Nat.add(Nat.double(J), 2n), Equal.sym(Nat, Nat.add(Nat.double(J), 2n), Nat.double(1n+J), VI.blk(J)),'
                   ' F.logic__subst(Nat, z => {Nat.is_le(Nat.double(1n+J), z) == True{} : Bool}, Nat.double(W.CQ(N)), U32.to_nat(N), Equal.sym(Nat, U32.to_nat(N), Nat.double(W.CQ(N)), eL), hm))')
        out.append('  +ep = EB3.mul2_u32(i, N, F.nat__lt_le_trans(Nat.double(J), Nat.add(Nat.double(J), 2n), U32.to_nat(N), EH.lt_add2(Nat.double(J)), hs))')
        out.append('  +sp = USP.split2(%s)' % P2)
        return out

    # ---- the runtime's read: get(o, k) is the halfword of its word ----
    WT = 'O.Words{F.array__thaw(U32, Tr), N}'
    L.append('def %s_get_of(+Tr: F.array__Tree<U32>, +N: U32, +k: U32, +x: U32, +hg: {U32.is_lt(k, U32.div(N, 2)) == True{} : Bool}, '
             '+hb: {O.words_byte_at(%s, (k * 2 : U32), 2) == (%s, x) : O.Words & U32})\n'
             '    -> {%s.%s_get(%s, k) == (%s, Some{x}) : O.Words & Maybe<&1, U32>}:' % (c, WT, WT, DEF, c, WT, WT))
    L.append('  %%Equal.sym(Bool, U32.is_lt(k, U32.div(N, 2)), True{}, hg) : {%s.%s_get_in(_, %s, k) == (%s, Some{x}) : O.Words & Maybe<&1, U32>}' % (DEF, c, WT, WT))
    L.append('  %%Equal.sym(O.Words & U32, O.words_byte_at(%s, (k * 2 : U32), 2), (%s, x), hb) : {%s.%s_some(_) == (%s, Some{x}) : O.Words & Maybe<&1, U32>}' % (WT, WT, DEF, c, WT))
    L.append('  {==}')
    L.append('')
    L.append('def %s_pf(+dw: Nat, +T: F.array__Tree<U32>, +N: U32, +h: {E.OKT(dw, T, N) == True{} : Bool}) -> {F.array__perfect(U32, dw, T) == True{} : Bool}:' % c)
    L += rp_lines()
    L.append('  p%d' % ik['pf'])
    L.append('')
    L.append('def %s_d28(+dw: Nat, +T: F.array__Tree<U32>, +N: U32, +h: {E.OKT(dw, T, N) == True{} : Bool}) -> {Nat.is_lt(dw, 28n) == True{} : Bool}:' % c)
    L += rp_lines()
    L.append('  p%d' % ik['d28'])
    L.append('')
    # the word of an element is a leaf of the tree (for any offset)
    L.append('def %s_hk(+dw: Nat, +T: F.array__Tree<U32>, +N: U32, +i: U32, +h: {E.OKT(dw, T, N) == True{} : Bool}, +hg: {U32.is_lt(i, U32.div(N, 2)) == True{} : Bool})\n'
             '    -> {Nat.is_lt(%s, F.spec_common__pow2(dw)) == True{} : Bool}:' % (c, QQ))
    L += rp_lines() + core_lines()
    L.append('  +e0 = Equal.trans(Nat, Nat.double(J), U32.to_nat(%s), Nat.add(U32.to_nat(U32.and(%s, 3)), A.quad(q)), Equal.sym(Nat, U32.to_nat(%s), Nat.double(J), ep), sp)' % (P2, P2, P2))
    L.append('  +hq1 = F.logic__subst(Nat, z => {Nat.is_le(A.quad(q), z) == True{} : Bool}, Nat.add(U32.to_nat(U32.and(%s, 3)), A.quad(q)), Nat.double(J), '
             'Equal.sym(Nat, Nat.double(J), Nat.add(U32.to_nat(U32.and(%s, 3)), A.quad(q)), e0), Order.left_below_sum(U32.to_nat(U32.and(%s, 3)), A.quad(q)))' % (P2, P2, P2))
    L.append('  +hq2 = F.nat__lt_le_trans(Nat.double(J), Nat.add(Nat.double(J), 2n), U32.to_nat(N), EH.lt_add2(Nat.double(J)), hs)')
    L.append('  +hqk = F.nat__lt_le_trans(A.quad(q), U32.to_nat(N), A.quad(VB.pw(dw)), F.nat__le_lt_trans(A.quad(q), Nat.double(J), U32.to_nat(N), hq1, hq2), p%d)' % ik['hn'])
    L.append('  EB2.qlt_rev(q, VB.pw(dw), hqk)')
    L.append('')
    PK = '(k * 2 : U32)'
    QK = 'U32.to_nat(U32.shrn(%s, 2n))' % PK
    XK = 'U32.and(O.shr_bytes(WR.at(F.array__slots(U32, T), %s), U32.and(%s, 3)), 65535)' % (QK, PK)
    L.append('def %s_get_orig(+dw: Nat, +T: F.array__Tree<U32>, +N: U32, +k: U32, +h: {E.OKT(dw, T, N) == True{} : Bool}, +hgk: {U32.is_lt(k, U32.div(N, 2)) == True{} : Bool})\n'
             '    -> {%s.%s_get(%s, k) == (%s, Some{%s}) : O.Words & Maybe<&1, U32>}:' % (c, DEF, c, OT, OT, XK))
    L.append('  %s_get_of(T, N, k, %s, hgk, EB3.ba_obj(dw, T, N, %s, %s, F.nat__lt_trans(dw, 28n, 32n, %s_d28(dw, T, N, h), {==}), {==}, %s_hk(dw, T, N, k, h, hgk), %s_pf(dw, T, N, h)))'
             % (c, XK, PK, QK, c, c, c))
    L.append('')
    # a written word does not change the elements of the other words
    L.append('def %s_get_other_dw(+dw: Nat, +T: F.array__Tree<U32>, +N: U32, +i: U32, +k: U32, +x: U32, +h: {E.OKT(dw, T, N) == True{} : Bool}, '
             '+hg: {U32.is_lt(i, U32.div(N, 2)) == True{} : Bool}, +hgk: {U32.is_lt(k, U32.div(N, 2)) == True{} : Bool}, '
             '+ne: {Nat.is_eq(%s, %s) == False{} : Bool})\n'
             '    -> {%s.%s_get(O.Words{F.array__thaw(U32, F.array__upd(U32, dw, T, %s, x)), N}, k) == (O.Words{F.array__thaw(U32, F.array__upd(U32, dw, T, %s, x)), N}, Some{%s}) : O.Words & Maybe<&1, U32>}:'
             % (c, QQ, QK, DEF, c, QQ, QQ, XK))
    L.append('  %s_get_of(F.array__upd(U32, dw, T, %s, x), N, k, %s, hgk, EB3.ba_other_dw(dw, T, N, %s, %s, %s, x, F.nat__lt_trans(dw, 28n, 32n, %s_d28(dw, T, N, h), {==}), {==}, %s_hk(dw, T, N, i, h, hg), %s_hk(dw, T, N, k, h, hgk), %s_pf(dw, T, N, h), ne))'
             % (c, QQ, XK, PK, QQ, QK, c, c, c, c))
    L.append('')
    for s in (0, 2):
        sfx = '_s%d' % s
        NW = 'O.merge_word(WR.at(F.array__slots(U32, T), q), v, %d, 2)' % s
        T2 = 'F.array__upd(U32, dw, T, q, %s)' % NW
        pres = pre + ', +hps: {U32.and(%s, 3) == %d : U32}' % (P2, s)

        def common():
            out = rp_lines() + core_lines()
            out.append('  +eq1 = Equal.trans(Nat, Nat.double(J), U32.to_nat(%s), Nat.add(U32.to_nat(%d), A.quad(q)), Equal.sym(Nat, U32.to_nat(%s), Nat.double(J), ep),'
                       ' Equal.trans(Nat, U32.to_nat(%s), Nat.add(U32.to_nat(U32.and(%s, 3)), A.quad(q)), Nat.add(U32.to_nat(%d), A.quad(q)), sp, Equal.cong(Nat, Nat, z => Nat.add(z, A.quad(q)), U32.to_nat(U32.and(%s, 3)), U32.to_nat(%d), Equal.cong(U32, Nat, z => U32.to_nat(z), U32.and(%s, 3), %d, hps))))'
                       % (P2, s, P2, P2, P2, s, P2, s, P2, s))
            if s == 0:
                out.append('  +hj = eq1')
            else:
                out.append('  +hj = Equal.trans(Nat, Nat.double(J), Nat.add(2n, A.quad(q)), Nat.add(A.quad(q), 2n), eq1, F.nat__add_comm(2n, A.quad(q)))')
            out.append('  +hq1 = %s' % ('F.logic__subst(Nat, z => {Nat.is_le(A.quad(q), z) == True{} : Bool}, A.quad(q), Nat.double(J), Equal.sym(Nat, Nat.double(J), A.quad(q), hj), F.nat__le_refl(A.quad(q)))' if s == 0 else
                                         'F.logic__subst(Nat, z => {Nat.is_le(A.quad(q), z) == True{} : Bool}, Nat.add(A.quad(q), 2n), Nat.double(J), Equal.sym(Nat, Nat.double(J), Nat.add(A.quad(q), 2n), hj), Order.below_sum(A.quad(q), 2n))'))
            out.append('  +hq2 = F.nat__lt_le_trans(Nat.double(J), Nat.add(Nat.double(J), 2n), U32.to_nat(N), EH.lt_add2(Nat.double(J)), hs)')
            out.append('  +hqk = F.nat__lt_le_trans(A.quad(q), U32.to_nat(N), A.quad(VB.pw(dw)), F.nat__le_lt_trans(A.quad(q), Nat.double(J), U32.to_nat(N), hq1, hq2), p%d)' % ik['hn'])
            out.append('  +hk = EB2.qlt_rev(q, VB.pw(dw), hqk)')
            return out

        L.append('def %s_set_obj%s(%s)\n    -> {%s.%s_set(%s, i, v) == (O.Words{F.array__thaw(U32, F.array__upd(U32, dw, T, %s, O.merge_word(WR.at(F.array__slots(U32, T), %s), v, %d, 2))), N}, True{}) : O.Words & Bool}:'
                 % (c, sfx, pres, DEF, c, OT, QQ, QQ, s))
        L += common()
        L.append('  +wo = EB3.ww_obj(dw, T, N, %s, v, q, F.nat__lt_trans(dw, 28n, 32n, p%d, {==}), {==}, hk, p%d)' % (P2, ik['d28'], ik['pf']))
        L.append('  +wo2 = F.logic__subst(U32, z => {O.words_write(%s, %s, v, 2) == O.Words{F.array__thaw(U32, F.array__upd(U32, dw, T, q, O.merge_word(WR.at(F.array__slots(U32, T), q), v, z, 2))), N} : O.Words}, U32.and(%s, 3), %d, hps, wo)' % (OT, P2, P2, s))
        L.append('  Equal.trans(O.Words & Bool, %s.%s_set(%s, i, v), (O.words_write(%s, %s, v, 2), True{}), (O.Words{F.array__thaw(U32, F.array__upd(U32, dw, T, q, %s)), N}, True{}), %s_set_eq(T, N, i, v, hg, hv),'
                 % (DEF, c, OT, OT, P2, NW, c))
        L.append('    Equal.cong(O.Words, O.Words & Bool, z => (z, True{}), O.words_write(%s, %s, v, 2), O.Words{F.array__thaw(U32, F.array__upd(U32, dw, T, q, %s)), N}, wo2))' % (OT, P2, NW))
        L.append('')
        L.append('def %s_api_set_encode%s(%s)\n    -> {Codec.parts(VSE.field_set(E.VAL(E.MW{dw, T, N}), U32.to_nat(i), %s), %s) == Some{[S.Variable{E.ENC(E.MW{dw, F.array__upd(U32, dw, T, %s, O.merge_word(WR.at(F.array__slots(U32, T), %s), v, %d, 2)), N})}]} : Maybe<&2, +List<S.Part>>}:'
                 % (c, sfx, pres, UV, f['schema'], QQ, QQ, s))
        L += common()
        L.append('  +tr = EHc.%s_api_encode_set%s(dw, T, N, J, q, v, h, hs, hj)' % (c, sfx))
        L.append('  F.logic__subst(S.Value, z => {Codec.parts(VSE.field_set(E.VAL(E.MW{dw, T, N}), J, z), %s) == Some{[S.Variable{E.ENC(E.MW{dw, %s, N})}]} : Maybe<&2, +List<S.Part>>}, %s, %s, '
                 'Equal.cong(U32, S.Value, z => S.UnsignedValue{P.UInt{z, 0, 0, 0, 0, 0, 0, 0}}, PM.v16of(%s, %s), v, V16.v16_rt(v, hv)), tr)' % (f['schema'], T2, UVL, UV, LO, HI))
        # the runtime's read after the set
        T2Q = 'F.array__upd(U32, dw, T, %s, %s)' % (QQ, NW.replace('T), q)', 'T), %s)' % QQ))
        W2 = 'O.Words{F.array__thaw(U32, %s), N}' % T2Q
        HD = 'F.nat__lt_trans(dw, 28n, 32n, %s_d28(dw, T, N, h), {==})' % c
        L.append('def %s_get_set%s(%s)\n    -> {%s.%s_get(%s, i) == (%s, Some{v}) : O.Words & Maybe<&1, U32>}:' % (c, sfx, pres, DEF, c, W2, W2))
        L.append('  %s_get_of(%s, N, i, v, hg, EB3.ba_same%s(dw, T, N, %s, v, %s, %s, {==}, %s_hk(dw, T, N, i, h, hg), %s_pf(dw, T, N, h), hps, hv))'
                 % (c, T2Q, sfx, P2, QQ, HD, c, c))
        L.append('')
        r = 2 - s
        XQ = 'U32.and(O.shr_bytes(WR.at(F.array__slots(U32, T), %s), U32.and(%s, 3)), 65535)' % (QQ, PK)
        L.append('def %s_get_other_sw%s(%s, +k: U32, +hgk: {U32.is_lt(k, U32.div(N, 2)) == True{} : Bool}, +hpk: {U32.and(%s, 3) == %d : U32}, +hwk: {%s == %s : Nat})\n'
                 '    -> {%s.%s_get(%s, k) == (%s, Some{%s}) : O.Words & Maybe<&1, U32>}:' % (c, sfx, pres, PK, r, QK, QQ, DEF, c, W2, W2, XK))
        L.append('  F.logic__subst(Nat, z => {%s.%s_get(%s, k) == (%s, Some{U32.and(O.shr_bytes(WR.at(F.array__slots(U32, T), z), U32.and(%s, 3)), 65535)}) : O.Words & Maybe<&1, U32>}, %s, %s, Equal.sym(Nat, %s, %s, hwk),'
                 % (DEF, c, W2, W2, PK, QQ, QK, QK, QQ))
        L.append('    %s_get_of(%s, N, k, %s, hgk, EB3.ba_other_sw%s(dw, T, N, %s, v, %s, %s, hwk, %s_hk(dw, T, N, i, h, hg), %s_pf(dw, T, N, h), hpk)))'
                 % (c, T2Q, XQ, sfx, PK, QQ, HD, c, c))
        L.append('')
        L.append('')
    body = '\n'.join(L)
    hsrc = (OBJ / ('encset_h_%s.bend' % c)).read_text()
    head = re.findall(r'^import .*$', hsrc, re.M)
    n_ = c.split('_')[0][1:]
    head += ['import ../../types/list_uint16_%s_def_generated.bend as DEF' % n_, 'import ./vu32.bend as VU', 'import ./view_u64.bend as VI',
             'import ./encset_h_%s.bend as EHc' % c, 'import ./encset_r_base.bend as EB3', 'import ./v16_rt.bend as V16']
    head = [x for k, x in enumerate(head) if x not in head[:k]]
    head += ['', '# GENERATED by encset_r (codegen). Do not edit.',
             '# The runtime set of the list %s and its composed encode: see codegen/proofs/collections/encset_r.py.' % c, '']
    return '\n'.join(head) + '\n' + body + '\n'


def out_path(c):
    return OBJ / ('encset_r_%s.bend' % c)


def main():
    run_each('encset_r', [(BASE, BASE_TEXT + '\n' + base_extra().rstrip('\n') + '\n')] + [(out_path(c), text(c)) for c in LISTS])


if __name__ == '__main__':
    main()
