#!/usr/bin/env python3
"""proofs/obj/encset_w_<list>.bend: the encode of a list of whole-word elements after one element is written (the lists of uint64).

The encode bridge of such a list (proofs/obj/encx_<list>.bend) says: for the mirror MW{dw, T, N} (a perfect tree T of depth dw holding N bytes) with
OKT(dw, T, N) (room, zero tail, whole elements, the limit), the spec encode of its value VAL = W.VALw(T, 0, N) is the runtime's bytes ENC (encx_spec).
Setting element i writes the two words x0, x1 at q = 2 i (words_win.bend's tk): T2 = tk([x0, x1], dw, T, q, 0). This file proves, symbolically:

    rwn_al, rws_items2     the window reads of the encode value are the indexed items over the slots (items2 of view_u64.bend)
    qle, dbl_le, ql_ge     the word count 2 c = 2 (N / 8) is within the room 2^dw and within the words N >> 2 in use
    valw_ul                the encode value of a tree is the Sequence of UL_L.uitems over its slots
    <c>_okt_set            OKT(dw, T, N) and i < N / 8 give OKT(dw, T2, N): the perfect tree, the room and limit (unchanged), the zero tail (the slot
                           of word N >> 2 is not one of the two written, words_win.bend's wd_after)
    <c>_vall_set           VAL(MW{dw, T2, N}) == field_set(VAL(MW{dw, T, N}), i, the element's value) (view_u64.bend's view_set_uitems)
    <c>_written            the object of the written mirror is the runtime's words_write_u64 of the old one (coll_u64.bend's u64_write)
    <c>_api_encode_set     the composed statement: the spec encode of the set value is ENC of the written mirror (encx_spec on MW{dw, T2, N})

    python3 codegen/proofs/collections/encset_w.py            # write
    python3 codegen/proofs/collections/encset_w.py --check    # nonzero exit if the output is stale
"""
import sys as _sys
import pathlib as _pathlib
_sys.path.insert(0, str(_pathlib.Path(__file__).resolve().parents[3]))  # the repository root: `codegen` is importable when this file runs as a script
import re
import sys

from codegen.core.paths import ROOT  # noqa: E402

OBJ = ROOT / 'proofs/obj'
BASE = OBJ / 'encset_w_base.bend'
LISTS = ('l131072_u64', 'l1099511627776_u64')
LISTS32 = ('l16777216_b32',)
BASE32 = OBJ / 'encset_w_base32.bend'

BASE_TEXT = '''import Base
import ../../types/schema.bend as S
import ../../types/primitive.bend as P
import ../compact/found.bend as F
import ../compact/arith.bend as A
import ../compact/reads.bend as RD
import ../../src/obj.bend as O
import ./vspec.bend as VS
import ./vbuf.bend as VB
import ./vua_rd.bend as UR
import ./vua.bend as UA
import ./view_u64.bend as VI
import ./words_win.bend as WW
import ./ulist_obj_light.bend as UL_L
import ./u32split.bend as USP
import ../nat_order.bend as Order
import ./mtree_run.bend as MR

# GENERATED by encset_w (codegen). Do not edit.
# Lemmas shared by the encode-after-set laws of the lists of uint64 (proofs/obj/encset_w_<list>.bend): see codegen/proofs/collections/encset_w.py.

def and_l(+a: Bool, +b: Bool, +e: {Bool.and(a, b) == True{} : Bool}) -> {a == True{} : Bool}:
  match a:
    case True{}: {==}
    case False{}: Empty.absurd({False{} == True{} : Bool}, F.logic__false_true(e))

def and_r(+a: Bool, +b: Bool, +e: {Bool.and(a, b) == True{} : Bool}) -> {b == True{} : Bool}:
  match a:
    case True{}: e
    case False{}: Empty.absurd({b == True{} : Bool}, F.logic__false_true(e))

def and_i(+a: Bool, +b: Bool, +ha: {a == True{} : Bool}, +hb: {b == True{} : Bool}) -> {Bool.and(a, b) == True{} : Bool}:
  match a:
    case True{}: hb
    case False{}: Empty.absurd({Bool.and(False{}, b) == True{} : Bool}, F.logic__false_true(ha))

# a window read at a word-aligned byte position is the slot
def rwn_al(+t: F.array__Tree<U32>, +j: Nat) -> {UR.RWN(t, A.quad(j)) == VB.slot(t, j) : U32}:
  +e0 = Equal.sym(Nat, Nat.add(A.quad(j), 0n), A.quad(j), F.nat__add_zero(A.quad(j)))
  +em = Equal.trans(Nat, UR.m4(A.quad(j)), UR.m4(Nat.add(A.quad(j), 0n)), 0n, Equal.cong(Nat, Nat, z => UR.m4(z), A.quad(j), Nat.add(A.quad(j), 0n), e0), UR.m4_eq(j, 0n, {==}))
  +ed = Equal.trans(Nat, UR.d4(A.quad(j)), UR.d4(Nat.add(A.quad(j), 0n)), j, Equal.cong(Nat, Nat, z => UR.d4(z), A.quad(j), Nat.add(A.quad(j), 0n), e0), UR.d4_eq(j, 0n, {==}))
  %Equal.sym(Nat, UR.m4(A.quad(j)), 0n, em) : {UA.jn(_, VB.slot(t, UR.d4(A.quad(j))), VB.slot(t, 1n+UR.d4(A.quad(j)))) == VB.slot(t, j) : U32}
  %Equal.sym(Nat, UR.d4(A.quad(j)), j, ed) : {UA.jn(0n, VB.slot(t, _), VB.slot(t, 1n+_)) == VB.slot(t, j) : U32}
  {==}

# a + 1 is 1 + a
def add_one(+a: Nat) -> {Nat.add(a, 1n) == 1n+a : Nat}:
  Equal.trans(Nat, Nat.add(a, 1n), 1n+Nat.add(a, 0n), 1n+a, F.nat__add_succ(a, 0n), Equal.cong(Nat, Nat, z => 1n+z, Nat.add(a, 0n), a, F.nat__add_zero(a)))

# the items read through the window from element i are the indexed items over the slots
def rws_items2(+k: Nat, +i: Nat, +t: F.array__Tree<U32>)
    -> {VS.uitems(k, UR.RWS(Nat.double(k), t, A.quad(Nat.double(i)))) == VI.items2(k, F.array__slots(U32, t), i) : S.Value}:
  match k:
    case 0n: {==}
    case 1n+ +c:
      +h0 = Equal.trans(U32, UR.RWN(t, A.quad(Nat.double(i))), VB.slot(t, Nat.double(i)), MR.wd(F.array__slots(U32, t), Nat.add(Nat.double(i), 0n)), rwn_al(t, Nat.double(i)),
        Equal.cong(Nat, U32, z => MR.wd(F.array__slots(U32, t), z), Nat.double(i), Nat.add(Nat.double(i), 0n), Equal.sym(Nat, Nat.add(Nat.double(i), 0n), Nat.double(i), F.nat__add_zero(Nat.double(i)))))
      +h1 = Equal.trans(U32, UR.RWN(t, A.quad(1n+Nat.double(i))), VB.slot(t, 1n+Nat.double(i)), MR.wd(F.array__slots(U32, t), Nat.add(Nat.double(i), 1n)), rwn_al(t, 1n+Nat.double(i)),
        Equal.cong(Nat, U32, z => MR.wd(F.array__slots(U32, t), z), 1n+Nat.double(i), Nat.add(Nat.double(i), 1n), Equal.sym(Nat, Nat.add(Nat.double(i), 1n), 1n+Nat.double(i), add_one(Nat.double(i)))))
      +ih = rws_items2(c, 1n+i, t)
      %Equal.sym(U32, UR.RWN(t, A.quad(Nat.double(i))), MR.wd(F.array__slots(U32, t), Nat.add(Nat.double(i), 0n)), h0) :
        {S.Items{S.UnsignedValue{P.UInt{_, UR.RWN(t, 4n+A.quad(Nat.double(i))), 0, 0, 0, 0, 0, 0}}, VS.uitems(c, UR.RWS(Nat.double(c), t, 4n+(4n+A.quad(Nat.double(i)))))} == VI.items2(1n+c, F.array__slots(U32, t), i) : S.Value}
      %Equal.sym(U32, UR.RWN(t, 4n+A.quad(Nat.double(i))), MR.wd(F.array__slots(U32, t), Nat.add(Nat.double(i), 1n)), h1) :
        {S.Items{S.UnsignedValue{P.UInt{MR.wd(F.array__slots(U32, t), Nat.add(Nat.double(i), 0n)), _, 0, 0, 0, 0, 0, 0}}, VS.uitems(c, UR.RWS(Nat.double(c), t, 4n+(4n+A.quad(Nat.double(i)))))} == VI.items2(1n+c, F.array__slots(U32, t), i) : S.Value}
      %Equal.sym(S.Value, VS.uitems(c, UR.RWS(Nat.double(c), t, A.quad(Nat.double(1n+i)))), VI.items2(c, F.array__slots(U32, t), 1n+i), ih) :
        {S.Items{S.UnsignedValue{P.UInt{MR.wd(F.array__slots(U32, t), Nat.add(Nat.double(i), 0n)), MR.wd(F.array__slots(U32, t), Nat.add(Nat.double(i), 1n)), 0, 0, 0, 0, 0, 0}}, _} == VI.items2(1n+c, F.array__slots(U32, t), i) : S.Value}
      {==}

# the encode value of a tree (the items read through the window) is the Sequence of the structural items over its slots
def valw_ul(+c: Nat, +d: Nat, +t: F.array__Tree<U32>, +pf: {F.array__perfect(U32, d, t) == True{} : Bool}, +hcap: {Nat.is_le(Nat.double(c), F.spec_common__pow2(d)) == True{} : Bool})
    -> {S.Sequence{VS.uitems(c, UR.RWS(Nat.double(c), t, 0n))} == S.Sequence{UL_L.uitems(c, F.array__slots(U32, t))} : S.Value}:
  +hroom = F.logic__subst(Nat, z => {Nat.is_le(Nat.double(c), z) == True{} : Bool}, F.spec_common__pow2(d), F.spec_common__length(U32, F.array__slots(U32, t)), Equal.sym(Nat, F.spec_common__length(U32, F.array__slots(U32, t)), F.spec_common__pow2(d), F.array__slots_length(U32, d, t, pf)), hcap)
  Equal.cong(S.Value, S.Value, z => S.Sequence{z}, VS.uitems(c, UR.RWS(Nat.double(c), t, 0n)), UL_L.uitems(c, F.array__slots(U32, t)),
    Equal.trans(S.Value, VS.uitems(c, UR.RWS(Nat.double(c), t, 0n)), VI.items2(c, F.array__slots(U32, t), 0n), UL_L.uitems(c, F.array__slots(U32, t)), rws_items2(c, 0n, t),
      Equal.sym(S.Value, UL_L.uitems(c, F.array__slots(U32, t)), VI.items2(c, F.array__slots(U32, t), 0n), VI.conv_uitems(c, F.array__slots(U32, t), hroom))))

# freezing the thawed tree changes nothing
def ft_seq(+c: Nat, +X: F.array__Tree<U32>) -> {S.Sequence{UL_L.uitems(c, F.array__slots(U32, F.array__freeze(U32, F.array__thaw(U32, X))))} == S.Sequence{UL_L.uitems(c, F.array__slots(U32, X))} : S.Value}:
  Equal.cong(F.array__Tree<U32>, S.Value, z => S.Sequence{UL_L.uitems(c, F.array__slots(U32, z))}, F.array__freeze(U32, F.array__thaw(U32, X)), X, F.array__freeze_thaw(U32, X))

# eight times is the quadruple of the double
def x8_quad2(+c: Nat) -> {VS.x8(c) == A.quad(Nat.double(c)) : Nat}:
  match c:
    case 0n: {==}
    case 1n+ +p: Equal.cong(Nat, Nat, z => 8n+z, VS.x8(p), A.quad(Nat.double(p)), x8_quad2(p))

# quad a <= quad b + 3 gives a <= b
def qle(+a: Nat, +b: Nat, +h: {Nat.is_le(A.quad(a), Nat.add(A.quad(b), 3n)) == True{} : Bool}) -> {Nat.is_le(a, b) == True{} : Bool}:
  match a b:
    case 0n _: F.nat__zero_le(b)
    case 1n+ +p 0n: Empty.absurd({Nat.is_le(1n+p, 0n) == True{} : Bool}, F.logic__false_true(h))
    case 1n+ +p 1n+ +s: qle(p, s, h)

# 2 c <= P from 8 c <= 4 P
def dbl_le(+c: Nat, +P: Nat, +h: {Nat.is_le(VS.x8(c), A.quad(P)) == True{} : Bool}) -> {Nat.is_le(Nat.double(c), P) == True{} : Bool}:
  qle(Nat.double(c), P, F.nat__le_trans(A.quad(Nat.double(c)), A.quad(P), Nat.add(A.quad(P), 3n),
    F.logic__subst(Nat, z => {Nat.is_le(z, A.quad(P)) == True{} : Bool}, VS.x8(c), A.quad(Nat.double(c)), x8_quad2(c), h), Order.below_sum(A.quad(P), 3n)))

# r + 4 Q <= 4 Q + 3 for r <= 3
def qle_add(+r: Nat, +Q: Nat, +hr: {Nat.is_le(r, 3n) == True{} : Bool}) -> {Nat.is_le(Nat.add(r, A.quad(Q)), Nat.add(A.quad(Q), 3n)) == True{} : Bool}:
  F.logic__subst(Nat, z => {Nat.is_le(Nat.add(r, A.quad(Q)), z) == True{} : Bool}, Nat.add(3n, A.quad(Q)), Nat.add(A.quad(Q), 3n), F.nat__add_comm(3n, A.quad(Q)), Order.add_right(r, 3n, A.quad(Q), hr))

# 2 c <= N >> 2 for N = 8 c
def ql_ge(+c: Nat, +N: U32, +e: {U32.to_nat(N) == VS.x8(c) : Nat}) -> {Nat.is_le(Nat.double(c), U32.to_nat(U32.shrn(N, 2n))) == True{} : Bool}:
  +r = U32.to_nat(U32.and(N, 3))
  +Q = U32.to_nat(U32.shrn(N, 2n))
  +ex = Equal.trans(Nat, VS.x8(c), U32.to_nat(N), Nat.add(r, A.quad(Q)), Equal.sym(Nat, U32.to_nat(N), VS.x8(c), e), USP.split2(N))
  +h1 = F.logic__subst(Nat, z => {Nat.is_le(VS.x8(c), z) == True{} : Bool}, VS.x8(c), Nat.add(r, A.quad(Q)), ex, F.nat__le_refl(VS.x8(c)))
  qle(Nat.double(c), Q, F.nat__le_trans(A.quad(Nat.double(c)), Nat.add(r, A.quad(Q)), Nat.add(A.quad(Q), 3n),
    F.logic__subst(Nat, z => {Nat.is_le(z, Nat.add(r, A.quad(Q))) == True{} : Bool}, VS.x8(c), A.quad(Nat.double(c)), x8_quad2(c), h1), qle_add(r, Q, RD.and_le(N, 3))))
'''

BASE32_TEXT = '''import Base
import ../../types/schema.bend as S
import ../compact/found.bend as F
import ../compact/arith.bend as A
import ../compact/reads.bend as RD
import ../../src/obj.bend as O
import ./vspec.bend as VS
import ./vbuf.bend as VB
import ./vua_rd.bend as UR
import ./vmul.bend as VM
import ./view_b32.bend as V32
import ./words_root_light.bend as WR_L
import ./words_spec.bend as WS
import ./u32split.bend as USP
import ../nat_order.bend as Order
import ./mtree_run.bend as MR
import ./encset_w_base.bend as EB

# GENERATED by encset_w (codegen). Do not edit.
# Lemmas shared by the encode-after-set laws of the lists of 32-byte elements (proofs/obj/encset_w_<list>.bend): see codegen/proofs/collections/encset_w.py.

# the words of the k elements, 8 each, are 8 k
def mulE_e8(+c: Nat) -> {VM.mulE(8n, c) == O.e8(c) : Nat}:
  match c:
    case 0n: {==}
    case 1n+ +p: Equal.cong(Nat, Nat, z => 8n+z, VM.mulE(8n, p), O.e8(p), mulE_e8(p))

def e8_le2(+a: Nat, +b: Nat, +h: {Nat.is_le(a, b) == True{} : Bool}) -> {Nat.is_le(O.e8(a), O.e8(b)) == True{} : Bool}:
  match a b:
    case 0n _: F.nat__zero_le(O.e8(b))
    case 1n+ +p 0n: Empty.absurd({Nat.is_le(O.e8(1n+p), O.e8(0n)) == True{} : Bool}, F.logic__false_true(h))
    case 1n+ +p 1n+ +s: Order.add_left(8n, O.e8(p), O.e8(s), e8_le2(p, s, h))

# M <= P from 4 M <= 4 P
def cap_gen(+M: Nat, +P: Nat, +h: {Nat.is_le(A.quad(M), A.quad(P)) == True{} : Bool}) -> {Nat.is_le(M, P) == True{} : Bool}:
  EB.qle(M, P, F.nat__le_trans(A.quad(M), A.quad(P), Nat.add(A.quad(P), 3n), h, Order.below_sum(A.quad(P), 3n)))

# M <= N >> 2 for N = 4 M
def ql_gen(+M: Nat, +N: U32, +e: {U32.to_nat(N) == A.quad(M) : Nat}) -> {Nat.is_le(M, U32.to_nat(U32.shrn(N, 2n))) == True{} : Bool}:
  +r = U32.to_nat(U32.and(N, 3))
  +Q = U32.to_nat(U32.shrn(N, 2n))
  +ex = Equal.trans(Nat, A.quad(M), U32.to_nat(N), Nat.add(r, A.quad(Q)), Equal.sym(Nat, U32.to_nat(N), A.quad(M), e), USP.split2(N))
  EB.qle(M, Q, F.nat__le_trans(A.quad(M), Nat.add(r, A.quad(Q)), Nat.add(A.quad(Q), 3n), F.logic__subst(Nat, z => {Nat.is_le(A.quad(M), z) == True{} : Bool}, A.quad(M), Nat.add(r, A.quad(Q)), ex, F.nat__le_refl(A.quad(M))),
    EB.qle_add(r, Q, RD.and_le(N, 3))))

# the items read through the window from element i are the items over the slots (eight words each)
def rws_items8(+k: Nat, +i: Nat, +t: F.array__Tree<U32>)
    -> {VM.bvit(k, 8n, UR.RWS(VM.mulE(8n, k), t, A.quad(O.e8(i)))) == WR_L.items(k, F.array__slots(U32, t), i) : S.Value}:
  match k:
    case 0n: {==}
    case 1n+ +c:
@@HJ@@
      +el = V32.elem_to(F.array__slots(U32, t), i, @@YS@@, h0, h1, h2, h3, h4, h5, h6, h7)
      +ih = rws_items8(c, 1n+i, t)
      Equal.trans(S.Value, VM.bvit(1n+c, 8n, UR.RWS(VM.mulE(8n, 1n+c), t, A.quad(O.e8(i)))), S.Items{S.BytesValue{FX.limbs([@@YS@@])}, WR_L.items(c, F.array__slots(U32, t), 1n+i)}, WR_L.items(1n+c, F.array__slots(U32, t), i),
        Equal.cong(S.Value, S.Value, z => S.Items{S.BytesValue{FX.limbs([@@YS@@])}, z}, VM.bvit(c, 8n, UR.RWS(VM.mulE(8n, c), t, A.quad(O.e8(1n+i)))), WR_L.items(c, F.array__slots(U32, t), 1n+i), ih),
        Equal.cong(S.Value, S.Value, z => S.Items{z, WR_L.items(c, F.array__slots(U32, t), 1n+i)}, S.BytesValue{FX.limbs([@@YS@@])}, S.BytesValue{WS.cb(F.array__slots(U32, t), i)}, Equal.sym(S.Value, S.BytesValue{WS.cb(F.array__slots(U32, t), i)}, S.BytesValue{FX.limbs([@@YS@@])}, el)))

# the encode value of a tree is the Sequence of the items over its slots
def valw8(+c: Nat, +t: F.array__Tree<U32>) -> {S.Sequence{VM.bvit(c, 8n, UR.RWS(VM.mulE(8n, c), t, 0n))} == S.Sequence{WR_L.items(c, F.array__slots(U32, t), 0n)} : S.Value}:
  Equal.cong(S.Value, S.Value, z => S.Sequence{z}, VM.bvit(c, 8n, UR.RWS(VM.mulE(8n, c), t, 0n)), WR_L.items(c, F.array__slots(U32, t), 0n), rws_items8(c, 0n, t))

# freezing the thawed tree changes nothing
def ft_seq8(+c: Nat, +X: F.array__Tree<U32>) -> {S.Sequence{WR_L.items(c, F.array__slots(U32, F.array__freeze(U32, F.array__thaw(U32, X))), 0n)} == S.Sequence{WR_L.items(c, F.array__slots(U32, X), 0n)} : S.Value}:
  Equal.cong(F.array__Tree<U32>, S.Value, z => S.Sequence{WR_L.items(c, F.array__slots(U32, z), 0n)}, F.array__freeze(U32, F.array__thaw(U32, X)), X, F.array__freeze_thaw(U32, X))
'''


def _b32():
    ys = ', '.join('UR.RWN(t, %dn+A.quad(O.e8(i)))' % (4 * j) for j in range(8))
    hj = []
    for j in range(8):
        y = 'UR.RWN(t, %dn+A.quad(O.e8(i)))' % (4 * j)
        hj.append('      +h%d = Equal.sym(U32, %s, MR.wd(F.array__slots(U32, t), Nat.add(O.e8(i), %dn)), Equal.trans(U32, %s, VB.slot(t, Nat.add(%dn, O.e8(i))), MR.wd(F.array__slots(U32, t), Nat.add(O.e8(i), %dn)), EB.rwn_al(t, Nat.add(%dn, O.e8(i))), '
                  'Equal.cong(Nat, U32, z => MR.wd(F.array__slots(U32, t), z), Nat.add(%dn, O.e8(i)), Nat.add(O.e8(i), %dn), F.nat__add_comm(%dn, O.e8(i)))))' % (j, y, j, y, j, j, j, j, j, j))
    return BASE32_TEXT.replace('@@HJ@@', '\n'.join(hj)).replace('@@YS@@', ys).replace("import ./encset_w_base.bend as EB", "import ./encset_w_base.bend as EB\nimport ./spec_fixed.bend as FX")


def split_top(s):
    out, depth, cur = [], 0, ''
    for ch in s:
        if ch in '([{<':
            depth += 1
        elif ch in ')]}>':
            depth -= 1
        if ch == ',' and depth == 0:
            out.append(cur.strip())
            cur = ''
        else:
            cur += ch
    out.append(cur.strip())
    return out


def conjuncts(e):
    """Bool.and(a, Bool.and(b, c)) -> [a, b, c]"""
    e = e.strip()
    if e.startswith('Bool.and(') and e.endswith(')'):
        a, b = split_top(e[len('Bool.and('):-1])
        return [a] + conjuncts(b)
    return [e]


def facts(c):
    txt = (OBJ / ('encx_%s.bend' % c)).read_text()
    imps = {a: p for p, a in re.findall(r'^import (\S+) as (\w+)', txt, re.M)}
    mo = re.search(r'^def OKT\(\+dw: Nat, \+T: FD\.array__Tree<U32>, \+N: U32\) -> Bool:\n(.*?)\ndef OK\(', txt, re.M | re.S)
    cj = conjuncts(mo.group(1))
    sch = re.search(r'^def encx_spec\(m, hok\):', txt, re.M)
    ms = re.search(r'^  \{Codec\.parts\(VAL\(m\), (.+?)\) == Some\{\[S\.Variable\{ENC\(m\)\}\]\}', txt, re.M)
    return dict(c=c, imps=imps, cj=cj, schema=ms.group(1), W=imps['W'])


def text(c):
    f = facts(c)
    cj = f['cj']
    n = len(cj)
    T2 = 'WW.tk([x0, x1], dw, T, q, 0n)'
    sub = lambda s_, t_: re.sub(r'(?<![\w.])T(?![\w.])', t_, s_)
    pre = ('+dw: Nat, +T: F.array__Tree<U32>, +N: U32, +i: U32, +q: Nat, +x0: U32, +x1: U32, +h: {E.OKT(dw, T, N) == True{} : Bool}, '
           '+hs: {U32.is_lt(i, U32.div(N, 8)) == True{} : Bool}, +hqe: {q == Nat.double(U32.to_nat(i)) : Nat}')
    args = 'dw, T, N, i, q, x0, x1, h, hs, hqe'
    rest = lambda k: cj[k] if k == n - 1 else 'Bool.and(%s, %s)' % (cj[k], rest(k + 1))
    ik = {'pf': [k for k in range(n) if 'array__perfect' in cj[k]][0], 'tz': [k for k in range(n) if 'tail_zero' in cj[k]][0],
          'ch': [k for k in range(n) if 'CHKw' in cj[k]][0], 'hn': [k for k in range(n) if 'A.quad(VB.pw(dw))' in cj[k]][0]}
    L = []

    def common(inner_pf=True):
        out = []
        prf = ['h']
        for k in range(1, n):
            prf.append('EB.and_r(%s, %s, %s)' % (cj[k - 1], rest(k), prf[k - 1]))
        for k in range(n):
            out.append('  +r%d = %s' % (k, prf[k]))
        for k in range(n):
            out.append('  +p%d = %s' % (k, 'r%d' % k if k == n - 1 else 'EB.and_l(%s, %s, r%d)' % (cj[k], rest(k + 1), k)))
        out.append('  +J = U32.to_nat(i)')
        out.append('  +eN = W.eLc(T, 0n, 0, N, p%d)' % ik['ch'])
        out.append('  +hlt = F.logic__subst(Bool, z => {z == True{} : Bool}, U32.is_lt(i, U32.div(N, 8)), Nat.is_lt(J, W.CQ(N)), F.u32__is_lt_nat(i, U32.div(N, 8)), hs)')
        out.append('  +hcap = EB.dbl_le(W.CQ(N), VB.pw(dw), F.logic__subst(Nat, z => {Nat.is_le(z, A.quad(VB.pw(dw))) == True{} : Bool}, U32.to_nat(N), VS.x8(W.CQ(N)), eN, p%d))' % ik['hn'])
        out.append('  +hm = VI.mono(1n+J, W.CQ(N), F.nat__lt_succ_le_succ(J, W.CQ(N), hlt))')
        out.append('  +e2 = Equal.trans(Nat, Nat.add(q, 2n), Nat.add(Nat.double(J), 2n), Nat.double(1n+J), Equal.cong(Nat, Nat, z => Nat.add(z, 2n), q, Nat.double(J), hqe), VI.blk(J))')
        out.append('  +hy = F.logic__subst(Nat, z => {Nat.is_le(z, Nat.double(W.CQ(N))) == True{} : Bool}, Nat.double(1n+J), Nat.add(q, 2n), Equal.sym(Nat, Nat.add(q, 2n), Nat.double(1n+J), e2), hm)')
        out.append('  +hb = F.nat__le_trans(Nat.add(q, 2n), Nat.double(W.CQ(N)), F.spec_common__pow2(dw), hy, hcap)')
        out.append('  +pf2 = WW.tk_perfect([x0, x1], dw, T, q, 0n, p%d)' % ik['pf'])
        return out

    L.append('# ---- the premises of the encode bridge for the written mirror ----')
    L.append('def %s_okt_set(%s)\n    -> {E.OKT(dw, %s, N) == True{} : Bool}:' % (c, pre, T2))
    L += common()
    L.append('  +hql = F.nat__le_trans(Nat.add(q, 2n), Nat.double(W.CQ(N)), U32.to_nat(U32.shrn(N, 2n)), hy, EB.ql_ge(W.CQ(N), N, eN))')
    L.append('  +sl = WW.wd_after([x0, x1], dw, T, q, VYS.QL(N), hql, hb, p%d)' % ik['pf'])
    L.append('  +tz2 = F.logic__subst(U32, z => {O.tail_zero(U32.and(N, 3), z) == True{} : Bool}, VB.slot(T, VYS.QL(N)), VB.slot(%s, VYS.QL(N)), Equal.sym(U32, VB.slot(%s, VYS.QL(N)), VB.slot(T, VYS.QL(N)), sl), p%d)' % (T2, T2, ik['tz']))
    prf = {ik['pf']: 'pf2', ik['tz']: 'tz2'}

    def chain(k):
        if k == n - 1:
            return prf.get(k, 'p%d' % k)
        return 'EB.and_i(%s, %s, %s, %s)' % (sub(cj[k], T2), sub(rest(k + 1), T2), prf.get(k, 'p%d' % k), chain(k + 1))
    L.append('  ' + chain(0))
    L.append('')
    L.append('# ---- the value of the written mirror: the old value with item i replaced ----')
    L.append('def %s_vall_set(%s)\n    -> {W.VALw(%s, 0n, N) == VSE.field_set(W.VALw(T, 0n, N), U32.to_nat(i), S.UnsignedValue{P.UInt{x0, x1, 0, 0, 0, 0, 0, 0}}) : S.Value}:' % (c, pre, T2))
    L += common()
    UV = 'S.UnsignedValue{P.UInt{x0, x1, 0, 0, 0, 0, 0, 0}}'
    L.append('  +e0 = EB.valw_ul(W.CQ(N), dw, T, p%d, hcap)' % ik['pf'])
    L.append('  +e1 = EB.valw_ul(W.CQ(N), dw, %s, pf2, hcap)' % T2)
    L.append('  +vs = VI.view_set_uitems(W.CQ(N), dw, T, x0, x1, J, q, hqe, hb, p%d, hcap)' % ik['pf'])
    SQ = lambda t_: 'S.Sequence{UL_L.uitems(W.CQ(N), F.array__slots(U32, %s))}' % t_
    SQF = lambda t_: 'S.Sequence{UL_L.uitems(W.CQ(N), F.array__slots(U32, F.array__freeze(U32, F.array__thaw(U32, %s))))}' % t_
    L.append('  +e3 = Equal.trans(S.Value, %s, %s, VSE.field_set(%s, J, %s), Equal.sym(S.Value, %s, %s, EB.ft_seq(W.CQ(N), %s)),' % (SQ(T2), SQF(T2), SQ('T'), UV, SQF(T2), SQ(T2), T2))
    L.append('    Equal.trans(S.Value, %s, VSE.field_set(%s, J, %s), VSE.field_set(%s, J, %s), vs,' % (SQF(T2), SQF('T'), UV, SQ('T'), UV))
    L.append('      Equal.cong(S.Value, S.Value, z => VSE.field_set(z, J, %s), %s, %s, EB.ft_seq(W.CQ(N), T))))' % (UV, SQF('T'), SQ('T')))
    L.append('  %%Equal.sym(S.Value, W.VALw(%s, 0n, N), %s, e1) :' % (T2, SQ(T2)))
    L.append('    {_ == VSE.field_set(W.VALw(T, 0n, N), J, %s) : S.Value}' % UV)
    L.append('  %%Equal.sym(S.Value, W.VALw(T, 0n, N), %s, e0) :' % SQ('T'))
    L.append('    {%s == VSE.field_set(_, J, %s) : S.Value}' % (SQ(T2), UV))
    L.append('  e3')
    L.append('')
    L.append('# ---- the written object: the mirror of the updated tree is the runtime\'s words_write_u64 of the old one ----')
    L.append('def %s_written(+dw: Nat, +T: F.array__Tree<U32>, +N: U32, +i: U32, +q: Nat, +x0: U32, +x1: U32, +hd: {Nat.is_lt(dw, 32n) == True{} : Bool}, +pf: {F.array__perfect(U32, dw, T) == True{} : Bool}, '
             '+hq: {U32.to_nat(U32.shrn((i * 8 : U32), 2n)) == q : Nat}, +hr: {Nat.is_le(Nat.add(q, 2n), F.spec_common__pow2(dw)) == True{} : Bool})\n'
             '    -> {E.TH(E.MW{dw, %s, N}) == O.words_write_u64(E.TH(E.MW{dw, T, N}), (i * 8 : U32), O.U64{x0, x1}) : O.Words}:' % (c, T2))
    L.append('  Equal.sym(O.Words, O.words_write_u64(O.Words{F.array__thaw(U32, T), N}, (i * 8 : U32), O.U64{x0, x1}), E.TH(E.MW{dw, %s, N}), CW.u64_write(dw, T, N, (i * 8 : U32), q, hd, pf, hq, hr, x0, x1))' % T2)
    L.append('')
    L.append('# ---- the composed statement: the spec encode of the set value is the bytes of the written mirror ----')
    L.append('def %s_api_encode_set(%s)\n    -> {Codec.parts(VSE.field_set(E.VAL(E.MW{dw, T, N}), U32.to_nat(i), %s), %s) == Some{[S.Variable{E.ENC(E.MW{dw, %s, N})}]} : Maybe<&2, +List<S.Part>>}:' % (c, pre, UV, f['schema'], T2))
    L.append('  %%%s_vall_set(%s) :' % (c, args))
    L.append('    {Codec.parts(_, %s) == Some{[S.Variable{E.ENC(E.MW{dw, %s, N})}]} : Maybe<&2, +List<S.Part>>}' % (f['schema'], T2))
    L.append('  E.encx_spec(E.MW{dw, %s, N}, %s_okt_set(%s))' % (T2, c, args))
    body = '\n'.join(L)
    fixed = {'S': '../../types/schema.bend', 'P': '../../types/primitive.bend', 'F': '../compact/found.bend', 'FD': '../compact/found.bend', 'A': '../compact/arith.bend',
             'VS': './vspec.bend', 'VSE': './value_set.bend', 'VB': './vbuf.bend', 'VI': './view_u64.bend', 'WW': './words_win.bend', 'UL_L': './ulist_obj_light.bend', 'O': '../../src/obj.bend',
             'Codec': '../../spec/codec.bend', 'Spec': '../../spec/fulu_schemas.bend', 'VYS': './vbytes.bend', 'EB': './encset_w_base.bend', 'E': './encx_%s.bend' % c,
             'W': f['W'], 'CW': './coll_u64.bend'}
    imps = dict(fixed)
    head = ['import Base'] + ['import %s as %s' % (pth, a) for a, pth in imps.items()]
    head += ['', '# GENERATED by encset_w (codegen). Do not edit.',
             '# The encode of the list %s after one element is written, stated per element: see codegen/proofs/collections/encset_w.py.' % c, '']
    return '\n'.join(head) + '\n' + body + '\n'


def text32(c):
    f = facts(c)
    cj = f['cj']
    n = len(cj)
    X = ['x%d' % j for j in range(8)]
    XS = ', '.join(X)
    T2 = 'WW.tk([%s], dw, T, q, 0n)' % XS
    sub = lambda s_, t_: re.sub(r'(?<![\w.])T(?![\w.])', t_, s_)
    pre = ('+dw: Nat, +T: F.array__Tree<U32>, +N: U32, +i: U32, +q: Nat, ' + ', '.join('+%s: U32' % x for x in X) + ', +h: {E.OKT(dw, T, N) == True{} : Bool}, '
           '+hs: {U32.is_lt(i, U32.div(N, 32)) == True{} : Bool}, +hqe: {q == O.e8(U32.to_nat(i)) : Nat}')
    args = 'dw, T, N, i, q, %s, h, hs, hqe' % XS
    rest = lambda k: cj[k] if k == n - 1 else 'Bool.and(%s, %s)' % (cj[k], rest(k + 1))
    ik = {'pf': [k for k in range(n) if 'array__perfect' in cj[k]][0], 'tz': [k for k in range(n) if 'tail_zero' in cj[k]][0],
          'ch': [k for k in range(n) if 'CHKw' in cj[k]][0], 'hn': [k for k in range(n) if 'A.quad(VB.pw(dw))' in cj[k]][0]}
    UV = 'S.BytesValue{FX.limbs([%s])}' % XS
    L = []

    def common():
        out = []
        prf = ['h']
        for k in range(1, n):
            prf.append('EB.and_r(%s, %s, %s)' % (cj[k - 1], rest(k), prf[k - 1]))
        for k in range(n):
            out.append('  +r%d = %s' % (k, prf[k]))
        for k in range(n):
            out.append('  +p%d = %s' % (k, 'r%d' % k if k == n - 1 else 'EB.and_l(%s, %s, r%d)' % (cj[k], rest(k + 1), k)))
        out.append('  +J = U32.to_nat(i)')
        out.append('  +e4 = W.eqw(N, p%d)' % ik['ch'])
        out.append('  +hlt = F.logic__subst(Bool, z => {z == True{} : Bool}, U32.is_lt(i, U32.div(N, 32)), Nat.is_lt(J, W.CC(N)), F.u32__is_lt_nat(i, U32.div(N, 32)), hs)')
        out.append('  +hcap = B32.cap_gen(W.MQ(N), VB.pw(dw), F.logic__subst(Nat, z => {Nat.is_le(z, A.quad(VB.pw(dw))) == True{} : Bool}, U32.to_nat(N), A.quad(W.MQ(N)), e4, p%d))' % ik['hn'])
        out.append('  +hm = B32.e8_le2(1n+J, W.CC(N), F.nat__lt_succ_le_succ(J, W.CC(N), hlt))')
        out.append('  +hM = F.logic__subst(Nat, z => {Nat.is_le(O.e8(1n+J), z) == True{} : Bool}, O.e8(W.CC(N)), VM.mulE(8n, W.CC(N)), Equal.sym(Nat, VM.mulE(8n, W.CC(N)), O.e8(W.CC(N)), B32.mulE_e8(W.CC(N))), hm)')
        out.append('  +e2 = Equal.trans(Nat, Nat.add(q, 8n), Nat.add(O.e8(J), 8n), O.e8(1n+J), Equal.cong(Nat, Nat, z => Nat.add(z, 8n), q, O.e8(J), hqe), V32.blk(J))')
        out.append('  +hy = F.logic__subst(Nat, z => {Nat.is_le(z, W.MQ(N)) == True{} : Bool}, O.e8(1n+J), Nat.add(q, 8n), Equal.sym(Nat, Nat.add(q, 8n), O.e8(1n+J), e2), hM)')
        out.append('  +hb = F.nat__le_trans(Nat.add(q, 8n), W.MQ(N), F.spec_common__pow2(dw), hy, hcap)')
        out.append('  +pf2 = WW.tk_perfect([%s], dw, T, q, 0n, p%d)' % (XS, ik['pf']))
        return out

    L.append('# ---- the premises of the encode bridge for the written mirror ----')
    L.append('def %s_okt_set(%s)\n    -> {E.OKT(dw, %s, N) == True{} : Bool}:' % (c, pre, T2))
    L += common()
    L.append('  +hql = F.nat__le_trans(Nat.add(q, 8n), W.MQ(N), U32.to_nat(U32.shrn(N, 2n)), hy, B32.ql_gen(W.MQ(N), N, e4))')
    L.append('  +sl = WW.wd_after([%s], dw, T, q, VYS.QL(N), hql, hb, p%d)' % (XS, ik['pf']))
    L.append('  +tz2 = F.logic__subst(U32, z => {O.tail_zero(U32.and(N, 3), z) == True{} : Bool}, VB.slot(T, VYS.QL(N)), VB.slot(%s, VYS.QL(N)), Equal.sym(U32, VB.slot(%s, VYS.QL(N)), VB.slot(T, VYS.QL(N)), sl), p%d)' % (T2, T2, ik['tz']))
    prf = {ik['pf']: 'pf2', ik['tz']: 'tz2'}

    def chain(k):
        if k == n - 1:
            return prf.get(k, 'p%d' % k)
        return 'EB.and_i(%s, %s, %s, %s)' % (sub(cj[k], T2), sub(rest(k + 1), T2), prf.get(k, 'p%d' % k), chain(k + 1))
    L.append('  ' + chain(0))
    L.append('')
    L.append('# ---- the value of the written mirror: the old value with item i replaced ----')
    L.append('def %s_vall_set(%s)\n    -> {W.VALw(%s, 0n, N) == VSE.field_set(W.VALw(T, 0n, N), U32.to_nat(i), %s) : S.Value}:' % (c, pre, T2, UV))
    L += common()
    L.append('  +e0 = B32.valw8(W.CC(N), T)')
    L.append('  +e1 = B32.valw8(W.CC(N), %s)' % T2)
    L.append('  +vs = V32.view_set(W.CC(N), dw, T, %s, J, q, hqe, hb, p%d)' % (XS, ik['pf']))
    SQ = lambda t_: 'S.Sequence{WR_L.items(W.CC(N), F.array__slots(U32, %s), 0n)}' % t_
    SQF = lambda t_: 'S.Sequence{WR_L.items(W.CC(N), F.array__slots(U32, F.array__freeze(U32, F.array__thaw(U32, %s))), 0n)}' % t_
    L.append('  +e3 = Equal.trans(S.Value, %s, %s, VSE.field_set(%s, J, %s), Equal.sym(S.Value, %s, %s, B32.ft_seq8(W.CC(N), %s)),' % (SQ(T2), SQF(T2), SQ('T'), UV, SQF(T2), SQ(T2), T2))
    L.append('    Equal.trans(S.Value, %s, VSE.field_set(%s, J, %s), VSE.field_set(%s, J, %s), vs,' % (SQF(T2), SQF('T'), UV, SQ('T'), UV))
    L.append('      Equal.cong(S.Value, S.Value, z => VSE.field_set(z, J, %s), %s, %s, B32.ft_seq8(W.CC(N), T))))' % (UV, SQF('T'), SQ('T')))
    L.append('  %%Equal.sym(S.Value, W.VALw(%s, 0n, N), %s, e1) :' % (T2, SQ(T2)))
    L.append('    {_ == VSE.field_set(W.VALw(T, 0n, N), J, %s) : S.Value}' % UV)
    L.append('  %%Equal.sym(S.Value, W.VALw(T, 0n, N), %s, e0) :' % SQ('T'))
    L.append('    {%s == VSE.field_set(_, J, %s) : S.Value}' % (SQ(T2), UV))
    L.append('  e3')
    L.append('')
    L.append('# ---- the written object: the mirror of the updated tree is the runtime\'s Bytes32_into_words of the old one ----')
    L.append('def %s_written(+dw: Nat, +T: F.array__Tree<U32>, +N: U32, +i: U32, +q: Nat, %s, +hd: {Nat.is_lt(dw, 32n) == True{} : Bool}, +pf: {F.array__perfect(U32, dw, T) == True{} : Bool}, '
             '+hq: {U32.to_nat(U32.shrn((i * 32 : U32), 2n)) == q : Nat}, +hr: {Nat.is_le(Nat.add(q, 8n), F.spec_common__pow2(dw)) == True{} : Bool})\n'
             '    -> {E.TH(E.MW{dw, %s, N}) == FuluBytes32_d.Bytes32_into_words(E.TH(E.MW{dw, T, N}), (i * 32 : U32), FuluBytes32_d.Bytes32{%s}) : O.Words}:' % (c, ', '.join('+%s: U32' % x for x in X), T2, XS))
    L.append('  Equal.sym(O.Words, FuluBytes32_d.Bytes32_into_words(O.Words{F.array__thaw(U32, T), N}, (i * 32 : U32), FuluBytes32_d.Bytes32{%s}), E.TH(E.MW{dw, %s, N}), CW.b32_write(dw, T, N, (i * 32 : U32), q, hd, pf, hq, hr, %s))' % (XS, T2, XS))
    L.append('')
    L.append('# ---- the composed statement: the spec encode of the set value is the bytes of the written mirror ----')
    L.append('def %s_api_encode_set(%s)\n    -> {Codec.parts(VSE.field_set(E.VAL(E.MW{dw, T, N}), U32.to_nat(i), %s), %s) == Some{[S.Variable{E.ENC(E.MW{dw, %s, N})}]} : Maybe<&2, +List<S.Part>>}:' % (c, pre, UV, f['schema'], T2))
    L.append('  %%%s_vall_set(%s) :' % (c, args))
    L.append('    {Codec.parts(_, %s) == Some{[S.Variable{E.ENC(E.MW{dw, %s, N})}]} : Maybe<&2, +List<S.Part>>}' % (f['schema'], T2))
    L.append('  E.encx_spec(E.MW{dw, %s, N}, %s_okt_set(%s))' % (T2, c, args))
    body = '\n'.join(L)
    fixed = {'S': '../../types/schema.bend', 'F': '../compact/found.bend', 'FD': '../compact/found.bend', 'A': '../compact/arith.bend',
             'VS': './vspec.bend', 'VSE': './value_set.bend', 'VB': './vbuf.bend', 'VM': './vmul.bend', 'V32': './view_b32.bend', 'WR_L': './words_root_light.bend', 'WW': './words_win.bend',
             'O': '../../src/obj.bend', 'FX': './spec_fixed.bend', 'Codec': '../../spec/codec.bend', 'Spec': '../../spec/fulu_schemas.bend', 'VYS': './vbytes.bend',
             'EB': './encset_w_base.bend', 'B32': './encset_w_base32.bend', 'E': './encx_%s.bend' % c, 'W': f['W'], 'CW': './coll_b32.bend',
             'FuluBytes32_d': '../../types/FuluBytes32_def_generated.bend'}
    head = ['import Base'] + ['import %s as %s' % (pth, a) for a, pth in fixed.items()]
    head += ['', '# GENERATED by encset_w (codegen). Do not edit.',
             '# The encode of the list %s after one element is written, stated per element: see codegen/proofs/collections/encset_w.py.' % c, '']
    return '\n'.join(head) + '\n' + body + '\n'


def out_path(c):
    return OBJ / ('encset_w_%s.bend' % c)


def main():
    outs = [(BASE, BASE_TEXT), (BASE32, _b32())] + [(out_path(c), text(c)) for c in LISTS] + [(out_path(c), text32(c)) for c in LISTS32]
    stale = False
    for o, t in outs:
        if '--check' in sys.argv:
            if not o.exists() or o.read_text() != t:
                print('stale: %s' % o.name)
                stale = True
            continue
        if not o.exists() or o.read_text() != t:
            o.write_text(t)
        print('encset_w: proofs/obj/%s' % o.name)
    if '--check' in sys.argv:
        if stale:
            sys.exit(1)
        print('encset_w: up to date')


if __name__ == '__main__':
    main()
