#!/usr/bin/env python3
"""proofs/obj/halfword.bend: the bytes of a word after a halfword (two bytes) is merged into it.

The uint16 lists store two elements per word; a set of element j writes the halfword at byte offset s = 0 or 2 of the word q with O.merge_word(old, v, s, 2)
(mask_at(s, 2), view_bytes.bend does the same for one byte). The bytes of the written word are the low byte of v at s, the next byte of v at s + 1 (v >> 8) and the
old bytes elsewhere; no bound on v is needed (the mask keeps two bytes). Per offset s and byte j (bit patterns of the two words, as byte_bits.bend):

    hw_go_<s>_<j>      lo8 of byte j of the merged word is the bits of v (j = s, s + 1) or of old (otherwise)
    hw_rw_<s>_<j>      the same through U32.and(.., 255)
    limb_hw_<s>        I.limb(merge_word(old, v, s, 2)) is the limbs of old with the bytes s and s + 1 replaced
    limbs_upd_hw_<s>   the bytes of a word list after the word q is rewritten are the old bytes with two replaced (VS.list_set twice)

    python3 codegen/proofs/collections/halfword.py            # write
    python3 codegen/proofs/collections/halfword.py --check    # nonzero exit if the output is stale
"""
import sys as _sys
import pathlib as _pathlib
_sys.path.insert(0, str(_pathlib.Path(__file__).resolve().parents[3]))  # the repository root: `codegen` is importable when this file runs as a script
import sys

from codegen.core.paths import ROOT  # noqa: E402

OUT = ROOT / 'proofs/obj/halfword.bend'

HEAD = '''import Base
import ../../src/obj.bend as O
import ../../src/primitives.bend as I
import ../compact/found.bend as F
import ./u32bits.bend as UB
import ./word_mul.bend as WM
import ./value_set.bend as VS
import ./spec_fixed.bend as FX
import ./words_rw.bend as WR
import ./view_bytes.bend as VW

# GENERATED by halfword (codegen). Do not edit.
# The bytes of a word after a halfword is merged into it: see codegen/proofs/collections/halfword.py.

'''


def wpat(bits, tail='WNil{}'):
    s_ = tail
    for b in reversed(bits):
        s_ = 'WCon{%s, %s}' % (b, s_)
    return s_


Z24 = 'Word.zero(24n)'
XS = ['x%d' % k for k in range(32)]
YS = ['y%d' % k for k in range(32)]


def merged(s):
    M = 'O.mask_at(%d, 2)' % s
    SHV = 'v' if s == 0 else 'U32.shln(v, 16n)'
    return 'U32.or(U32.and(old, U32.not(%s)), U32.and(%s, %s))' % (M, SHV, M)


def target_lo(s, j):
    if j == s:
        return 'UB.lo8(v)'
    if j == s + 1:
        return 'UB.lo8(O.shr_bytes(v, 1))'
    return 'UB.lo8(O.shr_bytes(old, %d))' % j


def target_and(s, j):
    if j == s:
        return 'U32.and(v, 255)'
    if j == s + 1:
        return 'U32.and(O.shr_bytes(v, 1), 255)'
    return 'U32.and(O.shr_bytes(old, %d), 255)' % j


def go(s, j):
    inm = j in (s, s + 1)
    E, T, lem = [], [], []
    for b in range(8):
        P = 8 * j + b
        yi = P - 8 * s
        if inm:
            E.append('Bool.or(Bool.and(x%d, False{}), Bool.and(y%d, True{}))' % (P, yi))
            T.append('y%d' % yi)
            lem.append('UB.sel(x%d, y%d)' % (P, yi))
        else:
            Y = 'y%d' % yi if yi >= 0 else 'False{}'
            E.append('Bool.or(Bool.and(x%d, True{}), Bool.and(%s, False{}))' % (P, Y))
            T.append('x%d' % P)
            lem.append('UB.sel2(x%d, %s)' % (P, Y))
    L = ['def hw_go_%d_%d(+old: U32, +v: U32) -> {UB.lo8(O.shr_bytes(%s, %d)) == %s : U32}:' % (s, j, merged(s), j, target_lo(s, j))]
    L.append('  match old:')
    L.append('    case U32{%s}:' % wpat(['+' + x for x in XS]))
    L.append('      match v:')
    L.append('        case U32{%s}:' % wpat(['+' + y for y in YS]))
    R = 'U32{%s}' % wpat(T, Z24)
    for k in range(8):
        cur = T[:k] + ['_'] + E[k + 1:]
        L.append('          %%Equal.sym(Bool, %s, %s, %s) : {U32{%s} == %s : U32}' % (E[k], T[k], lem[k], wpat(cur, Z24), R))
    L.append('          {==}')
    L.append('')
    return L


def rw(s, j):
    Zx = 'O.shr_bytes(O.merge_word(old, v, %d, 2), %d)' % (s, j)
    if j == s:
        inner = 'v'
    elif j == s + 1:
        inner = 'O.shr_bytes(v, 1)'
    else:
        inner = 'O.shr_bytes(old, %d)' % j
    L = ['def hw_rw_%d_%d(+old: U32, +v: U32) -> {U32.and(%s, 255) == %s : U32}:' % (s, j, Zx, target_and(s, j))]
    L.append('  %%Equal.sym(U32, U32.and(%s, 255), UB.lo8(%s), UB.and255(%s)) : {_ == %s : U32}' % (Zx, Zx, Zx, target_and(s, j)))
    L.append('  %%Equal.sym(U32, %s, %s, UB.and255(%s)) : {UB.lo8(%s) == _ : U32}' % (target_and(s, j), target_lo(s, j), inner, Zx))
    if s == 2:
        M = 'O.mask_at(2, 2)'
        L.append('  %%Equal.sym(U32, U32.mul(v, 65536), U32.shln(v, 16n), WM.mul65536(v)) : {UB.lo8(O.shr_bytes(U32.or(U32.and(old, U32.not(%s)), U32.and(_, %s)), %d)) == %s : U32}' % (M, M, j, target_lo(s, j)))
    L.append('  hw_go_%d_%d(old, v)' % (s, j))
    L.append('')
    return L


LO = 'U32.and(v, 255)'
HI = 'U32.and(U32.shrn(v, 8n), 255)'


def old_limb(s_):
    return '[U32.and(old, 255), U32.and(U32.shrn(old, 8n), 255), U32.and(U32.shrn(old, 16n), 255), U32.shrn(old, 24n)]'


def limb(s):
    M = 'O.merge_word(old, v, %d, 2)' % s
    LHS = ['U32.and(%s, 255)' % M, 'U32.and(U32.shrn(%s, 8n), 255)' % M, 'U32.and(U32.shrn(%s, 16n), 255)' % M, 'U32.shrn(%s, 24n)' % M]
    OLD = ['U32.and(old, 255)', 'U32.and(U32.shrn(old, 8n), 255)', 'U32.and(U32.shrn(old, 16n), 255)', 'U32.shrn(old, 24n)']
    RHS = list(OLD)
    RHS[s] = LO
    RHS[s + 1] = HI
    eqs = []
    for j in range(4):
        if j < 3:
            eqs.append('hw_rw_%d_%d(old, v)' % (s, j))
        else:
            e = 'Equal.trans(U32, U32.shrn(%s, 24n), U32.and(U32.shrn(%s, 24n), 255), %s, Equal.sym(U32, U32.and(U32.shrn(%s, 24n), 255), U32.shrn(%s, 24n), VW.top_byte(%s)), hw_rw_%d_3(old, v))' % (
                M, M, target_and(s, 3), M, M, M, s)
            if s == 0:
                e = 'Equal.trans(U32, U32.shrn(%s, 24n), %s, U32.shrn(old, 24n), %s, VW.top_byte(old))' % (M, target_and(s, 3), e)
            eqs.append(e)
    L = ['def limb_hw_%d(+old: U32, +v: U32) -> {I.limb(%s) == VS.list_set(VS.list_set(I.limb(old), %dn, %s), %dn, %s) : +List<U32>}:' % (s, M, s, LO, s + 1, HI)]
    for j in range(4):
        cur = RHS[:j] + ['_'] + LHS[j + 1:]
        prev = RHS[:j] + LHS[j:]
        L.append('  %%Equal.sym(U32, %s, %s, %s) : {[%s] == [%s] : +List<U32>}' % (LHS[j], RHS[j], eqs[j], ', '.join(cur), ', '.join(RHS)))
    L.append('  {==}')
    L.append('')
    return L


def upd(s):
    LS2 = lambda X, qe, lit0: 'VS.list_set(VS.list_set(%s, %s, %s), %s, %s)' % (X, lit0[0], LO, lit0[1], HI)
    idx = lambda qe: ('Nat.add(Nat.double(Nat.double(%s)), %dn)' % (qe, s), 'Nat.add(Nat.double(Nat.double(%s)), %dn)' % (qe, s + 1))
    L = ['def limbs_upd_hw_%d(+W: List<&2, U32>, +q: Nat, +v: U32)' % s,
         '    -> {FX.limbs(F.spec_common__update(U32, W, q, O.merge_word(WR.at(W, q), v, %d, 2))) == %s : +List<U32>}:' % (s, LS2('FX.limbs(W)', 'q', idx('q')))]
    L.append('  match W q:')
    L.append('    case Nil{} _: {==}')
    L.append('    case Con{h, t} 0n:')
    L.append('      %%Equal.sym(+List<U32>, I.limb(O.merge_word(h, v, %d, 2)), VS.list_set(VS.list_set(I.limb(h), %dn, %s), %dn, %s), limb_hw_%d(h, v)) :' % (s, s, LO, s + 1, HI, s))
    L.append('        {List.append(&2, U32, _, FX.limbs(t)) == VS.list_set(VS.list_set(List.append(&2, U32, I.limb(h), FX.limbs(t)), %dn, %s), %dn, %s) : +List<U32>}' % (s, LO, s + 1, HI))
    L.append('      {==}')
    L.append('    case Con{h, t} 1n+p:')
    L.append('      %%Equal.sym(+List<U32>, FX.limbs(F.spec_common__update(U32, t, p, O.merge_word(WR.at(t, p), v, %d, 2))), %s, limbs_upd_hw_%d(t, p, v)) :' % (s, LS2('FX.limbs(t)', 'p', idx('p')), s))
    L.append('        {List.append(&2, U32, I.limb(h), _) == %s : +List<U32>}' % LS2('List.append(&2, U32, I.limb(h), FX.limbs(t))', '1n+p', idx('1n+p')))
    L.append('      {==}')
    L.append('')
    return L


def text():
    L = []
    for s in (0, 2):
        for j in range(4):
            L += go(s, j)
            L += rw(s, j)
    for s in (0, 2):
        L += limb(s)
        L += upd(s)
    return HEAD + '\n'.join(L) + '\n'


def main():
    t = text()
    if '--check' in sys.argv:
        if not OUT.exists() or OUT.read_text() != t:
            print('stale: halfword.bend')
            sys.exit(1)
        print('halfword: up to date')
        return
    if not OUT.exists() or OUT.read_text() != t:
        OUT.write_text(t)
    print('halfword: proofs/obj/halfword.bend')


if __name__ == '__main__':
    main()
