#!/usr/bin/env python3
"""proofs/obj/halfword16.bend: the halfword read of a word after a halfword is merged into it.

halfword.bend states the bytes of O.merge_word(old, v, s, 2) one at a time. The runtime reads an element of a uint16 list with keep(2, shr_bytes(word, p & 3)), that is
shr_bytes(word, r) & 65535 for the offset r = 0 or 2, so the same facts are needed for the sixteen bits at once (bit patterns of the two words, as halfword.bend):

    lo16, and16      z & 65535 is the first sixteen bits of z over a zero tail
    hw16_go_<s>_<r>  the first sixteen bits of shr_bytes(merged, r) are the bits of v (r = s) or of old (r != s)
    hw16_rw_<s>_<r>  shr_bytes(O.merge_word(old, v, s, 2), r) & 65535 is v & 65535 (r = s) or shr_bytes(old, r) & 65535 (r != s)
    and16_le         a value that fits sixteen bits is its own low sixteen bits: U32.is_le(v, 65535) == True gives v & 65535 == v

    python3 codegen/proofs/collections/halfword16.py            # write
    python3 codegen/proofs/collections/halfword16.py --check    # nonzero exit if the output is stale
"""
import sys as _sys
import pathlib as _pathlib
_sys.path.insert(0, str(_pathlib.Path(__file__).resolve().parents[3]))  # the repository root: `codegen` is importable when this file runs as a script
import sys

from codegen.core.paths import ROOT  # noqa: E402
from codegen.core.shared_laws import run_single  # noqa: E402

OUT = ROOT / 'proofs/obj/halfword16.bend'

HEAD = '''import Base
import ../../src/obj.bend as O
import ./u32bits.bend as UB
import ./word_mul.bend as WM
import ./v16_rt.bend as V16

# GENERATED by halfword16 (codegen). Do not edit.
# The halfword read of a word after a halfword is merged into it: see codegen/proofs/collections/halfword16.py.

'''


def wpat(bits, tail='WNil{}'):
    s_ = tail
    for b in reversed(bits):
        s_ = 'WCon{%s, %s}' % (b, s_)
    return s_


Z16 = 'Word.zero(16n)'
XS = ['x%d' % k for k in range(32)]
YS = ['y%d' % k for k in range(32)]
BS = ['b%d' % k for k in range(16)]


def merged(s):
    M = 'O.mask_at(%d, 2)' % s
    SHV = 'v' if s == 0 else 'U32.shln(v, 16n)'
    return 'U32.or(U32.and(old, U32.not(%s)), U32.and(%s, %s))' % (M, SHV, M)


def inner(s, r):
    return 'v' if r == s else 'O.shr_bytes(old, %d)' % r


def target_lo(s, r):
    return 'lo16(%s)' % inner(s, r)


def target_and(s, r):
    return 'U32.and(%s, 65535)' % inner(s, r)


def lo16_and16():
    L = ['def lo16(z: U32) -> U32:', '  match z:',
         '    case U32{%s}: U32{%s}' % (wpat(BS, 't'), wpat(BS, Z16)), '']
    L.append('def and16(+z: U32) -> {U32.and(z, 65535) == lo16(z) : U32}:')
    L.append('  match z:')
    L.append('    case U32{%s}:' % wpat(['+' + b for b in BS], '+t'))
    A = ['Bool.and(%s, True{})' % b for b in BS]
    L.append('      %%Equal.sym(Word(16n), Word.and(16n, t, Word.zero(16n)), Word.zero(16n), UB.wand_zero(16n, t)) : {U32{%s} == U32{%s} : U32}' % (wpat(A, '_'), wpat(BS, Z16)))
    for k in range(16):
        cur = BS[:k] + ['_'] + A[k + 1:]
        L.append('      %%Equal.sym(Bool, Bool.and(b%d, True{}), b%d, UB.band_true(b%d)) : {U32{%s} == U32{%s} : U32}' % (k, k, k, wpat(cur, Z16), wpat(BS, Z16)))
    L.append('      {==}')
    L.append('')
    L.append('def and16_le(+v: U32, +h: {U32.is_le(v, 65535) == True{} : Bool}) -> {U32.and(v, 65535) == v : U32}:')
    L.append('  match v:')
    L.append('    case U32{%s}:' % wpat(['+' + b for b in BS], '+t'))
    L.append('      +ht = UB.tail_zero(16n, t, V16.chain16(%s, Word.cmp(16n, t, Word.zero(16n)), h))' % ', '.join(BS))
    L.append('      Equal.trans(U32, U32.and(U32{%s}, 65535), U32{%s}, U32{%s}, and16(U32{%s}), Equal.cong(Word(16n), U32, z => U32{%s}, Word.zero(16n), t, Equal.sym(Word(16n), t, Word.zero(16n), ht)))'
             % (wpat(BS, 't'), wpat(BS, Z16), wpat(BS, 't'), wpat(BS, 't'), wpat(BS, 'z')))
    L.append('')
    return L


def go(s, r):
    E, T, lem = [], [], []
    for k in range(16):
        P = 8 * r + k
        yi = P - 8 * s
        if 0 <= yi < 16:
            E.append('Bool.or(Bool.and(x%d, False{}), Bool.and(y%d, True{}))' % (P, yi))
            T.append('y%d' % yi)
            lem.append('UB.sel(x%d, y%d)' % (P, yi))
        else:
            Y = 'y%d' % yi if yi >= 0 else 'False{}'
            E.append('Bool.or(Bool.and(x%d, True{}), Bool.and(%s, False{}))' % (P, Y))
            T.append('x%d' % P)
            lem.append('UB.sel2(x%d, %s)' % (P, Y))
    L = ['def hw16_go_%d_%d(+old: U32, +v: U32) -> {lo16(O.shr_bytes(%s, %d)) == %s : U32}:' % (s, r, merged(s), r, target_lo(s, r))]
    L.append('  match old:')
    L.append('    case U32{%s}:' % wpat(['+' + x for x in XS]))
    L.append('      match v:')
    L.append('        case U32{%s}:' % wpat(['+' + y for y in YS]))
    R = 'U32{%s}' % wpat(T, Z16)
    for k in range(16):
        cur = T[:k] + ['_'] + E[k + 1:]
        L.append('          %%Equal.sym(Bool, %s, %s, %s) : {U32{%s} == %s : U32}' % (E[k], T[k], lem[k], wpat(cur, Z16), R))
    L.append('          {==}')
    L.append('')
    return L


def rw(s, r):
    Zx = 'O.shr_bytes(O.merge_word(old, v, %d, 2), %d)' % (s, r)
    L = ['def hw16_rw_%d_%d(+old: U32, +v: U32) -> {U32.and(%s, 65535) == %s : U32}:' % (s, r, Zx, target_and(s, r))]
    L.append('  %%Equal.sym(U32, U32.and(%s, 65535), lo16(%s), and16(%s)) : {_ == %s : U32}' % (Zx, Zx, Zx, target_and(s, r)))
    L.append('  %%Equal.sym(U32, %s, %s, and16(%s)) : {lo16(%s) == _ : U32}' % (target_and(s, r), target_lo(s, r), inner(s, r), Zx))
    if s == 2:
        M = 'O.mask_at(2, 2)'
        L.append('  %%Equal.sym(U32, U32.mul(v, 65536), U32.shln(v, 16n), WM.mul65536(v)) : {lo16(O.shr_bytes(U32.or(U32.and(old, U32.not(%s)), U32.and(_, %s)), %d)) == %s : U32}' % (M, M, r, target_lo(s, r)))
    L.append('  hw16_go_%d_%d(old, v)' % (s, r))
    L.append('')
    return L


def text():
    L = lo16_and16()
    for s in (0, 2):
        for r in (0, 2):
            L += go(s, r)
            L += rw(s, r)
    return HEAD + '\n'.join(L).rstrip('\n') + '\n'


def main():
    run_single('halfword16', OUT, text(), '--check' in sys.argv)


if __name__ == '__main__':
    main()
