#!/usr/bin/env python3
"""The index of a packed element as a word and an offset: proofs/obj/u32split.bend.

For a 32-bit index i the runtime reads word i >> k and offset i & (2^k - 1) (k = 2 for a byte in a word, 5 for a bit in a
word). split_k(i) says the two make the number again:

    U32.to_nat(i) == U32.to_nat(U32.and(i, 2^k - 1)) + 2^k * U32.to_nat(U32.shrn(i, k))

It is proved on the word's first k bits (shr_split of found.bend k times, the mask by and_true and wand_zero), so the spec
index of the written element (to_nat(i), the k-th item of the view) is the word and offset the write used.
codegen/proofs/collections/coll_laws.py's byte and bit view laws use it.

    python3 codegen/proofs/collections/u32_split.py            # write
    python3 codegen/proofs/collections/u32_split.py --check    # nonzero exit if the output is stale
"""
import sys as _sys
import pathlib as _pathlib
_sys.path.insert(0, str(_pathlib.Path(__file__).resolve().parents[3]))  # the repository root: `codegen` is importable when this file runs as a script
import sys

from codegen.core.paths import ROOT  # noqa: E402
OUT = ROOT / 'proofs/obj/u32split.bend'
KS = (2, 5)

BV = lambda x: 'F.spec_numeric__bit_value(%s)' % x


def dbl(e, n=1):
    for _ in range(n):
        e = 'Nat.double(%s)' % e
    return e


def Fexpr(As, N):
    """to_nat of the number whose low bits are As and whose rest is the number N: A0 + 2 (A1 + 2 (... + 2 N))"""
    if not As:
        return N
    return 'Nat.add(%s, Nat.double(%s))' % (As[0], Fexpr(As[1:], N))


def Hexpr(As):
    """to_nat of the word of the low bits As alone (zero above): the same with 0 in place of N, the last added term unsimplified"""
    if not As:
        return '0n'
    return 'Nat.add(%s, Nat.double(%s))' % (As[0], Hexpr(As[1:]))


def text():
    out = ['import Base', 'import ../compact/found.bend as F', 'import ./u32bits.bend as UB', '', '# GENERATED by u32_split (codegen). Do not edit.',
           '# A 32-bit index is its low k bits and the number of the rest: i = (i & (2^k - 1)) + 2^k * (i >> k), k = 2 (a byte in a word) and 5 (a bit',
           '# in a word). See codegen/proofs/collections/u32_split.py.', '']
    out.append('''# A + 2 (H + D) is (A + 2 H) + 2 D
def alg_step(+A: Nat, +H: Nat, +D: Nat) -> {Nat.add(A, Nat.double(Nat.add(H, D))) == Nat.add(Nat.add(A, Nat.double(H)), Nat.double(D)) : Nat}:
  %F.nat__add_double(H, D) :
    {Nat.add(A, _) == Nat.add(Nat.add(A, Nat.double(H)), Nat.double(D)) : Nat}
  Equal.sym(Nat, Nat.add(Nat.add(A, Nat.double(H)), Nat.double(D)), Nat.add(A, Nat.add(Nat.double(H), Nat.double(D))), F.nat__add_assoc(A, Nat.double(H), Nat.double(D)))
''')
    for k in KS:
        a = ['a%d' % j for j in range(k)]
        # fh_j: F_j == H_j + 2^j N, by one alg_step on the lower ones
        for j in range(1, k + 1):
            As = a[:j]
            params = ', '.join('+%s: Nat' % x for x in As) + ', +N: Nat'
            lo = As[1:]
            if j == 1:
                inner = 'Equal.cong(Nat, Nat, z => Nat.add(%s, Nat.double(z)), N, Nat.add(0n, N), {==})' % As[0]
                # F_1 = A0 + 2 N, H_1 + D_1 = (A0 + 2 * 0) + 2 N
                out.append('def fh%d_%d(%s)\n    -> {%s == Nat.add(%s, %s) : Nat}:\n  Equal.trans(Nat, %s, Nat.add(%s, Nat.double(Nat.add(0n, N))), Nat.add(%s, %s),\n    %s,\n    alg_step(%s, 0n, N))\n' % (
                    k, j, params, Fexpr(As, 'N'), Hexpr(As), dbl('N', j), Fexpr(As, 'N'), As[0], Hexpr(As), dbl('N', j), inner, As[0]))
            else:
                inner = 'Equal.cong(Nat, Nat, z => Nat.add(%s, Nat.double(z)), %s, Nat.add(%s, %s), fh%d_%d(%s))' % (
                    As[0], Fexpr(lo, 'N'), Hexpr(lo), dbl('N', j - 1), k, j - 1, ', '.join(lo + ['N']))
                out.append('def fh%d_%d(%s)\n    -> {%s == Nat.add(%s, %s) : Nat}:\n  Equal.trans(Nat, %s, Nat.add(%s, Nat.double(Nat.add(%s, %s))), Nat.add(%s, %s),\n    %s,\n    alg_step(%s, %s, %s))\n' % (
                    k, j, params, Fexpr(As, 'N'), Hexpr(As), dbl('N', j), Fexpr(As, 'N'), As[0], Hexpr(lo), dbl('N', j - 1), Hexpr(As), dbl('N', j),
                    inner, As[0], Hexpr(lo), dbl('N', j - 1)))
        # and_k
        xs = ['x%d' % j for j in range(k)]
        tw = 'Word(%dn)' % (32 - k)
        mask = (1 << k) - 1
        W = 't'
        full = 'U32{%s}' % ('WCon{' + ', WCon{'.join(xs) + ', t' + '}' * k)
        masked = 'U32{%s}' % (''.join('WCon{Bool.and(%s, True{}), ' % x for x in xs) + '_' + '}' * k)
        out.append('def and%d(%s, +t: %s)\n    -> {U32.to_nat(U32.and(%s, %d)) == %s : Nat}:' % (k, ', '.join('+%s: Bool' % x for x in xs), tw, full, mask, Hexpr([BV(x) for x in xs])))
        out.append('  %%Equal.sym(%s, Word.and(%dn, t, Word.zero(%dn)), Word.zero(%dn), UB.wand_zero(%dn, t)) :' % (tw, 32 - k, 32 - k, 32 - k, 32 - k))
        out.append('    {U32.to_nat(%s) == %s : Nat}' % (masked.replace('_', 'Word.and(%dn, t, Word.zero(%dn))' % (32 - k, 32 - k), 0) if False else
                                                      'U32{%s}' % (''.join('WCon{Bool.and(%s, True{}), ' % x for x in xs) + '_' + '}' * k), Hexpr([BV(x) for x in xs])))
        for j in range(k - 1, -1, -1):
            cur = ''.join(('WCon{Bool.and(%s, True{}), ' % xs[m]) if m < j else ('WCon{_, ' if m == j else 'WCon{%s, ' % xs[m]) for m in range(k)) + 'Word.zero(%dn)' % (32 - k) + '}' * k
            out.append('  %%Equal.sym(Bool, Bool.and(%s, True{}), %s, F.u32__and_true(%s)) :\n    {U32.to_nat(U32{%s}) == %s : Nat}' % (xs[j], xs[j], xs[j], cur, Hexpr([BV(x) for x in xs])))
        zw = 'WCon{' + ', WCon{'.join(xs) + ', Word.zero(%dn)' % (32 - k) + '}' * k
        out.append('  F.u32__to_nat_word(%s)\n' % zw)
        # split_k
        N = 'U32.to_nat(U32.shrn(%s, %dn))' % (full, k)
        # to_nat(shr^m i) = A_m + 2 to_nat(shr^(m+1) i), m = 0..k-1, by found.bend's shr_split
        def shr_m(m):
            return full if m == 0 else 'U32.shrn(%s, %dn)' % (full, m)

        def nat_m(m):
            return 'U32.to_nat(%s)' % shr_m(m)
        # chain: nat_0 == F_k(A, nat_k) built from the inside: T_m: nat_m == F_{k-m}(A_m.., nat_k)
        As = [BV(x) for x in xs]
        steps = {}
        steps[k] = None   # nat_k == nat_k
        expr = {}
        proof = {}
        expr[k] = nat_m(k)
        proof[k] = None
        for m in range(k - 1, -1, -1):
            # nat_m == A_m + 2 nat_{m+1}  (shr_split), then cong with T_{m+1}
            split_m = 'F.u32__shr_split(%s)' % shr_m(m)
            e_next = expr[m + 1]
            expr[m] = 'Nat.add(%s, Nat.double(%s))' % (As[m], e_next)
            if proof[m + 1] is None:
                proof[m] = split_m
            else:
                proof[m] = 'Equal.trans(Nat, %s, Nat.add(%s, Nat.double(%s)), %s,\n      %s,\n      Equal.cong(Nat, Nat, z => Nat.add(%s, Nat.double(z)), %s, %s,\n      %s))' % (
                    nat_m(m), As[m], nat_m(m + 1), expr[m], split_m, As[m], nat_m(m + 1), expr[m + 1], proof[m + 1])
        # the goal: to_nat(i) == H + 2^k N
        Hk = Hexpr(As)
        Dk = dbl(N, k)
        goal = 'U32.to_nat(%s) == Nat.add(U32.to_nat(U32.and(%s, %d)), %s)' % (full, full, mask, Dk)
        fh = 'fh%d_%d(%s)' % (k, k, ', '.join(As + [N]))
        out.append('def split%d(+i: U32) -> {U32.to_nat(i) == Nat.add(U32.to_nat(U32.and(i, %d)), %s) : Nat}:\n  match i:\n    case U32{%s}:' % (
            k, mask, dbl('U32.to_nat(U32.shrn(i, %dn))' % k, k), 'WCon{' + ', WCon{'.join('+' + x for x in xs) + ', +t' + '}' * k))
        out.append('      Equal.trans(Nat, %s, %s, Nat.add(U32.to_nat(U32.and(%s, %d)), %s),\n      %s,\n      Equal.trans(Nat, %s, Nat.add(%s, %s), Nat.add(U32.to_nat(U32.and(%s, %d)), %s),\n        %s,\n        Equal.cong(Nat, Nat, z => Nat.add(z, %s), %s, U32.to_nat(U32.and(%s, %d)), Equal.sym(Nat, U32.to_nat(U32.and(%s, %d)), %s, and%d(%s, t)))))\n' % (
            nat_m(0), expr[0], full, mask, Dk,
            proof[0],
            expr[0], Hk, Dk, full, mask, Dk,
            fh, Dk, Hk, full, mask, full, mask, Hk, k, ', '.join(xs)))
    return '\n'.join(out)


def main():
    t = text()
    if '--check' in sys.argv:
        if not OUT.exists() or OUT.read_text() != t:
            print('stale: u32split.bend')
            sys.exit(1)
        print('u32_split: up to date')
        return
    if not OUT.exists() or OUT.read_text() != t:
        OUT.write_text(t)
    print('u32_split: proofs/obj/u32split.bend')


if __name__ == '__main__':
    main()
