#!/usr/bin/env python3
"""proofs/obj/u64_tail.bend: the zero tail of a list of uint64 after one element is written.

A byte list of whole 8-byte elements is stored as words; its representation invariant (words_obj_light.bend's wf1) says that the part of its last 32-byte
chunk past the r bytes in use is zero: bdrop(r, cb(slots t, q)) == zero_bytes(32 - r), r in 1 .. 32. A written element (two words at q_w = 2 i, i below
the count) is inside the bytes in use, so the tree after the write keeps that fact. This file proves it, symbolically:

    split8(a, c, r, e): from 8 a + r = 8 c, c = a + m and r = 8 m (the bytes in use are whole elements: r = 8 m)
    y_le(i, ..):        the words of the written element end before the word 8 q + k, for k >= 2 m
    tail_m<m>(..):      for r = 8 m (m = 1 .. 4), the words 8 q + k, k >= 2 m, of the written tree are the old ones (words_win.bend's wd_after), and the
                        bytes past r of the chunk are those of the limbs of just those words: the tail is the old tail
    tail_u(..):         the cases of m (r is 8, 16, 24 or 32 bytes)

codegen/proofs/collections/coll_laws.py's root-after-set laws of the uint64 collections (coll_root.bend) use tail_u to rebuild the invariant of the written object.

    python3 codegen/proofs/collections/u64_tail.py            # write
    python3 codegen/proofs/collections/u64_tail.py --check    # nonzero exit if the output is stale
"""
import sys as _sys
import pathlib as _pathlib
_sys.path.insert(0, str(_pathlib.Path(__file__).resolve().parents[3]))  # the repository root: `codegen` is importable when this file runs as a script
from codegen.core.paths import ROOT  # noqa: E402
from codegen.core.shared_laws import run_single  # noqa: E402
OUT = ROOT / 'proofs/obj/u64_tail.bend'

HEAD = '''import Base
import ../../src/obj.bend as O
import ../../spec/primitives.bend as SP
import ../compact/found.bend as F
import ../nat_order.bend as Order
import ./dk.bend as DK
import ./mtree_run.bend as MR
import ./spec_fixed.bend as FX
import ./words_spec.bend as WS
import ./words_win.bend as WW

# GENERATED by u64_tail (codegen). Do not edit.
# The zero tail of a list of uint64 after one element is written: see codegen/proofs/collections/u64_tail.py.

# the 32 q bytes below the chunk are 8 (4 q) bytes: e32 is e8 of four times
def e32_quad(+x: Nat) -> {WS.e32(x) == O.e8(Nat.double(Nat.double(x))) : Nat}:
  match x:
    case 0n: {==}
    case 1n+ +p: Equal.cong(Nat, Nat, z => Nat.add(32n, z), WS.e32(p), O.e8(Nat.double(Nat.double(p))), e32_quad(p))

def dbl_add(+a: Nat, +b: Nat) -> {Nat.double(Nat.add(a, b)) == Nat.add(Nat.double(a), Nat.double(b)) : Nat}:
  match a:
    case 0n: {==}
    case 1n+ +p: Equal.cong(Nat, Nat, z => Nat.add(2n, z), Nat.double(Nat.add(p, b)), Nat.add(Nat.double(p), Nat.double(b)), dbl_add(p, b))

def split8_step(+a1: Nat, +c1: Nat, +r: Nat, +ih: DK.Ex(Nat, m => DK.P2({c1 == Nat.add(a1, m) : Nat}, {r == O.e8(m) : Nat})))
    -> DK.Ex(Nat, m => DK.P2({1n+c1 == Nat.add(1n+a1, m) : Nat}, {r == O.e8(m) : Nat})):
  (+m, +p) = ih
  (+h1, +h2) = p
  (m, (Equal.cong(Nat, Nat, z => 1n+z, c1, Nat.add(a1, m), h1), h2))

# whole 8-byte elements: 8 a + r = 8 c gives c = a + m with r = 8 m
def split8(+a: Nat, +c: Nat, +r: Nat, +e: {Nat.add(O.e8(a), r) == O.e8(c) : Nat})
    -> DK.Ex(Nat, m => DK.P2({c == Nat.add(a, m) : Nat}, {r == O.e8(m) : Nat})):
  match a c:
    case 0n +cc: (cc, ({==}, e))
    case 1n+ +a1 0n: Empty.absurd(DK.Ex(Nat, m => DK.P2({0n == Nat.add(1n+a1, m) : Nat}, {r == O.e8(m) : Nat})), F.nat__succ_zero(Nat.add(7n, Nat.add(O.e8(a1), r)), e))
    case 1n+ +a1 1n+ +c1: split8_step(a1, c1, r, split8(a1, c1, r, F.lru_subtraction_bounds__cancel_left(8n, Nat.add(O.e8(a1), r), O.e8(c1), e)))

# the written element (words 2 i, 2 i + 1) is below the word 8 q + k, k >= 2 m, of the chunk q holding the last 8 m bytes
def y_le(+i: Nat, +q: Nat, +qc: Nat, +c: Nat, +m: Nat, +k: Nat, +hq: {q == Nat.double(i) : Nat}, +hlt: {Nat.is_le(1n+i, c) == True{} : Bool},
    +hc: {c == Nat.add(Nat.double(Nat.double(qc)), m) : Nat}, +hk: {Nat.is_le(Nat.double(m), k) == True{} : Bool})
    -> {Nat.is_le(Nat.add(q, 2n), Nat.add(O.e8(qc), k)) == True{} : Bool}:
  +h1 = Order.double_monotone(1n+i, c, hlt)
  +h2 = F.logic__subst(Nat, z => {Nat.is_le(Nat.double(1n+i), z) == True{} : Bool}, Nat.double(c), Nat.add(O.e8(qc), Nat.double(m)),
    Equal.trans(Nat, Nat.double(c), Nat.double(Nat.add(Nat.double(Nat.double(qc)), m)), Nat.add(O.e8(qc), Nat.double(m)),
      Equal.cong(Nat, Nat, z => Nat.double(z), c, Nat.add(Nat.double(Nat.double(qc)), m), hc), dbl_add(Nat.double(Nat.double(qc)), m)), h1)
  +h3 = F.nat__le_trans(Nat.double(1n+i), Nat.add(O.e8(qc), Nat.double(m)), Nat.add(O.e8(qc), k), h2, Order.add_left(O.e8(qc), Nat.double(m), k, hk))
  F.logic__subst(Nat, z => {Nat.is_le(z, Nat.add(O.e8(qc), k)) == True{} : Bool}, Nat.double(1n+i), Nat.add(q, 2n),
    Equal.trans(Nat, Nat.double(1n+i), Nat.add(2n, Nat.double(i)), Nat.add(q, 2n), {==},
      Equal.trans(Nat, Nat.add(2n, Nat.double(i)), Nat.add(Nat.double(i), 2n), Nat.add(q, 2n), F.nat__add_comm(2n, Nat.double(i)),
        Equal.cong(Nat, Nat, z => Nat.add(z, 2n), Nat.double(i), q, Equal.sym(Nat, q, Nat.double(i), hq)))), h3)
def dbl_succ_q(+i: Nat, +q: Nat, +hq: {q == Nat.double(i) : Nat}) -> {Nat.double(1n+i) == Nat.add(q, 2n) : Nat}:
  Equal.trans(Nat, Nat.double(1n+i), Nat.add(2n, Nat.double(i)), Nat.add(q, 2n), {==},
    Equal.trans(Nat, Nat.add(2n, Nat.double(i)), Nat.add(Nat.double(i), 2n), Nat.add(q, 2n), F.nat__add_comm(2n, Nat.double(i)),
      Equal.cong(Nat, Nat, z => Nat.add(z, 2n), Nat.double(i), q, Equal.sym(Nat, q, Nat.double(i), hq))))

# the written element's two words are inside the storage: its index is below the count, which fits the storage
def hr_of(+i: Nat, +q: Nat, +c: Nat, +P: Nat, +hq: {q == Nat.double(i) : Nat}, +hlt: {Nat.is_le(1n+i, c) == True{} : Bool}, +hcap: {Nat.is_le(Nat.double(c), P) == True{} : Bool})
    -> {Nat.is_le(Nat.add(q, 2n), P) == True{} : Bool}:
  F.logic__subst(Nat, z => {Nat.is_le(z, P) == True{} : Bool}, Nat.double(1n+i), Nat.add(q, 2n), dbl_succ_q(i, q, hq),
    F.nat__le_trans(Nat.double(1n+i), Nat.double(c), P, Order.double_monotone(1n+i, c, hlt), hcap))
'''


def words(side, k0, iq='iq'):
    return ['MR.wd(%s, Nat.add(O.e8(%s), %dn))' % (side, iq, k) for k in range(8)]


def tail_m(m):
    r = 8 * m
    a = 2 * m   # the first word kept
    W2 = 'F.array__slots(U32, WW.tk([x0, x1], d, t, qw, 0n))'
    W = 'F.array__slots(U32, t)'
    w2 = words(W2, a)
    w1 = words(W, a)
    CB = lambda ws: 'FX.limbs([%s])' % ', '.join(ws)
    ZB = 'SP.zero_bytes(Nat.sub(32n, %dn))' % r
    out = []
    out.append('def tail_m%d(+d: Nat, +t: F.array__Tree<U32>, +qw: Nat, +x0: U32, +x1: U32, +iq: Nat, +i: Nat, +qc: Nat, +c: Nat, +eiq: {iq == qc : Nat}, +hq: {qw == Nat.double(i) : Nat},' % m)
    out.append('    +hlt: {Nat.is_le(1n+i, c) == True{} : Bool}, +hc: {c == Nat.add(Nat.double(Nat.double(qc)), %dn) : Nat}, +hb: {Nat.is_le(Nat.add(qw, 2n), F.spec_common__pow2(d)) == True{} : Bool},' % m)
    out.append('    +pf: {F.array__perfect(U32, d, t) == True{} : Bool}, +slack: {WS.bdrop(%dn, WS.cb(%s, iq)) == %s : +List<U32>})' % (r, W, ZB))
    out.append('    -> {WS.bdrop(%dn, WS.cb(%s, iq)) == %s : +List<U32>}:' % (r, W2, ZB))
    for k in range(a, 8):
        out.append('  +e%d = WW.wd_after([x0, x1], d, t, qw, Nat.add(O.e8(iq), %dn), F.logic__subst(Nat, z => {Nat.is_le(Nat.add(qw, 2n), Nat.add(O.e8(z), %dn)) == True{} : Bool}, qc, iq, Equal.sym(Nat, iq, qc, eiq), y_le(i, qw, qc, c, %dn, %dn, hq, hlt, hc, {==})), hb, pf)' % (k, k, k, m, k))
    out.append('  Equal.trans(+List<U32>, WS.bdrop(%dn, WS.cb(%s, iq)), WS.bdrop(%dn, WS.cb(%s, iq)), %s,' % (r, W2, r, W, ZB))
    out.append('    bdeq_m%d(d, t, qw, x0, x1, iq, %s),' % (m, ', '.join(['e%d' % k for k in range(a, 8)])))
    out.append('    slack)')
    return '\n'.join(out)


def bdeq_m(m):
    r = 8 * m
    a = 2 * m
    W2 = 'F.array__slots(U32, WW.tk([x0, x1], d, t, qw, 0n))'
    W = 'F.array__slots(U32, t)'
    w2 = ['MR.wd(%s, Nat.add(O.e8(iq), %dn))' % (W2, k) for k in range(8)]
    w1 = ['MR.wd(%s, Nat.add(O.e8(iq), %dn))' % (W, k) for k in range(8)]
    CB = lambda ws: 'FX.limbs([%s])' % ', '.join(ws)
    out = []
    sig = '+d: Nat, +t: F.array__Tree<U32>, +qw: Nat, +x0: U32, +x1: U32, +iq: Nat'
    hyp = ', '.join('+e%d: {%s == %s : U32}' % (k, w2[k], w1[k]) for k in range(a, 8))
    out.append('def bdeq_m%d(%s, %s)' % (m, sig, hyp))
    out.append('    -> {WS.bdrop(%dn, WS.cb(%s, iq)) == WS.bdrop(%dn, WS.cb(%s, iq)) : +List<U32>}:' % (r, W2, r, W))
    cur = list(w2)
    for k in range(a, 8):
        pat = list(cur)
        pat[k] = '_'
        nxt = list(cur)
        nxt[k] = w1[k]
        out.append('  %%Equal.sym(U32, %s, %s, e%d) : {WS.bdrop(%dn, %s) == WS.bdrop(%dn, WS.cb(%s, iq)) : +List<U32>}' % (w2[k], w1[k], k, r, CB(pat), r, W))
        cur = nxt
    out.append('  {==}')
    return '\n'.join(out)


def dispatcher():
    out = ['def tail_u(+m: Nat, +d: Nat, +t: F.array__Tree<U32>, +qw: Nat, +x0: U32, +x1: U32, +iq: Nat, +i: Nat, +qc: Nat, +c: Nat, +r: Nat, +eiq: {iq == qc : Nat}, +hq: {qw == Nat.double(i) : Nat},',
           '    +hlt: {Nat.is_le(1n+i, c) == True{} : Bool}, +hc: {c == Nat.add(Nat.double(Nat.double(qc)), m) : Nat}, +er: {r == O.e8(m) : Nat}, +h1: {Nat.is_lt(0n, r) == True{} : Bool},',
           '    +h32: {Nat.is_le(r, 32n) == True{} : Bool}, +hb: {Nat.is_le(Nat.add(qw, 2n), F.spec_common__pow2(d)) == True{} : Bool}, +pf: {F.array__perfect(U32, d, t) == True{} : Bool},',
           '    +slack: {WS.bdrop(r, WS.cb(F.array__slots(U32, t), iq)) == SP.zero_bytes(Nat.sub(32n, r)) : +List<U32>})',
           '    -> {WS.bdrop(r, WS.cb(F.array__slots(U32, WW.tk([x0, x1], d, t, qw, 0n)), iq)) == SP.zero_bytes(Nat.sub(32n, r)) : +List<U32>}:',
           '  match m:']
    goal = lambda z: '{WS.bdrop(%s, WS.cb(F.array__slots(U32, WW.tk([x0, x1], d, t, qw, 0n)), iq)) == SP.zero_bytes(Nat.sub(32n, %s)) : +List<U32>}' % (z, z)
    out.append('    case 0n: Empty.absurd(%s, F.logic__false_true(F.logic__subst(Nat, z => {Nat.is_lt(0n, z) == True{} : Bool}, r, 0n, er, h1)))' % goal('r'))
    for m in range(1, 5):
        r = 8 * m
        slk = lambda z: '{WS.bdrop(%s, WS.cb(F.array__slots(U32, t), iq)) == SP.zero_bytes(Nat.sub(32n, %s)) : +List<U32>}' % (z, z)
        # the case m: r is the literal; the invariant's tail and the result move between r and the literal
        out.append('    case %dn:' % m)
        out.append('      F.logic__subst(Nat, z => %s, %dn, r, Equal.sym(Nat, r, %dn, er),' % (goal('z'), r, r))
        out.append('        tail_m%d(d, t, qw, x0, x1, iq, i, qc, c, eiq, hq, hlt, hc, hb, pf, F.logic__subst(Nat, z => %s, r, %dn, er, slack)))' % (m, slk('z'), r))
    out.append('    case 5n+ +p: Empty.absurd(%s, F.logic__false_true(F.logic__subst(Nat, z => {Nat.is_le(z, 32n) == True{} : Bool}, r, O.e8(5n+p), er, h32)))' % goal('r'))
    return '\n'.join(out)

WRAP = """# the same with the cases of m given as a value (split8)
def tail_w(+d: Nat, +t: F.array__Tree<U32>, +qw: Nat, +x0: U32, +x1: U32, +iq: Nat, +i: Nat, +qc: Nat, +c: Nat, +r: Nat, +eiq: {iq == qc : Nat}, +hq: {qw == Nat.double(i) : Nat},
    +hlt: {Nat.is_le(1n+i, c) == True{} : Bool}, +h1: {Nat.is_lt(0n, r) == True{} : Bool}, +h32: {Nat.is_le(r, 32n) == True{} : Bool},
    +hb: {Nat.is_le(Nat.add(qw, 2n), F.spec_common__pow2(d)) == True{} : Bool}, +pf: {F.array__perfect(U32, d, t) == True{} : Bool},
    +slack: {WS.bdrop(r, WS.cb(F.array__slots(U32, t), iq)) == SP.zero_bytes(Nat.sub(32n, r)) : +List<U32>},
    +sp: DK.Ex(Nat, m => DK.P2({c == Nat.add(Nat.double(Nat.double(qc)), m) : Nat}, {r == O.e8(m) : Nat})))
    -> {WS.bdrop(r, WS.cb(F.array__slots(U32, WW.tk([x0, x1], d, t, qw, 0n)), iq)) == SP.zero_bytes(Nat.sub(32n, r)) : +List<U32>}:
  (+m, +p) = sp
  (+hc, +er) = p
  tail_u(m, d, t, qw, x0, x1, iq, i, qc, c, r, eiq, hq, hlt, hc, er, h1, h32, hb, pf, slack)"""


def text():
    parts = [HEAD.rstrip('\n'), '']
    for m in range(1, 5):
        parts.append('# the limbs of the written chunk, past the first %d bytes: the words %d .. 7 are the old words' % (8 * m, 2 * m))
        parts.append(bdeq_m(m))
        parts.append('')
        parts.append(tail_m(m))
        parts.append('')
    parts.append('# the bytes in use are 8, 16, 24 or 32: the tail of the written tree is the old tail')
    parts.append(dispatcher())
    parts.append('')
    parts.append(WRAP)
    return '\n'.join(parts) + '\n'


def main():
    run_single('u64_tail', OUT, text())


if __name__ == '__main__':
    main()
