#!/usr/bin/env python3
"""Round-3 crash hunt (a): every public entry point of every packed collection on an object that LIES about its length.

    python3 tools/crash_hunt/gen_lie.py gen --repo . --out tools/crash_hunt/lie
    python3 tools/crash_hunt/gen_lie.py run --repo . --out DIR [--jobs 3]        (server; needs build/ch/lie_<id>)

For each packed collection of gen_packed_diff.SPECS (lists, bit lists, progressive lists, byte lists, vectors) the program builds
`O.Words{8-word storage, claim}` (`O.Bits` for bit lists) and applies ONE operation, SSZ_OP:
  1 _valid   2 _root   3 _serialize (when the name has one)   4 _append   5 _set at claim - 1   6 _get at claim - 1   7 _len   8 _set at 0
The claim (SSZ_CLAIM) is taken from {limit, limit + 1, 2^31 - 1, 2^31, 2^32 - 32, 2^32 - 5, 2^32 - 1}. A run must finish within 60 s and the
answer must be a value: the verdict CRASH is a signal, abort, timeout or a resident set above 3 GB (a few words of input), WRONG is a `_valid`
of 1 for a claim the 8 words of storage cannot hold (the representation invariant of docs/API_CONTRACTS.md), or an accepted `_serialize`.
"""
import argparse
import collections
import json
import os
import re
import resource
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import gen_packed_diff as G  # noqa: E402

PROG = '''import Base
import ../../../src/buffer.bend as B
import ../../../src/digest.bend as D
import ../../../src/obj.bend as O
import ../../../types/%(file)s_def_generated.bend as Dd
import ../../../types/%(file)s_hashtreeroot_generated.bend as Hh
import ../../../types/%(file)s_encode_ssz_generated.bend as Ee
%(ELIMP)s
import ../../../benchmarks/compact/objio.bend as IOx

# GENERATED by tools/crash_hunt/gen_lie.py (round-3 crash hunt: lying lengths into every entry point of %(file)s)

def nx(+x: U32) -> U32: (x * 1664525 + 1013904223 : U32)

def mk(+claim: U32) -> %(OT)s: %(MK)s

def x0() -> U32: 12345

def line_valid(pair: %(OT)s & Bool) -> IO(Unit):
  (o, ok) = pair
  IO.print("valid=" ++ O.pick_str(ok))

def line_root(pair: B.Buf & (%(OT)s & D.Digest)) -> IO(Unit):
  (h, r) = pair
  (o, d) = r
  IO.print("root=" ++ IOx.words(d))

def line_flag(label: String, pair: %(OT)s & Bool) -> IO(Unit):
  (o, ok) = pair
  IO.print(label ++ "=" ++ O.pick_str(ok))

def line_get(pair: %(OT)s & Maybe<&1, %(GT)s>) -> IO(Unit):
  (o, m) = pair
  match m:
    case Some{v}: IO.print("get=some")
    case None{}: IO.print("get=none")

def line_len(pair: %(OT)s & U32) -> IO(Unit):
  (o, +n) = pair
  IO.print("len=" ++ U32.show(n))

%(SER)s

def op(+c: U32, +claim: U32, +x: U32) -> IO(Unit):
  match c:
    case 1: line_valid(Ee.%(P)s_valid(mk(claim)))
    case 2: line_root(Hh.%(P)s_root(64n, O.hasher(), mk(claim), 0))
    case 3: %(SERCALL)s
    case 4: line_flag("append", %(APP)s)
    case 5: line_flag("set_last", Dd.%(P)s_set(mk(claim), (claim - 1 : U32), %(VAL)s))
    case 6: line_get(Dd.%(P)s_get(mk(claim), (claim - 1 : U32)))
    case 7: line_len(Dd.%(P)s_len(mk(claim)))
    case _: line_flag("set_first", Dd.%(P)s_set(mk(claim), 0, %(VAL)s))

def main() -> IO(Unit):
  do IO<Unit>:
    +c : U32 <- IOx.env_u32("SSZ_OP")
    +claim : U32 <- IOx.env_u32("SSZ_CLAIM")
    op(c, claim, x0())
'''


def render(repo, s):
    ot = 'O.Bits' if s['kind'] == 'bit' else 'O.Words'
    P = s['prefix']
    gt = {'bit': 'Bool', 'bool': 'Bool', 'u8': 'U32', 'u16': 'U32', 'u32': 'U32', 'u64': 'O.U64', 'u128': 'Bt.Uint128', 'u256': 'Bt.Uint256', 'b32': 'Bt.Bytes32',
          'b48': 'Bt.Bytes48', 'cell': 'O.Words'}[s['kind']]
    si = G.ser_info(repo, s['file'])
    ser, sercall = '', 'IO.print("ser=none")'
    if si:
        name, pair, plus = si
        ser = ('def line_ser2(+n: U32, ok: Bool, pair: B.Buf & U32) -> IO(Unit):\n  (b, +m) = pair\n  IO.print("ser_ok=" ++ O.pick_str(ok) ++ " ser_sz=" ++ U32.show(m))\n\n'
               'def line_ser(e: O.Encoded) -> IO(Unit):\n  match e:\n    case O.Encoded{ok, b}: line_ser2(0, ok, B.size(b))\n\n')
        if pair:
            ser += 'def line_ser_p(pair: %s & O.Encoded) -> IO(Unit):\n  (o, e) = pair\n  line_ser(e)\n' % ot
            sercall = 'line_ser_p(Ee.%s(mk(claim)))' % name
        else:
            sercall = 'line_ser(Ee.%s(mk(claim)))' % name
    mk = 'O.Bits{Array.new(U32, 3n, 0), claim}' if s['kind'] == 'bit' else 'O.Words{Array.new(U32, 3n, 0), claim}'
    app = 'Dd.%s_append(mk(claim), %s)' % (P, G.VAL[s['kind']]) if s['shape'] != 'vector' else '(mk(claim), True{})'
    return PROG % dict(file=s['file'], ELIMP=G.EL.get(s['kind'], ''), OT=ot, MK=mk, GT=gt, P=P, SER=ser, SERCALL=sercall, APP=app, VAL=G.VAL[s['kind']])


def claims(s):
    lim = s['limit']
    cs = {2 ** 31 - 1, 2 ** 31, 2 ** 32 - 32, 2 ** 32 - 5, 2 ** 32 - 1, 100, 33}
    if lim is not None and lim < 2 ** 32 - 1:
        cs |= {lim, lim + 1}
    if s['shape'] == 'vector':
        cs |= {s['vn'], s['vn'] * 8, s['vn'] * 48}
    return sorted(c for c in cs if 1 <= c < 2 ** 32)


def run(prog, op, claim, timeout=60):
    env = {**os.environ, 'SSZ_OP': str(op), 'SSZ_CLAIM': str(claim)}
    p = subprocess.Popen(['nice', '-n', '19', '/usr/bin/time', '-f', 'MAXRSS=%M', prog, '--threads', '1', '--gpu', 'off'], env=env, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    try:
        so, se = p.communicate(timeout=timeout)
        return p.returncode, so, se
    except subprocess.TimeoutExpired:
        p.kill()
        so, se = p.communicate()
        return 'timeout', so, se


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('mode', choices=['gen', 'run'])
    ap.add_argument('--repo', default='.')
    ap.add_argument('--out', required=True)
    ap.add_argument('--only', default='')
    ap.add_argument('--jobs', type=int, default=3)
    a = ap.parse_args()
    only = [x for x in a.only.split(',') if x]
    specs = [s for s in G.SPECS if not only or s['id'] in only]
    if a.mode == 'gen':
        os.makedirs(a.out, exist_ok=True)
        for s in specs:
            open(os.path.join(a.out, 'lie_%s.bend' % s['id']), 'w').write(render(a.repo, s))
        print('generated', len(specs))
        return
    tally = collections.Counter()
    findings = []
    slow = []

    def work(s):
        prog = os.path.join(a.repo, 'build', 'ch', 'lie_' + s['id'])
        res = []
        for c in claims(s):
            for op in (1, 2, 3, 4, 5, 6, 7, 8):
                import time
                t0 = time.time()
                rc, so, se = run(prog, op, c)
                res.append((op, c, rc, so, se, time.time() - t0))
        return s, res
    with ThreadPoolExecutor(a.jobs) as ex:
        for s, res in ex.map(work, [x for x in specs]):
            bad = 0
            for op, c, rc, so, se, sec in res:
                m = re.search(r'MAXRSS=(\d+)', se)
                rss = int(m.group(1)) if m else 0
                out = so.strip()
                if rc != 0 or not out or rss > 3 * 2 ** 20:
                    tally['CRASH'] += 1
                    bad += 1
                    findings.append({'class': 'CRASH', 'id': s['id'], 'op': op, 'claim': c, 'rc': rc, 'rss_kb': rss, 'sec': round(sec, 1), 'err': se[-160:], 'out': out[:80]})
                    print('  CRASH', findings[-1], flush=True)
                    continue
                if sec > 8:
                    slow.append({'id': s['id'], 'op': op, 'claim': c, 'sec': round(sec, 1), 'rss_kb': rss})
                if op == 1 and out == 'valid=1':
                    # storage is 8 words (32 bytes / 256 bits): any claim above that must not be valid
                    cap = 256 if s['kind'] == 'bit' else 32
                    unit = {'u8': 1, 'u16': 2, 'u32': 4, 'u64': 8, 'u128': 16, 'u256': 32, 'b32': 32, 'b48': 48, 'cell': 2048, 'bool': 1}.get(s['kind'], 1)
                    need = c if s['kind'] in ('bit',) else c
                    if need > cap and not (c >= 2 ** 32 - 3 and s['kind'] != 'bit'):
                        tally['WRONG'] += 1
                        bad += 1
                        findings.append({'class': 'WRONG', 'id': s['id'], 'op': op, 'claim': c, 'why': 'valid=1 with 32 bytes of storage', 'out': out})
                        continue
                if op == 3 and 'ser_ok=1' in out:
                    tally['WRONG'] += 1
                    bad += 1
                    findings.append({'class': 'WRONG', 'id': s['id'], 'op': op, 'claim': c, 'why': 'serialize accepted', 'out': out})
                    continue
                tally['OK'] += 1
            print(s['id'], 'runs', len(res), 'bad', bad, flush=True)
    os.makedirs(a.out, exist_ok=True)
    json.dump({'tally': dict(tally), 'findings': findings[:400], 'slow': slow[:100]}, open(os.path.join(a.out, 'lie.json'), 'w'), indent=1)
    print('FINAL', dict(tally), 'slow', len(slow))


if __name__ == '__main__':
    main()
