#!/usr/bin/env python3
"""Round-3 crash hunt (b): containers built through public setters only, against the reference port.

    python3 tools/crash_hunt/gen_setters.py gen --repo . --cs CS --out tools/crash_hunt/st          (writes st_<name>.bend, st_specs.json)
    python3 tools/crash_hunt/gen_setters.py run --repo . --cs CS --out DIR [--jobs 3]               (server; needs build/ch/st_<name>)

For every named container (Fulu or generic) that has `_serialize`, the program starts from `X_default()` and sets EVERY scalar and byte-vector
field (uint8/16/32/64/128/256, bool, ByteVectorN, BitvectorN) to a value from the LCG x' = x * 1664525 + 1013904223 (seeded by SSZ_SEED),
fields of composite or list type stay default. It prints the size and word checksum of `X_serialize(o)` and the root. The reference port builds
the same value (zero value with the same fields replaced) and must give the same bytes and root.
"""
import argparse
import collections
import glob
import json
import os
import re
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..', 'spec_audit'))
M32 = 0xFFFFFFFF


def nx(x):
    return (x * 1664525 + 1013904223) & M32


PROG = '''import Base
import ../../../src/buffer.bend as B
import ../../../src/digest.bend as D
import ../../../src/obj.bend as O
import ../../../types/%(file)s_def_generated.bend as Dd
import ../../../types/%(file)s_encode_ssz_generated.bend as Ee
import ../../../types/%(file)s_hashtreeroot_generated.bend as Hh
%(IMPS)s
import ../../../benchmarks/compact/objio.bend as IOx

# GENERATED by tools/crash_hunt/gen_setters.py (round-3 crash hunt: %(file)s built through its setters)

def nx(+x: U32) -> U32: (x * 1664525 + 1013904223 : U32)

def cs_go(+k: Nat, +i: U32, +acc: U32, pair: B.Buf & U32) -> B.Buf & U32:
  match k:
    case 0n:
      (b, +w) = pair
      (b, (acc * 31 + w : U32))
    case 1n+q:
      (b, +w) = pair
      cs_go(q, (i + 1 : U32), (acc * 31 + w : U32), B.word(b, (i + 1 : U32)))

def cs_fin(pair: B.Buf & U32) -> U32:
  (b, +x) = pair
  x

def cs_pick(zero: Bool, b: B.Buf, +words: U32) -> B.Buf & U32:
  match zero:
    case True{}: (b, 7)
    case False{}: cs_go(U32.to_nat((words - 1 : U32)), 0, 7, B.word(b, 0))

def csum(b: B.Buf, +words: U32) -> U32: cs_fin(cs_pick(U32.is_eq(words, 0), b, words))

def ser_line2(ok: Bool, pair: B.Buf & U32) -> String:
  (b, +n) = pair
  "%(file)s ser_ok=" ++ O.pick_str(ok) ++ " ser_sz=" ++ U32.show(n) ++ " ser_cs=" ++ U32.show(csum(b, U32.shrn((n + 3 : U32), 2n)))

def ser_line(e: O.Encoded) -> String:
  match e:
    case O.Encoded{ok, b}: ser_line2(ok, B.size(b))

def okfst(pair: Dd.%(T)s & Bool) -> Dd.%(T)s:
  (o, ok) = pair
  o

def obj(+x: U32) -> Dd.%(T)s: %(BUILD)s

%(TAIL)s

def main() -> IO(Unit):
  do IO<Unit>:
    +seed : U32 <- IOx.env_u32("SSZ_SEED")
    go(seed)
'''

TAIL_TYPE = '''def fin(line: String, pair: B.Buf & (Dd.%(T)s & D.Digest)) -> IO(Unit):
  (h, r) = pair
  (o, d) = r
  IO.print(line ++ " root=" ++ IOx.words(d))

def s2(pair: Dd.%(T)s & O.Encoded) -> IO(Unit):
  (o, e) = pair
  fin(ser_line(e), Hh.%(T)s_hash_tree_root(O.hasher(), o))

def go(+seed: U32) -> IO(Unit): s2(Ee.%(T)s_serialize(obj(seed)))'''

TAIL_DATA = '''def fin(line: String, pair: B.Buf & D.Digest) -> IO(Unit):
  (h, d) = pair
  IO.print(line ++ " root=" ++ IOx.words(d))

def go(+seed: U32) -> IO(Unit): fin(ser_line(Ee.%(T)s_serialize(obj(seed))), Hh.%(T)s_hash_tree_root(O.hasher(), obj(seed)))'''


def nxe(k, e='x'):
    for _ in range(k):
        e = 'nx(%s)' % e
    return e


def words_expr(k, base='x', lastmask=None):
    ws = [nxe(j, base) if j else base for j in range(k)]
    if lastmask is not None:
        ws[-1] = 'U32.and(%s, %d)' % (ws[-1], lastmask)
    return ', '.join(ws)


def value_py(t, x):
    k = t[0]
    if k == 'bool':
        return (x >> 31) == 1, 1
    if k == 'uint':
        b = t[1]
        if b == 64:
            return x | (nx(x) << 32), 2
        if b < 32:
            return x >> (32 - b), 1
        if b == 32:
            return x, 1
        n = b // 32
        v, y = 0, x
        for j in range(n):
            v |= y << (32 * j)
            y = nx(y)
        return v, n
    raise ValueError(k)


def rec_words(repo, mod, tname):
    s = open(os.path.join(repo, 'types', mod + '_def_generated.bend')).read()
    m = re.search(r'^type %s is Data:\n  %s\{([^}]*)\}' % (re.escape(tname), re.escape(tname)), s, re.M)
    return len(m.group(1).split(',')) if m else None


def specs(repo, ref, gen, fulu_names):
    out = []
    for f in sorted(glob.glob(os.path.join(repo, 'types', '*_encode_ssz_generated.bend'))):
        file = os.path.basename(f)[:-len('_encode_ssz_generated.bend')]
        enc = open(f).read()
        dp = os.path.join(repo, 'types', file + '_def_generated.bend')
        if '_serialize(' not in enc or not os.path.exists(dp):
            continue
        d = open(dp).read()
        ms = re.search(r'^def (\w+)_serialize\(', enc, re.M)
        m = re.search(r'^type %s is (Type|Data):' % re.escape(ms.group(1)), d, re.M) if ms else None
        if not m:
            continue
        T, kind = ms.group(1), m.group(1)
        if not re.search(r'^def %s_default\(\)' % re.escape(T), d, re.M) or not re.search(r'^def %s_serialize\(' % re.escape(T), enc, re.M):
            continue
        nm = file[4:] if file.startswith('Fulu') and file[4:] in fulu_names else file
        try:
            t = ref.type_of(nm) if nm in fulu_names else gen[nm][0]
        except Exception:
            continue
        if t[0] not in ('container', 'progcontainer'):
            continue
        fields = [n for n, _ in t[1]]
        sets_full = re.findall(r'^def %s_set_(\w+)\(o: %s, \+v: ([\w.]+)\) -> ([^:]*?):' % (re.escape(T), re.escape(T)), d, re.M)
        sets = {f: p for f, p, r in sets_full}
        pairs = {f for f, p, r in sets_full if '&' in r}
        assigns, imps, x = [], [], 0
        for i, (fname0, ft) in enumerate(t[1]):
            fname = fname0 if fname0 in sets else ('f_' + fname0 if 'f_' + fname0 in sets else fname0)
            if fname not in sets:
                continue
            pt = sets[fname]
            if ft[0] == 'bool' and pt == 'Bool':
                v = 'U32.is_eq(U32.shrn(%s, 31n), 1)'
            elif ft[0] == 'uint' and ft[1] == 64 and pt == 'O.U64':
                v = 'O.U64{%s, nx(%s)}'
            elif ft[0] == 'uint' and ft[1] in (8, 16, 32) and pt == 'U32':
                v = {8: 'U32.shrn(%s, 24n)', 16: 'U32.shrn(%s, 16n)', 32: '%s'}[ft[1]]
            elif ft[0] in ('bytes', 'bitvector', 'uint') and '.' in pt and not pt.startswith('O.'):
                alias, tn = pt.split('.')
                imp = re.search(r'^import \./(\w+)_def_generated\.bend as %s$' % re.escape(alias), d, re.M)
                if not imp:
                    continue
                nw = rec_words(repo, imp.group(1), tn)
                if not nw:
                    continue
                imps.append('import ../../../types/%s_def_generated.bend as %s' % (imp.group(1), alias))
                lm = None
                if ft[0] == 'bytes' and ft[1] % 4:
                    lm = (1 << (8 * (ft[1] % 4))) - 1
                if ft[0] == 'bitvector' and ft[1] % 32:
                    lm = (1 << (ft[1] % 32)) - 1
                v = '%s.%s{%s}' % (alias, tn, words_expr(nw, '%s', lm))
            else:
                continue
            assigns.append((fname, ft, pt, v, i, fname in pairs))
        out.append(dict(id=file, file=file, T=T, kind=kind, assigns=assigns, imps=sorted(set(imps)), nm=nm))
    return out


def render(s):
    build = 'Dd.%s_default()' % s['T']
    cur = []
    expr = build
    for j, (fname, ft, pt, v, i, pr) in enumerate(s['assigns']):
        # the value of field j comes from x advanced by 7 * j steps so that fields differ
        xe = nxe(7 * j, 'x') if j else 'x'
        expr = 'Dd.%s_set_%s(%s, %s)' % (s['T'], fname, expr, v.replace('%s', '(' + xe + ')'))
        if pr:
            expr = 'okfst(%s)' % expr
    tail = (TAIL_TYPE if s['kind'] == 'Type' else TAIL_DATA) % dict(T=s['T'])
    return PROG % dict(file=s['file'], T=s['T'], IMPS='\n'.join(s['imps']), BUILD=expr, TAIL=tail)


def cs(b):
    b = b + b'\0' * (-len(b) % 4)
    acc = 7
    for i in range(0, len(b), 4):
        acc = (acc * 31 + int.from_bytes(b[i:i + 4], 'little')) & M32
    return acc


def ref_value(S, t, s, seed):
    v = list(S.zero_value(t))
    for j, (fname, ft, pt, vexpr, i, pr) in enumerate(s['assigns']):
        x = seed
        for _ in range(7 * j):
            x = nx(x)
        if ft[0] == 'bool':
            v[i] = (x >> 31) == 1
        elif ft[0] == 'uint' and ft[1] in (8, 16, 32, 64):
            v[i], _ = value_py(ft, x)
        elif ft[0] == 'uint':
            nw = ft[1] // 32
            val, y = 0, x
            for k in range(nw):
                val |= y << (32 * k)
                y = nx(y)
            v[i] = val
        else:
            alias, tn = pt.split('.')
            nw = len(re.findall(r'nx|\bx\b', '')) or None
            # the record's word count is in the expression: count the words
            nw = vexpr.count('{') and (vexpr.count(',') + 1)
            raw = b''
            y = x
            for k in range(nw):
                raw += y.to_bytes(4, 'little')
                y = nx(y)
            if ft[0] == 'bytes':
                v[i] = raw[:ft[1]]
            else:
                nb = (ft[1] + 7) // 8
                bits = []
                rb = bytearray(raw)
                for bi in range(ft[1]):
                    bits.append(bool((rb[bi // 8] >> (bi % 8)) & 1))
                v[i] = bits
    return v


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('mode', choices=['gen', 'run'])
    ap.add_argument('--repo', default='.')
    ap.add_argument('--cs', required=True)
    ap.add_argument('--out', required=True)
    ap.add_argument('--only', default='')
    ap.add_argument('--jobs', type=int, default=3)
    a = ap.parse_args()
    import ssz_ref as S
    from constants import ref_generic
    from refparse import Ref
    ref = Ref(a.cs)
    gen = ref_generic(a.cs)
    fulu = json.load(open(os.path.join(a.repo, 'types/obj_groups.json')))
    only = [x for x in a.only.split(',') if x]
    sps = [s for s in specs(a.repo, ref, gen, set(fulu)) if not only or s['id'] in only]
    if a.mode == 'gen':
        os.makedirs(a.out, exist_ok=True)
        for s in sps:
            open(os.path.join(a.out, 'st_%s.bend' % s['id']), 'w').write(render(s))
        json.dump([{k: v for k, v in s.items() if k != 'assigns'} | {'nassign': len(s['assigns'])} for s in sps], open(os.path.join(a.out, 'st_specs.json'), 'w'), indent=1)
        print('generated', len(sps), 'fields set', sum(len(s['assigns']) for s in sps))
        return
    tally = collections.Counter()
    findings = []

    def typeof(s):
        return ref.type_of(s['nm']) if s['nm'] in fulu else gen[s['nm']][0]

    def work(s):
        prog = os.path.join(a.repo, 'build', 'ch', 'st_' + s['id'])
        res = []
        for seed in (1, 77, 4242424242):
            env = {**os.environ, 'SSZ_SEED': str(seed)}
            try:
                r = subprocess.run(['nice', '-n', '19', prog, '--threads', '1', '--gpu', 'off'], env=env, capture_output=True, text=True, timeout=120)
                res.append((seed, r.returncode, r.stdout, r.stderr))
            except subprocess.TimeoutExpired:
                res.append((seed, 'timeout', '', ''))
        return s, res
    with ThreadPoolExecutor(a.jobs) as ex:
        for s, res in ex.map(work, sps):
            t = typeof(s)
            for seed, rc, so, se in res:
                line = so.strip().splitlines()[-1] if so.strip() else ''
                if rc != 0 or ' root=' not in line:
                    tally['CRASH'] += 1
                    findings.append({'class': 'CRASH', 'id': s['id'], 'seed': seed, 'rc': rc, 'err': se[-160:]})
                    continue
                kv = dict(p.split('=', 1) for p in line.split()[1:])
                try:
                    v = ref_value(S, t, s, seed)
                    ser = S.serialize(t, v)
                    root = S.hash_tree_root(t, v)
                except Exception as e:
                    tally['REFERR'] += 1
                    findings.append({'class': 'REFERR', 'id': s['id'], 'seed': seed, 'err': repr(e)[:160]})
                    continue
                eroot = ','.join(str(int.from_bytes(root[i:i + 4], 'big')) for i in range(0, 32, 4))
                probs = []
                if kv.get('ser_ok') != '1':
                    probs.append('serialize refused')
                elif kv.get('ser_sz') != str(len(ser)) or kv.get('ser_cs') != str(cs(ser)):
                    probs.append('bytes differ (sz %s expected %d)' % (kv.get('ser_sz'), len(ser)))
                if kv.get('root') != eroot:
                    probs.append('root differs')
                if probs:
                    tally['WRONG'] += 1
                    findings.append({'class': 'WRONG', 'id': s['id'], 'seed': seed, 'why': probs, 'fields': len(s['assigns'])})
                else:
                    tally['OK'] += 1
            print(s['id'], 'fields', len(s['assigns']), 'ok' if not any(f['id'] == s['id'] for f in findings) else 'PROBLEM', flush=True)
    os.makedirs(a.out, exist_ok=True)
    json.dump({'tally': dict(tally), 'findings': findings[:400]}, open(os.path.join(a.out, 'setters.json'), 'w'), indent=1)
    print('FINAL', dict(tally))


if __name__ == '__main__':
    main()
