#!/usr/bin/env python3
"""Decoder-acceptance witnesses of the composed theorems of the variable-size names: e2e/<Name>_e2e_decode_witness_generated.bend.

Every composed theorem (e2e/<Name>_e2e_comp_generated.bend: <Name>_e2e_decode_encode, <Name>_e2e_decode_root) assumes
`decode(bs) == Some{o}`; its other hypotheses (hn, hd, hS) are facts about the input. Nothing in them shows that a real input is
accepted, so a composed theorem could hold vacuously. For a variable-size name whose default object encodes to few enough bytes for the
checker to evaluate, this file takes the real input, the encoding of the default object (bs0 = E.obytes of X_encode(default), n0 its
size), and states

  <Name>_e2e_decode_witness           isS(X_decode(fill_at(alloc(n0), 0, bs0), n0)) == True       the decoder accepts bs0
  <Name>_e2e_decode_witness_encode    the composed decode;encode theorem applied at (bs0, n0, o0): every hypothesis proved, o0 the decoded object
  <Name>_e2e_decode_witness_root      the composed decode;root theorem applied at the same input

A name whose default encodes to too many bytes (the fixed parts of BeaconState are 2.7 MB) is listed with its reason in
e2e/DECODE_WITNESS.txt (generated), and in docs/PREMISES.md.

    python3 codegen/proofs/witnesses/decode_witness.py [--check] [--only A,B] [--skip A,B]
"""
import sys as _sys
import pathlib as _pathlib
_sys.path.insert(0, str(_pathlib.Path(__file__).resolve().parents[3]))  # the repository root: `codegen` is importable when this file runs as a script
import re
import sys

from codegen.proofs.witnesses import e2e_witness as W  # noqa: E402

ROOT = W.ROOT
E2E = W.E2E
HEADER = '# GENERATED by decode_witness (codegen). Do not edit.'
# names whose input is too large to evaluate (filled in from the checked results, with the reason): {name: reason}
TOO_BIG = {
    'FuluBeaconState': 'the default object encodes to 2.7 MB (the fixed-size parts: block_roots, state_roots, randao_mixes, slashings, ...); the checker does not evaluate '
                       'the encoder and the decoder over that input (the run does not finish in the check budget)',
    'FuluLightClientUpdate': 'the default object encodes to over 50 KB (two sync committees and their branches); the run does not finish in the check budget',
    'FuluLightClientBootstrap': 'the default object encodes to over 25 KB (a sync committee and two branches); the run overflows the checker stack after 6 minutes',
}


# names whose input holds one element in every list: a default with an EMPTY last progressive list is no input the premise hPB can be evaluated at
# (PBQ's PALL walks 2^32 - 1 element slots of an empty window: NN - 1 wraps), the object with one element per list is
NONEMPTY = {'ProgressiveComplexTestStruct'}


def split_param(p):
    n, _, t = p.partition(':')
    return n.strip().lstrip('+-'), t.strip()


def build(name):
    cp = E2E / f'{name}_e2e_comp_generated.bend'
    W.Mod.cache.clear()
    cm = W.Mod.get(cp)
    de, dr = f'{name}_e2e_decode_encode', f'{name}_e2e_decode_root'
    if de not in cm.defs or dr not in cm.defs:
        return None, 'no composed theorem'
    _, ceonc, _ = cm.signature(de)
    pe = [split_param(p) for p in cm.fullp]
    _, croncl, _ = cm.signature(dr)
    pr = [split_param(p) for p in cm.fullp]
    if not any(n == 'hS' for n, _ in pe):
        return None, 'a fixed-size name'
    W.PREFER.clear()
    for pth, al in ((ROOT / 'src/buffer.bend', 'B'), (ROOT / 'src/obj.bend', 'O'), (E2E / 'e2e_support.bend', 'E'),
                    (ROOT / 'proofs/compact/found.bend', 'FD')):
        W.PREFER[pth.resolve()] = al
    ctx = W.Ctx()
    CP = ctx.alias(cp)
    lift = lambda e: ctx.lift(cm, e)
    mdec = re.search(r'^\{Pair\.snd\(B\.Buf, Maybe<&1, ([\w.]+)>, (.*?)\) == Some\{o\} : Maybe<&1, [\w.]+>\}$', dict(pe)['dec'], re.S)
    if not mdec:
        return None, 'the decode hypothesis is not read'
    OBJ, DECALL = lift(mdec.group(1)), lift(mdec.group(2))
    menc = re.search(r'\w+\.obytes\(Pair\.snd\([\w.]+, B\.Buf, ([\w.]+\.\w+)\(o\)\)\) == bs', ceonc)
    if not menc:
        return None, 'the encode call is not read'
    ENC = lift(menc.group(1))
    otype = dict(pe)['o']
    tmod, dflt = W.default_of(ctx, cm, otype, name)
    DEF = f'{ctx.alias(tmod.path)}.{dflt}'
    # a default that holds empty boxes where a vector needs values (ComplexTestStruct's vec_VarTestStruct_2) is not a legal
    # object: its encoding is not an input the decoder accepts. DV() is the default with valid values there (as in e2e_witness)
    dv = ''
    lists = name in NONEMPTY
    probe = W.model_ne(W.Ctx(), tmod, dflt, lists=lists)     # on a throwaway context: the imports are the file's only if DV() is used
    if getattr(probe, 'changed', False):
        obj0 = W.model_ne(ctx, tmod, dflt, lists=lists)
        dv = f'def {name}_DV() -> {OBJ}:\n  {obj0.expr}'
        DEF = f'{name}_DV()'
    BA = ctx.alias(ROOT / 'src/buffer.bend')
    EA = ctx.alias(E2E / 'e2e_support.bend')
    OA = ctx.alias(ROOT / 'src/obj.bend')
    pre = f'{name}_dw'
    sub = {'bs': f'{pre}_bs()', 'n': f'{pre}_n()', 'o': f'{pre}_o()'}

    def inst(t):
        t = lift(t)
        return re.sub(r'(?<![\w.])(bs|n|o)(?![\w.])', lambda m: sub[m.group(1)], t)

    # the decode call at the instance
    dec0 = f'Pair.snd({BA}.Buf, Maybe<&1, {OBJ}>, ' + re.sub(r'(?<![\w.])(bs|n)(?![\w.])', lambda m: sub[m.group(1)], DECALL) + ')'
    defs = ([dv] if dv else []) + [
        f'def {pre}_isS(m: Maybe<&1, {OBJ}>) -> Bool:\n  match m:\n    case Some{{x}}: True{{}}\n    case None{{}}: False{{}}',
        f'def {pre}_gm(m: Maybe<&1, {OBJ}>, d: {OBJ}) -> {OBJ}:\n  match m:\n    case Some{{x}}: x\n    case None{{}}: d',
        f'def {pre}_buf() -> {BA}.Buf: Pair.snd({OBJ}, {BA}.Buf, {ENC}({DEF}))',
        f'def {pre}_n() -> U32: Pair.snd({BA}.Buf, U32, {BA}.size({pre}_buf()))',
        f'def {pre}_bs() -> +List<U32>: {EA}.obytes({pre}_buf())',
        f'def {pre}_dec() -> Maybe<&1, {OBJ}>: {dec0}',
        f'def {pre}_o() -> {OBJ}: {pre}_gm({pre}_dec(), {DEF})',
        f'def {name}_e2e_decode_witness() -> {{{pre}_isS({pre}_dec()) == True{{}} : Bool}}:\n  {{==}}',
    ]
    for tag, law, params, concl in (('encode', de, pe, ceonc), ('root', dr, pr, croncl)):
        args = []
        for n, t in params:
            if n == 'h':
                args.append(f'{BA}.alloc(0)')
            elif n in sub:
                args.append(sub[n])
            else:
                args.append('{==}')
        c2 = inst(concl)
        c2 = re.sub(r'(?<![\w.])h(?=[),])', f'{BA}.alloc(0)', c2)
        defs.append(f'def {name}_e2e_decode_witness_{tag}() -> {c2}:\n  {CP}.{law}({", ".join(args)})')
    return W.imports_text(ctx) + '\n\n' + HEADER + '\n' + (
        f'# {name}: the decoder accepts the encoding of the default object, and the composed theorems apply at that input.\n\n') + '\n\n'.join(defs) + '\n', None


def main():
    check = '--check' in sys.argv
    only = sys.argv[sys.argv.index('--only') + 1].split(',') if '--only' in sys.argv else None
    skip = set(sys.argv[sys.argv.index('--skip') + 1].split(',')) if '--skip' in sys.argv else set()
    outs, rows = {}, []
    for cp in sorted(E2E.glob('*_e2e_comp_generated.bend')):
        name = cp.name[:-len('_e2e_comp_generated.bend')]
        if only and name not in only:
            continue
        if name in TOO_BIG or name in skip:
            rows.append(f'{name}\tpending: {TOO_BIG.get(name, "skipped")}')
            continue
        try:
            t, why = build(name)
        except SystemExit as e:
            t, why = None, str(e).replace('\n', ' ')[:200]
        if t is None:
            if why != 'a fixed-size name':
                rows.append(f'{name}\tpending: {why}')
            continue
        outs[E2E / f'{name}_e2e_decode_witness_generated.bend'] = t
        rows.append(f'{name}\twitnessed')
    if not only:
        outs[E2E / 'DECODE_WITNESS.txt'] = ('# GENERATED by decode_witness (codegen). Do not edit.\n# the variable-size names with a composed theorem: the decoder '
                                            'accepts the encoding of the default object (e2e/<Name>_e2e_decode_witness_generated.bend), or why not\n' + '\n'.join(rows) + '\n')
    stale = []
    for p, t in outs.items():
        if not p.exists() or p.read_text() != t:
            stale.append(p.name)
            if not check:
                p.write_text(t)
    if not only:
        for p in sorted(E2E.glob('*_e2e_decode_witness_generated.bend')):
            if p not in outs:
                if check:
                    stale.append(p.name + ' (orphan)')
                else:
                    p.unlink()
    if check:
        if stale:
            print('stale: ' + ', '.join(stale))
            sys.exit(1)
        print(f'decode_witness: {len(outs)} files up to date')
    else:
        print(f'decode_witness: wrote {len(stale)} of {len(outs)}')


if __name__ == '__main__':
    main()
