#!/usr/bin/env python3
"""The object API's facade proofs, per readable name and operation (not yet the gate: nothing reads
these files; codegen/api_gate.py stays the gate until the restructure flips).

    python3 codegen/api_facade.py [--check] [--no-big]

For every name X of the API (the 109 Fulu names and the generic forms, under codegen/names.py's
readable names) and each operation, one module

  proofs/api/<X>_encode_ssz_proof_generated.bend     encode_eval, encode_spec, encoded_size, roundtrip, serialize_valid
  proofs/api/<X>_decode_ssz_proof_generated.bend     ok_eval, decode_accept, decode_spec, decode_unique, decode_reject,
                                                     decode_none, reject_short, reject_long, decode_tree, decode_input
  proofs/api/<X>_hashtreeroot_proof_generated.bend   root

stating each of that name's laws of the operation in the object API's terms (the proving law's own
statement: T.<name>_encode / _decode / _ok / _hash_tree_root / _serialize, Spec.<name>() under
Decoding.decodes / outside_image) and discharging it by the proving law. The source is
proofs/gate/api_map.json ({name: {law: [{file, law, big}]}}, api_gate's scan). A module imports its
proving files, each file's own imports under a per-file alias prefix (P<i>_), so the statements of
several proving files sit side by side; the def of a law is <X>__<law>__<proving law>.

proofs/api/manifest.json lists, per module, its proving files and whether one is big (checkq --big),
and per name and operation the core laws no proving law covers yet (no module is written for an
operation with no law at all).
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'codegen'))
OBJ = ROOT / 'proofs/obj'
OUT = ROOT / 'proofs/api'

import api_gate as AG  # noqa: E402

OPS = {
    'encode_ssz': ['encode_eval', 'encode_spec', 'encoded_size', 'roundtrip', 'serialize_valid'],
    'decode_ssz': ['ok_eval', 'decode_accept', 'decode_spec', 'decode_unique', 'decode_reject', 'decode_none',
                   'reject_short', 'reject_long', 'decode_tree', 'decode_input'],
    'hashtreeroot': ['root'],
}


def fname(X, op):
    return f'{X}_{op}_proof_generated.bend'  # flat: Bend import paths take no extra dots (as types/)


def module(X, R, op, rows, parsed):
    """rows: [(kind, file, law)] of name X (readable R) and operation op."""
    files = []
    for _, f, _ in rows:
        if f not in files:
            files.append(f)
    L, seen = [], set()
    alias = {}
    for i, f in enumerate(files):
        src = (OBJ / f).read_text()
        amap = {}
        for l in src.split('\n'):
            if not l.startswith('import '):
                continue
            m = re.match(r'import (\S+)( as (\w+))?$', l)
            path = m.group(1)
            if path.startswith('./'):
                path = '../obj/' + path[2:]
            if m.group(3):
                a = f'P{i}_{m.group(3)}'
                amap[m.group(3)] = a
                line = f'import {path} as {a}'
            else:
                line = f'import {path}'
            if line not in seen:
                seen.add(line)
                L.append(line)
        pv = f'P{i}_PRV'
        L.append(f'import ../obj/{f} as {pv}')
        alias[f] = (amap, pv)
    L += ['', '# GENERATED by codegen/api_facade.py. Do not edit.',
          f'# {R}{"" if R == X else f" ({X})"}: its {op} laws in the object API\'s terms, each discharged by its proving law.', '']
    used = set()
    for kind, f, law in rows:
        amap, pv = alias[f]
        blk = next(b for b in parsed[f] if b[1] == law)
        _, n, params, st = blk
        names = {AG.pname(p) for p in params}
        local = {b[1] for b in parsed[f]}

        def qual(s):
            s = re.sub(r'(?<![\w.])([A-Za-z_]\w*)\.', lambda m: f'{amap[m.group(1)]}.' if m.group(1) in amap else m.group(0), s)
            return re.sub(r'(?<![\w.])([A-Za-z_]\w*)(?=[({])', lambda m: f'{pv}.{m.group(1)}' if m.group(1) in local and m.group(1) not in names else m.group(1), s)
        ps = ', '.join(qual(p) for p in params)
        args = ', '.join(AG.pname(p) for p in params)
        dn = f'{R}__{kind}__{law}'
        k2 = 1
        while dn in used:
            k2 += 1
            dn = f'{R}__{kind}__{law}_{k2}'
        used.add(dn)
        L.append(f'def {dn}({ps}) -> {qual(st)}:')
        L.append(f'  {pv}.{law}({args})')
        L.append('')
    return '\n'.join(L) + '\n', files


def outputs(no_big=False):
    import names as NM
    amap = json.loads((ROOT / 'proofs/gate/api_map.json').read_text())
    readable = NM.mapping()
    parsed = {}
    out, manifest = {}, {'modules': {}, 'uncovered': {}}
    # a readable name may carry several generated names (a basic type: Fulu's uint8 and the generic
    # suite's): one module per readable name and operation, with every one's laws
    group = {}
    for X in amap['fulu'] + amap['generic']:
        group.setdefault(readable[X], []).append(X)
    for R, Xs in group.items():
        X = '/'.join(Xs)
        for op, kinds in OPS.items():
            rows = [(k, e['file'], e['law']) for X_ in Xs for k in kinds for e in amap['map'][X_].get(k, [])]
            miss = [k for k in kinds if k in amap['core_laws'] and not any(amap['map'][X_].get(k) for X_ in Xs)]
            if miss:
                manifest['uncovered'].setdefault(R, {})[op] = miss
            if not rows:
                continue
            big = any(f.startswith('big_') for _, f, _ in rows)
            if big and no_big:
                continue
            for _, f, _ in rows:
                if f not in parsed:
                    parsed[f] = AG.blocks((OBJ / f).read_text())
            text, files = module(X, R, op, rows, parsed)
            out[OUT / fname(R, op)] = text
            manifest['modules'][fname(R, op)] = {'name': R, 'generated_name': X, 'op': op, 'files': files, 'big': big}
    if not no_big:
        out[OUT / 'manifest.json'] = json.dumps(manifest, indent=1) + '\n'
    return out


def main():
    no_big = '--no-big' in sys.argv
    out = outputs(no_big)
    mine = list(OUT.glob('*_proof_generated.bend')) if OUT.exists() else []
    if '--check' in sys.argv:
        stale = [str(p.relative_to(ROOT)) for p, t in out.items() if not p.exists() or p.read_text() != t]
        orphans = [str(q.relative_to(ROOT)) for q in mine if q not in out and not no_big]
        if stale or orphans:
            print('stale api facade: ' + ', '.join((stale + orphans)[:20]) + (' ...' if len(stale + orphans) > 20 else ''))
            sys.exit(1)
        print('api facade is current')
        return
    OUT.mkdir(exist_ok=True)
    if not no_big:
        for q in mine:
            if q not in out:
                q.unlink()
    for p, t in out.items():
        p.write_text(t)
    print(f'{len(out)} files')


if __name__ == '__main__':
    main()
