#!/usr/bin/env python3
"""Generates e2e/e2e_dbk.bend: facts about a decoded BeaconBlock / SignedBeaconBlock (proofs/obj/var_winx_BeaconBlock.bend,
var_winx_SignedBeaconBlock.bend at any window) that their composed theorems need beside the body's: the nested window's length facts
(below the window's, below 2^31, below NMAX) and the encode law's size premise RK.SZW / RS.SZW (the body's nine window sums, the
wrappers' fixed bytes added). The lists' encoded sizes against the windows are hypotheses of szk / szs, as in e2e_dbb.

Usage: python3 codegen/e2e_decbk.py [--check]"""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import e2e_decbb as BB  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'e2e' / 'e2e_dbk.bend'
TP = '+t: FD.array__Tree<U32>, +x: Nat, +off: U32, +n: U32'
HC = '+hchk: {W.CHKw(t, x, off, n) == True{} : Bool}'
H31 = BB.H31
HS = BB.HS
TN = BB.TN
NW, FIELD = BB.NW, BB.FIELD

# wrapper: (window module alias, record module alias, record file, fixed bytes, object projection of the body, window object)
WRAP = {
    'bk': dict(win='var_winx_BeaconBlock', rec='RK', recf='e2e_rec_BeaconBlock.bend', fixed=84, T='BeaconBlock',
               body='RT.pjb_BeaconBlockBody_bx(RT.pj_BeaconBlock_4(o))'),
    'sb': dict(win='var_winx_SignedBeaconBlock', rec='RS', recf='e2e_rec_SignedBeaconBlock.bend', fixed=100, T='SignedBeaconBlock',
               body='RT.pjb_BeaconBlockBody_bx(RT.pj_BeaconBlock_4(RT.pj_SignedBeaconBlock_0(o)))'),
}


def parts_of(recf):
    s = (ROOT / 'e2e' / recf).read_text()
    line = [l for l in s.split('\n') if l.startswith('def SZW(')][0]
    ps = re.findall(r'\{n(\d+) == (.+?) : Nat\}', line)
    assert [int(a) for a, _ in ps] == FIELD, ps
    return [e for _, e in ps]


def text():
    out = ['import Base', 'import ../src/obj.bend as O', 'import ../proofs/compact/found.bend as FD', 'import ../proofs/compact/arith.bend as A',
           'import ../proofs/nat_order.bend as Order', 'import ../proofs/obj/vbuf.bend as VB', 'import ../proofs/obj/root_types_light.bend as RT',
           'import ../proofs/obj/var_winx_BeaconBlock.bend as WK', 'import ../proofs/obj/var_winx_SignedBeaconBlock.bend as WS',
           'import ../proofs/obj/var_winx_BeaconBlockBody.bend as WB', 'import ./e2e_dbb.bend as DBB',
           'import ./e2e_rec_BeaconBlock.bend as RK', 'import ./e2e_rec_SignedBeaconBlock.bend as RS']
    seen = set()
    for l in (ROOT / 'e2e' / 'e2e_rec_BeaconBlockBody.bend').read_text().split('\n'):
        m = re.match(r'import (\S+) as (\w+)$', l)
        if m and m.group(2) in BB.IMP and m.group(2) not in seen:
            seen.add(m.group(2))
            out.append(l)
    t = '\n'.join(out) + '\n'
    t += '''
# GENERATED by codegen/e2e_decbk.py. Do not edit.
# A decoded BeaconBlock / SignedBeaconBlock at a byte window: the body's window inside it (its length below the window's, below 2^31
# and NMAX) and the size premise of the encode law (RK.SZW / RS.SZW).
'''
    for pre, w in WRAP.items():
        mod = 'WK' if pre == 'bk' else 'WS'
        hc = f'+hchk: {{{mod}.CHKw(t, x, off, n) == True{{}} : Bool}}'
        O0, L0 = f'{mod}.O0(t, x)', f'{mod}.LJ0(t, x, n)'
        fx = w['fixed']
        t += f'''
def {pre}_lsum({TP}, {hc}) -> {{Nat.add({TN(O0)}, {TN(L0)}) == U32.to_nat(n) : Nat}}:
  Equal.trans(Nat, Nat.add({TN(O0)}, {TN(L0)}), Nat.add({TN(O0)}, Nat.sub(U32.to_nat(n), {TN(O0)})), U32.to_nat(n),
    Equal.cong(Nat, Nat, z => Nat.add({TN(O0)}, z), {TN(L0)}, Nat.sub(U32.to_nat(n), {TN(O0)}), FD.u32__sub_nat(n, {O0}, {mod}.r10(t, x, off, n, hchk))),
    FD.nat__sub_add(U32.to_nat(n), {TN(O0)}, {mod}.r10(t, x, off, n, hchk)))
def {pre}_lwn({TP}, {hc}) -> {{Nat.is_le({TN(L0)}, U32.to_nat(n)) == True{{}} : Bool}}:
  FD.logic__subst(Nat, z => {{Nat.is_le({TN(L0)}, z) == True{{}} : Bool}}, Nat.add({TN(O0)}, {TN(L0)}), U32.to_nat(n), {pre}_lsum(t, x, off, n, hchk), A.le_skip({TN(O0)}, {TN(L0)}))
def {pre}_h31({TP}, {H31}, {hc}) -> {{Nat.is_lt({TN(L0)}, VB.pw(31n)) == True{{}} : Bool}}:
  FD.nat__le_lt_trans({TN(L0)}, U32.to_nat(n), VB.pw(31n), {pre}_lwn(t, x, off, n, hchk), h31)
def {pre}_hSN({TP}, {HS}, {hc}) -> {{Nat.is_le({TN(L0)}, U32.to_nat(VB.NMAX())) == True{{}} : Bool}}:
  FD.nat__le_trans({TN(L0)}, U32.to_nat(n), U32.to_nat(VB.NMAX()), {pre}_lwn(t, x, off, n, hchk), DBB.u2n(n, VB.NMAX(), hS))
def {pre}_hS({TP}, {HS}, {hc}) -> {{U32.is_le({L0}, VB.NMAX()) == True{{}} : Bool}}:
  DBB.n2u({L0}, VB.NMAX(), {pre}_hSN(t, x, off, n, hS, hchk))
'''
    # the body's nine window lengths inside a block window / a signed block window
    def body_win(pre):
        if pre == 'bk':
            return 'WK.XJ0(t, x)', 'WK.FJ0(off, t, x)', 'WK.LJ0(t, x, n)', 'WK.itD0(t, x, off, n, hchk)'
        XM, FM, LM = 'WS.XJ0(t, x)', 'WS.FJ0(off, t, x)', 'WS.LJ0(t, x, n)'
        hm = 'WS.itD0(t, x, off, n, hchk)'
        return f'WK.XJ0(t, {XM})', f'WK.FJ0({FM}, t, {XM})', f'WK.LJ0(t, {XM}, {LM})', f'WK.itD0(t, {XM}, {FM}, {LM}, {hm})'

    def lens_of(pre):
        XB, FB, LB, _ = body_win(pre)
        return [TN(f'WB.LJ{i}(t, {XB})' if i < NW - 1 else f'WB.LJ{NW - 1}(t, {XB}, {LB})') for i in range(NW)]
    SZb = {pre: BB._sz(lens_of(pre), BB.F0) for pre in WRAP}
    # bk_tot: 84 + the body's windows = n
    XB, FB, LB, hcb = body_win('bk')
    t += f'''
# the block's fixed 84 bytes and the body's windows add up to n
def bk_tot({TP}, +hchk: {{WK.CHKw(t, x, off, n) == True{{}} : Bool}}) -> {{Nat.add(84n, {SZb['bk']}) == U32.to_nat(n) : Nat}}:
  Equal.trans(Nat, Nat.add(84n, {SZb['bk']}), Nat.add(84n, {TN(LB)}), U32.to_nat(n), Equal.cong(Nat, Nat, z => Nat.add(84n, z), {SZb['bk']}, {TN(LB)}, DBB.tot(t, {XB}, {FB}, {LB}, {hcb})),
    Equal.trans(Nat, Nat.add(84n, {TN(LB)}), Nat.add({TN('WK.O0(t, x)')}, {TN(LB)}), U32.to_nat(n), Equal.cong(Nat, Nat, z => Nat.add(z, {TN(LB)}), 84n, {TN('WK.O0(t, x)')}, Equal.sym(Nat, {TN('WK.O0(t, x)')}, 84n, WK.eO0(t, x, off, n, hchk))), bk_lsum(t, x, off, n, hchk)))
'''
    XM, FM, LM = 'WS.XJ0(t, x)', 'WS.FJ0(off, t, x)', 'WS.LJ0(t, x, n)'
    t += f'''
# the signed block's fixed 100 bytes, the block's 84 and the body's windows add up to n
def sb_tot({TP}, +hchk: {{WS.CHKw(t, x, off, n) == True{{}} : Bool}}) -> {{Nat.add(100n, Nat.add(84n, {SZb['sb']})) == U32.to_nat(n) : Nat}}:
  Equal.trans(Nat, Nat.add(100n, Nat.add(84n, {SZb['sb']})), Nat.add(100n, {TN(LM)}), U32.to_nat(n), Equal.cong(Nat, Nat, z => Nat.add(100n, z), Nat.add(84n, {SZb['sb']}), {TN(LM)}, bk_tot(t, {XM}, {FM}, {LM}, WS.itD0(t, x, off, n, hchk))),
    Equal.trans(Nat, Nat.add(100n, {TN(LM)}), Nat.add({TN('WS.O0(t, x)')}, {TN(LM)}), U32.to_nat(n), Equal.cong(Nat, Nat, z => Nat.add(z, {TN(LM)}), 100n, {TN('WS.O0(t, x)')}, Equal.sym(Nat, {TN('WS.O0(t, x)')}, 100n, WS.eO0(t, x, off, n, hchk))), sb_lsum(t, x, off, n, hchk)))
'''
    FLIP = (3, 4, 5, 6, 9, 12)
    for pre, w in WRAP.items():
        mod = 'WK' if pre == 'bk' else 'WS'
        parts = parts_of(w['recf'])
        lens = lens_of(pre)
        OBJ = f'{mod}.OBJw(d, t, x, off, n)'
        sub = lambda e: re.sub(r'(?<![\w.])o(?![\w{(])', OBJ, e)
        eqs = [(f'+e{FIELD[i]}: {{{sub(parts[i])} == {lens[i]} : Nat}}' if FIELD[i] in FLIP else f'+e{FIELD[i]}: {{{lens[i]} == {sub(parts[i])} : Nat}}') for i in range(NW)]
        fixed = f'Nat.add(84n, {SZb[pre]})' if pre == 'bk' else f'Nat.add(100n, Nat.add(84n, {SZb[pre]}))'
        # the record's SZW pairs each witness with its equality, then the total below 2^31
        comps = list(lens) + [(f'Equal.sym(Nat, {sub(parts[i])}, {lens[i]}, e{FIELD[i]})' if FIELD[i] in FLIP else f'e{FIELD[i]}') for i in range(NW)]
        r = f'FD.logic__subst(Nat, z => {{Nat.is_lt(z, VB.pw(31n)) == True{{}} : Bool}}, U32.to_nat(n), {fixed}, Equal.sym(Nat, {fixed}, U32.to_nat(n), {pre}_tot(t, x, off, n, hchk)), h31)'
        for c in reversed(comps):
            r = f'({c}, {r})'
        hc = f'+hchk: {{{mod}.CHKw(t, x, off, n) == True{{}} : Bool}}'
        t += (f'\n# the encode law\'s size premise\n'
              f'def sz{pre}(+d: Nat, {TP}, {", ".join(eqs)}, {H31}, {hc}) -> {w["rec"]}.SZW({OBJ}):\n  {r}\n')
    return t


def main():
    t = text()
    if '--check' in sys.argv:
        if not OUT.exists() or OUT.read_text() != t:
            print('stale: e2e/e2e_dbk.bend')
            sys.exit(1)
        print('e2e_decbk: up to date')
        return
    OUT.write_text(t)
    print('e2e_decbk: wrote e2e/e2e_dbk.bend')


if __name__ == '__main__':
    main()
