"""The second variable-size worker's share of the e2e bridges (codegen/e2e_bridge.py imports it).

codegen/e2e_bridge.py owns the templates, the shared support modules (e2e_load, e2e_cap, e2e_emit,
e2e_ulist) and the manifest; this module only adds per-name entries and any new shared module:

  VDEC_VIEWS[X]   = {'view': 'RT.v_X', 'imports': [...], 'text': ...}   (ii)/(iii): the view lemma vv
  VROOT_SHAPES[X] = f(R, X) -> text                                     (iv): the rebuild from rep
  VENC_SHAPES[X]  = f(R, X) -> text                                     (i)
  SUPPORT_OUT     = {'e2e_<name>.bend': text}                           new shared modules
  VENC_PREMISE[X] = '...'                                               (i)'s premise text in the manifest

X is the generated name (api_map.json), R the readable one (names.py). A name counts as bridged in the
manifest's variable_size section once it has all three; see e2e_bridge's DataColumnsByRootIdentifier
entries for the pattern. Texts may import ../types/fulu_obj.bend as T: e2e_bridge rewires them.

The decode template reads from the name's decode facade: the decoder (T.<fn>), the object type
(Maybe<&1, ..>; override with VDEC_VIEWS[X]['otype']), the schema (Spec or GS), and whether OBJ / VAL
take the depth (OBJ(d, t, n)); it calls the view lemma with decode_accept's own hypotheses:
  vv(+d, +t, +n, +pf: perfect(d, t), +hd: d < bound, +hn: to_nat(n) <= quad(pow2(d)), +hchk: CHK(t, n) == True)
    -> {view(OBJ(..)) == VAL(..)}
"""

VDEC_VIEWS = {}
VROOT_SHAPES = {}
VENC_SHAPES = {}
SUPPORT_OUT = {}
VENC_PREMISE = {}


# ---- byte lists ----

# (iv) of a bare byte list (the object is O.Words; its root law and validity lemma live in the
# name's big_root_ / big_gvalid_ modules, over rep = LO.rep_bl). The words are rebuilt from wfl's
# witnesses (both cases) so the view is over copyable t, N.
def vroot_bytelist(R, X):
    OW = 'O.Words{FD.array__thaw(U32, t), N}'
    RX = lambda o: f'D.bytes(Pair.snd(O.Words, D.Digest, Pair.snd(B.Buf, O.Words & D.Digest, {R}_h.{X}_hash_tree_root(h, {o}))))'
    G = lambda o: f'{{Some{{{RX(o)}}} == API.hash_tree_root(Spec.{X}(), S.BytesValue{{WO.wview({o})}}) : Maybe<&2, +List<U32>>}}'
    imps = ['import Base', 'import ../END_TO_END.bend as E2E', 'import ../src/model.bend as API', 'import ../src/buffer.bend as B',
            'import ../src/digest.bend as D', 'import ../src/obj.bend as O', f'import ../types/{R}_hashtreeroot_generated.bend as {R}_h',
            'import ../types/schema.bend as S', 'import ../spec/fulu_schemas.bend as Spec', 'import ../proofs/type_validator_soundness.bend as VS',
            'import ../proofs/compact/found.bend as FD', 'import ../proofs/obj/words_obj.bend as WO', 'import ../proofs/obj/list_obj.bend as LO',
            f'import ../proofs/obj/big_root_{X}.bend as BR', f'import ../proofs/obj/big_gvalid_{X}.bend as GV', 'import ./e2e_support.bend as E']
    return '\n'.join(imps) + f"""

# GENERATED by codegen/e2e_bridge.py (codegen/e2e_var_b.py). Do not edit.
# {R} (variable size, a byte list): the object API's root is END_TO_END's hash_tree_root, for every
# object the root law represents (LO.rep_bl: its words in a perfect tree of depth below 32, its length
# within the limit).

def rt1(h: B.Buf, +t: FD.array__Tree<U32>, +N: U32, +rep: LO.rep_bl({OW}, Spec.{X}())) -> {G(OW)}:
  E.root_legal(Spec.{X}(), S.BytesValue{{WO.wview({OW})}}, VS.public_sound(Spec.{X}(), {{==}}), {RX(OW)},
    GV.{X}_root_valid({OW}, Spec.{X}(), {{==}}, rep), BR.{X}_root_correct(h, {OW}, Spec.{X}(), {{==}}, rep))

# the object as rep's witnesses name it
def rt2(h: B.Buf, -o: O.Words, +rep: LO.rep_bl(o, Spec.{X}()), +t: FD.array__Tree<U32>, +N: U32,
    +eo: {{o == {OW} : O.Words}}) -> {G('o')}:
  %Equal.sym(O.Words, o, {OW}, eo) : {G('_')}
  rt1(h, t, N, FD.logic__subst(O.Words, z => LO.rep_bl(z, Spec.{X}()), o, {OW}, eo, rep))

# (iv)
def {R}_e2e_root(h: B.Buf, -o: O.Words, +rep: LO.rep_bl(o, Spec.{X}())) -> {G('o')}:
  (+wf, +hl) = rep
  match wf:
    case Inl{{w}}:
      (+t, w1) = w
      (+dw, w2) = w1
      (+N, w3) = w2
      (+eo, w4) = w3
      rt2(h, o, rep, t, N, eo)
    case Inr{{w}}:
      (+t, w1) = w
      (+dw, w2) = w1
      (+N, w3) = w2
      (+q, w4) = w3
      (+r, w5) = w4
      (+eo, w6) = w5
      rt2(h, o, rep, t, N, eo)
"""


VROOT_SHAPES['Transaction'] = vroot_bytelist

# The byte-list view (shared): the words a byte-list reader copies out of a buffer (vua_ct's CT at
# any byte offset) view as the window's bytes.
SUPPORT_OUT['e2e_blist.bend'] = r"""import Base
import ../src/obj.bend as O
import ../proofs/compact/found.bend as FD
import ../proofs/compact/arith.bend as A
import ../proofs/obj/spec_fixed.bend as FX
import ../proofs/obj/vspec.bend as VS
import ../proofs/obj/vbuf.bend as VB
import ../proofs/obj/vlist.bend as VLS
import ../proofs/nat_order.bend as Order
import ../proofs/obj/vua.bend as UA
import ../proofs/obj/vua_ct.bend as UCT
import ../proofs/obj/vua_win.bend as UW
import ../proofs/obj/words_spec.bend as WS
import ../proofs/obj/words_obj.bend as WO
import ../proofs/obj/dk.bend as DK
import ../proofs/obj/vbytes.bend as VY
import ../proofs/obj/pv_obj.bend as PV
import ../proofs/obj/words_root.bend as WR
import ../types/schema.bend as S
import ../spec/primitives.bend as SP

# GENERATED by codegen/e2e_bridge.py (codegen/e2e_var_b.py). Do not edit.
# Byte lists in the e2e bridges: the root view of the storage a byte-list reader copies out of a
# buffer (vua_ct.CT, len bytes at byte offset off = x) is the window's bytes UW.WX(t, x, len).

def btake_bt(+n: Nat, +xs: +List<U32>) -> {WS.btake(n, xs) == VS.bt(n, xs) : +List<U32>}:
  match n xs:
    case 0n _: {==}
    case 1n+ +p Nil{}: {==}
    case 1n+ +p Con{+h, +t}:
      %Equal.sym(+List<U32>, WS.btake(p, t), VS.bt(p, t), btake_bt(p, t)) : {h <> _ == h <> VS.bt(p, t) : +List<U32>}
      {==}

def CW(+d: Nat, +t: FD.array__Tree<U32>, +off: U32, +len: U32) -> FD.array__Tree<U32>: UCT.CT(d, t, off, len, VLS.DZ(len))
def WX0(+t: FD.array__Tree<U32>, +len: U32) -> +List<U32>: UW.WX(t, 0n, U32.to_nat(len))

def bview(+d: Nat, +t: FD.array__Tree<U32>, +off: U32, +len: U32, +x: Nat, +eo: {U32.to_nat(off) == x : Nat}, +hd: {Nat.is_lt(d, 28n) == True{} : Bool},
    +hw: {Nat.is_le(Nat.add(x, U32.to_nat(len)), A.quad(VB.pw(d))) == True{} : Bool}, +pf: {FD.array__perfect(U32, d, t) == True{} : Bool})
    -> {WO.wview(O.Words{FD.array__thaw(U32, CW(d, t, off, len)), len}) == UW.WX(t, x, U32.to_nat(len)) : +List<U32>}:
  +hL = FD.nat__le_trans(U32.to_nat(len), Nat.add(x, U32.to_nat(len)), A.quad(VB.pw(d)), Order.left_below_sum(x, U32.to_nat(len)), hw)
  +hB = FD.logic__subst(Nat, z => {Nat.is_le(Nat.add(z, U32.to_nat(len)), A.quad(VB.pw(d))) == True{} : Bool}, x, U32.to_nat(off), Equal.sym(Nat, U32.to_nat(off), x, eo), hw)
  %Equal.sym(FD.array__Tree<U32>, FD.array__freeze(U32, FD.array__thaw(U32, CW(d, t, off, len))), CW(d, t, off, len), FD.array__freeze_thaw(U32, CW(d, t, off, len))) :
    {WS.btake(U32.to_nat(len), FX.limbs(FD.array__slots(U32, _))) == UW.WX(t, x, U32.to_nat(len)) : +List<U32>}
  %Equal.sym(+List<U32>, WS.btake(U32.to_nat(len), FX.limbs(FD.array__slots(U32, CW(d, t, off, len)))), VS.bt(U32.to_nat(len), FX.limbs(FD.array__slots(U32, CW(d, t, off, len)))), btake_bt(U32.to_nat(len), FX.limbs(FD.array__slots(U32, CW(d, t, off, len))))) :
    {_ == UW.WX(t, x, U32.to_nat(len)) : +List<U32>}
  %eo : {VS.bt(U32.to_nat(len), FX.limbs(FD.array__slots(U32, CW(d, t, off, len)))) == VS.bt(U32.to_nat(len), VS.bdr(_, UA.BYT(t))) : +List<U32>}
  UCT.ct_bytes(d, t, off, len, VLS.DZ(len), VLS.KK(d), VLS.kk_lt(d, hd), VLS.hyn(d, len, hL), pf, UW.hsx(d, off, x, len, eo, hd, hw), VLS.hrg(d, len, hd, hL), hB)

# The view of byte storage O.Words{thaw(T), N} is its first N bytes, as the encode laws' WX(T, 0, N).
def wvb(+M: FD.array__Tree<U32>, +L: U32) -> {WO.wview(O.Words{FD.array__thaw(U32, M), L}) == VS.bt(U32.to_nat(L), FX.limbs(FD.array__slots(U32, M))) : +List<U32>}:
  %Equal.sym(FD.array__Tree<U32>, FD.array__freeze(U32, FD.array__thaw(U32, M)), M, FD.array__freeze_thaw(U32, M)) :
    {WS.btake(U32.to_nat(L), FX.limbs(FD.array__slots(U32, _))) == VS.bt(U32.to_nat(L), FX.limbs(FD.array__slots(U32, M))) : +List<U32>}
  btake_bt(U32.to_nat(L), FX.limbs(FD.array__slots(U32, M)))

def wv0(+T: FD.array__Tree<U32>, +N: U32) -> {WO.wview(O.Words{FD.array__thaw(U32, T), N}) == WX0(T, N) : +List<U32>}:
  %Equal.sym(FD.array__Tree<U32>, FD.array__freeze(U32, FD.array__thaw(U32, T)), T, FD.array__freeze_thaw(U32, T)) :
    {WS.btake(U32.to_nat(N), FX.limbs(FD.array__slots(U32, _))) == WX0(T, N) : +List<U32>}
  btake_bt(U32.to_nat(N), FX.limbs(FD.array__slots(U32, T)))

# ---- fixed-size storage: the first k words of a perfect tree with room for them ----

def seqn(k: Nat, +i: Nat, +W: List<&2, U32>) -> List<&2, U32>:
  match k:
    case 0n: []
    case 1n+p: FD.flat__nthc(W, i) <> seqn(p, 1n+i, W)

def wtk(+k: Nat, +i: Nat, +W: List<&2, U32>, +h: {Nat.is_le(Nat.add(k, i), VB.len(W)) == True{} : Bool}) -> {VS.wtake(k, VB.wdr(i, W)) == seqn(k, i, W) : List<&2, U32>}:
  match k:
    case 0n: {==}
    case 1n+ +p:
      +hi = FD.nat__le_lt_trans(i, Nat.add(p, i), VB.len(W), Order.left_below_sum(p, i), FD.nat__succ_le_lt(Nat.add(p, i), VB.len(W), h))
      +h2 = FD.logic__subst(Nat, z => {Nat.is_le(z, VB.len(W)) == True{} : Bool}, 1n+Nat.add(p, i), Nat.add(p, 1n+i), Equal.sym(Nat, Nat.add(p, 1n+i), 1n+Nat.add(p, i), FD.nat__add_succ(p, i)), h)
      %Equal.sym(List<&2, U32>, VB.wdr(i, W), Con{FD.flat__nthc(W, i), VB.wdr(1n+i, W)}, VB.wdr_eta(i, W, hi)) : {VS.wtake(1n+p, _) == seqn(1n+p, i, W) : List<&2, U32>}
      Equal.cong(List<&2, U32>, List<&2, U32>, z => FD.flat__nthc(W, i) <> z, VS.wtake(p, VB.wdr(1n+i, W)), seqn(p, 1n+i, W), wtk(p, 1n+i, W, h2))

# the bytes of a byte vector of m <= 4 k bytes stored in a perfect tree with room for k words
def wbv(+T: FD.array__Tree<U32>, +dw: Nat, +k: Nat, +M: U32, +pf: {FD.array__perfect(U32, dw, T) == True{} : Bool}, +hk: {Nat.is_le(k, VB.pw(dw)) == True{} : Bool},
    +hm: {Nat.is_le(U32.to_nat(M), A.quad(k)) == True{} : Bool}) -> {WO.wview(O.Words{FD.array__thaw(U32, T), M}) == VS.bt(U32.to_nat(M), FX.limbs(seqn(k, 0n, FD.array__slots(U32, T)))) : +List<U32>}:
  +hl = FD.logic__subst(Nat, z => {Nat.is_le(Nat.add(k, 0n), z) == True{} : Bool}, VB.pw(dw), VB.len(FD.array__slots(U32, T)),
    Equal.sym(Nat, VB.len(FD.array__slots(U32, T)), VB.pw(dw), FD.array__slots_length(U32, dw, T, pf)),
    FD.logic__subst(Nat, z => {Nat.is_le(z, VB.pw(dw)) == True{} : Bool}, k, Nat.add(k, 0n), Equal.sym(Nat, Nat.add(k, 0n), k, FD.nat__add_zero(k)), hk))
  %Equal.sym(+List<U32>, WO.wview(O.Words{FD.array__thaw(U32, T), M}), VS.bt(U32.to_nat(M), FX.limbs(FD.array__slots(U32, T))), wvb(T, M)) : {_ == VS.bt(U32.to_nat(M), FX.limbs(seqn(k, 0n, FD.array__slots(U32, T)))) : +List<U32>}
  %VY.bt_take(k, U32.to_nat(M), FD.array__slots(U32, T), hm) :
    {_ == VS.bt(U32.to_nat(M), FX.limbs(seqn(k, 0n, FD.array__slots(U32, T)))) : +List<U32>}
  Equal.cong(List<&2, U32>, +List<U32>, z => VS.bt(U32.to_nat(M), FX.limbs(z)), VS.wtake(k, VB.wdr(0n, FD.array__slots(U32, T))), seqn(k, 0n, FD.array__slots(U32, T)), wtk(k, 0n, FD.array__slots(U32, T), hl))

# the chunks of a vector of Bytes32 stored as words
def pvh(+T: FD.array__Tree<U32>, +M: U32) -> {PV.pview(O.Words{FD.array__thaw(U32, T), M}) == S.Sequence{WR.items(O.chunks_of(M), FD.array__slots(U32, T), 0n)} : S.Value}:
  %Equal.sym(FD.array__Tree<U32>, FD.array__freeze(U32, FD.array__thaw(U32, T)), T, FD.array__freeze_thaw(U32, T)) :
    {S.Sequence{WR.items(O.chunks_of(M), FD.array__slots(U32, _), 0n)} == S.Sequence{WR.items(O.chunks_of(M), FD.array__slots(U32, T), 0n)} : S.Value}
  {==}

# ---- the (i) premise: byte storage as the root law's invariant (list_obj.wfl), at depth below k ----
# (the encode laws take storage depth below their own bound; the root law's invariant gives dw < 32)

def sdk0(w: O.Words, +k: Nat) -> Data:
  DK.Ex(FD.array__Tree<U32>, t => DK.Ex(Nat, dw => DK.Ex(U32, N =>
    DK.P2({w == O.Words{FD.array__thaw(U32, t), N} : O.Words},
    DK.P2({FD.array__perfect(U32, dw, t) == True{} : Bool},
    DK.P2({Nat.is_lt(dw, k) == True{} : Bool},
          {U32.to_nat(N) == 0n : Nat}))))))

def sdk1(w: O.Words, +k: Nat) -> Data:
  DK.Ex(FD.array__Tree<U32>, t => DK.Ex(Nat, dw => DK.Ex(U32, N => DK.Ex(Nat, q => DK.Ex(Nat, r =>
    DK.P2({w == O.Words{FD.array__thaw(U32, t), N} : O.Words},
    DK.P2({FD.array__perfect(U32, dw, t) == True{} : Bool},
    DK.P2({Nat.is_lt(dw, k) == True{} : Bool},
    DK.P2({U32.to_nat(N) == Nat.add(WS.e32(q), r) : Nat},
    DK.P2({Nat.is_lt(0n, r) == True{} : Bool},
    DK.P2({Nat.is_le(r, 32n) == True{} : Bool},
    DK.P2({Nat.is_le(O.e8(1n+q), FD.spec_common__pow2(dw)) == True{} : Bool},
          {WS.bdrop(r, WS.cb(FD.array__slots(U32, t), Nat.add(q, 0n))) == SP.zero_bytes(Nat.sub(32n, r)) : +List<U32>}))))))))))))

def sdk(w: O.Words, +k: Nat) -> Data: DK.Or2(sdk0(w, k), sdk1(w, k))

# a vector of Bytes32 (pv_obj.wfv at depth below k)
def sdpv(w: O.Words, +k: Nat) -> Data:
  DK.Ex(FD.array__Tree<U32>, t => DK.Ex(Nat, dw => DK.Ex(U32, N => DK.Ex(Nat, q =>
    DK.P2({w == O.Words{FD.array__thaw(U32, t), N} : O.Words},
    DK.P2({FD.array__perfect(U32, dw, t) == True{} : Bool},
    DK.P2({Nat.is_lt(dw, k) == True{} : Bool},
    DK.P2({U32.to_nat(N) == Nat.add(WS.e32(q), 32n) : Nat},
          {Nat.is_le(O.e8(1n+q), FD.spec_common__pow2(dw)) == True{} : Bool}))))))))
"""


# (ii)/(iii) of a bare byte list: the reader's words at offset 0 (the codec's OBJ(d, t, n) =
# O.Words{thaw(CT(d, t, 0, n, DZ(n))), n}) view as VAL's bytes WX(t, 0, n) (e2e_blist.bview).
def vdec_bytelist(X, bound):
    return {'view': 'vbl',
            'imports': ['import ../proofs/obj/words_obj.bend as WO', 'import ./e2e_blist.bend as BL'],
            'text': f'''# ---- the view of a decoded object is the codec law's value ----

def vbl(o: O.Words) -> S.Value: S.BytesValue{{WO.wview(o)}}

def vv(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +pf: {{FD.array__perfect(U32, d, t) == True{{}} : Bool}}, +hd: {{Nat.is_lt(d, {bound}n) == True{{}} : Bool}},
    +hn: {{Nat.is_le(U32.to_nat(n), A.quad(FD.spec_common__pow2(d))) == True{{}} : Bool}}, +hchk: {{DC.CHK(t, n) == True{{}} : Bool}}) -> {{vbl(DC.OBJ(d, t, n)) == DC.VAL(t, n) : S.Value}}:
  Equal.cong(+List<U32>, S.Value, z => S.BytesValue{{z}}, WO.wview(O.Words{{FD.array__thaw(U32, BL.CW(d, t, 0, n)), n}}), BL.WX0(t, n), BL.bview(d, t, 0, n, 0n, {{==}}, hd, hn, pf))

'''}


VDEC_VIEWS['Transaction'] = vdec_bytelist('Transaction', 28)



# (i) of a bare byte list: encode_eval / encode_spec of big_var_codec_X_enc (storage depth below
# DB, the runtime's length check N <= LIM, a U32 literal equal to the schema's limit), the output path
# (e2e_emit.ob at the output's depth DO(N)), the view (e2e_blist.wv0) and END_TO_END's serialize law.
def venc_bytelist(DB, LIM):
    def f(R, X):
        OW = 'O.Words{FD.array__thaw(U32, T), N}'
        ENC = lambda o: f'{R}_e.{X}_encode({o})'
        G = lambda o, v: f'{{Some{{E.obytes(Pair.snd(O.Words, B.Buf, {ENC(o)}))}} == API.serialize(Spec.{X}(), S.BytesValue{{{v}}}) : Maybe<&2, +List<U32>>}}'
        BYT = 'VSP.bt(U32.to_nat(N), SF.limbs(FD.array__slots(U32, EN.OUT(N, T))))'
        HN = f'{{Nat.is_le(U32.to_nat(N), A.quad(VB.pw(dw))) == True{{}} : Bool}}'
        imps = ['import Base', 'import ../END_TO_END.bend as E2E', 'import ../src/model.bend as API', 'import ../src/buffer.bend as B',
                'import ../src/obj.bend as O', f'import ../types/{R}_encode_ssz_generated.bend as {R}_e', 'import ../types/schema.bend as S',
                'import ../spec/fulu_schemas.bend as Spec', 'import ../spec/primitives.bend as SP', 'import ../proofs/type_validator_soundness.bend as VS',
                'import ../proofs/compact/found.bend as FD', 'import ../proofs/compact/arith.bend as A', 'import ../proofs/nat_order.bend as Order',
                'import ../spec/codec.bend as Encoding', 'import ../proofs/obj/spec_fixed.bend as SF', 'import ../proofs/obj/vspec.bend as VSP',
                'import ../proofs/obj/vbuf.bend as VB', 'import ../proofs/obj/vcopy.bend as VC', 'import ../proofs/obj/vdepth.bend as VD',
                'import ../proofs/obj/vu32.bend as VU', 'import ../proofs/obj/vlist.bend as VL', 'import ../proofs/obj/vbspec.bend as VZ',
                'import ../proofs/obj/words_obj.bend as WO', 'import ../proofs/obj/words_spec.bend as WS', 'import ../proofs/obj/list_obj.bend as LO',
                'import ../proofs/obj/schema_shapes.bend as SH', f'import ../proofs/obj/big_var_codec_{X}_enc.bend as EN',
                'import ./e2e_support.bend as E', './e2e_cap.bend', './e2e_emit.bend', './e2e_blist.bend']
        imps = imps[:-4] + ['import ./e2e_support.bend as E', 'import ./e2e_cap.bend as C', 'import ./e2e_emit.bend as EM', 'import ./e2e_blist.bend as BL']
        return '\n'.join(imps) + f"""

# GENERATED by codegen/e2e_bridge.py (codegen/e2e_var_b.py). Do not edit.
# {R} (variable size, a byte list): the object API's encoder's bytes are END_TO_END's serialize of the
# object's view, for every object the root law represents (rep) whose storage is at depth below {DB} (hs:
# the encode laws take dw < {DB}, the root law's invariant dw < 32).

# the output's depth DO(N) is below 29, and 4 * 2^DO(N) holds the N bytes
def hdo(+dw: Nat, +N: U32, +hdw: {{Nat.is_lt(dw, {DB}n) == True{{}} : Bool}}, +hn: {HN}) -> {{Nat.is_lt(VL.DO(N), 29n) == True{{}} : Bool}}:
  FD.nat__le_lt_trans(VL.DO(N), dw, 29n, VD.wd_min(VC.nwu(N), dw, EN.nwp(dw, N, hdw, hn)), FD.nat__lt_trans(dw, {DB}n, 29n, hdw, {{==}}))

def hno(+dw: Nat, +N: U32, +hdw: {{Nat.is_lt(dw, {DB}n) == True{{}} : Bool}}, +hn: {HN}) -> {{Nat.is_le(U32.to_nat(N), A.quad(FD.spec_common__pow2(VL.DO(N)))) == True{{}} : Bool}}:
  +h0 = FD.logic__subst(Nat, z => {{Nat.is_le(z, VB.pw(VL.DO(N))) == True{{}} : Bool}}, Nat.add(VC.NW(N), 0n), VC.NW(N), FD.nat__add_zero(VC.NW(N)), EN.hdst(dw, N, hdw, hn))
  FD.nat__le_trans(U32.to_nat(N), A.quad(VC.NW(N)), A.quad(FD.spec_common__pow2(VL.DO(N))), VZ.quad_nw_ge(N, VL.KK(dw), VL.kk_lt(dw, hdw), VL.hyn(dw, N, hn)),
    C.q4(VC.NW(N), FD.spec_common__pow2(VL.DO(N)), h0))

# (i) on storage T of depth dw < {DB} holding N bytes
def a1(+dw: Nat, +T: FD.array__Tree<U32>, +N: U32, +pf: {{FD.array__perfect(U32, dw, T) == True{{}} : Bool}}, +hdw: {{Nat.is_lt(dw, {DB}n) == True{{}} : Bool}},
    +hn: {HN}, +hN: {{U32.is_le(N, {LIM}) == True{{}} : Bool}}) -> {G(OW, f'WO.wview({OW})')}:
  %Equal.sym(O.Words & B.Buf, {ENC(OW)}, ({OW}, B.Buf{{FD.array__thaw(U32, EN.OUT(N, T)), N}}), EN.encode_eval(dw, T, N, pf, hdw, hn, hN)) :
    {{Some{{E.obytes(Pair.snd(O.Words, B.Buf, _))}} == API.serialize(Spec.{X}(), S.BytesValue{{WO.wview({OW})}}) : Maybe<&2, +List<U32>>}}
  %Equal.sym(+List<U32>, E.obytes(B.Buf{{FD.array__thaw(U32, EN.OUT(N, T)), N}}), {BYT},
      EM.ob(VL.DO(N), EN.OUT(N, T), N, VB.mone_perfect(VC.NW(N), 0n, 0n, VL.DO(N), VC.ZT(VL.DO(N)), T, FD.array__trep_perfect(U32, VL.DO(N), 0)), hdo(dw, N, hdw, hn), hno(dw, N, hdw, hn))) :
    {{Some{{_}} == API.serialize(Spec.{X}(), S.BytesValue{{WO.wview({OW})}}) : Maybe<&2, +List<U32>>}}
  %Equal.sym(+List<U32>, WO.wview({OW}), BL.WX0(T, N), BL.wv0(T, N)) :
    {{Some{{{BYT}}} == API.serialize(Spec.{X}(), S.BytesValue{{_}}) : Maybe<&2, +List<U32>>}}
  Equal.sym(Maybe<&2, +List<U32>>, API.serialize(Spec.{X}(), EN.XV(T, N)), Some{{{BYT}}},
    Equal.trans(Maybe<&2, +List<U32>>, API.serialize(Spec.{X}(), EN.XV(T, N)), Encoding.encoding_for_legal_type(Spec.{X}(), EN.XV(T, N)), Some{{{BYT}}},
      E.serialize_legal(Spec.{X}(), EN.XV(T, N), VS.public_sound(Spec.{X}(), {{==}})), EN.encode_spec(dw, T, N, pf, hdw, hn, hN)))

# the schema's limit is the runtime's literal
def elim() -> {{SH.ByteList_limit(Spec.{X}()) == U32.to_nat({LIM}) : Nat}}: {{==}}

# the runtime's length check from rep's limit
def lim(+N: U32, +hl: {{Nat.is_le(U32.to_nat(N), SH.ByteList_limit(Spec.{X}())) == True{{}} : Bool}}) -> {{U32.is_le(N, {LIM}) == True{{}} : Bool}}:
  %Equal.sym(Bool, U32.is_le(N, {LIM}), Nat.is_le(U32.to_nat(N), U32.to_nat({LIM})), VU.le_u32(N, {LIM})) : {{_ == True{{}} : Bool}}
  %elim() : {{Nat.is_le(U32.to_nat(N), _) == True{{}} : Bool}}
  hl

# ---- (i) from the representation ----

def e2(-o: O.Words, +t: FD.array__Tree<U32>, +dw: Nat, +N: U32, +eo: {{o == O.Words{{FD.array__thaw(U32, t), N}} : O.Words}}, +pf: {{FD.array__perfect(U32, dw, t) == True{{}} : Bool}},
    +hdw: {{Nat.is_lt(dw, {DB}n) == True{{}} : Bool}}, +hn: {{Nat.is_le(U32.to_nat(N), A.quad(VB.pw(dw))) == True{{}} : Bool}},
    +hl: {{Nat.is_le(U32.to_nat(WO.len(o)), SH.ByteList_limit(Spec.{X}())) == True{{}} : Bool}}) -> {G('o', 'WO.wview(o)')}:
  +hN = lim(N, FD.logic__subst(O.Words, z => {{Nat.is_le(U32.to_nat(WO.len(z)), SH.ByteList_limit(Spec.{X}())) == True{{}} : Bool}}, o, O.Words{{FD.array__thaw(U32, t), N}}, eo, hl))
  %Equal.sym(O.Words, o, O.Words{{FD.array__thaw(U32, t), N}}, eo) : {G('_', 'WO.wview(_)')}
  a1(dw, t, N, pf, hdw, hn, hN)

# (i): for every object the root law represents, its storage at depth below {DB} (hs)
def {R}_e2e_encode(-o: O.Words, +rep: LO.rep_bl(o, Spec.{X}()), +hs: BL.sdk(o, {DB}n)) -> {G('o', 'WO.wview(o)')}:
  (+wf, +hl) = rep
  match hs:
    case Inl{{s}}:
      (+t, s1) = s
      (+dw, s2) = s1
      (+N, s3) = s2
      (+eo, s4) = s3
      (+pf, s5) = s4
      (+hdw, +en0) = s5
      +hn = FD.logic__subst(Nat, z => {{Nat.is_le(z, A.quad(VB.pw(dw))) == True{{}} : Bool}}, 0n, U32.to_nat(N), Equal.sym(Nat, U32.to_nat(N), 0n, en0), Order.zero_le(A.quad(VB.pw(dw))))
      e2(o, t, dw, N, eo, pf, hdw, hn, hl)
    case Inr{{s}}:
      (+t, s1) = s
      (+dw, s2) = s1
      (+N, s3) = s2
      (+q, s4) = s3
      (+r, s5) = s4
      (+eo, s6) = s5
      (+pf, s7) = s6
      (+hdw, s8) = s7
      (+eN, s9) = s8
      (+hr0, s10) = s9
      (+hr32, s11) = s10
      (+hcap, +bz) = s11
      +hq = FD.logic__subst(Nat, z => {{Nat.is_le(z, A.quad(O.e8(1n+q))) == True{{}} : Bool}}, Nat.add(r, WS.e32(q)), U32.to_nat(N),
        Equal.sym(Nat, U32.to_nat(N), Nat.add(r, WS.e32(q)), Equal.trans(Nat, U32.to_nat(N), Nat.add(WS.e32(q), r), Nat.add(r, WS.e32(q)), eN, FD.nat__add_comm(WS.e32(q), r))),
        Order.add_right(r, 32n, WS.e32(q), hr32))
      +hn = FD.nat__le_trans(U32.to_nat(N), A.quad(O.e8(1n+q)), A.quad(VB.pw(dw)), hq, C.q4(O.e8(1n+q), FD.spec_common__pow2(dw), hcap))
      e2(o, t, dw, N, eo, pf, hdw, hn, hl)
"""
    return f


VENC_SHAPES['Transaction'] = venc_bytelist(28, 1073741824)
VENC_PREMISE['Transaction'] = 'rep: LO.rep_bl(o, Spec.Transaction()) and hs: BL.sdk(o, 28n) (its storage at depth below 28: the encode laws take dw < 28, the root law dw < 32; dropped when the encode laws take dw < 32)'



# ---- views of the byte-offset windows (var_bytes_<X>_win: OBJw(t, i, len), VALw(t, i, len)) ----
# vw: RT.v_X(OBJw(t, i, len)) == VALw(t, i, len) at any word offset i. The window's object with its
# variable parts as holes (OBJH) views as XVw over the holes' values (vz: rewrite each hole's view,
# then evaluate the fixed fields); vw fills the holes.
import re as _re
import json
from pathlib import Path as _Path
_OBJ = _Path(__file__).resolve().parents[1] / 'proofs/obj'
_RT = _OBJ / 'root_types.bend'


def _defline(text, name):
    m = _re.search(r'^def ' + name + r'\((.*?)\) -> (.*?): (.*)$', text, _re.M)
    return m.group(1), m.group(2), m.group(3)


def _d_imports(text, body):
    return [l.replace('import ../../', 'import ../') for l in text.splitlines()
            if _re.match(r'import \.\./\.\./types/\S+ as (\w+_d)$', l) and _re.search(r'(?<![\w.])' + l.split()[-1] + r'\.', body)]


# holes: dicts {'obj': the part's text in OBJw, 'ty': its type, 'arg': the part at the call (W.-qualified),
# 'view': the view function of the part, 'vty': the view's type, 'val': the view's value (VALw's term),
# 'pf': the proof of view(arg) == val}; xv(ys) is XVw's last argument over the holes' values.
def vw_module(X, win, holes, xv, extra_imports=()):
    text = (_OBJ / f'{win}.bend').read_text()
    _, oty, body = _defline(text, 'OBJw')
    zs = [f'z{k}' for k in range(len(holes))]
    ys = [f'Y{k}' for k in range(len(holes))]
    bh = body
    for h, z in zip(holes, zs):
        assert h['obj'] in bh, (X, h['obj'])
        bh = bh.replace(h['obj'], z)
    imps = ['import Base', 'import ../src/obj.bend as O', 'import ../types/schema.bend as S', 'import ../types/primitive.bend as P',
            'import ../proofs/compact/found.bend as FD', 'import ../proofs/obj/spec_fixed.bend as F', 'import ../proofs/obj/vbuf.bend as VB',
            'import ../proofs/obj/vcopy.bend as VC', 'import ../proofs/obj/words_obj.bend as WO', 'import ../proofs/obj/root_types.bend as RT',
            f'import ../proofs/obj/{win}.bend as W', 'import ./e2e_blist.bend as BL'] + list(extra_imports) + _d_imports(text + '\n' + _RT.read_text(), body + oty + ' '.join(h['ty'] for h in holes))
    zp = ', '.join(f'{z}: {h["ty"]}' for z, h in zip(zs, holes))
    L = ['\n'.join(dict.fromkeys(imps)), '',
         '# GENERATED by codegen/e2e_bridge.py (codegen/e2e_var_b.py). Do not edit.',
         f'# {X}\'s byte-offset window ({win}): the root view of the object it reads is its value at any',
         '# word offset i (vw). OBJH is the window\'s object with its variable parts as holes (vz: each hole\'s',
         '# view rewritten to its value, the fixed fields by evaluation).', '',
         f'def OBJH(+t: FD.array__Tree<U32>, +i: Nat, {zp}) -> {oty}: {bh}', '']
    hyps = ', '.join(f'{z}: {h["ty"]}, +{y}: {h["vty"]}, +e{k}: {{{h["view"]}({z}) == {y} : {h["vty"]}}}' for k, (z, y, h) in enumerate(zip(zs, ys, holes)))
    L.append(f'def vz(+t: FD.array__Tree<U32>, +i: Nat, {hyps}) -> {{RT.v_{X}(OBJH(t, i, {", ".join(zs)})) == W.XVw(t, i, {xv(ys)}) : S.Value}}:')
    for k in range(len(holes)):
        cur = [f'{holes[j]["view"]}({zs[j]})' if j < k else ('_' if j == k else ys[j]) for j in range(len(holes))]
        L.append(f'  %e{k} : {{RT.v_{X}(OBJH(t, i, {", ".join(zs)})) == W.XVw(t, i, {xv(cur)}) : S.Value}}')
    L.append('  {==}')
    L.append('')
    args = ', '.join(f'{h["arg"]}, {h["val"]}, {h["pf"]}' for h in holes)
    L.append(f'def vw(+t: FD.array__Tree<U32>, +i: Nat, +len: U32) -> {{RT.v_{X}(W.OBJw(t, i, len)) == W.VALw(t, i, len) : S.Value}}:')
    L.append(f'  vz(t, i, {args})')
    return '\n'.join(L) + '\n'


SUPPORT_OUT['e2e_vw_ExecutionPayloadHeader.bend'] = vw_module('ExecutionPayloadHeader', 'var_bytes_ExecutionPayloadHeader_win', [
    {'obj': 'O.Words{FD.array__thaw(U32, MKw(t, i, len)), LL(len)}', 'ty': 'O.Words', 'arg': 'O.Words{FD.array__thaw(U32, W.MKw(t, i, len)), W.LL(len)}',
     'view': 'WO.wview', 'vty': '+List<U32>', 'val': 'W.YB(t, i, len)', 'pf': 'BL.wvb(W.MKw(t, i, len), W.LL(len))'}], lambda ys: ys[0])


# (ii)/(iii) of a name whose codec object is its window's at word offset 0 (DC.OBJ(t, n) =
# W.OBJw(t, 0n, n), DC.VAL(t, n) = W.VALw(t, 0n, n)): the view lemma is the window's vw.
def vdec_win(X, bound, vwmod):
    return {'view': f'RT.v_{X}',
            'imports': ['import ../proofs/obj/root_types.bend as RT', f'import ./{vwmod}.bend as VWX'],
            'text': f'''# ---- the view of a decoded object is the codec law's value (the window's view, at offset 0) ----

def vv(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +pf: {{FD.array__perfect(U32, d, t) == True{{}} : Bool}}, +hd: {{Nat.is_lt(d, {bound}n) == True{{}} : Bool}},
    +hn: {{Nat.is_le(U32.to_nat(n), A.quad(FD.spec_common__pow2(d))) == True{{}} : Bool}}, +hchk: {{DC.CHK(t, n) == True{{}} : Bool}}) -> {{RT.v_{X}(DC.OBJ(t, n)) == DC.VAL(t, n) : S.Value}}:
  VWX.vw(t, 0n, n)

'''}


VDEC_VIEWS['ExecutionPayloadHeader'] = vdec_win('ExecutionPayloadHeader', 29, 'e2e_vw_ExecutionPayloadHeader')


# ---- rebuilding an object from its root law's representation invariant (e2e/e2e_rb.bend) ----
# RT.rep_Y(o, s) names Y's fixed fields (Ex binders), o == CONS (its fields, the storage-backed ones
# as projections pj(o)) and each storage-backed field's invariant. nw_Y turns it into WIT_Y(o): copyable
# witnesses (the fixed fields; each word-storage field's tree and length; each boxed or nested
# container's own witnesses) and o == BUILD_Y(witnesses), so a law about o can be restated over a
# copyable object (the laws of END_TO_END take the value as a + parameter).
_RT = (_OBJ / 'root_types.bend')

WORDS_KINDS = {  # storage invariant: (its wf's Ex binders before the equation, a wfl-like Or2?)
    'WO.rep_bv': (['t', 'dw', 'N', 'q', 'rr'], False), 'LO.rep_bl': (None, True), 'PV.rep_pv': (['t', 'dw', 'N', 'q'], False),
    'E48.rep_ev': (['t', 'dw', 'N'], False), 'E48.rep_el': (['t', 'dw', 'N'], False), 'CE.rep_el': (['t', 'dw', 'N'], False)}


def split_args(s):
    out, dep, cur, prev = [], 0, '', ''
    for c in s:
        if c in '([{<':
            dep += 1
        elif c in ')]}' or (c == '>' and prev not in '=-'):
            dep -= 1
        prev = c
        if c == ',' and dep == 0:
            out.append(cur.strip())
            cur = ''
        else:
            cur += c
    if cur.strip():
        out.append(cur.strip())
    return out


def call(s):
    m = _re.match(r'([\w.]+)\((.*)\)$', s.strip(), _re.S)
    return (m.group(1), split_args(m.group(2))) if m else (None, None)


_rt_cache = {}


def rt_def(name):
    if 'text' not in _rt_cache:
        _rt_cache['text'] = _RT.read_text()
    t = _rt_cache['text']
    m = _re.search(r'^def ' + name + r'\((.*?)\) -> (.*?):\n  (.*)$', t, _re.M)
    if m:
        return m.group(1), m.group(2), m.group(3)
    m = _re.search(r'^def ' + name + r'\((.*?)\) -> (.*?): (.*)$', t, _re.M)
    return (m.group(1), m.group(2), m.group(3)) if m else None


def rep_info(Y):
    """(binders [(x, type)], CONS, otype, fields [(pj, rep call name, schema, field type)])."""
    params, _, body = rt_def('rep_' + Y)
    otype = _re.match(r'o: (.*), \+s: S\.Schema$', params).group(1)
    binders = []
    while body.startswith('DK.Ex('):
        n, a = call(body)
        ty, lam = a
        x, rest = _re.match(r'(\w+) => (.*)$', lam, _re.S).groups()
        binders.append((x, ty))
        body = rest
    n, a = call(body) if body.startswith('DK.P2(') else (None, [body, None])
    eq, rest = a
    cons = _re.match(r'\{o == (.*) : ' + _re.escape(otype) + r'\}$', eq, _re.S).group(1)
    fields = []
    while rest is not None:
        if rest.startswith('DK.P2('):
            _, (f, rest) = call(rest)
        else:
            f, rest = rest, None
        fn, fa = call(f)
        pj = fa[0]
        pjn = call(pj)[0]
        fty = rt_def(pjn)[1]
        fields.append((pj, fn, fa[1], fty))
    return binders, cons, otype, fields


def field_kind(fn):
    if fn in WORDS_KINDS:
        return ('words', None)
    if fn.startswith('rep_') and fn.endswith('_bx'):
        body = rt_def(fn)[2]
        if body.startswith('DK.Ex('):
            _, (ty, _) = call(body)
            return ('dbox', ty)
        Z = fn[4:-3]
        return ('rbox', Z)
    if fn.startswith('rep_') and rt_def(fn):
        return ('rec', fn[4:])
    raise SystemExit(f'e2e_var_b: unknown field invariant {fn}')


class Wit:
    """Y's witnesses: [(type)], and BUILD_Y over witness names."""
    def __init__(self, Y):
        self.Y = Y
        binders, cons, otype, fields = rep_info(Y)
        self.otype, self.binders, self.cons, self.fields = otype, binders, cons, fields
        self.tys = [ty for _, ty in binders]
        self.parts = []  # per field: (kind, info, slice of witness indices)
        for pj, fn, sch, fty in fields:
            k, info = field_kind(fn)
            i0 = len(self.tys)
            if k == 'words':
                self.tys += ['FD.array__Tree<U32>', 'U32']
            elif k == 'dbox':
                self.tys += [info]
            else:
                sub = wit(info)
                self.tys += sub.tys
            self.parts.append((k, info, list(range(i0, len(self.tys)))))

    def field_term(self, j, names):
        k, info, idx = self.parts[j]
        ns = [names[i] for i in idx]
        if k == 'words':
            return f'O.Words{{FD.array__thaw(U32, {ns[0]}), {ns[1]}}}'
        if k == 'dbox':
            return f'O.BSome{{{ns[0]}, O.BNone{{}}}}'
        if k == 'rbox':
            return f'O.BSome{{{wit(info).build(ns)}, O.BNone{{}}}}'
        return wit(info).build(ns)

    def cons_with(self, names, upto, o='o'):
        """CONS with the binders named and fields < upto replaced by their witness terms."""
        c = self.cons
        for (x, _), nm in zip(self.binders, names):
            c = _re.sub(r'(?<![\w.])' + x + r'(?![\w])', nm, c)
        for j in range(upto):
            c = c.replace(self.fields[j][0], self.field_term(j, names), 1)
        if o != 'o':
            c = c.replace('(o)', f'({o})')
        return c

    def build(self, names):
        return self.cons_with(names, len(self.fields))


_wits = {}


def wit(Y):
    if Y not in _wits:
        _wits[Y] = Wit(Y)
    return _wits[Y]


def _wtype(ty):
    return ty if ty.startswith(('O.', 'FD.', 'U32', 'Nat')) else f'RT.{ty}' if _re.match(r'\w+$', ty) else ty


def rb_defs(Y, done):
    """WIT_Y, mk_Y, nw_Y (after the ones of its nested containers)."""
    w = wit(Y)
    L = []
    for k, info, _ in w.parts:
        if k in ('rbox', 'rec') and info not in done:
            L += rb_defs(info, done)
    done.add(Y)
    n = len(w.tys)
    a = [f'a{i}' for i in range(n)]
    OT = w.otype
    body = f'{{o == {w.build(a)} : {OT}}}'
    for i in reversed(range(n)):
        body = f'DK.Ex({w.tys[i]}, {a[i]} => {body})'
    L.append(f'# {Y}: its witnesses and the object over them')
    L.append(f'def WIT_{Y}(o: {OT}) -> Data:\n  {body}\n')
    tup = 'e'
    for i in reversed(range(n)):
        tup = f'({a[i]}, {tup})'
    ps = ', '.join(f'+{a[i]}: {w.tys[i]}' for i in range(n))
    L.append(f'def mk_{Y}(-o: {OT}, {ps}, +e: {{o == {w.build(a)} : {OT}}}) -> WIT_{Y}(o):\n  {tup}\n')
    # nw_Y: rep's fixed witnesses, equation and field invariants; each field's witnesses computed here
    # and destructured in nw2_Y (a computed local can only be destructured as a parameter)
    nf = len(w.fields)
    nb = len(w.binders)
    L0 = L
    L = []
    L.append(f'def nw_{Y}(-o: {OT}, +s: S.Schema, +rep: RT.rep_{Y}(o, s)) -> WIT_{Y}(o):')
    cur = 'rep'
    for i in range(nb):
        L.append(f'  (+{a[i]}, q{i}) = {cur}')
        cur = f'q{i}'
    if nf == 0:
        L.append(f'  mk_{Y}(o, {", ".join(a)}, {cur})\n')
        return L0 + L
    if nf == 1:
        L.append(f'  (+eo, +r0) = {cur}')
    else:
        L.append(f'  (+eo, qe) = {cur}')
        cur = 'qe'
        for j in range(nf - 1):
            if j == nf - 2:
                L.append(f'  (+r{j}, +r{j + 1}) = {cur}')
            else:
                L.append(f'  (+r{j}, qf{j}) = {cur}')
                cur = f'qf{j}'
    args, params = [], []
    for j, (pj, fn, sch, fty) in enumerate(w.fields):
        k, info, idx = w.parts[j]
        if k == 'words':
            args.append(f'ww_{fn.replace(".", "_")}({pj}, {sch}, r{j})')
            params.append(f'+w{j}: WW({pj})')
        elif k == 'dbox':
            L.append(f'  (+v{j}, +ev{j}) = r{j}')
            args += [f'v{j}', f'ev{j}']
            params += [f'+{a[idx[0]]}: {w.tys[idx[0]]}', f'+e{j}: {{{pj} == O.BSome{{{a[idx[0]]}, O.BNone{{}}}} : {_wtype(fty)}}}']
        elif k == 'rbox':
            inner = f'pjb_{info}_bx({pj})'
            L.append(f'  (+eb{j}, +ri{j}) = r{j}')
            args += [f'eb{j}', f'nw_{info}({inner}, {sch}, ri{j})']
            params += [f'+eb{j}: {{{pj} == O.BSome{{{inner}, O.BNone{{}}}} : {_wtype(fty)}}}', f'+w{j}: WIT_{info}({inner})']
        else:
            args.append(f'nw_{info}({pj}, {sch}, r{j})')
            params.append(f'+w{j}: WIT_{info}({pj})')
    L.append(f'  nw2_{Y}(o, {", ".join(a[:nb])}, eo, {", ".join(args)})\n')
    Lnw = L
    L = L0
    pfix = ', '.join(f'+{a[i]}: {w.tys[i]}' for i in range(nb))
    L.append(f'def nw2_{Y}(-o: {OT}, {pfix + ", " if pfix else ""}+eo: {{o == {w.cons_with(a, 0)} : {OT}}}, {", ".join(params)}) -> WIT_{Y}(o):')
    for j, (pj, fn, sch, fty) in enumerate(w.fields):  # destructure first: no let may precede a match
        k, info, idx = w.parts[j]
        ns = [a[i] for i in idx]
        if k == 'words':
            L.append(f'  (+{ns[0]}, w{j}a) = w{j}')
            L.append(f'  (+{ns[1]}, +e{j}) = w{j}a')
        elif k in ('rbox', 'rec'):
            c = f'w{j}'
            for i2, nm in enumerate(ns):
                last = i2 == len(ns) - 1
                L.append(f'  (+{nm}, {"+ei" + str(j) if last else c + "_" + str(i2)}) = {c}')
                c = f'{c}_{i2}'
    eq = 'eo'
    for j, (pj, fn, sch, fty) in enumerate(w.fields):
        k, info, idx = w.parts[j]
        ns = [a[i] for i in idx]
        fty_q = _wtype(fty)
        if k == 'rbox':
            sub = wit(info)
            inner = f'pjb_{info}_bx({pj})'
            BT = f'O.Boxed<{sub.otype}>'
            L.append(f'  +e{j} = Equal.trans({BT}, {pj}, O.BSome{{{inner}, O.BNone{{}}}}, O.BSome{{{sub.build(ns)}, O.BNone{{}}}}, eb{j},')
            L.append(f'    Equal.cong({sub.otype}, {BT}, z => O.BSome{{z, O.BNone{{}}}}, {inner}, {sub.build(ns)}, ei{j}))')
        elif k == 'rec':
            L.append(f'  +e{j} = ei{j}')
        cj, cj1 = w.cons_with(a, j), w.cons_with(a, j + 1)
        hole = cj.replace(pj, 'z', 1)
        L.append(f'  +c{j} = Equal.trans({OT}, o, {cj}, {cj1}, {eq}, Equal.cong({fty_q}, {OT}, z => {hole}, {pj}, {w.field_term(j, a)}, e{j}))')
        eq = f'c{j}'
    L.append(f'  mk_{Y}(o, {", ".join(a)}, {eq})\n')
    return L + Lnw


def rb_text(names):
    done = set()
    L = []
    for Y in names:
        if Y not in done:
            L += rb_defs(Y, done)
    body = '\n'.join(L)
    body = _re.sub(r'(?<![\w.])(pj_\w+|pjb_\w+)\(', r'RT.\1(', body).replace('RT.RT.', 'RT.')
    rtt = _RT.read_text()
    dimps = [l.replace('import ../../', 'import ../') for l in rtt.splitlines()
             if _re.match(r'import \.\./\.\./types/\S+ as (\w+_d)$', l) and (l.split()[-1] + '.') in body]
    head = ['import Base', 'import ../src/obj.bend as O', 'import ../types/schema.bend as S', 'import ../proofs/compact/found.bend as FD',
            'import ../proofs/obj/dk.bend as DK', 'import ../proofs/obj/words_obj.bend as WO', 'import ../proofs/obj/list_obj.bend as LO',
            'import ../proofs/obj/pv_obj.bend as PV', 'import ../proofs/obj/elems48.bend as E48', 'import ../proofs/obj/cells.bend as CE',
            'import ../proofs/obj/schema_shapes.bend as SH', 'import ../proofs/obj/root_types.bend as RT'] + dimps
    ww = ['', '# GENERATED by codegen/e2e_bridge.py (codegen/e2e_var_b.py). Do not edit.',
          '# Objects rebuilt from their root laws\' representation invariants (RT.rep_Y): WIT_Y(o) is copyable',
          '# witnesses with o == the object over them; nw_Y derives it from rep_Y.', '',
          '# word storage: its tree and length',
          'def WW(w: O.Words) -> Data: DK.Ex(FD.array__Tree<U32>, t => DK.Ex(U32, N => {w == O.Words{FD.array__thaw(U32, t), N} : O.Words}))', '',
          'def mkw(-w: O.Words, +t: FD.array__Tree<U32>, +N: U32, +e: {w == O.Words{FD.array__thaw(U32, t), N} : O.Words}) -> WW(w): (t, (N, e))', '']
    for fn, (bs, orr) in WORDS_KINDS.items():
        mod, rn = fn.split('.')
        nm = fn.replace('.', '_')
        ww.append(f'def ww_{nm}(-w: O.Words, +s: S.Schema, +r: {fn}(w, s)) -> WW(w):')
        ww.append('  (+f, +n) = r')
        if orr:
            ww.append('  match f:')
            for case, b in (('Inl', ['t', 'dw', 'N']), ('Inr', ['t', 'dw', 'N', 'q', 'rr'])):
                ww.append(f'    case {case}{{g}}:')
                cur = 'g'
                for i, x in enumerate(b):
                    ww.append(f'      (+{x}, g{i}) = {cur}')
                    cur = f'g{i}'
                ww.append(f'      (+eo, g9) = {cur}')
                ww.append('      mkw(w, t, N, eo)')
        else:
            cur = 'f'
            for i, x in enumerate(bs):
                ww.append(f'  (+{x}, g{i}) = {cur}')
                cur = f'g{i}'
            ww.append(f'  (+eo, g9) = {cur}')
            ww.append('  mkw(w, t, N, eo)')
        ww.append('')
    return '\n'.join(head + ww) + '\n' + body + '\n'


RB_NAMES = ['ExecutionPayloadHeader', 'LightClientHeader']
SUPPORT_OUT['e2e_rb.bend'] = rb_text(RB_NAMES)


# (iv) of a container through e2e_rb: rep's witnesses give a copyable object; then root_correct,
# the validity lemma and END_TO_END's root law on it.
def vroot_container(R, X):
    w = wit(X)
    n = len(w.tys)
    a = [f'a{i}' for i in range(n)]
    OT = w.otype
    B_ = w.build(a)
    RX = lambda o: f'D.bytes(Pair.snd({OT}, D.Digest, Pair.snd(B.Buf, {OT} & D.Digest, {R}_h.{X}_hash_tree_root(h, {o}))))'
    G = lambda o: f'{{Some{{{RX(o)}}} == API.hash_tree_root(Spec.{X}(), RT.v_{X}({o})) : Maybe<&2, +List<U32>>}}'
    ps = ', '.join(f'+{a[i]}: {w.tys[i]}' for i in range(n))
    body = '\n'.join([
        f'def rt1(h: B.Buf, {ps}, +rep: RT.rep_{X}({B_}, Spec.{X}())) -> {G(B_)}:',
        f'  E.root_legal(Spec.{X}(), RT.v_{X}({B_}), VS.public_sound(Spec.{X}(), {{==}}), {RX(B_)},',
        f'    GV.{X}_root_valid({B_}, Spec.{X}(), {{==}}, rep), RT.{X}_root_correct(h, {B_}, Spec.{X}(), {{==}}, rep))', '',
        '# the object as rep\'s witnesses name it',
        f'def rt2(h: B.Buf, -o: {OT}, +rep: RT.rep_{X}(o, Spec.{X}()), {ps}, +eo: {{o == {B_} : {OT}}}) -> {G("o")}:',
        f'  %Equal.sym({OT}, o, {B_}, eo) : {G("_")}',
        f'  rt1(h, {", ".join(a)}, FD.logic__subst({OT}, z => RT.rep_{X}(z, Spec.{X}()), o, {B_}, eo, rep))', '',
        f'def rt3(h: B.Buf, -o: {OT}, +rep: RT.rep_{X}(o, Spec.{X}()), +w: RB.WIT_{X}(o)) -> {G("o")}:'] +
        [f'  (+{a[i]}, {"+eo" if i == n - 1 else "w" + str(i)}) = {"w" if i == 0 else "w" + str(i - 1)}' for i in range(n)] +
        [f'  rt2(h, o, rep, {", ".join(a)}, eo)', '', '# (iv)',
         f'def {R}_e2e_root(h: B.Buf, -o: {OT}, +rep: RT.rep_{X}(o, Spec.{X}())) -> {G("o")}:',
         f'  rt3(h, o, rep, RB.nw_{X}(o, Spec.{X}(), rep))'])
    rtt = _RT.read_text()
    dimps = [l.replace('import ../../', 'import ../') for l in rtt.splitlines()
             if _re.match(r'import \.\./\.\./types/\S+ as (\w+_d)$', l) and (l.split()[-1] + '.') in body]
    imps = ['import Base', 'import ../END_TO_END.bend as E2E', 'import ../src/model.bend as API', 'import ../src/buffer.bend as B',
            'import ../src/digest.bend as D', 'import ../src/obj.bend as O', f'import ../types/{R}_hashtreeroot_generated.bend as {R}_h',
            'import ../types/schema.bend as S', 'import ../spec/fulu_schemas.bend as Spec', 'import ../proofs/type_validator_soundness.bend as VS',
            'import ../proofs/compact/found.bend as FD', 'import ../proofs/obj/root_types.bend as RT', 'import ../proofs/obj/gvalid_types.bend as GV',
            'import ./e2e_support.bend as E', 'import ./e2e_rb.bend as RB'] + dimps
    return '\n'.join(dict.fromkeys(imps)) + f"""

# GENERATED by codegen/e2e_bridge.py (codegen/e2e_var_b.py). Do not edit.
# {R} (variable size): the object API's root is END_TO_END's hash_tree_root, for every object the root
# law represents (rep_{X}); the object is rebuilt from rep's witnesses (e2e_rb.nw_{X}).

""" + body + '\n'


VROOT_SHAPES['ExecutionPayloadHeader'] = vroot_container


# ---- byte lists in the root invariant: the zero tail (e2e/e2e_tz.bend) ----
# The root law's byte storage has its chunk's bytes after the length zero (wf1:
# bdrop(r, cb(slots t, q)) == zero_bytes(32 - r), N = 32 q + r, 1 <= r <= 32); the encode laws take
# the word form, O.tail_zero(N & 3, slot(t, N >> 2)). tz derives the second from the first: r = 4a + b,
# N >> 2 = 8q + a and N & 3 = b (halvings, e2e bits of N), then the bytes b..3 of word 8q + a are zero
# (the chunk's bytes from r), and a word whose bytes b..3 are zero has tail_zero(b) (its bits, tzw_b).
def _uw(xs):
    return 'U32{' + ''.join(f'WCon{{{x}, ' for x in xs) + 'WNil{}' + '}' * len(xs) + '}'


def tz_text():
    L = ['import Base', 'import ../src/obj.bend as O', 'import ../src/primitives.bend as I', 'import ../proofs/compact/found.bend as FD',
         'import ../proofs/compact/arith.bend as A', 'import ../proofs/obj/spec_fixed.bend as FX', 'import ../proofs/obj/vbuf.bend as VB',
         'import ../proofs/obj/vcopy.bend as VC', 'import ../proofs/obj/vbrt.bend as VR', 'import ../proofs/obj/vbytes.bend as VY',
         'import ../proofs/obj/vdepth.bend as VD', 'import ../proofs/obj/words_spec.bend as WS', 'import ../proofs/obj/mtree_run.bend as MR',
         'import ../spec/primitives.bend as SP', '',
         '# GENERATED by codegen/e2e_bridge.py (codegen/e2e_var_b.py). Do not edit.',
         '# Byte storage in the root invariant: its zero tail as the encode laws take it (tz).', '']
    xs = [f'x{i}' for i in range(32)]
    pat = _uw([f'+{x}' for x in xs])
    for i in range(8):
        L.append(f'def pb{i}(+u: U32) -> Bool:\n  match u:\n    case {pat}: x{i}\n')
    L.append('def andT(+x: Bool, +h: {Bool.and(x, True{}) == False{} : Bool}) -> {x == False{} : Bool}:\n  match x:\n'
             '    case True{}: Empty.absurd({True{} == False{} : Bool}, FD.logic__false_true(Equal.sym(Bool, True{}, False{}, h)))\n'
             '    case False{}: {==}\n')
    hyp = {1: '+e1: {U32.and(U32.shrn(w, 8n), 255) == 0 : U32}', 2: '+e2: {U32.and(U32.shrn(w, 16n), 255) == 0 : U32}', 3: '+e3: {U32.shrn(w, 24n) == 0 : U32}'}
    W = _uw(xs)
    for b in (1, 2, 3):
        hw = {j: (f'+e{j}: {{U32.shrn({W}, 24n) == 0 : U32}}' if j == 3 else f'+e{j}: {{U32.and(U32.shrn({W}, {8 * j}n), 255) == 0 : U32}}') for j in range(b, 4)}
        L.append(f'def tzg{b}({", ".join("+" + x + ": Bool" for x in xs)}, {", ".join(hw[j] for j in range(b, 4))}) -> {{O.tail_zero({b}, {W}) == True{{}} : Bool}}:')
        for j in range(b, 4):
            lhs = f'U32.shrn({W}, 24n)' if j == 3 else f'U32.and(U32.shrn({W}, {8 * j}n), 255)'
            for i in range(8):
                pr = f'Equal.cong(U32, Bool, u => pb{i}(u), {lhs}, 0, e{j})'
                L.append(f'  +f{8 * j + i} = {pr if j == 3 else f"andT(x{8 * j + i}, {pr})"}')
        cur = list(xs)
        for k in range(8 * b, 32):
            mot = list(cur)
            mot[k] = '_'
            L.append(f'  %Equal.sym(Bool, x{k}, False{{}}, f{k}) : {{O.tail_zero({b}, {_uw(mot)}) == True{{}} : Bool}}')
            cur[k] = 'False{}'
        L.append('  {==}\n')
        L.append(f'# a word whose bytes {b}..3 are zero')
        L.append(f'def tzw{b}(+w: U32, {", ".join(hyp[j] for j in range(b, 4))}) -> {{O.tail_zero({b}, w) == True{{}} : Bool}}:')
        L.append('  match w:')
        L.append(f'    case {pat}: tzg{b}({", ".join(xs)}, {", ".join("e" + str(j) for j in range(b, 4))})\n')
    bv = lambda x: f'FD.spec_numeric__bit_value({x})'
    # halving twice: s_rng(2, b + 4 X) = X for b < 4
    for b in range(4):
        b0, b1 = ('True{}' if b & 1 else 'False{}'), ('True{}' if b & 2 else 'False{}')
        inner = f'Nat.add({bv(b1)}, Nat.double(X))'
        L.append(f'def hq{b}(+X: Nat) -> {{VD.s_rng(2n, Nat.add({b}n, A.quad(X))) == X : Nat}}:')
        L.append(f'  %Equal.sym(Nat, VD.s_h2(Nat.add({bv(b0)}, Nat.double({inner}))), {inner}, VD.s_h2_bit({b0}, {inner})) : {{VD.s_h2(_) == X : Nat}}')
        L.append(f'  VD.s_h2_bit({b1}, X)\n')
    L.append('# the byte of a list at a position (0 past its end)')
    L.append('def bat(+k: Nat, +xs: +List<U32>) -> U32:\n  match k xs:\n    case 0n Nil{}: 0\n    case 0n Con{+h, +t}: h\n    case 1n+ +p Nil{}: 0\n    case 1n+ +p Con{+h, +t}: bat(p, t)\n')
    HN = '+eN: {U32.to_nat(N) == Nat.add(e32q, r) : Nat}'
    ZB = '+zb: {WS.bdrop(r, WS.cb(FD.array__slots(U32, t), q)) == SP.zero_bytes(Nat.sub(32n, r)) : +List<U32>}'
    GOAL = '{O.tail_zero(U32.and(N, 3), VB.slot(t, VY.QL(N))) == True{} : Bool}'
    for R in range(1, 33):
        a, b = R // 4, R % 4
        E = 'O.e8(q)'
        X = f'Nat.add({a}n, {E})'
        L.append(f'# r = {R} = 4 * {a} + {b}')
        L.append(f'def lf{R}(+t: FD.array__Tree<U32>, +N: U32, +q: Nat, +e32q: Nat, +ee: {{e32q == WS.e32(q) : Nat}}, +r: Nat, +er: {{r == {R}n : Nat}}, {HN}, {ZB}) -> {GOAL}:')
        L.append(f'  +e2 = Equal.trans(Nat, U32.to_nat(N), Nat.add(e32q, r), Nat.add({b}n, A.quad({X})), eN,')
        L.append(f'    FD.logic__subst(Nat, z => {{Nat.add(e32q, z) == Nat.add({b}n, A.quad({X})) : Nat}}, {R}n, r, Equal.sym(Nat, r, {R}n, er),')
        L.append(f'      FD.logic__subst(Nat, z => {{Nat.add(z, {R}n) == Nat.add({b}n, A.quad({X})) : Nat}}, WS.e32(q), e32q, Equal.sym(Nat, e32q, WS.e32(q), ee),')
        L.append(f'        Equal.trans(Nat, Nat.add(WS.e32(q), {R}n), Nat.add({R}n, WS.e32(q)), Nat.add({b}n, A.quad({X})), FD.nat__add_comm(WS.e32(q), {R}n), {{==}}))))')
        L.append(f'  +eQ = Equal.trans(Nat, VY.QL(N), VD.s_rng(2n, U32.to_nat(N)), {X}, VD.shrk(2n, N),')
        L.append(f'    FD.logic__subst(Nat, z => {{VD.s_rng(2n, z) == {X} : Nat}}, Nat.add({b}n, A.quad({X})), U32.to_nat(N), Equal.sym(Nat, U32.to_nat(N), Nat.add({b}n, A.quad({X})), e2), hq{b}({X})))')
        L.append(f'  +e1 = FD.logic__subst(Nat, z => {{U32.to_nat(N) == Nat.add(A.quad(z), U32.to_nat(U32.and(N, 3))) : Nat}}, VY.QL(N), {X}, eQ, VC.split4(N))')
        L.append(f'  +eR = FD.lru_subtraction_bounds__cancel_left(A.quad({X}), U32.to_nat(U32.and(N, 3)), {b}n,')
        L.append(f'    Equal.trans(Nat, Nat.add(A.quad({X}), U32.to_nat(U32.and(N, 3))), U32.to_nat(N), Nat.add(A.quad({X}), {b}n), Equal.sym(Nat, U32.to_nat(N), Nat.add(A.quad({X}), U32.to_nat(U32.and(N, 3))), e1),')
        L.append(f'      Equal.trans(Nat, U32.to_nat(N), Nat.add({b}n, A.quad({X})), Nat.add(A.quad({X}), {b}n), e2, FD.nat__add_comm({b}n, A.quad({X})))))')
        L.append(f'  +eA = FD.u32__injective(U32.and(N, 3), {b}, eR)')
        L.append(f'  %Equal.sym(U32, U32.and(N, 3), {b}, eA) : {{O.tail_zero(_, VB.slot(t, VY.QL(N))) == True{{}} : Bool}}')
        if b == 0:
            L.append('  {==}\n')
            continue
        L.append(f'  %Equal.sym(Nat, VY.QL(N), {X}, eQ) : {{O.tail_zero({b}, VB.slot(t, _)) == True{{}} : Bool}}')
        L.append(f'  %Equal.sym(Nat, {X}, Nat.add({E}, {a}n), FD.nat__add_comm({a}n, {E})) : {{O.tail_zero({b}, VB.slot(t, _)) == True{{}} : Bool}}')
        L.append(f'  +zc = FD.logic__subst(Nat, z => {{WS.bdrop(z, WS.cb(FD.array__slots(U32, t), q)) == SP.zero_bytes(Nat.sub(32n, z)) : +List<U32>}}, r, {R}n, er, zb)')
        w = f'VB.slot(t, Nat.add({E}, {a}n))'
        lhs = f'WS.bdrop({R}n, WS.cb(FD.array__slots(U32, t), q))'
        facts = []
        for j in range(b, 4):
            facts.append(f'Equal.cong(+List<U32>, U32, xs => bat({j - b}n, xs), {lhs}, SP.zero_bytes(Nat.sub(32n, {R}n)), zc)')
        L.append(f'  tzw{b}({w}, {", ".join(facts)})\n')
    # r = k + p, k = 1 .. 33
    for k in range(33, 0, -1):
        L.append(f'def tr{k}(+t: FD.array__Tree<U32>, +N: U32, +q: Nat, +e32q: Nat, +ee: {{e32q == WS.e32(q) : Nat}}, +r: Nat, +p: Nat, +erp: {{r == Nat.add({k}n, p) : Nat}},')
        L.append(f'    +h32: {{Nat.is_le(r, 32n) == True{{}} : Bool}}, {HN}, {ZB}) -> {GOAL}:')
        if k == 33:
            L.append(f'  Empty.absurd({GOAL}, FD.logic__false_true(FD.logic__subst(Nat, z => {{Nat.is_le(z, 32n) == True{{}} : Bool}}, r, Nat.add(33n, p), erp, h32)))\n')
            continue
        L.append('  match p:')
        L.append(f'    case 0n: lf{k}(t, N, q, e32q, ee, r, erp, eN, zb)')
        L.append(f'    case 1n+ +p1: tr{k + 1}(t, N, q, e32q, ee, r, p1, erp, h32, eN, zb)\n')
    L.append('# the zero tail of byte storage in the root invariant, as the encode laws take it')
    L.append('def tz(+t: FD.array__Tree<U32>, +N: U32, +q: Nat, +r: Nat, +eN: {U32.to_nat(N) == Nat.add(WS.e32(q), r) : Nat}, +h1: {Nat.is_lt(0n, r) == True{} : Bool},')
    L.append('    +h32: {Nat.is_le(r, 32n) == True{} : Bool}, +zb: {WS.bdrop(r, WS.cb(FD.array__slots(U32, t), Nat.add(q, 0n))) == SP.zero_bytes(Nat.sub(32n, r)) : +List<U32>})')
    L.append(f'    -> {GOAL}:')
    L.append('  match r:')
    L.append(f'    case 0n: Empty.absurd({GOAL}, FD.logic__false_true(h1))')
    L.append('    case 1n+ +p: tr1(t, N, q, WS.e32(q), {==}, 1n+p, p, {==}, h32, eN,')
    L.append('      FD.logic__subst(Nat, z => {WS.bdrop(1n+p, WS.cb(FD.array__slots(U32, t), z)) == SP.zero_bytes(Nat.sub(32n, 1n+p)) : +List<U32>}, Nat.add(q, 0n), q, FD.nat__add_zero(q), zb))\n')
    return '\n'.join(L) + '\n'


SUPPORT_OUT['e2e_tz.bend'] = tz_text()


# ---- views of the encode laws' objects (var_bytes_enc modules: OBJE(ps), XE(ps) = XEY(..)) ----
# ve: RT.v_X(EN.OBJE(ps)) == EN.XE(ps) over the laws' free words and storage trees. The storage
# fields are holes: a byte list's view is its bytes (BL.wvb), a byte vector's its first k words
# (BL.wbv: perfect tree with room), a Bytes32 vector's its chunks (BL.pvh), a nested encoded object's
# its own ve; the fixed fields evaluate.
VE_MODS = {}   # enc module file -> (ve module, X)


def _def_full(text, name):
    m = _re.search(r'^def ' + name + r'\((.*?)\) -> (.*?): (.*)$', text, _re.M)
    return m.group(1), m.group(2), m.group(3)


def _params(ps):
    return [(p.split(':')[0].strip().lstrip('+-'), p.split(':', 1)[1].strip()) for p in split_args(ps)]


def _ctor_args(term):
    m = _re.match(r'([\w.]+)\{(.*)\}$', term.strip(), _re.S)
    return m.group(1), split_args(m.group(2))


def _flat_fields(body):
    c, args = _ctor_args(body)
    out = []
    for a in args:
        m = _re.match(r'([\w.]+)\{', a)
        if m and _re.search(r'_g\d+$', m.group(1)):
            out += _ctor_args(a)[1]
        else:
            out.append(a)
    return out


def _view_fields(X):
    body = rt_def('v_' + X)[2]
    t = _RT.read_text()
    m = _re.search(r'^def v_' + X + r'\(o: .*?\) -> S\.Value:\n((?:  .*\n)+)', t, _re.M)
    lines = m.group(1).rstrip('\n').split('\n')
    expr = lines[-1].strip()
    if expr.startswith('case '):
        expr = expr.split(': ', 1)[1]
    xs = []
    for l in lines:
        mm = _re.search(r'case [\w.]+\{(.*)\}:', l)
        if mm and not _re.search(r'_g\d+\{', mm.group(0)) or (mm and '_g' in l):
            pass
    # the field binders x0.. in order, and the Items chain
    e = expr
    assert e.startswith('S.Sequence{') and e.endswith('}')
    e = e[len('S.Sequence{'):-1]
    views = []
    while e.startswith('S.Items{'):
        a, rest = split_args(e[len('S.Items{'):-1])
        views.append(a)
        e = rest
    return views


def _q(expr):
    return _re.sub(r'(?<![\w.])(v_\w+|pview|wview)\(', lambda m: ('RT.' + m.group(1) if m.group(1).startswith('v_') else m.group(0)) + '(', expr).replace('(RT.', 'RT.').replace('RT.' + 'v', 'RT.v') if False else _re.sub(r'(?<![\w.])(v_\w+)\(', r'RT.\1(', expr)


def _rel(l):
    """An import line of a proofs/obj module, relative to e2e/."""
    m = _re.match(r'import (\S+) as (\w+)$', l)
    path = m.group(1)
    if path.startswith('./'):
        path = '../proofs/obj/' + path[2:]
    elif path.startswith('../../'):
        path = '../' + path[6:]
    elif path.startswith('../'):
        path = '../proofs/' + path[3:]
    return f'import {path} as {m.group(2)}'


def ve_module(X, enc):
    text = (_OBJ / f'{enc}.bend').read_text()
    ps_o, oty, obody = _def_full(text, 'OBJE')
    ps_xe, _, xebody = _def_full(text, 'XE')
    ps_xey, _, xeybody = _def_full(text, 'XEY')
    P = _params(ps_o)
    assert _params(ps_xe) == P, X
    pnames = [n for n, _ in P]
    fields = _flat_fields(obody)
    views = _view_fields(X)
    assert len(fields) == len(views), (X, len(fields), len(views))
    xn, xargs = call(xebody)
    assert xn == 'XEY'
    xey_p = [n for n, _ in _params(ps_xey)]
    imports = {}
    holes = []   # dicts: obj (text in OBJE body), ty, view, vty, val, pf, xey (param name or text in XEY body)
    hyps = []    # (name, type)
    for f, v in zip(fields, views):
        m = _re.match(r'O\.Words\{FD\.array__thaw\(U32, (\w+)\), (\w+)\}$', f)
        if m:
            T, LEN = m.groups()
            sfx = T[1:]
            d = 'd' + sfx
            if v.startswith('S.BytesValue{WO.wview('):
                if LEN in pnames:   # a byte list: XEY's own parameter
                    val = f'VS.bt(U32.to_nat({LEN}), F.limbs(FD.array__slots(U32, {T})))'
                    k = xargs.index(val)
                    holes.append(dict(obj=f, ty='O.Words', view='WO.wview', vty='+List<U32>', val=val, pf=f'BL.wvb({T}, {LEN})', xey=xey_p[k], karg=k))
                else:
                    K = int(LEN) // 4
                    val = 'F.limbs([' + ', '.join(f'VB.slot({T}, {i}n)' for i in range(K)) + '])'
                    assert val in xeybody, (X, T)
                    hyps += [(f'pf{sfx}', f'{{FD.array__perfect(U32, {d}, {T}) == True{{}} : Bool}}'), (f'hr{sfx}', f'{{Nat.is_le({K}n, VB.pw({d})) == True{{}} : Bool}}')]
                    holes.append(dict(obj=f, ty='O.Words', view='WO.wview', vty='+List<U32>', val=val, pf=f'BL.wbv({T}, {d}, {K}n, {LEN}, pf{sfx}, hr{sfx}, {{==}})', xey=None))
            elif v.startswith('PV.pview('):
                C = int(LEN) // 32
                val = 'S.Sequence{' + ''.join('S.Items{S.BytesValue{F.limbs([' + ', '.join(f'VB.slot({T}, {8 * c + i}n)' for i in range(8)) + '])}, ' for c in range(C)) + 'S.EmptyItems{}' + '}' * C + '}'
                assert val in xeybody, (X, T, 'pv')
                holes.append(dict(obj=f, ty='O.Words', view='PV.pview', vty='S.Value', val=val, pf=f'BL.pvh({T}, {LEN})', xey=None))
            else:
                raise SystemExit(f've_module {X}: storage view {v}')
            continue
        m = _re.match(r'O\.BSome\{(\w+)\.OBJE\((.*)\), O\.BNone\{\}\}$', f)
        if m:
            al, args = m.groups()
            sub = _re.search(r'^import \./(\S+)\.bend as ' + al + '$', text, _re.M).group(1)
            vmod, Y = VE_MODS[sub]
            imports[vmod] = f'import ./{vmod}.bend as {al}V'
            val = f'{al}.XE({args})'
            k = xargs.index(val)
            sub_hyps = VE_HYPS[vmod]
            sub_p = [n for n, _ in _params(_def_full((_OBJ / f'{sub}.bend').read_text(), 'OBJE')[0])]
            amap = dict(zip(sub_p, split_args(args)))
            hs = []
            for hn, ht in sub_hyps:
                ht2 = ht
                for a, b in amap.items():
                    ht2 = _re.sub(r'(?<![\w.])' + a + r'(?![\w])', b, ht2)
                hyps.append((hn, ht2))
                hs.append(hn)
            holes.append(dict(obj=f, ty=f'O.Boxed<{_re.sub(r"RT\.", "", "")}>', view=f'RT.v_{Y}_bx', vty='S.Value', val=f'{val}', pf=f'{al}V.ve({args}{", " if hs else ""}{", ".join(hs)})',
                              xey=xey_p[k], karg=k, box=Y, al=al, args=args))
            continue
    hyps = list(dict.fromkeys(hyps))
    # hole types for boxed ones
    for h in holes:
        if 'box' in h:
            h['ty'] = f'O.Boxed<{wit(h["box"]).otype}>'
    zs = [f'z{k}' for k in range(len(holes))]
    ys = [f'Y{k}' for k in range(len(holes))]
    bh = obody
    for h, z in zip(holes, zs):
        assert bh.count(h['obj']) == 1, (X, h['obj'])
        bh = bh.replace(h['obj'], z)
    xh = xeybody
    extra = []
    for h, y in zip(holes, ys):
        if h['xey'] is None:
            xh = xh.replace(h['val'], y)
            extra.append(y)
    def xeyh_call(vals):
        a = list(xargs)
        ex = []
        for h, val in zip(holes, vals):
            if h['xey'] is None:
                ex.append(val)
            else:
                a[h['karg']] = val
        return f'XEYH({", ".join(a + ex)})'
    ly_ps = ', '.join(f'+{n}: {t}' for n, t in P)
    hole_ty = {y: h['vty'] for h, y in zip(holes, ys)}
    xeyh_params = ps_xey + ''.join(f', +{y}: {hole_ty[y]}' for y in extra)
    L = []
    L.append(f'def OBJEH({ly_ps}, {", ".join(f"{z}: {h["ty"]}" for z, h in zip(zs, holes))}) -> {oty}: {bh}\n')
    L.append(f'def XEYH({xeyh_params}) -> S.Value: {xh}\n')
    hy = ', '.join(f'{z}: {h["ty"]}, +{y}: {h["vty"]}, +e{k}: {{{h["view"]}({z}) == {y} : {h["vty"]}}}' for k, (z, y, h) in enumerate(zip(zs, ys, holes)))
    LHS = f'RT.v_{X}(OBJEH({", ".join(pnames)}, {", ".join(zs)}))'
    L.append(f'def vz({ly_ps}, {hy}) -> {{{LHS} == {xeyh_call(ys)} : S.Value}}:')
    for k in range(len(holes)):
        cur = [f'{holes[j]["view"]}({zs[j]})' if j < k else ('_' if j == k else ys[j]) for j in range(len(holes))]
        L.append(f'  %e{k} : {{{LHS} == {xeyh_call(cur)} : S.Value}}')
    L.append('  {==}\n')
    hp = ''.join(f', +{n}: {t}' for n, t in hyps)
    L.append(f'def ve({ly_ps}{hp}) -> {{RT.v_{X}(EN.OBJE({", ".join(pnames)})) == EN.XE({", ".join(pnames)}) : S.Value}}:')
    L.append(f'  vz({", ".join(pnames)}, {", ".join(f"{h['obj']}, {h['val']}, {h['pf']}" for h in holes)})')
    body = '\n'.join(L)
    # qualify the enc module's own defs in the copied texts
    own = set(_re.findall(r'^def (\w+)\(', text, _re.M))
    body = _re.sub(r'(?<![\w.])(' + '|'.join(sorted(own, key=len, reverse=True)) + r')\(', lambda m: m.group(0) if m.group(1) in ('OBJEH', 'XEYH', 'vz', 've') else f'EN.{m.group(0)}', body)
    enc_imps = [_rel(l) for l in text.splitlines() if l.startswith('import ') and l != 'import Base' and _re.search(r'(?<![\w.])' + l.split()[-1] + r'\.', body)]
    imps = ['import Base'] + enc_imps + [f'import ../proofs/obj/{enc}.bend as EN', 'import ../proofs/obj/root_types.bend as RT',
            'import ../proofs/obj/words_obj.bend as WO', 'import ../proofs/obj/pv_obj.bend as PV', 'import ../proofs/obj/vdepth.bend as VD',
            'import ../proofs/nat_order.bend as Order', 'import ./e2e_blist.bend as BL'] + list(imports.values())
    head = '\n'.join(dict.fromkeys(imps)) + f'''

# GENERATED by codegen/e2e_bridge.py (codegen/e2e_var_b.py). Do not edit.
# {X}: the root view of the encode laws' object ({enc}.OBJE) is their value XE (ve), over the laws'
# free words and storage; OBJEH / XEYH are the two with the storage parts as holes.

'''
    VE_HYPS[f'e2e_ve_{X}'] = hyps
    VE_MODS[enc] = (f'e2e_ve_{X}', X)
    return head + body + '\n\n' + _sb_text(X, text) + '\n'


VEB = {}   # X -> the bound of its encoder's size SFS(N) for a byte list of N <= 32 bytes


def _sb_text(X, text):
    """sb: to_nat(SFS(N)) <= its bound, for N <= 32."""
    _, _, sbody = _def_full(text, 'SFS')
    m = _re.match(r'U32\.add\((\d+), (N|(\w+)\.SFS\(N\))\)$', sbody)
    C, inner, al = int(m.group(1)), m.group(2), m.group(3)
    if al:
        sub = _re.search(r'^import \./(\S+)\.bend as ' + al + '$', text, _re.M).group(1)
        Y = VE_MODS[sub][1]
        IB, HI, IN = VEB[Y], f'{al}V.sb(N, hN)', f'{al}.SFS(N)'
    else:
        IB, HI, IN = 32, 'hN', 'N'
    B = C + IB
    k = max(1, (B - 1).bit_length())
    VEB[X] = B
    return f"""# the encoder's size for a byte list of N <= 32 bytes
def esfs(+N: U32) -> {{U32.add({C}, {IN}) == EN.SFS(N) : U32}}: {{==}}

def sb(+N: U32, +hN: {{Nat.is_le(U32.to_nat(N), 32n) == True{{}} : Bool}}) -> {{Nat.is_le(U32.to_nat(EN.SFS(N)), {B}n) == True{{}} : Bool}}:
  +hi = {HI}
  +hs = FD.nat__le_trans(Nat.add({C}n, U32.to_nat({IN})), Nat.add({C}n, {IB}n), O.pow2n({k}n), Order.add_left({C}n, U32.to_nat({IN}), {IB}n, hi), {{==}})
  %esfs(N) : {{Nat.is_le(U32.to_nat(_), {B}n) == True{{}} : Bool}}
  %Equal.sym(Nat, U32.to_nat(U32.add({C}, {IN})), Nat.add(U32.to_nat({C}), U32.to_nat({IN})), VD.s_add_nat({C}, {IN}, {k}n, {{==}}, hs)) : {{Nat.is_le(_, {B}n) == True{{}} : Bool}}
  Order.add_left({C}n, U32.to_nat({IN}), {IB}n, hi)
"""


VE_HYPS = {}
SUPPORT_OUT['e2e_ve_ExecutionPayloadHeader.bend'] = ve_module('ExecutionPayloadHeader', 'var_bytes_ExecutionPayloadHeader_enc')


# ---- (i) of the var_bytes_enc names: from rep and the storage premises to the encode laws ----
# Premise per storage field (every nesting level): its invariant at depth below 31 (BL.sdk1 for a byte
# vector, BL.sdk for a byte list, BL.sdpv for a Bytes32 vector); rep gives the fixed fields, the object
# equations and the length bounds. The storage facts become the laws' hypotheses (room from the chunk
# count, a byte list's zero tail from TZ.tz); the object is the laws' OBJE over the fixed fields' words.
class EncX:
    def __init__(self, X, enc):
        self.X, self.enc = X, enc
        self.text = (_OBJ / f'{enc}.bend').read_text()
        ps, _, body = _def_full(self.text, 'OBJE')
        self.P = _params(ps)
        self.pn = [n for n, _ in self.P]
        law = self.text.split('law encode_eval:\n')[1].split('\ndef encode_eval(')[0]
        self.hyps = [(m.group(1), m.group(2)) for m in _re.finditer(r'^  for \+(\w+): (\{.*\})$', law, _re.M)]
        self.rhs = _re.search(r'^  \{.*? == \((OBJE\(.*?\)), (B\.Buf\{.*\})\) : ', law, _re.M).group(2)
        self.lines, self.prem, self.fixed, self.eqs, self.hypv = [], [], [], [], {}
        self.n = 0

    def fresh(self, b):
        self.n += 1
        return f'{b}{self.n}'

    def level(self, Y, PO, repv, SC, obj_fields, amap):
        """Destructure rep_Y (repv) at object PO, schema SC; obj_fields: the OBJE fields of this level
        (in the top parameters' names). Returns the equation name {PO == this level's OBJE term}."""
        w = wit(Y)
        cons_f = _flat_fields(w.cons)
        assert len(cons_f) == len(obj_fields), (Y, len(cons_f), len(obj_fields))
        nb, nf = len(w.binders), len(w.fields)
        bn = [self.fresh('a') for _ in range(nb)]
        cur = repv
        for i in range(nb):
            self.lines.append(f'  (+{bn[i]}, {self.fresh("q")}) = {cur}')
            cur = f'q{self.n}'
        eo = self.fresh('eo')
        rs = [self.fresh('r') for _ in range(nf)]
        if nf == 0:
            self.lines.append(f'  +{eo} = {cur}')
        elif nf == 1:
            self.lines.append(f'  (+{eo}, +{rs[0]}) = {cur}')
        else:
            self.lines.append(f'  (+{eo}, {self.fresh("q")}) = {cur}')
            cur = f'q{self.n}'
            for j in range(nf - 1):
                if j == nf - 2:
                    self.lines.append(f'  (+{rs[j]}, +{rs[j + 1]}) = {cur}')
                else:
                    self.lines.append(f'  (+{rs[j]}, {self.fresh("q")}) = {cur}')
                    cur = f'q{self.n}'
        sub = lambda t: t.replace('(o)', f'({PO})').replace('(s)', f'({SC})') if PO != 'o' else t.replace('(s)', f'({SC})')
        # the level's equation: PO == CONS (binders named, pj over PO)
        cons = w.cons
        for (x, _), nm in zip(w.binders, bn):
            cons = _re.sub(r'(?<![\w.])' + x + r'(?![\w])', nm, cons)
        cons = _re.sub(r'(?<![\w.])(pj_\w+)\(o\)', lambda m: f'RT.{m.group(1)}({PO})', cons)
        OT = w.otype
        target_f = []   # this level's OBJE-side fields, in order
        steps = []      # (pj text, replacement term, equation name, field type)
        bi = 0
        fi = 0
        for cf, of in zip(cons_f, obj_fields):
            if bi < nb and _re.fullmatch(r'\w+', cf.strip()) and cf.strip() in [x for x, _ in w.binders]:
                # a fixed field: its witness destructured into the OBJE field's words
                idx = [x for x, _ in w.binders].index(cf.strip())
                self.fixed.append((bn[idx], w.binders[idx][1], of))
                target_f.append(of)
                continue
            pj, fn, sch, fty = w.fields[fi]
            r = rs[fi]
            fi += 1
            pjt = f'RT.{pj}'.replace('(o)', f'({PO})')
            scht = sch.replace('(s)', f'({SC})') if True else sch
            scht = _re.sub(r'(?<![\w.])s(?![\w])', SC, sch)
            k, info = field_kind(fn)
            if k == 'words':
                m = _re.match(r'O\.Words\{FD\.array__thaw\(U32, (\w+)\), (\w+)\}$', of)
                T, LEN = m.groups()
                sfx = T[1:]
                kind = {'WO.rep_bv': 'bv', 'LO.rep_bl': 'bl', 'PV.rep_pv': 'pv'}[fn]
                pv = self.fresh('hs')
                self.prem.append((pv, {'bv': 'BL.sdk1', 'bl': 'BL.sdk', 'pv': 'BL.sdpv'}[kind] + f'({pjt}, 31n)', kind, pjt, T, 'd' + sfx, LEN, sfx, r, scht))
                target_f.append(of)
                steps.append((pjt, f'O.Words{{FD.array__thaw(U32, {T}), {LEN}}}', f'ew_{sfx}', 'O.Words'))
            elif k == 'rbox':
                m = _re.match(r'O\.BSome\{(\w+)\.OBJE\((.*)\), O\.BNone\{\}\}$', of)
                al, args = m.groups()
                subenc = _re.search(r'^import \./(\S+)\.bend as ' + al + '$', self.text, _re.M).group(1)
                subtext = (_OBJ / f'{subenc}.bend').read_text()
                sps, _, sbody = _def_full(subtext, 'OBJE')
                spn = [n for n, _ in _params(sps)]
                sa = split_args(args)
                assert spn == sa, (Y, 'nested OBJE args are its parameter names')
                eb, ri = self.fresh('eb'), self.fresh('ri')
                self.lines.append(f'  (+{eb}, +{ri}) = {r}')
                inner = f'RT.pjb_{info}_bx({pjt})'
                isch = _re.sub(r'(?<![\w.])s(?![\w])', SC, sch)
                e_in = self.level(info, inner, ri, isch, _flat_fields(sbody), amap)
                tin = self.level_terms[inner]
                BT = f'O.Boxed<{wit(info).otype}>'
                ob = f'O.BSome{{{tin}, O.BNone{{}}}}'
                ename = self.fresh('ex')
                self.eqs.append(f'  +{ename} = Equal.trans({BT}, {pjt}, O.BSome{{{inner}, O.BNone{{}}}}, {ob}, {eb}, Equal.cong({wit(info).otype}, {BT}, z => O.BSome{{z, O.BNone{{}}}}, {inner}, {tin}, {e_in}))')
                self.subimports.append((al, subenc))
                target_f.append(of)
                steps.append((pjt, ob, ename, BT))
            else:
                raise SystemExit(f'EncX {Y}: field kind {k}')
        # PO == CONS -> PO == OBJE term: replace fixed binders by their patterns (they are matched in c2),
        # and the pj's step by step
        c0 = cons
        eq = eo
        for pjt, rep_t, en, fty in steps:
            c1 = c0.replace(pjt, rep_t, 1)
            hole = c0.replace(pjt, 'z', 1)
            en2 = self.fresh('c')
            self.eqs.append(f'  +{en2} = Equal.trans({OT}, {PO}, {c0}, {c1}, {eq}, Equal.cong({fty}, {OT}, z => {hole}, {pjt}, {rep_t}, {en}))')
            c0, eq = c1, en2
        self.level_terms = getattr(self, 'level_terms', {})
        self.level_terms[PO] = c0
        return eq


def venc_bytes(R, X):
    m = json.loads((_OBJ.parents[1] / 'proofs/gate/api_map.json').read_text())['map'][X]
    enc = m['encode_eval'][0]['file'][:-5]
    ex = EncX(X, enc)
    ex.subimports = []
    _, oty, obody = _def_full(ex.text, 'OBJE')
    eqtop = ex.level(X, 'o', 'rep', 'Spec.' + X + '()', _flat_fields(obody), {})
    OT = wit(X).otype
    ps = ', '.join(ex.pn)
    hn = [h for h, _ in ex.hyps]
    ENC = lambda o: f'{R}_e.{X}_encode({o})'
    G = lambda o: f'{{Some{{E.obytes(Pair.snd({OT}, B.Buf, {ENC(o)}))}} == API.serialize(Spec.{X}(), RT.v_{X}({o})) : Maybe<&2, +List<U32>>}}'
    OB = f'EN.OBJE({ps})'
    mo = _re.match(r'B\.Buf\{FD\.array__thaw\(U32, (OUTW\(.*?, (\d+)n, VC\.ZT\(\d+n\), 0n\))\), SFS\(N\)\}$', ex.rhs)
    OUT, DD = 'EN.' + mo.group(1), int(mo.group(2))
    BYT = f'VSP.bt(U32.to_nat(EN.SFS(N)), SF.limbs(FD.array__slots(U32, {OUT})))'
    vehyps = [h for h, _ in VE_HYPS[f'e2e_ve_{X}']]
    L = []
    L.append(f'''# (i) over the encode laws' free words and storage, under their hypotheses
def core({", ".join(f"+{n}: {t}" for n, t in ex.P)}, {", ".join(f"+{n}: {t}" for n, t in ex.hyps)}) -> {G(OB)}:
  %Equal.sym({OT} & B.Buf, {ENC(OB)}, ({OB}, B.Buf{{FD.array__thaw(U32, {OUT}), EN.SFS(N)}}), EN.encode_eval({ps}, {", ".join(hn)})) :
    {{Some{{E.obytes(Pair.snd({OT}, B.Buf, _))}} == API.serialize(Spec.{X}(), RT.v_{X}({OB})) : Maybe<&2, +List<U32>>}}
  %Equal.sym(+List<U32>, E.obytes(B.Buf{{FD.array__thaw(U32, {OUT}), EN.SFS(N)}}), {BYT},
      EM.ob({DD}n, {OUT}, EN.SFS(N), EN.pfO({ps}, {DD}n, VC.ZT({DD}n), 0n, FD.array__trep_perfect(U32, {DD}n, 0)), {{==}},
        FD.nat__le_trans(U32.to_nat(EN.SFS(N)), {VEB[X]}n, A.quad(FD.spec_common__pow2({DD}n)), VEV.sb(N, hN), {{==}}))) :
    {{Some{{_}} == API.serialize(Spec.{X}(), RT.v_{X}({OB})) : Maybe<&2, +List<U32>>}}
  %Equal.sym(S.Value, RT.v_{X}({OB}), EN.XE({ps}), VEV.ve({ps}{", " if vehyps else ""}{", ".join(vehyps)})) :
    {{Some{{{BYT}}} == API.serialize(Spec.{X}(), _) : Maybe<&2, +List<U32>>}}
  Equal.sym(Maybe<&2, +List<U32>>, API.serialize(Spec.{X}(), EN.XE({ps})), Some{{{BYT}}},
    Equal.trans(Maybe<&2, +List<U32>>, API.serialize(Spec.{X}(), EN.XE({ps})), Encoding.encoding_for_legal_type(Spec.{X}(), EN.XE({ps})), Some{{{BYT}}},
      E.serialize_legal(Spec.{X}(), EN.XE({ps}), VS.public_sound(Spec.{X}(), {{==}})), EN.encode_spec({ps}, {", ".join(hn)})))
''')
    # c2: the fixed witnesses matched into the words, then a1
    fx = ex.fixed
    nonw = [(n, t) for n, t in ex.P if not any(_re.search(r'(?<![\w.])' + n + r'(?![\w])', of) for _, _, of in fx)]
    wordset = set(ex.pn) - set(n for n, _ in nonw)
    objA = ex.level_terms['o']   # the object over the fixed fields' witnesses (rep's constructors)
    L.append(f'# the fixed fields\' words')
    c2ps = ', '.join([f'+{a}: {ty}' for a, ty, _ in fx] + [f'+{n}: {t}' for n, t in nonw] + [f'+{n}: {t}' for n, t in ex.hyps])
    L.append(f'def c2(-o: {OT}, {c2ps}, +eq: {{o == {objA} : {OT}}}) -> {G("o")}:')
    L.append(f'  match {" ".join(a for a, _, _ in fx)}:')
    L.append(f'    case {" ".join(_plus(of) for _, _, of in fx)}:')
    L.append(f'      %Equal.sym({OT}, o, {OB}, eq) : {G("_")}')
    L.append(f'      core({ps}, {", ".join(hn)})\n')
    L_top = _enc_top(ex, X, R, OT, G, fx, nonw, objA, eqtop)
    imps = ['import Base', 'import ../END_TO_END.bend as E2E', 'import ../src/model.bend as API', 'import ../src/buffer.bend as B',
            'import ../src/obj.bend as O', f'import ../types/{R}_encode_ssz_generated.bend as {R}_e', 'import ../types/schema.bend as S',
            'import ../types/primitive.bend as P', 'import ../spec/fulu_schemas.bend as Spec', 'import ../spec/primitives.bend as SP',
            'import ../proofs/type_validator_soundness.bend as VS', 'import ../proofs/compact/found.bend as FD', 'import ../proofs/compact/arith.bend as A',
            'import ../proofs/nat_order.bend as Order', 'import ../spec/codec.bend as Encoding', 'import ../proofs/obj/spec_fixed.bend as SF',
            'import ../proofs/obj/vspec.bend as VSP', 'import ../proofs/obj/vbuf.bend as VB', 'import ../proofs/obj/vcopy.bend as VC',
            'import ../proofs/obj/words_obj.bend as WO', 'import ../proofs/obj/words_spec.bend as WS', 'import ../proofs/obj/list_obj.bend as LO',
            'import ../proofs/obj/pv_obj.bend as PV', 'import ../proofs/obj/schema_shapes.bend as SH', 'import ../proofs/obj/root_types.bend as RT',
            f'import ../proofs/obj/{enc}.bend as EN'] + [f'import ../proofs/obj/{se}.bend as {al}' for al, se in dict.fromkeys(ex.subimports)] + [
            'import ./e2e_support.bend as E', 'import ./e2e_cap.bend as C', 'import ./e2e_emit.bend as EM', 'import ./e2e_blist.bend as BL',
            'import ../proofs/obj/vbytes.bend as VY', 'import ./e2e_tz.bend as TZ', f'import ./e2e_ve_{X}.bend as VEV']
    body = '\n'.join(L + L_top)
    dimps = [_rel(l) for l in ex.text.splitlines() if _re.match(r'import \.\./\.\./types/\S+ as (\w+_d)$', l) and (l.split()[-1] + '.') in body]
    rtt = _RT.read_text()
    dimps += [l.replace('import ../../', 'import ../') for l in rtt.splitlines()
              if _re.match(r'import \.\./\.\./types/\S+ as (\w+_d)$', l) and (l.split()[-1] + '.') in body]
    return '\n'.join(dict.fromkeys(imps + dimps)) + f'''

# GENERATED by codegen/e2e_bridge.py (codegen/e2e_var_b.py). Do not edit.
# {R} (variable size): the object API's encoder's bytes are END_TO_END's serialize of the object's view,
# for every object the root law represents (rep) whose storage fields are at depth below 31 (the hs
# premises: the encode laws take dw < 31, the root law's invariant dw < 32).

''' + body + '\n'


def _plus(t):
    return _re.sub(r'(?<=[{,] )(\w+)(?=[,}])|(?<=\{)(\w+)(?=[,}])', lambda m: '+' + (m.group(1) or m.group(2)), t)


def _qual_enc(t, ex):
    return _re.sub(r'(?<![\w.])(OBJE)\(', r'EN.\1(', t)


_LIMK = {32: 3}   # a byte list's limit L <= 4 * 2^k


def _enc_top(ex, X, R, OT, G, fx, nonw, objA, eqtop):
    prem = ex.prem
    bls = [p for p in prem if p[2] == 'bl']
    assert len(bls) <= 1, X
    ps = ', '.join(f'+{pv}: {pt}' for pv, pt, *_ in prem)
    L = [f'# (i): for every object the root law represents, its storage fields at depth below 31 (the hs premises)',
         f'def {R}_e2e_encode(-o: {OT}, +rep: RT.rep_{X}(o, Spec.{X}()), {ps}) -> {G("o")}:']
    # destructuring, parameter by parameter in declaration order (a destructured parameter's fields
    # must be taken apart before the next parameter's): rep, then the premises
    D = list(ex.lines) + [f'  (+wf{p_[7]}, +nb{p_[7]}) = {p_[8]}' for p_ in prem]
    lets = []
    for pv, pt, kind, pjt, T, d, LEN, sfx, r, SC in prem:
        if kind == 'bl':
            continue
        names = {'bv': [T, d, f'N{sfx}', f'q{sfx}', f'r{sfx}', f'eo{sfx}', f'pf{sfx}', f'hd{sfx}', f'eN{sfx}', f'h1{sfx}', f'h32{sfx}', f'hc{sfx}', f'bz{sfx}'],
                 'pv': [T, d, f'N{sfx}', f'q{sfx}', f'eo{sfx}', f'pf{sfx}', f'hd{sfx}', f'eN{sfx}', f'hc{sfx}']}[kind]
        cur = pv
        for i, nm in enumerate(names[:-2]):
            D.append(f'  (+{nm}, {pv}_{i}) = {cur}')
            cur = f'{pv}_{i}'
        D.append(f'  (+{names[-2]}, +{names[-1]}) = {cur}')
        N, q = f'N{sfx}', f'q{sfx}'
        WOW = lambda n: f'O.Words{{FD.array__thaw(U32, {T}), {n}}}'
        if kind == 'bv':
            lets.append(f'  +nn{sfx} = FD.logic__subst(O.Words, z => {{Nat.is_eq(U32.to_nat(WO.len(z)), SH.ByteVector_length({SC})) == True{{}} : Bool}}, {pjt}, {WOW(N)}, eo{sfx}, nb{sfx})')
            lets.append(f'  +eL{sfx} = FD.u32__injective({N}, {LEN}, Equal.trans(Nat, U32.to_nat({N}), {LEN}n, U32.to_nat({LEN}), FD.nat__eq_from_is_eq(U32.to_nat({N}), {LEN}n, nn{sfx}), {{==}}))')
            lets.append(f'  +hq{sfx} = FD.logic__subst(Nat, z => {{Nat.is_le(z, A.quad(O.e8(1n+{q}))) == True{{}} : Bool}}, Nat.add(r{sfx}, WS.e32({q})), U32.to_nat({N}),')
            lets.append(f'    Equal.sym(Nat, U32.to_nat({N}), Nat.add(r{sfx}, WS.e32({q})), Equal.trans(Nat, U32.to_nat({N}), Nat.add(WS.e32({q}), r{sfx}), Nat.add(r{sfx}, WS.e32({q})), eN{sfx}, FD.nat__add_comm(WS.e32({q}), r{sfx}))),')
            lets.append(f'    Order.add_right(r{sfx}, 32n, WS.e32({q}), h32{sfx}))')
            lets.append(f'  +hL{sfx} = FD.logic__subst(Nat, z => {{Nat.is_le(z, A.quad(O.e8(1n+{q}))) == True{{}} : Bool}}, U32.to_nat({N}), {LEN}n, FD.nat__eq_from_is_eq(U32.to_nat({N}), {LEN}n, nn{sfx}), hq{sfx})')
            K = int(LEN) // 4
            lets.append(f'  +hr{sfx} = FD.nat__le_trans({K}n, O.e8(1n+{q}), VB.pw({d}), C.nle({LEN}n, O.e8(1n+{q}), hL{sfx}), hc{sfx})')
        else:
            CN = int(LEN) // 32
            lets.append(f'  +nn{sfx} = FD.logic__subst(O.Words, z => {{Nat.is_eq(O.chunks_of(WO.len(z)), SH.Vector_length({SC})) == True{{}} : Bool}}, {pjt}, {WOW(N)}, eo{sfx}, nb{sfx})')
            lets.append(f'  +cc{sfx} = FD.logic__subst(Nat, z => {{Nat.div(Nat.add(z, 31n), 32n) == 1n+{q} : Nat}}, Nat.add(WS.e32({q}), 32n), U32.to_nat({N}), Equal.sym(Nat, U32.to_nat({N}), Nat.add(WS.e32({q}), 32n), eN{sfx}), WS.chunks_count({q}, 32n, {{==}}, {{==}}))')
            lets.append(f'  +ec{sfx} = Equal.trans(Nat, 1n+{q}, O.chunks_of({N}), {CN}n, Equal.sym(Nat, O.chunks_of({N}), 1n+{q}, cc{sfx}), FD.nat__eq_from_is_eq(O.chunks_of({N}), {CN}n, nn{sfx}))')
            lets.append(f'  +eq{sfx} = FD.nat__succ_inj({q}, {CN - 1}n, ec{sfx})')
            lets.append(f'  +eL{sfx} = FD.u32__injective({N}, {LEN}, FD.logic__subst(Nat, z => {{U32.to_nat({N}) == Nat.add(WS.e32(z), 32n) : Nat}}, {q}, {CN - 1}n, eq{sfx}, eN{sfx}))')
            lets.append(f'  +hr{sfx} = FD.logic__subst(Nat, z => {{Nat.is_le(O.e8(z), FD.spec_common__pow2({d})) == True{{}} : Bool}}, 1n+{q}, {CN}n, ec{sfx}, hc{sfx})')
        lets.append(f'  +ew_{sfx} = Equal.trans(O.Words, {pjt}, {WOW(N)}, {WOW(LEN)}, eo{sfx}, Equal.cong(U32, O.Words, z => {WOW("z")}, {N}, {LEN}, eL{sfx}))')
    hyp_names = [h for h, _ in ex.hyps]
    call = f'c2(o, {", ".join(a for a, _, _ in fx)}, {", ".join(n for n, _ in nonw)}, {", ".join(hyp_names)}, {eqtop})'
    if not bls:
        L += D + lets + ex.eqs + [f'  {call}']
        return L
    pv, pt, kind, pjt, T, d, LEN, sfx, r, SC = bls[0]
    LIMK = 3
    WOW = f'O.Words{{FD.array__thaw(U32, {T}), {LEN}}}'
    common = [f'    +hN = FD.logic__subst(O.Words, z => {{Nat.is_le(U32.to_nat(WO.len(z)), SH.ByteList_limit({SC})) == True{{}} : Bool}}, {pjt}, {WOW}, eo{sfx}, nb{sfx})',
              f'    +hN3 = FD.nat__le_trans(U32.to_nat({LEN}), 32n, A.quad(FD.spec_common__pow2({LIMK}n)), hN, {{==}})',
              f'    +enw = Equal.trans(Nat, Nat.add(VC.NW({LEN}), 0n), VC.NW({LEN}), C.nwn(U32.to_nat({LEN})), FD.nat__add_zero(VC.NW({LEN})), C.nw({LEN}, {LIMK}n, {{==}}, hN3))',
              f'    +ew_{sfx} = eo{sfx}']
    others = [(pv2, pt2) for pv2, pt2, k2, *_ in prem if k2 != 'bl']
    oargs = ''.join(f', {x}' for x, _ in others)
    ops = ''.join(f', +{x}: {t}' for x, t in others)
    L.append(f'  match {pv}:')
    L.append(f'    case Inl{{s}}: g0(o, rep{oargs}, s)')
    L.append(f'    case Inr{{s}}: g1(o, rep{oargs}, s)')
    L0 = L
    L = [f'def g0(-o: {OT}, +rep: RT.rep_{X}(o, Spec.{X}()){ops}, +s: BL.sdk0({pjt}, 31n)) -> {G("o")}:']
    L += ['    ' + l for l in D]
    for i, nm in enumerate([T, d, LEN, f'eo{sfx}', f'pf{sfx}']):
        L.append(f'      (+{nm}, s{i}) = {"s" if i == 0 else "s" + str(i - 1)}')
    L.append(f'      (+hd{sfx}, +en0) = s4')
    b0 = [f'    +hr{sfx} = FD.logic__subst(Nat, z => {{Nat.is_le(z, VB.pw({d})) == True{{}} : Bool}}, 0n, Nat.add(VC.NW({LEN}), 0n),',
          f'      Equal.sym(Nat, Nat.add(VC.NW({LEN}), 0n), 0n, Equal.trans(Nat, Nat.add(VC.NW({LEN}), 0n), C.nwn(U32.to_nat({LEN})), 0n, enw, Equal.cong(Nat, Nat, z => C.nwn(z), U32.to_nat({LEN}), 0n, en0))),',
          f'      Order.zero_le(VB.pw({d})))',
          f'    +htz = FD.logic__subst(U32, z => {{O.tail_zero(U32.and(z, 3), VB.slot({T}, VY.QL(z))) == True{{}} : Bool}}, 0, {LEN}, Equal.sym(U32, {LEN}, 0, FD.u32__injective({LEN}, 0, en0)), {{==}})']
    L += ['    ' + l for l in lets] + ['  ' + l for l in common + b0] + ['    ' + l for l in ex.eqs] + [f'      {call}']
    L1 = L
    L = [f'def g1(-o: {OT}, +rep: RT.rep_{X}(o, Spec.{X}()){ops}, +s: BL.sdk1({pjt}, 31n)) -> {G("o")}:']
    L += ['    ' + l for l in D]
    nm = [T, d, LEN, f'q{sfx}', f'r{sfx}', f'eo{sfx}', f'pf{sfx}', f'hd{sfx}', f'eN{sfx}', f'h1{sfx}', f'h32{sfx}', f'hc{sfx}', f'bz{sfx}']
    for i, n_ in enumerate(nm[:-2]):
        L.append(f'      (+{n_}, s{i}) = {"s" if i == 0 else "s" + str(i - 1)}')
    L.append(f'      (+{nm[-2]}, +{nm[-1]}) = s{len(nm) - 3}')
    q = f'q{sfx}'
    b1 = [f'    +hq = FD.logic__subst(Nat, z => {{Nat.is_le(z, A.quad(O.e8(1n+{q}))) == True{{}} : Bool}}, Nat.add(r{sfx}, WS.e32({q})), U32.to_nat({LEN}),',
          f'      Equal.sym(Nat, U32.to_nat({LEN}), Nat.add(r{sfx}, WS.e32({q})), Equal.trans(Nat, U32.to_nat({LEN}), Nat.add(WS.e32({q}), r{sfx}), Nat.add(r{sfx}, WS.e32({q})), eN{sfx}, FD.nat__add_comm(WS.e32({q}), r{sfx}))),',
          f'      Order.add_right(r{sfx}, 32n, WS.e32({q}), h32{sfx}))',
          f'    +hr{sfx} = FD.logic__subst(Nat, z => {{Nat.is_le(z, VB.pw({d})) == True{{}} : Bool}}, C.nwn(U32.to_nat({LEN})), Nat.add(VC.NW({LEN}), 0n), Equal.sym(Nat, Nat.add(VC.NW({LEN}), 0n), C.nwn(U32.to_nat({LEN})), enw),',
          f'      FD.nat__le_trans(C.nwn(U32.to_nat({LEN})), O.e8(1n+{q}), VB.pw({d}), C.nle(U32.to_nat({LEN}), O.e8(1n+{q}), hq), hc{sfx}))',
          f'    +htz = TZ.tz({T}, {LEN}, {q}, r{sfx}, eN{sfx}, h1{sfx}, h32{sfx}, bz{sfx})']
    L += ['    ' + l for l in lets] + ['  ' + l for l in common + b1] + ['    ' + l for l in ex.eqs] + [f'      {call}']
    return L1 + [''] + L + [''] + L0


VENC_SHAPES['ExecutionPayloadHeader'] = venc_bytes
VENC_PREMISE['ExecutionPayloadHeader'] = 'rep: RT.rep_ExecutionPayloadHeader(o, Spec.ExecutionPayloadHeader()) and the hs premises: each storage field\'s invariant at depth below 31 (BL.sdk1 / BL.sdk; the encode laws take dw < 31, the root law dw < 32; dropped when the encode laws take dw < 32)'


SUPPORT_OUT['e2e_vw_LightClientHeader.bend'] = vw_module('LightClientHeader', 'var_bytes_LightClientHeader_win', [
    {'obj': 'YW.OBJw(t, Nat.add(61n, i), LL(len))', 'ty': 'FuluExecutionPayloadHeader_d.ExecutionPayloadHeader', 'arg': 'YW.OBJw(t, Nat.add(61n, i), W.LL(len))',
     'view': 'RT.v_ExecutionPayloadHeader', 'vty': 'S.Value', 'val': 'YW.VALw(t, Nat.add(61n, i), W.LL(len))', 'pf': 'YWV.vw(t, Nat.add(61n, i), W.LL(len))'}],
    lambda ys: ys[0], ['import ../proofs/obj/var_bytes_ExecutionPayloadHeader_win.bend as YW', 'import ./e2e_vw_ExecutionPayloadHeader.bend as YWV'])
VDEC_VIEWS['LightClientHeader'] = vdec_win('LightClientHeader', 29, 'e2e_vw_LightClientHeader')

VROOT_SHAPES['LightClientHeader'] = vroot_container
SUPPORT_OUT['e2e_ve_LightClientHeader.bend'] = ve_module('LightClientHeader', 'var_bytes_LightClientHeader_enc')
VENC_SHAPES['LightClientHeader'] = venc_bytes
VENC_PREMISE['LightClientHeader'] = 'rep: RT.rep_LightClientHeader(o, Spec.LightClientHeader()) and the hs premises: each storage field\'s invariant at depth below 31 (BL.sdpv / BL.sdk1 / BL.sdk; the encode laws take dw < 31, the root law dw < 32; dropped when the encode laws take dw < 32)'
