#!/usr/bin/env python3
"""Non-vacuity witnesses for the bridges that take premises: e2e/<Name>_e2e_witness_generated.bend.

For every name whose encode (i) or root (iv) bridge takes premises besides the object (premised(): read
from e2e/manifest.json), checked defs apply those bridges (<Name>_e2e_encode, <Name>_e2e_root) to the
object API's default object (the def <..>_default() returning the bridge's object type; DV(), the default
with valid elements, where a vector holds empty boxes; the literal 0 for a bare U32), with every premise
of the bridge (rep and each storage, size and budget premise) proved of that object: <Name>_e2e_witness
and <Name>_e2e_witness_root. So each premise set is jointly satisfiable and each bridge's conclusion holds
of at least one object: no bridge is vacuous. The light-client branch types' bridges quantify over a
perfect word tree: their witness is the zero tree of the least depth with room. e2e/WITNESS.txt lists
every premised name, witnessed or pending with the reason.

The premise proofs are synthesized from the premise predicates' own definitions (read from the
modules the bridge imports): a predicate is a nest of DK.Ex / DK.P2 / DK.Or2 over equalities; the
existential witnesses come from the default object (a field's default value; a zero-filled word
array words_new(n) is thaw(trep(d, 0)) at its depth d, by found.array__new; an empty list is one
leaf of depth 0), and every equality is closed by computation ({==}), except the word-array
equation (the per-size lemma WZ<n>) and a word tree's perfectness (found.array__trep_perfect).

A second witness per name applies the same bridge to a NON-empty object NE(): the default with
every list reachable through containers and boxes (not inside list elements) holding one element:
a list of Data or boxed elements is Seq{ALeaf{e}, 1} with e the element's default (boxed: its
_bx_default()), a byte or packed list is O.words_new(k) for one k-byte element. Its storage
witnesses are the one-leaf tree (TLeaf{e}, or the mirror tfz_<list>(ALeaf{e})) at depth 0 with
N = 1, and the element-wise premises (predicates defined by `match k`) are unfolded once and
proved of the element. So no premise holds only of empty lists.

    python3 codegen/e2e_witness.py            # write
    python3 codegen/e2e_witness.py --check    # nonzero exit if any output is stale
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
E2E = ROOT / 'e2e'

# the names whose encode bridge carries premises beyond rep
NAMES = ['FuluExecutionPayload', 'FuluExecutionPayloadHeader', 'FuluExecutionRequests', 'FuluDataColumnSidecar',
         'FuluLightClientHeader', 'FuluLightClientBootstrap', 'FuluLightClientOptimisticUpdate',
         'FuluLightClientFinalityUpdate', 'FuluLightClientUpdate',
         'FuluBeaconBlockBody', 'FuluBeaconBlock', 'FuluSignedBeaconBlock', 'FuluBeaconState']

R = '{==}'

SUPPORT = '''import Base
import ../src/obj.bend as O
import ../proofs/compact/found.bend as FD
import ../proofs/obj/words_spec.bend as WS
import ../proofs/obj/words_obj_light.bend as WO
import ../proofs/obj/packed_obj_light.bend as PK
import ../proofs/obj/vbuf.bend as VB

# GENERATED by codegen/e2e_witness.py. Do not edit.
# Arithmetic for the non-vacuity witnesses (e2e/<Name>_e2e_witness_generated.bend) of large zero-filled word
# arrays: n = 2^b bytes of 2^c chunks (b = c + 5), stated with c symbolic so that no unary 2^b is ever compared.

def sp(+x: Nat, +h: {Nat.is_le(1n, x) == True{} : Bool}) -> {1n+FD.nat__pred(x) == x : Nat}:
  match x:
    case 0n: Empty.absurd({1n+FD.nat__pred(0n) == 0n : Nat}, FD.logic__false_true(h))
    case 1n+p: {==}

# the chunk count minus one, as the witness q of a vector's length equation
def QP(+c: Nat) -> Nat: FD.nat__pred(FD.spec_common__pow2(c))

def q1(+c: Nat) -> {1n+QP(c) == FD.spec_common__pow2(c) : Nat}: sp(FD.spec_common__pow2(c), FD.nat__pow2_pos(c))

# 32 (q + 1) = 2^b
def eN(+c: Nat, +b: Nat, +eb: {Nat.add(5n, c) == b : Nat}, +N: U32, +hN: {U32.to_nat(N) == FD.spec_common__pow2(b) : Nat})
    -> {U32.to_nat(N) == Nat.add(WS.e32(QP(c)), 32n) : Nat}:
  %FD.nat__add_comm(32n, WS.e32(QP(c))) : {U32.to_nat(N) == _ : Nat}
  %Equal.sym(Nat, 1n+QP(c), FD.spec_common__pow2(c), q1(c)) : {U32.to_nat(N) == WS.e32(_) : Nat}
  %Equal.sym(Nat, Nat.add(5n, c), b, eb) : {U32.to_nat(N) == FD.spec_common__pow2(_) : Nat}
  hN

# 8 (q + 1) words fit in 2^d, d >= c + 3
def eQ(+c: Nat, +d: Nat, +hd: {Nat.is_le(Nat.add(3n, c), d) == True{} : Bool}) -> {Nat.is_le(O.e8(1n+QP(c)), FD.spec_common__pow2(d)) == True{} : Bool}:
  %Equal.sym(Nat, 1n+QP(c), FD.spec_common__pow2(c), q1(c)) : {Nat.is_le(O.e8(_), FD.spec_common__pow2(d)) == True{} : Bool}
  FD.nat__pow2_mono(Nat.add(3n, c), d, hd)

# shifting 2^(3 + a) right by 3 gives 2^a
def shr3(+a: Nat, +h: {Nat.is_lt(3n+a, 32n) == True{} : Bool}) -> {U32.shrn(FD.u32__pow2u(3n+a), 3n) == FD.u32__pow2u(a) : U32}:
  %Equal.sym(U32, U32.shr(FD.u32__pow2u(3n+a)), FD.u32__pow2u(2n+a), FD.u32__shr_pow2u(2n+a, h)) : {U32.shr(U32.shr(_)) == FD.u32__pow2u(a) : U32}
  %Equal.sym(U32, U32.shr(FD.u32__pow2u(2n+a)), FD.u32__pow2u(1n+a), FD.u32__shr_pow2u(1n+a, FD.nat__lt_trans(2n+a, 3n+a, 32n, FD.nat__lt_succ(2n+a), h))) : {U32.shr(_) == FD.u32__pow2u(a) : U32}
  FD.u32__shr_pow2u(a, FD.nat__lt_trans(1n+a, 3n+a, 32n, FD.nat__lt_trans(1n+a, 2n+a, 3n+a, FD.nat__lt_succ(1n+a), FD.nat__lt_succ(2n+a)), h))

# a zero array of 2^b = 8 * 2^a bytes holds a whole number of 8-byte elements (packed_obj_light.rep_v8's count)
def len8(-w: O.Words, +a: Nat, +b: Nat, +d: Nat, +eb: {3n+a == b : Nat}, +hb: {Nat.is_lt(b, 32n) == True{} : Bool},
    +ew: {w == O.Words{FD.array__thaw(U32, FD.array__trep(U32, d, 0)), FD.u32__pow2u(b)} : O.Words})
    -> {U32.to_nat(WO.len(w)) == PK.e8(PK.cnt8(w)) : Nat}:
  %Equal.sym(O.Words, w, O.Words{FD.array__thaw(U32, FD.array__trep(U32, d, 0)), FD.u32__pow2u(b)}, ew) : {U32.to_nat(WO.len(_)) == PK.e8(PK.cnt8(w)) : Nat}
  %Equal.sym(O.Words, w, O.Words{FD.array__thaw(U32, FD.array__trep(U32, d, 0)), FD.u32__pow2u(b)}, ew) : {U32.to_nat(FD.u32__pow2u(b)) == PK.e8(PK.cnt8(_)) : Nat}
  %Equal.sym(Nat, b, 3n+a, Equal.sym(Nat, 3n+a, b, eb)) : {U32.to_nat(FD.u32__pow2u(_)) == PK.e8(U32.to_nat(U32.shrn(FD.u32__pow2u(_), 3n))) : Nat}
  %Equal.sym(U32, U32.shrn(FD.u32__pow2u(3n+a), 3n), FD.u32__pow2u(a), shr3(a, FD.logic__subst(Nat, z => {Nat.is_lt(z, 32n) == True{} : Bool}, b, 3n+a, Equal.sym(Nat, 3n+a, b, eb), hb))) : {U32.to_nat(FD.u32__pow2u(3n+a)) == PK.e8(U32.to_nat(_)) : Nat}
  %Equal.sym(Nat, U32.to_nat(FD.u32__pow2u(3n+a)), FD.spec_common__pow2(3n+a), FD.u32__pow2u_value(3n+a, FD.logic__subst(Nat, z => {Nat.is_lt(z, 32n) == True{} : Bool}, b, 3n+a, Equal.sym(Nat, 3n+a, b, eb), hb))) : {_ == PK.e8(U32.to_nat(FD.u32__pow2u(a))) : Nat}
  %Equal.sym(Nat, U32.to_nat(FD.u32__pow2u(a)), FD.spec_common__pow2(a), FD.u32__pow2u_value(a, FD.nat__lt_trans(a, 3n+a, 32n, FD.nat__lt_trans(a, 2n+a, 3n+a, FD.nat__lt_trans(a, 1n+a, 2n+a, FD.nat__lt_succ(a), FD.nat__lt_succ(1n+a)), FD.nat__lt_succ(2n+a)), FD.logic__subst(Nat, z => {Nat.is_lt(z, 32n) == True{} : Bool}, b, 3n+a, Equal.sym(Nat, 3n+a, b, eb), hb)))) : {FD.spec_common__pow2(3n+a) == PK.e8(_) : Nat}
  {==}

# shifting 2^(5 + a) right by 5 gives 2^a
def shr5(+a: Nat, +h: {Nat.is_lt(5n+a, 32n) == True{} : Bool}) -> {U32.shrn(FD.u32__pow2u(5n+a), 5n) == FD.u32__pow2u(a) : U32}:
  %Equal.sym(U32, U32.shr(FD.u32__pow2u(5n+a)), FD.u32__pow2u(4n+a), FD.u32__shr_pow2u(4n+a, h)) : {U32.shr(U32.shr(U32.shr(U32.shr(_)))) == FD.u32__pow2u(a) : U32}
  %Equal.sym(U32, U32.shr(FD.u32__pow2u(4n+a)), FD.u32__pow2u(3n+a), FD.u32__shr_pow2u(3n+a, FD.nat__lt_trans(4n+a, 5n+a, 32n, FD.nat__lt_succ(4n+a), h))) : {U32.shr(U32.shr(U32.shr(_))) == FD.u32__pow2u(a) : U32}
  shr3(a, FD.nat__lt_trans(3n+a, 5n+a, 32n, FD.nat__lt_trans(3n+a, 4n+a, 5n+a, FD.nat__lt_succ(3n+a), FD.nat__lt_succ(4n+a)), h))

# a zero array of 2^b = 32 * 2^a bytes holds a whole number of 32-byte elements (packed_obj_light.rep_v32's count)
def len32(-w: O.Words, +a: Nat, +b: Nat, +d: Nat, +eb: {5n+a == b : Nat}, +hb: {Nat.is_lt(b, 32n) == True{} : Bool},
    +ew: {w == O.Words{FD.array__thaw(U32, FD.array__trep(U32, d, 0)), FD.u32__pow2u(b)} : O.Words})
    -> {U32.to_nat(WO.len(w)) == PK.e32(PK.cnt32(w)) : Nat}:
  %Equal.sym(O.Words, w, O.Words{FD.array__thaw(U32, FD.array__trep(U32, d, 0)), FD.u32__pow2u(b)}, ew) : {U32.to_nat(WO.len(_)) == PK.e32(PK.cnt32(w)) : Nat}
  %Equal.sym(O.Words, w, O.Words{FD.array__thaw(U32, FD.array__trep(U32, d, 0)), FD.u32__pow2u(b)}, ew) : {U32.to_nat(FD.u32__pow2u(b)) == PK.e32(PK.cnt32(_)) : Nat}
  %Equal.sym(Nat, b, 5n+a, Equal.sym(Nat, 5n+a, b, eb)) : {U32.to_nat(FD.u32__pow2u(_)) == PK.e32(U32.to_nat(U32.shrn(FD.u32__pow2u(_), 5n))) : Nat}
  %Equal.sym(U32, U32.shrn(FD.u32__pow2u(5n+a), 5n), FD.u32__pow2u(a), shr5(a, FD.logic__subst(Nat, z => {Nat.is_lt(z, 32n) == True{} : Bool}, b, 5n+a, Equal.sym(Nat, 5n+a, b, eb), hb))) : {U32.to_nat(FD.u32__pow2u(5n+a)) == PK.e32(U32.to_nat(_)) : Nat}
  %Equal.sym(Nat, U32.to_nat(FD.u32__pow2u(5n+a)), FD.spec_common__pow2(5n+a), FD.u32__pow2u_value(5n+a, FD.logic__subst(Nat, z => {Nat.is_lt(z, 32n) == True{} : Bool}, b, 5n+a, Equal.sym(Nat, 5n+a, b, eb), hb))) : {_ == PK.e32(U32.to_nat(FD.u32__pow2u(a))) : Nat}
  %Equal.sym(Nat, U32.to_nat(FD.u32__pow2u(a)), FD.spec_common__pow2(a), FD.u32__pow2u_value(a, FD.nat__lt_trans(a, 5n+a, 32n, FD.nat__lt_trans(a, 4n+a, 5n+a, FD.nat__lt_trans(a, 3n+a, 4n+a, FD.nat__lt_trans(a, 2n+a, 3n+a, FD.nat__lt_trans(a, 1n+a, 2n+a, FD.nat__lt_succ(a), FD.nat__lt_succ(1n+a)), FD.nat__lt_succ(2n+a)), FD.nat__lt_succ(3n+a)), FD.nat__lt_succ(4n+a)), FD.logic__subst(Nat, z => {Nat.is_lt(z, 32n) == True{} : Bool}, b, 5n+a, Equal.sym(Nat, 5n+a, b, eb), hb)))) : {FD.spec_common__pow2(5n+a) == PK.e32(_) : Nat}
  {==}

# the same for any word array of 2^b bytes (a decoder's tree-form object)
def len32g(-arr: Array<U32>, +a: Nat, +b: Nat, +eb: {5n+a == b : Nat}, +hb: {Nat.is_lt(b, 32n) == True{} : Bool})
    -> {U32.to_nat(WO.len(O.Words{arr, FD.u32__pow2u(b)})) == PK.e32(PK.cnt32(O.Words{arr, FD.u32__pow2u(b)})) : Nat}:
  %Equal.sym(Nat, b, 5n+a, Equal.sym(Nat, 5n+a, b, eb)) : {U32.to_nat(FD.u32__pow2u(_)) == PK.e32(U32.to_nat(U32.shrn(FD.u32__pow2u(_), 5n))) : Nat}
  %Equal.sym(U32, U32.shrn(FD.u32__pow2u(5n+a), 5n), FD.u32__pow2u(a), shr5(a, FD.logic__subst(Nat, z => {Nat.is_lt(z, 32n) == True{} : Bool}, b, 5n+a, Equal.sym(Nat, 5n+a, b, eb), hb))) : {U32.to_nat(FD.u32__pow2u(5n+a)) == PK.e32(U32.to_nat(_)) : Nat}
  %Equal.sym(Nat, U32.to_nat(FD.u32__pow2u(5n+a)), FD.spec_common__pow2(5n+a), FD.u32__pow2u_value(5n+a, FD.logic__subst(Nat, z => {Nat.is_lt(z, 32n) == True{} : Bool}, b, 5n+a, Equal.sym(Nat, 5n+a, b, eb), hb))) : {_ == PK.e32(U32.to_nat(FD.u32__pow2u(a))) : Nat}
  %Equal.sym(Nat, U32.to_nat(FD.u32__pow2u(a)), FD.spec_common__pow2(a), FD.u32__pow2u_value(a, FD.nat__lt_trans(a, 5n+a, 32n, FD.nat__lt_trans(a, 4n+a, 5n+a, FD.nat__lt_trans(a, 3n+a, 4n+a, FD.nat__lt_trans(a, 2n+a, 3n+a, FD.nat__lt_trans(a, 1n+a, 2n+a, FD.nat__lt_succ(a), FD.nat__lt_succ(1n+a)), FD.nat__lt_succ(2n+a)), FD.nat__lt_succ(3n+a)), FD.nat__lt_succ(4n+a)), FD.logic__subst(Nat, z => {Nat.is_lt(z, 32n) == True{} : Bool}, b, 5n+a, Equal.sym(Nat, 5n+a, b, eb), hb)))) : {FD.spec_common__pow2(5n+a) == PK.e32(_) : Nat}
  {==}
# e32 written out: the checker compares Nat.double chains without expanding the sums (the defs e32 / e8 would be walked)
def e32d(-x: Nat) -> {WS.e32(x) == Nat.double(Nat.double(Nat.double(Nat.double(Nat.double(x))))) : Nat}: {==}
def pe32d(-x: Nat) -> {PK.e32(x) == Nat.double(Nat.double(Nat.double(Nat.double(Nat.double(x))))) : Nat}: {==}
def pe16d(-x: Nat) -> {PK.e16(x) == Nat.double(Nat.double(Nat.double(Nat.double(x)))) : Nat}: {==}
def pe8d(-x: Nat) -> {PK.e8(x) == Nat.double(Nat.double(Nat.double(x))) : Nat}: {==}

# the length fact of an n-byte word array, with the sum proved by the caller in a form the checker compares in halves
def lbig(-o: O.Words, +n: U32, +hl: {WO.len(o) == n : U32}, +h: {U32.to_nat(n) == Nat.double(Nat.double(Nat.double(Nat.double(Nat.double(PK.cnt32(o)))))) : Nat})
    -> {U32.to_nat(WO.len(o)) == PK.e32(PK.cnt32(o)) : Nat}:
  %Equal.sym(Nat, PK.e32(PK.cnt32(o)), Nat.double(Nat.double(Nat.double(Nat.double(Nat.double(PK.cnt32(o)))))), pe32d(PK.cnt32(o))) : {U32.to_nat(WO.len(o)) == _ : Nat}
  %Equal.sym(U32, WO.len(o), n, hl) : {U32.to_nat(_) == Nat.double(Nat.double(Nat.double(Nat.double(Nat.double(PK.cnt32(o)))))) : Nat}
  h
def lbig16(-o: O.Words, +n: U32, +hl: {WO.len(o) == n : U32}, +h: {U32.to_nat(n) == Nat.double(Nat.double(Nat.double(Nat.double(PK.cnt16(o))))) : Nat})
    -> {U32.to_nat(WO.len(o)) == PK.e16(PK.cnt16(o)) : Nat}:
  %Equal.sym(Nat, PK.e16(PK.cnt16(o)), Nat.double(Nat.double(Nat.double(Nat.double(PK.cnt16(o))))), pe16d(PK.cnt16(o))) : {U32.to_nat(WO.len(o)) == _ : Nat}
  %Equal.sym(U32, WO.len(o), n, hl) : {U32.to_nat(_) == Nat.double(Nat.double(Nat.double(Nat.double(PK.cnt16(o))))) : Nat}
  h
def lbig8(-o: O.Words, +n: U32, +hl: {WO.len(o) == n : U32}, +h: {U32.to_nat(n) == Nat.double(Nat.double(Nat.double(PK.cnt8(o)))) : Nat})
    -> {U32.to_nat(WO.len(o)) == PK.e8(PK.cnt8(o)) : Nat}:
  %Equal.sym(Nat, PK.e8(PK.cnt8(o)), Nat.double(Nat.double(Nat.double(PK.cnt8(o)))), pe8d(PK.cnt8(o))) : {U32.to_nat(WO.len(o)) == _ : Nat}
  %Equal.sym(U32, WO.len(o), n, hl) : {U32.to_nat(_) == Nat.double(Nat.double(Nat.double(PK.cnt8(o)))) : Nat}
  h


# ---- a total size with a 2^29 + 1 term (a progressive bit list's bound): below 2^31, never walked in unary ----
# c + a < c + b from a < b, by c's structure
def lt_addl(+c: Nat, +a: Nat, +b: Nat, +h: {Nat.is_lt(a, b) == True{} : Bool}) -> {Nat.is_lt(Nat.add(c, a), Nat.add(c, b)) == True{} : Bool}:
  match c:
    case 0n: h
    case 1n+p: lt_addl(p, a, b, h)

# (u + q) + x == (u + x) + q
def swapq(+u: Nat, +q: Nat, +x: Nat) -> {Nat.add(Nat.add(u, q), x) == Nat.add(Nat.add(u, x), q) : Nat}:
  Equal.trans(Nat, Nat.add(Nat.add(u, q), x), Nat.add(u, Nat.add(q, x)), Nat.add(Nat.add(u, x), q), FD.nat__add_assoc(u, q, x),
    Equal.trans(Nat, Nat.add(u, Nat.add(q, x)), Nat.add(u, Nat.add(x, q)), Nat.add(Nat.add(u, x), q),
      Equal.cong(Nat, Nat, z => Nat.add(u, z), Nat.add(q, x), Nat.add(x, q), FD.nat__add_comm(q, x)),
      Equal.sym(Nat, Nat.add(Nat.add(u, x), q), Nat.add(u, Nat.add(x, q)), FD.nat__add_assoc(u, x, q))))

# R + (P + 1) < 4 P when R + 1 < P (P symbolic)
def totP(+R: Nat, +P: Nat, +h: {Nat.is_lt(Nat.add(R, 1n), P) == True{} : Bool})
    -> {Nat.is_lt(Nat.add(R, Nat.add(P, 1n)), Nat.double(Nat.double(P))) == True{} : Bool}:
  +t = Nat.add(R, Nat.add(P, 1n))
  +e1 = Equal.trans(Nat, t, Nat.add(Nat.add(R, P), 1n), Nat.add(P, Nat.add(R, 1n)),
    Equal.sym(Nat, Nat.add(Nat.add(R, P), 1n), t, FD.nat__add_assoc(R, P, 1n)),
    Equal.trans(Nat, Nat.add(Nat.add(R, P), 1n), Nat.add(Nat.add(P, R), 1n), Nat.add(P, Nat.add(R, 1n)),
      Equal.cong(Nat, Nat, z => Nat.add(z, 1n), Nat.add(R, P), Nat.add(P, R), FD.nat__add_comm(R, P)),
      FD.nat__add_assoc(P, R, 1n)))
  +l1 = lt_addl(P, Nat.add(R, 1n), P, h)
  +l2 = FD.logic__subst(Nat, z => {Nat.is_lt(z, Nat.add(P, P)) == True{} : Bool}, Nat.add(P, Nat.add(R, 1n)), t, Equal.sym(Nat, t, Nat.add(P, Nat.add(R, 1n)), e1), l1)
  +l3 = FD.logic__subst(Nat, z => {Nat.is_lt(t, z) == True{} : Bool}, Nat.add(P, P), Nat.double(P), Equal.sym(Nat, Nat.double(P), Nat.add(P, P), FD.lru_nat_algebra__double_self(P)), l2)
  FD.nat__lt_le_trans(t, Nat.double(P), Nat.double(Nat.double(P)), l3, FD.nat__double_self_le(Nat.double(P)))

# the same at P = 2^29, the bound 2^31 written as the spec's power
def tot29(+R: Nat, +q: Nat, +hq: {q == Nat.add(VB.pw(29n), 1n) : Nat}, +h: {Nat.is_lt(Nat.add(R, 1n), VB.pw(29n)) == True{} : Bool})
    -> {Nat.is_lt(Nat.add(R, q), VB.pw(31n)) == True{} : Bool}:
  %Equal.sym(Nat, q, Nat.add(VB.pw(29n), 1n), hq) : {Nat.is_lt(Nat.add(R, _), VB.pw(31n)) == True{} : Bool}
  totP(R, VB.pw(29n), h)

# 2x + 2k = 2(x + k), by x's structure (a big sum rewritten into doublings the checker compares level by level)
def dadd2(+x: Nat, +k: Nat) -> {Nat.add(Nat.double(x), Nat.double(k)) == Nat.double(Nat.add(x, k)) : Nat}:
  match x:
    case 0n: {==}
    case 1n+p: Equal.cong(Nat, Nat, z => 2n+z, Nat.add(Nat.double(p), Nat.double(k)), Nat.double(Nat.add(p, k)), dadd2(p, k))

# dadd2 with the doubled constant a literal (k2), so a caller's sum is compared syntactically, never evaluated
def daddk(+x: Nat, +k: Nat, +k2: Nat, +hk: {Nat.double(k) == k2 : Nat}) -> {Nat.add(Nat.double(x), k2) == Nat.double(Nat.add(x, k)) : Nat}:
  %hk : {Nat.add(Nat.double(x), _) == Nat.double(Nat.add(x, k)) : Nat}
  dadd2(x, k)

'''
HEADER = '# GENERATED by codegen/e2e_witness.py. Do not edit.'

# ---------------------------------------------------------------- Bend source reading

class Mod:
    cache = {}

    def __init__(self, path):
        self.path = path.resolve()
        self.text = self.path.read_text()
        self.imports = {}
        for m in re.finditer(r'^import (\S+) as (\w+)$', self.text, re.M):
            self.imports[m.group(2)] = (self.path.parent / m.group(1)).resolve()
        self.defs = {}
        lines = self.text.split('\n')
        i = 0
        while i < len(lines):
            l = lines[i]
            m = re.match(r'def (\w+)\(', l)
            if m:
                j = i + 1
                while j < len(lines) and (lines[j].startswith(' ') or lines[j] == ''):
                    j += 1
                self.defs[m.group(1)] = '\n'.join(lines[i:j]).rstrip()
                i = j
            else:
                i += 1

    @classmethod
    def get(cls, path):
        path = Path(path).resolve()
        if path not in cls.cache:
            cls.cache[path] = Mod(path)
        return cls.cache[path]

    def resolve(self, qname):
        """(module, name) of a qualified or bare function name as written in this module"""
        if '.' in qname:
            a, n = qname.split('.', 1)
            if a in self.imports:
                return Mod.get(self.imports[a]), n
            return None, qname
        return self, qname

    def signature(self, name):
        """(param names, return type text, body text) of a def"""
        d = self.defs[name]
        k = d.index('(')
        depth, j = 0, k
        while True:
            c = d[j]
            if c in '([{':
                depth += 1
            elif c in ')]}':
                depth -= 1
                if depth == 0:
                    break
            j += 1
        self.fullp = [p.strip() for p in split_top(d[k + 1:j])]
        params = [p.strip().lstrip('+-').split(':')[0].strip() for p in split_top(d[k + 1:j])]
        rest = d[j + 1:]
        m = re.match(r'\s*->\s*', rest)
        rest = rest[m.end():]
        # the return type ends at the first top-level ':' followed by a newline or a space
        depth, q = 0, 0
        while q < len(rest):
            c = rest[q]
            if c in '([{<':
                depth += 1
            elif c in ')]}>' and not (c == '>' and q and rest[q - 1] in '=-'):
                depth -= 1
            elif c == ':' and depth == 0:
                break
            q += 1
        return params, rest[:q].strip(), rest[q + 1:].strip()


def split_top(s):
    """split on commas at depth 0 of ( [ { and type application < >"""
    out, depth, cur, i = [], 0, [], 0
    while i < len(s):
        c = s[i]
        if c in '([{':
            depth += 1
        elif c in ')]}':
            depth -= 1
        elif c == '<' and i and (s[i - 1].isalnum() or s[i - 1] == '_'):
            depth += 1
        elif c == '>' and depth > 0 and s[i - 1] not in '=-' and s[i - 1] != ' ':
            depth -= 1
        if c == ',' and depth == 0:
            out.append(''.join(cur).strip())
            cur = []
        else:
            cur.append(c)
        i += 1
    if ''.join(cur).strip():
        out.append(''.join(cur).strip())
    return out


def parse_call(e):
    """(fn, [args]) of 'fn(args)' when e is exactly one call, else None"""
    e = e.strip()
    m = re.match(r'([\w.]+)\(', e)
    if not m:
        return None
    depth = 0
    for i in range(m.end() - 1, len(e)):
        c = e[i]
        if c in '([{':
            depth += 1
        elif c in ')]}':
            depth -= 1
            if depth == 0:
                if i != len(e) - 1:
                    return None
                return m.group(1), split_top(e[m.end():i])
    return None


# ---------------------------------------------------------------- the default object's model

# from this many bytes the checker must not compare a size in unary (the rigid checker's stack gives out between
# 4096 and 8192 levels of a Nat comparison)
BIG = 2048


def pow2_of(n):
    """b when n = 2^b is a large power of two (a word array whose arithmetic must stay symbolic)"""
    if n >= BIG and n & (n - 1) == 0:
        return n.bit_length() - 1
    return None


def words_depth(n):
    w = ((n + 31) // 32) * 8 + 8
    return (w - 1).bit_length()


class Words:
    def __init__(self, n):
        self.n, self.d = n, words_depth(n)


class EList:
    def __init__(self, fill):
        self.fill = fill


class Cont:
    def __init__(self, mod, tname, fields):
        self.mod, self.tname, self.fields = mod, tname, fields   # fields: [(default expr in canon aliases, model)]


class Box:
    def __init__(self, inner, expr):
        self.inner, self.iexpr = inner, expr


class Leaf:
    def __init__(self, expr):
        self.expr = expr


class BitsM:
    """O.Bits{Array.new(U32, d, 0), k}: a zero bit array of depth d holding k bits"""
    def __init__(self, d, k):
        self.d, self.k = d, k


class OneList:
    """a list holding one element: Seq{ALeaf{elem}, 1}"""
    def __init__(self, elem, eexpr):
        self.elem, self.eexpr = elem, eexpr


class VecN:
    """a vector (or list) of n Data elements, all the element's default: Seq{Array.new(T, d, e), n}"""
    def __init__(self, elem, eexpr, ty, n, d):
        self.elem, self.eexpr, self.ty, self.n, self.d = elem, eexpr, ty, n, d


class ArrM:
    """an array of copies of one element (a vector's items)"""
    def __init__(self, elem):
        self.elem = elem


class Tree:
    """the storage tree witnessed for a OneList: one leaf holding the element"""
    def __init__(self, elem):
        self.elem = elem


class Slots:
    """array__slots of a Tree: the list [elem]"""
    def __init__(self, elem):
        self.elem = elem


PREFER = {}   # path -> the alias the bridge file gives it


def canon(path):
    p = Path(path).resolve()
    if p in PREFER:
        return PREFER[p]
    rel = p.relative_to(ROOT).as_posix()
    m = re.match(r'types/(\w+)_def_generated\.bend$', rel)
    if m:
        return m.group(1) + '_d'
    return 'W_' + re.sub(r'\W', '_', rel[:-len('.bend')])


_DECLS = {}   # id(mod) -> (mod, the type and constructor names its text declares)


def _decl_names(mod):
    """the names `^type N` and `^  N{` declare in mod.text (one scan per module: lift asked per token, which made
    e2e_compose quadratic, 150 of its 157 s)"""
    e = _DECLS.get(id(mod))
    if e is None or e[0] is not mod:
        e = _DECLS[id(mod)] = (mod, set(re.findall(r'^type (\w+)\b', mod.text, re.M)) | set(re.findall(r'^  (\w+)\{', mod.text, re.M)))
    return e[1]


class Ctx:
    """the imports the witness file needs, by canonical alias"""

    def __init__(self):
        self.used = {}

    def alias(self, path):
        a = canon(path)
        self.used[a] = Path(path).resolve()
        return a

    def lift(self, mod, expr):
        """an expression of module mod, with its aliases made canonical (bare names of mod qualified)"""
        def sub(m):
            q = m.group(0)
            if '.' in q:
                a, rest = q.split('.', 1)
                if a in mod.imports:
                    return self.alias(mod.imports[a]) + '.' + rest
                return q
            if q in mod.defs or q in _decl_names(mod):
                return self.alias(mod.path) + '.' + q
            return q
        return re.sub(r'(?<![\w.])[A-Za-z_]\w*(?:\.\w+)?', sub, expr)


def model_of(ctx, mod, expr):
    """the model of a default-valued expression written in module mod (its .expr: the expression, lifted)"""
    m = model_of_(ctx, mod, expr)
    m.expr = ctx.lift(mod, expr)
    return m


def model_of_(ctx, mod, expr):
    c = parse_call(expr)
    if c is None:
        raise SystemExit(f'e2e_witness: no model for {expr!r} ({mod.path.name})')
    fn, args = c
    if fn == 'O.words_new':
        return Words(int(args[0]))
    m2, name = mod.resolve(fn)
    if m2 is None or name not in m2.defs:
        raise SystemExit(f'e2e_witness: no def {fn} ({mod.path.name})')
    params, ret, body = m2.signature(name)
    if params:
        raise SystemExit(f'e2e_witness: default with params {fn}')
    b = body.strip()
    if b.startswith('O.words_new('):
        return Words(int(parse_call(b)[1][0]))
    mbits = re.fullmatch(r'O\.Bits\{Array\.new\(U32, (\d+)n, 0\), (\d+)\}', b)
    if mbits:
        return BitsM(int(mbits.group(1)), int(mbits.group(2)))
    mb = parse_call(b)
    if mb and mb[0].endswith('_bx_wrap'):
        return Box(model_of(ctx, m2, mb[1][0]), ctx.lift(m2, mb[1][0]))
    ms = re.match(r'(\w+)\{(.*)\}$', b, re.S)
    if ms and ms.group(1).endswith('_Seq'):
        items = split_top(ms.group(2))
        if items[1].strip() != '0':
            n = int(items[1].strip())
            fill = parse_call(items[0])
            fb = m2.signature(fill[0])[2].strip() if fill and fill[0] in m2.defs else ''
            mf = re.match(r'Array\.new\(([^,]+), d, (.*)\)$', fb)
            if not mf:
                raise SystemExit(f'e2e_witness: nonempty default list {fn}')
            el = model_of(ctx, m2, mf.group(2))
            return VecN(el, el.expr, ctx.lift(m2, mf.group(1)), n, (n - 1).bit_length())
        return EList((m2, items[0]))
    if ms and all(parse_call(a) for a in split_top(ms.group(2))):
        fields = []
        for a in split_top(ms.group(2)):
            sub = model_of(ctx, m2, a)
            if isinstance(sub, Cont) and sub.tname.startswith(ms.group(1) + '_g'):
                fields.extend(sub.fields)      # a group of a grouped container
            else:
                fields.append((ctx.lift(m2, a), sub))
        return Cont(m2, ms.group(1), fields)
    return Leaf(ctx.lift(m2, b))


# the element size in bytes of a byte or packed list module (its default is O.words_new(0))
def words_list_elem(path):
    n = Path(path).name
    m = re.match(r'Fulu_bytelist_\d+_def_generated\.bend$', n)
    if m:
        return 1
    m = re.match(r'Fulu_list_uint(\d+)_\d+_def_generated\.bend$', n)
    if m:
        return int(m.group(1)) // 8
    m = re.match(r'Fulu_list_bytevec_(\d+)_\d+_def_generated\.bend$', n)
    if m:
        return int(m.group(1))
    return None


def model_ne(ctx, mod, expr, lists=True):
    """the model of the non-empty object built from the default expression expr of module mod: every list
    reachable through containers and boxes holds one element (lists=False: lists stay empty). A vector of
    boxed elements (whose default holds empty boxes, BNone) holds valid ones (_bx_default()), in both
    modes. Its .expr is the object's expression."""
    c = parse_call(expr)
    if c is None:
        raise SystemExit(f'e2e_witness: no model for {expr!r} ({mod.path.name})')
    fn, args = c
    m2, name = mod.resolve(fn)
    if fn == 'O.words_new' or m2 is None or name not in m2.defs:
        return model_of(ctx, mod, expr)
    params, ret, body = m2.signature(name)
    b = body.strip()
    if b == 'O.words_new(0)' and words_list_elem(m2.path) and lists:
        k = words_list_elem(m2.path)
        m = Words(k)
        m.expr = f'O.words_new({k})'
        m.changed = True
        return m
    mb = parse_call(b)
    if mb and mb[0].endswith('_bx_wrap'):
        inner = model_ne(ctx, m2, mb[1][0], lists)
        if not getattr(inner, 'changed', False):
            return model_of(ctx, mod, expr)
        m = Box(inner, inner.expr)
        m.expr = f'{ctx.lift(m2, mb[0])}({inner.expr})'
        m.changed = True
        return m
    ms = re.match(r'(\w+)\{(.*)\}$', b, re.S)
    if ms and ms.group(1).endswith('_Seq'):
        items = split_top(ms.group(2))
        fill = parse_call(items[0])
        mw = re.search(r'Array\.set\([^,]+, arr, i, ([\w.]+_bx_wrap)\(v\)\)', m2.text)
        if items[1].strip() != '0':
            # a vector: its length is fixed; boxed elements must be valid (the default's are empty boxes)
            if not mw:
                return model_of(ctx, mod, expr)
            n = int(items[1].strip())
            d = (n - 1).bit_length()
            ty = ctx.lift(m2, re.match(r'Array<(.*)>$', m2.signature(fill[0])[1].strip()).group(1))
            el = model_of(ctx, m2, mw.group(1)[:-len('_bx_wrap')] + '_bx_default()')
            items_e = f'ALeaf{{{el.expr}}}'      # the array of 2^d copies, written out (boxes are not Data)
            for _ in range(d):
                items_e = f'ANode{{{items_e}, {items_e}}}'
            m = VecN(el, el.expr, ty, n, d)
            m.items = items_e
            m.expr = f'{ctx.lift(m2, ms.group(1))}{{{items_e}, {n}}}'
            m.changed = True
            return m
        if not lists:
            return model_of(ctx, mod, expr)
        mw = re.search(r'Array\.set\([^,]+, arr, i, ([\w.]+_bx_wrap)\(v\)\)', m2.text)
        if mw:
            wm, wn = m2.resolve(mw.group(1))
            eexpr_local = mw.group(1)[:-len('_bx_wrap')] + '_bx_default()'
        else:
            fb = m2.signature(fill[0])[2].strip()
            mf = re.match(r'Array\.new\(([^,]+), d, (.*)\)$', fb)
            if not mf:
                raise SystemExit(f'e2e_witness: no element default for {fn} ({m2.path.name})')
            eexpr_local = mf.group(2)
        elem = model_of(ctx, m2, eexpr_local)
        m = OneList(elem, elem.expr)
        m.expr = f'{ctx.lift(m2, ms.group(1))}{{ALeaf{{{elem.expr}}}, 1}}'
        m.changed = True
        return m
    if ms and all(parse_call(a) for a in split_top(ms.group(2))):
        fields, parts, changed = [], [], False
        for a in split_top(ms.group(2)):
            sub = model_ne(ctx, m2, a, lists)
            changed |= getattr(sub, 'changed', False)
            parts.append(sub.expr)
            if isinstance(sub, Cont) and sub.tname.startswith(ms.group(1) + '_g'):
                fields.extend(sub.fields)
            else:
                fields.append((sub.expr, sub))
        if not changed:
            return model_of(ctx, mod, expr)
        m = Cont(m2, ms.group(1), fields)
        m.expr = f'{ctx.lift(m2, ms.group(1))}{{{", ".join(parts)}}}'
        m.changed = True
        return m
    return model_of(ctx, mod, expr)


def nat_value(e):
    """the value of a closed numeral expression (Nn, N, U32.to_nat(N), 1n+..), else None"""
    e = e.strip()
    m = re.fullmatch(r'(\d+)n?', e)
    if m:
        return int(m.group(1))
    m = re.fullmatch(r'U32\.to_nat\((.*)\)', e)
    if m:
        return nat_value(m.group(1))
    m = re.fullmatch(r'1n\+(.*)', e)
    if m:
        v = nat_value(m.group(1))
        return None if v is None else v + 1
    return None


def parse_match(body):
    """(scrutinee, [(pattern, branch text)]) of a def body `match x:` with its cases, else None"""
    lines = body.split('\n')
    m = re.fullmatch(r'match (\w+):', lines[0].strip())
    if not m:
        return None
    rest = [l for l in lines[1:] if l.strip()]
    if not rest:
        return None
    ind = len(rest[0]) - len(rest[0].lstrip())
    cases, cur = [], None
    for l in rest:
        li = len(l) - len(l.lstrip())
        if li == ind:
            mc = re.match(r'\s*case (.*?): ?(.*)$', l)
            if not mc:
                return None
            cur = [mc.group(1).strip(), [mc.group(2)] if mc.group(2).strip() else []]
            cases.append(cur)
        elif li > ind and cur is not None:
            cur[1].append(l)
        else:
            return None
    out = []
    for pat, bl in cases:
        if len(bl) > 1 or (bl and bl[0] != bl[0].lstrip()):
            k = min(len(x) - len(x.lstrip()) for x in bl)
            text = '\n'.join(x[k:] for x in bl)
        else:
            text = bl[0].strip() if bl else ''
        out.append((pat, text.strip()))
    return m.group(1), out


# ---------------------------------------------------------------- premise synthesis

class Synth:
    def __init__(self, ctx):
        self.ctx = ctx
        self.lemmas = {}
        self.named = {}

    def wz(self, n, d):
        nm = f'WZ{n}'
        self.lemmas[nm] = (f'def {nm}() -> {{O.words_new({n}) == O.Words{{FD.array__thaw(U32, FD.array__trep(U32, {d}n, 0)), {n}}} : O.Words}}:\n'
                           f'  %FD.array__new(U32, {d}n, 0) : {{O.words_new({n}) == O.Words{{_, {n}}} : O.Words}}\n'
                           f'  {{==}}')
        return f'{nm}()'

    def arg_model(self, e, env):
        """the model of an argument expression: a variable of env, or projections of one"""
        e = e.strip()
        if e in env:
            x = env[e]
            if isinstance(x, tuple):
                return x[2] if len(x) > 2 else None
            return x
        c = parse_call(e)
        if c is None:
            return None
        fn, args = c
        base = fn.split('.')[-1]
        if base == 'array__slots' and len(args) == 2:
            t = self.arg_model(args[1], env)
            return Slots(t.elem) if isinstance(t, Tree) else None
        inner = self.arg_model(args[0], env) if args else None
        if base.startswith('tfz_') and isinstance(inner, ArrM):
            return Tree(inner.elem)
        if re.match(r'pju_\w+_\d+$', base) and isinstance(inner, Cont) and len(inner.fields) == 1:
            return inner.fields[0][1]
        if re.match(r'xat_\w+$', base) and isinstance(inner, Slots):
            return inner.elem
        if re.match(r'(th|fz)_\w+$', base) and inner is not None:
            return inner
        if inner is None:
            return None
        m = re.match(r'pj_\w+_(\d+)$', base)
        if m and isinstance(inner, Cont):
            return inner.fields[int(m.group(1))][1]
        if re.match(r'pjb_\w+_bx$', base) and isinstance(inner, Box):
            return inner.inner
        return None

    def part(self, mod, pred, env):
        """one part of a split P2 chain: a nested P2 stays split, anything else is a named lemma of its predicate"""
        c = parse_call(pred.strip())
        if c and c[0].split('.')[-1] == 'P2' and mod.resolve(c[0])[0] is not None and mod.resolve(c[0])[0].path.name == 'dk.bend':
            return self.prove(mod, pred, env)
        ty = self.subst(mod, pred.strip(), env)
        term = self.prove(mod, pred, dict(env, __split=False))
        nm = f'PC{len(self.lemmas)}'
        self.lemmas[f'zz{len(self.lemmas):04d}_{nm}'] = f'def {nm}() -> {ty}:\n  {term}'
        return f'{nm}()'

    def prove(self, mod, pred, env):
        """a proof term of the Data predicate text pred (written in mod), with its variables' models in env"""
        p = pred.strip()
        if p.startswith('{'):
            return self.eq(p, dict(env, __mod=mod))
        if p.startswith('match '):
            return self.unfold(mod, p, env)
        c = parse_call(p)
        if c is None:
            raise SystemExit(f'e2e_witness: cannot read {p[:120]!r}')
        fn, args = c
        base = fn.split('.')[-1]
        m2, name = mod.resolve(fn)
        if (m2 is not None and m2.path.name == 'dk.bend') or fn in ('Ex', 'P2', 'Or2'):
            if base == 'Ex':
                lam = args[1]
                mv = re.match(r'(\w+)\s*=>\s*', lam, re.S)
                v = mv.group(1)
                wit = self.witness(mod, args[0], v, lam[mv.end():], env)
                env2 = dict(env)
                subj = env.get('__subj')
                if isinstance(subj, (OneList, VecN)) and 'array__Tree<' in args[0]:
                    env2[v] = ('val', wit, Tree(subj.elem))
                else:
                    env2[v] = ('val', wit)
                return f'({wit}, {self.prove(mod, lam[mv.end():], env2)})'
            if base == 'P2':
                if env.get('__split') or re.search(r'(?<![\w.])TOT_\w+\(', args[1]):
                    # a total-size chain: each part its own lemma, typed by its predicate (the checker would
                    # otherwise compare the parts inside the chain's type, walking the total's 2^29 term)
                    env2 = dict(env, __split=True)
                    return f'({self.part(mod, args[0], env2)}, {self.part(mod, args[1], env2)})'
                return f'({self.prove(mod, args[0], env)}, {self.prove(mod, args[1], env)})'
            if base == 'Or2':
                subj = env.get('__subj')
                mu = re.match(r'.*_c(\d+)$', subj.tname) if isinstance(subj, Cont) else None
                if mu:
                    ma0 = re.search(r'_(\d+)\(', args[0])
                    return (f'Inl{{{self.prove(mod, args[0], env)}}}' if ma0 and ma0.group(1) == mu.group(1)
                            else f'Inr{{{self.prove(mod, args[1], env)}}}')
                if (isinstance(subj, Words) and subj.n == 0) or (isinstance(subj, BitsM) and subj.k == 0):
                    return f'Inl{{{self.prove(mod, args[0], env)}}}'
                return f'Inr{{{self.prove(mod, args[1], env)}}}'
        if m2 is None or name not in m2.defs:
            raise SystemExit(f'e2e_witness: no def {fn} ({mod.path.name})')
        params, ret, body = m2.signature(name)
        env2 = {'__e': {}, '__raw': {}}
        for pn, a in zip(params, args):
            env2['__raw'][pn] = (a, env)
            mdl = self.arg_model(a, env)
            if mdl is not None:
                env2[pn] = mdl
            env2['__e'][pn] = self.subst(mod, a, env)
        if params and params[0] in env2:
            env2['__subj'] = env2[params[0]]
        elif '__subj' in env:
            env2['__subj'] = env['__subj']
        if body.startswith('match'):
            return self.unfold(m2, body, env2)
        subj = env2.get('__subj')
        full = list(m2.fullp)
        if isinstance(subj, Words) and pow2_of(subj.n) and params and params[0] in env2 \
                and re.match(r'DK\.Ex\(\w+\.array__Tree<U32>, t =>', body):
            return self.leaf(m2, name, full, params, body, env2, subj)
        if isinstance(subj, Words) and subj.n >= BIG and params and params[0] in env2:
            # a large word array: its own lemma, so that a failure is located and nothing is inlined twice
            ty = f'{self.ctx.alias(m2.path)}.{name}(' + ', '.join(env2['__e'][pn] for pn in params) + ')'
            key = ty
            if key not in self.named:
                term = self.prove(m2, body, env2)
                nm = f'big{len(self.named)}'
                self.named[key] = nm
                self.lemmas[f'z{len(self.named):03d}_{nm}'] = f'def {nm}() -> {ty}:\n  {term}'
            return f'{self.named[key]}()'
        return self.prove(m2, body, env2)

    def unfold(self, m2, body, env2):
        """a premise defined by a match, at known arguments. On a numeral k (`case 0n: A / case 1n+q: B`,
        the element-wise premises): A at 0 (over zero elements, {True{} == True{}}), B with q := k-1
        otherwise. On a boxed or mirrored element (`case MSome{v}` / `case BSome{v, ..}`) whose model is
        a box: the Some case with v the inner model. On a container mirror (`case M_X{a0, ..}`) whose
        model is a container: its fields (boxes unwrapped). Anything else keeps the old reading, R."""
        mt = parse_match(body)
        if mt is None:
            return R
        var, cases = mt
        pats = [p for p, _ in cases]
        if pats[:1] == ['0n'] and len(cases) == 2 and re.fullmatch(r'1n\+\+?\w+', pats[1]):
            raw, cenv = env2.get('__raw', {}).get(var, ('', {}))
            # the caller's Ex-bound variables (N, ..) by their witnesses
            raw = re.sub(r'(?<![\w.])[A-Za-z_]\w*(?![\w.{(])',
                         lambda m: cenv[m.group(0)][1] if isinstance(cenv.get(m.group(0)), tuple) else m.group(0), raw)
            k = nat_value(self.subst(m2, raw, cenv)) if raw else None
            if not k:
                return R
            q = pats[1][3:].lstrip('+')
            env3 = dict(env2)
            env3['__e'] = dict(env2['__e'])
            env3['__e'][q] = f'{k - 1}n'
            env3[q] = ('val', f'{k - 1}n')
            return self.prove(m2, cases[1][1], env3)
        mdl = env2.get(var)
        if isinstance(mdl, Cont):
            # a match on the container (or union option) itself: the case of its constructor, fields bound
            for pat_, sub_ in cases:
                mc = re.fullmatch(r'([\w.]+)\{(.*)\}', pat_)
                if mc and mc.group(1).split('.')[-1] == mdl.tname:
                    bs_ = [b.strip().lstrip('+') for b in split_top(mc.group(2))]
                    if len(bs_) == len(mdl.fields):
                        env3 = dict(env2)
                        env3['__e'] = dict(env2.get('__e', {}))
                        for b_, (fe, fm) in zip(bs_, mdl.fields):
                            env3[b_] = fm
                            env3['__e'][b_] = fe
                        return self.prove(m2, sub_, env3)
        if isinstance(mdl, OneList) and len(cases) == 1:
            mc = re.fullmatch(r'([\w.]+)\{(.*)\}', cases[0][0])
            if mc and mc.group(1).endswith('_Seq'):
                bs_ = [b.strip().lstrip('+') for b in split_top(mc.group(2))]
                env3 = dict(env2)
                env3['__e'] = dict(env2.get('__e', {}))
                it = f'ALeaf{{{mdl.eexpr}}}'
                env3[bs_[0]] = ('val', it, ArrM(mdl.elem))
                env3['__e'][bs_[0]] = it
                env3[bs_[1]] = ('val', '1')
                env3['__e'][bs_[1]] = '1'
                return self.prove(m2, cases[0][1], env3)
        if isinstance(mdl, EList) and len(cases) == 1:
            mc = re.fullmatch(r'([\w.]+)\{(.*)\}', cases[0][0])
            if mc and mc.group(1).endswith('_Seq'):
                bs_ = [b.strip().lstrip('+') for b in split_top(mc.group(2))]
                env3 = dict(env2)
                env3['__e'] = dict(env2.get('__e', {}))
                fm_, fe_ = mdl.fill
                env3[bs_[0]] = ('val', self.ctx.lift(fm_, fe_))
                env3['__e'][bs_[0]] = self.ctx.lift(fm_, fe_)
                env3[bs_[1]] = ('val', '0')
                env3['__e'][bs_[1]] = '0'
                return self.prove(m2, cases[0][1], env3)
        if isinstance(mdl, Words) and len(cases) == 1:
            mc = re.fullmatch(r'([\w.]+)\{(.*)\}', cases[0][0])
            if mc and mc.group(1).split('.')[-1] == 'Words':
                bs_ = [b.strip().lstrip('+') for b in split_top(mc.group(2))]
                env3 = dict(env2)
                env3['__e'] = dict(env2.get('__e', {}))
                for b_, v_ in zip(bs_, (f'FD.array__thaw(U32, FD.array__trep(U32, {mdl.d}n, 0))', f'{mdl.n}')):
                    env3[b_] = ('val', v_)
                    env3['__e'][b_] = v_
                return self.prove(m2, cases[0][1], env3)
        if isinstance(mdl, VecN) and len(cases) == 1 and getattr(mdl, 'items', None):
            mc = re.fullmatch(r'([\w.]+)\{(.*)\}', cases[0][0])
            if mc and mc.group(1).endswith('_Seq'):
                bs_ = [b.strip().lstrip('+') for b in split_top(mc.group(2))]
                env3 = dict(env2)
                env3['__e'] = dict(env2.get('__e', {}))
                env3[bs_[0]] = ('val', mdl.items, ArrM(mdl.elem))
                env3['__e'][bs_[0]] = mdl.items
                env3[bs_[1]] = ('val', f'{mdl.n}')
                env3['__e'][bs_[1]] = f'{mdl.n}'
                return self.prove(m2, cases[0][1], env3)
        if isinstance(mdl, BitsM) and len(cases) == 1:
            mc = re.fullmatch(r'([\w.]+)\{(.*)\}', cases[0][0])
            if mc and mc.group(1).split('.')[-1] == 'Bits':
                bs_ = [b.strip().lstrip('+') for b in split_top(mc.group(2))]
                env3 = dict(env2)
                env3['__e'] = dict(env2.get('__e', {}))
                for b_, v_ in zip(bs_, (f'Array.new(U32, {mdl.d}n, 0)', f'{mdl.k}')):
                    env3[b_] = ('val', v_)
                    env3['__e'][b_] = v_
                return self.prove(m2, cases[0][1], env3)
        for pat, sub in cases:
            mc = re.fullmatch(r'([\w.]+)\{(.*)\}', pat)
            if not mc:
                continue
            ctor, binders = mc.group(1).split('.')[-1], [b.strip().lstrip('+') for b in split_top(mc.group(2))]
            env3 = dict(env2)
            if ctor in ('MSome', 'BSome') and isinstance(mdl, Box):
                env3[binders[0]] = mdl.inner
                return self.prove(m2, sub, env3)
            if isinstance(mdl, Cont) and ctor.startswith('M_') and len(binders) == len(mdl.fields):
                for b, (_, fm) in zip(binders, mdl.fields):
                    env3[b] = fm.inner if isinstance(fm, Box) else fm
                return self.prove(m2, sub, env3)
        return R

    def leaf(self, m2, name, full, params, body, env2, subj):
        """a storage predicate (DK.Ex over a word tree t) of a large zero array 2^b bytes, 2^c chunks, depth d:
        a lemma with b, c, d symbolic (no unary 2^b is ever built), applied at the concrete sizes"""
        b = pow2_of(subj.n)
        c, d = b - 5, subj.d
        self.ctx.alias(E2E / 'e2e_wit.bend')
        key = ('leaf', m2.path, name)
        hyps = []
        if key not in self.named:
            sym = {'t': 'FD.array__trep(U32, d, 0)', 'dw': 'd', 'N': 'FD.u32__pow2u(b)', 'q': 'WT.QP(c)', 'r': '32n'}
            def walk(e):
                e = e.strip()
                cl = parse_call(e)
                if cl and cl[0].split('.')[-1] == 'Ex' and cl[0].startswith('DK'):
                    lam = cl[1][1]
                    mv = re.match(r'(\w+)\s*=>\s*', lam, re.S)
                    return f'({sym[mv.group(1)]}, {walk(lam[mv.end():])})'
                if cl and cl[0].split('.')[-1] == 'P2' and cl[0].startswith('DK'):
                    return f'({walk(cl[1][0])}, {walk(cl[1][1])})'
                if not e.startswith('{'):
                    raise SystemExit(f'e2e_witness: leaf {name}: cannot read {e[:80]!r}')
                if re.search(r'== O\.Words\{', e) and 'array__thaw' in e:
                    return 'ew'
                if 'array__perfect(U32' in e:
                    return 'FD.array__trep_perfect(U32, d, 0)'
                if re.search(r'U32\.to_nat\(N\) == Nat\.add\(WS\.e32\(q\), (32n|r)\)', e):
                    return 'WT.eN(c, b, eb, FD.u32__pow2u(b), FD.u32__pow2u_value(b, hb))'
                if re.search(r'Nat\.is_le\(O\.e8\(1n\+q\), \w+\.spec_common__pow2\(dw\)\)', e):
                    return 'WT.eQ(c, d, hd)'
                t = self.ctx.lift(m2, e)
                t = re.sub(r'(?<![\w.])(t|dw|N|q|r)(?![\w{(])', lambda m: sym[m.group(1)], t)
                hyps.append(t)
                return f'h{len(hyps) - 1}'
            term = walk(body)
            ps = []
            for i, fp in enumerate(full):
                mode = fp[0] if fp[0] in '+-' else ''
                pn, pt = fp.lstrip('+-').split(':', 1)
                ps.append(('-' if i == 0 else mode) + pn.strip() + ': ' + self.ctx.lift(m2, pt.strip()))
            w = params[0]
            ps += ['+c: Nat', '+b: Nat', '+d: Nat', '+eb: {Nat.add(5n, c) == b : Nat}', '+hb: {Nat.is_lt(b, 32n) == True{} : Bool}',
                   '+hd: {Nat.is_le(Nat.add(3n, c), d) == True{} : Bool}',
                   f'+ew: {{{w} == O.Words{{FD.array__thaw(U32, FD.array__trep(U32, d, 0)), FD.u32__pow2u(b)}} : O.Words}}']
            ps += [f'+h{i}: {h}' for i, h in enumerate(hyps)]
            nm = f'sym_{canon(m2.path)}_{name}'
            ret = f'{self.ctx.alias(m2.path)}.{name}(' + ', '.join(params) + ')'
            self.named[key] = (nm, len(hyps))
            self.lemmas[f'y{len(self.named):03d}_{nm}'] = f'def {nm}(' + ', '.join(ps) + f') -> {ret}:\n  {term}'
        nm, nh = self.named[key]
        args = [env2['__e'][pn] for pn in params] + [f'{c}n', f'{b}n', f'{d}n', R, R, R, self.wz(subj.n, subj.d)] + [R] * nh
        return f'{nm}(' + ', '.join(args) + ')'

    def witness(self, mod, ty, v, body, env):
        subj = env.get('__subj')
        ty = ty.strip()
        if isinstance(subj, Words):
            if ty.endswith('array__Tree<U32>'):
                return f'FD.array__trep(U32, {subj.d}n, 0)'
            if v == 'dw':
                return f'{subj.d}n'
            pw = pow2_of(subj.n)
            if v == 'N':
                return f'FD.u32__pow2u({pw}n)' if pw else f'{subj.n}'
            if v == 'q' and pw and re.search(r'U32\.to_nat\(N\) == Nat\.add\(WS\.e32\(q\), (32n|r)\)', body):
                self.ctx.alias(E2E / 'e2e_wit.bend')
                return f'WT.QP({pw - 5}n)'
            if v == 'r' and pw:
                return '32n'
            if v == 'q':
                if re.search(r'U32\.to_nat\(N\) == Nat\.add\(WS\.e32\(q\), 32n\)', body):
                    return f'{subj.n // 32 - 1}n'
                return f'{(subj.n - 1) // 32}n'
            if v == 'r':
                return f'{subj.n - 32 * ((subj.n - 1) // 32)}n'
        if isinstance(subj, BitsM):
            if ty.endswith('array__Tree<U32>'):
                return f'FD.array__trep(U32, {subj.d}n, 0)'
            if v == 'dw':
                return f'{subj.d}n'
            if v in ('K', 'N'):
                return f'{subj.k}'
        if isinstance(subj, VecN):
            if 'array__Tree<' in ty:
                ma = re.search(r'(?<![\w])(\w+\.)?am_(\w+)\(' + v + r'\)', body)
                if ma and getattr(subj, 'items', None):
                    return self.ctx.lift(mod, (ma.group(1) or '') + 'tfz_' + ma.group(2)) + f'({subj.items})'
                return f'FD.array__trep({subj.ty}, {subj.d}n, {subj.eexpr})'
            if v == 'dw':
                return f'{subj.d}n'
            if v == 'N':
                return f'{subj.n}'
        if isinstance(subj, Words) and v == 'd':
            return f'{subj.d}n'
        if isinstance(subj, Cont):
            mc = re.search(r'\{\w+ == ([\w.]+)\{(.*?)\} : ', body)
            if mc:
                cargs = [a_.strip() for a_ in split_top(mc.group(2))]
                if v in cargs and len(cargs) == len(subj.fields):
                    return subj.fields[cargs.index(v)][0]
        if isinstance(subj, OneList):
            if 'array__Tree<' in ty:
                ma = re.search(r'(?<![\w])(\w+\.)?am_(\w+)\(' + v + r'\)', body)
                if ma:
                    return self.ctx.lift(mod, (ma.group(1) or '') + 'tfz_' + ma.group(2)) + f'(ALeaf{{{subj.eexpr}}})'
                return f'FD.TLeaf{{{subj.eexpr}}}'
            if v == 'dw':
                return '0n'
            if v == 'N':
                return '1'
        if isinstance(subj, EList):
            if 'array__Tree<' in ty:
                inner = ty[ty.index('array__Tree<') + len('array__Tree<'):-1]
                mm = re.match(r'(?:(\w+)\.)?MB<', inner)
                if mm:
                    return 'FD.TLeaf{' + self.ctx.lift(mod, (mm.group(1) + '.' if mm.group(1) else '') + 'MNone') + '{}}'
                el = self.ctx.lift(mod, inner)
                return 'FD.TLeaf{' + el + '_default()}'
            if v == 'dw':
                return '0n'
            if v == 'N':
                return '0'
        if isinstance(subj, Box) and v == 'v':
            return subj.iexpr
        me = re.search(r'\{' + v + r' == (.*?) : [\w.<>&, ]+\}', body)
        if me:
            return self.subst(mod, me.group(1), env)
        if isinstance(subj, Cont):
            mx = re.match(r'x(\d+)$', v)
            if mx:
                return subj.fields[int(mx.group(1))][0]
        raise SystemExit(f'e2e_witness: no witness for {v}: {ty} of {type(subj).__name__} ({mod.path.name})')

    def subst(self, mod, e, env):
        """expression e of module mod, lifted, with its variables replaced by their models' expressions"""
        e = self.ctx.lift(mod, e)
        def sub(m):
            v = m.group(0)
            if v in env.get('__e', {}):
                return env['__e'][v]
            x = env.get(v)
            if x is None or isinstance(x, tuple) or v.startswith('__'):
                if isinstance(x, tuple):
                    return x[1]
                return v
            return x.expr
        return re.sub(r'(?<![\w.])[a-z]\w*(?![\w.{(])', sub, e)

    def _dbl(self, j, x):
        for _ in range(j):
            x = f'Nat.double({x})'
        return x

    def _chain(self, n, j, y):
        """{U32.to_nat(n) == double^j(y)}: j splits of n by its low bit (shr_split: the low j bits of n are 0), then
        {U32.to_nat(n >> j) == y} compared (n >> j levels, not n)"""
        FDA = self.ctx.alias(ROOT / 'proofs/compact/found.bend')
        if j == 0:
            return '{==}'
        L = f'Nat.add({FDA}.spec_numeric__bit_value({FDA}.u32__low_bit({n})), Nat.double(U32.to_nat(U32.shr({n}))))'
        inner = self._chain(n >> 1, j - 1, y)
        return (f'Equal.trans(Nat, U32.to_nat({n}), {L}, {self._dbl(j, y)}, {FDA}.u32__shr_split({n}), '
                f'Equal.cong(Nat, Nat, z => Nat.add({FDA}.spec_numeric__bit_value({FDA}.u32__low_bit({n})), Nat.double(z)), '
                f'U32.to_nat(U32.shr({n})), {self._dbl(j - 1, y)}, {inner}))')

    def big_nfact(self, n):
        """{U32.to_nat(n) == Nat.add(WS.e32(q), r)} for n = 32 q + r (0 < r <= 32, r = 2^t s with s odd): e32 written
        out, the sum rewritten into t doublings of 2^(5-t) q + s (WT.daddk), and n split t times by its low bit:
        nothing is compared deeper than n >> t"""
        WSA = self.ctx.alias(ROOT / 'proofs/obj/words_spec.bend')
        self.ctx.alias(E2E / 'e2e_wit.bend')
        r = n % 32 or 32
        q = (n - r) // 32
        t = (r & -r).bit_length() - 1
        D = lambda k: self._dbl(k, f'{q}n')
        T = [f'{self._dbl(i, f"Nat.add({D(5 - i)}, {r >> i}n)")}' for i in range(t + 1)]
        R = f'Nat.add({WSA}.e32({q}n), {r}n)'
        nm = f'NB{n}'
        parts = []   # one lemma entry, its defs in order (callers sort or reverse the entries)
        parts.append(f'def {nm}s0() -> {{{R} == {T[0]} : Nat}}:\n'
                     f'  Equal.cong(Nat, Nat, z => Nat.add(z, {r}n), {WSA}.e32({q}n), {D(5)}, WT.e32d({q}n))')
        # each step its own def: T(i-1) == T(i) by daddk under i - 1 doublings
        for i in range(1, t + 1):
            core = f'WT.daddk({D(5 - i)}, {r >> i}n, {r >> (i - 1)}n, {{==}})'
            if i > 1:
                core = (f'Equal.cong(Nat, Nat, z => {self._dbl(i - 1, "z")}, Nat.add({D(6 - i)}, {r >> (i - 1)}n), '
                        f'Nat.double(Nat.add({D(5 - i)}, {r >> i}n)), {core})')
            parts.append(f'def {nm}s{i}() -> {{{T[i - 1]} == {T[i]} : Nat}}:\n  {core}')
        pf = f'{nm}s0()'
        for i in range(1, t + 1):
            pf = f'Equal.trans(Nat, {R}, {T[i - 1]}, {T[i]}, {pf}, {nm}s{i}())'
        parts.append(f'def {nm}r() -> {{{R} == {T[t]} : Nat}}:\n  {pf}')
        parts.append(f'def {nm}c() -> {{U32.to_nat({n}) == {T[t]} : Nat}}:\n'
                     f'  {self._chain(n, t, f"Nat.add({D(5 - t)}, {r >> t}n)")}')
        self.lemmas[nm] = '\n\n'.join(parts) + (f'\n\ndef {nm}() -> {{U32.to_nat({n}) == {R} : Nat}}:\n'
                                                f'  Equal.trans(Nat, U32.to_nat({n}), {T[t]}, {R}, {nm}c(), Equal.sym(Nat, {R}, {T[t]}, {nm}r()))')
        return f'{nm}()'

    def big_lfact(self, n, o, k=32):
        """{U32.to_nat(WO.len(o)) == PK.e<k>(PK.cnt<k>(o))} for the n-byte object o, k-byte elements (WT.lbig<k>): n
        split log2(k) times by its low bit, then n / k compared with the count"""
        PKA = self.ctx.alias(ROOT / 'proofs/obj/packed_obj_light.bend')
        self.ctx.alias(E2E / 'e2e_wit.bend')
        j = {8: 3, 16: 4, 32: 5}[k]
        c = n // k
        Djo = self._dbl(j, f'{PKA}.cnt{k}({o})')
        nm = f'LB{n}_{k}'
        bsp, bsa = ('+bs: +List<U32>', 'bs') if re.search(r'(?<![\w.])bs(?![\w])', o) else ('', '')
        self.lemmas[nm] = (f'def {nm}({bsp}) -> {{U32.to_nat({n}) == {Djo} : Nat}}:\n'
                           f'  Equal.trans(Nat, U32.to_nat({n}), {self._dbl(j, f"{c}n")}, {Djo}, {self._chain(n, j, f"{c}n")},\n'
                           f'    Equal.cong(Nat, Nat, z => {self._dbl(j, "z")}, {c}n, {PKA}.cnt{k}({o}), {{==}}))')
        return f'WT.lbig{"" if k == 32 else k}({o}, {n}, {{==}}, {nm}({bsa}))'

    def tot_qp(self, q):
        """{Nat.is_lt(S, pw(31n)) == True} for a left-nested sum S with one progressive bit list's term QP(..) = 2^29 + 1:
        QP moved last (WT.swapq, one step per later term), then WT.tot29 with the rest compared in unary (small)"""
        m = re.match(r'^\{Nat\.is_lt\((.*), ([\w.]+)\.pw\(31n\)\) == True\{\} : Bool\}$', q, re.S)
        terms, cur = [], m.group(1)
        while True:
            ma = re.match(r'^Nat\.add\((.*)\)$', cur, re.S)
            parts = split_top(ma.group(1)) if ma else None
            if not parts or len(parts) != 2:
                terms.insert(0, cur)
                break
            terms.insert(0, parts[1])
            cur = parts[0]
        js = [i for i, t in enumerate(terms) if re.search(r'\.QP\(', t)]
        if len(js) != 1 or js[0] == 0:
            return None
        j = js[0]
        FDA = self.ctx.alias(ROOT / 'proofs/compact/found.bend')
        self.ctx.alias(E2E / 'e2e_wit.bend')
        Q = terms[j]
        U = [terms[0]]
        for t in terms[1:]:
            U.append(f'Nat.add({U[-1]}, {t})')
        W = U[j - 1]
        pf = None    # {U_k == add(W_k, Q)}
        for k in range(j + 1, len(terms)):
            Wn = f'Nat.add({W}, {terms[k]})'
            step = f'WT.swapq({W}, {Q}, {terms[k]})'
            if pf is None:
                pf = step
            else:
                pf = (f'Equal.trans(Nat, {U[k]}, Nat.add(Nat.add({W}, {Q}), {terms[k]}), Nat.add({Wn}, {Q}), '
                      f'Equal.cong(Nat, Nat, z => Nat.add(z, {terms[k]}), {U[k - 1]}, Nat.add({W}, {Q}), {pf}), {step})')
            W = Wn
        S = U[-1]
        PW = m.group(2)
        body = f'WT.tot29({W}, {Q}, {{==}}, {{==}})'
        if pf is not None:
            body = (f'{FDA}.logic__subst(Nat, z => {{Nat.is_lt(z, {PW}.pw(31n)) == True{{}} : Bool}}, Nat.add({W}, {Q}), {S}, '
                    f'Equal.sym(Nat, {S}, Nat.add({W}, {Q}), {pf}), {body})')
        nm = f'TOT{len(self.lemmas)}'
        self.lemmas[f'x5{nm}'] = f'def {nm}() -> {q}:\n  {body}'
        return f'{nm}()'

    def bz(self, d, k):
        nm = f'BZ{d}_{k}'
        self.lemmas[nm] = (f'def {nm}() -> {{O.Bits{{Array.new(U32, {d}n, 0), {k}}} == O.Bits{{FD.array__thaw(U32, FD.array__trep(U32, {d}n, 0)), {k}}} : O.Bits}}:\n'
                           f'  %FD.array__new(U32, {d}n, 0) : {{O.Bits{{Array.new(U32, {d}n, 0), {k}}} == O.Bits{{_, {k}}} : O.Bits}}\n'
                           f'  {{==}}')
        return f'{nm}()'

    def eq(self, p, env):
        subj = env.get('__subj')
        mt = re.match(r'^\{Nat\.is_lt\((.*), (\w+)\.pw\(31n\)\) == True\{\} : Bool\}$', p, re.S)
        if mt and re.search(r'(?<![\w.])QP\(', mt.group(1)) and env.get('__mod'):
            r = self.tot_qp(self.subst(env['__mod'], p, env))
            if r:
                return r
        if isinstance(subj, VecN) and 'array__thaw' in p and '== ' in p:
            q = self.subst(env['__mod'], p, env) if env.get('__mod') else p
            q = re.sub(r'(?<![\w.])[A-Za-z_]\w*(?![\w.{(])',
                       lambda m: env[m.group(0)][1] if isinstance(env.get(m.group(0)), tuple) else m.group(0), q)
            tt = f'FD.array__thaw({subj.ty}, FD.array__trep({subj.ty}, {subj.d}n, {subj.eexpr}))'
            if tt in q:
                nm = f'VZ{len(self.lemmas)}'
                self.lemmas[nm] = (f'def {nm}() -> {q}:\n  %FD.array__new({subj.ty}, {subj.d}n, {subj.eexpr}) : '
                                   f'{q.replace(tt, "_", 1)}\n  {{==}}')
                return f'{nm}()'
        if isinstance(subj, BitsM) and re.search(r'== O\.Bits\{', p) and 'array__thaw' in p:
            return self.bz(subj.d, subj.k)
        if isinstance(subj, BitsM) and 'array__perfect(U32' in p:
            return f'FD.array__trep_perfect(U32, {subj.d}n, 0)'
        if isinstance(subj, Words) and re.search(r'== O\.Words\{', p) and 'array__thaw' in p:
            return self.wz(subj.n, subj.d)
        if isinstance(subj, Words) and 'array__perfect(U32' in p:
            return f'FD.array__trep_perfect(U32, {subj.d}n, 0)'
        pw = pow2_of(subj.n) if isinstance(subj, Words) else None
        if pw and re.search(r'U32\.to_nat\(N\) == Nat\.add\(WS\.e32\(q\), (32n|r)\)', p):
            return f'WT.eN({pw - 5}n, {pw}n, {{==}}, FD.u32__pow2u({pw}n), FD.u32__pow2u_value({pw}n, {{==}}))'
        if pw and re.search(r'^\{U32\.to_nat\(WO\.len\(o\)\) == e8\(cnt8\(o\)\) : Nat\}$', p) and pw >= 3:
            self.ctx.alias(E2E / 'e2e_wit.bend')
            return f'WT.len8({env["__e"]["o"]}, {pw - 3}n, {pw}n, {subj.d}n, {{==}}, {{==}}, {self.wz(subj.n, subj.d)})'
        big = isinstance(subj, Words) and subj.n >= BIG
        if big and not pw and re.search(r'U32\.to_nat\(N\) == Nat\.add\(WS\.e32\(q\), (32n|r)\)', p):
            return self.big_nfact(subj.n)
        ml = re.search(r'^\{U32\.to_nat\(WO\.len\(o\)\) == e(8|16|32)\(cnt\1\(o\)\) : Nat\}$', p)
        if big and ml and subj.n % int(ml.group(1)) == 0 and (not pw or ml.group(1) == '16'):
            return self.big_lfact(subj.n, env["__e"]["o"], int(ml.group(1)))
        if pw and re.search(r'^\{U32\.to_nat\(WO\.len\(o\)\) == e32\(cnt32\(o\)\) : Nat\}$', p) and pw >= 5:
            self.ctx.alias(E2E / 'e2e_wit.bend')
            return f'WT.len32({env["__e"]["o"]}, {pw - 5}n, {pw}n, {subj.d}n, {{==}}, {{==}}, {self.wz(subj.n, subj.d)})'
        if pw and re.search(r'Nat\.is_le\(O\.e8\(1n\+q\), \w+\.spec_common__pow2\(dw\)\)', p):
            return f'WT.eQ({pw - 5}n, {subj.d}n, {{==}})'
        return R


# ---------------------------------------------------------------- one name

def szr_term(syn, mod, pt, at_d):
    """the total-size premise {Nat.is_lt(SZR(U32.to_nat(F), t0, ..), pw(31n)) == True} with a large fixed part F:
    SZR adds on its first argument, so evaluating it walks F once per term; a lemma reassociates the sum to
    t0 + .. + tn + F first (F stays a U32 in the proof term)"""
    m = re.match(r'\{Nat\.is_lt\(SZR\((.*)\), VB\.pw\(31n\)\) == True\{\} : Bool\}$', pt, re.S)
    if not m:
        return None
    args = split_top(m.group(1))
    mf = re.match(r'U32\.to_nat\((\d+)\)$', args[0])
    if not mf or int(mf.group(1)) < BIG:
        return None
    ts = [f't{i}' for i in range(len(args) - 1)]
    S = ts[0]
    for t in ts[1:]:
        S = f'Nat.add({S}, {t})'
    F = 'U32.to_nat(x)'
    # A_k = add(..add(add(F, t0), t1).., tk) is add(F, S_k), by one reassociation per term
    lines = []
    Sk = [ts[0]]
    for t in ts[1:]:
        Sk.append(f'Nat.add({Sk[-1]}, {t})')
    for k in range(1, len(ts)):
        inner = f'_'
        ctx = inner
        for t in ts[k + 1:]:
            ctx = f'Nat.add({ctx}, {t})'
        lhs = f'Nat.add(Nat.add({F}, {Sk[k - 1]}), {ts[k]})'
        rhs = f'Nat.add({F}, {Sk[k]})'
        lines.append(f'  %Equal.sym(Nat, {lhs}, {rhs}, FD.nat__add_assoc({F}, {Sk[k - 1]}, {ts[k]})) : {{{ctx} == Nat.add({F}, {S}) : Nat}}')
    params = ', '.join(f'+{t}: Nat' for t in ts)
    nm = 'szr_sum'
    syn.lemmas['x000_' + nm] = (f'# SZR(F, t0, .., tn) = F + (t0 + .. + tn)\n'
                                f'def {nm}(+x: U32, {params}) -> {{BR.SZR({F}, {", ".join(ts)}) == Nat.add({F}, {S}) : Nat}}:\n'
                                + '\n'.join(lines) + '\n  {==}')
    syn.lemmas['x001_szr_lt'] = (f'def szr_lt(+x: U32, {params}, +h: {{Nat.is_lt(Nat.add({S}, {F}), VB.pw(31n)) == True{{}} : Bool}})\n'
                                 f'    -> {{Nat.is_lt(BR.SZR({F}, {", ".join(ts)}), VB.pw(31n)) == True{{}} : Bool}}:\n'
                                 f'  %Equal.sym(Nat, BR.SZR({F}, {", ".join(ts)}), Nat.add({F}, {S}), {nm}(x, {", ".join(ts)})) : {{Nat.is_lt(_, VB.pw(31n)) == True{{}} : Bool}}\n'
                                 f'  %Equal.sym(Nat, Nat.add({F}, {S}), Nat.add({S}, {F}), FD.nat__add_comm({F}, {S})) : {{Nat.is_lt(_, VB.pw(31n)) == True{{}} : Bool}}\n'
                                 f'  h')
    syn.ctx.alias(ROOT / 'proofs/obj/vbuf.bend')
    return f'szr_lt({mf.group(1)}, ' + ', '.join(at_d(a) for a in args[1:]) + ', {==})'


def law_files():
    """{law name: bridge file path} from e2e/manifest.json"""
    man = json.loads((E2E / 'manifest.json').read_text())
    return {l: E2E / f for f, es in man['files'].items() for e in es for l in e['laws']}


def params_of(d):
    k = d.index('(')
    depth, j = 0, k
    while True:
        c = d[j]
        if c in '([{':
            depth += 1
        elif c in ')]}':
            depth -= 1
            if depth == 0:
                break
        j += 1
    rest = d[j + 1:]
    a = rest.index('{')
    depth, e = 0, a
    while True:
        if rest[e] == '{':
            depth += 1
        elif rest[e] == '}':
            depth -= 1
            if depth == 0:
                break
        e += 1
    return split_top(d[k + 1:j]), rest[a:e + 1]


def premised(lf):
    """the names whose encode (i) or root (iv) bridge takes premises besides the object (and the buffer)"""
    out = []
    for l in sorted(lf):
        if not l.endswith('_e2e_encode'):
            continue
        n = l[:-len('_e2e_encode')]
        ep, _ = params_of(Mod.get(lf[l]).defs[l])
        rp, _ = params_of(Mod.get(lf[n + '_e2e_root']).defs[n + '_e2e_root'])
        if [x.lstrip('+-').split(':')[0].strip() for x in ep] != ['o'] or \
                [x.lstrip('+-').split(':')[0].strip() for x in rp] != ['h', 'o']:
            out.append(n)
    return out


def default_of(ctx, mod, otype, name):
    """(module, default call) of the object API's default object of the bridge's object type"""
    otype = otype.strip()
    a, _, tn = otype.rpartition('.')
    path = mod.imports.get(a) if a else mod.path
    if path is None or not re.search(r'types/\w+_def_generated\.bend$', str(path)):
        path = ROOT / f'types/{name}_def_generated.bend'
    tmod = Mod.get(path)
    for d in tmod.defs:
        if d.endswith('_default') and '_bx_' not in d:
            ps, ret, _ = tmod.signature(d)
            if not ps and ret.strip().split('.')[-1] == tn:
                return tmod, f'{d}()'
    if tn == 'U32':
        return None, '0'
    raise SystemExit(f'e2e_witness: no default {tn} in {Path(path).name}')


BRANCH_T = 'FD.array__Tree<U32>'


def build_branch(name, lf):
    """a branch type's bridges quantify over a perfect word tree t of depth dw: the zero tree of the least depth"""
    em = Mod.get(lf[f'{name}_e2e_encode'])
    rm = Mod.get(lf[f'{name}_e2e_root'])
    ctx = Ctx()
    PREFER.clear()
    for m_ in (em, rm):
        for a, pth in m_.imports.items():
            PREFER.setdefault(pth, a)
    PREFER[em.path], PREFER[rm.path] = 'BR', 'RB'
    ctx.alias(em.path)
    ctx.alias(rm.path)
    out = []
    for tag, mod, law, extra in (('', em, f'{name}_e2e_encode', ''), ('_root', rm, f'{name}_e2e_root', 'B.alloc(0), ')):
        ps, concl = params_of(mod.defs[law])
        cap = next(p for p in ps if p.lstrip('+').startswith('cap:'))
        k = int(re.search(r'O\.e8\((\d+)n\)', cap).group(1))
        dw = max(0, (8 * k - 1).bit_length())
        sub = {'t': f'FD.array__trep(U32, {dw}n, 0)', 'dw': f'{dw}n', 'h': 'B.alloc(0)'}
        c = ctx.lift(mod, concl)
        c = re.sub(r'(?<![\w.])(t|dw|h)(?=[),}])', lambda m: sub[m.group(1)], c)
        args = [sub['t'], sub['dw'], '{==}', f'FD.array__trep_perfect(U32, {dw}n, 0)', '{==}']
        out.append(f'def {name}_e2e_witness{tag}() -> {c}:\n  {"BR" if not tag else "RB"}.{law}({extra}{", ".join(args)})\n')
    ctx.alias(ROOT / 'src/buffer.bend')
    ctx.alias(ROOT / 'proofs/compact/found.bend')
    head = imports_text(ctx)
    return head + '\n\n' + HEADER + '\n' + (
        f'# Non-vacuity of the bridges of {name}: they quantify over a perfect word tree t of depth dw with\n'
        f'# room for the vector; the zero tree of the least such depth meets every premise.\n\n') + '\n'.join(out)


def build_u32(name, em, rm, eparams, econcl, rparams, rconcl, ctx, syn):
    """a bridge over a bare U32 object: the object 0, every premise computed"""
    BUF = ctx.alias(ROOT / 'src/buffer.bend') + '.alloc(0)'
    out = []
    for tag, mod, law, ps, concl, pre in (('', em, f'{name}_e2e_encode', eparams, econcl, ''),
                                          ('_root', rm, f'{name}_e2e_root', rparams, rconcl, BUF + ', ')):
        extra = [p_ for p_ in ps if p_.lstrip('+-').split(':')[0].strip() not in ('o', 'h')]
        if not extra:
            continue
        c = re.sub(r'(?<![\w.])o(?=[),])', '0', ctx.lift(mod, concl))
        c = re.sub(r'(?<![\w.])h(?=[),])', BUF, c)
        al = PREFER[mod.path]
        out.append(f'def {name}_e2e_witness{tag}() -> {c}:\n  {al}.{law}({pre}0, ' + ', '.join('{==}' for _ in extra) + ')\n')
    return imports_text(ctx) + '\n\n' + HEADER + '\n' + f'# Non-vacuity of the bridges of {name} that take premises: they hold of the object 0.\n\n' + '\n'.join(out)


def imports_text(ctx):
    lines = ['import Base']
    for a, pth in sorted(ctx.used.items(), key=lambda x: x[1].relative_to(ROOT).as_posix()):
        rel = pth.relative_to(E2E).as_posix() if pth.parent == E2E else (Path('..') / pth.relative_to(ROOT)).as_posix()
        if pth.parent == E2E:
            rel = './' + rel
        lines.append(f'import {rel} as {a}')
    return '\n'.join(lines)


# premised names whose witness the pinned checker cannot evaluate (with the reason); e2e/WITNESS.txt lists them
PENDING = {}
# names whose default-object witness checks but whose non-empty one is not synthesized (the progressive
# lists' element premises, nested progressive containers): the default witness only
NO_NE = {'ProgressiveTestStruct', 'ProgressiveComplexTestStruct'}


def build(name, lf=None):
    lf = lf or law_files()
    if name in PENDING:
        raise SystemExit(PENDING[name])
    em = Mod.get(lf[f'{name}_e2e_encode'])
    rm = Mod.get(lf[f'{name}_e2e_root'])
    ed, rd = em.defs[f'{name}_e2e_encode'], rm.defs[f'{name}_e2e_root']
    eparams, econcl = params_of(ed)
    rparams, rconcl = params_of(rd)
    if eparams[0].lstrip('+-').split(':')[0].strip() != 'o':
        return build_branch(name, lf)
    PREFER.clear()
    PREFER[em.path] = 'BR'
    if rm.path != em.path:
        PREFER[rm.path] = 'RB'
    taken = {'BR', 'RB', 'WT'}
    for m_ in (em, rm):
        for a, pth in m_.imports.items():
            if pth not in PREFER and a not in taken:
                PREFER[pth] = a
                taken.add(a)
    PREFER[(E2E / 'e2e_wit.bend').resolve()] = 'WT'
    ctx = Ctx()
    ctx.alias(em.path)
    ctx.alias(rm.path)
    RBA = PREFER[rm.path]
    syn = Synth(ctx)
    otype = eparams[0].lstrip('+-').split(':', 1)[1]
    tmod, dflt = default_of(ctx, em, otype, name)
    if tmod is None:            # a bare U32 (FuluParticipationFlags): the literal 0
        return build_u32(name, em, rm, eparams, econcl, rparams, rconcl, ctx, syn)
    dmod_alias = ctx.alias(tmod.path)
    D = f'{dmod_alias}.{dflt}'
    BUF = ctx.alias(ROOT / 'src/buffer.bend') + '.alloc(0)'
    enc_prem = len(eparams) > 1
    root_prem = len(rparams) > 2

    def subst_obj(mod, t, obj):
        t = ctx.lift(mod, t)
        t = re.sub(r'(?<![\w.])o(?=[),])', obj, t)
        return re.sub(r'(?<![\w.])h(?=[),])', BUF, t)

    def prove_all(mod, params, obj, model, prefix):
        env = {'o': model}
        out = []
        for p_ in params:
            pn, pt = p_.lstrip('+-').split(':', 1)
            pn = pn.strip()
            if pn in ('o', 'h'):
                continue
            env['__subj'] = None
            term = szr_term(syn, mod, pt.strip(), lambda t: subst_obj(mod, t, obj)) or syn.prove(mod, pt, env)
            out.append((f'{prefix}{pn}', subst_obj(mod, pt.strip(), obj), term))
        return out

    obj = model_ne(ctx, tmod, dflt, lists=False)
    dv_expr = None
    if getattr(obj, 'changed', False):       # the default holds empty boxes where a vector needs values: DV()
        dv_expr, obj.expr, D = obj.expr, 'DV()', 'DV()'
    else:
        obj = model_of(ctx, tmod, dflt)
    sections = []   # (premises, witness name, conclusion, application)
    if enc_prem:
        pr = prove_all(em, eparams, D, obj, 'premise_')
        sections.append((pr, f'{name}_e2e_witness', subst_obj(em, econcl, D),
                         f'BR.{name}_e2e_encode({D}, ' + ', '.join(f'{p}()' for p, _, _ in pr) + ')'))
    if root_prem:
        pr = prove_all(rm, rparams, D, obj, 'premise_root_')
        sections.append((pr, f'{name}_e2e_witness_root', subst_obj(rm, rconcl, D),
                         f'{RBA}.{name}_e2e_root({BUF}, {D}, ' + ', '.join(f'{p}()' for p, _, _ in pr) + ')'))
    # the same bridges at the non-empty object NE() (one element in every list), when there are lists
    ne_expr, tyname = None, f'{dmod_alias}.{tmod.signature(dflt[:-2])[1].strip()}'
    try:
        if name in NO_NE:
            raise SystemExit('no non-empty witness')
        ne = model_ne(ctx, tmod, dflt)
        if getattr(ne, 'changed', False):
            ne_expr = ne.expr
            ne.expr = 'NE()'
            nes = []
            if enc_prem:
                pr = prove_all(em, eparams, 'NE()', ne, 'premise_ne_')
                nes.append((pr, f'{name}_e2e_witness_nonempty', subst_obj(em, econcl, 'NE()'),
                            f'BR.{name}_e2e_encode(NE(), ' + ', '.join(f'{p}()' for p, _, _ in pr) + ')'))
            if root_prem:
                ne2 = model_ne(ctx, tmod, dflt)
                ne2.expr = 'NE()'
                pr = prove_all(rm, rparams, 'NE()', ne2, 'premise_ne_root_')
                nes.append((pr, f'{name}_e2e_witness_root_nonempty', subst_obj(rm, rconcl, 'NE()'),
                            f'{RBA}.{name}_e2e_root({BUF}, NE(), ' + ', '.join(f'{p}()' for p, _, _ in pr) + ')'))
            sections += nes
    except SystemExit:
        ne_expr = None
        sections = [s_ for s_ in sections if 'NE()' not in s_[3]]
    ctx.alias(ROOT / 'src/obj.bend')
    ctx.alias(ROOT / 'proofs/compact/found.bend')
    X = dflt[:-2]
    txt = imports_text(ctx) + '\n\n' + HEADER + '\n'
    txt += (f'# Non-vacuity of the bridges of {name} that take premises: every premise holds of the default object\n'
            f'# D = {X}() (one def per premise, named after its binder), so the bridge applies to D.\n\n')
    if dv_expr:
        txt += (f'# DV() is the default with valid elements in its vectors of boxed values (the default\'s are empty)\n'
                f'def DV() -> {tyname}:\n  {dv_expr}\n\n')
    if ne_expr:
        # NE() first: a def is unfolded only after it is declared, and the lemmas mention NE()
        txt += (f'# NE() is the default with one element in every list reachable through containers and boxes\n'
                f'# (the witnesses named _nonempty).\n'
                f'def NE() -> {tyname}:\n  {ne_expr}\n\n')
    for nm in sorted(syn.lemmas):
        txt += syn.lemmas[nm] + '\n\n'
    seen = {}
    for k_, (pr, wn, concl, app) in enumerate(sections):
        if k_ and ('NE()' in app) != ('NE()' in sections[k_ - 1][3]):
            txt += '# The same bridges at the non-empty object NE(): every premise is proved of NE().\n\n'
        for pn, pt, term in pr:
            if pt in seen:          # the same premise as an earlier bridge's: reuse its def
                app = app.replace(f'{pn}()', f'{seen[pt]}()')
                continue
            seen[pt] = pn
            txt += f'def {pn}() -> {pt}:\n  {term}\n\n'
        txt += f'def {wn}() -> {concl}:\n  {app}\n\n'
    return txt.rstrip('\n') + '\n'


def main():
    check = '--check' in sys.argv
    only = None
    if '--only' in sys.argv:
        only = sys.argv[sys.argv.index('--only') + 1].split(',')
    outs = {E2E / 'e2e_wit.bend': SUPPORT}
    lf = law_files()
    rows = []
    for n in premised(lf):
        if only and n not in only:
            continue
        Mod.cache.clear()
        try:
            outs[E2E / f'{n}_e2e_witness_generated.bend'] = build(n, lf)
            rows.append(f'{n}\twitnessed')
        except SystemExit as e:
            rows.append(f'{n}\tpending: {str(e).replace(chr(10), " ")[:200]}')
    if not only:
        done = sum(1 for r in rows if r.endswith('\twitnessed'))
        outs[E2E / 'WITNESS.txt'] = (f'# GENERATED by codegen/e2e_witness.py. Do not edit.\n# {done} of {len(rows)} names whose encode or root '
                                     f'bridge takes premises have a checked witness (e2e/<Name>_e2e_witness_generated.bend)\n'
                                     + '\n'.join(rows) + '\n')
    stale = []
    for p, t in outs.items():
        if not p.exists() or p.read_text() != t:
            stale.append(p.name)
            if not check:
                p.write_text(t)
    if not only:
        have = {p.name for p in E2E.glob('*_e2e_witness_generated.bend')}
        orphans = sorted(have - {p.name for p in outs})
        for o in orphans:
            if check:
                stale.append(o + ' (orphan)')
            else:
                (E2E / o).unlink()
    if check:
        if stale:
            print('stale: ' + ', '.join(stale))
            sys.exit(1)
        print(f'e2e_witness: {len(outs)} witnesses up to date')
    else:
        print(f'e2e_witness: wrote {len(stale)} of {len(outs)}')


if __name__ == '__main__':
    main()
