#!/usr/bin/env python3
"""e2e/e2e_hpl_pl_VarTestStruct.bend: the element hooks of a pl_VarTestStruct window (a progressive list of VarTestStruct records, read at a byte window:
vvl_pl_VarTestStruct, e2e_dvp_pl_VarTestStruct.bend: D) as an element of pl_pl_VarTestStruct (e2e_dvp_pl_pl_VarTestStruct.bend), in the root_gtypes2_light
mirrors (RT = RT2 of e2e_encld.bend). The element at the window (x, off, len) (V.OBJw; Seq the pl_VarTestStruct_Seq object) has, with
WF = eo, hd, hw, hw32, pfw, h31 (h31: the element window is shorter than 2^31 bytes; e2e_dvp.py's H31 lists derive it for each element):

    repT(d, t, x, off, len, hchk, WF, sE, ee)     RT.rep_pl_VarTestStruct_bx(th_bx(MSome{fz(Seq)}), sE)
    sde(d, t, x, off, len, hchk, WF)              EL.EPB_pl_pl_VarTestStruct(MSome{fz(Seq)})
    sz(d, t, x, off, len, hchk, WF)               the encoder's bytes of the element are the window's: length(XB.YE(EL.fbx_pl_pl_VarTestStruct(MSome{fz(Seq)}))) == len
    canon(d, t, x, off, len, hchk, WF)            th_bx(MSome{fz(Seq)}) == BSome{Seq, BNone}

The lemmas are D's: rep, sdl (the encode premise PRV), szl (the encoder's byte count LNQ) and thfz (freezing then thawing the object gives it back);
the only new ones are that EP_pl_VarTestStruct(fz(o)) is PRV_pl_VarTestStruct(o) and that the encoder's bytes of fz(o) are LNQ(o) long (len_encl).

Usage: python3 codegen/e2e_hpl.py [--check]"""
import sys
from pathlib import Path

import e2e_dvv2 as DV2

ROOT = Path(__file__).resolve().parent.parent
E2E = ROOT / 'e2e'
WIN = DV2.WIN
H31T = '+h31: {Nat.is_lt(U32.to_nat(len), VB.pw(31n)) == True{} : Bool}'
WF_SIG = DV2.WF_SIG + ', ' + H31T
WF_ARG = DV2.WF_ARG


def text():
    imports = ['import Base', 'import ../src/obj.bend as O', 'import ../types/schema.bend as S', 'import ../proofs/obj/generic_specs.bend as Spec',
               'import ../types/proglist_VarTestStruct_def_generated.bend as proglist_VarTestStruct_d', 'import ../proofs/compact/found.bend as FD',
               'import ../proofs/compact/arith.bend as A', 'import ../proofs/obj/vbuf.bend as VB', 'import ../proofs/obj/schema_shapes.bend as SH',
               'import ../proofs/obj/root_gtypes2_light.bend as RT', 'import ../proofs/obj/vvl_pl_VarTestStruct.bend as V', 'import ./e2e_dvp_pl_VarTestStruct.bend as D',
               'import ./e2e_encld.bend as EL', 'import ../proofs/obj/encx_pl_VarTestStruct.bend as XA', 'import ../proofs/obj/encx_pl_pl_VarTestStruct.bend as XB']
    SEQ = 'proglist_VarTestStruct_d.pl_VarTestStruct_Seq'
    OW = 'V.OBJw(d, t, x, off, len)'
    FZ = f'RT.fz_pl_VarTestStruct({OW})'
    TH = f'RT.th_pl_VarTestStruct({FZ})'
    HCK = '+hchk: {V.CHKw(t, x, off, len) == True{} : Bool}'
    SCH = 'S.ProgressiveList{Spec.VarTestStruct()}'
    DW = 'd, t, x, off, len, eo, hd, hw, hw32, pfw'
    o = []
    A_ = o.append
    A_('\n'.join(imports))
    A_('')
    A_('# GENERATED by codegen/e2e_hpl.py. Do not edit.')
    A_('# The hooks of a pl_VarTestStruct window as an element of pl_pl_VarTestStruct (root_gtypes2_light mirrors): see the generator.')
    A_('')
    A_(f'# the premise of the frozen list is the encode premise of the list')
    A_(f'def epfz(o: {SEQ}, +h: EL.PRV_pl_VarTestStruct(o)) -> EL.EP_pl_VarTestStruct(RT.fz_pl_VarTestStruct(o)):\n'
       f'  match o:\n    case {SEQ}{{arr, +n}}: h')
    A_('')
    A_(f'# the encoder\'s bytes of the frozen list are the list\'s byte count\n'
       f'def szo(o: {SEQ}) -> {{List.length(&2, U32, XB.YE(EL.fbx_pl_pl_VarTestStruct(RT.MSome{{RT.fz_pl_VarTestStruct(o)}}))) == D.LNQ(o) : Nat}}:\n'
       f'  match o:\n    case {SEQ}{{arr, +n}}: XA.len_encl(EL.TM_pl_VarTestStruct(RT.tfz_pl_VarTestStruct(arr)), n)')
    A_('')
    A_('# the element schema of the list schema')
    A_(f'def ees(+sE: S.Schema, +ee: {{sE == {SCH} : S.Schema}}) -> {{SH.ProgressiveList_element(sE) == Spec.VarTestStruct() : S.Schema}}:\n'
       f'  FD.logic__subst(S.Schema, z => {{SH.ProgressiveList_element(z) == Spec.VarTestStruct() : S.Schema}}, {SCH}, sE, Equal.sym(S.Schema, sE, {SCH}, ee), {{==}})')
    A_('')
    A_('# ---- the hooks ----')
    A_(f'def repT({WIN}, {HCK}, {WF_SIG}, +sE: S.Schema, +ee: {{sE == {SCH} : S.Schema}})\n'
       f'    -> RT.rep_pl_VarTestStruct_bx(RT.th_pl_VarTestStruct_bx(RT.MSome{{{FZ}}}), sE):\n'
       f'  ({{==}}, FD.logic__subst({SEQ}, z => RT.rep_pl_VarTestStruct(z, sE), {OW}, {TH}, Equal.sym({SEQ}, {TH}, {OW}, D.thfz(d, t, x, off, len, {WF_ARG}, hchk)),\n'
       f'    D.rep({DW}, sE, ees(sE, ee), hchk)))')
    A_('')
    A_(f'def sde({WIN}, {HCK}, {WF_SIG}) -> EL.EPB_pl_pl_VarTestStruct(RT.MSome{{{FZ}}}):\n  epfz({OW}, D.sdl({DW}, h31, hchk))')
    A_('')
    A_(f'def canon({WIN}, {HCK}, {WF_SIG}) -> {{RT.th_pl_VarTestStruct_bx(RT.MSome{{{FZ}}}) == O.BSome{{{OW}, O.BNone{{}}}} : O.Boxed<{SEQ}>}}:\n'
       f'  Equal.cong({SEQ}, O.Boxed<{SEQ}>, z => O.BSome{{z, O.BNone{{}}}}, {TH}, {OW}, D.thfz(d, t, x, off, len, {WF_ARG}, hchk))')
    A_('')
    A_(f'def sz({WIN}, {HCK}, {WF_SIG})\n    -> {{List.length(&2, U32, XB.YE(EL.fbx_pl_pl_VarTestStruct(RT.MSome{{{FZ}}}))) == U32.to_nat(len) : Nat}}:\n'
       f'  Equal.trans(Nat, List.length(&2, U32, XB.YE(EL.fbx_pl_pl_VarTestStruct(RT.MSome{{{FZ}}}))), D.LNQ({OW}), U32.to_nat(len), szo({OW}), D.szl({DW}, hchk))')
    return '\n'.join(o) + '\n'


def main():
    p = E2E / 'e2e_hpl_pl_VarTestStruct.bend'
    t = text()
    if '--check' in sys.argv:
        if not p.exists() or p.read_text() != t:
            print('stale: ' + p.name)
            sys.exit(1)
        print('e2e_hpl: up to date')
        return
    if not p.exists() or p.read_text() != t:
        p.write_text(t)
    print('e2e_hpl: 1 file')


if __name__ == '__main__':
    main()
