#!/usr/bin/env python3
"""Non-vacuity witnesses for the encode (i) bridges: e2e/<Name>_e2e_witness_generated.bend.

For each name in NAMES, one checked def applies the name's encode bridge
(<Name>_e2e_encode of e2e/<Name>_e2e_generated.bend) to the object API's default object
<Name>_default(), with every premise of the bridge (rep and each storage, size and budget premise)
proved of that object. So the bridge's premises are jointly satisfiable and its conclusion holds
of at least one object: the bridge is not vacuous.

The premise proofs are synthesized from the premise predicates' own definitions (read from the
modules the bridge imports): a predicate is a nest of DK.Ex / DK.P2 / DK.Or2 over equalities; the
existential witnesses come from the default object (a field's default value; a zero-filled word
array words_new(n) is thaw(trep(d, 0)) at its depth d, by found.array__new; an empty list is one
leaf of depth 0), and every equality is closed by computation ({==}), except the word-array
equation (the per-size lemma WZ<n>) and a word tree's perfectness (found.array__trep_perfect).

    python3 codegen/e2e_witness.py            # write
    python3 codegen/e2e_witness.py --check    # nonzero exit if any output is stale
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
E2E = ROOT / 'e2e'

# the names whose encode bridge carries premises beyond rep
NAMES = ['FuluExecutionPayload', 'FuluExecutionPayloadHeader', 'FuluExecutionRequests', 'FuluDataColumnSidecar',
         'FuluLightClientHeader', 'FuluLightClientBootstrap', 'FuluLightClientOptimisticUpdate',
         'FuluLightClientFinalityUpdate', 'FuluLightClientUpdate',
         'FuluBeaconBlockBody', 'FuluBeaconBlock', 'FuluSignedBeaconBlock', 'FuluBeaconState']

R = '{==}'

SUPPORT = '''import Base
import ../src/obj.bend as O
import ../proofs/compact/found.bend as FD
import ../proofs/obj/words_spec.bend as WS
import ../proofs/obj/words_obj_light.bend as WO
import ../proofs/obj/packed_obj_light.bend as PK

# GENERATED by codegen/e2e_witness.py. Do not edit.
# Arithmetic for the non-vacuity witnesses (e2e/<Name>_e2e_witness_generated.bend) of large zero-filled word
# arrays: n = 2^b bytes of 2^c chunks (b = c + 5), stated with c symbolic so that no unary 2^b is ever compared.

def sp(+x: Nat, +h: {Nat.is_le(1n, x) == True{} : Bool}) -> {1n+FD.nat__pred(x) == x : Nat}:
  match x:
    case 0n: Empty.absurd({1n+FD.nat__pred(0n) == 0n : Nat}, FD.logic__false_true(h))
    case 1n+p: {==}

# the chunk count minus one, as the witness q of a vector's length equation
def QP(+c: Nat) -> Nat: FD.nat__pred(FD.spec_common__pow2(c))

def q1(+c: Nat) -> {1n+QP(c) == FD.spec_common__pow2(c) : Nat}: sp(FD.spec_common__pow2(c), FD.nat__pow2_pos(c))

# 32 (q + 1) = 2^b
def eN(+c: Nat, +b: Nat, +eb: {Nat.add(5n, c) == b : Nat}, +N: U32, +hN: {U32.to_nat(N) == FD.spec_common__pow2(b) : Nat})
    -> {U32.to_nat(N) == Nat.add(WS.e32(QP(c)), 32n) : Nat}:
  %FD.nat__add_comm(32n, WS.e32(QP(c))) : {U32.to_nat(N) == _ : Nat}
  %Equal.sym(Nat, 1n+QP(c), FD.spec_common__pow2(c), q1(c)) : {U32.to_nat(N) == WS.e32(_) : Nat}
  %Equal.sym(Nat, Nat.add(5n, c), b, eb) : {U32.to_nat(N) == FD.spec_common__pow2(_) : Nat}
  hN

# 8 (q + 1) words fit in 2^d, d >= c + 3
def eQ(+c: Nat, +d: Nat, +hd: {Nat.is_le(Nat.add(3n, c), d) == True{} : Bool}) -> {Nat.is_le(O.e8(1n+QP(c)), FD.spec_common__pow2(d)) == True{} : Bool}:
  %Equal.sym(Nat, 1n+QP(c), FD.spec_common__pow2(c), q1(c)) : {Nat.is_le(O.e8(_), FD.spec_common__pow2(d)) == True{} : Bool}
  FD.nat__pow2_mono(Nat.add(3n, c), d, hd)

# shifting 2^(3 + a) right by 3 gives 2^a
def shr3(+a: Nat, +h: {Nat.is_lt(3n+a, 32n) == True{} : Bool}) -> {U32.shrn(FD.u32__pow2u(3n+a), 3n) == FD.u32__pow2u(a) : U32}:
  %Equal.sym(U32, U32.shr(FD.u32__pow2u(3n+a)), FD.u32__pow2u(2n+a), FD.u32__shr_pow2u(2n+a, h)) : {U32.shr(U32.shr(_)) == FD.u32__pow2u(a) : U32}
  %Equal.sym(U32, U32.shr(FD.u32__pow2u(2n+a)), FD.u32__pow2u(1n+a), FD.u32__shr_pow2u(1n+a, FD.nat__lt_trans(2n+a, 3n+a, 32n, FD.nat__lt_succ(2n+a), h))) : {U32.shr(_) == FD.u32__pow2u(a) : U32}
  FD.u32__shr_pow2u(a, FD.nat__lt_trans(1n+a, 3n+a, 32n, FD.nat__lt_trans(1n+a, 2n+a, 3n+a, FD.nat__lt_succ(1n+a), FD.nat__lt_succ(2n+a)), h))

# a zero array of 2^b = 8 * 2^a bytes holds a whole number of 8-byte elements (packed_obj_light.rep_v8's count)
def len8(-w: O.Words, +a: Nat, +b: Nat, +d: Nat, +eb: {3n+a == b : Nat}, +hb: {Nat.is_lt(b, 32n) == True{} : Bool},
    +ew: {w == O.Words{FD.array__thaw(U32, FD.array__trep(U32, d, 0)), FD.u32__pow2u(b)} : O.Words})
    -> {U32.to_nat(WO.len(w)) == PK.e8(PK.cnt8(w)) : Nat}:
  %Equal.sym(O.Words, w, O.Words{FD.array__thaw(U32, FD.array__trep(U32, d, 0)), FD.u32__pow2u(b)}, ew) : {U32.to_nat(WO.len(_)) == PK.e8(PK.cnt8(w)) : Nat}
  %Equal.sym(O.Words, w, O.Words{FD.array__thaw(U32, FD.array__trep(U32, d, 0)), FD.u32__pow2u(b)}, ew) : {U32.to_nat(FD.u32__pow2u(b)) == PK.e8(PK.cnt8(_)) : Nat}
  %Equal.sym(Nat, b, 3n+a, Equal.sym(Nat, 3n+a, b, eb)) : {U32.to_nat(FD.u32__pow2u(_)) == PK.e8(U32.to_nat(U32.shrn(FD.u32__pow2u(_), 3n))) : Nat}
  %Equal.sym(U32, U32.shrn(FD.u32__pow2u(3n+a), 3n), FD.u32__pow2u(a), shr3(a, FD.logic__subst(Nat, z => {Nat.is_lt(z, 32n) == True{} : Bool}, b, 3n+a, Equal.sym(Nat, 3n+a, b, eb), hb))) : {U32.to_nat(FD.u32__pow2u(3n+a)) == PK.e8(U32.to_nat(_)) : Nat}
  %Equal.sym(Nat, U32.to_nat(FD.u32__pow2u(3n+a)), FD.spec_common__pow2(3n+a), FD.u32__pow2u_value(3n+a, FD.logic__subst(Nat, z => {Nat.is_lt(z, 32n) == True{} : Bool}, b, 3n+a, Equal.sym(Nat, 3n+a, b, eb), hb))) : {_ == PK.e8(U32.to_nat(FD.u32__pow2u(a))) : Nat}
  %Equal.sym(Nat, U32.to_nat(FD.u32__pow2u(a)), FD.spec_common__pow2(a), FD.u32__pow2u_value(a, FD.nat__lt_trans(a, 3n+a, 32n, FD.nat__lt_trans(a, 2n+a, 3n+a, FD.nat__lt_trans(a, 1n+a, 2n+a, FD.nat__lt_succ(a), FD.nat__lt_succ(1n+a)), FD.nat__lt_succ(2n+a)), FD.logic__subst(Nat, z => {Nat.is_lt(z, 32n) == True{} : Bool}, b, 3n+a, Equal.sym(Nat, 3n+a, b, eb), hb)))) : {FD.spec_common__pow2(3n+a) == PK.e8(_) : Nat}
  {==}
'''
HEADER = '# GENERATED by codegen/e2e_witness.py. Do not edit.'


# ---------------------------------------------------------------- Bend source reading

class Mod:
    cache = {}

    def __init__(self, path):
        self.path = path.resolve()
        self.text = self.path.read_text()
        self.imports = {}
        for m in re.finditer(r'^import (\S+) as (\w+)$', self.text, re.M):
            self.imports[m.group(2)] = (self.path.parent / m.group(1)).resolve()
        self.defs = {}
        lines = self.text.split('\n')
        i = 0
        while i < len(lines):
            l = lines[i]
            m = re.match(r'def (\w+)\(', l)
            if m:
                j = i + 1
                while j < len(lines) and (lines[j].startswith(' ') or lines[j] == ''):
                    j += 1
                self.defs[m.group(1)] = '\n'.join(lines[i:j]).rstrip()
                i = j
            else:
                i += 1

    @classmethod
    def get(cls, path):
        path = Path(path).resolve()
        if path not in cls.cache:
            cls.cache[path] = Mod(path)
        return cls.cache[path]

    def resolve(self, qname):
        """(module, name) of a qualified or bare function name as written in this module"""
        if '.' in qname:
            a, n = qname.split('.', 1)
            if a in self.imports:
                return Mod.get(self.imports[a]), n
            return None, qname
        return self, qname

    def signature(self, name):
        """(param names, return type text, body text) of a def"""
        d = self.defs[name]
        k = d.index('(')
        depth, j = 0, k
        while True:
            c = d[j]
            if c in '([{':
                depth += 1
            elif c in ')]}':
                depth -= 1
                if depth == 0:
                    break
            j += 1
        self.fullp = [p.strip() for p in split_top(d[k + 1:j])]
        params = [p.strip().lstrip('+-').split(':')[0].strip() for p in split_top(d[k + 1:j])]
        rest = d[j + 1:]
        m = re.match(r'\s*->\s*', rest)
        rest = rest[m.end():]
        # the return type ends at the first top-level ':' followed by a newline or a space
        depth, q = 0, 0
        while q < len(rest):
            c = rest[q]
            if c in '([{<':
                depth += 1
            elif c in ')]}>' and not (c == '>' and q and rest[q - 1] in '=-'):
                depth -= 1
            elif c == ':' and depth == 0:
                break
            q += 1
        return params, rest[:q].strip(), rest[q + 1:].strip()


def split_top(s):
    """split on commas at depth 0 of ( [ { and type application < >"""
    out, depth, cur, i = [], 0, [], 0
    while i < len(s):
        c = s[i]
        if c in '([{':
            depth += 1
        elif c in ')]}':
            depth -= 1
        elif c == '<' and i and (s[i - 1].isalnum() or s[i - 1] == '_'):
            depth += 1
        elif c == '>' and depth > 0 and s[i - 1] not in '=-' and s[i - 1] != ' ':
            depth -= 1
        if c == ',' and depth == 0:
            out.append(''.join(cur).strip())
            cur = []
        else:
            cur.append(c)
        i += 1
    if ''.join(cur).strip():
        out.append(''.join(cur).strip())
    return out


def parse_call(e):
    """(fn, [args]) of 'fn(args)' when e is exactly one call, else None"""
    e = e.strip()
    m = re.match(r'([\w.]+)\(', e)
    if not m:
        return None
    depth = 0
    for i in range(m.end() - 1, len(e)):
        c = e[i]
        if c in '([{':
            depth += 1
        elif c in ')]}':
            depth -= 1
            if depth == 0:
                if i != len(e) - 1:
                    return None
                return m.group(1), split_top(e[m.end():i])
    return None


# ---------------------------------------------------------------- the default object's model

BIG = 16384


def pow2_of(n):
    """b when n = 2^b is a large power of two (a word array whose arithmetic must stay symbolic)"""
    if n >= BIG and n & (n - 1) == 0:
        return n.bit_length() - 1
    return None


def words_depth(n):
    w = ((n + 31) // 32) * 8 + 8
    return (w - 1).bit_length()


class Words:
    def __init__(self, n):
        self.n, self.d = n, words_depth(n)


class EList:
    def __init__(self, fill):
        self.fill = fill


class Cont:
    def __init__(self, mod, tname, fields):
        self.mod, self.tname, self.fields = mod, tname, fields   # fields: [(default expr in canon aliases, model)]


class Box:
    def __init__(self, inner, expr):
        self.inner, self.iexpr = inner, expr


class Leaf:
    def __init__(self, expr):
        self.expr = expr


PREFER = {}   # path -> the alias the bridge file gives it


def canon(path):
    p = Path(path).resolve()
    if p in PREFER:
        return PREFER[p]
    rel = p.relative_to(ROOT).as_posix()
    m = re.match(r'types/(\w+)_def_generated\.bend$', rel)
    if m:
        return m.group(1) + '_d'
    return 'W_' + re.sub(r'\W', '_', rel[:-len('.bend')])


class Ctx:
    """the imports the witness file needs, by canonical alias"""

    def __init__(self):
        self.used = {}

    def alias(self, path):
        a = canon(path)
        self.used[a] = Path(path).resolve()
        return a

    def lift(self, mod, expr):
        """an expression of module mod, with its aliases made canonical (bare names of mod qualified)"""
        def sub(m):
            q = m.group(0)
            if '.' in q:
                a, rest = q.split('.', 1)
                if a in mod.imports:
                    return self.alias(mod.imports[a]) + '.' + rest
                return q
            if q in mod.defs or re.search(r'^type ' + re.escape(q) + r'\b', mod.text, re.M) or \
                    re.search(r'^  ' + re.escape(q) + r'\{', mod.text, re.M):
                return self.alias(mod.path) + '.' + q
            return q
        return re.sub(r'(?<![\w.])[A-Za-z_]\w*(?:\.\w+)?', sub, expr)


def model_of(ctx, mod, expr):
    """the model of a default-valued expression written in module mod (its .expr: the expression, lifted)"""
    m = model_of_(ctx, mod, expr)
    m.expr = ctx.lift(mod, expr)
    return m


def model_of_(ctx, mod, expr):
    c = parse_call(expr)
    if c is None:
        raise SystemExit(f'e2e_witness: no model for {expr!r} ({mod.path.name})')
    fn, args = c
    if fn == 'O.words_new':
        return Words(int(args[0]))
    m2, name = mod.resolve(fn)
    if m2 is None or name not in m2.defs:
        raise SystemExit(f'e2e_witness: no def {fn} ({mod.path.name})')
    params, ret, body = m2.signature(name)
    if params:
        raise SystemExit(f'e2e_witness: default with params {fn}')
    b = body.strip()
    if b.startswith('O.words_new('):
        return Words(int(parse_call(b)[1][0]))
    mb = parse_call(b)
    if mb and mb[0].endswith('_bx_wrap'):
        return Box(model_of(ctx, m2, mb[1][0]), ctx.lift(m2, mb[1][0]))
    ms = re.match(r'(\w+)\{(.*)\}$', b, re.S)
    if ms and ms.group(1).endswith('_Seq'):
        items = split_top(ms.group(2))
        if items[1].strip() != '0':
            raise SystemExit(f'e2e_witness: nonempty default list {fn}')
        return EList((m2, items[0]))
    if ms and all(parse_call(a) for a in split_top(ms.group(2))):
        fields = []
        for a in split_top(ms.group(2)):
            sub = model_of(ctx, m2, a)
            if isinstance(sub, Cont) and sub.tname.startswith(ms.group(1) + '_g'):
                fields.extend(sub.fields)      # a group of a grouped container
            else:
                fields.append((ctx.lift(m2, a), sub))
        return Cont(m2, ms.group(1), fields)
    return Leaf(ctx.lift(m2, b))


# ---------------------------------------------------------------- premise synthesis

class Synth:
    def __init__(self, ctx):
        self.ctx = ctx
        self.lemmas = {}
        self.named = {}

    def wz(self, n, d):
        nm = f'WZ{n}'
        self.lemmas[nm] = (f'def {nm}() -> {{O.words_new({n}) == O.Words{{FD.array__thaw(U32, FD.array__trep(U32, {d}n, 0)), {n}}} : O.Words}}:\n'
                           f'  %FD.array__new(U32, {d}n, 0) : {{O.words_new({n}) == O.Words{{_, {n}}} : O.Words}}\n'
                           f'  {{==}}')
        return f'{nm}()'

    def arg_model(self, e, env):
        """the model of an argument expression: a variable of env, or projections of one"""
        e = e.strip()
        if e in env:
            return env[e]
        c = parse_call(e)
        if c is None:
            return None
        fn, args = c
        base = fn.split('.')[-1]
        inner = self.arg_model(args[0], env) if args else None
        if inner is None:
            return None
        m = re.match(r'pj_\w+_(\d+)$', base)
        if m and isinstance(inner, Cont):
            return inner.fields[int(m.group(1))][1]
        if re.match(r'pjb_\w+_bx$', base) and isinstance(inner, Box):
            return inner.inner
        return None

    def prove(self, mod, pred, env):
        """a proof term of the Data predicate text pred (written in mod), with its variables' models in env"""
        p = pred.strip()
        if p.startswith('{'):
            return self.eq(p, env)
        c = parse_call(p)
        if c is None:
            raise SystemExit(f'e2e_witness: cannot read {p[:120]!r}')
        fn, args = c
        base = fn.split('.')[-1]
        m2, name = mod.resolve(fn)
        if (m2 is not None and m2.path.name == 'dk.bend') or fn in ('Ex', 'P2', 'Or2'):
            if base == 'Ex':
                lam = args[1]
                mv = re.match(r'(\w+)\s*=>\s*', lam, re.S)
                v = mv.group(1)
                wit = self.witness(mod, args[0], v, lam[mv.end():], env)
                env2 = dict(env)
                env2[v] = ('val', wit)
                return f'({wit}, {self.prove(mod, lam[mv.end():], env2)})'
            if base == 'P2':
                return f'({self.prove(mod, args[0], env)}, {self.prove(mod, args[1], env)})'
            if base == 'Or2':
                subj = env.get('__subj')
                if isinstance(subj, Words) and subj.n == 0:
                    return f'Inl{{{self.prove(mod, args[0], env)}}}'
                return f'Inr{{{self.prove(mod, args[1], env)}}}'
        if m2 is None or name not in m2.defs:
            raise SystemExit(f'e2e_witness: no def {fn} ({mod.path.name})')
        params, ret, body = m2.signature(name)
        if body.startswith('match'):
            return R     # an element-wise premise over zero elements: {True{} == True{}}
        env2 = {'__e': {}}
        for pn, a in zip(params, args):
            mdl = self.arg_model(a, env)
            if mdl is not None:
                env2[pn] = mdl
            env2['__e'][pn] = self.subst(mod, a, env)
        if params and params[0] in env2:
            env2['__subj'] = env2[params[0]]
        elif '__subj' in env:
            env2['__subj'] = env['__subj']
        subj = env2.get('__subj')
        full = list(m2.fullp)
        if isinstance(subj, Words) and pow2_of(subj.n) and params and params[0] in env2 \
                and re.match(r'DK\.Ex\(\w+\.array__Tree<U32>, t =>', body):
            return self.leaf(m2, name, full, params, body, env2, subj)
        if isinstance(subj, Words) and subj.n >= BIG and params and params[0] in env2:
            # a large word array: its own lemma, so that a failure is located and nothing is inlined twice
            ty = f'{self.ctx.alias(m2.path)}.{name}(' + ', '.join(env2['__e'][pn] for pn in params) + ')'
            key = ty
            if key not in self.named:
                term = self.prove(m2, body, env2)
                nm = f'big{len(self.named)}'
                self.named[key] = nm
                self.lemmas[f'z{len(self.named):03d}_{nm}'] = f'def {nm}() -> {ty}:\n  {term}'
            return f'{self.named[key]}()'
        return self.prove(m2, body, env2)

    def leaf(self, m2, name, full, params, body, env2, subj):
        """a storage predicate (DK.Ex over a word tree t) of a large zero array 2^b bytes, 2^c chunks, depth d:
        a lemma with b, c, d symbolic (no unary 2^b is ever built), applied at the concrete sizes"""
        b = pow2_of(subj.n)
        c, d = b - 5, subj.d
        self.ctx.alias(E2E / 'e2e_wit.bend')
        key = ('leaf', m2.path, name)
        hyps = []
        if key not in self.named:
            sym = {'t': 'FD.array__trep(U32, d, 0)', 'dw': 'd', 'N': 'FD.u32__pow2u(b)', 'q': 'WT.QP(c)', 'r': '32n'}
            def walk(e):
                e = e.strip()
                cl = parse_call(e)
                if cl and cl[0].split('.')[-1] == 'Ex' and cl[0].startswith('DK'):
                    lam = cl[1][1]
                    mv = re.match(r'(\w+)\s*=>\s*', lam, re.S)
                    return f'({sym[mv.group(1)]}, {walk(lam[mv.end():])})'
                if cl and cl[0].split('.')[-1] == 'P2' and cl[0].startswith('DK'):
                    return f'({walk(cl[1][0])}, {walk(cl[1][1])})'
                if not e.startswith('{'):
                    raise SystemExit(f'e2e_witness: leaf {name}: cannot read {e[:80]!r}')
                if re.search(r'== O\.Words\{', e) and 'array__thaw' in e:
                    return 'ew'
                if 'array__perfect(U32' in e:
                    return 'FD.array__trep_perfect(U32, d, 0)'
                if re.search(r'U32\.to_nat\(N\) == Nat\.add\(WS\.e32\(q\), (32n|r)\)', e):
                    return 'WT.eN(c, b, eb, FD.u32__pow2u(b), FD.u32__pow2u_value(b, hb))'
                if re.search(r'Nat\.is_le\(O\.e8\(1n\+q\), \w+\.spec_common__pow2\(dw\)\)', e):
                    return 'WT.eQ(c, d, hd)'
                t = self.ctx.lift(m2, e)
                t = re.sub(r'(?<![\w.])(t|dw|N|q|r)(?![\w{(])', lambda m: sym[m.group(1)], t)
                hyps.append(t)
                return f'h{len(hyps) - 1}'
            term = walk(body)
            ps = []
            for i, fp in enumerate(full):
                mode = fp[0] if fp[0] in '+-' else ''
                pn, pt = fp.lstrip('+-').split(':', 1)
                ps.append(('-' if i == 0 else mode) + pn.strip() + ': ' + self.ctx.lift(m2, pt.strip()))
            w = params[0]
            ps += ['+c: Nat', '+b: Nat', '+d: Nat', '+eb: {Nat.add(5n, c) == b : Nat}', '+hb: {Nat.is_lt(b, 32n) == True{} : Bool}',
                   '+hd: {Nat.is_le(Nat.add(3n, c), d) == True{} : Bool}',
                   f'+ew: {{{w} == O.Words{{FD.array__thaw(U32, FD.array__trep(U32, d, 0)), FD.u32__pow2u(b)}} : O.Words}}']
            ps += [f'+h{i}: {h}' for i, h in enumerate(hyps)]
            nm = f'sym_{canon(m2.path)}_{name}'
            ret = f'{self.ctx.alias(m2.path)}.{name}(' + ', '.join(params) + ')'
            self.named[key] = (nm, len(hyps))
            self.lemmas[f'y{len(self.named):03d}_{nm}'] = f'def {nm}(' + ', '.join(ps) + f') -> {ret}:\n  {term}'
        nm, nh = self.named[key]
        args = [env2['__e'][pn] for pn in params] + [f'{c}n', f'{b}n', f'{d}n', R, R, R, self.wz(subj.n, subj.d)] + [R] * nh
        return f'{nm}(' + ', '.join(args) + ')'

    def witness(self, mod, ty, v, body, env):
        subj = env.get('__subj')
        ty = ty.strip()
        if isinstance(subj, Words):
            if ty.endswith('array__Tree<U32>'):
                return f'FD.array__trep(U32, {subj.d}n, 0)'
            if v == 'dw':
                return f'{subj.d}n'
            pw = pow2_of(subj.n)
            if v == 'N':
                return f'FD.u32__pow2u({pw}n)' if pw else f'{subj.n}'
            if v == 'q' and pw and re.search(r'U32\.to_nat\(N\) == Nat\.add\(WS\.e32\(q\), (32n|r)\)', body):
                self.ctx.alias(E2E / 'e2e_wit.bend')
                return f'WT.QP({pw - 5}n)'
            if v == 'r' and pw:
                return '32n'
            if v == 'q':
                if re.search(r'U32\.to_nat\(N\) == Nat\.add\(WS\.e32\(q\), 32n\)', body):
                    return f'{subj.n // 32 - 1}n'
                return f'{(subj.n - 1) // 32}n'
            if v == 'r':
                return f'{subj.n - 32 * ((subj.n - 1) // 32)}n'
        if isinstance(subj, EList):
            if 'array__Tree<' in ty:
                inner = ty[ty.index('array__Tree<') + len('array__Tree<'):-1]
                mm = re.match(r'(?:(\w+)\.)?MB<', inner)
                if mm:
                    return 'FD.TLeaf{' + self.ctx.lift(mod, (mm.group(1) + '.' if mm.group(1) else '') + 'MNone') + '{}}'
                el = self.ctx.lift(mod, inner)
                return 'FD.TLeaf{' + el + '_default()}'
            if v == 'dw':
                return '0n'
            if v == 'N':
                return '0'
        if isinstance(subj, Box) and v == 'v':
            return subj.iexpr
        me = re.search(r'\{' + v + r' == (.*?) : [\w.<>&, ]+\}', body)
        if me:
            return self.subst(mod, me.group(1), env)
        if isinstance(subj, Cont):
            mx = re.match(r'x(\d+)$', v)
            if mx:
                return subj.fields[int(mx.group(1))][0]
        raise SystemExit(f'e2e_witness: no witness for {v}: {ty} of {type(subj).__name__} ({mod.path.name})')

    def subst(self, mod, e, env):
        """expression e of module mod, lifted, with its variables replaced by their models' expressions"""
        e = self.ctx.lift(mod, e)
        def sub(m):
            v = m.group(0)
            if v in env.get('__e', {}):
                return env['__e'][v]
            x = env.get(v)
            if x is None or isinstance(x, tuple) or v.startswith('__'):
                if isinstance(x, tuple):
                    return x[1]
                return v
            return x.expr
        return re.sub(r'(?<![\w.])[a-z]\w*(?![\w.{(])', sub, e)

    def eq(self, p, env):
        subj = env.get('__subj')
        if isinstance(subj, Words) and re.search(r'== O\.Words\{', p) and 'array__thaw' in p:
            return self.wz(subj.n, subj.d)
        if isinstance(subj, Words) and 'array__perfect(U32' in p:
            return f'FD.array__trep_perfect(U32, {subj.d}n, 0)'
        pw = pow2_of(subj.n) if isinstance(subj, Words) else None
        if pw and re.search(r'U32\.to_nat\(N\) == Nat\.add\(WS\.e32\(q\), (32n|r)\)', p):
            return f'WT.eN({pw - 5}n, {pw}n, {{==}}, FD.u32__pow2u({pw}n), FD.u32__pow2u_value({pw}n, {{==}}))'
        if pw and re.search(r'^\{U32\.to_nat\(WO\.len\(o\)\) == e8\(cnt8\(o\)\) : Nat\}$', p) and pw >= 3:
            self.ctx.alias(E2E / 'e2e_wit.bend')
            return f'WT.len8({env["__e"]["o"]}, {pw - 3}n, {pw}n, {subj.d}n, {{==}}, {{==}}, {self.wz(subj.n, subj.d)})'
        if pw and re.search(r'Nat\.is_le\(O\.e8\(1n\+q\), \w+\.spec_common__pow2\(dw\)\)', p):
            return f'WT.eQ({pw - 5}n, {subj.d}n, {{==}})'
        return R


# ---------------------------------------------------------------- one name

def szr_term(syn, mod, pt, at_d):
    """the total-size premise {Nat.is_lt(SZR(U32.to_nat(F), t0, ..), pw(31n)) == True} with a large fixed part F:
    SZR adds on its first argument, so evaluating it walks F once per term; a lemma reassociates the sum to
    t0 + .. + tn + F first (F stays a U32 in the proof term)"""
    m = re.match(r'\{Nat\.is_lt\(SZR\((.*)\), VB\.pw\(31n\)\) == True\{\} : Bool\}$', pt, re.S)
    if not m:
        return None
    args = split_top(m.group(1))
    mf = re.match(r'U32\.to_nat\((\d+)\)$', args[0])
    if not mf or int(mf.group(1)) < BIG:
        return None
    ts = [f't{i}' for i in range(len(args) - 1)]
    S = ts[0]
    for t in ts[1:]:
        S = f'Nat.add({S}, {t})'
    F = 'U32.to_nat(x)'
    # A_k = add(..add(add(F, t0), t1).., tk) is add(F, S_k), by one reassociation per term
    lines = []
    Sk = [ts[0]]
    for t in ts[1:]:
        Sk.append(f'Nat.add({Sk[-1]}, {t})')
    for k in range(1, len(ts)):
        inner = f'_'
        ctx = inner
        for t in ts[k + 1:]:
            ctx = f'Nat.add({ctx}, {t})'
        lhs = f'Nat.add(Nat.add({F}, {Sk[k - 1]}), {ts[k]})'
        rhs = f'Nat.add({F}, {Sk[k]})'
        lines.append(f'  %Equal.sym(Nat, {lhs}, {rhs}, FD.nat__add_assoc({F}, {Sk[k - 1]}, {ts[k]})) : {{{ctx} == Nat.add({F}, {S}) : Nat}}')
    params = ', '.join(f'+{t}: Nat' for t in ts)
    nm = 'szr_sum'
    syn.lemmas['x000_' + nm] = (f'# SZR(F, t0, .., tn) = F + (t0 + .. + tn)\n'
                                f'def {nm}(+x: U32, {params}) -> {{BR.SZR({F}, {", ".join(ts)}) == Nat.add({F}, {S}) : Nat}}:\n'
                                + '\n'.join(lines) + '\n  {==}')
    syn.lemmas['x001_szr_lt'] = (f'def szr_lt(+x: U32, {params}, +h: {{Nat.is_lt(Nat.add({S}, {F}), VB.pw(31n)) == True{{}} : Bool}})\n'
                                 f'    -> {{Nat.is_lt(BR.SZR({F}, {", ".join(ts)}), VB.pw(31n)) == True{{}} : Bool}}:\n'
                                 f'  %Equal.sym(Nat, BR.SZR({F}, {", ".join(ts)}), Nat.add({F}, {S}), {nm}(x, {", ".join(ts)})) : {{Nat.is_lt(_, VB.pw(31n)) == True{{}} : Bool}}\n'
                                 f'  %Equal.sym(Nat, Nat.add({F}, {S}), Nat.add({S}, {F}), FD.nat__add_comm({F}, {S})) : {{Nat.is_lt(_, VB.pw(31n)) == True{{}} : Bool}}\n'
                                 f'  h')
    syn.ctx.alias(ROOT / 'proofs/obj/vbuf.bend')
    return f'szr_lt({mf.group(1)}, ' + ', '.join(at_d(a) for a in args[1:]) + ', {==})'


def bridge_decl(name):
    f = E2E / f'{name}_e2e_generated.bend'
    mod = Mod.get(f)
    d = mod.defs[f'{name}_e2e_encode']
    return mod, d


def build(name):
    mod, d = bridge_decl(name)
    PREFER.clear()
    taken = set()
    for a, pth in mod.imports.items():
        if pth not in PREFER and a not in taken:
            PREFER[pth] = a
            taken.add(a)
    PREFER[mod.path] = 'BR'
    PREFER[(E2E / 'e2e_wit.bend').resolve()] = 'WT'
    ctx = Ctx()
    ctx.alias(mod.path)
    syn = Synth(ctx)
    k = d.index('(')
    depth, j = 0, k
    while True:
        c = d[j]
        if c in '([{':
            depth += 1
        elif c in ')]}':
            depth -= 1
            if depth == 0:
                break
        j += 1
    params = split_top(d[k + 1:j])
    concl = re.search(r'\) -> (\{Some\{.*\}):\n', d, re.S).group(1)
    tmod = Mod.get(ROOT / f'types/{name}_def_generated.bend')
    X = name[len('Fulu'):] if name.startswith('Fulu') else name
    dflt = f'{X}_default()'
    obj = model_of(ctx, tmod, dflt)
    env = {'o': obj}
    dmod_alias = ctx.alias(tmod.path)
    D = f'{dmod_alias}.{dflt}'

    def at_d(t):
        t = ctx.lift(mod, t)
        return re.sub(r'(?<![\w.])o(?=[),])', D, t)
    prem = []
    for p in params[1:]:
        pn, pt = p.lstrip('+-').split(':', 1)
        env['__subj'] = None
        term = szr_term(syn, mod, pt.strip(), at_d) or syn.prove(mod, pt, env)
        prem.append((pn.strip(), at_d(pt.strip()), term))
    bralias = 'BR'
    concl_c = at_d(concl)
    ctx.alias(ROOT / 'src/obj.bend')
    ctx.alias(ROOT / 'proofs/compact/found.bend')
    lines = ['import Base']
    for a, pth in sorted(ctx.used.items(), key=lambda x: x[1].relative_to(ROOT).as_posix()):
        rel = pth.relative_to(E2E).as_posix() if pth.parent == E2E else (Path('..') / pth.relative_to(ROOT)).as_posix()
        if pth.parent == E2E:
            rel = './' + rel
        lines.append(f'import {rel} as {a}')
    txt = '\n'.join(lines) + '\n\n' + HEADER + '\n'
    txt += (f'# Non-vacuity of the encode bridge {name}_e2e_encode: every premise holds of the default object\n'
            f'# D = {X}_default() (one def per premise, named after its binder), so the bridge applies to D.\n\n')
    for nm in sorted(syn.lemmas):
        txt += syn.lemmas[nm] + '\n\n'
    for pn, pt, term in prem:
        txt += f'def premise_{pn}() -> {pt}:\n  {term}\n\n'
    txt += (f'def {name}_e2e_witness() -> {concl_c}:\n  {bralias}.{name}_e2e_encode({D}, '
            + ', '.join(f'premise_{pn}()' for pn, _, _ in prem) + ')\n')
    return txt


def outputs():
    return {E2E / f'{n}_e2e_witness_generated.bend': build(n) for n in NAMES}


def main():
    check = '--check' in sys.argv
    only = None
    if '--only' in sys.argv:
        only = sys.argv[sys.argv.index('--only') + 1].split(',')
    outs = {E2E / 'e2e_wit.bend': SUPPORT}
    for n in NAMES:
        if only and n not in only:
            continue
        outs[E2E / f'{n}_e2e_witness_generated.bend'] = build(n)
    stale = []
    for p, t in outs.items():
        if not p.exists() or p.read_text() != t:
            stale.append(p.name)
            if not check:
                p.write_text(t)
    if not only:
        have = {p.name for p in E2E.glob('*_e2e_witness_generated.bend')}
        orphans = sorted(have - {p.name for p in outs})
        for o in orphans:
            if check:
                stale.append(o + ' (orphan)')
            else:
                (E2E / o).unlink()
    if check:
        if stale:
            print('stale: ' + ', '.join(stale))
            sys.exit(1)
        print(f'e2e_witness: {len(outs)} witnesses up to date')
    else:
        print(f'e2e_witness: wrote {len(stale)} of {len(outs)}')


if __name__ == '__main__':
    main()
