"""The (ii)/(iii) bridges of the word-storage vectors whose decode laws are over one perfect tree
(vec_uint{32,64,128,256}_512: spec_arr.uvec, the laws <X>_spec_decode(t, pt), <X>_spec_reject,
<X>_spec_encode(t, pt, s, es) in proofs/obj/spec_garr_<X>.bend). codegen/e2e_bridge.py calls
build() from outputs() and owns the manifest.

The loader's buffer on a byte list bs of the right length is B.Buf{thaw(segt(d, 0, wlp(bs))), N}
(e2e_load.bf), a perfect tree of the decode law's depth, whose byte view is bs (e2e_load.vw), as
for FuluBlob (e2e_fix_d.py). The decoded object's value is the object API's view
(packed_obj_light.vview<K>); e2e_vw512.vw<K> shows it is the spec encode law's value
S.Sequence{chu(slots(t))} for such an object. Sizes and depths stay symbolic (dd, ed: {dd == Dn})
as in the FuluBlob file.

build(amap) -> ({support fname: text}, {bridge fname: text}, {R: (fname, laws)})
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OBJ = ROOT / 'proofs/obj'

# element bytes -> (view K, shift, it<K>c lemma, chu, m)
FAM = {4: ('4', '2n', 'it4c', 'chu1', 'm1'), 8: ('8', '3n', 'it8c', 'chu2', 'm2'),
       16: ('16', '4n', 'it16c', 'chu4', 'm4'), 32: ('32', '5n', 'it32c', 'chu8', 'm8')}
NAMES = ['vec_uint32_512', 'vec_uint64_512', 'vec_uint128_512', 'vec_uint256_512']

SUPPORT = '''import Base
import ../src/obj.bend as O
import ../types/schema.bend as S
import ../proofs/compact/found.bend as FD
import ../proofs/obj/packed_obj_light.bend as PK
import ../proofs/obj/arr_vec.bend as AV
import ../proofs/obj/wany.bend as WA

# GENERATED by codegen/e2e_bridge.py. Do not edit.
# The object API's view of a word-storage vector whose words are a tree a (and whatever b holds past
# them, a tree bt) is the spec value of a's slots (codegen/e2e_arr512.py).

# taking a list's own length from it appended to anything gives the list back
def tl(+xs: List<&2, U32>, +ys: List<&2, U32>) -> {FD.spec_common__take(U32, FD.spec_common__append(U32, xs, ys), FD.spec_common__length(U32, xs)) == xs : List<&2, U32>}:
  match xs:
    case Nil{}: FD.list__sc_take_zero(U32, ys)
    case Con{+x, +r}: Equal.cong(List<&2, U32>, List<&2, U32>, z => Con{x, z}, FD.spec_common__take(U32, FD.spec_common__append(U32, r, ys), FD.spec_common__length(U32, r)), r, tl(r, ys))
'''

VW = '''
def vw{K}(+a: FD.array__Tree<U32>, +bt: FD.array__Tree<U32>, +k: Nat, +N: U32, +eN: {{U32.to_nat(U32.shrn(N, {SH})) == k : Nat}},
    +el: {{FD.spec_common__length(U32, FD.array__slots(U32, a)) == AV.{M}(k) : Nat}})
    -> {{PK.vview{K}(O.Words{{ANode{{FD.array__thaw(U32, a), FD.array__thaw(U32, bt)}}, N}}) == S.Sequence{{AV.{C}(FD.array__slots(U32, a))}} : S.Value}}:
  %Equal.sym(Nat, U32.to_nat(U32.shrn(N, {SH})), k, eN) :
    {{S.Sequence{{PK.it{K}(_, FD.spec_common__append(U32, FD.array__slots(U32, FD.array__freeze(U32, FD.array__thaw(U32, a))), FD.array__slots(U32, FD.array__freeze(U32, FD.array__thaw(U32, bt)))))}} == S.Sequence{{AV.{C}(FD.array__slots(U32, a))}} : S.Value}}
  %Equal.sym(FD.array__Tree<U32>, FD.array__freeze(U32, FD.array__thaw(U32, a)), a, FD.array__freeze_thaw(U32, a)) :
    {{S.Sequence{{PK.it{K}(k, FD.spec_common__append(U32, FD.array__slots(U32, _), FD.array__slots(U32, FD.array__freeze(U32, FD.array__thaw(U32, bt)))))}} == S.Sequence{{AV.{C}(FD.array__slots(U32, a))}} : S.Value}}
  Equal.trans(S.Value, S.Sequence{{PK.it{K}(k, {APP})}}, S.Sequence{{AV.{C}(FD.spec_common__take(U32, {APP}, AV.{M}(k)))}}, S.Sequence{{AV.{C}(FD.array__slots(U32, a))}},
    Equal.cong(S.Value, S.Value, z => S.Sequence{{z}}, PK.it{K}(k, {APP}), AV.{C}(FD.spec_common__take(U32, {APP}, AV.{M}(k))), WA.{IT}(k, {APP})),
    Equal.cong(List<&2, U32>, S.Value, z => S.Sequence{{AV.{C}(z)}}, FD.spec_common__take(U32, {APP}, AV.{M}(k)), FD.array__slots(U32, a),
      Equal.trans(List<&2, U32>, FD.spec_common__take(U32, {APP}, AV.{M}(k)), FD.spec_common__take(U32, {APP}, FD.spec_common__length(U32, FD.array__slots(U32, a))), FD.array__slots(U32, a),
        Equal.cong(Nat, List<&2, U32>, z => FD.spec_common__take(U32, {APP}, z), AV.{M}(k), FD.spec_common__length(U32, FD.array__slots(U32, a)), Equal.sym(Nat, FD.spec_common__length(U32, FD.array__slots(U32, a)), AV.{M}(k), el)),
        tl(FD.array__slots(U32, a), FD.array__slots(U32, FD.array__freeze(U32, FD.array__thaw(U32, bt)))))))
'''


def support_text():
    t = SUPPORT
    for eb, (K, SH, IT, C, M) in sorted(FAM.items()):
        APP = 'FD.spec_common__append(U32, FD.array__slots(U32, a), FD.array__slots(U32, FD.array__freeze(U32, FD.array__thaw(U32, bt))))'
        t += VW.format(K=K, SH=SH, IT=IT, C=C, M=M, APP=APP)
    return t


def info(X, amap):
    """the decode law's depth and byte size, the element bytes, the reject law's file"""
    f = OBJ / f'spec_garr_{X}.bend'
    if not f.exists():
        return None
    s = f.read_text()
    md = re.search(r'^def ' + X + r'_spec_decode\(\+t: F\.array__Tree<U32>, \+pt: \{F\.array__perfect\(U32, (\d+)n, t\) == True\{\} : Bool\}\)\n'
                   r'    -> \{' + X + r'_r\.' + X + r'_decode\(B\.Buf\{F\.array__thaw\(U32, t\), (\d+)\}, \2\)', s, re.M)
    me = re.search(r'^def ' + X + r'_spec_encode\(\+t: F\.array__Tree<U32>, \+pt: \{F\.array__perfect\(U32, (\d+)n, t\) == True\{\} : Bool\}, '
                   r'\+s: S\.Schema, \+es: \{s == Spec\.' + X + r'\(\) : S\.Schema\}\)\n    -> Decoding\.decodes\(s, SF\.limbs\(F\.array__slots\(U32, t\)\), '
                   r'S\.Sequence\{AV\.(chu\d+)\(F\.array__slots\(U32, t\)\)\}\):', s, re.M)
    mr = re.search(r'^def ' + X + r'_spec_reject\(buf: B\.Buf, \+m: U32, e: \{U32\.is_eq\(m, (\d+)\) == False\{\} : Bool\}\)', s, re.M)
    rj = amap['map'][X].get('decode_reject', [])
    if not (md and me and mr and rj) or md.group(1) != me.group(1) or md.group(2) != mr.group(1):
        return None
    eb = {'chu1': 4, 'chu2': 8, 'chu4': 16, 'chu8': 32}[me.group(2)]
    d, N = int(md.group(1)), int(md.group(2))
    if 4 * 2 ** d != N or N % eb:
        return None
    rtext = (OBJ / rj[0]['file']).read_text()
    mk = re.search(r'^def ' + X + r'_decode_reject\(\+bs: \+List<U32>, \+hn: \{Nat\.is_eq\(List\.length\(&2, U32, bs\), (' + str(N) + r'n|VRF\.SZ\(GS\.' + X + r'\(\)\))\) == False\{\} : Bool\}\) -> Decoding\.outside_image\(GS\.' + X + r'\(\), bs\):', rtext, re.M)
    if not mk:
        return None
    return {'d': d, 'N': N, 'eb': eb, 'k': N // eb, 'rj': rj[0]['file'], 'rk': mk.group(1)}


def bridge_text(X, i):
    d, N, eb, k = i['d'], i['N'], i['eb'], i['k']
    K, SH, IT, C, M = FAM[eb]
    DN = f'{d}n'
    T = 'AC.segt(dd, 0n, L.wlp(bs))'
    OBJW = f'O.Words{{ANode{{FD.array__thaw(U32, {T}), Array.new(U32, {DN}, 0)}}, {N}}}'
    VAL = f'S.Sequence{{AV.{C}(FD.array__slots(U32, {T}))}}'
    M1 = 'Maybe<&1, O.Words>'
    MV = 'Maybe<&2, S.Value>'
    IN = 'B.fill_at(B.alloc(n), 0, bs)'
    DEC = f'{X}_r.{X}_decode({IN}, n)'
    RES = f'Pair.snd(B.Buf, {M1}, {DEC})'
    API = f'API.deserialize(GS.{X}(), bs)'
    DP = f'+dd: Nat, +ed: {{dd == {DN} : Nat}}'
    HN = '+hn: {List.length(&2, U32, bs) == U32.to_nat(n) : Nat}'
    HD = '+hd: {SP.bytes_domain(bs) == True{} : Bool}'
    EN = f'+en: {{n == {N} : U32}}'
    PT = f'FD.logic__subst(Nat, z => {{FD.array__perfect(U32, z, {T}) == True{{}} : Bool}}, dd, {DN}, ed, L.seg_pf(dd, L.wlp(bs)))'
    KN = f'FD.nat__eq_from_is_eq(U32.to_nat({N}), {N}n, {{==}})'
    L = f'''import Base
import ../END_TO_END.bend as E2E
import ../src/model.bend as API
import ../src/buffer.bend as B
import ../src/obj.bend as O
import ../types/{X}_decode_ssz_generated.bend as {X}_r
import ../types/schema.bend as S
import ../spec/codec.bend as Encoding
import ../spec/primitives.bend as SP
import ../proofs/type_validator_soundness.bend as VS
import ../proofs/compact/found.bend as FD
import ../proofs/compact/arith.bend as A
import ../proofs/obj/spec_fixed.bend as F
import ../proofs/obj/packed_obj_light.bend as PK
import ../proofs/obj/arr_copy.bend as AC
import ../proofs/obj/arr_vec.bend as AV
import ../proofs/obj/generic_specs.bend as GS
import ../proofs/obj/spec_garr_{X}.bend as M
import ../proofs/obj/{i['rj'][:-len('.bend')]}.bend as RJ
import ../proofs/word_facts.bend as WF
import ./e2e_bytes.bend as EY
import ./e2e_load.bend as L
import ./e2e_cap.bend as C
import ./e2e_fixdw.bend as XW
import ../proofs/obj/vrejf.bend as VRF
import ./e2e_vw512.bend as VW

# GENERATED by codegen/e2e_bridge.py. Do not edit.
# {X}: (ii) through the view and (iii) (codegen/e2e_arr512.py): the loader's buffer on a byte list of
# {N} bytes is a perfect tree of depth {d} whose bytes are the list, which the decode law takes; the
# decoded object's view is the spec encode law's value. Sizes and depths symbolic (dd = {d}).

def mv(m: {M1}) -> {MV}:
  match m:
    case None{{}}: None{{}}
    case Some{{o}}: Some{{PK.vview{K}(o)}}

def d_none(+bs: +List<U32>, +n: U32, +ec: {{U32.is_eq(n, {N}) == False{{}} : Bool}}) -> {{{RES} == None{{}} : {M1}}}:
  Equal.cong(B.Buf & {M1}, {M1}, q => Pair.snd(B.Buf, {M1}, q), {DEC}, ({IN}, None{{}}), M.{X}_spec_reject({IN}, n, ec))

def d_anone(+bs: +List<U32>, +n: U32, {HN}, +ec: {{U32.is_eq(n, {N}) == False{{}} : Bool}}) -> {{{API} == None{{}} : {MV}}}:
  EY.outside_none(GS.{X}(), bs, RJ.{X}_decode_reject(bs, XW.rz(bs, n, hn, {N}, {i['rk']}, FD.nat__eq_from_is_eq(U32.to_nat({N}), {i['rk']}, {{==}}), ec)))

def ekn(+n: U32, {EN}) -> {{U32.to_nat(n) == {N}n : Nat}}:
  FD.logic__subst(U32, z => {{U32.to_nat(z) == {N}n : Nat}}, {N}, n, Equal.sym(U32, n, {N}, en), {KN})

def hcap({DP}, +n: U32, {EN}) -> {{B.capacity(n) == dd : Nat}}:
  Equal.trans(Nat, B.capacity(n), {DN}, dd, FD.logic__subst(U32, z => {{B.capacity(z) == {DN} : Nat}}, {N}, n, Equal.sym(U32, n, {N}, en), {{==}}), Equal.sym(Nat, dd, {DN}, ed))

def hw({DP}, +bs: +List<U32>, +n: U32, {HN}, {EN}) -> {{Nat.is_le(FD.spec_common__length(U32, L.wlp(bs)), FD.spec_common__pow2(dd)) == True{{}} : Bool}}:
  +h = FD.logic__subst(Nat, z => {{Nat.is_le(z, A.quad(FD.spec_common__pow2({DN}))) == True{{}} : Bool}}, {N}n, U32.to_nat(n), Equal.sym(Nat, U32.to_nat(n), {N}n, ekn(n, en)), {{==}})
  FD.logic__subst(Nat, z => {{Nat.is_le(FD.spec_common__length(U32, L.wlp(bs)), FD.spec_common__pow2(z)) == True{{}} : Bool}}, B.capacity(n), dd, hcap(dd, ed, n, en), C.cap_w(bs, n, {DN}, hn, {{==}}, h))

def d_by({DP}, +bs: +List<U32>, +n: U32, {HN}, {HD}, {EN}) -> {{F.limbs(FD.array__slots(U32, {T})) == bs : +List<U32>}}:
  Equal.trans(+List<U32>, F.limbs(FD.array__slots(U32, {T})), VSP.bt(U32.to_nat(n), F.limbs(FD.array__slots(U32, {T}))), bs,
    Equal.sym(+List<U32>, VSP.bt(U32.to_nat(n), F.limbs(FD.array__slots(U32, {T}))), F.limbs(FD.array__slots(U32, {T})),
      Equal.trans(+List<U32>, VSP.bt(U32.to_nat(n), F.limbs(FD.array__slots(U32, {T}))), VSP.bt(List.length(&2, U32, F.limbs(FD.array__slots(U32, {T}))), F.limbs(FD.array__slots(U32, {T}))), F.limbs(FD.array__slots(U32, {T})),
        Equal.cong(Nat, +List<U32>, z => VSP.bt(z, F.limbs(FD.array__slots(U32, {T}))), U32.to_nat(n), List.length(&2, U32, F.limbs(FD.array__slots(U32, {T}))), XW.vleng(dd, {T}, L.seg_pf(dd, L.wlp(bs)), n, {N}n, ekn(n, en), FD.logic__subst(Nat, z => {{Nat.is_eq(A.quad(FD.spec_common__pow2(z)), {N}n) == True{{}} : Bool}}, {DN}, dd, Equal.sym(Nat, dd, {DN}, ed), {{==}}))),
        XW.btf(F.limbs(FD.array__slots(U32, {T}))))),
    L.vw(bs, n, dd, hd, hn, hw(dd, ed, bs, n, hn, en)))

def d_some({DP}, +bs: +List<U32>, +n: U32, {HN}, {HD}, {EN}) -> {{{RES} == Some{{{OBJW}}} : {M1}}}:
  %Equal.sym(B.Buf, {IN}, B.Buf{{FD.array__thaw(U32, {T}), n}}, L.bf(bs, n, dd, hd, hcap(dd, ed, n, en), FD.logic__subst(Nat, z => {{Nat.is_lt(z, 32n) == True{{}} : Bool}}, {DN}, dd, Equal.sym(Nat, dd, {DN}, ed), {{==}}), hw(dd, ed, bs, n, hn, en))) :
    {{Pair.snd(B.Buf, {M1}, {X}_r.{X}_decode(_, n)) == Some{{{OBJW}}} : {M1}}}
  %Equal.sym(U32, n, {N}, en) : {{Pair.snd(B.Buf, {M1}, {X}_r.{X}_decode(B.Buf{{FD.array__thaw(U32, {T}), _}}, _)) == Some{{{OBJW}}} : {M1}}}
  Equal.cong(B.Buf & {M1}, {M1}, q => Pair.snd(B.Buf, {M1}, q), {X}_r.{X}_decode(B.Buf{{FD.array__thaw(U32, {T}), {N}}}, {N}), (B.Buf{{FD.array__thaw(U32, {T}), {N}}}, Some{{{OBJW}}}), M.{X}_spec_decode({T}, {PT}))

def d_asome({DP}, +bs: +List<U32>, +n: U32, {HN}, {HD}, {EN}) -> {{{API} == Some{{{VAL}}} : {MV}}}:
  E2E.spec_accepted(GS.{X}(), bs, {VAL}, (VS.public_sound(GS.{X}(), {{==}}),
    %d_by(dd, ed, bs, n, hn, hd, en) : {{Encoding.encoding_for_legal_type(GS.{X}(), {VAL}) == Some{{_}} : Maybe<&2, +List<U32>>}}
    M.{X}_spec_encode({T}, {PT}, GS.{X}(), {{==}})))

def d_br({DP}, +bs: +List<U32>) -> {{PK.vview{K}({OBJW}) == {VAL} : S.Value}}:
  +na = Equal.trans(Array<U32>, Array.new(U32, {DN}, 0), Array.new(U32, dd, 0), FD.array__thaw(U32, FD.array__trep(U32, dd, 0)), Equal.cong(Nat, Array<U32>, z => Array.new(U32, z, 0), {DN}, dd, Equal.sym(Nat, dd, {DN}, ed)), FD.array__new(U32, dd, 0))
  %Equal.sym(Array<U32>, Array.new(U32, {DN}, 0), FD.array__thaw(U32, FD.array__trep(U32, dd, 0)), na) : {{PK.vview{K}(O.Words{{ANode{{FD.array__thaw(U32, {T}), _}}, {N}}}) == {VAL} : S.Value}}
  VW.vw{K}({T}, FD.array__trep(U32, dd, 0), {k}n, {N}, FD.nat__eq_from_is_eq(U32.to_nat(U32.shrn({N}, {SH})), {k}n, {{==}}),
    Equal.trans(Nat, FD.spec_common__length(U32, FD.array__slots(U32, {T})), FD.spec_common__pow2(dd), AV.{M}({k}n),
      FD.array__slots_length(U32, dd, {T}, L.seg_pf(dd, L.wlp(bs))),
      FD.logic__subst(Nat, z => {{FD.spec_common__pow2(z) == AV.{M}({k}n) : Nat}}, {DN}, dd, Equal.sym(Nat, dd, {DN}, ed), FD.nat__eq_from_is_eq(FD.spec_common__pow2({DN}), AV.{M}({k}n), {{==}}))))

def d_v({DP}, +bs: +List<U32>, +n: U32, {HN}, {HD}, +c: Bool, +ec: {{U32.is_eq(n, {N}) == c : Bool}}) -> {{mv({RES}) == {API} : {MV}}}:
  match c:
    case False{{}}:
      %Equal.sym({M1}, {RES}, None{{}}, d_none(bs, n, ec)) : {{mv(_) == {API} : {MV}}}
      %Equal.sym({MV}, {API}, None{{}}, d_anone(bs, n, hn, ec)) : {{mv(None{{}}) == _ : {MV}}}
      {{==}}
    case True{{}}:
      +en = WF.u32_equal_sound(n, {N}, ec)
      %Equal.sym({M1}, {RES}, Some{{{OBJW}}}, d_some(dd, ed, bs, n, hn, hd, en)) : {{mv(_) == {API} : {MV}}}
      %Equal.sym({MV}, {API}, Some{{{VAL}}}, d_asome(dd, ed, bs, n, hn, hd, en)) : {{mv(Some{{{OBJW}}}) == _ : {MV}}}
      Equal.cong(S.Value, {MV}, v => Some{{v}}, PK.vview{K}({OBJW}), {VAL}, d_br(dd, ed, bs))

# (ii) through the view
def {X}_e2e_decode_view(+bs: +List<U32>, +n: U32, {HN}, {HD}) -> {{mv({RES}) == {API} : {MV}}}:
  d_v({DN}, {{==}}, bs, n, hn, hd, U32.is_eq(n, {N}), {{==}})

def d_bn(m: {M1}, +e: {{Maybe.is_some(&2, S.Value, mv(m)) == False{{}} : Bool}}) -> {{m == None{{}} : {M1}}}:
  match m:
    case None{{}}: {{==}}
    case Some{{x}}: Empty.absurd({{Some{{x}} == None{{}} : {M1}}}, FD.logic__false_true(Equal.sym(Bool, True{{}}, False{{}}, e)))

# (iii)
def {X}_e2e_decode_reject(+bs: +List<U32>, +n: U32, {HN}, {HD})
    -> ({{{RES} == None{{}} : {M1}}} -> {{{API} == None{{}} : {MV}}}) & ({{{API} == None{{}} : {MV}}} -> {{{RES} == None{{}} : {M1}}}):
  (dn => Equal.trans({MV}, {API}, mv({RES}), None{{}}, Equal.sym({MV}, mv({RES}), {API}, {X}_e2e_decode_view(bs, n, hn, hd)),
     Equal.cong({M1}, {MV}, q => mv(q), {RES}, None{{}}, dn)),
   an => d_bn({RES}, Equal.cong({MV}, Bool, z => Maybe.is_some(&2, S.Value, z), mv({RES}), None{{}}, Equal.trans({MV}, mv({RES}), {API}, None{{}}, {X}_e2e_decode_view(bs, n, hn, hd), an))))
'''
    return L.replace('import ../proofs/obj/arr_copy.bend as AC\n', 'import ../proofs/obj/arr_copy.bend as AC\nimport ../proofs/obj/vspec.bend as VSP\n')


def build(amap, readable):
    """readable: generated name -> manifest name R"""
    files, cover = {}, {}
    for X in NAMES:
        if X not in amap['map']:
            continue
        i = info(X, amap)
        if not i:
            continue
        R = readable.get(X, X)
        fn = f'{R}_e2e_dec_generated.bend'
        files[fn] = bridge_text(X, i)
        cover[R] = (fn, [f'{R}_e2e_decode_view', f'{R}_e2e_decode_reject'])
    support = {'e2e_vw512.bend': support_text()} if files else {}
    return support, files, cover
