"""The second variable-size worker's share of the e2e bridges (codegen/e2e_bridge.py imports it).

codegen/e2e_bridge.py owns the templates, the shared support modules (e2e_load, e2e_cap, e2e_emit,
e2e_ulist) and the manifest; this module only adds per-name entries and any new shared module:

  VDEC_VIEWS[X]   = {'view': 'RT.v_X', 'imports': [...], 'text': ...}   (ii)/(iii): the view lemma vv
  VROOT_SHAPES[X] = f(R, X) -> text                                     (iv): the rebuild from rep
  VENC_SHAPES[X]  = f(R, X) -> text                                     (i)
  SUPPORT_OUT     = {'e2e_<name>.bend': text}                           new shared modules
  VENC_PREMISE[X] = '...'                                               (i)'s premise text in the manifest

X is the generated name (api_map.json), R the readable one (names.py). A name counts as bridged in the
manifest's variable_size section once it has all three; see e2e_bridge's DataColumnsByRootIdentifier
entries for the pattern. Texts may import ../types/fulu_obj.bend as T: e2e_bridge rewires them.

The decode template reads from the name's decode facade: the decoder (T.<fn>), the object type
(Maybe<&1, ..>; override with VDEC_VIEWS[X]['otype']), the schema (Spec or GS), and whether OBJ / VAL
take the depth (OBJ(d, t, n)); it calls the view lemma with decode_accept's own hypotheses:
  vv(+d, +t, +n, +pf: perfect(d, t), +hd: d < bound, +hn: to_nat(n) <= quad(pow2(d)), +hchk: CHK(t, n) == True)
    -> {view(OBJ(..)) == VAL(..)}
"""

VDEC_VIEWS = {}
VROOT_SHAPES = {}
VENC_SHAPES = {}
SUPPORT_OUT = {}
VENC_PREMISE = {}


# ---- byte lists ----

# (iv) of a bare byte list (the object is O.Words; its root law and validity lemma live in the
# name's big_root_ / big_gvalid_ modules, over rep = LO.rep_bl). The words are rebuilt from wfl's
# witnesses (both cases) so the view is over copyable t, N.
def vroot_bytelist(R, X):
    OW = 'O.Words{FD.array__thaw(U32, t), N}'
    RX = lambda o: f'D.bytes(Pair.snd(O.Words, D.Digest, Pair.snd(B.Buf, O.Words & D.Digest, {R}_h.{X}_hash_tree_root(h, {o}))))'
    G = lambda o: f'{{Some{{{RX(o)}}} == API.hash_tree_root(Spec.{X}(), S.BytesValue{{WO.wview({o})}}) : Maybe<&2, +List<U32>>}}'
    imps = ['import Base', 'import ../END_TO_END.bend as E2E', 'import ../src/model.bend as API', 'import ../src/buffer.bend as B',
            'import ../src/digest.bend as D', 'import ../src/obj.bend as O', f'import ../types/{R}_hashtreeroot_generated.bend as {R}_h',
            'import ../types/schema.bend as S', 'import ../spec/fulu_schemas.bend as Spec', 'import ../proofs/type_validator_soundness.bend as VS',
            'import ../proofs/compact/found.bend as FD', 'import ../proofs/obj/words_obj.bend as WO', 'import ../proofs/obj/list_obj.bend as LO',
            f'import ../proofs/obj/big_root_{X}.bend as BR', f'import ../proofs/obj/big_gvalid_{X}.bend as GV', 'import ./e2e_support.bend as E']
    return '\n'.join(imps) + f"""

# GENERATED by codegen/e2e_bridge.py (codegen/e2e_var_b.py). Do not edit.
# {R} (variable size, a byte list): the object API's root is END_TO_END's hash_tree_root, for every
# object the root law represents (LO.rep_bl: its words in a perfect tree of depth below 32, its length
# within the limit).

def rt1(h: B.Buf, +t: FD.array__Tree<U32>, +N: U32, +rep: LO.rep_bl({OW}, Spec.{X}())) -> {G(OW)}:
  E.root_legal(Spec.{X}(), S.BytesValue{{WO.wview({OW})}}, VS.public_sound(Spec.{X}(), {{==}}), {RX(OW)},
    GV.{X}_root_valid({OW}, Spec.{X}(), {{==}}, rep), BR.{X}_root_correct(h, {OW}, Spec.{X}(), {{==}}, rep))

# the object as rep's witnesses name it
def rt2(h: B.Buf, -o: O.Words, +rep: LO.rep_bl(o, Spec.{X}()), +t: FD.array__Tree<U32>, +N: U32,
    +eo: {{o == {OW} : O.Words}}) -> {G('o')}:
  %Equal.sym(O.Words, o, {OW}, eo) : {G('_')}
  rt1(h, t, N, FD.logic__subst(O.Words, z => LO.rep_bl(z, Spec.{X}()), o, {OW}, eo, rep))

# (iv)
def {R}_e2e_root(h: B.Buf, -o: O.Words, +rep: LO.rep_bl(o, Spec.{X}())) -> {G('o')}:
  (+wf, +hl) = rep
  match wf:
    case Inl{{w}}:
      (+t, w1) = w
      (+dw, w2) = w1
      (+N, w3) = w2
      (+eo, w4) = w3
      rt2(h, o, rep, t, N, eo)
    case Inr{{w}}:
      (+t, w1) = w
      (+dw, w2) = w1
      (+N, w3) = w2
      (+q, w4) = w3
      (+r, w5) = w4
      (+eo, w6) = w5
      rt2(h, o, rep, t, N, eo)
"""


VROOT_SHAPES['Transaction'] = vroot_bytelist

# The byte-list view (shared): the words a byte-list reader copies out of a buffer (vua_ct's CT at
# any byte offset) view as the window's bytes.
SUPPORT_OUT['e2e_blist.bend'] = r"""import Base
import ../src/obj.bend as O
import ../proofs/compact/found.bend as FD
import ../proofs/compact/arith.bend as A
import ../proofs/obj/spec_fixed.bend as FX
import ../proofs/obj/vspec.bend as VS
import ../proofs/obj/vbuf.bend as VB
import ../proofs/obj/vlist.bend as VLS
import ../proofs/nat_order.bend as Order
import ../proofs/obj/vua.bend as UA
import ../proofs/obj/vua_ct.bend as UCT
import ../proofs/obj/vua_win.bend as UW
import ../proofs/obj/words_spec.bend as WS
import ../proofs/obj/words_obj.bend as WO
import ../proofs/obj/dk.bend as DK
import ../spec/primitives.bend as SP

# GENERATED by codegen/e2e_bridge.py (codegen/e2e_var_b.py). Do not edit.
# Byte lists in the e2e bridges: the root view of the storage a byte-list reader copies out of a
# buffer (vua_ct.CT, len bytes at byte offset off = x) is the window's bytes UW.WX(t, x, len).

def btake_bt(+n: Nat, +xs: +List<U32>) -> {WS.btake(n, xs) == VS.bt(n, xs) : +List<U32>}:
  match n xs:
    case 0n _: {==}
    case 1n+ +p Nil{}: {==}
    case 1n+ +p Con{+h, +t}:
      %Equal.sym(+List<U32>, WS.btake(p, t), VS.bt(p, t), btake_bt(p, t)) : {h <> _ == h <> VS.bt(p, t) : +List<U32>}
      {==}

def CW(+d: Nat, +t: FD.array__Tree<U32>, +off: U32, +len: U32) -> FD.array__Tree<U32>: UCT.CT(d, t, off, len, VLS.DZ(len))
def WX0(+t: FD.array__Tree<U32>, +len: U32) -> +List<U32>: UW.WX(t, 0n, U32.to_nat(len))

def bview(+d: Nat, +t: FD.array__Tree<U32>, +off: U32, +len: U32, +x: Nat, +eo: {U32.to_nat(off) == x : Nat}, +hd: {Nat.is_lt(d, 28n) == True{} : Bool},
    +hw: {Nat.is_le(Nat.add(x, U32.to_nat(len)), A.quad(VB.pw(d))) == True{} : Bool}, +pf: {FD.array__perfect(U32, d, t) == True{} : Bool})
    -> {WO.wview(O.Words{FD.array__thaw(U32, CW(d, t, off, len)), len}) == UW.WX(t, x, U32.to_nat(len)) : +List<U32>}:
  +hL = FD.nat__le_trans(U32.to_nat(len), Nat.add(x, U32.to_nat(len)), A.quad(VB.pw(d)), Order.left_below_sum(x, U32.to_nat(len)), hw)
  +hB = FD.logic__subst(Nat, z => {Nat.is_le(Nat.add(z, U32.to_nat(len)), A.quad(VB.pw(d))) == True{} : Bool}, x, U32.to_nat(off), Equal.sym(Nat, U32.to_nat(off), x, eo), hw)
  %Equal.sym(FD.array__Tree<U32>, FD.array__freeze(U32, FD.array__thaw(U32, CW(d, t, off, len))), CW(d, t, off, len), FD.array__freeze_thaw(U32, CW(d, t, off, len))) :
    {WS.btake(U32.to_nat(len), FX.limbs(FD.array__slots(U32, _))) == UW.WX(t, x, U32.to_nat(len)) : +List<U32>}
  %Equal.sym(+List<U32>, WS.btake(U32.to_nat(len), FX.limbs(FD.array__slots(U32, CW(d, t, off, len)))), VS.bt(U32.to_nat(len), FX.limbs(FD.array__slots(U32, CW(d, t, off, len)))), btake_bt(U32.to_nat(len), FX.limbs(FD.array__slots(U32, CW(d, t, off, len))))) :
    {_ == UW.WX(t, x, U32.to_nat(len)) : +List<U32>}
  %eo : {VS.bt(U32.to_nat(len), FX.limbs(FD.array__slots(U32, CW(d, t, off, len)))) == VS.bt(U32.to_nat(len), VS.bdr(_, UA.BYT(t))) : +List<U32>}
  UCT.ct_bytes(d, t, off, len, VLS.DZ(len), VLS.KK(d), VLS.kk_lt(d, hd), VLS.hyn(d, len, hL), pf, UW.hsx(d, off, x, len, eo, hd, hw), VLS.hrg(d, len, hd, hL), hB)

# The view of byte storage O.Words{thaw(T), N} is its first N bytes, as the encode laws' WX(T, 0, N).
def wv0(+T: FD.array__Tree<U32>, +N: U32) -> {WO.wview(O.Words{FD.array__thaw(U32, T), N}) == WX0(T, N) : +List<U32>}:
  %Equal.sym(FD.array__Tree<U32>, FD.array__freeze(U32, FD.array__thaw(U32, T)), T, FD.array__freeze_thaw(U32, T)) :
    {WS.btake(U32.to_nat(N), FX.limbs(FD.array__slots(U32, _))) == WX0(T, N) : +List<U32>}
  btake_bt(U32.to_nat(N), FX.limbs(FD.array__slots(U32, T)))

# ---- the (i) premise: byte storage as the root law's invariant (list_obj.wfl), at depth below k ----
# (the encode laws take storage depth below their own bound; the root law's invariant gives dw < 32)

def sdk0(w: O.Words, +k: Nat) -> Data:
  DK.Ex(FD.array__Tree<U32>, t => DK.Ex(Nat, dw => DK.Ex(U32, N =>
    DK.P2({w == O.Words{FD.array__thaw(U32, t), N} : O.Words},
    DK.P2({FD.array__perfect(U32, dw, t) == True{} : Bool},
    DK.P2({Nat.is_lt(dw, k) == True{} : Bool},
          {U32.to_nat(N) == 0n : Nat}))))))

def sdk1(w: O.Words, +k: Nat) -> Data:
  DK.Ex(FD.array__Tree<U32>, t => DK.Ex(Nat, dw => DK.Ex(U32, N => DK.Ex(Nat, q => DK.Ex(Nat, r =>
    DK.P2({w == O.Words{FD.array__thaw(U32, t), N} : O.Words},
    DK.P2({FD.array__perfect(U32, dw, t) == True{} : Bool},
    DK.P2({Nat.is_lt(dw, k) == True{} : Bool},
    DK.P2({U32.to_nat(N) == Nat.add(WS.e32(q), r) : Nat},
    DK.P2({Nat.is_lt(0n, r) == True{} : Bool},
    DK.P2({Nat.is_le(r, 32n) == True{} : Bool},
    DK.P2({Nat.is_le(O.e8(1n+q), FD.spec_common__pow2(dw)) == True{} : Bool},
          {WS.bdrop(r, WS.cb(FD.array__slots(U32, t), Nat.add(q, 0n))) == SP.zero_bytes(Nat.sub(32n, r)) : +List<U32>}))))))))))))

def sdk(w: O.Words, +k: Nat) -> Data: DK.Or2(sdk0(w, k), sdk1(w, k))
"""


# (ii)/(iii) of a bare byte list: the reader's words at offset 0 (the codec's OBJ(d, t, n) =
# O.Words{thaw(CT(d, t, 0, n, DZ(n))), n}) view as VAL's bytes WX(t, 0, n) (e2e_blist.bview).
def vdec_bytelist(X, bound):
    return {'view': 'vbl',
            'imports': ['import ../proofs/obj/words_obj.bend as WO', 'import ./e2e_blist.bend as BL'],
            'text': f'''# ---- the view of a decoded object is the codec law's value ----

def vbl(o: O.Words) -> S.Value: S.BytesValue{{WO.wview(o)}}

def vv(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +pf: {{FD.array__perfect(U32, d, t) == True{{}} : Bool}}, +hd: {{Nat.is_lt(d, {bound}n) == True{{}} : Bool}},
    +hn: {{Nat.is_le(U32.to_nat(n), A.quad(FD.spec_common__pow2(d))) == True{{}} : Bool}}, +hchk: {{DC.CHK(t, n) == True{{}} : Bool}}) -> {{vbl(DC.OBJ(d, t, n)) == DC.VAL(t, n) : S.Value}}:
  Equal.cong(+List<U32>, S.Value, z => S.BytesValue{{z}}, WO.wview(O.Words{{FD.array__thaw(U32, BL.CW(d, t, 0, n)), n}}), BL.WX0(t, n), BL.bview(d, t, 0, n, 0n, {{==}}, hd, hn, pf))

'''}


VDEC_VIEWS['Transaction'] = vdec_bytelist('Transaction', 28)



# (i) of a bare byte list: encode_eval / encode_spec of big_var_codec_X_enc (storage depth below
# DB, the runtime's length check N <= LIM, a U32 literal equal to the schema's limit), the output path
# (e2e_emit.ob at the output's depth DO(N)), the view (e2e_blist.wv0) and END_TO_END's serialize law.
def venc_bytelist(DB, LIM):
    def f(R, X):
        OW = 'O.Words{FD.array__thaw(U32, T), N}'
        ENC = lambda o: f'{R}_e.{X}_encode({o})'
        G = lambda o, v: f'{{Some{{E.obytes(Pair.snd(O.Words, B.Buf, {ENC(o)}))}} == API.serialize(Spec.{X}(), S.BytesValue{{{v}}}) : Maybe<&2, +List<U32>>}}'
        BYT = 'VSP.bt(U32.to_nat(N), SF.limbs(FD.array__slots(U32, EN.OUT(N, T))))'
        HN = f'{{Nat.is_le(U32.to_nat(N), A.quad(VB.pw(dw))) == True{{}} : Bool}}'
        imps = ['import Base', 'import ../END_TO_END.bend as E2E', 'import ../src/model.bend as API', 'import ../src/buffer.bend as B',
                'import ../src/obj.bend as O', f'import ../types/{R}_encode_ssz_generated.bend as {R}_e', 'import ../types/schema.bend as S',
                'import ../spec/fulu_schemas.bend as Spec', 'import ../spec/primitives.bend as SP', 'import ../proofs/type_validator_soundness.bend as VS',
                'import ../proofs/compact/found.bend as FD', 'import ../proofs/compact/arith.bend as A', 'import ../proofs/nat_order.bend as Order',
                'import ../spec/codec.bend as Encoding', 'import ../proofs/obj/spec_fixed.bend as SF', 'import ../proofs/obj/vspec.bend as VSP',
                'import ../proofs/obj/vbuf.bend as VB', 'import ../proofs/obj/vcopy.bend as VC', 'import ../proofs/obj/vdepth.bend as VD',
                'import ../proofs/obj/vu32.bend as VU', 'import ../proofs/obj/vlist.bend as VL', 'import ../proofs/obj/vbspec.bend as VZ',
                'import ../proofs/obj/words_obj.bend as WO', 'import ../proofs/obj/words_spec.bend as WS', 'import ../proofs/obj/list_obj.bend as LO',
                'import ../proofs/obj/schema_shapes.bend as SH', f'import ../proofs/obj/big_var_codec_{X}_enc.bend as EN',
                'import ./e2e_support.bend as E', './e2e_cap.bend', './e2e_emit.bend', './e2e_blist.bend']
        imps = imps[:-4] + ['import ./e2e_support.bend as E', 'import ./e2e_cap.bend as C', 'import ./e2e_emit.bend as EM', 'import ./e2e_blist.bend as BL']
        return '\n'.join(imps) + f"""

# GENERATED by codegen/e2e_bridge.py (codegen/e2e_var_b.py). Do not edit.
# {R} (variable size, a byte list): the object API's encoder's bytes are END_TO_END's serialize of the
# object's view, for every object the root law represents (rep) whose storage is at depth below {DB} (hs:
# the encode laws take dw < {DB}, the root law's invariant dw < 32).

# the output's depth DO(N) is below 29, and 4 * 2^DO(N) holds the N bytes
def hdo(+dw: Nat, +N: U32, +hdw: {{Nat.is_lt(dw, {DB}n) == True{{}} : Bool}}, +hn: {HN}) -> {{Nat.is_lt(VL.DO(N), 29n) == True{{}} : Bool}}:
  FD.nat__le_lt_trans(VL.DO(N), dw, 29n, VD.wd_min(VC.nwu(N), dw, EN.nwp(dw, N, hdw, hn)), FD.nat__lt_trans(dw, {DB}n, 29n, hdw, {{==}}))

def hno(+dw: Nat, +N: U32, +hdw: {{Nat.is_lt(dw, {DB}n) == True{{}} : Bool}}, +hn: {HN}) -> {{Nat.is_le(U32.to_nat(N), A.quad(FD.spec_common__pow2(VL.DO(N)))) == True{{}} : Bool}}:
  +h0 = FD.logic__subst(Nat, z => {{Nat.is_le(z, VB.pw(VL.DO(N))) == True{{}} : Bool}}, Nat.add(VC.NW(N), 0n), VC.NW(N), FD.nat__add_zero(VC.NW(N)), EN.hdst(dw, N, hdw, hn))
  FD.nat__le_trans(U32.to_nat(N), A.quad(VC.NW(N)), A.quad(FD.spec_common__pow2(VL.DO(N))), VZ.quad_nw_ge(N, VL.KK(dw), VL.kk_lt(dw, hdw), VL.hyn(dw, N, hn)),
    C.q4(VC.NW(N), FD.spec_common__pow2(VL.DO(N)), h0))

# (i) on storage T of depth dw < {DB} holding N bytes
def a1(+dw: Nat, +T: FD.array__Tree<U32>, +N: U32, +pf: {{FD.array__perfect(U32, dw, T) == True{{}} : Bool}}, +hdw: {{Nat.is_lt(dw, {DB}n) == True{{}} : Bool}},
    +hn: {HN}, +hN: {{U32.is_le(N, {LIM}) == True{{}} : Bool}}) -> {G(OW, f'WO.wview({OW})')}:
  %Equal.sym(O.Words & B.Buf, {ENC(OW)}, ({OW}, B.Buf{{FD.array__thaw(U32, EN.OUT(N, T)), N}}), EN.encode_eval(dw, T, N, pf, hdw, hn, hN)) :
    {{Some{{E.obytes(Pair.snd(O.Words, B.Buf, _))}} == API.serialize(Spec.{X}(), S.BytesValue{{WO.wview({OW})}}) : Maybe<&2, +List<U32>>}}
  %Equal.sym(+List<U32>, E.obytes(B.Buf{{FD.array__thaw(U32, EN.OUT(N, T)), N}}), {BYT},
      EM.ob(VL.DO(N), EN.OUT(N, T), N, VB.mone_perfect(VC.NW(N), 0n, 0n, VL.DO(N), VC.ZT(VL.DO(N)), T, FD.array__trep_perfect(U32, VL.DO(N), 0)), hdo(dw, N, hdw, hn), hno(dw, N, hdw, hn))) :
    {{Some{{_}} == API.serialize(Spec.{X}(), S.BytesValue{{WO.wview({OW})}}) : Maybe<&2, +List<U32>>}}
  %Equal.sym(+List<U32>, WO.wview({OW}), BL.WX0(T, N), BL.wv0(T, N)) :
    {{Some{{{BYT}}} == API.serialize(Spec.{X}(), S.BytesValue{{_}}) : Maybe<&2, +List<U32>>}}
  Equal.sym(Maybe<&2, +List<U32>>, API.serialize(Spec.{X}(), EN.XV(T, N)), Some{{{BYT}}},
    Equal.trans(Maybe<&2, +List<U32>>, API.serialize(Spec.{X}(), EN.XV(T, N)), Encoding.encoding_for_legal_type(Spec.{X}(), EN.XV(T, N)), Some{{{BYT}}},
      E.serialize_legal(Spec.{X}(), EN.XV(T, N), VS.public_sound(Spec.{X}(), {{==}})), EN.encode_spec(dw, T, N, pf, hdw, hn, hN)))

# the schema's limit is the runtime's literal
def elim() -> {{SH.ByteList_limit(Spec.{X}()) == U32.to_nat({LIM}) : Nat}}: {{==}}

# the runtime's length check from rep's limit
def lim(+N: U32, +hl: {{Nat.is_le(U32.to_nat(N), SH.ByteList_limit(Spec.{X}())) == True{{}} : Bool}}) -> {{U32.is_le(N, {LIM}) == True{{}} : Bool}}:
  %Equal.sym(Bool, U32.is_le(N, {LIM}), Nat.is_le(U32.to_nat(N), U32.to_nat({LIM})), VU.le_u32(N, {LIM})) : {{_ == True{{}} : Bool}}
  %elim() : {{Nat.is_le(U32.to_nat(N), _) == True{{}} : Bool}}
  hl

# ---- (i) from the representation ----

def e2(-o: O.Words, +t: FD.array__Tree<U32>, +dw: Nat, +N: U32, +eo: {{o == O.Words{{FD.array__thaw(U32, t), N}} : O.Words}}, +pf: {{FD.array__perfect(U32, dw, t) == True{{}} : Bool}},
    +hdw: {{Nat.is_lt(dw, {DB}n) == True{{}} : Bool}}, +hn: {{Nat.is_le(U32.to_nat(N), A.quad(VB.pw(dw))) == True{{}} : Bool}},
    +hl: {{Nat.is_le(U32.to_nat(WO.len(o)), SH.ByteList_limit(Spec.{X}())) == True{{}} : Bool}}) -> {G('o', 'WO.wview(o)')}:
  +hN = lim(N, FD.logic__subst(O.Words, z => {{Nat.is_le(U32.to_nat(WO.len(z)), SH.ByteList_limit(Spec.{X}())) == True{{}} : Bool}}, o, O.Words{{FD.array__thaw(U32, t), N}}, eo, hl))
  %Equal.sym(O.Words, o, O.Words{{FD.array__thaw(U32, t), N}}, eo) : {G('_', 'WO.wview(_)')}
  a1(dw, t, N, pf, hdw, hn, hN)

# (i): for every object the root law represents, its storage at depth below {DB} (hs)
def {R}_e2e_encode(-o: O.Words, +rep: LO.rep_bl(o, Spec.{X}()), +hs: BL.sdk(o, {DB}n)) -> {G('o', 'WO.wview(o)')}:
  (+wf, +hl) = rep
  match hs:
    case Inl{{s}}:
      (+t, s1) = s
      (+dw, s2) = s1
      (+N, s3) = s2
      (+eo, s4) = s3
      (+pf, s5) = s4
      (+hdw, +en0) = s5
      +hn = FD.logic__subst(Nat, z => {{Nat.is_le(z, A.quad(VB.pw(dw))) == True{{}} : Bool}}, 0n, U32.to_nat(N), Equal.sym(Nat, U32.to_nat(N), 0n, en0), Order.zero_le(A.quad(VB.pw(dw))))
      e2(o, t, dw, N, eo, pf, hdw, hn, hl)
    case Inr{{s}}:
      (+t, s1) = s
      (+dw, s2) = s1
      (+N, s3) = s2
      (+q, s4) = s3
      (+r, s5) = s4
      (+eo, s6) = s5
      (+pf, s7) = s6
      (+hdw, s8) = s7
      (+eN, s9) = s8
      (+hr0, s10) = s9
      (+hr32, s11) = s10
      (+hcap, +bz) = s11
      +hq = FD.logic__subst(Nat, z => {{Nat.is_le(z, A.quad(O.e8(1n+q))) == True{{}} : Bool}}, Nat.add(r, WS.e32(q)), U32.to_nat(N),
        Equal.sym(Nat, U32.to_nat(N), Nat.add(r, WS.e32(q)), Equal.trans(Nat, U32.to_nat(N), Nat.add(WS.e32(q), r), Nat.add(r, WS.e32(q)), eN, FD.nat__add_comm(WS.e32(q), r))),
        Order.add_right(r, 32n, WS.e32(q), hr32))
      +hn = FD.nat__le_trans(U32.to_nat(N), A.quad(O.e8(1n+q)), A.quad(VB.pw(dw)), hq, C.q4(O.e8(1n+q), FD.spec_common__pow2(dw), hcap))
      e2(o, t, dw, N, eo, pf, hdw, hn, hl)
"""
    return f


VENC_SHAPES['Transaction'] = venc_bytelist(28, 1073741824)
VENC_PREMISE['Transaction'] = 'rep: LO.rep_bl(o, Spec.Transaction()) and hs: BL.sdk(o, 28n) (its storage at depth below 28: the encode laws take dw < 28, the root law dw < 32; dropped when the encode laws take dw < 32)'
