"""The block body's lists of variable-size elements read at a byte window (e2e-c's share of the block decode
bridges (ii)/(iii)): the attestations (vvl_l8_Attestation) and the attester slashings
(vvl_l1_AttesterSlashing), at any tree depth d < 31 with the window's end below 2^32 (hw32).

codegen/e2e_bridge.py writes the modules (e2e_var_b's SUPPORT_OUT imports them from here):
  e2e/e2e_wxa.bend                         the elements at a window at any byte offset (var_winx_*): the
                                           view lemmas vw_Attestation / vw_AttesterSlashing (root view == the
                                           window's value) and tf_Attestation / tf_AttesterSlashing (the object
                                           survives RT.fz then RT.th)
  e2e/e2e_vlm_l8_Attestation.bend          vl: RT.xv_l8_Attestation(W.OBJw(..)) == W.VALw(..)
  e2e/e2e_vlm_l1_AttesterSlashing.bend     vl: RT.xv_l1_AttesterSlashing(W.OBJw(..)) == W.VALw(..)
The list modules are e2e_var_c's progressive-list template (GVL_PER) at depth d < 31 with hw32 threaded, the
list's limit conjunct in its head check (HC), the root_types_light mirrors and root_types' array lemmas.
"""

import re
from pathlib import Path

import e2e_var_c as EVC
from light_split import unlight as _unlight

ROOT = Path(__file__).resolve().parents[1]
GEN = 'codegen/e2e_bridge.py (codegen/e2e_vlm_vvl.py)'


def _src(name):
    return _unlight((ROOT / 'proofs/obj' / name).read_text())


WPD = ('+d: Nat, +t: FD.array__Tree<U32>, +x: Nat, +off: U32, +len: U32, +eo: {U32.to_nat(off) == x : Nat}, +hd: {Nat.is_lt(d, 31n) == True{} : Bool},\n'
       '    +hw: {Nat.is_le(Nat.add(x, U32.to_nat(len)), A.quad(VB.pw(d))) == True{} : Bool}, +hw32: {Nat.is_lt(Nat.add(x, U32.to_nat(len)), FD.spec_common__pow2(32n)) == True{} : Bool},\n'
       '    +pf: {FD.array__perfect(U32, d, t) == True{} : Bool}')


def _bv64(ya):
    """the Attestation window's aggregation bits words: its OBJw's Bitvector64{u, v}"""
    m = re.search(r'^def OBJw\(.*?Fulu_bitvector_64_d\.Bitvector64\{(UR\.RWN\(t, \d+n\+x\)), (UR\.RWN\(t, \d+n\+x\))\}', _src(ya), re.M)
    return m.group(1), m.group(2)


def wxa_text():
    u, v = _bv64('var_winx_Attestation.bend')
    # the fixed parts' offsets the element windows use (asserted: the lemmas below are written for them)
    assert re.search(r'^def JW\(\+x: Nat\) -> Nat: Nat\.add\(236n, x\)$', _src('var_winx_Attestation.bend'), re.M)
    assert re.search(r'^def JW\(\+x: Nat\) -> Nat: Nat\.add\(228n, x\)$', _src('var_winx_IndexedAttestation.bend'), re.M)
    K = int(re.search(r'^def hyL\(.*?VB\.pw\((\d+)n\)\) == True', _src('var_winx_l131072_u64.bend'), re.M).group(1))
    head = '''import Base
import ../src/obj.bend as O
import ../types/schema.bend as S
import ../types/primitive.bend as P
import ../proofs/compact/found.bend as FD
import ../proofs/compact/arith.bend as A
import ../proofs/nat_order.bend as Order
import ../proofs/obj/vbuf.bend as VB
import ../proofs/obj/vcopy.bend as VC
import ../proofs/obj/vdepth.bend as VD
import ../proofs/obj/vspec.bend as VS
import ../proofs/obj/spec_fixed.bend as SF
import ../proofs/obj/spec_bits.bend as FB
import ../proofs/obj/vbig.bend as VBG
import ../proofs/obj/vlist.bend as VLS
import ../proofs/obj/vbitl.bend as VBL
import ../proofs/obj/vbrt.bend as VR
import ../proofs/obj/vpb29.bend as VP
import ../proofs/obj/vua_win.bend as UW
import ../proofs/obj/vua_ct.bend as UCT
import ../proofs/obj/vua_rd.bend as UR
import ../proofs/obj/var_elems.bend as EL
import ../proofs/obj/words_obj_light.bend as WO
import ../proofs/obj/bitlist_obj_light.bend as BO
import ../proofs/obj/ulist_obj_light.bend as UL
import ../proofs/obj/root_types_light.bend as RT
import ../proofs/obj/root_names_light.bend as RN
import ../proofs/obj/var_winx_bits131072.bend as W131
import ../proofs/obj/var_winx_l131072_u64.bend as WU
import ../proofs/obj/var_winx_Attestation.bend as YA
import ../proofs/obj/var_winx_IndexedAttestation.bend as YI
import ../proofs/obj/var_winx_AttesterSlashing.bend as YS
import ../types/Fulu_bitvector_64_def_generated.bend as Fulu_bitvector_64_d
import ../types/FuluBytes96_def_generated.bend as FuluBytes96_d
import ../types/FuluAttestationData_def_generated.bend as FuluAttestationData_d
import ../types/FuluAttestation_def_generated.bend as FuluAttestation_d
import ../types/FuluIndexedAttestation_def_generated.bend as FuluIndexedAttestation_d
import ../types/FuluAttesterSlashing_def_generated.bend as FuluAttesterSlashing_d
import ./e2e_bits.bend as E2B
import ./e2e_blist.bend as BL
import ./e2e_gpb.bend as GPB
import ./e2e_plw.bend as PW
import ./e2e_bx.bend as BXW
'''
    body = r'''
# GENERATED by @GEN@. Do not edit.
# The block body's variable-size list elements at a window at any byte offset (var_winx_*), at any tree
# depth d < 31 with the window's end below 2^32 (hw32): vw_E, the object's root view is the window's value;
# tf_E, the object survives RT.fz_E then RT.th_E (the list views' mirrors, e2e_vlm_*).

def thfr(a: Array<U32>) -> {FD.array__thaw(U32, FD.array__freeze(U32, a)) == a : Array<U32>}:
  match a:
    case ALeaf{+v}: {==}
    case ANode{l, r}:
      %Equal.sym(Array<U32>, FD.array__thaw(U32, FD.array__freeze(U32, l)), l, thfr(l)) : {ANode{_, FD.array__thaw(U32, FD.array__freeze(U32, r))} == ANode{l, r} : Array<U32>}
      %Equal.sym(Array<U32>, FD.array__thaw(U32, FD.array__freeze(U32, r)), r, thfr(r)) : {ANode{l, _} == ANode{l, r} : Array<U32>}
      {==}

# ---- a BitList[131072] (var_winx_bits131072) ----
# len - 1 < 2^29 from the limit's len <= 16385 (2^15 <= 2^29, the exponents symbolic)
def lt29B(+len: U32, +m: Nat, +e1: {U32.to_nat(len) == 1n+m : Nat}, +hb: {Nat.is_le(U32.to_nat(len), 16385n) == True{} : Bool})
    -> {U32.is_lt(U32.sub(len, 1), 536870912) == True{} : Bool}:
  +hq = FD.nat__le_trans(U32.to_nat(len), FD.spec_common__pow2(15n), FD.spec_common__pow2(29n),
    FD.nat__le_trans(U32.to_nat(len), 16385n, FD.spec_common__pow2(15n), hb, {==}), FD.nat__pow2_mono(15n, 29n, {==}))
  +h1m = FD.logic__subst(Nat, z => {Nat.is_le(z, FD.spec_common__pow2(29n)) == True{} : Bool}, U32.to_nat(len), 1n+m, e1, hq)
  +hm = FD.nat__succ_le_lt(m, FD.spec_common__pow2(29n), h1m)
  +hs = FD.logic__subst(Nat, z => {Nat.is_lt(z, FD.spec_common__pow2(29n)) == True{} : Bool}, m, U32.to_nat(U32.sub(len, 1)), Equal.sym(Nat, U32.to_nat(U32.sub(len, 1)), m, VP.em1(len, m, e1)), hm)
  Equal.trans(Bool, U32.is_lt(U32.sub(len, 1), FD.u32__pow2u(29n)), Nat.is_lt(U32.to_nat(U32.sub(len, 1)), FD.spec_common__pow2(29n)), True{},
    Equal.sym(Bool, Nat.is_lt(U32.to_nat(U32.sub(len, 1)), FD.spec_common__pow2(29n)), U32.is_lt(U32.sub(len, 1), FD.u32__pow2u(29n)),
      FD.array__lt_bridge(U32.sub(len, 1), 29n, {==}, U32.is_lt(U32.sub(len, 1), FD.u32__pow2u(29n)), {==})),
    hs)

# its bits are the window's (e2e_gpb.pbc; the copy bounded by the limit: W131.hyB)
def bvx(@WPD@, +hchk: {W131.CHKw(t, x, off, len) == True{} : Bool})
    -> {BO.bview(W131.OBJw(d, t, x, off, len)) == VBL.bl(UW.WX(t, x, U32.to_nat(len))) : +List<Bool>}:
  +e1 = W131.cE(t, x, off, len, hchk)
  +m = W131.M1(len)
  +h1 = W131.c1(t, x, off, len, hchk)
  +hb = W131.hB(t, off, len, e1, W131.cC(t, off, len, h1, W131.cB(t, off, len, h1)))
  +h29 = lt29B(len, m, e1, hb)
  +M = UCT.CT(d, t, off, len, VLS.DZ(len))
  +hw1 = FD.logic__subst(Nat, z => {Nat.is_le(Nat.add(x, z), A.quad(VB.pw(d))) == True{} : Bool}, U32.to_nat(len), 1n+m, e1, hw)
  +hy = FD.nat__le_trans(VC.YL(len), VB.pw(15n), U32.to_nat(VB.UMAX()), W131.hyB(len, hb), VC.pw_umax(15n, {==}))
  +ewl = Equal.trans(+List<U32>, VS.bt(U32.to_nat(len), SF.limbs(FD.array__slots(U32, M))), WO.wview(O.Words{FD.array__thaw(U32, M), len}), UW.WX(t, x, U32.to_nat(len)),
    Equal.sym(+List<U32>, WO.wview(O.Words{FD.array__thaw(U32, M), len}), VS.bt(U32.to_nat(len), SF.limbs(FD.array__slots(U32, M))), BL.wvb(M, len)), BL.bviewY(d, t, off, len, x, eo, hw, pf, hy))
  GPB.pbc(t, x, off, len, M, GPB.ctp(VR.RX(off), d, t, off, len, VLS.DZ(len)), m, e1, h29, ewl, UW.lenWX(d, t, x, 1n+m, pf, hw1),
    UW.lastWX(d, t, x, m, VR.XN(off, len), pf, hw1, W131.eX(d, x, off, len, eo, hd, hw, hw32, e1)))

# ---- a List[uint64, 131072] (var_winx_l131072_u64): its first 2 c words are the window's ----
# the two uitems (ulist_obj, vspec) agree
def uu(+k: Nat, +W: List<&2, U32>) -> {UL.uitems(k, W) == VS.uitems(k, W) : S.Value}:
  match k W:
    case 0n _: {==}
    case 1n+ +c Nil{}: {==}
    case 1n+ +c Con{+a, Nil{}}: {==}
    case 1n+ +c Con{+a, Con{+b, +rest}}: Equal.cong(S.Value, S.Value, z => S.Items{S.UnsignedValue{P.UInt{a, b, 0, 0, 0, 0, 0, 0}}, z}, UL.uitems(c, rest), VS.uitems(c, rest), uu(c, rest))
# ... and read only the first 2 k words
def ut(+k: Nat, +W: List<&2, U32>) -> {VS.uitems(k, W) == VS.uitems(k, VS.wtake(Nat.double(k), W)) : S.Value}:
  match k W:
    case 0n _: {==}
    case 1n+ +c Nil{}: {==}
    case 1n+ +c Con{+a, Nil{}}: {==}
    case 1n+ +c Con{+a, Con{+b, +rest}}: Equal.cong(S.Value, S.Value, z => S.Items{S.UnsignedValue{P.UInt{a, b, 0, 0, 0, 0, 0, 0}}, z}, VS.uitems(c, rest), VS.uitems(c, VS.wtake(Nat.double(c), rest)), ut(c, rest))
def xb2(+c: Nat) -> {VS.x8(c) == EL.b2(c) : Nat}:
  match c:
    case 0n: {==}
    case 1n+ +q: Equal.cong(Nat, Nat, z => 8n+z, VS.x8(q), EL.b2(q), xb2(q))

def uvx(@WPD@, +hc: {WU.CHKw(t, x, off, len) == True{} : Bool}) -> {UL.uview(WU.OBJw(d, t, x, off, len)) == WU.VALw(t, x, len) : S.Value}:
  +c = WU.CQ(len)
  +M = UCT.CT(d, t, off, len, VLS.DZ(len))
  +el = WU.eLc(t, x, off, len, hc)
  +ec = Equal.trans(Nat, U32.to_nat(U32.shrn(len, 3n)), VD.s_rng(3n, U32.to_nat(len)), c, VD.shrk(3n, len),
    Equal.trans(Nat, VD.s_rng(3n, U32.to_nat(len)), VD.s_rng(3n, EL.b2(c)), c,
      Equal.cong(Nat, Nat, z => VD.s_rng(3n, z), U32.to_nat(len), EL.b2(c), Equal.trans(Nat, U32.to_nat(len), VS.x8(c), EL.b2(c), el, xb2(c))), PW.rb2(c)))
  +eL = Equal.trans(Nat, U32.to_nat(len), VS.x8(c), A.quad(Nat.double(c)), el, Equal.trans(Nat, VS.x8(c), Nat.mul(c, 8n), A.quad(Nat.double(c)), Equal.sym(Nat, Nat.mul(c, 8n), VS.x8(c), VC.x8_mul(c)), VBG.mul8(c)))
  +hy = FD.nat__le_trans(VC.YL(len), VB.pw(@K@n), U32.to_nat(VB.UMAX()), WU.hyL(t, x, off, len, hc), VC.pw_umax(@K@n, {==}))
  +ew = BXW.ctwY(d, t, off, len, VLS.DZ(len), x, Nat.double(c), eo, hy, hw, pf, VC.hrgU(len, hy), eL)
  %Equal.sym(FD.array__Tree<U32>, FD.array__freeze(U32, FD.array__thaw(U32, M)), M, FD.array__freeze_thaw(U32, M)) :
    {S.Sequence{UL.uitems(U32.to_nat(U32.shrn(len, 3n)), FD.array__slots(U32, _))} == WU.VALw(t, x, len) : S.Value}
  %Equal.sym(Nat, U32.to_nat(U32.shrn(len, 3n)), c, ec) : {S.Sequence{UL.uitems(_, FD.array__slots(U32, M))} == WU.VALw(t, x, len) : S.Value}
  %Equal.sym(S.Value, UL.uitems(c, FD.array__slots(U32, M)), VS.uitems(c, FD.array__slots(U32, M)), uu(c, FD.array__slots(U32, M))) : {S.Sequence{_} == WU.VALw(t, x, len) : S.Value}
  %Equal.sym(S.Value, VS.uitems(c, FD.array__slots(U32, M)), VS.uitems(c, VS.wtake(Nat.double(c), FD.array__slots(U32, M))), ut(c, FD.array__slots(U32, M))) : {S.Sequence{_} == WU.VALw(t, x, len) : S.Value}
  %Equal.sym(List<&2, U32>, VS.wtake(Nat.double(c), FD.array__slots(U32, M)), UR.RWS(Nat.double(c), t, x), ew) : {S.Sequence{VS.uitems(c, _)} == WU.VALw(t, x, len) : S.Value}
  {==}

# ---- Attestation (var_winx_Attestation) ----
def adA(o: FuluAttestation_d.Attestation) -> FuluAttestationData_d.AttestationData:
  match o:
    case FuluAttestation_d.Attestation{x0, +x1, +x2, +x3}: x1
def sgA(o: FuluAttestation_d.Attestation) -> FuluBytes96_d.Bytes96:
  match o:
    case FuluAttestation_d.Attestation{x0, +x1, +x2, +x3}: x2
def bvA(o: FuluAttestation_d.Attestation) -> Fulu_bitvector_64_d.Bitvector64:
  match o:
    case FuluAttestation_d.Attestation{x0, +x1, +x2, +x3}: x3

# the root view from its bits' view (the aggregation bits' words as the spec's bit vector: E2B.bw)
def att4(+M: FD.array__Tree<U32>, +k: U32, +b2: +List<Bool>, +e: {BO.bview(O.Bits{O.clear_bit(FD.array__thaw(U32, M), k), k}) == b2 : +List<Bool>},
    +ad: FuluAttestationData_d.AttestationData, +sg: FuluBytes96_d.Bytes96, +u: U32, +v: U32)
    -> {RT.v_Attestation(FuluAttestation_d.Attestation{O.Bits{O.clear_bit(FD.array__thaw(U32, M), k), k}, ad, sg, Fulu_bitvector_64_d.Bitvector64{u, v}})
        == S.Sequence{S.Items{S.BitsValue{b2}, S.Items{RN.v_AttestationData(ad), S.Items{RN.v_b96(sg), S.Items{S.BitsValue{FB.bitsof([u, v])}, S.EmptyItems{}}}}}} : S.Value}:
  %Equal.sym(+List<Bool>, FB.bitsof([u, v]), E2B.wcat([u, v]), E2B.bw([u, v])) :
    {RT.v_Attestation(FuluAttestation_d.Attestation{O.Bits{O.clear_bit(FD.array__thaw(U32, M), k), k}, ad, sg, Fulu_bitvector_64_d.Bitvector64{u, v}})
        == S.Sequence{S.Items{S.BitsValue{b2}, S.Items{RN.v_AttestationData(ad), S.Items{RN.v_b96(sg), S.Items{S.BitsValue{_}, S.EmptyItems{}}}}}} : S.Value}
  Equal.cong(+List<Bool>, S.Value, z => S.Sequence{S.Items{S.BitsValue{z}, S.Items{RN.v_AttestationData(ad), S.Items{RN.v_b96(sg), S.Items{S.BitsValue{E2B.wcat([u, v])}, S.EmptyItems{}}}}}},
    BO.bview(O.Bits{O.clear_bit(FD.array__thaw(U32, M), k), k}), b2, e)

def vw_Attestation(@WPD@, +hc: {YA.CHKw(t, x, off, len) == True{} : Bool})
    -> {RT.v_Attestation(YA.OBJw(d, t, x, off, len)) == YA.VALw(t, x, len) : S.Value}:
  +a = U32.is_le(236, len)
  +b = U32.is_eq(YA.SPOw(t, x), 236)
  +c = W131.CHKw(t, YA.JW(x), YA.OWc(off), YA.LLw(len))
  +ha = YA.ch_a(a, b, c, hc)
  +e1 = bvx(d, t, YA.JW(x), YA.OWc(off), YA.LLw(len), YA.eoF(d, t, 0, x, off, len, eo, hd, hw, hw32, pf, ha), hd,
    YA.hwc(d, t, 0, x, off, len, eo, hd, hw, hw32, pf, ha), YA.hwc32(d, t, 0, x, off, len, eo, hd, hw, hw32, pf, ha), pf, YA.ch_c(a, b, c, hc))
  att4(UCT.CT(d, t, YA.OWc(off), YA.LLw(len), VLS.DZ(YA.LLw(len))), W131.NB(t, YA.OWc(off), YA.LLw(len)), VBL.bl(UW.WX(t, YA.JW(x), U32.to_nat(YA.LLw(len)))), e1,
    adA(YA.OBJw(d, t, x, off, len)), sgA(YA.OBJw(d, t, x, off, len)), @U@, @V@)

def tf_Attestation(@WPD@, +hc: {YA.CHKw(t, x, off, len) == True{} : Bool})
    -> {RT.th_Attestation(RT.fz_Attestation(YA.OBJw(d, t, x, off, len))) == YA.OBJw(d, t, x, off, len) : FuluAttestation_d.Attestation}:
  +k = W131.NB(t, YA.OWc(off), YA.LLw(len))
  +M = UCT.CT(d, t, YA.OWc(off), YA.LLw(len), VLS.DZ(YA.LLw(len)))
  %Equal.sym(Array<U32>, FD.array__thaw(U32, FD.array__freeze(U32, O.clear_bit(FD.array__thaw(U32, M), k))), O.clear_bit(FD.array__thaw(U32, M), k), thfr(O.clear_bit(FD.array__thaw(U32, M), k))) :
    {FuluAttestation_d.Attestation{O.Bits{_, k}, adA(YA.OBJw(d, t, x, off, len)), sgA(YA.OBJw(d, t, x, off, len)), bvA(YA.OBJw(d, t, x, off, len))} == YA.OBJw(d, t, x, off, len) : FuluAttestation_d.Attestation}
  {==}

# ---- IndexedAttestation (var_winx_IndexedAttestation) ----
def adI(o: FuluIndexedAttestation_d.IndexedAttestation) -> FuluAttestationData_d.AttestationData:
  match o:
    case FuluIndexedAttestation_d.IndexedAttestation{x0, +x1, +x2}: x1
def sgI(o: FuluIndexedAttestation_d.IndexedAttestation) -> FuluBytes96_d.Bytes96:
  match o:
    case FuluIndexedAttestation_d.IndexedAttestation{x0, +x1, +x2}: x2

def ia3(+M: FD.array__Tree<U32>, +n: U32, +V: S.Value, +e: {UL.uview(O.Words{FD.array__thaw(U32, M), n}) == V : S.Value},
    +ad: FuluAttestationData_d.AttestationData, +sg: FuluBytes96_d.Bytes96)
    -> {RT.v_IndexedAttestation(FuluIndexedAttestation_d.IndexedAttestation{O.Words{FD.array__thaw(U32, M), n}, ad, sg})
        == S.Sequence{S.Items{V, S.Items{RN.v_AttestationData(ad), S.Items{RN.v_b96(sg), S.EmptyItems{}}}}} : S.Value}:
  Equal.cong(S.Value, S.Value, z => S.Sequence{S.Items{z, S.Items{RN.v_AttestationData(ad), S.Items{RN.v_b96(sg), S.EmptyItems{}}}}}, UL.uview(O.Words{FD.array__thaw(U32, M), n}), V, e)

def vw_IndexedAttestation(@WPD@, +hc: {YI.CHKw(t, x, off, len) == True{} : Bool})
    -> {RT.v_IndexedAttestation(YI.OBJw(d, t, x, off, len)) == YI.VALw(t, x, len) : S.Value}:
  +a = U32.is_le(228, len)
  +b = U32.is_eq(YI.SPOw(t, x), 228)
  +c = WU.CHKw(t, YI.JW(x), YI.OWc(off), YI.LLw(len))
  +ha = YI.ch_a(a, b, c, hc)
  +e1 = uvx(d, t, YI.JW(x), YI.OWc(off), YI.LLw(len), YI.eoF(d, t, 0, x, off, len, eo, hd, hw, hw32, pf, ha), hd,
    YI.hwc(d, t, 0, x, off, len, eo, hd, hw, hw32, pf, ha), YI.hwc32(d, t, 0, x, off, len, eo, hd, hw, hw32, pf, ha), pf, YI.ch_c(a, b, c, hc))
  ia3(UCT.CT(d, t, YI.OWc(off), YI.LLw(len), VLS.DZ(YI.LLw(len))), YI.LLw(len), WU.VALw(t, YI.JW(x), YI.LLw(len)), e1,
    adI(YI.OBJw(d, t, x, off, len)), sgI(YI.OBJw(d, t, x, off, len)))

# ---- AttesterSlashing (var_winx_AttesterSlashing): two IndexedAttestation windows ----
def vw_AttesterSlashing(@WPD@, +hc: {YS.CHKw(t, x, off, len) == True{} : Bool})
    -> {RT.v_AttesterSlashing(YS.OBJw(d, t, x, off, len)) == YS.VALw(t, x, len) : S.Value}:
  +r1 = YS.ck(U32.is_eq(YS.O0(t, x), 8), YS.ck(YS.RR(t, x, len), YS.ck(YS.D0(t, x, off), YS.D1(t, x, off, len))))
  +r2 = YS.ck(YS.RR(t, x, len), YS.ck(YS.D0(t, x, off), YS.D1(t, x, off, len)))
  +r3 = YS.ck(YS.D0(t, x, off), YS.D1(t, x, off, len))
  +h1 = YS.ck_b(U32.is_le(8, len), r1, hc)
  +h2 = YS.ck_b(U32.is_eq(YS.O0(t, x), 8), r2, h1)
  +h3 = YS.ck_b(YS.RR(t, x, len), r3, h2)
  +hr = YS.ck_a(YS.RR(t, x, len), r3, h2)
  +h01 = YS.le_nat(YS.O0(t, x), YS.O1(t, x), FD.logic__and_left(U32.is_le(YS.O0(t, x), YS.O1(t, x)), U32.is_le(YS.O1(t, x), len), hr))
  +h1n = YS.le_nat(YS.O1(t, x), len, FD.logic__and_right(U32.is_le(YS.O0(t, x), YS.O1(t, x)), U32.is_le(YS.O1(t, x), len), hr))
  +e0 = vw_IndexedAttestation(d, t, YS.J0(t, x), YS.W0(t, x, off), YS.L0(t, x),
    YS.eoj(d, t, 0, x, off, len, eo, hd, hw, hw32, pf, YS.O0(t, x), FD.nat__le_trans(U32.to_nat(YS.O0(t, x)), U32.to_nat(YS.O1(t, x)), U32.to_nat(len), h01, h1n)), hd,
    YS.hwj(d, t, 0, x, off, len, eo, hd, hw, hw32, pf, YS.O0(t, x), YS.O1(t, x), h01, h1n), YS.hwj32(d, t, 0, x, off, len, eo, hd, hw, hw32, pf, YS.O0(t, x), YS.O1(t, x), h01, h1n), pf,
    YS.ck_a(YS.D0(t, x, off), YS.D1(t, x, off, len), h3))
  +e1 = vw_IndexedAttestation(d, t, YS.J1(t, x), YS.W1(t, x, off), YS.L1(t, x, len),
    YS.eoj(d, t, 0, x, off, len, eo, hd, hw, hw32, pf, YS.O1(t, x), h1n), hd,
    YS.hwj(d, t, 0, x, off, len, eo, hd, hw, hw32, pf, YS.O1(t, x), len, h1n, FD.nat__le_refl(U32.to_nat(len))),
    YS.hwj32(d, t, 0, x, off, len, eo, hd, hw, hw32, pf, YS.O1(t, x), len, h1n, FD.nat__le_refl(U32.to_nat(len))), pf,
    YS.ck_b(YS.D0(t, x, off), YS.D1(t, x, off, len), h3))
  +V0 = YI.VALw(t, YS.J0(t, x), YS.L0(t, x))
  +V1 = YI.VALw(t, YS.J1(t, x), YS.L1(t, x, len))
  +A0 = RT.v_IndexedAttestation(YI.OBJw(d, t, YS.J0(t, x), YS.W0(t, x, off), YS.L0(t, x)))
  +A1 = RT.v_IndexedAttestation(YI.OBJw(d, t, YS.J1(t, x), YS.W1(t, x, off), YS.L1(t, x, len)))
  Equal.trans(S.Value, S.Sequence{S.Items{A0, S.Items{A1, S.EmptyItems{}}}}, S.Sequence{S.Items{V0, S.Items{A1, S.EmptyItems{}}}}, S.Sequence{S.Items{V0, S.Items{V1, S.EmptyItems{}}}},
    Equal.cong(S.Value, S.Value, z => S.Sequence{S.Items{z, S.Items{A1, S.EmptyItems{}}}}, A0, V0, e0),
    Equal.cong(S.Value, S.Value, z => S.Sequence{S.Items{V0, S.Items{z, S.EmptyItems{}}}}, A1, V1, e1))

def tf_AttesterSlashing(@WPD@, +hc: {YS.CHKw(t, x, off, len) == True{} : Bool})
    -> {RT.th_AttesterSlashing(RT.fz_AttesterSlashing(YS.OBJw(d, t, x, off, len))) == YS.OBJw(d, t, x, off, len) : FuluAttesterSlashing_d.AttesterSlashing}:
  +J0 = YS.J0(t, x)
  +F0 = YS.W0(t, x, off)
  +L0 = YS.L0(t, x)
  +J1 = YS.J1(t, x)
  +F1 = YS.W1(t, x, off)
  +L1 = YS.L1(t, x, len)
  +C0 = UCT.CT(d, t, YI.OWc(F0), YI.LLw(L0), VLS.DZ(YI.LLw(L0)))
  +C1 = UCT.CT(d, t, YI.OWc(F1), YI.LLw(L1), VLS.DZ(YI.LLw(L1)))
  %Equal.sym(FD.array__Tree<U32>, FD.array__freeze(U32, FD.array__thaw(U32, C0)), C0, FD.array__freeze_thaw(U32, C0)) :
    {FuluAttesterSlashing_d.AttesterSlashing{O.BSome{FuluIndexedAttestation_d.IndexedAttestation{O.Words{FD.array__thaw(U32, _), YI.LLw(L0)}, adI(YI.OBJw(d, t, J0, F0, L0)), sgI(YI.OBJw(d, t, J0, F0, L0))}, O.BNone{}},
      O.BSome{FuluIndexedAttestation_d.IndexedAttestation{O.Words{FD.array__thaw(U32, FD.array__freeze(U32, FD.array__thaw(U32, C1))), YI.LLw(L1)}, adI(YI.OBJw(d, t, J1, F1, L1)), sgI(YI.OBJw(d, t, J1, F1, L1))}, O.BNone{}}}
      == YS.OBJw(d, t, x, off, len) : FuluAttesterSlashing_d.AttesterSlashing}
  %Equal.sym(FD.array__Tree<U32>, FD.array__freeze(U32, FD.array__thaw(U32, C1)), C1, FD.array__freeze_thaw(U32, C1)) :
    {FuluAttesterSlashing_d.AttesterSlashing{O.BSome{FuluIndexedAttestation_d.IndexedAttestation{O.Words{FD.array__thaw(U32, C0), YI.LLw(L0)}, adI(YI.OBJw(d, t, J0, F0, L0)), sgI(YI.OBJw(d, t, J0, F0, L0))}, O.BNone{}},
      O.BSome{FuluIndexedAttestation_d.IndexedAttestation{O.Words{FD.array__thaw(U32, _), YI.LLw(L1)}, adI(YI.OBJw(d, t, J1, F1, L1)), sgI(YI.OBJw(d, t, J1, F1, L1))}, O.BNone{}}}
      == YS.OBJw(d, t, x, off, len) : FuluAttesterSlashing_d.AttesterSlashing}
  {==}
'''
    body = body.replace('@WPD@', WPD).replace('@GEN@', GEN).replace('@K@', str(K)).replace('@U@', u).replace('@V@', v)
    return head + body


# the lists: (vvl module, element E, element def module alias and file, list def module alias and file)
VLM = {
    'l8_Attestation': ('vvl_l8_Attestation', 'Attestation', ('FuluAttestation_d', 'FuluAttestation_def_generated'),
                       ('Fulu_list_Attestation_8_d', 'Fulu_list_Attestation_8_def_generated')),
    'l1_AttesterSlashing': ('vvl_l1_AttesterSlashing', 'AttesterSlashing', ('FuluAttesterSlashing_d', 'FuluAttesterSlashing_def_generated'),
                            ('Fulu_list_AttesterSlashing_1_d', 'Fulu_list_AttesterSlashing_1_def_generated')),
}


def _ea_deep(TX):
    """the element's window arguments (d, t, x, off, len, eo, hd, hw, hw32, pf, hc) from EE(True, .., s, e) == True (h)."""
    hab = f'{TX}.el_ab(t, x, off, len, s, e, h)'
    hb = f'{TX}.el_b(t, x, off, len, s, e, h)'
    return (f'd, t, Nat.add(U32.to_nat(s), x), U32.add(off, s), U32.sub(e, s), '
            f'{TX}.eocD(d, x, off, len, s, FD.nat__le_trans(U32.to_nat(s), U32.to_nat(e), U32.to_nat(len), {hab}, {hb}), eo, hd, hw, hw32), hd, '
            f'{TX}.hwab(d, x, len, s, e, {hab}, {hb}, hw), {TX}.hwab32(x, len, s, e, {hab}, {hb}, hw32), pf, {TX}.el_c(t, x, off, len, s, e, h)')


def vlm_text(L):
    mod, E, (EA, EF), (LD, LF) = VLM[L]
    src = _src(mod + '.bend')
    lim = re.search(r'^def HC\(\+f: U32, \+len: U32\) -> Bool: Bool\.and\(Bool\.and\(U32\.is_eq\(U32\.and\(f, 3\), 0\), U32\.is_le\(f, len\)\), '
                    r'Bool\.and\(U32\.is_le\(4, f\), (U32\.is_le\(U32\.shrn\(f, 2n\), \d+\))\)\)$', src, re.M).group(1)
    assert re.search(r'^import \./var_winx_' + E + r'\.bend as YW$', src, re.M)
    shared = EVC.GVL_SHARED.split('# ---- VarTestStruct elements')[0]
    assert '@' not in shared
    TX = 'W'
    pre = EVC.GVL_PRE
    for a, b in [('FD.nat__lt_trans(d, 28n, 32n, hd, {==})', 'FD.nat__lt_trans(d, 31n, 32n, hd, {==})'),
                 ('@TX@.hlen(d, x, len, hw)', '@TX@.hlen(d, x, len, hw, hw32)'),
                 ('Bool.and(U32.is_le(4, f), True{})', f'Bool.and(U32.is_le(4, f), {lim})'),
                 ('FD.logic__and_left(U32.is_le(4, f), True{}, hB)', f'FD.logic__and_left(U32.is_le(4, f), {lim}, hB)')]:
        assert a in pre, a
        pre = pre.replace(a, b)
    txt = EVC.GVL_PER.replace('@PRE@', pre).replace('@EA@', _ea_deep(TX)).replace('@WP@', WPD)
    n0 = txt.count('eo, hd, hw, pf')
    assert n0 >= 8, n0
    txt = txt.replace('eo, hd, hw, pf', 'eo, hd, hw, hw32, pf')
    txt = (txt.replace('@MB@', f'RT.MB<RT.M_{E}>').replace('@BX@', f'O.Boxed<{EA}.{E}>').replace('@ETY@', f'{EA}.{E}')
           .replace('@YW@', 'YW').replace('@TX@', TX).replace('@LD@', LD).replace('@L@', L).replace('@E@', E))
    assert not re.search(r'@[A-Z]+@', txt), re.findall(r'@[A-Z]+@', txt)[:3]
    assert '28n' not in txt
    txt = re.sub(r'(?<![\w.])(tf|vw)_' + E + r'\(', lambda m: f'WXA.{m.group(1)}_{E}(', txt)
    txt = txt.replace('RT2.', 'RT.')
    assert 'RT2' not in txt
    # the array lemmas over the mirrors (amset, nth, tfzam) are root_types' (not in its light companion)
    # (whichever of them root_laws_generic's light split has moved to root_types_light stay RT)
    lt = (ROOT / 'proofs/obj/root_types_light.bend').read_text()
    heavy = [f for f in ('amset', 'nth', 'tfzam') if not re.search(rf'^def {f}_{L}\(', lt, re.M)]
    if heavy:
        txt = re.sub(r'\bRT\.(' + '|'.join(heavy) + ')_' + L + r'\(', lambda m: f'RTH.{m.group(1)}_{L}(', txt)
    vl = f'''
# ======== the law: the list a window reads views as the window's value ========
def vl({WPD}, +hchk: {{W.CHKw(t, x, off, len) == True{{}} : Bool}})
    -> {{RT.xv_{L}(W.OBJw(d, t, x, off, len)) == W.VALw(t, x, len) : S.Value}}:
  vw_{L}(d, t, x, off, len, eo, hd, hw, hw32, pf, hchk)
'''
    head = ['import Base', 'import ../src/obj.bend as O', 'import ../src/buffer.bend as B', 'import ../types/schema.bend as S',
            'import ../proofs/compact/found.bend as FD', 'import ../proofs/compact/arith.bend as A', 'import ../proofs/nat_order.bend as Order',
            'import ../proofs/obj/vbuf.bend as VB', 'import ../proofs/obj/vdepth.bend as VD', 'import ../proofs/obj/vlist.bend as VLS',
            'import ../proofs/obj/vcopy.bend as VC', 'import ../proofs/obj/vua_ct.bend as UCT', 'import ../proofs/obj/vvlu.bend as VVU',
            'import ../proofs/obj/root_types_light.bend as RT'] + (['import ../proofs/obj/root_types.bend as RTH'] if heavy else []) + [
            f'import ../proofs/obj/{mod}.bend as W', f'import ../proofs/obj/var_winx_{E}.bend as YW',
            f'import ../types/{EF}.bend as {EA}', f'import ../types/{LF}.bend as {LD}', 'import ./e2e_wxa.bend as WXA']
    return '\n'.join(head) + f'''

# GENERATED by {GEN}. Do not edit.
# {L} (the block body's list of variable-size {E}, W = {mod}) read at a byte window at any tree
# depth d < 31, the window's end below 2^32 (hw32): the reader's Array.set chain is RT.am of tree updates FT_{L}
# (rvF_{L}; each element written is th_bx of its mirror, eqE_{L}); element 0 of FT_{L} is the first write
# (lemV_{L}), element 1 + c the write of element c (lemN_{L}); an element's view is its window's value
# (e2e_wxa.vw_{E}). vl: the list's root view is the window's value.

''' + shared + '\n' + txt + vl


SUPPORT_OUT = {
    'e2e_wxa.bend': wxa_text(),
    'e2e_vlm_l8_Attestation.bend': vlm_text('l8_Attestation'),
    'e2e_vlm_l1_AttesterSlashing.bend': vlm_text('l1_AttesterSlashing'),
}
