#!/usr/bin/env python3
"""Generates e2e/e2e_dpl.bend: the length facts of a decoded progressive list of uint8/16/32/64/128/256 (rep_pl*):
the byte length is 2^k times the element count (k = 1, 2, 3, 4, 5), with the count the object's own shifted length,
and a length of four-byte multiples has no bytes past a whole word (the decoders' mask keeps the tree). Everything is
symbolic in the count: no number is evaluated.

Usage: python3 codegen/e2e_decpl.py [--check]"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'e2e' / 'e2e_dpl.bend'

# D_j(c): the j-fold element width in words (EL.w<j>(c) = j * c) as doublings
DJ = {1: 'c', 2: 'Nat.double(c)', 4: 'Nat.double(Nat.double(c))', 8: 'Nat.double(Nat.double(Nat.double(c)))'}

W = ''.join(f"""
# EL.w{j}(c) = {j} * c, as doublings
def wd{j}(+c: Nat) -> {{EL.w{j}(c) == {DJ[j]} : Nat}}:
  match c:
    case 0n: {{==}}
    case 1n+ +p:
      %Equal.sym(Nat, EL.w{j}(p), {DJ[j].replace('c', 'p')}, wd{j}(p)) : {{{ {1: '1n+_', 2: '2n+_', 4: '4n+_', 8: '8n+_'}[j] } == {DJ[j].replace('c', '1n+p')} : Nat}}
      {{==}}
""" for j in (1, 2, 4, 8))

TEXT = f"""import Base
import ../src/obj.bend as O
import ../proofs/compact/found.bend as FD
import ../proofs/compact/arith.bend as A
import ../proofs/compact/reads.bend as RD
import ../proofs/obj/vdepth.bend as VD
import ../proofs/obj/vcopy.bend as VC
import ../proofs/obj/vu32.bend as VU
import ../proofs/obj/var_elems.bend as EL
import ../proofs/obj/vrejb.bend as VRB
import ../proofs/obj/packed_bytes_light.bend as PBL
import ./e2e_mask.bend as MK

# GENERATED by codegen/e2e_decpl.py. Do not edit.

# sc(k, c) = 2^k * c, as k doublings
def sc(+k: Nat, +c: Nat) -> Nat:
  match k:
    case 0n: c
    case 1n+ +p: sc(p, Nat.double(c))

def srq(+k: Nat, +c: Nat) -> {{VD.s_rng(k, sc(k, c)) == c : Nat}}:
  match k:
    case 0n: {{==}}
    case 1n+ +p:
      %Equal.sym(Nat, VD.s_rng(p, sc(p, Nat.double(c))), Nat.double(c), srq(p, Nat.double(c))) : {{VD.s_h2(_) == c : Nat}}
      VD.s_h2_bit(False{{}}, c)

# a length of 2^k c bytes shifted right by k is c
def cnt(+k: Nat, +L: U32, +c: Nat, +e: {{U32.to_nat(L) == sc(k, c) : Nat}}) -> {{U32.to_nat(U32.shrn(L, k)) == c : Nat}}:
  Equal.trans(Nat, U32.to_nat(U32.shrn(L, k)), VD.s_rng(k, U32.to_nat(L)), c, VD.shrk(k, L),
    Equal.trans(Nat, VD.s_rng(k, U32.to_nat(L)), VD.s_rng(k, sc(k, c)), c, Equal.cong(Nat, Nat, z => VD.s_rng(k, z), U32.to_nat(L), sc(k, c), e), srq(k, c)))
{W}
# bytes each at most 1 (the decoder's check, VRB.ALLB) are each below 2 (the representation's bscope), over their own length
def bsc(+xs: +List<U32>, +h: {{VRB.ALLB(xs) == True{{}} : Bool}}) -> {{PBL.bscope(List.length(&2, U32, xs), xs) == True{{}} : Bool}}:
  match xs:
    case Nil{{}}: {{==}}
    case Con{{+x, +t}}:
      %Equal.sym(Bool, U32.is_lt(x, 2), True{{}}, MK.le1_lt2(x, MK.band_l(U32.is_le(x, 1), VRB.ALLB(t), h))) :
        {{Bool.and(_, PBL.bscope(List.length(&2, U32, t), t)) == True{{}} : Bool}}
      bsc(t, MK.band_r(U32.is_le(x, 1), VRB.ALLB(t), h))

# a multiple of four bytes has no bytes past a whole word
def and3q(+L: U32, +m: Nat, +e: {{U32.to_nat(L) == A.quad(m) : Nat}}) -> {{U32.and(L, 3) == 0 : U32}}:
  +q = U32.to_nat(U32.shrn(L, 2n))
  +r = U32.to_nat(U32.and(L, 3))
  +e1 = Equal.trans(Nat, Nat.add(Nat.mul(q, 4n), r), Nat.add(A.quad(q), r), Nat.add(Nat.mul(m, 4n), 0n),
    Equal.cong(Nat, Nat, z => Nat.add(z, r), Nat.mul(q, 4n), A.quad(q), VC.quad_mul(q)),
    Equal.trans(Nat, Nat.add(A.quad(q), r), U32.to_nat(L), Nat.add(Nat.mul(m, 4n), 0n), Equal.sym(Nat, U32.to_nat(L), Nat.add(A.quad(q), r), VC.split4(L)),
      Equal.trans(Nat, U32.to_nat(L), A.quad(m), Nat.add(Nat.mul(m, 4n), 0n), e,
        Equal.trans(Nat, A.quad(m), Nat.mul(m, 4n), Nat.add(Nat.mul(m, 4n), 0n), Equal.sym(Nat, Nat.mul(m, 4n), A.quad(m), VC.quad_mul(m)),
          Equal.sym(Nat, Nat.add(Nat.mul(m, 4n), 0n), Nat.mul(m, 4n), FD.nat__add_zero(Nat.mul(m, 4n)))))))
  +hr = FD.nat__le_lt_trans(r, 3n, 4n, RD.and_le(L, 3), {{==}})
  FD.u32__injective(U32.and(L, 3), 0, Pair.snd({{q == m : Nat}}, {{r == 0n : Nat}}, VU.dm_unique(q, r, m, 0n, 4n, e1, hr, {{==}})))
"""


def main():
    if '--check' in sys.argv:
        if not OUT.exists() or OUT.read_text() != TEXT:
            print('stale: e2e/e2e_dpl.bend')
            sys.exit(1)
        print('e2e_decpl: up to date')
        return
    OUT.write_text(TEXT)
    print('e2e_decpl: wrote e2e/e2e_dpl.bend')


if __name__ == '__main__':
    main()
