#!/usr/bin/env python3
"""The encoder-window children and sub-word leaves available to the container encoders
(codegen/var_cont_enc.py), by the runtime prefix of the field that uses them.

    python3 codegen/encx_children.py [--check]

CHILDREN[p]: a child in the encoder-window interface of codegen/var_plist_sub.py's ENCX
(proofs/obj/big_encx_<p>.bend): its module, the mirror type and constructor fields, the object
type TH returns, the runtime prefix T.<p>_putk, and the laws' names. Every such child writes its
bytes and the zeros to the end of its last word (putx_bytes: SPL(.., AP(ENC(m), ZB(PADB(r, m))))),
so pad is True. The table is read from the modules themselves, so it follows them.

LEAVES[k]: a sub-word Data leaf as a piece of a container's region (proofs/obj/vpiece.bend): its
size, model, perfect lemma, and the piece lemma returning DK.P2(runtime fact, bytes fact).

WLEAVES[p]: the generic bit-vector word leaves at a word position (proofs/obj/vuwg_<p>.bend).

TLEAVES[p]: the packed-words leaves Bitvector[1280] (vuwg_bv1280) and Bitvector[1281] (vuwl_bv1281).

UNION: the union step lemmas (proofs/obj/vunion.bend).

--check verifies that every module listed exports the interface.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OBJ = ROOT / 'proofs/obj'

# the children of the generic containers and unions (and the Fulu ones in the same interface)
PREFIXES = ['pl_u8', 'pl_u16', 'pl_bool', 'pl_u64', 'l1024_u16', 'l128_u16', 'l123_u16', 'bl256', 'bl32',
            'bits5', 'bits6', 'bits256', 'bits257', 'bits1280', 'bits1281', 'bits131072', 'pbits',
            'pl_Gc4ED9619F50', 'l10_GpF350A3C486',
            # lists of variable-size elements (codegen/var_vlist_enc.py GLISTS)
            'pl_Gc465214E502', 'pl_pl_Gc465214E502', 'pl_Gp66304057C3', 'v2_Gc465214E502', 'l1_AttesterSlashing', 'l8_Attestation',
            # containers (codegen/var_cont_enc.py's interface modules, big_encx_<C>_iface)
            'Gc465214E502', 'Gp66304057C3', 'IndexedAttestation', 'AttesterSlashing', 'Attestation', 'ExecutionRequests',
            # Fulu (codegen/var_rec_enc.py's FLISTS)
            'l4096_b48', 'l131072_u64',
            # BeaconState's packed lists (codegen/var_rec_enc.py FLISTS)
            'l16777216_b32', 'l1099511627776_u64', 'l1099511627776_u8']
LAWS = ['putx', 'putx_bytes', 'pfx', 'szx', 'sizex', 'encx_spec']
DEFS = ['TH', 'OK', 'ENC', 'VAL', 'SZ', 'PUTX', 'PADB']


def child_file(p):
    f = OBJ / f'big_encx_{p}_iface.bend'
    return f if f.exists() else OBJ / f'big_encx_{p}.bend'


def read_child(p, text=None, fname=None):
    """A child's interface record, from its module (or the given text of the module fname)."""
    f = child_file(p) if fname is None else OBJ / fname
    s = f.read_text() if text is None else text
    m = re.search(r'^type (\w+) is Data:\n  \1\{([^}]*)\}', s, re.M)
    mt, fields = m.group(1), [tuple(x.strip() for x in fd.split(':', 1)) for fd in m.group(2).split(',')]
    th = re.search(rf'^def TH\(m: {mt}\) -> ([^:]+):', s, re.M).group(1).strip()
    pre = re.search(r'\{T\.(\w+)_putk\(F?D?\.array__thaw\(U32, D\), X, TH\(m\)\)', s).group(1)
    sch = re.search(r'\{Codec\.parts\(VAL\(m\), (.*)\) == Some\{\[S\.Variable\{ENC\(m\)\}\]\}', s).group(1)
    gen = re.search(r'# GENERATED by (\S+)\.', s).group(1)
    return {'file': f.name, 'mirror': mt, 'fields': fields, 'obj': th, 'runtime': pre, 'schema': sch, 'generator': gen,
            'pad': True, 'defs': DEFS, 'laws': LAWS}


CHILDREN = {p: read_child(p) for p in PREFIXES if child_file(p).exists()}

# sub-word leaves as region pieces: (size, model(dd, D, X, c, x), perfect, piece lemma, extra parameters, padded)
LEAVES = {
    'u8': {'size': 1, 'module': 'vpiece.bend', 'model': 'P8', 'perfect': 'p8_perfect', 'piece': 'u8piece', 'runtime': 'T.u8_put',
           'bytes': lambda x: f'[U32.and({x}, 255)]', 'pad': False},
    'u16': {'size': 2, 'module': 'vpiece.bend', 'model': 'P16', 'perfect': 'p16_perfect', 'piece': 'u16piece', 'runtime': 'T.u16_put',
            'bytes': lambda x: f'[U32.and({x}, 255), U32.and(U32.shrn({x}, 8n), 255)]', 'pad': False},
    'bv1281': {'size': 161, 'module': 'vpiece.bend', 'model': 'P1281', 'perfect': 'p1281_perfect', 'piece': 'bv1281piece', 'runtime': 'T.bv1281_putk',
               'extra': ['dB', 'TB', 'pfB', 'hdB', 'hrB', 'htz', 'hbz'], 'pad': True},
}

# word leaves of the generic types at a word position (q, r) (the bytes worker's vuwg_<p>.bend, like
# var_cont_enc's Leaf): the object T.<ctor>{w0 .. w{W-1}}, its m bytes; pad: its bytes are
# bt(m, limbs(ws)) ++ ZB(PADB(r, m)) and its hz covers m + PADB(r, m) bytes (else FX.limbs(ws) and m);
# vt: the premise U32.shrn(w_last, 8n) == 0 (the runtime's bits-above-zero check) between pf and hz.
WLEAVES = {p: {'module': f'vuwg_{p}.bend', 'ctor': f'T.Bitvector{p[2:]}', 'W': W, 'size': m, 'model': f'PX_{p}', 'rt': f'{p}_any',
               'bytes': f'{p}_any_bytes', 'perfect': f'{p}x_perfect', 'runtime': f'T.{p}_put', 'pad': pad, 'vt': pad, 'rt_hz': True}
           for p, W, m, pad in [('bv1', 1, 1, True), ('bv2', 1, 1, True), ('bv8', 1, 1, True), ('bv256', 8, 32, False), ('bv257', 9, 33, True)]}

# the packed-words leaves (O.Words{thaw TB, m} objects, checked writers T.<p>_putk returning size 0) at a word
# position (q, r): <p>_any(dd, D, X, q, r, dB, TB, e, hr, hd, hl, pf, pfB, hdB, hrB, [htz, hbz,] hz)
TLEAVES = {
    'bv1280': {'module': 'vuwg_bv1280.bend', 'size': 160, 'words': 40, 'model': 'PX_bv1280', 'rt': 'bv1280_any', 'bytes': 'bv1280_any_bytes',
               'perfect': 'bv1280x_perfect', 'runtime': 'T.bv1280_putk', 'pad': False, 'extra': ['pfB', 'hdB', 'hrB'],
               'hdB': 'Nat.is_lt(dB, 31n)', 'hrB': 'Nat.is_le(40n, VB.pw(dB))'},
    'bv1281': {'module': 'vuwl_bv1281.bend', 'size': 161, 'words': 41, 'model': 'PX_bv1281', 'rt': 'bv1281_any', 'bytes': 'bv1281_any_bytes',
               'perfect': 'bv1281x_perfect', 'runtime': 'T.bv1281_putk', 'pad': True, 'extra': ['pfB', 'hdB', 'hrB', 'htz', 'hbz'],
               'hdB': 'Nat.is_lt(dB, 28n)', 'hrB': 'Nat.is_le(161n, A.quad(VB.pw(dB)))'},
}

# the union step (vunion.bend): the selector byte with O.w8 at X, the arm at X + 1 (4 AQ(q, r) + AR(r))
UNION = {'module': 'vunion.bend', 'arm_q': 'AQ', 'arm_r': 'AR', 'sel_model': 'DS', 'sel_rt': 'sel_rt', 'sel_by': 'sel_by', 'sel_pf': 'sel_pf',
         'arm_e': 'arm_e', 'arm_room': 'aroom', 'arm_hz': 'arm_hz', 'bytes': 'ubytes', 'pad': 'padsh', 'r_lt': 'ar_lt',
         'spec_variable': 'tag_v', 'spec_fixed': 'tag_f'}


def check():
    bad = []
    for p, c in CHILDREN.items():
        s = (OBJ / c['file']).read_text()
        for d in DEFS:
            if not re.search(rf'^def {d}\(', s, re.M):
                bad.append(f'{c["file"]}: no def {d}')
        for l in LAWS:
            if not re.search(rf'^law {l}:', s, re.M):
                bad.append(f'{c["file"]}: no law {l}')
    missing = [p for p in PREFIXES if p not in CHILDREN]
    for k, lf in LEAVES.items():
        s = (OBJ / lf['module']).read_text()
        for n in (lf['model'], lf['perfect'], lf['piece']):
            if not re.search(rf'^def {n}\(', s, re.M):
                bad.append(f'{lf["module"]}: no def {n}')
    for k, lf in list(WLEAVES.items()) + list(TLEAVES.items()):
        f = OBJ / lf['module']
        if not f.exists():
            bad.append(f'no {lf["module"]}')
            continue
        s = f.read_text()
        for n in (lf['model'], lf['perfect'], lf['rt'], lf['bytes']):
            if not re.search(rf'^def {n}\(', s, re.M):
                bad.append(f'{lf["module"]}: no def {n}')
    s = (OBJ / UNION['module']).read_text()
    for k, n in UNION.items():
        if k != 'module' and not re.search(rf'^def {n}\(', s, re.M):
            bad.append(f'{UNION["module"]}: no def {n}')
    return bad, missing


def main():
    bad, missing = check()
    if '--check' in sys.argv:
        if bad or missing:
            print('encoder children: ' + '; '.join(bad + [f'missing big_encx_{p}' for p in missing]))
            sys.exit(1)
        print(f'encoder children are consistent ({len(CHILDREN)} children, {len(LEAVES)} piece leaves, {len(WLEAVES)} word leaves, {len(TLEAVES)} packed-words leaves, union step)')
        return
    for p, c in CHILDREN.items():
        print(f'{p}: {c["file"]} {c["mirror"]}{{{", ".join(n for n, t in c["fields"])}}} -> {c["obj"]} [{c["generator"]}]')


if __name__ == '__main__':
    main()
