#!/usr/bin/env python3
"""The encoder-window children and sub-word leaves available to the container encoders
(codegen/var_cont_enc.py), by the runtime prefix of the field that uses them.

    python3 codegen/encx_children.py [--check]

CHILDREN[p]: a child in the encoder-window interface of codegen/var_plist_sub.py's ENCX
(proofs/obj/big_encx_<p>.bend): its module, the mirror type and constructor fields, the object
type TH returns, the runtime prefix T.<p>_putk, and the laws' names. Every such child writes its
bytes and the zeros to the end of its last word (putx_bytes: SPL(.., AP(ENC(m), ZB(PADB(r, m))))),
so pad is True. The table is read from the modules themselves, so it follows them.

LEAVES[k]: a sub-word Data leaf as a piece of a container's region (proofs/obj/vpiece.bend): its
size, model, perfect lemma, and the piece lemma returning DK.P2(runtime fact, bytes fact).

UNION: the union step lemmas (proofs/obj/vunion.bend).

--check verifies that every module listed exports the interface.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OBJ = ROOT / 'proofs/obj'

# the children of the generic containers and unions (and the Fulu ones in the same interface)
PREFIXES = ['pl_u8', 'pl_u16', 'pl_bool', 'pl_u64', 'l1024_u16', 'l128_u16', 'l123_u16', 'bl256', 'bl32',
            'bits5', 'bits6', 'bits256', 'bits257', 'bits1280', 'bits1281', 'bits131072', 'pbits',
            'pl_Gc4ED9619F50', 'l10_GpF350A3C486']
LAWS = ['putx', 'putx_bytes', 'pfx', 'szx', 'sizex', 'encx_spec']
DEFS = ['TH', 'OK', 'ENC', 'VAL', 'SZ', 'PUTX', 'PADB']


def read_child(p):
    f = OBJ / f'big_encx_{p}.bend'
    s = f.read_text()
    m = re.search(r'^type (\w+) is Data:\n  \1\{([^}]*)\}', s, re.M)
    mt, fields = m.group(1), [tuple(x.strip() for x in fd.split(':', 1)) for fd in m.group(2).split(',')]
    th = re.search(rf'^def TH\(m: {mt}\) -> ([^:]+):', s, re.M).group(1).strip()
    pre = re.search(r'\{T\.(\w+)_putk\(FD\.array__thaw\(U32, D\), X, TH\(m\)\)', s).group(1)
    sch = re.search(r'\{Codec\.parts\(VAL\(m\), (.*)\) == Some\{\[S\.Variable\{ENC\(m\)\}\]\}', s).group(1)
    gen = re.search(r'# GENERATED by (\S+)\.', s).group(1)
    return {'file': f.name, 'mirror': mt, 'fields': fields, 'obj': th, 'runtime': pre, 'schema': sch, 'generator': gen,
            'pad': True, 'defs': DEFS, 'laws': LAWS}


CHILDREN = {p: read_child(p) for p in PREFIXES if (OBJ / f'big_encx_{p}.bend').exists()}

# sub-word leaves as region pieces: (size, model(dd, D, X, c, x), perfect, piece lemma, extra parameters, padded)
LEAVES = {
    'u8': {'size': 1, 'module': 'vpiece.bend', 'model': 'P8', 'perfect': 'p8_perfect', 'piece': 'u8piece', 'runtime': 'T.u8_put',
           'bytes': lambda x: f'[U32.and({x}, 255)]', 'pad': False},
    'u16': {'size': 2, 'module': 'vpiece.bend', 'model': 'P16', 'perfect': 'p16_perfect', 'piece': 'u16piece', 'runtime': 'T.u16_put',
            'bytes': lambda x: f'[U32.and({x}, 255), U32.and(U32.shrn({x}, 8n), 255)]', 'pad': False},
    'bv1281': {'size': 161, 'module': 'vpiece.bend', 'model': 'P1281', 'perfect': 'p1281_perfect', 'piece': 'bv1281piece', 'runtime': 'T.bv1281_putk',
               'extra': ['dB', 'TB', 'pfB', 'hdB', 'hrB', 'htz', 'hbz'], 'pad': True},
}

# the union step (vunion.bend): the selector byte with O.w8 at X, the arm at X + 1 (4 AQ(q, r) + AR(r))
UNION = {'module': 'vunion.bend', 'arm_q': 'AQ', 'arm_r': 'AR', 'sel_model': 'DS', 'sel_rt': 'sel_rt', 'sel_by': 'sel_by', 'sel_pf': 'sel_pf',
         'arm_e': 'arm_e', 'arm_room': 'aroom', 'arm_hz': 'arm_hz', 'bytes': 'ubytes', 'pad': 'padsh', 'r_lt': 'ar_lt',
         'spec_variable': 'tag_v', 'spec_fixed': 'tag_f'}


def check():
    bad = []
    for p, c in CHILDREN.items():
        s = (OBJ / c['file']).read_text()
        for d in DEFS:
            if not re.search(rf'^def {d}\(', s, re.M):
                bad.append(f'{c["file"]}: no def {d}')
        for l in LAWS:
            if not re.search(rf'^law {l}:', s, re.M):
                bad.append(f'{c["file"]}: no law {l}')
    missing = [p for p in PREFIXES if p not in CHILDREN]
    for k, lf in LEAVES.items():
        s = (OBJ / lf['module']).read_text()
        for n in (lf['model'], lf['perfect'], lf['piece']):
            if not re.search(rf'^def {n}\(', s, re.M):
                bad.append(f'{lf["module"]}: no def {n}')
    s = (OBJ / UNION['module']).read_text()
    for k, n in UNION.items():
        if k != 'module' and not re.search(rf'^def {n}\(', s, re.M):
            bad.append(f'{UNION["module"]}: no def {n}')
    return bad, missing


def main():
    bad, missing = check()
    if '--check' in sys.argv:
        if bad or missing:
            print('encoder children: ' + '; '.join(bad + [f'missing big_encx_{p}' for p in missing]))
            sys.exit(1)
        print(f'encoder children are consistent ({len(CHILDREN)} children, {len(LEAVES)} leaves, union step)')
        return
    for p, c in CHILDREN.items():
        print(f'{p}: {c["file"]} {c["mirror"]}{{{", ".join(n for n, t in c["fields"])}}} -> {c["obj"]} [{c["generator"]}]')


if __name__ == '__main__':
    main()
