#!/usr/bin/env python3
"""ok_eval and decode_reject for the bit vectors whose validator checks the padding bits
of the last byte (O.ok_pad): BitVector[n] with n = 8 K + r, 0 < r < 8, N = K + 1 bytes.

    python3 codegen/fix_reject_pad.py [--check] [--no-big]

With PADK(bs, K, r) = bits r..7 of byte K of bs clear:
  <X>_ok_eval(d, t, n, off, x, e, hd, pf, hb, len)
      : {T.<p>_ok(UA.BF(t, n), off, len) == (UA.BF(t, n), Bool.and(U32.is_eq(len, N), PADK(UW.WX(t, x, N), K, r)))}
  <X>_decode_reject(bs, h: {Bool.and(Nat.is_eq(|bs|, N), PADK(bs, K, r)) == False})
      : Decoding.outside_image(<schema>, bs)
proofs/obj/vrejp.bend: pack(bits) of 8 q + r bits has bits r..7 of its byte q clear (by
induction on q; the last byte by cases on its r bits). The names come from the runtime.
"""
import itertools
import re
import sys
from pathlib import Path
import runtime_refs as RR  # noqa: E402  the runtime split: the monoliths' text, the split files' imports

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'codegen'))
TRUE = 'True{} : Bool'
P = 'A.quad(VB.pw(d))'
B = lambda b: 'True{}' if b else 'False{}'


def rows():
    import generic
    gen = {n for n, t, e in generic.inventory_all() if e is None}
    src = RR.mono_text('generic')
    specs = (ROOT / 'proofs/obj/generic_specs.bend').read_text()
    out = []
    for m in re.finditer(r'^def (\w+)_decode\(buf: B\.Buf, \+size: U32\)[^\n]*\n  \w+\(size, (\w+)_ok\(buf, 0, size\)\)', src, re.M):
        X, p = m.groups()
        if X not in gen:
            continue
        at = re.search(rf'^def {p}_ok_at\(buf: B\.Buf, \+off: U32\) -> B\.Buf & Bool: O\.ok_pad\(buf, \(off \+ (\d+) : U32\), (\d)\)$', src, re.M)
        ok = re.search(rf'^def {p}_ok\(buf: B\.Buf, \+off: U32, \+len: U32\) -> B\.Buf & Bool: {p}_ok_len\(U32\.is_eq\(len, (\d+)\), buf, off\)$', src, re.M)
        sch = re.search(rf'^def {X}\(\) -> S\.Schema: S\.BitVector\{{(\d+)n\}}$', specs, re.M)
        if at and ok and sch:
            K, r, N, n = int(at.group(1)), int(at.group(2)), int(ok.group(1)), int(sch.group(1))
            assert N == K + 1 and n == 8 * K + r and 0 < r < 8, X
            out.append((X, p, n, K, r, N))
    return out


def word_list(xs):
    t = 'Nil{}'
    for x in reversed(xs):
        t = f'Con{{{x}, {t}}}'
    return t


def lib(rs):
    L = ['import Base', 'import ../../src/obj.bend as O', 'import ../../spec/bit_packing.bend as Bp', 'import ../compact/found.bend as FD',
         'import ./vbitl.bend as VBL', '',
         '# GENERATED by codegen/fix_reject_pad.py. Do not edit.',
         '# pack(bits) of 8 q + r bits has bits r..7 of its byte q clear (the padding of a bit vector).', '',
         '# 8 q + r', 'def LB(q: Nat, +r: Nat) -> Nat:', '  match q:', '    case 0n: r', '    case 1n+p: 8n+LB(p, r)', '',
         '# bits r..7 of byte K of bs clear',
         'def PADK(+bs: +List<U32>, +K: Nat, +r: U32) -> Bool: U32.is_eq(U32.and(VBL.nthb(bs, K), U32.not(O.low_mask(r))), 0)', '']
    for r in sorted({x[4] for x in rs}):
        bs = [f'b{i}' for i in range(r)]
        octet = f'Bp.octet({", ".join(bs + ["False{}"] * (8 - r))})'
        L.append(f'# the last byte of {r} bits')
        L.append(f'def base{r}({", ".join("+" + b + ": Bool" for b in bs)}) -> {{PADK([{octet}], 0n, {r}) == {TRUE}}}:')
        L.append(f'  match {" ".join(bs)}:')
        for vs in itertools.product([False, True], repeat=r):
            L.append(f'    case {" ".join(B(v) for v in vs)}: {{==}}')
        L.append('')
        # padq_r by induction on q
        goal = lambda lst, q: f'{{PADK(Bp.pack({lst}), {q}, {r}) == {TRUE}}}'
        L.append(f'def padq{r}(+q: Nat, +bits: +List<Bool>, +h: {{Nat.is_eq(List.length(&2, Bool, bits), LB(q, {r}n)) == {TRUE}}})')
        L.append(f'    -> {goal("bits", "q")}:')
        L.append('  match q:')
        L.append('    case 0n:')
        # peel r elements
        ind = '      '
        names = []
        cur = 'bits'
        for i in range(r):
            L.append(f'{ind}match {cur}:')
            L.append(f'{ind}  case Nil{{}}: Empty.absurd({goal(word_list(names), "0n")}, FD.logic__false_true(h))')
            nb, nr = f'b{i}', f'r{i}'
            L.append(f'{ind}  case Con{{+{nb}, +{nr}}}:')
            names.append(nb)
            cur = nr
            ind += '    '
        L.append(f'{ind}match {cur}:')
        L.append(f'{ind}  case Nil{{}}: base{r}({", ".join(names)})')
        L.append(f'{ind}  case Con{{+c, +cr}}: Empty.absurd({goal(word_list(names + ["c"]).replace("Nil{}", "cr"), "0n")}, FD.logic__false_true(h))')
        L.append('    case 1n+ +p:')
        ind = '      '
        names = []
        cur = 'bits'
        for i in range(8):
            L.append(f'{ind}match {cur}:')
            L.append(f'{ind}  case Nil{{}}: Empty.absurd({goal(word_list(names), "1n+p")}, FD.logic__false_true(h))')
            nb, nr = f'c{i}', f's{i}'
            L.append(f'{ind}  case Con{{+{nb}, +{nr}}}:')
            names.append(nb)
            cur = nr
            ind += '    '
        L.append(f'{ind}padq{r}(p, {cur}, h)')
        L.append('')
    return '\n'.join(L) + '\n'


def _with_deep(X, text):
    """The validator laws (_at, _okl, _ok_eval) at any depth d < 31: twins X_atD / X_oklD / X_ok_evalD after the d < 28
    originals (which stay, for the callers that have d < 28). The byte at K + x is strictly inside the tree (hy), so the
    strict-bound lemmas of the deep interface (UR.offx31, hd < 31 for VR.byte_at_ok) are all it needs."""
    a = text.index(f'def {X}_at(')
    b = text.index('# every encoding at BitVector')
    core = text[a:b]
    d = core
    for old, new in [(f'{X}_at', f'{X}_atD'), (f'{X}_okl', f'{X}_oklD'), (f'{X}_ok_eval', f'{X}_ok_evalD'),
                     ('Nat.is_lt(d, 28n)', 'Nat.is_lt(d, 31n)')]:
        assert old in d, old
        d = d.replace(old, new)
    d, n1 = re.subn(r'UR\.offx\(d, off, (\d+), x, e, FD\.nat__lt_trans\(d, 28n, 30n, hd, \{==\}\), hy\)', r'UR.offx31(d, off, \1, x, e, hd, hy)', d)
    d, n2 = re.subn(r'FD\.nat__lt_trans\(d, 28n, 32n, hd, \{==\}\)', 'FD.nat__lt_trans(d, 31n, 32n, hd, {==})', d)
    assert n1 == 1 and n2 == 1, (n1, n2)
    assert '28n' not in d, d
    return text[:b] + d + text[b:]


def name_text(X, p, n, K, r, N):
    s = f'GS.{X}()'
    W = f'UW.WX(t, x, {N}n)'
    BF = 'UA.BF(t, n)'
    sig = (f'+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +off: U32, +x: Nat, +e: {{U32.to_nat(off) == x : Nat}},\n'
           f'    +hd: {{Nat.is_lt(d, 28n) == {TRUE}}}, +pf: {{FD.array__perfect(U32, d, t) == {TRUE}}},\n'
           f'    +hb: {{Nat.is_le(Nat.add(x, {N}n), {P}) == {TRUE}}}')
    args = 'd, t, n, off, x, e, hd, pf, hb'
    PK = lambda bs: f'VRP.PADK({bs}, {K}n, {r})'
    ABS = ''.join(f"    case S.{c}: Empty.absurd({{{PK('bs')} == {TRUE}}}, FD.logic__none_some(+List<U32>, bs, e))\n"
                  for c in ['BooleanValue{+b}', 'UnsignedValue{+u}', 'BytesValue{+xs}', 'Sequence{+it}', 'Items{+hh, +tt}', 'EmptyItems{}', 'Selected{+sel, +sv}', 'NullValue{}'])
    y = f'Nat.add({K}n, x)'
    return _with_deep(X, f'''# ---- {X} (BitVector[{n}], {N} bytes; validator T.{p}_ok: bits {r}..7 of byte {K} clear) ----
def {X}_at({sig})
    -> {{T.{p}_ok_at({BF}, off) == ({BF}, {PK(W)}) : B.Buf & Bool}}:
  +hk = FD.nat__lt_le_trans(Nat.add(x, {K}n), Nat.add(x, {N}n), {P}, FD.nat__lt_add_left({K}n, {N}n, x, {{==}}), hb)
  +hy = FD.logic__subst(Nat, z => {{Nat.is_lt(z, {P}) == {TRUE}}}, Nat.add(x, {K}n), {y}, FD.nat__add_comm(x, {K}n), hk)
  +ey = UR.offx(d, off, {K}, x, e, FD.nat__lt_trans(d, 28n, 30n, hd, {{==}}), hy)
  %Equal.sym(B.Buf & U32, B.byte_at({BF}, U32.add(off, {K})), ({BF}, VR.VX(t, U32.add(off, {K}))),
      VR.byte_at_ok(d, t, n, U32.add(off, {K}), FD.nat__lt_trans(d, 28n, 32n, hd, {{==}}), VR.hiX(d, U32.add(off, {K}), {y}, ey, hy), pf)) :
    {{O.pad_pick({r}, _) == ({BF}, {PK(W)}) : B.Buf & Bool}}
  %Equal.sym(U32, VR.VX(t, U32.add(off, {K})), VRB.BX(t, {y}), VRB.vx_bx(t, U32.add(off, {K}), {y}, ey)) :
    {{O.pad_pick({r}, ({BF}, _)) == ({BF}, {PK(W)}) : B.Buf & Bool}}
  %Equal.sym(U32, VBL.nthb({W}, {K}n), VBL.nthb(UA.BYT(t), Nat.add(x, {K}n)),
      Equal.trans(U32, VBL.nthb({W}, {K}n), VBL.nthb(VS.bdr(x, UA.BYT(t)), {K}n), VBL.nthb(UA.BYT(t), Nat.add(x, {K}n)),
        VR.nth_bt({N}n, VS.bdr(x, UA.BYT(t)), {K}n, {{==}}), VR.nth_bdr(x, UA.BYT(t), {K}n))) :
    {{O.pad_pick({r}, ({BF}, VRB.BX(t, {y}))) == ({BF}, U32.is_eq(U32.and(_, U32.not(O.low_mask({r}))), 0)) : B.Buf & Bool}}
  %Equal.sym(Nat, Nat.add(x, {K}n), {y}, FD.nat__add_comm(x, {K}n)) :
    {{O.pad_pick({r}, ({BF}, VRB.BX(t, {y}))) == ({BF}, U32.is_eq(U32.and(VBL.nthb(UA.BYT(t), _), U32.not(O.low_mask({r}))), 0)) : B.Buf & Bool}}
  {{==}}

def {X}_okl({sig}, +b: Bool)
    -> {{T.{p}_ok_len(b, {BF}, off) == ({BF}, Bool.and(b, {PK(W)})) : B.Buf & Bool}}:
  match b:
    case True{{}}: {X}_at({args})
    case False{{}}: {{==}}

# the validator returns the length check and the padding check of the last window byte
def {X}_ok_eval({sig}, +len: U32)
    -> {{T.{p}_ok({BF}, off, len) == ({BF}, Bool.and(U32.is_eq(len, {N}), {PK(W)})) : B.Buf & Bool}}:
  {X}_okl({args}, U32.is_eq(len, {N}))

# every encoding at BitVector[{n}]: its padding bits clear
def {X}_dom(+bits: +List<Bool>, +bs: +List<U32>, +c: Bool, +ec: {{Bool.and(Nat.is_lt(0n, {n}n), Nat.is_eq(List.length(&2, Bool, bits), {n}n)) == c : Bool}},
    +e: {{Codec.bytes(Codec.one(SBF.encoding(c, bits), Some{{Nat.div(Nat.add({n}n, 7n), 8n)}})) == Some{{bs}} : Maybe<&2, +List<U32>>}})
    -> {{{PK("bs")} == {TRUE}}}:
  match c:
    case False{{}}: Empty.absurd({{{PK("bs")} == {TRUE}}}, FD.logic__none_some(+List<U32>, bs, e))
    case True{{}}:
      FD.logic__subst(+List<U32>, z => {{{PK("z")} == {TRUE}}}, Bp.pack(bits), bs, FD.logic__some_inj(+List<U32>, Bp.pack(bits), bs, e), VRP.padq{r}({K}n, bits, ec))
def {X}_pv(+v: S.Value, +bs: +List<U32>, +e: {{Codec.encoding_for_legal_type({s}, v) == Some{{bs}} : Maybe<&2, +List<U32>>}})
    -> {{{PK("bs")} == {TRUE}}}:
  match v:
    case S.BitsValue{{+bits}}: {X}_dom(bits, bs, Bool.and(Nat.is_lt(0n, {n}n), Nat.is_eq(List.length(&2, Bool, bits), {n}n)), {{==}}, e)
{ABS}
def {X}_rj(+bs: +List<U32>, +h: {{Bool.and(Nat.is_eq(List.length(&2, U32, bs), {N}n), {PK("bs")}) == False{{}} : Bool}}, +v: S.Value,
    +e: {{Codec.encoding_for_legal_type({s}, v) == Some{{bs}} : Maybe<&2, +List<U32>>}}) -> Empty:
  VRB.chk_true(Nat.is_eq(List.length(&2, U32, bs), {N}n), {PK("bs")},
    VRB.len_eq(SS.fixed_size({s}), {N}n, bs, Codec.parts(v, {s}), DS.facts(v, {s}, {{==}}), {{==}}, e), {X}_pv(v, bs, e), h)

# a byte list of another length, or with a padding bit set, is no encoding
def {X}_decode_reject(+bs: +List<U32>, +h: {{Bool.and(Nat.is_eq(List.length(&2, U32, bs), {N}n), {PK("bs")}) == False{{}} : Bool}}) -> Decoding.outside_image({s}, bs):
  v => e => {X}_rj(bs, h, v, e)
''')


def module(rs):
    L = ['import Base', 'import ../../src/buffer.bend as B', 'import ../../src/obj.bend as O', 'import ../../types/generic_obj.bend as T',
         'import ../../types/schema.bend as S', 'import ../../spec/codec.bend as Codec', 'import ../../spec/decoding_relation.bend as Decoding',
         'import ../../spec/schema.bend as SS', 'import ../../spec/bitfields.bend as SBF', 'import ../../spec/bit_packing.bend as Bp',
         'import ../../proofs/decode_shape.bend as DS', 'import ./generic_specs.bend as GS',
         'import ../compact/found.bend as FD', 'import ../compact/arith.bend as A', 'import ./vbuf.bend as VB', 'import ./vspec.bend as VS',
         'import ./vbrt.bend as VR', 'import ./vbitl.bend as VBL', 'import ./vua.bend as UA', 'import ./vua_rd.bend as UR',
         'import ./vua_win.bend as UW', 'import ./vrejb.bend as VRB', 'import ./vrejp.bend as VRP', '',
         '# GENERATED by codegen/fix_reject_pad.py. Do not edit.',
         '# Bit vectors whose validator checks the padding bits: ok_eval and decode_reject (see the generator).', '']
    for r in rs:
        L.append(name_text(*r))
    return '\n'.join(L) + '\n'


def outputs():
    rs = rows()
    return {ROOT / 'proofs/obj/vrejp.bend': lib(rs), ROOT / 'proofs/obj/fixchk_pad.bend': module(rs)}


def main():
    out = outputs()
    out = RR.rewire_out(out)
    if '--check' in sys.argv:
        stale = [str(p.relative_to(ROOT)) for p, t in out.items() if not p.exists() or p.read_text() != t]
        if stale:
            print('stale: ' + ', '.join(stale))
            sys.exit(1)
        print('bit-vector padding reject laws are current')
        return
    for p, t in out.items():
        p.write_text(t)
    print(f'{len(out)} files: ' + ', '.join(r[0] for r in rows()))


if __name__ == '__main__':
    main()
