"""Progressive-container root trees (codegen/root_laws_generic.py writes
proofs/obj/pcont.bend with them).

A progressive container's runtime root (codegen/generate.py
`emit_pcontainer_root`) is O.mix_len(hl, T, mask): T is a fixed tree of node
hashes over the active fields' digests, zero chunks (D.zero()) at the inactive
positions and zero-subtree constants (D.zconst(k)) where a whole subtree is
inactive or past the last slot; mask is the active bit vector as a number.

Per active pattern K this emits, over OPAQUE field digests x0.. and a symbolic
hash length hl (with hl == 64n):
  pt_K   D.bytes(T) is spec/progressive.bend `tree` of the slot chunks
         (built bottom-up with `nb`: the bytes of a node are SHA-256 of its
         children's bytes, so no SHA is evaluated on a partly known message);
  mk_K   Progressive.merkleize(slots) == Some{D.bytes(T)};
  ar_K   RR.active_root(active, chunks, [D.bytes(O.mix_len(hl, T, mask))]):
         the specification's rule for the container's root.
A per-shape law instantiates the x_i with the fields' digests.
"""

HEAD = ['import Base', 'import ../../src/digest.bend as D', 'import ../../src/obj.bend as O',
        'import ../../spec/root_relation.bend as RR', 'import ../../spec/progressive.bend as PS',
        'import ../../spec/primitives.bend as SP', 'import ../../spec/packing.bend as Pack',
        'import ../../spec/bit_root.bend as Mix', 'import ../../spec/bit_packing.bend as Bp',
        'import ../../spec/mixing.bend as Mx', 'import ./mtree_defs.bend as MD', 'import ./sha_node.bend as SN',
        'import 0xe4067e0d858024083f36a7abe7281e89/spec/crypto/sha.bend as VF', '',
        '# GENERATED by codegen/root_laws_generic.py (codegen/pcont_laws.py). Do not edit.',
        '# The root trees of the progressive containers, and the selector mix of the',
        '# compatible unions (see codegen/pcont_laws.py).', '']

LEMMAS = r'''# Every digest's bytes are a chunk.
def cdb(+L: List<&2, D.Digest>) -> {Pack.chunks_domain(MD.bytes_list(L)) == True{} : Bool}:
  match L:
    case Nil{}: {==}
    case Con{+x, +t}:
      %Equal.sym(Bool, SP.byte_scope(32n, D.bytes(x)), True{}, SN.digest_scope(x)) :
        {Bool.and(_, Pack.chunks_domain(MD.bytes_list(t))) == True{} : Bool}
      cdb(t)

# The bytes of a node from its children's bytes.
def nb(+hl: Nat, +ehl: {hl == 64n : Nat}, +l: D.Digest, +r: D.Digest, +A: +List<U32>, +B: +List<U32>,
    +el: {D.bytes(l) == A : +List<U32>}, +er: {D.bytes(r) == B : +List<U32>})
    -> {D.bytes(D.node(hl, l, r)) == VF.sha256_bytes(List.append(&2, U32, A, B)) : +List<U32>}:
  %Equal.sym(+List<U32>, D.bytes(D.node(hl, l, r)), VF.sha256_bytes(List.append(&2, U32, D.bytes(l), D.bytes(r))), SN.node_at(hl, ehl, l, r)) :
    {_ == VF.sha256_bytes(List.append(&2, U32, A, B)) : +List<U32>}
  %Equal.sym(+List<U32>, D.bytes(l), A, el) : {VF.sha256_bytes(List.append(&2, U32, _, D.bytes(r))) == VF.sha256_bytes(List.append(&2, U32, A, B)) : +List<U32>}
  %Equal.sym(+List<U32>, D.bytes(r), B, er) : {VF.sha256_bytes(List.append(&2, U32, A, _)) == VF.sha256_bytes(List.append(&2, U32, A, B)) : +List<U32>}
  {==}

# Equality of active lists as a Bool (a closed schema fact), and its meaning.
def beq(xs: +List<Bool>, ys: +List<Bool>) -> Bool:
  match xs ys:
    case Nil{} Nil{}: True{}
    case Nil{} Con{True{}, u}: False{}
    case Nil{} Con{False{}, u}: False{}
    case Con{True{}, t} Nil{}: False{}
    case Con{False{}, t} Nil{}: False{}
    case Con{True{}, t} Con{True{}, u}: beq(t, u)
    case Con{True{}, t} Con{False{}, u}: False{}
    case Con{False{}, t} Con{True{}, u}: False{}
    case Con{False{}, t} Con{False{}, u}: beq(t, u)

law beq_eq:
  for +xs: +List<Bool>
  for +ys: +List<Bool>
  for +h: {beq(xs, ys) == True{} : Bool}
  {xs == ys : +List<Bool>}
def beq_eq(xs, ys, h):
  match xs ys:
    case Nil{} Nil{}: {==}
    case Nil{} Con{True{}, +u}: Empty.absurd({Nil{} == Con{True{}, u} : +List<Bool>}, MD.false_true(h))
    case Nil{} Con{False{}, +u}: Empty.absurd({Nil{} == Con{False{}, u} : +List<Bool>}, MD.false_true(h))
    case Con{True{}, +t} Nil{}: Empty.absurd({Con{True{}, t} == Nil{} : +List<Bool>}, MD.false_true(h))
    case Con{False{}, +t} Nil{}: Empty.absurd({Con{False{}, t} == Nil{} : +List<Bool>}, MD.false_true(h))
    case Con{True{}, +t} Con{True{}, +u}: Equal.cong(+List<Bool>, +List<Bool>, z => Con{True{}, z}, t, u, beq_eq(t, u, h))
    case Con{True{}, +t} Con{False{}, +u}: Empty.absurd({Con{True{}, t} == Con{False{}, u} : +List<Bool>}, MD.false_true(h))
    case Con{False{}, +t} Con{True{}, +u}: Empty.absurd({Con{False{}, t} == Con{True{}, u} : +List<Bool>}, MD.false_true(h))
    case Con{False{}, +t} Con{False{}, +u}: Equal.cong(+List<Bool>, +List<Bool>, z => Con{False{}, z}, t, u, beq_eq(t, u, h))

# The active bits mixed into a root, as the runtime's length mix.
def ml(+hl: Nat, +ehl: {hl == 64n : Nat}, +r: D.Digest, +m: U32, +LB: +List<U32>, +e: {D.bytes(O.len_chunk(m)) == LB : +List<U32>})
    -> RR.single(Mix.mix_length_bytes(Some{D.bytes(r)}, Some{LB}), [D.bytes(O.mix_len(hl, r, m))]):
  %Equal.sym(+List<U32>, D.bytes(D.node(hl, r, O.len_chunk(m))), VF.sha256_bytes(List.append(&2, U32, D.bytes(r), D.bytes(O.len_chunk(m)))), SN.node_at(hl, ehl, r, O.len_chunk(m))) :
    {Some{VF.sha256_bytes(List.append(&2, U32, D.bytes(r), LB))} == Some{_} : Maybe<&2, +List<U32>>}
  %Equal.sym(+List<U32>, D.bytes(O.len_chunk(m)), LB, e) :
    {Some{VF.sha256_bytes(List.append(&2, U32, D.bytes(r), LB))} == Some{VF.sha256_bytes(List.append(&2, U32, D.bytes(r), _))} : Maybe<&2, +List<U32>>}
  {==}
'''


def segments(L):
    """generate.prog_segments: [(k, start, cap)] covering L slots."""
    out, k = [], 0
    while True:
        start = ((1 << (2 * k)) - 1) // 3
        cap = 1 << (2 * k)
        out.append((k, start, cap))
        if start + cap >= L:
            return out
        k += 1


def tree(active):
    """The runtime tree of generate.emit_pcontainer_root as nodes:
    ('x', j) field j, ('0',) D.zero(), ('z', lv) D.zconst(lv), ('n', a, b)."""
    L = len(active)
    slots, j = [], 0
    for b in active:
        if b:
            slots.append(j)
            j += 1
        else:
            slots.append(None)
    acc = ('0',)
    for k, start, cap in reversed(segments(L)):
        level = []
        for i in range(cap):
            idx = start + i
            level.append(('x', slots[idx]) if idx < L and slots[idx] is not None else ('Z', 0))
        lv = 0
        while len(level) > 1:
            nxt = []
            for i in range(0, len(level), 2):
                a, b = level[i], level[i + 1]
                if a[0] == 'Z' and b[0] == 'Z':
                    nxt.append(('Z', lv + 1))
                else:
                    nxt.append(('n', conc(a), conc(b)))
            level = nxt
            lv += 1
        acc = ('n', conc(acc), conc(level[0]))
    return conc(acc)


def conc(node):
    if node[0] == 'Z':
        return ('0',) if node[1] == 0 else ('z', node[1])
    return node


def expr(t, xs):
    if t[0] == 'x':
        return xs[t[1]]
    if t[0] == '0':
        return 'D.zero()'
    if t[0] == 'z':
        return f'D.zconst({t[1]}n)'
    return f'D.node(hl, {expr(t[1], xs)}, {expr(t[2], xs)})'


def spec_bytes(t, xs):
    """(A, proof of {D.bytes(expr) == A})."""
    if t[0] != 'n':
        return f'D.bytes({expr(t, xs)})', '{==}'
    la, lp = spec_bytes(t[1], xs)
    ra, rp = spec_bytes(t[2], xs)
    return (f'VF.sha256_bytes(List.append(&2, U32, {la}, {ra}))',
            f'nb(hl, ehl, {expr(t[1], xs)}, {expr(t[2], xs)}, {la}, {ra}, {lp}, {rp})')


def key(active):
    return 'pc_' + ''.join('1' if a else '0' for a in active)


def mask(active):
    return sum(1 << i for i, b in enumerate(active) if b)


def act_term(active):
    return '[' + ', '.join('True{}' if a else 'False{}' for a in active) + ']'


def emit(active, w):
    K = key(active)
    n = sum(1 for a in active if a)
    xs = [f'x{i}' for i in range(n)]
    T = expr(tree(active), xs)
    ls, j = [], 0
    for a in active:
        if a:
            ls.append(xs[j])
            j += 1
        else:
            ls.append('D.zero()')
    Ls = '[' + ', '.join(ls) + ']'
    L = len(active)
    xa = ', '.join(f'+{x}: D.Digest' for x in xs)
    xc = ', '.join(xs)
    _, pf = spec_bytes(tree(active), xs)
    w(f'# ---- active {act_term(active)} ----')
    w(f'def {K}_pt(+hl: Nat, +ehl: {{hl == 64n : Nat}}, {xa})')
    w(f'    -> {{D.bytes({T}) == PS.tree({L}n, 0n, MD.bytes_list({Ls})) : +List<U32>}}:')
    w(f'  {pf}')
    w(f'def {K}_mk(+hl: Nat, +ehl: {{hl == 64n : Nat}}, {xa})')
    w(f'    -> {{PS.merkleize(MD.bytes_list({Ls})) == Some{{D.bytes({T})}} : Maybe<&2, +List<U32>>}}:')
    w(f'  %Equal.sym(Bool, Pack.chunks_domain(MD.bytes_list({Ls})), True{{}}, cdb({Ls})) :')
    w(f'    {{PS.gate(_, MD.bytes_list({Ls})) == Some{{D.bytes({T})}} : Maybe<&2, +List<U32>>}}')
    w(f'  %Equal.sym(+List<U32>, D.bytes({T}), PS.tree({L}n, 0n, MD.bytes_list({Ls})), {K}_pt(hl, ehl, {xc})) :')
    w(f'    {{Some{{PS.tree({L}n, 0n, MD.bytes_list({Ls}))}} == Some{{_}} : Maybe<&2, +List<U32>>}}')
    w('  {==}')
    A = act_term(active)
    LB = f'List.append(&2, U32, Bp.pack({A}), SP.zero_bytes(Nat.sub(32n, List.length(&2, U32, Bp.pack({A})))))'
    placed = 'Unit{}'
    for _ in active:
        placed = f'({{==}}, {placed})'
    w(f'def {K}_ar(+hl: Nat, +ehl: {{hl == 64n : Nat}}, {xa})')
    w(f'    -> RR.active_root({A}, MD.bytes_list([{xc}]), [D.bytes(O.mix_len(hl, {T}, {mask(active)}))]):')
    w(f'  (MD.bytes_list({Ls}), ({placed}, (D.bytes({T}),')
    w(f'    ({K}_mk(hl, ehl, {xc}), ml(hl, ehl, {T}, {mask(active)}, {LB}, {{==}})))))')
    w('')


def emit_msel(k, w):
    """A union's selector mixed into an option's root (spec/mixing.bend)."""
    w(f'def msel_{k}(+hl: Nat, +ehl: {{hl == 64n : Nat}}, +r: D.Digest) -> RR.single(Mx.mix_in_selector(D.bytes(r), {k}), [D.bytes(O.mix_len(hl, r, {k}))]):')
    w('  %Equal.sym(Bool, SP.byte_scope(32n, D.bytes(r)), True{}, SN.digest_scope(r)) :')
    w(f'    {{Mx.selector_checked(Bool.and(_, U32.is_lt({k}, 256)), D.bytes(r), {k}) == Some{{D.bytes(D.node(hl, r, O.len_chunk({k})))}} : Maybe<&2, +List<U32>>}}')
    w(f'  %Equal.sym(+List<U32>, D.bytes(D.node(hl, r, O.len_chunk({k}))), VF.sha256_bytes(List.append(&2, U32, D.bytes(r), D.bytes(O.len_chunk({k})))), SN.node_at(hl, ehl, r, O.len_chunk({k}))) :')
    w(f'    {{Mx.selector_checked(True{{}}, D.bytes(r), {k}) == Some{{_}} : Maybe<&2, +List<U32>>}}')
    w('  {==}')
    w('')


def emit_file(patterns, selectors=()):
    L = list(HEAD)
    L.append(LEMMAS)
    for k in sorted(set(selectors)):
        emit_msel(k, L.append)
    seen = set()
    for a in patterns:
        a = tuple(a)
        if a in seen:
            continue
        seen.add(a)
        emit(a, L.append)
    return '\n'.join(L) + '\n'
