#!/usr/bin/env python3
"""Emit proofs/obj/sha_node.bend: one Merkle node of the runtime hashes the
same 64-byte message as the independent specification.

    python3 codegen/sha_laws.py [--check]

Runtime (src/digest.bend): `hash_pair(l, r) = of_result(PKG.sha256(pair_words(l, r), 64n))`
with the pinned BendHub package. Specification (spec/merkle.bend): the
vendored FIPS 180-4 `sha256_bytes` of the 64 bytes `bytes(l) ++ bytes(r)`.

The checker normalizes eagerly and without sharing, so a type that contains
the 48-round message schedule of a concretely shaped block, or 16 unfolded
rounds from a concrete state, does not check in practice (measured, see
WORK_LOG.md). Nothing here normalizes SHA-256. Instead:

* `node_blocks` states the two compressions of a 64-byte message for an
  ARBITRARY round count `extra` and start state `s0`. With both variable the
  schedule extension and every round stay stuck, so the proof may case on the
  sixteen message words: both sides become the same two `compress` calls over
  the same words (`dec_be` identifies the specification's big-endian words
  with the runtime's words).
* The package law `sha256_array_correct` and the laws below are instantiated
  with `extra = 48` and the initial state only where the message array is
  still stuck on the variable digests, so the instances check without
  unfolding anything.
* `sha_bridge.bend` identifies the package's and the vendored copy of FIPS
  function by function.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'proofs/obj/sha_node.bend'
ZOUT = ROOT / 'proofs/obj/zero_roots.bend'
FOUT = ROOT / 'proofs/obj/sha_fast.bend'


def word(bits):
    s = 'WNil{}'
    for b in reversed(bits):
        s = f'WCon{{{b}, {s}}}'
    return f'U32{{{s}}}'


def be_bytes_of(x):
    return [f'(U32.shrn({x}, 24n) .&. 255 : U32)', f'(U32.shrn({x}, 16n) .&. 255 : U32)',
            f'(U32.shrn({x}, 8n) .&. 255 : U32)', f'({x} .&. 255 : U32)']


def dec_of(x):
    return f'VF.decode({", ".join(be_bytes_of(x))})'


# The residual of bit i of VF.decode(big-endian bytes of x) after casing x on
# its bits (read off the checker's normal form): byte k of the word carries
# k `or(_, and(and(a, False), False))` layers around `and(and(a, True), True)`.
def residual(i, a):
    e = f'Bool.and(Bool.and({a}, True{{}}), True{{}})'
    for _ in range(i // 8):
        e = f'Bool.or({e}, Bool.and(Bool.and({a}, False{{}}), False{{}}))'
    return e


def emit():
    L = []
    w = L.append
    w('import Base')
    w('import ../../src/digest.bend as D')
    w('import 0xe4067e0d858024083f36a7abe7281e89/spec/crypto/sha.bend as VF')
    w('import 0xe4067e0d858024083f36a7abe7281e89/src/crypto/sha/state.bend as VS')
    w('import 0xe4067e0d858024083f36a7abe7281e89/spec/crypto/sha.bend as PF')
    w('import 0xe4067e0d858024083f36a7abe7281e89/src/crypto/sha/state.bend as PS')
    w('import 0xe4067e0d858024083f36a7abe7281e89/spec/crypto/sha/packed.bend as PSP')
    w('import ../../proofs/compact/bits.bend as BT')
    w('import ./sha_bridge.bend as SB')
    w('import 0xe4067e0d858024083f36a7abe7281e89/src/crypto/sha/packed/buffer.bend as Buf')
    w('import 0xe4067e0d858024083f36a7abe7281e89/src/crypto/sha/packed/sha256.bend as PKG')
    w('import 0xe4067e0d858024083f36a7abe7281e89/proofs/crypto/sha/packed/laws.bend as PL')
    w('import 0xe4067e0d858024083f36a7abe7281e89/proofs/crypto/sha/packed/proof.bend as PC')
    w('import ../../spec/merkle.bend as M')
    w('import ../../spec/primitives.bend as P')
    w('')
    w('# GENERATED by codegen/sha_laws.py. Do not edit.')
    w('')
    # ---- dec_be ------------------------------------------------------------
    a = [f'a{i}' for i in range(32)]
    for k in range(4):
        e = residual(8 * k, 'x')
        w(f'def fixb{k}(+x: Bool) -> {{{e} == x : Bool}}:')
        w('  match x:')
        w('    case True{}: {==}')
        w('    case False{}: {==}')
    w('')
    w('# The specification reads a word back from its four big-endian bytes.')
    w('law dec_be:')
    w('  for +x: U32')
    w(f'  {{{dec_of("x")} == x : U32}}')
    w('def dec_be(x):')
    w('  match x:')
    w(f'    case {word(a)}:')
    res = [residual(i, a[i]) for i in range(32)]
    w(f'      BT.word32_eq({", ".join(res)}, {", ".join(a)}, ' +
      ', '.join(f'fixb{i // 8}({a[i]})' for i in range(32)) + ')')
    w('')
    # ---- node_blocks ---------------------------------------------------------
    la = [f'a{i}' for i in range(8)]
    lb = [f'b{i}' for i in range(8)]
    W1 = la + lb
    W1l = '[' + ', '.join(W1) + ']'
    W1s = '[' + ', '.join(dec_of(x) for x in W1) + ']'
    W2l = '[2147483648, ' + ', '.join(['0'] * 14) + ', 512]'
    K = 'PF.constants()'
    S1 = f'PF.compress(PF.schedule(extra, {W1l}), {K}, s0)'
    w('# The two compressions of a 64-byte message, for any round count and any')
    w('# start state: the packed reference over the runtime\'s message array, and')
    w('# the vendored FIPS over the 64 bytes of the same two chunks.')
    w('law node_blocks:')
    w('  for +extra: Nat')
    w('  for +s0: PS.State')
    w('  for +l: D.Digest')
    w('  for +r: D.Digest')
    w('  {SB.conv(PSP.take_state(PSP.blocks(extra, 1n, 0, 0n, 64n, (D.pair_words(l, r), s0))))')
    w('    == VF.blocks(VF.prepare(List.append(&2, U32, D.bytes(l), D.bytes(r)), extra), VF.constants())(SB.conv(s0)) : VS.State}')
    w('def node_blocks(extra, s0, l, r):')
    w('  match l:')
    w(f'    case D.D{{{", ".join("+" + x for x in la)}}}:')
    w('      match r:')
    w(f'        case D.D{{{", ".join("+" + x for x in lb)}}}:')
    I = '          '
    RHS = f'VF.compress(VF.schedule(extra, {W2l}), VF.constants(), VF.compress(VF.schedule(extra, {W1s}), VF.constants(), SB.conv(s0)))'
    # step 1: outer compression PF -> VF
    w(f'{I}%Equal.sym(VS.State, SB.conv(PF.compress(PF.schedule(extra, {W2l}), {K}, {S1})), VF.compress(PF.schedule(extra, {W2l}), {K}, SB.conv({S1})),')
    w(f'{I}    SB.compress_eq(PF.schedule(extra, {W2l}), {K}, {S1})) :')
    w(f'{I}  {{_ == {RHS} : VS.State}}')
    # step 2: inner compression
    w(f'{I}%Equal.sym(VS.State, SB.conv({S1}), VF.compress(PF.schedule(extra, {W1l}), {K}, SB.conv(s0)),')
    w(f'{I}    SB.compress_eq(PF.schedule(extra, {W1l}), {K}, s0)) :')
    w(f'{I}  {{VF.compress(PF.schedule(extra, {W2l}), {K}, _) == {RHS} : VS.State}}')
    # step 3/4: schedules
    w(f'{I}%Equal.sym(List<&2, U32>, PF.schedule(extra, {W2l}), VF.schedule(extra, {W2l}), SB.schedule_eq(extra, {W2l})) :')
    w(f'{I}  {{VF.compress(_, {K}, VF.compress(PF.schedule(extra, {W1l}), {K}, SB.conv(s0))) == {RHS} : VS.State}}')
    w(f'{I}%Equal.sym(List<&2, U32>, PF.schedule(extra, {W1l}), VF.schedule(extra, {W1l}), SB.schedule_eq(extra, {W1l})) :')
    w(f'{I}  {{VF.compress(VF.schedule(extra, {W2l}), {K}, VF.compress(_, {K}, SB.conv(s0))) == {RHS} : VS.State}}')
    # step 5: the words of the first block
    for i, x in enumerate(W1):
        pre = [dec_of(y) for y in W1[:i]]
        post = W1[i + 1:]
        hole = '[' + ', '.join(pre + ['_'] + post) + ']'
        w(f'{I}%dec_be({x}) :')
        w(f'{I}  {{VF.compress(VF.schedule(extra, {W2l}), {K}, VF.compress(VF.schedule(extra, {hole}), {K}, SB.conv(s0))) == {RHS} : VS.State}}')
    w(f'{I}{{==}}')
    w('')
    emit_node(w)
    return '\n'.join(L) + '\n'


def emit_node(w):
    la = [f'a{i}' for i in range(8)]
    lb = [f'b{i}' for i in range(8)]
    PW = 'D.pair_words(l, r)'
    w('# The message array of a node holds sixteen words.')
    w('law pair_size:')
    w('  for +l: D.Digest')
    w('  for +r: D.Digest')
    w(f'  {{Array.size(U32, {PW}) == ({PW}, 16) : Array<U32> & U32}}')
    w('def pair_size(l, r):')
    w('  match l:')
    w(f'    case D.D{{{", ".join("+" + x for x in la)}}}:')
    w('      match r:')
    w(f'        case D.D{{{", ".join("+" + x for x in lb)}}}: {{==}}')
    w('')
    w('# The runtime node is the package\'s packed specification of its message')
    w('# (package law `sha256_array_correct`, instantiated at the stuck message).')
    w('law hash_pair_packed:')
    w('  for +l: D.Digest')
    w('  for +r: D.Digest')
    w(f'  {{D.hash_pair(l, r) == D.of_result(Buf.result(PSP.hash({PW}, 64n))) : D.Digest}}')
    w('def hash_pair_packed(l, r):')
    w(f'  Equal.cong(Maybe<&1, Array<U32>>, D.Digest, x => D.of_result(x), PKG.sha256({PW}, 64n),')
    w(f'    Buf.result(PSP.hash({PW}, 64n)), PL.sha256_array_correct({PW}, 64n))')
    w('')
    st = [f's{i}' for i in range(8)]
    w('# The bytes of the eight result words are the FIPS digest octets.')
    w('law digest_bytes:')
    w('  for +s: PS.State')
    w('  {D.bytes(D.of_array(Buf.digest(s))) == VF.digest_octets(VF.digest(SB.conv(s))) : List<&2, U32>}')
    w('def digest_bytes(s):')
    w('  match s:')
    w(f'    case PS.H{{{", ".join("+" + x for x in st)}}}: {{==}}')
    w('')
    ST = f'PSP.take_state(PSP.blocks(48n, 1n, 0, 0n, 64n, ({PW}, PF.initial())))'
    MSG = 'List.append(&2, U32, D.bytes(l), D.bytes(r))'
    w('# ONE MERKLE NODE: the runtime node hashes exactly the specification\'s')
    w('# 64-byte message, through the pinned package, with no SHA normalization.')
    w('law node:')
    w('  for +l: D.Digest')
    w('  for +r: D.Digest')
    w(f'  {{D.bytes(D.hash_pair(l, r)) == VF.sha256_bytes({MSG}) : List<&2, U32>}}')
    w('def node(l, r):')
    w(f'  %Equal.sym(D.Digest, D.hash_pair(l, r), D.of_result(Buf.result(PSP.hash({PW}, 64n))), hash_pair_packed(l, r)) :')
    w(f'    {{D.bytes(_) == VF.sha256_bytes({MSG}) : List<&2, U32>}}')
    w(f'  %Equal.sym(Array<U32> & U32, Array.size(U32, {PW}), ({PW}, 16), pair_size(l, r)) :')
    w(f'    {{D.bytes(D.of_result(Buf.result(PSP.sized(64n, _)))) == VF.sha256_bytes({MSG}) : List<&2, U32>}}')
    w(f'  %Equal.sym(List<&2, U32>, D.bytes(D.of_array(Buf.digest({ST}))), VF.digest_octets(VF.digest(SB.conv({ST}))), digest_bytes({ST})) :')
    w(f'    {{_ == VF.sha256_bytes({MSG}) : List<&2, U32>}}')
    w(f'  %Equal.sym(VS.State, SB.conv({ST}), VF.blocks(VF.prepare({MSG}, 48n), VF.constants())(SB.conv(PF.initial())), node_blocks(48n, PF.initial(), l, r)) :')
    w(f'    {{VF.digest_octets(VF.digest(_)) == VF.sha256_bytes({MSG}) : List<&2, U32>}}')
    w('  {==}')
    w('')
    w('# The node at a message length known only through an equation: the root')
    w('# laws hold `hl` abstract (so nodes over constructor digests stay stuck) and')
    w('# carry `hl == 64n`; this is the only place that equation is used.')
    w('law node_at:')
    w('  for +hl: Nat')
    w('  for +ehl: {hl == 64n : Nat}')
    w('  for +l: D.Digest')
    w('  for +r: D.Digest')
    w(f'  {{D.bytes(D.node(hl, l, r)) == VF.sha256_bytes({MSG}) : List<&2, U32>}}')
    w('def node_at(hl, ehl, l, r):')
    w(f'  %Equal.sym(Nat, hl, 64n, ehl) : {{D.bytes(D.node(_, l, r)) == VF.sha256_bytes({MSG}) : List<&2, U32>}}')
    w('  node(l, r)')
    w('')
    # ---- the specification's node over digest bytes ------------------------
    a = [f'a{i}' for i in range(32)]
    lo = [f'Bool.and({a[i]}, True{{}})' for i in range(8)]
    hi = [f'Bool.and({a[i]}, False{{}})' for i in range(8, 32)]
    w('# A masked byte is below 256.')
    w('law lt_byte:')
    w('  for +y: U32')
    w('  {U32.is_lt((y .&. 255 : U32), 256) == True{} : Bool}')
    w('def lt_byte(y):')
    w('  match y:')
    w(f'    case {word(a)}:')
    for i in range(8, 32):
        bits = lo + ['False{}'] * (i - 8) + ['_'] + hi[i - 7:]
        w(f'      %Equal.sym(Bool, Bool.and({a[i]}, False{{}}), False{{}}, BT.and_false({a[i]})) :')
        w(f'        {{U32.is_lt({word(bits)}, 256) == True{{}} : Bool}}')
    w('      {==}')
    w('')
    ds = [f'd{i}' for i in range(8)]
    w('# The bytes of a digest are 32 bytes.')
    w('law digest_scope:')
    w('  for +d: D.Digest')
    w('  {P.byte_scope(32n, D.bytes(d)) == True{} : Bool}')
    w('def digest_scope(d):')
    w('  match d:')
    w(f'    case D.D{{{", ".join("+" + x for x in ds)}}}:')
    terms = []
    for x in ds:
        terms += [f'U32.shrn({x}, 24n)', f'U32.shrn({x}, 16n)', f'U32.shrn({x}, 8n)', x]
    lts = [f'U32.is_lt(({t} .&. 255 : U32), 256)' for t in terms]
    for i, t in enumerate(terms):
        parts = ['True{}'] * i + ['_'] + lts[i + 1:]
        e = 'True{}'
        for p in reversed(parts):
            e = f'Bool.and({p}, {e})'
        w(f'      %Equal.sym(Bool, {lts[i]}, True{{}}, lt_byte({t})) :')
        w(f'        {{{e} == True{{}} : Bool}}')
    w('      {==}')
    w('')
    w('# The specification\'s node over the bytes of two digests is the runtime')
    w('# node\'s bytes.')
    w('law spec_node:')
    w('  for +l: D.Digest')
    w('  for +r: D.Digest')
    w('  {M.hash_pair(D.bytes(l), D.bytes(r)) == Some{D.bytes(D.hash_pair(l, r))} : Maybe<&2, List<&2, U32>>}')
    w('def spec_node(l, r):')
    w('  %Equal.sym(Bool, P.byte_scope(32n, D.bytes(l)), True{}, digest_scope(l)) :')
    w('    {M.pair_checked(Bool.and(_, P.byte_scope(32n, D.bytes(r))), D.bytes(l), D.bytes(r)) == Some{D.bytes(D.hash_pair(l, r))} : Maybe<&2, List<&2, U32>>}')
    w('  %Equal.sym(Bool, P.byte_scope(32n, D.bytes(r)), True{}, digest_scope(r)) :')
    w('    {M.pair_checked(Bool.and(True{}, _), D.bytes(l), D.bytes(r)) == Some{D.bytes(D.hash_pair(l, r))} : Maybe<&2, List<&2, U32>>}')
    w(f'  %Equal.sym(List<&2, U32>, D.bytes(D.hash_pair(l, r)), VF.sha256_bytes({MSG}), node(l, r)) :')
    w(f'    {{Some{{VF.sha256_bytes({MSG})}} == Some{{_}} : Maybe<&2, List<&2, U32>>}}')
    w('  {==}')
    w('')


def emit_fast():
    """proofs/obj/sha_fast.bend: FIPS 180-4 SHA-256 with one-pattern shifts, proved
    equal to the specification for every input (sha256_bytes_eq)."""
    L = []
    w = L.append
    PKG = '0xe4067e0d858024083f36a7abe7281e89'
    w('import Base')
    w(f'import {PKG}/spec/crypto/sha.bend as VF')
    w(f'import {PKG}/src/crypto/sha/state.bend as Types')
    w('')
    w('# GENERATED by codegen/sha_laws.py. Do not edit.')
    w('# A second evaluator of the FIPS 180-4 SHA-256 specification (spec/crypto/sha.bend)')
    w('# for closed inputs: the same definitions with each shift and rotation by a')
    w('# constant written as one pattern over the 32 bits (U32.shrn(x, n) takes n')
    w('# passes over the word). `sha256_bytes_eq` proves it equal to the specification')
    w('# for every input, symbolically; proofs/obj/zero_roots.bend evaluates it.')
    w('')
    def cons(xs, tail):
        s = tail
        for x in reversed(xs):
            s = f'Con{{{x}, {s}}}'
        return s
    bits = [f'b{i}' for i in range(32)]
    def word(xs):
        s = 'WNil{}'
        for x in reversed(xs):
            s = f'WCon{{{x}, {s}}}'
        return s
    pat = f'U32{{{word(bits)}}}'
    rots = [7, 18, 17, 19, 2, 13, 22, 6, 11, 25]
    shr_ns = sorted(set(rots + [3, 10, 8, 16, 24]))
    shl_ns = sorted(set([32 - r for r in rots] + [8, 16, 24]))
    for n in shr_ns:
        w(f'def shr{n}(x: U32) -> U32:')
        w('  match x:')
        w(f'    case {pat}: U32{{{word(bits[n:] + ["False{}"] * n)}}}')
        w('')
        w(f'law shr{n}_eq:')
        w('  for +x: U32')
        w(f'  {{shr{n}(x) == U32.shrn(x, {n}n) : U32}}')
        w(f'def shr{n}_eq(x):')
        w('  match x:')
        w(f'    case {pat}: {{==}}')
        w('')
    for n in shl_ns:
        w(f'def shl{n}(x: U32) -> U32:')
        w('  match x:')
        w(f'    case {pat}: U32{{{word(["False{}"] * n + bits[:32 - n])}}}')
        w('')
        w(f'law shl{n}_eq:')
        w('  for +x: U32')
        w(f'  {{shl{n}(x) == U32.shln(x, {n}n) : U32}}')
        w(f'def shl{n}_eq(x):')
        w('  match x:')
        w(f'    case {pat}: {{==}}')
        w('')
    for r in rots:
        m = 32 - r
        w(f'def rot{r}(+x: U32) -> U32: U32.or(shr{r}(x), shl{m}(x))')
        w(f'law rot{r}_eq:')
        w('  for +x: U32')
        w(f'  {{rot{r}(x) == VF.rotate(x, {r}n) : U32}}')
        w(f'def rot{r}_eq(x):')
        w(f'  %Equal.sym(U32, shr{r}(x), U32.shrn(x, {r}n), shr{r}_eq(x)) : {{U32.or(_, shl{m}(x)) == VF.rotate(x, {r}n) : U32}}')
        w(f'  %Equal.sym(U32, shl{m}(x), U32.shln(x, {m}n), shl{m}_eq(x)) : {{U32.or(U32.shrn(x, {r}n), _) == VF.rotate(x, {r}n) : U32}}')
        w('  {==}')
        w('')
    # sigma / sum
    fams = [('sigma0', ('rot', 7), ('rot', 18), ('shr', 3)), ('sigma1', ('rot', 17), ('rot', 19), ('shr', 10)),
            ('sum0', ('rot', 2), ('rot', 13), ('rot', 22)), ('sum1', ('rot', 6), ('rot', 11), ('rot', 25))]
    def fast(t):
        return f'{t[0]}{t[1]}(x)'
    def spec(t):
        return f'VF.rotate(x, {t[1]}n)' if t[0] == 'rot' else f'U32.shrn(x, {t[1]}n)'
    for nm, a, b, c in fams:
        w(f'def {nm}f(+x: U32) -> U32: U32.xor(U32.xor({fast(a)}, {fast(b)}), {fast(c)})')
        w(f'law {nm}_eq:')
        w('  for +x: U32')
        w(f'  {{{nm}f(x) == VF.{nm}(x) : U32}}')
        w(f'def {nm}_eq(x):')
        w(f'  %Equal.sym(U32, {fast(a)}, {spec(a)}, {a[0]}{a[1]}_eq(x)) : {{U32.xor(U32.xor(_, {fast(b)}), {fast(c)}) == VF.{nm}(x) : U32}}')
        w(f'  %Equal.sym(U32, {fast(b)}, {spec(b)}, {b[0]}{b[1]}_eq(x)) : {{U32.xor(U32.xor({spec(a)}, _), {fast(c)}) == VF.{nm}(x) : U32}}')
        w(f'  %Equal.sym(U32, {fast(c)}, {spec(c)}, {c[0]}{c[1]}_eq(x)) : {{U32.xor(U32.xor({spec(a)}, {spec(b)}), _) == VF.{nm}(x) : U32}}')
        w('  {==}')
        w('')
    P = lambda h, l: f'VF.previous({h}, {l}n)'
    w('def recurrencef(+history: List<&2, U32>) -> U32:')
    w(f'  (sigma1f({P("history", 2)}) + {P("history", 7)} + sigma0f({P("history", 15)}) + {P("history", 16)} : U32)')
    w('law recurrence_eq:')
    w('  for +history: List<&2, U32>')
    w('  {recurrencef(history) == VF.recurrence(history) : U32}')
    w('def recurrence_eq(history):')
    w(f'  %Equal.sym(U32, sigma1f({P("history", 2)}), VF.sigma1({P("history", 2)}), sigma1_eq({P("history", 2)})) :')
    w(f'    {{(_ + {P("history", 7)} + sigma0f({P("history", 15)}) + {P("history", 16)} : U32) == VF.recurrence(history) : U32}}')
    w(f'  %Equal.sym(U32, sigma0f({P("history", 15)}), VF.sigma0({P("history", 15)}), sigma0_eq({P("history", 15)})) :')
    w(f'    {{(VF.sigma1({P("history", 2)}) + {P("history", 7)} + _ + {P("history", 16)} : U32) == VF.recurrence(history) : U32}}')
    w('  {==}')
    w('')
    w('def extensionf(rounds: Nat, +history: List<&2, U32>) -> List<&2, U32>:')
    w('  match rounds:')
    w('    case 0n:')
    w('      Nil{}')
    w('    case 1n+p:')
    w('      +w = recurrencef(history)')
    w('      w <> extensionf(p, w <> history)')
    w('')
    w('law extension_eq:')
    w('  for +rounds: Nat')
    w('  for +history: List<&2, U32>')
    w('  {extensionf(rounds, history) == VF.extension(rounds, history) : List<&2, U32>}')
    w('def extension_eq(rounds, history):')
    w('  match rounds:')
    w('    case 0n: {==}')
    w('    case 1n+ +p:')
    w('      %Equal.sym(U32, recurrencef(history), VF.recurrence(history), recurrence_eq(history)) :')
    w('        {Con{_, extensionf(p, Con{_, history})} == VF.extension(1n+p, history) : List<&2, U32>}')
    w('      Equal.cong(List<&2, U32>, List<&2, U32>, zl_ => Con{VF.recurrence(history), zl_},')
    w('        extensionf(p, Con{VF.recurrence(history), history}), VF.extension(p, Con{VF.recurrence(history), history}),')
    w('        extension_eq(p, Con{VF.recurrence(history), history}))')
    w('')
    w('def schedulef(extra: Nat, +block: List<&2, U32>) -> List<&2, U32>:')
    w('  List.append(&2, U32, block, extensionf(extra, List.reverse(&2, U32, block)))')
    w('law schedule_eq:')
    w('  for +extra: Nat')
    w('  for +block: List<&2, U32>')
    w('  {schedulef(extra, block) == VF.schedule(extra, block) : List<&2, U32>}')
    w('def schedule_eq(extra, block):')
    w('  Equal.cong(List<&2, U32>, List<&2, U32>, zl_ => List.append(&2, U32, block, zl_),')
    w('    extensionf(extra, List.reverse(&2, U32, block)), VF.extension(extra, List.reverse(&2, U32, block)),')
    w('    extension_eq(extra, List.reverse(&2, U32, block)))')
    w('')
    v16 = 'abcdefghijklmnop'
    w('def schedulesf(ws: List<&2, U32>, +extra: Nat) -> List<&2, List<&2, U32>>:')
    w('  match ws:')
    w('    case ' + ' <> '.join(v16) + ' <> rest:')
    w('      schedulef(extra, [' + ', '.join(v16) + ']) <> schedulesf(rest, extra)')
    w('    case _:')
    w('      Nil{}')
    w('')
    w('law schedules_eq:')
    w('  for +ws: List<&2, U32>')
    w('  for +extra: Nat')
    w('  {schedulesf(ws, extra) == VF.schedules(ws, extra) : List<&2, List<&2, U32>>}')
    w('def schedules_eq(ws, extra):')
    w('  match ws:')
    for n in range(16):
        w(f'    case {cons(["+" + c for c in v16[:n]], "Nil{}")}: {{==}}')
    blk = '[' + ', '.join(v16) + ']'
    w(f'    case {cons(["+" + c for c in v16], "+rest")}:')
    w(f'      %Equal.sym(List<&2, U32>, schedulef(extra, {blk}), VF.schedule(extra, {blk}), schedule_eq(extra, {blk})) :')
    w(f'        {{Con{{_, schedulesf(rest, extra)}} == VF.schedules({cons(list(v16), "rest")}, extra) : List<&2, List<&2, U32>>}}')
    w(f'      Equal.cong(List<&2, List<&2, U32>>, List<&2, List<&2, U32>>, zl_ => Con{{VF.schedule(extra, {blk}), zl_}},')
    w('        schedulesf(rest, extra), VF.schedules(rest, extra), schedules_eq(rest, extra))')
    w('')
    w('def decodef(a: U32, b: U32, c: U32, d: U32) -> U32:')
    w('  U32.or(U32.or(U32.or(shl24(U32.and(a, 255)), shl16(U32.and(b, 255))), shl8(U32.and(c, 255))), U32.and(d, 255))')
    w('law decode_eq:')
    w('  for +a: U32')
    w('  for +b: U32')
    w('  for +c: U32')
    w('  for +d: U32')
    w('  {decodef(a, b, c, d) == VF.decode(a, b, c, d) : U32}')
    w('def decode_eq(a, b, c, d):')
    DA = lambda x, y, z: f'U32.or(U32.or(U32.or({x}, {y}), {z}), U32.and(d, 255))'
    w(f'  %Equal.sym(U32, shl24(U32.and(a, 255)), U32.shln(U32.and(a, 255), 24n), shl24_eq(U32.and(a, 255))) :')
    w(f'    {{{DA("_", "shl16(U32.and(b, 255))", "shl8(U32.and(c, 255))")} == VF.decode(a, b, c, d) : U32}}')
    w(f'  %Equal.sym(U32, shl16(U32.and(b, 255)), U32.shln(U32.and(b, 255), 16n), shl16_eq(U32.and(b, 255))) :')
    w(f'    {{{DA("U32.shln(U32.and(a, 255), 24n)", "_", "shl8(U32.and(c, 255))")} == VF.decode(a, b, c, d) : U32}}')
    w(f'  %Equal.sym(U32, shl8(U32.and(c, 255)), U32.shln(U32.and(c, 255), 8n), shl8_eq(U32.and(c, 255))) :')
    w(f'    {{{DA("U32.shln(U32.and(a, 255), 24n)", "U32.shln(U32.and(b, 255), 16n)", "_")} == VF.decode(a, b, c, d) : U32}}')
    w('  {==}')
    w('')
    w('def wordsf(bytes: List<&2, U32>) -> List<&2, U32>:')
    w('  match bytes:')
    w('    case a <> b <> c <> d <> rest:')
    w('      decodef(a, b, c, d) <> wordsf(rest)')
    w('    case _:')
    w('      Nil{}')
    w('')
    w('law words_eq:')
    w('  for +bytes: List<&2, U32>')
    w('  {wordsf(bytes) == VF.words(bytes) : List<&2, U32>}')
    w('def words_eq(bytes):')
    w('  match bytes:')
    for n in range(4):
        w(f'    case {cons(["+" + c for c in "abcd"[:n]], "Nil{}")}: {{==}}')
    w(f'    case {cons(["+" + c for c in "abcd"], "+rest")}:')
    w('      %Equal.sym(U32, decodef(a, b, c, d), VF.decode(a, b, c, d), decode_eq(a, b, c, d)) :')
    w(f'        {{Con{{_, wordsf(rest)}} == VF.words({cons(list("abcd"), "rest")}) : List<&2, U32>}}')
    w('      Equal.cong(List<&2, U32>, List<&2, U32>, zl_ => Con{VF.decode(a, b, c, d), zl_}, wordsf(rest), VF.words(rest), words_eq(rest))')
    w('')
    w('def preparef(bytes: List<&2, U32>, extra: Nat) -> List<&2, List<&2, U32>>:')
    w('  schedulesf(wordsf(VF.pad(bytes)), extra)')
    w('')
    w('law prepare_eq:')
    w('  for +bytes: List<&2, U32>')
    w('  for +extra: Nat')
    w('  {preparef(bytes, extra) == VF.prepare(bytes, extra) : List<&2, List<&2, U32>>}')
    w('def prepare_eq(bytes, extra):')
    w('  %Equal.sym(List<&2, U32>, wordsf(VF.pad(bytes)), VF.words(VF.pad(bytes)), words_eq(VF.pad(bytes))) :')
    w('    {schedulesf(_, extra) == VF.prepare(bytes, extra) : List<&2, List<&2, U32>>}')
    w('  schedules_eq(VF.words(VF.pad(bytes)), extra)')
    w('')
    w('def stepf(s: Types.State, k: U32, w: U32) -> Types.State:')
    w('  Types.H{+a, +b, +c, d, +e, +f, +g, h} = s')
    w('  +t1 = (h + sum1f(e) + VF.ch(e, f, g) + k + w : U32)')
    w('  t2 = (sum0f(a) + VF.maj(a, b, c) : U32)')
    w('  Types.H{(t1 + t2 : U32), a, b, c, (d + t1 : U32), e, f, g}')
    w('')
    w('law step_eq:')
    w('  for +s: Types.State')
    w('  for +k: U32')
    w('  for +w: U32')
    w('  {stepf(s, k, w) == VF.step(s, k, w) : Types.State}')
    w('def step_eq(s, k, w):')
    w('  match s:')
    w('    case Types.H{+a, +b, +c, +d, +e, +f, +g, +h}:')
    T1 = lambda S1: f'(h + {S1} + VF.ch(e, f, g) + k + w : U32)'
    ST = lambda S1, S0: f'Types.H{{({T1(S1)} + ({S0} + VF.maj(a, b, c) : U32) : U32), a, b, c, (d + {T1(S1)} : U32), e, f, g}}'
    goal = 'VF.step(Types.H{a, b, c, d, e, f, g, h}, k, w)'
    w(f'      %Equal.sym(U32, sum1f(e), VF.sum1(e), sum1_eq(e)) :')
    w(f'        {{{ST("_", "sum0f(a)")} == {goal} : Types.State}}')
    w(f'      %Equal.sym(U32, sum0f(a), VF.sum0(a), sum0_eq(a)) :')
    w(f'        {{{ST("VF.sum1(e)", "_")} == {goal} : Types.State}}')
    w('      {==}')
    w('')
    w('def roundsf(ks: List<&2, U32>, ws: List<&2, U32>) -> Types.State -> Types.State:')
    w('  match ks ws:')
    w('    case Nil{} _:')
    w('      s => s')
    w('    case k <> kt Nil{}:')
    w('      s => s')
    w('    case k <> kt w <> wt:')
    w('      next = roundsf(kt, wt)')
    w('      s => next(stepf(s, k, w))')
    w('')
    w('law rounds_eq:')
    w('  for +ks: List<&2, U32>')
    w('  for +ws: List<&2, U32>')
    w('  for +s: Types.State')
    w('  {roundsf(ks, ws)(s) == VF.rounds(ks, ws)(s) : Types.State}')
    w('def rounds_eq(ks, ws, s):')
    w('  match ks ws:')
    w('    case Nil{} Nil{}: {==}')
    w('    case Nil{} Con{+w, +wt}: {==}')
    w('    case Con{+k, +kt} Nil{}: {==}')
    w('    case Con{+k, +kt} Con{+w, +wt}:')
    w('      %Equal.sym(Types.State, stepf(s, k, w), VF.step(s, k, w), step_eq(s, k, w)) :')
    w('        {roundsf(kt, wt)(_) == VF.rounds(Con{k, kt}, Con{w, wt})(s) : Types.State}')
    w('      rounds_eq(kt, wt, VF.step(s, k, w))')
    w('')
    w('def compressf(ws: List<&2, U32>, ks: List<&2, U32>, +s: Types.State) -> Types.State:')
    w('  VF.feedforward(s, roundsf(ks, ws)(s))')
    w('')
    w('def blocksf(prepared: List<&2, List<&2, U32>>, +ks: List<&2, U32>) -> Types.State -> Types.State:')
    w('  match prepared:')
    w('    case Nil{}:')
    w('      s => s')
    w('    case block <> rest:')
    w('      next = blocksf(rest, ks)')
    w('      s => next(compressf(block, ks, s))')
    w('')
    w('law blocks_eq:')
    w('  for +prepared: List<&2, List<&2, U32>>')
    w('  for +ks: List<&2, U32>')
    w('  for +s: Types.State')
    w('  {blocksf(prepared, ks)(s) == VF.blocks(prepared, ks)(s) : Types.State}')
    w('def blocks_eq(prepared, ks, s):')
    w('  match prepared:')
    w('    case Nil{}: {==}')
    w('    case Con{+block, +rest}:')
    w('      %Equal.sym(Types.State, roundsf(ks, block)(s), VF.rounds(ks, block)(s), rounds_eq(ks, block, s)) :')
    w('        {blocksf(rest, ks)(VF.feedforward(s, _)) == VF.blocks(Con{block, rest}, ks)(s) : Types.State}')
    w('      blocks_eq(rest, ks, VF.compress(block, ks, s))')
    w('')
    w('def word_octetsf(+w: U32) -> List<&2, U32>:')
    w('  [U32.and(shr24(w), 255), U32.and(shr16(w), 255), U32.and(shr8(w), 255), U32.and(w, 255)]')
    w('')
    w('def digest_octetsf(ws: List<&2, U32>) -> List<&2, U32>:')
    w('  match ws:')
    w('    case Nil{}:')
    w('      Nil{}')
    w('    case w <> tail:')
    w('      List.append(&2, U32, word_octetsf(w), digest_octetsf(tail))')
    w('')
    w('law digest_octets_eq:')
    w('  for +ws: List<&2, U32>')
    w('  {digest_octetsf(ws) == VF.digest_octets(ws) : List<&2, U32>}')
    w('def digest_octets_eq(ws):')
    w('  match ws:')
    w('    case Nil{}: {==}')
    w('    case Con{+w, +tail}:')
    WO = lambda x, y, z: f'List.append(&2, U32, [U32.and({x}, 255), U32.and({y}, 255), U32.and({z}, 255), U32.and(w, 255)], digest_octetsf(tail))'
    goal = 'VF.digest_octets(Con{w, tail})'
    w(f'      %Equal.sym(U32, shr24(w), U32.shrn(w, 24n), shr24_eq(w)) : {{{WO("_", "shr16(w)", "shr8(w)")} == {goal} : List<&2, U32>}}')
    w(f'      %Equal.sym(U32, shr16(w), U32.shrn(w, 16n), shr16_eq(w)) : {{{WO("U32.shrn(w, 24n)", "_", "shr8(w)")} == {goal} : List<&2, U32>}}')
    w(f'      %Equal.sym(U32, shr8(w), U32.shrn(w, 8n), shr8_eq(w)) : {{{WO("U32.shrn(w, 24n)", "U32.shrn(w, 16n)", "_")} == {goal} : List<&2, U32>}}')
    w('      Equal.cong(List<&2, U32>, List<&2, U32>, zl_ => List.append(&2, U32, VF.word_octets(w), zl_), digest_octetsf(tail), VF.digest_octets(tail), digest_octets_eq(tail))')
    w('')
    w('def sha256_bytesf(bytes: List<&2, U32>) -> List<&2, U32>:')
    w('  digest_octetsf(VF.digest(blocksf(preparef(bytes, 48n), VF.constants())(VF.initial())))')
    w('')
    w('law sha256_bytes_eq:')
    w('  for +bytes: List<&2, U32>')
    w('  {sha256_bytesf(bytes) == VF.sha256_bytes(bytes) : List<&2, U32>}')
    w('def sha256_bytes_eq(bytes):')
    w('  %Equal.sym(List<&2, List<&2, U32>>, preparef(bytes, 48n), VF.prepare(bytes, 48n), prepare_eq(bytes, 48n)) :')
    w('    {digest_octetsf(VF.digest(blocksf(_, VF.constants())(VF.initial()))) == VF.sha256_bytes(bytes) : List<&2, U32>}')
    w('  %Equal.sym(Types.State, blocksf(VF.prepare(bytes, 48n), VF.constants())(VF.initial()), VF.blocks(VF.prepare(bytes, 48n), VF.constants())(VF.initial()),')
    w('      blocks_eq(VF.prepare(bytes, 48n), VF.constants(), VF.initial())) :')
    w('    {digest_octetsf(VF.digest(_)) == VF.sha256_bytes(bytes) : List<&2, U32>}')
    w('  digest_octets_eq(VF.digest(VF.blocks(VF.prepare(bytes, 48n), VF.constants())(VF.initial())))')
    return '\n'.join(L) + '\n'


def emit_zero():
    """proofs/obj/zero_roots.bend: the constants D.zconst(k) are the
    specification's zero subtrees, for every k < 64."""
    L = []
    w = L.append
    w('import Base')
    w('import ../../src/digest.bend as D')
    w('import ../../spec/merkle.bend as M')
    w('import 0xe4067e0d858024083f36a7abe7281e89/spec/crypto/sha.bend as VF')
    w('import ../compact/found.bend as F')
    w('import ./sha_fast.bend as SF')
    w('')
    w('# GENERATED by codegen/sha_laws.py. Do not edit.')
    w('# The zero-subtree constants of src/digest.bend against spec/merkle.bend:')
    w('# `zconst_fast` evaluates one concrete FIPS 180-4 hash per level (63 cases) on')
    w('# sha_fast.bend\'s evaluator (2.6x fewer steps than the specification\'s own');
    w('# shifts), `zconst_step` is the specification\'s hash by SF.sha256_bytes_eq, and')
    w('# `zconst_spec` then follows zero_subtree\'s own recursion.')
    w('')
    w('def disc(b: Bool) -> Type:')
    w('  match b:')
    w('    case True{}: Unit')
    w('    case False{}: Empty')
    w('')
    w('def false_true(e: {False{} == True{} : Bool}) -> Empty:')
    w('  %Equal.sym(Bool, False{}, True{}, e) : disc(_)')
    w('  Unit{}')
    w('')
    Z = lambda k: f'D.zconst({k})'
    w('law zconst_fast:')
    w('  for +k: Nat')
    w('  for +hk: {Nat.is_lt(k, 63n) == True{} : Bool}')
    w(f'  {{D.bytes(D.zconst(1n+k)) == SF.sha256_bytesf(List.append(&2, U32, D.bytes(D.zconst(k)), D.bytes(D.zconst(k)))) : List<&2, U32>}}')
    w('def zconst_fast(k, hk):')
    cur = 'k'
    for i in range(63):
        pad = '  ' * (i + 1)
        w(f'{pad}match {cur}:')
        w(f'{pad}  case 0n: {{==}}')
        nxt = f'k{i + 1}'
        if i < 62:
            w(f'{pad}  case 1n+ +{nxt}:')
        else:
            kk = f'{i + 1}n+{nxt}'
            w(f'{pad}  case 1n+ +{nxt}:')
            w(f'{pad}    Empty.absurd({{D.bytes(D.zconst(1n+{kk})) == SF.sha256_bytesf(List.append(&2, U32, D.bytes(D.zconst({kk})), D.bytes(D.zconst({kk})))) : List<&2, U32>}}, false_true(Equal.trans(Bool, False{{}}, Nat.is_lt({nxt}, 0n), True{{}}, Equal.sym(Bool, Nat.is_lt({nxt}, 0n), False{{}}, F.nat__not_lt_zero({nxt})), hk)))')
        cur = nxt
    w('')
    MSG = 'List.append(&2, U32, D.bytes(D.zconst(k)), D.bytes(D.zconst(k)))'
    w('law zconst_step:')
    w('  for +k: Nat')
    w('  for +hk: {Nat.is_lt(k, 63n) == True{} : Bool}')
    w(f'  {{D.bytes(D.zconst(1n+k)) == VF.sha256_bytes({MSG}) : List<&2, U32>}}')
    w('def zconst_step(k, hk):')
    w(f'  Equal.trans(List<&2, U32>, D.bytes(D.zconst(1n+k)), SF.sha256_bytesf({MSG}), VF.sha256_bytes({MSG}),')
    w(f'    zconst_fast(k, hk), SF.sha256_bytes_eq({MSG}))')
    w('')
    w('law zconst_spec:')
    w('  for +k: Nat')
    w('  for +hk: {Nat.is_lt(k, 64n) == True{} : Bool}')
    w('  {D.bytes(D.zconst(k)) == M.zero_subtree(k) : List<&2, U32>}')
    w('def zconst_spec(k, hk):')
    w('  match k:')
    w('    case 0n: {==}')
    w('    case 1n+ +p:')
    w('      %zconst_spec(p, F.nat__lt_trans(p, 63n, 64n, hk, {==})) :')
    w('        {D.bytes(D.zconst(1n+p)) == VF.sha256_bytes(List.append(&2, U32, _, _)) : List<&2, U32>}')
    w('      zconst_step(p, hk)')
    return '\n'.join(L) + '\n'


def main():
    text = emit()
    ztext = emit_zero()
    ftext = emit_fast()
    if '--check' in sys.argv:
        for path, t in ((OUT, text), (ZOUT, ztext), (FOUT, ftext)):
            if not path.exists():
                sys.exit('stale generated SHA laws: ' + str(path.relative_to(ROOT)))
            if path.read_text() != t:
                sys.exit('stale generated SHA laws: ' + str(path.relative_to(ROOT)))
        print('generated SHA laws are current')
        return
    OUT.write_text(text)
    ZOUT.write_text(ztext)
    FOUT.write_text(ftext)
    print(OUT.relative_to(ROOT), ZOUT.relative_to(ROOT), FOUT.relative_to(ROOT))


if __name__ == '__main__':
    main()
