#!/usr/bin/env python3
"""Emit proofs/obj/sha_node.bend: one Merkle node of the runtime hashes the
same 64-byte message as the independent specification.

    python3 codegen/sha_laws.py [--check]

Runtime (src/digest.bend): `hash_pair(l, r) = of_result(PKG.sha256(pair_words(l, r), 64n))`
with the pinned BendHub package. Specification (spec/merkle.bend): the
vendored FIPS 180-4 `sha256_bytes` of the 64 bytes `bytes(l) ++ bytes(r)`.

The checker normalizes eagerly and without sharing, so a type that contains
the 48-round message schedule of a concretely shaped block, or 16 unfolded
rounds from a concrete state, does not check in practice (measured, see
WORK_LOG.md). Nothing here normalizes SHA-256. Instead:

* `node_blocks` states the two compressions of a 64-byte message for an
  ARBITRARY round count `extra` and start state `s0`. With both variable the
  schedule extension and every round stay stuck, so the proof may case on the
  sixteen message words: both sides become the same two `compress` calls over
  the same words (`dec_be` identifies the specification's big-endian words
  with the runtime's words).
* The package law `sha256_array_correct` and the laws below are instantiated
  with `extra = 48` and the initial state only where the message array is
  still stuck on the variable digests, so the instances check without
  unfolding anything.
* `sha_bridge.bend` identifies the package's and the vendored copy of FIPS
  function by function.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'proofs/obj/sha_node.bend'
ZOUT = ROOT / 'proofs/obj/zero_roots.bend'


def word(bits):
    s = 'WNil{}'
    for b in reversed(bits):
        s = f'WCon{{{b}, {s}}}'
    return f'U32{{{s}}}'


def be_bytes_of(x):
    return [f'(U32.shrn({x}, 24n) .&. 255 : U32)', f'(U32.shrn({x}, 16n) .&. 255 : U32)',
            f'(U32.shrn({x}, 8n) .&. 255 : U32)', f'({x} .&. 255 : U32)']


def dec_of(x):
    return f'VF.decode({", ".join(be_bytes_of(x))})'


# The residual of bit i of VF.decode(big-endian bytes of x) after casing x on
# its bits (read off the checker's normal form): byte k of the word carries
# k `or(_, and(and(a, False), False))` layers around `and(and(a, True), True)`.
def residual(i, a):
    e = f'Bool.and(Bool.and({a}, True{{}}), True{{}})'
    for _ in range(i // 8):
        e = f'Bool.or({e}, Bool.and(Bool.and({a}, False{{}}), False{{}}))'
    return e


def emit():
    L = []
    w = L.append
    w('import Base')
    w('import ../../src/digest.bend as D')
    w('import ../../vendor/bend_sha256/fips.bend as VF')
    w('import ../../vendor/bend_sha256/state.bend as VS')
    w('import 0xda83506fb9f059ead7afcfa2f498df5f/fips.bend as PF')
    w('import 0xda83506fb9f059ead7afcfa2f498df5f/state.bend as PS')
    w('import 0xda83506fb9f059ead7afcfa2f498df5f/packed_spec.bend as PSP')
    w('import ../../proofs/compact/bits.bend as BT')
    w('import ./sha_bridge.bend as SB')
    w('import 0xda83506fb9f059ead7afcfa2f498df5f/buffer.bend as Buf')
    w('import 0xda83506fb9f059ead7afcfa2f498df5f/sha256.bend as PKG')
    w('import 0xda83506fb9f059ead7afcfa2f498df5f/LAWS.bend as PL')
    w('import 0xda83506fb9f059ead7afcfa2f498df5f/CORRECTNESS.bend as PC')
    w('import ../../spec/merkle.bend as M')
    w('import ../../spec/primitives.bend as P')
    w('')
    w('# GENERATED by codegen/sha_laws.py. Do not edit.')
    w('')
    # ---- dec_be ------------------------------------------------------------
    a = [f'a{i}' for i in range(32)]
    for k in range(4):
        e = residual(8 * k, 'x')
        w(f'def fixb{k}(+x: Bool) -> {{{e} == x : Bool}}:')
        w('  match x:')
        w('    case True{}: {==}')
        w('    case False{}: {==}')
    w('')
    w('# The specification reads a word back from its four big-endian bytes.')
    w('law dec_be:')
    w('  for +x: U32')
    w(f'  {{{dec_of("x")} == x : U32}}')
    w('def dec_be(x):')
    w('  match x:')
    w(f'    case {word(a)}:')
    res = [residual(i, a[i]) for i in range(32)]
    w(f'      BT.word32_eq({", ".join(res)}, {", ".join(a)}, ' +
      ', '.join(f'fixb{i // 8}({a[i]})' for i in range(32)) + ')')
    w('')
    # ---- node_blocks ---------------------------------------------------------
    la = [f'a{i}' for i in range(8)]
    lb = [f'b{i}' for i in range(8)]
    W1 = la + lb
    W1l = '[' + ', '.join(W1) + ']'
    W1s = '[' + ', '.join(dec_of(x) for x in W1) + ']'
    W2l = '[2147483648, ' + ', '.join(['0'] * 14) + ', 512]'
    K = 'PF.constants()'
    S1 = f'PF.compress(PF.schedule(extra, {W1l}), {K}, s0)'
    w('# The two compressions of a 64-byte message, for any round count and any')
    w('# start state: the packed reference over the runtime\'s message array, and')
    w('# the vendored FIPS over the 64 bytes of the same two chunks.')
    w('law node_blocks:')
    w('  for +extra: Nat')
    w('  for +s0: PS.State')
    w('  for +l: D.Digest')
    w('  for +r: D.Digest')
    w('  {SB.conv(PSP.take_state(PSP.blocks(extra, 1n, 0, 0n, 64n, (D.pair_words(l, r), s0))))')
    w('    == VF.blocks(VF.prepare(List.append(&2, U32, D.bytes(l), D.bytes(r)), extra), VF.constants())(SB.conv(s0)) : VS.State}')
    w('def node_blocks(extra, s0, l, r):')
    w('  match l:')
    w(f'    case D.D{{{", ".join("+" + x for x in la)}}}:')
    w('      match r:')
    w(f'        case D.D{{{", ".join("+" + x for x in lb)}}}:')
    I = '          '
    RHS = f'VF.compress(VF.schedule(extra, {W2l}), VF.constants(), VF.compress(VF.schedule(extra, {W1s}), VF.constants(), SB.conv(s0)))'
    # step 1: outer compression PF -> VF
    w(f'{I}%Equal.sym(VS.State, SB.conv(PF.compress(PF.schedule(extra, {W2l}), {K}, {S1})), VF.compress(PF.schedule(extra, {W2l}), {K}, SB.conv({S1})),')
    w(f'{I}    SB.compress_eq(PF.schedule(extra, {W2l}), {K}, {S1})) :')
    w(f'{I}  {{_ == {RHS} : VS.State}}')
    # step 2: inner compression
    w(f'{I}%Equal.sym(VS.State, SB.conv({S1}), VF.compress(PF.schedule(extra, {W1l}), {K}, SB.conv(s0)),')
    w(f'{I}    SB.compress_eq(PF.schedule(extra, {W1l}), {K}, s0)) :')
    w(f'{I}  {{VF.compress(PF.schedule(extra, {W2l}), {K}, _) == {RHS} : VS.State}}')
    # step 3/4: schedules
    w(f'{I}%Equal.sym(List<&2, U32>, PF.schedule(extra, {W2l}), VF.schedule(extra, {W2l}), SB.schedule_eq(extra, {W2l})) :')
    w(f'{I}  {{VF.compress(_, {K}, VF.compress(PF.schedule(extra, {W1l}), {K}, SB.conv(s0))) == {RHS} : VS.State}}')
    w(f'{I}%Equal.sym(List<&2, U32>, PF.schedule(extra, {W1l}), VF.schedule(extra, {W1l}), SB.schedule_eq(extra, {W1l})) :')
    w(f'{I}  {{VF.compress(VF.schedule(extra, {W2l}), {K}, VF.compress(_, {K}, SB.conv(s0))) == {RHS} : VS.State}}')
    # step 5: the words of the first block
    for i, x in enumerate(W1):
        pre = [dec_of(y) for y in W1[:i]]
        post = W1[i + 1:]
        hole = '[' + ', '.join(pre + ['_'] + post) + ']'
        w(f'{I}%dec_be({x}) :')
        w(f'{I}  {{VF.compress(VF.schedule(extra, {W2l}), {K}, VF.compress(VF.schedule(extra, {hole}), {K}, SB.conv(s0))) == {RHS} : VS.State}}')
    w(f'{I}{{==}}')
    w('')
    emit_node(w)
    return '\n'.join(L) + '\n'


def emit_node(w):
    la = [f'a{i}' for i in range(8)]
    lb = [f'b{i}' for i in range(8)]
    PW = 'D.pair_words(l, r)'
    w('# The message array of a node holds sixteen words.')
    w('law pair_size:')
    w('  for +l: D.Digest')
    w('  for +r: D.Digest')
    w(f'  {{Array.size(U32, {PW}) == ({PW}, 16) : Array<U32> & U32}}')
    w('def pair_size(l, r):')
    w('  match l:')
    w(f'    case D.D{{{", ".join("+" + x for x in la)}}}:')
    w('      match r:')
    w(f'        case D.D{{{", ".join("+" + x for x in lb)}}}: {{==}}')
    w('')
    w('# The runtime node is the package\'s packed specification of its message')
    w('# (package law `sha256_array_correct`, instantiated at the stuck message).')
    w('law hash_pair_packed:')
    w('  for +l: D.Digest')
    w('  for +r: D.Digest')
    w(f'  {{D.hash_pair(l, r) == D.of_result(Buf.result(PSP.hash({PW}, 64n))) : D.Digest}}')
    w('def hash_pair_packed(l, r):')
    w(f'  Equal.cong(Maybe<&1, Array<U32>>, D.Digest, x => D.of_result(x), PKG.sha256({PW}, 64n),')
    w(f'    Buf.result(PSP.hash({PW}, 64n)), PL.sha256_array_correct({PW}, 64n))')
    w('')
    st = [f's{i}' for i in range(8)]
    w('# The bytes of the eight result words are the FIPS digest octets.')
    w('law digest_bytes:')
    w('  for +s: PS.State')
    w('  {D.bytes(D.of_array(Buf.digest(s))) == VF.digest_octets(VF.digest(SB.conv(s))) : List<&2, U32>}')
    w('def digest_bytes(s):')
    w('  match s:')
    w(f'    case PS.H{{{", ".join("+" + x for x in st)}}}: {{==}}')
    w('')
    ST = f'PSP.take_state(PSP.blocks(48n, 1n, 0, 0n, 64n, ({PW}, PF.initial())))'
    MSG = 'List.append(&2, U32, D.bytes(l), D.bytes(r))'
    w('# ONE MERKLE NODE: the runtime node hashes exactly the specification\'s')
    w('# 64-byte message, through the pinned package, with no SHA normalization.')
    w('law node:')
    w('  for +l: D.Digest')
    w('  for +r: D.Digest')
    w(f'  {{D.bytes(D.hash_pair(l, r)) == VF.sha256_bytes({MSG}) : List<&2, U32>}}')
    w('def node(l, r):')
    w(f'  %Equal.sym(D.Digest, D.hash_pair(l, r), D.of_result(Buf.result(PSP.hash({PW}, 64n))), hash_pair_packed(l, r)) :')
    w(f'    {{D.bytes(_) == VF.sha256_bytes({MSG}) : List<&2, U32>}}')
    w(f'  %Equal.sym(Array<U32> & U32, Array.size(U32, {PW}), ({PW}, 16), pair_size(l, r)) :')
    w(f'    {{D.bytes(D.of_result(Buf.result(PSP.sized(64n, _)))) == VF.sha256_bytes({MSG}) : List<&2, U32>}}')
    w(f'  %Equal.sym(List<&2, U32>, D.bytes(D.of_array(Buf.digest({ST}))), VF.digest_octets(VF.digest(SB.conv({ST}))), digest_bytes({ST})) :')
    w(f'    {{_ == VF.sha256_bytes({MSG}) : List<&2, U32>}}')
    w(f'  %Equal.sym(VS.State, SB.conv({ST}), VF.blocks(VF.prepare({MSG}, 48n), VF.constants())(SB.conv(PF.initial())), node_blocks(48n, PF.initial(), l, r)) :')
    w(f'    {{VF.digest_octets(VF.digest(_)) == VF.sha256_bytes({MSG}) : List<&2, U32>}}')
    w('  {==}')
    w('')
    w('# The node at a message length known only through an equation: the root')
    w('# laws hold `hl` abstract (so nodes over constructor digests stay stuck) and')
    w('# carry `hl == 64n`; this is the only place that equation is used.')
    w('law node_at:')
    w('  for +hl: Nat')
    w('  for +ehl: {hl == 64n : Nat}')
    w('  for +l: D.Digest')
    w('  for +r: D.Digest')
    w(f'  {{D.bytes(D.node(hl, l, r)) == VF.sha256_bytes({MSG}) : List<&2, U32>}}')
    w('def node_at(hl, ehl, l, r):')
    w(f'  %Equal.sym(Nat, hl, 64n, ehl) : {{D.bytes(D.node(_, l, r)) == VF.sha256_bytes({MSG}) : List<&2, U32>}}')
    w('  node(l, r)')
    w('')
    # ---- the specification's node over digest bytes ------------------------
    a = [f'a{i}' for i in range(32)]
    lo = [f'Bool.and({a[i]}, True{{}})' for i in range(8)]
    hi = [f'Bool.and({a[i]}, False{{}})' for i in range(8, 32)]
    w('# A masked byte is below 256.')
    w('law lt_byte:')
    w('  for +y: U32')
    w('  {U32.is_lt((y .&. 255 : U32), 256) == True{} : Bool}')
    w('def lt_byte(y):')
    w('  match y:')
    w(f'    case {word(a)}:')
    for i in range(8, 32):
        bits = lo + ['False{}'] * (i - 8) + ['_'] + hi[i - 7:]
        w(f'      %Equal.sym(Bool, Bool.and({a[i]}, False{{}}), False{{}}, BT.and_false({a[i]})) :')
        w(f'        {{U32.is_lt({word(bits)}, 256) == True{{}} : Bool}}')
    w('      {==}')
    w('')
    ds = [f'd{i}' for i in range(8)]
    w('# The bytes of a digest are 32 bytes.')
    w('law digest_scope:')
    w('  for +d: D.Digest')
    w('  {P.byte_scope(32n, D.bytes(d)) == True{} : Bool}')
    w('def digest_scope(d):')
    w('  match d:')
    w(f'    case D.D{{{", ".join("+" + x for x in ds)}}}:')
    terms = []
    for x in ds:
        terms += [f'U32.shrn({x}, 24n)', f'U32.shrn({x}, 16n)', f'U32.shrn({x}, 8n)', x]
    lts = [f'U32.is_lt(({t} .&. 255 : U32), 256)' for t in terms]
    for i, t in enumerate(terms):
        parts = ['True{}'] * i + ['_'] + lts[i + 1:]
        e = 'True{}'
        for p in reversed(parts):
            e = f'Bool.and({p}, {e})'
        w(f'      %Equal.sym(Bool, {lts[i]}, True{{}}, lt_byte({t})) :')
        w(f'        {{{e} == True{{}} : Bool}}')
    w('      {==}')
    w('')
    w('# The specification\'s node over the bytes of two digests is the runtime')
    w('# node\'s bytes.')
    w('law spec_node:')
    w('  for +l: D.Digest')
    w('  for +r: D.Digest')
    w('  {M.hash_pair(D.bytes(l), D.bytes(r)) == Some{D.bytes(D.hash_pair(l, r))} : Maybe<&2, List<&2, U32>>}')
    w('def spec_node(l, r):')
    w('  %Equal.sym(Bool, P.byte_scope(32n, D.bytes(l)), True{}, digest_scope(l)) :')
    w('    {M.pair_checked(Bool.and(_, P.byte_scope(32n, D.bytes(r))), D.bytes(l), D.bytes(r)) == Some{D.bytes(D.hash_pair(l, r))} : Maybe<&2, List<&2, U32>>}')
    w('  %Equal.sym(Bool, P.byte_scope(32n, D.bytes(r)), True{}, digest_scope(r)) :')
    w('    {M.pair_checked(Bool.and(True{}, _), D.bytes(l), D.bytes(r)) == Some{D.bytes(D.hash_pair(l, r))} : Maybe<&2, List<&2, U32>>}')
    w(f'  %Equal.sym(List<&2, U32>, D.bytes(D.hash_pair(l, r)), VF.sha256_bytes({MSG}), node(l, r)) :')
    w(f'    {{Some{{VF.sha256_bytes({MSG})}} == Some{{_}} : Maybe<&2, List<&2, U32>>}}')
    w('  {==}')
    w('')


def emit_zero():
    """proofs/obj/zero_roots.bend: the constants D.zconst(k) are the
    specification's zero subtrees, for every k < 64."""
    L = []
    w = L.append
    w('import Base')
    w('import ../../src/digest.bend as D')
    w('import ../../spec/merkle.bend as M')
    w('import ../../vendor/bend_sha256/fips.bend as VF')
    w('import ../compact/found.bend as F')
    w('')
    w('# GENERATED by codegen/sha_laws.py. Do not edit.')
    w('# The zero-subtree constants of src/digest.bend against spec/merkle.bend:')
    w('# `zconst_step` evaluates one concrete FIPS 180-4 hash per level (63 cases),')
    w('# `zconst_spec` then follows zero_subtree\'s own recursion.')
    w('')
    w('def disc(b: Bool) -> Type:')
    w('  match b:')
    w('    case True{}: Unit')
    w('    case False{}: Empty')
    w('')
    w('def false_true(e: {False{} == True{} : Bool}) -> Empty:')
    w('  %Equal.sym(Bool, False{}, True{}, e) : disc(_)')
    w('  Unit{}')
    w('')
    Z = lambda k: f'D.zconst({k})'
    w('law zconst_step:')
    w('  for +k: Nat')
    w('  for +hk: {Nat.is_lt(k, 63n) == True{} : Bool}')
    w(f'  {{D.bytes(D.zconst(1n+k)) == VF.sha256_bytes(List.append(&2, U32, D.bytes(D.zconst(k)), D.bytes(D.zconst(k)))) : List<&2, U32>}}')
    w('def zconst_step(k, hk):')
    cur = 'k'
    for i in range(63):
        pad = '  ' * (i + 1)
        w(f'{pad}match {cur}:')
        w(f'{pad}  case 0n: {{==}}')
        nxt = f'k{i + 1}'
        if i < 62:
            w(f'{pad}  case 1n+ +{nxt}:')
        else:
            kk = f'{i + 1}n+{nxt}'
            w(f'{pad}  case 1n+ +{nxt}:')
            w(f'{pad}    Empty.absurd({{D.bytes(D.zconst(1n+{kk})) == VF.sha256_bytes(List.append(&2, U32, D.bytes(D.zconst({kk})), D.bytes(D.zconst({kk})))) : List<&2, U32>}}, false_true(Equal.trans(Bool, False{{}}, Nat.is_lt({nxt}, 0n), True{{}}, Equal.sym(Bool, Nat.is_lt({nxt}, 0n), False{{}}, F.nat__not_lt_zero({nxt})), hk)))')
        cur = nxt
    w('')
    w('law zconst_spec:')
    w('  for +k: Nat')
    w('  for +hk: {Nat.is_lt(k, 64n) == True{} : Bool}')
    w('  {D.bytes(D.zconst(k)) == M.zero_subtree(k) : List<&2, U32>}')
    w('def zconst_spec(k, hk):')
    w('  match k:')
    w('    case 0n: {==}')
    w('    case 1n+ +p:')
    w('      %zconst_spec(p, F.nat__lt_trans(p, 63n, 64n, hk, {==})) :')
    w('        {D.bytes(D.zconst(1n+p)) == VF.sha256_bytes(List.append(&2, U32, _, _)) : List<&2, U32>}')
    w('      zconst_step(p, hk)')
    return '\n'.join(L) + '\n'


def main():
    text = emit()
    ztext = emit_zero()
    if '--check' in sys.argv:
        for path, t in ((OUT, text), (ZOUT, ztext)):
            if path.read_text() != t:
                sys.exit('stale generated SHA laws: ' + str(path.relative_to(ROOT)))
        print('generated SHA laws are current')
        return
    OUT.write_text(text)
    ZOUT.write_text(ztext)
    print(OUT.relative_to(ROOT), ZOUT.relative_to(ROOT))


if __name__ == '__main__':
    main()
