#!/usr/bin/env python3
"""The encoder of the list of transactions (List[ByteList[2^30], 2^20]) at any byte
position of an output tree: codegen/var_vlist.py's list, writer side.

    python3 codegen/var_vlist_enc.py [--check] [--no-big]

proofs/obj/big_encx_l1048576_bl1073741824.bend (BIG: the 2^30 element limit is compared
as the window modules do). The list object is Seq{am(t), N} for a Data mirror tree t of
its boxed elements (the mirrors of proofs/obj/root_types.bend, copied here by name from
that generated file so this module does not import it: WMr, MB, th/fz, am, amswap,
amset, amswap_back, xat); every element i < N is MSome{WMr{T_i, N_i}} with T_i a perfect
tree of depth < 28 holding its N_i bytes and zero past them (EOK). The runtime's validity
loop va is evaluated by induction on its counter (va_go).
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'proofs/obj/big_encx_l1048576_bl1073741824.bend'
RT = ROOT / 'proofs/obj/root_types.bend'
P = 'l1048576_bl1073741824'
E = 'bl1073741824'
LIM = '1073741824'
LIML = '1048576'

COPY = ['WMr', 'th_w', 'fz_w', 'fzth_w', 'MB', f'th_{E}_bx', f'fz_{E}_bx', f'fzth_{E}_bx', f'am_{P}', f'amsize_{P}',
        f'amswap_go_{P}', f'amswap_{P}', f'amset_{P}', f'amswap_back_{P}', f'xat_{P}', f'nth_{P}']


def blocks(text):
    """{name: text} of the top-level def / law / type blocks."""
    out, cur, name = {}, [], None
    for l in text.split('\n'):
        m = re.match(r'(?:def|law|type) (\w+)', l)
        if m or (l and not l[0].isspace() and not l.startswith('#')):
            if name:
                out.setdefault(name, []).extend(cur)
            name, cur = (m.group(1) if m else None), [l]
        else:
            cur.append(l)
    if name:
        out.setdefault(name, []).extend(cur)
    return {k: '\n'.join(v).rstrip('\n') for k, v in out.items()}


HEAD = ['import Base', 'import ../compact/found.bend as F', 'import ../../src/buffer.bend as B', 'import ../../src/obj.bend as O',
        'import ../../types/fulu_obj.bend as T', 'import ../../types/schema.bend as S', 'import ../compact/arith.bend as A',
        'import ../compact/reads.bend as RD', 'import ../../proofs/nat_order.bend as Order', 'import ./amap.bend as AM',
        'import ./mtree_defs.bend as MD', 'import ./vspec.bend as VS', 'import ./vbuf.bend as VB', 'import ./vu32.bend as VU',
        'import ./vcopy.bend as VC', 'import ./vdepth.bend as VD', 'import ./vbytes.bend as VY', 'import ./vlist.bend as VL',
        'import ./venc.bend as VE', 'import ./vbenc.bend as VBE', 'import ./spec_fixed.bend as FX',
        'import ./vbrt.bend as VBR', 'import ./vua.bend as UA', 'import ./vuw.bend as UW',
        'import ./vvle.bend as VE2', 'import ./vvl.bend as VVL', 'import ./vrej.bend as VR', 'import ../../src/primitives.bend as I', 'import ./vdig.bend as VG',
        'import ./dk.bend as DK', 'import ./vfix.bend as VF', 'import ./big_vvlu.bend as VVU', 'import ./vbspec.bend as VZ', 'import ../../spec/nat_bytes.bend as N', 'import ./vuwd.bend as WD', 'import ./vbsize.bend as VBZ', 'import ../../spec/codec.bend as Codec',
        'import ../../spec/layout.bend as Layout', 'import ../../spec/fulu_schemas.bend as Spec', 'import ../../spec/primitives.bend as SP', 'import ../../proofs/nat_bytes.bend as Digits']

TEMPLATE = ROOT / 'codegen/vvle_list.bend.in'


def main():
    nb = '--no-big' in sys.argv
    out = {}
    if not nb:
        bl = blocks(RT.read_text())
        missing = [c for c in COPY if c not in bl]
        assert not missing, missing
        L = HEAD + ['', '# GENERATED by codegen/var_vlist_enc.py. Do not edit.',
                    '# The list of transactions, writer side (see the generator\'s docstring).', '',
                    '# ---- mirrors of the boxed elements (copied from proofs/obj/root_types.bend) ----']
        L += [bl[c] for c in COPY]
        txt = '\n'.join(L) + '\n' + TEMPLATE.read_text().replace('@P', P).replace('@E', E).replace('@LIML', LIML).replace('@LIM', LIM)
        out[OUT] = txt
    if '--check' in sys.argv:
        stale = [str(p.relative_to(ROOT)) for p, t in out.items() if not p.exists() or p.read_text() != t]
        if stale:
            print('stale generated list encoder modules: ' + ', '.join(stale))
            sys.exit(1)
        print('generated list encoder modules are current')
        return
    for p, t in out.items():
        p.write_text(t)
    print(', '.join(str(p.relative_to(ROOT)) for p in out) or 'nothing (--no-big)')


if __name__ == '__main__':
    main()
