#!/usr/bin/env python3
"""Byte-offset window modules (the interface of proofs/obj/vua_win.bend) of LISTS OF
RECORDS WITH SUB-WORD FIELDS: codegen/var_rlist.py's lists of fixed-size records, for
records whose fields are read by the byte-position modules vfx_u8 / vfx_u16 (the generic
GpF350A3C486 = ProgressiveContainer{uint8} and Gc4ED9619F50 = Container{uint16, uint16}),
bounded (List[R, N]) or progressive (ProgressiveList[R]).

    python3 codegen/var_rlist_sub.py [--check]

Record j of the window starts at byte y = x + RS j; its fields are read there by their
vfx module's rdx (rdb), the object's record array is the tree RT of those records; the
value's items are the records' values, whose parts are the window's RS bytes at y (RPRF:
the fields' fixed parts, joined by vua_win.splitWX), so the parts of the list's items are
the fixed parts BP of consecutive RS-byte windows, whose encoding is the window's bytes.
The storage depth is bounded from the window (var_rlist.sym_depth). The inversion is
var_rlist's inv_text for a bounded list, and its unbounded variant (PINV) otherwise.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'codegen'))
import var_rlist as RL  # noqa: E402

HDR = '# GENERATED by codegen/var_rlist_sub.py. Do not edit.'
U8S, U16S = 'S.Unsigned{P.U8{}}', 'S.Unsigned{P.U16{}}'
# record type -> (size RS, schema, fields [(byte position c, field size, vfx module alias, the field's object at byte y, field schema)])
RECS = {
    'GpF350A3C486': (1, 'S.ProgressiveContainer{["f_A"], S.Chain{S.Unsigned{P.U8{}}, S.End{}}, [True{}]}',
                     [(0, 1, 'FXA', lambda y: f'VRB.BX(t, {y})', U8S)]),
    'Gc4ED9619F50': (4, 'S.Container{["f_A", "f_B"], S.Chain{S.Unsigned{P.U16{}}, S.Chain{S.Unsigned{P.U16{}}, S.End{}}}}',
                     [(0, 2, 'FXB', lambda y: f'O.keep(2, UR.RWN(t, {y}))', U16S), (2, 2, 'FXB', lambda y: f'O.keep(2, UR.RWN(t, {y}))', U16S)]),
}
FXMOD = {'FXA': 'vfx_u8.bend', 'FXB': 'vfx_u16.bend'}
# (runtime list prefix, record type, limit (None: a progressive list))
LISTS = [('l10_GpF350A3C486', 'GpF350A3C486', 10), ('pl_Gc4ED9619F50', 'Gc4ED9619F50', None)]

HEAD = [x.replace('../../types/fulu_obj.bend as T', '../../types/generic_obj.bend as T').replace('../../spec/fulu_schemas.bend as Spec', './generic_specs.bend as Spec')
        for x in RL.HEAD] + ['import ./vlist.bend as VLS', 'import ./vbrt.bend as VR', 'import ./vbitl.bend as VBL', 'import ./vrejb.bend as VRB',
                             'import ./vmv.bend as VMV', 'import ./sub_pack.bend as SP2', 'import ./dk.bend as DK'] + [f'import ./{m} as {a}' for a, m in FXMOD.items()]


def fname(p, LIM):
    return ROOT / f'proofs/obj/{"" if LIM else "big_"}var_winx_{p}.bend'


def pos(c, y):
    return y if c == 0 else f'{c}n+{y}'


READER = r"""# ---- the reader ---------------------------------------------------------------------------------

def LOBJ(e: Bool, +t: @TR, +x: Nat, +len: U32) -> T.@p_Seq:
  match e:
    case True{}: T.@p_Seq{T.@p_fill(0n), 0}
    case False{}: T.@p_Seq{FD.array__thaw(T.@R, RT(U32.to_nat(U32.sub(NN(len), 1)), 0n, B.words_depth(NN(len)), FD.array__trep(T.@R, B.words_depth(NN(len)), T.@R_default()), t, x)), NN(len)}
def OBJw(+d: Nat, +t: @TR, +x: Nat, +off: U32, +len: U32) -> T.@p_Seq: LOBJ(U32.is_eq(len, 0), t, x, len)

# The read loop from record j (index i) on.
def lp(k: Nat, +d: Nat, +t: @TR, +n: U32, +x: Nat, +off: U32, +i: U32, +j: Nat, +dd: Nat, +D: @TRR,
    +eo: {U32.to_nat(off) == x : Nat}, +ej: {U32.to_nat(i) == j : Nat}, +hd: {Nat.is_lt(d, 28n) == @TRUE},
    +pf: {FD.array__perfect(U32, d, t) == @TRUE}, +hb: {Nat.is_le(VRL.pos(Nat.add(1n+k, j), @RSn, x), @Q) == @TRUE},
    +hdd: {Nat.is_lt(dd, 32n) == @TRUE}, +hk: {Nat.is_lt(Nat.add(k, j), VB.pw(dd)) == @TRUE},
    +pfD: {FD.array__perfect(T.@R, dd, D) == @TRUE})
    -> {T.@p_rd(k, i, off, FD.array__thaw(T.@R, D), (BF(t, n), RX(t, VRL.pos(j, @RSn, x)))) == (BF(t, n), FD.array__thaw(T.@R, RT(k, j, dd, D, t, x))) : @RD}:
  match k:
    case 0n:
      %Equal.sym(Array<T.@R>, Array.set(T.@R, FD.array__thaw(T.@R, D), i, RX(t, VRL.pos(j, @RSn, x))), FD.array__thaw(T.@R, FD.array__upd(T.@R, dd, D, j, RX(t, VRL.pos(j, @RSn, x)))),
          VRL.set_g(T.@R, dd, D, i, j, RX(t, VRL.pos(j, @RSn, x)), T.@R_default(), ej, hdd, hk, pfD)) :
        {(BF(t, n), _) == (BF(t, n), FD.array__thaw(T.@R, RT(0n, j, dd, D, t, x))) : @RD}
      {==}
    case 1n+ +q:
      +v = RX(t, VRL.pos(j, @RSn, x))
      +D1 = FD.array__upd(T.@R, dd, D, j, v)
      +hkj = FD.nat__le_lt_trans(j, Nat.add(q, j), VB.pw(dd), Order.left_below_sum(q, j), FD.nat__lt_trans(Nat.add(q, j), 1n+Nat.add(q, j), VB.pw(dd), FD.nat__lt_succ(Nat.add(q, j)), hk))
      +hk2 = FD.logic__subst(Nat, z => {Nat.is_lt(z, VB.pw(dd)) == @TRUE}, 1n+Nat.add(q, j), Nat.add(q, 1n+j), Equal.sym(Nat, Nat.add(q, 1n+j), 1n+Nat.add(q, j), FD.nat__add_succ(q, j)), hk)
      +hb2 = FD.logic__subst(Nat, z => {Nat.is_le(VRL.pos(1n+z, @RSn, x), @Q) == @TRUE}, 1n+Nat.add(q, j), Nat.add(q, 1n+j), Equal.sym(Nat, Nat.add(q, 1n+j), 1n+Nat.add(q, j), FD.nat__add_succ(q, j)), hb)
      +hx = VRL.nextfit(j, q, @RSn, x, @Q, hb)
      +ex = VRL.posU(d, off, x, i, j, @RS, @RM1, {==}, eo, ej, hd, hx)
      %Equal.sym(Array<T.@R>, Array.set(T.@R, FD.array__thaw(T.@R, D), i, v), FD.array__thaw(T.@R, D1), VRL.set_g(T.@R, dd, D, i, j, v, T.@R_default(), ej, hdd, hkj, pfD)) :
        {T.@p_rd(q, U32.add(i, 1), off, _, T.@R_read(BF(t, n), U32.add(off, U32.mul(U32.add(i, 1), @RS)), @RS)) == (BF(t, n), FD.array__thaw(T.@R, RT(1n+q, j, dd, D, t, x))) : @RD}
      %Equal.sym(B.Buf & T.@R, T.@R_read(BF(t, n), U32.add(off, U32.mul(U32.add(i, 1), @RS)), @RS), (BF(t, n), RX(t, VRL.pos(1n+j, @RSn, x))),
          rdb(d, t, n, U32.add(off, U32.mul(U32.add(i, 1), @RS)), VRL.pos(1n+j, @RSn, x), ex, hd, pf, hx)) :
        {T.@p_rd(q, U32.add(i, 1), off, FD.array__thaw(T.@R, D1), _) == (BF(t, n), FD.array__thaw(T.@R, RT(1n+q, j, dd, D, t, x))) : @RD}
      lp(q, d, t, n, x, off, U32.add(i, 1), 1n+j, dd, D1, eo, VRL.succU(d, i, j, @RM1, x, ej, hd, hx), hd, pf, hb2, hdd, hk2, FD.array__upd_perfect(T.@R, dd, D, j, v, pfD))

# A non-empty window holds c >= 1 records.
def cpos(+len: U32, +c: Nat, +ec: {U32.to_nat(len) == Nat.mul(c, @RSn) : Nat}, +eb: {U32.is_eq(len, 0) == False{} : Bool})
    -> {Nat.is_le(1n, c) == @TRUE}:
  match c:
    case 0n: Empty.absurd({Nat.is_le(1n, 0n) == @TRUE}, FD.logic__true_false(Equal.trans(Bool, True{}, U32.is_eq(len, 0), False{},
      Equal.sym(Bool, U32.is_eq(len, 0), True{}, FD.u32alg__eq_true(len, 0, FD.u32__injective(len, 0, ec))), eb)))
    case 1n+ +p: FD.nat__zero_le(p)

def rd_go(@CW, @HC, +b: Bool, +eb: {U32.is_eq(len, 0) == b : Bool})
    -> {T.@p_rd_start(b, off, NN(len), BF(t, n)) == (BF(t, n), LOBJ(b, t, x, len)) : B.Buf & T.@p_Seq}:
  match b:
    case True{}: {==}
    case False{}:
      +c = CC(len)
      +ec = ecw(len, hchk)
      +h1 = cpos(len, c, ec, eb)
      +k = U32.to_nat(U32.sub(NN(len), 1))
      +e1 = Equal.trans(Nat, 1n+k, 1n+Nat.sub(c, 1n), c, Equal.cong(Nat, Nat, z => 1n+z, k, Nat.sub(c, 1n), FD.u32__sub_nat(NN(len), 1, h1)), FD.nat__sub_add(c, 1n, h1))
      +P = @Q
      +hL = FD.logic__subst(Nat, z => {Nat.is_le(z, P) == @TRUE}, Nat.add(x, U32.to_nat(len)), Nat.add(U32.to_nat(len), x), FD.nat__add_comm(x, U32.to_nat(len)), hw)
      +hLc = FD.logic__subst(Nat, z => {Nat.is_le(Nat.add(z, x), P) == @TRUE}, U32.to_nat(len), Nat.mul(c, @RSn), ec, hL)
      +hb = FD.logic__subst(Nat, z => {Nat.is_le(VRL.pos(z, @RSn, x), P) == @TRUE}, c, Nat.add(1n+k, 0n),
        Equal.trans(Nat, c, 1n+k, Nat.add(1n+k, 0n), Equal.sym(Nat, 1n+k, c, e1), Equal.sym(Nat, Nat.add(1n+k, 0n), 1n+k, FD.nat__add_zero(1n+k))), hLc)
      +hcp = VD.wd_cover(NN(len), 99n, {==}, FD.nat__le_trans(c, U32.to_nat(0), O.pow2n(99n), hcl, {==}))
      +hcP = FD.logic__subst(Nat, z => {Nat.is_le(c, z) == @TRUE}, O.pow2n(B.words_depth(NN(len))), VB.pw(B.words_depth(NN(len))), Equal.sym(Nat, VB.pw(B.words_depth(NN(len))), O.pow2n(B.words_depth(NN(len))), VD.s_pow2_eq(B.words_depth(NN(len)))), hcp)
      +hk = FD.logic__subst(Nat, z => {Nat.is_lt(z, VB.pw(B.words_depth(NN(len)))) == @TRUE}, k, Nat.add(k, 0n), Equal.sym(Nat, Nat.add(k, 0n), k, FD.nat__add_zero(k)),
        FD.nat__lt_le_trans(k, c, VB.pw(B.words_depth(NN(len))), FD.logic__subst(Nat, z => {Nat.is_lt(k, z) == @TRUE}, 1n+k, c, e1, FD.nat__lt_succ(k)), hcP))
      +hdd = FD.nat__le_lt_trans(B.words_depth(NN(len)), 99n, 32n, VD.wd_min(NN(len), 99n, hcl), {==})
      +hb0 = FD.nat__le_trans(Nat.add(x, @RSn), Nat.add(x, U32.to_nat(len)), P,
        Order.add_left(x, @RSn, U32.to_nat(len), FD.logic__subst(Nat, z => {Nat.is_le(@RSn, z) == @TRUE}, Nat.mul(c, @RSn), U32.to_nat(len), Equal.sym(Nat, U32.to_nat(len), Nat.mul(c, @RSn), ec),
          FD.logic__subst(Nat, z => {Nat.is_le(@RSn, Nat.mul(z, @RSn)) == @TRUE}, 1n+k, c, e1, Order.below_sum(@RSn, Nat.mul(k, @RSn))))), hw)
      +cap = B.words_depth(NN(len))
      %Equal.sym(B.Buf & T.@R, T.@R_read(BF(t, n), off, @RS), (BF(t, n), RX(t, x)), rdb(d, t, n, off, x, eo, hd, pf, hb0)) :
        {T.@p_rd_fin(NN(len), T.@p_rd(k, 0, off, T.@p_fill(T.@p_cap(NN(len))), _)) == (BF(t, n), LOBJ(False{}, t, x, len)) : B.Buf & T.@p_Seq}
      %Equal.sym(Array<T.@R>, Array.new(T.@R, cap, T.@R_default()), FD.array__thaw(T.@R, FD.array__trep(T.@R, cap, T.@R_default())), FD.array__new(T.@R, cap, T.@R_default())) :
        {T.@p_rd_fin(NN(len), T.@p_rd(k, 0, off, _, (BF(t, n), RX(t, x)))) == (BF(t, n), LOBJ(False{}, t, x, len)) : B.Buf & T.@p_Seq}
      %Equal.sym(@RD, T.@p_rd(k, 0, off, FD.array__thaw(T.@R, FD.array__trep(T.@R, cap, T.@R_default())), (BF(t, n), RX(t, x))),
          (BF(t, n), FD.array__thaw(T.@R, RT(k, 0n, cap, FD.array__trep(T.@R, cap, T.@R_default()), t, x))),
          lp(k, d, t, n, x, off, 0, 0n, cap, FD.array__trep(T.@R, cap, T.@R_default()), eo, {==}, hd, pf, hb, hdd, hk, FD.array__trep_perfect(T.@R, cap, T.@R_default()))) :
        {T.@p_rd_fin(NN(len), _) == (BF(t, n), LOBJ(False{}, t, x, len)) : B.Buf & T.@p_Seq}
      {==}

def readw(@CW, @HC)
    -> {T.@p_read(BF(t, n), off, len) == (BF(t, n), OBJw(d, t, x, off, len)) : B.Buf & T.@p_Seq}:
  rd_go(@CA, hchk, U32.is_eq(len, 0), {==})
"""

SPEC = r"""# ---- the spec side ------------------------------------------------------------------------------

def RITEMS(c: Nat, +t: @TR, +y: Nat) -> S.Value:
  match c:
    case 0n: S.EmptyItems{}
    case 1n+q: S.Items{RVAL(t, y), RITEMS(q, t, Nat.add(@RSn, y))}

# the records' parts: a fixed part of each record's bytes
def BP(c: Nat, +t: @TR, +y: Nat) -> +List<S.Part>:
  match c:
    case 0n: []
    case 1n+q: Con{S.Fixed{UW.WX(t, y, @RSn)}, BP(q, t, Nat.add(@RSn, y))}

law cnt_items:
  for +c: Nat
  for +t: @TR
  for +y: Nat
  {Codec.count(RITEMS(c, t, y)) == c : Nat}
def cnt_items(c, t, y):
  match c:
    case 0n: {==}
    case 1n+ +q: FD.nat__succ_cong(Codec.count(RITEMS(q, t, Nat.add(@RSn, y))), q, cnt_items(q, t, Nat.add(@RSn, y)))

law bp_all:
  for +c: Nat
  for +t: @TR
  for +y: Nat
  {SP2.allfx(BP(c, t, y)) == @TRUE}
def bp_all(c, t, y):
  match c:
    case 0n: {==}
    case 1n+ +q: bp_all(q, t, Nat.add(@RSn, y))

law bp_cat:
  for +c: Nat
  for +t: @TR
  for +y: Nat
  {SP2.fcat(BP(c, t, y)) == UW.WX(t, y, Nat.mul(c, @RSn)) : +List<U32>}
def bp_cat(c, t, y):
  match c:
    case 0n: {==}
    case 1n+ +q:
      +M = Nat.mul(q, @RSn)
      %Equal.sym(+List<U32>, SP2.fcat(BP(q, t, Nat.add(@RSn, y))), UW.WX(t, Nat.add(@RSn, y), M), bp_cat(q, t, Nat.add(@RSn, y))) :
        {List.append(&2, U32, UW.WX(t, y, @RSn), _) == UW.WX(t, y, Nat.mul(1n+q, @RSn)) : +List<U32>}
      Equal.sym(+List<U32>, UW.WX(t, y, Nat.add(@RSn, M)), List.append(&2, U32, UW.WX(t, y, @RSn), UW.WX(t, Nat.add(@RSn, y), M)), UW.splitWX(t, y, @RSn, M))

# The records' parts are their bytes.
law prt_items:
  for +c: Nat
  for +d: Nat
  for +t: @TR
  for +y: Nat
  for +pf: {FD.array__perfect(U32, d, t) == @TRUE}
  for +h: {Nat.is_le(Nat.add(y, Nat.mul(c, @RSn)), @Q) == @TRUE}
  {Codec.parts(RITEMS(c, t, y), S.Repeat{@SCH}) == Some{BP(c, t, y)} : @MP}
def prt_items(c, d, t, y, pf, h):
  match c:
    case 0n: {==}
    case 1n+ +q:
      +M = Nat.mul(q, @RSn)
      +e = Equal.trans(Nat, Nat.add(Nat.add(@RSn, y), M), Nat.add(@RSn, Nat.add(y, M)), Nat.add(y, Nat.add(@RSn, M)),
        FD.nat__add_assoc(@RSn, y, M), FD.lru_nat_algebra__add_swap(@RSn, y, M))
      +h2 = FD.logic__subst(Nat, z => {Nat.is_le(z, @Q) == @TRUE}, Nat.add(y, Nat.add(@RSn, M)), Nat.add(Nat.add(@RSn, y), M), Equal.sym(Nat, Nat.add(Nat.add(@RSn, y), M), Nat.add(y, Nat.add(@RSn, M)), e), h)
      +h1 = FD.nat__le_trans(Nat.add(y, @RSn), Nat.add(y, Nat.add(@RSn, M)), @Q, Order.add_left(y, @RSn, Nat.add(@RSn, M), Order.below_sum(@RSn, M)), h)
      F.cat_fixed(Codec.parts(RVAL(t, y), @SCH), UW.WX(t, y, @RSn), Codec.parts(RITEMS(q, t, Nat.add(@RSn, y)), S.Repeat{@SCH}), BP(q, t, Nat.add(@RSn, y)),
        RPRF(d, t, y, pf, h1), prt_items(q, d, t, Nat.add(@RSn, y), pf, h2))

def VALw(+t: @TR, +x: Nat, +len: U32) -> S.Value: S.Sequence{RITEMS(CC(len), t, x)}

def specw(@CW, @HC)
    -> {Codec.parts(VALw(t, x, len), @LSCH) == Some{[S.Variable{UW.WX(t, x, U32.to_nat(len))}]} : @MP}:
  +c = CC(len)
  +ec = ecw(len, hchk)
  +Y = UW.WX(t, x, Nat.mul(c, @RSn))
  +hf = FD.logic__subst(Nat, z => {Nat.is_le(Nat.add(x, z), @Q) == @TRUE}, U32.to_nat(len), Nat.mul(c, @RSn), ec, hw)
  +lY = UW.lenWX(d, t, x, Nat.mul(c, @RSn), pf, hf)
  +fit = FD.logic__subst(Nat, z => {N.fits(4n, z) == @TRUE}, Nat.mul(c, @RSn), Nat.add(Nat.mul(c, @RSn), 0n), Equal.sym(Nat, Nat.add(Nat.mul(c, @RSn), 0n), Nat.mul(c, @RSn), FD.nat__add_zero(Nat.mul(c, @RSn))),
    VFT.fits4(2n+d, Nat.mul(c, @RSn), FD.nat__le_trans(Nat.mul(c, @RSn), Nat.add(x, Nat.mul(c, @RSn)), @Q, Order.left_below_sum(x, Nat.mul(c, @RSn)), hf), FD.nat__lt_trans(d, 28n, 30n, hd, {==})))
  +ha = bp_all(c, t, x)
  +cat = bp_cat(c, t, x)
  +hs = Equal.trans(Nat, Layout.fixed_size(BP(c, t, x)), List.length(&2, U32, SP2.fcat(BP(c, t, x))), Nat.mul(c, @RSn), SP2.fsz(BP(c, t, x), ha),
    Equal.trans(Nat, List.length(&2, U32, SP2.fcat(BP(c, t, x))), List.length(&2, U32, Y), Nat.mul(c, @RSn), Equal.cong(+List<U32>, Nat, z => List.length(&2, U32, z), SP2.fcat(BP(c, t, x)), Y, cat), lY))
  +hfp = Equal.trans(+List<U32>, Layout.fixed_parts(BP(c, t, x), Nat.mul(c, @RSn)), SP2.fcat(BP(c, t, x)), Y, SP2.fxp(BP(c, t, x), Nat.mul(c, @RSn), ha), cat)
  +hv = SP2.bvl(BP(c, t, x), ha, FD.logic__subst(+List<U32>, z => {SP.bytes_domain(z) == @TRUE}, Y, SP2.fcat(BP(c, t, x)), Equal.sym(+List<U32>, SP2.fcat(BP(c, t, x)), Y, cat), UW.domWX(t, x, Nat.mul(c, @RSn))))
  %Equal.sym(Nat, U32.to_nat(len), Nat.mul(c, @RSn), ec) : {Codec.parts(VALw(t, x, len), @LSCH) == Some{[S.Variable{UW.WX(t, x, _)}]} : @MP}
@REQ
  %Equal.sym(Maybe<&2, +List<U32>>, Layout.encoding(BP(c, t, x)), Some{List.append(&2, U32, Y, [])},
      VMV.enc_gen(BP(c, t, x), Nat.mul(c, @RSn), Y, [], hs, hfp, SP2.pay0(BP(c, t, x), ha), hv, fit)) :
    {Codec.one(_, None{}) == Some{[S.Variable{Y}]} : @MP}
  %Equal.sym(+List<U32>, List.append(&2, U32, Y, []), Y, VS.app_nil(Y)) : {Codec.one(Some{_}, None{}) == Some{[S.Variable{Y}]} : @MP}
  {==}
"""

REQ_LIM = r"""  %Equal.sym(Nat, Codec.count(RITEMS(c, t, x)), c, cnt_items(c, t, x)) :
    {Codec.require(Nat.is_le(_, @LIMn), Codec.aggregate(Codec.parts(RITEMS(c, t, x), S.Repeat{@SCH}), None{})) == Some{[S.Variable{Y}]} : @MP}
  %Equal.sym(Bool, Nat.is_le(c, @LIMn), True{}, hcw(len, hchk)) :
    {Codec.require(_, Codec.aggregate(Codec.parts(RITEMS(c, t, x), S.Repeat{@SCH}), None{})) == Some{[S.Variable{Y}]} : @MP}
  %Equal.sym(@MP, Codec.parts(RITEMS(c, t, x), S.Repeat{@SCH}), Some{BP(c, t, x)}, prt_items(c, d, t, x, pf, hf)) :
    {Codec.require(True{}, Codec.aggregate(_, None{})) == Some{[S.Variable{Y}]} : @MP}"""

REQ_PROG = r"""  %Equal.sym(@MP, Codec.parts(RITEMS(c, t, x), S.Repeat{@SCH}), Some{BP(c, t, x)}, prt_items(c, d, t, x, pf, hf)) :
    {Codec.aggregate(_, None{}) == Some{[S.Variable{Y}]} : @MP}"""

PINV = r"""# ---- the inversion ------------------------------------------------------------------------------

def rp_t(+xs: +List<U32>, +el: S.Value, +tl: S.Value, +ps: +List<S.Part>, +mB: Maybe<&2, +List<S.Part>>,
    +eB: {Codec.parts(tl, S.Repeat{@SCH}) == mB : Maybe<&2, +List<S.Part>>},
    +lx: {List.length(&2, U32, xs) == @RSn : Nat},
    +e: {Codec.concatenate(Some{[S.Fixed{xs}]}, mB) == Some{ps} : Maybe<&2, +List<S.Part>>},
    ih: @+pb: +List<S.Part> -> {Codec.parts(tl, S.Repeat{@SCH}) == Some{pb} : Maybe<&2, +List<S.Part>>} -> VMR.REPB(tl, pb, @RSn))
    -> VMR.REPB(S.Items{el, tl}, ps, @RSn):
  match mB:
    case None{}: Empty.absurd(VMR.REPB(S.Items{el, tl}, ps, @RSn), FD.logic__none_some(+List<S.Part>, ps, e))
    case Some{+pb}:
      +eps = FD.logic__some_inj(+List<S.Part>, S.Fixed{xs} <> pb, ps, e)
      %Equal.sym(+List<S.Part>, ps, S.Fixed{xs} <> pb, Equal.sym(+List<S.Part>, S.Fixed{xs} <> pb, ps, eps)) : VMR.REPB(S.Items{el, tl}, _, @RSn)
      VMR.rpb_t2(xs, el, tl, pb, @RSn, lx, ih(pb, eB))

def rp_p(+el: S.Value, +tl: S.Value, +ps: +List<S.Part>, +ph: +List<S.Part>, hf: DF.single(Some{@RSn}, ph),
    +e: {Codec.concatenate(Some{ph}, Codec.parts(tl, S.Repeat{@SCH})) == Some{ps} : Maybe<&2, +List<S.Part>>},
    ih: @+pb: +List<S.Part> -> {Codec.parts(tl, S.Repeat{@SCH}) == Some{pb} : Maybe<&2, +List<S.Part>>} -> VMR.REPB(tl, pb, @RSn))
    -> VMR.REPB(S.Items{el, tl}, ps, @RSn):
  match ph:
    case Nil{}: Empty.absurd(VMR.REPB(S.Items{el, tl}, ps, @RSn), hf)
    case Con{S.Fixed{+xs}, Nil{}}:
      rp_t(xs, el, tl, ps, Codec.parts(tl, S.Repeat{@SCH}), {==}, Equal.sym(Nat, @RSn, List.length(&2, U32, xs), FD.logic__some_inj(Nat, @RSn, List.length(&2, U32, xs), hf)), e, ih)
    case Con{S.Variable{+xs}, Nil{}}: Empty.absurd(VMR.REPB(S.Items{el, tl}, ps, @RSn), FD.logic__none_some(Nat, @RSn, Equal.sym(Maybe<&2, Nat>, Some{@RSn}, None{}, hf)))
    case Con{S.Fixed{+xs}, Con{+a, +b}}: Empty.absurd(VMR.REPB(S.Items{el, tl}, ps, @RSn), hf)
    case Con{S.Variable{+xs}, Con{+a, +b}}: Empty.absurd(VMR.REPB(S.Items{el, tl}, ps, @RSn), hf)

def rp_m(+el: S.Value, +tl: S.Value, +ps: +List<S.Part>, +mh: Maybe<&2, +List<S.Part>>, hf: DF.single_result(Some{@RSn}, mh),
    +e: {Codec.concatenate(mh, Codec.parts(tl, S.Repeat{@SCH})) == Some{ps} : Maybe<&2, +List<S.Part>>},
    ih: @+pb: +List<S.Part> -> {Codec.parts(tl, S.Repeat{@SCH}) == Some{pb} : Maybe<&2, +List<S.Part>>} -> VMR.REPB(tl, pb, @RSn))
    -> VMR.REPB(S.Items{el, tl}, ps, @RSn):
  match mh:
    case None{}: Empty.absurd(VMR.REPB(S.Items{el, tl}, ps, @RSn), FD.logic__none_some(+List<S.Part>, ps, e))
    case Some{+ph}: rp_p(el, tl, ps, ph, hf, e, ih)

# The parts of records are fixed parts of @RS bytes each.
law rep_r:
  for +its: S.Value
  for +ps: +List<S.Part>
  for +e: {Codec.parts(its, S.Repeat{@SCH}) == Some{ps} : Maybe<&2, +List<S.Part>>}
  VMR.REPB(its, ps, @RSn)
def rep_r(its, ps, e):
  match its:
    case S.EmptyItems{}:
      +eps = FD.logic__some_inj(+List<S.Part>, [], ps, e)
      %Equal.sym(+List<S.Part>, ps, [], Equal.sym(+List<S.Part>, [], ps, eps)) : VMR.REPB(S.EmptyItems{}, _, @RSn)
      ({==}, {==})
    case S.Items{+h, +tl}: rp_m(h, tl, ps, Codec.parts(h, @SCH), DS.facts(h, @SCH, {==}), e, pb => eb => rep_r(tl, pb, eb))
    case S.BooleanValue{+b}: Empty.absurd(VMR.REPB(S.BooleanValue{b}, ps, @RSn), FD.logic__none_some(+List<S.Part>, ps, e))
    case S.UnsignedValue{+u}: Empty.absurd(VMR.REPB(S.UnsignedValue{u}, ps, @RSn), FD.logic__none_some(+List<S.Part>, ps, e))
    case S.BytesValue{+xs}: Empty.absurd(VMR.REPB(S.BytesValue{xs}, ps, @RSn), FD.logic__none_some(+List<S.Part>, ps, e))
    case S.BitsValue{+bs}: Empty.absurd(VMR.REPB(S.BitsValue{bs}, ps, @RSn), FD.logic__none_some(+List<S.Part>, ps, e))
    case S.Sequence{+it}: Empty.absurd(VMR.REPB(S.Sequence{it}, ps, @RSn), FD.logic__none_some(+List<S.Part>, ps, e))
    case S.Selected{+sel, +sv}: Empty.absurd(VMR.REPB(S.Selected{sel, sv}, ps, @RSn), FD.logic__none_some(+List<S.Part>, ps, e))
    case S.NullValue{}: Empty.absurd(VMR.REPB(S.NullValue{}, ps, @RSn), FD.logic__none_some(+List<S.Part>, ps, e))

def PF(+ys: +List<U32>) -> Data: DK.Ex(Nat, k => DK.P2({List.length(&2, U32, ys) == Nat.mul(k, @RSn) : Nat}, {k == k : Nat}))

def pm4(+its: S.Value, +ys: +List<U32>, +ps: +List<S.Part>,
    +em3: {Codec.parts(its, S.Repeat{@SCH}) == Some{ps} : Maybe<&2, +List<S.Part>>}, +m4: Maybe<&2, +List<U32>>,
    +em4: {Layout.encoding(ps) == m4 : Maybe<&2, +List<U32>>}, +e: {Codec.bytes(Codec.one(m4, None{})) == Some{ys} : Maybe<&2, +List<U32>>})
    -> PF(ys):
  match m4:
    case None{}: Empty.absurd(PF(ys), FD.logic__none_some(+List<U32>, ys, e))
    case Some{+zs}:
      +ez = FD.logic__some_inj(+List<U32>, zs, ys, e)
      +lz = Equal.trans(Nat, List.length(&2, U32, zs), Layout.fixed_size(ps), Nat.mul(Codec.count(its), @RSn),
        VS.enc_len(ps, zs, Pair.fst({VS.allfix(ps) == @TRUE}, {Layout.fixed_size(ps) == Nat.mul(Codec.count(its), @RSn) : Nat}, rep_r(its, ps, em3)), em4),
        Pair.snd({VS.allfix(ps) == @TRUE}, {Layout.fixed_size(ps) == Nat.mul(Codec.count(its), @RSn) : Nat}, rep_r(its, ps, em3)))
      (Codec.count(its), (FD.logic__subst(+List<U32>, z => {List.length(&2, U32, z) == Nat.mul(Codec.count(its), @RSn) : Nat}, zs, ys, ez, lz), {==}))

def pm3(+its: S.Value, +ys: +List<U32>, +m3: Maybe<&2, +List<S.Part>>,
    +em3: {Codec.parts(its, S.Repeat{@SCH}) == m3 : Maybe<&2, +List<S.Part>>}, +e: {Codec.bytes(Codec.aggregate(m3, None{})) == Some{ys} : Maybe<&2, +List<U32>>})
    -> PF(ys):
  match m3:
    case None{}: Empty.absurd(PF(ys), FD.logic__none_some(+List<U32>, ys, e))
    case Some{+ps}: pm4(its, ys, ps, em3, Layout.encoding(ps), {==}, e)

# The spec bytes ys of any value of the list are whole records.
law linvr:
  for +h: S.Value
  for +ys: +List<U32>
  for +e: {Codec.bytes(Codec.parts(h, @LSCH)) == Some{ys} : Maybe<&2, +List<U32>>}
  PF(ys)
def linvr(h, ys, e):
  match h:
    case S.Sequence{+its}: pm3(its, ys, Codec.parts(its, S.Repeat{@SCH}), {==}, e)
    case S.BooleanValue{+b0}: Empty.absurd(PF(ys), FD.logic__none_some(+List<U32>, ys, e))
    case S.UnsignedValue{+u0}: Empty.absurd(PF(ys), FD.logic__none_some(+List<U32>, ys, e))
    case S.BytesValue{+xs0}: Empty.absurd(PF(ys), FD.logic__none_some(+List<U32>, ys, e))
    case S.BitsValue{+bs0}: Empty.absurd(PF(ys), FD.logic__none_some(+List<U32>, ys, e))
    case S.Items{+hd0, +tl0}: Empty.absurd(PF(ys), FD.logic__none_some(+List<U32>, ys, e))
    case S.EmptyItems{}: Empty.absurd(PF(ys), FD.logic__none_some(+List<U32>, ys, e))
    case S.Selected{+sel0, +sv0}: Empty.absurd(PF(ys), FD.logic__none_some(+List<U32>, ys, e))
    case S.NullValue{}: Empty.absurd(PF(ys), FD.logic__none_some(+List<U32>, ys, e))

def chk_i(@CW, f: PF(UW.WX(t, x, U32.to_nat(len)))) -> {CHKw(t, x, off, len) == @TRUE}:
  (+k, +pr) = f
  (+hl, +kk) = pr
  +ek = Equal.trans(Nat, U32.to_nat(len), List.length(&2, U32, UW.WX(t, x, U32.to_nat(len))), Nat.mul(k, @RSn),
    Equal.sym(Nat, List.length(&2, U32, UW.WX(t, x, U32.to_nat(len))), U32.to_nat(len), UW.lenWX(d, t, x, U32.to_nat(len), pf, hw)), hl)
  +hc = FD.logic__subst(Nat, z => {Nat.is_le(k, z) == @TRUE}, Nat.mul(k, @RSn), U32.to_nat(len), Equal.sym(Nat, U32.to_nat(len), Nat.mul(k, @RSn), ek), VRL.le_mul(k, @RM1))
  +w = VU.whole_i(len, @RS, len, vR(), {==}, {==}, {==}, k, ek, hc)
  FD.logic__and_intro(U32.is_eq(len, (U32.div(len, @RS) * @RS : U32)), True{}, FD.logic__and_left(U32.is_eq(len, (U32.div(len, @RS) * @RS : U32)), U32.is_le(U32.div(len, @RS), len), w), {==})

# Every value whose parts are the window's bytes passes the check.
def invw(@CW, +v: S.Value,
    +e: {Codec.parts(v, @LSCH) == Some{[S.Variable{UW.WX(t, x, U32.to_nat(len))}]} : Maybe<&2, +List<S.Part>>})
    -> {CHKw(t, x, off, len) == @TRUE}:
  chk_i(@CA, linvr(v, UW.WX(t, x, U32.to_nat(len)),
    Equal.cong(Maybe<&2, +List<S.Part>>, Maybe<&2, +List<U32>>, z => Codec.bytes(z), Codec.parts(v, @LSCH), Some{[S.Variable{UW.WX(t, x, U32.to_nat(len))}]}, e)))
"""


def subst(text, mp):
    for k in sorted(mp, key=len, reverse=True):
        text = text.replace(k, mp[k])
    return text


def list_text(p, R, LIM):
    RS, sch, fields = RECS[R]
    TR = 'FD.array__Tree<U32>'
    TRUE = 'True{} : Bool'
    MP = 'Maybe<&2, +List<S.Part>>'
    Q = 'A.quad(VB.pw(d))'
    LSCH = f'S.ListOf{{{sch}, {LIM}n}}' if LIM else f'S.ProgressiveList{{{sch}}}'
    CW = (f'+d: Nat, +t: {TR}, +n: U32, +x: Nat, +off: U32, +len: U32, +eo: {{U32.to_nat(off) == x : Nat}},\n'
          f'    +hd: {{Nat.is_lt(d, 28n) == {TRUE}}}, +hw: {{Nat.is_le(Nat.add(x, U32.to_nat(len)), {Q}) == {TRUE}}},\n'
          f'    +pf: {{FD.array__perfect(U32, d, t) == {TRUE}}}')
    CA = 'd, t, n, x, off, len, eo, hd, hw, pf'
    HC = f'+hchk: {{CHKw(t, x, off, len) == {TRUE}}}'
    CHK = (f'Bool.and(U32.is_eq(len, (U32.div(len, {RS}) * {RS} : U32)), U32.is_le(U32.div(len, {RS}), {LIM}))' if LIM
           else f'Bool.and(U32.is_eq(len, (U32.div(len, {RS}) * {RS} : U32)), True{{}})')
    mp = {'@TRR': f'FD.array__Tree<T.{R}>', '@TRUE': TRUE, '@TR': TR, '@RD': f'B.Buf & Array<T.{R}>', '@RSn': f'{RS}n', '@RS': str(RS),
          '@RM1': f'{RS - 1}n', '@R': R, '@p': p, '@CW': CW, '@CA': CA, '@HC': HC, '@Q': Q, '@LSCH': LSCH, '@SCH': sch, '@MP': MP,
          '@LIMn': f'{LIM}n'}
    desc = f'List[{R}, {LIM}]' if LIM else f'ProgressiveList[{R}]'
    L = list(HEAD) + ['', HDR, f'# The byte-offset window module of {p} ({desc}, records of {RS} byte{"s" if RS > 1 else ""}): see the',
                      '# module docstring of codegen/var_rlist_sub.py and the interface in proofs/obj/vua_win.bend.', '']
    w = L.append

    def its(i):
        t_ = 'S.EmptyItems{}'
        for c, _, a, _, _ in reversed(fields[i:]):
            t_ = f'S.Items{{{a}.VAL(t, {pos(c, "y")}), {t_}}}'
        return t_

    def chs(i):
        t_ = 'S.End{}'
        for _, _, _, _, fs in reversed(fields[i:]):
            t_ = f'S.Chain{{{fs}, {t_}}}'
        return t_

    def pls(i):
        return '[' + ', '.join(f'S.Fixed{{UW.WX(t, {pos(c, "y")}, {sz}n)}}' for c, sz, _, _, _ in fields[i:]) + ']'

    pf_term = '{==}'
    for i in range(len(fields) - 1, -1, -1):
        c, sz, a, _, fs = fields[i]
        room = f'UR.roomf(y, {RS}n, {c}n, {sz}n, {Q}, hb, {{==}})'
        pf_term = (f'F.cat_fixed(Codec.parts({a}.VAL(t, {pos(c, "y")}), {fs}), UW.WX(t, {pos(c, "y")}, {sz}n), Codec.parts({its(i + 1)}, {chs(i + 1)}), {pls(i + 1)},\n'
                   f'        {a}.prt(d, t, {pos(c, "y")}, pf, {room}, {fs}, {{==}}), {pf_term})')
    fc = '[]'
    for c, sz, _, _, _ in reversed(fields):
        fc = f'List.append(&2, U32, UW.WX(t, {pos(c, "y")}, {sz}n), {fc})'
    if len(fields) == 1:
        fcat_eq = f'VS.app_nil(UW.WX(t, y, {RS}n))'
    else:
        (c0, s0, _, _, _), (c1, s1, _, _, _) = fields
        assert len(fields) == 2 and c1 == s0 and s0 + s1 == RS
        fcat_eq = (f'Equal.trans(+List<U32>, {fc}, List.append(&2, U32, UW.WX(t, y, {s0}n), UW.WX(t, {pos(c1, "y")}, {s1}n)), UW.WX(t, y, {RS}n),\n'
                   f'    Equal.cong(+List<U32>, +List<U32>, z => List.append(&2, U32, UW.WX(t, y, {s0}n), z), List.append(&2, U32, UW.WX(t, {pos(c1, "y")}, {s1}n), []), UW.WX(t, {pos(c1, "y")}, {s1}n), VS.app_nil(UW.WX(t, {pos(c1, "y")}, {s1}n))),\n'
                   f'    Equal.sym(+List<U32>, UW.WX(t, y, Nat.add({s0}n, {s1}n)), List.append(&2, U32, UW.WX(t, y, {s0}n), UW.WX(t, Nat.add({s0}n, y), {s1}n)), UW.splitWX(t, y, {s0}n, {s1}n)))')
    RXT = f'T.{R}{{' + ', '.join(f(pos(c, 'y')) for c, _, _, f, _ in fields) + '}'
    w(f'''def BF(t: {TR}, +n: U32) -> B.Buf: UA.BF(t, n)

# ---- the records ---------------------------------------------------------------------------------

# the record whose bytes start at y
def RX(+t: {TR}, +y: Nat) -> T.{R}: {RXT}

# its spec value, and that value's parts: the window's {RS} byte{"s" if RS > 1 else ""} at y
def RVAL(+t: {TR}, +y: Nat) -> S.Value: S.Sequence{{{its(0)}}}
def RPRF(+d: Nat, +t: {TR}, +y: Nat, +pf: {{FD.array__perfect(U32, d, t) == {TRUE}}}, +hb: {{Nat.is_le(Nat.add(y, {RS}n), {Q}) == {TRUE}}})
    -> {{Codec.parts(RVAL(t, y), {sch}) == Some{{[S.Fixed{{UW.WX(t, y, {RS}n)}}]}} : {MP}}}:
  +ec = {fcat_eq}
  +dm = FD.logic__subst(+List<U32>, z => {{SP.bytes_domain(z) == {TRUE}}}, UW.WX(t, y, {RS}n), {fc}, Equal.sym(+List<U32>, {fc}, UW.WX(t, y, {RS}n), ec), UW.domWX(t, y, {RS}n))
  +ln = FD.logic__subst(+List<U32>, z => {{List.length(&2, U32, z) == {RS}n : Nat}}, UW.WX(t, y, {RS}n), {fc}, Equal.sym(+List<U32>, {fc}, UW.WX(t, y, {RS}n), ec), UW.lenWX(d, t, y, {RS}n, pf, hb))
  %Equal.sym({MP}, Codec.parts({its(0)}, {chs(0)}), Some{{{pls(0)}}},
      {pf_term}) :
    {{Codec.aggregate(_, Some{{{RS}n}}) == Some{{[S.Fixed{{UW.WX(t, y, {RS}n)}}]}} : {MP}}}
  %ec : {{Codec.aggregate(Some{{{pls(0)}}}, Some{{{RS}n}}) == Some{{[S.Fixed{{_}}]}} : {MP}}}
  SP2.agg({pls(0)}, {RS}n, {RS}n, {{==}}, dm, ln, {{==}})

# the records j, j + 1, ..., j + k written into a record tree D
def RT(k: Nat, +j: Nat, +dd: Nat, D: FD.array__Tree<T.{R}>, +t: {TR}, +x: Nat) -> FD.array__Tree<T.{R}>:
  match k:
    case 0n: FD.array__upd(T.{R}, dd, D, j, RX(t, VRL.pos(j, {RS}n, x)))
    case 1n+q: RT(q, 1n+j, dd, FD.array__upd(T.{R}, dd, D, j, RX(t, VRL.pos(j, {RS}n, x))), t, x)
''')
    rr = [f'''# the runtime's record read at byte position x (its fields by their vfx modules)
def rdb(+d: Nat, +t: {TR}, +n: U32, +off: U32, +x: Nat, +e: {{U32.to_nat(off) == x : Nat}},
    +hd: {{Nat.is_lt(d, 28n) == {TRUE}}}, +pf: {{FD.array__perfect(U32, d, t) == {TRUE}}},
    +hb: {{Nat.is_le(Nat.add(x, {RS}n), {Q}) == {TRUE}}})
    -> {{T.{R}_read(BF(t, n), off, {RS}) == (BF(t, n), RX(t, x)) : B.Buf & T.{R}}}:''']
    got = []
    for i, (c, sz, a, f, _) in enumerate(fields):
        room = f'UR.roomf(x, {RS}n, {c}n, {sz}n, {Q}, hb, {{==}})'
        ex = (f'UR.offx(d, off, {c}, x, e, FD.nat__lt_trans(d, 28n, 30n, hd, {{==}}), '
              f'FD.nat__lt_le_trans({pos(c, "x")}, Nat.add({pos(c, "x")}, {sz}n), {Q}, VTX.ltp({pos(c, "x")}, {sz - 1}n), {room}))')
        rdf = 'u8_read' if sz == 1 else 'u16_read'
        ctx = f'T.{R}_rd{i}(off, {RS}, ' + ''.join(g + ', ' for g in got) + '_)'
        rr.append(f'  %Equal.sym(B.Buf & U32, T.{rdf}(BF(t, n), U32.add(off, {c}), {sz}), (BF(t, n), {a}.OBJ(d, t, {pos(c, "x")})),\n'
                  f'      {a}.rdx(d, t, n, U32.add(off, {c}), {pos(c, "x")}, {ex}, hd, pf, {room})) :\n'
                  f'    {{{ctx} == (BF(t, n), RX(t, x)) : B.Buf & T.{R}}}')
        got.append(f'{a}.OBJ(d, t, {pos(c, "x")})')
    rr.append('  {==}\n')
    w('\n'.join(rr))
    if LIM:
        ec_def = (f'''def ecw(+len: U32, +h: {{{CHK} == {TRUE}}})
    -> {{U32.to_nat(len) == Nat.mul(CC(len), {RS}n) : Nat}}:
  Pair.fst({{U32.to_nat(len) == Nat.mul(CC(len), U32.to_nat({RS})) : Nat}}, {{Nat.is_le(CC(len), U32.to_nat({LIM})) == {TRUE}}}, VU.whole_t(len, {RS}, {LIM}, vR(), {{==}}, {{==}}, {{==}}, h))
def hcw(+len: U32, +h: {{{CHK} == {TRUE}}})
    -> {{Nat.is_le(CC(len), U32.to_nat({LIM})) == {TRUE}}}:
  Pair.snd({{U32.to_nat(len) == Nat.mul(CC(len), U32.to_nat({RS})) : Nat}}, {{Nat.is_le(CC(len), U32.to_nat({LIM})) == {TRUE}}}, VU.whole_t(len, {RS}, {LIM}, vR(), {{==}}, {{==}}, {{==}}, h))''')
    else:
        ec_def = (f'''def ecw(+len: U32, +h: {{{CHK} == {TRUE}}})
    -> {{U32.to_nat(len) == Nat.mul(CC(len), {RS}n) : Nat}}:
  VLS.whole_t1(len, {RS}, vR(), {{==}}, {{==}}, {{==}}, h)''')
    w(f'''# ---- the validator ------------------------------------------------------------------------------

def CHKw(+t: {TR}, +x: Nat, +off: U32, +len: U32) -> Bool:
  {CHK}

def ok_evalw({CW}) -> {{T.{p}_ok(BF(t, n), off, len) == (BF(t, n), CHKw(t, x, off, len)) : B.Buf & Bool}}:
  {{==}}

def vR() -> Word(31n): FD.spec_numeric__from_nat(31n, {RS}n)

# The window is c whole records{f", c <= {LIM}" if LIM else ""}.
def NN(+len: U32) -> U32: U32.div(len, {RS})
def CC(+len: U32) -> Nat: U32.to_nat(NN(len))
{ec_def}
''')
    w(subst(READER, mp))
    w(subst(SPEC.replace('@REQ', REQ_LIM if LIM else REQ_PROG), mp))
    if LIM:
        w(RL.inv_text(sch, RS, str(LIM), LSCH, CW, CA))
    else:
        w(subst(PINV, mp))
    txt = '\n'.join(L) + '\n'
    # the record storage depth from the window, not from a bound
    txt = txt.replace('      +hdd = FD.nat__le_lt_trans(B.words_depth(NN(len)), 99n, 32n, VD.wd_min(NN(len), 99n, hcl), {==})\n',
                      '      +hdd = FD.nat__le_lt_trans(B.words_depth(NN(len)), 99n, \n')
    txt = txt.replace('      +hcp = VD.wd_cover(NN(len), 99n, {==}, FD.nat__le_trans(c, U32.to_nat(0), O.pow2n(99n), hcl, {==}))\n',
                      '      +hcp = VD.wd_cover(NN(len), 99n, {==}, FD.nat__le_trans(c, U32.to_nat(\n')
    return rs_deep(RL.sym_depth(txt, RS, 99), RS, LIM)


def rs_deep(text, RS, LIM):
    """The record list's decode window at any depth d < 31 (var_rlist.deep_rlist's pattern): the read loop
    carries the records' end below 2^32 (hb32: VRL.posU32 / succU32), the fields by their vfx modules' rdxD
    (UR.offx31), the storage depth from the limit (LIM: c <= LIM) or from records of four bytes (c <= 2^d)."""
    import var_win as VWN
    T = 'True{} : Bool'
    P32 = 'FD.spec_common__pow2(32n)'
    POS = lambda j: f'VRL.pos({j}, {RS}n, x)'
    a = text.index('      +hcN = ')
    b = text.index('      +hcP = ')
    if LIM:
        K = max(LIM - 1, 1).bit_length()
        hc = (f'      +hcN = FD.nat__le_trans(c, U32.to_nat({LIM}), O.pow2n({K}n), hcw(len, hchk), {{==}})\n'
              f'      +hcp = VD.wd_cover(NN(len), {K}n, {{==}}, hcN)\n')
        hdd = f'      +hdd = FD.nat__le_lt_trans(B.words_depth(NN(len)), {K}n, 32n, VD.wd_min(NN(len), {K}n, hcN), {{==}})\n'
    else:
        assert RS >= 4, RS
        hc = (f'      +hcN = FD.logic__subst(Nat, z => {{Nat.is_le(c, z) == {T}}}, VB.pw(d), O.pow2n(d), VD.s_pow2_eq(d),\n'
              f'        VC.quad_inv(c, VB.pw(d), FD.nat__le_trans(A.quad(c), Nat.mul(c, {RS}n), A.quad(VB.pw(d)), VRL.quad_le_mul(c, {RS - 4}n),\n'
              f'          FD.logic__subst(Nat, z => {{Nat.is_le(z, A.quad(VB.pw(d))) == {T}}}, U32.to_nat(len), Nat.mul(c, {RS}n), ec,\n'
              f'            FD.nat__le_trans(U32.to_nat(len), Nat.add(x, U32.to_nat(len)), A.quad(VB.pw(d)), Order.left_below_sum(x, U32.to_nat(len)), hw)))))\n'
              f'      +hcp = VD.wd_cover(NN(len), d, FD.nat__lt_le(d, 32n, FD.nat__lt_trans(d, 31n, 32n, hd, {{==}})), hcN)\n')
        hdd = '      +hdd = FD.nat__le_lt_trans(B.words_depth(NN(len)), d, 32n, VD.wd_min(NN(len), d, hcN), FD.nat__lt_trans(d, 31n, 32n, hd, {==}))\n'
    hb32 = (f"      +hL32 = FD.logic__subst(Nat, z => {{Nat.is_lt(z, {P32}) == {T}}}, Nat.add(x, U32.to_nat(len)), Nat.add(U32.to_nat(len), x), FD.nat__add_comm(x, U32.to_nat(len)), hw32)\n"
            f"      +hLc32 = FD.logic__subst(Nat, z => {{Nat.is_lt(Nat.add(z, x), {P32}) == {T}}}, U32.to_nat(len), Nat.mul(c, {RS}n), ec, hL32)\n"
            f"      +hb32 = FD.logic__subst(Nat, z => {{Nat.is_lt({POS('z')}, {P32}) == {T}}}, c, Nat.add(1n+k, 0n),\n"
            f"        Equal.trans(Nat, c, 1n+k, Nat.add(1n+k, 0n), Equal.sym(Nat, 1n+k, c, e1), Equal.sym(Nat, Nat.add(1n+k, 0n), 1n+k, FD.nat__add_zero(1n+k))), hLc32)\n")
    text = text[:a] + hb32 + hc + text[b:]
    a = text.index('      +hdd = ')
    text = text[:a] + hdd + text[text.index('\n', a) + 1:]
    reps = [
        (f"+hb: {{Nat.is_le({POS('Nat.add(1n+k, j)')}, A.quad(VB.pw(d))) == {T}}},\n",
         f"+hb: {{Nat.is_le({POS('Nat.add(1n+k, j)')}, A.quad(VB.pw(d))) == {T}}}, +hb32: {{Nat.is_lt({POS('Nat.add(1n+k, j)')}, {P32}) == {T}}},\n"),
        (f"      +hx = VRL.nextfit(j, q, {RS}n, x, A.quad(VB.pw(d)), hb)\n",
         f"      +hx = VRL.nextfit(j, q, {RS}n, x, A.quad(VB.pw(d)), hb)\n"
         f"      +hx32 = FD.nat__le_lt_trans(Nat.add({POS('1n+j')}, {RS}n), {POS('Nat.add(2n+q, j)')}, {P32},\n"
         f"        VRL.nextfit(j, q, {RS}n, x, {POS('Nat.add(2n+q, j)')}, FD.nat__le_refl({POS('Nat.add(2n+q, j)')})), hb32)\n"
         f"      +hb232 = FD.logic__subst(Nat, z => {{Nat.is_lt(VRL.pos(1n+z, {RS}n, x), {P32}) == {T}}}, 1n+Nat.add(q, j), Nat.add(q, 1n+j), Equal.sym(Nat, Nat.add(q, 1n+j), 1n+Nat.add(q, j), FD.nat__add_succ(q, j)), hb32)\n"),
        (f"      +ex = VRL.posU(d, off, x, i, j, {RS}, {RS - 1}n, {{==}}, eo, ej, hd, hx)", f"      +ex = VRL.posU32(off, x, i, j, {RS}, {RS - 1}n, {{==}}, eo, ej, hx32)"),
        (f"VRL.succU(d, i, j, {RS - 1}n, x, ej, hd, hx), hd, pf, hb2, hdd, hk2,", f"VRL.succU32(i, j, {RS - 1}n, x, ej, hx32), hd, pf, hb2, hb232, hdd, hk2,"),
        ("eo, {==}, hd, pf, hb, hdd, hk,", "eo, {==}, hd, pf, hb, hb32, hdd, hk,"),
        ("FD.nat__lt_trans(d, 28n, 30n, hd, {==}), FD.nat__lt_le_trans(", "hd, FD.nat__lt_le_trans("),
        (f"  +hf = FD.logic__subst(Nat, z => {{Nat.is_le(Nat.add(x, z), A.quad(VB.pw(d))) == {T}}}, U32.to_nat(len), Nat.mul(c, {RS}n), ec, hw)\n",
         f"  +hf = FD.logic__subst(Nat, z => {{Nat.is_le(Nat.add(x, z), A.quad(VB.pw(d))) == {T}}}, U32.to_nat(len), Nat.mul(c, {RS}n), ec, hw)\n"
         f"  +hf32 = FD.logic__subst(Nat, z => {{Nat.is_lt(Nat.add(x, z), {P32}) == {T}}}, U32.to_nat(len), Nat.mul(c, {RS}n), ec, hw32)\n"),
        (f"VFT.fits4(2n+d, Nat.mul(c, {RS}n), FD.nat__le_trans(Nat.mul(c, {RS}n), Nat.add(x, Nat.mul(c, {RS}n)), A.quad(VB.pw(d)), Order.left_below_sum(x, Nat.mul(c, {RS}n)), hf), FD.nat__lt_trans(d, 28n, 30n, hd, {{==}}))",
         f"VFT.fits4lt(Nat.mul(c, {RS}n), FD.nat__le_lt_trans(Nat.mul(c, {RS}n), Nat.add(x, Nat.mul(c, {RS}n)), {P32}, Order.left_below_sum(x, Nat.mul(c, {RS}n)), hf32))"),
    ]
    for x_, y_ in reps:
        assert text.count(x_) >= 1, (text.count(x_), x_[:90])
        text = text.replace(x_, y_)
    text = text.replace('UR.offx(', 'UR.offx31(')
    text = re.sub(r'(?<![\w.])(FX[AB])\.rdx\(', r'\1.rdxD(', text)
    assert 'nat__lt_trans(d, 28n' not in text, [l for l in text.split('\n') if 'nat__lt_trans(d, 28n' in l][:2]
    return VWN.deep_x(text)


def outputs():
    return {fname(p, LIM): list_text(p, R, LIM) for p, R, LIM in LISTS}


def main():
    out = outputs()
    mine = sorted((ROOT / 'proofs/obj').glob('*var_winx_*.bend'))
    mine = [q for q in mine if q.read_text().find(HDR) >= 0]
    orphans = [str(q.relative_to(ROOT)) for q in mine if q not in out]
    import runtime_refs as RR  # the runtime split: the modules import the per-name files they use
    out = RR.rewire_out(out)
    if '--check' in sys.argv:
        stale = [str(p.relative_to(ROOT)) for p, t in out.items() if not p.exists() or p.read_text() != t]
        if stale or orphans:
            print('stale generated record lists: ' + ', '.join(stale + orphans))
            sys.exit(1)
        print('generated record lists are current')
        return
    for q in orphans:
        (ROOT / q).unlink()
    for p, t in out.items():
        p.write_text(t)
    print(', '.join(str(p.relative_to(ROOT)) for p in out))


if __name__ == '__main__':
    main()
