#!/usr/bin/env python3
"""Readers of BeaconState's FIXED fields at any byte position x (the field's bytes are the
window slice UW.WX(t, x, S)), for the byte-offset BeaconState module.

    python3 codegen/var_fixx.py [--check] [--no-big]

One module per field type p, proofs/obj/{big_,}vfx_<p>.bend, exporting (S = the field's
byte size, SCH = its spec schema):
  OBJ(d, t, x)                     the object T.<p>_read returns at byte position x
  rdx(d, t, n, off, x, e, hd, pf, hb)
      : T.<p>_read(UA.BF(t, n), off, S) == (UA.BF(t, n), OBJ(d, t, x))
        (e: off = x, hd: d < 28, pf: t perfect of depth d, hb: x + S <= 4 2^d)
  VAL(t, x)                        the spec value over the words UR.RWN(t, x + 4 k)
  prt(d, t, x, pf, hb)
      : Codec.parts(VAL(t, x), SCH) == Some{[S.Fixed{UW.WX(t, x, S)}]}
Vectors are read by copy_into (OBJ holds vua_fixb's copy CTN(d, t, x, S, dz)); their
values are arr_vec's chunkings of UR.RWS(S / 4, t, x), proved for every word list (no
element is unrolled). Modules whose statements carry closed sizes above stock Bend's
stack are big_ files.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'codegen'))

HEAD = ['import Base', 'import ../../src/buffer.bend as B', 'import ../../src/obj.bend as O',
        'import ../../types/fulu_obj.bend as T', 'import ../../types/schema.bend as S', 'import ../../types/primitive.bend as P',
        'import ../compact/found.bend as FD', 'import ../compact/arith.bend as A', 'import ../../proofs/nat_order.bend as Order',
        'import ../../spec/layout.bend as Layout', 'import ../../spec/codec.bend as Codec', 'import ../../spec/nat_bytes.bend as N',
        'import ../../spec/fulu_schemas.bend as Spec', 'import ./spec_fixed.bend as F', 'import ./vspec.bend as VS',
        'import ./vbuf.bend as VB', 'import ./vmr.bend as VMR', 'import ./vua.bend as UA', 'import ./vua_rd.bend as UR',
        'import ./vua_win.bend as UW', 'import ./vua_fix.bend as VTX', 'import ./vbx.bend as VBX', 'import ./vua_fixb.bend as VXB',
        'import ./arr_vec.bend as AV']
TRUE = 'True{} : Bool'
TR = 'FD.array__Tree<U32>'
BIG = 1 << 40    # (no vector needs checkq --big: sizes stay literals, values stay neutral)


def log2c(n):
    k = 0
    while (1 << k) < n:
        k += 1
    return k


def sig(name, S, rest=''):
    return (f'def {name}(+d: Nat, +t: {TR}, +n: U32, +off: U32, +x: Nat, +e: {{U32.to_nat(off) == x : Nat}},\n'
            f'    +hd: {{Nat.is_lt(d, 28n) == {TRUE}}}, +pf: {{FD.array__perfect(U32, d, t) == {TRUE}}},\n'
            f'    +hb: {{Nat.is_le(Nat.add(x, {S}n), A.quad(VB.pw(d))) == {TRUE}}}){rest}')


GEN_HEAD = HEAD + ['import ./vcopy.bend as VC', 'import ./schema_shapes.bend as SH']


def gen_text():
    """proofs/obj/vfxg.bend: the readers and values, for every size (instantiated by the
    vfx_<p> modules with closed facts that evaluate to True)."""
    L = list(GEN_HEAD) + ['', '# GENERATED by codegen/var_fixx.py. Do not edit.',
                          '# Fixed fields at any byte position, for every size: see codegen/var_fixx.py.', '']
    P = 'A.quad(VB.pw(d))'
    L.append(f'''# M, as a term that stays neutral while x is (so a value over M words is not unfolded)
def CNT(+x: Nat, +M: Nat) -> Nat: Nat.add(Nat.sub(x, x), M)
def cnt_eq(+x: Nat, +M: Nat) -> {{CNT(x, M) == M : Nat}}:
  %Equal.sym(Nat, Nat.sub(x, x), 0n, FD.nat__sub_self(x)) : {{Nat.add(_, M) == M : Nat}}
  {{==}}

''')
    L.append(f'''# copy_into of L bytes (S = L) at off (byte position x) into a zero storage of depth dz
def rdg(+d: Nat, +t: {TR}, +n: U32, +off: U32, +x: Nat, +e: {{U32.to_nat(off) == x : Nat}},
    +hd: {{Nat.is_lt(d, 28n) == {TRUE}}}, +pf: {{FD.array__perfect(U32, d, t) == {TRUE}}},
    +L: U32, +S: Nat, +dz: Nat, +k: Nat, +eS: {{Nat.is_eq(U32.to_nat(L), S) == {TRUE}}}, +hdz: {{Nat.is_lt(dz, 31n) == {TRUE}}},
    +hr: {{Nat.is_le(Nat.add(VC.NW(L), 0n), VB.pw(dz)) == {TRUE}}}, +hk: {{Nat.is_lt(k, 31n) == {TRUE}}}, +hy: {{Nat.is_le(VC.YL(L), VB.pw(k)) == {TRUE}}},
    +hb: {{Nat.is_le(Nat.add(x, S), {P}) == {TRUE}}})
    -> {{O.copy_into(UA.BF(t, n), off, L, Array.new(U32, dz, 0)) == (UA.BF(t, n), O.Words{{FD.array__thaw(U32, VXB.CTN(d, t, x, L, dz)), L}}) : B.Buf & O.Words}}:
  +hw = FD.logic__subst(Nat, z => {{Nat.is_le(Nat.add(x, z), {P}) == {TRUE}}}, S, U32.to_nat(L), Equal.sym(Nat, U32.to_nat(L), S, FD.nat__eq_from_is_eq(U32.to_nat(L), S, eS)), hb)
  %VXB.ct_n(d, t, off, x, L, dz, e) : {{O.copy_into(UA.BF(t, n), off, L, Array.new(U32, dz, 0)) == (UA.BF(t, n), O.Words{{FD.array__thaw(U32, _), L}}) : B.Buf & O.Words}}
  VBX.copy_into_at(d, t, n, off, L, dz, k, pf, FD.nat__lt_trans(d, 28n, 31n, hd, {{==}}), hdz, UW.hsx(d, off, x, L, e, hd, hw), hr, hk, hy)
''')
    for ch, mm, vp, el in (('ch8', 'm8', 'vparts8', 'S.ByteVector{32n}'), ('chu2', 'm2', 'vpartsu2', 'S.Unsigned{P.U64{}}'), ('ch12', 'm12', 'vparts12', 'S.ByteVector{48n}')):
        W = 'UR.RWS(M, t, x)'
        L.append(f'''# the value of a vector of k elements over the M words at x: its parts are the S window bytes
def prt_{ch}(+d: Nat, +t: {TR}, +x: Nat, +pf: {{FD.array__perfect(U32, d, t) == {TRUE}}}, +s: S.Schema, +k: Nat, +M: Nat, +S: Nat,
    +hs: {{SH.is_Vector(s) == {TRUE}}}, +he: {{SH.Vector_element(s) == {el} : S.Schema}}, +hk: {{Nat.is_eq(SH.Vector_length(s), k) == {TRUE}}},
    +hk0: {{Nat.is_lt(0n, k) == {TRUE}}}, +hL: {{Nat.is_eq(AV.{mm}(k), M) == {TRUE}}}, +eS: {{Nat.is_eq(A.quad(M), S) == {TRUE}}},
    +hf: {{N.fits(4n, Nat.add(S, 0n)) == {TRUE}}}, +hb: {{Nat.is_le(Nat.add(x, S), {P}) == {TRUE}}})
    -> {{Codec.parts(S.Sequence{{AV.{ch}(UR.RWS(CNT(x, M), t, x))}}, s) == Some{{[S.Fixed{{UW.WX(t, x, S)}}]}} : Maybe<&2, +List<S.Part>>}}:
  %Equal.sym(Nat, CNT(x, M), M, cnt_eq(x, M)) : {{Codec.parts(S.Sequence{{AV.{ch}(UR.RWS(_, t, x))}}, s) == Some{{[S.Fixed{{UW.WX(t, x, S)}}]}} : Maybe<&2, +List<S.Part>>}}
  prt0_{ch}(d, t, x, pf, s, k, M, S, hs, he, hk, hk0, hL, eS, hf, hb)
def prt0_{ch}(+d: Nat, +t: {TR}, +x: Nat, +pf: {{FD.array__perfect(U32, d, t) == {TRUE}}}, +s: S.Schema, +k: Nat, +M: Nat, +S: Nat,
    +hs: {{SH.is_Vector(s) == {TRUE}}}, +he: {{SH.Vector_element(s) == {el} : S.Schema}}, +hk: {{Nat.is_eq(SH.Vector_length(s), k) == {TRUE}}},
    +hk0: {{Nat.is_lt(0n, k) == {TRUE}}}, +hL: {{Nat.is_eq(AV.{mm}(k), M) == {TRUE}}}, +eS: {{Nat.is_eq(A.quad(M), S) == {TRUE}}},
    +hf: {{N.fits(4n, Nat.add(S, 0n)) == {TRUE}}}, +hb: {{Nat.is_le(Nat.add(x, S), {P}) == {TRUE}}})
    -> {{Codec.parts(S.Sequence{{AV.{ch}({W})}}, s) == Some{{[S.Fixed{{UW.WX(t, x, S)}}]}} : Maybe<&2, +List<S.Part>>}}:
  +eq = FD.nat__eq_from_is_eq(A.quad(M), S, eS)
  +hq = FD.logic__subst(Nat, z => {{Nat.is_le(Nat.add(x, z), {P}) == {TRUE}}}, S, A.quad(M), Equal.sym(Nat, A.quad(M), S, eq), hb)
  +hN = Equal.trans(Nat, F.wlen({W}), A.quad(M), S,
    Equal.trans(Nat, F.wlen({W}), A.quad(List.length(&2, U32, {W})), A.quad(M), VS.wlen_quad({W}),
      Equal.cong(Nat, Nat, z => A.quad(z), List.length(&2, U32, {W}), M, Equal.trans(Nat, List.length(&2, U32, {W}), FD.spec_common__length(U32, {W}), M, VMR.len_eq({W}), UR.rws_len(M, t, x)))), eq)
  %eq : {{Codec.parts(S.Sequence{{AV.{ch}({W})}}, s) == Some{{[S.Fixed{{UW.WX(t, x, _)}}]}} : Maybe<&2, +List<S.Part>>}}
  %UR.rws_bytes(M, d, t, x, pf, hq) : {{Codec.parts(S.Sequence{{AV.{ch}({W})}}, s) == Some{{[S.Fixed{{_}}]}} : Maybe<&2, +List<S.Part>>}}
  AV.{vp}(s, {W}, k, M, S, hs, he, hk, hk0, UR.rws_len(M, t, x), hL, hN, hf)
''')
    out = []
    for blk in L:
        if 'def prt0_' in blk:
            a = blk.index('def prt_')
            b = blk.index('def prt0_')
            blk = blk[:a] + blk[b:].rstrip('\n') + '\n\n' + blk[a:b]
        out.append(blk)
    return '\n'.join(out) + '\n'


def rt_depth(p):
    """The zero storage depth the runtime reader of p allocates."""
    import re
    src = (ROOT / 'types/fulu_obj.bend').read_text()
    m = re.search(rf'^def {p}_read\(.*Array\.new\(U32, (\d+)n, 0\)\)$', src, re.M)
    return int(m.group(1))


def vec_text(p, S, k, sch, ch, el):
    """A Vector of k elements, S bytes, read by copy_into."""
    M = S // 4
    EL = {'ch8': 'S.ByteVector{32n}', 'chu2': 'S.Unsigned{P.U64{}}', 'ch12': 'S.ByteVector{48n}'}[ch]
    dz = rt_depth(p)
    ky = log2c(S + 31)
    L = list(HEAD) + ['import ./schema_shapes.bend as SH', 'import ./vfxg.bend as VXG', '', '# GENERATED by codegen/var_fixx.py. Do not edit.',
                      f'# {p}: Vector[{el}, {k}] ({S} bytes) at any byte position: see codegen/var_fixx.py.', '']
    L.append(f'''def OBJ(+d: Nat, +t: {TR}, +x: Nat) -> O.Words: O.Words{{FD.array__thaw(U32, VXB.CTN(d, t, x, {S}, {dz}n)), {S}}}

{sig('rdx', S)}
    -> {{T.{p}_read(UA.BF(t, n), off, {S}) == (UA.BF(t, n), OBJ(d, t, x)) : B.Buf & O.Words}}:
  VXG.rdg(d, t, n, off, x, e, hd, pf, {S}, {S}n, {dz}n, {ky}n, {{==}}, {{==}}, {{==}}, {{==}}, {{==}}, hb)

def VAL(+t: {TR}, +x: Nat) -> S.Value: S.Sequence{{AV.{ch}(UR.RWS(VXG.CNT(x, {M}n), t, x))}}

def prt(+d: Nat, +t: {TR}, +x: Nat, +pf: {{FD.array__perfect(U32, d, t) == {TRUE}}}, +hb: {{Nat.is_le(Nat.add(x, {S}n), A.quad(VB.pw(d))) == {TRUE}}},
    +s: S.Schema, +es: {{s == {sch} : S.Schema}})
    -> {{Codec.parts(VAL(t, x), s) == Some{{[S.Fixed{{UW.WX(t, x, {S}n)}}]}} : Maybe<&2, +List<S.Part>>}}:
  VXG.prt_{ch}(d, t, x, pf, s, {k}n, {M}n, {S}n,
    FD.logic__subst(S.Schema, z => {{SH.is_Vector(z) == {TRUE}}}, {sch}, s, Equal.sym(S.Schema, s, {sch}, es), {{==}}),
    FD.logic__subst(S.Schema, z => {{SH.Vector_element(z) == {EL} : S.Schema}}, {sch}, s, Equal.sym(S.Schema, s, {sch}, es), {{==}}),
    FD.logic__subst(S.Schema, z => {{Nat.is_eq(SH.Vector_length(z), {k}n) == {TRUE}}}, {sch}, s, Equal.sym(S.Schema, s, {sch}, es), {{==}}),
    {{==}}, {{==}}, {{==}}, {{==}}, hb)
''')
    return '\n'.join(L) + '\n'


VECS = [('v8192_b32', 262144, 8192, 'Spec.Schema32()', 'ch8', 'Bytes32'),
        ('v65536_b32', 2097152, 65536, 'Spec.Schema80()', 'ch8', 'Bytes32'),
        ('v8192_u64', 65536, 8192, 'Spec.Schema81()', 'chu2', 'uint64')]


def outputs(no_big=False):
    out = {ROOT / 'proofs/obj/vfxg.bend': gen_text()}
    for p, S, k, sch, ch, el in VECS:
        big = S > BIG
        if big and no_big:
            continue
        out[ROOT / f'proofs/obj/{"big_" if big else ""}vfx_{p}.bend'] = vec_text(p, S, k, sch, ch, el)
    return out


def main():
    out = outputs('--no-big' in sys.argv)
    if '--check' in sys.argv:
        stale = [str(p.relative_to(ROOT)) for p, t in out.items() if not p.exists() or p.read_text() != t]
        if stale:
            print('stale: ' + ', '.join(stale))
            sys.exit(1)
        print('fixed-field readers are current')
        return
    for p, t in out.items():
        p.write_text(t)
    print(f'{len(out)} files')


if __name__ == '__main__':
    main()
