#!/usr/bin/env python3
"""Encoder laws of the bit lists (O.put_bits: the words, then the delimiter
bit at position k) against spec/bitfields.bend list_encoding.

    python3 codegen/var_bits_enc.py [--check] [--no-big]

proofs/obj/var_bits_enc_bw.bend (generated, stock): for each bit position
r < 32, OR-ing bit r into a word whose bits r..31 are zero (hzw r)
appends True to its first r bits and leaves its bits past r + 1 zero; the
dispatcher dlc over byte j, bit b; dmk_dl, the runtime mask as DL(j, b).
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

ROOT = Path(__file__).resolve().parents[1]
BW = ROOT / 'proofs/obj/var_bits_enc_bw.bend'


def word(bs):
    return ''.join(f'WCon{{{b}, ' for b in bs) + 'WNil{}' + '}' * len(bs)


def bw_module():
    L = ['import Base', 'import ../../proofs/word_split.bend as WSp', 'import ../compact/found.bend as F',
         'import ./bits_leaf.bend as BLf', 'import ./bitlist_pack.bend as BK', 'import ./dk.bend as DK',
         'import ./vspec.bend as VS', 'import ./vdepth.bend as VD', 'import ../../spec/bit_packing.bend as Bp', 'import ../../src/obj.bend as O', 'import ../../src/merkle_fast.bend as MF', '',
         '# GENERATED by codegen/var_bits_enc.py. Do not edit.',
         '# The delimiter bit: OR-ing bit r into a word whose bits r..31 are zero.', '',
         'def zlist(bs: +List<Bool>) -> Bool:', '  match bs:', '    case Nil{}: True{}', '    case Con{b, t}:',
         '      match b:', '        case True{}: False{}', '        case False{}: zlist(t)', '',
         'def bdrB(n: Nat, xs: +List<Bool>) -> +List<Bool>:', '  match n:', '    case 0n: xs', '    case 1n+p:',
         '      match xs:', '        case Nil{}: []', '        case Con{b, t}: bdrB(p, t)', '',
         '# The bits r..31 of x are zero.', 'def hzw(+r: Nat, +x: U32) -> Bool: zlist(bdrB(r, BLf.wbits(x)))', '']
    w = L.append
    for r in range(32):
        m = 32 - r
        a = [f'a{i}' for i in range(r)]
        pat = 'U32{' + word([f'+{v}' for v in a] + ['False{}'] * m) + '}'
        LO = word(a) if r else 'WNil{}'
        E = word(['True{}'] + ['False{}'] * (m - 1))
        DM = 1 << r
        T = (f'DK.P2({{BK.btk({r + 1}n, BLf.wbits(U32.or(x, {DM}))) == List.append(&2, Bool, BK.btk({r}n, BLf.wbits(x)), [True{{}}]) : +List<Bool>}}, '
             f'{{BK.zw({r + 1}n, U32.or(x, {DM})) == True{{}} : Bool}})')
        w(f'law bw{r}:')
        w('  for +x: U32')
        w(f'  for +hz: {{hzw({r}n, x) == True{{}} : Bool}}')
        w(f'  {T}')
        w(f'def bw{r}(x, hz):')
        w('  match x:')
        w(f'    case {pat}:')
        xx = 'U32{' + word(a + ['False{}'] * m) + '}'
        mot = (f'DK.P2({{BK.btk({r + 1}n, BLf.wbits(U32{{_}})) == List.append(&2, Bool, BK.btk({r}n, BLf.wbits({xx})), [True{{}}]) : +List<Bool>}}, '
               f'{{BK.zw({r + 1}n, U32{{_}}) == True{{}} : Bool}})')
        w(f'      %Equal.sym(Word(32n), Word.or(32n, WSp.join({r}n, {m}n, {LO}, Word.zero({m}n)), WSp.join({r}n, {m}n, Word.zero({r}n), {E})), '
          f'WSp.join({r}n, {m}n, {LO}, {E}), WSp.join_or({r}n, {m}n, {LO}, {E})) :')
        w(f'        {mot}')
        w('      ({==}, {==})')
        for i in range(r, 32):
            bits = [f'+{v}' for v in a] + ['False{}'] * (i - r) + ['True{}'] + [f'+c{k}' for k in range(i + 1, 32)]
            w(f'    case U32{{{word(bits)}}}: Empty.absurd({T.replace("x", "U32{" + word([v.lstrip("+") for v in bits]) + "}")}, F.logic__false_true(hz))')
        w('')
    # The delimiter mask of byte j, bit b.
    w('# The delimiter mask of byte j < 4, bit b < 8: bit 8 j + b.')
    w('def DL(j: Nat, b: Nat) -> U32:')
    w('  match j:')
    for J in range(4):
        w(f'    case {J}n:')
        w('      match b:')
        for B in range(8):
            w(f'        case {B}n: {1 << (8 * J + B)}')
        w('        case 8n+e: 0')
    w('    case 4n+e: 0')
    w('')
    RR = 'Nat.add(VS.x8(j), b)'
    TG = (f'DK.P2({{BK.btk(1n+{RR}, BLf.wbits(U32.or(x, DL(j, b)))) == List.append(&2, Bool, BK.btk({RR}, BLf.wbits(x)), [True{{}}]) : +List<Bool>}}, '
          f'{{BK.zw(1n+{RR}, U32.or(x, DL(j, b))) == True{{}} : Bool}})')
    w('# OR-ing the delimiter into word x: bit r = 8 j + b is set, the bits below kept,')
    w('# the bits above zero.')
    w('law dlc:')
    w('  for +j: Nat')
    w('  for +b: Nat')
    w('  for +x: U32')
    w('  for +hj: {Nat.is_lt(j, 4n) == True{} : Bool}')
    w('  for +hb: {Nat.is_lt(b, 8n) == True{} : Bool}')
    w(f'  for +hz: {{hzw({RR}, x) == True{{}} : Bool}}')
    w(f'  {TG}')
    w('def dlc(j, b, x, hj, hb, hz):')
    w('  match j b:')
    for J in range(4):
        for B in range(8):
            r = 8 * J + B
            w(f'    case {J}n {B}n:')
            w(f'      bw{r}(x, hz)')
        w(f'    case {J}n 8n+ +e: Empty.absurd({TG.replace("(j,", f"({J}n,").replace("VS.x8(j)", f"VS.x8({J}n)").replace(", b)", ", 8n+e)")}, F.nat__lt_zero_absurd(e, hb))')
    w(f'    case 4n+ +e _: Empty.absurd({TG.replace("(j,", "(4n+e,").replace("VS.x8(j)", "VS.x8(4n+e)")}, F.nat__lt_zero_absurd(e, hj))')
    w('')
    KD = 'O.shl_bytes(U32.and(MF.shl_by(1, U32.and(K, 7)), 255), U32.and(U32.add(0, U32.shrn(K, 3n)), 3))'
    w('# The runtime delimiter mask (O.w8_delim at p = 0) is DL of the bit count\'s byte and bit.')
    w('law dmk_dl:')
    w('  for +K: U32')
    w('  for +j: Nat')
    w('  for +b: Nat')
    w('  for +ej: {U32.to_nat(U32.and(U32.add(0, U32.shrn(K, 3n)), 3)) == j : Nat}')
    w('  for +eb: {U32.to_nat(U32.and(K, 7)) == b : Nat}')
    w('  for +hj: {Nat.is_lt(j, 4n) == True{} : Bool}')
    w('  for +hb: {Nat.is_lt(b, 8n) == True{} : Bool}')
    w(f'  {{{KD} == DL(j, b) : U32}}')
    w('def dmk_dl(K, j, b, ej, eb, hj, hb):')
    w('  match j b:')
    for J in range(4):
        for B in range(8):
            w(f'    case {J}n {B}n:')
            w(f'      %Equal.sym(U32, U32.and(K, 7), {B}, F.u32__injective(U32.and(K, 7), {B}, eb)) :')
            w(f'        {{O.shl_bytes(U32.and(MF.shl_by(1, _), 255), U32.and(U32.add(0, U32.shrn(K, 3n)), 3)) == DL({J}n, {B}n) : U32}}')
            w(f'      %Equal.sym(U32, U32.and(U32.add(0, U32.shrn(K, 3n)), 3), {J}, F.u32__injective(U32.and(U32.add(0, U32.shrn(K, 3n)), 3), {J}, ej)) :')
            w(f'        {{O.shl_bytes(U32.and(MF.shl_by(1, {B}), 255), _) == DL({J}n, {B}n) : U32}}')
            w('      {==}')
        w(f'    case {J}n 8n+ +e: Empty.absurd({{{KD} == DL({J}n, 8n+e) : U32}}, F.nat__lt_zero_absurd(e, hb))')
    w(f'    case 4n+ +e _: Empty.absurd({{{KD} == DL(4n+e, b) : U32}}, F.nat__lt_zero_absurd(e, hj))')
    w('')
    w('# Whether the last word is partial: 0 at a word boundary, else 1.')
    w('def CWr(r: Nat) -> Nat:')
    w('  match r:')
    w('    case 0n: 0n')
    w('    case 1n+p: 1n')
    w('')
    CF = ('DK.P2({VD.s_rng(2n, Nat.add(Nat.add(j, VD.s_rng(3n, Nat.add(b, 7n))), 3n)) == CWr(Nat.add(VS.x8(j), b)) : Nat}, '
          'DK.P2({Nat.is_le(VD.s_rng(3n, Nat.add(b, 7n)), 1n) == True{} : Bool}, '
          'DK.P2({VD.s_rng(2n, Nat.add(j, VD.s_rng(3n, b))) == 0n : Nat}, '
          'DK.P2({VD.s_rng(2n, Nat.add(Nat.add(j, 1n), 3n)) == 1n : Nat}, '
          'DK.P2({Nat.is_le(Nat.add(VS.x8(j), b), 31n) == True{} : Bool}, '
          '{Bp.byte_count(1n+Nat.add(VS.x8(j), b)) == Nat.add(j, 1n) : Nat})))))')
    w('# The closed facts of byte j < 4, bit b < 8.')
    w('law cfj:')
    w('  for +j: Nat')
    w('  for +b: Nat')
    w('  for +hj: {Nat.is_lt(j, 4n) == True{} : Bool}')
    w('  for +hb: {Nat.is_lt(b, 8n) == True{} : Bool}')
    w(f'  {CF}')
    w('def cfj(j, b, hj, hb):')
    w('  match j b:')
    for J in range(4):
        for B in range(8):
            w(f'    case {J}n {B}n: ({{==}}, ({{==}}, ({{==}}, ({{==}}, ({{==}}, {{==}})))))')
        w(f'    case {J}n 8n+ +e: Empty.absurd({CF.replace("(j,", f"({J}n,").replace("VS.x8(j)", f"VS.x8({J}n)").replace("Nat.add(b,", "Nat.add(8n+e,").replace(", b)", ", 8n+e)")}, F.nat__lt_zero_absurd(e, hb))')
    w(f'    case 4n+ +e _: Empty.absurd({CF.replace("(j,", "(4n+e,").replace("VS.x8(j)", "VS.x8(4n+e)")}, F.nat__lt_zero_absurd(e, hj))')
    return '\n'.join(L) + '\n'


def main():
    out = {BW: bw_module()}
    no_big = '--no-big' in sys.argv
    mine = [q for q in (ROOT / 'proofs/obj').glob('*.bend') if q.name.startswith(('var_bits_enc_', 'var_bitc_enc_', 'big_var_bitc_enc_'))]
    orphans = sorted(str(q.relative_to(ROOT)) for q in mine if q not in out and not (no_big and q.name.startswith('big_')))
    if '--check' in sys.argv:
        stale = [str(p.relative_to(ROOT)) for p, t in out.items() if not p.exists() or p.read_text() != t] + orphans
        if stale:
            print('stale generated bit-list encoder laws: ' + ', '.join(stale))
            sys.exit(1)
        print('generated bit-list encoder laws are current')
        return
    for q in orphans:
        (ROOT / q).unlink()
    for p, t in out.items():
        p.write_text(t)
    print('wrote ' + ', '.join(str(p.relative_to(ROOT)) for p in out))


if __name__ == '__main__':
    main()
