#!/usr/bin/env python3
"""Encoder laws of the bit lists (O.put_bits: the words, then the delimiter
bit at position k) against spec/bitfields.bend list_encoding.

    python3 codegen/var_bits_enc.py [--check] [--no-big]

proofs/obj/var_bits_enc_bw.bend (generated, stock): for each bit position
r < 32, OR-ing bit r into a word whose bits r..31 are zero (hzw r)
appends True to its first r bits and leaves its bits past r + 1 zero; the
dispatcher dlc over byte j, bit b; dmk_dl, the runtime mask as DL(j, b); cfj,
the closed facts of each (j, b).

proofs/obj/var_bits_enc_<X>.bend (generated, stock), for each generic BitList[N]
name X (codegen/var_bits.py gbits_names): encode_eval, X_encode(O.Bits{thaw T, K})
== (O.Bits{thaw T, K}, B.Buf{thaw(OUT(T, K)), K / 8 + 1}) with OUT the explicit
tree DL.OZ (the object's words copied into a zero tree, the delimiter OR-ed in),
and encode_spec, Decoding.decodes(GS.X(), BY(T, K), BitsValue{btk(K, bitsof(slots T))})
for BY the first K / 8 + 1 bytes of OUT. Hypotheses: T perfect of depth dw < 31,
K <= N, the bits K mod 32.. of word K / 32 zero (DL.HZ), and for N >= 32 (the
sized shape, O.out_new after O.bits_sizek) the capacity check K / 32 + 1 <= 2^dw.
The hand-written libraries: proofs/obj/vbitenc.bend (put_bits over main's
VBE.put_words_any, pack_delim, the numbers of K), vbitdl.bend (words_pack),
vbitcore.bend (enc_core, enc_small, enc_sized).
"""
import re
import sys
from pathlib import Path
import runtime_refs as RR  # noqa: E402  the runtime split: the monoliths' text, the split files' imports

sys.path.insert(0, str(Path(__file__).resolve().parent))

ROOT = Path(__file__).resolve().parents[1]
BW = ROOT / 'proofs/obj/var_bits_enc_bw.bend'


def word(bs):
    return ''.join(f'WCon{{{b}, ' for b in bs) + 'WNil{}' + '}' * len(bs)


def bw_module():
    L = ['import Base', 'import ../../proofs/word_split.bend as WSp', 'import ../compact/found.bend as F',
         'import ./bits_leaf.bend as BLf', 'import ./bitlist_pack.bend as BK', 'import ./dk.bend as DK',
         'import ./vspec.bend as VS', 'import ./vdepth.bend as VD', 'import ../../spec/bit_packing.bend as Bp', 'import ../../src/obj.bend as O', 'import ../../src/merkle_fast.bend as MF', '',
         '# GENERATED by codegen/var_bits_enc.py. Do not edit.',
         '# The delimiter bit: OR-ing bit r into a word whose bits r..31 are zero.', '',
         'def zlist(bs: +List<Bool>) -> Bool:', '  match bs:', '    case Nil{}: True{}', '    case Con{b, t}:',
         '      match b:', '        case True{}: False{}', '        case False{}: zlist(t)', '',
         'def bdrB(n: Nat, xs: +List<Bool>) -> +List<Bool>:', '  match n:', '    case 0n: xs', '    case 1n+p:',
         '      match xs:', '        case Nil{}: []', '        case Con{b, t}: bdrB(p, t)', '',
         '# The bits r..31 of x are zero.', 'def hzw(+r: Nat, +x: U32) -> Bool: zlist(bdrB(r, BLf.wbits(x)))', '']
    w = L.append
    for r in range(32):
        m = 32 - r
        a = [f'a{i}' for i in range(r)]
        pat = 'U32{' + word([f'+{v}' for v in a] + ['False{}'] * m) + '}'
        LO = word(a) if r else 'WNil{}'
        E = word(['True{}'] + ['False{}'] * (m - 1))
        DM = 1 << r
        T = (f'DK.P2({{BK.btk({r + 1}n, BLf.wbits(U32.or(x, {DM}))) == List.append(&2, Bool, BK.btk({r}n, BLf.wbits(x)), [True{{}}]) : +List<Bool>}}, '
             f'{{BK.zw({r + 1}n, U32.or(x, {DM})) == True{{}} : Bool}})')
        w(f'law bw{r}:')
        w('  for +x: U32')
        w(f'  for +hz: {{hzw({r}n, x) == True{{}} : Bool}}')
        w(f'  {T}')
        w(f'def bw{r}(x, hz):')
        w('  match x:')
        w(f'    case {pat}:')
        xx = 'U32{' + word(a + ['False{}'] * m) + '}'
        mot = (f'DK.P2({{BK.btk({r + 1}n, BLf.wbits(U32{{_}})) == List.append(&2, Bool, BK.btk({r}n, BLf.wbits({xx})), [True{{}}]) : +List<Bool>}}, '
               f'{{BK.zw({r + 1}n, U32{{_}}) == True{{}} : Bool}})')
        w(f'      %Equal.sym(Word(32n), Word.or(32n, WSp.join({r}n, {m}n, {LO}, Word.zero({m}n)), WSp.join({r}n, {m}n, Word.zero({r}n), {E})), '
          f'WSp.join({r}n, {m}n, {LO}, {E}), WSp.join_or({r}n, {m}n, {LO}, {E})) :')
        w(f'        {mot}')
        w('      ({==}, {==})')
        for i in range(r, 32):
            bits = [f'+{v}' for v in a] + ['False{}'] * (i - r) + ['True{}'] + [f'+c{k}' for k in range(i + 1, 32)]
            w(f'    case U32{{{word(bits)}}}: Empty.absurd({T.replace("x", "U32{" + word([v.lstrip("+") for v in bits]) + "}")}, F.logic__false_true(hz))')
        w('')
    # The delimiter mask of byte j, bit b.
    w('# The delimiter mask of byte j < 4, bit b < 8: bit 8 j + b.')
    w('def DL(j: Nat, b: Nat) -> U32:')
    w('  match j:')
    for J in range(4):
        w(f'    case {J}n:')
        w('      match b:')
        for B in range(8):
            w(f'        case {B}n: {1 << (8 * J + B)}')
        w('        case 8n+e: 0')
    w('    case 4n+e: 0')
    w('')
    RR = 'Nat.add(VS.x8(j), b)'
    TG = (f'DK.P2({{BK.btk(1n+{RR}, BLf.wbits(U32.or(x, DL(j, b)))) == List.append(&2, Bool, BK.btk({RR}, BLf.wbits(x)), [True{{}}]) : +List<Bool>}}, '
          f'{{BK.zw(1n+{RR}, U32.or(x, DL(j, b))) == True{{}} : Bool}})')
    w('# OR-ing the delimiter into word x: bit r = 8 j + b is set, the bits below kept,')
    w('# the bits above zero.')
    w('law dlc:')
    w('  for +j: Nat')
    w('  for +b: Nat')
    w('  for +x: U32')
    w('  for +hj: {Nat.is_lt(j, 4n) == True{} : Bool}')
    w('  for +hb: {Nat.is_lt(b, 8n) == True{} : Bool}')
    w(f'  for +hz: {{hzw({RR}, x) == True{{}} : Bool}}')
    w(f'  {TG}')
    w('def dlc(j, b, x, hj, hb, hz):')
    w('  match j b:')
    for J in range(4):
        for B in range(8):
            r = 8 * J + B
            w(f'    case {J}n {B}n:')
            w(f'      bw{r}(x, hz)')
        w(f'    case {J}n 8n+ +e: Empty.absurd({TG.replace("(j,", f"({J}n,").replace("VS.x8(j)", f"VS.x8({J}n)").replace(", b)", ", 8n+e)")}, F.nat__lt_zero_absurd(e, hb))')
    w(f'    case 4n+ +e _: Empty.absurd({TG.replace("(j,", "(4n+e,").replace("VS.x8(j)", "VS.x8(4n+e)")}, F.nat__lt_zero_absurd(e, hj))')
    w('')
    KD = 'O.shl_bytes(U32.and(MF.shl_by(1, U32.and(K, 7)), 255), U32.and(U32.add(0, U32.shrn(K, 3n)), 3))'
    w('# The runtime delimiter mask (O.w8_delim at p = 0) is DL of the bit count\'s byte and bit.')
    w('law dmk_dl:')
    w('  for +K: U32')
    w('  for +j: Nat')
    w('  for +b: Nat')
    w('  for +ej: {U32.to_nat(U32.and(U32.add(0, U32.shrn(K, 3n)), 3)) == j : Nat}')
    w('  for +eb: {U32.to_nat(U32.and(K, 7)) == b : Nat}')
    w('  for +hj: {Nat.is_lt(j, 4n) == True{} : Bool}')
    w('  for +hb: {Nat.is_lt(b, 8n) == True{} : Bool}')
    w(f'  {{{KD} == DL(j, b) : U32}}')
    w('def dmk_dl(K, j, b, ej, eb, hj, hb):')
    w('  match j b:')
    for J in range(4):
        for B in range(8):
            w(f'    case {J}n {B}n:')
            w(f'      %Equal.sym(U32, U32.and(K, 7), {B}, F.u32__injective(U32.and(K, 7), {B}, eb)) :')
            w(f'        {{O.shl_bytes(U32.and(MF.shl_by(1, _), 255), U32.and(U32.add(0, U32.shrn(K, 3n)), 3)) == DL({J}n, {B}n) : U32}}')
            w(f'      %Equal.sym(U32, U32.and(U32.add(0, U32.shrn(K, 3n)), 3), {J}, F.u32__injective(U32.and(U32.add(0, U32.shrn(K, 3n)), 3), {J}, ej)) :')
            w(f'        {{O.shl_bytes(U32.and(MF.shl_by(1, {B}), 255), _) == DL({J}n, {B}n) : U32}}')
            w('      {==}')
        w(f'    case {J}n 8n+ +e: Empty.absurd({{{KD} == DL({J}n, 8n+e) : U32}}, F.nat__lt_zero_absurd(e, hb))')
    w(f'    case 4n+ +e _: Empty.absurd({{{KD} == DL(4n+e, b) : U32}}, F.nat__lt_zero_absurd(e, hj))')
    w('')
    w('# Whether the last word is partial: 0 at a word boundary, else 1.')
    w('def CWr(r: Nat) -> Nat:')
    w('  match r:')
    w('    case 0n: 0n')
    w('    case 1n+p: 1n')
    w('')
    CF = ('DK.P2({VD.s_rng(2n, Nat.add(Nat.add(j, VD.s_rng(3n, Nat.add(b, 7n))), 3n)) == CWr(Nat.add(VS.x8(j), b)) : Nat}, '
          'DK.P2({Nat.is_le(VD.s_rng(3n, Nat.add(b, 7n)), 1n) == True{} : Bool}, '
          'DK.P2({VD.s_rng(2n, Nat.add(j, VD.s_rng(3n, b))) == 0n : Nat}, '
          'DK.P2({VD.s_rng(2n, Nat.add(Nat.add(j, 1n), 3n)) == 1n : Nat}, '
          'DK.P2({Nat.is_le(Nat.add(VS.x8(j), b), 31n) == True{} : Bool}, '
          '{Bp.byte_count(1n+Nat.add(VS.x8(j), b)) == Nat.add(j, 1n) : Nat})))))')
    w('# The closed facts of byte j < 4, bit b < 8.')
    w('law cfj:')
    w('  for +j: Nat')
    w('  for +b: Nat')
    w('  for +hj: {Nat.is_lt(j, 4n) == True{} : Bool}')
    w('  for +hb: {Nat.is_lt(b, 8n) == True{} : Bool}')
    w(f'  {CF}')
    w('def cfj(j, b, hj, hb):')
    w('  match j b:')
    for J in range(4):
        for B in range(8):
            w(f'    case {J}n {B}n: ({{==}}, ({{==}}, ({{==}}, ({{==}}, ({{==}}, {{==}})))))')
        w(f'    case {J}n 8n+ +e: Empty.absurd({CF.replace("(j,", f"({J}n,").replace("VS.x8(j)", f"VS.x8({J}n)").replace("Nat.add(b,", "Nat.add(8n+e,").replace(", b)", ", 8n+e)")}, F.nat__lt_zero_absurd(e, hb))')
    w(f'    case 4n+ +e _: Empty.absurd({CF.replace("(j,", "(4n+e,").replace("VS.x8(j)", "VS.x8(4n+e)")}, F.nat__lt_zero_absurd(e, hj))')
    return '\n'.join(L) + '\n'


PAD = ROOT / 'proofs/obj/var_bits_enc_pad.bend'


def pad_module():
    L = ['import Base', 'import ../../src/obj.bend as O', 'import ../../src/primitives.bend as I', 'import ../../spec/primitives.bend as SP',
         'import ../compact/found.bend as F', 'import ../compact/arith.bend as A', 'import ./bits_leaf.bend as BLf', 'import ./bitlist_pack.bend as BK',
         'import ./words_spec.bend as WS', 'import ./mtree_run.bend as MR', 'import ./vspec.bend as VS', 'import ./vdepth.bend as VD',
         'import ./var_bits_enc_bw.bend as BW', 'import ./vbitdl.bend as DL', '',
         '# GENERATED by codegen/var_bits_enc.py. Do not edit.',
         '# The object invariant of the bit-list root laws (bitlist_obj wfb1: the bits of the last',
         '# byte past K zero, BK.zt; the bytes of the last chunk past the byte count zero) gives',
         '# DL.HZ at word K / 32: its bits K mod 32 .. 31 are zero.', '',
         'def unth(n: Nat, xs: +List<U32>) -> U32:', '  match n:', '    case 0n:', '      match xs:', '        case Nil{}: 0', '        case Con{h, t}: h',
         '    case 1n+p:', '      match xs:', '        case Nil{}: 0', '        case Con{h, t}: unth(p, t)', '',
         'def bnth(n: Nat, xs: +List<Bool>) -> Bool:', '  match n:', '    case 0n:', '      match xs:', '        case Nil{}: False{}', '        case Con{h, t}: h',
         '    case 1n+p:', '      match xs:', '        case Nil{}: False{}', '        case Con{h, t}: bnth(p, t)', '']
    w = L.append
    for r in range(1, 32):
        j, b = r // 8, r % 8
        c = j + (1 if b else 0)
        a = [f'a{i}' for i in range(r)]
        G = lambda X: f'{{BW.hzw({r}n, {X}) == True{{}} : Bool}}'
        w(f'law hzp{r}:')
        w('  for +x: U32')
        w(f'  for +hz: {{BK.zw({r}n, x) == True{{}} : Bool}}')
        w(f'  for +hp: {{WS.bdrop({c}n, I.limb(x)) == SP.zero_bytes({4 - c}n) : +List<U32>}}')
        w(f'  {G("x")}')
        w(f'def hzp{r}(x, hz, hp):')
        w('  match x:')
        w(f'    case U32{{{word([f"+{v}" for v in a] + ["False{}"] * (32 - r))}}}: {{==}}')
        for q in range(r, 32):
            bits = [f'+{v}' for v in a] + ['False{}'] * (q - r) + ['True{}'] + [f'+c{k}' for k in range(q + 1, 32)]
            X = 'U32{' + word([v.lstrip('+') for v in bits]) + '}'
            if q < 8 * c:
                pr = 'F.logic__false_true(hz)'
            else:
                pr = (f'F.logic__true_false(Equal.cong(+List<U32>, Bool, z => bnth({q % 8}n, BLf.wbits(unth({q // 8 - c}n, z))), '
                      f'WS.bdrop({c}n, I.limb({X})), SP.zero_bytes({4 - c}n), hp))')
            w(f'    case U32{{{word(bits)}}}: Empty.absurd({G(X)}, {pr})')
        w('')
    for R in range(1, 33):
        i, c = (R - 1) // 4, (R - 1) % 4 + 1
        CB = 'WS.cb(S, Nat.add(Q, 0n))'
        w(f'law padw{R}:')
        w('  for +S: List<&2, U32>')
        w('  for +Q: Nat')
        w(f'  for +hp: {{WS.bdrop({R}n, {CB}) == SP.zero_bytes({32 - R}n) : +List<U32>}}')
        w(f'  {{WS.bdrop({c}n, I.limb(MR.wd(S, Nat.add(O.e8(Nat.add(Q, 0n)), {i}n)))) == SP.zero_bytes({4 - c}n) : +List<U32>}}')
        w(f'def padw{R}(S, Q, hp):')
        w(f'  Equal.cong(+List<U32>, +List<U32>, z => WS.btake({4 - c}n, z), WS.bdrop({R}n, {CB}), SP.zero_bytes({32 - R}n), hp)')
        w('')
    w('law cwb:')
    w('  for +b: Nat')
    w('  for +hb: {Nat.is_lt(b, 8n) == True{} : Bool}')
    w('  {VD.s_rng(3n, Nat.add(b, 7n)) == BW.CWr(b) : Nat}')
    w('def cwb(b, hb):')
    w('  match b:')
    for B in range(8):
        w(f'    case {B}n: {{==}}')
    w('    case 8n+ +e: Empty.absurd({VD.s_rng(3n, Nat.add(8n+e, 7n)) == BW.CWr(8n+e) : Nat}, F.nat__lt_zero_absurd(e, hb))')
    w('')
    CI = '{Nat.is_le(Nat.add(A.quad(i), Nat.add(j, BW.CWr(b))), 32n) == True{} : Bool}'
    w('# The offset 4 i + j + [b > 0] of a byte count in its chunk is at most 32.')
    w('law cib:')
    for v in ['j', 'b', 'i']:
        w(f'  for +{v}: Nat')
    w('  for +hj: {Nat.is_lt(j, 4n) == True{} : Bool}')
    w('  for +hb: {Nat.is_lt(b, 8n) == True{} : Bool}')
    w('  for +hi: {Nat.is_lt(i, 8n) == True{} : Bool}')
    w(f'  {CI}')
    w('def cib(j, b, i, hj, hb, hi):')
    w('  match j b i:')
    for J in range(4):
        for B in range(8):
            for I in range(8):
                w(f'    case {J}n {B}n {I}n: {{==}}')
            w(f'    case {J}n {B}n 8n+ +e: Empty.absurd({{Nat.is_le(Nat.add(A.quad(8n+e), Nat.add({J}n, BW.CWr({B}n))), 32n) == True{{}} : Bool}}, F.nat__lt_zero_absurd(e, hi))')
        w(f'    case {J}n 8n+ +e _: Empty.absurd({{Nat.is_le(Nat.add(A.quad(i), Nat.add({J}n, BW.CWr(8n+e))), 32n) == True{{}} : Bool}}, F.nat__lt_zero_absurd(e, hb))')
    w('    case 4n+ +e _ _: Empty.absurd({Nat.is_le(Nat.add(A.quad(i), Nat.add(4n+e, BW.CWr(b))), 32n) == True{} : Bool}, F.nat__lt_zero_absurd(e, hj))')
    w('')
    w('# A nonzero bit offset 8 j + b has a nonzero byte count j + [b > 0] in its word.')
    w('law cpos:')
    w('  for +j: Nat')
    w('  for +b: Nat')
    w('  for +hj: {Nat.is_lt(j, 4n) == True{} : Bool}')
    w('  for +hb: {Nat.is_lt(b, 8n) == True{} : Bool}')
    w('  for +h: {Nat.is_lt(0n, Nat.add(VS.x8(j), b)) == True{} : Bool}')
    w('  {Nat.is_lt(0n, Nat.add(j, BW.CWr(b))) == True{} : Bool}')
    w('def cpos(j, b, hj, hb, h):')
    w('  match j b:')
    for J in range(4):
        for B in range(8):
            if J == 0 and B == 0:
                w('    case 0n 0n: Empty.absurd({Nat.is_lt(0n, Nat.add(0n, BW.CWr(0n))) == True{} : Bool}, F.logic__false_true(h))')
            else:
                w(f'    case {J}n {B}n: {{==}}')
        w(f'    case {J}n 8n+ +e: Empty.absurd({{Nat.is_lt(0n, Nat.add({J}n, BW.CWr(8n+e))) == True{{}} : Bool}}, F.nat__lt_zero_absurd(e, hb))')
    w('    case 4n+ +e _: Empty.absurd({Nat.is_lt(0n, Nat.add(4n+e, BW.CWr(b))) == True{} : Bool}, F.nat__lt_zero_absurd(e, hj))')
    w('')
    W_ = 'MR.wd(S, Nat.add(O.e8(Nat.add(Q, 0n)), i))'
    RR = 'Nat.add(A.quad(i), Nat.add(j, BW.CWr(b)))'
    HZ = f'{{BK.zw(Nat.add(VS.x8(j), b), {W_}) == True{{}} : Bool}}'
    HP = f'{{WS.bdrop({RR}, WS.cb(S, Nat.add(Q, 0n))) == SP.zero_bytes(Nat.sub(32n, {RR})) : +List<U32>}}'
    GL = f'{{DL.HZ(Nat.add(VS.x8(j), b), {W_}) == True{{}} : Bool}}'
    w('# At byte j, bit b of word 8 Q + i of the storage (the last chunk Q).')
    w('law hzd:')
    for v in ['j', 'b', 'i']:
        w(f'  for +{v}: Nat')
    w('  for +S: List<&2, U32>')
    w('  for +Q: Nat')
    w('  for +hj: {Nat.is_lt(j, 4n) == True{} : Bool}')
    w('  for +hb: {Nat.is_lt(b, 8n) == True{} : Bool}')
    w('  for +hi: {Nat.is_lt(i, 8n) == True{} : Bool}')
    w(f'  for +hz: {HZ}')
    w(f'  for +hp: {HP}')
    w(f'  {GL}')
    w('def hzd(j, b, i, S, Q, hj, hb, hi, hz, hp):')
    w('  match j b i:')

    def sub(t, J, B, I):
        return t.replace('VS.x8(j)', f'VS.x8({J})').replace('Nat.add(j, ', f'Nat.add({J}, ').replace('CWr(b)', f'CWr({B})').replace('VS.x8(' + J + '), b)', f'VS.x8({J}), {B})').replace('A.quad(i)', f'A.quad({I})').replace('0n)), i))', f'0n)), {I}))')
    for J in range(4):
        for B in range(8):
            for I in range(8):
                r = 8 * J + B
                w(f'    case {J}n {B}n {I}n:')
                if r == 0:
                    w('      {==}')
                else:
                    c = J + (1 if B else 0)
                    R = 4 * I + c
                    w(f'      hzp{r}(MR.wd(S, Nat.add(O.e8(Nat.add(Q, 0n)), {I}n)), hz, padw{R}(S, Q, hp))')
            w(f'    case {J}n {B}n 8n+ +e: Empty.absurd({sub(GL, f"{J}n", f"{B}n", "8n+e")}, F.nat__lt_zero_absurd(e, hi))')
        w(f'    case {J}n 8n+ +e _: Empty.absurd({sub(GL, f"{J}n", "8n+e", "i")}, F.nat__lt_zero_absurd(e, hb))')
    w(f'    case 4n+ +e _ _: Empty.absurd({sub(GL, "4n+e", "b", "i")}, F.nat__lt_zero_absurd(e, hj))')
    return '\n'.join(L) + '\n'


def lg(x):
    """The least k with x <= 2^k."""
    k = 0
    while (1 << k) < x:
        k += 1
    return k


def names():
    import var_bits
    return var_bits.gbits_names()


NHEAD = ['import Base', 'import ../../src/buffer.bend as B', 'import ../../src/obj.bend as O', 'import ../../types/generic_obj.bend as T',
         'import ../../types/schema.bend as S', 'import ../compact/found.bend as F', 'import ../../spec/decoding_relation.bend as Decoding',
         'import ../../spec/codec.bend as Codec', 'import ../../spec/bitfields.bend as Bits', 'import ../../spec/bit_packing.bend as Bp',
         'import ./generic_specs.bend as GS', 'import ./spec_fixed.bend as FX', 'import ./vspec.bend as VS', 'import ./vbuf.bend as VB',
         'import ./vcopy.bend as VC', 'import ./vdepth.bend as VD', 'import ./vbenc.bend as VBE', 'import ./vbitenc.bend as VBT',
         'import ./vbitdl.bend as DL', 'import ./vbitcore.bend as CO', 'import ./bitlist_pack.bend as BK', 'import ./bitlist_rep.bend as BO', 'import ./vbitrep.bend as VR']


def name_module(X, N, p, src):
    small = f'def {X}_encode(o: O.Bits) -> O.Bits & B.Buf: {X}_enc_put({p}_putn(O.out_at(0n), 0, o))' in src
    sized = f'def {X}_encode(o: O.Bits) -> O.Bits & B.Buf: {X}_enc_sized({p}_size(o))' in src
    assert small != sized, X
    if sized:
        assert f'def {p}_size(o: O.Bits) -> O.Bits & U32: O.bits_sizek(o)' in src, X
        assert f'  {X}_enc_put(n, {p}_putn(O.out_new(n), 0, o))' in src, X
    else:
        assert N <= 31 and f'  (o, O.out_done((m .&. 2147483647 : U32), out))' in src, X
    assert f'def {p}_putn(out: Array<U32>, +pos: U32, o: O.Bits) -> Array<U32> & (O.Bits & U32): O.put_bits_n(out, pos, o)' in src, X
    kb = lg(N + 8)
    KY = lg(32 + N)
    KS = lg(N + 2)
    KO = lg((N >> 5) + 1)
    DO = '0n' if small else 'CO.DOK(K)'
    L = NHEAD + ['', '# GENERATED by codegen/var_bits_enc.py. Do not edit.',
                 f'# {X}: BitList[{N}] (runtime {p}), the encoder: {X}_encode of an object O.Bits{{thaw(T), K}}',
                 '# representing a value of GS.X() (the root laws\' BO.rep_bits: bitlist_obj wfb, K <= N)',
                 '# returns the object and the buffer of an explicit tree, whose K / 8 + 1 bytes are the',
                 '# spec/codec.bend encoding of the object\'s value BO.bview, the first K bits of its words.', '']
    w = L.append
    OBJ = 'O.Bits{F.array__thaw(U32, T), K}'
    w(f'def OUT(+T: F.array__Tree<U32>, +K: U32) -> F.array__Tree<U32>: DL.OZ({DO}, T, K)')
    w(f'def VAL(+T: F.array__Tree<U32>, +K: U32) -> S.Value: S.BitsValue{{BO.bview({OBJ})}}')
    w('def BY(+T: F.array__Tree<U32>, +K: U32) -> +List<U32>: VS.bt(U32.to_nat(CO.NK(K)), FX.limbs(F.array__slots(U32, OUT(T, K))))')
    w('')
    P = ['+dw: Nat', '+T: F.array__Tree<U32>', '+K: U32', '+pfT: {F.array__perfect(U32, dw, T) == True{} : Bool}',
         '+hdw: {Nat.is_lt(dw, 31n) == True{} : Bool}', f'+rep: BO.rep_bits({OBJ}, GS.{X}())']
    A = ['dw', 'T', 'K', 'pfT', 'hdw', 'rep']
    if sized:
        P.append('+hcap: {Nat.is_le(Nat.add(U32.to_nat(U32.shrn(K, 5n)), 1n), VB.pw(dw)) == True{} : Bool}')
        A.append('hcap')
    PS, AS = ', '.join(P), ', '.join(A)
    if small:
        core = f'CO.enc_small(dw, T, K, {kb}n, {KY}n, {N}n, pfT, hdw, {{==}}, {{==}}, hN, {{==}}, {{==}}, {{==}}, hz)'
    else:
        core = f'CO.enc_sized(dw, T, K, {kb}n, {KY}n, {KO}n, {N}n, pfT, hdw, {{==}}, {{==}}, {{==}}, hN, {{==}}, {{==}}, {{==}}, hcap, hz)'
    QS = (f'CO.qs_small(dw, K, {kb}n, {N}n, {{==}}, hN, {{==}}, {{==}})' if small else
          f'CO.qs_sized(dw, K, {kb}n, {N}n, {{==}}, hN, {{==}}, hcap)')
    w(f'def cr({PS}) -> CO.CR({DO}, T, K):')
    w('  (+wf, +r1) = rep')
    w(f'  +hN = VR.rep_N(T, K, {N}n, rep)')
    w(f'  +hz = VR.rep_hz(dw, T, K, {kb}n, {N}n, pfT, {{==}}, hN, {{==}}, {QS}, wf)')
    w(f'  {core}')
    w('')
    if sized:
        w(f'def zeros_at(+du: U32, +k: Nat, +e: {{U32.to_nat(du) == k : Nat}}, +hk: {{Nat.is_le(k, {KO}n) == True{{}} : Bool}})')
        w('    -> {B.zeros(du) == Array.new(U32, k, 0) : Array<U32>}:')
        w('  match k:')
        for j in range(KO + 1):
            w(f'    case {j}n:')
            w(f'      %Equal.sym(U32, du, {j}, F.u32__injective(du, {j}, e)) : {{B.zeros(_) == Array.new(U32, {j}n, 0) : Array<U32>}}')
            w('      {==}')
        w(f'    case {KO + 1}n+p: Empty.absurd({{B.zeros(du) == Array.new(U32, {KO + 1}n+p, 0) : Array<U32>}}, F.logic__false_true(hk))')
        w('')
    RE = f'({OBJ}, B.Buf{{F.array__thaw(U32, OUT(T, K)), CO.NK(K)}})'
    ZT = f'F.array__thaw(U32, VC.ZT({DO}))'
    EV = f'CO.cr1({DO}, T, K, cr({AS}))'
    PN = f'Array<U32> & (O.Bits & U32)'
    w('# The encoder returns the object and the buffer of the tree OUT, K / 8 + 1 bytes.')
    w('law encode_eval:')
    for q in P:
        w(f'  for {q}')
    w(f'  {{T.{X}_encode({OBJ}) == {RE} : O.Bits & B.Buf}}')
    w(f'def encode_eval({", ".join(A)}):')
    if small:
        w(f'  %Equal.sym(Array<U32>, Array.new(U32, 0n, 0), {ZT}, F.array__new(U32, 0n, 0)) :')
        w(f'    {{T.{X}_enc_put(T.{p}_putn(_, 0, {OBJ})) == {RE} : O.Bits & B.Buf}}')
        w(f'  %Equal.sym({PN}, O.put_bits_n({ZT}, 0, {OBJ}), (F.array__thaw(U32, OUT(T, K)), ({OBJ}, CO.NK(K))), {EV}) :')
        w(f'    {{T.{X}_enc_put(_) == {RE} : O.Bits & B.Buf}}')
        HL = (f'F.nat__le_lt_trans(U32.to_nat(CO.NK(K)), {N + 1}n, F.spec_common__pow2({KS}n), '
              f'CO.nk_le(K, {kb}n, {N}n, {{==}}, VR.rep_N(T, K, {N}n, rep), {{==}}), {{==}})')
        w(f'  %Equal.sym(U32, U32.and(CO.NK(K), 2147483647), CO.NK(K), VBE.and31(CO.NK(K), {KS}n, {{==}}, {HL})) :')
        w(f'    {{({OBJ}, O.out_done(_, F.array__thaw(U32, OUT(T, K)))) == {RE} : O.Bits & B.Buf}}')
        w('  {==}')
    else:
        CAP = 'U32.is_le(U32.add(U32.shrn(K, 5n), 1), F.u32__pow2u(dw))'
        w(f'  %Equal.sym(Array<U32> & U32, Array.size(U32, F.array__thaw(U32, T)), (F.array__thaw(U32, T), F.u32__pow2u(dw)), F.array__size_thaw(U32, dw, T, pfT)) :')
        w(f'    {{T.{X}_enc_sized(O.bsz_pick(K, _)) == {RE} : O.Bits & B.Buf}}')
        w(f'  %Equal.sym(Bool, {CAP}, True{{}}, CO.capT(K, dw, hdw, hcap)) :')
        w(f'    {{T.{X}_enc_sized(({OBJ}, O.pick(_, U32.add(U32.shrn(K, 3n), 1), 2147483648))) == {RE} : O.Bits & B.Buf}}')
        ZB = 'B.zeros(B.words_depth_u(VC.nwu(CO.NK(K))))'
        w(f'  %Equal.sym(Array<U32>, {ZB}, {ZT},')
        w(f'      Equal.trans(Array<U32>, {ZB}, Array.new(U32, CO.DOK(K), 0), {ZT},')
        w(f'        zeros_at(B.words_depth_u(VC.nwu(CO.NK(K))), CO.DOK(K), VD.wdu(VC.nwu(CO.NK(K))), CO.hDOK(K, {kb}n, {KO}n, {N}n, {{==}}, VR.rep_N(T, K, {N}n, rep), {{==}}, {{==}})),')
        w(f'        F.array__new(U32, CO.DOK(K), 0))) :')
        w(f'    {{T.{X}_enc_put(CO.NK(K), T.{p}_putn(_, 0, {OBJ})) == {RE} : O.Bits & B.Buf}}')
        w(f'  %Equal.sym({PN}, O.put_bits_n({ZT}, 0, {OBJ}), (F.array__thaw(U32, OUT(T, K)), ({OBJ}, CO.NK(K))), {EV}) :')
        w(f'    {{T.{X}_enc_put(CO.NK(K), _) == {RE} : O.Bits & B.Buf}}')
        w('  {==}')
    w('')
    w('# Those bytes are the spec/codec.bend encoding of the object\'s value.')
    w('law encode_spec:')
    for q in P:
        w(f'  for {q}')
    w('  Decoding.decodes(GS.' + X + '(), BY(T, K), VAL(T, K))')
    w(f'def encode_spec({", ".join(A)}):')
    w(f'  +c = cr({AS})')
    w('  %Equal.sym(F.array__Tree<U32>, F.array__freeze(U32, F.array__thaw(U32, T)), T, F.array__freeze_thaw(U32, T)) :')
    w(f'    Decoding.decodes(GS.{X}(), BY(T, K), S.BitsValue{{BK.btk(U32.to_nat(K), BK.bitsof(F.array__slots(U32, _)))}})')
    MOT = 'Codec.bytes(Codec.one(Bits.encoding(@D, List.append(&2, Bool, CO.BITS(T, K), [True{}])), None{}))'
    w(f'  %Equal.sym(Nat, List.length(&2, Bool, CO.BITS(T, K)), U32.to_nat(K), CO.cr3({DO}, T, K, c)) :')
    w('    {' + MOT.replace('@D', f'Nat.is_le(_, {N}n)') + ' == Some{BY(T, K)} : Maybe<&2, +List<U32>>}')
    w(f'  %Equal.sym(Bool, Nat.is_le(U32.to_nat(K), {N}n), True{{}}, VR.rep_N(T, K, {N}n, rep)) :')
    w('    {' + MOT.replace('@D', '_') + ' == Some{BY(T, K)} : Maybe<&2, +List<U32>>}')
    w(f'  %Equal.sym(+List<U32>, Bp.pack(List.append(&2, Bool, CO.BITS(T, K), [True{{}}])), BY(T, K), CO.cr2({DO}, T, K, c)) :')
    w('    {Codec.bytes(Codec.one(Some{_}, None{})) == Some{BY(T, K)} : Maybe<&2, +List<U32>>}')
    w('  {==}')
    return '\n'.join(L) + '\n'


def cont_names():
    import schema
    import generate as G
    import var_bitc as VBI
    names = schema.load(ROOT / 'codegen/fulu.yaml')
    g = G.Gen()
    for n, t in names.items():
        g.shape(t)
    return g, [VBI.BName(g, n, names[n]) for n in VBI.NAMES]


def cont_fname(x):
    import var_bitc as VBI
    return ROOT / f'proofs/obj/{"big_" if VBI.is_big(x) else ""}var_bitc_enc_{x.n}.bend'


def cont_module(g, x, src):
    import var_laws as VL
    import var_bitc as VBI
    n, FS, H, po, N, lp = x.n, x.FS, x.H, x.po, x.N, x.p
    assert po == 0 and FS == 4 * H
    vi = [f['kind'] for f in x.fields].index('bits')
    LIMN = VBI.spec_bits_lim(n, vi)
    assert LIMN in (f'{N}n', f'U32.to_nat({N})'), LIMN
    Tn = f'T.{n}'
    # the runtime shapes this proof follows
    assert f'def {n}_encode(o: {n}) -> {n} & B.Buf: {n}_enc_sized({n}_size(o))' in src
    assert f'def {lp}_valid(o: O.Bits) -> O.Bits & Bool: O.bits_ok(o, {N}, False{{}})' in src
    assert f'def {lp}_size(o: O.Bits) -> O.Bits & U32: O.bits_sizek(o)' in src
    assert f'def {lp}_putn(out: Array<U32>, +pos: U32, o: O.Bits) -> Array<U32> & (O.Bits & U32): O.put_bits_n(out, pos, o)' in src
    kb = lg(N + 8)
    KY = lg(32 + N)
    KO = lg(H + (N >> 5) + 1)
    PB = lg(N + 2)
    kb2 = lg(FS + N + 4)
    assert KO < 29 and kb < 32 and KY < 31 and PB <= 31 and kb2 < 32
    fixed = [f for f in x.fields if f['kind'] == 'fix']
    ks = [k for k in range(H) if k != po]
    WS = ', '.join(f'+w{k}: U32' for k in ks)
    WA = ', '.join(f'w{k}' for k in ks)

    def V(f):
        return '[' + ', '.join(f'w{f["k"] + j}' for j in range(f['ft'].W)) + ']'

    def fobj(f):
        return f['ft'].obj([f'w{f["k"] + j}' for j in range(f['ft'].W)])
    OBB = 'OB(T, K)'
    objs = [fobj(f) if f['kind'] == 'fix' else OBB for f in x.fields]
    OBJ = f'OBJE({WA}, T, K)'
    FIXOBJS = ', '.join(fobj(f) for f in fixed)
    NC = f'+K: U32, +hN: {{Nat.is_le(U32.to_nat(K), {N}n) == True{{}} : Bool}}'
    NCa = 'K, hN'
    ALLP = (f'{WS}, +dw: Nat, +T: FD.array__Tree<U32>, +K: U32,\n'
            '    +pfT: {FD.array__perfect(U32, dw, T) == True{} : Bool}, +hdw: {Nat.is_lt(dw, 31n) == True{} : Bool},\n'
            f'    +rep: BO.rep_bits(OB(T, K), S.BitList{{{LIMN}}}),\n'
            '    +hcap: {Nat.is_le(Nat.add(U32.to_nat(U32.shrn(K, 5n)), 1n), VB.pw(dw)) == True{} : Bool},\n'
            '    +hv: {O.bits_above_zero(U32.and(K, 31), VB.slot(T, VBT.QK(K))) == True{} : Bool}')
    ALLa = f'{WA}, dw, T, K, pfT, hdw, rep, hcap, hv'
    HN = f'VR.rep_N(T, K, {N}n, rep)'
    TD = lambda j: f'TD{j}({WA}, T, K)'  # noqa: E731
    OUT = TD(len(fixed))
    SO = f'FD.array__slots(U32, {OUT})'
    ST = 'FD.array__slots(U32, T)'
    SA = 'FD.array__slots(U32, OUTA(T, K))'
    hdr = []
    for f in x.fields:
        hdr += [f'w{f["k"] + j}' for j in range(f['ft'].W)] if f['kind'] == 'fix' else [str(FS)]
    HDRL = '[' + ', '.join(hdr) + ']'
    LT = 'List<&2, U32>'
    M = 'Maybe<&2, +List<U32>>'
    MP = 'Maybe<&2, +List<S.Part>>'
    q = 'VBT.QK(K)'
    L = list(VL.DEC_HEAD) + ['import ./venc.bend as VE', 'import ./venc2.bend as V2', 'import ./vbspec.bend as VZ', 'import ./vbytes.bend as VY',
                             'import ./vbitc.bend as VBC', 'import ./spec_bits.bend as FB', 'import ../../spec/bitfields.bend as Bits', 'import ../../spec/bit_packing.bend as Bp',
                             'import ./bitlist_pack.bend as BK', 'import ./bitlist_rep.bend as BO', 'import ./vbitenc.bend as VBT',
                             'import ./vbitdl.bend as DL', 'import ./vbitcore.bend as CO', 'import ./vbitcont.bend as CT', 'import ./vbitrep.bend as VR',
                             'import ./var_bits_enc_bw.bend as BW', 'import ../compact/reads.bend as RD', '',
                             '# GENERATED by codegen/var_bits_enc.py. Do not edit.',
                             f'# The encoder of {n} (fixed fields around the bit list {x.fields[vi]["name"]}, BitList[{N}]): for',
                             '# every object whose bit list O.Bits{thaw(T), K} represents a value (the root laws\' BO.rep_bits)',
                             '# and passes the runtime\'s checks (capacity, zero bits past K), the encoder returns the',
                             f'# object and B.Buf{{thaw(OUT), {FS} + K / 8 + 1}} (encode_eval), and those bytes are the',
                             '# spec/codec.bend encoding of the object\'s value (encode_spec).', '']
    w = L.append
    T0 = [f'def OB(+T: FD.array__Tree<U32>, +K: U32) -> O.Bits: O.Bits{{FD.array__thaw(U32, T), K}}',
          f'def OBJE({WS}, +T: FD.array__Tree<U32>, +K: U32) -> {Tn}: {Tn}{{' + ', '.join(objs) + '}',
          f'def SFS(+K: U32) -> U32: U32.add({FS}, CO.NK(K))',
          'def DO(+K: U32) -> Nat: B.words_depth(VC.nwu(SFS(K)))',
          f'def OUT1(+K: U32) -> FD.array__Tree<U32>: FD.array__upd(U32, DO(K), VC.ZT(DO(K)), {po}n, {FS})',
          f'def OUTA(+T: FD.array__Tree<U32>, +K: U32) -> FD.array__Tree<U32>: CT.OA(DO(K), OUT1(K), T, U32.add(0, {FS}), {H}n, K)',
          f'def TD0({WS}, +T: FD.array__Tree<U32>, +K: U32) -> FD.array__Tree<U32>: OUTA(T, K)']
    for j, f in enumerate(fixed):
        T0.append(f'def TD{j + 1}({WS}, +T: FD.array__Tree<U32>, +K: U32) -> FD.array__Tree<U32>: VF.updv({V(f)}, DO(K), {TD(j)}, {f["k"]}n)')
    w('\n'.join(T0))
    CF = '''  +j = VBT.JK(K)
  +b = VBT.BKk(K)
  +hj = FD.nat__le_lt_trans(j, 3n, 4n, RD.and_le(VBT.PDK(K), 3), {==})
  +hb = FD.nat__le_lt_trans(b, 7n, 8n, RD.and_le(K, 7), {==})
  +cf = BW.cfj(j, b, hj, hb)
  +cD = DL.p1(DL.TD(j), DL.CE(j, b), DL.p2(DL.TC(j, b), DL.CD(j, b), DL.p2(DL.TB(b), DL.CC(j, b), DL.p2(DL.TA(j, b), DL.CB(j, b), cf))))'''
    w(f"""
# The closed bounds, compared on VB.pw.
def hNk0() -> {{Nat.is_le(Nat.add({N}n, 8n), O.pow2n({kb}n)) == True{{}} : Bool}}:
  %VD.s_pow2_eq({kb}n) : {{Nat.is_le(Nat.add({N}n, 8n), _) == True{{}} : Bool}}
  {{==}}

def hNk2() -> {{Nat.is_le(Nat.add(Nat.add({FS}n, Nat.add({N}n, 1n)), 3n), O.pow2n({kb2}n)) == True{{}} : Bool}}:
  %VD.s_pow2_eq({kb2}n) : {{Nat.is_le(Nat.add(Nat.add({FS}n, Nat.add({N}n, 1n)), 3n), _) == True{{}} : Bool}}
  {{==}}

def hKk({NC}) -> VBT.HK(K, {kb}n):
  FD.nat__le_trans(Nat.add(U32.to_nat(K), 8n), Nat.add({N}n, 8n), O.pow2n({kb}n), Order.add_right(U32.to_nat(K), {N}n, 8n, hN), hNk0())

def eNK({NC}) -> {{Nat.is_le(U32.to_nat(CO.NK(K)), Nat.add({N}n, 1n)) == True{{}} : Bool}}:
  CO.nk_le(K, {kb}n, {N}n, {{==}}, hN, hNk0())

def eS({NC}) -> {{U32.to_nat(SFS(K)) == Nat.add({FS}n, U32.to_nat(CO.NK(K))) : Nat}}:
  A.add_le({FS}, CO.NK(K), {FS + N + 1}, FD.nat__le_trans(Nat.add({FS}n, U32.to_nat(CO.NK(K))), Nat.add({FS}n, Nat.add({N}n, 1n)), U32.to_nat({FS + N + 1}),
    Order.add_left({FS}n, U32.to_nat(CO.NK(K)), Nat.add({N}n, 1n), eNK({NCa})), {{==}}))

def padd({NC}) -> {{O.padd({FS}, CO.NK(K)) == SFS(K) : U32}}:
  VE.padd_ok({FS}, CO.NK(K), VE.winit(31n, VE.bits32({FS})), VE.winit(31n, VE.bits32(CO.NK(K))), {{==}},
    VE.small_pad(CO.NK(K), {PB}n, {{==}}, FD.nat__le_lt_trans(U32.to_nat(CO.NK(K)), Nat.add({N}n, 1n), FD.spec_common__pow2({PB}n), eNK({NCa}), {{==}})))

# The encoding's words: the header's {H}, then the bit list's q + 1.
def nwS({NC}) -> {{VC.NW(SFS(K)) == Nat.add({H}n, Nat.add({q}, 1n)) : Nat}}:
{CF}
  +e1 = Equal.trans(Nat, U32.to_nat(SFS(K)), Nat.add({FS}n, U32.to_nat(CO.NK(K))), Nat.add(A.quad(Nat.add({H}n, {q})), Nat.add(j, 1n)), eS({NCa}),
    Equal.trans(Nat, Nat.add({FS}n, U32.to_nat(CO.NK(K))), Nat.add(A.quad({H}n), Nat.add(A.quad({q}), Nat.add(j, 1n))), Nat.add(A.quad(Nat.add({H}n, {q})), Nat.add(j, 1n)),
      Equal.cong(Nat, Nat, z => Nat.add({FS}n, z), U32.to_nat(CO.NK(K)), Nat.add(A.quad({q}), Nat.add(j, 1n)), VBT.G4(K, {kb}n, {{==}}, hKk({NCa}), j, {{==}})),
      Equal.trans(Nat, Nat.add(A.quad({H}n), Nat.add(A.quad({q}), Nat.add(j, 1n))), Nat.add(Nat.add(A.quad({H}n), A.quad({q})), Nat.add(j, 1n)), Nat.add(A.quad(Nat.add({H}n, {q})), Nat.add(j, 1n)),
        Equal.sym(Nat, Nat.add(Nat.add(A.quad({H}n), A.quad({q})), Nat.add(j, 1n)), Nat.add(A.quad({H}n), Nat.add(A.quad({q}), Nat.add(j, 1n))), FD.nat__add_assoc(A.quad({H}n), A.quad({q}), Nat.add(j, 1n))),
        Equal.cong(Nat, Nat, z => Nat.add(z, Nat.add(j, 1n)), Nat.add(A.quad({H}n), A.quad({q})), A.quad(Nat.add({H}n, {q})), VF.quad_add({H}n, {q})))))
  +h3 = FD.logic__subst(Nat, z => {{Nat.is_le(Nat.add(z, 3n), O.pow2n({kb2}n)) == True{{}} : Bool}}, Nat.add({FS}n, U32.to_nat(CO.NK(K))), U32.to_nat(SFS(K)), Equal.sym(Nat, U32.to_nat(SFS(K)), Nat.add({FS}n, U32.to_nat(CO.NK(K))), eS({NCa})),
    FD.nat__le_trans(Nat.add(Nat.add({FS}n, U32.to_nat(CO.NK(K))), 3n), Nat.add(Nat.add({FS}n, Nat.add({N}n, 1n)), 3n), O.pow2n({kb2}n),
      Order.add_right(Nat.add({FS}n, U32.to_nat(CO.NK(K))), Nat.add({FS}n, Nat.add({N}n, 1n)), 3n, Order.add_left({FS}n, U32.to_nat(CO.NK(K)), Nat.add({N}n, 1n), eNK({NCa}))), hNk2()))
  +e2 = VBT.NWq(SFS(K), Nat.add({H}n, {q}), Nat.add(j, 1n), {kb2}n, {{==}}, h3, e1)
  Equal.trans(Nat, VC.NW(SFS(K)), Nat.add(Nat.add({H}n, {q}), VD.s_rng(2n, Nat.add(Nat.add(j, 1n), 3n))), Nat.add({H}n, Nat.add({q}, 1n)), e2,
    Equal.trans(Nat, Nat.add(Nat.add({H}n, {q}), VD.s_rng(2n, Nat.add(Nat.add(j, 1n), 3n))), Nat.add(Nat.add({H}n, {q}), 1n), Nat.add({H}n, Nat.add({q}, 1n)),
      Equal.cong(Nat, Nat, z => Nat.add(Nat.add({H}n, {q}), z), VD.s_rng(2n, Nat.add(Nat.add(j, 1n), 3n)), 1n, cD),
      FD.nat__add_assoc({H}n, {q}, 1n)))

# (N >> 5) + 1 words past the header fit 2^{KO}: computed on U32.
def e5le() -> {{Nat.is_le(Nat.add({H}n, Nat.add(VD.s_rng(5n, {N}n), 1n)), O.pow2n({KO}n)) == True{{}} : Bool}}:
  %VD.shrk(5n, {N}) : {{Nat.is_le(Nat.add({H}n, Nat.add(_, 1n)), O.pow2n({KO}n)) == True{{}} : Bool}}
  %VD.s_pow2_eq({KO}n) : {{Nat.is_le(Nat.add({H}n, Nat.add(U32.to_nat(U32.shrn({N}, 5n)), 1n)), _) == True{{}} : Bool}}
  {{==}}

def hwO({NC}) -> {{Nat.is_le(U32.to_nat(VC.nwu(SFS(K))), O.pow2n({KO}n)) == True{{}} : Bool}}:
  FD.logic__subst(Nat, z => {{Nat.is_le(z, O.pow2n({KO}n)) == True{{}} : Bool}}, Nat.add({H}n, Nat.add({q}, 1n)), U32.to_nat(VC.nwu(SFS(K))),
    Equal.sym(Nat, U32.to_nat(VC.nwu(SFS(K))), Nat.add({H}n, Nat.add({q}, 1n)), nwS({NCa})),
    FD.nat__le_trans(Nat.add({H}n, Nat.add({q}, 1n)), Nat.add({H}n, Nat.add(VD.s_rng(5n, {N}n), 1n)), O.pow2n({KO}n),
      Order.add_left({H}n, Nat.add({q}, 1n), Nat.add(VD.s_rng(5n, {N}n), 1n), CO.qle(K, {kb}n, {N}n, {{==}}, hN, hNk0())), e5le()))

def hDOK({NC}) -> {{Nat.is_le(DO(K), {KO}n) == True{{}} : Bool}}: VD.wd_min(VC.nwu(SFS(K)), {KO}n, hwO({NCa}))
def hDO29({NC}) -> {{Nat.is_lt(DO(K), 29n) == True{{}} : Bool}}: FD.nat__le_lt_trans(DO(K), {KO}n, 29n, hDOK({NCa}), {{==}})
def hDO31({NC}) -> {{Nat.is_lt(DO(K), 31n) == True{{}} : Bool}}: FD.nat__le_lt_trans(DO(K), {KO}n, 31n, hDOK({NCa}), {{==}})

# The room of the output tree: H + q + 1 <= 2^DO.
def hDq({NC}) -> {{Nat.is_le(Nat.add({H}n, Nat.add({q}, 1n)), VB.pw(DO(K))) == True{{}} : Bool}}:
  %Equal.sym(Nat, VB.pw(DO(K)), O.pow2n(DO(K)), VD.s_pow2_eq(DO(K))) : {{Nat.is_le(Nat.add({H}n, Nat.add({q}, 1n)), _) == True{{}} : Bool}}
  %nwS({NCa}) : {{Nat.is_le(_, O.pow2n(DO(K))) == True{{}} : Bool}}
  VD.wd_cover(VC.nwu(SFS(K)), {KO}n, {{==}}, hwO({NCa}))

# a <= H: a <= 2^DO.
def hbk(+a: Nat, {NC}, +ha: {{Nat.is_le(a, {H}n) == True{{}} : Bool}}) -> {{Nat.is_le(a, VB.pw(DO(K))) == True{{}} : Bool}}:
  FD.nat__le_trans(a, {H}n, VB.pw(DO(K)), ha, FD.nat__le_trans({H}n, Nat.add({H}n, Nat.add({q}, 1n)), VB.pw(DO(K)), Order.below_sum({H}n, Nat.add({q}, 1n)), hDq({NCa})))

def pf0(+K: U32) -> {{FD.array__perfect(U32, DO(K), VC.ZT(DO(K))) == True{{}} : Bool}}: FD.array__trep_perfect(U32, DO(K), 0)
def pf1(+K: U32) -> {{FD.array__perfect(U32, DO(K), OUT1(K)) == True{{}} : Bool}}: FD.array__upd_perfect(U32, DO(K), VC.ZT(DO(K)), {po}n, {FS}, pf0(K))

# The words of OUT1 past the header are zero.
def sl1({NC}, +k: Nat, +hk: {{Nat.is_le({H}n, k) == True{{}} : Bool}}) -> {{VB.slot(OUT1(K), k) == 0 : U32}}:
  %Equal.sym({LT}, FD.array__slots(U32, OUT1(K)), FD.spec_common__update(U32, FD.array__slots(U32, VC.ZT(DO(K))), {po}n, {FS}),
      FD.array__upd_slots(U32, DO(K), VC.ZT(DO(K)), {po}n, {FS}, FD.nat__lt_le_trans({po}n, {H}n, VB.pw(DO(K)), {{==}}, hbk({H}n, {NCa}, {{==}})), pf0(K))) :
    {{FD.flat__nthc(_, k) == 0 : U32}}
  Equal.trans(U32, FD.flat__nthc(FD.spec_common__update(U32, FD.array__slots(U32, VC.ZT(DO(K))), {po}n, {FS}), k), FD.flat__nthc(FD.array__slots(U32, VC.ZT(DO(K))), k), 0,
    FD.flat__nthc_other(FD.array__slots(U32, VC.ZT(DO(K))), {po}n, k, {FS}, FD.nat__is_eq_lt({po}n, k, FD.nat__lt_le_trans({po}n, {H}n, k, {{==}}, hk))),
    VBT.zslot(DO(K), k))
""")
    for j, f in enumerate(fixed):
        pass
    w('def pfD0(+T: FD.array__Tree<U32>, +K: U32) -> {FD.array__perfect(U32, DO(K), OUTA(T, K)) == True{} : Bool}:')
    w(f'  FD.array__upd_perfect(U32, DO(K), VBT.MT(DO(K), OUT1(K), T, {H}n, K), Nat.add({H}n, {q}), U32.or(VB.slot(VBT.MT(DO(K), OUT1(K), T, {H}n, K), Nat.add({H}n, {q})), VBT.DMK(U32.add(0, {FS}), K)),')
    w(f'    VB.mone_perfect(VC.NW(O.bits_nbytes(K)), 0n, {H}n, DO(K), OUT1(K), T, pf1(K)))')
    for j, f in enumerate(fixed):
        prev = f'pfD{j}(T, K)' if j == 0 else f'pfD{j}({WA}, T, K)'
        w(f'def pfD{j + 1}({WS}, +T: FD.array__Tree<U32>, +K: U32) -> {{FD.array__perfect(U32, DO(K), {TD(j + 1)}) == True{{}} : Bool}}:')
        w(f'  VF.updv_perfect({V(f)}, DO(K), {TD(j)}, {f["k"]}n, {prev})')

    def pfd(j):
        return 'pfD0(T, K)' if j == 0 else f'pfD{j}({WA}, T, K)'

    def hb(f):
        return f'hbk(Nat.add({f["ft"].W}n, {f["k"]}n), {NCa}, {{==}})'
    # ---- the bit list's writer ----
    w(f'''
def cra({ALLP}) -> CT.CRA(DO(K), OUT1(K), T, U32.add(0, {FS}), {H}n, K):
  (+wf, +r1) = rep
  +hN = {HN}
  +hz = VR.rep_hz(dw, T, K, {kb}n, {N}n, pfT, {{==}}, hN, hNk0(), CO.qs_sized(dw, K, {kb}n, {N}n, {{==}}, hN, hNk0(), hcap), wf)
  CT.enc_at(DO(K), dw, OUT1(K), T, U32.add(0, {FS}), {H}n, K, {kb}n, {KY}n, {N}n, pf1(K), pfT, hDO29({NCa}), hdw, {{==}}, {{==}},
    {{==}}, {{==}}, {{==}}, hN, hNk0(), {{==}}, hDq({NCa}), hcap, hz,
    sl1({NCa}, Nat.add({H}n, {q}), Order.below_sum({H}n, {q})),
    sl1({NCa}, Nat.add(VY.QL(O.bits_nbytes(K)), {H}n), FD.logic__subst(Nat, z => {{Nat.is_le({H}n, z) == True{{}} : Bool}}, Nat.add({H}n, VY.QL(O.bits_nbytes(K))), Nat.add(VY.QL(O.bits_nbytes(K)), {H}n),
      FD.nat__add_comm({H}n, VY.QL(O.bits_nbytes(K))), Order.below_sum({H}n, VY.QL(O.bits_nbytes(K))))))
''')
    # ---- size and put ----
    RS = f'({OBJ}, SFS(K))'
    w(f'''def size_eval({ALLP})
    -> {{{Tn}_size({OBJ}) == {RS} : {Tn} & U32}}:
  %Equal.sym(Array<U32> & U32, Array.size(U32, FD.array__thaw(U32, T)), (FD.array__thaw(U32, T), FD.u32__pow2u(dw)), FD.array__size_thaw(U32, dw, T, pfT)) :
    {{{Tn}_sz0({FIXOBJS}, {FS}, O.bsz_pick(K, _)) == {RS} : {Tn} & U32}}
  %Equal.sym(Bool, U32.is_le(U32.add(U32.shrn(K, 5n), 1), FD.u32__pow2u(dw)), True{{}}, CO.capT(K, dw, hdw, hcap)) :
    {{{Tn}_sz0({FIXOBJS}, {FS}, ({OBB}, O.pick(_, U32.add(U32.shrn(K, 3n), 1), 2147483648))) == {RS} : {Tn} & U32}}
  %Equal.sym(U32, O.padd({FS}, CO.NK(K)), SFS(K), padd(K, {HN})) : {{({OBJ}, _) == {RS} : {Tn} & U32}}
  {{==}}
''')
    RP = f'(FD.array__thaw(U32, {OUT}), ({OBJ}, SFS(K)))'
    TP = f'Array<U32> & ({Tn} & U32)'

    def puts(j, inner):
        t = inner
        for f in fixed[j:]:
            t = f'T.{f["ft"].p}_put({t}, U32.add(0, {f["c"]}), {fobj(f)})'
        return t
    w(f'def put_eval({ALLP})')
    w(f'    -> {{{Tn}_putn(FD.array__thaw(U32, VC.ZT(DO(K))), 0, {OBJ}) == {RP} : {TP}}}:')
    w(f'  +hN = {HN}')
    w(f'  +c = cra({ALLa})')
    w(f'  %Equal.sym(Array<U32>, Array.set(U32, FD.array__thaw(U32, VC.ZT(DO(K))), {po}, {FS}), FD.array__thaw(U32, OUT1(K)),')
    w(f'      VB.set_n(DO(K), VC.ZT(DO(K)), {po}, {po}n, {FS}, {{==}}, VB.lt32(DO(K), hDO31({NCa})), FD.nat__lt_le_trans({po}n, {H}n, VB.pw(DO(K)), {{==}}, hbk({H}n, {NCa}, {{==}})), pf0(K))) :')
    w(f'    {{{Tn}_pw0(0, {FIXOBJS}, T.{lp}_pvb({FS}, T.{lp}_pk(_, U32.add(0, {FS}), T.{lp}_valid({OBB})))) == {RP} : {TP}}}')
    w(f'  %Equal.sym(O.Bits & Bool, T.{lp}_valid({OBB}), ({OBB}, True{{}}),')
    w(f'      CT.valid_eval(dw, T, K, {kb}n, {N}n, {N}, pfT, hdw, {{==}}, {{==}}, hN, hNk0(), hcap, hv)) :')
    w(f'    {{{Tn}_pw0(0, {FIXOBJS}, T.{lp}_pvb({FS}, T.{lp}_pk(FD.array__thaw(U32, OUT1(K)), U32.add(0, {FS}), _))) == {RP} : {TP}}}')
    w(f'  %Equal.sym(Array<U32> & (O.Bits & U32), O.put_bits_n(FD.array__thaw(U32, OUT1(K)), U32.add(0, {FS}), {OBB}), (FD.array__thaw(U32, OUTA(T, K)), ({OBB}, CO.NK(K))),')
    w(f'      CT.cra1(DO(K), OUT1(K), T, U32.add(0, {FS}), {H}n, K, c)) :')
    w(f'    {{{Tn}_pw0(0, {FIXOBJS}, T.{lp}_pvb({FS}, _)) == {RP} : {TP}}}')
    w(f'  %Equal.sym(U32, O.padd({FS}, CO.NK(K)), SFS(K), padd({NCa})) :')
    w(f'    {{({puts(0, "FD.array__thaw(U32, OUTA(T, K))")}, ({OBJ}, _)) == {RP} : {TP}}}')
    for j, f in enumerate(fixed):
        ft = f['ft']
        cur = f'T.{ft.p}_put(FD.array__thaw(U32, {TD(j)}), U32.add(0, {f["c"]}), {fobj(f)})'
        ws = ', '.join(f'w{f["k"] + i}' for i in range(ft.W))
        w(f'  %Equal.sym(Array<U32>, {cur}, FD.array__thaw(U32, {TD(j + 1)}),')
        w(f'      VT.put_{ft.p}(DO(K), {TD(j)}, U32.add(0, {f["c"]}), {f["k"]}n, {{==}}, hDO29({NCa}), {pfd(j)}, {hb(f)}, {ws})) :')
        w(f'    {{({puts(j + 1, "_")}, ({OBJ}, SFS(K))) == {RP} : {TP}}}')
    w('  {==}')
    w('')
    w(f'def zeros_at(+du: U32, +k: Nat, +e: {{U32.to_nat(du) == k : Nat}}, +hk: {{Nat.is_le(k, {KO}n) == True{{}} : Bool}})')
    w('    -> {B.zeros(du) == Array.new(U32, k, 0) : Array<U32>}:')
    w('  match k:')
    for jj in range(KO + 1):
        w(f'    case {jj}n:')
        w(f'      %Equal.sym(U32, du, {jj}, FD.u32__injective(du, {jj}, e)) : {{B.zeros(_) == Array.new(U32, {jj}n, 0) : Array<U32>}}')
        w('      {==}')
    w(f'    case {KO + 1}n+p: Empty.absurd({{B.zeros(du) == Array.new(U32, {KO + 1}n+p, 0) : Array<U32>}}, FD.logic__false_true(hk))')
    RE = f'({OBJ}, B.Buf{{FD.array__thaw(U32, {OUT}), SFS(K)}})'
    TE = f'{Tn} & B.Buf'
    ps = ['+' + p_.strip() for p_ in re.split(r',\s*\+', ' '.join(ALLP.split()).lstrip('+'))]
    w('')
    w('# The encoder returns the object and the buffer of the output tree.')
    w('law encode_eval:')
    for p_ in ps:
        w(f'  for {p_}')
    w(f'  {{{Tn}_encode({OBJ}) == {RE} : {TE}}}')
    w(f'def encode_eval({ALLa}):')
    w(f'  +hN = {HN}')
    w(f'  %Equal.sym({Tn} & U32, {Tn}_size({OBJ}), {RS}, size_eval({ALLa})) :')
    w(f'    {{{Tn}_enc_sized(_) == {RE} : {TE}}}')
    w(f'  %Equal.sym(Array<U32>, B.zeros(B.words_depth_u(VC.nwu(SFS(K)))), FD.array__thaw(U32, VC.ZT(DO(K))),')
    w(f'      Equal.trans(Array<U32>, B.zeros(B.words_depth_u(VC.nwu(SFS(K)))), Array.new(U32, DO(K), 0), FD.array__thaw(U32, VC.ZT(DO(K))),')
    w(f'        zeros_at(B.words_depth_u(VC.nwu(SFS(K))), DO(K), VD.wdu(VC.nwu(SFS(K))), hDOK({NCa})), FD.array__new(U32, DO(K), 0))) :')
    w(f'    {{{Tn}_enc_put(SFS(K), {Tn}_putn(_, 0, {OBJ})) == {RE} : {TE}}}')
    w(f'  %Equal.sym({TP}, {Tn}_putn(FD.array__thaw(U32, VC.ZT(DO(K))), 0, {OBJ}), {RP}, put_eval({ALLa})) :')
    w(f'    {{{Tn}_enc_put(SFS(K), _) == {RE} : {TE}}}')
    w('  {==}')
    w('')
    w(f'''def hdstW({NC}) -> {{Nat.is_le(Nat.add(VC.NW(O.bits_nbytes(K)), {H}n), VB.pw(DO(K))) == True{{}} : Bool}}:
{CF}
  +cA = DL.p1(DL.TA(j, b), DL.CB(j, b), cf)
  +cB = DL.p1(DL.TB(b), DL.CC(j, b), DL.p2(DL.TA(j, b), DL.CB(j, b), cf))
  +eNW = Equal.trans(Nat, VC.NW(O.bits_nbytes(K)), Nat.add({q}, VD.s_rng(2n, Nat.add(Nat.add(j, VD.s_rng(3n, Nat.add(b, 7n))), 3n))), Nat.add({q}, BW.CWr(DL.RK(K))),
    VBT.FNWnb(K, {kb}n, {{==}}, hKk({NCa}), j, b, Nat.add(j, VD.s_rng(3n, Nat.add(b, 7n))), VD.s_rng(2n, Nat.add(Nat.add(j, VD.s_rng(3n, Nat.add(b, 7n))), 3n)), {{==}}, {{==}}, {{==}}, cB, {{==}}),
    Equal.cong(Nat, Nat, z => Nat.add({q}, z), VD.s_rng(2n, Nat.add(Nat.add(j, VD.s_rng(3n, Nat.add(b, 7n))), 3n)), BW.CWr(DL.RK(K)), cA))
  +h1 = FD.logic__subst(Nat, z => {{Nat.is_le(z, Nat.add({q}, 1n)) == True{{}} : Bool}}, Nat.add({q}, BW.CWr(DL.RK(K))), VC.NW(O.bits_nbytes(K)),
    Equal.sym(Nat, VC.NW(O.bits_nbytes(K)), Nat.add({q}, BW.CWr(DL.RK(K))), eNW), Order.add_left({q}, BW.CWr(DL.RK(K)), 1n, CO.cwle(DL.RK(K))))
  FD.nat__le_trans(Nat.add(VC.NW(O.bits_nbytes(K)), {H}n), Nat.add({H}n, Nat.add({q}, 1n)), VB.pw(DO(K)),
    FD.logic__subst(Nat, z => {{Nat.is_le(Nat.add(VC.NW(O.bits_nbytes(K)), {H}n), z) == True{{}} : Bool}}, Nat.add(Nat.add({q}, 1n), {H}n), Nat.add({H}n, Nat.add({q}, 1n)),
      FD.nat__add_comm(Nat.add({q}, 1n), {H}n), Order.add_right(VC.NW(O.bits_nbytes(K)), Nat.add({q}, 1n), {H}n, h1)), hDq({NCa}))

''')
    # ---- windows ----
    SP_ = f'{WS}, {NC}, +T: FD.array__Tree<U32>'
    SPa = f'{WA}, {NCa}, T'

    def win(m, p, j):
        return f'VF.WIN({m}, {p}, FD.array__slots(U32, {TD(j)}))'

    def peel_chain(m, p, lo_hi, stop, last_term, last_proof):
        steps = []
        for gg in range(len(fixed) - 1, stop - 1, -1):
            fg = fixed[gg]
            kind = lo_hi(fg)
            pr = f'V2.peel_{kind}({V(fg)}, DO(K), {TD(gg)}, {fg["k"]}n, {m}, {p}, {pfd(gg)}, {hb(fg)}, {{==}})'
            steps.append((win(m, p, gg + 1), win(m, p, gg), pr))
        out = last_proof
        for a_, b_, pr in reversed(steps):
            out = f'Equal.trans({LT}, {a_}, {b_}, {last_term}, {pr},\n    {out})'
        return out

    def rel(fg, k0):
        return 'lo' if fg['k'] + fg['ft'].W <= k0 else 'hi'
    # own segments
    MTK = f'VBT.MT(DO(K), OUT1(K), T, {H}n, K)'
    VV = f'U32.or(VB.slot({MTK}, Nat.add({H}n, {q})), VBT.DMK(U32.add(0, {FS}), K))'
    LM = f'VB.lm(VC.NW(O.bits_nbytes(K)), 0n, {H}n, FD.array__slots(U32, OUT1(K)), {ST})'
    for i, f in enumerate(x.fields):
        if f['kind'] == 'fix':
            j = fixed.index(f)
            k0, W0 = f['k'], f['ft'].W
            last = f'V2.own({V(f)}, DO(K), {TD(j)}, {k0}n, {pfd(j)}, {hb(f)})'
            body = peel_chain(f'{W0}n', f'{k0}n', lambda fg: rel(fg, k0), j + 1, V(f), last)
            w(f'def seg{i}({SP_}) -> {{{win(f"{W0}n", f"{k0}n", len(fixed))} == {V(f)} : {LT}}}:')
            w('  ' + body)
            w('')
        else:
            tail = (f'Equal.trans({LT}, VF.WIN(1n, {po}n, {SA}), VS.wtake(1n, FD.spec_common__update(U32, FD.array__slots(U32, {MTK}), Nat.add({H}n, {q}), {VV})), [{FS}],\n'
                    f'    Equal.cong({LT}, {LT}, z => VS.wtake(1n, z), {SA}, FD.spec_common__update(U32, FD.array__slots(U32, {MTK}), Nat.add({H}n, {q}), {VV}),\n'
                    f'      FD.array__upd_slots(U32, DO(K), {MTK}, Nat.add({H}n, {q}), {VV}, FD.nat__lt_le_trans(Nat.add({H}n, {q}), Nat.add({H}n, Nat.add({q}, 1n)), VB.pw(DO(K)), FD.nat__lt_add_left({q}, Nat.add({q}, 1n), {H}n, DL.lt_add1({q})), hDq({NCa})),\n'
                    f'        VB.mone_perfect(VC.NW(O.bits_nbytes(K)), 0n, {H}n, DO(K), OUT1(K), T, pf1(K)))),\n'
                    f'    Equal.trans({LT}, VS.wtake(1n, FD.spec_common__update(U32, FD.array__slots(U32, {MTK}), Nat.add({H}n, {q}), {VV})), VF.WIN(1n, {po}n, FD.array__slots(U32, {MTK})), [{FS}],\n'
                    f'      VF.take_upd(1n, FD.array__slots(U32, {MTK}), Nat.add({H}n, {q}), {VV}, FD.nat__le_trans(1n, {H}n, Nat.add({H}n, {q}), {{==}}, Order.below_sum({H}n, {q}))),\n'
                    f'      Equal.trans({LT}, VF.WIN(1n, {po}n, FD.array__slots(U32, {MTK})), VF.WIN(1n, {po}n, {LM}), [{FS}],\n'
                    f'        Equal.cong({LT}, {LT}, z => VF.WIN(1n, {po}n, z), FD.array__slots(U32, {MTK}), {LM}, VB.slots_mone(VC.NW(O.bits_nbytes(K)), 0n, {H}n, DO(K), OUT1(K), T, pf1(K), hdstW({NCa}))),\n'
                    f'        Equal.trans({LT}, VF.WIN(1n, {po}n, {LM}), VF.WIN(1n, {po}n, FD.array__slots(U32, OUT1(K))), [{FS}],\n'
                    f'          VF.lm_hi(VC.NW(O.bits_nbytes(K)), 0n, {H}n, 1n, {po}n, FD.array__slots(U32, OUT1(K)), {ST}, {{==}}),\n'
                    f'          V2.own([{FS}], DO(K), VC.ZT(DO(K)), {po}n, pf0(K), hbk(Nat.add(1n, {po}n), {NCa}, {{==}}))))))')
            body = peel_chain('1n', f'{po}n', lambda fg: rel(fg, po), 0, f'[{FS}]', tail)
            w(f'def seg{i}({SP_}) -> {{{win("1n", f"{po}n", len(fixed))} == [{FS}] : {LT}}}:')
            w('  ' + body)
            w('')
    # header window
    S3 = SO
    w(f'def hdr_eq({SP_}) -> {{{win(f"{H}n", "0n", len(fixed))} == {HDRL} : {LT}}}:')
    segs = []
    for i, f in enumerate(x.fields):
        segs.append((i, f['ft'].W if f['kind'] == 'fix' else 1, f['k'], V(f) if f['kind'] == 'fix' else f'[{FS}]'))
    R, s_ = H, 0
    pre = lambda t: t  # noqa: E731
    for idx, (i, Wd, k, Vs) in enumerate(segs):
        assert k == s_
        if idx < len(segs) - 1:
            w(f'  %Equal.sym({LT}, {win(f"Nat.add({Wd}n, {R - Wd}n)", f"{s_}n", len(fixed))}, VF.app({win(f"{Wd}n", f"{s_}n", len(fixed))}, {win(f"{R - Wd}n", f"Nat.add({s_}n, {Wd}n)", len(fixed))}),')
            w(f'      VF.win_split({Wd}n, {R - Wd}n, {s_}n, {S3})) :')
            w(f'    {{{pre("_")} == {HDRL} : {LT}}}')
            w(f'  %Equal.sym({LT}, {win(f"{Wd}n", f"{s_}n", len(fixed))}, {Vs}, seg{i}({SPa})) :')
            p0 = pre
            rest = win(f'{R - Wd}n', f'{s_ + Wd}n', len(fixed))
            w(f'    {{{p0(f"VF.app(_, {rest})")} == {HDRL} : {LT}}}')
            pre = (lambda p0, Vs: (lambda t: p0(f'VF.app({Vs}, {t})')))(p0, Vs)
            R, s_ = R - Wd, s_ + Wd
        else:
            assert R == Wd
            w(f'  %Equal.sym({LT}, {win(f"{Wd}n", f"{s_}n", len(fixed))}, {Vs}, seg{i}({SPa})) :')
            w(f'    {{{pre("_")} == {HDRL} : {LT}}}')
    w('  {==}')
    w('')
    # payload window: the fixed fields are below H
    MQ = f'Nat.add({q}, 1n)'
    body = peel_chain(MQ, f'{H}n', lambda fg: 'lo', 0, f'VF.WIN({MQ}, {H}n, {SA})', '{==}')
    w(f'def pay_eq({SP_}) -> {{{win(MQ, f"{H}n", len(fixed))} == VF.WIN({MQ}, {H}n, {SA}) : {LT}}}:')
    w('  ' + body)
    w('')
    Y = f'VS.bt(U32.to_nat(CO.NK(K)), F.limbs(VB.wdr({H}n, {SA})))'
    BY = f'VS.bt(U32.to_nat(SFS(K)), F.limbs({SO}))'
    RHS = f'List.append(&2, U32, F.limbs({HDRL}), {Y})'
    w(f'''# K / 8 + 1 <= 4 (q + 1).
def nkq({NC}) -> {{Nat.is_le(U32.to_nat(CO.NK(K)), A.quad(Nat.add({q}, 1n))) == True{{}} : Bool}}:
  +j = VBT.JK(K)
  +hj = RD.and_le(VBT.PDK(K), 3)
  %Equal.sym(Nat, U32.to_nat(CO.NK(K)), Nat.add(A.quad({q}), Nat.add(j, 1n)), VBT.G4(K, {kb}n, {{==}}, hKk({NCa}), j, {{==}})) : {{Nat.is_le(_, A.quad(Nat.add({q}, 1n))) == True{{}} : Bool}}
  %VF.quad_add({q}, 1n) : {{Nat.is_le(Nat.add(A.quad({q}), Nat.add(j, 1n)), _) == True{{}} : Bool}}
  Order.add_left(A.quad({q}), Nat.add(j, 1n), 4n, Order.add_right(j, 3n, 1n, hj))

# The output's bytes: the header's words, then the bit list's bytes.
def out_eq({ALLP})
    -> {{{BY} == {RHS} : +List<U32>}}:
  +hN = {HN}
  +hH = FD.logic__subst(Nat, z => {{Nat.is_le({H}n, z) == True{{}} : Bool}}, VB.pw(DO(K)), VB.len({SO}),
    Equal.sym(Nat, VB.len({SO}), VB.pw(DO(K)), FD.array__slots_length(U32, DO(K), {OUT}, pfD{len(fixed)}({WA}, T, K))), hbk({H}n, {NCa}, {{==}}))
  %Equal.sym(Nat, U32.to_nat(SFS(K)), Nat.add({FS}n, U32.to_nat(CO.NK(K))), eS({NCa})) : {{VS.bt(_, F.limbs({SO})) == {RHS} : +List<U32>}}
  %Equal.sym(+List<U32>, VS.bt(Nat.add(A.quad({H}n), U32.to_nat(CO.NK(K))), F.limbs({SO})),
      List.append(&2, U32, F.limbs(VS.wtake({H}n, {SO})), VS.bt(U32.to_nat(CO.NK(K)), F.limbs(VB.wdr({H}n, {SO})))), VY.bt_split({H}n, U32.to_nat(CO.NK(K)), {SO}, hH)) :
    {{_ == {RHS} : +List<U32>}}
  %Equal.sym({LT}, VF.WIN({H}n, 0n, {SO}), {HDRL}, hdr_eq({SPa})) :
    {{List.append(&2, U32, F.limbs(_), VS.bt(U32.to_nat(CO.NK(K)), F.limbs(VB.wdr({H}n, {SO})))) == {RHS} : +List<U32>}}
  %VY.bt_take({MQ}, U32.to_nat(CO.NK(K)), VB.wdr({H}n, {SO}), nkq({NCa})) :
    {{List.append(&2, U32, F.limbs({HDRL}), _) == {RHS} : +List<U32>}}
  %Equal.sym({LT}, VF.WIN({MQ}, {H}n, {SO}), VF.WIN({MQ}, {H}n, {SA}), pay_eq({SPa})) :
    {{List.append(&2, U32, F.limbs({HDRL}), VS.bt(U32.to_nat(CO.NK(K)), F.limbs(_))) == {RHS} : +List<U32>}}
  %Equal.sym(+List<U32>, VS.bt(U32.to_nat(CO.NK(K)), F.limbs(VF.WIN({MQ}, {H}n, {SA}))), {Y}, VY.bt_take({MQ}, U32.to_nat(CO.NK(K)), VB.wdr({H}n, {SA}), nkq({NCa}))) :
    {{List.append(&2, U32, F.limbs({HDRL}), _) == {RHS} : +List<U32>}}
  {{==}}
''')
    # ---- spec ----
    nodes = VL.field_nodes(g, x, lambda k: f'w{k}')
    VALB = f'S.BitsValue{{BO.bview({OBB})}}'
    vals, schs, parts = [], [], []
    for f, nd in zip(x.fields, nodes):
        if f['kind'] == 'fix':
            vals.append(nd['val'])
            schs.append(nd['sch'])
            parts.append(f'S.Fixed{{F.limbs([{", ".join(nd["words"])}])}}')
        else:
            vals.append(VALB)
            schs.append(f'S.BitList{{{LIMN}}}')
            parts.append(f'S.Variable{{{Y}}}')

    def items(i):
        return 'S.EmptyItems{}' if i == len(vals) else f'S.Items{{{vals[i]}, {items(i + 1)}}}'

    def chain(i):
        return 'S.End{}' if i == len(vals) else f'S.Chain{{{schs[i]}, {chain(i + 1)}}}'

    def cat(i):
        if i == len(vals):
            return '{==}'
        rest = '[' + ', '.join(parts[i + 1:]) + ']'
        if x.fields[i]['kind'] == 'fix':
            return (f'F.cat_fixed(Codec.parts({vals[i]}, {schs[i]}), F.limbs([{", ".join(nodes[i]["words"])}]), '
                    f'Codec.parts({items(i + 1)}, {chain(i + 1)}), {rest}, {nodes[i]["proof"]}, {cat(i + 1)})')
        return (f'VS.cat_var(Codec.parts({vals[i]}, {schs[i]}), {Y}, Codec.parts({items(i + 1)}, {chain(i + 1)}), {rest}, '
                f'bparts({ALLa}), {cat(i + 1)})')
    PRE = '[' + ', '.join('[' + ', '.join(nd['words']) + ']' for nd in nodes[:vi]) + ']'
    POST = '[' + ', '.join('[' + ', '.join(nd['words']) + ']' for nd in nodes[vi + 1:]) + ']'
    ENCR = f'List.append(&2, U32, List.append(&2, U32, F.flat({PRE}), List.append(&2, U32, N.digits(4n, VS.FSZ({PRE}, {POST})), F.flat({POST}))), {Y})'
    RHSk = f'Some{{{RHS}}}'
    MOT = 'Codec.bytes(Codec.one(Bits.encoding(@D, List.append(&2, Bool, @B, [True{}])), None{}))'
    BITS = 'CO.BITS(T, K)'
    w(f'''def VAL({WS}, +T: FD.array__Tree<U32>, +K: U32) -> S.Value: S.Sequence{{{items(0)}}}

# The bit list's spec part is the window's bytes.
def bparts({ALLP})
    -> {{Codec.parts({VALB}, S.BitList{{{LIMN}}}) == Some{{[S.Variable{{{Y}}}]}} : {MP}}}:
  +hN = {HN}
  +c = cra({ALLa})
  %Equal.sym(FD.array__Tree<U32>, FD.array__freeze(U32, FD.array__thaw(U32, T)), T, FD.array__freeze_thaw(U32, T)) :
    {{Codec.parts(S.BitsValue{{BK.btk(U32.to_nat(K), BK.bitsof(FD.array__slots(U32, _)))}}, S.BitList{{{LIMN}}}) == Some{{[S.Variable{{{Y}}}]}} : {MP}}}
  %Equal.sym(Nat, List.length(&2, Bool, {BITS}), U32.to_nat(K), CT.cra3(DO(K), OUT1(K), T, U32.add(0, {FS}), {H}n, K, c)) :
    {{Codec.one(Bits.encoding(Nat.is_le(_, {LIMN}), List.append(&2, Bool, {BITS}, [True{{}}])), None{{}}) == Some{{[S.Variable{{{Y}}}]}} : {MP}}}
  %Equal.sym(Bool, Nat.is_le(U32.to_nat(K), {LIMN}), True{{}}, hN) :
    {{Codec.one(Bits.encoding(_, List.append(&2, Bool, {BITS}, [True{{}}])), None{{}}) == Some{{[S.Variable{{{Y}}}]}} : {MP}}}
  %Equal.sym(+List<U32>, Bp.pack(List.append(&2, Bool, {BITS}, [True{{}}])), {Y}, CT.cra2(DO(K), OUT1(K), T, U32.add(0, {FS}), {H}n, K, c)) :
    {{Codec.one(Some{{_}}, None{{}}) == Some{{[S.Variable{{{Y}}}]}} : {MP}}}
  {{==}}

def fitY({ALLP})
    -> {{N.fits(4n, Nat.add(VS.FSZ({PRE}, {POST}), List.length(&2, U32, {Y}))) == True{{}} : Bool}}:
  +hN = {HN}
  VS.fits_mono(4n, Nat.add(VS.FSZ({PRE}, {POST}), List.length(&2, U32, {Y})), Nat.add({FS}n, Nat.add({N}n, 1n)),
    Order.add_left({FS}n, List.length(&2, U32, {Y}), Nat.add({N}n, 1n),
      FD.nat__le_trans(List.length(&2, U32, {Y}), U32.to_nat(CO.NK(K)), Nat.add({N}n, 1n), VZ.bt_len_le(U32.to_nat(CO.NK(K)), F.limbs(VB.wdr({H}n, {SA}))), eNK({NCa}))),
    {{==}})

# The spec encoding of the object's value: the header words' limbs, then the window's bytes.
def encE({ALLP})
    -> {{Codec.encoding_for_legal_type(Spec.{n}(), VAL({WA}, T, K)) == {RHSk} : {M}}}:
  %Equal.sym({MP}, Codec.parts({items(0)}, {chain(0)}), Some{{[{', '.join(parts)}]}},
      {cat(0)}) :
    {{Codec.bytes(Codec.aggregate(_, None{{}})) == {RHSk} : {M}}}
  %Equal.sym({M}, Layout.encoding(VS.fpv({PRE}, {Y}, {POST})), Some{{{ENCR}}}, VBC.enc_fpvb({PRE}, {Y}, {POST}, VZ.bd_btl(U32.to_nat(CO.NK(K)), VB.wdr({H}n, {SA})), fitY({ALLa}))) :
    {{Codec.bytes(Codec.one(_, None{{}})) == {RHSk} : {M}}}
  {{==}}
''')
    w('# The bytes the encoder writes are the spec/codec.bend encoding of the object\'s value.')
    w('law encode_spec:')
    for p_ in ps:
        w(f'  for {p_}')
    w(f'  Decoding.decodes(Spec.{n}(), {BY}, VAL({WA}, T, K))')
    w(f'def encode_spec({ALLa}):')
    w(f'  Equal.trans({M}, Codec.encoding_for_legal_type(Spec.{n}(), VAL({WA}, T, K)), {RHSk}, Some{{{BY}}},')
    w(f'    encE({ALLa}),')
    w(f'    Equal.cong(+List<U32>, {M}, z => Some{{z}}, {RHS}, {BY}, Equal.sym(+List<U32>, {BY}, {RHS}, out_eq({ALLa}))))')
    txt = '\n'.join(L) + '\n'
    if LIMN != f'{N}n':
        txt = re.sub(rf'\b{N}n\b', LIMN, txt)
    return txt


def main():
    no_big = '--no-big' in sys.argv
    out = {BW: bw_module(), PAD: pad_module()}
    src = RR.mono_text('generic')
    for X, N, p in names():
        out[ROOT / f'proofs/obj/var_bits_enc_{X}.bend'] = name_module(X, N, p, src)
    fsrc = RR.mono_text('fulu')
    g, xs = cont_names()
    import var_bitc as VBI
    for x in xs:
        if no_big and VBI.is_big(x):
            continue
        out[cont_fname(x)] = cont_module(g, x, fsrc)
    mine = [q for q in (ROOT / 'proofs/obj').glob('*.bend') if q.name.startswith(('var_bits_enc_', 'var_bitc_enc_', 'big_var_bitc_enc_'))]
    orphans = sorted(str(q.relative_to(ROOT)) for q in mine if q not in out and not (no_big and q.name.startswith('big_')))
    out = RR.rewire_out(out)
    if '--check' in sys.argv:
        stale = [str(p.relative_to(ROOT)) for p, t in out.items() if not p.exists() or p.read_text() != t] + orphans
        if stale:
            print('stale generated bit-list encoder laws: ' + ', '.join(stale))
            sys.exit(1)
        print('generated bit-list encoder laws are current')
        return
    for q in orphans:
        (ROOT / q).unlink()
    for p, t in out.items():
        p.write_text(t)
    print('wrote ' + ', '.join(str(p.relative_to(ROOT)) for p in out))


if __name__ == '__main__':
    main()
