#!/usr/bin/env python3
"""Byte-list names at a window at ANY byte offset: the byte-offset window
interface of proofs/obj/vua_win.bend for the names of codegen/var_bytes.py.

    python3 codegen/var_bytes_x.py [--check] [--no-big]

For a name X of var_bytes.py (fixed fields around one byte list), the module
proofs/obj/var_bytesx_X.bend exports, for a window [off, off + len) of
UA.BF(t, n) with off at byte position x (eo: to_nat off == x, hd: d < 28,
hw: x + len <= 4 2^d, pf: t perfect of depth d):

  CHKw(t, x, off, len), ok_evalw   the validator returns CHKw;
  OBJw(d, t, x, off, len), readw   when CHKw holds the reader returns OBJw: its
                                   fixed fields' words are the four-byte joins
                                   UR.RWN(t, x + c) (vua_fix / vbx_fix rdx_*),
                                   its byte vectors and byte list the copies
                                   UCT.CT (vbx.copy_into_at, vua_ct.copy_in_at);
  VALw(t, x, len), specw           the spec parts of VALw are the window's
                                   bytes UW.WX(t, x, len), one variable part;
  invw                             every value with those parts passes CHKw.

VALw's fixed fields are built from the words RWN(t, x + c) and its byte list
is the window's tail WX(t, 4 H + x, len - FS); specw splits the window with
UW.headWX. invw runs the spec inversion of var_bytes.py's rejection module
(written here without its whole-buffer part, as var_bytesx_X_inv.bend) and
reads the offset word back with UW.byteWX.

proofs/obj/vbx_fix.bend holds the rdx_* readers vua_fix.bend lacks;
proofs/obj/vbx.bend (hand-written) holds copy_into_at.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import generate as G  # noqa: E402
import schema  # noqa: E402
import var_laws as VL  # noqa: E402
import var_ua as VUA  # noqa: E402
import var_bytes as VBY  # noqa: E402
import spec_laws as SL  # noqa: E402
import var_bytes_nest as VBN  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
NAMES = ['ExecutionPayloadHeader']
# names nesting a covered name (codegen/var_bytes_nest.py), in dependency order
NEST = ['LightClientHeader']


def posx(c):
    """c + x as a chain of successors (a literal above 256 would parse as Nat.add)."""
    if c == 0:
        return 'x'
    s, r = '', c
    while r > 256:
        s += '256n+'
        r -= 256
    return f'{s}{r}n+x'


def rwn(c):
    return f'UR.RWN(t, {posx(c)})'


def vtx_types():
    src = (ROOT / 'proofs/obj/vua_fix.bend').read_text()
    return {ln.split('(')[0][len('def rdx_'):] for ln in src.splitlines() if ln.startswith('def rdx_')}


class XName(VBY.Name):
    def slot(self, k):
        return rwn(4 * k)

    def obj(self, f):
        if f['kind'] == 'fix':
            return f['ft'].obj(self.words(f))
        if f['kind'] == 'words':
            return f'O.Words{{FD.array__thaw(U32, UCT.CT(d, t, U32.add(off, {f["c"]}), {f["size"]}, {f["dz"]}n)), {f["size"]}}}'
        return f'O.Words{{FD.array__thaw(U32, UCT.CT(d, t, U32.add(off, {self.FS}), LL(len), DZ(len))), LL(len)}}'


def fname(x, part=''):
    return ROOT / f'proofs/obj/var_bytesx_{x.n}{part}.bend'


# ---- the readers vua_fix.bend lacks -----------------------------------------------------------

def fix_module(fts):
    have = vtx_types()
    L = ['import Base', 'import ../../src/buffer.bend as B', 'import ../../src/obj.bend as O', 'import ../../types/fulu_obj.bend as T',
         'import ../compact/found.bend as F', 'import ../compact/arith.bend as A', 'import ../../proofs/nat_order.bend as Order',
         'import ./vbuf.bend as VB', 'import ./vua.bend as UA', 'import ./vua_rd.bend as UR', 'import ./vua_fix.bend as VTX', '',
         '# GENERATED by codegen/var_bytes_x.py. Do not edit.',
         '# T.<p>_read at an offset off at ANY byte position x, for the fixed field types of',
         '# codegen/var_bytes_x.py that proofs/obj/vua_fix.bend lacks (as codegen/var_ua.py rdx_lemma).', '']
    for ft in fts:
        if ft.p in have:
            continue
        for ln in VUA.rdx_lemma(ft):
            ln = ln.replace('ltp(', 'VTX.ltp(')
            for kp in have:
                ln = ln.replace(f'rdx_{kp}(', f'VTX.rdx_{kp}(')
            L.append(ln)
        L.append('')
    return '\n'.join(L) + '\n'


def rdx_ref(ft):
    return f'VTX.rdx_{ft.p}' if ft.p in vtx_types() else f'XF.rdx_{ft.p}'


# ---- the spec inversion, without the whole-buffer part ----------------------------------------

def inv_text(x):
    L = [ln for ln in VBY.rej_text(x, pure=True) if not (ln.startswith('import ./') and (' as W' in ln or ' as DC' in ln))]
    L = [ln.replace('codegen/var_bytes.py', 'codegen/var_bytes_x.py') for ln in L]
    q = VL.REJ
    q = q[q.index('def q0('):q.index('def ec_sub(')]
    fsb = [x.FS & 255, (x.FS >> 8) & 255, (x.FS >> 16) & 255, (x.FS >> 24) & 255]
    for a, b in [('@FSL', '[' + ', '.join(map(str, fsb)) + ']'), ('@FS', str(x.FS)),
                 ('@B0', str(fsb[0])), ('@B1', str(fsb[1])), ('@B2', str(fsb[2])), ('@B3', str(fsb[3]))]:
        q = q.replace(a, b)
    L.append(q.rstrip() + '\n')
    L.append('# Every value whose spec parts are one variable part has its bytes in the checked shape.')
    L.append(f'def inv_p(+v: S.Value, +bs: +List<U32>, +e: {{Codec.parts(v, Spec.{x.n}()) == Some{{[S.Variable{{bs}}]}} : Maybe<&2, +List<S.Part>>}}) -> FACTS(bs):')
    L.append(f'  inv_v(v, bs, Equal.cong(Maybe<&2, +List<S.Part>>, Maybe<&2, +List<U32>>, z => Codec.bytes(z), Codec.parts(v, Spec.{x.n}()), Some{{[S.Variable{{bs}}]}}, e))')
    return '\n'.join(L) + '\n'


# ---- the window module --------------------------------------------------------------------------

HEAD = ['import Base', 'import ../../src/buffer.bend as B', 'import ../../src/obj.bend as O',
        'import ../../types/fulu_obj.bend as T', 'import ../../types/schema.bend as S', 'import ../../types/primitive.bend as P',
        'import ../compact/found.bend as FD', 'import ../compact/arith.bend as A', 'import ../../proofs/nat_order.bend as Order',
        'import ../../spec/primitives.bend as SP', 'import ../../spec/layout.bend as Layout', 'import ../../spec/codec.bend as Codec',
        'import ../../spec/nat_bytes.bend as N', 'import ../../spec/fulu_schemas.bend as Spec', 'import ./spec_fixed.bend as F',
        'import ./vspec.bend as VS', 'import ./vbuf.bend as VB', 'import ./vu32.bend as VU', 'import ./vcopy.bend as VC',
        'import ./vdepth.bend as VD', 'import ./vbytes.bend as VY', 'import ./vbspec.bend as VZ', 'import ./vbrt.bend as VRT',
        'import ./vua.bend as UA', 'import ./vua_rd.bend as UR', 'import ./vua_win.bend as UW', 'import ./vua_ct.bend as UCT',
        'import ./vua_fix.bend as VTX', 'import ./vbx_fix.bend as XF', 'import ./vbx.bend as VBX']

WHX = ('+eo: {U32.to_nat(off) == x : Nat}, +hd: {Nat.is_lt(d, 28n) == True{} : Bool},\n'
       '    +hw: {Nat.is_le(Nat.add(x, U32.to_nat(len)), A.quad(VB.pw(d))) == True{} : Bool}')
PF = '+pf: {FD.array__perfect(U32, d, t) == True{} : Bool}'
P4 = 'A.quad(VB.pw(d))'


def between(s, a, b):
    i = s.index(a)
    return s[i:s.index(b, i)]


def win_text(x):
    n, FS, H, po, cvar, LIM, KY, KZ = x.n, x.FS, x.H, x.po, x.cvar, x.LIM, x.KY, x.KZ
    Tn = f'T.{n}'
    HA = f'+ha: {{U32.is_le({FS}, len) == True{{}} : Bool}}'
    HX = '+hx: {BLW(LL(len)) == True{} : Bool}'
    MP = 'Maybe<&2, +List<S.Part>>'
    BF = 'UA.BF(t, n)'
    al = VBY.win_text(x)
    L = list(HEAD) + [f'import ./{fname(x, "_inv").name} as XI', '', '# GENERATED by codegen/var_bytes_x.py. Do not edit.',
                      f'# {n} at a window at ANY byte offset: the interface of proofs/obj/vua_win.bend',
                      '# (see the module docstring of codegen/var_bytes_x.py).', '']
    w = L.append
    w(between(al, 'def chk3(', '# The byte list\'s check'))
    w(f'''# The byte list's check: its length is at most the limit.
def BLW(+L: U32) -> Bool: U32.is_le(L, {LIM})
def LL(+len: U32) -> U32: U32.sub(len, {FS})
def SPOw(t: FD.array__Tree<U32>, +x: Nat) -> U32: {rwn(cvar).replace("UR.RWN(t, ", "UR.RWN(t, ")}

def CHKw(+t: FD.array__Tree<U32>, +x: Nat, +off: U32, +len: U32) -> Bool:
  chk3(U32.is_le({FS}, len), U32.is_eq(SPOw(t, x), {FS}), BLW(U32.sub(len, SPOw(t, x))))
''')
    w(between(al, 'def c1_id(', 'def winb('))
    w(f'''# c + x <= 4 2^d for c <= {FS}.
def hcx(+d: Nat, +x: Nat, +len: U32, +c: Nat, +hc: {{Nat.is_le(c, {FS}n) == True{{}} : Bool}}, +hw: {{Nat.is_le(Nat.add(x, U32.to_nat(len)), {P4}) == True{{}} : Bool}}, {HA})
    -> {{Nat.is_le(Nat.add(c, x), {P4}) == True{{}} : Bool}}:
  FD.nat__le_trans(Nat.add(c, x), Nat.add(U32.to_nat(len), x), {P4},
    Order.add_right(c, U32.to_nat(len), x, FD.nat__le_trans(c, {FS}n, U32.to_nat(len), hc, leFS(len, ha))),
    FD.logic__subst(Nat, z => {{Nat.is_le(z, {P4}) == True{{}} : Bool}}, Nat.add(x, U32.to_nat(len)), Nat.add(U32.to_nat(len), x), FD.nat__add_comm(x, U32.to_nat(len)), hw))

# The byte offset off + c of header byte c <= {FS} is at c + x.
def eoc(+d: Nat, +x: Nat, +off: U32, +len: U32, +c: U32, +hc: {{Nat.is_le(U32.to_nat(c), {FS}n) == True{{}} : Bool}}, {WHX}, {HA})
    -> {{U32.to_nat(U32.add(off, c)) == Nat.add(U32.to_nat(c), x) : Nat}}:
  VB.add_le_at(off, c, x, 2n+d, eo, FD.nat__lt_trans(d, 28n, 29n, hd, {{==}}), hcx(d, x, len, U32.to_nat(c), hc, hw, ha))

# Room for a field of s bytes at c + x, for c + s <= {FS}.
def roomc(+d: Nat, +x: Nat, +len: U32, +c: Nat, +s: Nat, +hc: {{Nat.is_le(Nat.add(c, s), {FS}n) == True{{}} : Bool}}, +hw: {{Nat.is_le(Nat.add(x, U32.to_nat(len)), {P4}) == True{{}} : Bool}}, {HA})
    -> {{Nat.is_le(Nat.add(Nat.add(c, x), s), {P4}) == True{{}} : Bool}}:
  UR.roomf(x, U32.to_nat(len), c, s, {P4}, hw, FD.nat__le_trans(Nat.add(c, s), {FS}n, U32.to_nat(len), hc, leFS(len, ha)))

# The byte list's window: ({FS} + x) + (len - {FS}) = x + len.
def hwv(+d: Nat, +x: Nat, +len: U32, +hw: {{Nat.is_le(Nat.add(x, U32.to_nat(len)), {P4}) == True{{}} : Bool}}, {HA})
    -> {{Nat.is_le(Nat.add(Nat.add(U32.to_nat({FS}), x), U32.to_nat(LL(len))), {P4}) == True{{}} : Bool}}:
  +e = Equal.trans(Nat, Nat.add(Nat.add({FS}n, x), U32.to_nat(LL(len))), Nat.add({FS}n, Nat.add(x, U32.to_nat(LL(len)))), Nat.add(x, Nat.add({FS}n, U32.to_nat(LL(len)))),
    FD.nat__add_assoc({FS}n, x, U32.to_nat(LL(len))), FD.lru_nat_algebra__add_swap({FS}n, x, U32.to_nat(LL(len))))
  %Equal.sym(Nat, Nat.add(Nat.add({FS}n, x), U32.to_nat(LL(len))), Nat.add(x, Nat.add({FS}n, U32.to_nat(LL(len)))), e) : {{Nat.is_le(_, {P4}) == True{{}} : Bool}}
  %Equal.sym(Nat, Nat.add({FS}n, U32.to_nat(LL(len))), U32.to_nat(len), enFS(len, ha)) : {{Nat.is_le(Nat.add(x, _), {P4}) == True{{}} : Bool}}
  hw

# ---- the validator ----------------------------------------------------------------------------

def rdoff(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, {WHX}, {PF}, {HA})
    -> {{B.read32({BF}, U32.add(off, {cvar})) == ({BF}, SPOw(t, x)) : B.Buf & U32}}:
  UR.rwx(d, t, n, U32.add(off, {cvar}), {posx(cvar)}, eoc(d, x, off, len, {cvar}, {{==}}, eo, hd, hw, ha), FD.nat__lt_trans(d, 28n, 31n, hd, {{==}}), pf,
    roomc(d, x, len, {cvar}n, 4n, {{==}}, hw, ha))

def okw_c0(+t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, +b: Bool)
    -> {{{Tn}_c0(b, {BF}, off, len, SPOw(t, x)) == ({BF}, chk3(True{{}}, b, BLW(U32.sub(len, SPOw(t, x))))) : B.Buf & Bool}}:
  match b:
    case False{{}}: {{==}}
    case True{{}}: c1_id(BLW(U32.sub(len, SPOw(t, x))), {BF}, off, len, SPOw(t, x))

def okw_len(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, {WHX}, {PF},
    +a: Bool, +ea: {{U32.is_le({FS}, len) == a : Bool}})
    -> {{{Tn}_ok_len(a, {BF}, off, len) == ({BF}, chk3(a, U32.is_eq(SPOw(t, x), {FS}), BLW(U32.sub(len, SPOw(t, x))))) : B.Buf & Bool}}:
  match a:
    case False{{}}: {{==}}
    case True{{}}:
      %Equal.sym(B.Buf & U32, B.read32({BF}, U32.add(off, {cvar})), ({BF}, SPOw(t, x)), rdoff(d, t, n, x, off, len, eo, hd, hw, pf, ea)) :
        {{{Tn}_v0(off, len, _) == ({BF}, chk3(True{{}}, U32.is_eq(SPOw(t, x), {FS}), BLW(U32.sub(len, SPOw(t, x))))) : B.Buf & Bool}}
      okw_c0(t, n, x, off, len, U32.is_eq(SPOw(t, x), {FS}))

# The validator on the window returns the buffer and CHKw(t, x, off, len).
def ok_evalw(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, {WHX}, {PF})
    -> {{{Tn}_ok({BF}, off, len) == ({BF}, CHKw(t, x, off, len)) : B.Buf & Bool}}:
  okw_len(d, t, n, x, off, len, eo, hd, hw, pf, U32.is_le({FS}, len), {{==}})

# ---- the byte list's bounds --------------------------------------------------------------------
''')
    w(between(al, 'def hLx(', '# The byte list\'s words lie in the buffer'))
    w(between(al, '# The storage of the byte list: depth', '# The byte list\'s storage: the masked copy'))
    w(f'''# The byte list's words lie in the buffer.
def hsv(+d: Nat, +x: Nat, +off: U32, +len: U32, {WHX}, {HA})
    -> {{Nat.is_le(Nat.add(VC.NW(LL(len)), VRT.QX(U32.add(off, {FS}))), VB.pw(d)) == True{{}} : Bool}}:
  UW.hsx(d, U32.add(off, {FS}), Nat.add(U32.to_nat({FS}), x), LL(len), eoc(d, x, off, len, {FS}, {{==}}, eo, hd, hw, ha), hd, hwv(d, x, len, hw, ha))

# The offset word, once checked, reads as {FS}.
def rdo(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, {WHX}, {PF}, {HA}, +epo: {{SPOw(t, x) == {FS} : U32}})
    -> {{B.read32({BF}, U32.add(off, {cvar})) == ({BF}, {FS}) : B.Buf & U32}}:
  %Equal.sym(B.Buf & U32, B.read32({BF}, U32.add(off, {cvar})), ({BF}, SPOw(t, x)), rdoff(d, t, n, x, off, len, eo, hd, hw, pf, ha)) :
    {{_ == ({BF}, {FS}) : B.Buf & U32}}
  %Equal.sym(U32, SPOw(t, x), {FS}, epo) : {{({BF}, _) == ({BF}, {FS}) : B.Buf & U32}}
  {{==}}
''')
    # ---- the reader ----
    leaves, OBJ = VBY.read_plan(x)
    OBJ = OBJ.replace('VF.BF(t, n)', BF)
    RHS = f'({BF}, OBJw(d, t, x, off, len))'
    TY = f'B.Buf & {Tn}'
    w(f'def OBJw(+d: Nat, +t: FD.array__Tree<U32>, +x: Nat, +off: U32, +len: U32) -> {Tn}: {OBJ}')
    w('')
    w('# The reader on the window, when the checks hold.')
    w(f'def rdw_go(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, {WHX}, {PF},')
    w(f'    {HA}, +epo: {{SPOw(t, x) == {FS} : U32}}, {HX})')
    w(f'    -> {{{Tn}_read({BF}, off, len) == {RHS} : {TY}}}:')
    w('  +hd30 = FD.nat__lt_trans(d, 28n, 30n, hd, {==})')
    w('  +hd31 = FD.nat__lt_trans(d, 28n, 31n, hd, {==})')

    def ecf(c):
        return f'eoc(d, x, off, len, {c}, {{==}}, eo, hd, hw, ha)'
    for ctx, call, val, kind, f in leaves:
        ctx = ctx.replace('VF.BF(t, n)', BF)
        call = call.replace('VF.BF(t, n)', BF)
        pat = ctx.replace('@', '_')
        if kind == 'off':
            w(f'  %Equal.sym(B.Buf & U32, {call}, ({BF}, {val}), rdo(d, t, n, x, off, len, eo, hd, hw, pf, ha, epo)) :')
        elif kind == 'fix':
            ft = f['ft']
            c = f['c']
            w(f'  %Equal.sym(B.Buf & {ft.rep()}, {call}, ({BF}, {val}),')
            w(f'      {rdx_ref(ft)}(d, t, n, U32.add(off, {c}), {posx(c)}, {ecf(c)}, hd30, pf, roomc(d, x, len, {c}n, {ft.size}n, {{==}}, hw, ha))) :')
        elif kind == 'words':
            c, z = f['c'], f['size']
            kw = VBY.kfit(31 + z)
            hs = (f'UW.hsx(d, U32.add(off, {c}), Nat.add(U32.to_nat({c}), x), {z}, {ecf(c)}, hd, '
                  f'roomc(d, x, len, U32.to_nat({c}), U32.to_nat({z}), {{==}}, hw, ha))')
            w(f'  %Equal.sym(B.Buf & O.Words, {call}, ({BF}, {val}),')
            w(f'      VBX.copy_into_at(d, t, n, U32.add(off, {c}), {z}, {f["dz"]}n, {kw}n, pf, hd31, {{==}}, {hs}, {{==}}, {{==}}, {{==}})) :')
        else:
            w(f'  %Equal.sym(B.Buf & O.Words, {call}, ({BF}, {val}),')
            w(f'      UCT.copy_in_at(d, t, n, U32.add(off, {FS}), LL(len), DZ(len), {KY}n, pf, hd31, hdz31(len, hx), ez(len, hx),')
            w(f'        hsv(d, x, off, len, eo, hd, hw, ha), hr(len, hx), {{==}}, hyL(len, hx))) :')
        w(f'    {{{pat} == {RHS} : {TY}}}')
    w('  {==}')
    w(f'''
# When the window's checks hold, the reader returns OBJw(d, t, x, off, len).
def readw(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, {WHX}, {PF},
    +hchk: {{CHKw(t, x, off, len) == True{{}} : Bool}})
    -> {{{Tn}_read({BF}, off, len) == {RHS} : {TY}}}:
  +a = U32.is_le({FS}, len)
  +b = U32.is_eq(SPOw(t, x), {FS})
  +c = BLW(U32.sub(len, SPOw(t, x)))
  +epo = FD.u32alg__eq_of(SPOw(t, x), {FS}, chk_b(a, b, c, hchk))
  rdw_go(d, t, n, x, off, len, eo, hd, hw, pf, chk_a(a, b, c, hchk), epo,
    FD.logic__subst(U32, z => {{BLW(U32.sub(len, z)) == True{{}} : Bool}}, SPOw(t, x), {FS}, epo, chk_c(a, b, c, hchk)))
''')
    L.extend(spec_part(x))
    L.extend(inv_part(x))
    return '\n'.join(L) + '\n'


def spec_part(x):
    n, FS, H, po, LIM = x.n, x.FS, x.H, x.po, x.LIM
    HA = f'+ha: {{U32.is_le({FS}, len) == True{{}} : Bool}}'
    HX = '+hx: {BLW(LL(len)) == True{} : Bool}'
    ITEMS, CHAIN, PL, CAT, PRE, POST, hdr, CDEFS = VBY.spec_items(x, 'Y', named=('XC', '+t: FD.array__Tree<U32>, +x: Nat, +Y: +List<U32>', 't, x, Y', '+t: FD.array__Tree<U32>, +x: Nat, +Y: +List<U32>', 't, x, Y'))
    CDEF = '\n'.join(CDEFS)
    HDR = '[' + ', '.join(hdr) + ']'
    hdrh = '[' + ', '.join(h if j != po else '_' for j, h in enumerate(hdr)) + ']'
    MP = 'Maybe<&2, +List<S.Part>>'
    M = 'Maybe<&2, +List<U32>>'
    ENC = f'List.append(&2, U32, F.limbs({HDR}), Y)'
    ENCR = f'List.append(&2, U32, List.append(&2, U32, F.flat({PRE}), List.append(&2, U32, N.digits(4n, VS.FSZ({PRE}, {POST})), F.flat({POST}))), Y)'
    YX = f'UW.WX(t, Nat.add(A.quad({H}n), x), U32.to_nat(LL(len)))'
    WX = 'UW.WX(t, x, U32.to_nat(len))'
    L4 = 'U32.to_nat(LL(len))'
    return [f'''
# ---- the spec side ------------------------------------------------------------------------------

# The value of the window's fixed words and byte list Y, through its named field suffixes.
{CDEF}
def XVw(+t: FD.array__Tree<U32>, +x: Nat, +Y: +List<U32>) -> S.Value: S.Sequence{{{ITEMS}}}

# Its spec parts: one variable part, the header's bytes (the offset is {FS}) and Y.
def encpw(+t: FD.array__Tree<U32>, +x: Nat, +Y: +List<U32>, +hdom: {{SP.bytes_domain(Y) == True{{}} : Bool}},
    +hlen: {{Nat.is_le(List.length(&2, U32, Y), {LIM}n) == True{{}} : Bool}})
    -> {{Codec.parts(XVw(t, x, Y), Spec.{n}()) == Some{{[S.Variable{{{ENC}}}]}} : {MP}}}:
  +fit = VS.fits_mono(4n, Nat.add(VS.FSZ({PRE}, {POST}), List.length(&2, U32, Y)), Nat.add({FS}n, {LIM}n),
    Order.add_left({FS}n, List.length(&2, U32, Y), {LIM}n, hlen), {{==}})
  %Equal.sym({MP}, Codec.parts({ITEMS}, {CHAIN}), Some{{{PL}}},
      {CAT}) :
    {{Codec.aggregate(_, None{{}}) == Some{{[S.Variable{{{ENC}}}]}} : {MP}}}
  %Equal.sym({M}, Layout.encoding(VS.fpv({PRE}, Y, {POST})), Some{{{ENCR}}}, VZ.enc_fpvb({PRE}, Y, {POST}, hdom, fit)) :
    {{Codec.one(_, None{{}}) == Some{{[S.Variable{{{ENC}}}]}} : {MP}}}
  {{==}}

# The byte list's value: the window's bytes after the header.
def VALw(+t: FD.array__Tree<U32>, +x: Nat, +len: U32) -> S.Value: XVw(t, x, {YX})

# The window is the header's words and the byte list's bytes.
def hwH(+d: Nat, +x: Nat, +len: U32, +hw: {{Nat.is_le(Nat.add(x, U32.to_nat(len)), A.quad(VB.pw(d))) == True{{}} : Bool}}, {HA})
    -> {{Nat.is_le(Nat.add(x, Nat.add(A.quad({H}n), {L4})), A.quad(VB.pw(d))) == True{{}} : Bool}}:
  %Equal.sym(Nat, Nat.add({FS}n, U32.to_nat(LL(len))), U32.to_nat(len), enFS(len, ha)) : {{Nat.is_le(Nat.add(x, _), A.quad(VB.pw(d))) == True{{}} : Bool}}
  hw

def hwY(+d: Nat, +x: Nat, +len: U32, +hw: {{Nat.is_le(Nat.add(x, U32.to_nat(len)), A.quad(VB.pw(d))) == True{{}} : Bool}}, {HA})
    -> {{Nat.is_le(Nat.add(Nat.add(A.quad({H}n), x), {L4}), A.quad(VB.pw(d))) == True{{}} : Bool}}:
  %Equal.sym(Nat, Nat.add(Nat.add(A.quad({H}n), x), {L4}), Nat.add(x, Nat.add(A.quad({H}n), {L4})), Equal.trans(Nat, Nat.add(Nat.add(A.quad({H}n), x), {L4}), Nat.add(A.quad({H}n), Nat.add(x, {L4})), Nat.add(x, Nat.add(A.quad({H}n), {L4})),
    FD.nat__add_assoc(A.quad({H}n), x, {L4}), FD.lru_nat_algebra__add_swap(A.quad({H}n), x, {L4}))) : {{Nat.is_le(_, A.quad(VB.pw(d))) == True{{}} : Bool}}
  hwH(d, x, len, hw, ha)

def len_y(+d: Nat, +t: FD.array__Tree<U32>, +x: Nat, +len: U32, {PF}, +hw: {{Nat.is_le(Nat.add(x, U32.to_nat(len)), A.quad(VB.pw(d))) == True{{}} : Bool}}, {HA}, {HX})
    -> {{Nat.is_le(List.length(&2, U32, {YX}), {LIM}n) == True{{}} : Bool}}:
  %Equal.sym(Nat, List.length(&2, U32, {YX}), {L4}, UW.lenWX(d, t, Nat.add(A.quad({H}n), x), {L4}, pf, hwY(d, x, len, hw, ha))) : {{Nat.is_le(_, {LIM}n) == True{{}} : Bool}}
  hLx(len, hx)

def bytesw(+d: Nat, +t: FD.array__Tree<U32>, +x: Nat, +len: U32, {PF},
    +hw: {{Nat.is_le(Nat.add(x, U32.to_nat(len)), A.quad(VB.pw(d))) == True{{}} : Bool}}, {HA}, +epo: {{SPOw(t, x) == {FS} : U32}})
    -> {{List.append(&2, U32, F.limbs({HDR}), {YX}) == {WX} : +List<U32>}}:
  %enFS(len, ha) : {{List.append(&2, U32, F.limbs({HDR}), {YX}) == UW.WX(t, x, _) : +List<U32>}}
  %Equal.sym(+List<U32>, UW.WX(t, x, Nat.add(A.quad({H}n), {L4})), List.append(&2, U32, F.limbs(UR.RWS({H}n, t, x)), {YX}),
      UW.headWX(d, t, x, {H}n, {L4}, pf, hwH(d, x, len, hw, ha))) :
    {{List.append(&2, U32, F.limbs({HDR}), {YX}) == _ : +List<U32>}}
  %epo : {{List.append(&2, U32, F.limbs({hdrh}), {YX}) == List.append(&2, U32, F.limbs(UR.RWS({H}n, t, x)), {YX}) : +List<U32>}}
  {{==}}

def specw_go(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +len: U32, {PF},
    +hw: {{Nat.is_le(Nat.add(x, U32.to_nat(len)), A.quad(VB.pw(d))) == True{{}} : Bool}}, {HA}, +epo: {{SPOw(t, x) == {FS} : U32}}, {HX})
    -> {{Codec.parts(VALw(t, x, len), Spec.{n}()) == Some{{[S.Variable{{{WX}}}]}} : {MP}}}:
  %bytesw(d, t, x, len, pf, hw, ha, epo) :
    {{Codec.parts(VALw(t, x, len), Spec.{n}()) == Some{{[S.Variable{{_}}]}} : {MP}}}
  encpw(t, x, {YX}, UW.domWX(t, Nat.add(A.quad({H}n), x), {L4}), len_y(d, t, x, len, pf, hw, ha, hx))

# When the window's checks hold, the spec parts of VALw are its bytes, as one variable part.
def specw(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, {WHX}, {PF},
    +hchk: {{CHKw(t, x, off, len) == True{{}} : Bool}})
    -> {{Codec.parts(VALw(t, x, len), Spec.{n}()) == Some{{[S.Variable{{{WX}}}]}} : {MP}}}:
  +a = U32.is_le({FS}, len)
  +b = U32.is_eq(SPOw(t, x), {FS})
  +c = BLW(U32.sub(len, SPOw(t, x)))
  +epo = FD.u32alg__eq_of(SPOw(t, x), {FS}, chk_b(a, b, c, hchk))
  specw_go(d, t, n, x, len, pf, hw, chk_a(a, b, c, hchk), epo,
    FD.logic__subst(U32, z => {{BLW(U32.sub(len, z)) == True{{}} : Bool}}, SPOw(t, x), {FS}, epo, chk_c(a, b, c, hchk)))
''']


def inv_part(x):
    n, FS, H, po, cvar, LIM = x.n, x.FS, x.H, x.po, x.cvar, x.LIM
    R = FS - cvar - 4
    fsb = [FS & 255, (FS >> 8) & 255, (FS >> 16) & 255, (FS >> 24) & 255]
    FSL = '[' + ', '.join(map(str, fsb)) + ']'
    WX = 'UW.WX(t, x, U32.to_nat(len))'
    MP = 'Maybe<&2, +List<S.Part>>'
    return [f'''
# ---- every value whose spec parts are the window's bytes passes the checks ----------------------

def ek_sub(+n: U32, +k: Nat, +en: {{U32.to_nat(n) == Nat.add({FS}n, k) : Nat}}) -> {{U32.to_nat(LL(n)) == k : Nat}}:
  +le = FD.logic__subst(Nat, z => {{Nat.is_le({FS}n, z) == True{{}} : Bool}}, Nat.add({FS}n, k), U32.to_nat(n), Equal.sym(Nat, U32.to_nat(n), Nat.add({FS}n, k), en), Order.below_sum({FS}n, k))
  %Equal.sym(Nat, U32.to_nat(LL(n)), Nat.sub(U32.to_nat(n), {FS}n), FD.u32__sub_nat(n, {FS}, le)) : {{_ == k : Nat}}
  %Equal.sym(Nat, U32.to_nat(n), Nat.add({FS}n, k), en) : {{Nat.sub(_, {FS}n) == k : Nat}}
  FD.nat__add_sub_cancel({FS}n, k)

def chk_truew(+t: FD.array__Tree<U32>, +x: Nat, +off: U32, +len: U32, +k: Nat, +en: {{U32.to_nat(len) == Nat.add({FS}n, k) : Nat}},
    +hk: {{Nat.is_le(k, {LIM}n) == True{{}} : Bool}}, +epo: {{SPOw(t, x) == {FS} : U32}}) -> {{CHKw(t, x, off, len) == True{{}} : Bool}}:
  +le = FD.logic__subst(Nat, z => {{Nat.is_le({FS}n, z) == True{{}} : Bool}}, Nat.add({FS}n, k), U32.to_nat(len), Equal.sym(Nat, U32.to_nat(len), Nat.add({FS}n, k), en), Order.below_sum({FS}n, k))
  +hL = FD.logic__subst(Nat, z => {{Nat.is_le(z, {LIM}n) == True{{}} : Bool}}, k, U32.to_nat(LL(len)), Equal.sym(Nat, U32.to_nat(LL(len)), k, ek_sub(len, k, en)), hk)
  %Equal.sym(Bool, U32.is_le({FS}, len), True{{}}, FD.logic__subst(Bool, z => {{z == True{{}} : Bool}}, Nat.is_le({FS}n, U32.to_nat(len)), U32.is_le({FS}, len), Equal.sym(Bool, U32.is_le({FS}, len), Nat.is_le({FS}n, U32.to_nat(len)), VU.le_u32({FS}, len)), le)) :
    {{chk3(_, U32.is_eq(SPOw(t, x), {FS}), BLW(U32.sub(len, SPOw(t, x)))) == True{{}} : Bool}}
  %Equal.sym(U32, SPOw(t, x), {FS}, epo) : {{chk3(True{{}}, U32.is_eq(_, {FS}), BLW(U32.sub(len, _))) == True{{}} : Bool}}
  FD.logic__subst(Bool, z => {{z == True{{}} : Bool}}, Nat.is_le(U32.to_nat(LL(len)), U32.to_nat({LIM})), U32.is_le(LL(len), {LIM}), Equal.sym(Bool, U32.is_le(LL(len), {LIM}), Nat.is_le(U32.to_nat(LL(len)), U32.to_nat({LIM})), VU.le_u32(LL(len), {LIM})), hL)

# The four bytes at the window's offset field are the limbs of its offset word.
def byteP(+d: Nat, +t: FD.array__Tree<U32>, +x: Nat, +len: U32, +k: Nat, +en: {{U32.to_nat(len) == Nat.add({FS}n, k) : Nat}}, {PF},
    +hw: {{Nat.is_le(Nat.add(x, U32.to_nat(len)), A.quad(VB.pw(d))) == True{{}} : Bool}})
    -> {{VS.bt(4n, VS.bdr({cvar}n, {WX})) == F.limbs([SPOw(t, x)]) : +List<U32>}}:
  +hw2 = FD.logic__subst(Nat, z => {{Nat.is_le(Nat.add(x, z), A.quad(VB.pw(d))) == True{{}} : Bool}}, U32.to_nat(len), Nat.add({cvar}n, 4n+Nat.add({R}n, k)), en, hw)
  %Equal.sym(Nat, U32.to_nat(len), Nat.add({cvar}n, 4n+Nat.add({R}n, k)), en) : {{VS.bt(4n, VS.bdr({cvar}n, UW.WX(t, x, _))) == F.limbs([SPOw(t, x)]) : +List<U32>}}
  UW.byteWX(d, t, x, {cvar}n, Nat.add({R}n, k), pf, hw2)

def inv_facts(+d: Nat, +t: FD.array__Tree<U32>, +x: Nat, +off: U32, +len: U32, {PF},
    +hw: {{Nat.is_le(Nat.add(x, U32.to_nat(len)), A.quad(VB.pw(d))) == True{{}} : Bool}}, facts: XI.FACTS({WX}))
    -> {{CHKw(t, x, off, len) == True{{}} : Bool}}:
  (+hb, ex) = facts
  (+k, +pr) = ex
  (+hlen, +hk) = pr
  +en = Equal.trans(Nat, U32.to_nat(len), List.length(&2, U32, {WX}), Nat.add({FS}n, k), Equal.sym(Nat, List.length(&2, U32, {WX}), U32.to_nat(len), UW.lenWX(d, t, x, U32.to_nat(len), pf, hw)), hlen)
  +epo = XI.wordFS(SPOw(t, x), Equal.trans(+List<U32>, F.limbs([SPOw(t, x)]), VS.bt(4n, VS.bdr({cvar}n, {WX})), {FSL},
    Equal.sym(+List<U32>, VS.bt(4n, VS.bdr({cvar}n, {WX})), F.limbs([SPOw(t, x)]), byteP(d, t, x, len, k, en, pf, hw)), hb))
  chk_truew(t, x, off, len, k, en, hk, epo)

# Every value whose spec parts are the window's bytes passes the checks.
def invw(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, {WHX}, {PF},
    +v: S.Value, +e: {{Codec.parts(v, Spec.{n}()) == Some{{[S.Variable{{{WX}}}]}} : {MP}}})
    -> {{CHKw(t, x, off, len) == True{{}} : Bool}}:
  inv_facts(d, t, x, off, len, pf, hw, XI.inv_p(v, {WX}, e))
''']


# ---- names nesting a covered name ---------------------------------------------------------------

class XNName(VBN.NName):
    def slot(self, k):
        return rwn(4 * k)

    @property
    def JX(self):
        return posx(self.FS)

    def yobj(self):
        return f'YW.OBJw(d, t, {self.JX}, U32.add(off, {self.FS}), LL(len))'

    def obj(self, f):
        if f['kind'] == 'fix':
            o = f['ft'].obj(self.words(f))
            return f'O.BSome{{{o}, O.BNone{{}}}}' if f['box'] else o
        if f['kind'] == 'words':
            return XName.obj(self, f)
        if f['kind'] == 'var':
            o = self.yobj()
            return f'O.BSome{{{o}, O.BNone{{}}}}' if f['box'] else o
        raise VBY.Skip('field kind ' + f['kind'])


def xn_inv_text(x):
    drop = (' as W', ' as DC', ' as YW', ' as YR')
    L = [ln for ln in VBN.rej_text(x, pure=True) if not (ln.startswith('import ./') and ln.endswith(drop))]
    L = [ln.replace('codegen/var_bytes_nest.py', 'codegen/var_bytes_x.py') for ln in L]
    q = VL.REJ
    q = q[q.index('def q0('):q.index('def ec_sub(')]
    fsb = [x.FS & 255, (x.FS >> 8) & 255, (x.FS >> 16) & 255, (x.FS >> 24) & 255]
    for a, b in [('@FSL', '[' + ', '.join(map(str, fsb)) + ']'), ('@FS', str(x.FS)),
                 ('@B0', str(fsb[0])), ('@B1', str(fsb[1])), ('@B2', str(fsb[2])), ('@B3', str(fsb[3]))]:
        q = q.replace(a, b)
    L.append(q.rstrip() + '\n')
    L.append('# Every value whose spec parts are one variable part has its bytes in the checked shape.')
    L.append(f'def inv_p(+v: S.Value, +bs: +List<U32>, +e: {{Codec.parts(v, Spec.{x.n}()) == Some{{[S.Variable{{bs}}]}} : Maybe<&2, +List<S.Part>>}}) -> FACTS(bs):')
    L.append(f'  inv_v(v, bs, Equal.cong(Maybe<&2, +List<S.Part>>, Maybe<&2, +List<U32>>, z => Codec.bytes(z), Codec.parts(v, Spec.{x.n}()), Some{{[S.Variable{{bs}}]}}, e))')
    return '\n'.join(L) + '\n'


def xn_win_text(x):
    n, FS, H, po, cvar, Y, JX = x.n, x.FS, x.H, x.po, x.cvar, x.Y, x.JX
    Tn = f'T.{n}'
    HA = f'+ha: {{U32.is_le({FS}, len) == True{{}} : Bool}}'
    HW = f'+hw: {{Nat.is_le(Nat.add(x, U32.to_nat(len)), {P4}) == True{{}} : Bool}}'
    MP = 'Maybe<&2, +List<S.Part>>'
    M = 'Maybe<&2, +List<U32>>'
    BF = 'UA.BF(t, n)'
    yok = f'T.{Y}_bx_ok' if x.var['box'] else f'T.{Y}_ok'
    YCHK = f'YW.CHKw(t, {JX}, U32.add(off, {FS}), LL(len))'
    al = VBN.win_text(x)
    L = list(HEAD) + ['import ./vbsize.bend as VBZ', 'import ./dk.bend as DK', f'import ./{fname(type("X", (), {"n": Y})).name} as YW', f'import ./{fname(x, "_inv").name} as XI', '',
                      '# GENERATED by codegen/var_bytes_x.py. Do not edit.',
                      f'# {n} at a window at ANY byte offset: the interface of proofs/obj/vua_win.bend, on',
                      f'# {Y}\'s at the window (off + {FS}, len - {FS}) (see codegen/var_bytes_x.py).', '']
    w = L.append
    w(between(al, 'def chk3(', 'def LL('))
    w(f'''def LL(+len: U32) -> U32: U32.sub(len, {FS})
def SPOw(t: FD.array__Tree<U32>, +x: Nat) -> U32: {rwn(cvar)}

# The checks: the size, the offset, and {Y}'s checks on the window after the header.
def CHKw(+t: FD.array__Tree<U32>, +x: Nat, +off: U32, +len: U32) -> Bool:
  chk3(U32.is_le({FS}, len), U32.is_eq(SPOw(t, x), {FS}), {YCHK})

''')
    w(between(al, 'def c1_id(', 'def winb('))
    w(f'''def hcx(+d: Nat, +x: Nat, +len: U32, +c: Nat, +hc: {{Nat.is_le(c, {FS}n) == True{{}} : Bool}}, {HW}, {HA})
    -> {{Nat.is_le(Nat.add(c, x), {P4}) == True{{}} : Bool}}:
  FD.nat__le_trans(Nat.add(c, x), Nat.add(U32.to_nat(len), x), {P4},
    Order.add_right(c, U32.to_nat(len), x, FD.nat__le_trans(c, {FS}n, U32.to_nat(len), hc, leFS(len, ha))),
    FD.logic__subst(Nat, z => {{Nat.is_le(z, {P4}) == True{{}} : Bool}}, Nat.add(x, U32.to_nat(len)), Nat.add(U32.to_nat(len), x), FD.nat__add_comm(x, U32.to_nat(len)), hw))

# The byte offset off + c of header byte c <= {FS} is at c + x.
def eoc(+d: Nat, +x: Nat, +off: U32, +len: U32, +c: U32, +hc: {{Nat.is_le(U32.to_nat(c), {FS}n) == True{{}} : Bool}}, {WHX}, {HA})
    -> {{U32.to_nat(U32.add(off, c)) == Nat.add(U32.to_nat(c), x) : Nat}}:
  VB.add_le_at(off, c, x, 2n+d, eo, FD.nat__lt_trans(d, 28n, 29n, hd, {{==}}), hcx(d, x, len, U32.to_nat(c), hc, hw, ha))

def roomc(+d: Nat, +x: Nat, +len: U32, +c: Nat, +s: Nat, +hc: {{Nat.is_le(Nat.add(c, s), {FS}n) == True{{}} : Bool}}, {HW}, {HA})
    -> {{Nat.is_le(Nat.add(Nat.add(c, x), s), {P4}) == True{{}} : Bool}}:
  UR.roomf(x, U32.to_nat(len), c, s, {P4}, hw, FD.nat__le_trans(Nat.add(c, s), {FS}n, U32.to_nat(len), hc, leFS(len, ha)))

# The child's window ({FS} + x, len - {FS}) lies in the buffer.
def hwY(+d: Nat, +x: Nat, +len: U32, {HW}, {HA})
    -> {{Nat.is_le(Nat.add(Nat.add(U32.to_nat({FS}), x), U32.to_nat(LL(len))), {P4}) == True{{}} : Bool}}:
  +e = Equal.trans(Nat, Nat.add(Nat.add({FS}n, x), U32.to_nat(LL(len))), Nat.add({FS}n, Nat.add(x, U32.to_nat(LL(len)))), Nat.add(x, Nat.add({FS}n, U32.to_nat(LL(len)))),
    FD.nat__add_assoc({FS}n, x, U32.to_nat(LL(len))), FD.lru_nat_algebra__add_swap({FS}n, x, U32.to_nat(LL(len))))
  %Equal.sym(Nat, Nat.add(Nat.add({FS}n, x), U32.to_nat(LL(len))), Nat.add(x, Nat.add({FS}n, U32.to_nat(LL(len)))), e) : {{Nat.is_le(_, {P4}) == True{{}} : Bool}}
  %Equal.sym(Nat, Nat.add({FS}n, U32.to_nat(LL(len))), U32.to_nat(len), enFS(len, ha)) : {{Nat.is_le(Nat.add(x, _), {P4}) == True{{}} : Bool}}
  hw

def ecY(+d: Nat, +x: Nat, +off: U32, +len: U32, {WHX}, {HA}) -> {{U32.to_nat(U32.add(off, {FS})) == {JX} : Nat}}:
  eoc(d, x, off, len, {FS}, {{==}}, eo, hd, hw, ha)

# ---- the validator ----------------------------------------------------------------------------

def rdoff(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, {WHX}, {PF}, {HA})
    -> {{B.read32({BF}, U32.add(off, {cvar})) == ({BF}, SPOw(t, x)) : B.Buf & U32}}:
  UR.rwx(d, t, n, U32.add(off, {cvar}), {posx(cvar)}, eoc(d, x, off, len, {cvar}, {{==}}, eo, hd, hw, ha), FD.nat__lt_trans(d, 28n, 31n, hd, {{==}}), pf,
    roomc(d, x, len, {cvar}n, 4n, {{==}}, hw, ha))

def okw_c1(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, {WHX}, {PF}, {HA}, +epo: {{SPOw(t, x) == {FS} : U32}})
    -> {{{Tn}_c0(True{{}}, {BF}, off, len, SPOw(t, x)) == ({BF}, {YCHK}) : B.Buf & Bool}}:
  %Equal.sym(U32, SPOw(t, x), {FS}, epo) :
    {{{Tn}_v1(off, len, _, {yok}({BF}, U32.add(off, _), U32.sub(len, _))) == ({BF}, {YCHK}) : B.Buf & Bool}}
  %Equal.sym(B.Buf & Bool, T.{Y}_ok({BF}, U32.add(off, {FS}), LL(len)), ({BF}, {YCHK}),
      YW.ok_evalw(d, t, n, {JX}, U32.add(off, {FS}), LL(len), ecY(d, x, off, len, eo, hd, hw, ha), hd, hwY(d, x, len, hw, ha), pf)) :
    {{{Tn}_v1(off, len, {FS}, _) == ({BF}, {YCHK}) : B.Buf & Bool}}
  c1_id({YCHK}, {BF}, off, len, {FS})

def okw_c0(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, {WHX}, {PF}, {HA},
    +b: Bool, +eb: {{U32.is_eq(SPOw(t, x), {FS}) == b : Bool}})
    -> {{{Tn}_c0(b, {BF}, off, len, SPOw(t, x)) == ({BF}, chk3(True{{}}, b, {YCHK})) : B.Buf & Bool}}:
  match b:
    case False{{}}: {{==}}
    case True{{}}: okw_c1(d, t, n, x, off, len, eo, hd, hw, pf, ha, FD.u32alg__eq_of(SPOw(t, x), {FS}, eb))

def okw_len(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, {WHX}, {PF},
    +a: Bool, +ea: {{U32.is_le({FS}, len) == a : Bool}})
    -> {{{Tn}_ok_len(a, {BF}, off, len) == ({BF}, chk3(a, U32.is_eq(SPOw(t, x), {FS}), {YCHK})) : B.Buf & Bool}}:
  match a:
    case False{{}}: {{==}}
    case True{{}}:
      %Equal.sym(B.Buf & U32, B.read32({BF}, U32.add(off, {cvar})), ({BF}, SPOw(t, x)), rdoff(d, t, n, x, off, len, eo, hd, hw, pf, ea)) :
        {{{Tn}_v0(off, len, _) == ({BF}, chk3(True{{}}, U32.is_eq(SPOw(t, x), {FS}), {YCHK})) : B.Buf & Bool}}
      okw_c0(d, t, n, x, off, len, eo, hd, hw, pf, ea, U32.is_eq(SPOw(t, x), {FS}), {{==}})

# The validator on the window returns the buffer and CHKw(t, x, off, len).
def ok_evalw(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, {WHX}, {PF})
    -> {{{Tn}_ok({BF}, off, len) == ({BF}, CHKw(t, x, off, len)) : B.Buf & Bool}}:
  okw_len(d, t, n, x, off, len, eo, hd, hw, pf, U32.is_le({FS}, len), {{==}})

# The offset word, once checked, reads as {FS}.
def rdo(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, {WHX}, {PF}, {HA}, +epo: {{SPOw(t, x) == {FS} : U32}})
    -> {{B.read32({BF}, U32.add(off, {cvar})) == ({BF}, {FS}) : B.Buf & U32}}:
  %Equal.sym(B.Buf & U32, B.read32({BF}, U32.add(off, {cvar})), ({BF}, SPOw(t, x)), rdoff(d, t, n, x, off, len, eo, hd, hw, pf, ha)) :
    {{_ == ({BF}, {FS}) : B.Buf & U32}}
  %Equal.sym(U32, SPOw(t, x), {FS}, epo) : {{({BF}, _) == ({BF}, {FS}) : B.Buf & U32}}
  {{==}}
''')
    leaves, OBJ = VBN.read_plan(x)
    OBJ = OBJ.replace('VF.BF(t, n)', BF)
    RHS = f'({BF}, OBJw(d, t, x, off, len))'
    TY = f'B.Buf & {Tn}'
    w(f'def OBJw(+d: Nat, +t: FD.array__Tree<U32>, +x: Nat, +off: U32, +len: U32) -> {Tn}: {OBJ}')
    w('')
    w('# The reader on the window, when the checks hold.')
    w(f'def rdw_go(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, {WHX}, {PF},')
    w(f'    {HA}, +epo: {{SPOw(t, x) == {FS} : U32}}, +hY: {{{YCHK} == True{{}} : Bool}})')
    w(f'    -> {{{Tn}_read({BF}, off, len) == {RHS} : {TY}}}:')
    w('  +hd30 = FD.nat__lt_trans(d, 28n, 30n, hd, {==})')
    w('  +hd31 = FD.nat__lt_trans(d, 28n, 31n, hd, {==})')

    def ecf(c):
        return f'eoc(d, x, off, len, {c}, {{==}}, eo, hd, hw, ha)'
    for ctx, call, val, kind, f in leaves:
        ctx = ctx.replace('VF.BF(t, n)', BF)
        call = call.replace('VF.BF(t, n)', BF)
        pat = ctx.replace('@', '_')
        if kind == 'off':
            w(f'  %Equal.sym(B.Buf & U32, {call}, ({BF}, {val}), rdo(d, t, n, x, off, len, eo, hd, hw, pf, ha, epo)) :')
        elif kind == 'fix':
            ft = f['ft']
            c = f['c']
            w(f'  %Equal.sym(B.Buf & {ft.rep()}, {call}, ({BF}, {val}),')
            w(f'      {rdx_ref(ft)}(d, t, n, U32.add(off, {c}), {posx(c)}, {ecf(c)}, hd30, pf, roomc(d, x, len, {c}n, {ft.size}n, {{==}}, hw, ha))) :')
        elif kind == 'words':
            c, z = f['c'], f['size']
            kw = VBY.kfit(31 + z)
            hs = (f'UW.hsx(d, U32.add(off, {c}), Nat.add(U32.to_nat({c}), x), {z}, {ecf(c)}, hd, '
                  f'roomc(d, x, len, U32.to_nat({c}), U32.to_nat({z}), {{==}}, hw, ha))')
            w(f'  %Equal.sym(B.Buf & O.Words, {call}, ({BF}, {val}),')
            w(f'      VBX.copy_into_at(d, t, n, U32.add(off, {c}), {z}, {f["dz"]}n, {kw}n, pf, hd31, {{==}}, {hs}, {{==}}, {{==}}, {{==}})) :')
        elif kind == 'var':
            w(f'  %Equal.sym(B.Buf & T.{Y}, {call}, ({BF}, {x.yobj()}),')
            w(f'      YW.readw(d, t, n, {JX}, U32.add(off, {FS}), LL(len), ecY(d, x, off, len, eo, hd, hw, ha), hd, hwY(d, x, len, hw, ha), pf, hY)) :')
        else:
            raise VBY.Skip('leaf kind ' + kind)
        w(f'    {{{pat} == {RHS} : {TY}}}')
    w('  {==}')
    w(f'''
# When the window's checks hold, the reader returns OBJw(d, t, x, off, len).
def readw(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, {WHX}, {PF},
    +hchk: {{CHKw(t, x, off, len) == True{{}} : Bool}})
    -> {{{Tn}_read({BF}, off, len) == {RHS} : {TY}}}:
  +a = U32.is_le({FS}, len)
  +b = U32.is_eq(SPOw(t, x), {FS})
  +c = {YCHK}
  +epo = FD.u32alg__eq_of(SPOw(t, x), {FS}, chk_b(a, b, c, hchk))
  rdw_go(d, t, n, x, off, len, eo, hd, hw, pf, chk_a(a, b, c, hchk), epo, chk_c(a, b, c, hchk))
''')
    # ---- the spec side ----
    ITEMS, CHAIN, PL, CAT, PRE, POST, hdr, CDEFS = VBN.spec_items(x, 'V', 'Yb', 'hv', named=('XC', '+t: FD.array__Tree<U32>, +x: Nat, +V: S.Value', 't, x, V', '+t: FD.array__Tree<U32>, +x: Nat, +Yb: +List<U32>', 't, x, Yb'))
    CDEF = '\n'.join(CDEFS)
    HDR = '[' + ', '.join(hdr) + ']'
    hdrh = '[' + ', '.join(h if j != po else '_' for j, h in enumerate(hdr)) + ']'
    ENC = f'List.append(&2, U32, F.limbs({HDR}), Yb)'
    ENCR = f'List.append(&2, U32, List.append(&2, U32, F.flat({PRE}), List.append(&2, U32, N.digits(4n, VS.FSZ({PRE}, {POST})), F.flat({POST}))), Yb)'
    L4 = 'U32.to_nat(LL(len))'
    YX = f'UW.WX(t, {JX}, {L4})'
    WX = 'UW.WX(t, x, U32.to_nat(len))'
    VY_ = f'YW.VALw(t, {JX}, LL(len))'
    w(f'''
# ---- the spec side ------------------------------------------------------------------------------

# The value of the window's fixed words and the child's value V, through its named field suffixes.
{CDEF}
def XVw(+t: FD.array__Tree<U32>, +x: Nat, +V: S.Value) -> S.Value: S.Sequence{{{ITEMS}}}

# Its spec parts: one variable part, the header's bytes (the offset is {FS}) and the child's bytes Yb.
def encpw(+t: FD.array__Tree<U32>, +x: Nat, +V: S.Value, +Yb: +List<U32>,
    +hv: {{Codec.parts(V, Spec.{Y}()) == Some{{[S.Variable{{Yb}}]}} : {MP}}}, +hdom: {{SP.bytes_domain(Yb) == True{{}} : Bool}},
    +fit: {{N.fits(4n, Nat.add(VS.FSZ({PRE}, {POST}), List.length(&2, U32, Yb))) == True{{}} : Bool}})
    -> {{Codec.parts(XVw(t, x, V), Spec.{n}()) == Some{{[S.Variable{{{ENC}}}]}} : {MP}}}:
  %Equal.sym({MP}, Codec.parts({ITEMS}, {CHAIN}), Some{{{PL}}},
      {CAT}) :
    {{Codec.aggregate(_, None{{}}) == Some{{[S.Variable{{{ENC}}}]}} : {MP}}}
  %Equal.sym({M}, Layout.encoding(VS.fpv({PRE}, Yb, {POST})), Some{{{ENCR}}}, VZ.enc_fpvb({PRE}, Yb, {POST}, hdom, fit)) :
    {{Codec.one(_, None{{}}) == Some{{[S.Variable{{{ENC}}}]}} : {MP}}}
  {{==}}

def VALw(+t: FD.array__Tree<U32>, +x: Nat, +len: U32) -> S.Value: XVw(t, x, {VY_})

def hwH(+d: Nat, +x: Nat, +len: U32, {HW}, {HA})
    -> {{Nat.is_le(Nat.add(x, Nat.add(A.quad({H}n), {L4})), {P4}) == True{{}} : Bool}}:
  %Equal.sym(Nat, Nat.add({FS}n, {L4}), U32.to_nat(len), enFS(len, ha)) : {{Nat.is_le(Nat.add(x, _), {P4}) == True{{}} : Bool}}
  hw

# The header's bytes and the child's window's bytes are the window's bytes.
def bytesw(+d: Nat, +t: FD.array__Tree<U32>, +x: Nat, +len: U32, {PF}, {HW}, {HA}, +epo: {{SPOw(t, x) == {FS} : U32}})
    -> {{List.append(&2, U32, F.limbs({HDR}), {YX}) == {WX} : +List<U32>}}:
  %enFS(len, ha) : {{List.append(&2, U32, F.limbs({HDR}), {YX}) == UW.WX(t, x, _) : +List<U32>}}
  %Equal.sym(+List<U32>, UW.WX(t, x, Nat.add(A.quad({H}n), {L4})), List.append(&2, U32, F.limbs(UR.RWS({H}n, t, x)), UW.WX(t, Nat.add(A.quad({H}n), x), {L4})),
      UW.headWX(d, t, x, {H}n, {L4}, pf, hwH(d, x, len, hw, ha))) :
    {{List.append(&2, U32, F.limbs({HDR}), {YX}) == _ : +List<U32>}}
  %epo : {{List.append(&2, U32, F.limbs({hdrh}), {YX}) == List.append(&2, U32, F.limbs(UR.RWS({H}n, t, x)), UW.WX(t, Nat.add(A.quad({H}n), x), {L4})) : +List<U32>}}
  {{==}}

def hlY(+d: Nat, +t: FD.array__Tree<U32>, +x: Nat, +len: U32, {PF}, {HW}, {HA})
    -> {{Nat.is_le(List.length(&2, U32, {YX}), {L4}) == True{{}} : Bool}}:
  %Equal.sym(Nat, List.length(&2, U32, {YX}), {L4}, UW.lenWX(d, t, {JX}, {L4}, pf, hwY(d, x, len, hw, ha))) : {{Nat.is_le(_, {L4}) == True{{}} : Bool}}
  FD.nat__le_refl({L4})

def fitw(+d: Nat, +t: FD.array__Tree<U32>, +x: Nat, +len: U32, {PF}, +hd: {{Nat.is_lt(d, 28n) == True{{}} : Bool}}, {HW}, {HA})
    -> {{N.fits(4n, Nat.add(VS.FSZ({PRE}, {POST}), List.length(&2, U32, {YX}))) == True{{}} : Bool}}:
  VBZ.fit_b(d, {FS}n, LL(len), len, {YX}, hlY(d, t, x, len, pf, hw, ha), enFS(len, ha),
    FD.nat__le_trans(U32.to_nat(len), Nat.add(x, U32.to_nat(len)), {P4}, Order.left_below_sum(x, U32.to_nat(len)), hw),
    FD.nat__lt_trans(d, 28n, 30n, hd, {{==}}))

def specw_go(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, {WHX}, {PF}, {HA}, +epo: {{SPOw(t, x) == {FS} : U32}},
    +hY: {{{YCHK} == True{{}} : Bool}})
    -> {{Codec.parts(VALw(t, x, len), Spec.{n}()) == Some{{[S.Variable{{{WX}}}]}} : {MP}}}:
  %bytesw(d, t, x, len, pf, hw, ha, epo) :
    {{Codec.parts(VALw(t, x, len), Spec.{n}()) == Some{{[S.Variable{{_}}]}} : {MP}}}
  encpw(t, x, {VY_}, {YX}, YW.specw(d, t, n, {JX}, U32.add(off, {FS}), LL(len), ecY(d, x, off, len, eo, hd, hw, ha), hd, hwY(d, x, len, hw, ha), pf, hY),
    UW.domWX(t, {JX}, {L4}), fitw(d, t, x, len, pf, hd, hw, ha))

# When the window's checks hold, the spec parts of VALw are its bytes, as one variable part.
def specw(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, {WHX}, {PF},
    +hchk: {{CHKw(t, x, off, len) == True{{}} : Bool}})
    -> {{Codec.parts(VALw(t, x, len), Spec.{n}()) == Some{{[S.Variable{{{WX}}}]}} : {MP}}}:
  +a = U32.is_le({FS}, len)
  +b = U32.is_eq(SPOw(t, x), {FS})
  +c = {YCHK}
  +epo = FD.u32alg__eq_of(SPOw(t, x), {FS}, chk_b(a, b, c, hchk))
  specw_go(d, t, n, x, off, len, eo, hd, hw, pf, chk_a(a, b, c, hchk), epo, chk_c(a, b, c, hchk))
''')
    # ---- the inversion ----
    fsb = [FS & 255, (FS >> 8) & 255, (FS >> 16) & 255, (FS >> 24) & 255]
    FSL = '[' + ', '.join(map(str, fsb)) + ']'
    R = FS - cvar - 4
    w(f'''
# ---- every value whose spec parts are the window's bytes passes the checks ----------------------

def ek_sub(+n: U32, +k: Nat, +en: {{U32.to_nat(n) == Nat.add({FS}n, k) : Nat}}) -> {{U32.to_nat(LL(n)) == k : Nat}}:
  +le = FD.logic__subst(Nat, z => {{Nat.is_le({FS}n, z) == True{{}} : Bool}}, Nat.add({FS}n, k), U32.to_nat(n), Equal.sym(Nat, U32.to_nat(n), Nat.add({FS}n, k), en), Order.below_sum({FS}n, k))
  %Equal.sym(Nat, U32.to_nat(LL(n)), Nat.sub(U32.to_nat(n), {FS}n), FD.u32__sub_nat(n, {FS}, le)) : {{_ == k : Nat}}
  %Equal.sym(Nat, U32.to_nat(n), Nat.add({FS}n, k), en) : {{Nat.sub(_, {FS}n) == k : Nat}}
  FD.nat__add_sub_cancel({FS}n, k)

def chk_truew(+t: FD.array__Tree<U32>, +x: Nat, +off: U32, +len: U32, +k: Nat, +en: {{U32.to_nat(len) == Nat.add({FS}n, k) : Nat}},
    +epo: {{SPOw(t, x) == {FS} : U32}}, +hY: {{{YCHK} == True{{}} : Bool}}) -> {{CHKw(t, x, off, len) == True{{}} : Bool}}:
  +le = FD.logic__subst(Nat, z => {{Nat.is_le({FS}n, z) == True{{}} : Bool}}, Nat.add({FS}n, k), U32.to_nat(len), Equal.sym(Nat, U32.to_nat(len), Nat.add({FS}n, k), en), Order.below_sum({FS}n, k))
  %Equal.sym(Bool, U32.is_le({FS}, len), True{{}}, FD.logic__subst(Bool, z => {{z == True{{}} : Bool}}, Nat.is_le({FS}n, U32.to_nat(len)), U32.is_le({FS}, len), Equal.sym(Bool, U32.is_le({FS}, len), Nat.is_le({FS}n, U32.to_nat(len)), VU.le_u32({FS}, len)), le)) :
    {{chk3(_, U32.is_eq(SPOw(t, x), {FS}), {YCHK}) == True{{}} : Bool}}
  %Equal.sym(U32, SPOw(t, x), {FS}, epo) : {{chk3(True{{}}, U32.is_eq(_, {FS}), {YCHK}) == True{{}} : Bool}}
  hY

def byteP(+d: Nat, +t: FD.array__Tree<U32>, +x: Nat, +len: U32, +k: Nat, +en: {{U32.to_nat(len) == Nat.add({FS}n, k) : Nat}}, {PF}, {HW})
    -> {{VS.bt(4n, VS.bdr({cvar}n, {WX})) == F.limbs([SPOw(t, x)]) : +List<U32>}}:
  +hw2 = FD.logic__subst(Nat, z => {{Nat.is_le(Nat.add(x, z), {P4}) == True{{}} : Bool}}, U32.to_nat(len), Nat.add({cvar}n, 4n+Nat.add({R}n, k)), en, hw)
  %Equal.sym(Nat, U32.to_nat(len), Nat.add({cvar}n, 4n+Nat.add({R}n, k)), en) : {{VS.bt(4n, VS.bdr({cvar}n, UW.WX(t, x, _))) == F.limbs([SPOw(t, x)]) : +List<U32>}}
  UW.byteWX(d, t, x, {cvar}n, Nat.add({R}n, k), pf, hw2)

# The child's bytes: the window after the header.
def eys(+t: FD.array__Tree<U32>, +x: Nat, +len: U32, +k: Nat, +en: {{U32.to_nat(len) == Nat.add({FS}n, k) : Nat}})
    -> {{VS.bdr({FS}n, {WX}) == {YX} : +List<U32>}}:
  %Equal.sym(Nat, U32.to_nat(len), Nat.add({FS}n, k), en) : {{VS.bdr({FS}n, UW.WX(t, x, _)) == {YX} : +List<U32>}}
  %Equal.sym(Nat, {L4}, k, ek_sub(len, k, en)) : {{VS.bdr({FS}n, UW.WX(t, x, Nat.add({FS}n, k))) == UW.WX(t, {JX}, _) : +List<U32>}}
  UW.tailWX(t, x, {FS}n, k)

def inv_tail(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, {WHX}, {PF},
    +hb: {{VS.bt(4n, VS.bdr({cvar}n, {WX})) == {FSL} : +List<U32>}}, +hv0: S.Value, +ys: +List<U32>,
    +hlen: {{List.length(&2, U32, {WX}) == Nat.add({FS}n, List.length(&2, U32, ys)) : Nat}},
    +hdr: {{VS.bdr({FS}n, {WX}) == ys : +List<U32>}},
    +hvp: {{Codec.parts(hv0, Spec.{Y}()) == Some{{[S.Variable{{ys}}]}} : {MP}}})
    -> {{CHKw(t, x, off, len) == True{{}} : Bool}}:
  +k = List.length(&2, U32, ys)
  +en = Equal.trans(Nat, U32.to_nat(len), List.length(&2, U32, {WX}), Nat.add({FS}n, k), Equal.sym(Nat, List.length(&2, U32, {WX}), U32.to_nat(len), UW.lenWX(d, t, x, U32.to_nat(len), pf, hw)), hlen)
  +ha = FD.logic__subst(Bool, z => {{z == True{{}} : Bool}}, Nat.is_le({FS}n, U32.to_nat(len)), U32.is_le({FS}, len), Equal.sym(Bool, U32.is_le({FS}, len), Nat.is_le({FS}n, U32.to_nat(len)), VU.le_u32({FS}, len)),
    FD.logic__subst(Nat, z => {{Nat.is_le({FS}n, z) == True{{}} : Bool}}, Nat.add({FS}n, k), U32.to_nat(len), Equal.sym(Nat, U32.to_nat(len), Nat.add({FS}n, k), en), Order.below_sum({FS}n, k)))
  +epo = XI.wordFS(SPOw(t, x), Equal.trans(+List<U32>, F.limbs([SPOw(t, x)]), VS.bt(4n, VS.bdr({cvar}n, {WX})), {FSL},
    Equal.sym(+List<U32>, VS.bt(4n, VS.bdr({cvar}n, {WX})), F.limbs([SPOw(t, x)]), byteP(d, t, x, len, k, en, pf, hw)), hb))
  +ey = Equal.trans(+List<U32>, ys, VS.bdr({FS}n, {WX}), {YX}, Equal.sym(+List<U32>, VS.bdr({FS}n, {WX}), ys, hdr), eys(t, x, len, k, en))
  +hv = FD.logic__subst(+List<U32>, z => {{Codec.parts(hv0, Spec.{Y}()) == Some{{[S.Variable{{z}}]}} : {MP}}}, ys, {YX}, ey, hvp)
  chk_truew(t, x, off, len, k, en, epo,
    YW.invw(d, t, n, {JX}, U32.add(off, {FS}), LL(len), ecY(d, x, off, len, eo, hd, hw, ha), hd, hwY(d, x, len, hw, ha), pf, hv0, hv))

def inv_p2(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, {WHX}, {PF},
    +hb: {{VS.bt(4n, VS.bdr({cvar}n, {WX})) == {FSL} : +List<U32>}}, +hv0: S.Value, +ys: +List<U32>,
    +hlen: {{List.length(&2, U32, {WX}) == Nat.add({FS}n, List.length(&2, U32, ys)) : Nat}},
    r3: DK.P2({{VS.bdr({FS}n, {WX}) == ys : +List<U32>}}, {{Codec.parts(hv0, Spec.{Y}()) == Some{{[S.Variable{{ys}}]}} : {MP}}}))
    -> {{CHKw(t, x, off, len) == True{{}} : Bool}}:
  (+hdr, hvp) = r3
  inv_tail(d, t, n, x, off, len, eo, hd, hw, pf, hb, hv0, ys, hlen, hdr, hvp)

def inv_facts(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, {WHX}, {PF}, facts: XI.FACTS({WX}))
    -> {{CHKw(t, x, off, len) == True{{}} : Bool}}:
  (+hb, ex) = facts
  (+hv0, r1) = ex
  (+ys, r2) = r1
  (+hlen, r3) = r2
  inv_p2(d, t, n, x, off, len, eo, hd, hw, pf, hb, hv0, ys, hlen, r3)

# Every value whose spec parts are the window's bytes passes the checks.
def invw(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, {WHX}, {PF},
    +v: S.Value, +e: {{Codec.parts(v, Spec.{n}()) == Some{{[S.Variable{{{WX}}}]}} : {MP}}})
    -> {{CHKw(t, x, off, len) == True{{}} : Bool}}:
  inv_facts(d, t, n, x, off, len, eo, hd, hw, pf, XI.inv_p(v, {WX}, e))
''')
    return '\n'.join(L) + '\n'


def main():
    SL.EXACT = True   # spec_laws' exact spec-parts proofs (F.items_fixed, container_fixed, ...)
    names = schema.load(ROOT / 'codegen/fulu.yaml')
    g = G.Gen()
    for nm, t in names.items():
        g.shape(t)
    xs = [XName(g, nm, names[nm]) for nm in NAMES]
    ns = [XNName(g, nm, names[nm]) for nm in NEST]
    import var_bytes_x2 as VX2
    x2s = [VX2.X2Name(g, nm, names[nm]) for nm in VX2.X2]
    fts = []
    for x in xs + ns + x2s:
        for f in x.fields:
            if f['kind'] == 'fix':
                for dft in f['ft'].deps():
                    if dft.p not in [q.p for q in fts]:
                        fts.append(dft)
    out = {ROOT / 'proofs/obj/vbx_fix.bend': fix_module(fts)}
    for x in xs:
        out[fname(x, '_inv')] = inv_text(x)
        out[fname(x)] = win_text(x)
    for x in ns:
        out[fname(x, '_inv')] = xn_inv_text(x)
        out[fname(x)] = xn_win_text(x)
    for x in x2s:
        out[fname(x, '_inv')] = VX2.inv_text(x)
        out[fname(x)] = VX2.win_text(x)
        out[fname(x, '_dec')] = VX2.dec_text(x)
    mine = sorted((ROOT / 'proofs/obj').glob('var_bytesx_*.bend'))
    orphans = [str(q.relative_to(ROOT)) for q in mine if q not in out]
    import runtime_refs as RR  # the runtime split: the modules import the per-name files they use
    out = RR.rewire_out(out)
    if '--check' in sys.argv:
        stale = [str(p.relative_to(ROOT)) for p, text in out.items() if not p.exists() or p.read_text() != text]
        if stale or orphans:
            print('stale generated byte-offset byte-list laws: ' + ', '.join(stale + orphans))
            sys.exit(1)
        print('generated byte-offset byte-list laws are current')
        return
    for p, text in out.items():
        p.write_text(text)
    for q in orphans:
        (ROOT / q).unlink()
    print(f'{len(xs) + len(ns) + len(x2s)} names: ' + ', '.join(str(p.relative_to(ROOT)) for p in out))


if __name__ == '__main__':
    main()
