#!/usr/bin/env python3
"""Codec laws of the bare progressive lists of sub-word elements: the generic forms
ProgressiveList[uint8] (GtDE4B86A990), ProgressiveList[uint16] (GtF23A2FB97E) and
ProgressiveList[boolean] (Gt83D8B3D008).

    python3 codegen/var_plist_sub.py [--check] [--no-big]

Writes, for each element kind k in u8, u16, bool:

    proofs/obj/big_var_winp_<k>.bend   the list at a window of any byte offset x and
        length len of a buffer (the interface of proofs/obj/vua_win.bend: CHKw,
        ok_evalw, OBJw, readw, VALw, specw, invw), so that a container holding
        such a list can import it as a child window;
    proofs/obj/big_var_plist_<X>_top.bend     ok_eval, decode_accept, decode_none,
        decode_spec, decode_reject: the window at x = 0, off = 0, len = n
        (codegen/var_win.py's top template);
    proofs/obj/big_var_plist_<X>_top_unique.bend   decode_unique;
    proofs/obj/big_var_plist_<X>_enc.bend     encode_eval, encode_spec.

The window modules are BIG (checked with `checkq --big`): the reader's list storage
is B.zeros(u) at every depth u (big_vvlz.bend's zg).  With --no-big nothing is
written.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'codegen'))
import var_win as VW  # noqa: E402

# element kind -> (generic name, runtime prefix)
KINDS = {'u8': ('GtDE4B86A990', 'pl_u8'), 'u16': ('GtF23A2FB97E', 'pl_u16'), 'bool': ('Gt83D8B3D008', 'pl_bool')}
HDR = '# GENERATED by codegen/var_plist_sub.py. Do not edit.'


def generic(lines):
    out = []
    for ln in lines:
        ln = ln.replace('import ../../types/fulu_obj.bend as T', 'import ../../types/generic_obj.bend as T')
        ln = ln.replace('import ../../spec/fulu_schemas.bend as Spec', 'import ./generic_specs.bend as Spec')
        out.append(ln)
    return out


def win_fname(k):
    return ROOT / f'proofs/obj/big_var_winp_{k}.bend'


def top_fname(X, part=''):
    return ROOT / f'proofs/obj/big_var_plist_{X}{part}.bend'


READW = r"""
# The reader on the window, when the checks hold: a copy of the window's words.
def OBJw(+d: Nat, +t: FD.array__Tree<U32>, +x: Nat, +off: U32, +len: U32) -> O.Words: O.Words{FD.array__thaw(U32, UCT.CT(d, t, off, len, VLS.DZ(len))), len}

def readw(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, +eo: {U32.to_nat(off) == x : Nat},
    +hd: {Nat.is_lt(d, 28n) == True{} : Bool}, +hw: {Nat.is_le(Nat.add(x, U32.to_nat(len)), A.quad(VB.pw(d))) == True{} : Bool},
    +pf: {FD.array__perfect(U32, d, t) == True{} : Bool}, +hchk: {CHKw(t, x, off, len) == True{} : Bool})
    -> {T.@p_read(BF(t, n), off, len) == (BF(t, n), OBJw(d, t, x, off, len)) : B.Buf & O.Words}:
  +hL = hlen(d, x, len, hw)
  +hz = VLS.hdz29(d, len, hd, hL)
  +ez = FD.logic__subst(Nat, z => {B.zeros(B.words_depth_u(VC.WZ(len))) == Array.new(U32, z, 0) : Array<U32>}, U32.to_nat(B.words_depth_u(VC.WZ(len))), VLS.DZ(len),
    VD.wdu(VC.WZ(len)), VZG.zg(B.words_depth_u(VC.WZ(len))))
  UCT.copy_in_at(d, t, n, off, len, VLS.DZ(len), VLS.KK(d), pf, FD.nat__lt_trans(d, 28n, 31n, hd, {==}), FD.nat__le_lt_trans(VLS.DZ(len), 29n, 31n, hz, {==}), ez,
    UW.hsx(d, off, x, len, eo, hd, hw), VLS.hrg(d, len, hd, hL), VLS.kk_lt(d, hd), VLS.hyn(d, len, hL))
"""

WIN_U8 = r"""
def v1() -> Word(31n): FD.spec_numeric__from_nat(31n, 1n)

# Whole elements: every length is (one-byte elements, no limit).
def CHKw(+t: FD.array__Tree<U32>, +x: Nat, +off: U32, +len: U32) -> Bool: Bool.and(U32.is_eq(len, (U32.div(len, 1) * 1 : U32)), True{})

# The validator on the window returns the buffer and CHKw.
def ok_evalw(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, +eo: {U32.to_nat(off) == x : Nat},
    +hd: {Nat.is_lt(d, 28n) == True{} : Bool}, +hw: {Nat.is_le(Nat.add(x, U32.to_nat(len)), A.quad(VB.pw(d))) == True{} : Bool},
    +pf: {FD.array__perfect(U32, d, t) == True{} : Bool})
    -> {T.@p_ok(BF(t, n), off, len) == (BF(t, n), CHKw(t, x, off, len)) : B.Buf & Bool}:
  {==}

# The checks hold for every window.
def chk(+t: FD.array__Tree<U32>, +x: Nat, +off: U32, +len: U32) -> {CHKw(t, x, off, len) == True{} : Bool}:
  +w = VU.whole_i(len, 1, len, v1(), {==}, {==}, {==}, U32.to_nat(len), PB.mul1(U32.to_nat(len)), FD.nat__le_refl(U32.to_nat(len)))
  FD.logic__and_intro(U32.is_eq(len, (U32.div(len, 1) * 1 : U32)), True{}, FD.logic__and_left(U32.is_eq(len, (U32.div(len, 1) * 1 : U32)), U32.is_le(U32.div(len, 1), len), w), {==})
@READW
def VALw(+t: FD.array__Tree<U32>, +x: Nat, +len: U32) -> S.Value: S.Sequence{PB.it1(U32.to_nat(len), UW.WX(t, x, U32.to_nat(len)))}

# The progressive list of a byte string's bytes: one variable part, the string.
def prog_parts(+k: Nat, +xs: +List<U32>, +hs: {SP.byte_scope(k, xs) == True{} : Bool}, +hfit: {N.fits(4n, k) == True{} : Bool})
    -> {Codec.parts(S.Sequence{PB.it1(k, xs)}, Spec.@X()) == Some{[S.Variable{xs}]} : Maybe<&2, +List<S.Part>>}:
  %Equal.sym(Maybe<&2, +List<S.Part>>, Codec.parts(PB.it1(k, xs), S.Repeat{S.Unsigned{P.U8{}}}), Some{U8.sparts(xs)}, U8.u8parts(k, xs, hs)) :
    {Codec.aggregate(_, None{}) == Some{[S.Variable{xs}]} : Maybe<&2, +List<S.Part>>}
  %Equal.sym(Maybe<&2, +List<U32>>, Layout.encoding(U8.sparts(xs)), Some{List.append(&2, U32, xs, [])},
      VMV.enc_gen(U8.sparts(xs), k, xs, [], Equal.trans(Nat, Layout.fixed_size(U8.sparts(xs)), List.length(&2, U32, xs), k, U8.sp_size(xs), U8.scope_len(k, xs, hs)),
        U8.sp_fp(xs, k), U8.sp_pay(xs), U8.scope_valid(k, xs, hs),
        FD.logic__subst(Nat, z => {N.fits(4n, z) == True{} : Bool}, k, Nat.add(k, 0n), Equal.sym(Nat, Nat.add(k, 0n), k, FD.nat__add_zero(k)), hfit))) :
    {Codec.one(_, None{}) == Some{[S.Variable{xs}]} : Maybe<&2, +List<S.Part>>}
  %Equal.sym(+List<U32>, List.append(&2, U32, xs, []), xs, VS.app_nil(xs)) : {Codec.one(Some{_}, None{}) == Some{[S.Variable{xs}]} : Maybe<&2, +List<S.Part>>}
  {==}

# The spec parts of the value: one variable part, the window's bytes.
def specw(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, +eo: {U32.to_nat(off) == x : Nat},
    +hd: {Nat.is_lt(d, 28n) == True{} : Bool}, +hw: {Nat.is_le(Nat.add(x, U32.to_nat(len)), A.quad(VB.pw(d))) == True{} : Bool},
    +pf: {FD.array__perfect(U32, d, t) == True{} : Bool}, +hchk: {CHKw(t, x, off, len) == True{} : Bool})
    -> {Codec.parts(VALw(t, x, len), Spec.@X()) == Some{[S.Variable{UW.WX(t, x, U32.to_nat(len))}]} : Maybe<&2, +List<S.Part>>}:
  +Y = UW.WX(t, x, U32.to_nat(len))
  +hs = FD.logic__subst(Nat, z => {SP.byte_scope(z, Y) == True{} : Bool}, List.length(&2, U32, Y), U32.to_nat(len), UW.lenWX(d, t, x, U32.to_nat(len), pf, hw),
    U8.dom_scope(Y, UW.domWX(t, x, U32.to_nat(len))))
  prog_parts(U32.to_nat(len), Y, hs, VFT.fits4(2n+d, U32.to_nat(len), hlen(d, x, len, hw), FD.nat__lt_trans(d, 28n, 30n, hd, {==})))

# Every value whose spec parts are the window's bytes passes the checks (every window does).
def invw(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, +eo: {U32.to_nat(off) == x : Nat},
    +hd: {Nat.is_lt(d, 28n) == True{} : Bool}, +hw: {Nat.is_le(Nat.add(x, U32.to_nat(len)), A.quad(VB.pw(d))) == True{} : Bool},
    +pf: {FD.array__perfect(U32, d, t) == True{} : Bool}, +v: S.Value,
    +e: {Codec.parts(v, Spec.@X()) == Some{[S.Variable{UW.WX(t, x, U32.to_nat(len))}]} : Maybe<&2, +List<S.Part>>})
    -> {CHKw(t, x, off, len) == True{} : Bool}:
  chk(t, x, off, len)
"""

WIN_U16 = r"""
def v2() -> Word(31n): FD.spec_numeric__from_nat(31n, 2n)
def CQ(+len: U32) -> Nat: U32.to_nat(U32.div(len, 2))

# Whole elements (two bytes each, no limit).
def CHKw(+t: FD.array__Tree<U32>, +x: Nat, +off: U32, +len: U32) -> Bool: Bool.and(U32.is_eq(len, (U32.div(len, 2) * 2 : U32)), True{})

# The validator on the window returns the buffer and CHKw.
def ok_evalw(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, +eo: {U32.to_nat(off) == x : Nat},
    +hd: {Nat.is_lt(d, 28n) == True{} : Bool}, +hw: {Nat.is_le(Nat.add(x, U32.to_nat(len)), A.quad(VB.pw(d))) == True{} : Bool},
    +pf: {FD.array__perfect(U32, d, t) == True{} : Bool})
    -> {T.@p_ok(BF(t, n), off, len) == (BF(t, n), CHKw(t, x, off, len)) : B.Buf & Bool}:
  {==}

# CHKw: the length is twice the element count.
def eLc(+t: FD.array__Tree<U32>, +x: Nat, +off: U32, +len: U32, +hc: {CHKw(t, x, off, len) == True{} : Bool}) -> {U32.to_nat(len) == Nat.double(CQ(len)) : Nat}:
  Equal.trans(Nat, U32.to_nat(len), Nat.mul(CQ(len), 2n), Nat.double(CQ(len)), VLS.whole_t1(len, 2, v2(), {==}, {==}, {==}, hc),
    Equal.sym(Nat, Nat.double(CQ(len)), Nat.mul(CQ(len), 2n), PB.dbl_mul(CQ(len))))

# A length of 2 c bytes passes the checks.
def chk2(+t: FD.array__Tree<U32>, +x: Nat, +off: U32, +len: U32, +c: Nat, +ec: {U32.to_nat(len) == Nat.double(c) : Nat}) -> {CHKw(t, x, off, len) == True{} : Bool}:
  +hc = FD.logic__subst(Nat, z => {Nat.is_le(c, z) == True{} : Bool}, Nat.add(c, c), U32.to_nat(len),
    Equal.trans(Nat, Nat.add(c, c), Nat.double(c), U32.to_nat(len), Equal.sym(Nat, Nat.double(c), Nat.add(c, c), FD.lru_nat_algebra__double_self(c)), Equal.sym(Nat, U32.to_nat(len), Nat.double(c), ec)),
    Order.left_below_sum(c, c))
  +w = VU.whole_i(len, 2, len, v2(), {==}, {==}, {==}, c, Equal.trans(Nat, U32.to_nat(len), Nat.double(c), Nat.mul(c, 2n), ec, PB.dbl_mul(c)), hc)
  FD.logic__and_intro(U32.is_eq(len, (U32.div(len, 2) * 2 : U32)), True{}, FD.logic__and_left(U32.is_eq(len, (U32.div(len, 2) * 2 : U32)), U32.is_le(U32.div(len, 2), len), w), {==})
@READW
def VALw(+t: FD.array__Tree<U32>, +x: Nat, +len: U32) -> S.Value: S.Sequence{PB.it2(CQ(len), UW.WX(t, x, U32.to_nat(len)))}

# ---- the spec parts of a list of 2-byte elements ------------------------------------------------

def sp2(xs: +List<U32>) -> +List<S.Part>:
  match xs:
    case Nil{}: []
    case Con{x0, t}:
      match t:
        case Nil{}: []
        case Con{x1, r}: S.Fixed{[x0, x1]} <> sp2(r)

def u16p(+x0: U32, +x1: U32, +e0: {U32.is_lt(x0, 256) == True{} : Bool}, +e1: {U32.is_lt(x1, 256) == True{} : Bool})
    -> {Codec.parts(S.UnsignedValue{P.UInt{PB.v16of(x0, x1), 0, 0, 0, 0, 0, 0, 0}}, S.Unsigned{P.U16{}}) == Some{[S.Fixed{[x0, x1]}]} : Maybe<&2, +List<S.Part>>}:
  %Equal.sym(Maybe<&2, +List<U32>>, RR.basic_one(S.UnsignedValue{P.UInt{PB.v16of(x0, x1), 0, 0, 0, 0, 0, 0, 0}}, S.Unsigned{P.U16{}}), Some{[x0, x1]}, PB.two(x0, x1, e0, e1)) :
    {Codec.one(_, Some{2n}) == Some{[S.Fixed{[x0, x1]}]} : Maybe<&2, +List<S.Part>>}
  {==}

# The facts of a byte string in scope for k elements, by induction on k.
law sc2p:
  for +k: Nat
  for +xs: +List<U32>
  for +hs: {SP.byte_scope(Nat.double(k), xs) == True{} : Bool}
  {Codec.parts(PB.it2(k, xs), S.Repeat{S.Unsigned{P.U16{}}}) == Some{sp2(xs)} : Maybe<&2, +List<S.Part>>}
def sc2p(k, xs, hs):
  match k xs:
    case 0n Nil{}: {==}
    case 0n Con{+x, +t}: Empty.absurd({Codec.parts(PB.it2(0n, x <> t), S.Repeat{S.Unsigned{P.U16{}}}) == Some{sp2(x <> t)} : Maybe<&2, +List<S.Part>>}, FD.logic__false_true(hs))
    case 1n+ +c Nil{}: Empty.absurd({Codec.parts(PB.it2(1n+c, Nil{}), S.Repeat{S.Unsigned{P.U16{}}}) == Some{sp2(Nil{})} : Maybe<&2, +List<S.Part>>}, FD.logic__false_true(hs))
    case 1n+ +c Con{+x0, +t}:
      match t:
        case Nil{}: Empty.absurd({Codec.parts(PB.it2(1n+c, [x0]), S.Repeat{S.Unsigned{P.U16{}}}) == Some{sp2([x0])} : Maybe<&2, +List<S.Part>>}, FD.logic__false_true(FD.logic__and_right(U32.is_lt(x0, 256), False{}, hs)))
        case Con{+x1, +rest}:
          +k1 = FD.logic__and_right(U32.is_lt(x0, 256), Bool.and(U32.is_lt(x1, 256), SP.byte_scope(Nat.double(c), rest)), hs)
          +e0 = FD.logic__and_left(U32.is_lt(x0, 256), Bool.and(U32.is_lt(x1, 256), SP.byte_scope(Nat.double(c), rest)), hs)
          +e1 = FD.logic__and_left(U32.is_lt(x1, 256), SP.byte_scope(Nat.double(c), rest), k1)
          +ih = sc2p(c, rest, FD.logic__and_right(U32.is_lt(x1, 256), SP.byte_scope(Nat.double(c), rest), k1))
          F.cat_fixed(Codec.parts(S.UnsignedValue{P.UInt{PB.v16of(x0, x1), 0, 0, 0, 0, 0, 0, 0}}, S.Unsigned{P.U16{}}), [x0, x1], Codec.parts(PB.it2(c, rest), S.Repeat{S.Unsigned{P.U16{}}}), sp2(rest), u16p(x0, x1, e0, e1), ih)

law sc2s:
  for +k: Nat
  for +xs: +List<U32>
  for +hs: {SP.byte_scope(Nat.double(k), xs) == True{} : Bool}
  {Layout.fixed_size(sp2(xs)) == Nat.double(k) : Nat}
def sc2s(k, xs, hs):
  match k xs:
    case 0n Nil{}: {==}
    case 0n Con{+x, +t}: Empty.absurd({Layout.fixed_size(sp2(x <> t)) == Nat.double(0n) : Nat}, FD.logic__false_true(hs))
    case 1n+ +c Nil{}: Empty.absurd({Layout.fixed_size(sp2(Nil{})) == Nat.double(1n+c) : Nat}, FD.logic__false_true(hs))
    case 1n+ +c Con{+x0, +t}:
      match t:
        case Nil{}: Empty.absurd({Layout.fixed_size(sp2([x0])) == Nat.double(1n+c) : Nat}, FD.logic__false_true(FD.logic__and_right(U32.is_lt(x0, 256), False{}, hs)))
        case Con{+x1, +rest}:
          +k1 = FD.logic__and_right(U32.is_lt(x0, 256), Bool.and(U32.is_lt(x1, 256), SP.byte_scope(Nat.double(c), rest)), hs)
          +e0 = FD.logic__and_left(U32.is_lt(x0, 256), Bool.and(U32.is_lt(x1, 256), SP.byte_scope(Nat.double(c), rest)), hs)
          +e1 = FD.logic__and_left(U32.is_lt(x1, 256), SP.byte_scope(Nat.double(c), rest), k1)
          +ih = sc2s(c, rest, FD.logic__and_right(U32.is_lt(x1, 256), SP.byte_scope(Nat.double(c), rest), k1))
          Equal.cong(Nat, Nat, z => 2n+z, Layout.fixed_size(sp2(rest)), Nat.double(c), ih)

law sc2v:
  for +k: Nat
  for +xs: +List<U32>
  for +hs: {SP.byte_scope(Nat.double(k), xs) == True{} : Bool}
  {Layout.bytes_valid(sp2(xs)) == True{} : Bool}
def sc2v(k, xs, hs):
  match k xs:
    case 0n Nil{}: {==}
    case 0n Con{+x, +t}: Empty.absurd({Layout.bytes_valid(sp2(x <> t)) == True{} : Bool}, FD.logic__false_true(hs))
    case 1n+ +c Nil{}: Empty.absurd({Layout.bytes_valid(sp2(Nil{})) == True{} : Bool}, FD.logic__false_true(hs))
    case 1n+ +c Con{+x0, +t}:
      match t:
        case Nil{}: Empty.absurd({Layout.bytes_valid(sp2([x0])) == True{} : Bool}, FD.logic__false_true(FD.logic__and_right(U32.is_lt(x0, 256), False{}, hs)))
        case Con{+x1, +rest}:
          +k1 = FD.logic__and_right(U32.is_lt(x0, 256), Bool.and(U32.is_lt(x1, 256), SP.byte_scope(Nat.double(c), rest)), hs)
          +e0 = FD.logic__and_left(U32.is_lt(x0, 256), Bool.and(U32.is_lt(x1, 256), SP.byte_scope(Nat.double(c), rest)), hs)
          +e1 = FD.logic__and_left(U32.is_lt(x1, 256), SP.byte_scope(Nat.double(c), rest), k1)
          +ih = sc2v(c, rest, FD.logic__and_right(U32.is_lt(x1, 256), SP.byte_scope(Nat.double(c), rest), k1))
          FD.logic__and_intro(SP.bytes_domain([x0, x1]), Layout.bytes_valid(sp2(rest)), FD.logic__and_intro(U32.is_lt(x0, 256), Bool.and(U32.is_lt(x1, 256), True{}), e0, FD.logic__and_intro(U32.is_lt(x1, 256), True{}, e1, {==})), ih)

law sc2l:
  for +k: Nat
  for +xs: +List<U32>
  for +hs: {SP.byte_scope(Nat.double(k), xs) == True{} : Bool}
  {List.length(&2, U32, xs) == Nat.double(k) : Nat}
def sc2l(k, xs, hs):
  match k xs:
    case 0n Nil{}: {==}
    case 0n Con{+x, +t}: Empty.absurd({List.length(&2, U32, x <> t) == Nat.double(0n) : Nat}, FD.logic__false_true(hs))
    case 1n+ +c Nil{}: Empty.absurd({List.length(&2, U32, Nil{}) == Nat.double(1n+c) : Nat}, FD.logic__false_true(hs))
    case 1n+ +c Con{+x0, +t}:
      match t:
        case Nil{}: Empty.absurd({List.length(&2, U32, [x0]) == Nat.double(1n+c) : Nat}, FD.logic__false_true(FD.logic__and_right(U32.is_lt(x0, 256), False{}, hs)))
        case Con{+x1, +rest}:
          +k1 = FD.logic__and_right(U32.is_lt(x0, 256), Bool.and(U32.is_lt(x1, 256), SP.byte_scope(Nat.double(c), rest)), hs)
          +e0 = FD.logic__and_left(U32.is_lt(x0, 256), Bool.and(U32.is_lt(x1, 256), SP.byte_scope(Nat.double(c), rest)), hs)
          +e1 = FD.logic__and_left(U32.is_lt(x1, 256), SP.byte_scope(Nat.double(c), rest), k1)
          +ih = sc2l(c, rest, FD.logic__and_right(U32.is_lt(x1, 256), SP.byte_scope(Nat.double(c), rest), k1))
          Equal.cong(Nat, Nat, z => 2n+z, List.length(&2, U32, rest), Nat.double(c), ih)

def ev(xs: +List<U32>) -> Bool:
  match xs:
    case Nil{}: True{}
    case Con{x0, t}:
      match t:
        case Nil{}: False{}
        case Con{x1, r}: ev(r)

law sc2e:
  for +k: Nat
  for +xs: +List<U32>
  for +hs: {SP.byte_scope(Nat.double(k), xs) == True{} : Bool}
  {ev(xs) == True{} : Bool}
def sc2e(k, xs, hs):
  match k xs:
    case 0n Nil{}: {==}
    case 0n Con{+x, +t}: Empty.absurd({ev(x <> t) == True{} : Bool}, FD.logic__false_true(hs))
    case 1n+ +c Nil{}: Empty.absurd({ev(Nil{}) == True{} : Bool}, FD.logic__false_true(hs))
    case 1n+ +c Con{+x0, +t}:
      match t:
        case Nil{}: Empty.absurd({ev([x0]) == True{} : Bool}, FD.logic__false_true(FD.logic__and_right(U32.is_lt(x0, 256), False{}, hs)))
        case Con{+x1, +rest}:
          +k1 = FD.logic__and_right(U32.is_lt(x0, 256), Bool.and(U32.is_lt(x1, 256), SP.byte_scope(Nat.double(c), rest)), hs)
          sc2e(c, rest, FD.logic__and_right(U32.is_lt(x1, 256), SP.byte_scope(Nat.double(c), rest), k1))

law s2_fp:
  for +xs: +List<U32>
  for +o: Nat
  for +h: {ev(xs) == True{} : Bool}
  {Layout.fixed_parts(sp2(xs), o) == xs : +List<U32>}
def s2_fp(xs, o, h):
  match xs:
    case Nil{}: {==}
    case Con{+x0, +t}:
      match t:
        case Nil{}: Empty.absurd({Layout.fixed_parts(sp2([x0]), o) == [x0] : +List<U32>}, FD.logic__false_true(h))
        case Con{+x1, +r}: Equal.cong(+List<U32>, +List<U32>, z => x0 <> x1 <> z, Layout.fixed_parts(sp2(r), o), r, s2_fp(r, o, h))

law s2_pay:
  for +xs: +List<U32>
  {Layout.payloads(sp2(xs)) == [] : +List<U32>}
def s2_pay(xs):
  match xs:
    case Nil{}: {==}
    case Con{+x0, +t}:
      match t:
        case Nil{}: {==}
        case Con{+x1, +r}: s2_pay(r)

# The progressive list of the 2-byte elements of a byte string: one variable part, the string.
def prog_parts(+k: Nat, +xs: +List<U32>, +hs: {SP.byte_scope(Nat.double(k), xs) == True{} : Bool}, +hfit: {N.fits(4n, Nat.double(k)) == True{} : Bool})
    -> {Codec.parts(S.Sequence{PB.it2(k, xs)}, Spec.@X()) == Some{[S.Variable{xs}]} : Maybe<&2, +List<S.Part>>}:
  +hm = sc2e(k, xs, hs)
  %Equal.sym(Maybe<&2, +List<S.Part>>, Codec.parts(PB.it2(k, xs), S.Repeat{S.Unsigned{P.U16{}}}), Some{sp2(xs)}, sc2p(k, xs, hs)) :
    {Codec.aggregate(_, None{}) == Some{[S.Variable{xs}]} : Maybe<&2, +List<S.Part>>}
  %Equal.sym(Maybe<&2, +List<U32>>, Layout.encoding(sp2(xs)), Some{List.append(&2, U32, xs, [])},
      VMV.enc_gen(sp2(xs), Nat.double(k), xs, [], sc2s(k, xs, hs), s2_fp(xs, Nat.double(k), hm), s2_pay(xs), sc2v(k, xs, hs),
        FD.logic__subst(Nat, z => {N.fits(4n, z) == True{} : Bool}, Nat.double(k), Nat.add(Nat.double(k), 0n), Equal.sym(Nat, Nat.add(Nat.double(k), 0n), Nat.double(k), FD.nat__add_zero(Nat.double(k))), hfit))) :
    {Codec.one(_, None{}) == Some{[S.Variable{xs}]} : Maybe<&2, +List<S.Part>>}
  %Equal.sym(+List<U32>, List.append(&2, U32, xs, []), xs, VS.app_nil(xs)) : {Codec.one(Some{_}, None{}) == Some{[S.Variable{xs}]} : Maybe<&2, +List<S.Part>>}
  {==}

# The spec parts of the value: one variable part, the window's bytes.
def specw(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, +eo: {U32.to_nat(off) == x : Nat},
    +hd: {Nat.is_lt(d, 28n) == True{} : Bool}, +hw: {Nat.is_le(Nat.add(x, U32.to_nat(len)), A.quad(VB.pw(d))) == True{} : Bool},
    +pf: {FD.array__perfect(U32, d, t) == True{} : Bool}, +hchk: {CHKw(t, x, off, len) == True{} : Bool})
    -> {Codec.parts(VALw(t, x, len), Spec.@X()) == Some{[S.Variable{UW.WX(t, x, U32.to_nat(len))}]} : Maybe<&2, +List<S.Part>>}:
  +Y = UW.WX(t, x, U32.to_nat(len))
  +el = eLc(t, x, off, len, hchk)
  +hs0 = FD.logic__subst(Nat, z => {SP.byte_scope(z, Y) == True{} : Bool}, List.length(&2, U32, Y), U32.to_nat(len), UW.lenWX(d, t, x, U32.to_nat(len), pf, hw),
    U8.dom_scope(Y, UW.domWX(t, x, U32.to_nat(len))))
  +hs = FD.logic__subst(Nat, z => {SP.byte_scope(z, Y) == True{} : Bool}, U32.to_nat(len), Nat.double(CQ(len)), el, hs0)
  +hf = FD.logic__subst(Nat, z => {N.fits(4n, z) == True{} : Bool}, U32.to_nat(len), Nat.double(CQ(len)), el,
    VFT.fits4(2n+d, U32.to_nat(len), hlen(d, x, len, hw), FD.nat__lt_trans(d, 28n, 30n, hd, {==})))
  prog_parts(CQ(len), Y, hs, hf)

# ---- every value whose spec parts are the window's bytes passes the checks ----------------------

@REP

def ivf(+d: Nat, +t: FD.array__Tree<U32>, +x: Nat, +off: U32, +len: U32, +hw: {Nat.is_le(Nat.add(x, U32.to_nat(len)), A.quad(VB.pw(d))) == True{} : Bool},
    +pf: {FD.array__perfect(U32, d, t) == True{} : Bool}, +c: Nat,
    +ys: +List<U32>, +ly: {List.length(&2, U32, ys) == Nat.double(c) : Nat}, +ey: {ys == UW.WX(t, x, U32.to_nat(len)) : +List<U32>})
    -> {CHKw(t, x, off, len) == True{} : Bool}:
  +el = Equal.trans(Nat, U32.to_nat(len), List.length(&2, U32, UW.WX(t, x, U32.to_nat(len))), Nat.double(c),
    Equal.sym(Nat, List.length(&2, U32, UW.WX(t, x, U32.to_nat(len))), U32.to_nat(len), UW.lenWX(d, t, x, U32.to_nat(len), pf, hw)),
    Equal.trans(Nat, List.length(&2, U32, UW.WX(t, x, U32.to_nat(len))), List.length(&2, U32, ys), Nat.double(c),
      Equal.cong(+List<U32>, Nat, z => List.length(&2, U32, z), UW.WX(t, x, U32.to_nat(len)), ys, Equal.sym(+List<U32>, ys, UW.WX(t, x, U32.to_nat(len)), ey)), ly))
  chk2(t, x, off, len, c, el)

def ivm4(+d: Nat, +t: FD.array__Tree<U32>, +x: Nat, +off: U32, +len: U32, +hw: {Nat.is_le(Nat.add(x, U32.to_nat(len)), A.quad(VB.pw(d))) == True{} : Bool},
    +pf: {FD.array__perfect(U32, d, t) == True{} : Bool}, +its: S.Value,
    +ps: +List<S.Part>, +em3: {Codec.parts(its, S.Repeat{U16S()}) == Some{ps} : Maybe<&2, +List<S.Part>>},
    +m4: Maybe<&2, +List<U32>>, +em4: {Layout.encoding(ps) == m4 : Maybe<&2, +List<U32>>},
    +e: {Codec.one(m4, None{}) == Some{[S.Variable{UW.WX(t, x, U32.to_nat(len))}]} : Maybe<&2, +List<S.Part>>})
    -> {CHKw(t, x, off, len) == True{} : Bool}:
  match m4:
    case None{}: Empty.absurd({CHKw(t, x, off, len) == True{} : Bool}, FD.logic__none_some(+List<S.Part>, [S.Variable{UW.WX(t, x, U32.to_nat(len))}], e))
    case Some{+ys}:
      +lys = Equal.trans(Nat, List.length(&2, U32, ys), Layout.fixed_size(ps), Nat.double(Codec.count(its)),
        VS.enc_len(ps, ys, Pair.fst({VS.allfix(ps) == True{} : Bool}, {Layout.fixed_size(ps) == Nat.double(Codec.count(its)) : Nat}, rep_facts(its, ps, em3)), em4),
        Pair.snd({VS.allfix(ps) == True{} : Bool}, {Layout.fixed_size(ps) == Nat.double(Codec.count(its)) : Nat}, rep_facts(its, ps, em3)))
      ivf(d, t, x, off, len, hw, pf, Codec.count(its), ys, lys, var_inj(ys, UW.WX(t, x, U32.to_nat(len)), e))

def ivm3(+d: Nat, +t: FD.array__Tree<U32>, +x: Nat, +off: U32, +len: U32, +hw: {Nat.is_le(Nat.add(x, U32.to_nat(len)), A.quad(VB.pw(d))) == True{} : Bool},
    +pf: {FD.array__perfect(U32, d, t) == True{} : Bool}, +its: S.Value,
    +m3: Maybe<&2, +List<S.Part>>, +em3: {Codec.parts(its, S.Repeat{U16S()}) == m3 : Maybe<&2, +List<S.Part>>},
    +e: {Codec.aggregate(m3, None{}) == Some{[S.Variable{UW.WX(t, x, U32.to_nat(len))}]} : Maybe<&2, +List<S.Part>>})
    -> {CHKw(t, x, off, len) == True{} : Bool}:
  match m3:
    case None{}: Empty.absurd({CHKw(t, x, off, len) == True{} : Bool}, FD.logic__none_some(+List<S.Part>, [S.Variable{UW.WX(t, x, U32.to_nat(len))}], e))
    case Some{+ps}: ivm4(d, t, x, off, len, hw, pf, its, ps, em3, Layout.encoding(ps), {==}, e)

# Every value whose spec parts are the window's bytes passes the checks.
def invw(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, +eo: {U32.to_nat(off) == x : Nat},
    +hd: {Nat.is_lt(d, 28n) == True{} : Bool}, +hw: {Nat.is_le(Nat.add(x, U32.to_nat(len)), A.quad(VB.pw(d))) == True{} : Bool},
    +pf: {FD.array__perfect(U32, d, t) == True{} : Bool}, +v: S.Value,
    +e: {Codec.parts(v, Spec.@X()) == Some{[S.Variable{UW.WX(t, x, U32.to_nat(len))}]} : Maybe<&2, +List<S.Part>>})
    -> {CHKw(t, x, off, len) == True{} : Bool}:
  match v:
    case S.Sequence{+its}: ivm3(d, t, x, off, len, hw, pf, its, Codec.parts(its, S.Repeat{U16S()}), {==}, e)
@ABSURDV
"""


def rep16_text():
    """vspec.bend's inversion of repeated uint64 parts, for uint16 (2 bytes each)."""
    src = (ROOT / 'proofs/obj/vspec.bend').read_text().split('\n')
    a = src.index('def REPF(+its: S.Value, +ps: +List<S.Part>) -> Type:')
    b = next(i for i in range(a, len(src)) if src[i].startswith('law allfix_pay:'))
    txt = '\n'.join(src[a:b]).rstrip()
    for o, n in [('F.', 'FD.'), ('x8(', 'Nat.double('), ('8n+Nat.double', '2n+Nat.double'), ('== 8n', '== 2n'), ('SP.prefix(8n,', 'SP.prefix(2n,'),
                 ('Some{8n}', 'Some{2n}'), (', 8n, l8)', ', 2n, l8)'), ('{8n+_', '{2n+_'), ('U64S()', 'U16S()'), ('P.U64{}', 'P.U16{}'), ('allfix(', 'VS.allfix(')]:
        txt = txt.replace(o, n)
    assert '8n' not in txt and 'x8' not in txt, txt
    return txt


def absurd_v(goal):
    L = []
    for c, args in VW.VALUE_CTORS:
        if c == 'Sequence':
            continue
        pat = f'S.{c}{{' + ', '.join('+' + a for a in args) + '}'
        term = f'S.{c}{{' + ', '.join(args) + '}'
        L.append(f'    case {pat}: Empty.absurd({goal}, FD.logic__none_some(+List<S.Part>, [S.Variable{{UW.WX(t, x, U32.to_nat(len))}}], e))')
    return '\n'.join(L)


WIN_BOOL = r"""
def v1() -> Word(31n): FD.spec_numeric__from_nat(31n, 1n)

# Every byte of the window a boolean (0 or 1).
def CHKw(+t: FD.array__Tree<U32>, +x: Nat, +off: U32, +len: U32) -> Bool: VRB.ALLB(UW.WX(t, x, U32.to_nat(len)))

# The validator's length check holds for every length (one-byte elements, no limit).
def chk1(+len: U32) -> {Bool.and(U32.is_eq(len, (U32.div(len, 1) * 1 : U32)), True{}) == True{} : Bool}:
  +w = VU.whole_i(len, 1, len, v1(), {==}, {==}, {==}, U32.to_nat(len), PB.mul1(U32.to_nat(len)), FD.nat__le_refl(U32.to_nat(len)))
  FD.logic__and_intro(U32.is_eq(len, (U32.div(len, 1) * 1 : U32)), True{}, FD.logic__and_left(U32.is_eq(len, (U32.div(len, 1) * 1 : U32)), U32.is_le(U32.div(len, 1), len), w), {==})

def em(+len: U32) -> {U32.to_nat(len) == U32.to_nat(U32.div(len, 1)) : Nat}:
  Equal.trans(Nat, U32.to_nat(len), Nat.mul(U32.to_nat(U32.div(len, 1)), 1n), U32.to_nat(U32.div(len, 1)), VLS.whole_t1(len, 1, v1(), {==}, {==}, {==}, chk1(len)),
    Equal.sym(Nat, U32.to_nat(U32.div(len, 1)), Nat.mul(U32.to_nat(U32.div(len, 1)), 1n), PB.mul1(U32.to_nat(U32.div(len, 1)))))

def s1(+c: Nat, +h: {Nat.is_le(1n, c) == True{} : Bool}) -> {c == 1n+Nat.sub(c, 1n) : Nat}:
  match c:
    case 0n: Empty.absurd({0n == 1n+Nat.sub(0n, 1n) : Nat}, FD.logic__false_true(h))
    case 1n+ +p: Equal.cong(Nat, Nat, z => 1n+z, p, Nat.sub(1n+p, 1n), Equal.sym(Nat, Nat.sub(Nat.add(1n, p), 1n), p, FD.nat__add_sub_cancel(1n, p)))

@CK
# The loop's bound: byte 1 + k of the window is inside the buffer.
def hbk(+d: Nat, +x: Nat, +len: U32, +k: Nat, +ek: {U32.to_nat(len) == 1n+k : Nat},
    +hw: {Nat.is_le(Nat.add(x, U32.to_nat(len)), A.quad(VB.pw(d))) == True{} : Bool})
    -> {Nat.is_le(VRL.pos(Nat.add(1n+k, 0n), 1n, x), A.quad(VB.pw(d))) == True{} : Bool}:
  %Equal.sym(Nat, Nat.add(1n+k, 0n), 1n+k, FD.nat__add_zero(1n+k)) : {Nat.is_le(Nat.add(Nat.mul(_, 1n), x), A.quad(VB.pw(d))) == True{} : Bool}
  %PB.mul1(1n+k) : {Nat.is_le(Nat.add(_, x), A.quad(VB.pw(d))) == True{} : Bool}
  FD.logic__subst(Nat, z => {Nat.is_le(z, A.quad(VB.pw(d))) == True{} : Bool}, Nat.add(x, U32.to_nat(len)), Nat.add(1n+k, x),
    Equal.trans(Nat, Nat.add(x, U32.to_nat(len)), Nat.add(x, 1n+k), Nat.add(1n+k, x), Equal.cong(Nat, Nat, z => Nat.add(x, z), U32.to_nat(len), 1n+k, ek), FD.nat__add_comm(x, 1n+k)), hw)

def nzb(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, +eo: {U32.to_nat(off) == x : Nat},
    +hd: {Nat.is_lt(d, 28n) == True{} : Bool}, +hw: {Nat.is_le(Nat.add(x, U32.to_nat(len)), A.quad(VB.pw(d))) == True{} : Bool},
    +pf: {FD.array__perfect(U32, d, t) == True{} : Bool}, +b: Bool, +eb: {U32.is_eq(U32.div(len, 1), 0) == b : Bool})
    -> {T.pl_bool_ok_nz(b, BF(t, n), off, U32.div(len, 1)) == (BF(t, n), CHKw(t, x, off, len)) : B.Buf & Bool}:
  match b:
    case True{}:
      +e0 = Equal.trans(Nat, U32.to_nat(len), U32.to_nat(U32.div(len, 1)), 0n, em(len),
        Equal.cong(U32, Nat, z => U32.to_nat(z), U32.div(len, 1), 0, FD.u32alg__eq_of(U32.div(len, 1), 0, eb)))
      %Equal.sym(Nat, U32.to_nat(len), 0n, e0) : {(BF(t, n), True{}) == (BF(t, n), VRB.ALLB(UW.WX(t, x, _))) : B.Buf & Bool}
      {==}
    case False{}:
      +M = U32.div(len, 1)
      +k = U32.to_nat(U32.sub(M, 1))
      +h1 = VRL.cposu(M, U32.to_nat(M), {==}, eb)
      +ek = Equal.trans(Nat, U32.to_nat(len), U32.to_nat(M), 1n+k, em(len),
        Equal.trans(Nat, U32.to_nat(M), 1n+Nat.sub(U32.to_nat(M), 1n), 1n+k, s1(U32.to_nat(M), h1),
          Equal.cong(Nat, Nat, z => 1n+z, Nat.sub(U32.to_nat(M), 1n), k, Equal.sym(Nat, k, Nat.sub(U32.to_nat(M), 1n), FD.u32__sub_nat(M, 1, h1)))))
      +hwk = FD.logic__subst(Nat, z => {Nat.is_le(Nat.add(x, z), A.quad(VB.pw(d))) == True{} : Bool}, U32.to_nat(len), 1n+k, ek, hw)
      +hx = FD.nat__lt_le_trans(x, Nat.add(x, 1n+k), A.quad(VB.pw(d)), VTX.ltp(x, k), hwk)
      %Equal.sym(B.Buf & Bool, O.ok_bool(BF(t, n), off), (BF(t, n), U32.is_le(VRB.BX(t, x), 1)), VRB.okb(d, t, n, off, x, eo, hd, pf, hx)) :
        {T.pl_bool_ck(k, 0, off, True{}, _) == (BF(t, n), CHKw(t, x, off, len)) : B.Buf & Bool}
      %Equal.sym(Nat, U32.to_nat(len), 1n+k, ek) :
        {T.pl_bool_ck(k, 0, off, True{}, (BF(t, n), U32.is_le(VRB.BX(t, x), 1))) == (BF(t, n), VRB.ALLB(UW.WX(t, x, _))) : B.Buf & Bool}
      ck(k, d, t, n, off, x, 0, 0n, True{}, eo, {==}, hd, pf, hbk(d, x, len, k, ek, hw))

# The validator on the window returns the buffer and CHKw.
def ok_evalw(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, +eo: {U32.to_nat(off) == x : Nat},
    +hd: {Nat.is_lt(d, 28n) == True{} : Bool}, +hw: {Nat.is_le(Nat.add(x, U32.to_nat(len)), A.quad(VB.pw(d))) == True{} : Bool},
    +pf: {FD.array__perfect(U32, d, t) == True{} : Bool})
    -> {T.pl_bool_ok(BF(t, n), off, len) == (BF(t, n), CHKw(t, x, off, len)) : B.Buf & Bool}:
  %Equal.sym(Bool, Bool.and(U32.is_eq(len, (U32.div(len, 1) * 1 : U32)), True{}), True{}, chk1(len)) :
    {T.pl_bool_ok_len(_, BF(t, n), off, len) == (BF(t, n), CHKw(t, x, off, len)) : B.Buf & Bool}
  nzb(d, t, n, x, off, len, eo, hd, hw, pf, U32.is_eq(U32.div(len, 1), 0), {==})
@READW
# ---- the spec side ------------------------------------------------------------------------------

def vb(xs: +List<U32>) -> S.Value:
  match xs:
    case Nil{}: S.EmptyItems{}
    case Con{x, t}: S.Items{S.BooleanValue{U32.is_eq(x, 1)}, vb(t)}

def VALw(+t: FD.array__Tree<U32>, +x: Nat, +len: U32) -> S.Value: S.Sequence{vb(UW.WX(t, x, U32.to_nat(len)))}

law prt_b:
  for +xs: +List<U32>
  for +h: {VRB.ALLB(xs) == True{} : Bool}
  {Codec.parts(vb(xs), S.Repeat{S.Boolean{}}) == Some{U8.sparts(xs)} : Maybe<&2, +List<S.Part>>}
def prt_b(xs, h):
  match xs:
    case Nil{}: {==}
    case Con{+x, +t}:
      F.cat_fixed(Codec.parts(S.BooleanValue{U32.is_eq(x, 1)}, S.Boolean{}), [x], Codec.parts(vb(t), S.Repeat{S.Boolean{}}), U8.sparts(t),
        SP2.bool_part(x, FD.logic__and_left(U32.is_le(x, 1), VRB.ALLB(t), h)), prt_b(t, FD.logic__and_right(U32.is_le(x, 1), VRB.ALLB(t), h)))

# The progressive list of the booleans of a string of bytes 0 and 1: one variable part, the string.
def prog_parts(+xs: +List<U32>, +hb: {VRB.ALLB(xs) == True{} : Bool}, +hdm: {SP.bytes_domain(xs) == True{} : Bool},
    +hfit: {N.fits(4n, List.length(&2, U32, xs)) == True{} : Bool})
    -> {Codec.parts(S.Sequence{vb(xs)}, Spec.@X()) == Some{[S.Variable{xs}]} : Maybe<&2, +List<S.Part>>}:
  +L = List.length(&2, U32, xs)
  %Equal.sym(Maybe<&2, +List<S.Part>>, Codec.parts(vb(xs), S.Repeat{S.Boolean{}}), Some{U8.sparts(xs)}, prt_b(xs, hb)) :
    {Codec.aggregate(_, None{}) == Some{[S.Variable{xs}]} : Maybe<&2, +List<S.Part>>}
  %Equal.sym(Maybe<&2, +List<U32>>, Layout.encoding(U8.sparts(xs)), Some{List.append(&2, U32, xs, [])},
      VMV.enc_gen(U8.sparts(xs), L, xs, [], U8.sp_size(xs), U8.sp_fp(xs, L), U8.sp_pay(xs), U8.scope_valid(L, xs, U8.dom_scope(xs, hdm)),
        FD.logic__subst(Nat, z => {N.fits(4n, z) == True{} : Bool}, L, Nat.add(L, 0n), Equal.sym(Nat, Nat.add(L, 0n), L, FD.nat__add_zero(L)), hfit))) :
    {Codec.one(_, None{}) == Some{[S.Variable{xs}]} : Maybe<&2, +List<S.Part>>}
  %Equal.sym(+List<U32>, List.append(&2, U32, xs, []), xs, VS.app_nil(xs)) : {Codec.one(Some{_}, None{}) == Some{[S.Variable{xs}]} : Maybe<&2, +List<S.Part>>}
  {==}

# The spec parts of the value: one variable part, the window's bytes.
def specw(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, +eo: {U32.to_nat(off) == x : Nat},
    +hd: {Nat.is_lt(d, 28n) == True{} : Bool}, +hw: {Nat.is_le(Nat.add(x, U32.to_nat(len)), A.quad(VB.pw(d))) == True{} : Bool},
    +pf: {FD.array__perfect(U32, d, t) == True{} : Bool}, +hchk: {CHKw(t, x, off, len) == True{} : Bool})
    -> {Codec.parts(VALw(t, x, len), Spec.@X()) == Some{[S.Variable{UW.WX(t, x, U32.to_nat(len))}]} : Maybe<&2, +List<S.Part>>}:
  +Y = UW.WX(t, x, U32.to_nat(len))
  +hf = FD.logic__subst(Nat, z => {N.fits(4n, z) == True{} : Bool}, U32.to_nat(len), List.length(&2, U32, Y),
    Equal.sym(Nat, List.length(&2, U32, Y), U32.to_nat(len), UW.lenWX(d, t, x, U32.to_nat(len), pf, hw)),
    VFT.fits4(2n+d, U32.to_nat(len), hlen(d, x, len, hw), FD.nat__lt_trans(d, 28n, 30n, hd, {==})))
  prog_parts(Y, hchk, UW.domWX(t, x, U32.to_nat(len)), hf)

# Every value whose spec parts are the window's bytes has only bytes 0 and 1 there.
def invw(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +x: Nat, +off: U32, +len: U32, +eo: {U32.to_nat(off) == x : Nat},
    +hd: {Nat.is_lt(d, 28n) == True{} : Bool}, +hw: {Nat.is_le(Nat.add(x, U32.to_nat(len)), A.quad(VB.pw(d))) == True{} : Bool},
    +pf: {FD.array__perfect(U32, d, t) == True{} : Bool}, +v: S.Value,
    +e: {Codec.parts(v, Spec.@X()) == Some{[S.Variable{UW.WX(t, x, U32.to_nat(len))}]} : Maybe<&2, +List<S.Part>>})
    -> {CHKw(t, x, off, len) == True{} : Bool}:
  match v:
    case S.Sequence{+its}:
      VRB.agg_m(its, Codec.parts(its, S.Repeat{S.Boolean{}}), {==}, None{}, UW.WX(t, x, U32.to_nat(len)),
        Equal.cong(Maybe<&2, +List<S.Part>>, Maybe<&2, +List<U32>>, z => Codec.bytes(z), Codec.aggregate(Codec.parts(its, S.Repeat{S.Boolean{}}), None{}),
          Some{[S.Variable{UW.WX(t, x, U32.to_nat(len))}]}, e))
@ABSURDV
"""


def ck_text():
    """fix_reject_chk.py's loop lemma for the boolean check O.ok_bool, for T.pl_bool_ck."""
    import fix_reject_chk as FRC
    t = FRC.name_text('PLB', 'g', 'pl_bool', 1, 'vec')
    a = t.index('# the check loop')
    b = t.index('def PLB_at')
    return t[a:b].replace('PLB_ck', 'ck').replace('UA.BF(t, n)', 'BF(t, n)').rstrip() + '\n'


WIN_IMPORTS = ['import ../../spec/root_relation.bend as RR', 'import ./vua_rd.bend as UR', 'import ./big_vvlz.bend as VZG', 'import ./vu8.bend as U8', 'import ./vmv.bend as VMV',
               'import ./pb_min.bend as PB', 'import ./vrl.bend as VRL', 'import ./vrejb.bend as VRB',
               'import ./vua_fix.bend as VTX', 'import ./vua.bend as UA', 'import ./sub_pack.bend as SP2']


def win_text(k):
    X, p = KINDS[k]
    body = {'u8': WIN_U8, 'u16': WIN_U16, 'bool': WIN_BOOL}[k].replace('@READW', READW)
    if k == 'bool':
        body = body.replace('@CK', ck_text()).replace('@ABSURDV', absurd_v('{CHKw(t, x, off, len) == True{} : Bool}'))
    if k == 'u16':
        body = body.replace('@REP', rep16_text()).replace('@ABSURDV', absurd_v('{CHKw(t, x, off, len) == True{} : Bool}'))
    body = body.replace('@X(', f'{X}(').replace('@p_', f'{p}_')
    L = generic(VW.HEADX) + WIN_IMPORTS + ['', HDR,
                                           f'# ProgressiveList[{ {"u8": "uint8", "u16": "uint16", "bool": "boolean"}[k] }] ({X}) at a window of any byte offset x:',
                                           '# the interface of proofs/obj/vua_win.bend.', '']
    return '\n'.join(L) + VW.COMMONX + body


def top_text(k):
    X, p = KINDS[k]
    el = {'u8': 'S.Unsigned{P.U8{}}', 'u16': 'S.Unsigned{P.U16{}}', 'bool': 'S.Boolean{}'}[k]
    import types
    txt = VW.top_text(types.SimpleNamespace(n=X), win_fname(k).name, [])
    txt = txt.replace('Codec.parts(items, S.End{})', f'Codec.parts(items, S.Repeat{{{el}}})')
    txt = txt.replace('# GENERATED by codegen/var_win.py. Do not edit.', HDR)
    # the byte-offset window's object also takes the tree's depth
    old = f'def OBJ(+t: FD.array__Tree<U32>, +n: U32) -> T.{X}: W.OBJw(t, 0n, 0, n)'
    assert old in txt
    txt = txt.replace(old, 'def OBJ(+d: Nat, +t: FD.array__Tree<U32>, +n: U32) -> O.Words: W.OBJw(d, t, 0n, 0, n)')
    txt = txt.replace(f'T.{X}_ok(', f'T.{p}_ok(').replace(f'T.{X}_read(', f'T.{p}_read(')
    txt = txt.replace('OBJ(t, n)', 'OBJ(d, t, n)').replace(f'T.{X}_', '@@').replace(f'T.{X}', 'O.Words').replace('@@', f'T.{X}_')
    return '\n'.join(generic(txt.split('\n')))


def unique_text(k):
    X, p = KINDS[k]
    D = top_fname(X, '_top').name
    return '\n'.join(['import Base', 'import ../../types/schema.bend as S', 'import ../../spec/decoding_relation.bend as Decoding',
                      'import ../compact/found.bend as FD', 'import ../compact/arith.bend as A', 'import ./vbuf.bend as VB',
                      'import ./generic_specs.bend as GS', f'import ./{D} as DC', 'import ../../proofs/decode_complete.bend as DCO', '',
                      HDR, '# Every spec value of an accepted buffer\'s bytes is the decoded value.',
                      'law decode_unique:', '  for +d: Nat', '  for +t: FD.array__Tree<U32>', '  for +n: U32',
                      '  for +pf: {FD.array__perfect(U32, d, t) == True{} : Bool}', '  for +hd: {Nat.is_lt(d, 28n) == True{} : Bool}',
                      '  for +hn: {Nat.is_le(U32.to_nat(n), A.quad(VB.pw(d))) == True{} : Bool}',
                      '  for +hchk: {DC.CHK(t, n) == True{} : Bool}', '  for +v: S.Value',
                      f'  for spec: Decoding.decodes(GS.{X}(), DC.VW(t, n), v)', '  {v == DC.VAL(t, n) : S.Value}',
                      'def decode_unique(d, t, n, pf, hd, hn, hchk, v, spec):',
                      f'  DCO.valid_unique(GS.{X}(), DC.VW(t, n), v, DC.VAL(t, n), {{==}}, spec, DC.decode_spec(d, t, n, pf, hd, hn, hchk))']) + '\n'


ENC = r"""
def OBJ(+T: FD.array__Tree<U32>, +N: U32) -> O.Words: O.Words{FD.array__thaw(U32, T), N}
def OUT(+T: FD.array__Tree<U32>, +N: U32) -> B.Buf: B.Buf{FD.array__thaw(U32, VLS.OUTP(N, T)), N}

# The object's words fit its storage.
def hsrc(+dw: Nat, +N: U32, +hdw: {Nat.is_lt(dw, 28n) == True{} : Bool}, +hN: {Nat.is_le(U32.to_nat(N), A.quad(VB.pw(dw))) == True{} : Bool})
    -> {Nat.is_le(Nat.add(VC.NW(N), 0n), VB.pw(dw)) == True{} : Bool}:
  UW.hsx(dw, 0, 0n, N, {==}, hdw, hN)

def leWo(+dw: Nat, +N: U32, +hdw: {Nat.is_lt(dw, 28n) == True{} : Bool}, +hN: {Nat.is_le(U32.to_nat(N), A.quad(VB.pw(dw))) == True{} : Bool})
    -> {Nat.is_le(U32.to_nat(VC.nwu(N)), O.pow2n(dw)) == True{} : Bool}:
  +h = FD.logic__subst(Nat, z => {Nat.is_le(z, VB.pw(dw)) == True{} : Bool}, Nat.add(VC.NW(N), 0n), VC.NW(N), FD.nat__add_zero(VC.NW(N)), hsrc(dw, N, hdw, hN))
  FD.logic__subst(Nat, z => {Nat.is_le(VC.NW(N), z) == True{} : Bool}, VB.pw(dw), O.pow2n(dw), VD.s_pow2_eq(dw), h)

# The encoder's output depth is at most dw, and holds the words.
def hDO(+dw: Nat, +N: U32, +hdw: {Nat.is_lt(dw, 28n) == True{} : Bool}, +hN: {Nat.is_le(U32.to_nat(N), A.quad(VB.pw(dw))) == True{} : Bool})
    -> {Nat.is_le(VLS.DO(N), dw) == True{} : Bool}:
  VD.wd_min(VC.nwu(N), dw, leWo(dw, N, hdw, hN))

def hdsto(+dw: Nat, +N: U32, +hdw: {Nat.is_lt(dw, 28n) == True{} : Bool}, +hN: {Nat.is_le(U32.to_nat(N), A.quad(VB.pw(dw))) == True{} : Bool})
    -> {Nat.is_le(Nat.add(VC.NW(N), 0n), VB.pw(VLS.DO(N))) == True{} : Bool}:
  %Equal.sym(Nat, Nat.add(VC.NW(N), 0n), VC.NW(N), FD.nat__add_zero(VC.NW(N))) : {Nat.is_le(_, VB.pw(VLS.DO(N))) == True{} : Bool}
  %Equal.sym(Nat, VB.pw(VLS.DO(N)), O.pow2n(VLS.DO(N)), VD.s_pow2_eq(VLS.DO(N))) : {Nat.is_le(VC.NW(N), _) == True{} : Bool}
  VD.wd_cover(VC.nwu(N), dw, FD.nat__le_trans(dw, 28n, 32n, FD.nat__lt_le(dw, 28n, hdw), {==}), leWo(dw, N, hdw, hN))

# The encoder returns the object and the buffer of OUTP(N, T), N bytes.
law encode_eval:
  for +dw: Nat
  for +T: FD.array__Tree<U32>
  for +N: U32
  for +pfT: {FD.array__perfect(U32, dw, T) == True{} : Bool}
  for +hdw: {Nat.is_lt(dw, 28n) == True{} : Bool}
  for +hN: {Nat.is_le(U32.to_nat(N), A.quad(VB.pw(dw))) == True{} : Bool}
  {T.@X_encode(OBJ(T, N)) == (OBJ(T, N), OUT(T, N)) : O.Words & B.Buf}
def encode_eval(dw, T, N, pfT, hdw, hN):
  +hdw31 = FD.nat__lt_trans(dw, 28n, 31n, hdw, {==})
  +DO = VLS.DO(N)
  %Equal.sym(Array<U32> & U32, Array.size(U32, FD.array__thaw(U32, T)), (FD.array__thaw(U32, T), FD.u32__pow2u(dw)), FD.array__size_thaw(U32, dw, T, pfT)) :
    {T.@X_enc_sized(O.wsz_pick(N, _)) == (OBJ(T, N), OUT(T, N)) : O.Words & B.Buf}
  %Equal.sym(Bool, U32.is_le(VC.nwu(N), FD.u32__pow2u(dw)), True{}, VE.le_room(N, dw, hdw31, hsrc(dw, N, hdw, hN))) :
    {T.@X_enc_sized((OBJ(T, N), O.pick(_, N, 2147483648))) == (OBJ(T, N), OUT(T, N)) : O.Words & B.Buf}
  %Equal.sym(Array<U32>, B.zeros(B.words_depth_u(VC.nwu(N))), Array.new(U32, DO, 0),
      FD.logic__subst(Nat, z => {B.zeros(B.words_depth_u(VC.nwu(N))) == Array.new(U32, z, 0) : Array<U32>}, U32.to_nat(B.words_depth_u(VC.nwu(N))), DO, VD.wdu(VC.nwu(N)), VZG.zg(B.words_depth_u(VC.nwu(N))))) :
    {T.@X_enc_put(N, T.@p_putn(_, 0, OBJ(T, N))) == (OBJ(T, N), OUT(T, N)) : O.Words & B.Buf}
  %Equal.sym(Array<U32>, Array.new(U32, DO, 0), FD.array__thaw(U32, VC.ZT(DO)), FD.array__new(U32, DO, 0)) :
    {T.@X_enc_put(N, T.@p_putn(_, 0, OBJ(T, N))) == (OBJ(T, N), OUT(T, N)) : O.Words & B.Buf}
  %Equal.sym(Array<U32> & O.Words, O.put_words(FD.array__thaw(U32, VC.ZT(DO)), 0, OBJ(T, N)), (FD.array__thaw(U32, VLS.OUTP(N, T)), OBJ(T, N)),
      VBE.put_words_any(DO, dw, VC.ZT(DO), T, 0, 0n, N, VLS.KK(dw), FD.array__trep_perfect(U32, DO, 0), pfT,
        FD.nat__le_lt_trans(DO, dw, 31n, hDO(dw, N, hdw, hN), hdw31), hdw31, {==}, {==}, VLS.kk_lt(dw, hdw), VLS.hyn(dw, N, hN),
        hsrc(dw, N, hdw, hN), hdsto(dw, N, hdw, hN), VBE.slot_zt(DO, Nat.add(VYS.QL(N), 0n)))) :
    {T.@X_enc_put(N, O.pwn(_)) == (OBJ(T, N), OUT(T, N)) : O.Words & B.Buf}
  {==}

# The output's bytes are the object's first N bytes.
def out_eq(+dw: Nat, +T: FD.array__Tree<U32>, +N: U32, +pfT: {FD.array__perfect(U32, dw, T) == True{} : Bool},
    +hdw: {Nat.is_lt(dw, 28n) == True{} : Bool}, +hN: {Nat.is_le(U32.to_nat(N), A.quad(VB.pw(dw))) == True{} : Bool})
    -> {VS.bt(U32.to_nat(N), F.limbs(FD.array__slots(U32, VLS.OUTP(N, T)))) == UW.WX(T, 0n, U32.to_nat(N)) : +List<U32>}:
  +s = FD.array__slots(U32, T)
  +Z = FD.array__slots(U32, VC.ZT(VLS.DO(N)))
  +LM = VB.lm(VC.NW(N), 0n, 0n, Z, s)
  +hd0 = hdsto(dw, N, hdw, hN)
  +hsl = FD.logic__subst(Nat, z => {Nat.is_le(Nat.add(VC.NW(N), 0n), z) == True{} : Bool}, VB.pw(dw), VB.len(s), Equal.sym(Nat, VB.len(s), VB.pw(dw), FD.array__slots_length(U32, dw, T, pfT)), hsrc(dw, N, hdw, hN))
  +hz = FD.logic__subst(Nat, z => {Nat.is_le(Nat.add(VC.NW(N), 0n), z) == True{} : Bool}, VB.pw(VLS.DO(N)), VB.len(Z),
    Equal.sym(Nat, VB.len(Z), VB.pw(VLS.DO(N)), FD.array__slots_length(U32, VLS.DO(N), VC.ZT(VLS.DO(N)), FD.array__trep_perfect(U32, VLS.DO(N), 0))), hd0)
  %Equal.sym(List<&2, U32>, FD.array__slots(U32, VLS.OUTP(N, T)), LM,
      VB.slots_mone(VC.NW(N), 0n, 0n, VLS.DO(N), VC.ZT(VLS.DO(N)), T, FD.array__trep_perfect(U32, VLS.DO(N), 0), hd0)) :
    {VS.bt(U32.to_nat(N), F.limbs(_)) == UW.WX(T, 0n, U32.to_nat(N)) : +List<U32>}
  VBE.bytes_frame(U32.to_nat(N), VC.NW(N), 0n, LM, s, VBS.quad_nw_ge(N, VLS.KK(dw), VLS.kk_lt(dw, hdw), VLS.hyn(dw, N, hN)),
    VB.lm_win(VC.NW(N), 0n, 0n, Z, s, hz, hsl))

# The bytes of the encoder's buffer are the spec encoding of the object's value.
law encode_spec:
  for +dw: Nat
  for +T: FD.array__Tree<U32>
  for +N: U32
  for +pfT: {FD.array__perfect(U32, dw, T) == True{} : Bool}
  for +hdw: {Nat.is_lt(dw, 28n) == True{} : Bool}
  for +hN: {Nat.is_le(U32.to_nat(N), A.quad(VB.pw(dw))) == True{} : Bool}
@SHYP  Decoding.decodes(Spec.@X(), VS.bt(U32.to_nat(N), F.limbs(FD.array__slots(U32, VLS.OUTP(N, T)))), W.VALw(T, 0n, N))
def encode_spec(dw, T, N, pfT, hdw, hN@SARG):
  %Equal.sym(Maybe<&2, +List<S.Part>>, Codec.parts(W.VALw(T, 0n, N), Spec.@X()), Some{[S.Variable{UW.WX(T, 0n, U32.to_nat(N))}]},
      W.specw(dw, T, N, 0n, 0, N, {==}, hdw, hN, pfT, @CHK)) :
    {Codec.bytes(_) == Some{VS.bt(U32.to_nat(N), F.limbs(FD.array__slots(U32, VLS.OUTP(N, T))))} : Maybe<&2, +List<U32>>}
  Equal.cong(+List<U32>, Maybe<&2, +List<U32>>, z => Some{z}, UW.WX(T, 0n, U32.to_nat(N)), VS.bt(U32.to_nat(N), F.limbs(FD.array__slots(U32, VLS.OUTP(N, T)))),
    Equal.sym(+List<U32>, VS.bt(U32.to_nat(N), F.limbs(FD.array__slots(U32, VLS.OUTP(N, T)))), UW.WX(T, 0n, U32.to_nat(N)), out_eq(dw, T, N, pfT, hdw, hN)))
"""


def enc_text(k):
    X, p = KINDS[k]
    chk = {'u8': 'W.chk(T, 0n, 0, N)', 'u16': 'W.chk2(T, 0n, 0, N, c, ec)', 'bool': 'hb'}[k]
    shyp, sarg = {'u8': ('', ''), 'u16': ('  for +c: Nat\n  for +ec: {U32.to_nat(N) == Nat.double(c) : Nat}\n', ', c, ec'),
                  'bool': ('  for +hb: {W.CHKw(T, 0n, 0, N) == True{} : Bool}\n', ', hb')}[k]
    body = ENC.replace('@X', X).replace('@p_', f'{p}_').replace('@CHK', chk).replace('@SHYP', shyp).replace('@SARG', sarg)
    L = generic(VW.HEADX) + ['import ./big_vvlz.bend as VZG', 'import ./venc.bend as VE', 'import ./vbenc.bend as VBE', 'import ./vbspec.bend as VBS', 'import ./vbytes.bend as VYS',
                             f'import ./{win_fname(k).name} as W', '', HDR,
                             f'# The encoder of {X}: for every object O.Words{{thaw(T), N}} whose storage T is a perfect',
                             '# tree of depth dw < 28 with room for its N bytes, the encoder returns the object and',
                             '# B.Buf{thaw(OUTP(N, T)), N} (encode_eval), and the bytes of that buffer are the spec',
                             '# encoding of the object\'s value, the list of its first N bytes (encode_spec).', '']
    return '\n'.join(L) + body


# ---- the encoder-window interface (encx): the list written at any byte position X = 4 q + r ------

ENCX = r"""
# The object's Data mirror: storage tree T of depth dw holding N bytes.
type MW is Data:
  MW{dw: Nat, T: FD.array__Tree<U32>, N: U32}

def TH(m: MW) -> O.Words:
  match m:
    case MW{+dw, +T, +N}: O.Words{FD.array__thaw(U32, T), N}

@PRE
# A valid object: a perfect tree of depth < 28 with room for its N bytes, zero past them in
# the last word@OKDOC.
def OKT(+dw: Nat, +T: FD.array__Tree<U32>, +N: U32) -> Bool:
  Bool.and(FD.array__perfect(U32, dw, T), Bool.and(Nat.is_lt(dw, 28n), Bool.and(Nat.is_le(U32.to_nat(N), A.quad(VB.pw(dw))),
    Bool.and(O.tail_zero(U32.and(N, 3), VB.slot(T, VYS.QL(N))), @EXTRA))))
def OK(m: MW) -> Bool:
  match m:
    case MW{+dw, +T, +N}: OKT(dw, T, N)

def ENC(m: MW) -> +List<U32>:
  match m:
    case MW{+dw, +T, +N}: VS.bt(U32.to_nat(N), F.limbs(FD.array__slots(U32, T)))
def VAL(m: MW) -> S.Value:
  match m:
    case MW{+dw, +T, +N}: W.VALw(T, 0n, N)
def SZ(m: MW) -> U32:
  match m:
    case MW{+dw, +T, +N}: N
def PUTX(m: MW, +dd: Nat, +D: FD.array__Tree<U32>, +q: Nat, +r: Nat) -> FD.array__Tree<U32>:
  match m:
    case MW{+dw, +T, +N}: VWD.PWM(r, dd, D, q, T, N)
def PADB(+r: Nat, m: MW) -> Nat: VWD.PADB(r, List.length(&2, U32, ENC(m)))

# The pieces of OKT.
def ok_pf(+dw: Nat, +T: FD.array__Tree<U32>, +N: U32, +h: {OKT(dw, T, N) == True{} : Bool}) -> {FD.array__perfect(U32, dw, T) == True{} : Bool}:
  FD.logic__and_left(FD.array__perfect(U32, dw, T), Bool.and(Nat.is_lt(dw, 28n), Bool.and(Nat.is_le(U32.to_nat(N), A.quad(VB.pw(dw))), Bool.and(O.tail_zero(U32.and(N, 3), VB.slot(T, VYS.QL(N))), @EXTRA))), h)
def ok_r1(+dw: Nat, +T: FD.array__Tree<U32>, +N: U32, +h: {OKT(dw, T, N) == True{} : Bool})
    -> {Bool.and(Nat.is_lt(dw, 28n), Bool.and(Nat.is_le(U32.to_nat(N), A.quad(VB.pw(dw))), Bool.and(O.tail_zero(U32.and(N, 3), VB.slot(T, VYS.QL(N))), @EXTRA))) == True{} : Bool}:
  FD.logic__and_right(FD.array__perfect(U32, dw, T), Bool.and(Nat.is_lt(dw, 28n), Bool.and(Nat.is_le(U32.to_nat(N), A.quad(VB.pw(dw))), Bool.and(O.tail_zero(U32.and(N, 3), VB.slot(T, VYS.QL(N))), @EXTRA))), h)
def ok_hd(+dw: Nat, +T: FD.array__Tree<U32>, +N: U32, +h: {OKT(dw, T, N) == True{} : Bool}) -> {Nat.is_lt(dw, 28n) == True{} : Bool}:
  FD.logic__and_left(Nat.is_lt(dw, 28n), Bool.and(Nat.is_le(U32.to_nat(N), A.quad(VB.pw(dw))), Bool.and(O.tail_zero(U32.and(N, 3), VB.slot(T, VYS.QL(N))), @EXTRA)), ok_r1(dw, T, N, h))
def ok_r2(+dw: Nat, +T: FD.array__Tree<U32>, +N: U32, +h: {OKT(dw, T, N) == True{} : Bool})
    -> {Bool.and(Nat.is_le(U32.to_nat(N), A.quad(VB.pw(dw))), Bool.and(O.tail_zero(U32.and(N, 3), VB.slot(T, VYS.QL(N))), @EXTRA)) == True{} : Bool}:
  FD.logic__and_right(Nat.is_lt(dw, 28n), Bool.and(Nat.is_le(U32.to_nat(N), A.quad(VB.pw(dw))), Bool.and(O.tail_zero(U32.and(N, 3), VB.slot(T, VYS.QL(N))), @EXTRA)), ok_r1(dw, T, N, h))
def ok_hN(+dw: Nat, +T: FD.array__Tree<U32>, +N: U32, +h: {OKT(dw, T, N) == True{} : Bool}) -> {Nat.is_le(U32.to_nat(N), A.quad(VB.pw(dw))) == True{} : Bool}:
  FD.logic__and_left(Nat.is_le(U32.to_nat(N), A.quad(VB.pw(dw))), Bool.and(O.tail_zero(U32.and(N, 3), VB.slot(T, VYS.QL(N))), @EXTRA), ok_r2(dw, T, N, h))
def ok_r3(+dw: Nat, +T: FD.array__Tree<U32>, +N: U32, +h: {OKT(dw, T, N) == True{} : Bool})
    -> {Bool.and(O.tail_zero(U32.and(N, 3), VB.slot(T, VYS.QL(N))), @EXTRA) == True{} : Bool}:
  FD.logic__and_right(Nat.is_le(U32.to_nat(N), A.quad(VB.pw(dw))), Bool.and(O.tail_zero(U32.and(N, 3), VB.slot(T, VYS.QL(N))), @EXTRA), ok_r2(dw, T, N, h))
def ok_tz(+dw: Nat, +T: FD.array__Tree<U32>, +N: U32, +h: {OKT(dw, T, N) == True{} : Bool}) -> {O.tail_zero(U32.and(N, 3), VB.slot(T, VYS.QL(N))) == True{} : Bool}:
  FD.logic__and_left(O.tail_zero(U32.and(N, 3), VB.slot(T, VYS.QL(N))), @EXTRA, ok_r3(dw, T, N, h))
def ok_ex(+dw: Nat, +T: FD.array__Tree<U32>, +N: U32, +h: {OKT(dw, T, N) == True{} : Bool}) -> {@EXTRA == True{} : Bool}:
  FD.logic__and_right(O.tail_zero(U32.and(N, 3), VB.slot(T, VYS.QL(N))), @EXTRA, ok_r3(dw, T, N, h))

def hsrc(+dw: Nat, +N: U32, +hdw: {Nat.is_lt(dw, 28n) == True{} : Bool}, +hN: {Nat.is_le(U32.to_nat(N), A.quad(VB.pw(dw))) == True{} : Bool})
    -> {Nat.is_le(Nat.add(VC.NW(N), 0n), VB.pw(dw)) == True{} : Bool}:
  UW.hsx(dw, 0, 0n, N, {==}, hdw, hN)

def eL(+dw: Nat, +T: FD.array__Tree<U32>, +N: U32, +h: {OKT(dw, T, N) == True{} : Bool}) -> {List.length(&2, U32, ENC(MW{dw, T, N})) == U32.to_nat(N) : Nat}:
  UW.lenWX(dw, T, 0n, U32.to_nat(N), ok_pf(dw, T, N, h), ok_hN(dw, T, N, h))

# The storage check with no upper bound (big), for any unit the length satisfies.
def wok(+dw: Nat, +T: FD.array__Tree<U32>, +N: U32, +unit: U32, +pfT: {FD.array__perfect(U32, dw, T) == True{} : Bool},
    +hdw: {Nat.is_lt(dw, 28n) == True{} : Bool}, +hN: {Nat.is_le(U32.to_nat(N), A.quad(VB.pw(dw))) == True{} : Bool},
    +htz: {O.tail_zero(U32.and(N, 3), VB.slot(T, VYS.QL(N))) == True{} : Bool}, +hu: {O.unit_ok(unit, N) == True{} : Bool})
    -> {O.words_ok(O.Words{FD.array__thaw(U32, T), N}, 0, 0, True{}, unit) == (O.Words{FD.array__thaw(U32, T), N}, True{}) : O.Words & Bool}:
  +hdw31 = FD.nat__lt_trans(dw, 28n, 31n, hdw, {==})
  %Equal.sym(Array<U32> & U32, Array.size(U32, FD.array__thaw(U32, T)), (FD.array__thaw(U32, T), FD.u32__pow2u(dw)), FD.array__size_thaw(U32, dw, T, pfT)) :
    {O.wk_cap(Bool.and(Bool.and(U32.is_le(0, N), Bool.or(True{}, U32.is_le(N, 0))), O.unit_ok(unit, N)), N, _) == (O.Words{FD.array__thaw(U32, T), N}, True{}) : O.Words & Bool}
  %Equal.sym(Bool, U32.is_le(0, N), True{}, VE.le_hi(0, N, FD.nat__zero_le(U32.to_nat(N)))) :
    {O.wk_last(Bool.and(Bool.and(Bool.and(_, Bool.or(True{}, U32.is_le(N, 0))), O.unit_ok(unit, N)), U32.is_le(VC.nwu(N), FD.u32__pow2u(dw))), N, Array.get(U32, FD.array__thaw(U32, T), U32.shrn(N, 2n))) == (O.Words{FD.array__thaw(U32, T), N}, True{}) : O.Words & Bool}
  %Equal.sym(Bool, U32.is_le(VC.nwu(N), FD.u32__pow2u(dw)), True{}, VE.le_room(N, dw, hdw31, hsrc(dw, N, hdw, hN))) :
    {O.wk_last(Bool.and(Bool.and(Bool.and(True{}, Bool.or(True{}, U32.is_le(N, 0))), O.unit_ok(unit, N)), _), N, Array.get(U32, FD.array__thaw(U32, T), U32.shrn(N, 2n))) == (O.Words{FD.array__thaw(U32, T), N}, True{}) : O.Words & Bool}
  %Equal.sym(Bool, O.unit_ok(unit, N), True{}, hu) :
    {O.wk_last(Bool.and(Bool.and(Bool.and(True{}, Bool.or(True{}, U32.is_le(N, 0))), _), True{}), N, Array.get(U32, FD.array__thaw(U32, T), U32.shrn(N, 2n))) == (O.Words{FD.array__thaw(U32, T), N}, True{}) : O.Words & Bool}
  VBE.wob_go(dw, T, N, VLS.KK(dw), pfT, hdw31, VLS.kk_lt(dw, hdw), VLS.hyn(dw, N, hN), hsrc(dw, N, hdw, hN), htz, U32.is_eq(VYS.RM(N), 0), {==})
@VALID
def putx_go(+dw: Nat, +T: FD.array__Tree<U32>, +N: U32, +dd: Nat, +D: FD.array__Tree<U32>, +X: U32, +q: Nat, +r: Nat,
    +e: {U32.to_nat(X) == Nat.add(A.quad(q), r) : Nat}, +hr: {Nat.is_lt(r, 4n) == True{} : Bool}, +hd: {Nat.is_lt(dd, 29n) == True{} : Bool},
    +pf: {FD.array__perfect(U32, dd, D) == True{} : Bool},
    +hl: {Nat.is_le(Nat.add(q, VWD.NWN(Nat.add(r, U32.to_nat(N)))), VB.pw(dd)) == True{} : Bool},
    +hz: {VS.bt(Nat.add(U32.to_nat(N), VWD.PADB(r, U32.to_nat(N))), VS.bdr(Nat.add(A.quad(q), r), UA.BYT(D))) == UWW.ZB(Nat.add(U32.to_nat(N), VWD.PADB(r, U32.to_nat(N)))) : +List<U32>},
    +h: {OKT(dw, T, N) == True{} : Bool})
    -> {O.put_words(FD.array__thaw(U32, D), X, O.Words{FD.array__thaw(U32, T), N}) == (FD.array__thaw(U32, VWD.PWM(r, dd, D, q, T, N)), O.Words{FD.array__thaw(U32, T), N}) : Array<U32> & O.Words}:
  +hdw = ok_hd(dw, T, N, h)
  +hN = ok_hN(dw, T, N, h)
  VWD.putw_any(dd, D, X, q, r, dw, T, N, VLS.KK(dw), e, hr, hd, FD.nat__lt_trans(dw, 28n, 31n, hdw, {==}), VLS.kk_lt(dw, hdw), VLS.hyn(dw, N, hN),
    FD.logic__subst(Nat, z => {Nat.is_le(z, VB.pw(dw)) == True{} : Bool}, Nat.add(VC.NW(N), 0n), VC.NW(N), FD.nat__add_zero(VC.NW(N)), hsrc(dw, N, hdw, hN)),
    hl, pf, ok_pf(dw, T, N, h), ok_tz(dw, T, N, h), hz)

def bytes_go(+dw: Nat, +T: FD.array__Tree<U32>, +N: U32, +dd: Nat, +D: FD.array__Tree<U32>, +X: U32, +q: Nat, +r: Nat,
    +e: {U32.to_nat(X) == Nat.add(A.quad(q), r) : Nat}, +hr: {Nat.is_lt(r, 4n) == True{} : Bool}, +hd: {Nat.is_lt(dd, 29n) == True{} : Bool},
    +pf: {FD.array__perfect(U32, dd, D) == True{} : Bool},
    +hl: {Nat.is_le(Nat.add(q, VWD.NWN(Nat.add(r, U32.to_nat(N)))), VB.pw(dd)) == True{} : Bool},
    +hz: {VS.bt(Nat.add(U32.to_nat(N), VWD.PADB(r, U32.to_nat(N))), VS.bdr(Nat.add(A.quad(q), r), UA.BYT(D))) == UWW.ZB(Nat.add(U32.to_nat(N), VWD.PADB(r, U32.to_nat(N)))) : +List<U32>},
    +h: {OKT(dw, T, N) == True{} : Bool})
    -> {UA.BYT(VWD.PWM(r, dd, D, q, T, N)) == UWW.SPL(UA.BYT(D), Nat.add(A.quad(q), r), List.append(&2, U32, VS.bt(U32.to_nat(N), F.limbs(FD.array__slots(U32, T))), UWW.ZB(VWD.PADB(r, U32.to_nat(N))))) : +List<U32>}:
  +hdw = ok_hd(dw, T, N, h)
  +hN = ok_hN(dw, T, N, h)
  VWD.putw_any_bytes(dd, D, X, q, r, dw, T, N, VLS.KK(dw), e, hr, hd, FD.nat__lt_trans(dw, 28n, 31n, hdw, {==}), VLS.kk_lt(dw, hdw), VLS.hyn(dw, N, hN),
    FD.logic__subst(Nat, z => {Nat.is_le(z, VB.pw(dw)) == True{} : Bool}, Nat.add(VC.NW(N), 0n), VC.NW(N), FD.nat__add_zero(VC.NW(N)), hsrc(dw, N, hdw, hN)),
    hl, pf, ok_pf(dw, T, N, h), ok_tz(dw, T, N, h), hz)

# ---- the interface's laws ----------------------------------------------------------------------

law putx:
  for +m: MW
  for +dd: Nat
  for +D: FD.array__Tree<U32>
  for +X: U32
  for +q: Nat
  for +r: Nat
  for +e: {U32.to_nat(X) == Nat.add(A.quad(q), r) : Nat}
  for +hr: {Nat.is_lt(r, 4n) == True{} : Bool}
  for +hd: {Nat.is_lt(dd, 29n) == True{} : Bool}
  for +pf: {FD.array__perfect(U32, dd, D) == True{} : Bool}
  for +hl: {Nat.is_le(Nat.add(q, VWD.NWN(Nat.add(r, List.length(&2, U32, ENC(m))))), VB.pw(dd)) == True{} : Bool}
  for +hz: {VS.bt(Nat.add(List.length(&2, U32, ENC(m)), PADB(r, m)), VS.bdr(Nat.add(A.quad(q), r), UA.BYT(D))) == UWW.ZB(Nat.add(List.length(&2, U32, ENC(m)), PADB(r, m))) : +List<U32>}
  for +hok: {OK(m) == True{} : Bool}
  {T.@p_putk(FD.array__thaw(U32, D), X, TH(m)) == (FD.array__thaw(U32, PUTX(m, dd, D, q, r)), (TH(m), SZ(m))) : Array<U32> & (O.Words & U32)}
def putx(m, dd, D, X, q, r, e, hr, hd, pf, hl, hz, hok):
  match m:
    case MW{+dw, +T, +N}:
      +E = List.length(&2, U32, ENC(MW{dw, T, N}))
      +eE = eL(dw, T, N, hok)
      +hl2 = FD.logic__subst(Nat, z => {Nat.is_le(Nat.add(q, VWD.NWN(Nat.add(r, z))), VB.pw(dd)) == True{} : Bool}, E, U32.to_nat(N), eE, hl)
      +hz2 = FD.logic__subst(Nat, z => {VS.bt(Nat.add(z, VWD.PADB(r, z)), VS.bdr(Nat.add(A.quad(q), r), UA.BYT(D))) == UWW.ZB(Nat.add(z, VWD.PADB(r, z))) : +List<U32>}, E, U32.to_nat(N), eE, hz)
      %Equal.sym(O.Words & Bool, T.@p_valid(O.Words{FD.array__thaw(U32, T), N}), (O.Words{FD.array__thaw(U32, T), N}, True{}), valid(dw, T, N, hok)) :
        {T.@p_pk(FD.array__thaw(U32, D), X, _) == (FD.array__thaw(U32, VWD.PWM(r, dd, D, q, T, N)), (O.Words{FD.array__thaw(U32, T), N}, N)) : Array<U32> & (O.Words & U32)}
      %Equal.sym(Array<U32> & O.Words, O.put_words(FD.array__thaw(U32, D), X, O.Words{FD.array__thaw(U32, T), N}), (FD.array__thaw(U32, VWD.PWM(r, dd, D, q, T, N)), O.Words{FD.array__thaw(U32, T), N}),
          putx_go(dw, T, N, dd, D, X, q, r, e, hr, hd, pf, hl2, hz2, hok)) :
        {O.pwn(_) == (FD.array__thaw(U32, VWD.PWM(r, dd, D, q, T, N)), (O.Words{FD.array__thaw(U32, T), N}, N)) : Array<U32> & (O.Words & U32)}
      {==}

law putx_bytes:
  for +m: MW
  for +dd: Nat
  for +D: FD.array__Tree<U32>
  for +X: U32
  for +q: Nat
  for +r: Nat
  for +e: {U32.to_nat(X) == Nat.add(A.quad(q), r) : Nat}
  for +hr: {Nat.is_lt(r, 4n) == True{} : Bool}
  for +hd: {Nat.is_lt(dd, 29n) == True{} : Bool}
  for +pf: {FD.array__perfect(U32, dd, D) == True{} : Bool}
  for +hl: {Nat.is_le(Nat.add(q, VWD.NWN(Nat.add(r, List.length(&2, U32, ENC(m))))), VB.pw(dd)) == True{} : Bool}
  for +hz: {VS.bt(Nat.add(List.length(&2, U32, ENC(m)), PADB(r, m)), VS.bdr(Nat.add(A.quad(q), r), UA.BYT(D))) == UWW.ZB(Nat.add(List.length(&2, U32, ENC(m)), PADB(r, m))) : +List<U32>}
  for +hok: {OK(m) == True{} : Bool}
  {UA.BYT(PUTX(m, dd, D, q, r)) == UWW.SPL(UA.BYT(D), Nat.add(A.quad(q), r), List.append(&2, U32, ENC(m), UWW.ZB(PADB(r, m)))) : +List<U32>}
def putx_bytes(m, dd, D, X, q, r, e, hr, hd, pf, hl, hz, hok):
  match m:
    case MW{+dw, +T, +N}:
      +E = List.length(&2, U32, ENC(MW{dw, T, N}))
      +eE = eL(dw, T, N, hok)
      +hl2 = FD.logic__subst(Nat, z => {Nat.is_le(Nat.add(q, VWD.NWN(Nat.add(r, z))), VB.pw(dd)) == True{} : Bool}, E, U32.to_nat(N), eE, hl)
      +hz2 = FD.logic__subst(Nat, z => {VS.bt(Nat.add(z, VWD.PADB(r, z)), VS.bdr(Nat.add(A.quad(q), r), UA.BYT(D))) == UWW.ZB(Nat.add(z, VWD.PADB(r, z))) : +List<U32>}, E, U32.to_nat(N), eE, hz)
      %Equal.sym(Nat, E, U32.to_nat(N), eE) : {UA.BYT(VWD.PWM(r, dd, D, q, T, N)) == UWW.SPL(UA.BYT(D), Nat.add(A.quad(q), r), List.append(&2, U32, VS.bt(U32.to_nat(N), F.limbs(FD.array__slots(U32, T))), UWW.ZB(VWD.PADB(r, _)))) : +List<U32>}
      bytes_go(dw, T, N, dd, D, X, q, r, e, hr, hd, pf, hl2, hz2, hok)

law pfx:
  for +m: MW
  for +dd: Nat
  for +D: FD.array__Tree<U32>
  for +q: Nat
  for +r: Nat
  for +pf: {FD.array__perfect(U32, dd, D) == True{} : Bool}
  {FD.array__perfect(U32, dd, PUTX(m, dd, D, q, r)) == True{} : Bool}
def pfx(m, dd, D, q, r, pf):
  match m:
    case MW{+dw, +T, +N}: VWD.pwm_perfect(r, dd, D, q, T, N, pf)

law szx:
  for +m: MW
  for +hok: {OK(m) == True{} : Bool}
  {U32.to_nat(SZ(m)) == List.length(&2, U32, ENC(m)) : Nat}
def szx(m, hok):
  match m:
    case MW{+dw, +T, +N}: Equal.sym(Nat, List.length(&2, U32, ENC(MW{dw, T, N})), U32.to_nat(N), eL(dw, T, N, hok))

law sizex:
  for +m: MW
  for +hok: {OK(m) == True{} : Bool}
  {T.@p_size(TH(m)) == (TH(m), SZ(m)) : O.Words & U32}
def sizex(m, hok):
  match m:
    case MW{+dw, +T, +N}:
      +hdw = ok_hd(dw, T, N, hok)
      %Equal.sym(Array<U32> & U32, Array.size(U32, FD.array__thaw(U32, T)), (FD.array__thaw(U32, T), FD.u32__pow2u(dw)), FD.array__size_thaw(U32, dw, T, ok_pf(dw, T, N, hok))) :
        {O.wsz_pick(N, _) == (O.Words{FD.array__thaw(U32, T), N}, N) : O.Words & U32}
      %Equal.sym(Bool, U32.is_le(VC.nwu(N), FD.u32__pow2u(dw)), True{}, VE.le_room(N, dw, FD.nat__lt_trans(dw, 28n, 31n, hdw, {==}), hsrc(dw, N, hdw, ok_hN(dw, T, N, hok)))) :
        {(O.Words{FD.array__thaw(U32, T), N}, O.pick(_, N, 2147483648)) == (O.Words{FD.array__thaw(U32, T), N}, N) : O.Words & U32}
      {==}

law encx_spec:
  for +m: MW
  for +hok: {OK(m) == True{} : Bool}
  {Codec.parts(VAL(m), Spec.@X()) == Some{[S.Variable{ENC(m)}]} : Maybe<&2, +List<S.Part>>}
def encx_spec(m, hok):
  match m:
    case MW{+dw, +T, +N}: W.specw(dw, T, N, 0n, 0, N, {==}, ok_hd(dw, T, N, hok), ok_hN(dw, T, N, hok), ok_pf(dw, T, N, hok), @CHK)

law validx:
  for +m: MW
  for +hok: {OK(m) == True{} : Bool}
  {T.@p_valid(TH(m)) == (TH(m), True{}) : O.Words & Bool}
def validx(m, hok):
  match m:
    case MW{+dw, +T, +N}: valid(dw, T, N, hok)
"""

ENCX_KIND = {
    'u8': dict(EXTRA='True{}', OKDOC='', CHK='W.chk(T, 0n, 0, N)', VALID="""
def valid(+dw: Nat, +T: FD.array__Tree<U32>, +N: U32, +h: {OKT(dw, T, N) == True{} : Bool})
    -> {T.pl_u8_valid(O.Words{FD.array__thaw(U32, T), N}) == (O.Words{FD.array__thaw(U32, T), N}, True{}) : O.Words & Bool}:
  wok(dw, T, N, 1, ok_pf(dw, T, N, h), ok_hd(dw, T, N, h), ok_hN(dw, T, N, h), ok_tz(dw, T, N, h), {==})
"""),
}

ENCX_KIND['u16'] = dict(EXTRA='Bool.and(U32.is_eq(U32.and(N, 1), 0), W.CHKw(T, 0n, 0, N))', OKDOC=', an even length',
    CHK='FD.logic__and_right(U32.is_eq(U32.and(N, 1), 0), W.CHKw(T, 0n, 0, N), ok_ex(dw, T, N, hok))', VALID="""
def valid(+dw: Nat, +T: FD.array__Tree<U32>, +N: U32, +h: {OKT(dw, T, N) == True{} : Bool})
    -> {T.pl_u16_valid(O.Words{FD.array__thaw(U32, T), N}) == (O.Words{FD.array__thaw(U32, T), N}, True{}) : O.Words & Bool}:
  wok(dw, T, N, 2, ok_pf(dw, T, N, h), ok_hd(dw, T, N, h), ok_hN(dw, T, N, h), ok_tz(dw, T, N, h),
    FD.logic__and_left(U32.is_eq(U32.and(N, 1), 0), W.CHKw(T, 0n, 0, N), ok_ex(dw, T, N, h)))
""")

ENCX_KIND['bool'] = dict(EXTRA='Bool.and(BOM(VC.NW(N), 0, True{}, dw, T), W.CHKw(T, 0n, 0, N))',
    OKDOC=',\n# every byte of its words at most 1 (the runtime word check, BOM) and of its N bytes (CHKw)',
    CHK='FD.logic__and_right(BOM(VC.NW(N), 0, True{}, dw, T), W.CHKw(T, 0n, 0, N), ok_ex(dw, T, N, hok))', PRE="""
# The runtime's boolean check of the first k words from word i (O.bo_go), on the tree's words.
def BOM(k: Nat, +i: U32, acc: Bool, +dw: Nat, +T: FD.array__Tree<U32>) -> Bool:
  match k:
    case 0n: acc
    case 1n+q: BOM(q, U32.add(i, 1), Bool.and(acc, U32.is_eq(U32.and(RD.wd(T, dw, i), 4278124286), 0)), dw, T)

law bog:
  for +k: Nat
  for +i: U32
  for +acc: Bool
  for +dw: Nat
  for +T: FD.array__Tree<U32>
  for +hdw: {Nat.is_lt(dw, 32n) == True{} : Bool}
  for +pfT: {FD.array__perfect(U32, dw, T) == True{} : Bool}
  {O.bo_go(k, i, acc, (FD.array__thaw(U32, T), RD.wd(T, dw, i))) == (FD.array__thaw(U32, T), BOM(k, i, acc, dw, T)) : Array<U32> & Bool}
def bog(k, i, acc, dw, T, hdw, pfT):
  match k:
    case 0n: {==}
    case 1n+ +q:
      +a2 = Bool.and(acc, U32.is_eq(U32.and(RD.wd(T, dw, i), 4278124286), 0))
      %Equal.sym(Array<U32> & U32, Array.get(U32, FD.array__thaw(U32, T), U32.add(i, 1)), (FD.array__thaw(U32, T), RD.wd(T, dw, U32.add(i, 1))), VE.get_any(dw, T, U32.add(i, 1), hdw, pfT)) :
        {O.bo_go(q, U32.add(i, 1), a2, _) == (FD.array__thaw(U32, T), BOM(q, U32.add(i, 1), a2, dw, T)) : Array<U32> & Bool}
      bog(q, U32.add(i, 1), a2, dw, T, hdw, pfT)
""", VALID="""
def valid(+dw: Nat, +T: FD.array__Tree<U32>, +N: U32, +h: {OKT(dw, T, N) == True{} : Bool})
    -> {T.pl_bool_valid(O.Words{FD.array__thaw(U32, T), N}) == (O.Words{FD.array__thaw(U32, T), N}, True{}) : O.Words & Bool}:
  +pf = ok_pf(dw, T, N, h)
  +hdw32 = FD.nat__lt_trans(dw, 28n, 32n, ok_hd(dw, T, N, h), {==})
  %Equal.sym(O.Words & Bool, O.words_ok(O.Words{FD.array__thaw(U32, T), N}, 0, 0, True{}, 1), (O.Words{FD.array__thaw(U32, T), N}, True{}),
      wok(dw, T, N, 1, pf, ok_hd(dw, T, N, h), ok_hN(dw, T, N, h), ok_tz(dw, T, N, h), {==})) :
    {O.bools_ok(_) == (O.Words{FD.array__thaw(U32, T), N}, True{}) : O.Words & Bool}
  %Equal.sym(Array<U32> & U32, Array.get(U32, FD.array__thaw(U32, T), 0), (FD.array__thaw(U32, T), RD.wd(T, dw, 0)), VE.get_any(dw, T, 0, hdw32, pf)) :
    {O.bools_fin(N, True{}, O.bo_go(VC.NW(N), 0, True{}, _)) == (O.Words{FD.array__thaw(U32, T), N}, True{}) : O.Words & Bool}
  %Equal.sym(Array<U32> & Bool, O.bo_go(VC.NW(N), 0, True{}, (FD.array__thaw(U32, T), RD.wd(T, dw, 0))), (FD.array__thaw(U32, T), BOM(VC.NW(N), 0, True{}, dw, T)),
      bog(VC.NW(N), 0, True{}, dw, T, hdw32, pf)) :
    {O.bools_fin(N, True{}, _) == (O.Words{FD.array__thaw(U32, T), N}, True{}) : O.Words & Bool}
  %Equal.sym(Bool, BOM(VC.NW(N), 0, True{}, dw, T), True{}, FD.logic__and_left(BOM(VC.NW(N), 0, True{}, dw, T), W.CHKw(T, 0n, 0, N), ok_ex(dw, T, N, h))) :
    {O.bools_fin(N, True{}, (FD.array__thaw(U32, T), _)) == (O.Words{FD.array__thaw(U32, T), N}, True{}) : O.Words & Bool}
  {==}
""")


def encx_fname(k):
    return ROOT / f'proofs/obj/big_encx_{KINDS[k][1]}.bend'


def encx_text(k):
    X, p = KINDS[k]
    kd = ENCX_KIND[k]
    body = ENCX.replace('@PRE', kd.get('PRE', '')).replace('@VALID', kd['VALID']).replace('@EXTRA', kd['EXTRA']).replace('@OKDOC', kd['OKDOC']).replace('@CHK', kd['CHK'])
    body = body.replace('@X(', f'{X}(').replace('@p_', f'{p}_')
    L = generic(VW.HEADX) + ['import ./venc.bend as VE', 'import ./vbenc.bend as VBE', 'import ./vbytes.bend as VYS', 'import ./vua.bend as UA',
                             'import ./vuw.bend as UWW', 'import ./vuwd.bend as VWD', 'import ../compact/reads.bend as RD',
                             f'import ./{win_fname(k).name} as W', '', HDR,
                             f'# {X} (T.{p}_*) in the encoder-window interface: the list written at any byte position',
                             '# X = 4 q + r of a perfect tree D of depth dd < 29 (vuwd.putw_any / putw_any_bytes).', '']
    return '\n'.join(L) + body


# ---- bounded lists of uint16 (List[uint16, N], codec-var's windows var_winx_l<N>_u16) in encx form ---------

L16 = [1024, 128, 123]


def l16_kind(N):
    C1 = f'Nat.is_le(U32.to_nat(N), U32.to_nat({2 * N}))'
    C2 = 'U32.is_eq(U32.and(N, 1), 0)'
    C3 = 'W.CHKw(T, 0n, 0, N)'
    EX = f'Bool.and({C1}, Bool.and({C2}, {C3}))'
    return dict(EXTRA=EX, OKDOC=f', at most {2 * N} bytes, an even length', CHK=f'FD.logic__and_right({C2}, {C3}, FD.logic__and_right({C1}, Bool.and({C2}, {C3}), ok_ex(dw, T, N, hok)))',
                VALID=f"""
def valid(+dw: Nat, +T: FD.array__Tree<U32>, +N: U32, +h: {{OKT(dw, T, N) == True{{}} : Bool}})
    -> {{T.l{N}_u16_valid(O.Words{{FD.array__thaw(U32, T), N}}) == (O.Words{{FD.array__thaw(U32, T), N}}, True{{}}) : O.Words & Bool}}:
  +ex = ok_ex(dw, T, N, h)
  +hdw = ok_hd(dw, T, N, h)
  +hN = ok_hN(dw, T, N, h)
  VBE.words_ok_b(dw, T, N, 0, {2 * N}, VLS.KK(dw), ok_pf(dw, T, N, h), FD.nat__lt_trans(dw, 28n, 31n, hdw, {{==}}), VLS.kk_lt(dw, hdw), VLS.hyn(dw, N, hN),
    FD.nat__zero_le(U32.to_nat(N)), FD.logic__and_left({C1}, Bool.and({C2}, {C3}), ex), hsrc(dw, N, hdw, hN), ok_tz(dw, T, N, h), 2,
    FD.logic__and_left({C2}, {C3}, FD.logic__and_right({C1}, Bool.and({C2}, {C3}), ex)))
""")


def l16_fname(N):
    return ROOT / f'proofs/obj/big_encx_l{N}_u16.bend'


def l16_text(N):
    kd = l16_kind(N)
    p = f'l{N}_u16'
    body = ENCX.replace('@PRE', '').replace('@VALID', kd['VALID']).replace('@EXTRA', kd['EXTRA']).replace('@OKDOC', kd['OKDOC']).replace('@CHK', kd['CHK'])
    body = body.replace('Spec.@X()', f'S.ListOf{{S.Unsigned{{P.U16{{}}}}, {N}n}}').replace('@p_', f'{p}_')
    assert '@' not in body.replace('&2', ''), [l for l in body.split('\n') if '@' in l.replace('&2', '')][:3]
    L = generic(VW.HEADX) + ['import ./venc.bend as VE', 'import ./vbenc.bend as VBE', 'import ./vbytes.bend as VYS', 'import ./vua.bend as UA',
                             'import ./vuw.bend as UWW', 'import ./vuwd.bend as VWD', 'import ../compact/reads.bend as RD',
                             f'import ./var_winx_{p}.bend as W', '', HDR,
                             f'# List[uint16, {N}] (T.{p}_*) in the encoder-window interface: the list written at any byte position',
                             '# X = 4 q + r of a perfect tree D of depth dd < 29 (vuwd.putw_any / putw_any_bytes).', '']
    return '\n'.join(L) + body


# ---- ByteList[N] of the generic forms in encx form (var_rec_enc.bl_text over generic_obj, schema S.ByteList{N}) ----

GBL = [('bl256', 256)]


def gbl_fname(q):
    return ROOT / f'proofs/obj/big_encx_{q}.bend'


def gbl_text(q, N):
    import var_rec_enc as RE
    txt = RE.bl_text(q, 'GBLSCHX', N).replace('Spec.GBLSCHX()', f'S.ByteList{{{N}n}}')
    assert 'GBLSCHX' not in txt
    txt = txt.replace('# GENERATED by codegen/var_rec_enc.py. Do not edit.', HDR)
    return '\n'.join(generic(txt.split('\n')))


# ---- ProgressiveBits at a byte-offset window (var_win's BitList window with no bound) ----------

def cut(text, start, end):
    a = text.index(start)
    b = text.index(end, a)
    return text[:a] + text[b:]


def pbits_text():
    b = VW.Bits(0, 'pbits', 'Spec.GtF7582E0E9A()', '0n')
    body = VW.bitsx_text(b)
    head, body = body.split('\ndef BF(', 1)
    body = '\ndef BF(' + body
    # the validator's bound check is off (big = True)
    body = body.replace('O.bsel(False{}, True{}, ', 'O.bsel(True{}, True{}, ')
    body = body.replace('off, len, 0, False{})', 'off, len, 0, True{})').replace('O.bitlist_pick(len, 0, False{}, _)', 'O.bitlist_pick(len, 0, True{}, _)')
    body = body.replace('# A bit list\'s window: non-empty, a non-zero last byte, at most 0 bits.', '# A progressive bit list\'s window: non-empty, a non-zero last byte (no bound).')
    # no length bound: drop cC, hB, hdzK, zeros_at
    body = cut(body, 'def cC(', 'def cE(')
    body = cut(body, 'def hB(', 'def NB(')
    body = body.replace("""  +hz = hdzK(d, len, hd, hL, hB(t, off, len, e1, cC(t, off, len, h1, cB(t, off, len, h1))))
  +ez = zeros_at(B.words_depth_u(VC.WZ(len)), VLS.DZ(len), VD.wdu(VC.WZ(len)), hz)""", """  +hz = VLS.hdz29(d, len, hd, hL)
  +ez = FD.logic__subst(Nat, z => {B.zeros(B.words_depth_u(VC.WZ(len))) == Array.new(U32, z, 0) : Array<U32>}, U32.to_nat(B.words_depth_u(VC.WZ(len))), VLS.DZ(len),
    VD.wdu(VC.WZ(len)), VZG.zg(B.words_depth_u(VC.WZ(len))))""")
    body = body.replace(f'FD.nat__le_lt_trans(VLS.DZ(len), {b.K}n, 31n, hz, {{==}})', 'FD.nat__le_lt_trans(VLS.DZ(len), 29n, 31n, hz, {==})')
    # the spec: the list encoding at the bits' own length
    body = body.replace('  +bd = cC(t, off, len, h1, nz)\n', '')
    body = cut(body, '  +bd1 = FD.logic__subst(Nat, z => {Nat.is_le(Nat.add(z, U32.to_nat(O.high_bit(V(t, off, len)))), U32.to_nat(0))', '  %Equal.sym(Nat, U32.to_nat(len), 1n+m, e1) :\n    {Codec.parts(S.BitsValue')
    body = body.replace('  VBC.bl_parts(W1, 0n, dom, nzl, hl)',
                        '  VBC.bl_parts(W1, List.length(&2, Bool, VBL.bl(W1)), dom, nzl, FD.nat__le_refl(List.length(&2, Bool, VBL.bl(W1))))')
    # the inversion: every bit list is in the domain
    body = body.replace(''',
    +nz: {U32.is_eq(V(t, off, len), 0) == False{} : Bool}, +bd: {Nat.is_le(BD(t, off, len), U32.to_nat(0)) == True{} : Bool})
    -> {CHKw(t, x, off, len) == True{} : Bool}:''', ''',
    +nz: {U32.is_eq(V(t, off, len), 0) == False{} : Bool})
    -> {CHKw(t, x, off, len) == True{} : Bool}:''')
    body = body.replace('''  %Equal.sym(Bool, U32.is_eq(V(t, off, len), 0), False{}, nz) : {O.bsel(_, False{}, O.bsel(True{}, True{}, Nat.is_le(BD(t, off, len), U32.to_nat(0)))) == True{} : Bool}
  bd''', '''  %Equal.sym(Bool, U32.is_eq(V(t, off, len), 0), False{}, nz) : {O.bsel(_, False{}, O.bsel(True{}, True{}, Nat.is_le(BD(t, off, len), U32.to_nat(0)))) == True{} : Bool}
  {==}''')
    body = body.replace('+bits: +List<Bool>, +hb: {Nat.is_le(List.length(&2, Bool, bits), 0n) == True{} : Bool}, +pk:', '+bits: +List<Bool>, +pk:')
    body = cut(body, '  +eBD = Equal.trans(Nat, BD(t, off, len)', '  chk_true(t, x, off, len, m, e1, nz, bd)')
    body = body.replace('  chk_true(t, x, off, len, m, e1, nz, bd)', '  chk_true(t, x, off, len, m, e1, nz)')
    body = body.replace('+bits: +List<Bool>, +b: Bool, +eb: {Nat.is_le(List.length(&2, Bool, bits), 0n) == b : Bool},',
                        '+bits: +List<Bool>, +b: Bool, +eb: {Nat.is_le(List.length(&2, Bool, bits), List.length(&2, Bool, bits)) == b : Bool},')
    body = body.replace('inv_t(d, t, x, off, len, eo, hd, hw, pf, bits, eb, var_inj', 'inv_t(d, t, x, off, len, eo, hd, hw, pf, bits, var_inj')
    body = body.replace('inv_b(d, t, x, off, len, eo, hd, hw, pf, bits, Nat.is_le(List.length(&2, Bool, bits), 0n), {==}, e)',
                        'inv_b(d, t, x, off, len, eo, hd, hw, pf, bits, Nat.is_le(List.length(&2, Bool, bits), List.length(&2, Bool, bits)), {==}, e)')
    for bad in ['hdzK', 'zeros_at', 'hB(', 'cC(', 'bd1', ', bd)']:
        assert bad not in body, (bad, [l for l in body.split('\n') if bad in l][:3])
    L = generic(VW.HEADX) + ['import ./big_vvlz.bend as VZG', '', HDR,
                             '# ProgressiveBits (GtF7582E0E9A, runtime pbits) at a window of any byte offset x: the',
                             '# interface of proofs/obj/vua_win.bend (var_win BitList window with the bound removed).', '']
    return '\n'.join(L) + body


PBITS_FNAME = ROOT / 'proofs/obj/big_var_winp_pbits.bend'


# ---- ProgressiveList[uint64] at a byte-offset window (var_win's List[uint64, 2^40] window, no bound) --

REQ_INV = """
# A list's parts with the bound check passed are its aggregate's.
def req_inv(+b: Bool, +A: Maybe<&2, +List<S.Part>>, +P: +List<S.Part>, +e: {Codec.require(b, A) == Some{P} : Maybe<&2, +List<S.Part>>})
    -> {A == Some{P} : Maybe<&2, +List<S.Part>>}:
  match b:
    case False{}: Empty.absurd({A == Some{P} : Maybe<&2, +List<S.Part>>}, FD.logic__none_some(+List<S.Part>, P, e))
    case True{}: e
"""


def plu64_text():
    body = VW.listx40_text('pl_u64', 'Spec.GtE83F21B20A()', 'S.Unsigned{P.U64{}}', 'LIMX')
    head, body = body.split('\ndef BF(', 1)
    body = '\ndef BF(' + body
    a = body.index('def hcL(')
    body = body[:a] + body[body.index('\ndef ', a) + 1:]
    a = body.index('  V40.list_u64_partsk(k, W, LIMX, hcL(t, x, off, len, hchk),')
    b = body.index('\n', body.index('FD.nat__le_refl(Nat.double(k))))', a))
    call = body[a:b]
    call = call.replace('  V40.list_u64_partsk(k, W, LIMX, hcL(t, x, off, len, hchk),',
                        '  req_inv(Nat.is_le(Codec.count(VS.uitems(k, W)), k), Codec.aggregate(Codec.parts(VS.uitems(k, W), S.Repeat{S.Unsigned{P.U64{}}}), None{}),\n'
                        '    [S.Variable{F.limbs(VS.wtake(Nat.double(k), W))}], V40.list_u64_partsk(k, W, k, FD.nat__le_refl(k),') + ')'
    body = body[:a] + call + body[b:]
    body = body.replace('+c: Nat, +hk: {Nat.is_le(c, LIMX) == True{} : Bool},', '+c: Nat, +hk: {Nat.is_le(c, c) == True{} : Bool},')
    body = body.replace('+hk: {Nat.is_le(Codec.count(its), LIMX) == True{} : Bool},', '+hk: {Nat.is_le(Codec.count(its), Codec.count(its)) == True{} : Bool},')
    body = cut(body, 'def ivb(', '# Every value whose spec parts')
    body = body.replace('    case S.Sequence{+its}: ivb(d, t, x, off, len, hw, pf, its, Nat.is_le(Codec.count(its), LIMX), {==}, e)',
                        '    case S.Sequence{+its}: ivm3(d, t, x, off, len, hw, pf, its, FD.nat__le_refl(Codec.count(its)), Codec.parts(its, S.Repeat{S.Unsigned{P.U64{}}}), {==}, e)')
    body = body.replace('# Whole elements (a U32 length is below the limit).', '# Whole elements (no limit).')
    assert 'LIMX' not in body and 'hcL' not in body, [l for l in body.split('\n') if 'LIMX' in l or 'hcL' in l][:3]
    L = generic(head.split('\n')[:-1]) + ['', HDR, '# ProgressiveList[uint64] (GtE83F21B20A, runtime pl_u64) at a window of any byte offset x:',
                                          '# the interface of proofs/obj/vua_win.bend (the List[uint64, 2^40] window with the bound removed).', '']
    L = [l for l in L if not l.startswith('# GENERATED by codegen/var_win.py') and not l.startswith('# List[uint64, 2^40] at a window')]
    return '\n'.join(L) + REQ_INV + body


PLU64_FNAME = ROOT / 'proofs/obj/big_var_winp_pl_u64.bend'

# ProgressiveList[uint64] (pl_u64) in encx form, over its window big_var_winp_pl_u64 (unit 8).
PLU64X_FNAME = ROOT / 'proofs/obj/big_encx_pl_u64.bend'
U64EX = 'Bool.and(U32.is_eq(U32.and(N, 7), 0), W.CHKw(T, 0n, 0, N))'


def plu64x_text():
    kd = dict(EXTRA=U64EX, OKDOC=', a multiple of 8',
              CHK='FD.logic__and_right(U32.is_eq(U32.and(N, 7), 0), W.CHKw(T, 0n, 0, N), ok_ex(dw, T, N, hok))', VALID="""
def valid(+dw: Nat, +T: FD.array__Tree<U32>, +N: U32, +h: {OKT(dw, T, N) == True{} : Bool})
    -> {T.pl_u64_valid(O.Words{FD.array__thaw(U32, T), N}) == (O.Words{FD.array__thaw(U32, T), N}, True{}) : O.Words & Bool}:
  wok(dw, T, N, 8, ok_pf(dw, T, N, h), ok_hd(dw, T, N, h), ok_hN(dw, T, N, h), ok_tz(dw, T, N, h),
    FD.logic__and_left(U32.is_eq(U32.and(N, 7), 0), W.CHKw(T, 0n, 0, N), ok_ex(dw, T, N, h)))
""")
    body = ENCX.replace('@PRE', '').replace('@VALID', kd['VALID']).replace('@EXTRA', kd['EXTRA']).replace('@OKDOC', kd['OKDOC']).replace('@CHK', kd['CHK'])
    body = body.replace('@X(', 'GtE83F21B20A(').replace('@p_', 'pl_u64_')
    L = generic(VW.HEADX) + ['import ./venc.bend as VE', 'import ./vbenc.bend as VBE', 'import ./vbytes.bend as VYS', 'import ./vua.bend as UA',
                             'import ./vuw.bend as UWW', 'import ./vuwd.bend as VWD', 'import ../compact/reads.bend as RD',
                             f'import ./{PLU64_FNAME.name} as W', '', HDR,
                             '# GtE83F21B20A (T.pl_u64_*) in the encoder-window interface: the list written at any byte position',
                             '# X = 4 q + r of a perfect tree D of depth dd < 29 (vuwd.putw_any / putw_any_bytes).', '']
    return '\n'.join(L) + body


DONE = ['u8', 'u16', 'bool']


def outputs(no_big):
    out = {}
    if no_big:
        return out
    out[PBITS_FNAME] = pbits_text()
    for _N in L16:
        out[l16_fname(_N)] = l16_text(_N)
    for _q, _N in GBL:
        out[gbl_fname(_q)] = gbl_text(_q, _N)
    out[PLU64_FNAME] = plu64_text()
    out[PLU64X_FNAME] = plu64x_text()
    for k in DONE:
        X, p = KINDS[k]
        out[win_fname(k)] = win_text(k)
        out[top_fname(X, '_top')] = top_text(k)
        out[top_fname(X, '_top_unique')] = unique_text(k)
        out[top_fname(X, '_enc')] = enc_text(k)
        if k in ENCX_KIND:
            out[encx_fname(k)] = encx_text(k)
    return out


def main():
    no_big = '--no-big' in sys.argv
    out = outputs(no_big)
    mine = sorted((ROOT / 'proofs/obj').glob('big_var_winp_*.bend')) + [encx_fname(k) for k in KINDS if encx_fname(k).exists()] + [l16_fname(N) for N in L16 if l16_fname(N).exists()] + [gbl_fname(q) for q, N in GBL if gbl_fname(q).exists()] + ([PLU64X_FNAME] if PLU64X_FNAME.exists() else [])
    for X, _ in KINDS.values():
        mine += sorted((ROOT / 'proofs/obj').glob(f'big_var_plist_{X}*.bend'))
    orphans = [str(q.relative_to(ROOT)) for q in mine if q not in out and not no_big]
    if '--check' in sys.argv:
        stale = [str(p.relative_to(ROOT)) for p, t in out.items() if not p.exists() or p.read_text() != t]
        if stale or orphans:
            print('stale generated sub-word progressive-list laws: ' + ', '.join(stale + orphans))
            sys.exit(1)
        print('generated sub-word progressive-list laws are current')
        return
    for q in orphans:
        (ROOT / q).unlink()
    for p, t in out.items():
        p.write_text(t)
    print(', '.join(str(p.relative_to(ROOT)) for p in out))


if __name__ == '__main__':
    main()
