#!/usr/bin/env python3
"""Spec-connected codec laws of variable-size names with SEVERAL variable fields.

    python3 codegen/var_multi.py [--check] [--no-big]

Covered: DataColumnSidecar (a uint64, three lists of byte vectors held as packed
words -- Cell = 512 words, KZGCommitment / KZGProof = 12 words, 4096 elements at
most -- a boxed SignedBeaconBlockHeader and a Vector[Bytes32, 4]).

Writes proofs/obj/vmul.bend (from codegen/vmul.bend.in: the spec side of a list of
byte vectors of E words, for every E, k and word list), proofs/obj/var_fix_types_m.bend
(the reader/writer lemmas of the fixed field types, codegen/var_laws.py's rd/put
lemmas) and proofs/obj/var_codec_<X>{,_unique,_rej,_enc}.bend with the law set of
codegen/var_laws.py (ok_eval, decode_accept, decode_spec, decode_unique,
decode_reject, decode_none, encode_eval, encode_spec).

The buffer laws quantify over every buffer B.Buf{thaw(t), n} on a perfect word
tree of depth d < 23 (16 MiB; the list storage the decoder allocates then has
depth at most 23, whose zero arrays stock Bend compares case by case), n <= 4 2^d.

`--no-big` is accepted: this generator writes no big_* file.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import generate as G  # noqa: E402
import schema  # noqa: E402
import var_laws as VLW  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
X = 'DataColumnSidecar'

DEC_HEAD = ['import Base', 'import ../../src/buffer.bend as B', 'import ../../src/obj.bend as O',
            'import ../../types/fulu_obj.bend as T', 'import ../../types/schema.bend as S', 'import ../../types/primitive.bend as P',
            'import ../compact/found.bend as FD', 'import ../compact/arith.bend as A', 'import ../../proofs/nat_order.bend as Order',
            'import ../../spec/primitives.bend as SP', 'import ../../spec/layout.bend as Layout', 'import ../../spec/codec.bend as Codec',
            'import ../../spec/decoding_relation.bend as Decoding', 'import ../../spec/nat_bytes.bend as N',
            'import ../../spec/fulu_schemas.bend as Spec', 'import ./spec_fixed.bend as F', 'import ./vspec.bend as VS',
            'import ./vbuf.bend as VB', 'import ./vu32.bend as VU', 'import ./vcopy.bend as VC', 'import ./vdepth.bend as VD',
            'import ./vfix.bend as VF', 'import ./vlist.bend as VL', 'import ./vmul.bend as VM', 'import ./var_fix_types_m.bend as VT']


def fix_types(g, names):
    fts = []
    for f, ft in names[X].fields:
        if ft.fixed() and ft.kind == 'container':
            for d in VLW.FT(g, ft).deps():
                if d.p not in [x.p for x in fts]:
                    fts.append(d)
    u = VLW.FT(g, names[X].fields[0][1])
    if u.p not in [x.p for x in fts]:
        fts.insert(0, u)
    return VLW.fix_module(fts).replace('codegen/var_laws.py', 'codegen/var_multi.py (codegen/var_laws.py fix_module)')


ZK = 24


def zeros_text():
    L = ['import Base', 'import ../../src/buffer.bend as B', 'import ../compact/found.bend as FD', '',
         '# GENERATED by codegen/var_multi.py. Do not edit.',
         f'# The runtime zero array of depth k <= {ZK} is Array.new(U32, k, 0), case by case (the',
         f'# comparison of the closed trees of 2^{ZK} leaves takes about a minute on stock Bend).', '',
         f'def zat(+du: U32, +k: Nat, +e: {{U32.to_nat(du) == k : Nat}}, +hk: {{Nat.is_le(k, {ZK}n) == True{{}} : Bool}})',
         '    -> {B.zeros(du) == Array.new(U32, k, 0) : Array<U32>}:', '  match k:']
    for j in range(ZK + 1):
        L.append(f'    case {j}n:')
        L.append(f'      %Equal.sym(U32, du, {j}, FD.u32__injective(du, {j}, e)) : {{B.zeros(_) == Array.new(U32, {j}n, 0) : Array<U32>}}')
        L.append('      {==}')
    L.append(f'    case {ZK + 1}n+p: Empty.absurd({{B.zeros(du) == Array.new(U32, {ZK + 1}n+p, 0) : Array<U32>}}, FD.logic__false_true(hk))')
    return '\n'.join(L) + '\n'


def dec_text():
    L = list(DEC_HEAD) + ['', '# GENERATED by codegen/var_multi.py. Do not edit.',
                          f'# {X}: the validator, the decoder, and the spec relation of the decoded value',
                          '# (see the module docstring of codegen/var_multi.py).', '']
    L.append(DEC_BODY)
    return '\n'.join(L) + '\n'


DEC_BODY = r'''def BF(t: FD.array__Tree<U32>, +n: U32) -> B.Buf: B.Buf{FD.array__thaw(U32, t), n}

def rd32(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +q: U32, +i: Nat, +eq: {U32.to_nat(q) == i : Nat},
    +hd: {Nat.is_lt(d, 32n) == True{} : Bool}, +hi: {Nat.is_lt(i, VB.pw(d)) == True{} : Bool},
    +pf: {FD.array__perfect(U32, d, t) == True{} : Bool})
    -> {B.word(BF(t, n), q) == (BF(t, n), VB.slot(t, i)) : B.Buf & U32}:
  %Equal.sym(Array<U32> & U32, Array.get(U32, FD.array__thaw(U32, t), q), (FD.array__thaw(U32, t), VB.slot(t, i)), VB.get_n(d, t, q, i, eq, hd, hi, pf)) :
    {B.rewrap(n, _) == (BF(t, n), VB.slot(t, i)) : B.Buf & U32}
  {==}

# ---- the validator ----------------------------------------------------------------------------

# the three list offsets
def O0(t: FD.array__Tree<U32>) -> U32: VB.slot(t, 2n)
def O1(t: FD.array__Tree<U32>) -> U32: VB.slot(t, 3n)
def O2(t: FD.array__Tree<U32>) -> U32: VB.slot(t, 4n)

# a list of whole elements of b bytes, at most lim of them
def WH(+L: U32, +b: U32, +lim: U32) -> Bool: Bool.and(U32.is_eq(L, (U32.div(L, b) * b : U32)), U32.is_le(U32.div(L, b), lim))

def L0(+t: FD.array__Tree<U32>) -> U32: U32.sub(O1(t), O0(t))
def L1(+t: FD.array__Tree<U32>) -> U32: U32.sub(O2(t), O1(t))
def L2(+t: FD.array__Tree<U32>, +n: U32) -> U32: U32.sub(n, O2(t))

def CA(+n: U32) -> Bool: U32.is_le(356, n)
def CB(+t: FD.array__Tree<U32>) -> Bool: U32.is_eq(O0(t), 356)
def CC(+t: FD.array__Tree<U32>, +n: U32) -> Bool: Bool.and(U32.is_le(O0(t), O1(t)), U32.is_le(O1(t), n))
def CD(+t: FD.array__Tree<U32>, +n: U32) -> Bool: Bool.and(U32.is_le(O1(t), O2(t)), U32.is_le(O2(t), n))
def CE(+t: FD.array__Tree<U32>) -> Bool: WH(L0(t), 2048, 4096)
def CF(+t: FD.array__Tree<U32>) -> Bool: WH(L1(t), 48, 4096)
def CG(+t: FD.array__Tree<U32>, +n: U32) -> Bool: WH(L2(t, n), 48, 4096)

# the checks, in the validator's order
def CHK(+t: FD.array__Tree<U32>, +n: U32) -> Bool:
  Bool.and(CA(n), Bool.and(CB(t), Bool.and(CC(t, n), Bool.and(CD(t, n), Bool.and(CE(t), Bool.and(CF(t), CG(t, n)))))))

def okG(+t: FD.array__Tree<U32>, +n: U32, +g: Bool)
    -> {T.DataColumnSidecar_c5(g, BF(t, n), 0, n, O0(t), O1(t), O2(t)) == (BF(t, n), g) : B.Buf & Bool}:
  match g:
    case True{}: {==}
    case False{}: {==}

def okF(+t: FD.array__Tree<U32>, +n: U32, +f: Bool)
    -> {T.DataColumnSidecar_c4(f, BF(t, n), 0, n, O0(t), O1(t), O2(t)) == (BF(t, n), Bool.and(f, CG(t, n))) : B.Buf & Bool}:
  match f:
    case True{}: okG(t, n, CG(t, n))
    case False{}: {==}

def okE(+t: FD.array__Tree<U32>, +n: U32, +e: Bool)
    -> {T.DataColumnSidecar_c3(e, BF(t, n), 0, n, O0(t), O1(t), O2(t)) == (BF(t, n), Bool.and(e, Bool.and(CF(t), CG(t, n)))) : B.Buf & Bool}:
  match e:
    case True{}: okF(t, n, CF(t))
    case False{}: {==}

def okD(+t: FD.array__Tree<U32>, +n: U32, +c: Bool)
    -> {T.DataColumnSidecar_c2(c, BF(t, n), 0, n, O0(t), O1(t), O2(t)) == (BF(t, n), Bool.and(c, Bool.and(CE(t), Bool.and(CF(t), CG(t, n))))) : B.Buf & Bool}:
  match c:
    case True{}: okE(t, n, CE(t))
    case False{}: {==}

def okC(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +c: Bool,
    +hd: {Nat.is_lt(d, 32n) == True{} : Bool}, +hpo: {Nat.is_lt(4n, VB.pw(d)) == True{} : Bool},
    +pf: {FD.array__perfect(U32, d, t) == True{} : Bool})
    -> {T.DataColumnSidecar_c1(c, BF(t, n), 0, n, O0(t), O1(t)) == (BF(t, n), Bool.and(c, Bool.and(CD(t, n), Bool.and(CE(t), Bool.and(CF(t), CG(t, n)))))) : B.Buf & Bool}:
  match c:
    case True{}:
      %Equal.sym(B.Buf & U32, B.word(BF(t, n), 4), (BF(t, n), O2(t)), rd32(d, t, n, 4, 4n, {==}, hd, hpo, pf)) :
        {T.DataColumnSidecar_v2(0, n, O0(t), O1(t), _) == (BF(t, n), Bool.and(CD(t, n), Bool.and(CE(t), Bool.and(CF(t), CG(t, n))))) : B.Buf & Bool}
      okD(t, n, CD(t, n))
    case False{}: {==}

def okB(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +b: Bool,
    +hd: {Nat.is_lt(d, 32n) == True{} : Bool}, +hpo: {Nat.is_lt(4n, VB.pw(d)) == True{} : Bool},
    +pf: {FD.array__perfect(U32, d, t) == True{} : Bool})
    -> {T.DataColumnSidecar_c0(b, BF(t, n), 0, n, O0(t)) == (BF(t, n), Bool.and(b, Bool.and(CC(t, n), Bool.and(CD(t, n), Bool.and(CE(t), Bool.and(CF(t), CG(t, n))))))) : B.Buf & Bool}:
  match b:
    case True{}:
      %Equal.sym(B.Buf & U32, B.word(BF(t, n), 3), (BF(t, n), O1(t)), rd32(d, t, n, 3, 3n, {==}, hd, FD.nat__lt_trans(3n, 4n, VB.pw(d), {==}, hpo), pf)) :
        {T.DataColumnSidecar_v1(0, n, O0(t), _) == (BF(t, n), Bool.and(CC(t, n), Bool.and(CD(t, n), Bool.and(CE(t), Bool.and(CF(t), CG(t, n)))))) : B.Buf & Bool}
      okC(d, t, n, CC(t, n), hd, hpo, pf)
    case False{}: {==}

def okA(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +a: Bool,
    +hd: {Nat.is_lt(d, 32n) == True{} : Bool}, +hpo: {Nat.is_lt(4n, VB.pw(d)) == True{} : Bool},
    +pf: {FD.array__perfect(U32, d, t) == True{} : Bool})
    -> {T.DataColumnSidecar_ok_len(a, BF(t, n), 0, n) == (BF(t, n), Bool.and(a, Bool.and(CB(t), Bool.and(CC(t, n), Bool.and(CD(t, n), Bool.and(CE(t), Bool.and(CF(t), CG(t, n)))))))) : B.Buf & Bool}:
  match a:
    case True{}:
      %Equal.sym(B.Buf & U32, B.word(BF(t, n), 2), (BF(t, n), O0(t)), rd32(d, t, n, 2, 2n, {==}, hd, FD.nat__lt_trans(2n, 4n, VB.pw(d), {==}, hpo), pf)) :
        {T.DataColumnSidecar_v0(0, n, _) == (BF(t, n), Bool.and(CB(t), Bool.and(CC(t, n), Bool.and(CD(t, n), Bool.and(CE(t), Bool.and(CF(t), CG(t, n))))))) : B.Buf & Bool}
      okB(d, t, n, CB(t), hd, hpo, pf)
    case False{}: {==}

# The validator returns the buffer and CHK(t, n).
law ok_eval:
  for +d: Nat
  for +t: FD.array__Tree<U32>
  for +n: U32
  for +hd: {Nat.is_lt(d, 32n) == True{} : Bool}
  for +hpo: {Nat.is_lt(4n, VB.pw(d)) == True{} : Bool}
  for +pf: {FD.array__perfect(U32, d, t) == True{} : Bool}
  {T.DataColumnSidecar_ok(BF(t, n), 0, n) == (BF(t, n), CHK(t, n)) : B.Buf & Bool}
def ok_eval(d, t, n, hd, hpo, pf): okA(d, t, n, CA(n), hd, hpo, pf)
'''


def outputs():
    names = schema.load(ROOT / 'codegen/fulu.yaml')
    g = G.Gen()
    for n, t in names.items():
        g.shape(t)
    out = {ROOT / 'proofs/obj/vmul.bend': (ROOT / 'codegen/vmul.bend.in').read_text(),
           ROOT / 'proofs/obj/var_fix_types_m.bend': fix_types(g, names),
           ROOT / 'proofs/obj/vzeros.bend': zeros_text(),
           ROOT / f'proofs/obj/var_codec_{X}.bend': dec_text()}
    return out


def main():
    out = outputs()
    if '--check' in sys.argv:
        stale = [str(p.relative_to(ROOT)) for p, t in out.items() if not p.exists() or p.read_text() != t]
        if stale:
            print('stale: ' + ', '.join(stale))
            sys.exit(1)
        print('multi-variable laws are current')
        return
    for p, t in out.items():
        p.write_text(t)
    print(f'{len(out)} files')


if __name__ == '__main__':
    main()
