#!/usr/bin/env python3
"""The fixed-size word-vector writers at ANY byte position X = 4 q + r (r < 4, symbolic),
in the tight, data-only form of vuwd's b20_any: the aligned runs of var_bytes_fix /
var_fix_types at r = 0, the unaligned writers of vuwf<s> (putu_<p>, the model SWc) at
r = 1, 2, 3.

    python3 codegen/var_uwv.py [--check]

Writes proofs/obj/vuwv_<p>.bend, one module per writer. For each writer p of N words (T.<p>_put over T.<C>{w0..}):
  PX_<p>(r, dd, D, q, w0..)   the output tree (VF.updv at r = 0, UW.SWc(r, [w0..]) otherwise)
  <p>_any        T.<p>_put(thaw D, X, T.<C>{w0..}) == thaw PX_<p>(r, dd, D, q, w0..)
  <p>_any_bytes  UA.BYT(PX_<p>(..)) == UW.SPL(UA.BYT(D), 4 q + r, FX.limbs([w0..]))
  <p>x_perfect   the model is a perfect tree
with room hl: q + NWN(r + 4 N) <= 2^dd and zero bytes hz over the 4 N data bytes only.
b256 (T.b256_putk over the O.Words of 256 bytes, validity then its copy) has the same
three laws over its storage tree TB, with data FX.limbs(VS.wtake(64n, UW.SLW(TB))).
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# (runtime prefix, constructor, words, aligned lemma)
VECS = [('b32', 'Bytes32', 8, 'VBF.put_b32'), ('u256', 'Uint256', 8, 'VBF.put_u256'), ('b48', 'Bytes48', 12, 'VBF.put_b48'),
        ('b96', 'Bytes96', 24, 'VBF.put_b96'), ('bv512', 'Bitvector512', 16, 'VBF.put_bv512'), ('bv64', 'Bitvector64', 2, 'VT.put_bv64')]

HEAD = '''import Base
import ../../src/obj.bend as O
import ../../types/fulu_obj.bend as T
import ../compact/found.bend as FD
import ../compact/arith.bend as A
import ../../proofs/nat_order.bend as Order
import ./spec_fixed.bend as FX
import ./vspec.bend as VS
import ./vbuf.bend as VB
import ./vfix.bend as VF
import ./vbrt.bend as VR
import ./vua.bend as UA
import ./vuw.bend as UW
import ./vuw1.bend as UB1
import ./vuw2.bend as UB2
import ./vuw3.bend as UB3
import ./vuwd.bend as UWD
@IMPORTS
# GENERATED by codegen/var_uwv.py. Do not edit.
# @WHAT at any byte position X = 4 q + r, in the tight, data-only form of vuwd's b20_any
# (see codegen/var_uwv.py).
'''

TH = 'FD.array__thaw(U32, {})'
E_ = '+e: {U32.to_nat(X) == Nat.add(A.quad(q), r) : Nat}, +hr: {Nat.is_lt(r, 4n) == True{} : Bool}'


def vec_text(p, C, N, AL):
    ws = [f'w{k}' for k in range(N)]
    W = ', '.join(ws)
    WP = ', '.join(f'+{w}: U32' for w in ws)
    L = f'[{W}]'
    m = 4 * N
    HL = f'+hl: {{Nat.is_le(Nat.add(q, UWD.NWN(Nat.add(r, {m}n))), VB.pw(dd)) == True{{}} : Bool}}'
    HZ = f'+hz: {{VS.bt({m}n, VS.bdr(Nat.add(A.quad(q), r), UA.BYT(D))) == UW.ZB({m}n) : +List<U32>}}'
    PF = '+pf: {FD.array__perfect(U32, dd, D) == True{} : Bool}'
    HD = '+hd: {Nat.is_lt(dd, 29n) == True{} : Bool}'
    PX = lambda r: f'PX_{p}({r}, dd, D, q, {W})'  # noqa: E731
    RT = lambda r: f'{{T.{p}_put({TH.format("D")}, X, T.{C}{{{W}}}) == {TH.format(PX(r))} : Array<U32>}}'  # noqa: E731
    BY = lambda r, x: f'{{UA.BYT({PX(r)}) == UW.SPL(UA.BYT(D), {x}, FX.limbs({L})) : +List<U32>}}'  # noqa: E731
    lq = f'UWD.le_q(q, {N}n, VB.pw(dd), hl)'
    out = [f'''
# ---- {p}: T.{C}, {N} words ----

def PX_{p}(+r: Nat, +dd: Nat, +D: FD.array__Tree<U32>, +q: Nat, {WP}) -> FD.array__Tree<U32>:
  match r:
    case 0n: VF.updv({L}, dd, D, q)
    case 1n: UW.SWc(1, {L}, dd, D, q, 0)
    case 2n: UW.SWc(2, {L}, dd, D, q, 0)
    case 3n: UW.SWc(3, {L}, dd, D, q, 0)
    case 4n+t: D

def {p}x_perfect(+r: Nat, +dd: Nat, +D: FD.array__Tree<U32>, +q: Nat, {WP}, {PF})
    -> {{FD.array__perfect(U32, dd, {PX("r")}) == True{{}} : Bool}}:
  match r:
    case 0n: VF.updv_perfect({L}, dd, D, q, pf)
    case 1n: UW.swc_perfect(1, {L}, dd, D, q, 0, pf)
    case 2n: UW.swc_perfect(2, {L}, dd, D, q, 0, pf)
    case 3n: UW.swc_perfect(3, {L}, dd, D, q, 0, pf)
    case 4n+ +t: pf

# T.{p}_put at any byte position X = 4 q + r.
def {p}_any(+dd: Nat, +D: FD.array__Tree<U32>, +X: U32, +q: Nat, +r: Nat, {WP}, {E_},
    {HD}, {HL}, {PF}, {HZ})
    -> {RT("r")}:
  match r:
    case 0n: {AL}(dd, D, X, q, FD.logic__subst(Nat, z => {{U32.to_nat(X) == z : Nat}}, Nat.add(A.quad(q), 0n), A.quad(q), FD.nat__add_zero(A.quad(q)), e), hd, pf,
      FD.logic__subst(Nat, z => {{Nat.is_le(z, VB.pw(dd)) == True{{}} : Bool}}, Nat.add(q, {N}n), Nat.add({N}n, q), FD.nat__add_comm(q, {N}n), hl), {W})''']
    for s in (1, 2, 3):
        out.append(f'''    case {s}n: UF{s}.putu_{p}(dd, D, X, q, {W}, e, FD.nat__lt_trans(dd, 29n, 31n, hd, {{==}}), {lq}, pf, hz)''')
    out.append(f'''    case 4n+ +t: Empty.absurd({RT("4n+t")}, FD.nat__lt_zero_absurd(t, hr))

# Its bytes: the words' limbs at X, when the {m} bytes there were zero.
def {p}_any_bytes(+dd: Nat, +D: FD.array__Tree<U32>, +X: U32, +q: Nat, +r: Nat, {WP}, {E_},
    {HD}, {HL}, {PF}, {HZ})
    -> {BY("r", "Nat.add(A.quad(q), r)")}:
  match r:
    case 0n:
      %Equal.sym(Nat, Nat.add(A.quad(q), 0n), A.quad(q), FD.nat__add_zero(A.quad(q))) : {BY("0n", "_")}
      UW.updv_bytes({L}, dd, D, q, pf, hl)''')
    for s in (1, 2, 3):
        out.append(f'''    case {s}n: UB{s}.swcb({L}, dd, D, q, pf, FD.logic__subst(Nat, z => {{Nat.is_lt(z, VB.pw(dd)) == True{{}} : Bool}}, Nat.add({N}n, q), Nat.add(q, {N}n), FD.nat__add_comm({N}n, q), {lq}), hz)''')
    out.append(f'''    case 4n+ +t: Empty.absurd({BY("4n+t", "Nat.add(A.quad(q), 4n+t)")}, FD.nat__lt_zero_absurd(t, hr))
''')
    return '\n'.join(out)


def b256_text():
    WS = 'VS.wtake(64n, UW.SLW(TB))'
    OBJ = f'O.Words{{{TH.format("TB")}, 256}}'
    PX = lambda r: f'PX_b256({r}, dd, D, q, TB)'  # noqa: E731
    RT = lambda r: f'{{T.b256_putk({TH.format("D")}, X, {OBJ}) == ({TH.format(PX(r))}, ({OBJ}, 0)) : Array<U32> & (O.Words & U32)}}'  # noqa: E731
    BY = lambda r, x: f'{{UA.BYT({PX(r)}) == UW.SPL(UA.BYT(D), {x}, FX.limbs({WS})) : +List<U32>}}'  # noqa: E731
    P = ('+dd: Nat, +D: FD.array__Tree<U32>, +X: U32, +q: Nat, +r: Nat, +dB: Nat, +TB: FD.array__Tree<U32>, ' + E_ + ',\n'
         '    +hd: {Nat.is_lt(dd, 29n) == True{} : Bool}, +hl: {Nat.is_le(Nat.add(q, UWD.NWN(Nat.add(r, 256n))), VB.pw(dd)) == True{} : Bool},\n'
         '    +pf: {FD.array__perfect(U32, dd, D) == True{} : Bool}, +pfB: {FD.array__perfect(U32, dB, TB) == True{} : Bool},\n'
         '    +hdB: {Nat.is_lt(dB, 31n) == True{} : Bool}, +hrB: {Nat.is_le(64n, VB.pw(dB)) == True{} : Bool},\n'
         '    +hz: {VS.bt(256n, VS.bdr(Nat.add(A.quad(q), r), UA.BYT(D))) == UW.ZB(256n) : +List<U32>}')
    lq = 'UWD.le_q(q, 64n, VB.pw(dd), hl)'
    EL = 'UW.len_take(64n, UW.SLW(TB), FD.logic__subst(Nat, z => {Nat.is_le(64n, z) == True{} : Bool}, VB.pw(dB), VB.len(UW.SLW(TB)), Equal.sym(Nat, VB.len(UW.SLW(TB)), VB.pw(dB), FD.array__slots_length(U32, dB, TB, pfB)), hrB))'
    out = [f'''
# ---- b256: T.b256_putk over the O.Words of 256 bytes held in TB ----

# The first k words of L from word i, as a list of its slots.
def TKS(+k: Nat, +i: Nat, +L: List<&2, U32>) -> List<&2, U32>:
  match k:
    case 0n: []
    case 1n+p: Con{{FD.flat__nthc(L, i), TKS(p, 1n+i, L)}}

law tks:
  for +k: Nat
  for +i: Nat
  for +L: List<&2, U32>
  for +h: {{Nat.is_le(Nat.add(i, k), VB.len(L)) == True{{}} : Bool}}
  {{VS.wtake(k, VB.wdr(i, L)) == TKS(k, i, L) : List<&2, U32>}}
def tks(k, i, L, h):
  match k:
    case 0n: {{==}}
    case 1n+ +p:
      +hi = FD.nat__le_lt_trans(i, Nat.add(i, p), VB.len(L), Order.below_sum(i, p),
        FD.nat__succ_le_lt(Nat.add(i, p), VB.len(L), FD.logic__subst(Nat, z => {{Nat.is_le(z, VB.len(L)) == True{{}} : Bool}}, Nat.add(i, 1n+p), 1n+Nat.add(i, p), FD.nat__add_succ(i, p), h)))
      %Equal.sym(List<&2, U32>, VB.wdr(i, L), Con{{FD.flat__nthc(L, i), VB.wdr(1n+i, L)}}, UW.wdr_con(L, i, hi)) :
        {{VS.wtake(1n+p, _) == TKS(1n+p, i, L) : List<&2, U32>}}
      Equal.cong(List<&2, U32>, List<&2, U32>, z => Con{{FD.flat__nthc(L, i), z}}, VS.wtake(p, VB.wdr(1n+i, L)), TKS(p, 1n+i, L),
        tks(p, 1n+i, L, FD.logic__subst(Nat, z => {{Nat.is_le(z, VB.len(L)) == True{{}} : Bool}}, Nat.add(i, 1n+p), Nat.add(1n+i, p), FD.nat__add_succ(i, p), h)))

def wl_b256(+dB: Nat, +TB: FD.array__Tree<U32>, +pfB: {{FD.array__perfect(U32, dB, TB) == True{{}} : Bool}}, +hrB: {{Nat.is_le(64n, VB.pw(dB)) == True{{}} : Bool}})
    -> {{VW.WL_b256(TB) == {WS} : List<&2, U32>}}:
  Equal.sym(List<&2, U32>, {WS}, VW.WL_b256(TB),
    tks(64n, 0n, UW.SLW(TB), FD.logic__subst(Nat, z => {{Nat.is_le(64n, z) == True{{}} : Bool}}, VB.pw(dB), VB.len(UW.SLW(TB)), Equal.sym(Nat, VB.len(UW.SLW(TB)), VB.pw(dB), FD.array__slots_length(U32, dB, TB, pfB)), hrB)))

def PX_b256(+r: Nat, +dd: Nat, +D: FD.array__Tree<U32>, +q: Nat, +TB: FD.array__Tree<U32>) -> FD.array__Tree<U32>:
  match r:
    case 0n: VF.updv({WS}, dd, D, q)
    case 1n: UW.SWc(1, {WS}, dd, D, q, 0)
    case 2n: UW.SWc(2, {WS}, dd, D, q, 0)
    case 3n: UW.SWc(3, {WS}, dd, D, q, 0)
    case 4n+t: D

def b256x_perfect(+r: Nat, +dd: Nat, +D: FD.array__Tree<U32>, +q: Nat, +TB: FD.array__Tree<U32>, +pf: {{FD.array__perfect(U32, dd, D) == True{{}} : Bool}})
    -> {{FD.array__perfect(U32, dd, {PX("r")}) == True{{}} : Bool}}:
  match r:
    case 0n: VF.updv_perfect({WS}, dd, D, q, pf)
    case 1n: UW.swc_perfect(1, {WS}, dd, D, q, 0, pf)
    case 2n: UW.swc_perfect(2, {WS}, dd, D, q, 0, pf)
    case 3n: UW.swc_perfect(3, {WS}, dd, D, q, 0, pf)
    case 4n+ +t: pf

# T.b256_putk at any byte position X = 4 q + r (its validity check, then its copy).
def b256_any({P})
    -> {RT("r")}:
  match r:
    case 0n:
      %wl_b256(dB, TB, pfB, hrB) : {{T.b256_putk({TH.format("D")}, X, {OBJ}) == ({TH.format("VF.updv(_, dd, D, q)")}, ({OBJ}, 0)) : Array<U32> & (O.Words & U32)}}
      VW.wput_b256(dd, D, X, q, FD.logic__subst(Nat, z => {{U32.to_nat(X) == z : Nat}}, Nat.add(A.quad(q), 0n), A.quad(q), FD.nat__add_zero(A.quad(q)), e), hd, pf,
        FD.logic__subst(Nat, z => {{Nat.is_le(z, VB.pw(dd)) == True{{}} : Bool}}, Nat.add(q, 64n), Nat.add(64n, q), FD.nat__add_comm(q, 64n), hl), dB, TB, pfB, hdB, hrB)''']
    for s in (1, 2, 3):
        out.append(f'''    case {s}n: UK{s}.wputu_b256(dd, D, X, q, dB, TB, e, FD.nat__lt_trans(dd, 29n, 31n, hd, {{==}}), {lq}, pf, pfB, hdB, hrB, hz)''')
    out.append(f'''    case 4n+ +t: Empty.absurd({RT("4n+t")}, FD.nat__lt_zero_absurd(t, hr))

# Its bytes: the 256 bytes of TB's first 64 words at X, when the bytes there were zero.
def b256_any_bytes({P})
    -> {BY("r", "Nat.add(A.quad(q), r)")}:
  match r:
    case 0n:
      +eL = {EL}
      %Equal.sym(Nat, Nat.add(A.quad(q), 0n), A.quad(q), FD.nat__add_zero(A.quad(q))) : {BY("0n", "_")}
      UW.updv_bytes({WS}, dd, D, q, pf, FD.logic__subst(Nat, z => {{Nat.is_le(Nat.add(q, z), VB.pw(dd)) == True{{}} : Bool}}, 64n, VB.len({WS}),
        Equal.sym(Nat, VB.len({WS}), 64n, Equal.trans(Nat, VB.len({WS}), List.length(&2, U32, {WS}), 64n, Equal.sym(Nat, List.length(&2, U32, {WS}), VB.len({WS}), VR.len_eq({WS})), eL)), hl))''')
    for s in (1, 2, 3):
        out.append(f'''    case {s}n:
      +eL = {EL}
      UB{s}.swcb({WS}, dd, D, q, pf,
      FD.logic__subst(Nat, z => {{Nat.is_lt(Nat.add(q, z), VB.pw(dd)) == True{{}} : Bool}}, 64n, List.length(&2, U32, {WS}), Equal.sym(Nat, List.length(&2, U32, {WS}), 64n, eL),
        FD.logic__subst(Nat, z => {{Nat.is_lt(z, VB.pw(dd)) == True{{}} : Bool}}, Nat.add(64n, q), Nat.add(q, 64n), FD.nat__add_comm(64n, q), {lq})),
      FD.logic__subst(Nat, z => {{VS.bt(A.quad(z), VS.bdr(Nat.add(A.quad(q), {s}n), UA.BYT(D))) == UW.ZB(A.quad(z)) : +List<U32>}}, 64n, List.length(&2, U32, {WS}), Equal.sym(Nat, List.length(&2, U32, {WS}), 64n, eL), hz))''')
    out.append(f'''    case 4n+ +t: Empty.absurd({BY("4n+t", "Nat.add(A.quad(q), 4n+t)")}, FD.nat__lt_zero_absurd(t, hr))
''')
    return '\n'.join(out)


def module(imports, what, body):
    return HEAD.replace('@IMPORTS\n', ''.join(f'{i}\n' for i in imports) + '\n').replace('@WHAT', what) + body


def outputs():
    out = {}
    for v in VECS:
        p, C, N, AL = v
        uf = [f'import ./vuwf{s}.bend as UF{s}' if p in ('b32', 'u256') else f'import ./vuwf{s}_{p}.bend as UF{s}' for s in (1, 2, 3)]
        al = 'import ./var_fix_types.bend as VT' if AL.startswith('VT.') else 'import ./var_bytes_fix.bend as VBF'
        out[ROOT / f'proofs/obj/vuwv_{p}.bend'] = module(uf + [al], f'T.{p}_put ({C}, {N} words)', vec_text(*v))
    uk = [f'import ./vuwk{s}.bend as UK{s}' for s in (1, 2, 3)] + ['import ./var_bytes_wput.bend as VW']
    out[ROOT / 'proofs/obj/vuwv_b256.bend'] = module(uk, 'T.b256_putk (the 256-byte O.Words)', b256_text())
    return out


def main():
    out = outputs()
    if '--check' in sys.argv:
        stale = [str(p.relative_to(ROOT)) for p, t in out.items() if not p.exists() or p.read_text() != t]
        if stale:
            print('stale: ' + ', '.join(stale))
            sys.exit(1)
        print('word-vector writers are current')
        return
    for p, t in out.items():
        p.write_text(t)
    print('wrote ' + ', '.join(str(p.relative_to(ROOT)) for p in out))


if __name__ == '__main__':
    main()
