#!/usr/bin/env python3
"""The unaligned-offset layer: the runtime's word reads and copies at any byte
offset, related to the buffer's spec bytes.

    python3 codegen/var_ua.py [--check]

proofs/obj/vua_bits.bend (generated here, stock): the byte structure of the
runtime's unaligned word join B.join_sel(j, lo, hi) (j = 1, 2, 3): its four
limbs are the last 4 - j limbs of lo followed by the first j limbs of hi. The
proofs compute each output bit symbolically (a simulator of Word.and/or/shift
below) and close every position with one of five one-bit lemmas; no case
split over the words' bits is needed.

proofs/obj/vua.bend (hand-written, stock) builds U1 on it: B.read32 at any
byte offset returns a word whose limbs are the buffer's spec bytes there.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'proofs/obj/vua_bits.bend'

F_, T_ = 'False{}', 'True{}'


def const(v):
    return [T_ if (v >> i) & 1 else F_ for i in range(32)]


def b_and(x, y):
    if x == T_:
        return y
    if x == F_:
        return F_
    return f'Bool.and({x}, {y})'


def b_or(x, y):
    if x == T_:
        return T_
    if x == F_:
        return y
    return f'Bool.or({x}, {y})'


def w_and(xs, ys):
    return [b_and(x, y) for x, y in zip(xs, ys)]


def w_or(xs, ys):
    return [b_or(x, y) for x, y in zip(xs, ys)]


def shrn(xs, k):
    return xs[k:] + [F_] * k


def shln(xs, k):
    return [F_] * k + xs[:32 - k]


def limb(xs):
    return [w_and(xs, const(255)), w_and(shrn(xs, 8), const(255)), w_and(shrn(xs, 16), const(255)), shrn(xs, 24)]


def join_sel(j, lo, hi):
    return w_or(shrn(lo, 8 * j), shln(hi, 32 - 8 * j))


def word(bs):
    return 'U32{' + ''.join(f'WCon{{{b}, ' for b in bs) + 'WNil{}' + '}' * len(bs) + '}'


def canon(bits8):
    return bits8 + [F_] * 24


def pos_proof(x, y):
    """A proof of {x == y : Bool} for one position (y is a variable or False)."""
    if x == y:
        return '{==}'
    for name, pat in [('p1', 'Bool.and(Bool.or({a}, False{{}}), True{{}})'), ('p2', 'Bool.and(Bool.or({a}, False{{}}), False{{}})'),
                      ('p3', 'Bool.and({a}, True{{}})'), ('p4', 'Bool.and({a}, False{{}})'), ('p5', 'Bool.or({a}, False{{}})')]:
        for a in [f'a{i}' for i in range(32)] + [f'b{i}' for i in range(32)]:
            if x == pat.format(a=a):
                return f'{name}({a})'
    raise ValueError(f'no position lemma for {x} == {y}')


A = [f'a{i}' for i in range(32)]
Bv = [f'b{i}' for i in range(32)]


def emit():
    L = ['import Base', 'import ../../src/buffer.bend as B', 'import ../../src/primitives.bend as I', '',
         '# GENERATED by codegen/var_ua.py. Do not edit.',
         '# The limbs of the runtime\'s unaligned word join (see the module docstring', '# of codegen/var_ua.py).', '']
    w = L.append
    for name, lhs, rhs in [('p1', 'Bool.and(Bool.or(a, False{}), True{})', 'a'), ('p2', 'Bool.and(Bool.or(a, False{}), False{})', 'False{}'),
                           ('p3', 'Bool.and(a, True{})', 'a'), ('p4', 'Bool.and(a, False{})', 'False{}'), ('p5', 'Bool.or(a, False{})', 'a')]:
        w(f'def {name}(+a: Bool) -> {{{lhs} == {rhs} : Bool}}:')
        w('  match a:')
        w('    case True{}: {==}')
        w('    case False{}: {==}')
        w('')
    xs = [f'x{i}' for i in range(32)]
    ys = [f'y{i}' for i in range(32)]
    w('# Two words with equal bits are equal.')
    w('def weq(' + ', '.join(f'+{v}: Bool' for v in xs + ys) + ', ' + ', '.join(f'+e{i}: {{x{i} == y{i} : Bool}}' for i in range(32)) + ')')
    w(f'    -> {{{word(xs)} == {word(ys)} : U32}}:')
    for i in range(32):
        cur = ys[:i] + ['_'] + xs[i + 1:]
        w(f'  %Equal.sym(Bool, x{i}, y{i}, e{i}) : {{{word(cur)} == {word(ys)} : U32}}')
    w('  {==}')
    w('')
    w('def l4(+x0: U32, +x1: U32, +x2: U32, +x3: U32, +y0: U32, +y1: U32, +y2: U32, +y3: U32,')
    w('    +e0: {x0 == y0 : U32}, +e1: {x1 == y1 : U32}, +e2: {x2 == y2 : U32}, +e3: {x3 == y3 : U32}) -> {[x0, x1, x2, x3] == [y0, y1, y2, y3] : List<&2, U32>}:')
    w('  %Equal.sym(U32, x0, y0, e0) : {[_, x1, x2, x3] == [y0, y1, y2, y3] : List<&2, U32>}')
    w('  %Equal.sym(U32, x1, y1, e1) : {[y0, _, x2, x3] == [y0, y1, y2, y3] : List<&2, U32>}')
    w('  %Equal.sym(U32, x2, y2, e2) : {[y0, y1, _, x3] == [y0, y1, y2, y3] : List<&2, U32>}')
    w('  %Equal.sym(U32, x3, y3, e3) : {[y0, y1, y2, _] == [y0, y1, y2, y3] : List<&2, U32>}')
    w('  {==}')
    w('')

    def weq_call(xbits, ybits):
        return 'weq(' + ', '.join(xbits + ybits) + ', ' + ', '.join(pos_proof(x, y) for x, y in zip(xbits, ybits)) + ')'

    def canon_list(words_bits):
        return '[' + ', '.join(word(b) for b in words_bits) + ']'

    WL = word(A)
    WH = word(Bv)
    bytes_lo = [canon(A[8 * k:8 * k + 8]) for k in range(4)]
    bytes_hi = [canon(Bv[8 * k:8 * k + 8]) for k in range(4)]
    # the limbs of a word, canonically
    lb = limb(A)
    w('# The limbs of a word are its four bytes.')
    w('def limbC(' + ', '.join(f'+{v}: Bool' for v in A) + f') -> {{I.limb({WL}) == {canon_list(bytes_lo)} : List<&2, U32>}}:')
    w('  l4(' + ', '.join(word(b) for b in lb) + ', ' + ', '.join(word(b) for b in bytes_lo) + ', '
      + ', '.join(weq_call(lb[k], bytes_lo[k]) for k in range(4)) + ')')
    w('')
    for j in (1, 2, 3):
        js = join_sel(j, A, Bv)
        lj = limb(js)
        target = bytes_lo[j:] + bytes_hi[:j]
        w(f'def joinC{j}(' + ', '.join(f'+{v}: Bool' for v in A + Bv) + f') -> {{I.limb(B.join_sel({j}, {WL}, {WH})) == {canon_list(target)} : List<&2, U32>}}:')
        w('  l4(' + ', '.join(word(b) for b in lj) + ', ' + ', '.join(word(b) for b in target) + ', '
          + ', '.join(weq_call(lj[k], target[k]) for k in range(4)) + ')')
        w('')
    # over words
    pat_lo = 'U32{' + ''.join(f'WCon{{+{a}, ' for a in A) + 'WNil{}' + '}' * 32 + '}'
    pat_hi = 'U32{' + ''.join(f'WCon{{+{b}, ' for b in Bv) + 'WNil{}' + '}' * 32 + '}'
    for j in (1, 2, 3):
        rhs = ', '.join([f'I.at(I.limb(lo), {k}n)' for k in range(j, 4)] + [f'I.at(I.limb(hi), {k}n)' for k in range(j)])
        w(f'# The limbs of the join at byte {j}: limbs {j}..3 of lo, then limbs 0..{j - 1} of hi.')
        w(f'law join{j}:')
        w('  for +lo: U32')
        w('  for +hi: U32')
        w(f'  {{I.limb(B.join_sel({j}, lo, hi)) == [{rhs}] : List<&2, U32>}}')
        w(f'def join{j}(lo, hi):')
        w('  match lo hi:')
        w(f'    case {pat_lo} {pat_hi}:')
        rw = f'[{", ".join([f"I.at(I.limb({WL}), {k}n)" for k in range(j, 4)] + [f"I.at(I.limb({WH}), {k}n)" for k in range(j)])}]'
        w(f'      %Equal.sym(List<&2, U32>, I.limb({WL}), {canon_list(bytes_lo)}, limbC({", ".join(A)})) :')
        w(f'        {{I.limb(B.join_sel({j}, {WL}, {WH})) == [{", ".join([f"I.at(_, {k}n)" for k in range(j, 4)] + [f"I.at(I.limb({WH}), {k}n)" for k in range(j)])}] : List<&2, U32>}}')
        limbC_b = 'limbC(' + ', '.join(Bv) + ')'
        w(f'      %Equal.sym(List<&2, U32>, I.limb({WH}), {canon_list(bytes_hi)}, {limbC_b}) :')
        inner = [f'I.at({canon_list(bytes_lo)}, {k}n)' for k in range(j, 4)] + [f'I.at(_, {k}n)' for k in range(j)]
        w(f'        {{I.limb(B.join_sel({j}, {WL}, {WH})) == [{", ".join(inner)}] : List<&2, U32>}}')
        w(f'      joinC{j}(' + ', '.join(A + Bv) + ')')
        w('')
    return '\n'.join(L) + '\n'


def main():
    text = emit()
    if '--check' in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            print('stale generated unaligned-offset laws: proofs/obj/vua_bits.bend')
            sys.exit(1)
        print('generated unaligned-offset laws are current')
        return
    OUT.write_text(text)
    print('wrote proofs/obj/vua_bits.bend')


if __name__ == '__main__':
    main()
