#!/usr/bin/env python3
"""The encoder laws of the variable-size names of codegen/var_laws.py.

For a name X of the family (fixed word-aligned fields around one list of
uint64) this writes, into var_laws.fname(x, '_enc'),

    encode_eval    for every object whose fixed fields hold the words w_k and
                   whose list is O.Words{thaw(T), N} (T a perfect tree of depth
                   dw < 31 with room for its words, N = 8c, c <= limit),
                   T.X_encode returns the object and the buffer
                   B.Buf{thaw(OUT3), FS + N}, OUT3 an explicit output tree;
    encode_spec    the bytes of that buffer are the spec/codec.bend encoding
                   of the object's value XE(w.., c, slots(T)).

The output tree is the offset word at po, the list's words copied after the
header (VB.mone) and the fixed fields' words written by runs of word writes
(VF.updv); its slots are read back window by window (proofs/obj/venc2.bend).
"""
import re

import var_laws as VL
import lim_pow as LPW
import runtime_refs as RR  # noqa: E402  the runtime split: the monoliths' text, the split files' imports


def enc_module_text(g, x):
    n, FS, H, po, LIM, lp = x.n, x.FS, x.H, x.po, x.LIM, x.lp
    KO, KK = x.KO, max(x.K, x.KO)
    Tn = f'T.{n}'
    src = RR.mono_text('fulu')
    m = re.search(rf'def {lp}_valid\(o: O\.Words\) -> O\.Words & Bool: O\.words_ok\(o, 0, (\d+), False\{{\}}, 8\)', src)
    if not m or int(m.group(1)) != 8 * LIM:
        raise VL.Skip('list storage check differs')
    LIMB = int(m.group(1))
    PB = (8 * LIM).bit_length()
    P2 = (31 + FS + 8 * LIM).bit_length()
    assert PB <= 31 and P2 < 31 and KO < 29

    ITEMS, CHAIN, PL, CAT, PRE, POST, hdr, LIMN, YS = VL.spec_parts(g, x, lambda k: f'w{k}')
    # The closed facts about the limit: `{==}` for a small limit, symbolic (codegen/lim_pow.py) for 2^p.
    LP = LPW.LimPow(LIMN)
    q = (8 * LIM).bit_length() - 1
    if LP.big:
        X8 = LP.x8()
        assert PB == q + 1 and P2 == q + 1
        BS = 1 << (q + 1)
        K_PB = LP.lt(X8, PB)
        K_ES = LP.le_u32(LP.add(FS, X8), q + 1)
        K_YN = LP.le(LP.add(31, X8), P2)
        K_YS = LP.le(LP.add(31, LP.add(FS, X8)), P2)
        MKO = f'Nat.add({H}n, Nat.double({LIMN}))'
        K_KO = LP.le_pow2n(LP.add(H, LP.dbl()), KO)
        K_LB = LP.le_u32(X8, q)
        K_FIT = LP.fits(LP.add(FS, X8), q + 1)
    else:
        BS = FS + LIMB
        K_PB = K_ES = K_YN = K_YS = K_KO = K_LB = K_FIT = '{==}'
        MKO = f'{H}n+Nat.double({LIMN})'
    ks = [k for k in range(H) if k != po]
    WS = ', '.join(f'+w{k}: U32' for k in ks)
    WA = ', '.join(f'w{k}' for k in ks)
    fixed = [f for f in x.fields if f['kind'] == 'fix']

    def V(f):
        return '[' + ', '.join(f'w{f["k"] + j}' for j in range(f['ft'].W)) + ']'

    def fobj(f):
        return f['ft'].obj([f'w{f["k"] + j}' for j in range(f['ft'].W)])
    objs = [fobj(f) if f['kind'] == 'fix' else 'O.Words{FD.array__thaw(U32, T), N}' for f in x.fields]
    OBJ = f'{Tn}{{' + ', '.join(objs) + '}'
    FIXOBJS = ', '.join(fobj(f) for f in fixed)
    WORDS = 'O.Words{FD.array__thaw(U32, T), N}'
    NC = '+N: U32, +c: Nat, +ec: {U32.to_nat(N) == VS.x8(c) : Nat}, +hc: {Nat.is_le(c, ' + LIMN + ') == True{} : Bool}'
    NCa = 'N, c, ec, hc'
    ALLP = (f'{WS}, +dw: Nat, +T: FD.array__Tree<U32>, +N: U32, +c: Nat,\n'
            '    +pfT: {FD.array__perfect(U32, dw, T) == True{} : Bool}, +hdw: {Nat.is_lt(dw, 31n) == True{} : Bool},\n'
            '    +ec: {U32.to_nat(N) == VS.x8(c) : Nat}, +hc: {Nat.is_le(c, ' + LIMN + ') == True{} : Bool},\n'
            '    +hroom: {Nat.is_le(Nat.add(VC.NW(N), 0n), VB.pw(dw)) == True{} : Bool}')
    ALLa = f'{WA}, dw, T, N, c, pfT, hdw, ec, hc, hroom'
    TD = lambda j: f'TD{j}({WA}, N, T)'  # noqa: E731
    OUT3 = TD(len(fixed))
    S3 = f'FD.array__slots(U32, {OUT3})'
    ST = 'FD.array__slots(U32, T)'
    HDR = ' <> '.join(hdr)
    HDRL = '[' + ', '.join(hdr) + ']'
    NW = 'VC.NW(N)'
    toN = 'U32.to_nat(N)'
    M = 'Maybe<&2, +List<U32>>'
    MP = 'Maybe<&2, +List<S.Part>>'
    L = list(VL.DEC_HEAD) + ['import ./venc.bend as VE', 'import ./venc2.bend as V2', f'import ./{VL.fname(x).name} as DC'] + LP.imports() + VL.SPEC_IMPORTS + ['',
                             '# GENERATED by codegen/var_enc.py. Do not edit.',
                             f'# The encoder of {n}: for every object whose list storage is a perfect tree T',
                             f'# holding N = 8c bytes (c <= limit) with room for them, the encoder returns the',
                             f'# object and B.Buf{{thaw(OUT3), {FS} + N}} (encode_eval), and the bytes of that',
                             '# buffer are the spec/codec.bend encoding of the object\'s value (encode_spec).', '']
    w = L.append
    TREES = [f'def SFS(+N: U32) -> U32: U32.add({FS}, N)',
             'def DO(+N: U32) -> Nat: B.words_depth(VC.nwu(SFS(N)))',
             f'def OUT1(+N: U32) -> FD.array__Tree<U32>: FD.array__upd(U32, DO(N), VC.ZT(DO(N)), {po}n, {FS})',
             f'def OUT2(+N: U32, +T: FD.array__Tree<U32>) -> FD.array__Tree<U32>: VB.mone(VC.NW(N), 0n, {H}n, DO(N), OUT1(N), T)',
             f'def TD0({WS}, +N: U32, +T: FD.array__Tree<U32>) -> FD.array__Tree<U32>: OUT2(N, T)']
    for j, f in enumerate(fixed):
        TREES.append(f'def TD{j + 1}({WS}, +N: U32, +T: FD.array__Tree<U32>) -> FD.array__Tree<U32>: VF.updv({V(f)}, DO(N), {TD(j)}, {f["k"]}n)')
    w('\n'.join(TREES))
    w(f'''
def leN({NC}) -> {{Nat.is_le({toN}, VS.x8({LIMN})) == True{{}} : Bool}}:
  %Equal.sym(Nat, {toN}, VS.x8(c), ec) : {{Nat.is_le(_, VS.x8({LIMN})) == True{{}} : Bool}}
  VS.x8_mono(c, {LIMN}, hc)

def padd({NC}) -> {{O.padd({FS}, N) == SFS(N) : U32}}:
  VE.padd_ok({FS}, N, VE.winit(31n, VE.bits32({FS})), VE.winit(31n, VE.bits32(N)), {{==}},
    VE.small_pad(N, {PB}n, {{==}}, FD.nat__le_lt_trans({toN}, VS.x8({LIMN}), VB.pw({PB}n), leN({NCa}), {K_PB})))

def eS({NC}) -> {{U32.to_nat(SFS(N)) == Nat.add({FS}n, {toN}) : Nat}}:
  A.add_le({FS}, N, {BS}, FD.nat__le_trans(Nat.add({FS}n, {toN}), Nat.add({FS}n, VS.x8({LIMN})), U32.to_nat({BS}),
    Order.add_left({FS}n, {toN}, VS.x8({LIMN}), leN({NCa})), {K_ES}))

def hyN({NC}) -> {{Nat.is_le(VC.YL(N), VB.pw({P2}n)) == True{{}} : Bool}}:
  FD.nat__le_trans(Nat.add(31n, {toN}), Nat.add(31n, VS.x8({LIMN})), VB.pw({P2}n), Order.add_left(31n, {toN}, VS.x8({LIMN}), leN({NCa})), {K_YN})

def hyS({NC}) -> {{Nat.is_le(VC.YL(SFS(N)), VB.pw({P2}n)) == True{{}} : Bool}}:
  %Equal.sym(Nat, U32.to_nat(SFS(N)), Nat.add({FS}n, {toN}), eS({NCa})) : {{Nat.is_le(Nat.add(31n, _), VB.pw({P2}n)) == True{{}} : Bool}}
  FD.nat__le_trans(Nat.add(31n, Nat.add({FS}n, {toN})), Nat.add(31n, Nat.add({FS}n, VS.x8({LIMN}))), VB.pw({P2}n),
    Order.add_left(31n, Nat.add({FS}n, {toN}), Nat.add({FS}n, VS.x8({LIMN})), Order.add_left({FS}n, {toN}, VS.x8({LIMN}), leN({NCa}))), {K_YS})

def nwN({NC}) -> {{VC.NW(N) == Nat.double(c) : Nat}}:
  %Equal.sym(Nat, VC.NW(N), VD.s_rng(2n, 3n+{toN}), VC.eNW(N, {P2}n, {{==}}, hyN({NCa}))) : {{_ == Nat.double(c) : Nat}}
  %Equal.sym(Nat, {toN}, VS.x8(c), ec) : {{VD.s_rng(2n, 3n+_) == Nat.double(c) : Nat}}
  VC.rng2_x8(c)

def nwS({NC}) -> {{VC.NW(SFS(N)) == {H}n+Nat.double(c) : Nat}}:
  %Equal.sym(Nat, VC.NW(SFS(N)), VD.s_rng(2n, 3n+U32.to_nat(SFS(N))), VC.eNW(SFS(N), {P2}n, {{==}}, hyS({NCa}))) : {{_ == {H}n+Nat.double(c) : Nat}}
  %Equal.sym(Nat, U32.to_nat(SFS(N)), Nat.add({FS}n, {toN}), eS({NCa})) : {{VD.s_rng(2n, 3n+_) == {H}n+Nat.double(c) : Nat}}
  %Equal.sym(Nat, {toN}, VS.x8(c), ec) : {{VD.s_rng(2n, {3 + FS}n+_) == {H}n+Nat.double(c) : Nat}}
  Equal.cong(Nat, Nat, z => {H}n+z, VD.s_rng(2n, 3n+VS.x8(c)), Nat.double(c), VC.rng2_x8(c))

def leKO({NC}) -> {{Nat.is_le({H}n+Nat.double(c), O.pow2n({KO}n)) == True{{}} : Bool}}:
  FD.nat__le_trans({H}n+Nat.double(c), {MKO}, O.pow2n({KO}n),
    Order.add_left({H}n, Nat.double(c), Nat.double({LIMN}), FD.nat__double_le(c, {LIMN}, hc)), {K_KO})

def leW({NC}) -> {{Nat.is_le(U32.to_nat(VC.nwu(SFS(N))), O.pow2n({KO}n)) == True{{}} : Bool}}:
  FD.logic__subst(Nat, z => {{Nat.is_le(z, O.pow2n({KO}n)) == True{{}} : Bool}}, {H}n+Nat.double(c), VC.NW(SFS(N)),
    Equal.sym(Nat, VC.NW(SFS(N)), {H}n+Nat.double(c), nwS({NCa})), leKO({NCa}))

def hDOK({NC}) -> {{Nat.is_le(DO(N), {KO}n) == True{{}} : Bool}}:
  VD.wd_min(VC.nwu(SFS(N)), {KO}n, leW({NCa}))

def roomS({NC}) -> {{Nat.is_le({H}n+Nat.double(c), VB.pw(DO(N))) == True{{}} : Bool}}:
  %Equal.sym(Nat, VB.pw(DO(N)), O.pow2n(DO(N)), VD.s_pow2_eq(DO(N))) : {{Nat.is_le({H}n+Nat.double(c), _) == True{{}} : Bool}}
  %nwS({NCa}) : {{Nat.is_le(_, O.pow2n(DO(N))) == True{{}} : Bool}}
  VD.wd_cover(VC.nwu(SFS(N)), {KO}n, {{==}}, leW({NCa}))

def hDO29({NC}) -> {{Nat.is_lt(DO(N), 29n) == True{{}} : Bool}}:
  FD.nat__le_lt_trans(DO(N), {KO}n, 29n, hDOK({NCa}), {{==}})

def hDO31({NC}) -> {{Nat.is_lt(DO(N), 31n) == True{{}} : Bool}}:
  FD.nat__le_lt_trans(DO(N), {KO}n, 31n, hDOK({NCa}), {{==}})

# a <= H: a <= 2^DO.
def hbk(+a: Nat, {NC}, +ha: {{Nat.is_le(a, {H}n) == True{{}} : Bool}}) -> {{Nat.is_le(a, VB.pw(DO(N))) == True{{}} : Bool}}:
  FD.nat__le_trans(a, {H}n, VB.pw(DO(N)), ha, FD.nat__le_trans({H}n, {H}n+Nat.double(c), VB.pw(DO(N)), Order.below_sum({H}n, Nat.double(c)), roomS({NCa})))

def ltH(+k: Nat, {NC}, +hk: {{Nat.is_lt(k, {H}n) == True{{}} : Bool}}) -> {{Nat.is_lt(k, VB.pw(DO(N))) == True{{}} : Bool}}:
  FD.nat__lt_le_trans(k, {H}n, VB.pw(DO(N)), hk, hbk({H}n, {NCa}, {{==}}))

def hdst({NC}) -> {{Nat.is_le(Nat.add(VC.NW(N), {H}n), VB.pw(DO(N))) == True{{}} : Bool}}:
  FD.logic__subst(Nat, z => {{Nat.is_le(Nat.add(z, {H}n), VB.pw(DO(N))) == True{{}} : Bool}}, Nat.double(c), VC.NW(N), Equal.sym(Nat, VC.NW(N), Nat.double(c), nwN({NCa})),
    FD.logic__subst(Nat, z => {{Nat.is_le(z, VB.pw(DO(N))) == True{{}} : Bool}}, {H}n+Nat.double(c), Nat.add(Nat.double(c), {H}n), FD.nat__add_comm({H}n, Nat.double(c)), roomS({NCa})))

def pf0(+N: U32) -> {{FD.array__perfect(U32, DO(N), VC.ZT(DO(N))) == True{{}} : Bool}}: FD.array__trep_perfect(U32, DO(N), 0)
def pf1(+N: U32) -> {{FD.array__perfect(U32, DO(N), OUT1(N)) == True{{}} : Bool}}: FD.array__upd_perfect(U32, DO(N), VC.ZT(DO(N)), {po}n, {FS}, pf0(N))
def pfD0({WS}, +N: U32, +T: FD.array__Tree<U32>) -> {{FD.array__perfect(U32, DO(N), {TD(0)}) == True{{}} : Bool}}:
  VB.mone_perfect(VC.NW(N), 0n, {H}n, DO(N), OUT1(N), T, pf1(N))''')
    for j, f in enumerate(fixed):
        w(f'def pfD{j + 1}({WS}, +N: U32, +T: FD.array__Tree<U32>) -> {{FD.array__perfect(U32, DO(N), {TD(j + 1)}) == True{{}} : Bool}}:')
        w(f'  VF.updv_perfect({V(f)}, DO(N), {TD(j)}, {f["k"]}n, pfD{j}({WA}, N, T))')

    def hb(f):
        return f'hbk(Nat.add({f["ft"].W}n, {f["k"]}n), {NCa}, {{==}})'

    # ---- size and put ----
    RS = f'({OBJ}, SFS(N))'
    w(f'''
def size_eval({ALLP})
    -> {{{Tn}_size({OBJ}) == {RS} : {Tn} & U32}}:
  %Equal.sym(Array<U32> & U32, Array.size(U32, FD.array__thaw(U32, T)), (FD.array__thaw(U32, T), FD.u32__pow2u(dw)), FD.array__size_thaw(U32, dw, T, pfT)) :
    {{{Tn}_sz0({FIXOBJS}, {FS}, O.wsz_pick(N, _)) == {RS} : {Tn} & U32}}
  %Equal.sym(Bool, U32.is_le(VC.nwu(N), FD.u32__pow2u(dw)), True{{}}, VE.le_room(N, dw, hdw, hroom)) :
    {{({OBJ}, O.padd({FS}, O.pick(_, N, 2147483648))) == {RS} : {Tn} & U32}}
  %Equal.sym(U32, O.padd({FS}, N), SFS(N), padd({NCa})) : {{({OBJ}, _) == {RS} : {Tn} & U32}}
  {{==}}
''')
    RP = f'(FD.array__thaw(U32, {OUT3}), ({OBJ}, SFS(N)))'
    TP = f'Array<U32> & ({Tn} & U32)'

    def puts(j, inner):
        """The runtime's nested puts of fixed fields j.. around `inner`."""
        t = inner
        for f in fixed[j:]:
            t = f'T.{f["ft"].p}_put({t}, U32.add(0, {f["c"]}), {fobj(f)})'
        return t
    w(f'def put_eval({ALLP})')
    w(f'    -> {{{Tn}_putn(FD.array__thaw(U32, VC.ZT(DO(N))), 0, {OBJ}) == {RP} : {TP}}}:')
    w(f'  +hd31 = hDO31({NCa})')
    w(f'  +hd32 = VB.lt32(DO(N), hd31)')
    w(f'  +hd29 = hDO29({NCa})')
    w(f'  %Equal.sym(Array<U32>, Array.set(U32, FD.array__thaw(U32, VC.ZT(DO(N))), {po}, {FS}), FD.array__thaw(U32, OUT1(N)),')
    w(f'      VB.set_n(DO(N), VC.ZT(DO(N)), {po}, {po}n, {FS}, {{==}}, hd32, ltH({po}n, {NCa}, {{==}}), pf0(N))) :')
    w(f'    {{{Tn}_pw0(0, {FIXOBJS}, T.{lp}_pvb({FS}, T.{lp}_pk(_, U32.add(0, {FS}), T.{lp}_valid({WORDS})))) == {RP} : {TP}}}')
    w(f'  %Equal.sym(O.Words & Bool, O.words_ok({WORDS}, 0, {LIMB}, False{{}}, 8), ({WORDS}, True{{}}),')
    w(f'      VE.words_ok_u64(dw, T, N, {LIMB}, c, pfT, hdw, ec, FD.nat__le_trans({toN}, VS.x8({LIMN}), U32.to_nat({LIMB}), leN({NCa}), {K_LB}), hroom)) :')
    w(f'    {{{Tn}_pw0(0, {FIXOBJS}, T.{lp}_pvb({FS}, T.{lp}_pk(FD.array__thaw(U32, OUT1(N)), U32.add(0, {FS}), _))) == {RP} : {TP}}}')
    w(f'  %Equal.sym(Array<U32> & O.Words, O.put_words(FD.array__thaw(U32, OUT1(N)), U32.add(0, {FS}), {WORDS}), (FD.array__thaw(U32, OUT2(N, T)), {WORDS}),')
    w(f'      VE.put_words_ok(DO(N), dw, OUT1(N), T, U32.add(0, {FS}), {H}n, N, pf1(N), pfT, hd31, hdw, {{==}}, {{==}}, VC.and3_x8(N, c, ec), hroom, hdst({NCa}))) :')
    w(f'    {{{Tn}_pw0(0, {FIXOBJS}, T.{lp}_pvb({FS}, O.pwn(_))) == {RP} : {TP}}}')
    w(f'  %Equal.sym(U32, O.padd({FS}, N), SFS(N), padd({NCa})) :')
    w(f'    {{({puts(0, "FD.array__thaw(U32, OUT2(N, T))")}, ({OBJ}, _)) == {RP} : {TP}}}')
    for j, f in enumerate(fixed):
        ft = f['ft']
        cur = f'T.{ft.p}_put(FD.array__thaw(U32, {TD(j)}), U32.add(0, {f["c"]}), {fobj(f)})'
        ws = ', '.join(f'w{f["k"] + i}' for i in range(ft.W))
        w(f'  %Equal.sym(Array<U32>, {cur}, FD.array__thaw(U32, {TD(j + 1)}),')
        w(f'      VT.put_{ft.p}(DO(N), {TD(j)}, U32.add(0, {f["c"]}), {f["k"]}n, {{==}}, hd29, pfD{j}({WA}, N, T), {hb(f)}, {ws})) :')
        w(f'    {{({puts(j + 1, "_")}, ({OBJ}, SFS(N))) == {RP} : {TP}}}')
    w('  {==}')
    RE = f'({OBJ}, B.Buf{{FD.array__thaw(U32, {OUT3}), SFS(N)}})'
    TE = f'{Tn} & B.Buf'
    w(f'''
# The encoder returns the object and the buffer of OUT3, {FS} + N bytes.
def encode_eval({ALLP})
    -> {{{Tn}_encode({OBJ}) == {RE} : {TE}}}:
  %Equal.sym({Tn} & U32, {Tn}_size({OBJ}), {RS}, size_eval({ALLa})) :
    {{{Tn}_enc_sized(_) == {RE} : {TE}}}
  %Equal.sym(Array<U32>, B.zeros(B.words_depth_u(VC.nwu(SFS(N)))), Array.new(U32, DO(N), 0),
      DC.zeros_at(B.words_depth_u(VC.nwu(SFS(N))), DO(N), VD.wdu(VC.nwu(SFS(N))), FD.nat__le_trans(DO(N), {KO}n, {KK}n, hDOK({NCa}), {{==}}))) :
    {{{Tn}_enc_put(SFS(N), {Tn}_putn(_, 0, {OBJ})) == {RE} : {TE}}}
  %Equal.sym(Array<U32>, Array.new(U32, DO(N), 0), FD.array__thaw(U32, VC.ZT(DO(N))), FD.array__new(U32, DO(N), 0)) :
    {{{Tn}_enc_put(SFS(N), {Tn}_putn(_, 0, {OBJ})) == {RE} : {TE}}}
  %Equal.sym({TP}, {Tn}_putn(FD.array__thaw(U32, VC.ZT(DO(N))), 0, {OBJ}), {RP}, put_eval({ALLa})) :
    {{{Tn}_enc_put(SFS(N), _) == {RE} : {TE}}}
  {{==}}
''')
    # ---- the output's words, window by window ----
    SP = f'{WS}, {NC}, +T: FD.array__Tree<U32>'
    SPa = f'{WA}, {NCa}, T'
    LT = 'List<&2, U32>'

    def win(m, p, j):
        return f'VF.WIN({m}, {p}, FD.array__slots(U32, {TD(j)}))'

    def peel_chain(m, p, lo_hi, stop, last_term, last_proof):
        """Equal.trans chain WIN(m, p, TD_M) = ... = WIN(m, p, TD_stop) = rest."""
        steps = []
        for g in range(len(fixed) - 1, stop - 1, -1):
            fg = fixed[g]
            kind = lo_hi(fg)
            if kind == 'lo':
                h = f'Nat.is_le(Nat.add(VF.slen({V(fg)}), {fg["k"]}n), {p}) == True{{}} : Bool'
            else:
                h = f'Nat.is_le(Nat.add({m}, {p}), {fg["k"]}n) == True{{}} : Bool'
            pr = f'V2.peel_{kind}({V(fg)}, DO(N), {TD(g)}, {fg["k"]}n, {m}, {p}, pfD{g}({WA}, N, T), {hb(fg)}, {{==}})'
            steps.append((win(m, p, g + 1), win(m, p, g), pr))
        # fold
        out = last_proof
        for a, b, pr in reversed(steps):
            out = f'Equal.trans({LT}, {a}, {b}, {last_term}, {pr},\n    {out})'
        return out

    def rel(fg, k0, W0):
        return 'lo' if fg['k'] + fg['ft'].W <= k0 else 'hi'
    for i, f in enumerate(x.fields):
        if f['kind'] == 'fix':
            j = fixed.index(f)
            k0, W0 = f['k'], f['ft'].W
            last = f'V2.own({V(f)}, DO(N), {TD(j)}, {k0}n, pfD{j}({WA}, N, T), {hb(f)})'
            body = peel_chain(f'{W0}n', f'{k0}n', lambda fg: rel(fg, k0, W0), j + 1, V(f), last)
            w(f'def seg{i}({SP}) -> {{{win(f"{W0}n", f"{k0}n", len(fixed))} == {V(f)} : {LT}}}:')
            w('  ' + body)
            w('')
        else:
            LM = f'VB.lm({NW}, 0n, {H}n, FD.array__slots(U32, OUT1(N)), {ST})'
            tail = (f'Equal.trans({LT}, VF.WIN(1n, {po}n, FD.array__slots(U32, OUT2(N, T))), VF.WIN(1n, {po}n, {LM}), [{FS}],\n'
                    f'    Equal.cong({LT}, {LT}, z => VF.WIN(1n, {po}n, z), FD.array__slots(U32, OUT2(N, T)), {LM}, VB.slots_mone({NW}, 0n, {H}n, DO(N), OUT1(N), T, pf1(N), hdst({NCa}))),\n'
                    f'    Equal.trans({LT}, VF.WIN(1n, {po}n, {LM}), VF.WIN(1n, {po}n, FD.array__slots(U32, OUT1(N))), [{FS}],\n'
                    f'      VF.lm_hi({NW}, 0n, {H}n, 1n, {po}n, FD.array__slots(U32, OUT1(N)), {ST}, {{==}}),\n'
                    f'      V2.own([{FS}], DO(N), VC.ZT(DO(N)), {po}n, pf0(N), hbk(Nat.add(1n, {po}n), {NCa}, {{==}}))))')
            body = peel_chain('1n', f'{po}n', lambda fg: rel(fg, po, 1), 0, f'[{FS}]', tail)
            w(f'def seg{i}({SP}) -> {{{win("1n", f"{po}n", len(fixed))} == [{FS}] : {LT}}}:')
            w('  ' + body)
            w('')
    # payload window
    LM = f'VB.lm({NW}, 0n, {H}n, FD.array__slots(U32, OUT1(N)), {ST})'
    tail = (f'Equal.trans({LT}, VF.WIN({NW}, {H}n, FD.array__slots(U32, OUT2(N, T))), VF.WIN({NW}, {H}n, {LM}), VS.wtake({NW}, {ST}),\n'
            f'    Equal.cong({LT}, {LT}, z => VF.WIN({NW}, {H}n, z), FD.array__slots(U32, OUT2(N, T)), {LM}, VB.slots_mone({NW}, 0n, {H}n, DO(N), OUT1(N), T, pf1(N), hdst({NCa}))),\n'
            f'    VB.lm_win({NW}, 0n, {H}n, FD.array__slots(U32, OUT1(N)), {ST},\n'
            f'      FD.logic__subst(Nat, z => {{Nat.is_le(Nat.add({NW}, {H}n), z) == True{{}} : Bool}}, VB.pw(DO(N)), VB.len(FD.array__slots(U32, OUT1(N))), Equal.sym(Nat, VB.len(FD.array__slots(U32, OUT1(N))), VB.pw(DO(N)), FD.array__slots_length(U32, DO(N), OUT1(N), pf1(N))), hdst({NCa})),\n'
            f'      FD.logic__subst(Nat, z => {{Nat.is_le(Nat.add({NW}, 0n), z) == True{{}} : Bool}}, VB.pw(dw), VB.len({ST}), Equal.sym(Nat, VB.len({ST}), VB.pw(dw), FD.array__slots_length(U32, dw, T, pfT)), hroom)))')
    body = peel_chain(NW, f'{H}n', lambda fg: 'lo', 0, f'VS.wtake({NW}, {ST})', tail)
    w(f'def pay_eq({SP}, +dw: Nat, +pfT: {{FD.array__perfect(U32, dw, T) == True{{}} : Bool}}, +hroom: {{Nat.is_le(Nat.add(VC.NW(N), 0n), VB.pw(dw)) == True{{}} : Bool}})')
    w(f'    -> {{{win(NW, f"{H}n", len(fixed))} == VS.wtake({NW}, {ST}) : {LT}}}:')
    w('  ' + body)
    w('')
    # header window
    w(f'def hdr_eq({SP}) -> {{{win(f"{H}n", "0n", len(fixed))} == {HDRL} : {LT}}}:')
    segs = []
    for i, f in enumerate(x.fields):
        segs.append((i, f['ft'].W if f['kind'] == 'fix' else 1, f['k'], V(f) if f['kind'] == 'fix' else f'[{FS}]'))
    R, s = H, 0
    pre = lambda t: t  # noqa: E731
    for idx, (i, Wd, k, Vs) in enumerate(segs):
        assert k == s
        if idx < len(segs) - 1:
            w(f'  %Equal.sym({LT}, {win(f"Nat.add({Wd}n, {R - Wd}n)", f"{s}n", len(fixed))}, VF.app({win(f"{Wd}n", f"{s}n", len(fixed))}, {win(f"{R - Wd}n", f"Nat.add({s}n, {Wd}n)", len(fixed))}),')
            w(f'      VF.win_split({Wd}n, {R - Wd}n, {s}n, {S3})) :')
            w(f'    {{{pre("_")} == {HDRL} : {LT}}}')
            w(f'  %Equal.sym({LT}, {win(f"{Wd}n", f"{s}n", len(fixed))}, {Vs}, seg{i}({SPa})) :')
            p0 = pre
            rest = win(f'{R - Wd}n', f'{s + Wd}n', len(fixed))
            w(f'    {{{p0(f"VF.app(_, {rest})")} == {HDRL} : {LT}}}')
            pre = (lambda p0, Vs: (lambda t: p0(f'VF.app({Vs}, {t})')))(p0, Vs)
            R, s = R - Wd, s + Wd
        else:
            assert R == Wd
            w(f'  %Equal.sym({LT}, {win(f"{Wd}n", f"{s}n", len(fixed))}, {Vs}, seg{i}({SPa})) :')
            w(f'    {{{pre("_")} == {HDRL} : {LT}}}')
    w('  {==}')
    w('')
    # ---- spec ----
    RHSk = f'Some{{F.limbs({HDR} <> {YS})}}'
    ENCR = f'List.append(&2, U32, List.append(&2, U32, F.flat({PRE}), List.append(&2, U32, N.digits(4n, VS.FSZ({PRE}, {POST})), F.flat({POST}))), F.limbs({YS}))'
    RHS = f'F.limbs({HDR} <> VS.wtake(Nat.double(c), {ST}))'
    BT = f'VS.bt(U32.to_nat(SFS(N)), F.limbs({S3}))'
    Kx = f'Nat.add({H}n, {NW})'
    w(f'''def XE({WS}, +k: Nat, +W: List<&2, U32>) -> S.Value: S.Sequence{{{ITEMS}}}

# The spec encoding of the value of words w.. and list words W (k elements).
def encE({WS}, +k: Nat, +W: List<&2, U32>,
    +hk: {{Nat.is_le(k, {LIMN}) == True{{}} : Bool}},
    +hl: {{Nat.is_le(Nat.double(k), FD.spec_common__length(U32, W)) == True{{}} : Bool}})
    -> {{Codec.encoding_for_legal_type(Spec.{n}(), XE({WA}, k, W)) == {RHSk} : {M}}}:
  +le2 = FD.logic__subst(Nat, z => {{Nat.is_le(z, VS.x8({LIMN})) == True{{}} : Bool}}, VS.x8(k), List.length(&2, U32, F.limbs({YS})),
    Equal.sym(Nat, List.length(&2, U32, F.limbs({YS})), VS.x8(k), VS.len_limbs_wtake2(k, W, hl)), VS.x8_mono(k, {LIMN}, hk))
  +fit = VS.fits_mono(4n, Nat.add(VS.FSZ({PRE}, {POST}), List.length(&2, U32, F.limbs({YS}))), Nat.add({FS}n, VS.x8({LIMN})),
    Order.add_left({FS}n, List.length(&2, U32, F.limbs({YS})), VS.x8({LIMN}), le2), {K_FIT})
  %Equal.sym({MP}, Codec.parts({ITEMS}, {CHAIN}), Some{{{PL}}},
      {CAT}) :
    {{Codec.bytes(Codec.aggregate(_, None{{}})) == {RHSk} : {M}}}
  %Equal.sym({M}, Layout.encoding(VS.fpv({PRE}, F.limbs({YS}), {POST})), Some{{{ENCR}}}, VS.enc_fpv({PRE}, {YS}, {POST}, fit)) :
    {{Codec.bytes(Codec.one(_, None{{}})) == {RHSk} : {M}}}
  {{==}}

def eSq({NC}) -> {{A.quad({Kx}) == U32.to_nat(SFS(N)) : Nat}}:
  %Equal.sym(Nat, {NW}, Nat.double(c), nwN({NCa})) : {{A.quad(Nat.add({H}n, _)) == U32.to_nat(SFS(N)) : Nat}}
  %Equal.sym(Nat, U32.to_nat(SFS(N)), Nat.add({FS}n, {toN}), eS({NCa})) : {{A.quad(Nat.add({H}n, Nat.double(c))) == _ : Nat}}
  %Equal.sym(Nat, {toN}, VS.x8(c), ec) : {{A.quad(Nat.add({H}n, Nat.double(c))) == Nat.add({FS}n, _) : Nat}}
  %Equal.sym(Nat, VS.x8(c), VB.d3(c), VB.x8_d3(c)) : {{A.quad(Nat.add({H}n, Nat.double(c))) == Nat.add({FS}n, _) : Nat}}
  {{==}}

# The output's bytes are the limbs of the header words and the list's words.
def out_eq({ALLP})
    -> {{{BT} == {RHS} : +List<U32>}}:
  %eSq({NCa}) : {{VS.bt(_, F.limbs({S3})) == {RHS} : +List<U32>}}
  %Equal.sym(+List<U32>, VS.bt(A.quad({Kx}), F.limbs({S3})), F.limbs(VS.wtake({Kx}, {S3})), VS.bt_limbs({Kx}, {S3})) :
    {{_ == {RHS} : +List<U32>}}
  %Equal.sym({LT}, VF.WIN({Kx}, 0n, {S3}), VF.app(VF.WIN({H}n, 0n, {S3}), VF.WIN({NW}, Nat.add(0n, {H}n), {S3})), VF.win_split({H}n, {NW}, 0n, {S3})) :
    {{F.limbs(_) == {RHS} : +List<U32>}}
  %Equal.sym({LT}, VF.WIN({H}n, 0n, {S3}), {HDRL}, hdr_eq({SPa})) :
    {{F.limbs(VF.app(_, VF.WIN({NW}, {H}n, {S3}))) == {RHS} : +List<U32>}}
  %Equal.sym({LT}, VF.WIN({NW}, {H}n, {S3}), VS.wtake({NW}, {ST}), pay_eq({SPa}, dw, pfT, hroom)) :
    {{F.limbs(VF.app({HDRL}, _)) == {RHS} : +List<U32>}}
  %Equal.sym(Nat, {NW}, Nat.double(c), nwN({NCa})) :
    {{F.limbs(VF.app({HDRL}, VS.wtake(_, {ST}))) == {RHS} : +List<U32>}}
  {{==}}

def hl_t({ALLP})
    -> {{Nat.is_le(Nat.double(c), FD.spec_common__length(U32, {ST})) == True{{}} : Bool}}:
  %Equal.sym(Nat, FD.spec_common__length(U32, {ST}), VB.pw(dw), FD.array__slots_length(U32, dw, T, pfT)) : {{Nat.is_le(Nat.double(c), _) == True{{}} : Bool}}
  %nwN({NCa}) : {{Nat.is_le(_, VB.pw(dw)) == True{{}} : Bool}}
  FD.logic__subst(Nat, z => {{Nat.is_le(z, VB.pw(dw)) == True{{}} : Bool}}, Nat.add({NW}, 0n), {NW}, FD.nat__add_zero({NW}), hroom)

# The bytes the encoder writes are the spec/codec.bend encoding of the object's value.
def encode_spec({ALLP})
    -> Decoding.decodes(Spec.{n}(), {BT}, XE({WA}, c, {ST})):
  Equal.trans({M}, Codec.encoding_for_legal_type(Spec.{n}(), XE({WA}, c, {ST})), Some{{{RHS}}}, Some{{{BT}}},
    encE({WA}, c, {ST}, hc, hl_t({ALLa})),
    Equal.cong(+List<U32>, {M}, z => Some{{z}}, {RHS}, {BT}, Equal.sym(+List<U32>, {BT}, {RHS}, out_eq({ALLa}))))
''')
    return '\n'.join(L) + '\n'
