#!/usr/bin/env python3
"""Readers of BeaconState's FIXED fields at any byte position x (the field's bytes are the
window slice UW.WX(t, x, S)), for the byte-offset BeaconState module.

    python3 codegen/var_fixx.py [--check] [--no-big]

One module per field type p, proofs/obj/{big_,}vfx_<p>.bend, exporting (S = the field's
byte size, SCH = its spec schema):
  OBJ(d, t, x)                     the object T.<p>_read returns at byte position x
  rdx(d, t, n, off, x, e, hd, pf, hb)
      : T.<p>_read(UA.BF(t, n), off, S) == (UA.BF(t, n), OBJ(d, t, x))
        (e: off = x, hd: d < 28, pf: t perfect of depth d, hb: x + S <= 4 2^d)
  VAL(t, x)                        the spec value over the words UR.RWN(t, x + 4 k)
  prt(d, t, x, pf, hb)
      : Codec.parts(VAL(t, x), SCH) == Some{[S.Fixed{UW.WX(t, x, S)}]}
Vectors are read by copy_into (OBJ holds vua_fixb's copy CTN(d, t, x, S, dz)); their
values are arr_vec's chunkings of UR.RWS(S / 4, t, x), proved for every word list (no
element is unrolled). Modules whose statements carry closed sizes above stock Bend's
stack are big_ files.
"""
import sys
from pathlib import Path
import runtime_refs as RR  # noqa: E402  the runtime split: the monoliths' text, the split files' imports

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'codegen'))

HEAD = ['import Base', 'import ../../src/buffer.bend as B', 'import ../../src/obj.bend as O',
        'import ../../types/fulu_obj.bend as T', 'import ../../types/schema.bend as S', 'import ../../types/primitive.bend as P',
        'import ../compact/found.bend as FD', 'import ../compact/arith.bend as A', 'import ../../proofs/nat_order.bend as Order',
        'import ../../spec/layout.bend as Layout', 'import ../../spec/codec.bend as Codec', 'import ../../spec/nat_bytes.bend as N',
        'import ../../spec/fulu_schemas.bend as Spec', 'import ./spec_fixed.bend as F', 'import ./vspec.bend as VS',
        'import ./vbuf.bend as VB', 'import ./vmr.bend as VMR', 'import ./vua.bend as UA', 'import ./vua_rd.bend as UR',
        'import ./vua_win.bend as UW', 'import ./vua_fix.bend as VTX', 'import ./vbx.bend as VBX', 'import ./vua_fixb.bend as VXB',
        'import ./arr_vec.bend as AV']
TRUE = 'True{} : Bool'
TR = 'FD.array__Tree<U32>'
BIG = 1 << 40    # (no vector needs checkq --big: sizes stay literals, values stay neutral)


def log2c(n):
    k = 0
    while (1 << k) < n:
        k += 1
    return k


def sig(name, S, rest='', sn=None):
    return (f'def {name}(+d: Nat, +t: {TR}, +n: U32, +off: U32, +x: Nat, +e: {{U32.to_nat(off) == x : Nat}},\n'
            f'    +hd: {{Nat.is_lt(d, 28n) == {TRUE}}}, +pf: {{FD.array__perfect(U32, d, t) == {TRUE}}},\n'
            f'    +hb: {{Nat.is_le(Nat.add(x, {sn or str(S) + "n"}), A.quad(VB.pw(d))) == {TRUE}}}){rest}')


GEN_HEAD = HEAD + ['import ./vcopy.bend as VC', 'import ./schema_shapes.bend as SH', 'import ./arr_spec.bend as AS', 'import ../../spec/schema.bend as SSC']


def gen_text():
    """proofs/obj/vfxg.bend: the readers and values, for every size (instantiated by the
    vfx_<p> modules with closed facts that evaluate to True)."""
    L = list(GEN_HEAD) + ['', '# GENERATED by codegen/var_fixx.py. Do not edit.',
                          '# Fixed fields at any byte position, for every size: see codegen/var_fixx.py.', '']
    P = 'A.quad(VB.pw(d))'
    L.append(f'''# M, as a term that stays neutral while x is (so a value over M words is not unfolded)
def CNT(+x: Nat, +M: Nat) -> Nat: Nat.add(Nat.sub(x, x), M)
def cnt_eq(+x: Nat, +M: Nat) -> {{CNT(x, M) == M : Nat}}:
  %Equal.sym(Nat, Nat.sub(x, x), 0n, FD.nat__sub_self(x)) : {{Nat.add(_, M) == M : Nat}}
  {{==}}

''')
    L.append(f'''# ---- positions and splits ----------------------------------------------------------------------

def lenC(+t: {TR}, +x: Nat, +M: Nat) -> {{FD.spec_common__length(U32, UR.RWS(CNT(x, M), t, x)) == M : Nat}}:
  %Equal.sym(Nat, CNT(x, M), M, cnt_eq(x, M)) : {{FD.spec_common__length(U32, UR.RWS(_, t, x)) == M : Nat}}
  UR.rws_len(M, t, x)

# x < P from x + S <= P, S > 0
def ltx(+x: Nat, +S: Nat, +P: Nat, +h0: {{Nat.is_lt(0n, S) == {TRUE}}}, +hb: {{Nat.is_le(Nat.add(x, S), P) == {TRUE}}}) -> {{Nat.is_lt(x, P) == {TRUE}}}:
  FD.nat__lt_le_trans(x, Nat.add(x, S), P, FD.logic__subst(Nat, z => {{Nat.is_lt(z, Nat.add(x, S)) == {TRUE}}}, Nat.add(x, 0n), x, FD.nat__add_zero(x),
    FD.nat__lt_add_left(0n, S, x, h0)), hb)

# off + c is at byte C + x, for C < S the field size
def offc(+d: Nat, +off: U32, +c: U32, +C: Nat, +x: Nat, +S: Nat, +e: {{U32.to_nat(off) == x : Nat}}, +hd: {{Nat.is_lt(d, 28n) == {TRUE}}},
    +eC: {{Nat.is_eq(U32.to_nat(c), C) == {TRUE}}}, +hC: {{Nat.is_lt(C, S) == {TRUE}}}, +hb: {{Nat.is_le(Nat.add(x, S), {P}) == {TRUE}}})
    -> {{U32.to_nat(U32.add(off, c)) == Nat.add(x, C) : Nat}}:
  %FD.nat__add_comm(C, x) : {{U32.to_nat(U32.add(off, c)) == _ : Nat}}
  offc0(d, off, c, C, x, S, e, hd, eC, hC, hb)
def offc0(+d: Nat, +off: U32, +c: U32, +C: Nat, +x: Nat, +S: Nat, +e: {{U32.to_nat(off) == x : Nat}}, +hd: {{Nat.is_lt(d, 28n) == {TRUE}}},
    +eC: {{Nat.is_eq(U32.to_nat(c), C) == {TRUE}}}, +hC: {{Nat.is_lt(C, S) == {TRUE}}}, +hb: {{Nat.is_le(Nat.add(x, S), {P}) == {TRUE}}})
    -> {{U32.to_nat(U32.add(off, c)) == Nat.add(C, x) : Nat}}:
  +ec = FD.nat__eq_from_is_eq(U32.to_nat(c), C, eC)
  +h = FD.logic__subst(Nat, z => {{Nat.is_lt(z, {P}) == {TRUE}}}, Nat.add(x, C), Nat.add(C, x), FD.nat__add_comm(x, C),
    FD.nat__lt_le_trans(Nat.add(x, C), Nat.add(x, S), {P}, FD.nat__lt_add_left(C, S, x, hC), hb))
  %Equal.sym(Nat, C, U32.to_nat(c), Equal.sym(Nat, U32.to_nat(c), C, ec)) : {{U32.to_nat(U32.add(off, c)) == Nat.add(_, x) : Nat}}
  UR.offx(d, off, c, x, e, FD.nat__lt_trans(d, 28n, 30n, hd, {{==}}), FD.logic__subst(Nat, z => {{Nat.is_lt(Nat.add(z, x), {P}) == {TRUE}}}, C, U32.to_nat(c), Equal.sym(Nat, U32.to_nat(c), C, ec), h))

# room for S2 bytes at x + C inside a field of S bytes at x
def roomc(+x: Nat, +S: Nat, +C: Nat, +S2: Nat, +P: Nat, +hb: {{Nat.is_le(Nat.add(x, S), P) == {TRUE}}}, +hc: {{Nat.is_le(Nat.add(C, S2), S) == {TRUE}}})
    -> {{Nat.is_le(Nat.add(Nat.add(x, C), S2), P) == {TRUE}}}:
  FD.logic__subst(Nat, z => {{Nat.is_le(z, P) == {TRUE}}}, Nat.add(x, Nat.add(C, S2)), Nat.add(Nat.add(x, C), S2), Equal.sym(Nat, Nat.add(Nat.add(x, C), S2), Nat.add(x, Nat.add(C, S2)), FD.nat__add_assoc(x, C, S2)),
    FD.nat__le_trans(Nat.add(x, Nat.add(C, S2)), Nat.add(x, S), P, Order.add_left(x, Nat.add(C, S2), S, hc), hb))

# the window's S = S1 + S2 bytes: the limbs of the M words at x (4 M = S1), then S2 bytes at S1 + x
def splitC(+d: Nat, +t: {TR}, +x: Nat, +pf: {{FD.array__perfect(U32, d, t) == {TRUE}}}, +M: Nat, +S1: Nat, +S2: Nat, +S: Nat,
    +eS: {{Nat.is_eq(A.quad(M), S1) == {TRUE}}}, +hS: {{Nat.is_eq(Nat.add(S1, S2), S) == {TRUE}}}, +hw: {{Nat.is_le(Nat.add(x, S), {P}) == {TRUE}}})
    -> {{UW.WX(t, x, S) == List.append(&2, U32, F.limbs(UR.RWS(CNT(x, M), t, x)), UW.WX(t, Nat.add(x, S1), S2)) : +List<U32>}}:
  %FD.nat__add_comm(S1, x) : {{UW.WX(t, x, S) == List.append(&2, U32, F.limbs(UR.RWS(CNT(x, M), t, x)), UW.WX(t, _, S2)) : +List<U32>}}
  splitC0(d, t, x, pf, M, S1, S2, S, eS, hS, hw)
def splitC0(+d: Nat, +t: {TR}, +x: Nat, +pf: {{FD.array__perfect(U32, d, t) == {TRUE}}}, +M: Nat, +S1: Nat, +S2: Nat, +S: Nat,
    +eS: {{Nat.is_eq(A.quad(M), S1) == {TRUE}}}, +hS: {{Nat.is_eq(Nat.add(S1, S2), S) == {TRUE}}}, +hw: {{Nat.is_le(Nat.add(x, S), {P}) == {TRUE}}})
    -> {{UW.WX(t, x, S) == List.append(&2, U32, F.limbs(UR.RWS(CNT(x, M), t, x)), UW.WX(t, Nat.add(S1, x), S2)) : +List<U32>}}:
  +eq = FD.nat__eq_from_is_eq(A.quad(M), S1, eS)
  +es = FD.nat__eq_from_is_eq(Nat.add(S1, S2), S, hS)
  %Equal.sym(Nat, CNT(x, M), M, cnt_eq(x, M)) : {{UW.WX(t, x, S) == List.append(&2, U32, F.limbs(UR.RWS(_, t, x)), UW.WX(t, Nat.add(S1, x), S2)) : +List<U32>}}
  %es : {{UW.WX(t, x, _) == List.append(&2, U32, F.limbs(UR.RWS(M, t, x)), UW.WX(t, Nat.add(S1, x), S2)) : +List<U32>}}
  %eq : {{UW.WX(t, x, Nat.add(_, S2)) == List.append(&2, U32, F.limbs(UR.RWS(M, t, x)), UW.WX(t, Nat.add(_, x), S2)) : +List<U32>}}
  UW.headWX(d, t, x, M, S2, pf, FD.logic__subst(Nat, z => {{Nat.is_le(Nat.add(x, z), {P}) == {TRUE}}}, S, Nat.add(A.quad(M), S2),
    Equal.trans(Nat, S, Nat.add(S1, S2), Nat.add(A.quad(M), S2), Equal.sym(Nat, Nat.add(S1, S2), S, es), Equal.cong(Nat, Nat, z => Nat.add(z, S2), S1, A.quad(M), Equal.sym(Nat, A.quad(M), S1, eq))), hw))

''')
    L.append(f'''# copy_into of L bytes (S = L) at off (byte position x) into a zero storage of depth dz
def rdg(+d: Nat, +t: {TR}, +n: U32, +off: U32, +x: Nat, +e: {{U32.to_nat(off) == x : Nat}},
    +hd: {{Nat.is_lt(d, 28n) == {TRUE}}}, +pf: {{FD.array__perfect(U32, d, t) == {TRUE}}},
    +L: U32, +S: Nat, +dz: Nat, +k: Nat, +eS: {{Nat.is_eq(U32.to_nat(L), S) == {TRUE}}}, +hdz: {{Nat.is_lt(dz, 31n) == {TRUE}}},
    +hr: {{Nat.is_le(Nat.add(VC.NW(L), 0n), VB.pw(dz)) == {TRUE}}}, +hk: {{Nat.is_lt(k, 31n) == {TRUE}}}, +hy: {{Nat.is_le(VC.YL(L), VB.pw(k)) == {TRUE}}},
    +hb: {{Nat.is_le(Nat.add(x, S), {P}) == {TRUE}}})
    -> {{O.copy_into(UA.BF(t, n), off, L, Array.new(U32, dz, 0)) == (UA.BF(t, n), O.Words{{FD.array__thaw(U32, VXB.CTN(d, t, x, L, dz)), L}}) : B.Buf & O.Words}}:
  +hw = FD.logic__subst(Nat, z => {{Nat.is_le(Nat.add(x, z), {P}) == {TRUE}}}, S, U32.to_nat(L), Equal.sym(Nat, U32.to_nat(L), S, FD.nat__eq_from_is_eq(U32.to_nat(L), S, eS)), hb)
  %VXB.ct_n(d, t, off, x, L, dz, e) : {{O.copy_into(UA.BF(t, n), off, L, Array.new(U32, dz, 0)) == (UA.BF(t, n), O.Words{{FD.array__thaw(U32, _), L}}) : B.Buf & O.Words}}
  VBX.copy_into_at(d, t, n, off, L, dz, k, pf, FD.nat__lt_trans(d, 28n, 31n, hd, {{==}}), hdz, UW.hsx(d, off, x, L, e, hd, hw), hr, hk, hy)
''')
    for ch, mm, vp, el in (('ch8', 'm8', 'vparts8', 'S.ByteVector{32n}'), ('chu2', 'm2', 'vpartsu2', 'S.Unsigned{P.U64{}}'), ('ch12', 'm12', 'vparts12', 'S.ByteVector{48n}')):
        W = 'UR.RWS(M, t, x)'
        L.append(f'''# the value of a vector of k elements over the M words at x: its parts are the S window bytes
def prt_{ch}(+d: Nat, +t: {TR}, +x: Nat, +pf: {{FD.array__perfect(U32, d, t) == {TRUE}}}, +s: S.Schema, +k: Nat, +M: Nat, +S: Nat,
    +hs: {{SH.is_Vector(s) == {TRUE}}}, +he: {{SH.Vector_element(s) == {el} : S.Schema}}, +hk: {{Nat.is_eq(SH.Vector_length(s), k) == {TRUE}}},
    +hk0: {{Nat.is_lt(0n, k) == {TRUE}}}, +hL: {{Nat.is_eq(AV.{mm}(k), M) == {TRUE}}}, +eS: {{Nat.is_eq(A.quad(M), S) == {TRUE}}},
    +hf: {{N.fits(4n, Nat.add(S, 0n)) == {TRUE}}}, +hb: {{Nat.is_le(Nat.add(x, S), {P}) == {TRUE}}})
    -> {{Codec.parts(S.Sequence{{AV.{ch}(UR.RWS(CNT(x, M), t, x))}}, s) == Some{{[S.Fixed{{UW.WX(t, x, S)}}]}} : Maybe<&2, +List<S.Part>>}}:
  %Equal.sym(Nat, CNT(x, M), M, cnt_eq(x, M)) : {{Codec.parts(S.Sequence{{AV.{ch}(UR.RWS(_, t, x))}}, s) == Some{{[S.Fixed{{UW.WX(t, x, S)}}]}} : Maybe<&2, +List<S.Part>>}}
  prt0_{ch}(d, t, x, pf, s, k, M, S, hs, he, hk, hk0, hL, eS, hf, hb)
def prt0_{ch}(+d: Nat, +t: {TR}, +x: Nat, +pf: {{FD.array__perfect(U32, d, t) == {TRUE}}}, +s: S.Schema, +k: Nat, +M: Nat, +S: Nat,
    +hs: {{SH.is_Vector(s) == {TRUE}}}, +he: {{SH.Vector_element(s) == {el} : S.Schema}}, +hk: {{Nat.is_eq(SH.Vector_length(s), k) == {TRUE}}},
    +hk0: {{Nat.is_lt(0n, k) == {TRUE}}}, +hL: {{Nat.is_eq(AV.{mm}(k), M) == {TRUE}}}, +eS: {{Nat.is_eq(A.quad(M), S) == {TRUE}}},
    +hf: {{N.fits(4n, Nat.add(S, 0n)) == {TRUE}}}, +hb: {{Nat.is_le(Nat.add(x, S), {P}) == {TRUE}}})
    -> {{Codec.parts(S.Sequence{{AV.{ch}({W})}}, s) == Some{{[S.Fixed{{UW.WX(t, x, S)}}]}} : Maybe<&2, +List<S.Part>>}}:
  +eq = FD.nat__eq_from_is_eq(A.quad(M), S, eS)
  +hq = FD.logic__subst(Nat, z => {{Nat.is_le(Nat.add(x, z), {P}) == {TRUE}}}, S, A.quad(M), Equal.sym(Nat, A.quad(M), S, eq), hb)
  +hN = Equal.trans(Nat, F.wlen({W}), A.quad(M), S,
    Equal.trans(Nat, F.wlen({W}), A.quad(List.length(&2, U32, {W})), A.quad(M), VS.wlen_quad({W}),
      Equal.cong(Nat, Nat, z => A.quad(z), List.length(&2, U32, {W}), M, Equal.trans(Nat, List.length(&2, U32, {W}), FD.spec_common__length(U32, {W}), M, VMR.len_eq({W}), UR.rws_len(M, t, x)))), eq)
  %eq : {{Codec.parts(S.Sequence{{AV.{ch}({W})}}, s) == Some{{[S.Fixed{{UW.WX(t, x, _)}}]}} : Maybe<&2, +List<S.Part>>}}
  %UR.rws_bytes(M, d, t, x, pf, hq) : {{Codec.parts(S.Sequence{{AV.{ch}({W})}}, s) == Some{{[S.Fixed{{_}}]}} : Maybe<&2, +List<S.Part>>}}
  AV.{vp}(s, {W}, k, M, S, hs, he, hk, hk0, UR.rws_len(M, t, x), hL, hN, hf)
''')
    L.append(sc_text())
    out = []
    for blk in L:
        for X, X0 in (('prt_', 'prt0_'), ('offc(', 'offc0('), ('splitC(', 'splitC0(')):
            if f'def {X0}' in blk:
                a = blk.index(f'def {X}')
                b = blk.index(f'def {X0}')
                e = blk.find('\n\n', b)
                e = len(blk) if e < 0 else e + 1
                blk = blk[:a] + blk[b:e].rstrip('\n') + '\n' + blk[a:b] + blk[e:]
        out.append(blk)
    return '\n'.join(out) + '\n'


def sc_text():
    """SyncCommittee's parts over any 6144 pubkey words W and aggregate words g (after
    codegen/spec_arr.py sync_committee, with W a variable), and the window splits."""
    import re
    import spec_arr as SA
    P = 'A.quad(VB.pw(d))'
    g = [f'g{i}' for i in range(12)]
    G = '[' + ', '.join(g) + ']'
    gsig = ', '.join(f'+{x}: U32' for x in g)
    spec = 'Spec.SyncCommittee()'
    WA = 'W'
    VAL = f'S.Sequence{{S.Items{{S.Sequence{{AV.ch12({WA})}}, S.Items{{S.BytesValue{{SF.limbs({G})}}, S.EmptyItems{{}}}}}}}}'
    PT = 'Maybe<&2, +List<S.Part>>'
    FL = f'SF.flat([{WA}, {G}])'
    RHSF = f'Some{{[S.Fixed{{{FL}}}]}}'
    fs = 'SH.Container_fields(s)'
    h1, t1 = f'SH.Chain_head({fs})', f'SH.Chain_tail({fs})'
    h2, t2 = f'SH.Chain_head({t1})', f'SH.Chain_tail({t1})'
    BV = 'S.ByteVector{48n}'
    V1 = f'S.Vector{{{BV}, SH.Vector_length({h1})}}'
    names = 'SH.Container_names(s)'
    gg = lambda sch, rhs: f'{{Codec.parts({VAL}, {sch}) == {rhs} : {PT}}}'
    la, lg = f'SF.limbs({WA})', f'SF.limbs({G})'
    L = [f'# SyncCommittee\'s parts over any M = 6144 pubkey words W and any aggregate words g',
         f'def sc_parts(+s: S.Schema, +es: {{s == {spec} : S.Schema}}, +W: List<&2, U32>, +M: Nat, +S1: Nat, +Sn: Nat, {gsig},',
         f'    +hl: {{F.spec_common__length(U32, W) == M : Nat}}, +hm: {{Nat.is_eq(AV.m12(512n), M) == True{{}} : Bool}},',
         f'    +h1: {{Nat.is_eq(A.quad(M), S1) == True{{}} : Bool}}, +hS: {{Nat.is_eq(Nat.add(S1, Nat.add(48n, 0n)), Sn) == True{{}} : Bool}},',
         f'    +hf: {{NB.fits(4n, Nat.add(Sn, 0n)) == True{{}} : Bool}}, +hf1: {{NB.fits(4n, Nat.add(S1, 0n)) == True{{}} : Bool}})',
         f'    -> {{Codec.parts({VAL}, s) == Some{{[S.Fixed{{List.append(&2, U32, {la}, {lg})}}]}} : {PT}}}:']
    w = L.append
    w(f'  %AS.app_nil({lg}) :')
    w('    ' + gg('s', f'Some{{[S.Fixed{{List.append(&2, U32, {la}, _)}}]}}'))
    steps = [
        (f'Equal.sym(S.Schema, s, S.Container{{{names}, {fs}}}, SH.Container_shape(s, {SA.bfact(spec, "SH.is_Container(s)")}))', '_'),
        (f'Equal.sym(S.Schema, {fs}, S.Chain{{{h1}, {t1}}}, SH.Chain_shape({fs}, {SA.bfact(spec, f"SH.is_Chain({fs})")}))', f'S.Container{{{names}, _}}'),
        (f'Equal.sym(S.Schema, {t1}, S.Chain{{{h2}, {t2}}}, SH.Chain_shape({t1}, {SA.bfact(spec, f"SH.is_Chain({t1})")}))', f'S.Container{{{names}, S.Chain{{{h1}, _}}}}'),
        (f'Equal.sym(S.Schema, {t2}, S.End{{}}, SH.End_shape({t2}, {SA.bfact(spec, f"SH.is_End({t2})")}))', f'S.Container{{{names}, S.Chain{{{h1}, S.Chain{{{h2}, _}}}}}}'),
        (f'Equal.sym(S.Schema, {h1}, S.Vector{{SH.Vector_element({h1}), SH.Vector_length({h1})}}, SH.Vector_shape({h1}, {SA.bfact(spec, f"SH.is_Vector({h1})")}))', f'S.Container{{{names}, S.Chain{{_, S.Chain{{{h2}, S.End{{}}}}}}}}'),
        (f'Equal.sym(S.Schema, SH.Vector_element({h1}), {BV}, {SA.sfact(spec, f"SH.Vector_element({h1})", BV)})', f'S.Container{{{names}, S.Chain{{S.Vector{{_, SH.Vector_length({h1})}}, S.Chain{{{h2}, S.End{{}}}}}}}}'),
        (f'Equal.sym(S.Schema, {h2}, {BV}, {SA.sfact(spec, h2, BV)})', f'S.Container{{{names}, S.Chain{{{V1}, S.Chain{{_, S.End{{}}}}}}}}'),
    ]
    for eq, sch in steps:
        w(f'  %{eq} :')
        w('    ' + gg(sch, RHSF))
    FIELDS = f'S.Chain{{{V1}, S.Chain{{{BV}, S.End{{}}}}}}'
    agg = lambda a_, b_: f'{{Codec.aggregate(Codec.concatenate({a_}, Codec.concatenate({b_}, Some{{[]}})), SSC.fixed_size({FIELDS})) == {RHSF} : {PT}}}'
    kf = SA.bfact(spec, f'Nat.is_eq(SH.Vector_length({h1}), 512n)')
    eq1 = 'F.nat__eq_from_is_eq(A.quad(M), S1, h1)'
    hN = (f'Equal.trans(Nat, SF.wlen(W), A.quad(M), S1, Equal.trans(Nat, SF.wlen(W), A.quad(List.length(&2, U32, W)), A.quad(M), VS.wlen_quad(W), '
          f'Equal.cong(Nat, Nat, z => A.quad(z), List.length(&2, U32, W), M, Equal.trans(Nat, List.length(&2, U32, W), F.spec_common__length(U32, W), M, VMR.len_eq(W), hl))), {eq1})')
    vp = (f'AV.vparts12({V1}, {WA}, 512n, M, S1, {{==}}, {{==}}, {kf}, {{==}}, hl, hm, {hN}, hf1)')
    P1 = f'Codec.parts(S.Sequence{{AV.ch12({WA})}}, {V1})'
    P2 = f'Codec.parts(S.BytesValue{{{lg}}}, {BV})'
    F1 = f'Some{{[S.Fixed{{SF.limbs({WA})}}]}}'
    F2 = f'Some{{[S.Fixed{{{lg}}}]}}'
    w(f'  %Equal.sym({PT}, {P1}, {F1}, {vp}) :')
    w('    ' + agg('_', P2))
    w(f'  %Equal.sym({PT}, {P2}, {F2}, SF.bytes_part(g0, [{", ".join(g[1:])}], {{==}})) :')
    w('    ' + agg(F1, '_'))
    x = f'Nat.add(Nat.mul(SH.Vector_length({h1}), 48n), Nat.add(48n, 0n))'
    ea = f'Equal.trans(Nat, List.length(&2, U32, SF.limbs({WA})), SF.wlen({WA}), S1, AS.len_limbs({WA}), {hN})'
    w(f'  AS.agg([{WA}, {G}], {x}, Sn,')
    w(f'    AS.add2(List.length(&2, U32, SF.limbs({WA})), List.length(&2, U32, {lg}), S1, 48n, Sn, {ea}, {{==}}, hS), hf)')
    t = '\n'.join(L) + '\n'
    t = t.replace('SF.', '@SF@')
    t = re.sub(r'(?<![A-Za-z_@])F\.', 'FD.', t)
    t = t.replace('@SF@', 'F.').replace('NB.', 'N.')
    return t


def rt_depth(p):
    """The zero storage depth the runtime reader of p allocates."""
    import re
    src = RR.mono_text('fulu')
    m = re.search(rf'^def {p}_read\(.*Array\.new\(U32, (\d+)n, 0\)\)$', src, re.M)
    return int(m.group(1))


def big_pow(S):
    """A byte size handled symbolically (proofs/obj/vbig.bend): a power of two of at least 2^16."""
    return S >= 65536 and S & (S - 1) == 0


def vec_text(p, S, k, sch, ch, el):
    """A Vector of k elements, S bytes, read by copy_into."""
    M = S // 4
    EL = {'ch8': 'S.ByteVector{32n}', 'chu2': 'S.Unsigned{P.U64{}}', 'ch12': 'S.ByteVector{48n}'}[ch]
    dz = rt_depth(p)
    ky = log2c(S + 31)
    L = list(HEAD) + ['import ./schema_shapes.bend as SH', 'import ./vfxg.bend as VXG'] + (['import ./vbig.bend as VG'] if big_pow(S) and ch != 'ch12' else []) + [
        '', '# GENERATED by codegen/var_fixx.py. Do not edit.',
        f'# {p}: Vector[{el}, {k}] ({S} bytes) at any byte position: see codegen/var_fixx.py.', '']
    if big_pow(S) and ch != 'ch12':
        # the size as U32.to_nat(S) and the counts over U32.to_nat(k): the facts are symbolic
        # (vbig.bend); closed, they were unary work of millions of steps
        r, e = S.bit_length() - 1, k.bit_length() - 1
        q = r - 2
        mm, es = ('m8', 'es_pow') if ch == 'ch8' else ('m2', 'es_pow2')
        SN, KN = f'U32.to_nat({S})', f'U32.to_nat({k})'
        EK = f'VG.u32pow({k}, {e}n, {{==}}, {{==}})'
        L.append(f'''def OBJ(+d: Nat, +t: {TR}, +x: Nat) -> O.Words: O.Words{{FD.array__thaw(U32, VXB.CTN(d, t, x, {S}, {dz}n)), {S}}}

{sig('rdx', S, sn=SN)}
    -> {{T.{p}_read(UA.BF(t, n), off, {S}) == (UA.BF(t, n), OBJ(d, t, x)) : B.Buf & O.Words}}:
  VXG.rdg(d, t, n, off, x, e, hd, pf, {S}, {SN}, {dz}n, {ky}n, FD.nat__is_eq_refl({SN}), {{==}}, VG.nw_pow({S}, {q}n, {dz}n, {{==}}, {{==}}, {{==}}), {{==}},
    VG.yl_pow({S}, {r}n, {ky}n, {{==}}, {{==}}, {{==}}, {{==}}), hb)

def VAL(+t: {TR}, +x: Nat) -> S.Value: S.Sequence{{AV.{ch}(UR.RWS(VXG.CNT(x, AV.{mm}({KN})), t, x))}}

def prt(+d: Nat, +t: {TR}, +x: Nat, +pf: {{FD.array__perfect(U32, d, t) == {TRUE}}}, +hb: {{Nat.is_le(Nat.add(x, {SN}), A.quad(VB.pw(d))) == {TRUE}}},
    +s: S.Schema, +es: {{s == {sch} : S.Schema}})
    -> {{Codec.parts(VAL(t, x), s) == Some{{[S.Fixed{{UW.WX(t, x, {SN})}}]}} : Maybe<&2, +List<S.Part>>}}:
  VXG.prt_{ch}(d, t, x, pf, s, {KN}, AV.{mm}({KN}), {SN},
    FD.logic__subst(S.Schema, z => {{SH.is_Vector(z) == {TRUE}}}, {sch}, s, Equal.sym(S.Schema, s, {sch}, es), {{==}}),
    FD.logic__subst(S.Schema, z => {{SH.Vector_element(z) == {EL} : S.Schema}}, {sch}, s, Equal.sym(S.Schema, s, {sch}, es), {{==}}),
    FD.logic__subst(S.Schema, z => {{Nat.is_eq(SH.Vector_length(z), {KN}) == {TRUE}}}, {sch}, s, Equal.sym(S.Schema, s, {sch}, es), {{==}}),
    VG.pos_pow({KN}, {e}n, {EK}), FD.nat__is_eq_refl(AV.{mm}({KN})), VG.{es}({S}, {KN}, {e}n, {r}n, {EK}, {{==}}, {{==}}, {{==}}),
    VG.fits_pow({S}, {r}n, {{==}}, {{==}}), hb)
''')
        return '\n'.join(L) + '\n'
    L.append(f'''def OBJ(+d: Nat, +t: {TR}, +x: Nat) -> O.Words: O.Words{{FD.array__thaw(U32, VXB.CTN(d, t, x, {S}, {dz}n)), {S}}}

{sig('rdx', S)}
    -> {{T.{p}_read(UA.BF(t, n), off, {S}) == (UA.BF(t, n), OBJ(d, t, x)) : B.Buf & O.Words}}:
  VXG.rdg(d, t, n, off, x, e, hd, pf, {S}, {S}n, {dz}n, {ky}n, {{==}}, {{==}}, {{==}}, {{==}}, {{==}}, hb)

def VAL(+t: {TR}, +x: Nat) -> S.Value: S.Sequence{{AV.{ch}(UR.RWS(VXG.CNT(x, {M}n), t, x))}}

def prt(+d: Nat, +t: {TR}, +x: Nat, +pf: {{FD.array__perfect(U32, d, t) == {TRUE}}}, +hb: {{Nat.is_le(Nat.add(x, {S}n), A.quad(VB.pw(d))) == {TRUE}}},
    +s: S.Schema, +es: {{s == {sch} : S.Schema}})
    -> {{Codec.parts(VAL(t, x), s) == Some{{[S.Fixed{{UW.WX(t, x, {S}n)}}]}} : Maybe<&2, +List<S.Part>>}}:
  VXG.prt_{ch}(d, t, x, pf, s, {k}n, {M}n, {S}n,
    FD.logic__subst(S.Schema, z => {{SH.is_Vector(z) == {TRUE}}}, {sch}, s, Equal.sym(S.Schema, s, {sch}, es), {{==}}),
    FD.logic__subst(S.Schema, z => {{SH.Vector_element(z) == {EL} : S.Schema}}, {sch}, s, Equal.sym(S.Schema, s, {sch}, es), {{==}}),
    FD.logic__subst(S.Schema, z => {{Nat.is_eq(SH.Vector_length(z), {k}n) == {TRUE}}}, {sch}, s, Equal.sym(S.Schema, s, {sch}, es), {{==}}),
    {{==}}, {{==}}, {{==}}, {{==}}, hb)
''')
    return '\n'.join(L) + '\n'


def sc_mod():
    """SyncCommittee: Vector[BLSPubkey, 512] (copy_into), then a Bytes48."""
    S, S1, M, dz = 24624, 24576, 6144, rt_depth('v512_b48')
    ky = log2c(S1 + 31)
    P = 'A.quad(VB.pw(d))'
    y = f'Nat.add(x, {S1}n)'
    G = [f'UR.RWN(t, {y})' if k == 0 else f'UR.RWN(t, {4 * k}n+{y})' for k in range(12)]
    PK = f'O.Words{{FD.array__thaw(U32, VXB.CTN(d, t, x, {S1}, {dz}n)), {S1}}}'
    B48 = 'T.Bytes48{' + ', '.join(G) + '}'
    OBJ = f'T.SyncCommittee{{{PK}, {B48}}}'
    VAL = f'S.Sequence{{S.Items{{S.Sequence{{AV.ch12(UR.RWS(VXG.CNT(x, {M}n), t, x))}}, S.Items{{S.BytesValue{{F.limbs([{", ".join(G)}])}}, S.EmptyItems{{}}}}}}}}'
    RHS = f'(UA.BF(t, n), OBJ(d, t, x))'
    L = list(HEAD) + ['import ./schema_shapes.bend as SH', 'import ./vfxg.bend as VXG', '', '# GENERATED by codegen/var_fixx.py. Do not edit.',
                      f'# SyncCommittee ({S} bytes) at any byte position: see codegen/var_fixx.py.', '']
    L.append(f'''def OBJ(+d: Nat, +t: {TR}, +x: Nat) -> T.SyncCommittee: {OBJ}

{sig('rdx', S)}
    -> {{T.SyncCommittee_read(UA.BF(t, n), off, {S}) == {RHS} : B.Buf & T.SyncCommittee}}:
  %Equal.sym(B.Buf & O.Words, T.v512_b48_read(UA.BF(t, n), U32.add(off, 0), {S1}), (UA.BF(t, n), {PK}),
      VXG.rdg(d, t, n, U32.add(off, 0), x, Equal.trans(Nat, U32.to_nat(U32.add(off, 0)), Nat.add(x, 0n), x, VXG.offc(d, off, 0, 0n, x, {S}n, e, hd, {{==}}, {{==}}, hb), FD.nat__add_zero(x)),
        hd, pf, {S1}, {S1}n, {dz}n, {ky}n, {{==}}, {{==}}, {{==}}, {{==}}, {{==}},
        FD.nat__le_trans(Nat.add(x, {S1}n), Nat.add(x, {S}n), {P}, Order.add_left(x, {S1}n, {S}n, {{==}}), hb))) :
    {{T.SyncCommittee_rd0(off, {S}, _) == {RHS} : B.Buf & T.SyncCommittee}}
  %Equal.sym(B.Buf & T.Bytes48, T.b48_read(UA.BF(t, n), U32.add(off, {S1}), 48), (UA.BF(t, n), {B48}),
      VTX.rdx_b48(d, t, n, U32.add(off, {S1}), {y}, VXG.offc(d, off, {S1}, {S1}n, x, {S}n, e, hd, {{==}}, {{==}}, hb), FD.nat__lt_trans(d, 28n, 30n, hd, {{==}}), pf,
        VXG.roomc(x, {S}n, {S1}n, 48n, {P}, hb, {{==}}))) :
    {{T.SyncCommittee_rd1(off, {S}, {PK}, _) == {RHS} : B.Buf & T.SyncCommittee}}
  {{==}}

def VAL(+t: {TR}, +x: Nat) -> S.Value: {VAL}

def prt(+d: Nat, +t: {TR}, +x: Nat, +pf: {{FD.array__perfect(U32, d, t) == {TRUE}}}, +hb: {{Nat.is_le(Nat.add(x, {S}n), {P}) == {TRUE}}},
    +s: S.Schema, +es: {{s == Spec.SyncCommittee() : S.Schema}})
    -> {{Codec.parts(VAL(t, x), s) == Some{{[S.Fixed{{UW.WX(t, x, {S}n)}}]}} : Maybe<&2, +List<S.Part>>}}:
  %Equal.sym(+List<U32>, UW.WX(t, x, {S}n), List.append(&2, U32, F.limbs(UR.RWS(VXG.CNT(x, {M}n), t, x)), UW.WX(t, {y}, 48n)), VXG.splitC(d, t, x, pf, {M}n, {S1}n, 48n, {S}n, {{==}}, {{==}}, hb)) : {{Codec.parts(VAL(t, x), s) == Some{{[S.Fixed{{_}}]}} : Maybe<&2, +List<S.Part>>}}
  %UR.rws_bytes(12n, d, t, {y}, pf, VXG.roomc(x, {S}n, {S1}n, 48n, {P}, hb, {{==}})) :
    {{Codec.parts(VAL(t, x), s) == Some{{[S.Fixed{{List.append(&2, U32, F.limbs(UR.RWS(VXG.CNT(x, {M}n), t, x)), _)}}]}} : Maybe<&2, +List<S.Part>>}}
  VXG.sc_parts(s, es, UR.RWS(VXG.CNT(x, {M}n), t, x), {M}n, {S1}n, {S}n, {", ".join(G)}, VXG.lenC(t, x, {M}n), {{==}}, {{==}}, {{==}}, {{==}}, {{==}})
''')
    return '\n'.join(L) + '\n'


VECS = [('v8192_b32', 262144, 8192, 'Spec.Schema32()', 'ch8', 'Bytes32'),
        ('v65536_b32', 2097152, 65536, 'Spec.Schema80()', 'ch8', 'Bytes32'),
        ('v8192_u64', 65536, 8192, 'Spec.Schema81()', 'chu2', 'uint64'),
        ('v64_u64', 512, 64, 'Spec.Schema88()', 'chu2', 'uint64')]

# fixed field types read word by word (vua_fix / vbx_fix readers), by BeaconState field
SMALL = [('genesis_time', 'Spec.Schema3()'), ('genesis_validators_root', 'Spec.Schema7()'), ('fork', 'Spec.Fork()'),
         ('latest_block_header', 'Spec.BeaconBlockHeader()'), ('eth1_data', 'Spec.Eth1Data()'), ('finalized_checkpoint', 'Spec.Checkpoint()')]


def have(f):
    src = (ROOT / f'proofs/obj/{f}').read_text()
    return {ln.split('(')[0][len('def rdx_'):] for ln in src.splitlines() if ln.startswith('def rdx_')}


def seq_head(sch, val, proof, W, exact):
    """For a fulu container Spec.X() whose walk() proof is F.aggregate_fixed(Codec.parts(items, chain), ..):
    first rewrite Codec.parts(VAL(t, x), Spec.X()) to Codec.aggregate(Codec.parts(items, chain), Some{n}) by
    VSQ.seq_parts (proofs/obj/vseq.bend), and chain the fields by VS.chain_fixed. Otherwise the conversion to aggregate_fixed's
    statement evaluates the whole container's parts (checker_findings item 2)."""
    import re
    import var_laws as VLW
    import var_bytes_x as VBX
    m = re.fullmatch(r'Spec\.(\w+)\(\)', sch)
    head = 'F.aggregate_fixed('
    if exact or not m or not proof.startswith(head) or not val.startswith('S.Sequence{'):
        return proof
    try:
        names = VBX.spec_names(m.group(1))
    except AssertionError:
        return proof
    args = VLW._split_args(proof[len(head):-1])
    assert len(args) == 5 and proof.endswith(')'), args
    a, n = args[0], args[2]
    items, chain = VLW._split_args(a[len('Codec.parts('):-1])
    assert val == f'S.Sequence{{{items}}}', (val, items)
    MP = 'Maybe<&2, +List<S.Part>>'
    RHS = f'Some{{[S.Fixed{{F.limbs(UR.RWS({W}n, t, x))}}]}}'
    return (f'%Equal.sym({MP}, Codec.parts(VAL(t, x), {sch}), Codec.aggregate({a}, SC.fixed_size({chain})),\n'
            f'      VSQ.seq_parts(VAL(t, x), {sch}, {items}, {names}, {chain}, {{==}}, {{==}})) :\n'
            f'    {{_ == {RHS} : {MP}}}\n'
            f'  %Equal.sym(Maybe<&2, Nat>, SC.fixed_size({chain}), Some{{{n}}}, {{==}}) :\n'
            f'    {{Codec.aggregate({a}, _) == {RHS} : {MP}}}\n'
            f'  {VLW.chainify(proof)}')


def small_mod(g, t, sch, exact=False):
    """A fixed type read word by word: thin wrappers over vua_fix / vbx_fix (or a reader here).
    exact: the spec-parts proof in spec_laws' SL.EXACT form, the schema rewritten to its node's first."""
    import var_laws as VLW
    import var_ua as VUA
    ft = VLW.FT(g, t)
    p, S, W = ft.p, ft.size, ft.W
    vtx, xf = have('vua_fix.bend'), have('vbx_fix.bend')
    word = lambda k: 'UR.RWN(t, x)' if k == 0 else f'UR.RWN(t, {4 * k}n+x)'
    OBJ = ft.obj([word(k) for k in range(W)])
    nd = VLW.SL.walk(g, t, iter(range(100000)))
    mp = {int(w_[1:]): word(j) for j, w_ in enumerate(nd.words)}
    val, proof = VLW.subst_words(nd.val, mp), VLW.subst_words(nd.proof, mp)
    proof = seq_head(sch, val, proof, W, exact)
    L = list(HEAD) + (['import ../../spec/schema.bend as SC', 'import ./vseq.bend as VSQ'] if 'SC.' in proof else []) + [
        '', '# GENERATED by codegen/var_fixx.py. Do not edit.', f'# {p} ({S} bytes) at any byte position: see codegen/var_fixx.py.', '']
    local = []
    for dep in ft.deps():
        if dep.p in vtx or dep.p in xf:
            continue
        for ln in VUA.rdx_lemma(dep):
            ln = ln.replace('ltp(', 'VTX.ltp(').replace('F.', 'FD.')
            for kp in vtx:
                ln = ln.replace(f'rdx_{kp}(', f'VTX.rdx_{kp}(')
            for kp in xf:
                ln = ln.replace(f'rdx_{kp}(', f'XF.rdx_{kp}(')
            L.append(ln)
        L.append('')
        local.append(dep.p)
    ref = f'VTX.rdx_{p}' if p in vtx else (f'XF.rdx_{p}' if p in xf else f'rdx_{p}')
    if p in xf:
        L.insert(L.index('import ./vua_fix.bend as VTX') + 1, 'import ./vbx_fix.bend as XF')
    P = 'A.quad(VB.pw(d))'
    xrw = (f'  %Equal.sym(S.Schema, {sch}, {nd.sch}, {{==}}) : {{Codec.parts(VAL(t, x), _) == Some{{[S.Fixed{{F.limbs(UR.RWS({W}n, t, x))}}]}} : Maybe<&2, +List<S.Part>>}}\n'
           if exact else '')
    L.append(f'''def OBJ(+d: Nat, +t: {TR}, +x: Nat) -> {ft.rep()}: {OBJ}

{sig('rdx', S)}
    -> {{T.{p}_read(UA.BF(t, n), off, {S}) == (UA.BF(t, n), OBJ(d, t, x)) : B.Buf & {ft.rep()}}}:
  {ref}(d, t, n, off, x, e, FD.nat__lt_trans(d, 28n, 30n, hd, {{==}}), pf, hb)

def VAL(+t: {TR}, +x: Nat) -> S.Value: {val}

def prt(+d: Nat, +t: {TR}, +x: Nat, +pf: {{FD.array__perfect(U32, d, t) == {TRUE}}}, +hb: {{Nat.is_le(Nat.add(x, {S}n), {P}) == {TRUE}}},
    +s: S.Schema, +es: {{s == {sch} : S.Schema}})
    -> {{Codec.parts(VAL(t, x), s) == Some{{[S.Fixed{{UW.WX(t, x, {S}n)}}]}} : Maybe<&2, +List<S.Part>>}}:
  %Equal.sym(S.Schema, s, {sch}, es) : {{Codec.parts(VAL(t, x), _) == Some{{[S.Fixed{{UW.WX(t, x, {S}n)}}]}} : Maybe<&2, +List<S.Part>>}}
  %UR.rws_bytes({W}n, d, t, x, pf, hb) : {{Codec.parts(VAL(t, x), {sch}) == Some{{[S.Fixed{{_}}]}} : Maybe<&2, +List<S.Part>>}}
{xrw}  {proof}
''')
    return p, '\n'.join(L) + '\n'



def outputs(no_big=False):
    import var_fixx_bv4 as BV4
    out = {ROOT / 'proofs/obj/vfxg.bend': gen_text(), ROOT / 'proofs/obj/vfx_SyncCommittee.bend': sc_mod(),
           ROOT / 'proofs/obj/vfx_bv4.bend': BV4.bv4_mod(HEAD, sig, TR, TRUE)}
    import var_fixx_gen as GEN   # the generic containers' short fields (types/generic_obj.bend)
    out[ROOT / 'proofs/obj/vfx_u8.bend'] = GEN.u8_mod(HEAD, sig, TR, TRUE)
    out[ROOT / 'proofs/obj/vfx_u16.bend'] = GEN.u16_mod(HEAD, sig, TR, TRUE)
    out[ROOT / 'proofs/obj/vfx_u32.bend'] = GEN.u32_mod(HEAD, sig, TR, TRUE)
    import generic as GN0
    import generate as G0
    gn0 = {n_: t_ for n_, t_, err in GN0.inventory_all() if err is None}
    g0 = G0.Gen()
    for t_ in gn0.values():
        g0.shape(t_)
    for P_, R_, K_ in GEN.RECVECS:
        out[ROOT / f'proofs/obj/vfx_{P_}.bend'] = GEN.recvec_mod(gn0, g0, P_, R_, K_, HEAD, sig, TR, TRUE)
    for N in (1, 2, 8):
        out[ROOT / f'proofs/obj/vfx_bv{N}.bend'] = GEN.bvn_mod(N, HEAD, sig, TR, TRUE)
    import generic as GN
    gnames = {n: t for n, t, err in GN.inventory_all() if err is None}
    out[ROOT / 'proofs/obj/vfx_bv257.bend'] = GEN.bvw1_mod(HEAD, sig, TR, TRUE)
    out[ROOT / 'proofs/obj/vfx_bv1281.bend'] = GEN.bvw1_mod(HEAD, sig, TR, TRUE, 1281)
    out[ROOT / 'proofs/obj/vfx_bv1280.bend'] = GEN.bvc_mod(1280, HEAD, sig, TR, TRUE)
    for p, txt in GEN.generic_small(gnames, small_mod).items():
        out[ROOT / f'proofs/obj/vfx_{p}.bend'] = txt
    import schema
    import generate as G
    names = schema.load(ROOT / 'codegen/fulu.yaml')
    g = G.Gen()
    for n_, t_ in names.items():
        g.shape(t_)
    for fld, sch in SMALL:
        p, txt = small_mod(g, dict(names['BeaconState'].fields)[fld], sch)
        out[ROOT / f'proofs/obj/vfx_{p}.bend'] = txt
    for p, S, k, sch, ch, el in VECS:
        big = S > BIG
        if big and no_big:
            continue
        out[ROOT / f'proofs/obj/{"big_" if big else ""}vfx_{p}.bend'] = vec_text(p, S, k, sch, ch, el)
    return out


def main():
    out = outputs('--no-big' in sys.argv)
    out = RR.rewire_out(out)
    if '--check' in sys.argv:
        stale = [str(p.relative_to(ROOT)) for p, t in out.items() if not p.exists() or p.read_text() != t]
        if stale:
            print('stale: ' + ', '.join(stale))
            sys.exit(1)
        print('fixed-field readers are current')
        return
    for p, t in out.items():
        p.write_text(t)
    print(f'{len(out)} files')


if __name__ == '__main__':
    main()
