#!/usr/bin/env python3
"""The view of a packed list after one element is written: proofs/obj/view_<family>.bend.

The spec value of a packed list or vector (the `Sequence` of its items, the view the root and encode bridges state against)
is built from the word list of its storage, element i from the K words of block i. When the runtime writes one element
(K words at word K*J, the chain of F.array__upd that proofs/obj/coll_words.bend calls <kind>_write, words_win.bend's tk) the
view is the old view with item J replaced by the view of the new element (value_set.bend's items_set):

    view_set(c, d, t, x0..x{K-1}, J, q, hq: q == BASE(J), hb: q + K <= 2^d, pf)
        Sequence{ITEMS(c, slots(freeze(thaw(tk([x..], d, t, q, 0)))), 0)}
          == field_set(Sequence{ITEMS(c, slots(freeze(thaw(t))), 0)}, J, MK(x0..x{K-1}))

for a perfect tree t of depth d. It holds for any item count c (no relation between c and the storage is needed: a block
past the written one is the same, and the written one is inside the tree). The proof is one induction (items_set) over the
items, with the word-level facts of words_win.bend (a word before, inside or after the run). codegen/coll_laws.py composes
view_set with the runtime's write (coll_<...>_api_view_set) for each collection whose view is this family's items.

Families (FAMILIES): each has the block size K, the base word of block i, the element as the view builder reads it, and the
builder. The file proofs/obj/view_<family>.bend has: elem_to (the element is MK of the words when each word is given), the
gap lemmas (block i ends before block J when i < J), el_hit / el_same (the written element, every other one), items_same,
items_set (the induction) and view_set.

    python3 codegen/view_laws.py            # write
    python3 codegen/view_laws.py --check    # nonzero exit if an output is stale or orphaned
"""
import sys
from pathlib import Path

import viewbytes
import viewseq

ROOT = Path(__file__).resolve().parents[1]
OBJ = ROOT / 'proofs/obj'
HEADER = '# GENERATED by codegen/view_laws.py. Do not edit.'


def arith_e8(K=8):
    return '''def blk(+i: Nat) -> {Nat.add(O.e8(i), 8n) == O.e8(1n+i) : Nat}:
  Equal.trans(Nat, Nat.add(O.e8(i), 8n), Nat.add(8n, O.e8(i)), O.e8(1n+i), F.nat__add_comm(O.e8(i), 8n), {==})

def mono(+a: Nat, +b: Nat, +h: {Nat.is_le(a, b) == True{} : Bool}) -> {Nat.is_le(O.e8(a), O.e8(b)) == True{} : Bool}:
  F.nat__double_le(Nat.double(Nat.double(a)), Nat.double(Nat.double(b)), F.nat__double_le(Nat.double(a), Nat.double(b), F.nat__double_le(a, b, h)))
'''


def arith_double():
    return '''def blk(+i: Nat) -> {Nat.add(Nat.double(i), 2n) == Nat.double(1n+i) : Nat}:
  Equal.trans(Nat, Nat.add(Nat.double(i), 2n), Nat.add(2n, Nat.double(i)), Nat.double(1n+i), F.nat__add_comm(Nat.double(i), 2n), {==})

def mono(+a: Nat, +b: Nat, +h: {Nat.is_le(a, b) == True{} : Bool}) -> {Nat.is_le(Nat.double(a), Nat.double(b)) == True{} : Bool}:
  F.nat__double_le(a, b, h)
'''


def arith_mul12():
    return '''def blk(+i: Nat) -> {Nat.add(Nat.mul(i, 12n), 12n) == Nat.mul(1n+i, 12n) : Nat}:
  Equal.trans(Nat, Nat.add(Nat.mul(i, 12n), 12n), Nat.add(12n, Nat.mul(i, 12n)), Nat.mul(1n+i, 12n), F.nat__add_comm(Nat.mul(i, 12n), 12n), {==})

def mono(+a: Nat, +b: Nat, +h: {Nat.is_le(a, b) == True{} : Bool}) -> {Nat.is_le(Nat.mul(a, 12n), Nat.mul(b, 12n)) == True{} : Bool}:
  match a b:
    case 0n _: F.nat__zero_le(Nat.mul(b, 12n))
    case 1n+p 0n: Empty.absurd({Nat.is_le(Nat.mul(1n+p, 12n), Nat.mul(0n, 12n)) == True{} : Bool}, F.logic__false_true(h))
    case 1n+p 1n+q: F.nat__le_add_left(Nat.mul(p, 12n), Nat.mul(q, 12n), 12n, mono(p, q, h))
'''



def pre_u64():
    """items2 (the uint64 items read by word index) and its equality with the views' structural builders"""
    t = """# element i of a uint64 list: words 2i and 2i + 1 (low, high), read by word index
def el2(+W: List<&2, U32>, +i: Nat) -> S.Value:
  S.UnsignedValue{P.UInt{MR.wd(W, Nat.add(Nat.double(i), 0n)), MR.wd(W, Nat.add(Nat.double(i), 1n)), 0, 0, 0, 0, 0, 0}}

def items2(k: Nat, +W: List<&2, U32>, +i: Nat) -> S.Value:
  match k:
    case 0n: S.EmptyItems{}
    case 1n+q: S.Items{el2(W, i), items2(q, W, 1n+i)}

# the items from the next element on are the items of the words after this element's two
def items2_shift(+k: Nat, +a: U32, +b: U32, +rest: List<&2, U32>, +i: Nat) -> {items2(k, Con{a, Con{b, rest}}, 1n+i) == items2(k, rest, i) : S.Value}:
  match k:
    case 0n: {==}
    case 1n+q:
      %Equal.sym(S.Value, items2(q, Con{a, Con{b, rest}}, 1n+(1n+i)), items2(q, rest, 1n+i), items2_shift(q, a, b, rest, 1n+i)) :
        {S.Items{el2(Con{a, Con{b, rest}}, 1n+i), _} == S.Items{el2(rest, i), items2(q, rest, 1n+i)} : S.Value}
      {==}
"""
    for name, fn in (('UL_L.uitems', 'conv_uitems'), ('PK_L.it8', 'conv_it8')):
        t += """
# the structural builder over a word list that holds its words is the indexed one
def %(fn)s(+k: Nat, +W: List<&2, U32>, +h: {Nat.is_le(Nat.double(k), F.spec_common__length(U32, W)) == True{} : Bool})
    -> {%(nm)s(k, W) == items2(k, W, 0n) : S.Value}:
  match k W:
    case 0n _: {==}
    case 1n+c Nil{}: Empty.absurd({%(nm)s(1n+c, Nil{}) == items2(1n+c, Nil{}, 0n) : S.Value}, F.logic__false_true(h))
    case 1n+c Con{a, t0}:
      match t0:
        case Nil{}: Empty.absurd({%(nm)s(1n+c, Con{a, Nil{}}) == items2(1n+c, Con{a, Nil{}}, 0n) : S.Value}, F.logic__false_true(h))
        case Con{b, rest}:
          %%Equal.sym(S.Value, items2(c, Con{a, Con{b, rest}}, 1n), items2(c, rest, 0n), items2_shift(c, a, b, rest, 0n)) :
            {%(nm)s(1n+c, Con{a, Con{b, rest}}) == S.Items{el2(Con{a, Con{b, rest}}, 0n), _} : S.Value}
          %%Equal.sym(S.Value, %(nm)s(c, rest), items2(c, rest, 0n), %(fn)s(c, rest, h)) :
            {S.Items{S.UnsignedValue{P.UInt{a, b, 0, 0, 0, 0, 0, 0}}, _} == S.Items{el2(Con{a, Con{b, rest}}, 0n), items2(c, rest, 0n)} : S.Value}
          {==}
""" % dict(nm=name, fn=fn)
    return t


# name: file suffix; K words per block; imports {alias: path}; BASE(i); atom word of block i; MK(atoms) the view of an
# element from its K words; EL(W, i) and ITEMS(k, W, i) as the view's builder reads them; arith: blk and mono lemmas
FAMILIES = {
    'b32': dict(K=8, imports={'WR_L': './words_root_light.bend', 'WS': './words_spec.bend', 'FX': './spec_fixed.bend'},
                BASE=lambda i: 'O.e8(%s)' % i,
                MK=lambda ys: 'S.BytesValue{FX.limbs([%s])}' % ', '.join(ys),
                EL=lambda W, i: 'S.BytesValue{WS.cb(%s, %s)}' % (W, i),
                ITEMS=lambda k, W, i: 'WR_L.items(%s, %s, %s)' % (k, W, i), arith=arith_e8,
                doc='lists and vectors of 32-byte elements (words_root_light.bend items)'),
    'u64': dict(K=2, imports={'P': '../../types/primitive.bend', 'UL_L': './ulist_obj_light.bend', 'PK_L': './packed_obj_light.bend'},
                BASE=lambda i: 'Nat.double(%s)' % i,
                MK=lambda ys: 'S.UnsignedValue{P.UInt{%s, 0, 0, 0, 0, 0, 0}}' % ', '.join(ys),
                EL=lambda W, i: 'el2(%s, %s)' % (W, i),
                ITEMS=lambda k, W, i: 'items2(%s, %s, %s)' % (k, W, i), arith=arith_double, pre=pre_u64,
                builders=[('UL_L.uitems', 'uitems'), ('PK_L.it8', 'it8')],
                doc='lists and vectors of uint64 elements (items2: two words each; the lists\' UL_L.uitems and the vectors\' PK_L.it8 are equal to it)'),
    'b48': dict(K=12, imports={'EL48': './elems48_light.bend', 'RN_L': './root_names_light.bend', 'FuluBytes48_d': '../../types/FuluBytes48_def_generated.bend'},
                BASE=lambda i: 'Nat.mul(%s, 12n)' % i,
                MK=lambda ys: 'RN_L.v_b48(FuluBytes48_d.Bytes48{%s})' % ', '.join(ys),
                EL=lambda W, i: 'RN_L.v_b48(EL48.rec48(%s, Nat.mul(%s, 12n)))' % (W, i),
                ITEMS=lambda k, W, i: 'EL48.eitems(%s, %s, %s)' % (k, W, i), arith=arith_mul12,
                doc='lists and vectors of 48-byte elements (elems48_light.bend eitems)'),
}


def family(name, sp):
    K = sp['K']
    BASE, MK, EL, ITEMS = sp['BASE'], sp['MK'], sp['EL'], sp['ITEMS']
    xs = ['x%d' % m for m in range(K)]
    ys = ['y%d' % m for m in range(K)]
    XS = '[%s]' % ', '.join(xs)
    KN = '%dn' % K
    out = []
    w = out.append

    def atom(W, i, m):
        return 'MR.wd(%s, Nat.add(%s, %dn))' % (W, BASE(i), m)
    imps = ['import Base', 'import ../../src/obj.bend as O', 'import ../../types/schema.bend as S', 'import ../compact/found.bend as F',
            'import ./mtree_run.bend as MR', 'import ./value_set.bend as VS', 'import ./words_rw.bend as WR', 'import ./words_win.bend as WW']
    for a, p in sp['imports'].items():
        imps.append('import %s as %s' % (p, a))
    w('\n'.join(imps))
    w('')
    w(HEADER)
    w('# The view of %s after one element (%d words at word %s) is written into perfect storage: the view before with that item replaced.' % (sp['doc'], K, BASE('J')))
    w('# See codegen/view_laws.py.')
    w('')
    if sp.get('pre'):
        w(sp['pre']())
    # the element from its words
    w('def elem_to(+W: List<&2, U32>, +i: Nat, %s,\n    %s)\n    -> {%s == %s : S.Value}:' % (
        ', '.join('+y%d: U32' % m for m in range(K)),
        ', '.join('+h%d: {%s == y%d : U32}' % (m, atom('W', 'i', m), m) for m in range(K)),
        EL('W', 'i'), MK(ys)))
    for m in range(K):
        cur = [('y%d' % a) if a < m else ('_' if a == m else atom('W', 'i', a)) for a in range(K)]
        w('  %%Equal.sym(U32, %s, y%d, h%d) : {%s == %s : S.Value}' % (atom('W', 'i', m), m, m, MK(cur), MK(ys)))
    w('  {==}\n')
    w(sp['arith']())
    w('''def gap_before(+i: Nat, +J: Nat, +h: {Nat.is_lt(i, J) == True{} : Bool}) -> {Nat.is_le(Nat.add(%s, %s), %s) == True{} : Bool}:
  F.logic__subst(Nat, z => {Nat.is_le(z, %s) == True{} : Bool}, %s, Nat.add(%s, %s), Equal.sym(Nat, Nat.add(%s, %s), %s, blk(i)),
    mono(1n+i, J, F.nat__lt_succ_le_succ(i, J, h)))

# the word m of block i is past the run of block J, when J is before i
def gap_after(+i: Nat, +J: Nat, +m: Nat, +h: {Nat.is_lt(J, i) == True{} : Bool}) -> {Nat.is_le(Nat.add(%s, %s), Nat.add(%s, m)) == True{} : Bool}:
  F.nat__le_trans(Nat.add(%s, %s), %s, Nat.add(%s, m), gap_before(J, i, h), F.nat__le_add_right(%s, m))

def ne_lt(+a: Nat, +b: Nat, +h: {Nat.is_lt(a, b) == True{} : Bool}) -> {Nat.is_eq(b, a) == False{} : Bool}:
  WR.neq_sym(a, b, F.nat__is_eq_lt(a, b, h))

def lt_add_succ(+a: Nat, +p: Nat) -> {Nat.is_lt(a, Nat.add(a, 1n+p)) == True{} : Bool}:
  F.logic__subst(Nat, z => {Nat.is_lt(a, z) == True{} : Bool}, 1n+Nat.add(a, p), Nat.add(a, 1n+p), Equal.sym(Nat, Nat.add(a, 1n+p), 1n+Nat.add(a, p), F.nat__add_succ(a, p)),
    F.nat__le_lt_succ(a, Nat.add(a, p), F.nat__le_add_right(a, p)))
''' % (BASE('i'), KN, BASE('J'),
       BASE('J'), BASE('1n+i'), BASE('i'), KN, BASE('i'), KN, BASE('1n+i'),
       BASE('J'), KN, BASE('i'),
       BASE('J'), KN, BASE('i'), BASE('i'), BASE('i')))
    Q = BASE('J')
    T2 = 'WW.tk(%s, d, t, %s, 0n)' % (XS, Q)
    W2 = 'F.array__slots(U32, %s)' % T2
    W1 = 'F.array__slots(U32, t)'
    XP = ', '.join('+x%d: U32' % m for m in range(K))
    XA = ', '.join(xs)
    HB = '+hb: {Nat.is_le(Nat.add(%s, %s), F.spec_common__pow2(d)) == True{} : Bool}' % (Q, KN)
    PF = '+pf: {F.array__perfect(U32, d, t) == True{} : Bool}'
    MKX = MK(xs)
    SUBS = {'@XP@': XP, '@HB@': HB, '@PF@': PF, '@W2@': W2, '@W1@': W1, '@XA@': XA, '@XS@': XS, '@MKX@': MKX, '@K@': KN}

    def sub(t):
        for k, v in SUBS.items():
            t = t.replace(k, v)
        return t
    w(sub('''# ---- one element ----
def el_hit(+d: Nat, +t: F.array__Tree<U32>, @XP@, +J: Nat, @HB@, @PF@)
    -> {%s == @MKX@ : S.Value}:
  elem_to(@W2@, J, @XA@, %s)
''' % (EL('F.array__slots(U32, WW.tk(%s, d, t, %s, 0n))' % (XS, Q), 'J'),
       ', '.join('WW.wd_in(%s, d, t, %s, %dn, {==}, hb, pf)' % (XS, Q, m) for m in range(K)))))
    w(sub('''def el_same_go(+s: Bool, +d: Nat, +t: F.array__Tree<U32>, @XP@, +i: Nat, +J: Nat, +hs: {Nat.is_lt(i, J) == s : Bool},
    +ne: {Nat.is_eq(i, J) == False{} : Bool}, @HB@, @PF@)
    -> {%s == %s : S.Value}:
  match s:
    case True{}:
      elem_to(@W2@, i, %s, %s)
    case False{}:
      elem_to(@W2@, i, %s, %s)
''' % (EL(W2, 'i'), EL(W1, 'i'),
       ', '.join(atom(W1, 'i', m) for m in range(K)),
       ', '.join('WW.wd_before(%s, d, t, %s, Nat.add(%s, %dn), WR.bound(%s, %dn, %s, %s, gap_before(i, J, hs), {==}), hb, pf)' % (XS, Q, BASE('i'), m, BASE('i'), m, KN, Q) for m in range(K)),
       ', '.join(atom(W1, 'i', m) for m in range(K)),
       ', '.join('WW.wd_after(%s, d, t, %s, Nat.add(%s, %dn), gap_after(i, J, %dn, F.nat__lt_or_eq(J, i, F.nat__not_lt_le(i, J, hs), WR.neq_sym(i, J, ne))), hb, pf)' % (XS, Q, BASE('i'), m, m) for m in range(K)))))
    w(sub('''def el_same(+d: Nat, +t: F.array__Tree<U32>, @XP@, +i: Nat, +J: Nat, +ne: {Nat.is_eq(i, J) == False{} : Bool}, @HB@, @PF@)
    -> {%s == %s : S.Value}:
  el_same_go(Nat.is_lt(i, J), d, t, @XA@, i, J, {==}, ne, hb, pf)
''' % (EL(W2, 'i'), EL(W1, 'i'))))
    w(sub('''# ---- the items ----
# from block i0 on, all after block J: the same items
def items_same(+k: Nat, +d: Nat, +t: F.array__Tree<U32>, @XP@, +i0: Nat, +J: Nat, +hlt: {Nat.is_lt(J, i0) == True{} : Bool}, @HB@, @PF@)
    -> {%s == %s : S.Value}:
  match k:
    case 0n: {==}
    case 1n+q:
      %%Equal.sym(S.Value, %s, %s, el_same(d, t, @XA@, i0, J, ne_lt(J, i0, hlt), hb, pf)) :
        {S.Items{_, %s} == S.Items{%s, %s} : S.Value}
      %%Equal.sym(S.Value, %s, %s, items_same(q, d, t, @XA@, 1n+i0, J, F.nat__lt_trans(J, i0, 1n+i0, hlt, F.nat__lt_succ(i0)), hb, pf)) :
        {S.Items{%s, _} == S.Items{%s, %s} : S.Value}
      {==}
''' % (ITEMS('k', W2, 'i0'), ITEMS('k', W1, 'i0'),
       EL(W2, 'i0'), EL(W1, 'i0'), ITEMS('q', W2, '1n+i0'), EL(W1, 'i0'), ITEMS('q', W1, '1n+i0'),
       ITEMS('q', W2, '1n+i0'), ITEMS('q', W1, '1n+i0'), EL(W1, 'i0'), EL(W1, 'i0'), ITEMS('q', W1, '1n+i0'))))
    w(sub('''# the run written at block J = i0 + r: the items are the old items with item r replaced
def items_set(+k: Nat, +r: Nat, +d: Nat, +t: F.array__Tree<U32>, @XP@, +i0: Nat, +J: Nat, +hJ: {J == Nat.add(i0, r) : Nat}, @HB@, @PF@)
    -> {%s == VS.items_set(%s, r, @MKX@) : S.Value}:
  match k r:
    case 0n _: {==}
    case 1n+q 0n:
      +eJ = Equal.trans(Nat, J, Nat.add(i0, 0n), i0, hJ, F.nat__add_zero(i0))
      %%Equal.sym(S.Value, %s, @MKX@, F.logic__subst(Nat, z => {%s == @MKX@ : S.Value}, J, i0, eJ, el_hit(d, t, @XA@, J, hb, pf))) :
        {S.Items{_, %s} == S.Items{@MKX@, %s} : S.Value}
      %%Equal.sym(S.Value, %s, %s, items_same(q, d, t, @XA@, 1n+i0, J, F.logic__subst(Nat, z => {Nat.is_lt(z, 1n+i0) == True{} : Bool}, i0, J, Equal.sym(Nat, J, i0, eJ), F.nat__lt_succ(i0)), hb, pf)) :
        {S.Items{@MKX@, _} == S.Items{@MKX@, %s} : S.Value}
      {==}
    case 1n+q 1n+p:
      +hlt = F.logic__subst(Nat, z => {Nat.is_lt(i0, z) == True{} : Bool}, Nat.add(i0, 1n+p), J, Equal.sym(Nat, J, Nat.add(i0, 1n+p), hJ), lt_add_succ(i0, p))
      %%Equal.sym(S.Value, %s, %s, el_same(d, t, @XA@, i0, J, F.nat__is_eq_lt(i0, J, hlt), hb, pf)) :
        {S.Items{_, %s} == S.Items{%s, VS.items_set(%s, p, @MKX@)} : S.Value}
      %%Equal.sym(S.Value, %s, VS.items_set(%s, p, @MKX@), items_set(q, p, d, t, @XA@, 1n+i0, J, Equal.trans(Nat, J, Nat.add(i0, 1n+p), Nat.add(1n+i0, p), hJ, F.nat__add_succ(i0, p)), hb, pf)) :
        {S.Items{%s, _} == S.Items{%s, VS.items_set(%s, p, @MKX@)} : S.Value}
      {==}
''' % (ITEMS('k', W2, 'i0'), ITEMS('k', W1, 'i0'),
       EL(W2, 'i0'), EL(W2, 'z'), ITEMS('q', W2, '1n+i0'), ITEMS('q', W1, '1n+i0'),
       ITEMS('q', W2, '1n+i0'), ITEMS('q', W1, '1n+i0'), ITEMS('q', W1, '1n+i0'),
       EL(W2, 'i0'), EL(W1, 'i0'), ITEMS('q', W2, '1n+i0'), EL(W1, 'i0'), ITEMS('q', W1, '1n+i0'),
       ITEMS('q', W2, '1n+i0'), ITEMS('q', W1, '1n+i0'), EL(W1, 'i0'), EL(W1, 'i0'), ITEMS('q', W1, '1n+i0'))))
    TQ = 'WW.tk(%s, d, t, q, 0n)' % XS
    w(sub('''# the view of the storage after the run is written at word q = %s: the view before, with item J replaced.
# `c` is the element count the view reads.
def view_set(+c: Nat, +d: Nat, +t: F.array__Tree<U32>, @XP@, +J: Nat, +q: Nat, +hq: {q == %s : Nat},
    +hb: {Nat.is_le(Nat.add(q, @K@), F.spec_common__pow2(d)) == True{} : Bool}, @PF@)
    -> {S.Sequence{%s} == VS.field_set(S.Sequence{%s}, J, @MKX@) : S.Value}:
  %%Equal.sym(F.array__Tree<U32>, F.array__freeze(U32, F.array__thaw(U32, %s)), %s, F.array__freeze_thaw(U32, %s)) :
    {S.Sequence{%s} == VS.field_set(S.Sequence{%s}, J, @MKX@) : S.Value}
  %%Equal.sym(F.array__Tree<U32>, F.array__freeze(U32, F.array__thaw(U32, t)), t, F.array__freeze_thaw(U32, t)) :
    {S.Sequence{%s} == VS.field_set(S.Sequence{%s}, J, @MKX@) : S.Value}
  %%Equal.sym(Nat, q, %s, hq) :
    {S.Sequence{%s} == VS.field_set(S.Sequence{%s}, J, @MKX@) : S.Value}
  Equal.cong(S.Value, S.Value, z => S.Sequence{z}, %s, VS.items_set(%s, J, @MKX@),
    items_set(c, J, d, t, @XA@, 0n, J, {==}, F.logic__subst(Nat, z => {Nat.is_le(Nat.add(z, @K@), F.spec_common__pow2(d)) == True{} : Bool}, q, %s, hq, hb), pf))
''' % (BASE('J'), BASE('J'),
       ITEMS('c', 'F.array__slots(U32, F.array__freeze(U32, F.array__thaw(U32, %s)))' % TQ, '0n'), ITEMS('c', 'F.array__slots(U32, F.array__freeze(U32, F.array__thaw(U32, t)))', '0n'),
       TQ, TQ, TQ,
       ITEMS('c', 'F.array__slots(U32, _)', '0n'), ITEMS('c', 'F.array__slots(U32, F.array__freeze(U32, F.array__thaw(U32, t)))', '0n'),
       ITEMS('c', W2.replace(Q, 'q') if False else 'F.array__slots(U32, %s)' % TQ, '0n'), ITEMS('c', 'F.array__slots(U32, _)', '0n'),
       BASE('J'),
       ITEMS('c', 'F.array__slots(U32, WW.tk(%s, d, t, _, 0n))' % XS, '0n'), ITEMS('c', W1, '0n'),
       ITEMS('c', W2, '0n'), ITEMS('c', W1, '0n'), BASE('J'))))
    for name_, fn in sp.get('builders', []):
        # the same for a structural builder (equal to the indexed one when the storage holds its words)
        SL = lambda T: 'F.array__slots(U32, %s)' % T
        LENS = lambda T, pfT: 'F.logic__subst(Nat, z => {Nat.is_le(Nat.double(c), z) == True{} : Bool}, F.spec_common__pow2(d), F.spec_common__length(U32, %s), Equal.sym(Nat, F.spec_common__length(U32, %s), F.spec_common__pow2(d), F.array__slots_length(U32, d, %s, %s)), hcap)' % (SL(T), SL(T), T, pfT)
        w(sub('''# the same, for %s over storage that holds the element count's words
def view_set_%s(+c: Nat, +d: Nat, +t: F.array__Tree<U32>, @XP@, +J: Nat, +q: Nat, +hq: {q == %s : Nat},
    +hb: {Nat.is_le(Nat.add(q, @K@), F.spec_common__pow2(d)) == True{} : Bool}, @PF@,
    +hcap: {Nat.is_le(Nat.double(c), F.spec_common__pow2(d)) == True{} : Bool})
    -> {S.Sequence{%s(c, F.array__slots(U32, F.array__freeze(U32, F.array__thaw(U32, %s))))} == VS.field_set(S.Sequence{%s(c, F.array__slots(U32, F.array__freeze(U32, F.array__thaw(U32, t))))}, J, @MKX@) : S.Value}:
  %%Equal.sym(F.array__Tree<U32>, F.array__freeze(U32, F.array__thaw(U32, %s)), %s, F.array__freeze_thaw(U32, %s)) :
    {S.Sequence{%s(c, F.array__slots(U32, _))} == VS.field_set(S.Sequence{%s(c, F.array__slots(U32, F.array__freeze(U32, F.array__thaw(U32, t))))}, J, @MKX@) : S.Value}
  %%Equal.sym(F.array__Tree<U32>, F.array__freeze(U32, F.array__thaw(U32, t)), t, F.array__freeze_thaw(U32, t)) :
    {S.Sequence{%s(c, F.array__slots(U32, %s))} == VS.field_set(S.Sequence{%s(c, F.array__slots(U32, _))}, J, @MKX@) : S.Value}
  %%Equal.sym(S.Value, %s(c, %s), items2(c, %s, 0n), %s(c, %s, %s)) :
    {S.Sequence{_} == VS.field_set(S.Sequence{%s(c, %s)}, J, @MKX@) : S.Value}
  %%Equal.sym(S.Value, %s(c, %s), items2(c, %s, 0n), %s(c, %s, %s)) :
    {S.Sequence{items2(c, %s, 0n)} == VS.field_set(S.Sequence{_}, J, @MKX@) : S.Value}
  %%Equal.sym(Nat, q, %s, hq) :
    {S.Sequence{items2(c, F.array__slots(U32, WW.tk(@XS@, d, t, _, 0n)), 0n)} == VS.field_set(S.Sequence{items2(c, @W1@, 0n)}, J, @MKX@) : S.Value}
  Equal.cong(S.Value, S.Value, z => S.Sequence{z}, items2(c, @W2@, 0n), VS.items_set(items2(c, @W1@, 0n), J, @MKX@),
    items_set(c, J, d, t, @XA@, 0n, J, {==}, F.logic__subst(Nat, z => {Nat.is_le(Nat.add(z, @K@), F.spec_common__pow2(d)) == True{} : Bool}, q, %s, hq, hb), pf))
''' % (name_, fn, BASE('J'),
       name_, TQ, name_,
       TQ, TQ, TQ,
       name_, name_,
       name_, TQ, name_,
       name_, SL(TQ), SL(TQ), 'conv_' + fn, SL(TQ), LENS(TQ, 'WW.tk_perfect(%s, d, t, q, 0n, pf)' % XS),
       name_, SL('t'),
       name_, SL('t'), SL('t'), 'conv_' + fn, SL('t'), LENS('t', 'pf'),
       SL(TQ),
       BASE('J'), BASE('J'))))
    return '\n'.join(out)


def outputs():
    outs = {OBJ / ('view_%s.bend' % n): family(n, sp) for n, sp in FAMILIES.items()}
    outs[OBJ / 'view_seq.bend'] = viewseq.seq_file()
    outs[OBJ / 'view_bytes.bend'] = viewbytes.bytes_file()
    return outs


def main():
    check = '--check' in sys.argv
    outs = outputs()
    stale = [p.name for p, t in outs.items() if not p.exists() or p.read_text() != t]
    orphans = sorted({p.name for p in OBJ.glob('view_*.bend')} - {p.name for p in outs})
    if check:
        if stale or orphans:
            print('stale: ' + ', '.join(stale + [o + ' (orphan)' for o in orphans]))
            sys.exit(1)
        print('view_laws: %d files up to date' % len(outs))
        return
    for p, t in outs.items():
        if not p.exists() or p.read_text() != t:
            p.write_text(t)
    for o in orphans:
        (OBJ / o).unlink()
    print('view_laws: %d files' % len(outs))


if __name__ == '__main__':
    main()
