#!/usr/bin/env python3
"""The encoder laws of the names of codegen/proofs/var/byte_list_codec_laws.py.

For a name X (word-aligned fixed fields around one byte list) this writes
proofs/obj/var_bytes_<X>_enc.bend:

    putw          X_putn at a word-aligned position pos = 4 P of any perfect
                  output tree D writes the object: the result is an explicit
                  tree (layers of word writes over D) and the object's size;
    bytesw_enc    the bytes of that window are the header's words and the
                  byte list's bytes;
    encode_eval   the encoder returns the object and B.Buf{thaw(OUT), FS + N};
    encode_spec   whose bytes are the spec/codec.bend encoding of the object's
                  value XE,

for every object whose fixed fields hold free words, whose byte vectors of
packed words have perfect storage trees with room for their words, and whose
byte list is O.Words{thaw(TX), N}, N <= limit, on a perfect tree with room for
its words and no bytes past N in its last word (the runtime's storage check).
proofs/obj/var_bytes_wput.bend holds the writers of the packed word fields.
"""
import re

from codegen.core.bend_source_text_helpers import wsplit  # noqa: E402
from codegen.impl import typed_object_runtime as G
from codegen.proofs.var import single_list_container_codec_laws as VL  # noqa: F401  kept: the import may register hooks at import time
from codegen.proofs.var import byte_list_codec_laws as VBY
from codegen.core.template_loader_positional import Templates  # noqa: E402
TPL = Templates('byte_list_encoder_laws', globals())



def _seq_step(*a):
    from codegen.proofs.var import byte_list_offset_windows as VBX  # deferred: byte_list_offset_windows imports this module
    return VBX.seq_step(*a)

ROOT = VBY.ROOT


def wput_module(x_list):
    """The writer lemma of each packed-words field type (b256, v4_b32, ...)."""
    L = ['import Base', 'import ../../src/buffer.bend as B', 'import ../../src/obj.bend as O',
         'import ../../types/fulu_obj.bend as T', 'import ../compact/found.bend as F', 'import ../compact/arith.bend as A',
         'import ./vbuf.bend as VB', 'import ./vfix.bend as VF', 'import ./vcopy.bend as VC', 'import ./vbenc.bend as VBE', '',
         '# GENERATED by byte_list_encoder_laws (codegen). Do not edit.',
         '# The checked writer of a byte vector held as packed words, at a word-aligned',
         '# position 4 P: its words are written as one run (VF.updv) of the storage\'s first words.', '']
    done = set()
    w = L.append
    src = VBY.src()
    for x in x_list:
        for f in x.fields:
            if f['kind'] != 'words' or f['p'] in done:
                continue
            done.add(f['p'])
            p, S, W = f['p'], f['size'], f['W']
            m = re.search(rf'^def {p}_valid\(o: O\.Words\) -> O\.Words & Bool: O\.words_ok\(o, {S}, {S}, False\{{\}}, (\d+)\)$', src, re.M)
            if not m:
                raise VBY.Skip(f'{p}: storage check shape')
            unit = int(m.group(1))
            for j in range(W - 1):
                if f'def {p}_pa{j}(+q: U32, out: Array<U32>, pair: Array<U32> & U32) -> Array<U32> & Array<U32>:' not in src:
                    raise VBY.Skip(f'{p}: writer shape')
            WL = '[' + ', '.join(f'VB.slot(TB, {j}n)' for j in range(W)) + ']'
            w(f'def WL_{p}(+TB: F.array__Tree<U32>) -> List<&2, U32>: {WL}')
            for j in range(W + 1):
                w(f'def WP{j}_{p}(+TB: F.array__Tree<U32>) -> List<&2, U32>: [' + ', '.join(f'VB.slot(TB, {i}n)' for i in range(j)) + ']')
            kw = VBY.kfit(31 + S)
            OB = f'O.Words{{F.array__thaw(U32, TB), {S}}}'
            RHS = f'(F.array__thaw(U32, VF.updv(WL_{p}(TB), dd, D, P)), ({OB}, 0))'
            TY = 'Array<U32> & (O.Words & U32)'
            w(TPL.render('wput_module', OB=OB, RHS=RHS, S=S, TY=TY, W=W, kw=kw, p=p, unit=unit))
            for j in range(W):
                pre = f'F.array__thaw(U32, VF.updv(WP{j}_{p}(TB), dd, D, P))'
                post = f'F.array__thaw(U32, VF.updv(WP{j + 1}_{p}(TB), dd, D, P))'
                hi = f'F.nat__lt_le_trans({j}n, {W}n, VB.pw(dB), {{==}}, hrB)'
                w(f'  %Equal.sym(Array<U32> & U32, Array.get(U32, F.array__thaw(U32, TB), {j}), (F.array__thaw(U32, TB), VB.slot(TB, {j}n)), VB.get_n(dB, TB, {j}, {j}n, {{==}}, hB32, {hi}, pfB)) :')
                w(f'    {{T.{p}_pk_ok(T.{p}_pal({S}, T.{p}_pa{j}(U32.shrn(pos, 2n), {pre}, _))) == {RHS} : {TY}}}')
                nxt = f'T.{p}_pa{j + 1}(U32.shrn(pos, 2n), _, Array.get(U32, F.array__thaw(U32, TB), {j + 1}))' if j + 1 < W else '(_, F.array__thaw(U32, TB))'
                for line in TPL.render('wput_module_lines', RHS=RHS, S=S, TY=TY, W=W, j=j, nxt=nxt, p=p, post=post, pre=pre).split('\n'):
                    w(line)
            w('  {==}')
            w('')
    return '\n'.join(L) + '\n'


# ---- the name's encoder --------------------------------------------------------------------------

class Enc:
    """Parameters, object and writer plan of a name's encoder laws."""

    def __init__(self, x):
        self.x = x
        n = x.n
        src = VBY.src()
        m = re.search(rf'^def {n}_encode\(o: {n}\) -> {n} & B\.Buf: {n}_enc_put\({n}_putn\(O\.out_at\((\d+)n\), 0, o\)\)$', src, re.M)
        if not m:
            raise VBY.Skip('encoder shape')
        self.DO = int(m.group(1))
        # object parameters
        self.params, self.args = [], []
        self.hyps, self.hargs = [], []
        self.words = {}   # field index -> list of word terms
        self.fobj = {}    # field index -> object term
        for i, f in enumerate(x.fields):
            if f['kind'] == 'fix':
                ws = [f'w{f["k"] + j}' for j in range(f['W'])]
                self.words[i] = ws
                self.params += [f'+{q}: U32' for q in ws]
                self.args += ws
                self.fobj[i] = f['ft'].obj(ws)
            elif f['kind'] == 'words':
                b = f'B{i}'
                self.params += [f'+d{b}: Nat', f'+T{b}: FD.array__Tree<U32>']
                self.args += [f'd{b}', f'T{b}']
                self.hyps += [f'+pf{b}: {{FD.array__perfect(U32, d{b}, T{b}) == True{{}} : Bool}}', f'+hd{b}: {{Nat.is_lt(d{b}, 31n) == True{{}} : Bool}}',
                              f'+hr{b}: {{Nat.is_le({f["W"]}n, VB.pw(d{b})) == True{{}} : Bool}}']
                self.hargs += [f'pf{b}', f'hd{b}', f'hr{b}']
                self.words[i] = [f'VB.slot(T{b}, {j}n)' for j in range(f['W'])]
                self.fobj[i] = f'O.Words{{FD.array__thaw(U32, T{b}), {f["size"]}}}'
            else:
                self.params += ['+dX: Nat', '+TX: FD.array__Tree<U32>', '+N: U32']
                self.args += ['dX', 'TX', 'N']
                self.hyps += ['+pfX: {FD.array__perfect(U32, dX, TX) == True{} : Bool}', '+hdX: {Nat.is_lt(dX, 31n) == True{} : Bool}',
                              f'+hN: {{Nat.is_le(U32.to_nat(N), {x.LIM}n) == True{{}} : Bool}}',
                              '+hrX: {Nat.is_le(Nat.add(VC.NW(N), 0n), VB.pw(dX)) == True{} : Bool}',
                              '+htz: {O.tail_zero(U32.and(N, 3), VB.slot(TX, VY.QL(N))) == True{} : Bool}']
                self.hargs += ['pfX', 'hdX', 'hN', 'hrX', 'htz']
                self.fobj[i] = 'O.Words{FD.array__thaw(U32, TX), N}'
        self.P = ', '.join(self.params)
        self.A = ', '.join(self.args)
        self.PH = ', '.join(self.params + self.hyps)
        self.AH = ', '.join(self.args + self.hargs)

    def objterm(self):
        """The container term with the field objects (plain or grouped)."""
        x = self.x
        vals = [self.fobj[i] for i in range(len(x.fields))]
        if len(x.fields) <= G.GROUP:
            return f'T.{x.s.t.name}{{' + ', '.join(vals) + '}'
        gs = []
        for k in range(0, len(vals), G.GROUP):
            gp = f'{x.s.p}_g{k // G.GROUP}'
            gs.append(f'T.{gp}{{' + ', '.join(vals[k:k + G.GROUP]) + '}')
        return f'T.{x.s.t.name}{{' + ', '.join(gs) + '}'




def plan(x, E):
    """Simulate the runtime writer X_putn(thaw(D), pos, OBJE(..)): the layers of
    word writes over D, and the leaf steps (context with '@', field, layer before,
    layer after, kind, cursor) in evaluation order. Mirrors codegen/impl/typed_object_runtime.py
    emit_fieldset / emit_wide."""
    F = [(fn, fs) for (fn, _), (_, fs) in zip(x.t.fields, x.s.fields)]
    hoff, fixed_part = G.container_layout(F)
    layers = []
    leaves = []
    st = {'j': 0}

    def data_writes(ctx, fidx, rec_pair):
        data = [i for i in fidx if F[i][1].data]
        for a, i in enumerate(data):
            expr = '@'
            for i2 in data[a + 1:]:
                f2 = x.fields[i2]
                expr = f'T.{f2["p"]}_put({expr}, U32.add(pos, {f2["c"]}), {E.fobj[i2]})'
            c = ctx.replace('@', rec_pair(expr))
            j = st['j']
            layers.append(('updv', E.words[i], x.fields[i]['k'], i))
            st['j'] = len(layers)
            leaves.append((c, i, j, st['j'], 'fix', None))

    def fieldset(p, R, fidx, cur0, ctx):
        var = [i for i in fidx if not F[i][1].fixed]
        lin = [i for i in fidx if not F[i][1].data]
        psteps = [('putv', i) for i in var] + [('put', i) for i in lin if i not in var]
        cur = cur0
        for kk, (kind, i) in enumerate(psteps):
            held = [E.fobj[i2] for i2 in fidx if i2 != i]
            if kind == 'putv':
                frame = f'T.{p}_pw{kk}(' + ', '.join(['pos'] + held + ['@']) + ')'
            else:
                frame = f'T.{p}_pw{kk}(' + ', '.join(['pos', cur] + held + ['@']) + ')'
            j = st['j']
            if kind == 'putv':
                layers.append(('var', None, x.H, i))
                nxt = 'SFS(N)'
            else:
                layers.append(('words', E.words[i], x.fields[i]['k'], i))
                nxt = f'U32.or({cur}, 0)'
            st['j'] = len(layers)
            leaves.append((ctx.replace('@', frame), i, j, st['j'], kind, cur))
            cur = nxt
        rec = f'T.{R}{{' + ', '.join(E.fobj[i] for i in fidx) + '}'
        if psteps:
            data_writes(ctx, fidx, lambda e: f'({e}, ({rec}, {cur}))')
        else:
            data_writes(ctx, fidx, lambda e: e)
        return cur

    s = x.s
    if len(F) <= G.GROUP:
        fieldset(s.p, s.t.name, list(range(len(F))), str(fixed_part), '@')
    else:
        groups = [(k // G.GROUP, list(range(k, min(k + G.GROUP, len(F))))) for k in range(0, len(F), G.GROUP)]
        isdata = {gk: all(F[i][1].data for i in idx) for gk, idx in groups}
        lin = [gk for gk, _ in groups if not isdata[gk]]
        gvals = {gk: f'T.{s.p}_g{gk}{{' + ', '.join(E.fobj[i] for i in idx) + '}' for gk, idx in groups}
        if not lin or [gk for gk, _ in groups if isdata[gk] and gk < lin[-1]]:
            raise VBY.Skip('group layout')
        cur = str(fixed_part)
        for a, gk in enumerate(lin):
            held = [gvals[g2] for g2, _ in groups if g2 != gk]
            ctx = f'T.{s.p}_pw{a}(' + ', '.join(['pos'] + held + ['@']) + ')'
            cur = fieldset(f'{s.p}_g{gk}', f'{s.p}_g{gk}', groups[gk][1], cur, ctx)
        after = [gk for gk, _ in groups if isdata[gk] and gk > lin[-1]]
        OBJ = E.objterm()
        for a, gk in enumerate(after):
            expr = '@'
            for g2 in after[a + 1:]:
                expr = f'T.{s.p}_g{g2}_put({expr}, pos, {cur}, {gvals[g2]})'
            data_writes(f'({expr}, ({OBJ}, {cur}))', groups[gk][1], lambda e: e)
    return layers, leaves


def enc_text(x):
    E = Enc(x)
    n, FS, H, po, cvar, LIM, KY = x.n, x.FS, x.H, x.po, x.cvar, x.LIM, x.KY
    Tn = f'T.{n}'
    lp = x.lp
    KL = VBY.kfit(LIM + 1)
    L = list(VBY.HEAD) + ['import ./venc.bend as VE', 'import ./vbenc.bend as VBE', 'import ./var_bytes_wput.bend as WP',
                          'import ../../spec/schema.bend as SC', 'import ./vseq.bend as VSQ', '',
                          '# GENERATED by byte_list_encoder_laws (codegen). Do not edit.',
                          f'# The encoder of {n} (see the module docstring of codegen/proofs/var/byte_list_encoder_laws.py).', '']
    w = L.append
    DP = f'{E.P}, +dd: Nat, +D: FD.array__Tree<U32>, +P: Nat'
    DA = f'{E.A}, dd, D, P'
    OBJ = f'OBJE({E.A})'
    for line in TPL.render('enc_text_lines', E=E, FS=FS, H=H, Tn=Tn).split('\n'):
        w(line)
    layers, leaves = plan(x, E)
    NL = len(layers)

    def tree(j):
        return 'D' if j == 0 else f'LY{j}({DA})'

    def vterm(kind, V, i):
        f = x.fields[i]
        return f'WP.WL_{f["p"]}(T{"B" + str(i)})' if kind == 'words' else f'[{", ".join(V)}]'

    for j, (kind, V, k, i) in enumerate(layers):
        if kind == 'var':
            term = f'VB.mone(VC.NW(N), 0n, Nat.add({H}n, P), dd, VF.updv([{FS}], dd, {tree(j)}, Nat.add({po}n, P)), TX)'
        else:
            term = f'VF.updv({vterm(kind, V, i)}, dd, {tree(j)}, Nat.add({k}n, P))'
        w(f'def LY{j + 1}({DP}) -> FD.array__Tree<U32>: {term}')
    w(f'def OUTW({DP}) -> FD.array__Tree<U32>: {tree(NL)}')
    HN = f'+hN: {{Nat.is_le(U32.to_nat(N), {LIM}n) == True{{}} : Bool}}'
    HDST = '+hdst: {Nat.is_le(ROOM(N, P), VB.pw(dd)) == True{} : Bool}'
    K = f'Nat.add(VY.QL(N), Nat.add({H}n, P))'
    HZ = '+hz0: {VB.slot(D, KZ(N, P)) == 0 : U32}'
    PFD = '+pf: {FD.array__perfect(U32, dd, D) == True{} : Bool}'
    w(TPL.render('enc_text', FS=FS, H=H, HDST=HDST, HN=HN, K=K, KL=KL, KY=KY, LIM=LIM))

    def hbw(W, k):
        return f'hb({W}n, {k}n, P, dd, {{==}}, hHP(N, dd, P, hdst))'

    for j, (kind, V, k, i) in enumerate(layers):
        prev = f'pfL{j}({DA}, pf)' if j else 'pf'
        if kind == 'var':
            pr = (f'VB.mone_perfect(VC.NW(N), 0n, Nat.add({H}n, P), dd, VF.updv([{FS}], dd, {tree(j)}, Nat.add({po}n, P)), TX, '
                  f'VF.updv_perfect([{FS}], dd, {tree(j)}, Nat.add({po}n, P), {prev}))')
        else:
            pr = f'VF.updv_perfect({vterm(kind, V, i)}, dd, {tree(j)}, Nat.add({k}n, P), {prev})'
        w(f'def pfL{j + 1}({DP}, {PFD}) -> {{FD.array__perfect(U32, dd, {tree(j + 1)}) == True{{}} : Bool}}:')
        w(f'  {pr}')
    w(f'def pfO({DP}, {PFD}) -> {{FD.array__perfect(U32, dd, OUTW({DA})) == True{{}} : Bool}}: pfL{NL}({DA}, pf)')
    vj = [j for j, l in enumerate(layers) if l[0] == 'var'][0]
    for j in range(vj):
        kind, V, k, i = layers[j]
        f = x.fields[i]
        prev = f'hzL{j}({DA}, pf, hdst, hz0)' if j else 'hz0'
        pfp = f'pfL{j}({DA}, pf)' if j else 'pf'
        for line in TPL.render('enc_text_lines_3', DP=DP, HDST=HDST, HZ=HZ, K=K, PFD=PFD, V=V, f=f, hbw=hbw, i=i, j=j, k=k, kind=kind, pfp=pfp, prev=prev, tree=tree, vterm=vterm).split('\n'):
            w(line)
    w('')
    XOBJ = 'O.Words{FD.array__thaw(U32, TX), N}'
    D2 = f'VF.updv([{FS}], dd, D1, Nat.add({po}n, P))'
    D3 = f'VB.mone(VC.NW(N), 0n, Nat.add({H}n, P), dd, {D2}, TX)'
    RX = f'(FD.array__thaw(U32, {D3}), ({XOBJ}, SFS(N)))'
    TX_ = 'Array<U32> & (O.Words & U32)'
    ecv = f'eoc({po}n, {cvar}, P, pos, dd, eP, hdd, {{==}}, hbq(1n, {po}n, P, dd, {hbw(1, po)}))'
    ecF = f'eoc({H}n, {FS}, P, pos, dd, eP, hdd, {{==}}, hbq(VC.NW(N), {H}n, P, dd, hdst))'
    XH = ', '.join(E.hyps[-5:])
    w(TPL.render('enc_text_xput', D2=D2, D3=D3, FS=FS, H=H, HDST=HDST, K=K, KY=KY, LIM=LIM, RX=RX, TX_=TX_, XH=XH, XOBJ=XOBJ, cvar=cvar, ecF=ecF, ecv=ecv, hbw=hbw, lp=lp, po=po))
    RHS = f'(FD.array__thaw(U32, OUTW({DA})), ({OBJ}, SFS(N)))'
    TY = f'Array<U32> & ({Tn} & U32)'
    for line in TPL.render('enc_text_lines_2', DP=DP, E=E, HDST=HDST, HZ=HZ, OBJ=OBJ, PFD=PFD, RHS=RHS, TY=TY, Tn=Tn).split('\n'):
        w(line)
    for ctx, i, j0, j1, kind, cur in leaves:
        f = x.fields[i]
        pat = ctx.replace('@', '_')
        pfp = f'pfL{j0}({DA}, pf)' if j0 else 'pf'
        if kind == 'putv':
            call = f'T.{lp}_putv(FD.array__thaw(U32, {tree(j0)}), pos, {cvar}, {cur}, {E.fobj[i]})'
            res = f'(FD.array__thaw(U32, {tree(j1)}), ({E.fobj[i]}, SFS(N)))'
            hzp = f'hzL{j0}({DA}, pf, hdst, hz0)' if j0 else 'hz0'
            pr = f'xput(dd, {tree(j0)}, pos, P, eP, hdd, {pfp}, dX, TX, N, hdst, pfX, hdX, hN, hrX, htz, {hzp})'
            ty = 'Array<U32> & (O.Words & U32)'
        elif kind == 'put':
            b = f'B{i}'
            call = f'T.{f["p"]}_putk(FD.array__thaw(U32, {tree(j0)}), U32.add(pos, {f["c"]}), {E.fobj[i]})'
            res = f'(FD.array__thaw(U32, {tree(j1)}), ({E.fobj[i]}, 0))'
            pr = (f'WP.wput_{f["p"]}(dd, {tree(j0)}, U32.add(pos, {f["c"]}), Nat.add({f["k"]}n, P), '
                  f'eoc({f["k"]}n, {f["c"]}, P, pos, dd, eP, hdd, {{==}}, hbq({f["W"]}n, {f["k"]}n, P, dd, {hbw(f["W"], f["k"])})), '
                  f'hdd, {pfp}, {hbw(f["W"], f["k"])}, d{b}, T{b}, pf{b}, hd{b}, hr{b})')
            ty = 'Array<U32> & (O.Words & U32)'
        else:
            ft = f['ft']
            call = f'T.{ft.p}_put(FD.array__thaw(U32, {tree(j0)}), U32.add(pos, {f["c"]}), {E.fobj[i]})'
            res = f'FD.array__thaw(U32, {tree(j1)})'
            pr = (f'VT.put_{ft.p}(dd, {tree(j0)}, U32.add(pos, {f["c"]}), Nat.add({f["k"]}n, P), '
                  f'eoc({f["k"]}n, {f["c"]}, P, pos, dd, eP, hdd, {{==}}, hbq({f["W"]}n, {f["k"]}n, P, dd, {hbw(f["W"], f["k"])})), '
                  f'hdd, {pfp}, {hbw(f["W"], f["k"])}, {", ".join(E.words[i])})')
            ty = 'Array<U32>'
        for line in TPL.render('enc_text_lines_4', RHS=RHS, TY=TY, call=call, pat=pat, pr=pr, res=res, ty=ty).split('\n'):
            w(line)
    w('  {==}')
    return E, L, layers, leaves, NL




def enc_spec_text(x, E, layers, NL):
    """encode_eval, the output window's bytes, encE, encode_spec."""
    n, FS, H, po, cvar, LIM, KY = x.n, x.FS, x.H, x.po, x.cvar, x.LIM, x.KY
    Tn = f'T.{n}'
    L = []
    w = L.append
    DP = f'{E.P}, +dd: Nat, +D: FD.array__Tree<U32>, +P: Nat'
    DA = f'{E.A}, dd, D, P'
    OBJ = f'OBJE({E.A})'
    HN = f'+hN: {{Nat.is_le(U32.to_nat(N), {LIM}n) == True{{}} : Bool}}'
    HDST = '+hdst: {Nat.is_le(ROOM(N, P), VB.pw(dd)) == True{} : Bool}'
    PFD = '+pf: {FD.array__perfect(U32, dd, D) == True{} : Bool}'
    HDD = '+hdd: {Nat.is_lt(dd, 29n) == True{} : Bool}'
    NWM = (LIM + 3) // 4
    DO = E.DO
    KS = VBY.kfit(FS + LIM + 1)
    T0 = f'OUTW({E.A}, {DO}n, VC.ZT({DO}n), 0n)'
    A0 = f'{E.A}, {DO}n, VC.ZT({DO}n), 0n'

    def tree(j):
        return 'D' if j == 0 else f'LY{j}({DA})'

    def pfl(j):
        return f'pfL{j}({DA}, pf)' if j else 'pf'

    def hbw(W, k):
        return f'hb({W}n, {k}n, P, dd, {{==}}, hHP(N, dd, P, hdst))'

    def vterm(kind, V, i):
        f = x.fields[i]
        return f'WP.WL_{f["p"]}(TB{i})' if kind == 'words' else f'[{", ".join(V)}]'
    # ---- encode_eval ----
    RE = f'({OBJ}, B.Buf{{FD.array__thaw(U32, {T0}), SFS(N)}})'
    TY = f'Array<U32> & ({Tn} & U32)'
    HD0 = (f'FD.nat__le_trans(Nat.add(VC.NW(N), {H}n), Nat.add({NWM}n, {H}n), VB.pw({DO}n), '
           f'Order.add_right(VC.NW(N), {NWM}n, {H}n, hNW(N, hN)), {{==}})')
    w(TPL.render('enc_spec_text', FS=FS, HN=HN, KS=KS, KY=KY, LIM=LIM, NWM=NWM) + '\n'.join(f'  for {q}' for q in E.params + E.hyps) + TPL.render('enc_spec_text_encode_eval', A0=A0, DO=DO, E=E, H=H, HD0=HD0, KS=KS, OBJ=OBJ, RE=RE, T0=T0, TY=TY, Tn=Tn))
    # ---- the output window's words ----
    S_ = f'FD.array__slots(U32, OUTW({DA}))'
    LT = 'List<&2, U32>'
    WP_ = f'{DP}, {", ".join(E.hyps)}, {PFD}, {HDST}'
    WA_ = f'{DA}, {", ".join(E.hargs)}, pf, hdst'

    def win(m, p, j):
        return f'VF.WIN({m}, {p}, FD.array__slots(U32, {tree(j)}))'

    vj = [j for j, l in enumerate(layers) if l[0] == 'var'][0]

    def peel_chain(m, k0, mlit, j_stop, last_term, last_proof):
        """WIN(m, k0 + P, LY_NL) = ... = WIN(m, k0 + P, LY_j_stop), then last_proof."""
        p = f'Nat.add({k0}n, P)'

        def rel(W2, k2, pre):
            if k2 + W2 <= k0:
                return f'V2.peel_lo({pre}, {m}, {p}, ' + '@PF@, @HB@, ' + f'Order.add_right({W2 + k2}n, {k0}n, P, {{==}}))'
            assert mlit is not None and k0 + mlit <= k2
            return f'V2.peel_hi({pre}, {m}, {p}, ' + '@PF@, @HB@, ' + f'Order.add_right({mlit + k0}n, {k2}n, P, {{==}}))'
        steps = []
        for g in range(NL - 1, j_stop - 1, -1):
            kind, V, kL, i = layers[g]
            if kind == 'var':
                D2 = f'VF.updv([{FS}], dd, {tree(g)}, Nat.add({po}n, P))'
                pf2 = f'VF.updv_perfect([{FS}], dd, {tree(g)}, Nat.add({po}n, P), {pfl(g)})'
                assert mlit is not None and k0 + mlit <= H
                pr1 = (f'VBE.peel_mone_hi(VC.NW(N), 0n, Nat.add({H}n, P), dd, {D2}, TX, {m}, {p}, {pf2}, hdst, '
                       f'Order.add_right({mlit + k0}n, {H}n, P, {{==}}))')
                steps.append((win(m, p, g + 1), f'VF.WIN({m}, {p}, FD.array__slots(U32, {D2}))', pr1))
                pr2 = rel(1, po, f'[{FS}], dd, {tree(g)}, Nat.add({po}n, P)').replace('@PF@', pfl(g)).replace('@HB@', hbw(1, po))
                steps.append((f'VF.WIN({m}, {p}, FD.array__slots(U32, {D2}))', win(m, p, g), pr2))
            else:
                f = x.fields[i]
                pr = rel(f['W'], kL, f'{vterm(kind, V, i)}, dd, {tree(g)}, Nat.add({kL}n, P)').replace('@PF@', pfl(g)).replace('@HB@', hbw(f['W'], kL))
                steps.append((win(m, p, g + 1), win(m, p, g), pr))
        out = last_proof
        for a, b, pr in reversed(steps):
            out = f'Equal.trans({LT}, {a}, {b}, {last_term}, {pr},\n    {out})'
        return out

    segs = []
    for i, f in enumerate(x.fields):
        if f['kind'] == 'var':
            segs.append((i, 1, f['k'], f'[{FS}]'))
        else:
            segs.append((i, f['W'], f['k'], f'[{", ".join(E.words[i])}]'))
    layer_of = {l[3]: j for j, l in enumerate(layers)}
    for i, Wd, k0, Vs in segs:
        f = x.fields[i]
        j = layer_of[i]
        m, p = f'{Wd}n', f'Nat.add({k0}n, P)'
        if f['kind'] == 'var':
            D2 = f'VF.updv([{FS}], dd, {tree(j)}, Nat.add({po}n, P))'
            own = (TPL.render('own', D2=D2, FS=FS, H=H, LT=LT, Vs=Vs, hbw=hbw, j=j, m=m, p=p, pfl=pfl, po=po, tree=tree, win=win))
        else:
            own = f'V2.own({vterm(layers[j][0], layers[j][1], i)}, dd, {tree(j)}, Nat.add({k0}n, P), {pfl(j)}, {hbw(Wd, k0)})'
        body = peel_chain(m, k0, Wd, j + 1, Vs, own)
        w(f'def seg{i}({WP_}) -> {{{win(m, p, NL)} == {Vs} : {LT}}}:')
        w('  ' + body)
        w('')
    D2 = f'VF.updv([{FS}], dd, {tree(vj)}, Nat.add({po}n, P))'
    own = (f'VBE.own_mone(VC.NW(N), Nat.add({H}n, P), dd, {D2}, dX, TX, VF.updv_perfect([{FS}], dd, {tree(vj)}, Nat.add({po}n, P), {pfl(vj)}), '
           f'pfX, hdst, hrX)')
    body = peel_chain('VC.NW(N)', H, None, vj + 1, 'VS.wtake(VC.NW(N), FD.array__slots(U32, TX))', own)
    w(f'def pay_eq({WP_}) -> {{{win("VC.NW(N)", f"Nat.add({H}n, P)", NL)} == VS.wtake(VC.NW(N), FD.array__slots(U32, TX)) : {LT}}}:')
    w('  ' + body)
    w('')

    # the frame: windows below the encoding are left alone
    steps = []
    for g in range(NL - 1, -1, -1):
        kind, V, kL, i = layers[g]
        hlo = f'FD.nat__le_trans(Nat.add(m, p), P, Nat.add({kL}n, P), h, Order.left_below_sum({kL}n, P))'
        if kind == 'var':
            D2 = f'VF.updv([{FS}], dd, {tree(g)}, Nat.add({po}n, P))'
            pf2 = f'VF.updv_perfect([{FS}], dd, {tree(g)}, Nat.add({po}n, P), {pfl(g)})'
            steps.append((f'VF.WIN(m, p, FD.array__slots(U32, {tree(g + 1)}))', f'VF.WIN(m, p, FD.array__slots(U32, {D2}))',
                          f'VBE.peel_mone_hi(VC.NW(N), 0n, Nat.add({H}n, P), dd, {D2}, TX, m, p, {pf2}, hdst, FD.nat__le_trans(Nat.add(m, p), P, Nat.add({H}n, P), h, Order.left_below_sum({H}n, P)))'))
            steps.append((f'VF.WIN(m, p, FD.array__slots(U32, {D2}))', f'VF.WIN(m, p, FD.array__slots(U32, {tree(g)}))',
                          f'V2.peel_hi([{FS}], dd, {tree(g)}, Nat.add({po}n, P), m, p, {pfl(g)}, {hbw(1, po)}, FD.nat__le_trans(Nat.add(m, p), P, Nat.add({po}n, P), h, Order.left_below_sum({po}n, P)))'))
        else:
            f = x.fields[i]
            steps.append((f'VF.WIN(m, p, FD.array__slots(U32, {tree(g + 1)}))', f'VF.WIN(m, p, FD.array__slots(U32, {tree(g)}))',
                          f'V2.peel_hi({vterm(kind, V, i)}, dd, {tree(g)}, Nat.add({kL}n, P), m, p, {pfl(g)}, {hbw(f["W"], kL)}, {hlo})'))
    out = '{==}'
    for a_, b_, pr in reversed(steps):
        out = f'Equal.trans({LT}, {a_}, {b_}, VF.WIN(m, p, FD.array__slots(U32, D)), {pr},\n    {out})'
    for line in TPL.render('enc_spec_text_lines', DA=DA, DP=DP, HDST=HDST, LT=LT, PFD=PFD).split('\n'):
        w(line)
    w('  ' + out)
    w('')
    hdr = []
    for i, Wd, k0, Vs in segs:
        hdr += (E.words[i] if x.fields[i]['kind'] != 'var' else [str(FS)])
    HDRE = '[' + ', '.join(hdr) + ']'
    w(f'def hdr_eq({WP_}) -> {{{win(f"{H}n", "Nat.add(0n, P)", NL)} == {HDRE} : {LT}}}:')
    R, pos_ = H, 0
    pre = lambda t: t  # noqa: E731
    for idx, (i, Wd, k0, Vs) in enumerate(segs):
        assert k0 == pos_
        if idx < len(segs) - 1:
            s1, s3, sl = wsplit(Wd, R - Wd, pos_)
            w(f'  %Equal.sym({LT}, {win(s1, f"Nat.add({pos_}n, P)", NL)}, VF.app({win(f"{Wd}n", f"Nat.add({pos_}n, P)", NL)}, {win(f"{R - Wd}n", f"Nat.add({s3}, P)", NL)}),')
            w(f'      {sl}({Wd}n, {R - Wd}n, {pos_}n, P, {S_})) :')
            w(f'    {{{pre("_")} == {HDRE} : {LT}}}')
            rest = win(f'{R - Wd}n', f'Nat.add({pos_ + Wd}n, P)', NL)
            w(f'  %Equal.sym({LT}, {win(f"{Wd}n", f"Nat.add({pos_}n, P)", NL)}, {Vs}, seg{i}({WA_})) :')
            w(f'    {{{pre(f"VF.app(_, {rest})")} == {HDRE} : {LT}}}')
            pre = (lambda p0, Vs: (lambda t: p0(f'VF.app({Vs}, {t})')))(pre, Vs)
            R, pos_ = R - Wd, pos_ + Wd
        else:
            assert R == Wd
            w(f'  %Equal.sym({LT}, {win(f"{Wd}n", f"Nat.add({pos_}n, P)", NL)}, {Vs}, seg{i}({WA_})) :')
            w(f'    {{{pre("_")} == {HDRE} : {LT}}}')
    w('  {==}')
    w('')
    YE = 'VS.bt(U32.to_nat(N), F.limbs(FD.array__slots(U32, TX)))'
    BYTES = f'VS.bt(U32.to_nat(SFS(N)), F.limbs(VB.wdr(P, {S_})))'
    RB = f'List.append(&2, U32, F.limbs({HDRE}), {YE})'
    WT = f'VS.bt(U32.to_nat(N), F.limbs(VS.wtake(VC.NW(N), FD.array__slots(U32, TX))))'
    w(TPL.render('enc_spec_text_bytesw_enc', BYTES=BYTES, DA=DA, FS=FS, H=H, HDD=HDD, HDRE=HDRE, KY=KY, LT=LT, NL=NL, RB=RB, S_=S_, WA_=WA_, WP_=WP_, WT=WT, YE=YE))
    wt = lambda f, j: E.words[x.fields.index(f)][j]  # noqa: E731
    ITEMS, CHAIN, PL, CAT, PRE, POST, hdr2 = VBY.spec_items(x, 'Y', wt)
    assert '[' + ', '.join(hdr2) + ']' == HDRE
    MP = 'Maybe<&2, +List<S.Part>>'
    M = 'Maybe<&2, +List<U32>>'
    ENC = f'List.append(&2, U32, F.limbs({HDRE}), Y)'
    ENCR = f'List.append(&2, U32, List.append(&2, U32, F.flat({PRE}), List.append(&2, U32, N.digits(4n, VS.FSZ({PRE}, {POST})), F.flat({POST}))), Y)'
    BY0 = f'VS.bt(U32.to_nat(SFS(N)), F.limbs(FD.array__slots(U32, {T0})))'
    w(f'''# The value of an object of words w.., packed words TB.. and byte list Y.
def XEY({E.P}, +Y: +List<U32>) -> S.Value: S.Sequence{{{ITEMS}}}

def encE({E.P}, +Y: +List<U32>, +hdom: {{SP.bytes_domain(Y) == True{{}} : Bool}},
    +hlen: {{Nat.is_le(List.length(&2, U32, Y), {LIM}n) == True{{}} : Bool}})
    -> {{Codec.parts(XEY({E.A}, Y), Spec.{n}()) == Some{{[S.Variable{{{ENC}}}]}} : {MP}}}:
  +fit = VS.fits_mono(4n, Nat.add(VS.FSZ({PRE}, {POST}), List.length(&2, U32, Y)), Nat.add({FS}n, {LIM}n),
    Order.add_left({FS}n, List.length(&2, U32, Y), {LIM}n, hlen), {{==}})
{_seq_step(n, f'XEY({E.A}, Y)', ITEMS, CHAIN, f'Some{{[S.Variable{{{ENC}}}]}}', MP)}  %Equal.sym({MP}, Codec.parts({ITEMS}, {CHAIN}), Some{{{PL}}},
      {CAT}) :
    {{Codec.aggregate(_, SC.fixed_size({CHAIN})) == Some{{[S.Variable{{{ENC}}}]}} : {MP}}}
  %Equal.sym({M}, Layout.encoding(VS.fpv({PRE}, Y, {POST})), Some{{{ENCR}}}, VZ.enc_fpvb({PRE}, Y, {POST}, hdom, fit)) :
    {{Codec.one(_, None{{}}) == Some{{[S.Variable{{{ENC}}}]}} : {MP}}}
  {{==}}

# The value of the object: its byte list's value is the first N bytes of its storage.
def XE({E.P}) -> S.Value: XEY({E.A}, {YE})

def hlenE(+dX: Nat, +TX: FD.array__Tree<U32>, +N: U32, {HN}) -> {{Nat.is_le(List.length(&2, U32, {YE}), {LIM}n) == True{{}} : Bool}}:
  FD.nat__le_trans(List.length(&2, U32, {YE}), U32.to_nat(N), {LIM}n, VZ.bt_len_le(U32.to_nat(N), F.limbs(FD.array__slots(U32, TX))), hN)

# The spec parts of the object's value are one variable part: the bytes of the
# encoder's output window.
def partsw({WP_}, {HDD})
    -> {{Codec.parts(XE({E.A}), Spec.{n}()) == Some{{[S.Variable{{{BYTES}}}]}} : {MP}}}:
  %Equal.sym(+List<U32>, {BYTES}, {RB}, bytesw_enc({WA_}, hdd)) :
    {{Codec.parts(XE({E.A}), Spec.{n}()) == Some{{[S.Variable{{_}}]}} : {MP}}}
  encE({E.A}, {YE}, VZ.bd_btl(U32.to_nat(N), FD.array__slots(U32, TX)), hlenE(dX, TX, N, hN))

# The bytes the encoder writes are the spec/codec.bend encoding of the object's value.
law encode_spec:
''' + '\n'.join(f'  for {q}' for q in E.params + E.hyps) + TPL.render('enc_spec_text_encode_spec', A0=A0, BY0=BY0, DO=DO, E=E, HD0=HD0, M=M, MP=MP, n=n))
    return L


def enc_module_text(x):
    E, L, layers, leaves, NL = enc_text(x)
    L = L + enc_spec_text(x, E, layers, NL)
    txt = '\n'.join(L) + '\n'
    return txt.replace('import ./vbenc.bend as VBE\n', 'import ./vbenc.bend as VBE\nimport ./venc2.bend as V2\n', 1)
