#!/usr/bin/env python3
"""Encoder laws of containers of variable-size names (AttesterSlashing).

    encw_text(g, x)    -> VL.fname(x, '_encw'): the writer of a name x of the
                          single_list_container_codec_laws.py family at a symbolic word-aligned position
                          pos = 4 P into an existing output tree D (putw), the
                          output's windows (segments, winw) and the windows
                          before it (ow_hi), and the spec parts of the value
                          (partsE);
    as_enc_text(g, xc) -> var_codec_<parent>_enc.bend: encode_eval and
                          encode_spec of the container of two boxed xc.

The output tree of a name at P: the offset word (IW0), the list's words
copied after the header (IW1, VB.mone) and the fixed fields' words (runs of
VF.updv), all at P + their own word index; windows are peeled with
proofs/obj/venc2.bend and proofs/obj/vnenc.bend.
"""
import re

from codegen.proofs.var import single_list_container_codec_laws as VL
from codegen.impl import runtime_file_split as RR  # noqa: E402  the runtime split: the monoliths' text, the split files' imports
from codegen.proofs.support import zeros_without_case_split as ZD  # noqa: E402
from codegen.proofs.support import large_limit_size_facts as LPW  # noqa: E402
from codegen.core.template_loader import Templates  # noqa: E402
TEMPLATES = Templates('nested_container_encoder_laws', globals())


def _ctx(g, x, pre='w'):
    FS, H, po, lp, LIM = x.FS, x.H, x.po, x.lp, x.LIM
    ks = [k for k in range(H) if k != po]
    fixed = [f for f in x.fields if f['kind'] == 'fix']

    def V(f):
        return '[' + ', '.join(f'{pre}{f["k"] + j}' for j in range(f['ft'].W)) + ']'

    def fobj(f):
        return f['ft'].obj([f'{pre}{f["k"] + j}' for j in range(f['ft'].W)])
    return ks, fixed, V, fobj


def encw_text(g, x):
    n, FS, H, po, LIM, lp = x.n, x.FS, x.H, x.po, x.LIM, x.lp
    cvar = x.var['c']
    Tn = f'T.{n}'
    src = RR.mono_text('fulu')
    m = re.search(rf'def {lp}_valid\(o: O\.Words\) -> O\.Words & Bool: O\.words_ok\(o, 0, (\d+), False\{{\}}, 8\)', src)
    LIMB = int(m.group(1))
    ITEMS, CHAIN, PL, CAT, PRE, POST, hdr, LIMN, YS = VL.spec_parts(g, x, lambda k: f'w{k}')
    ks, fixed, V, fobj = _ctx(g, x)
    # The closed limit facts: `{==}` for a small limit, symbolic (codegen/proofs/support/large_limit_size_facts.py) for 2^p.
    LP = LPW.LimPow(LIMN)
    if LP.big:
        assert LIMB == 8 * LP.M
        K_LB = LP.le_u32(LP.x8(), LP.x8().s)
        XF = LP.add(FS, LP.x8())
        K_FIT = LP.fits(XF, LP.bound(XF))
    else:
        K_LB = K_FIT = '{==}'
    WS = ', '.join(f'+w{k}: U32' for k in ks)
    WA = ', '.join(f'w{k}' for k in ks)
    objs = [fobj(f) if f['kind'] == 'fix' else 'O.Words{FD.array__thaw(U32, T), N}' for f in x.fields]
    OBJ = f'{Tn}{{' + ', '.join(objs) + '}'
    FIXOBJS = ', '.join(fobj(f) for f in fixed)
    WORDS = 'O.Words{FD.array__thaw(U32, T), N}'
    NW = 'VC.NW(N)'
    toN = 'U32.to_nat(N)'
    ST = 'FD.array__slots(U32, T)'
    LT = 'List<&2, U32>'
    M = 'Maybe<&2, +List<U32>>'
    MP = 'Maybe<&2, +List<S.Part>>'
    HDR = ' <> '.join(hdr)
    HDRL = '[' + ', '.join(hdr) + ']'
    last = 1 + len(fixed)

    def IW(j):
        return f'IW{j}({WA}, dd, D, P, N, T)'
    IAW = IW(last)
    SW = f'FD.array__slots(U32, {IAW})'
    HR = f'+hR: {{Nat.is_le(Nat.add(Nat.add({H}n, {NW}), P), VB.pw(dd)) == True{{}} : Bool}}'
    CW = f'{WS}, +dd: Nat, +D: FD.array__Tree<U32>, +P: Nat, +N: U32, +T: FD.array__Tree<U32>'
    CWa = f'{WA}, dd, D, P, N, T'
    HW = ('+pfD: {FD.array__perfect(U32, dd, D) == True{} : Bool}, +hdd: {Nat.is_lt(dd, 29n) == True{} : Bool},\n    ' + HR)
    HWa = 'pfD, hdd, hR'
    SRC = ('+dw: Nat, +c: Nat, +pfT: {FD.array__perfect(U32, dw, T) == True{} : Bool}, +hdw: {Nat.is_lt(dw, 31n) == True{} : Bool},\n'
           '    +ec: {U32.to_nat(N) == VS.x8(c) : Nat}, +hc: {Nat.is_le(c, ' + LIMN + ') == True{} : Bool},\n'
           '    +hroom: {Nat.is_le(Nat.add(VC.NW(N), 0n), VB.pw(dw)) == True{} : Bool}')
    SRCa = 'dw, c, pfT, hdw, ec, hc, hroom'
    E = f'import ./{VL.fname(x, "_enc").name} as E'
    L = list(VL.DEC_HEAD) + ['import ./venc.bend as VE', 'import ./venc2.bend as V2', 'import ./vnenc.bend as VN', E] + VL.lim_imports(x) + VL.SPEC_IMPORTS + ['',
                             '# GENERATED by nested_container_encoder_laws (codegen). Do not edit.',
                             f'# The writer of {n} at a word-aligned position pos = 4 P of an existing output',
                             '# tree D (putw), the windows of its output (winw) and before it (ow_hi), and the',
                             '# spec parts of its value (partsE), for the encoders of containers of it.', '']
    w = L.append
    TREES = [f'def IW0({WS}, +dd: Nat, +D: FD.array__Tree<U32>, +P: Nat, +N: U32, +T: FD.array__Tree<U32>) -> FD.array__Tree<U32>:\n'
             f'  FD.array__upd(U32, dd, D, Nat.add({po}n, P), {FS})',
             f'def IW1({CW}) -> FD.array__Tree<U32>: VB.mone({NW}, 0n, Nat.add({H}n, P), dd, {IW(0)}, T)']
    for j, f in enumerate(fixed):
        TREES.append(f'def IW{j + 2}({CW}) -> FD.array__Tree<U32>: VF.updv({V(f)}, dd, {IW(j + 1)}, Nat.add({f["k"]}n, P))')
    w('\n'.join(TREES))
    w(TEMPLATES.render('encw_text', H=H, HR=HR, NW=NW, CW=CW, IW=IW, po=po, FS=FS, CWa=CWa))
    for j, f in enumerate(fixed):
        w(f'def pfW{j + 2}({CW}, +pfD: {{FD.array__perfect(U32, dd, D) == True{{}} : Bool}}) -> {{FD.array__perfect(U32, dd, {IW(j + 2)}) == True{{}} : Bool}}:')
        w(f'  VF.updv_perfect({V(f)}, dd, {IW(j + 1)}, Nat.add({f["k"]}n, P), pfW{j + 1}({CWa}, pfD))')

    def hbq(a):
        return f'hq({a}, dd, P, N, {{==}}, hR)'

    def puts(j, inner):
        t = inner
        for f in fixed[j:]:
            t = f'T.{f["ft"].p}_put({t}, U32.add(pos, {f["c"]}), {fobj(f)})'
        return t
    RP = f'(FD.array__thaw(U32, {IAW}), ({OBJ}, E.SFS(N)))'
    TP = f'Array<U32> & ({Tn} & U32)'
    pO = f'U32.add(pos, {cvar})'
    pF = f'U32.add(pos, {FS})'
    w(f'''
# The writer at pos = 4 P returns the output tree IW{last} and the object's size.
def putw({CW}, +pos: U32, +e: {{U32.to_nat(pos) == A.quad(P) : Nat}}, {HW},
    {SRC})
    -> {{{Tn}_putn(FD.array__thaw(U32, D), pos, {OBJ}) == {RP} : {TP}}}:
  +hd31 = FD.nat__lt_trans(dd, 29n, 31n, hdd, {{==}})
  +hd32 = VB.lt32(dd, hd31)
  +eO = eoff(pos, {cvar}, {po}n, dd, P, N, e, {{==}}, {{==}}, hdd, hR)
  +eF = eoff(pos, {FS}, {H}n, dd, P, N, e, {{==}}, {{==}}, hdd, hR)
  %Equal.sym(U32, U32.and({pO}, 3), 0, VF.al_3({pO}, Nat.add({po}n, P), eO)) :
    {{{Tn}_pw0(pos, {FIXOBJS}, T.{lp}_pvb({FS}, T.{lp}_pk(O.w32_pick(U32.is_eq(_, 0), FD.array__thaw(U32, D), {pO}, {FS}), {pF}, T.{lp}_valid({WORDS})))) == {RP} : {TP}}}
  %Equal.sym(Array<U32>, Array.set(U32, FD.array__thaw(U32, D), U32.shrn({pO}, 2n), {FS}), FD.array__thaw(U32, {IW(0)}),
      VB.set_n(dd, D, U32.shrn({pO}, 2n), Nat.add({po}n, P), {FS}, VF.al_q({pO}, Nat.add({po}n, P), eO), hd32,
        FD.nat__lt_le_trans(Nat.add({po}n, P), Nat.add({H}n, P), VB.pw(dd), VB.lt_kk({po}n, {H}n, P, {{==}}), {hbq(f"{H}n")}), pfD)) :
    {{{Tn}_pw0(pos, {FIXOBJS}, T.{lp}_pvb({FS}, T.{lp}_pk(_, {pF}, T.{lp}_valid({WORDS})))) == {RP} : {TP}}}
  %Equal.sym(O.Words & Bool, O.words_ok({WORDS}, 0, {LIMB}, False{{}}, 8), ({WORDS}, True{{}}),
      VE.words_ok_u64(dw, T, N, {LIMB}, c, pfT, hdw, ec, FD.nat__le_trans({toN}, VS.x8({LIMN}), U32.to_nat({LIMB}), E.leN(N, c, ec, hc), {K_LB}), hroom)) :
    {{{Tn}_pw0(pos, {FIXOBJS}, T.{lp}_pvb({FS}, T.{lp}_pk(FD.array__thaw(U32, {IW(0)}), {pF}, _))) == {RP} : {TP}}}
  %Equal.sym(Array<U32> & O.Words, O.put_words(FD.array__thaw(U32, {IW(0)}), {pF}, {WORDS}), (FD.array__thaw(U32, {IW(1)}), {WORDS}),
      VE.put_words_ok(dd, dw, {IW(0)}, T, {pF}, Nat.add({H}n, P), N, pfW0({CWa}, pfD), pfT, hd31, hdw,
        VF.al_3({pF}, Nat.add({H}n, P), eF), VF.al_q({pF}, Nat.add({H}n, P), eF), VC.and3_x8(N, c, ec), hroom, hdstw(dd, P, N, hR))) :
    {{{Tn}_pw0(pos, {FIXOBJS}, T.{lp}_pvb({FS}, O.pwn(_))) == {RP} : {TP}}}
  %Equal.sym(U32, O.padd({FS}, N), E.SFS(N), E.padd(N, c, ec, hc)) :
    {{({puts(0, f"FD.array__thaw(U32, {IW(1)})")}, ({OBJ}, _)) == {RP} : {TP}}}''')
    for j, f in enumerate(fixed):
        ft = f['ft']
        cur = f'T.{ft.p}_put(FD.array__thaw(U32, {IW(j + 1)}), U32.add(pos, {f["c"]}), {fobj(f)})'
        wsx = ', '.join(f'w{f["k"] + i}' for i in range(ft.W))
        k_f = f['k']
        w(f'  %Equal.sym(Array<U32>, {cur}, FD.array__thaw(U32, {IW(j + 2)}),')
        w(f'      VT.put_{ft.p}(dd, {IW(j + 1)}, U32.add(pos, {f["c"]}), Nat.add({f["k"]}n, P), eoff(pos, {f["c"]}, {f["k"]}n, dd, P, N, e, {{==}}, {{==}}, hdd, hR), hdd, pfW{j + 1}({CWa}, pfD), {hbq(f"Nat.add({ft.W}n, {k_f}n)")}, {wsx})) :')
        w(f'    {{({puts(j + 1, "_")}, ({OBJ}, E.SFS(N))) == {RP} : {TP}}}')
    w('  {==}')
    w('')

    # ---- windows of the output ----
    def win(mm, p, j=last):
        return f'VF.WIN({mm}, {p}, FD.array__slots(U32, {IW(j)}))'

    def shift(a, b):
        """is_le(a + P, b + P) for closed a <= b, as the checker reduces it."""
        assert a <= b
        return f'Order.left_below_sum({b - a}n, P)'

    def chain(steps, last_term, last_proof):
        out = last_proof
        for a, b, pr in reversed(steps):
            out = f'Equal.trans({LT}, {a}, {b}, {last_term}, {pr},\n    {out})'
        return out

    def peel_fixed(mm, p, lo_hi, stop):
        """steps peeling fixed fields len(fixed)-1 .. stop (window mm at p)."""
        steps = []
        for g_ in range(len(fixed) - 1, stop - 1, -1):
            fg = fixed[g_]
            kind, hproof = lo_hi(fg)
            hb = hbq(f'Nat.add({fg["ft"].W}n, {fg["k"]}n)')
            pr = f'V2.peel_{kind}({V(fg)}, dd, {IW(g_ + 1)}, Nat.add({fg["k"]}n, P), {mm}, {p}, pfW{g_ + 1}({CWa}, pfD), {hb}, {hproof})'
            steps.append((win(mm, p, g_ + 2), win(mm, p, g_ + 1), pr))
        return steps

    HWP = HW
    for i, f in enumerate(x.fields):
        if f['kind'] == 'fix':
            j = fixed.index(f)
            k0, W0 = f['k'], f['ft'].W

            def rel(fg, k0=k0, W0=W0):
                if fg['k'] + fg['ft'].W <= k0:
                    return 'lo', shift(fg['k'] + fg['ft'].W, k0)
                return 'hi', shift(k0 + W0, fg['k'])
            steps = peel_fixed(f'{W0}n', f'Nat.add({k0}n, P)', rel, j + 1)
            lastp = f'V2.own({V(f)}, dd, {IW(j + 1)}, Nat.add({k0}n, P), pfW{j + 1}({CWa}, pfD), {hbq(f"Nat.add({W0}n, {k0}n)")})'
            w(f'def segw{i}({CW}, {HWP}) -> {{{win(f"{W0}n", f"Nat.add({k0}n, P)")} == {V(f)} : {LT}}}:')
            w('  ' + chain(steps, V(f), lastp))
            w('')
        else:
            def rel(fg):
                if fg['k'] + fg['ft'].W <= po:
                    return 'lo', shift(fg['k'] + fg['ft'].W, po)
                return 'hi', shift(po + 1, fg['k'])
            steps = peel_fixed('1n', f'Nat.add({po}n, P)', rel, 0)
            steps.append((win('1n', f'Nat.add({po}n, P)', 1), win('1n', f'Nat.add({po}n, P)', 0),
                          f'VN.pm_hi({NW}, Nat.add({H}n, P), dd, {IW(0)}, T, 1n, Nat.add({po}n, P), pfW0({CWa}, pfD), hdstw(dd, P, N, hR), {shift(po + 1, H)})'))
            lastp = f'V2.own([{FS}], dd, D, Nat.add({po}n, P), pfD, {hbq(f"Nat.add(1n, {po}n)")})'
            w(f'def segw{i}({CW}, {HWP}) -> {{{win("1n", f"Nat.add({po}n, P)")} == [{FS}] : {LT}}}:')
            w('  ' + chain(steps, f'[{FS}]', lastp))
            w('')
    # payload
    steps = peel_fixed(NW, f'Nat.add({H}n, P)', lambda fg: ('lo', shift(fg['k'] + fg['ft'].W, H)), 0)
    lastp = f'VN.pm_own({NW}, Nat.add({H}n, P), dd, {IW(0)}, dw, T, pfW0({CWa}, pfD), pfT, hdstw(dd, P, N, hR), hroom)'
    w(f'def payw({CW}, {HWP}, +dw: Nat, +pfT: {{FD.array__perfect(U32, dw, T) == True{{}} : Bool}}, +hroom: {{Nat.is_le(Nat.add(VC.NW(N), 0n), VB.pw(dw)) == True{{}} : Bool}})')
    w(f'    -> {{{win(NW, f"Nat.add({H}n, P)")} == VS.wtake({NW}, {ST}) : {LT}}}:')
    w('  ' + chain(steps, f'VS.wtake({NW}, {ST})', lastp))
    w('')
    # header and whole window
    segs = []
    for i, f in enumerate(x.fields):
        segs.append((i, f['ft'].W if f['kind'] == 'fix' else 1, f['k'], V(f) if f['kind'] == 'fix' else f'[{FS}]'))
    w(f'def hdrw({CW}, {HWP}) -> {{{win(f"{H}n", "P")} == {HDRL} : {LT}}}:')
    R, s = H, 0
    pre = lambda t: t  # noqa: E731
    for idx, (i, Wd, k, Vs) in enumerate(segs):
        assert k == s
        ps = f'Nat.add({s}n, P)'
        if idx < len(segs) - 1:
            w(f'  %Equal.sym({LT}, {win(f"Nat.add({Wd}n, {R - Wd}n)", ps)}, VF.app({win(f"{Wd}n", ps)}, {win(f"{R - Wd}n", f"Nat.add({Wd}n, {ps})")}),')
            w(f'      VN.win_split2({Wd}n, {R - Wd}n, {ps}, {f"FD.array__slots(U32, {IAW})"})) :')
            w(f'    {{{pre("_")} == {HDRL} : {LT}}}')
            w(f'  %Equal.sym({LT}, {win(f"{Wd}n", ps)}, {Vs}, segw{i}({CWa}, {HWa})) :')
            rest = win(f'{R - Wd}n', f'Nat.add({s + Wd}n, P)')
            w(f'    {{{pre(f"VF.app(_, {rest})")} == {HDRL} : {LT}}}')
            pre = (lambda p0, Vs: (lambda t: p0(f'VF.app({Vs}, {t})')))(pre, Vs)
            R, s = R - Wd, s + Wd
        else:
            w(f'  %Equal.sym({LT}, {win(f"{Wd}n", ps)}, {Vs}, segw{i}({CWa}, {HWa})) :')
            w(f'    {{{pre("_")} == {HDRL} : {LT}}}')
    w('  {==}')
    w('')
    RWW = f'VF.app({HDRL}, VS.wtake(Nat.double(c), {ST}))'
    w(f'''# The output's window at P: the header words and the list's words.
def winw({CW}, {HW},
    {SRC})
    -> {{{win(f"Nat.add({H}n, {NW})", "P")} == {RWW} : {LT}}}:
  %Equal.sym({LT}, {win(f"Nat.add({H}n, {NW})", "P")}, VF.app({win(f"{H}n", "P")}, {win(NW, f"Nat.add({H}n, P)")}), VN.win_split2({H}n, {NW}, P, {SW})) :
    {{_ == {RWW} : {LT}}}
  %Equal.sym({LT}, {win(f"{H}n", "P")}, {HDRL}, hdrw({CWa}, {HWa})) : {{VF.app(_, {win(NW, f"Nat.add({H}n, P)")}) == {RWW} : {LT}}}
  %Equal.sym({LT}, {win(NW, f"Nat.add({H}n, P)")}, VS.wtake({NW}, {ST}), payw({CWa}, {HWa}, dw, pfT, hroom)) : {{VF.app({HDRL}, _) == {RWW} : {LT}}}
  %Equal.sym(Nat, {NW}, Nat.double(c), E.nwN(N, c, ec, hc)) : {{VF.app({HDRL}, VS.wtake(_, {ST})) == {RWW} : {LT}}}
  {{==}}
''')
    # before the output
    steps = peel_fixed('m', 'p', lambda fg: ('hi', f'FD.nat__le_trans(Nat.add(m, p), P, Nat.add({fg["k"]}n, P), hm, Order.left_below_sum({fg["k"]}n, P))'), 0)
    steps.append((win('m', 'p', 1), win('m', 'p', 0),
                  f'VN.pm_hi({NW}, Nat.add({H}n, P), dd, {IW(0)}, T, m, p, pfW0({CWa}, pfD), hdstw(dd, P, N, hR), FD.nat__le_trans(Nat.add(m, p), P, Nat.add({H}n, P), hm, Order.left_below_sum({H}n, P)))'))
    lastp = (f'V2.peel_hi([{FS}], dd, D, Nat.add({po}n, P), m, p, pfD, {hbq(f"Nat.add(1n, {po}n)")}, '
             f'FD.nat__le_trans(Nat.add(m, p), P, Nat.add({po}n, P), hm, Order.left_below_sum({po}n, P)))')
    WD = 'VF.WIN(m, p, FD.array__slots(U32, D))'
    w(f'# A window before P is that of D.')
    w(f'def ow_hi({CW}, {HW}, +m: Nat, +p: Nat, +hm: {{Nat.is_le(Nat.add(m, p), P) == True{{}} : Bool}})')
    w(f'    -> {{{win("m", "p")} == {WD} : {LT}}}:')
    w('  ' + chain(steps, WD, lastp))
    w('')
    # spec parts
    RHSp = f'Some{{[S.Variable{{F.limbs({HDR} <> {YS})}}]}}'
    ENCR = f'List.append(&2, U32, List.append(&2, U32, F.flat({PRE}), List.append(&2, U32, N.digits(4n, VS.FSZ({PRE}, {POST})), F.flat({POST}))), F.limbs({YS}))'
    w(TEMPLATES.render('encw_text_2', WS=WS, LIMN=LIMN, WA=WA, n=n, RHSp=RHSp, MP=MP, YS=YS, PRE=PRE, POST=POST, FS=FS, K_FIT=K_FIT, ITEMS=ITEMS, CHAIN=CHAIN, PL=PL, CAT=CAT, M=M, ENCR=ENCR, HDR=HDR))
    return '\n'.join(L) + '\n'


def _ae_limits(g, xc, parent):
    """the nested list's sizes, the bounds on its powers of two and the limit arithmetic"""
    n, FS, H, po, LIM = xc.n, xc.FS, xc.H, xc.po, xc.LIM
    Tc, Tp = f'T.{n}', f'T.{parent}'
    ITEMS, CHAIN, PL, CAT, PRE, POST, hdr, LIMN, YS = VL.spec_parts(g, xc, lambda k: f'w{k}')
    B1 = FS + 8 * LIM
    PB = (8 + 2 * B1).bit_length()
    P3 = (31 + 8 + 2 * B1).bit_length()
    KA = VL.ceil_log2(2 + 2 * (H + 2 * LIM))
    KO = KA - 1
    FA = (4 + FS + 8 * LIM).bit_length()
    assert FA + 1 < 32
    assert H + 1 + 2 * LIM <= 1 << KO
    assert PB <= 31 and P3 < 31 and KA < 29
    # The closed limit facts: `{==}` for a small limit, symbolic (codegen/proofs/support/large_limit_size_facts.py) for 2^p.
    LP = LPW.LimPow(LIMN)
    if LP.big:
        XLt = LP.add(FS, LP.x8())
        X8L = LP.add(8, XLt)
        X2 = LP.sum(X8L, XLt)
        BC1, BC2 = 1 << LP.bound(X8L), 1 << LP.bound(X2)
        K_C1 = LP.le_u32(X8L, LP.bound(X8L))
        K_C2 = LP.le_u32(X2, LP.bound(X2))
        K_P1, K_P8 = LP.lt(XLt, PB), LP.lt(X8L, PB)
        K_Y2 = LP.le(LP.add(31, X2), P3)
        MXB = f'Nat.add({H + 1}n, Nat.double({LIMN}))'
        K_XB = LP.le_pow2n(LP.add(H + 1, LP.dbl()), KO)
        K_FA = LP.le_spow2(LP.add(FS + 4, LP.x8()), FA)
    else:
        BC1, BC2 = 8 + B1, 8 + 2 * B1
        K_C1 = K_C2 = K_P1 = K_P8 = K_Y2 = K_XB = K_FA = '{==}'
        MXB = f'{H + 1}n+Nat.double({LIMN})'
    return n, FS, H, po, Tc, Tp, hdr, LIMN, YS, PB, P3, KA, KO, FA, BC1, BC2, K_C1, K_C2, K_P1, K_P8, K_Y2, MXB, K_XB, K_FA


def _ae_sides(g, xc, parent, n, H, po, Tc, hdr, LIMN):
    """the module header and the two sides (the child records) of the parent"""
    L = list(VL.DEC_HEAD) + ['import ./venc.bend as VE', 'import ./venc2.bend as V2', 'import ./vnenc.bend as VN', 'import ./vdig.bend as VG', 'import ./vfits.bend as VFT', 'import ../../src/primitives.bend as I',
                             f'import ./{VL.fname(xc, "_enc").name} as E', f'import ./{VL.fname(xc, "_encw").name} as IW'] + VL.lim_imports(xc) + VL.SPEC_IMPORTS + ['',
                             '# GENERATED by nested_container_encoder_laws (codegen). Do not edit.',
                             f'# The encoder of {parent}, two boxed {n}: for all objects of {n}',
                             '# (as in E.encode_eval), T.<parent>_encode returns the object and the buffer',
                             '# B.Buf{thaw(AW2), C2} (encode_eval), whose bytes are the spec/codec.bend',
                             '# encoding of the object\'s value (encode_spec).', '']
    w = L.append
    sides = []
    for s, pre in (('1', 'a'), ('2', 'b')):
        ks, fixed, V, fobj = _ctx(g, xc, pre)
        WS = ', '.join(f'+{pre}{k}: U32' for k in ks)
        WA = ', '.join(f'{pre}{k}' for k in ks)
        objs = [fobj(f) if f['kind'] == 'fix' else f'O.Words{{FD.array__thaw(U32, T{s}), N{s}}}' for f in xc.fields]
        hdrs = [h if i == po else f'{pre}{i}' for i, h in enumerate(hdr)]
        sides.append(dict(s=s, WS=WS, WA=WA, OBJ=f'{Tc}{{' + ', '.join(objs) + '}',
                          HDR=' <> '.join(hdrs), HDRL='[' + ', '.join(hdrs) + ']',
                          ALLP=(f'{WS}, +dw{s}: Nat, +T{s}: FD.array__Tree<U32>, +N{s}: U32, +c{s}: Nat,\n'
                                f'    +pfT{s}: {{FD.array__perfect(U32, dw{s}, T{s}) == True{{}} : Bool}}, +hdw{s}: {{Nat.is_lt(dw{s}, 31n) == True{{}} : Bool}},\n'
                                f'    +ec{s}: {{U32.to_nat(N{s}) == VS.x8(c{s}) : Nat}}, +hc{s}: {{Nat.is_le(c{s}, {LIMN}) == True{{}} : Bool}},\n'
                                f'    +hroom{s}: {{Nat.is_le(Nat.add(VC.NW(N{s}), 0n), VB.pw(dw{s})) == True{{}} : Bool}}'),
                          ALLa=f'{WA}, dw{s}, T{s}, N{s}, c{s}, pfT{s}, hdw{s}, ec{s}, hc{s}, hroom{s}',
                          NCa=f'N{s}, c{s}, ec{s}, hc{s}', ST=f'FD.array__slots(U32, T{s})',
                          X=f'Nat.add({H}n, VC.NW(N{s}))'))
    return L, w, sides


def _ae_names(xc, FS, Tp, LIMN, sides):
    """the parent's combined names: parameters, offsets, objects and the trees' words"""
    A_, B_ = sides
    ALLP = A_['ALLP'] + ',\n    ' + B_['ALLP']
    ALLa = A_['ALLa'] + ', ' + B_['ALLa']
    NCP = (f'+N1: U32, +c1: Nat, +ec1: {{U32.to_nat(N1) == VS.x8(c1) : Nat}}, +hc1: {{Nat.is_le(c1, {LIMN}) == True{{}} : Bool}},\n'
           f'    +N2: U32, +c2: Nat, +ec2: {{U32.to_nat(N2) == VS.x8(c2) : Nat}}, +hc2: {{Nat.is_le(c2, {LIMN}) == True{{}} : Bool}}')
    NCa = 'N1, c1, ec1, hc1, N2, c2, ec2, hc2'
    NC = '+N: U32, +c: Nat, +ec: {U32.to_nat(N) == VS.x8(c) : Nat}, +hc: {Nat.is_le(c, ' + LIMN + ') == True{} : Bool}'
    S1, S2 = 'E.SFS(N1)', 'E.SFS(N2)'
    C1, C2 = 'C1(N1)', 'C2(N1, N2)'
    X1, X2 = A_['X'], B_['X']
    P2 = f'Nat.add(2n, {X1})'
    Q = f'Nat.add(2n, Nat.add({X1}, {X2}))'
    XL = f'Nat.add({FS}n, VS.x8({LIMN}))'
    BX1 = f'O.BSome{{{A_["OBJ"]}, O.BNone{{}}}}'
    BX2 = f'O.BSome{{{B_["OBJ"]}, O.BNone{{}}}}'
    OBJ = f'{Tp}{{{BX1}, {BX2}}}'
    TW = f'{A_["WS"]}, +N1: U32, +T1: FD.array__Tree<U32>, {B_["WS"]}, +N2: U32, +T2: FD.array__Tree<U32>'
    TWa = f'{A_["WA"]}, N1, T1, {B_["WA"]}, N2, T2'
    IWl = f'IW{1 + len([f for f in xc.fields if f["kind"] == "fix"])}'
    DO = 'DOA(N1, N2)'
    A1 = 'A1(N1, N2)'
    W1 = f'AW1({TWa})'
    A2 = f'A2({TWa})'
    W2 = f'AW2({TWa})'
    S = f'FD.array__slots(U32, {W2})'
    LT = 'List<&2, U32>'
    M = 'Maybe<&2, +List<U32>>'
    MP = 'Maybe<&2, +List<S.Part>>'
    return X2, A_, B_, ALLP, ALLa, NCP, NCa, NC, S1, S2, C1, C2, X1, P2, Q, XL, BX1, BX2, OBJ, TW, TWa, IWl, DO, A1, W1, A2, W2, S, LT, M, MP


def _ae_object_laws(FS, H, LIMN, PB, P3, KA, KO, X2, BC1, BC2, K_C1, K_C2, K_P1, K_P8, K_Y2, MXB, K_XB, w, A_, B_, NCP, NCa, NC, S1, S2, C1, C2, X1, P2, Q, XL, TW, TWa, IWl, DO, A1, W1, A2):
    """the offsets C1 / C2, the object's trees and the laws of its words"""
    w(TEMPLATES.render('_ae_object_laws', S1=S1, S2=S2, C2=C2, DO=DO, TW=TW, IWl=IWl, A_=A_, A1=A1, W1=W1, C1=C1, B_=B_, A2=A2, P2=P2, NC=NC, XL=XL, FS=FS, LIMN=LIMN, BC1=BC1, K_C1=K_C1, NCP=NCP, BC2=BC2, K_C2=K_C2, NCa=NCa, PB=PB, K_P1=K_P1, K_P8=K_P8, Q=Q, X1=X1, X2=X2, P3=P3, K_Y2=K_Y2, H=H, KO=KO, MXB=MXB, K_XB=K_XB, KA=KA, TWa=TWa))
    # size / put / encode


def _ae_size_put_eval(Tc, Tp, KA, w, A_, B_, ALLP, ALLa, NCa, S1, S2, C1, C2, P2, Q, BX1, BX2, OBJ, TWa, DO, A1, W1, A2, W2):
    """size_eval and put_eval: the runtime's size pass and put against the model"""
    RS = f'({OBJ}, {C2})'
    IT = f'{Tc} & U32'
    w(TEMPLATES.render('_ae_size_put_eval', ALLP=ALLP, Tp=Tp, OBJ=OBJ, RS=RS, IT=IT, Tc=Tc, A_=A_, S1=S1, BX2=BX2, B_=B_, S2=S2, BX1=BX1, C1=C1, C2=C2, NCa=NCa))
    RP = f'(FD.array__thaw(U32, {W2}), {RS})'
    TP = f'Array<U32> & ({Tp} & U32)'
    TPc = f'Array<U32> & ({Tc} & U32)'
    w(TEMPLATES.render('_ae_size_put_eval_2', ALLP=ALLP, Tp=Tp, DO=DO, OBJ=OBJ, RP=RP, TP=TP, NCa=NCa, A1=A1, Q=Q, BX2=BX2, Tc=Tc, BX1=BX1, TPc=TPc, A_=A_, W1=W1, S1=S1, C1=C1, A2=A2, TWa=TWa, B_=B_, W2=W2, S2=S2, P2=P2, C2=C2))
    # zeros
    w(ZD.zeros_at_text(KA, 'FD'))
    RE = f'({OBJ}, B.Buf{{FD.array__thaw(U32, {W2}), {C2}}})'
    TE = f'{Tp} & B.Buf'
    w(TEMPLATES.render('_ae_size_put_eval_3', ALLP=ALLP, Tp=Tp, OBJ=OBJ, RE=RE, TE=TE, RS=RS, ALLa=ALLa, C2=C2, DO=DO, NCa=NCa, TP=TP, RP=RP))
    # windows of the output


def _ae_window_laws(X2, w, A_, B_, ALLP, ALLa, NCa, C1, C2, X1, P2, Q, TWa, DO, A1, W1, A2, W2, S, LT):
    """the windows of the output's words: the two offsets and the two children"""
    def win(m, p, t=W2):
        return f'VF.WIN({m}, {p}, FD.array__slots(U32, {t}))'
    IWc2 = f'{B_["WA"]}, {DO}, {A2}, {P2}, N2, T2, pfA2({TWa}), hd, hR2({NCa})'
    IWc1 = f'{A_["WA"]}, {DO}, {A1}, 2n, N1, T1, pfA1(N1, N2), hd, hR1({NCa})'
    hb2 = f'hQ(2n, {NCa}, {{==}})'
    WT1 = f'VS.wtake(Nat.double(c1), {A_["ST"]})'
    WT2 = f'VS.wtake(Nat.double(c2), {B_["ST"]})'
    RA = f'VF.app({A_["HDRL"]}, {WT1})'
    RBw = f'VF.app({B_["HDRL"]}, {WT2})'
    WPAR = f'{ALLP}'
    hmA = (f'FD.logic__subst(Nat, z => {{Nat.is_le(z, {P2}) == True{{}} : Bool}}, {P2}, Nat.add({X1}, 2n), FD.nat__add_comm(2n, {X1}), '
           f'Order.left_below_sum(0n, {P2}))')
    w(TEMPLATES.render('_ae_window_laws', WPAR=WPAR, win=win, LT=LT, NCa=NCa, A2=A2, IWc2=IWc2, W1=W1, C1=C1, DO=DO, TWa=TWa, hb2=hb2, A1=A1, IWc1=IWc1, X1=X1, RA=RA, hmA=hmA, X2=X2, P2=P2, RBw=RBw))
    Y1 = f'F.limbs({A_["HDR"]} <> {WT1})'
    Y2 = f'F.limbs({B_["HDR"]} <> {WT2})'
    RB = f'List.append(&2, U32, F.limbs([8, {C1}]), List.append(&2, U32, {Y1}, {Y2}))'
    BT = f'VS.bt(U32.to_nat({C2}), F.limbs({S}))'
    AA = f'VF.app([8], [{C1}])'
    BB = f'VF.app({RA}, {RBw})'
    w(f'''# The output's bytes: the two offsets and the two objects' words.
def out_eq({WPAR}) -> {{{BT} == {RB} : +List<U32>}}:
  %eQ({NCa}) : {{VS.bt(_, F.limbs({S})) == {RB} : +List<U32>}}
  %Equal.sym(+List<U32>, VS.bt(A.quad({Q}), F.limbs({S})), F.limbs(VS.wtake({Q}, {S})), VS.bt_limbs({Q}, {S})) : {{_ == {RB} : +List<U32>}}
  %Equal.sym({LT}, {win(Q, "0n")}, VF.app({win("2n", "0n")}, {win(f"Nat.add({X1}, {X2})", "2n")}), VN.win_split2(2n, Nat.add({X1}, {X2}), 0n, {S})) :
    {{F.limbs(_) == {RB} : +List<U32>}}
  %Equal.sym({LT}, {win("Nat.add(1n, 1n)", "0n")}, VF.app({win("1n", "0n")}, {win("1n", "Nat.add(1n, 0n)")}), VN.win_split2(1n, 1n, 0n, {S})) :
    {{F.limbs(VF.app(_, {win(f"Nat.add({X1}, {X2})", "2n")})) == {RB} : +List<U32>}}
  %Equal.sym({LT}, {win(f"Nat.add({X1}, {X2})", "2n")}, VF.app({win(X1, "2n")}, {win(X2, P2)}), VF.win_split({X1}, {X2}, 2n, {S})) :
    {{F.limbs(VF.app(VF.app({win("1n", "0n")}, {win("1n", "1n")}), _)) == {RB} : +List<U32>}}
  %Equal.sym({LT}, {win("1n", "0n")}, [8], w0({ALLa})) :
    {{F.limbs(VF.app(VF.app(_, {win("1n", "1n")}), VF.app({win(X1, "2n")}, {win(X2, P2)}))) == {RB} : +List<U32>}}
  %Equal.sym({LT}, {win("1n", "1n")}, [{C1}], w1({ALLa})) :
    {{F.limbs(VF.app(VF.app([8], _), VF.app({win(X1, "2n")}, {win(X2, P2)}))) == {RB} : +List<U32>}}
  %Equal.sym({LT}, {win(X1, "2n")}, {RA}, wA({ALLa})) :
    {{F.limbs(VF.app({AA}, VF.app(_, {win(X2, P2)}))) == {RB} : +List<U32>}}
  %Equal.sym({LT}, {win(X2, P2)}, {RBw}, wB({ALLa})) :
    {{F.limbs(VF.app({AA}, VF.app({RA}, _))) == {RB} : +List<U32>}}
  %Equal.sym(+List<U32>, F.limbs(VF.app({AA}, {BB})), List.append(&2, U32, F.limbs({AA}), F.limbs({BB})), VF.limbs_app({AA}, {BB})) :
    {{_ == {RB} : +List<U32>}}
  %Equal.sym(+List<U32>, F.limbs({BB}), List.append(&2, U32, F.limbs({RA}), F.limbs({RBw})), VF.limbs_app({RA}, {RBw})) :
    {{List.append(&2, U32, F.limbs({AA}), _) == {RB} : +List<U32>}}
  {{==}}
''')
    # spec
    return RB, BT


def _ae_spec_bytes(parent, n, FS, H, po, hdr, LIMN, YS, FA, K_FA, w, A_, B_, ALLP, ALLa, NCP, NCa, C1, XL, M, MP, RB, BT):
    """the spec side: the bytes of one parent value, its header words and its lists' words"""
    XEa = f'E.XE({A_["WA"]}, c1, W1)'
    XEb = f'E.XE({B_["WA"]}, c2, W2)'
    VT = lambda s: f'VS.wtake(Nat.double(c{s}), W{s})'  # noqa: E731
    y1 = f'YY({A_["WA"]}, c1, W1)'
    y2 = f'YY({B_["WA"]}, c2, W2)'
    wsY = ', '.join(f'+w{k}: U32' for k in range(H) if k != po)
    hdrY = ' <> '.join(hdr)
    RBs = f'List.append(&2, U32, F.limbs([8, {C1}]), List.append(&2, U32, {y1}, {y2}))'
    RBe = f'List.append(&2, U32, List.append(&2, U32, N.digits(4n, 8n), I.limb({C1})), List.append(&2, U32, {y1}, {y2}))'
    PLs = f'[S.Variable{{{y1}}}, S.Variable{{{y2}}}]'
    VALs = f'S.Sequence{{S.Items{{{XEa}, S.Items{{{XEb}, S.EmptyItems{{}}}}}}}}'
    OUTL = f'List.append(&2, U32, Layout.fixed_parts({PLs}, Layout.fixed_size({PLs})), Layout.payloads({PLs}))'
    FITS = f'N.fits(4n, Nat.add(Layout.fixed_size({PLs}), List.length(&2, U32, Layout.payloads({PLs}))))'
    SPP = (f'{A_["WS"]}, {B_["WS"]}, {NCP},\n    +W1: List<&2, U32>, +W2: List<&2, U32>,\n'
           '    +hl1: {Nat.is_le(Nat.double(c1), FD.spec_common__length(U32, W1)) == True{} : Bool}, +hl2: {Nat.is_le(Nat.double(c2), FD.spec_common__length(U32, W2)) == True{} : Bool}')
    SPa = f'{A_["WA"]}, {B_["WA"]}, {NCa}, W1, W2, hl1, hl2'
    YB = XL
    w(TEMPLATES.render('_ae_spec_bytes', n=n, wsY=wsY, hdrY=hdrY, YS=YS, A_=A_, B_=B_, VALs=VALs, SPP=SPP, y1=y1, y2=y2, FS=FS, FA=FA, LIMN=LIMN, K_FA=K_FA, C1=C1, SPa=SPa, XEa=XEa, XEb=XEb, PLs=PLs, MP=MP, RBe=RBe, M=M, VT=VT, parent=parent, RBs=RBs, ALLP=ALLP, BT=BT, RB=RB, NCa=NCa, ALLa=ALLa))
    # eC1x: to_nat(C1) == 8 + (FS + x8 c1)


def as_enc_text(g, xc, parent='AttesterSlashing'):
    n, FS, H, po, Tc, Tp, hdr, LIMN, YS, PB, P3, KA, KO, FA, BC1, BC2, K_C1, K_C2, K_P1, K_P8, K_Y2, MXB, K_XB, K_FA = _ae_limits(g, xc, parent)
    L, w, sides = _ae_sides(g, xc, parent, n, H, po, Tc, hdr, LIMN)
    X2, A_, B_, ALLP, ALLa, NCP, NCa, NC, S1, S2, C1, C2, X1, P2, Q, XL, BX1, BX2, OBJ, TW, TWa, IWl, DO, A1, W1, A2, W2, S, LT, M, MP = _ae_names(xc, FS, Tp, LIMN, sides)
    _ae_object_laws(FS, H, LIMN, PB, P3, KA, KO, X2, BC1, BC2, K_C1, K_C2, K_P1, K_P8, K_Y2, MXB, K_XB, w, A_, B_, NCP, NCa, NC, S1, S2, C1, C2, X1, P2, Q, XL, TW, TWa, IWl, DO, A1, W1, A2)
    _ae_size_put_eval(Tc, Tp, KA, w, A_, B_, ALLP, ALLa, NCa, S1, S2, C1, C2, P2, Q, BX1, BX2, OBJ, TWa, DO, A1, W1, A2, W2)
    RB, BT = _ae_window_laws(X2, w, A_, B_, ALLP, ALLa, NCa, C1, C2, X1, P2, Q, TWa, DO, A1, W1, A2, W2, S, LT)
    _ae_spec_bytes(parent, n, FS, H, po, hdr, LIMN, YS, FA, K_FA, w, A_, B_, ALLP, ALLa, NCP, NCa, C1, XL, M, MP, RB, BT)
    ex = (TEMPLATES.render('as_enc_text', LIMN=LIMN, C1=C1, FS=FS, S1=S1))
    txt = '\n'.join(L) + '\n'
    i = txt.index('def VAL(')
    return txt[:i] + ex + '\n' + txt[i:]
