#!/usr/bin/env python3
"""The unaligned-offset layer: the runtime's word reads and copies at any byte
offset, related to the buffer's spec bytes.

    python3 codegen/proofs/var/unaligned_read_laws.py [--check]

proofs/obj/vua_bits.bend (generated here, stock): the byte structure of the
runtime's unaligned word join B.join_sel(j, lo, hi) (j = 1, 2, 3): its four
limbs are the last 4 - j limbs of lo followed by the first j limbs of hi. The
proofs compute each output bit symbolically (a simulator of Word.and/or/shift
below) and close every position with one of five one-bit lemmas; no case
split over the words' bits is needed.

proofs/obj/vua.bend (hand-written, stock) builds U1 on it: B.read32 at any
byte offset returns a word whose limbs are the buffer's spec bytes there.

proofs/obj/vua_ci<s>_generated.bend (s = 0..3; manual audit round 13,
s01-copy/09, /10): O.copy_in, the decoder of every byte range, on a literal
buffer of 32 marked bytes at the offsets s and 4 + s and every length 1 to 9:
the copy's length and words are the source bytes shifted to byte 0, the rest
zero (laws ci_o<off>_n<n>, by computation). vcopy.bend proves copy_in for a
word-aligned range only; these pin the dispatch on off & 3.
"""
import sys as _sys
import pathlib as _pathlib
_sys.path.insert(0, str(_pathlib.Path(__file__).resolve().parents[3]))  # the repository root: `codegen` is importable when this file runs as a script
import sys

from codegen.core.repository_paths import ROOT  # noqa: E402
OUT = ROOT / 'proofs/obj/vua_bits.bend'
OUT_SC = ROOT / 'proofs/obj/vua_sc.bend'
OUT_FIX = ROOT / 'proofs/obj/vua_fix.bend'
# The fixed-size types read at any byte offset (with their fixed-size parts).
FIX_ROOTS = ['Attestation', 'IndexedAttestation', 'SignedVoluntaryExit', 'SignedBLSToExecutionChange', 'SyncAggregate', 'Eth1Data',
             'DepositRequest', 'WithdrawalRequest', 'ConsolidationRequest', 'Withdrawal', 'BeaconBlockBody',
             'HistoricalSummary', 'PendingDeposit', 'PendingPartialWithdrawal', 'PendingConsolidation']

F_, T_ = 'False{}', 'True{}'


def const(v):
    return [T_ if (v >> i) & 1 else F_ for i in range(32)]


def b_and(x, y):
    if x == T_:
        return y
    if x == F_:
        return F_
    return f'Bool.and({x}, {y})'


def b_or(x, y):
    if x == T_:
        return T_
    if x == F_:
        return y
    return f'Bool.or({x}, {y})'


def w_and(xs, ys):
    return [b_and(x, y) for x, y in zip(xs, ys)]


def w_or(xs, ys):
    return [b_or(x, y) for x, y in zip(xs, ys)]


def shrn(xs, k):
    return xs[k:] + [F_] * k


def shln(xs, k):
    return [F_] * k + xs[:32 - k]


def limb(xs):
    return [w_and(xs, const(255)), w_and(shrn(xs, 8), const(255)), w_and(shrn(xs, 16), const(255)), shrn(xs, 24)]


def join_sel(j, lo, hi):
    return w_or(shrn(lo, 8 * j), shln(hi, 32 - 8 * j))


def word(bs):
    return 'U32{' + ''.join(f'WCon{{{b}, ' for b in bs) + 'WNil{}' + '}' * len(bs) + '}'


def canon(bits8):
    return bits8 + [F_] * 24


def pos_proof(x, y):
    """A proof of {x == y : Bool} for one position (y is a variable or False)."""
    if x == y:
        return '{==}'
    for name, pat in [('p1', 'Bool.and(Bool.or({a}, False{{}}), True{{}})'), ('p2', 'Bool.and(Bool.or({a}, False{{}}), False{{}})'),
                      ('p3', 'Bool.and({a}, True{{}})'), ('p4', 'Bool.and({a}, False{{}})'), ('p5', 'Bool.or({a}, False{{}})')]:
        for a in [f'a{i}' for i in range(32)] + [f'b{i}' for i in range(32)]:
            if x == pat.format(a=a):
                return f'{name}({a})'
    raise ValueError(f'no position lemma for {x} == {y}')


A = [f'a{i}' for i in range(32)]
Bv = [f'b{i}' for i in range(32)]


def emit():
    L = ['import Base', 'import ../../src/buffer.bend as B', 'import ../../src/primitives.bend as I', '',
         '# GENERATED by unaligned_read_laws (codegen). Do not edit.',
         '# The limbs of the runtime\'s unaligned word join (see the module docstring', '# of codegen/proofs/var/unaligned_read_laws.py).', '']
    w = L.append
    for name, lhs, rhs in [('p1', 'Bool.and(Bool.or(a, False{}), True{})', 'a'), ('p2', 'Bool.and(Bool.or(a, False{}), False{})', 'False{}'),
                           ('p3', 'Bool.and(a, True{})', 'a'), ('p4', 'Bool.and(a, False{})', 'False{}'), ('p5', 'Bool.or(a, False{})', 'a')]:
        w(f'def {name}(+a: Bool) -> {{{lhs} == {rhs} : Bool}}:')
        w('  match a:')
        w('    case True{}: {==}')
        w('    case False{}: {==}')
        w('')
    xs = [f'x{i}' for i in range(32)]
    ys = [f'y{i}' for i in range(32)]
    w('# Two words with equal bits are equal.')
    w('def weq(' + ', '.join(f'+{v}: Bool' for v in xs + ys) + ', ' + ', '.join(f'+e{i}: {{x{i} == y{i} : Bool}}' for i in range(32)) + ')')
    w(f'    -> {{{word(xs)} == {word(ys)} : U32}}:')
    for i in range(32):
        cur = ys[:i] + ['_'] + xs[i + 1:]
        w(f'  %Equal.sym(Bool, x{i}, y{i}, e{i}) : {{{word(cur)} == {word(ys)} : U32}}')
    w('  {==}')
    w('')
    w('def l4(+x0: U32, +x1: U32, +x2: U32, +x3: U32, +y0: U32, +y1: U32, +y2: U32, +y3: U32,')
    w('    +e0: {x0 == y0 : U32}, +e1: {x1 == y1 : U32}, +e2: {x2 == y2 : U32}, +e3: {x3 == y3 : U32}) -> {[x0, x1, x2, x3] == [y0, y1, y2, y3] : List<&2, U32>}:')
    w('  %Equal.sym(U32, x0, y0, e0) : {[_, x1, x2, x3] == [y0, y1, y2, y3] : List<&2, U32>}')
    w('  %Equal.sym(U32, x1, y1, e1) : {[y0, _, x2, x3] == [y0, y1, y2, y3] : List<&2, U32>}')
    w('  %Equal.sym(U32, x2, y2, e2) : {[y0, y1, _, x3] == [y0, y1, y2, y3] : List<&2, U32>}')
    w('  %Equal.sym(U32, x3, y3, e3) : {[y0, y1, y2, _] == [y0, y1, y2, y3] : List<&2, U32>}')
    w('  {==}')
    w('')

    def weq_call(xbits, ybits):
        return 'weq(' + ', '.join(xbits + ybits) + ', ' + ', '.join(pos_proof(x, y) for x, y in zip(xbits, ybits)) + ')'

    def canon_list(words_bits):
        return '[' + ', '.join(word(b) for b in words_bits) + ']'

    WL = word(A)
    WH = word(Bv)
    bytes_lo = [canon(A[8 * k:8 * k + 8]) for k in range(4)]
    bytes_hi = [canon(Bv[8 * k:8 * k + 8]) for k in range(4)]
    # the limbs of a word, canonically
    lb = limb(A)
    w('# The limbs of a word are its four bytes.')
    w('def limbC(' + ', '.join(f'+{v}: Bool' for v in A) + f') -> {{I.limb({WL}) == {canon_list(bytes_lo)} : List<&2, U32>}}:')
    w('  l4(' + ', '.join(word(b) for b in lb) + ', ' + ', '.join(word(b) for b in bytes_lo) + ', '
      + ', '.join(weq_call(lb[k], bytes_lo[k]) for k in range(4)) + ')')
    w('')
    for j in (1, 2, 3):
        js = join_sel(j, A, Bv)
        lj = limb(js)
        target = bytes_lo[j:] + bytes_hi[:j]
        w(f'def joinC{j}(' + ', '.join(f'+{v}: Bool' for v in A + Bv) + f') -> {{I.limb(B.join_sel({j}, {WL}, {WH})) == {canon_list(target)} : List<&2, U32>}}:')
        w('  l4(' + ', '.join(word(b) for b in lj) + ', ' + ', '.join(word(b) for b in target) + ', '
          + ', '.join(weq_call(lj[k], target[k]) for k in range(4)) + ')')
        w('')
    # over words
    pat_lo = 'U32{' + ''.join(f'WCon{{+{a}, ' for a in A) + 'WNil{}' + '}' * 32 + '}'
    pat_hi = 'U32{' + ''.join(f'WCon{{+{b}, ' for b in Bv) + 'WNil{}' + '}' * 32 + '}'
    for j in (1, 2, 3):
        rhs = ', '.join([f'I.at(I.limb(lo), {k}n)' for k in range(j, 4)] + [f'I.at(I.limb(hi), {k}n)' for k in range(j)])
        w(f'# The limbs of the join at byte {j}: limbs {j}..3 of lo, then limbs 0..{j - 1} of hi.')
        w(f'law join{j}:')
        w('  for +lo: U32')
        w('  for +hi: U32')
        w(f'  {{I.limb(B.join_sel({j}, lo, hi)) == [{rhs}] : List<&2, U32>}}')
        w(f'def join{j}(lo, hi):')
        w('  match lo hi:')
        w(f'    case {pat_lo} {pat_hi}:')
        rw = f'[{", ".join([f"I.at(I.limb({WL}), {k}n)" for k in range(j, 4)] + [f"I.at(I.limb({WH}), {k}n)" for k in range(j)])}]'
        w(f'      %Equal.sym(List<&2, U32>, I.limb({WL}), {canon_list(bytes_lo)}, limbC({", ".join(A)})) :')
        w(f'        {{I.limb(B.join_sel({j}, {WL}, {WH})) == [{", ".join([f"I.at(_, {k}n)" for k in range(j, 4)] + [f"I.at(I.limb({WH}), {k}n)" for k in range(j)])}] : List<&2, U32>}}')
        limbC_b = 'limbC(' + ', '.join(Bv) + ')'
        w(f'      %Equal.sym(List<&2, U32>, I.limb({WH}), {canon_list(bytes_hi)}, {limbC_b}) :')
        inner = [f'I.at({canon_list(bytes_lo)}, {k}n)' for k in range(j, 4)] + [f'I.at(_, {k}n)' for k in range(j)]
        w(f'        {{I.limb(B.join_sel({j}, {WL}, {WH})) == [{", ".join(inner)}] : List<&2, U32>}}')
        w(f'      joinC{j}(' + ', '.join(A + Bv) + ')')
        w('')
    return '\n'.join(L) + '\n'


MULS = {1: 16777216, 2: 65536, 3: 256}

TH = 'F.array__thaw(U32, {})'


def nk(k, v):
    """The Nat k + v as the checker normalises it."""
    return v if k == 0 else f'{k}n+{v}'


def emit_sc():
    L = ['import Base', 'import ../../src/buffer.bend as B', 'import ../../src/obj.bend as O', 'import ../compact/found.bend as F', 'import ../../proofs/nat_order.bend as Order',
         'import ./vspec.bend as VS', 'import ./vbuf.bend as VB', 'import ./vcopy.bend as VC', 'import ./vbytes.bend as VBY', 'import ./word_mul.bend as WM',
         'import ./vua_copy.bend as UC', '',
         '# GENERATED by unaligned_read_laws (codegen). Do not edit.',
         '# U2 loops: the runtime\'s shifted copies O.scopy1/2/3 build UC.smone (see', '# proofs/obj/vua_copy.bend).', '']
    w = L.append
    ST = 'Array<U32> & (Array<U32> & U32)'
    hyps = ('+ea: {U32.to_nat(a) == i : Nat}, +eb: {U32.to_nat(b) == j : Nat},\n'
            '    +hdd: {Nat.is_lt(dd, 31n) == True{} : Bool}, +hds: {Nat.is_lt(ds, 31n) == True{} : Bool}')
    pfs = '+pfD: {F.array__perfect(U32, dd, D) == True{} : Bool}, +pfS: {F.array__perfect(U32, ds, S) == True{} : Bool}'
    for s in (1, 2, 3):
        M = MULS[s]
        sh = 8 * s
        up = 32 - sh

        def RS(k):
            return f'UC.RS(ds, S, {nk(k, "i")})'

        def V(k, cur):
            # the runtime's word k, with its product (cur = the product or a hole)
            return f'U32.or(U32.shrn({RS(k)}, {sh}n), {cur})'

        def mulrw(k, motive):
            return (f'  %Equal.sym(U32, U32.mul({RS(k + 1)}, {M}), U32.shln({RS(k + 1)}, {up}n), WM.mul{M}({RS(k + 1)})) :\n'
                    f'    {motive}')
        pre = f'sc{s}'
        w(f'# ---- byte {s} ' + '-' * 80)
        w('')
        for k in range(7, -1, -1):
            n = 8 - k
            rhs = f'({TH.format(f"UC.smone({s}n, {n}n, {nk(k, "i")}, {nk(k, "j")}, dd, ds, D, S)")}, ({TH.format("S")}, {RS(8)}))'
            w(f'def {pre}c{k}(+a: U32, +b: U32, +i: Nat, +j: Nat, +dd: Nat, +ds: Nat, +D: F.array__Tree<U32>, +S: F.array__Tree<U32>,')
            w(f'    {hyps},')
            w('    +hi: {Nat.is_le(8n+i, VB.pw(ds)) == True{} : Bool}, +hj: {Nat.is_lt(7n+j, VB.pw(dd)) == True{} : Bool},')
            w(f'    {pfs})')
            w(f'    -> {{O.{pre}_c{k}(a, b, {RS(k)}, {TH.format("D")}, ({TH.format("S")}, {RS(k + 1)})) == {rhs} : {ST}}}:')
            Vk = V(k, f'U32.shln({RS(k + 1)}, {up}n)')
            setlt = f'F.nat__le_lt_trans(Nat.add({k}n, j), 7n+j, VB.pw(dd), Order.left_below_sum({7 - k}n, j), hj)'
            setrw = (f'  %Equal.sym(Array<U32>, Array.set(U32, {TH.format("D")}, U32.add(b, {k}), {Vk}), {TH.format(f"F.array__upd(U32, dd, D, {nk(k, "j")}, {Vk})")},\n'
                     f'      VB.set_at(dd, D, b, {k}, j, {Vk}, eb, VB.lt32(dd, hdd), {setlt}, pfD)) :\n')
            D1 = f'F.array__upd(U32, dd, D, {nk(k, "j")}, {Vk})'
            if k == 7:
                w(mulrw(k, f'{{(Array.set(U32, {TH.format("D")}, U32.add(b, 7), {V(k, "_")}), ({TH.format("S")}, {RS(8)})) == {rhs} : {ST}}}'))
                w(setrw + f'    {{(_, ({TH.format("S")}, {RS(8)})) == {rhs} : {ST}}}')
                w('  {==}')
            else:
                get = f'Array.get(U32, {TH.format("S")}, U32.add(a, {k + 2}))'
                w(mulrw(k, f'{{O.{pre}_c{k + 1}(a, b, {RS(k + 1)}, Array.set(U32, {TH.format("D")}, U32.add(b, {k}), {V(k, "_")}), {get}) == {rhs} : {ST}}}'))
                w(setrw + f'    {{O.{pre}_c{k + 1}(a, b, {RS(k + 1)}, _, {get}) == {rhs} : {ST}}}')
                le = f'F.nat__le_trans({nk(k + 2, "i")}, 8n+i, VB.pw(ds), Order.left_below_sum({6 - k}n, i), hi)' if k < 6 else 'hi'
                w(f'  %Equal.sym(Array<U32> & U32, {get}, ({TH.format("S")}, {RS(k + 2)}),')
                w(f'      UC.get_rs(ds, S, U32.add(a, {k + 2}), {nk(k + 2, "i")}, VB.add_le_at(a, {k + 2}, i, ds, ea, hds, {le}), VB.lt32(ds, hds), {le}, pfS)) :')
                w(f'    {{O.{pre}_c{k + 1}(a, b, {RS(k + 1)}, {TH.format(D1)}, _) == {rhs} : {ST}}}')
                w(f'  {pre}c{k + 1}(a, b, i, j, dd, ds, {D1}, S, ea, eb, hdd, hds, hi, hj, F.array__upd_perfect(U32, dd, D, {nk(k, "j")}, {Vk}, pfD), pfS)')
            w('')
        # the eight-word loop
        R0 = '(' + TH.format('D') + ', (' + TH.format('S') + ', UC.RS(ds, S, i)))'
        w(f'# The eight-word loop at byte {s} writes 8k words.')
        w(f'law {pre}blk:')
        for v, t in [('k', 'Nat'), ('a', 'U32'), ('b', 'U32'), ('i', 'Nat'), ('j', 'Nat'), ('dd', 'Nat'), ('ds', 'Nat'), ('D', 'F.array__Tree<U32>'), ('S', 'F.array__Tree<U32>')]:
            w(f'  for +{v}: {t}')
        for h in ['ea: {U32.to_nat(a) == i : Nat}', 'eb: {U32.to_nat(b) == j : Nat}', 'hdd: {Nat.is_lt(dd, 31n) == True{} : Bool}', 'hds: {Nat.is_lt(ds, 31n) == True{} : Bool}',
                  'hi: {Nat.is_le(Nat.add(VS.x8(k), i), VB.pw(ds)) == True{} : Bool}', 'hj: {Nat.is_le(Nat.add(VS.x8(k), j), VB.pw(dd)) == True{} : Bool}',
                  'pfD: {F.array__perfect(U32, dd, D) == True{} : Bool}', 'pfS: {F.array__perfect(U32, ds, S) == True{} : Bool}']:
            w(f'  for +{h}')
        brhs = lambda K: f'({TH.format(f"UC.smone({s}n, VS.x8({K}), i, j, dd, ds, D, S)")}, ({TH.format("S")}, UC.RS(ds, S, Nat.add(VS.x8({K}), i))))'
        w(f'  {{O.{pre}_blk(k, a, b, {R0}) == {brhs("k")} : {ST}}}')
        w(f'def {pre}blk(k, a, b, i, j, dd, ds, D, S, ea, eb, hdd, hds, hi, hj, pfD, pfS):')
        w('  match k:')
        w('    case 0n: {==}')
        w('    case 1n+ +t:')
        M8 = f'UC.smone({s}n, 8n, i, j, dd, ds, D, S)'
        get1 = f'Array.get(U32, {TH.format("S")}, U32.add(a, 1))'
        g = 'O.' + pre + '_blk(t, U32.add(a, 8), U32.add(b, 8), {})'
        w(f'      +h8 = VB.le8_head(VS.x8(t), i, VB.pw(ds), hi)')
        w(f'      +h1 = F.nat__le_trans(1n+i, 8n+i, VB.pw(ds), Order.left_below_sum(7n, i), h8)')
        w(f'      %Equal.sym(Array<U32> & U32, {get1}, ({TH.format("S")}, UC.RS(ds, S, 1n+i)), UC.get_rs(ds, S, U32.add(a, 1), 1n+i, VB.add_le_at(a, 1, i, ds, ea, hds, h1), VB.lt32(ds, hds), h1, pfS)) :')
        w(f'        {{{g.format(f"O.{pre}_c0(a, b, UC.RS(ds, S, i), {TH.format(chr(68))}, _)")} == {brhs("1n+t")} : {ST}}}')
        c0res = f'({TH.format(M8)}, ({TH.format("S")}, UC.RS(ds, S, 8n+i)))'
        w(f'      %Equal.sym({ST}, O.{pre}_c0(a, b, UC.RS(ds, S, i), {TH.format("D")}, ({TH.format("S")}, UC.RS(ds, S, 1n+i))), {c0res},')
        w(f'          {pre}c0(a, b, i, j, dd, ds, D, S, ea, eb, hdd, hds, h8, VB.lt8(7n, VS.x8(t), j, VB.pw(dd), {{==}}, hj), pfD, pfS)) :')
        w(f'        {{{g.format("_")} == {brhs("1n+t")} : {ST}}}')
        w(f'      %F.lru_nat_algebra__add_swap(VS.x8(t), 8n, i) :')
        w(f'        {{{g.format(c0res)} == ({TH.format(f"UC.smone({s}n, VS.x8(1n+t), i, j, dd, ds, D, S)")}, ({TH.format("S")}, UC.RS(ds, S, _))) : {ST}}}')
        w(f'      {pre}blk(t, U32.add(a, 8), U32.add(b, 8), 8n+i, 8n+j, dd, ds, {M8}, S,')
        w(f'        VB.add_le_at(a, 8, i, ds, ea, hds, h8),')
        w(f'        VB.add_le_at(b, 8, j, dd, eb, hdd, VB.le8_head(VS.x8(t), j, VB.pw(dd), hj)),')
        w(f'        hdd, hds, VB.le8_shift(VS.x8(t), i, VB.pw(ds), hi), VB.le8_shift(VS.x8(t), j, VB.pw(dd), hj),')
        w(f'        UC.smone_perfect({s}n, 8n, i, j, dd, ds, D, S, pfD), pfS)')
        w('')
        # the one-word loop
        w(f'# The one-word loop at byte {s} writes k words.')
        w(f'law {pre}tail:')
        for v, t in [('k', 'Nat'), ('a', 'U32'), ('b', 'U32'), ('i', 'Nat'), ('j', 'Nat'), ('dd', 'Nat'), ('ds', 'Nat'), ('D', 'F.array__Tree<U32>'), ('S', 'F.array__Tree<U32>')]:
            w(f'  for +{v}: {t}')
        for h in ['ea: {U32.to_nat(a) == i : Nat}', 'eb: {U32.to_nat(b) == j : Nat}', 'hdd: {Nat.is_lt(dd, 31n) == True{} : Bool}', 'hds: {Nat.is_lt(ds, 31n) == True{} : Bool}',
                  'hi: {Nat.is_le(Nat.add(k, i), VB.pw(ds)) == True{} : Bool}', 'hj: {Nat.is_le(Nat.add(k, j), VB.pw(dd)) == True{} : Bool}',
                  'pfD: {F.array__perfect(U32, dd, D) == True{} : Bool}', 'pfS: {F.array__perfect(U32, ds, S) == True{} : Bool}']:
            w(f'  for +{h}')
        trhs = lambda K: f'({TH.format(f"UC.smone({s}n, {K}, i, j, dd, ds, D, S)")}, ({TH.format("S")}, UC.RS(ds, S, Nat.add({K}, i))))'
        w(f'  {{O.{pre}_tail(k, a, b, {R0}) == {trhs("k")} : {ST}}}')
        w(f'def {pre}tail(k, a, b, i, j, dd, ds, D, S, ea, eb, hdd, hds, hi, hj, pfD, pfS):')
        w('  match k:')
        w('    case 0n: {==}')
        w('    case 1n+ +t:')
        W0 = f'U32.or(U32.shrn(UC.RS(ds, S, i), {sh}n), U32.shln(UC.RS(ds, S, 1n+i), {up}n))'
        D1 = f'F.array__upd(U32, dd, D, j, {W0})'
        gt = 'O.' + pre + '_tail(t, U32.add(a, 1), U32.add(b, 1), {})'
        w(f'      +h1 = VB.le1_next(t, i, VB.pw(ds), hi)')
        w(f'      %Equal.sym(Array<U32> & U32, {get1}, ({TH.format("S")}, UC.RS(ds, S, 1n+i)), UC.get_rs(ds, S, U32.add(a, 1), 1n+i, VB.add_le_at(a, 1, i, ds, ea, hds, h1), VB.lt32(ds, hds), h1, pfS)) :')
        w(f'        {{{gt.format(f"O.{pre}_w(b, UC.RS(ds, S, i), {TH.format(chr(68))}, _)")} == {trhs("1n+t")} : {ST}}}')
        w(f'      %Equal.sym(U32, U32.mul(UC.RS(ds, S, 1n+i), {M}), U32.shln(UC.RS(ds, S, 1n+i), {up}n), WM.mul{M}(UC.RS(ds, S, 1n+i))) :')
        w(f'        {{{gt.format(f"(Array.set(U32, {TH.format(chr(68))}, b, U32.or(U32.shrn(UC.RS(ds, S, i), {sh}n), _)), ({TH.format(chr(83))}, UC.RS(ds, S, 1n+i)))")} == {trhs("1n+t")} : {ST}}}')
        w(f'      %Equal.sym(Array<U32>, Array.set(U32, {TH.format("D")}, b, {W0}), {TH.format(D1)},')
        w(f'          VB.set_n(dd, D, b, j, {W0}, eb, VB.lt32(dd, hdd), VB.le1_head(t, j, VB.pw(dd), hj), pfD)) :')
        w(f'        {{{gt.format(f"(_, ({TH.format(chr(83))}, UC.RS(ds, S, 1n+i)))")} == {trhs("1n+t")} : {ST}}}')
        w(f'      %F.nat__add_succ(t, i) :')
        w(f'        {{{gt.format(f"({TH.format(D1)}, ({TH.format(chr(83))}, UC.RS(ds, S, 1n+i)))")} == ({TH.format(f"UC.smone({s}n, 1n+t, i, j, dd, ds, D, S)")}, ({TH.format("S")}, UC.RS(ds, S, _))) : {ST}}}')
        w(f'      {pre}tail(t, U32.add(a, 1), U32.add(b, 1), 1n+i, 1n+j, dd, ds, {D1}, S,')
        w(f'        VB.add_le_at(a, 1, i, ds, ea, hds, h1),')
        w(f'        VB.add_le_at(b, 1, j, dd, eb, hdd, VB.le1_next(t, j, VB.pw(dd), hj)),')
        w(f'        hdd, hds, VB.le1_shift(t, i, VB.pw(ds), hi), VB.le1_shift(t, j, VB.pw(dd), hj),')
        w(f'        F.array__upd_perfect(U32, dd, D, j, {W0}, pfD), pfS)')
        w('')
        # the whole copy
        w(f'# The shifted copy at byte {s} writes nw words.')
        w(f'law scopy{s}_ok:')
        for v, t in [('nw', 'U32'), ('a', 'U32'), ('b', 'U32'), ('i', 'Nat'), ('j', 'Nat'), ('dd', 'Nat'), ('ds', 'Nat'), ('D', 'F.array__Tree<U32>'), ('S', 'F.array__Tree<U32>')]:
            w(f'  for +{v}: {t}')
        for h in ['ea: {U32.to_nat(a) == i : Nat}', 'eb: {U32.to_nat(b) == j : Nat}', 'hdd: {Nat.is_lt(dd, 31n) == True{} : Bool}', 'hds: {Nat.is_lt(ds, 31n) == True{} : Bool}',
                  'hi: {Nat.is_le(Nat.add(U32.to_nat(nw), i), VB.pw(ds)) == True{} : Bool}', 'hj: {Nat.is_le(Nat.add(U32.to_nat(nw), j), VB.pw(dd)) == True{} : Bool}',
                  'pfD: {F.array__perfect(U32, dd, D) == True{} : Bool}', 'pfS: {F.array__perfect(U32, ds, S) == True{} : Bool}']:
            w(f'  for +{h}')
        TD, TS = TH.format('D'), TH.format('S')
        fin = f'({TH.format(f"UC.smone({s}n, U32.to_nat(nw), i, j, dd, ds, D, S)")}, {TS})'
        w(f'  {{O.scopy{s}(nw, a, b, {TD}, {TS}) == {fin} : Array<U32> & Array<U32>}}')
        w(f'def scopy{s}_ok(nw, a, b, i, j, dd, ds, D, S, ea, eb, hdd, hds, hi, hj, pfD, pfS):')
        w('  +q = U32.to_nat(U32.shrn(nw, 3n))')
        w('  +A = VS.x8(q)')
        w('  +r = U32.to_nat(U32.and(nw, 7))')
        w('  +sp = VB.split8(nw)')
        w('  +hi2 = F.logic__subst(Nat, z => {Nat.is_le(Nat.add(z, i), VB.pw(ds)) == True{} : Bool}, U32.to_nat(nw), Nat.add(A, r), sp, hi)')
        w('  +hj2 = F.logic__subst(Nat, z => {Nat.is_le(Nat.add(z, j), VB.pw(dd)) == True{} : Bool}, U32.to_nat(nw), Nat.add(A, r), sp, hj)')
        w('  +hi0 = F.nat__le_trans(i, Nat.add(U32.to_nat(nw), i), VB.pw(ds), Order.left_below_sum(U32.to_nat(nw), i), hi)')
        w(f'  +M = UC.smone({s}n, A, i, j, dd, ds, D, S)')
        ra = 'U32.sub(U32.add(a, nw), U32.and(nw, 7))'
        rb = 'U32.sub(U32.add(b, nw), U32.and(nw, 7))'
        tl = 'O.sc_drop(O.' + pre + '_tail(r, ' + ra + ', ' + rb + ', {}))'
        bl = 'O.' + pre + '_blk(q, a, b, {})'
        w(f'  %Equal.sym(Array<U32> & U32, Array.get(U32, {TS}, a), ({TS}, UC.RS(ds, S, i)), UC.get_rs(ds, S, a, i, ea, VB.lt32(ds, hds), hi0, pfS)) :')
        w(f'    {{{tl.format(bl.format(f"O.sc_first({TD}, _)"))} == {fin} : Array<U32> & Array<U32>}}')
        bres = f'({TH.format("M")}, ({TS}, UC.RS(ds, S, Nat.add(A, i))))'
        w(f'  %Equal.sym({ST}, {bl.format(f"({TD}, ({TS}, UC.RS(ds, S, i)))")}, {bres},')
        w(f'      {pre}blk(q, a, b, i, j, dd, ds, D, S, ea, eb, hdd, hds, VB.le_add_r(A, r, i, VB.pw(ds), hi2), VB.le_add_r(A, r, j, VB.pw(dd), hj2), pfD, pfS)) :')
        w(f'    {{{tl.format("_")} == {fin} : Array<U32> & Array<U32>}}')
        tres = f'({TH.format(f"UC.smone({s}n, r, Nat.add(A, i), Nat.add(A, j), dd, ds, M, S)")}, ({TS}, UC.RS(ds, S, Nat.add(r, Nat.add(A, i)))))'
        w(f'  %Equal.sym({ST}, O.{pre}_tail(r, {ra}, {rb}, {bres}), {tres},')
        w(f'      {pre}tail(r, {ra}, {rb}, Nat.add(A, i), Nat.add(A, j), dd, ds, M, S,')
        w(f'        VB.rest_at(a, nw, i, ds, ea, hds, hi), VB.rest_at(b, nw, j, dd, eb, hdd, hj), hdd, hds,')
        w(f'        VB.le_add_rot(A, r, i, VB.pw(ds), hi2), VB.le_add_rot(A, r, j, VB.pw(dd), hj2), UC.smone_perfect({s}n, A, i, j, dd, ds, D, S, pfD), pfS)) :')
        w(f'    {{O.sc_drop(_) == {fin} : Array<U32> & Array<U32>}}')
        w(f'  %Equal.sym(Nat, U32.to_nat(nw), Nat.add(A, r), sp) :')
        w(f'    {{({TH.format(f"UC.smone({s}n, r, Nat.add(A, i), Nat.add(A, j), dd, ds, M, S)")}, {TS}) == ({TH.format(f"UC.smone({s}n, _, i, j, dd, ds, D, S)")}, {TS}) : Array<U32> & Array<U32>}}')
        w(f'  %UC.smone_add({s}n, A, r, i, j, dd, ds, D, S) :')
        w(f'    {{({TH.format(f"UC.smone({s}n, r, Nat.add(A, i), Nat.add(A, j), dd, ds, M, S)")}, {TS}) == ({TH.format("_")}, {TS}) : Array<U32> & Array<U32>}}')
        w('  {==}')
        w('')
        # copy_in at byte s
        BUF = 'B.Buf{F.array__thaw(U32, t), n}'
        Mo = f'UC.smone({s}n, VC.NW(L), i, 0n, dz, d, VC.ZT(dz), t)'
        RES = f'({BUF}, O.Words{{F.array__thaw(U32, VBY.MK(L, dz, {Mo})), L}})'
        HY = ['+pf: {F.array__perfect(U32, d, t) == True{} : Bool}', '+hd: {Nat.is_lt(d, 31n) == True{} : Bool}', '+hdz: {Nat.is_lt(dz, 31n) == True{} : Bool}']
        HY2 = [f'+h3: {{U32.and(off, 3) == {s} : U32}}', '+ei: {U32.to_nat(U32.shrn(off, 2n)) == i : Nat}',
               '+hs: {Nat.is_le(Nat.add(VC.NW(L), i), VB.pw(d)) == True{} : Bool}', '+hr: {Nat.is_le(Nat.add(VC.NW(L), 0n), VB.pw(dz)) == True{} : Bool}',
               '+hk: {Nat.is_lt(k, 31n) == True{} : Bool}', '+hy: {Nat.is_le(VC.YL(L), VB.pw(k)) == True{} : Bool}']
        w(f'def ci_any{s}(+d: Nat, +t: F.array__Tree<U32>, +n: U32, +off: U32, +i: Nat, +L: U32, +dz: Nat, +k: Nat,')
        w('    ' + ', '.join(HY + HY2) + ',')
        w('    +z: Bool, +ez: {U32.is_eq(L, 0) == z : Bool})')
        w(f'    -> {{O.ci_fin(n, L, O.ci_go(z, U32.and(off, 3), U32.shrn(off, 2n), VC.nwu(L), F.array__thaw(U32, VC.ZT(dz)), F.array__thaw(U32, t))) == {RES} : B.Buf & O.Words}}:')
        w('  match z:')
        w('    case True{}:')
        w('      +eL = F.u32alg__eq_of(L, 0, ez)')
        w('      %Equal.sym(U32, L, 0, eL) :')
        w(f'        {{({BUF}, O.Words{{O.mask_last(_, F.array__thaw(U32, VC.ZT(dz))), _}}) == ({BUF}, O.Words{{F.array__thaw(U32, VBY.MK(_, dz, UC.smone({s}n, VC.NW(_), i, 0n, dz, d, VC.ZT(dz), t))), _}}) : B.Buf & O.Words}}')
        w('      {==}')
        w('    case False{}:')
        w(f'      +Mo = {Mo}')
        w(f'      %Equal.sym(U32, U32.and(off, 3), {s}, h3) :')
        w(f'        {{O.ci_fin(n, L, O.ci_pick(_, U32.shrn(off, 2n), VC.nwu(L), F.array__thaw(U32, VC.ZT(dz)), F.array__thaw(U32, t))) == ({BUF}, O.Words{{F.array__thaw(U32, VBY.MK(L, dz, Mo)), L}}) : B.Buf & O.Words}}')
        w(f'      %Equal.sym(Array<U32> & Array<U32>, O.scopy{s}(VC.nwu(L), U32.shrn(off, 2n), 0, F.array__thaw(U32, VC.ZT(dz)), F.array__thaw(U32, t)),')
        w('          (F.array__thaw(U32, Mo), F.array__thaw(U32, t)),')
        w(f'          scopy{s}_ok(VC.nwu(L), U32.shrn(off, 2n), 0, i, 0n, dz, d, VC.ZT(dz), t, ei, {{==}}, hdz, hd, hs, hr, F.array__trep_perfect(U32, dz, 0), pf)) :')
        w(f'        {{O.ci_fin(n, L, _) == ({BUF}, O.Words{{F.array__thaw(U32, VBY.MK(L, dz, Mo)), L}}) : B.Buf & O.Words}}')
        w('      %Equal.sym(Array<U32>, O.mask_last(L, F.array__thaw(U32, Mo)), F.array__thaw(U32, VBY.MK(L, dz, Mo)),')
        w('          VBY.mask_ok(L, dz, Mo, k, hk, hy, VB.lt32(dz, hdz),')
        w('            F.logic__subst(Nat, z => {Nat.is_le(z, VB.pw(dz)) == True{} : Bool}, Nat.add(VC.NW(L), 0n), VC.NW(L), F.nat__add_zero(VC.NW(L)), hr),')
        w(f'            UC.smone_perfect({s}n, VC.NW(L), i, 0n, dz, d, VC.ZT(dz), t, F.array__trep_perfect(U32, dz, 0)))) :')
        w(f'        {{({BUF}, O.Words{{_, L}}) == ({BUF}, O.Words{{F.array__thaw(U32, VBY.MK(L, dz, Mo)), L}}) : B.Buf & O.Words}}')
        w('      {==}')
        w('')
        for name, call, extra in [(f'copy_in_ua{s}', 'O.copy_in({BUF}, off, L)', ['ez: {B.zeros(B.words_depth_u(VC.WZ(L))) == Array.new(U32, dz, 0) : Array<U32>}']),
                                  (f'copy_into_ua{s}', 'O.copy_into({BUF}, off, L, Array.new(U32, dz, 0))', [])]:
            if extra:
                w(f'# U2: copy_in of any length L at a byte offset off with off & 3 = {s}: the')
                w(f'# words are the joins at byte {s} of the source words from off >> 2, and the')
                w('# last one keeps only its L & 3 low bytes (MK); see UC.ci_bytes for its bytes.')
            else:
                w(f'# The same copy into a given zero array (byte {s}).')
            w(f'law {name}:')
            for v, ty in [('d', 'Nat'), ('t', 'F.array__Tree<U32>'), ('n', 'U32'), ('off', 'U32'), ('i', 'Nat'), ('L', 'U32'), ('dz', 'Nat'), ('k', 'Nat')]:
                w(f'  for +{v}: {ty}')
            hs_ = [h[1:] for h in HY] + extra + [h[1:] for h in HY2]
            for h in hs_:
                w(f'  for +{h}')
            w(f'  {{{call.format(BUF=BUF)} == {RES} : B.Buf & O.Words}}')
            names = [h.split(':')[0] for h in hs_]
            w(f'def {name}(d, t, n, off, i, L, dz, k, ' + ', '.join(names) + '):')
            if extra:
                w('  %Equal.sym(Array<U32>, B.zeros(B.words_depth_u(VC.WZ(L))), Array.new(U32, dz, 0), ez) :')
                w(f'    {{O.copy_into({BUF}, off, L, _) == {RES} : B.Buf & O.Words}}')
            w('  %Equal.sym(Array<U32>, Array.new(U32, dz, 0), F.array__thaw(U32, VC.ZT(dz)), F.array__new(U32, dz, 0)) :')
            w(f'    {{O.copy_into({BUF}, off, L, _) == {RES} : B.Buf & O.Words}}')
            w(f'  ci_any{s}(d, t, n, off, i, L, dz, k, pf, hd, hdz, h3, ei, hs, hr, hk, hy, U32.is_eq(L, 0), {{==}})')
            w('')
    return '\n'.join(L) + '\n'


def fix_types():
    from codegen.core import fulu_schema_loader as schema  # noqa: E402
    from codegen.impl import typed_object_runtime as G  # noqa: E402
    from codegen.proofs.var import single_list_container_codec_laws as VL  # noqa: E402
    names = schema.load(ROOT / 'codegen/fulu.yaml')
    g = G.Gen()
    for n, t in names.items():
        g.shape(t)
    fts = []

    def add(ft):
        try:
            f = VL.FT(g, ft)
        except VL.Skip:
            return
        for d in f.deps():
            if d.p not in [x.p for x in fts]:
                fts.append(d)
    for r in FIX_ROOTS:
        t = names[r]
        if t.fixed():
            add(t)
        else:
            for _, ft in t.fields:
                if ft.fixed():
                    add(ft)
    return fts


def posx(c):
    return 'x' if c == 0 else f'{c}n+x'


def rdx_lemma(ft, deep=False):
    """deep: rdxd_<p>, for any tree depth d < 31 (UR.offx31: the offsets below 2^32)."""
    rn = 'rdxd_' if deep else 'rdx_'
    """T.<p>_read at an offset off at byte position x: its words are the words at x, x + 4, ..."""
    W = ft.W
    words = [f'UR.RWN(t, {posx(4 * k)})' for k in range(W)]
    OBJ = ft.obj(words)
    RHS = f'(UA.BF(t, n), {OBJ})'
    TY = f'B.Buf & {ft.rep()}'
    P = 'A.quad(VB.pw(d))'
    L = [f'def {rn}{ft.p}(+d: Nat, +t: F.array__Tree<U32>, +n: U32, +off: U32, +x: Nat, +e: {{U32.to_nat(off) == x : Nat}},',
         f'    +hd: {{Nat.is_lt(d, {31 if deep else 30}n) == True{{}} : Bool}}, +pf: {{F.array__perfect(U32, d, t) == True{{}} : Bool}},',
         f'    +hb: {{Nat.is_le(Nat.add(x, {ft.size}n), {P}) == True{{}} : Bool}})',
         f'    -> {{T.{ft.p}_read(UA.BF(t, n), off, {ft.size}) == {RHS} : {TY}}}:']
    w = L.append
    hd31 = 'hd' if deep else 'F.nat__lt_trans(d, 30n, 31n, hd, {==})'
    ox = 'UR.offx31' if deep else 'UR.offx'

    def rd(k):
        c = 4 * k
        room = f'UR.roomw(x, {ft.size}n, {c}n, {P}, hb, {{==}})'
        if k == 0:
            o, eq = 'off', 'e'
        else:
            o = f'U32.add(off, {c})'
            eq = f'{ox}(d, off, {c}, x, e, hd, F.nat__lt_le_trans({posx(c)}, Nat.add({posx(c)}, 4n), {P}, ltp({posx(c)}, 3n), {room}))'
        return (f'Equal.sym(B.Buf & U32, B.read32(UA.BF(t, n), {o}), (UA.BF(t, n), UR.RWN(t, {posx(c)})), '
                f'UR.rwx(d, t, n, {o}, {posx(c)}, {eq}, {hd31}, pf, {room}))')
    if ft.kind == 'u64':
        w(f'  %{rd(0)} :')
        w(f'    {{O.u64_of(B.read64_lo(off, _)) == {RHS} : {TY}}}')
        w(f'  %{rd(1)} :')
        w(f'    {{O.u64_of(B.read64_hi({words[0]}, _)) == {RHS} : {TY}}}')
        w('  {==}')
    elif ft.kind == 'bytes':
        for k in range(W):
            args = ', '.join(['off'] + words[:k])
            w(f'  %{rd(k)} :')
            w(f'    {{T.{ft.p}_r{k}({args}, _) == {RHS} : {TY}}}')
        w('  {==}')
    else:
        for j, (c, kt) in enumerate(ft.kids):
            k0 = c // 4
            wk = words[k0:k0 + kt.W]
            prev = [kk.obj(words[cc // 4:cc // 4 + kk.W]) for cc, kk in ft.kids[:j]]
            args = ', '.join(['off', f'{ft.size}'] + prev)
            oj = f'U32.add(off, {c})'
            hbj = f'UR.roomf(x, {ft.size}n, {c}n, {kt.size}n, {P}, hb, {{==}})'
            ej = f'{ox}(d, off, {c}, x, e, hd, F.nat__lt_le_trans({posx(c)}, Nat.add({posx(c)}, {kt.size}n), {P}, ltp({posx(c)}, {kt.size - 1}n), {hbj}))'
            OBJj = kt.obj(wk)
            w(f'  %Equal.sym(B.Buf & {kt.rep()}, T.{kt.p}_read(UA.BF(t, n), {oj}, {kt.size}), (UA.BF(t, n), {OBJj}),')
            w(f'      {rn}{kt.p}(d, t, n, {oj}, {posx(c)}, {ej}, hd, pf, {hbj})) :')
            w(f'    {{T.{ft.p}_rd{j}({args}, _) == {RHS} : {TY}}}')
        w('  {==}')
    return L


def emit_fix():
    L = ['import Base', 'import ../../src/buffer.bend as B', 'import ../../src/obj.bend as O', 'import ../../types/fulu_obj.bend as T',
         'import ../compact/found.bend as F', 'import ../compact/arith.bend as A', 'import ../../proofs/nat_order.bend as Order',
         'import ./vbuf.bend as VB', 'import ./vua.bend as UA', 'import ./vua_rd.bend as UR', '',
         '# GENERATED by unaligned_read_laws (codegen). Do not edit.',
         '# U3, fixed-size types: T.<p>_read at an offset off at ANY byte position x',
         '# returns the object whose words are the four-byte joins UR.RWN(t, x + 4 k).', '',
         '# y < y + (1 + k)',
         'def ltp(+y: Nat, +k: Nat) -> {Nat.is_lt(y, Nat.add(y, 1n+k)) == True{} : Bool}:',
         '  %F.nat__add_comm(1n+k, y) : {Nat.is_lt(y, _) == True{} : Bool}',
         '  VB.lt_kk(0n, 1n+k, y, {==})', '']
    for ft in fix_types():
        L += rdx_lemma(ft) + ['']
    # the same at any tree depth d < 31 (the deep decode laws)
    for ft in fix_types():
        L += rdx_lemma(ft, True) + ['']
    return '\n'.join(L) + '\n'


CI_SRC = bytes(((17 + 29 * j) % 251) + 1 for j in range(32))     # 32 marked bytes, none zero, every neighbour different
CI_WORDS = 4                                                      # the words read back: 9 bytes at offset 3 end in word 2, word 3 stays zero


def le_words(data, k):
    data = data.ljust(4 * k, b'\0')
    return [int.from_bytes(data[4 * i:4 * i + 4], 'little') for i in range(k)]


def emit_ci(s):
    """(round 13: s01-copy/09, /10) O.copy_in on a literal buffer of 32 marked bytes at the byte offsets s and 4 + s, for every length 1 to 9:
    the length and the first CI_WORDS words of the copy are the source bytes [off, off + n) shifted to byte 0, the rest of the last word and the
    words after it zero. proofs/obj/vcopy.bend proves copy_in for a word-aligned range only, so a dispatch on off & 3 that picks the wrong
    shifted loop (scopy1 for s = 2) was caught only by the corpus."""
    src = 'Array.new(U32, 3n, 0)'
    for i, w in enumerate(le_words(CI_SRC, 8)):
        src = f'Array.set(U32, {src}, {i}, {w})'
    def nest(xs):
        return xs[0] if len(xs) == 1 else f'({xs[0]}, {nest(xs[1:])})'

    def tnest(k):
        return 'U32' if k == 1 else f'U32 & ({tnest(k - 1)})'
    tup = tnest(CI_WORDS + 1)
    L = ['import Base', 'import ../../src/buffer.bend as B', 'import ../../src/obj.bend as O', '',
         '# GENERATED by unaligned_read_laws (codegen). Do not edit.',
         f'# O.copy_in at byte offsets {s} and {4 + s} (offset & 3 = {s}) of a literal buffer, lengths 1 to 9 (round 13: s01-copy/09, /10;',
         '# see emit_ci in codegen/proofs/var/unaligned_read_laws.py).', '',
         f'def ci_src() -> B.Buf: B.Buf{{{src}, 32}}', '',
         f'def ci_c{CI_WORDS - 1}(pair: Array<U32> & U32) -> U32: Pair.snd(Array<U32>, U32, pair)', '']
    for i in range(CI_WORDS - 2, -1, -1):
        L += [f'def ci_c{i}(pair: Array<U32> & U32) -> {tnest(CI_WORDS - i)}:', '  (ws, +x) = pair', f'  (x, ci_c{i + 1}(Array.get(U32, ws, {i + 1})))', '']
    L += [f'def ci_rd(w: O.Words) -> {tup}:', '  match w:', '    case O.Words{ws, +n}: (n, ci_c0(Array.get(U32, ws, 0)))', '']
    for off in (s, 4 + s):
        for n in range(1, 10):
            want = nest([str(x) for x in [n] + le_words(CI_SRC[off:off + n], CI_WORDS)])
            L += [f'def ci_o{off}_n{n}() -> {{ci_rd(Pair.snd(B.Buf, O.Words, O.copy_in(ci_src(), {off}, {n}))) == {want} : {tup}}}:', '  {==}', '']
    return '\n'.join(L)


def main():
    from codegen.proofs.support import deep_window_decode_passes as deep  # the copy chain at any length 31 + L <= UMAX (the U twins)
    outs = [(OUT, emit()), (OUT_SC, deep.uify_file(emit_sc(), ROOT / 'proofs/obj')), (OUT_FIX, emit_fix())]
    outs += [(ROOT / f'proofs/obj/vua_ci{s}_generated.bend', emit_ci(s)) for s in (0, 1, 2, 3)]
    from codegen.impl import runtime_file_split as RR  # the runtime split: the modules import the per-name files they use
    outs = RR.rewire_out(outs)
    if '--check' in sys.argv:
        stale = [p.relative_to(ROOT) for p, text in outs if not p.exists() or p.read_text() != text]
        if stale:
            print('stale generated unaligned-offset laws: ' + ', '.join(map(str, stale)))
            sys.exit(1)
        print('generated unaligned-offset laws are current')
        return
    for p, text in outs:
        p.write_text(text)
        print(f'wrote {p.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
