from codegen.core.shared_var_a import Templates  # noqa: E402
TEMPLATES = Templates('var_rlist_bv', globals())
"""Byte-offset window modules (the interface of proofs/obj/vua_win.bend) of PACKED LISTS OF
BYTE VECTORS, e.g. BeaconBlockBody's blob_kzg_commitments (List[Bytes48, 4096]); written by
codegen/proofs/var/var_rlist.py.

The reader copies the window's bytes into a fresh word tree (O.copy_in, vua_ct.copy_in_at);
the value's items are the byte vectors of E = B / 4 words over the words UR.RWN(t, x + 4 k)
(vmul.bvit), whose parts are the window's bytes (vmul.list_bv, UR.rws_bytes). The copy's
storage depth is bounded from the element limit with every bound stated as a right shift
(VD.s_rng), so no closed number above the limit is evaluated.
"""


def bvx_text(HEAD, zeros_at_text, inv_text, p, B, N, sch_el, LSCH, big=False, deep=False):
    """deep: any tree depth d < 31, the window ending by NMAX (hwN): 31 + len <= UMAX and the copy is
    vcopy's U chain, no bound from the limit or the depth (codegen/proofs/var/var_win.py deep_N)."""
    E = B // 4
    # the allocation (at most 15 + PS c words, PS = 2^SH >= E) is below 2^K words, as
    # c <= N < 2^KR
    SH = 4            # hWZ: 7 + (M + 8) = 15 + M = 2^SH - 1 + M
    assert E <= 1 << SH
    PS, P1 = 1 << SH, (1 << SH) - 1
    KR = 0
    while (1 << KR) <= N:
        KR += 1
    K = SH + KR
    assert big or K <= 23
    TR = 'FD.array__Tree<U32>'
    TRUE = 'True{} : Bool'
    CW = (f'+d: Nat, +t: {TR}, +n: U32, +x: Nat, +off: U32, +len: U32, +eo: {{U32.to_nat(off) == x : Nat}},\n'
          f'    +hd: {{Nat.is_lt(d, 28n) == {TRUE}}}, +hw: {{Nat.is_le(Nat.add(x, U32.to_nat(len)), A.quad(VB.pw(d))) == {TRUE}}},\n'
          f'    +pf: {{FD.array__perfect(U32, d, t) == {TRUE}}}')
    CA = 'd, t, n, x, off, len, eo, hd, hw, pf'
    CK = f'{{Bool.and(U32.is_eq(len, (U32.div(len, {B}) * {B} : U32)), U32.is_le(U32.div(len, {B}), {N})) == {TRUE}}}'
    HC = f'+hchk: {{CHKw(t, x, off, len) == {TRUE}}}'
    L = list(HEAD) + ['import ./vmul.bend as VM', 'import ./vme.bend as VME', 'import ./vlist.bend as VLS', 'import ./vua_ct.bend as UCT', '',
                      '# GENERATED by var_rlist (codegen: var_rlist_bv). Do not edit.',
                      f'# The byte-offset window module of {p} (List[ByteVector[{B}], {N}], packed): see the',
                      '# module docstring of codegen/proofs/var/var_rlist_bv.py and the interface in proofs/obj/vua_win.bend.', '']
    if big or deep:
        # the copy's depth from the window (DZ <= 29), the zero array symbolically (vvlz)
        STORE, ZER, KZ = '', '', 29
        HZ = 'VLS.hdz29(d, len, hd, hlen(d, x, len, hw))'
        EZ = ('FD.logic__subst(Nat, z => {B.zeros(B.words_depth_u(VC.WZ(len))) == Array.new(U32, z, 0) : Array<U32>}, U32.to_nat(B.words_depth_u(VC.WZ(len))), VLS.DZ(len), '
              'VD.wdu(VC.WZ(len)), VZG.zg(B.words_depth_u(VC.WZ(len))))')
        L.insert(L.index('import ./vua_ct.bend as UCT') + 1, 'import ./vvlz.bend as VZG')
        if deep:
            HZ = 'VC.dz30(len, hy)'
    else:
        STORE = TEMPLATES.render('bvx_text', N=N, TRUE=TRUE, SH=SH, P1=P1, PS=PS, CW=CW, HC=HC, CA=CA, E=E, K=K, KR=KR)
        ZER, KZ = zeros_at_text(K), K
        HZ = f'hDZ({CA}, hchk)'
        EZ = 'zeros_at(B.words_depth_u(VC.WZ(len)), VLS.DZ(len), VD.wdu(VC.WZ(len)), hz)'
    if deep:
        READ = (TEMPLATES.render('bvx_text_2', HZ=HZ, EZ=EZ))
        FIT = ('VFT.fits4lt(U32.to_nat(len), FD.nat__le_lt_trans(U32.to_nat(len), Nat.add(x, U32.to_nat(len)), FD.spec_common__pow2(32n), Order.left_below_sum(x, U32.to_nat(len)),\n'
               '    VB.le_n_lt32(Nat.add(x, U32.to_nat(len)), VB.NMAX(), hwN)))')
    else:
        READ = (TEMPLATES.render('bvx_text_3', HZ=HZ, EZ=EZ, KZ=KZ))
        FIT = 'VLS.hfit(d, len, hd, hlen(d, x, len, hw))'
    L.append(TEMPLATES.render('bvx_text_4', TR=TR, B=B, N=N, CW=CW, p=p, E=E, CK=CK, TRUE=TRUE, STORE=STORE, ZER=ZER, HC=HC, READ=READ, LSCH=LSCH, FIT=FIT))
    L.append(inv_text(sch_el, B, N, LSCH, CW, CA))
    text = '\n'.join(L) + '\n'
    if deep:
        from codegen.proofs.var import var_win as VWN
        text = VWN.deep_N(text)
    return text
