#!/usr/bin/env python3
"""The encoder laws of the names of codegen/proofs/var/var_bytes_nest.py.

For a container X nesting a covered name Y this writes
proofs/obj/var_bytes_<X>_enc.bend with the same laws as
codegen/proofs/var/var_bytes_enc.py (putw, frame_lo, bytesw_enc, partsw, encode_eval,
encode_spec), built on Y's encoder laws at the window after X's header: Y's
writer putw at word H + P, Y's frame (its writes leave every window below it
alone), and the spec parts of Y's value (partsw).
"""
import re

from codegen.core.bendtext import wsplit  # noqa: E402
from codegen.impl import generate as G  # noqa: F401  kept: the import may register hooks at import time
from codegen.proofs.var import var_bytes as VBY
from codegen.proofs.var import var_bytes_enc as VBE
from codegen.proofs.var import var_bytes_nest as VBN
from codegen.core.shared_var_a import Templates  # noqa: E402
TEMPLATES = Templates('var_bytes_nenc', globals())

PREFIX = {'LightClientHeader': 'l', 'LightClientOptimisticUpdate': 'o'}


class NEnc:
    """Parameters and object of X's encoder laws, with the child's encoder C."""

    def __init__(self, x, C):
        self.x, self.C = x, C
        n = x.n
        pre = PREFIX[n]
        src = VBY.src()
        m = re.search(rf'^def {n}_encode\(o: {n}\) -> {n} & B\.Buf: {n}_enc_put\({n}_putn\(O\.out_at\((\d+)n\), 0, o\)\)$', src, re.M)
        if not m:
            raise VBY.Skip('encoder shape')
        self.DO = int(m.group(1))
        own_p, own_a, own_h, own_ha = [], [], [], []
        self.words, self.fobj = {}, {}
        for i, f in enumerate(x.fields):
            if f['kind'] == 'fix':
                ws = [f'{pre}w{f["k"] + j}' for j in range(f['W'])]
                self.words[i] = ws
                own_p += [f'+{q}: U32' for q in ws]
                own_a += ws
                o = f['ft'].obj(ws)
                self.fobj[i] = f'O.BSome{{{o}, O.BNone{{}}}}' if f['box'] else o
            elif f['kind'] == 'words':
                b = f'{pre}B{i}'
                own_p += [f'+d{b}: Nat', f'+T{b}: FD.array__Tree<U32>']
                own_a += [f'd{b}', f'T{b}']
                own_h += [f'+pf{b}: {{FD.array__perfect(U32, d{b}, T{b}) == True{{}} : Bool}}', f'+hd{b}: {{Nat.is_lt(d{b}, 31n) == True{{}} : Bool}}',
                          f'+hr{b}: {{Nat.is_le({f["W"]}n, VB.pw(d{b})) == True{{}} : Bool}}']
                own_ha += [f'pf{b}', f'hd{b}', f'hr{b}']
                self.words[i] = [f'VB.slot(T{b}, {j}n)' for j in range(f['W'])]
                self.fobj[i] = f'O.Words{{FD.array__thaw(U32, T{b}), {f["size"]}}}'
            else:
                o = f'YE.OBJE({C.A})'
                self.fobj[i] = f'O.BSome{{{o}, O.BNone{{}}}}' if f['box'] else o
        self.own_p, self.own_a, self.own_h, self.own_ha = own_p, own_a, own_h, own_ha
        self.params = own_p + C.params
        self.args = own_a + C.args
        self.hyps = own_h + C.hyps
        self.hargs = own_ha + C.hargs
        self.P = ', '.join(self.params)
        self.A = ', '.join(self.args)
        self.AH = ', '.join(self.args + self.hargs)
        # the largest encoding: the header and the child's largest encoding
        self.MAX = x.FS + C.MAX
        self.KS = VBY.kfit(self.MAX + 1)

    def objterm(self):
        return f'T.{self.x.s.t.name}{{' + ', '.join(self.fobj[i] for i in range(len(self.x.fields))) + '}'



def child_enc(n, g, names):
    """The encoder object of name n (EPH: codegen/proofs/var/var_bytes_enc.py Enc; nested: NEnc)."""
    if n in VBN.NEST:
        x = VBN.NName(g, n, names[n])
        return NEnc(x, child_enc(VBN.NEST[n], g, names))
    x = VBY.Name(g, n, names[n])
    E = VBE.Enc(x)
    E.MAX = x.FS + x.LIM
    E.KS = VBY.kfit(E.MAX + 1)
    return E


def rest_term(E, P):
    """ROOM(N, P) = Nat.add(VC.NW(N), rest_term(E, P))."""
    if isinstance(E, NEnc):
        return rest_term(E.C, f'Nat.add({E.x.H}n, {P})')
    return f'Nat.add({E.x.H}n, {P})'


def enc_module_text(x, E):
    n, FS, H, po, cvar, Y = x.n, x.FS, x.H, x.po, x.cvar, x.Y
    FSN = x.FSN
    C = E.C
    HY = C.x.H
    Tn = f'T.{n}'
    vi = [i for i, f in enumerate(x.fields) if f['kind'] == 'var'][0]
    vf = x.fields[vi]
    vp = f'{Y}_bx' if vf['box'] else Y
    VOBJ = E.fobj[vi]
    L = list(VBN.HEAD) + ['import ./venc.bend as VE', 'import ./vbenc.bend as VBE', 'import ./venc2.bend as V2', 'import ./var_bytes_wput.bend as WP',
                          f'import ./{VBY.fname(type("X", (), {"n": Y}), "_enc").name} as YE',
                          'import ../../spec/schema.bend as SC', 'import ./vseq.bend as VSQ', '',
                          '# GENERATED by var_bytes_nenc (codegen). Do not edit.',
                          f'# The encoder of {n} on {Y}\'s encoder laws (see the module docstring of codegen/proofs/var/var_bytes_nenc.py).', '']
    w = L.append
    DP = f'{E.P}, +dd: Nat, +D: FD.array__Tree<U32>, +P: Nat'
    DA = f'{E.A}, dd, D, P'
    OBJ = f'OBJE({E.A})'
    PC = f'Nat.add({H}n, P)'
    HN = '+hN: {Nat.is_le(U32.to_nat(N), 32n) == True{} : Bool}'
    HDST = '+hdst: {Nat.is_le(ROOM(N, P), VB.pw(dd)) == True{} : Bool}'
    HZ = '+hz0: {VB.slot(D, KZ(N, P)) == 0 : U32}'
    PFD = '+pf: {FD.array__perfect(U32, dd, D) == True{} : Bool}'
    HDD = '+hdd: {Nat.is_lt(dd, 29n) == True{} : Bool}'
    LT = 'List<&2, U32>'
    KS, MAX, CM = E.KS, E.MAX, C.MAX
    KY = VBY.kfit(31 + CM)
    w(f'def OBJE({E.P}) -> {Tn}: {E.objterm()}')
    w(f'def SFS(+N: U32) -> U32: U32.add({FS}, YE.SFS(N))')
    w(f'def ROOM(+N: U32, +P: Nat) -> Nat: YE.ROOM(N, {PC})')
    w(f'def KZ(+N: U32, +P: Nat) -> Nat: YE.KZ(N, {PC})')
    w(TEMPLATES.render('enc_module_text', HN=HN, PC=PC, H=H, HY=HY, FSN=FSN, FS=FS, MAX=MAX, CM=CM, KS=KS, C=C, HDST=HDST))

    def hbw(W, k):
        return f'hb({W}n, {k}n, P, dd, {{==}}, hHP(N, dd, P, hdst))'
    layers, leaves = VBE.plan(x, E)
    NL = len(layers)
    vj = [j for j, l in enumerate(layers) if l[0] == 'var'][0]
    if vj != 0:
        raise VBY.Skip('writes before the nested field')

    def tree(j):
        return 'D' if j == 0 else f'LY{j}({DA})'

    def pfl(j):
        return f'pfL{j}({DA}, pf)' if j else 'pf'

    def vterm(kind, V, i):
        f = x.fields[i]
        if f['kind'] == 'words':
            return f'WP.WL_{f["p"]}(T{PREFIX[n]}B{i})'
        return f'[{", ".join(V)}]'

    def d2(j):
        return f'VF.updv([{FS}], dd, {tree(j)}, Nat.add({po}n, P))'
    for j, (kind, V, k, i) in enumerate(layers):
        if kind == 'var':
            term = f'YE.OUTW({C.A}, dd, {d2(j)}, {PC})'
        else:
            term = f'VF.updv({vterm(kind, V, i)}, dd, {tree(j)}, Nat.add({k}n, P))'
        w(f'def LY{j + 1}({DP}) -> FD.array__Tree<U32>: {term}')
    w(f'def OUTW({DP}) -> FD.array__Tree<U32>: {tree(NL)}')
    for j, (kind, V, k, i) in enumerate(layers):
        if kind == 'var':
            pr = f'YE.pfO({C.A}, dd, {d2(j)}, {PC}, VF.updv_perfect([{FS}], dd, {tree(j)}, Nat.add({po}n, P), {pfl(j)}))'
        else:
            pr = f'VF.updv_perfect({vterm(kind, V, i)}, dd, {tree(j)}, Nat.add({k}n, P), {pfl(j)})'
        w(f'def pfL{j + 1}({DP}, {PFD}) -> {{FD.array__perfect(U32, dd, {tree(j + 1)}) == True{{}} : Bool}}:')
        w(f'  {pr}')
    w(f'def pfO({DP}, {PFD}) -> {{FD.array__perfect(U32, dd, OUTW({DA})) == True{{}} : Bool}}: pfL{NL}({DA}, pf)')
    w('')
    # ---- boxed Data records ----
    done = set()
    for i, f in enumerate(x.fields):
        if f['kind'] == 'fix' and f['box'] and f['p'] not in done:
            done.add(f['p'])
            ft = f['ft']
            xs = [f'x{j}' for j in range(f['W'])]
            ob = ft.obj(xs)
            RHS = f'(FD.array__thaw(U32, VF.updv([{", ".join(xs)}], dd, D, P)), (O.BSome{{{ob}, O.BNone{{}}}}, 0))'
            w(TEMPLATES.render('enc_module_text_2', ft=ft, PFD=PFD, f=f, xs=xs, ob=ob, RHS=RHS))
    # ---- the nested field's writer ----
    D2 = f'VF.updv([{FS}], dd, D1, Nat.add({po}n, P))'
    RX = f'(FD.array__thaw(U32, YE.OUTW({C.A}, dd, {D2}, {PC})), ({VOBJ}, SFS(N)))'
    TX_ = f'Array<U32> & ({"O.Boxed<T." + Y + ">" if vf["box"] else "T." + Y} & U32)'
    ecv = f'eoc({po}n, {cvar}, P, pos, dd, eP, hdd, {{==}}, hbq(1n, {po}n, P, dd, {hbw(1, po)}))'
    ecF = f'eoc({H}n, {FS}, P, pos, dd, eP, hdd, {{==}}, hbq(0n, {H}n, P, dd, hHP(N, dd, P, hdst)))'
    inner = f'T.{Y}_bx_pk_back(_)' if vf['box'] else '_'
    w(TEMPLATES.render('enc_module_text_3', po=po, H=H, C=C, HDST=HDST, vp=vp, cvar=cvar, FS=FS, VOBJ=VOBJ, RX=RX, TX_=TX_, ecv=ecv, D2=D2, hbw=hbw, Y=Y, PC=PC, ecF=ecF, inner=inner))
    # ---- the writer ----
    RHS = f'(FD.array__thaw(U32, OUTW({DA})), ({OBJ}, SFS(N)))'
    TY = f'Array<U32> & ({Tn} & U32)'
    w('# The writer at pos = 4 P over any perfect tree D (depth dd < 29) with room for the')
    w("# encoding and a zero word under the innermost byte list's partial last word.")
    w(f'def putw({DP}, {", ".join(E.hyps)}, +pos: U32, +eP: {{U32.to_nat(pos) == A.quad(P) : Nat}},')
    w(f'    {HDD}, {PFD}, {HDST}, {HZ})')
    w(f'    -> {{{Tn}_putn(FD.array__thaw(U32, D), pos, {OBJ}) == {RHS} : {TY}}}:')
    last_cur = 'SFS(N)'
    for ctx, i, j0, j1, kind, cur in leaves:
        f = x.fields[i]
        pat = ctx.replace('@', '_')
        pfp = pfl(j0)
        if kind == 'putv':
            call = f'T.{vp}_putv(FD.array__thaw(U32, {tree(j0)}), pos, {cvar}, {cur}, {E.fobj[i]})'
            res = f'(FD.array__thaw(U32, {tree(j1)}), ({E.fobj[i]}, SFS(N)))'
            pr = f'vput(dd, {tree(j0)}, pos, P, eP, hdd, {pfp}, {C.A}, hdst, {", ".join(C.hargs)}, hz0)'
            ty = TX_
        elif kind == 'put' and f['kind'] == 'words':
            b = f'{PREFIX[n]}B{i}'
            call = f'T.{f["p"]}_putk(FD.array__thaw(U32, {tree(j0)}), U32.add(pos, {f["c"]}), {E.fobj[i]})'
            res = f'(FD.array__thaw(U32, {tree(j1)}), ({E.fobj[i]}, 0))'
            pr = (f'WP.wput_{f["p"]}(dd, {tree(j0)}, U32.add(pos, {f["c"]}), Nat.add({f["k"]}n, P), '
                  f'eoc({f["k"]}n, {f["c"]}, P, pos, dd, eP, hdd, {{==}}, hbq({f["W"]}n, {f["k"]}n, P, dd, {hbw(f["W"], f["k"])})), '
                  f'hdd, {pfp}, {hbw(f["W"], f["k"])}, d{b}, T{b}, pf{b}, hd{b}, hr{b})')
            ty = 'Array<U32> & (O.Words & U32)'
            last_cur = f'U32.or({cur}, 0)'
        elif kind == 'put':
            ft = f['ft']
            call = f'T.{ft.p}_bx_putk(FD.array__thaw(U32, {tree(j0)}), U32.add(pos, {f["c"]}), {E.fobj[i]})'
            res = f'(FD.array__thaw(U32, {tree(j1)}), ({E.fobj[i]}, 0))'
            pr = (f'bxput_{ft.p}(dd, {tree(j0)}, U32.add(pos, {f["c"]}), Nat.add({f["k"]}n, P), '
                  f'eoc({f["k"]}n, {f["c"]}, P, pos, dd, eP, hdd, {{==}}, hbq({f["W"]}n, {f["k"]}n, P, dd, {hbw(f["W"], f["k"])})), '
                  f'hdd, {pfp}, {hbw(f["W"], f["k"])}, {", ".join(E.words[i])})')
            ty = f'Array<U32> & (O.Boxed<T.{ft.s.rep}> & U32)'
            last_cur = f'U32.or({cur}, 0)'
        else:
            ft = f['ft']
            call = f'T.{ft.p}_put(FD.array__thaw(U32, {tree(j0)}), U32.add(pos, {f["c"]}), {E.fobj[i]})'
            res = f'FD.array__thaw(U32, {tree(j1)})'
            pr = (f'VT.put_{ft.p}(dd, {tree(j0)}, U32.add(pos, {f["c"]}), Nat.add({f["k"]}n, P), '
                  f'eoc({f["k"]}n, {f["c"]}, P, pos, dd, eP, hdd, {{==}}, hbq({f["W"]}n, {f["k"]}n, P, dd, {hbw(f["W"], f["k"])})), '
                  f'hdd, {pfp}, {hbw(f["W"], f["k"])}, {", ".join(E.words[i])})')
            ty = 'Array<U32>'
        w(f'  %Equal.sym({ty}, {call}, {res},')
        w(f'      {pr}) :')
        w(f'    {{{pat} == {RHS} : {TY}}}')
    if last_cur != 'SFS(N)':
        w(f'  %Equal.sym(U32, U32.or(SFS(N), 0), SFS(N), VE.or_zero_u(SFS(N))) :')
        w(f'    {{(FD.array__thaw(U32, OUTW({DA})), ({OBJ}, _)) == {RHS} : {TY}}}')
    w('  {==}')
    w('')
    L += spec_text(x, E, layers, NL, tree, pfl, vterm, hbw, d2)
    return '\n'.join(L) + '\n'


def spec_text(x, E, layers, NL, tree, pfl, vterm, hbw, d2):
    n, FS, H, po, Y = x.n, x.FS, x.H, x.po, x.Y
    FSN = x.FSN
    C = E.C
    Tn = f'T.{n}'
    L = []
    w = L.append
    DP = f'{E.P}, +dd: Nat, +D: FD.array__Tree<U32>, +P: Nat'
    DA = f'{E.A}, dd, D, P'
    OBJ = f'OBJE({E.A})'
    PC = f'Nat.add({H}n, P)'
    HN = '+hN: {Nat.is_le(U32.to_nat(N), 32n) == True{} : Bool}'
    HDST = '+hdst: {Nat.is_le(ROOM(N, P), VB.pw(dd)) == True{} : Bool}'
    PFD = '+pf: {FD.array__perfect(U32, dd, D) == True{} : Bool}'
    HDD = '+hdd: {Nat.is_lt(dd, 29n) == True{} : Bool}'
    LT = 'List<&2, U32>'
    MP = 'Maybe<&2, +List<S.Part>>'
    M = 'Maybe<&2, +List<U32>>'
    S_ = f'FD.array__slots(U32, OUTW({DA}))'
    WP_ = f'{DP}, {", ".join(E.hyps)}, {PFD}, {HDST}'
    WA_ = f'{DA}, {", ".join(E.hargs)}, pf, hdst'
    DO = E.DO
    T0 = f'OUTW({E.A}, {DO}n, VC.ZT({DO}n), 0n)'
    A0 = f'{E.A}, {DO}n, VC.ZT({DO}n), 0n'
    REST = rest_term(E, '0n')
    HD0 = (f'FD.nat__le_trans(ROOM(N, 0n), Nat.add(8n, {REST}), VB.pw({DO}n), '
           f'Order.add_right(VC.NW(N), 8n, {REST}, hNW(N, hN)), {{==}})')

    def win(m, p, j):
        return f'VF.WIN({m}, {p}, FD.array__slots(U32, {tree(j)}))'
    vj = [j for j, l in enumerate(layers) if l[0] == 'var'][0]

    def peel_chain(m, k0, mlit, j_stop, last_term, last_proof):
        p = f'Nat.add({k0}n, P)'

        def rel(W2, k2, pre, pf_, hb_):
            if k2 + W2 <= k0:
                return f'V2.peel_lo({pre}, {m}, {p}, {pf_}, {hb_}, Order.add_right({W2 + k2}n, {k0}n, P, {{==}}))'
            assert mlit is not None and k0 + mlit <= k2
            return f'V2.peel_hi({pre}, {m}, {p}, {pf_}, {hb_}, Order.add_right({mlit + k0}n, {k2}n, P, {{==}}))'
        steps = []
        for g in range(NL - 1, j_stop - 1, -1):
            kind, V, kL, i = layers[g]
            if kind == 'var':
                assert mlit is not None and k0 + mlit <= H
                pf2 = f'VF.updv_perfect([{FS}], dd, {tree(g)}, Nat.add({po}n, P), {pfl(g)})'
                pr1 = (f'YE.frame_lo({C.A}, dd, {d2(g)}, {PC}, {pf2}, hdst, {m}, {p}, '
                       f'Order.add_right({mlit + k0}n, {H}n, P, {{==}}))')
                steps.append((win(m, p, g + 1), f'VF.WIN({m}, {p}, FD.array__slots(U32, {d2(g)}))', pr1))
                pr2 = rel(1, po, f'[{FS}], dd, {tree(g)}, Nat.add({po}n, P)', pfl(g), hbw(1, po))
                steps.append((f'VF.WIN({m}, {p}, FD.array__slots(U32, {d2(g)}))', win(m, p, g), pr2))
            else:
                f = x.fields[i]
                pr = rel(f['W'], kL, f'{vterm(kind, V, i)}, dd, {tree(g)}, Nat.add({kL}n, P)', pfl(g), hbw(f['W'], kL))
                steps.append((win(m, p, g + 1), win(m, p, g), pr))
        out = last_proof
        for a, b, pr in reversed(steps):
            out = f'Equal.trans({LT}, {a}, {b}, {last_term}, {pr},\n    {out})'
        return out

    segs = []
    for i, f in enumerate(x.fields):
        if f['kind'] == 'var':
            segs.append((i, 1, f['k'], f'[{FS}]'))
        else:
            segs.append((i, f['W'], f['k'], f'[{", ".join(E.words[i])}]'))
    layer_of = {l[3]: j for j, l in enumerate(layers)}
    for i, Wd, k0, Vs in segs:
        f = x.fields[i]
        j = layer_of[i]
        m, p = f'{Wd}n', f'Nat.add({k0}n, P)'
        if f['kind'] == 'var':
            own = (f'Equal.trans({LT}, {win(m, p, j + 1)}, VF.WIN({m}, {p}, FD.array__slots(U32, {d2(j)})), {Vs},\n'
                   f'    YE.frame_lo({C.A}, dd, {d2(j)}, {PC}, VF.updv_perfect([{FS}], dd, {tree(j)}, Nat.add({po}n, P), {pfl(j)}), hdst, {m}, {p}, '
                   f'Order.add_right({1 + po}n, {H}n, P, {{==}})),\n'
                   f'    V2.own([{FS}], dd, {tree(j)}, Nat.add({po}n, P), {pfl(j)}, {hbw(1, po)}))')
        else:
            own = f'V2.own({vterm(layers[j][0], layers[j][1], i)}, dd, {tree(j)}, Nat.add({k0}n, P), {pfl(j)}, {hbw(Wd, k0)})'
        body = peel_chain(m, k0, Wd, j + 1, Vs, own)
        w(f'def seg{i}({WP_}) -> {{{win(m, p, NL)} == {Vs} : {LT}}}:')
        w('  ' + body)
        w('')
    hdr = []
    for i, Wd, k0, Vs in segs:
        hdr += (E.words[i] if x.fields[i]['kind'] != 'var' else [str(FS)])
    HDRE = '[' + ', '.join(hdr) + ']'
    w(f'def hdr_eq({WP_}) -> {{{win(f"{H}n", "Nat.add(0n, P)", NL)} == {HDRE} : {LT}}}:')
    R, pos_ = H, 0
    pre = lambda t: t  # noqa: E731
    for idx, (i, Wd, k0, Vs) in enumerate(segs):
        assert k0 == pos_
        if idx < len(segs) - 1:
            s1, s3, sl = wsplit(Wd, R - Wd, pos_)
            w(f'  %Equal.sym({LT}, {win(s1, f"Nat.add({pos_}n, P)", NL)}, VF.app({win(f"{Wd}n", f"Nat.add({pos_}n, P)", NL)}, {win(f"{R - Wd}n", f"Nat.add({s3}, P)", NL)}),')
            w(f'      {sl}({Wd}n, {R - Wd}n, {pos_}n, P, {S_})) :')
            w(f'    {{{pre("_")} == {HDRE} : {LT}}}')
            rest = win(f'{R - Wd}n', f'Nat.add({pos_ + Wd}n, P)', NL)
            w(f'  %Equal.sym({LT}, {win(f"{Wd}n", f"Nat.add({pos_}n, P)", NL)}, {Vs}, seg{i}({WA_})) :')
            w(f'    {{{pre(f"VF.app(_, {rest})")} == {HDRE} : {LT}}}')
            pre = (lambda p0, Vs: (lambda t: p0(f'VF.app({Vs}, {t})')))(pre, Vs)
            R, pos_ = R - Wd, pos_ + Wd
        else:
            assert R == Wd
            w(f'  %Equal.sym({LT}, {win(f"{Wd}n", f"Nat.add({pos_}n, P)", NL)}, {Vs}, seg{i}({WA_})) :')
            w(f'    {{{pre("_")} == {HDRE} : {LT}}}')
    w('  {==}')
    w('')
    YBW = f'VS.bt(U32.to_nat(YE.SFS(N)), F.limbs(VB.wdr({PC}, {S_})))'
    BYTES = f'VS.bt(U32.to_nat(SFS(N)), F.limbs(VB.wdr(P, {S_})))'
    RB = f'List.append(&2, U32, F.limbs({HDRE}), {YBW})'
    w(TEMPLATES.render('spec_text', WP_=WP_, HDD=HDD, BYTES=BYTES, RB=RB, PC=PC, S_=S_, DA=DA, FSN=FSN, H=H, LT=LT, HDRE=HDRE, WA_=WA_))
    # the child's window in the final output is its own output window
    m = f'VC.NW(YE.SFS(N))'
    lo_steps = []
    for g in range(NL - 1, vj, -1):
        kind, V, kL, i = layers[g]
        f = x.fields[i]
        pr = (f'V2.peel_lo({vterm(kind, V, i)}, dd, {tree(g)}, Nat.add({kL}n, P), {m}, {PC}, {pfl(g)}, {hbw(f["W"], kL)}, '
              f'Order.add_right({f["W"] + kL}n, {H}n, P, {{==}}))')
        lo_steps.append((win(m, PC, g + 1), win(m, PC, g), pr))
    out = '{==}'
    for a, b, pr in reversed(lo_steps):
        out = f'Equal.trans({LT}, {a}, {b}, {win(m, PC, vj + 1)}, {pr},\n    {out})'
    KYc = VBY.kfit(31 + C.MAX)
    CB = f'VS.bt(U32.to_nat(YE.SFS(N)), F.limbs(VB.wdr({PC}, FD.array__slots(U32, {tree(vj + 1)}))))'
    w(TEMPLATES.render('spec_text_2', WP_=WP_, win=win, m=m, PC=PC, NL=NL, vj=vj, LT=LT, out=out, CB=CB, YBW=YBW, KYc=KYc, C=C, tree=tree, S_=S_, WA_=WA_))
    wt = lambda f, j: E.words[x.fields.index(f)][j]  # noqa: E731
    ITEMS, CHAIN, PL, CAT, PRE, POST, hdr2 = VBN.spec_items(x, 'V', 'Yb', 'hv', wt)
    assert '[' + ', '.join(hdr2) + ']' == HDRE
    ENC = f'List.append(&2, U32, F.limbs({HDRE}), Yb)'
    ENCR = f'List.append(&2, U32, List.append(&2, U32, F.flat({PRE}), List.append(&2, U32, N.digits(4n, VS.FSZ({PRE}, {POST})), F.flat({POST}))), Yb)'
    OWN = ', '.join(E.own_p)
    OWA = ', '.join(E.own_a)
    BY0 = f'VS.bt(U32.to_nat(SFS(N)), F.limbs(FD.array__slots(U32, {T0})))'
    RE = f'({OBJ}, B.Buf{{FD.array__thaw(U32, {T0}), SFS(N)}})'
    TY = f'Array<U32> & ({Tn} & U32)'
    w(f'''# The value of an object of own words and the child's value V.
def XEY({OWN}, +V: S.Value) -> S.Value: S.Sequence{{{ITEMS}}}

def encE({OWN}, +V: S.Value, +Yb: +List<U32>,
    +hv: {{Codec.parts(V, Spec.{Y}()) == Some{{[S.Variable{{Yb}}]}} : {MP}}}, +hdom: {{SP.bytes_domain(Yb) == True{{}} : Bool}},
    +fit: {{N.fits(4n, Nat.add(VS.FSZ({PRE}, {POST}), List.length(&2, U32, Yb))) == True{{}} : Bool}})
    -> {{Codec.parts(XEY({OWA}, V), Spec.{n}()) == Some{{[S.Variable{{{ENC}}}]}} : {MP}}}:
{VBE._seq_step(n, f'XEY({OWA}, V)', ITEMS, CHAIN, f'Some{{[S.Variable{{{ENC}}}]}}', MP)}  %Equal.sym({MP}, Codec.parts({ITEMS}, {CHAIN}), Some{{{PL}}},
      {CAT}) :
    {{Codec.aggregate(_, SC.fixed_size({CHAIN})) == Some{{[S.Variable{{{ENC}}}]}} : {MP}}}
  %Equal.sym({M}, Layout.encoding(VS.fpv({PRE}, Yb, {POST})), Some{{{ENCR}}}, VZ.enc_fpvb({PRE}, Yb, {POST}, hdom, fit)) :
    {{Codec.one(_, None{{}}) == Some{{[S.Variable{{{ENC}}}]}} : {MP}}}
  {{==}}

# The value of the object.
def XE({E.P}) -> S.Value: XEY({OWA}, YE.XE({C.A}))

def fitE({WP_}) -> {{N.fits(4n, Nat.add(VS.FSZ({PRE}, {POST}), List.length(&2, U32, {YBW}))) == True{{}} : Bool}}:
  VFT.fits4({E.KS}n, Nat.add({FSN}, List.length(&2, U32, {YBW})),
    FD.nat__le_trans(Nat.add({FSN}, List.length(&2, U32, {YBW})), {E.MAX}n, VB.pw({E.KS}n),
      Order.add_left({FSN}, List.length(&2, U32, {YBW}), {C.MAX}n,
        FD.nat__le_trans(List.length(&2, U32, {YBW}), U32.to_nat(YE.SFS(N)), {C.MAX}n, VZ.bt_len_le(U32.to_nat(YE.SFS(N)), F.limbs(VB.wdr({PC}, {S_}))), YE.hSle(N, hN))),
      {{==}}),
    {{==}})

# The spec parts of the object's value are one variable part: the bytes of the
# encoder's output window.
def partsw({WP_}, {HDD})
    -> {{Codec.parts(XE({E.A}), Spec.{n}()) == Some{{[S.Variable{{{BYTES}}}]}} : {MP}}}:
  +pf2 = VF.updv_perfect([{FS}], dd, D, Nat.add({po}n, P), pf)
  +hv0 = YE.partsw({C.A}, dd, {d2(0)}, {PC}, {", ".join(C.hargs)}, pf2, hdst, hdd)
  +hv = Equal.trans({MP}, Codec.parts(YE.XE({C.A}), Spec.{Y}()), Some{{[S.Variable{{{CB}}}]}}, Some{{[S.Variable{{{YBW}}}]}}, hv0,
    Equal.cong(+List<U32>, {MP}, z => Some{{[S.Variable{{z}}]}}, {CB}, {YBW}, child_bytes({WA_})))
  %Equal.sym(+List<U32>, {BYTES}, {RB}, bytesw_enc({WA_}, hdd)) :
    {{Codec.parts(XE({E.A}), Spec.{n}()) == Some{{[S.Variable{{_}}]}} : {MP}}}
  encE({OWA}, YE.XE({C.A}), {YBW}, hv, VZ.bd_btl(U32.to_nat(YE.SFS(N)), VB.wdr({PC}, {S_})), fitE({WA_}))

# The encoder returns the object and the buffer of the output tree.
law encode_eval:
''' + '\n'.join(f'  for {q}' for q in E.params + E.hyps) + TEMPLATES.render('spec_text_3', Tn=Tn, OBJ=OBJ, RE=RE, E=E, DO=DO, TY=TY, T0=T0, A0=A0, HD0=HD0) + '\n'.join(f'  for {q}' for q in E.params + E.hyps) + TEMPLATES.render('spec_text_4', n=n, BY0=BY0, E=E, M=M, MP=MP, A0=A0, DO=DO, HD0=HD0))
    # frame_lo
    steps = []
    for g in range(NL - 1, -1, -1):
        kind, V, kL, i = layers[g]
        if kind == 'var':
            pf2 = f'VF.updv_perfect([{FS}], dd, {tree(g)}, Nat.add({po}n, P), {pfl(g)})'
            steps.append((f'VF.WIN(m, p, FD.array__slots(U32, {tree(g + 1)}))', f'VF.WIN(m, p, FD.array__slots(U32, {d2(g)}))',
                          f'YE.frame_lo({C.A}, dd, {d2(g)}, {PC}, {pf2}, hdst, m, p, FD.nat__le_trans(Nat.add(m, p), P, {PC}, h, Order.left_below_sum({H}n, P)))'))
            steps.append((f'VF.WIN(m, p, FD.array__slots(U32, {d2(g)}))', f'VF.WIN(m, p, FD.array__slots(U32, {tree(g)}))',
                          f'V2.peel_hi([{FS}], dd, {tree(g)}, Nat.add({po}n, P), m, p, {pfl(g)}, {hbw(1, po)}, FD.nat__le_trans(Nat.add(m, p), P, Nat.add({po}n, P), h, Order.left_below_sum({po}n, P)))'))
        else:
            f = x.fields[i]
            steps.append((f'VF.WIN(m, p, FD.array__slots(U32, {tree(g + 1)}))', f'VF.WIN(m, p, FD.array__slots(U32, {tree(g)}))',
                          f'V2.peel_hi({vterm(kind, V, i)}, dd, {tree(g)}, Nat.add({kL}n, P), m, p, {pfl(g)}, {hbw(f["W"], kL)}, '
                          f'FD.nat__le_trans(Nat.add(m, p), P, Nat.add({kL}n, P), h, Order.left_below_sum({kL}n, P)))'))
    out = '{==}'
    for a, b, pr in reversed(steps):
        out = f'Equal.trans({LT}, {a}, {b}, VF.WIN(m, p, FD.array__slots(U32, D)), {pr},\n    {out})'
    w('# The encoder leaves every window below word P alone.')
    w(f'def frame_lo({DP}, {PFD}, {HDST}, +m: Nat, +p: Nat, +h: {{Nat.is_le(Nat.add(m, p), P) == True{{}} : Bool}})')
    w(f'    -> {{VF.WIN(m, p, FD.array__slots(U32, OUTW({DA}))) == VF.WIN(m, p, FD.array__slots(U32, D)) : {LT}}}:')
    w('  ' + out)
    w('')
    return L


def outputs(g, names):
    out = {}
    for n in VBN.ORDER:
        if n == 'LightClientBootstrap':
            # its 24820-byte header: codegen/proofs/var/var_bytes_benc.py (a big_ file)
            from codegen.proofs.var import var_bytes_benc as VBBE
            x = VBN.NName(g, n, names[n])
            L, _ = VBBE.enc_text(x, child_enc(VBN.NEST[n], g, names), 13)
            out[VBY.fname(x, '_enc')] = '\n'.join(L) + '\n'
            continue
        if n in VBN.NO_ENC:
            continue
        E = child_enc(n, g, names)
        out[VBY.fname(E.x, '_enc')] = enc_module_text(E.x, E)
    return out
