#!/usr/bin/env python3
"""Generate the codec laws of the bare progressive lists of whole-word unsigned
elements (the generic forms ProgressiveList[uint32/64/128/256]).

    python3 codegen/proofs/var/var_plist.py [--check]

Writes

    proofs/obj/var_elems.bend   (stock) the spec side of a list of k unsigned
        elements of E words each (E = 1, 2, 4, 8): its value it<E>(k, W), its
        parts, count, bytes, the progressive-list encoding plenc<E>, and the
        inversion rep_facts<E> of the repeated parts;
    proofs/obj/var_plist_<X>.bend          ok_eval, decode_accept, decode_spec
    proofs/obj/var_plist_<X>_unique.bend   decode_unique
    proofs/obj/var_plist_<X>_rej.bend      decode_reject, decode_none
    proofs/obj/var_plist_<X>_enc.bend      encode_eval, encode_spec

for every buffer B.Buf{thaw(t), n} on a perfect word tree t of depth d < 28
with n <= 4 2^d, and every object O.Words{thaw(T), N} whose storage T is a
perfect tree of depth dw < 28 holding its c elements. The per-name files are
BIG (checked with `checkq --big`): a progressive list has no length limit, so
the decoder's list storage depth ranges up to 29 and its zeros_at case split
compares Array.new trees of up to 2^29 leaves, which stock Bend normalizes
(the pinned checker compares the two identical calls rigidly). The element-agnostic
facts are the hand-written, stock-checked proofs/obj/vlist.bend.
"""
import sys as _sys
import pathlib as _pathlib
_sys.path.insert(0, str(_pathlib.Path(__file__).resolve().parents[3]))  # the repository root: `codegen` is importable when this file runs as a script
import re
import sys
from codegen.core import writer  # noqa: E402

from codegen.core.paths import ROOT  # noqa: E402

# name -> (runtime prefix, words per element)
NAMES = {'proglist_uint32': ('pl_u32', 1), 'proglist_uint64': ('pl_u64', 2),
         'proglist_uint128': ('pl_u128', 4), 'proglist_uint256': ('pl_u256', 8)}
WIDTH = {1: 'P.U32Width{}', 2: 'P.U64{}', 4: 'P.U128{}', 8: 'P.U256{}'}
PART = {1: 'FX.uint32_part', 2: 'FX.uint64_part', 4: 'FX.uint128_part', 8: 'FX.uint256_part'}

ELEM_HEAD = ['import Base', 'import ../../types/schema.bend as S', 'import ../../types/primitive.bend as P',
             'import ../../spec/primitives.bend as SP', 'import ../../spec/layout.bend as Layout',
             'import ../../spec/codec.bend as Codec', 'import ../../spec/nat_bytes.bend as N',
             'import ../compact/found.bend as F', 'import ../compact/arith.bend as A',
             'import ./spec_fixed.bend as FX', 'import ./vspec.bend as VS', 'import ./vfix.bend as VF', '',
             '# GENERATED by var_plist (codegen). Do not edit.',
             '# Lists of k unsigned elements of E words each, over a word list W (E = 1, 2, 4, 8):',
             '# the spec value, its parts, count and bytes, the progressive-list encoding, and',
             '# the inversion of the repeated parts.', '']


def elem_lib(E):
    B = 4 * E
    a = [f'a{i}' for i in range(E)]
    UV = 'S.UnsignedValue{P.UInt{' + ', '.join(a + ['0'] * (8 - E)) + '}}'
    L = []
    w = L.append

    def nest(k_case, leaf, nil, indent='    '):
        """match k / W nest: case 0n -> nil(-1); innermost -> leaf; Nil at level j -> nil(j)."""
        out = [f'  match k:', f'    case 0n: {nil(-1)}', f'    case 1n+{k_case}c:']
        ind = '      '
        cur = 'W'
        for j in range(E):
            nxt = 'rest' if j == E - 1 else f't{j}'
            out.append(f'{ind}match {cur}:')
            out.append(f'{ind}  case Nil{{}}: {nil(j)}')
            out.append(f'{ind}  case Con{{+a{j}, {k_case}{nxt}}}:' if k_case else f'{ind}  case Con{{+a{j}, {nxt}}}:')
            ind += '    '
            cur = nxt
        out.append(f'{ind}{leaf}')
        return out

    def lit(j):
        return '[' + ', '.join(a[:j]) + ']'

    w(f'def uS{E}() -> S.Schema: S.Unsigned{{{WIDTH[E]}}}')
    w('')
    w(f'def w{E}(k: Nat) -> Nat:')
    w('  match k:')
    w('    case 0n: 0n')
    w(f'    case 1n+c: {E}n+w{E}(c)')
    w('')
    w(f'def b{E}(k: Nat) -> Nat:')
    w('  match k:')
    w('    case 0n: 0n')
    w(f'    case 1n+c: {B}n+b{E}(c)')
    w('')
    w(f'def it{E}(k: Nat, W: List<&2, U32>) -> S.Value:')
    L.extend(nest('', f'S.Items{{{UV}, it{E}(c, rest)}}', lambda j: 'S.EmptyItems{}'))
    w('')
    w(f'def gp{E}(k: Nat, W: List<&2, U32>) -> +List<+List<U32>>:')
    L.extend(nest('', f'[{", ".join(a)}] <> gp{E}(c, rest)', lambda j: '[]'))
    w('')
    w(f'def nn{E}(k: Nat, W: List<&2, U32>) -> Nat:')
    L.extend(nest('', f'1n+nn{E}(c, rest)', lambda j: '0n'))
    w('')
    # the element's part at uS{E}() (a schema def: the part lemma is stated at the literal schema; carried by
    # subst so no conversion compares the two schemas under Codec.parts)
    AP = ', '.join('+' + x + ': U32' for x in a)
    SL = {1: 'P.U32Width{}', 2: 'P.U64{}', 4: 'P.U128{}', 8: 'P.U256{}'}[E]
    w(f'def eu{E}({AP}) -> {{Codec.parts({UV}, uS{E}()) == Some{{[S.Fixed{{FX.limbs([{", ".join(a)}])}}]}} : Maybe<&2, +List<S.Part>>}}:')
    w(f'  F.logic__subst(S.Schema, z => {{Codec.parts({UV}, z) == Some{{[S.Fixed{{FX.limbs([{", ".join(a)}])}}]}} : Maybe<&2, +List<S.Part>>}}, S.Unsigned{{{SL}}}, uS{E}(), {{==}}, {PART[E]}({", ".join(a)}))')
    w('')
    # parts
    w(f'law parts{E}:')
    w('  for +k: Nat')
    w('  for +W: List<&2, U32>')
    w(f'  {{Codec.parts(it{E}(k, W), S.Repeat{{uS{E}()}}) == Some{{FX.fparts(gp{E}(k, W))}} : Maybe<&2, +List<S.Part>>}}')
    w(f'def parts{E}(k, W):')
    WP = 'rest'
    for x in reversed(a):
        WP = f'Con{{{x}, {WP}}}'
    GOAL = lambda z: f'{{Codec.parts({z}, S.Repeat{{uS{E}()}}) == Some{{FX.fparts(gp{E}(1n+c, {WP}))}} : Maybe<&2, +List<S.Part>>}}'
    L.extend(nest('+ ', f'F.logic__subst(S.Value, z => {GOAL("z")}, S.Items{{{UV}, it{E}(c, rest)}}, it{E}(1n+c, {WP}), {{==}}, '
                  f'rcf({UV}, it{E}(c, rest), uS{E}(), FX.limbs([{", ".join(a)}]), '
                  f'FX.fparts(gp{E}(c, rest)), eu{E}({", ".join(a)}), parts{E}(c, rest)))', lambda j: '{==}'))
    w('')
    HL = f'{{Nat.is_le(w{E}(k), F.spec_common__length(U32, W)) == True{{}} : Bool}}'

    def absurd(goal):
        return lambda j: '{==}' if j < 0 else f'Empty.absurd({goal(j)}, F.logic__false_true(hl))'
    for nm, fn, tgt in [('cnt', lambda K, Wt: f'Codec.count(it{E}({K}, {Wt}))', 'k'), ('neq', lambda K, Wt: f'nn{E}({K}, {Wt})', 'k')]:
        w(f'law {nm}{E}:')
        w('  for +k: Nat')
        w('  for +W: List<&2, U32>')
        w(f'  for +hl: {HL}')
        w(f'  {{{fn("k", "W")} == k : Nat}}')
        w(f'def {nm}{E}(k, W, hl):')
        leaf = [f'%Equal.sym(Nat, {fn("c", "rest")}, c, {nm}{E}(c, rest, hl)) : {{1n+_ == 1n+c : Nat}}']
        body = nest('+ ', leaf[0], absurd(lambda j: f'{{{fn("1n+c", lit(j))} == 1n+c : Nat}}'))
        ind = body[-1][:len(body[-1]) - len(body[-1].lstrip())]
        L.extend(body)
        w(f'{ind}{{==}}')
        w('')
    w(f'law nle{E}:')
    w('  for +k: Nat')
    w('  for +W: List<&2, U32>')
    w(f'  {{Nat.is_le(nn{E}(k, W), k) == True{{}} : Bool}}')
    w(f'def nle{E}(k, W):')
    L.extend(nest('+ ', f'nle{E}(c, rest)', lambda j: '{==}'))
    w('')
    X = f'VS.wtake(w{E}(nn{E}(c, rest)), rest)'
    w(f'law flat{E}:')
    w('  for +k: Nat')
    w('  for +W: List<&2, U32>')
    w(f'  {{FX.flat(gp{E}(k, W)) == FX.limbs(VS.wtake(w{E}(nn{E}(k, W)), W)) : +List<U32>}}')
    w(f'def flat{E}(k, W):')
    body = nest('+ ', f'%Equal.sym(+List<U32>, FX.flat(gp{E}(c, rest)), FX.limbs({X}), flat{E}(c, rest)) : '
                      f'{{List.append(&2, U32, FX.limbs([{", ".join(a)}]), _) == FX.limbs({" <> ".join(a)} <> {X}) : +List<U32>}}',
                lambda j: '{==}')
    ind = body[-1][:len(body[-1]) - len(body[-1].lstrip())]
    L.extend(body)
    w(f'{ind}Equal.sym(+List<U32>, FX.limbs(VF.app([{", ".join(a)}], {X})), List.append(&2, U32, FX.limbs([{", ".join(a)}]), FX.limbs({X})), VF.limbs_app([{", ".join(a)}], {X}))')
    w('')
    w(f'law lenflat{E}:')
    w('  for +k: Nat')
    w('  for +W: List<&2, U32>')
    w(f'  {{List.length(&2, U32, FX.flat(gp{E}(k, W))) == b{E}(nn{E}(k, W)) : Nat}}')
    w(f'def lenflat{E}(k, W):')
    body = nest('+ ', f'%lenflat{E}(c, rest) : {{List.length(&2, U32, List.append(&2, U32, FX.limbs([{", ".join(a)}]), FX.flat(gp{E}(c, rest)))) == {B}n+_ : Nat}}',
                lambda j: '{==}')
    ind = body[-1][:len(body[-1]) - len(body[-1].lstrip())]
    L.extend(body)
    w(f'{ind}{{==}}')
    w('')
    w(f'''law bq{E}:
  for +c: Nat
  {{b{E}(c) == A.quad(w{E}(c)) : Nat}}
def bq{E}(c):
  match c:
    case 0n: {{==}}
    case 1n+ +p:
      %Equal.sym(Nat, b{E}(p), A.quad(w{E}(p)), bq{E}(p)) : {{{B}n+_ == A.quad({E}n+w{E}(p)) : Nat}}
      {{==}}

law mulb{E}:
  for +c: Nat
  {{Nat.mul(c, {B}n) == b{E}(c) : Nat}}
def mulb{E}(c):
  match c:
    case 0n: {{==}}
    case 1n+ +p:
      %Equal.sym(Nat, Nat.mul(p, {B}n), b{E}(p), mulb{E}(p)) : {{Nat.add({B}n, _) == b{E}(1n+p) : Nat}}
      {{==}}

# The progressive list of k elements over W is one variable part: the limbs of
# the first E k words of W.
def plenc{E}(+k: Nat, +W: List<&2, U32>, +hl: {HL}, +fit: {{N.fits(4n, b{E}(k)) == True{{}} : Bool}})
    -> {{Codec.bytes(Codec.parts(S.Sequence{{it{E}(k, W)}}, S.ProgressiveList{{uS{E}()}})) == Some{{FX.limbs(VS.wtake(w{E}(k), W))}} : Maybe<&2, +List<U32>>}}:
  +G = gp{E}(k, W)
  +e1 = Equal.trans(Nat, List.length(&2, U32, FX.flat(G)), b{E}(nn{E}(k, W)), b{E}(k), lenflat{E}(k, W),
    Equal.cong(Nat, Nat, z => b{E}(z), nn{E}(k, W), k, neq{E}(k, W, hl)))
  +fit2 = F.logic__subst(Nat, z => {{N.fits(4n, z) == True{{}} : Bool}}, b{E}(k), List.length(&2, U32, FX.flat(G)), Equal.sym(Nat, List.length(&2, U32, FX.flat(G)), b{E}(k), e1), fit)
  %Equal.sym(Maybe<&2, +List<S.Part>>, Codec.parts(it{E}(k, W), S.Repeat{{uS{E}()}}), Some{{FX.fparts(G)}}, parts{E}(k, W)) :
    {{Codec.bytes(Codec.aggregate(_, None{{}})) == Some{{FX.limbs(VS.wtake(w{E}(k), W))}} : Maybe<&2, +List<U32>>}}
  %Equal.sym(Maybe<&2, +List<U32>>, Layout.encoding(FX.fparts(G)), Some{{FX.flat(G)}}, VS.encoding_fparts(G, fit2)) :
    {{Codec.bytes(Codec.one(_, None{{}})) == Some{{FX.limbs(VS.wtake(w{E}(k), W))}} : Maybe<&2, +List<U32>>}}
  %Equal.sym(+List<U32>, FX.flat(G), FX.limbs(VS.wtake(w{E}(nn{E}(k, W)), W)), flat{E}(k, W)) :
    {{Codec.bytes(Codec.one(Some{{_}}, None{{}})) == Some{{FX.limbs(VS.wtake(w{E}(k), W))}} : Maybe<&2, +List<U32>>}}
  %Equal.sym(Nat, nn{E}(k, W), k, neq{E}(k, W, hl)) :
    {{Codec.bytes(Codec.one(Some{{FX.limbs(VS.wtake(w{E}(_), W))}}, None{{}})) == Some{{FX.limbs(VS.wtake(w{E}(k), W))}} : Maybe<&2, +List<U32>>}}
  {{==}}
''')
    # inversion
    A8 = [f'a{i}' for i in range(8)]
    UV8 = 'S.UnsignedValue{P.UInt{' + ', '.join(A8) + '}}'
    DIG = f'SP.prefix({B}n, SP.full_digits(P.UInt{{{", ".join(A8)}}}))'
    R = f'REPF{E}'
    IH = f'@+pb: +List<S.Part> -> {{Codec.parts(t, S.Repeat{{uS{E}()}}) == Some{{pb}} : Maybe<&2, +List<S.Part>>}} -> {R}(t, pb)'
    w(f'''def {R}(+its: S.Value, +ps: +List<S.Part>) -> Type:
  {{VS.allfix(ps) == True{{}} : Bool}} & {{Layout.fixed_size(ps) == b{E}(Codec.count(its)) : Nat}}

def rlen{E}(+P8: +List<U32>, +pb: +List<S.Part>, +t: S.Value, +l8: {{List.length(&2, U32, P8) == {B}n : Nat}},
    +hs: {{Layout.fixed_size(pb) == b{E}(Codec.count(t)) : Nat}})
    -> {{Nat.add(List.length(&2, U32, P8), Layout.fixed_size(pb)) == {B}n+b{E}(Codec.count(t)) : Nat}}:
  %Equal.sym(Nat, List.length(&2, U32, P8), {B}n, l8) : {{Nat.add(_, Layout.fixed_size(pb)) == {B}n+b{E}(Codec.count(t)) : Nat}}
  %Equal.sym(Nat, Layout.fixed_size(pb), b{E}(Codec.count(t)), hs) : {{{B}n+_ == {B}n+b{E}(Codec.count(t)) : Nat}}
  {{==}}

def rt2{E}(+P8: +List<U32>, +el: S.Value, +t: S.Value, +pb: +List<S.Part>, +l8: {{List.length(&2, U32, P8) == {B}n : Nat}}, r: {R}(t, pb))
    -> {R}(S.Items{{el, t}}, S.Fixed{{P8}} <> pb):
  (+ha, +hs) = r
  (ha, rlen{E}(P8, pb, t, l8, hs))

def rt{E}(+P8: +List<U32>, +el: S.Value, +t: S.Value, +ps: +List<S.Part>, +mB: Maybe<&2, +List<S.Part>>,
    +eB: {{Codec.parts(t, S.Repeat{{uS{E}()}}) == mB : Maybe<&2, +List<S.Part>>}},
    +l8: {{List.length(&2, U32, P8) == {B}n : Nat}},
    +e: {{Codec.concatenate(Some{{[S.Fixed{{P8}}]}}, mB) == Some{{ps}} : Maybe<&2, +List<S.Part>>}},
    ih: {IH})
    -> {R}(S.Items{{el, t}}, ps):
  match mB:
    case None{{}}: Empty.absurd({R}(S.Items{{el, t}}, ps), F.logic__none_some(+List<S.Part>, ps, e))
    case Some{{+pb}}:
      +eps = F.logic__some_inj(+List<S.Part>, S.Fixed{{P8}} <> pb, ps, e)
      %Equal.sym(+List<S.Part>, ps, S.Fixed{{P8}} <> pb, Equal.sym(+List<S.Part>, S.Fixed{{P8}} <> pb, ps, eps)) : {R}(S.Items{{el, t}}, _)
      rt2{E}(P8, el, t, pb, l8, ih(pb, eB))

def ru{E}({", ".join("+" + x + ": U32" for x in A8)}, +t: S.Value, +ps: +List<S.Part>, +b: Bool,
    +e: {{Codec.concatenate(Codec.one(SP.optional(b, {DIG}), Some{{{B}n}}), Codec.parts(t, S.Repeat{{uS{E}()}})) == Some{{ps}} : Maybe<&2, +List<S.Part>>}},
    ih: {IH})
    -> {R}(S.Items{{{UV8}, t}}, ps):
  match b:
    case False{{}}: Empty.absurd({R}(S.Items{{{UV8}, t}}, ps), F.logic__none_some(+List<S.Part>, ps, e))
    case True{{}}: rt{E}({DIG}, {UV8}, t, ps, Codec.parts(t, S.Repeat{{uS{E}()}}), {{==}}, {{==}}, e, ih)
''')
    w(f'law rep_facts{E}:')
    w('  for +its: S.Value')
    w('  for +ps: +List<S.Part>')
    w(f'  for +e: {{Codec.parts(its, S.Repeat{{uS{E}()}}) == Some{{ps}} : Maybe<&2, +List<S.Part>>}}')
    w(f'  {R}(its, ps)')
    w(f'def rep_facts{E}(its, ps, e):')
    w('  match its:')
    w('    case S.EmptyItems{}:')
    w('      +eps = F.logic__some_inj(+List<S.Part>, [], ps, e)')
    w(f'      %Equal.sym(+List<S.Part>, ps, [], Equal.sym(+List<S.Part>, [], ps, eps)) : {R}(S.EmptyItems{{}}, _)')
    w('      ({==}, {==})')
    w(f'    case S.Items{{S.UnsignedValue{{P.UInt{{{", ".join("+" + x for x in A8)}}}}}, +t}}:')
    w(f'      ru{E}({", ".join(A8)}, t, ps, SP.uint_domain({WIDTH[E]}, P.UInt{{{", ".join(A8)}}}), e, pb => eb => rep_facts{E}(t, pb, eb))')
    others = [('S.BooleanValue{+b}', 'S.BooleanValue{b}'), ('S.UnsignedValue{+u}', 'S.UnsignedValue{u}'), ('S.BytesValue{+xs}', 'S.BytesValue{xs}'),
              ('S.BitsValue{+bs}', 'S.BitsValue{bs}'), ('S.Sequence{+it}', 'S.Sequence{it}'),
              ('S.Items{S.BooleanValue{+b}, +t}', 'S.Items{S.BooleanValue{b}, t}'), ('S.Items{S.BytesValue{+xs}, +t}', 'S.Items{S.BytesValue{xs}, t}'),
              ('S.Items{S.BitsValue{+bs}, +t}', 'S.Items{S.BitsValue{bs}, t}'), ('S.Items{S.Sequence{+it}, +t}', 'S.Items{S.Sequence{it}, t}'),
              ('S.Items{S.Items{+hd, +tl}, +t}', 'S.Items{S.Items{hd, tl}, t}'), ('S.Items{S.EmptyItems{}, +t}', 'S.Items{S.EmptyItems{}, t}'),
              ('S.Items{S.Selected{+sel, +sv}, +t}', 'S.Items{S.Selected{sel, sv}, t}'), ('S.Items{S.NullValue{}, +t}', 'S.Items{S.NullValue{}, t}'),
              ('S.Selected{+sel, +sv}', 'S.Selected{sel, sv}'), ('S.NullValue{}', 'S.NullValue{}')]
    for pat, term in others:
        w(f'    case {pat}: Empty.absurd({R}({term}, ps), F.logic__none_some(+List<S.Part>, ps, e))')
    w('')
    return L


# one element of a repeat, stated as Codec.parts(Items{h, t}, Repeat{s}) over variables: the cat_fixed step
# met that goal only by evaluating the element's parts (a uint's literal zero limbs: ~375 k steps each,
# checker_findings item 1/2)
RCF = ['def rcf(+h: S.Value, +t: S.Value, +s: S.Schema, +xs: +List<U32>, +ps: +List<S.Part>,',
       '    +ea: {Codec.parts(h, s) == Some{[S.Fixed{xs}]} : Maybe<&2, +List<S.Part>>}, +eb: {Codec.parts(t, S.Repeat{s}) == Some{ps} : Maybe<&2, +List<S.Part>>})',
       '    -> {Codec.parts(S.Items{h, t}, S.Repeat{s}) == Some{S.Fixed{xs} <> ps} : Maybe<&2, +List<S.Part>>}:',
       '  FX.cat_fixed(Codec.parts(h, s), xs, Codec.parts(t, S.Repeat{s}), ps, ea, eb)', '']


def elems_text():
    L = list(ELEM_HEAD) + RCF
    for E in (1, 2, 4, 8):
        L += [f'# ---- elements of {E} word(s) ' + '-' * 60, '']
        L += elem_lib(E)
    return '\n'.join(L) + '\n'


# ---- per-name files --------------------------------------------------------------------------------

HEAD = ['import Base', 'import ../../src/buffer.bend as B', 'import ../../src/obj.bend as O',
        'import ../../types/generic_obj.bend as T', 'import ../../types/schema.bend as S', 'import ../../types/primitive.bend as P',
        'import ../compact/found.bend as FD', 'import ../compact/arith.bend as A', 'import ../../proofs/nat_order.bend as Order',
        'import ../../spec/primitives.bend as SP', 'import ../../spec/layout.bend as Layout', 'import ../../spec/codec.bend as Codec',
        'import ../../spec/decoding_relation.bend as Decoding', 'import ../../spec/nat_bytes.bend as N',
        'import ./generic_specs.bend as GS', 'import ./spec_fixed.bend as FX', 'import ./vspec.bend as VS', 'import ./vbuf.bend as VB',
        'import ./vu32.bend as VU', 'import ./vcopy.bend as VC', 'import ./vdepth.bend as VD', 'import ./vlist.bend as VL',
        'import ./vfits.bend as VFT', 'import ./var_elems.bend as EL', 'import ./var_plist_zeros.bend as Z']

BIG_NOTE = ['# BIG (checkq --big): a progressive list has no length limit, so the list storage',
            '# is B.zeros(u) at every depth u; var_plist_zeros.bend identifies it with',
            '# Array.new(U32, to_nat(u), 0) case by case, comparing closed Array.new trees of up to',
            '# 2^26 leaves: stock Bend normalizes them; the pinned rigid-memo checker compares the identical calls rigidly.']


def zeros_text():
    L = ['import Base', 'import ../../src/buffer.bend as B', 'import ../compact/found.bend as FD', '',
         '# GENERATED by var_plist (codegen). Do not edit.'] + BIG_NOTE + [
         '# zs: the runtime zero array of depth u is Array.new(U32, to_nat(u), 0), for every u.', '']
    for j in range(26, -1, -1):
        L.append(f'def zc{j}(+du: U32, +b: Bool, +eb: {{U32.is_eq(du, {j}) == b : Bool}}) -> {{B.zeros_c{j}(b, du) == Array.new(U32, U32.to_nat(du), 0) : Array<U32>}}:')
        L.append('  match b:')
        L.append('    case True{}:')
        L.append(f'      %Equal.sym(U32, du, {j}, FD.u32alg__eq_of(du, {j}, eb)) : {{B.zeros_c{j}(True{{}}, du) == Array.new(U32, U32.to_nat(_), 0) : Array<U32>}}')
        L.append(f'      %Equal.sym(Nat, U32.to_nat({j}), {j}n, {{==}}) : {{B.zeros_c{j}(True{{}}, du) == Array.new(U32, _, 0) : Array<U32>}}')
        L.append('      {==}')
        L.append('    case False{}: ' + ('{==}' if j == 26 else f'zc{j + 1}(du, U32.is_eq(du, {j + 1}), {{==}})'))
        L.append('')
    L.append('def zs(+du: U32) -> {B.zeros(du) == Array.new(U32, U32.to_nat(du), 0) : Array<U32>}: zc0(du, U32.is_eq(du, 0), {==})')
    return '\n'.join(L) + '\n'


def fname(X, part=''):
    return ROOT / f'proofs/obj/var_plist_{X}{part}.bend'


HNN = '{U32.is_le(n, VB.NMAX()) == True{} : Bool}'
HYP = ('+pf: {FD.array__perfect(U32, d, t) == True{} : Bool}, +hd: {Nat.is_lt(d, 31n) == True{} : Bool},\n'
       '    +hn: {Nat.is_le(U32.to_nat(n), A.quad(VB.pw(d))) == True{} : Bool}, +hN: ' + HNN)
LAWHYP = ['  for +d: Nat', '  for +t: FD.array__Tree<U32>', '  for +n: U32',
          '  for +pf: {FD.array__perfect(U32, d, t) == True{} : Bool}', '  for +hd: {Nat.is_lt(d, 31n) == True{} : Bool}',
          '  for +hn: {Nat.is_le(U32.to_nat(n), A.quad(VB.pw(d))) == True{} : Bool}', '  for +hN: ' + HNN]


def deep_helpers():
    """nwm / hsg / lim_eq_g of vlist.bend without the depth bound: from n <= NMAX (31 + n <= UMAX) the list storage is at most 2^30 words."""
    vl = (ROOT / 'proofs/obj/vlist.bend').read_text()
    a = vl.index('def lim_eq_g(')
    b = vl.index('\n\n', a)
    lim = vl[a:b]
    HY = '{Nat.is_le(VC.YL(n), U32.to_nat(VB.UMAX())) == True{} : Bool}'
    lim = lim.replace('def lim_eq_g(', 'def limU(').replace('    +hd: {Nat.is_lt(d, 28n) == True{} : Bool}, +hn:', '    +hn:')
    lim = lim.replace('    +em: {U32.to_nat(n) == A.quad(m) : Nat})', '    +hy: ' + HY + ', +em: {U32.to_nat(n) == A.quad(m) : Nat})', 1)
    lim = lim.replace('hrg(d, n, hd, hn)', 'VC.hrgU(n, hy)').replace('hsg(d, n, m, hd, hn, em)', 'hsgU(d, n, m, hn, hy, em)').replace('nwm(d, n, m, hd, hn, em)', 'nwmU(n, m, hy, em)')
    assert 'hd,' not in lim and 'hd)' not in lim, lim
    lim = lim.replace('F.', 'FD.')
    lim = re.sub(r'(?<![\w.])(MMg|DZ)\(', r'VL.\1(', lim)
    return f'''# n <= NMAX: 31 + n <= UMAX (the decoder's list storage has depth at most 30, whatever the tree's depth).
def hyN(+n: U32, +hN: {HNN}) -> {HY}:
  VC.hyW(0n, n, FD.logic__subst(Bool, z => {{z == True{{}} : Bool}}, U32.is_le(n, VB.NMAX()), Nat.is_le(U32.to_nat(n), U32.to_nat(VB.NMAX())), VB.le_u32n(n, VB.NMAX()), hN))

def nwmU(+n: U32, +m: Nat, +hy: {HY}, +em: {{U32.to_nat(n) == A.quad(m) : Nat}}) -> {{VC.NW(n) == m : Nat}}:
  %Equal.sym(Nat, VC.NW(n), VD.s_rng(2n, 3n+U32.to_nat(n)), VC.eNWu(n, hy)) : {{_ == m : Nat}}
  %Equal.sym(Nat, U32.to_nat(n), A.quad(m), em) : {{VD.s_rng(2n, 3n+_) == m : Nat}}
  VL.rng2_q(m)

def hsgU(+d: Nat, +n: U32, +m: Nat, +hn: {{Nat.is_le(U32.to_nat(n), A.quad(VB.pw(d))) == True{{}} : Bool}}, +hy: {HY},
    +em: {{U32.to_nat(n) == A.quad(m) : Nat}}) -> {{Nat.is_le(Nat.add(VC.NW(n), 0n), VB.pw(d)) == True{{}} : Bool}}:
  %Equal.sym(Nat, Nat.add(VC.NW(n), 0n), VC.NW(n), FD.nat__add_zero(VC.NW(n))) : {{Nat.is_le(_, VB.pw(d)) == True{{}} : Bool}}
  %Equal.sym(Nat, VC.NW(n), m, nwmU(n, m, hy, em)) : {{Nat.is_le(_, VB.pw(d)) == True{{}} : Bool}}
  VC.quad_inv(m, VB.pw(d), FD.logic__subst(Nat, z => {{Nat.is_le(z, A.quad(VB.pw(d))) == True{{}} : Bool}}, U32.to_nat(n), A.quad(m), em, hn))

''' + lim + '\n'


def dec_text(X):
    lp, E = NAMES[X]
    B = 4 * E
    Tn = f'T.{X}'
    L = list(HEAD) + ['', '# GENERATED by var_plist (codegen). Do not edit.',
                      f'# {X} = ProgressiveList[uint{32 * E}]: the validator, the decoder, and the spec',
                      '# relation of the decoded value, for every buffer B.Buf{thaw(t), n} on a perfect',
                      '# word tree t of depth d < 31 holding n <= 4 2^d bytes, n <= NMAX.'] + BIG_NOTE + ['']
    DM = f'B.Buf & Maybe<&1, O.Words>'
    L.append(deep_helpers())
    L.append(f'''def BF(t: FD.array__Tree<U32>, +n: U32) -> B.Buf: B.Buf{{FD.array__thaw(U32, t), n}}
def CHK(+n: U32) -> Bool: Bool.and(U32.is_eq(n, U32.mul(U32.div(n, {B}), {B})), True{{}})
def vB() -> Word(31n): FD.spec_numeric__from_nat(31n, {B}n)
def CQ(+n: U32) -> Nat: U32.to_nat(U32.div(n, {B}))
def M(+n: U32) -> Nat: EL.w{E}(CQ(n))
def OBJ(+t: FD.array__Tree<U32>, +n: U32) -> O.Words: O.Words{{FD.array__thaw(U32, VL.MMg(t, n)), n}}
def VW(+t: FD.array__Tree<U32>, +n: U32) -> +List<U32>: VS.bt(U32.to_nat(n), FX.limbs(FD.array__slots(U32, t)))
def VAL(+t: FD.array__Tree<U32>, +n: U32) -> S.Value: S.Sequence{{EL.it{E}(CQ(n), FD.array__slots(U32, VL.MMg(t, n)))}}

# The validator returns the buffer and CHK(n): a whole number of elements.
law ok_eval:
  for +t: FD.array__Tree<U32>
  for +n: U32
  {{T.{lp}_ok(BF(t, n), 0, n) == (BF(t, n), CHK(n)) : B.Buf & Bool}}
def ok_eval(t, n): {{==}}

def eLc(+n: U32, +hc: {{CHK(n) == True{{}} : Bool}}) -> {{U32.to_nat(n) == EL.b{E}(CQ(n)) : Nat}}:
  Equal.trans(Nat, U32.to_nat(n), Nat.mul(CQ(n), U32.to_nat({B})), EL.b{E}(CQ(n)), VL.whole_t1(n, {B}, vB(), {{==}}, {{==}}, {{==}}, hc), EL.mulb{E}(CQ(n)))

def eq(+n: U32, +hc: {{CHK(n) == True{{}} : Bool}}) -> {{U32.to_nat(n) == A.quad(M(n)) : Nat}}:
  Equal.trans(Nat, U32.to_nat(n), EL.b{E}(CQ(n)), A.quad(M(n)), eLc(n, hc), EL.bq{E}(CQ(n)))
''')
    L.append(f'''
def acc_go(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, {HYP}, +hc: {{CHK(n) == True{{}} : Bool}})
    -> {{{Tn}_decode(BF(t, n), n) == (BF(t, n), Some{{OBJ(t, n)}}) : {DM}}}:
  +hy = hyN(n, hN)
  +hz = VC.dz30(n, hy)
  +ez = FD.logic__subst(Nat, z => {{B.zeros(B.words_depth_u(VC.WZ(n))) == Array.new(U32, z, 0) : Array<U32>}}, U32.to_nat(B.words_depth_u(VC.WZ(n))), VL.DZ(n), VD.wdu(VC.WZ(n)), Z.zs(B.words_depth_u(VC.WZ(n))))
  %Equal.sym(Bool, CHK(n), True{{}}, hc) : {{{Tn}_built(n, (BF(t, n), _)) == (BF(t, n), Some{{OBJ(t, n)}}) : {DM}}}
  %Equal.sym(B.Buf & O.Words, O.copy_in(BF(t, n), 0, n), (BF(t, n), OBJ(t, n)),
      VC.copy_in_ok(d, t, n, 0, 0n, n, VL.DZ(n), pf, hd, FD.nat__le_lt_trans(VL.DZ(n), 30n, 31n, hz, {{==}}), ez, {{==}}, {{==}},
        VL.and3_q(n, M(n), eq(n, hc)), hsgU(d, n, M(n), hn, hy, eq(n, hc)), VC.hrgU(n, hy))) :
    {{{Tn}_some(_) == (BF(t, n), Some{{OBJ(t, n)}}) : {DM}}}
  {{==}}

# Every buffer the validator accepts decodes to OBJ(t, n), a copy of its words.
law decode_accept:
{chr(10).join(LAWHYP)}
  for +hchk: {{CHK(n) == True{{}} : Bool}}
  {{{Tn}_decode(BF(t, n), n) == (BF(t, n), Some{{OBJ(t, n)}}) : {DM}}}
def decode_accept(d, t, n, pf, hd, hn, hN, hchk): acc_go(d, t, n, pf, hd, hn, hN, hchk)

def hl_mm(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +hy: {{Nat.is_le(VC.YL(n), U32.to_nat(VB.UMAX())) == True{{}} : Bool}},
    +hn: {{Nat.is_le(U32.to_nat(n), A.quad(VB.pw(d))) == True{{}} : Bool}}, +hc: {{CHK(n) == True{{}} : Bool}})
    -> {{Nat.is_le(M(n), FD.spec_common__length(U32, FD.array__slots(U32, VL.MMg(t, n)))) == True{{}} : Bool}}:
  %Equal.sym(Nat, FD.spec_common__length(U32, FD.array__slots(U32, VL.MMg(t, n))), VB.pw(VL.DZ(n)),
      FD.array__slots_length(U32, VL.DZ(n), VL.MMg(t, n), VB.mone_perfect(VC.NW(n), 0n, 0n, VL.DZ(n), VC.ZT(VL.DZ(n)), t, FD.array__trep_perfect(U32, VL.DZ(n), 0)))) :
    {{Nat.is_le(M(n), _) == True{{}} : Bool}}
  %nwmU(n, M(n), hy, eq(n, hc)) : {{Nat.is_le(_, VB.pw(VL.DZ(n))) == True{{}} : Bool}}
  FD.logic__subst(Nat, z => {{Nat.is_le(z, VB.pw(VL.DZ(n))) == True{{}} : Bool}}, Nat.add(VC.NW(n), 0n), VC.NW(n), FD.nat__add_zero(VC.NW(n)), VC.hrgU(n, hy))

# The bytes of every accepted buffer are the spec encoding of the decoded value.
law decode_spec:
{chr(10).join(LAWHYP)}
  for +hchk: {{CHK(n) == True{{}} : Bool}}
  Decoding.decodes(GS.{X}(), VW(t, n), VAL(t, n))
def decode_spec(d, t, n, pf, hd, hn, hN, hchk):
  +hy = hyN(n, hN)
  +W = FD.array__slots(U32, VL.MMg(t, n))
  +fit = FD.logic__subst(Nat, z => {{N.fits(4n, z) == True{{}} : Bool}}, U32.to_nat(n), EL.b{E}(CQ(n)), eLc(n, hchk), VL.hfitA(n))
  Equal.trans(Maybe<&2, +List<U32>>, Codec.encoding_for_legal_type(GS.{X}(), VAL(t, n)), Some{{FX.limbs(VS.wtake(M(n), W))}}, Some{{VW(t, n)}},
    EL.plenc{E}(CQ(n), W, hl_mm(d, t, n, hy, hn, hchk), fit),
    Equal.cong(+List<U32>, Maybe<&2, +List<U32>>, z => Some{{z}}, FX.limbs(VS.wtake(M(n), W)), VW(t, n), limU(d, t, n, M(n), pf, hn, hy, eq(n, hchk))))
''')
    return '\n'.join(L) + '\n'


def uniq_text(X):
    D = fname(X).name
    return '\n'.join(['import Base', 'import ../../types/schema.bend as S', 'import ../../spec/decoding_relation.bend as Decoding',
                      'import ../compact/found.bend as FD', 'import ../compact/arith.bend as A', 'import ./vbuf.bend as VB',
                      'import ./generic_specs.bend as GS', f'import ./{D} as DC', 'import ../../proofs/decode_unique.bend as DCO', '',
                      '# GENERATED by var_plist (codegen). Do not edit.'] + BIG_NOTE + [
        '# Every spec value of an accepted buffer\'s bytes is the decoded value.',
        'law decode_unique:'] + LAWHYP + [
        '  for +hchk: {DC.CHK(n) == True{} : Bool}', '  for +v: S.Value',
        f'  for spec: Decoding.decodes(GS.{X}(), DC.VW(t, n), v)', '  {v == DC.VAL(t, n) : S.Value}',
        'def decode_unique(d, t, n, pf, hd, hn, hN, hchk, v, spec):',
        f'  DCO.valid_unique(GS.{X}(), DC.VW(t, n), v, DC.VAL(t, n), {{==}}, spec, DC.decode_spec(d, t, n, pf, hd, hn, hN, hchk))']) + '\n'


VCTORS = [('BooleanValue', ['b0']), ('UnsignedValue', ['u0']), ('BytesValue', ['xs0']), ('BitsValue', ['bs0']),
          ('Sequence', ['it0']), ('Items', ['hd0', 'tl0']), ('EmptyItems', []), ('Selected', ['sel0', 'sv0']), ('NullValue', [])]


def rej_text(X):
    lp, E = NAMES[X]
    B = 4 * E
    Tn = f'T.{X}'
    D = fname(X).name
    MB = 'Maybe<&2, +List<U32>>'
    L = list(HEAD) + ['import ./dk.bend as DK', f'import ./{D} as DC', '', '# GENERATED by var_plist (codegen). Do not edit.',
                      f'# Rejection of {X}: every byte string the spec relates to a value is a whole',
                      '# number of elements (inv_v), so when CHK(n) is False no value is related to the',
                      '# buffer\'s bytes (decode_reject), and the decoder returns None (decode_none).'] + BIG_NOTE + ['']
    w = L.append
    w(f'def FACTS(bs: +List<U32>) -> Type: DK.Ex(Nat, k => DK.P2({{List.length(&2, U32, bs) == EL.b{E}(k) : Nat}}, {{k == k : Nat}}))')
    w('')
    RE = f'S.Repeat{{EL.uS{E}()}}'
    w(f'''def inv_m4(+its: S.Value, +bs: +List<U32>, +ps: +List<S.Part>, +em3: {{Codec.parts(its, {RE}) == Some{{ps}} : Maybe<&2, +List<S.Part>>}},
    +m4: {MB}, +em4: {{Layout.encoding(ps) == m4 : {MB}}}, +e: {{Codec.bytes(Codec.one(m4, None{{}})) == Some{{bs}} : {MB}}}) -> FACTS(bs):
  match m4:
    case None{{}}: Empty.absurd(FACTS(bs), FD.logic__none_some(+List<U32>, bs, e))
    case Some{{+ys}}:
      +lys = Equal.trans(Nat, List.length(&2, U32, ys), Layout.fixed_size(ps), EL.b{E}(Codec.count(its)),
        VS.enc_len(ps, ys, Pair.fst({{VS.allfix(ps) == True{{}} : Bool}}, {{Layout.fixed_size(ps) == EL.b{E}(Codec.count(its)) : Nat}}, EL.rep_facts{E}(its, ps, em3)), em4),
        Pair.snd({{VS.allfix(ps) == True{{}} : Bool}}, {{Layout.fixed_size(ps) == EL.b{E}(Codec.count(its)) : Nat}}, EL.rep_facts{E}(its, ps, em3)))
      (Codec.count(its), (FD.logic__subst(+List<U32>, z => {{List.length(&2, U32, z) == EL.b{E}(Codec.count(its)) : Nat}}, ys, bs, FD.logic__some_inj(+List<U32>, ys, bs, e), lys), {{==}}))

def inv_m(+its: S.Value, +bs: +List<U32>, +m3: Maybe<&2, +List<S.Part>>, +em3: {{Codec.parts(its, {RE}) == m3 : Maybe<&2, +List<S.Part>>}},
    +e: {{Codec.bytes(Codec.aggregate(m3, None{{}})) == Some{{bs}} : {MB}}}) -> FACTS(bs):
  match m3:
    case None{{}}: Empty.absurd(FACTS(bs), FD.logic__none_some(+List<U32>, bs, e))
    case Some{{+ps}}: inv_m4(its, bs, ps, em3, Layout.encoding(ps), {{==}}, e)

# Every byte string the spec relates to a value is a whole number of elements.
law inv_v:
  for +v: S.Value
  for +bs: +List<U32>
  for +e: {{Codec.encoding_for_legal_type(GS.{X}(), v) == Some{{bs}} : {MB}}}
  FACTS(bs)
def inv_v(v, bs, e):
  match v:''')
    for c, args in VCTORS:
        pat = f'S.{c}{{' + ', '.join('+' + x for x in args) + '}'
        if c == 'Sequence':
            w(f'    case S.Sequence{{+its}}: inv_m(its, bs, Codec.parts(its, {RE}), {{==}}, e)')
        else:
            w(f'    case {pat}: Empty.absurd(FACTS(bs), FD.logic__none_some(+List<U32>, bs, e))')
    w(f'''
law len_eq:
  for +W: List<&2, U32>
  {{List.length(&2, U32, W) == FD.spec_common__length(U32, W) : Nat}}
def len_eq(W):
  match W:
    case Nil{{}}: {{==}}
    case Con{{+h, +t}}:
      %Equal.sym(Nat, List.length(&2, U32, t), FD.spec_common__length(U32, t), len_eq(t)) : {{1n+_ == 1n+FD.spec_common__length(U32, t) : Nat}}
      {{==}}

def SL(t: FD.array__Tree<U32>) -> List<&2, U32>: FD.array__slots(U32, t)

def lenS(+d: Nat, +t: FD.array__Tree<U32>, +pf: {{FD.array__perfect(U32, d, t) == True{{}} : Bool}})
    -> {{List.length(&2, U32, FX.limbs(SL(t))) == A.quad(VB.pw(d)) : Nat}}:
  %Equal.sym(Nat, List.length(&2, U32, FX.limbs(SL(t))), FX.wlen(SL(t)), VS.len_limbs(SL(t))) : {{_ == A.quad(VB.pw(d)) : Nat}}
  %Equal.sym(Nat, FX.wlen(SL(t)), A.quad(List.length(&2, U32, SL(t))), VS.wlen_quad(SL(t))) : {{_ == A.quad(VB.pw(d)) : Nat}}
  %Equal.sym(Nat, List.length(&2, U32, SL(t)), VB.pw(d), Equal.trans(Nat, List.length(&2, U32, SL(t)), FD.spec_common__length(U32, SL(t)), VB.pw(d), len_eq(SL(t)), FD.array__slots_length(U32, d, t, pf))) : {{A.quad(_) == A.quad(VB.pw(d)) : Nat}}
  {{==}}

def lenVW(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +pf: {{FD.array__perfect(U32, d, t) == True{{}} : Bool}},
    +hn: {{Nat.is_le(U32.to_nat(n), A.quad(VB.pw(d))) == True{{}} : Bool}})
    -> {{List.length(&2, U32, DC.VW(t, n)) == U32.to_nat(n) : Nat}}:
  VS.bt_len(U32.to_nat(n), FX.limbs(SL(t)),
    FD.logic__subst(Nat, z => {{Nat.is_le(U32.to_nat(n), z) == True{{}} : Bool}}, A.quad(VB.pw(d)), List.length(&2, U32, FX.limbs(SL(t))), Equal.sym(Nat, List.length(&2, U32, FX.limbs(SL(t))), A.quad(VB.pw(d)), lenS(d, t, pf)), hn))

def rej_f(+d: Nat, +t: FD.array__Tree<U32>, +n: U32, +pf: {{FD.array__perfect(U32, d, t) == True{{}} : Bool}},
    +hn: {{Nat.is_le(U32.to_nat(n), A.quad(VB.pw(d))) == True{{}} : Bool}}, +hchk: {{DC.CHK(n) == False{{}} : Bool}},
    facts: FACTS(DC.VW(t, n))) -> Empty:
  (+k, +pr) = facts
  (+hl, +hkk) = pr
  +en = Equal.trans(Nat, U32.to_nat(n), List.length(&2, U32, DC.VW(t, n)), EL.b{E}(k), Equal.sym(Nat, List.length(&2, U32, DC.VW(t, n)), U32.to_nat(n), lenVW(d, t, n, pf, hn)), hl)
  +ec = Equal.trans(Nat, U32.to_nat(n), EL.b{E}(k), Nat.mul(k, U32.to_nat({B})), en, Equal.sym(Nat, Nat.mul(k, {B}n), EL.b{E}(k), EL.mulb{E}(k)))
  +ht = VL.whole_i1(n, {B}, DC.vB(), {{==}}, {{==}}, {{==}}, k, ec)
  FD.logic__true_false(Equal.trans(Bool, True{{}}, DC.CHK(n), False{{}}, Equal.sym(Bool, DC.CHK(n), True{{}}, ht), hchk))

# When the validator refuses, no value is related to the buffer's bytes.
law decode_reject:
  for +d: Nat
  for +t: FD.array__Tree<U32>
  for +n: U32
  for +pf: {{FD.array__perfect(U32, d, t) == True{{}} : Bool}}
  for +hn: {{Nat.is_le(U32.to_nat(n), A.quad(VB.pw(d))) == True{{}} : Bool}}
  for +hchk: {{DC.CHK(n) == False{{}} : Bool}}
  Decoding.outside_image(GS.{X}(), DC.VW(t, n))
def decode_reject(d, t, n, pf, hn, hchk):
  v => e => rej_f(d, t, n, pf, hn, hchk, inv_v(v, DC.VW(t, n), e))

# When the validator refuses, the decoder returns None and the buffer.
law decode_none:
  for +t: FD.array__Tree<U32>
  for +n: U32
  for +hchk: {{DC.CHK(n) == False{{}} : Bool}}
  {{{Tn}_decode(DC.BF(t, n), n) == (DC.BF(t, n), None{{}}) : B.Buf & Maybe<&1, O.Words>}}
def decode_none(t, n, hchk):
  %Equal.sym(Bool, DC.CHK(n), False{{}}, hchk) : {{{Tn}_built(n, (DC.BF(t, n), _)) == (DC.BF(t, n), None{{}}) : B.Buf & Maybe<&1, O.Words>}}
  {{==}}
''')
    return '\n'.join(L) + '\n'


def enc_text(X):
    lp, E = NAMES[X]
    B = 4 * E
    Tn = f'T.{X}'
    D = fname(X).name
    L = list(HEAD) + ['import ./venc.bend as VE', f'import ./{D} as DC', '', '# GENERATED by var_plist (codegen). Do not edit.',
                      f'# The encoder of {X}: for every object O.Words{{thaw(T), N}} whose storage T is a',
                      '# perfect tree of depth dw < 31 holding its c elements (N = 4 E c bytes), the encoder',
                      '# returns the object and B.Buf{thaw(OUTP(N, T)), N} (encode_eval), and the bytes',
                      '# of that buffer are the spec encoding of the object\'s value (encode_spec).'] + BIG_NOTE + ['']
    O_ = 'O.Words{FD.array__thaw(U32, T), N}'
    RHS = f'({O_}, B.Buf{{FD.array__thaw(U32, VL.OUTP(N, T)), N}})'
    TY = 'O.Words & B.Buf'
    H = ('+dw: Nat, +T: FD.array__Tree<U32>, +N: U32, +c: Nat,\n'
         '    +pfT: {FD.array__perfect(U32, dw, T) == True{} : Bool}, +hdw: {Nat.is_lt(dw, 31n) == True{} : Bool},\n'
         f'    +ec: {{U32.to_nat(N) == EL.b{E}(c) : Nat}}, +hroom: {{Nat.is_le(EL.w{E}(c), VB.pw(dw)) == True{{}} : Bool}}')
    LH = ['  for +dw: Nat', '  for +T: FD.array__Tree<U32>', '  for +N: U32', '  for +c: Nat',
          '  for +pfT: {FD.array__perfect(U32, dw, T) == True{} : Bool}', '  for +hdw: {Nat.is_lt(dw, 31n) == True{} : Bool}',
          f'  for +ec: {{U32.to_nat(N) == EL.b{E}(c) : Nat}}', f'  for +hroom: {{Nat.is_le(EL.w{E}(c), VB.pw(dw)) == True{{}} : Bool}}']
    m = f'EL.w{E}(c)'
    L.append(f'''def em(+N: U32, +c: Nat, +ec: {{U32.to_nat(N) == EL.b{E}(c) : Nat}}) -> {{U32.to_nat(N) == A.quad(EL.w{E}(c)) : Nat}}:
  Equal.trans(Nat, U32.to_nat(N), EL.b{E}(c), A.quad(EL.w{E}(c)), ec, EL.bq{E}(c))

def XE(+c: Nat, +W: List<&2, U32>) -> S.Value: S.Sequence{{EL.it{E}(c, W)}}

# The encoder returns the object and the buffer of OUTP(N, T), N bytes.
law encode_eval:
{chr(10).join(LH)}
  {{{Tn}_encode({O_}) == {RHS} : {TY}}}
def encode_eval(dw, T, N, c, pfT, hdw, ec, hroom):
  +e4 = em(N, c, ec)
  +hdw31 = hdw
  +hDO = VL.hDOA(dw, N, {m}, hdw, e4, hroom)
  %Equal.sym(Array<U32> & U32, Array.size(U32, FD.array__thaw(U32, T)), (FD.array__thaw(U32, T), FD.u32__pow2u(dw)), FD.array__size_thaw(U32, dw, T, pfT)) :
    {{{Tn}_enc_sized(O.wsz_pick(N, _)) == {RHS} : {TY}}}
  %Equal.sym(Bool, U32.is_le(VC.nwu(N), FD.u32__pow2u(dw)), True{{}}, VE.le_room(N, dw, hdw31, VL.roomwA(dw, N, {m}, hdw, e4, hroom))) :
    {{{Tn}_enc_sized(({O_}, O.pick(_, N, 2147483648))) == {RHS} : {TY}}}
  %Equal.sym(Array<U32>, B.zeros(B.words_depth_u(VC.nwu(N))), Array.new(U32, VL.DO(N), 0),
      FD.logic__subst(Nat, z => {{B.zeros(B.words_depth_u(VC.nwu(N))) == Array.new(U32, z, 0) : Array<U32>}}, U32.to_nat(B.words_depth_u(VC.nwu(N))), VL.DO(N), VD.wdu(VC.nwu(N)), Z.zs(B.words_depth_u(VC.nwu(N))))) :
    {{{Tn}_enc_put(N, T.{lp}_putn(_, 0, {O_})) == {RHS} : {TY}}}
  %Equal.sym(Array<U32>, Array.new(U32, VL.DO(N), 0), FD.array__thaw(U32, VC.ZT(VL.DO(N))), FD.array__new(U32, VL.DO(N), 0)) :
    {{{Tn}_enc_put(N, T.{lp}_putn(_, 0, {O_})) == {RHS} : {TY}}}
  %Equal.sym(Array<U32> & O.Words, O.put_words(FD.array__thaw(U32, VC.ZT(VL.DO(N))), 0, {O_}), (FD.array__thaw(U32, VL.OUTP(N, T)), {O_}),
      VE.put_words_ok(VL.DO(N), dw, VC.ZT(VL.DO(N)), T, 0, 0n, N, FD.array__trep_perfect(U32, VL.DO(N), 0), pfT,
        FD.nat__le_lt_trans(VL.DO(N), dw, 31n, hDO, hdw31), hdw31, {{==}}, {{==}}, VL.and3_q(N, {m}, e4),
        VL.roomwA(dw, N, {m}, hdw, e4, hroom), VL.hdstoA(dw, N, {m}, hdw, e4, hroom))) :
    {{{Tn}_enc_put(N, O.pwn(_)) == {RHS} : {TY}}}
  {{==}}

# The bytes of the encoder's buffer are the spec encoding of the object's value.
law encode_spec:
{chr(10).join(LH)}
  Decoding.decodes(GS.{X}(), VS.bt(U32.to_nat(N), FX.limbs(FD.array__slots(U32, VL.OUTP(N, T)))), XE(c, FD.array__slots(U32, T)))
def encode_spec(dw, T, N, c, pfT, hdw, ec, hroom):
  +e4 = em(N, c, ec)
  +W = FD.array__slots(U32, T)
  +hl = FD.logic__subst(Nat, z => {{Nat.is_le({m}, z) == True{{}} : Bool}}, VB.pw(dw), FD.spec_common__length(U32, W), Equal.sym(Nat, FD.spec_common__length(U32, W), VB.pw(dw), FD.array__slots_length(U32, dw, T, pfT)), hroom)
  +fit = FD.logic__subst(Nat, z => {{N.fits(4n, z) == True{{}} : Bool}}, U32.to_nat(N), EL.b{E}(c), ec, VL.hfitA(N))
  Equal.trans(Maybe<&2, +List<U32>>, Codec.encoding_for_legal_type(GS.{X}(), XE(c, W)), Some{{FX.limbs(VS.wtake({m}, W))}}, Some{{VS.bt(U32.to_nat(N), FX.limbs(FD.array__slots(U32, VL.OUTP(N, T))))}},
    EL.plenc{E}(c, W, hl, fit),
    Equal.cong(+List<U32>, Maybe<&2, +List<U32>>, z => Some{{z}}, FX.limbs(VS.wtake({m}, W)), VS.bt(U32.to_nat(N), FX.limbs(FD.array__slots(U32, VL.OUTP(N, T)))),
      Equal.sym(+List<U32>, VS.bt(U32.to_nat(N), FX.limbs(FD.array__slots(U32, VL.OUTP(N, T)))), FX.limbs(VS.wtake({m}, W)), VL.out_eq_gA(dw, T, N, {m}, pfT, hdw, e4, hroom))))
''')
    return '\n'.join(L) + '\n'


def outputs():
    out = {ROOT / 'proofs/obj/var_elems.bend': elems_text()}
    out[ROOT / 'proofs/obj/var_plist_zeros.bend'] = zeros_text()
    for X in NAMES:
        out[fname(X)] = dec_text(X)
        out[fname(X, '_unique')] = uniq_text(X)
        out[fname(X, '_rej')] = rej_text(X)
        out[fname(X, '_enc')] = enc_text(X)
    return out



def _foreign(q, me):
    # a file whose header names another generator is not ours, whatever its name
    return writer.is_foreign(q, me)

def main():
    out = outputs()
    mine = [q for q in sorted((ROOT / 'proofs/obj').glob('var_plist_*.bend')) + sorted((ROOT / 'proofs/obj').glob('var_plist_*.bend'))
            if not _foreign(q, 'var_plist')]
    orphans = [str(q.relative_to(ROOT)) for q in mine if q not in out]
    from codegen.impl import runtime_refs as RR  # the runtime split: the modules import the per-name files they use
    out = RR.rewire_out(out)
    if '--check' in sys.argv:
        return writer.check(out, 'stale generated progressive-list laws: ', 'generated progressive-list laws are current', orphans=orphans)
    for q in orphans:
        (ROOT / q).unlink()
    for p, t in out.items():
        p.write_text(t)
    print(', '.join(str(p.relative_to(ROOT)) for p in out))


if __name__ == '__main__':
    main()
