#!/usr/bin/env python3
"""Readers of BeaconState's FIXED fields at any byte position x (the field's bytes are the
window slice UW.WX(t, x, S)), for the byte-offset BeaconState module.

    python3 codegen/proofs/var/var_fixx.py [--check]

One module per field type p, proofs/obj/{big_,}vfx_<p>.bend, exporting (S = the field's
byte size, SCH = its spec schema):
  OBJ(d, t, x)                     the object T.<p>_read returns at byte position x
  rdx(d, t, n, off, x, e, hd, pf, hb)
      : T.<p>_read(UA.BF(t, n), off, S) == (UA.BF(t, n), OBJ(d, t, x))
        (e: off = x, hd: d < 28, pf: t perfect of depth d, hb: x + S <= 4 2^d)
  VAL(t, x)                        the spec value over the words UR.RWN(t, x + 4 k)
  prt(d, t, x, pf, hb)
      : Codec.parts(VAL(t, x), SCH) == Some{[S.Fixed{UW.WX(t, x, S)}]}
Vectors are read by copy_into (OBJ holds vua_fixb's copy CTN(d, t, x, S, dz)); their
values are arr_vec's chunkings of UR.RWS(S / 4, t, x), proved for every word list (no
element is unrolled). Modules whose statements carry closed sizes above stock Bend's
stack are big_ files.
"""
import sys as _sys
import pathlib as _pathlib
_sys.path.insert(0, str(_pathlib.Path(__file__).resolve().parents[3]))  # the repository root: `codegen` is importable when this file runs as a script
import sys
from codegen.core import writer  # noqa: E402
from codegen.impl import runtime_refs as RR  # noqa: E402  the runtime split: the monoliths' text, the split files' imports

from codegen.core.paths import ROOT  # noqa: E402
from codegen.core.shared_var_a import Templates  # noqa: E402
TEMPLATES = Templates('var_fixx', globals())

HEAD = ['import Base', 'import ../../src/buffer.bend as B', 'import ../../src/obj.bend as O',
        'import ../../types/fulu_obj.bend as T', 'import ../../types/schema.bend as S', 'import ../../types/primitive.bend as P',
        'import ../compact/found.bend as FD', 'import ../compact/arith.bend as A', 'import ../../proofs/nat_order.bend as Order',
        'import ../../spec/layout.bend as Layout', 'import ../../spec/codec.bend as Codec', 'import ../../spec/nat_bytes.bend as N',
        'import ../../spec/fulu_schemas.bend as Spec', 'import ./spec_fixed.bend as F', 'import ./vspec.bend as VS',
        'import ./vbuf.bend as VB', 'import ./vmr.bend as VMR', 'import ./vua.bend as UA', 'import ./vua_rd.bend as UR',
        'import ./vua_win.bend as UW', 'import ./vua_fix.bend as VTX', 'import ./vbx.bend as VBX', 'import ./vua_fixb.bend as VXB',
        'import ./arr_vec.bend as AV']
TRUE = 'True{} : Bool'
TR = 'FD.array__Tree<U32>'
BIG = 1 << 40    # (no vector needs checkq --big: sizes stay literals, values stay neutral)


def log2c(n):
    k = 0
    while (1 << k) < n:
        k += 1
    return k


def sig(name, S, rest='', sn=None):
    return (f'def {name}(+d: Nat, +t: {TR}, +n: U32, +off: U32, +x: Nat, +e: {{U32.to_nat(off) == x : Nat}},\n'
            f'    +hd: {{Nat.is_lt(d, 28n) == {TRUE}}}, +pf: {{FD.array__perfect(U32, d, t) == {TRUE}}},\n'
            f'    +hb: {{Nat.is_le(Nat.add(x, {sn or str(S) + "n"}), A.quad(VB.pw(d))) == {TRUE}}}){rest}')


GEN_HEAD = HEAD + ['import ./vcopy.bend as VC', 'import ./schema_shapes.bend as SH', 'import ./arr_spec.bend as AS', 'import ../../spec/schema.bend as SSC']


def gen_text():
    """proofs/obj/vfxg.bend: the readers and values, for every size (instantiated by the
    vfx_<p> modules with closed facts that evaluate to True)."""
    L = list(GEN_HEAD) + ['', '# GENERATED by var_fixx (codegen). Do not edit.',
                          '# Fixed fields at any byte position, for every size: see codegen/proofs/var/var_fixx.py.', '']
    P = 'A.quad(VB.pw(d))'
    L.append(TEMPLATES.render('gen_text'))
    L.append(TEMPLATES.render('gen_text_2', P=P))
    L.append(TEMPLATES.render('gen_text_3', P=P))
    for ch, mm, vp, el in (('ch8', 'm8', 'vparts8', 'S.ByteVector{32n}'), ('chu2', 'm2', 'vpartsu2', 'S.Unsigned{P.U64{}}'), ('ch12', 'm12', 'vparts12', 'S.ByteVector{48n}')):
        W = 'UR.RWS(M, t, x)'
        L.append(TEMPLATES.render('gen_text_4', ch=ch, el=el, mm=mm, P=P, W=W, vp=vp))
    L.append(sc_text())
    out = []
    for blk in L:
        for X, X0 in (('prt_', 'prt0_'), ('offc(', 'offc0('), ('splitC(', 'splitC0(')):
            if f'def {X0}' in blk:
                a = blk.index(f'def {X}')
                b = blk.index(f'def {X0}')
                e = blk.find('\n\n', b)
                e = len(blk) if e < 0 else e + 1
                blk = blk[:a] + blk[b:e].rstrip('\n') + '\n' + blk[a:b] + blk[e:]
        out.append(blk)
    return '\n'.join(out) + '\n'


def sc_text():
    """SyncCommittee's parts over any 6144 pubkey words W and aggregate words g (after
    codegen/proofs/laws/spec_arr.py sync_committee, with W a variable), and the window splits."""
    import re
    from codegen.proofs.laws import spec_arr as SA
    P = 'A.quad(VB.pw(d))'
    g = [f'g{i}' for i in range(12)]
    G = '[' + ', '.join(g) + ']'
    gsig = ', '.join(f'+{x}: U32' for x in g)
    spec = 'Spec.SyncCommittee()'
    WA = 'W'
    VAL = f'S.Sequence{{S.Items{{S.Sequence{{AV.ch12({WA})}}, S.Items{{S.BytesValue{{SF.limbs({G})}}, S.EmptyItems{{}}}}}}}}'
    PT = 'Maybe<&2, +List<S.Part>>'
    FL = f'SF.flat([{WA}, {G}])'
    RHSF = f'Some{{[S.Fixed{{{FL}}}]}}'
    fs = 'SH.Container_fields(s)'
    h1, t1 = f'SH.Chain_head({fs})', f'SH.Chain_tail({fs})'
    h2, t2 = f'SH.Chain_head({t1})', f'SH.Chain_tail({t1})'
    BV = 'S.ByteVector{48n}'
    V1 = f'S.Vector{{{BV}, SH.Vector_length({h1})}}'
    names = 'SH.Container_names(s)'
    gg = lambda sch, rhs: f'{{Codec.parts({VAL}, {sch}) == {rhs} : {PT}}}'
    la, lg = f'SF.limbs({WA})', f'SF.limbs({G})'
    L = [f'# SyncCommittee\'s parts over any M = 6144 pubkey words W and any aggregate words g',
         f'def sc_parts(+s: S.Schema, +es: {{s == {spec} : S.Schema}}, +W: List<&2, U32>, +M: Nat, +S1: Nat, +Sn: Nat, {gsig},',
         f'    +hl: {{F.spec_common__length(U32, W) == M : Nat}}, +hm: {{Nat.is_eq(AV.m12(512n), M) == True{{}} : Bool}},',
         f'    +h1: {{Nat.is_eq(A.quad(M), S1) == True{{}} : Bool}}, +hS: {{Nat.is_eq(Nat.add(S1, Nat.add(48n, 0n)), Sn) == True{{}} : Bool}},',
         f'    +hf: {{NB.fits(4n, Nat.add(Sn, 0n)) == True{{}} : Bool}}, +hf1: {{NB.fits(4n, Nat.add(S1, 0n)) == True{{}} : Bool}})',
         f'    -> {{Codec.parts({VAL}, s) == Some{{[S.Fixed{{List.append(&2, U32, {la}, {lg})}}]}} : {PT}}}:']
    w = L.append
    w(f'  %AS.app_nil({lg}) :')
    w('    ' + gg('s', f'Some{{[S.Fixed{{List.append(&2, U32, {la}, _)}}]}}'))
    steps = [
        (f'Equal.sym(S.Schema, s, S.Container{{{names}, {fs}}}, SH.Container_shape(s, {SA.bfact(spec, "SH.is_Container(s)")}))', '_'),
        (f'Equal.sym(S.Schema, {fs}, S.Chain{{{h1}, {t1}}}, SH.Chain_shape({fs}, {SA.bfact(spec, f"SH.is_Chain({fs})")}))', f'S.Container{{{names}, _}}'),
        (f'Equal.sym(S.Schema, {t1}, S.Chain{{{h2}, {t2}}}, SH.Chain_shape({t1}, {SA.bfact(spec, f"SH.is_Chain({t1})")}))', f'S.Container{{{names}, S.Chain{{{h1}, _}}}}'),
        (f'Equal.sym(S.Schema, {t2}, S.End{{}}, SH.End_shape({t2}, {SA.bfact(spec, f"SH.is_End({t2})")}))', f'S.Container{{{names}, S.Chain{{{h1}, S.Chain{{{h2}, _}}}}}}'),
        (f'Equal.sym(S.Schema, {h1}, S.Vector{{SH.Vector_element({h1}), SH.Vector_length({h1})}}, SH.Vector_shape({h1}, {SA.bfact(spec, f"SH.is_Vector({h1})")}))', f'S.Container{{{names}, S.Chain{{_, S.Chain{{{h2}, S.End{{}}}}}}}}'),
        (f'Equal.sym(S.Schema, SH.Vector_element({h1}), {BV}, {SA.sfact(spec, f"SH.Vector_element({h1})", BV)})', f'S.Container{{{names}, S.Chain{{S.Vector{{_, SH.Vector_length({h1})}}, S.Chain{{{h2}, S.End{{}}}}}}}}'),
        (f'Equal.sym(S.Schema, {h2}, {BV}, {SA.sfact(spec, h2, BV)})', f'S.Container{{{names}, S.Chain{{{V1}, S.Chain{{_, S.End{{}}}}}}}}'),
    ]
    for eq, sch in steps:
        w(f'  %{eq} :')
        w('    ' + gg(sch, RHSF))
    FIELDS = f'S.Chain{{{V1}, S.Chain{{{BV}, S.End{{}}}}}}'
    agg = lambda a_, b_: f'{{Codec.aggregate(Codec.concatenate({a_}, Codec.concatenate({b_}, Some{{[]}})), SSC.fixed_size({FIELDS})) == {RHSF} : {PT}}}'
    kf = SA.bfact(spec, f'Nat.is_eq(SH.Vector_length({h1}), 512n)')
    eq1 = 'F.nat__eq_from_is_eq(A.quad(M), S1, h1)'
    hN = (f'Equal.trans(Nat, SF.wlen(W), A.quad(M), S1, Equal.trans(Nat, SF.wlen(W), A.quad(List.length(&2, U32, W)), A.quad(M), VS.wlen_quad(W), '
          f'Equal.cong(Nat, Nat, z => A.quad(z), List.length(&2, U32, W), M, Equal.trans(Nat, List.length(&2, U32, W), F.spec_common__length(U32, W), M, VMR.len_eq(W), hl))), {eq1})')
    vp = (f'AV.vparts12({V1}, {WA}, 512n, M, S1, {{==}}, {{==}}, {kf}, {{==}}, hl, hm, {hN}, hf1)')
    P1 = f'Codec.parts(S.Sequence{{AV.ch12({WA})}}, {V1})'
    P2 = f'Codec.parts(S.BytesValue{{{lg}}}, {BV})'
    F1 = f'Some{{[S.Fixed{{SF.limbs({WA})}}]}}'
    F2 = f'Some{{[S.Fixed{{{lg}}}]}}'
    w(f'  %Equal.sym({PT}, {P1}, {F1}, {vp}) :')
    w('    ' + agg('_', P2))
    w(f'  %Equal.sym({PT}, {P2}, {F2}, SF.bytes_part(g0, [{", ".join(g[1:])}], {{==}})) :')
    w('    ' + agg(F1, '_'))
    x = f'Nat.add(Nat.mul(SH.Vector_length({h1}), 48n), Nat.add(48n, 0n))'
    ea = f'Equal.trans(Nat, List.length(&2, U32, SF.limbs({WA})), SF.wlen({WA}), S1, AS.len_limbs({WA}), {hN})'
    w(f'  AS.agg([{WA}, {G}], {x}, Sn,')
    w(f'    AS.add2(List.length(&2, U32, SF.limbs({WA})), List.length(&2, U32, {lg}), S1, 48n, Sn, {ea}, {{==}}, hS), hf)')
    t = '\n'.join(L) + '\n'
    t = t.replace('SF.', '@SF@')
    t = re.sub(r'(?<![A-Za-z_@])F\.', 'FD.', t)
    t = t.replace('@SF@', 'F.').replace('NB.', 'N.')
    return t


def rt_depth(p):
    """The zero storage depth the runtime reader of p allocates."""
    import re
    src = RR.mono_text('fulu')
    m = re.search(rf'^def {p}_read\(.*Array\.new\(U32, (\d+)n, 0\)\)$', src, re.M)
    return int(m.group(1))


def big_pow(S):
    """A byte size handled symbolically (proofs/obj/vbig.bend): a power of two of at least 2^16."""
    return S >= 65536 and S & (S - 1) == 0


def vec_text(p, S, k, sch, ch, el):
    """A Vector of k elements, S bytes, read by copy_into."""
    M = S // 4
    EL = {'ch8': 'S.ByteVector{32n}', 'chu2': 'S.Unsigned{P.U64{}}', 'ch12': 'S.ByteVector{48n}'}[ch]
    dz = rt_depth(p)
    ky = log2c(S + 31)
    L = list(HEAD) + ['import ./schema_shapes.bend as SH', 'import ./vfxg.bend as VXG'] + (['import ./vbig.bend as VG'] if big_pow(S) and ch != 'ch12' else []) + [
        '', '# GENERATED by var_fixx (codegen). Do not edit.',
        f'# {p}: Vector[{el}, {k}] ({S} bytes) at any byte position: see codegen/proofs/var/var_fixx.py.', '']
    if big_pow(S) and ch != 'ch12':
        # the size as U32.to_nat(S) and the counts over U32.to_nat(k): the facts are symbolic
        # (vbig.bend); closed, they were unary work of millions of steps
        r, e = S.bit_length() - 1, k.bit_length() - 1
        q = r - 2
        mm, es = ('m8', 'es_pow') if ch == 'ch8' else ('m2', 'es_pow2')
        SN, KN = f'U32.to_nat({S})', f'U32.to_nat({k})'
        EK = f'VG.u32pow({k}, {e}n, {{==}}, {{==}})'
        L.append(TEMPLATES.render('vec_text', S=S, dz=dz, SN=SN, p=p, ky=ky, q=q, r=r, ch=ch, mm=mm, KN=KN, sch=sch, EL=EL, e=e, EK=EK, es=es))
        return fx_deep('\n'.join(L) + '\n')
    L.append(TEMPLATES.render('vec_text_2', S=S, dz=dz, p=p, ky=ky, ch=ch, M=M, sch=sch, k=k, EL=EL))
    return fx_deep('\n'.join(L) + '\n')


def sc_mod():
    """SyncCommittee: Vector[BLSPubkey, 512] (copy_into), then a Bytes48."""
    S, S1, M, dz = 24624, 24576, 6144, rt_depth('v512_b48')
    ky = log2c(S1 + 31)
    P = 'A.quad(VB.pw(d))'
    y = f'Nat.add(x, {S1}n)'
    G = [f'UR.RWN(t, {y})' if k == 0 else f'UR.RWN(t, {4 * k}n+{y})' for k in range(12)]
    PK = f'O.Words{{FD.array__thaw(U32, VXB.CTN(d, t, x, {S1}, {dz}n)), {S1}}}'
    B48 = 'T.Bytes48{' + ', '.join(G) + '}'
    OBJ = f'T.SyncCommittee{{{PK}, {B48}}}'
    VAL = f'S.Sequence{{S.Items{{S.Sequence{{AV.ch12(UR.RWS(VXG.CNT(x, {M}n), t, x))}}, S.Items{{S.BytesValue{{F.limbs([{", ".join(G)}])}}, S.EmptyItems{{}}}}}}}}'
    RHS = f'(UA.BF(t, n), OBJ(d, t, x))'
    L = list(HEAD) + ['import ./schema_shapes.bend as SH', 'import ./vfxg.bend as VXG', '', '# GENERATED by var_fixx (codegen). Do not edit.',
                      f'# SyncCommittee ({S} bytes) at any byte position: see codegen/proofs/var/var_fixx.py.', '']
    L.append(TEMPLATES.render('sc_mod', OBJ=OBJ, S=S, RHS=RHS, S1=S1, PK=PK, dz=dz, ky=ky, P=P, B48=B48, y=y, VAL=VAL, M=M, G=G))
    return '\n'.join(L) + '\n'


VECS = [('v8192_b32', 262144, 8192, 'Spec.Schema32()', 'ch8', 'Bytes32'),
        ('v65536_b32', 2097152, 65536, 'Spec.Schema80()', 'ch8', 'Bytes32'),
        ('v8192_u64', 65536, 8192, 'Spec.Schema81()', 'chu2', 'uint64'),
        ('v64_u64', 512, 64, 'Spec.Schema88()', 'chu2', 'uint64')]

# fixed field types read word by word (vua_fix / vbx_fix readers), by BeaconState field
SMALL = [('genesis_time', 'Spec.Schema3()'), ('genesis_validators_root', 'Spec.Schema7()'), ('fork', 'Spec.Fork()'),
         ('latest_block_header', 'Spec.BeaconBlockHeader()'), ('eth1_data', 'Spec.Eth1Data()'), ('finalized_checkpoint', 'Spec.Checkpoint()')]


def have(f):
    src = (ROOT / f'proofs/obj/{f}').read_text()
    return {ln.split('(')[0][len('def rdx_'):] for ln in src.splitlines() if ln.startswith('def rdx_')}


def seq_head(sch, val, proof, W, exact):
    """For a fulu container Spec.X() whose walk() proof is F.aggregate_fixed(Codec.parts(items, chain), ..):
    first rewrite Codec.parts(VAL(t, x), Spec.X()) to Codec.aggregate(Codec.parts(items, chain), Some{n}) by
    VSQ.seq_parts (proofs/obj/vseq.bend), and chain the fields by VS.chain_fixed. Otherwise the conversion to aggregate_fixed's
    statement evaluates the whole container's parts (checker_findings item 2)."""
    import re
    from codegen.proofs.var import var_laws as VLW
    from codegen.proofs.var import var_bytes_x as VBX
    m = re.fullmatch(r'Spec\.(\w+)\(\)', sch)
    head = 'F.aggregate_fixed('
    if exact or not m or not proof.startswith(head) or not val.startswith('S.Sequence{'):
        return proof
    try:
        names = VBX.spec_names(m.group(1))
    except AssertionError:
        return proof
    args = VLW._split_args(proof[len(head):-1])
    assert len(args) == 5 and proof.endswith(')'), args
    a, n = args[0], args[2]
    items, chain = VLW._split_args(a[len('Codec.parts('):-1])
    assert val == f'S.Sequence{{{items}}}', (val, items)
    MP = 'Maybe<&2, +List<S.Part>>'
    RHS = f'Some{{[S.Fixed{{F.limbs(UR.RWS({W}n, t, x))}}]}}'
    return (TEMPLATES.render('seq_head', MP=MP, sch=sch, a=a, chain=chain, items=items, names=names, RHS=RHS, n=n, proof=proof, VLW=VLW))


def small_mod(g, t, sch, exact=False):
    """A fixed type read word by word: thin wrappers over vua_fix / vbx_fix (or a reader here).
    exact: the spec-parts proof in spec_laws' SL.EXACT form, the schema rewritten to its node's first."""
    from codegen.proofs.var import var_laws as VLW
    from codegen.proofs.var import var_ua as VUA
    ft = VLW.FT(g, t)
    p, S, W = ft.p, ft.size, ft.W
    vtx, xf = have('vua_fix.bend'), have('vbx_fix.bend')
    word = lambda k: 'UR.RWN(t, x)' if k == 0 else f'UR.RWN(t, {4 * k}n+x)'
    OBJ = ft.obj([word(k) for k in range(W)])
    nd = VLW.SL.walk(g, t, iter(range(100000)))
    mp = {int(w_[1:]): word(j) for j, w_ in enumerate(nd.words)}
    val, proof = VLW.subst_words(nd.val, mp), VLW.subst_words(nd.proof, mp)
    proof = seq_head(sch, val, proof, W, exact)
    L = list(HEAD) + (['import ../../spec/schema.bend as SC', 'import ./vseq.bend as VSQ'] if 'SC.' in proof else []) + [
        '', '# GENERATED by var_fixx (codegen). Do not edit.', f'# {p} ({S} bytes) at any byte position: see codegen/proofs/var/var_fixx.py.', '']
    local = []
    for dep in ft.deps():
        if dep.p in vtx or dep.p in xf:
            continue
        for ln in VUA.rdx_lemma(dep):
            ln = ln.replace('ltp(', 'VTX.ltp(').replace('F.', 'FD.')
            for kp in vtx:
                ln = ln.replace(f'rdx_{kp}(', f'VTX.rdx_{kp}(')
            for kp in xf:
                ln = ln.replace(f'rdx_{kp}(', f'XF.rdx_{kp}(')
            L.append(ln)
        L.append('')
        local.append(dep.p)
    ref = f'VTX.rdx_{p}' if p in vtx else (f'XF.rdx_{p}' if p in xf else f'rdx_{p}')
    if p in xf:
        L.insert(L.index('import ./vua_fix.bend as VTX') + 1, 'import ./vbx_fix.bend as XF')
    P = 'A.quad(VB.pw(d))'
    xrw = (f'  %Equal.sym(S.Schema, {sch}, {nd.sch}, {{==}}) : {{Codec.parts(VAL(t, x), _) == Some{{[S.Fixed{{F.limbs(UR.RWS({W}n, t, x))}}]}} : Maybe<&2, +List<S.Part>>}}\n'
           if exact else '')
    L.append(TEMPLATES.render('small_mod', ft=ft, OBJ=OBJ, S=S, p=p, ref=ref, val=val, P=P, sch=sch, W=W, xrw=xrw, proof=proof))
    return p, fx_deep('\n'.join(L) + '\n')



def outputs():
    from codegen.proofs.var import var_fixx_bv4 as BV4
    out = {ROOT / 'proofs/obj/vfxg.bend': gen_text(), ROOT / 'proofs/obj/vfx_SyncCommittee.bend': sc_mod(),
           ROOT / 'proofs/obj/vfx_bv4.bend': BV4.bv4_mod(HEAD, sig, TR, TRUE)}
    from codegen.proofs.var import var_fixx_gen as GEN   # the generic containers' short fields (types/generic_obj.bend)
    out[ROOT / 'proofs/obj/vfx_u8.bend'] = GEN.u8_mod(HEAD, sig, TR, TRUE)
    out[ROOT / 'proofs/obj/vfx_u16.bend'] = GEN.u16_mod(HEAD, sig, TR, TRUE)
    out[ROOT / 'proofs/obj/vfx_u32.bend'] = GEN.u32_mod(HEAD, sig, TR, TRUE)
    from codegen.core import generic as GN0
    from codegen.impl import generate as G0
    gn0 = {n_: t_ for n_, t_, err in GN0.inventory_all() if err is None}
    g0 = G0.Gen()
    for t_ in gn0.values():
        g0.shape(t_)
    for P_, R_, K_ in GEN.RECVECS:
        out[ROOT / f'proofs/obj/vfx_{P_}.bend'] = GEN.recvec_mod(gn0, g0, P_, R_, K_, HEAD, sig, TR, TRUE)
    for N in (1, 2, 8):
        out[ROOT / f'proofs/obj/vfx_bv{N}.bend'] = GEN.bvn_mod(N, HEAD, sig, TR, TRUE)
    from codegen.core import generic as GN
    gnames = {n: t for n, t, err in GN.inventory_all() if err is None}
    out[ROOT / 'proofs/obj/vfx_bv257.bend'] = GEN.bvw1_mod(HEAD, sig, TR, TRUE)
    out[ROOT / 'proofs/obj/vfx_bv1281.bend'] = GEN.bvw1_mod(HEAD, sig, TR, TRUE, 1281)
    out[ROOT / 'proofs/obj/vfx_bv1280.bend'] = GEN.bvc_mod(1280, HEAD, sig, TR, TRUE)
    for p, txt in GEN.generic_small(gnames, small_mod).items():
        out[ROOT / f'proofs/obj/vfx_{p}.bend'] = txt
    from codegen.core import schema
    from codegen.impl import generate as G
    names = schema.load(ROOT / 'codegen/fulu.yaml')
    g = G.Gen()
    for n_, t_ in names.items():
        g.shape(t_)
    for fld, sch in SMALL:
        p, txt = small_mod(g, dict(names['BeaconState'].fields)[fld], sch)
        out[ROOT / f'proofs/obj/vfx_{p}.bend'] = txt
    for p, S, k, sch, ch, el in VECS:
        big = S > BIG
        out[ROOT / f'proofs/obj/{"" if big else ""}vfx_{p}.bend'] = vec_text(p, S, k, sch, ch, el)
    return out


# ---- any tree depth d < 31 --------------------------------------------------------------------
# A fixed field's bytes sit at x + S <= 4 2^d: with d < 31 every offset stays below 2^32 (UR.offx31,
# VTX.rdxd_), so the readers need no other bound. Each reader with hd: d < 28 becomes nameD with
# hd: d < 31, and the old name stays as a wrapper (callers not yet deep). The local rdx_ lemmas
# (hd: d < 30) get a deep twin rdx_<p>D.

_HDX = '+hd: {{Nat.is_lt(d, {}n) == True{{}} : Bool}}'
_LOCAL_D = {'VXG': ('offc', 'offc0', 'rdg')}
_VFX_D = ('rdx', 'ok')


def _fx_blocks(text):
    import re
    st = [m.start() for m in re.finditer(r'^def \w+\(', text, re.M)]
    out = []
    for i, a in enumerate(st):
        b = st[i + 1] if i + 1 < len(st) else len(text)
        seg = text[a:b]
        lines = seg.rstrip('\n').split('\n')
        while lines and (lines[-1].startswith('#') or not lines[-1].strip()):
            lines.pop()
        out.append((a, a + len('\n'.join(lines))))
    return out


def fx_deep(text):
    import re
    from codegen.proofs.support import deep
    ds = deep._defs(text)
    # (idempotent: a def whose deep twin exists is done)
    hd28 = [n for n, v in ds.items() if _HDX.format(28) in v[3] and n + 'D' not in ds]
    hd30 = [n for n, v in ds.items() if _HDX.format(30) in v[3] and n + 'D' not in ds]
    if not hd28 and not hd30:
        return text
    local = hd28 + hd30
    vfx = re.findall(r'^import \./(?:big_)?vfx_\w+\.bend as (\w+)$', text, re.M)
    pat = re.compile(r'(?<![\w.])(' + '|'.join(sorted(local, key=len, reverse=True)) + r')\(')
    reps = [('VTX.rdx_', 'VTX.rdxd_'), ('XF.rdx_', 'XF.rdxd_'), ('UR.offx(', 'UR.offx31('),
            ('UW.hsx(d, off, x, L, e, hd, hw)', 'UW.hsxB(d, off, x, L, e, k, hk, hy, hw)'),
            ('FD.nat__lt_trans(d, 28n, 32n, hd, {==})', 'FD.nat__lt_trans(d, 31n, 32n, hd, {==})')]
    for a, b in (('28n', '30n'), ('28n', '31n'), ('30n', '31n')):
        reps.append((f'FD.nat__lt_trans(d, {a}, {b}, hd, {{==}})', 'hd'))
    for q, ns in _LOCAL_D.items():
        for nm in ns:
            reps.append((f'{q}.{nm}(', f'{q}.{nm}D('))
    for q in vfx:
        for nm in _VFX_D:
            reps.append((f'{q}.{nm}(', f'{q}.{nm}D('))

    def dcopy(blk):
        blk = pat.sub(lambda m: m.group(1) + 'D(', blk)
        for a, b in reps:
            blk = blk.replace(a, b)
        blk = blk.replace(_HDX.format(28), _HDX.format(31)).replace(_HDX.format(30), _HDX.format(31))
        bad = re.findall(r'is_lt\(d, (?!31n)\d+n\)|lt_trans\(d, (?!31n, 32n)\d+n', blk)
        assert not bad, (bad, blk[:200])
        return blk

    out, last = [], 0
    for a, b in _fx_blocks(text):
        nm = re.compile(r'def (\w+)\(').match(text, a).group(1)
        out.append(text[last:a])
        blk = text[a:b]
        if nm in hd28:
            _, _, _, ps, rest = ds[nm]
            args = ['FD.nat__lt_trans(d, 28n, 31n, hd, {==})' if p == _HDX.format(28) else p.split(':')[0].strip().lstrip('+') for p in ps]
            wrap = f'def {nm}(' + ', '.join(ps) + ')' + rest + ':\n  ' + nm + 'D(' + ', '.join(args) + ')'
            out.append(dcopy(blk) + '\n\n' + wrap)
        elif nm in hd30:
            out.append(blk + '\n\n' + dcopy(blk))
        else:
            out.append(blk)
        last = b
    out.append(text[last:])
    return ''.join(out)


def main():
    out = outputs()
    out = {p_: fx_deep(t_) for p_, t_ in out.items()}
    out = RR.rewire_out(out)
    if '--check' in sys.argv:
        return writer.check(out, 'stale: ', 'fixed-field readers are current')
    for p, t in out.items():
        p.write_text(t)
    print(f'{len(out)} files')


if __name__ == '__main__':
    main()
