#!/usr/bin/env python3
"""Bit lists in the encoder-window interface (encx): the runtime's bit-list writer at any
byte position X = 4 q + r of an output tree, for the progressive bit list (pbits) and
bounded bit lists BitList[N] (bits<N>).

    python3 codegen/proofs/var/var_bits_encx.py [--check]

Writes proofs/obj/encx_<p>.bend with the interface of codegen/proofs/var/var_plist_sub.py's
list encx modules:

    MB{dw, T, K, B, kb, KY}   the object's Data mirror (storage T of depth dw, K bits; B a
                              bound on K and kb, KY bit widths, as vuwb.pbx_any takes them)
    TH, OK, ENC, VAL, SZ, PUTX (vuwb.PBX), PADB (vuwd.PADB of |ENC|)
    putx, putx_bytes, pfx, szx, sizex, encx_spec

on vuwb.pbx_any / pbx_any_bytes. ENC is the spec's packing of the bits and the delimiter,
Bp.pack(BITS ++ [True]); its length is K / 8 + 1 (pack_len, bcx: the byte count of
8 a + b + 1 bits, b < 8), the bits' count K from vbitcore.enc_core's CR3.
"""
import sys as _sys
import pathlib as _pathlib
_sys.path.insert(0, str(_pathlib.Path(__file__).resolve().parents[3]))  # the repository root: `codegen` is importable when this file runs as a script
from codegen.proofs.var.var_finish import finish  # noqa: E402

from codegen.core.paths import ROOT  # noqa: E402
from codegen.core.shared_var_b import Templates  # noqa: E402
TPL = Templates('var_bits_encx', globals())
HDR = '# GENERATED by var_bits_encx (codegen). Do not edit.'

# runtime prefix -> (types module, schema term, runtime bound N (None: progressive), the U32 bound term)
KINDS = {
    'pbits': ('generic_obj', 'GS.progbitlist()', None),
    'bits131072': ('fulu_obj', 'Spec.Schema38()', 131072),
}
# the bounded bit lists of the generic forms
for _N in (5, 6, 256, 257, 1280, 1281):
    KINDS[f'bits{_N}'] = ('generic_obj', f'S.BitList{{{_N}n}}', _N)


def fname(p):
    return ROOT / f'proofs/obj/encx_{p}.bend'


def head(tmod):
    L = ['import Base', 'import ../../src/buffer.bend as B', 'import ../../src/obj.bend as O', f'import ../../types/{tmod}.bend as T',
         'import ../../types/schema.bend as S', 'import ../compact/found.bend as FD', 'import ../compact/arith.bend as A',
         'import ../compact/reads.bend as RD', 'import ../../proofs/nat_order.bend as Order', 'import ../../spec/codec.bend as Codec',
         'import ../../spec/bit_packing.bend as Bp', 'import ../../spec/bitfields.bend as Bits',
         'import ./spec_fixed.bend as FX', 'import ./vspec.bend as VS', 'import ./vbuf.bend as VB', 'import ./vcopy.bend as VC',
         'import ./vdepth.bend as VD', 'import ./vu32.bend as VU', 'import ./venc.bend as VE', 'import ./vbytes.bend as VY',
         'import ./vua.bend as UA', 'import ./vuw.bend as UW', 'import ./vuwd.bend as UWD', 'import ./vuwb.bend as VWB',
         'import ./vbitenc.bend as VBT', 'import ./vbitdl.bend as DL', 'import ./vbitcore.bend as CO']
    L.append('import ./generic_specs.bend as GS' if tmod == 'generic_obj' else 'import ../../spec/fulu_schemas.bend as Spec')
    return L


# the bit lists small enough for their byte bound (maxx) to be stated
MAXX_LIM = 256


def text(p):
    tmod, sch, NB = KINDS[p]
    ARGS = '+dw: Nat, +T: FD.array__Tree<U32>, +K: U32, +B: Nat, +kb: Nat, +KY: Nat'
    A_ = 'dw, T, K, B, kb, KY'
    TRUE = 'True{} : Bool'
    # any storage depth dw < 31 and any bit count K + 8 <= 2^kb, kb <= 32 (K <= 2^32 - 8); KY is unused
    # (the copy's size is bounded by the bit count itself: vbitenc.y30)
    C = ['FD.array__perfect(U32, dw, T)', 'Nat.is_lt(dw, 31n)', 'Nat.is_lt(kb, 33n)', 'Nat.is_le(U32.to_nat(K), B)',
         'Nat.is_le(Nat.add(B, 8n), O.pow2n(kb))',
         'Nat.is_le(Nat.add(U32.to_nat(U32.shrn(K, 5n)), 1n), VB.pw(dw))',
         'O.tail_zero(U32.and(O.bits_nbytes(K), 3), VB.slot(T, VY.QL(O.bits_nbytes(K))))',
         'DL.HZ(DL.RK(K), VB.slot(T, VBT.QK(K)))',
         'O.bits_above_zero(U32.and(K, 31), RD.wd(T, dw, U32.shrn(K, 5n)))',
         f'U32.is_le(K, {NB})' if NB else 'True{}']
    names = ['pf', 'hdw', 'hkb', 'hN', 'hNk', 'hcap', 'htz', 'hbz', 'hbz2', 'hlim']

    def R(i):
        t = C[-1]
        for c in reversed(C[i:-1]):
            t = f'Bool.and({c}, {t})'
        return t
    L = head(tmod) + ['', HDR, f'# {p} in the encoder-window interface (see codegen/proofs/var/var_bits_encx.py).', '']
    w = L.append
    w(TPL.render('text', ARGS=ARGS, A_=A_, NB=NB, R=R))
    # accessors of OKT's conjuncts
    for i in range(len(C)):
        t = 'h'
        for j in range(i):
            t = f'FD.logic__and_right({C[j]}, {R(j + 1)}, {t})'
        body = t if i == len(C) - 1 else f'FD.logic__and_left({C[i]}, {R(i + 1)}, {t})'
        w(f'def ok_{names[i]}({ARGS}, +h: {{OKT({A_}) == {TRUE}}}) -> {{{C[i]} == {TRUE}}}:\n  {body}')
    w('')
    w(TPL.text('text_pack_len'))
    ind = '    '
    cur = 'xs'
    for k in range(8):
        nxt = f't{k}'
        if k > 0:
            w(f'{ind}case Con{{+b{k - 1}, +{cur}}}:')
            ind += '  '
            w(f'{ind}match {cur}:')
            ind += '  '
            w(f'{ind}case Nil{{}}: {{==}}')
        cur = nxt
    w(f'{ind}case Con{{+b7, +t8}}: Equal.cong(Nat, Nat, z => 1n+z, List.length(&2, U32, Bp.pack(t8)), Bp.byte_count(List.length(&2, Bool, t8)), pack_len(t8))')
    w('')
    bc_cases = '\n'.join(f'        case {b}n: {{==}}' for b in range(8))
    w(TPL.render('text_bcx', ARGS=ARGS, A_=A_, TRUE=TRUE, bc_cases=bc_cases))
    valid_or = 'Bool.or(True{}, U32.is_le(K, 0))' if not NB else f'Bool.or(False{{}}, U32.is_le(K, {NB}))'
    lim_rw = '' if not NB else f'''  %Equal.sym(Bool, U32.is_le(K, {NB}), True{{}}, ok_hlim({A_}, h)) :
    {{O.bk_cap(Bool.or(False{{}}, _), K, Array.size(U32, FD.array__thaw(U32, T))) == (O.Bits{{FD.array__thaw(U32, T), K}}, True{{}}) : O.Bits & Bool}}
'''
    after_or = 'Bool.or(True{}, U32.is_le(K, 0))' if not NB else 'Bool.or(False{}, True{})'
    w(TPL.render('text_valid', ARGS=ARGS, A_=A_, TRUE=TRUE, after_or=after_or, lim_rw=lim_rw, p=p))
    HYP = (TPL.text('HYP'))
    PB = (f'dd, D, X, q, r, dw, T, K, kb, B, e, hr, hd, hdw31({A_}, h), ok_hkb({A_}, h), ok_hN({A_}, h), ok_hNk({A_}, h),\n'
          f'      hWq({A_}, h), hl, pf, ok_pf({A_}, h), ok_htz({A_}, h), ok_hbz({A_}, h), hz')
    w(TPL.render('text_putx_go', ARGS=ARGS, A_=A_, HYP=HYP, PB=PB, TRUE=TRUE, p=p))
    LH = ['  for +m: MB', '  for +dd: Nat', '  for +D: FD.array__Tree<U32>', '  for +X: U32', '  for +q: Nat', '  for +r: Nat',
          '  for +e: {U32.to_nat(X) == Nat.add(A.quad(q), r) : Nat}', '  for +hr: {Nat.is_lt(r, 4n) == True{} : Bool}',
          '  for +hd: {Nat.is_lt(dd, 29n) == True{} : Bool}', '  for +pf: {FD.array__perfect(U32, dd, D) == True{} : Bool}',
          '  for +hl: {Nat.is_le(Nat.add(q, UWD.NWN(Nat.add(r, List.length(&2, U32, ENC(m))))), VB.pw(dd)) == True{} : Bool}',
          '  for +hz: {VS.bt(Nat.add(List.length(&2, U32, ENC(m)), PADB(r, m)), VS.bdr(Nat.add(A.quad(q), r), UA.BYT(D))) == UW.ZB(Nat.add(List.length(&2, U32, ENC(m)), PADB(r, m))) : +List<U32>}',
          '  for +hok: {OK(m) == True{} : Bool}']
    CONV = TPL.render('CONV', A_=A_)
    w('# ---- the interface\'s laws ----------------------------------------------------------------------\n')
    w('law putx:\n' + '\n'.join(LH) + f'\n  {{T.{p}_putk(FD.array__thaw(U32, D), X, TH(m)) == (FD.array__thaw(U32, PUTX(m, dd, D, q, r)), (TH(m), SZ(m))) : Array<U32> & (O.Bits & U32)}}')
    w(f'def putx(m, dd, D, X, q, r, e, hr, hd, pf, hl, hz, hok):\n  match m:\n{CONV}\n      putx_go({A_}, dd, D, X, q, r, e, hr, hd, pf, hl2, hz2, hok)\n')
    w('law putx_bytes:\n' + '\n'.join(LH) + '\n  {UA.BYT(PUTX(m, dd, D, q, r)) == UW.SPL(UA.BYT(D), Nat.add(A.quad(q), r), List.append(&2, U32, ENC(m), UW.ZB(PADB(r, m)))) : +List<U32>}')
    w(TPL.render('text_putx_bytes', A_=A_, CONV=CONV, TRUE=TRUE, p=p))
    if NB:
        dom = f'Nat.is_le(List.length(&2, Bool, CO.BITS(T, K)), U32.to_nat({NB}))'
        dproof = (f'FD.logic__subst(Nat, z => {{Nat.is_le(z, U32.to_nat({NB})) == {TRUE}}}, U32.to_nat(K), List.length(&2, Bool, CO.BITS(T, K)), '
                  f'Equal.sym(Nat, List.length(&2, Bool, CO.BITS(T, K)), U32.to_nat(K), lbits({A_}, hok)), '
                  f'FD.logic__subst(Bool, z => {{z == {TRUE}}}, U32.is_le(K, {NB}), Nat.is_le(U32.to_nat(K), U32.to_nat({NB})), VU.le_u32(K, {NB}), ok_hlim({A_}, hok)))')
    else:
        dom = 'Nat.is_le(List.length(&2, Bool, CO.BITS(T, K)), List.length(&2, Bool, CO.BITS(T, K)))'
        dproof = 'FD.nat__le_refl(List.length(&2, Bool, CO.BITS(T, K)))'
    w(TPL.render('text_encx_spec', TRUE=TRUE, dom=dom, dproof=dproof, sch=sch))
    if NB and NB < MAXX_LIM:
        M8 = NB // 8
        w(TPL.render('text_x8le', ARGS=ARGS, A_=A_, M8=M8, NB=NB, TRUE=TRUE))
    return '\n'.join(L) + '\n'


def main():
    # accepts '--check' (var_finish.finish reads it)
    out = {fname(p): text(p) for p in KINDS}
    return finish(out, 'stale generated bit-list encx modules: ', 'generated bit-list encx modules are current', dify={})


if __name__ == '__main__':
    main()
