#!/usr/bin/env python3
"""Emit proofs/obj/blist_obj.bend: root laws of lists with a limit (SSZ
List[E, L]) whose elements are packed in byte storage (O.Words), for element
kinds the uint64 list law (proofs/obj/ulist_obj.bend `ul`) does not cover:

  K = '1'   List[uint8, L]      (one byte per element; packed_bytes it1)
  K = '2'   List[uint16, L]     (two bytes per element; packed_bytes it2)
  K = 'h'   List[Bytes32, L]    (one chunk per element, composite: words_root items)

The runtime root of every such list is
    O.mix_count(hl, sh, O.words_root(hl, h, o, depth, seg))
(sh = log2 of the element's byte size): the byte storage's chunk tree with the
element count (the byte length shifted right by sh) mixed in. Per kind:

  rep_l{K}(o, s)    byte storage (list_obj wfl: empty or not) of whole
                    elements, at most the schema's limit of them
  ok_l{K}(s, d)     the schema is a list of the element whose chunk limit has
                    minimal depth d (one Bool; the depth is a parameter, so a
                    caller can hold it as a variable, see obj_support DV)
  l{K}_rs           the digest (bdig, the runtime's by bl_st) is a
                    specification root of the elements

The state law bl_st is ulist_obj's ul_st for any shift; the byte packing is
ulist_obj ul_pack, the tree root_support at_depth_tree, the counts the
progressive list laws' (codegen/proofs/laws/prog_laws.py count_law).

    python3 codegen/proofs/laws/blist_laws.py [--check]
"""
import sys as _sys
import pathlib as _pathlib
_sys.path.insert(0, str(_pathlib.Path(__file__).resolve().parents[3]))  # the repository root: `codegen` is importable when this file runs as a script
import sys

from codegen.proofs.laws import prog_laws as PL  # noqa: E402

from codegen.core.paths import ROOT  # noqa: E402
from codegen.core.shared_laws import light_pair  # noqa: E402
from codegen.proofs.support import light_split as LS  # noqa: E402
OUT = ROOT / 'proofs/obj/blist_obj.bend'
M = 'Maybe<&2, +List<U32>>'
SL = 'F.array__slots(U32, t)'
SLF = 'F.array__slots(U32, F.array__freeze(U32, F.array__thaw(U32, t)))'
BYTES = f'WS.btake(U32.to_nat(N), FX.limbs({SL}))'
W_ = 'O.Words{F.array__thaw(U32, t), N}'
TY = 'B.Buf & (O.Words & D.Digest)'

HEAD = '''import Base
import ../../src/buffer.bend as B
import ../../src/digest.bend as D
import ../../src/obj.bend as O
import ../../types/schema.bend as S
import ../../types/primitive.bend as P
import ../../spec/root_relation.bend as RR
import ../../spec/primitives.bend as SP
import ../../spec/codec.bend as Codec
import ../../spec/limits.bend as Lim
import ../../spec/bit_root.bend as Mix
import ../../spec/nat_bytes.bend as Len
import ../../proofs/primitive_invariants.bend as V
import ../../proofs/nat_order.bend as Order
import ../compact/found.bend as F
import ./spec_fixed.bend as FX
import ./mtree_defs.bend as MD
import ./mtree_run.bend as MR
import ./root_support.bend as RS
import ./words_spec.bend as WS
import ./words_root.bend as WR
import ./words_obj.bend as WO
import ./list_root.bend as LR
import ./list_obj.bend as LO
import ./ulist_obj.bend as UL
import ./packed_bytes.bend as PB
import ./nat_facts.bend as NF
import ./schema_shapes.bend as SH
import ./dk.bend as DK

# GENERATED by blist_laws (codegen). Do not edit.
# Lists with a limit whose elements are packed in byte storage (uint8, uint16,
# Bytes32; uint64 is ulist_obj's): the runtime root is the storage's chunk tree
# with the element count mixed in; the specification's is
# spec/root_relation.bend `sequence` (basic: packed bytes; Bytes32: one root per
# element) under the list's chunk limit, with the count.

# ---- the runtime root, for any element size 2^sh -----------------------------

def bdig(+hl: Nat, o: O.Words, +depth: Nat, +sh: Nat) -> D.Digest:
  match o:
    case O.Words{ws, +n}: O.mix_len(hl, MD.rtree(depth, Nat.is_lt(0n, O.chunks_of(n)), hl, MR.clist(O.chunks_of(n), F.array__slots(U32, F.array__freeze(U32, ws)), 0n), 0n), U32.shrn(n, sh))

def bl_st(+hl: Nat, -h: B.Buf, -o: O.Words, +dU: U32, +seg: U32, +depth: Nat, +sh: Nat, +wf: LO.wfl(o), +edu: {U32.to_nat(dU) == depth : Nat})
    -> {O.mix_count(hl, sh, O.words_root(hl, h, o, dU, seg)) == (h, (o, bdig(hl, o, depth, sh))) : B.Buf & (O.Words & D.Digest)}:
  match wf:
    case Inl{w}:
      (+t, w1) = w
      (+dw, w2) = w1
      (+N, w3) = w2
      (+eo, w4) = w3
      (+pf, w5) = w4
      (+hd, +en0) = w5
      %Equal.sym(O.Words, o, O.Words{F.array__thaw(U32, t), N}, eo) :
        {O.mix_count(hl, sh, O.words_root(hl, h, _, dU, seg)) == (h, (_, bdig(hl, _, depth, sh))) : B.Buf & (O.Words & D.Digest)}
      %Equal.sym(B.Buf & (O.Words & D.Digest), O.words_root(hl, h, O.Words{F.array__thaw(U32, t), N}, dU, seg), (h, (O.Words{F.array__thaw(U32, t), N}, MD.rtree(depth, False{}, hl, MR.clist(0n, F.array__slots(U32, t), 0n), 0n))),
          UL.wr0(hl, h, dU, seg, N, depth, dw, t, en0, pf, edu, hd)) :
        {O.mix_count(hl, sh, _) == (h, (O.Words{F.array__thaw(U32, t), N}, bdig(hl, O.Words{F.array__thaw(U32, t), N}, depth, sh))) : B.Buf & (O.Words & D.Digest)}
      %Equal.sym(F.array__Tree<U32>, F.array__freeze(U32, F.array__thaw(U32, t)), t, F.array__freeze_thaw(U32, t)) :
        {(h, (O.Words{F.array__thaw(U32, t), N}, O.mix_len(hl, MD.rtree(depth, False{}, hl, MR.clist(0n, F.array__slots(U32, t), 0n), 0n), U32.shrn(N, sh)))) == (h, (O.Words{F.array__thaw(U32, t), N}, O.mix_len(hl, MD.rtree(depth, Nat.is_lt(0n, O.chunks_of(N)), hl, MR.clist(O.chunks_of(N), F.array__slots(U32, _), 0n), 0n), U32.shrn(N, sh)))) : B.Buf & (O.Words & D.Digest)}
      %Equal.sym(Nat, U32.to_nat(N), 0n, en0) :
        {(h, (O.Words{F.array__thaw(U32, t), N}, O.mix_len(hl, MD.rtree(depth, False{}, hl, MR.clist(0n, F.array__slots(U32, t), 0n), 0n), U32.shrn(N, sh)))) == (h, (O.Words{F.array__thaw(U32, t), N}, O.mix_len(hl, MD.rtree(depth, Nat.is_lt(0n, Nat.div(Nat.add(_, 31n), 32n)), hl, MR.clist(Nat.div(Nat.add(_, 31n), 32n), F.array__slots(U32, t), 0n), 0n), U32.shrn(N, sh)))) : B.Buf & (O.Words & D.Digest)}
      {==}
    case Inr{w}:
      (+t, w1) = w
      (+dw, w2) = w1
      (+N, w3) = w2
      (+q, w4) = w3
      (+r, w5) = w4
      (+eo, w6) = w5
      (+pf, w7) = w6
      (+hd, w8) = w7
      (+enq, w9) = w8
      (+h1, w10) = w9
      (+h32, w11) = w10
      (+room, +slack) = w11
      %Equal.sym(O.Words, o, O.Words{F.array__thaw(U32, t), N}, eo) :
        {O.mix_count(hl, sh, O.words_root(hl, h, _, dU, seg)) == (h, (_, bdig(hl, _, depth, sh))) : B.Buf & (O.Words & D.Digest)}
      %Equal.sym(B.Buf & (O.Words & D.Digest), O.words_root(hl, h, O.Words{F.array__thaw(U32, t), N}, dU, seg), (h, (O.Words{F.array__thaw(U32, t), N}, MD.rtree(depth, True{}, hl, MR.clist(1n+q, F.array__slots(U32, t), 0n), 0n))),
          WR.bv_state(hl, h, dU, seg, N, depth, q, r, dw, t, enq, h1, h32, pf, room, slack, edu, hd)) :
        {O.mix_count(hl, sh, _) == (h, (O.Words{F.array__thaw(U32, t), N}, bdig(hl, O.Words{F.array__thaw(U32, t), N}, depth, sh))) : B.Buf & (O.Words & D.Digest)}
      %Equal.sym(F.array__Tree<U32>, F.array__freeze(U32, F.array__thaw(U32, t)), t, F.array__freeze_thaw(U32, t)) :
        {(h, (O.Words{F.array__thaw(U32, t), N}, O.mix_len(hl, MD.rtree(depth, True{}, hl, MR.clist(1n+q, F.array__slots(U32, t), 0n), 0n), U32.shrn(N, sh)))) == (h, (O.Words{F.array__thaw(U32, t), N}, O.mix_len(hl, MD.rtree(depth, Nat.is_lt(0n, O.chunks_of(N)), hl, MR.clist(O.chunks_of(N), F.array__slots(U32, _), 0n), 0n), U32.shrn(N, sh)))) : B.Buf & (O.Words & D.Digest)}
      %Equal.sym(Nat, O.chunks_of(N), 1n+q, WO.chunks_q(N, q, r, enq, h1, h32)) :
        {(h, (O.Words{F.array__thaw(U32, t), N}, O.mix_len(hl, MD.rtree(depth, True{}, hl, MR.clist(1n+q, F.array__slots(U32, t), 0n), 0n), U32.shrn(N, sh)))) == (h, (O.Words{F.array__thaw(U32, t), N}, O.mix_len(hl, MD.rtree(depth, Nat.is_lt(0n, _), hl, MR.clist(_, F.array__slots(U32, t), 0n), 0n), U32.shrn(N, sh)))) : B.Buf & (O.Words & D.Digest)}
      {==}

# ---- counts and arithmetic ---------------------------------------------------

# The count mixed in: the element count (the byte length shifted right).
def plen(+hl: Nat, +ehl: {hl == 64n : Nat}, +N: U32, +sh: Nat, +R: D.Digest, +c: Nat, +ec: {c == U32.to_nat(U32.shrn(N, sh)) : Nat})
    -> {Mix.mix_length_bytes(Some{D.bytes(R)}, Len.encoding(32n, c)) == Some{D.bytes(O.mix_len(hl, R, U32.shrn(N, sh)))} : Maybe<&2, +List<U32>>}:
  %Equal.sym(Nat, c, U32.to_nat(U32.shrn(N, sh)), ec) : {Mix.mix_length_bytes(Some{D.bytes(R)}, Len.encoding(32n, _)) == Some{D.bytes(O.mix_len(hl, R, U32.shrn(N, sh)))} : Maybe<&2, +List<U32>>}
  LR.mix_bytes(hl, ehl, R, U32.shrn(N, sh))

def plen0(+hl: Nat, +ehl: {hl == 64n : Nat}, +N: U32, +sh: Nat, +R: D.Digest, +c0: {U32.to_nat(U32.shrn(N, sh)) == 0n : Nat})
    -> {Mix.mix_length_bytes(Some{D.bytes(R)}, Len.encoding(32n, 0n)) == Some{D.bytes(O.mix_len(hl, R, U32.shrn(N, sh)))} : Maybe<&2, +List<U32>>}:
  plen(hl, ehl, N, sh, R, 0n, Equal.sym(Nat, U32.to_nat(U32.shrn(N, sh)), 0n, c0))

law mul1:
  for +L: Nat
  {Nat.mul(L, 1n) == L : Nat}
def mul1(L):
  match L:
    case 0n: {==}
    case 1n+ +p:
      %Equal.sym(Nat, Nat.mul(p, 1n), p, mul1(p)) : {1n+_ == 1n+p : Nat}
      {==}

law dz:
  for +c: Nat
  for +e: {0n == Nat.double(c) : Nat}
  {0n == c : Nat}
def dz(c, e):
  match c:
    case 0n: {==}
    case 1n+ +p: Empty.absurd({0n == 1n+p : Nat}, MD.false_true(Equal.sym(Bool, True{}, False{}, Equal.cong(Nat, Bool, x => Nat.is_eq(x, 0n), 0n, Nat.double(1n+p), e))))

def dbl_zero(+c: Nat, +e: {0n == Nat.double(c) : Nat}) -> {c == 0n : Nat}: Equal.sym(Nat, 0n, c, dz(c, e))

# 32 c bytes are c chunks.
law hdiv:
  for +c: Nat
  {Nat.div(Nat.add(WS.e32(c), 31n), 32n) == c : Nat}
def hdiv(c):
  match c:
    case 0n: {==}
    case 1n+ +p:
      %Equal.sym(Nat, WS.e32(1n+p), Nat.add(WS.e32(p), 32n), Equal.sym(Nat, Nat.add(WS.e32(p), 32n), WS.e32(1n+p), UL.add32(p))) :
        {Nat.div(Nat.add(_, 31n), 32n) == 1n+p : Nat}
      WS.chunks_count(p, 32n, {==}, {==})

'''


def count_items_h(w):
    w('law hcount:')
    w('  for +k: Nat')
    w('  for +W: List<&2, U32>')
    w('  for +i: Nat')
    w('  {Codec.count(WR.items(k, W, i)) == k : Nat}')
    w('def hcount(k, W, i):')
    w('  match k:')
    w('    case 0n: {==}')
    w('    case 1n+ +q:')
    w('      %Equal.sym(Nat, Codec.count(WR.items(q, W, 1n+i)), q, hcount(q, W, 1n+i)) : {1n+_ == 1n+q : Nat}')
    w('      {==}')
    w('')


def and_lets(conj, ind='  '):
    """let-bind the conjuncts of fold(conj) from `ok`: c0 .. c{n-1}."""
    out = []
    prev = 'ok'

    def fold(cs):
        t = cs[-1]
        for c in reversed(cs[:-1]):
            t = f'Bool.and({c}, {t})'
        return t
    for j in range(len(conj) - 1):
        rest = fold(conj[j + 1:])
        out.append(f'{ind}+c{j} = DK.and_l({conj[j]}, {rest}, {prev})')
        if j == len(conj) - 2:
            out.append(f'{ind}+c{j + 1} = DK.and_r({conj[j]}, {rest}, {prev})')
        else:
            out.append(f'{ind}+k{j + 1} = DK.and_r({conj[j]}, {rest}, {prev})')
            prev = f'k{j + 1}'
    return out, fold(conj)


def basic_kind(K, w):
    """List[uint8] (K = '1') or List[uint16] (K = '2')."""
    sh = {'1': 0, '2': 1}[K]
    Wd = {'1': 'P.U8{}', '2': 'P.U16{}'}[K]
    E = f'S.Unsigned{{{Wd}}}'
    isw = {'1': 'PB.is_U8', '2': 'PB.is_U16'}[K]
    shape = {'1': 'PB.is_U8_shape', '2': 'PB.is_U16_shape'}[K]
    view = {'1': 'PB.vview1', '2': 'PB.vview2'}[K]
    name = {'1': 'uint8', '2': 'uint16'}[K]
    mul = {'1': '1n', '2': '2n'}[K]
    if K == '1':
        cN = 'U32.to_nat(N)'
        cnt = lambda o: f'U32.to_nat(WO.len({o}))'
        items = f'PB.it1(U32.to_nat(N), {BYTES})'
        enc = f'PB.pb1(U32.to_nat(N), {BYTES}, PB.vscope(N, q, r, dw, t, enq, h32, pf, room))'
        cnt_pf = f'pc1(U32.to_nat(N), {BYTES}, PB.vscope(N, q, r, dw, t, enq, h32, pf, room))'
    else:
        cN = 'U32.to_nat(U32.shrn(N, 1n))'
        cnt = lambda o: f'PB.cnt2({o})'
        items = f'PB.it2(U32.to_nat(U32.shrn(N, 1n)), {BYTES})'
        enc = 'PB.v2_enc(N, q, r, dw, t, eNN, enq, h32, pf, room)'
        cnt_pf = f'pc2(U32.to_nat(U32.shrn(N, 1n)), {BYTES}, PB.v2_scope(N, q, r, dw, t, eNN, enq, h32, pf, room))'
    LIM = f'Nat.div(Nat.add(Nat.mul(L, {mul}), 31n), 32n)'
    SCH = f'S.ListOf{{{E}, L}}'
    w(f'# ---- List[{name}] ' + '-' * 50)
    w('')
    w(f'# The object represents a value of the list schema s: byte storage of whole')
    w(f'# elements, at most the limit of them.')
    if K == '1':
        w(f'def rep_l{K}(o: O.Words, +s: S.Schema) -> Data:')
        w(f'  DK.P2(LO.wfl(o), {{Nat.is_le({cnt("o")}, SH.ListOf_limit(s)) == True{{}} : Bool}})')
        w(f'def rep_wf{K}(-o: O.Words, +s: S.Schema, +rep: rep_l{K}(o, s)) -> LO.wfl(o):')
        w('  (+wf, +hv) = rep')
        w('  wf')
    else:
        w(f'def rep_l{K}(o: O.Words, +s: S.Schema) -> Data:')
        w(f'  DK.P2(LO.wfl(o), DK.P2({{U32.to_nat(WO.len(o)) == Nat.double(PB.cnt2(o)) : Nat}}, {{Nat.is_le(PB.cnt2(o), SH.ListOf_limit(s)) == True{{}} : Bool}}))')
        w(f'def rep_wf{K}(-o: O.Words, +s: S.Schema, +rep: rep_l{K}(o, s)) -> LO.wfl(o):')
        w('  (+wf, +r1) = rep')
        w('  wf')
    w('')
    conj = ['SH.is_ListOf(s)', 'SH.is_Unsigned(SH.ListOf_element(s))', f'{isw}(SH.Unsigned_width(SH.ListOf_element(s)))',
            f'Lim.minimal(Nat.div(Nat.add(Nat.mul(SH.ListOf_limit(s), {mul}), 31n), 32n), depth)']
    lets, okt = and_lets(conj)
    w(f'# The schema is a list of {name} whose chunk limit has minimal depth `depth`.')
    w(f'def ok_l{K}(+s: S.Schema, +depth: Nat) -> Bool: {okt}')
    w('')
    # the limit lemma
    w(f'def l{K}_lim(+N: U32, +q: Nat, +r: Nat, +L: Nat, +t: F.array__Tree<U32>,')
    if K == '2':
        w(f'    +eNN: {{U32.to_nat(N) == Nat.double({cN}) : Nat}},')
    w('    +enq: {U32.to_nat(N) == Nat.add(WS.e32(q), r) : Nat},')
    w('    +h1: {Nat.is_lt(0n, r) == True{} : Bool}, +h32: {Nat.is_le(r, 32n) == True{} : Bool},')
    w(f'    +hvN: {{Nat.is_le({cN}, L) == True{{}} : Bool}})')
    w(f'    -> {{Nat.is_le(MD.dlen(MR.clist(1n+q, {SL}, 0n)), {LIM}) == True{{}} : Bool}}:')
    if K == '1':
        w('  +hn = UL.rw_le_l(U32.to_nat(N), Nat.add(WS.e32(q), r), L, enq, hvN)')
        w(f'  +hm = UL.rw_le_r(Nat.add(WS.e32(q), r), L, Nat.mul(L, 1n), Equal.sym(Nat, Nat.mul(L, 1n), L, mul1(L)), hn)')
    else:
        w(f'  +hd2 = Order.double_monotone({cN}, L, hvN)')
        w(f'  +hm1 = UL.rw_le_r(Nat.double({cN}), Nat.double(L), Nat.mul(L, 2n), PB.dbl_mul(L), hd2)')
        w(f'  +ec = Equal.trans(Nat, Nat.double({cN}), U32.to_nat(N), Nat.add(WS.e32(q), r), Equal.sym(Nat, U32.to_nat(N), Nat.double({cN}), eNN), enq)')
        w(f'  +hm = UL.rw_le_l(Nat.double({cN}), Nat.add(WS.e32(q), r), Nat.mul(L, 2n), ec, hm1)')
    w(f'  LR.bl_hlen(q, t, Nat.mul(L, {mul}), NF.chunk_le(q, r, Nat.mul(L, {mul}), h1, h32, hm))')
    w('')
    # the body
    args = ['+hl: Nat', '+ehl: {hl == 64n : Nat}', '-o: O.Words', '+L: Nat', '+depth: Nat', '+wf: LO.wfl(o)']
    if K == '2':
        args.append('+eN: {U32.to_nat(WO.len(o)) == Nat.double(PB.cnt2(o)) : Nat}')
    args += [f'+hv: {{Nat.is_le({cnt("o")}, L) == True{{}} : Bool}}',
             f'+hmin: {{Lim.minimal({LIM}, depth) == True{{}} : Bool}}',
             '+hdep: {Nat.is_lt(depth, 64n) == True{} : Bool}']
    w(f'def l{K}_body({", ".join(args)})')
    w(f'    -> RR.roots({view}(o), {SCH}, [D.bytes(bdig(hl, o, depth, {sh}n))]):')
    w('  match wf:')
    w('    case Inl{w}:')
    for a, b, c in [('t', 'w1', 'w'), ('dw', 'w2', 'w1'), ('N', 'w3', 'w2'), ('eo', 'w4', 'w3'), ('pf', 'w5', 'w4')]:
        w(f'      (+{a}, {b}) = {c}')
    w('      (+hd, +en0) = w5')
    if K == '2':
        w('      +eNN = PB.eq_n2(o, t, N, eo, eN)')
        w(f'      +c0 = dbl_zero({cN}, Equal.trans(Nat, 0n, U32.to_nat(N), Nat.double({cN}), Equal.sym(Nat, U32.to_nat(N), 0n, en0), eNN))')
    else:
        w('      +c0 = Equal.sym(Nat, 0n, U32.to_nat(N), Equal.sym(Nat, U32.to_nat(N), 0n, en0))')
    Lc0 = f'MR.clist(0n, {SL}, 0n)'
    LcF = lambda x: f'MR.clist({x}, F.array__slots(U32, _), 0n)'
    w(f'      %Equal.sym(O.Words, o, {W_}, eo) :')
    w(f'        RR.roots({view}(_), {SCH}, [D.bytes(bdig(hl, _, depth, {sh}n))])')
    it0 = items.replace(SL, SLF)
    w(f'      %Equal.sym(Nat, {cN}, 0n, c0) :')
    w(f'        RR.roots(S.Sequence{{{it0.replace(cN, "_", 1)}}}, {SCH}, [D.bytes(bdig(hl, {W_}, depth, {sh}n))])')
    w('      %Equal.sym(F.array__Tree<U32>, F.array__freeze(U32, F.array__thaw(U32, t)), t, F.array__freeze_thaw(U32, t)) :')
    w(f'        RR.roots(S.Sequence{{S.EmptyItems{{}}}}, {SCH}, [D.bytes(O.mix_len(hl, MD.rtree(depth, Nat.is_lt(0n, O.chunks_of(N)), hl, {LcF("O.chunks_of(N)")}, 0n), U32.shrn(N, {sh}n)))])')
    w('      %Equal.sym(Nat, U32.to_nat(N), 0n, en0) :')
    w(f'        RR.roots(S.Sequence{{S.EmptyItems{{}}}}, {SCH}, [D.bytes(O.mix_len(hl, MD.rtree(depth, Nat.is_lt(0n, Nat.div(Nat.add(_, 31n), 32n)), hl, MR.clist(Nat.div(Nat.add(_, 31n), 32n), {SL}, 0n), 0n), U32.shrn(N, {sh}n)))])')
    R0 = f'MD.rtree(depth, False{{}}, hl, {Lc0}, 0n)'
    w(f'      (MD.bytes_list({Lc0}), (([], ({{==}}, {{==}})), (D.bytes({R0}),')
    w(f'        ((depth, (hmin, RS.at_depth_tree({LIM}, depth, hl, {Lc0}, hdep, LR.zero_le({LIM}), ehl))),')
    w(f'         plen0(hl, ehl, N, {sh}n, {R0}, c0)))))')
    w('    case Inr{w}:')
    for i, (a, b) in enumerate([('t', 'w1'), ('dw', 'w2'), ('N', 'w3'), ('q', 'w4'), ('r', 'w5'), ('eo', 'w6'), ('pf', 'w7'), ('hd', 'w8'), ('enq', 'w9'), ('h1', 'w10'), ('h32', 'w11')]):
        w(f'      (+{a}, {b}) = {"w" if i == 0 else "w" + str(i)}')
    w('      (+room, +slack) = w11')
    if K == '2':
        w('      +eNN = PB.eq_n2(o, t, N, eo, eN)')
        w(f'      +hvN = LO_len2(o, t, N, L, eo, hv)')
        lim = f'l{K}_lim(N, q, r, L, t, eNN, enq, h1, h32, hvN)'
    else:
        w(f'      +hvN = len1(o, t, N, L, eo, hv)')
        lim = f'l{K}_lim(N, q, r, L, t, enq, h1, h32, hvN)'
    w(f'      %Equal.sym(O.Words, o, {W_}, eo) :')
    w(f'        RR.roots({view}(_), {SCH}, [D.bytes(bdig(hl, _, depth, {sh}n))])')
    itF = items.replace(SL, 'F.array__slots(U32, _)')
    w('      %Equal.sym(F.array__Tree<U32>, F.array__freeze(U32, F.array__thaw(U32, t)), t, F.array__freeze_thaw(U32, t)) :')
    w(f'        RR.roots(S.Sequence{{{itF}}}, {SCH}, [D.bytes(O.mix_len(hl, MD.rtree(depth, Nat.is_lt(0n, O.chunks_of(N)), hl, {LcF("O.chunks_of(N)")}, 0n), U32.shrn(N, {sh}n)))])')
    w('      %Equal.sym(Nat, O.chunks_of(N), 1n+q, WO.chunks_q(N, q, r, enq, h1, h32)) :')
    w(f'        RR.roots(S.Sequence{{{items}}}, {SCH}, [D.bytes(O.mix_len(hl, MD.rtree(depth, Nat.is_lt(0n, _), hl, MR.clist(_, {SL}, 0n), 0n), U32.shrn(N, {sh}n)))])')
    Lc = f'MR.clist(1n+q, {SL}, 0n)'
    R = f'MD.rtree(depth, True{{}}, hl, {Lc}, 0n)'
    w(f'      (MD.bytes_list({Lc}),')
    w(f'        (({BYTES}, ({enc}, UL.ul_pack(N, q, r, dw, t, enq, h1, h32, pf, room, slack))),')
    w(f'         (D.bytes({R}), ((depth, (hmin, RS.at_depth_tree({LIM}, depth, hl, {Lc}, hdep, {lim}, ehl))),')
    w(f'           plen(hl, ehl, N, {sh}n, {R}, Codec.count({items}), {cnt_pf})))))')
    w('')
    # over the schema variable
    w(f'# A list of {name}: its digest is a specification root of its elements.')
    w(f'def l{K}_rs(+hl: Nat, +ehl: {{hl == 64n : Nat}}, -h: B.Buf, -o: O.Words, +s: S.Schema, +depth: Nat, +dU: U32, +seg: U32,')
    w(f'    +rep: rep_l{K}(o, s),')
    w(f'    +ok: {{ok_l{K}(s, depth) == True{{}} : Bool}},')
    w('    +edu: {U32.to_nat(dU) == depth : Nat},')
    w('    +hdep: {Nat.is_lt(depth, 64n) == True{} : Bool})')
    w(f'    -> RR.roots({view}(o), s, [D.bytes(bdig(hl, o, depth, {sh}n))]):')
    if K == '2':
        w('  (+wf, +r1) = rep')
        w('  (+eN, +hv) = r1')
    else:
        w('  (+wf, +hv) = rep')
    for x in lets:
        w(x)
    w(f'  %Equal.sym(S.Schema, s, S.ListOf{{SH.ListOf_element(s), SH.ListOf_limit(s)}}, SH.ListOf_shape(s, c0)) :')
    w(f'    RR.roots({view}(o), _, [D.bytes(bdig(hl, o, depth, {sh}n))])')
    w('  %Equal.sym(S.Schema, SH.ListOf_element(s), S.Unsigned{SH.Unsigned_width(SH.ListOf_element(s))}, SH.Unsigned_shape(SH.ListOf_element(s), c1)) :')
    w(f'    RR.roots({view}(o), S.ListOf{{_, SH.ListOf_limit(s)}}, [D.bytes(bdig(hl, o, depth, {sh}n))])')
    w(f'  %Equal.sym(P.Width, SH.Unsigned_width(SH.ListOf_element(s)), {Wd}, {shape}(SH.Unsigned_width(SH.ListOf_element(s)), c2)) :')
    w(f'    RR.roots({view}(o), S.ListOf{{S.Unsigned{{_}}, SH.ListOf_limit(s)}}, [D.bytes(bdig(hl, o, depth, {sh}n))])')
    ev = ', eN' if K == '2' else ''
    w(f'  l{K}_body(hl, ehl, o, SH.ListOf_limit(s), depth, wf{ev}, hv, c3, hdep)')
    w('')



def len_lemmas(w):
    w('def cnth(o: O.Words) -> Nat: U32.to_nat(U32.shrn(WO.len(o), 5n))')
    w('')
    # the count bound moved to the destructured length
    w('def len1(-o: O.Words, +t: F.array__Tree<U32>, +N: U32, +L: Nat, +eo: {o == O.Words{F.array__thaw(U32, t), N} : O.Words},')
    w('    +hv: {Nat.is_le(U32.to_nat(WO.len(o)), L) == True{} : Bool}) -> {Nat.is_le(U32.to_nat(N), L) == True{} : Bool}:')
    w('  %Equal.cong(O.Words, U32, WO.len, o, O.Words{F.array__thaw(U32, t), N}, eo) : {Nat.is_le(U32.to_nat(_), L) == True{} : Bool}')
    w('  hv')
    w('')
    for K, sh, cnt in (('2', 1, 'PB.cnt2'), ('h', 5, 'cnth')):
        nm = 'LO_len2' if K == '2' else 'lenh'
        w(f'def {nm}(-o: O.Words, +t: F.array__Tree<U32>, +N: U32, +L: Nat, +eo: {{o == O.Words{{F.array__thaw(U32, t), N}} : O.Words}},')
        w(f'    +hv: {{Nat.is_le({cnt}(o), L) == True{{}} : Bool}}) -> {{Nat.is_le(U32.to_nat(U32.shrn(N, {sh}n)), L) == True{{}} : Bool}}:')
        w(f'  %Equal.cong(O.Words, U32, WO.len, o, O.Words{{F.array__thaw(U32, t), N}}, eo) : {{Nat.is_le(U32.to_nat(U32.shrn(_, {sh}n)), L) == True{{}} : Bool}}')
        w('  hv')
        w('')


def bytes32_kind(w):
    E = 'S.ByteVector{32n}'
    SCH = f'S.ListOf{{{E}, L}}'
    c = 'U32.to_nat(U32.shrn(N, 5n))'
    w('# ---- List[Bytes32] ' + '-' * 50)
    w('')
    w('def hview(o: O.Words) -> S.Value:')
    w('  match o:')
    w('    case O.Words{ws, +n}: S.Sequence{WR.items(U32.to_nat(U32.shrn(n, 5n)), F.array__slots(U32, F.array__freeze(U32, ws)), 0n)}')
    w('')
    w('# The object represents a value of the list schema s: byte storage of whole')
    w('# 32-byte elements, at most the limit of them.')
    w('def rep_lh(o: O.Words, +s: S.Schema) -> Data:')
    w('  DK.P2(LO.wfl(o), DK.P2({U32.to_nat(WO.len(o)) == WS.e32(cnth(o)) : Nat}, {Nat.is_le(cnth(o), SH.ListOf_limit(s)) == True{} : Bool}))')
    w('def rep_wfh(-o: O.Words, +s: S.Schema, +rep: rep_lh(o, s)) -> LO.wfl(o):')
    w('  (+wf, +r1) = rep')
    w('  wf')
    w('')
    conj = ['SH.is_ListOf(s)', 'SH.is_ByteVector(SH.ListOf_element(s))', 'Nat.is_eq(SH.ByteVector_length(SH.ListOf_element(s)), 32n)',
            'Lim.minimal(SH.ListOf_limit(s), depth)']
    lets, okt = and_lets(conj)
    w('# The schema is a list of Bytes32 whose limit has minimal depth `depth`.')
    w(f'def ok_lh(+s: S.Schema, +depth: Nat) -> Bool: {okt}')
    w('')
    w('def eq_nh(-o: O.Words, +t: F.array__Tree<U32>, +N: U32, +eo: {o == O.Words{F.array__thaw(U32, t), N} : O.Words},')
    w(f'    +eN: {{U32.to_nat(WO.len(o)) == WS.e32(cnth(o)) : Nat}}) -> {{U32.to_nat(N) == WS.e32({c}) : Nat}}:')
    w('  %Equal.cong(O.Words, U32, WO.len, o, O.Words{F.array__thaw(U32, t), N}, eo) : {U32.to_nat(_) == WS.e32(U32.to_nat(U32.shrn(_, 5n))) : Nat}')
    w('  eN')
    w('')
    w(f'def chq(+N: U32, +eNN: {{U32.to_nat(N) == WS.e32({c}) : Nat}}) -> {{O.chunks_of(N) == {c} : Nat}}:')
    w(f'  %Equal.sym(Nat, U32.to_nat(N), WS.e32({c}), eNN) : {{Nat.div(Nat.add(_, 31n), 32n) == {c} : Nat}}')
    w(f'  hdiv({c})')
    w('')
    # the core over the destructured object
    Lc = f'MR.clist({c}, {SL}, 0n)'
    R = f'MD.rtree(depth, Nat.is_lt(0n, MD.dlen({Lc})), hl, {Lc}, 0n)'
    w('def lh_core(+hl: Nat, +ehl: {hl == 64n : Nat}, +t: F.array__Tree<U32>, +N: U32, +L: Nat, +depth: Nat,')
    w(f'    +eNN: {{U32.to_nat(N) == WS.e32({c}) : Nat}},')
    w(f'    +hvN: {{Nat.is_le({c}, L) == True{{}} : Bool}},')
    w('    +hmin: {Lim.minimal(L, depth) == True{} : Bool},')
    w('    +hdep: {Nat.is_lt(depth, 64n) == True{} : Bool})')
    w(f'    -> RR.roots(hview({W_}), {SCH}, [D.bytes(bdig(hl, {W_}, depth, 5n))]):')
    w('  %Equal.sym(F.array__Tree<U32>, F.array__freeze(U32, F.array__thaw(U32, t)), t, F.array__freeze_thaw(U32, t)) :')
    w(f'    RR.roots(S.Sequence{{WR.items({c}, F.array__slots(U32, _), 0n)}}, {SCH}, [D.bytes(O.mix_len(hl, MD.rtree(depth, Nat.is_lt(0n, O.chunks_of(N)), hl, MR.clist(O.chunks_of(N), F.array__slots(U32, _), 0n), 0n), U32.shrn(N, 5n)))])')
    w(f'  %Equal.sym(Nat, O.chunks_of(N), {c}, chq(N, eNN)) :')
    w(f'    RR.roots(S.Sequence{{WR.items({c}, {SL}, 0n)}}, {SCH}, [D.bytes(O.mix_len(hl, MD.rtree(depth, Nat.is_lt(0n, _), hl, MR.clist(_, {SL}, 0n), 0n), U32.shrn(N, 5n)))])')
    w(f'  %MR.clist_len({c}, {SL}, 0n) :')
    w(f'    RR.roots(S.Sequence{{WR.items({c}, {SL}, 0n)}}, {SCH}, [D.bytes(O.mix_len(hl, MD.rtree(depth, Nat.is_lt(0n, _), hl, {Lc}, 0n), U32.shrn(N, 5n)))])')
    hlen = f'UL.rw_le_l({c}, MD.dlen({Lc}), L, Equal.sym(Nat, MD.dlen({Lc}), {c}, MR.clist_len({c}, {SL}, 0n)), hvN)'
    w(f'  (MD.bytes_list({Lc}), (WR.items_roots({c}, {SL}, 0n), (D.bytes({R}),')
    w(f'    ((depth, (hmin, RS.at_depth_tree(L, depth, hl, {Lc}, hdep, {hlen}, ehl))),')
    w(f'     plen(hl, ehl, N, 5n, {R}, Codec.count(WR.items({c}, {SL}, 0n)), hcount({c}, {SL}, 0n))))))')
    w('')
    w('def lh_body(+hl: Nat, +ehl: {hl == 64n : Nat}, -o: O.Words, +L: Nat, +depth: Nat, +wf: LO.wfl(o),')
    w('    +eN: {U32.to_nat(WO.len(o)) == WS.e32(cnth(o)) : Nat},')
    w('    +hv: {Nat.is_le(cnth(o), L) == True{} : Bool},')
    w('    +hmin: {Lim.minimal(L, depth) == True{} : Bool},')
    w('    +hdep: {Nat.is_lt(depth, 64n) == True{} : Bool})')
    w(f'    -> RR.roots(hview(o), {SCH}, [D.bytes(bdig(hl, o, depth, 5n))]):')
    w('  match wf:')
    w('    case Inl{w}:')
    w('      (+t, w1) = w')
    w('      (+dw, w2) = w1')
    w('      (+N, w3) = w2')
    w('      (+eo, +w4) = w3')
    w(f'      %Equal.sym(O.Words, o, {W_}, eo) : RR.roots(hview(_), {SCH}, [D.bytes(bdig(hl, _, depth, 5n))])')
    w('      lh_core(hl, ehl, t, N, L, depth, eq_nh(o, t, N, eo, eN), lenh(o, t, N, L, eo, hv), hmin, hdep)')
    w('    case Inr{w}:')
    w('      (+t, w1) = w')
    w('      (+dw, w2) = w1')
    w('      (+N, w3) = w2')
    w('      (+q, w4) = w3')
    w('      (+r, w5) = w4')
    w('      (+eo, +w6) = w5')
    w(f'      %Equal.sym(O.Words, o, {W_}, eo) : RR.roots(hview(_), {SCH}, [D.bytes(bdig(hl, _, depth, 5n))])')
    w('      lh_core(hl, ehl, t, N, L, depth, eq_nh(o, t, N, eo, eN), lenh(o, t, N, L, eo, hv), hmin, hdep)')
    w('')
    w('# A list of Bytes32: its digest is a specification root of its elements.')
    w('def lh_rs(+hl: Nat, +ehl: {hl == 64n : Nat}, -h: B.Buf, -o: O.Words, +s: S.Schema, +depth: Nat, +dU: U32, +seg: U32,')
    w('    +rep: rep_lh(o, s),')
    w('    +ok: {ok_lh(s, depth) == True{} : Bool},')
    w('    +edu: {U32.to_nat(dU) == depth : Nat},')
    w('    +hdep: {Nat.is_lt(depth, 64n) == True{} : Bool})')
    w('    -> RR.roots(hview(o), s, [D.bytes(bdig(hl, o, depth, 5n))]):')
    w('  (+wf, +r1) = rep')
    w('  (+eN, +hv) = r1')
    for x in lets:
        w(x)
    w('  %Equal.sym(S.Schema, s, S.ListOf{SH.ListOf_element(s), SH.ListOf_limit(s)}, SH.ListOf_shape(s, c0)) :')
    w('    RR.roots(hview(o), _, [D.bytes(bdig(hl, o, depth, 5n))])')
    w('  %Equal.sym(S.Schema, SH.ListOf_element(s), S.ByteVector{SH.ByteVector_length(SH.ListOf_element(s))}, SH.ByteVector_shape(SH.ListOf_element(s), c1)) :')
    w('    RR.roots(hview(o), S.ListOf{_, SH.ListOf_limit(s)}, [D.bytes(bdig(hl, o, depth, 5n))])')
    w('  %Equal.sym(Nat, SH.ByteVector_length(SH.ListOf_element(s)), 32n, WS.nat_eq(SH.ByteVector_length(SH.ListOf_element(s)), 32n, c2)) :')
    w('    RR.roots(hview(o), S.ListOf{S.ByteVector{_}, SH.ListOf_limit(s)}, [D.bytes(bdig(hl, o, depth, 5n))])')
    w('  lh_body(hl, ehl, o, SH.ListOf_limit(s), depth, wf, eN, hv, c3, hdep)')
    w('')


def emit():
    out = [HEAD.rstrip('\n'), '']
    w = out.append
    PL.count_law('1', w)
    PL.count_law('2', w)
    count_items_h(w)
    len_lemmas(w)
    bytes32_kind(w)
    for K in ('1', '2'):
        basic_kind(K, w)
    return '\n'.join(out) + '\n'


def main():
    return light_pair(OUT, emit(), 'blist_laws', 'packed list laws are current', '--check' in sys.argv, LS)


if __name__ == '__main__':
    sys.exit(main())
