"""Generate the cached-root laws of every `_Cached` list whose elements are a
Data-kind name, from the checked BeaconState.validators instance.

The instance is proofs/obj/cloop.bend, cloop2.bend, cloop3.bend, cset.bend,
cmut.bend, capi.bend, cgrow.bend and chist.bend (list `l1099511627776_Validator`, element `Validator`, limit depth
40). The generated runtime code of every `_Cached` list is the same up to the
list's name, its element type and its limit depth (codegen/impl/typed_object_runtime.py), so
each other list's laws are the instance with those three substituted. They are
written into one file per list, proofs/obj/cached_<list>.bend, with the seven
parts' definitions side by side (their names do not collide). For the lists
whose uncached root law `rs_<list>` is in root_types.bend, the spec link is
written into proofs/obj/cspec_<list>.bend (template SPEC below): the cached
root's digest satisfies the independent relation RR.roots for the list's value,
and the same file (template PSEQ appended) proves that the list's public
producers (default, uncache, set, append) establish RT.rep_<list>, the root
law's hypothesis.

Elements that are Type-kind names (whose root law needs a representation
invariant per element: ProposerSlashing, AttesterSlashing, Attestation,
Deposit, bit lists) are not generated; `--status` lists them.

    python3 codegen/proofs/laws/cached_root_laws.py            # write the files
    python3 codegen/proofs/laws/cached_root_laws.py --check    # fail if a file is stale
    python3 codegen/proofs/laws/cached_root_laws.py --status
"""
import sys as _sys
import pathlib as _pathlib
_sys.path.insert(0, str(_pathlib.Path(__file__).resolve().parents[3]))  # the repository root: `codegen` is importable when this file runs as a script
import re
import sys
from codegen.impl import runtime_file_split as RR  # noqa: E402  the runtime split: the monoliths' text, the split files' imports

from codegen.core.repository_paths import OBJ  # noqa: E402
PARTS = ['cloop', 'cloop2', 'cloop3', 'cset', 'cmut', 'capi', 'cgrow', 'chist']
SELF = {'./cloop.bend', './cloop2.bend', './cloop3.bend', './cset.bend', './cmut.bend', './capi.bend', './cgrow.bend'}
T_LIST, T_ELEM, T_DEPTH = 'l1099511627776_Validator', 'Validator', 40


def cached_lists():
    types = RR.mono_text('fulu')
    out = []
    for m in re.finditer(r"def (l\d+)_(\w+?)_croot_pad\(.*?\n  .*?Nat\.sub\((\d+)n, d\)", types):
        out.append((f'{m.group(1)}_{m.group(2)}', m.group(2), int(m.group(3))))
    return out


def data_kind(elem):
    rn = (OBJ / 'root_names.bend').read_text()
    return f'def st_{elem}(' in rn and f'def d_{elem}(' in rn


def build(name, elem, depth):
    imports, bodies = [], []
    for part in PARTS:
        # the instance modules import the runtime split; the template works on T.<sym> (RR.unwire), and the
        # output's T import is rewired again (main)
        lines = RR.unwire((OBJ / f'{part}.bend').read_text()).split('\n')
        i = 0
        while i < len(lines) and lines[i].startswith('import'):
            if RR.SPLIT_IMP.match(lines[i]):
                lines[i] = 'import ../../types/fulu_obj.bend as T'
            if lines[i].split()[1] not in SELF and lines[i] not in imports:
                imports.append(lines[i])
            i += 1
        body = '\n'.join(lines[i:]).strip('\n')
        if part in ('cloop3', 'capi', 'cgrow', 'chist'):
            body = body.replace(f'{T_DEPTH}n', f'{depth}n').replace(f'depth {T_DEPTH}', f'depth {depth}')
        bodies.append(f'# ==== from the instance {part}.bend ' + '=' * 40 + '\n\n' + body)
    aliases = {}
    for line in imports:
        path, alias = line.split()[1], line.split()[-1]
        if aliases.setdefault(alias, path) != path:
            raise SystemExit(f'import alias {alias} names two modules')
    text = '\n\n'.join(bodies)
    for alias in ('CL2.', 'CL.', 'L2.', 'L3.', 'CS.', 'CM.', 'CA.', 'CG.'):
        text = re.sub(r'(?<![A-Za-z0-9_])' + re.escape(alias), '', text)
    guard = app_guard_cached(name)
    text = text.replace('def guard(+n: U32) -> Bool: True{}', f'def guard(+n: U32) -> Bool: U32.is_le((n + 1 : U32), {guard})')
    text = text.replace(T_LIST, name)
    text = text.replace(f'T.{T_ELEM}_default()', f'T.{elem}_default()').replace(f'T.{T_ELEM}_root(', f'T.{elem}_root(')
    text = text.replace(f'RN.d_{T_ELEM}(', f'RN.d_{elem}(').replace(f'RN.st_{T_ELEM}(', f'RN.st_{elem}(')
    text = re.sub(rf'\bT\.{T_ELEM}\b', f'T.{elem}', text)
    text = text.replace('BeaconState.validators', f'the list {name}').replace(f'd_{T_ELEM}', f'd_{elem}')
    if re.search(rf'\b{T_ELEM}\b|_{T_ELEM}\b', text):
        bad = sorted(set(l.strip()[:80] for l in text.split('\n') if re.search(rf'\b{T_ELEM}\b|_{T_ELEM}\b', l)))
        raise SystemExit(f'{name}: instance names left after substitution: {bad[:5]}')
    head = imports + ['', f'# GENERATED by cached_root_laws (codegen) from the checked {T_LIST} instance. Do not edit.',
                      f'# The cached root of {name} (element {elem}, limit depth {depth}): see cloop*.bend,',
                      '# cset.bend, cmut.bend, capi.bend, cgrow.bend and chist.bend for the statements and their reading.', '']
    return '\n'.join(head) + '\n' + text + '\n'


SPEC = """import Base
import ../compact/found.bend as F
import ../../src/buffer.bend as B
import ../../src/digest.bend as D
import ../../src/obj.bend as O
import ../../types/fulu_obj.bend as T
import ../../types/schema.bend as S
import ../../types/primitive.bend as P
import ../../spec/root_relation.bend as RR
import ./schema_shapes.bend as SH
import ./dk.bend as DK
import ./mtree_defs.bend as MD
import ./root_names.bend as RN
import ./cached_@L.bend as CA
import ./root_types.bend as RT

# GENERATED by cached_root_laws (codegen). Do not edit.
# The spec link of the cached root of @L (element @E, limit depth @Dn).
# cached_@L.bend proves the root the runtime returns is CA.dig(n, ta), the
# reference tree of the element roots CA.xl; root_types.bend proves the
# uncached root's digest RT.xd_@L satisfies the independent relation RR.roots
# (RT.rs_@L). The element-root lists of the two files are the same recursion
# (xl_same), so the cached root's digest satisfies RR.roots for the list's value.

law xat_same:
  for +W: List<&2, T.@E>
  for +i: Nat
  {CA.xat(W, i) == RT.xat_@L(W, i) : T.@E}
def xat_same(W, i):
  match W:
    case Nil{}: {==}
    case Con{+x, +t}:
      match i:
        case 0n: {==}
        case 1n+ +j: xat_same(t, j)

law xl_same:
  for +k: Nat
  for +W: List<&2, T.@E>
  for +i: Nat
  for +hl: Nat
  {CA.xl(k, W, i, hl) == RT.xl_@L(k, W, i, hl) : List<&2, D.Digest>}
def xl_same(k, W, i, hl):
  match k:
    case 0n: {==}
    case 1n+ +q:
      %Equal.sym(T.@E, CA.xat(W, i), RT.xat_@L(W, i), xat_same(W, i)) :
        {RN.d_@E(hl, _) <> CA.xl(q, W, 1n+i, hl) == RN.d_@E(hl, RT.xat_@L(W, i)) <> RT.xl_@L(q, W, 1n+i, hl) : List<&2, D.Digest>}
      %Equal.sym(List<&2, D.Digest>, CA.xl(q, W, 1n+i, hl), RT.xl_@L(q, W, 1n+i, hl), xl_same(q, W, 1n+i, hl)) :
        {RN.d_@E(hl, RT.xat_@L(W, i)) <> _ == RN.d_@E(hl, RT.xat_@L(W, i)) <> RT.xl_@L(q, W, 1n+i, hl) : List<&2, D.Digest>}
      {==}

def dig_spec(-h: B.Buf, +ta: F.array__Tree<T.@E>, +dw: Nat, +t: F.array__Tree<D.Digest>, +n: U32, +d: Nat, +lo: U32, +hi: U32, +s: S.Schema,
    +iv: CA.inv(ta, dw, t, n, d, lo, hi), +ok: {RT.ok_@L(s) == True{} : Bool}, +eq: @EQ,
    +hv: {Nat.is_le(U32.to_nat(n), SH.ListOf_limit(s)) == True{} : Bool})
    -> RR.roots(RT.xv_@L(T.@L_Seq{F.array__thaw(T.@E, ta), n}), s, [D.bytes(CA.dig(n, ta))]):
  (+hdw, w1) = iv
  (+pfa, w2) = w1
  (+hcap, w3) = w2
  (+hd, w4) = w3
  (+hdD, w5) = w4
  (+hnd, w6) = w5
  +hn = F.nat__le_trans(U32.to_nat(n), O.pow2n(d), F.spec_common__pow2(dw), hnd, hcap)
  +e1 = Equal.trans(List<&2, D.Digest>,
    RT.xl_@L(U32.to_nat(n), F.array__slots(T.@E, F.array__freeze(T.@E, F.array__thaw(T.@E, ta))), 0n, 64n),
    RT.xl_@L(U32.to_nat(n), F.array__slots(T.@E, ta), 0n, 64n),
    CA.xl(U32.to_nat(n), F.array__slots(T.@E, ta), 0n, 64n),
    Equal.cong(F.array__Tree<T.@E>, List<&2, D.Digest>, u => RT.xl_@L(U32.to_nat(n), F.array__slots(T.@E, u), 0n, 64n),
      F.array__freeze(T.@E, F.array__thaw(T.@E, ta)), ta, F.array__freeze_thaw(T.@E, ta)),
    Equal.sym(List<&2, D.Digest>, CA.xl(U32.to_nat(n), F.array__slots(T.@E, ta), 0n, 64n), RT.xl_@L(U32.to_nat(n), F.array__slots(T.@E, ta), 0n, 64n),
      xl_same(U32.to_nat(n), F.array__slots(T.@E, ta), 0n, 64n)))
  %e1 : RR.roots(RT.xv_@L(T.@L_Seq{F.array__thaw(T.@E, ta), n}), s, [D.bytes(O.mix_len(64n, MD.rtree(@Dn, Nat.is_lt(0n, U32.to_nat(n)), 64n, _, 0n), n))])
  RT.rs_@L(64n, {==}, h, T.@L_Seq{F.array__thaw(T.@E, ta), n}, s, ((ta, (dw, (n, ({==}, (pfa, (hdw, hn)))))), hv), ok, eq)

# For a valid cache of n elements (CA.inv) whose list value fits the schema s of
# @L: the runtime cached root returns CA.dig(n, ta), and that digest satisfies
# the independent root relation for the list's value.
law cached_spec:
  for -h: B.Buf
  for +ta: F.array__Tree<T.@E>
  for +dw: Nat
  for +t: F.array__Tree<D.Digest>
  for +n: U32
  for +d: Nat
  for +lo: U32
  for +hi: U32
  for +seg: U32
  for +s: S.Schema
  for +iv: CA.inv(ta, dw, t, n, d, lo, hi)
  for +ok: {RT.ok_@L(s) == True{} : Bool}
  for +eq: @EQ
  for +hv: {Nat.is_le(U32.to_nat(n), SH.ListOf_limit(s)) == True{} : Bool}
  {T.@L_cached_root(64n, h, CA.cached(ta, t, n, d, lo, hi), seg)
   == (h, (CA.cached(ta, CA.tafter(ta, t, n, d, lo, hi), n, d, n, 0), CA.dig(n, ta))) : B.Buf & (T.@L_Cached & D.Digest)}
  & RR.roots(RT.xv_@L(T.@L_Seq{F.array__thaw(T.@E, ta), n}), s, [D.bytes(CA.dig(n, ta))])
def cached_spec(h, ta, dw, t, n, d, lo, hi, seg, s, iv, ok, eq, hv):
  (CA.root_eq(h, ta, dw, t, n, d, lo, hi, seg, iv), dig_spec(h, ta, dw, t, n, d, lo, hi, s, iv, ok, eq, hv))
"""


PSEQ = """import Base
import ../compact/found.bend as F
import ../../src/digest.bend as D
import ../../src/obj.bend as O
import ../../types/fulu_obj.bend as T
import ../../types/schema.bend as S
import ./schema_shapes.bend as SH
import ./dk.bend as DK
import ./cidx.bend as CX
import ../../src/buffer.bend as B
import ./ctree.bend as CT
import ./wdstage.bend as WS2
import ./cached_@L.bend as CA
import ./root_types.bend as RT

# GENERATED by cached_root_laws (codegen). Do not edit.
# The public producers of @L values establish its representation invariant
# RT.rep_@L(o, s), the hypothesis of the root law RT.rs_@L: `default()`,
# `uncache(c)` of a valid cache (CA.inv), `set(o, i, v)` for i < n, and
# `append(o, v)` when the runtime accepts it (its guard n + 1 <= @G holds) and
# n < 2^k with k <= 30, and `read` (the list decoder) for a nonempty or empty
# field. Each mutation law also says the producer reports success.

def sq(pr: T.@L_Seq & Bool) -> T.@L_Seq:
  (o, +b) = pr
  o

def okb(pr: T.@L_Seq & Bool) -> Bool:
  (o, +b) = pr
  b

law default_rep:
  for +s: S.Schema
  RT.rep_@L(T.@L_default(), s)
def default_rep(s):
  %Equal.sym(Array<T.@E>, Array.new(T.@E, 0n, T.@E_default()), F.array__thaw(T.@E, F.array__trep(T.@E, 0n, T.@E_default())), F.array__new(T.@E, 0n, T.@E_default())) :
    RT.rep_@L(T.@L_Seq{_, 0}, s)
  ((F.array__trep(T.@E, 0n, T.@E_default()), (0n, (0, ({==}, (F.array__trep_perfect(T.@E, 0n, T.@E_default()), ({==}, {==})))))), F.nat__zero_le(SH.ListOf_limit(s)))

law uncache_rep:
  for +ta: F.array__Tree<T.@E>
  for +dw: Nat
  for +t: F.array__Tree<D.Digest>
  for +n: U32
  for +d: Nat
  for +lo: U32
  for +hi: U32
  for +s: S.Schema
  for +iv: CA.inv(ta, dw, t, n, d, lo, hi)
  for +hv: {Nat.is_le(U32.to_nat(n), SH.ListOf_limit(s)) == True{} : Bool}
  RT.rep_@L(T.@L_uncache(CA.cached(ta, t, n, d, lo, hi)), s)
def uncache_rep(ta, dw, t, n, d, lo, hi, s, iv, hv):
  (+hdw, w1) = iv
  (+pfa, w2) = w1
  (+hcap, w3) = w2
  (+hd, w4) = w3
  (+hdD, w5) = w4
  (+hnd, w6) = w5
  ((ta, (dw, (n, ({==}, (pfa, (hdw, F.nat__le_trans(U32.to_nat(n), O.pow2n(d), F.spec_common__pow2(dw), hnd, hcap))))))), hv)

# The length facts of o, moved to the length N of its representation.
def tr_lt(-o: T.@L_Seq, +t: F.array__Tree<T.@E>, +N: U32, +i: U32, +eo: {o == T.@L_Seq{F.array__thaw(T.@E, t), N} : T.@L_Seq},
    +h: {Nat.is_lt(U32.to_nat(i), U32.to_nat(RT.xlen_o_@L(o))) == True{} : Bool}) -> {Nat.is_lt(U32.to_nat(i), U32.to_nat(N)) == True{} : Bool}:
  %Equal.cong(T.@L_Seq, U32, RT.xlen_o_@L, o, T.@L_Seq{F.array__thaw(T.@E, t), N}, eo) : {Nat.is_lt(U32.to_nat(i), U32.to_nat(_)) == True{} : Bool}
  h

def tr_pw(-o: T.@L_Seq, +t: F.array__Tree<T.@E>, +N: U32, +P: Nat, +eo: {o == T.@L_Seq{F.array__thaw(T.@E, t), N} : T.@L_Seq},
    +h: {Nat.is_lt(U32.to_nat(RT.xlen_o_@L(o)), P) == True{} : Bool}) -> {Nat.is_lt(U32.to_nat(N), P) == True{} : Bool}:
  %Equal.cong(T.@L_Seq, U32, RT.xlen_o_@L, o, T.@L_Seq{F.array__thaw(T.@E, t), N}, eo) : {Nat.is_lt(U32.to_nat(_), P) == True{} : Bool}
  h

def tr_g(-o: T.@L_Seq, +t: F.array__Tree<T.@E>, +N: U32, +eo: {o == T.@L_Seq{F.array__thaw(T.@E, t), N} : T.@L_Seq},
    +h: {U32.is_le(U32.add(RT.xlen_o_@L(o), 1), @G) == True{} : Bool}) -> {U32.is_le(U32.add(N, 1), @G) == True{} : Bool}:
  %Equal.cong(T.@L_Seq, U32, RT.xlen_o_@L, o, T.@L_Seq{F.array__thaw(T.@E, t), N}, eo) : {U32.is_le(U32.add(_, 1), @G) == True{} : Bool}
  h

def tr_fit(-o: T.@L_Seq, +t: F.array__Tree<T.@E>, +N: U32, +P: Nat, +eo: {o == T.@L_Seq{F.array__thaw(T.@E, t), N} : T.@L_Seq},
    +h: {Nat.is_le(U32.to_nat(U32.add(RT.xlen_o_@L(o), 1)), P) == True{} : Bool}) -> {Nat.is_le(U32.to_nat(U32.add(N, 1)), P) == True{} : Bool}:
  %Equal.cong(T.@L_Seq, U32, RT.xlen_o_@L, o, T.@L_Seq{F.array__thaw(T.@E, t), N}, eo) : {Nat.is_le(U32.to_nat(U32.add(_, 1)), P) == True{} : Bool}
  h

# ---- set ----------------------------------------------------------------------------------

def set_eq(+t: F.array__Tree<T.@E>, +dw: Nat, +N: U32, +i: U32, +v: T.@E,
    +hdw: {Nat.is_lt(dw, 32n) == True{} : Bool},
    +pf: {F.array__perfect(T.@E, dw, t) == True{} : Bool},
    +hin: {Nat.is_lt(U32.to_nat(i), U32.to_nat(N)) == True{} : Bool},
    +hn: {Nat.is_le(U32.to_nat(N), F.spec_common__pow2(dw)) == True{} : Bool})
    -> {T.@L_set(T.@L_Seq{F.array__thaw(T.@E, t), N}, i, v) == (T.@L_Seq{F.array__thaw(T.@E, F.array__upd(T.@E, dw, t, U32.to_nat(i), v)), N}, True{}) : T.@L_Seq & Bool}:
  %Equal.sym(Bool, U32.is_lt(i, N), Nat.is_lt(U32.to_nat(i), U32.to_nat(N)), CX.lt_nat(i, N)) :
    {T.@L_put_in(_, F.array__thaw(T.@E, t), N, i, v) == (T.@L_Seq{F.array__thaw(T.@E, F.array__upd(T.@E, dw, t, U32.to_nat(i), v)), N}, True{}) : T.@L_Seq & Bool}
  %Equal.sym(Bool, Nat.is_lt(U32.to_nat(i), U32.to_nat(N)), True{}, hin) :
    {T.@L_put_in(_, F.array__thaw(T.@E, t), N, i, v) == (T.@L_Seq{F.array__thaw(T.@E, F.array__upd(T.@E, dw, t, U32.to_nat(i), v)), N}, True{}) : T.@L_Seq & Bool}
  %Equal.sym(Array<T.@E>, Array.set(T.@E, F.array__thaw(T.@E, t), i, v), F.array__thaw(T.@E, F.array__upd(T.@E, dw, t, U32.to_nat(i), v)),
      CA.set_items(t, dw, i, v, hdw, pf, F.nat__lt_le_trans(U32.to_nat(i), U32.to_nat(N), F.spec_common__pow2(dw), hin, hn))) :
    {(T.@L_Seq{_, N}, True{}) == (T.@L_Seq{F.array__thaw(T.@E, F.array__upd(T.@E, dw, t, U32.to_nat(i), v)), N}, True{}) : T.@L_Seq & Bool}
  {==}

law set_rep:
  for -o: T.@L_Seq
  for +s: S.Schema
  for +i: U32
  for +v: T.@E
  for +rep: RT.rep_@L(o, s)
  for +hin: {Nat.is_lt(U32.to_nat(i), U32.to_nat(RT.xlen_o_@L(o))) == True{} : Bool}
  DK.P2({okb(T.@L_set(o, i, v)) == True{} : Bool}, RT.rep_@L(sq(T.@L_set(o, i, v)), s))
def set_rep(o, s, i, v, rep, hin):
  (+wf, +hv) = rep
  (+t, w1) = wf
  (+dw, w2) = w1
  (+N, w3) = w2
  (+eo, w4) = w3
  (+pf, w5) = w4
  (+hdw, +hn) = w5
  +hin2 = tr_lt(o, t, N, i, eo, hin)
  +hv2 = RT.xhv_@L(o, t, N, SH.ListOf_limit(s), eo, hv)
  %Equal.sym(T.@L_Seq, o, T.@L_Seq{F.array__thaw(T.@E, t), N}, eo) :
    DK.P2({okb(T.@L_set(_, i, v)) == True{} : Bool}, RT.rep_@L(sq(T.@L_set(_, i, v)), s))
  %Equal.sym(T.@L_Seq & Bool, T.@L_set(T.@L_Seq{F.array__thaw(T.@E, t), N}, i, v), (T.@L_Seq{F.array__thaw(T.@E, F.array__upd(T.@E, dw, t, U32.to_nat(i), v)), N}, True{}),
      set_eq(t, dw, N, i, v, hdw, pf, hin2, hn)) :
    DK.P2({okb(_) == True{} : Bool}, RT.rep_@L(sq(_), s))
  ({==}, ((F.array__upd(T.@E, dw, t, U32.to_nat(i), v), (dw, (N, ({==}, (F.array__upd_perfect(T.@E, dw, t, U32.to_nat(i), v, pf), (hdw, hn)))))), hv2))

# ---- append -------------------------------------------------------------------------------

def n1_le(+N: U32, +P: Nat, +en1: {U32.to_nat((N + 1 : U32)) == 1n+U32.to_nat(N) : Nat},
    +h: {Nat.is_lt(U32.to_nat(N), P) == True{} : Bool}) -> {Nat.is_le(U32.to_nat((N + 1 : U32)), P) == True{} : Bool}:
  %Equal.sym(Nat, U32.to_nat((N + 1 : U32)), 1n+U32.to_nat(N), en1) : {Nat.is_le(_, P) == True{} : Bool}
  F.nat__lt_succ_le_succ(U32.to_nat(N), P, h)

def app_eq(+t: F.array__Tree<T.@E>, +dw: Nat, +N: U32, +v: T.@E, +k: Nat,
    +hk: {Nat.is_le(k, 30n) == True{} : Bool},
    +hdw: {Nat.is_lt(dw, 32n) == True{} : Bool},
    +pf: {F.array__perfect(T.@E, dw, t) == True{} : Bool},
    +hn: {Nat.is_le(U32.to_nat(N), F.spec_common__pow2(dw)) == True{} : Bool},
    +hlt: {Nat.is_lt(U32.to_nat(N), O.pow2n(k)) == True{} : Bool},
    +hg: {U32.is_le(U32.add(N, 1), @G) == True{} : Bool})
    -> {T.@L_append(T.@L_Seq{F.array__thaw(T.@E, t), N}, v) == (T.@L_Seq{F.array__thaw(T.@E, CA.gitems(dw, N, t, v)), (N + 1 : U32)}, True{}) : T.@L_Seq & Bool}:
  +c = CA.fits(dw, N)
  +D2 = CA.rdepth(c, dw, N)
  +R = CA.rtree(c, dw, N, t)
  +en1 = CA.n_next2(N, k, F.nat__le_lt_trans(k, 30n, 32n, hk, {==}), hlt)
  +hn1 = n1_le(N, O.pow2n(k), en1, hlt)
  +hr = CA.rt_room(c, dw, N, k, hk, hn1, en1, {==})
  +pr = CA.rt_perfect(c, dw, N, t, pf)
  %Equal.sym(Bool, U32.is_le(U32.add(N, 1), @G), True{}, hg) :
    {T.@L_app_in(_, F.array__thaw(T.@E, t), N, v) == (T.@L_Seq{F.array__thaw(T.@E, CA.gitems(dw, N, t, v)), (N + 1 : U32)}, True{}) : T.@L_Seq & Bool}
  %Equal.sym(Array<T.@E> & U32, Array.size(T.@E, F.array__thaw(T.@E, t)), (F.array__thaw(T.@E, t), F.u32__pow2u(dw)), F.array__size_thaw(T.@E, dw, t, pf)) :
    {(T.@L_Seq{Array.set(T.@E, T.@L_room_sized(N, _), N, v), (N + 1 : U32)}, True{}) == (T.@L_Seq{F.array__thaw(T.@E, CA.gitems(dw, N, t, v)), (N + 1 : U32)}, True{}) : T.@L_Seq & Bool}
  %Equal.sym(Bool, U32.is_lt(N, F.u32__pow2u(dw)), c, CA.size_cmp(dw, N, hdw)) :
    {(T.@L_Seq{Array.set(T.@E, T.@L_room_pick(_, F.array__thaw(T.@E, t), N), N, v), (N + 1 : U32)}, True{}) == (T.@L_Seq{F.array__thaw(T.@E, CA.gitems(dw, N, t, v)), (N + 1 : U32)}, True{}) : T.@L_Seq & Bool}
  %Equal.sym(Array<T.@E>, T.@L_room_pick(c, F.array__thaw(T.@E, t), N), F.array__thaw(T.@E, R), CA.room_pick_eq(c, dw, N, k, t, hdw, pf, hn, hk, hn1, en1, {==})) :
    {(T.@L_Seq{Array.set(T.@E, _, N, v), (N + 1 : U32)}, True{}) == (T.@L_Seq{F.array__thaw(T.@E, CA.gitems(dw, N, t, v)), (N + 1 : U32)}, True{}) : T.@L_Seq & Bool}
  %Equal.sym(Array<T.@E>, Array.set(T.@E, F.array__thaw(T.@E, R), N, v), F.array__thaw(T.@E, F.array__upd(T.@E, D2, R, U32.to_nat(N), v)),
      F.array__set(T.@E, D2, R, N, v, CA.xat(F.array__slots(T.@E, R), U32.to_nat(N)), CA.rt_depth(c, dw, N, k, hk, hn1, hdw), hr, CA.item_nth(R, D2, N, pr, hr), pr)) :
    {(T.@L_Seq{_, (N + 1 : U32)}, True{}) == (T.@L_Seq{F.array__thaw(T.@E, CA.gitems(dw, N, t, v)), (N + 1 : U32)}, True{}) : T.@L_Seq & Bool}
  {==}

law append_rep:
  for -o: T.@L_Seq
  for +s: S.Schema
  for +v: T.@E
  for +k: Nat
  for +hk: {Nat.is_le(k, 30n) == True{} : Bool}
  for +rep: RT.rep_@L(o, s)
  for +hlt: {Nat.is_lt(U32.to_nat(RT.xlen_o_@L(o)), O.pow2n(k)) == True{} : Bool}
  for +hg: {U32.is_le(U32.add(RT.xlen_o_@L(o), 1), @G) == True{} : Bool}
  for +hfit: {Nat.is_le(U32.to_nat(U32.add(RT.xlen_o_@L(o), 1)), SH.ListOf_limit(s)) == True{} : Bool}
  DK.P2({okb(T.@L_append(o, v)) == True{} : Bool}, RT.rep_@L(sq(T.@L_append(o, v)), s))
def append_rep(o, s, v, k, hk, rep, hlt, hg, hfit):
  (+wf, +hv) = rep
  (+t, w1) = wf
  (+dw, w2) = w1
  (+N, w3) = w2
  (+eo, w4) = w3
  (+pf, w5) = w4
  (+hdw, +hn) = w5
  +hlt2 = tr_pw(o, t, N, O.pow2n(k), eo, hlt)
  +hg2 = tr_g(o, t, N, eo, hg)
  +hfit2 = tr_fit(o, t, N, SH.ListOf_limit(s), eo, hfit)
  +en1 = CA.n_next2(N, k, F.nat__le_lt_trans(k, 30n, 32n, hk, {==}), hlt2)
  +hn1 = n1_le(N, O.pow2n(k), en1, hlt2)
  +c = CA.fits(dw, N)
  %Equal.sym(T.@L_Seq, o, T.@L_Seq{F.array__thaw(T.@E, t), N}, eo) :
    DK.P2({okb(T.@L_append(_, v)) == True{} : Bool}, RT.rep_@L(sq(T.@L_append(_, v)), s))
  %Equal.sym(T.@L_Seq & Bool, T.@L_append(T.@L_Seq{F.array__thaw(T.@E, t), N}, v), (T.@L_Seq{F.array__thaw(T.@E, CA.gitems(dw, N, t, v)), (N + 1 : U32)}, True{}),
      app_eq(t, dw, N, v, k, hk, hdw, pf, hn, hlt2, hg2)) :
    DK.P2({okb(_) == True{} : Bool}, RT.rep_@L(sq(_), s))
  ({==}, ((CA.gitems(dw, N, t, v), (CA.rdepth(c, dw, N), ((N + 1 : U32), ({==},
    (F.array__upd_perfect(T.@E, CA.rdepth(c, dw, N), CA.rtree(c, dw, N, t), U32.to_nat(N), v, CA.rt_perfect(c, dw, N, t, pf)),
    (CA.rt_depth(c, dw, N, k, hk, hn1, hdw), n1_le(N, F.spec_common__pow2(CA.rdepth(c, dw, N)), en1, CA.rt_room(c, dw, N, k, hk, hn1, en1, {==})))))))), hfit2))

# ---- read (the list decoder) --------------------------------------------------------------

def sqr(p: B.Buf & T.@L_Seq) -> T.@L_Seq:
  (b, o) = p
  o

# The buffer the element loop leaves (positions i .. i + k written).
def rbo(k: Nat, +i: U32, +off: U32, pr: B.Buf & T.@E) -> B.Buf:
  match k:
    case 0n:
      (b, +v) = pr
      b
    case 1n+q:
      (b, +v) = pr
      rbo(q, (i + 1 : U32), off, T.@E_read(b, (off + (i + 1 : U32) * @SZ : U32), @SZ))

# The element loop over a perfect tree of depth D returns (rbo, thaw u) for a
# perfect tree u (the tree is a witness, so the loop's input is used once).
def rd_eq(k: Nat, +i: U32, +off: U32, +D: Nat, +t: F.array__Tree<T.@E>, pr: B.Buf & T.@E,
    +hD: {Nat.is_lt(D, 32n) == True{} : Bool},
    +pf: {F.array__perfect(T.@E, D, t) == True{} : Bool},
    +hk: {Nat.is_le(Nat.add(U32.to_nat(i), 1n+k), F.spec_common__pow2(D)) == True{} : Bool})
    -> DK.Ex(F.array__Tree<T.@E>, u => DK.P2({T.@L_rd(k, i, off, F.array__thaw(T.@E, t), pr) == (rbo(k, i, off, pr), F.array__thaw(T.@E, u)) : B.Buf & Array<T.@E>},
                                             {F.array__perfect(T.@E, D, u) == True{} : Bool})):
  match k:
    case 0n:
      match pr:
        case (b, +v):
          +hi = CA.step_lt(U32.to_nat(i), 0n, F.spec_common__pow2(D), hk)
          (F.array__upd(T.@E, D, t, U32.to_nat(i), v),
           (Equal.cong(Array<T.@E>, B.Buf & Array<T.@E>, x => (b, x), Array.set(T.@E, F.array__thaw(T.@E, t), i, v), F.array__thaw(T.@E, F.array__upd(T.@E, D, t, U32.to_nat(i), v)),
              F.array__set(T.@E, D, t, i, v, CA.xat(F.array__slots(T.@E, t), U32.to_nat(i)), hD, hi, CA.item_nth(t, D, i, pf, hi), pf)),
            F.array__upd_perfect(T.@E, D, t, U32.to_nat(i), v, pf)))
    case 1n+ +q:
      match pr:
        case (b, +v):
          +hi = CA.step_lt(U32.to_nat(i), 1n+q, F.spec_common__pow2(D), hk)
          +ei = CA.i_next(i, 1n+q, D, hD, hk)
          %Equal.sym(Array<T.@E>, Array.set(T.@E, F.array__thaw(T.@E, t), i, v), F.array__thaw(T.@E, F.array__upd(T.@E, D, t, U32.to_nat(i), v)),
              F.array__set(T.@E, D, t, i, v, CA.xat(F.array__slots(T.@E, t), U32.to_nat(i)), hD, hi, CA.item_nth(t, D, i, pf, hi), pf)) :
            DK.Ex(F.array__Tree<T.@E>, u => DK.P2({T.@L_rd(q, (i + 1 : U32), off, _, T.@E_read(b, (off + (i + 1 : U32) * @SZ : U32), @SZ))
                   == (rbo(q, (i + 1 : U32), off, T.@E_read(b, (off + (i + 1 : U32) * @SZ : U32), @SZ)), F.array__thaw(T.@E, u)) : B.Buf & Array<T.@E>},
                  {F.array__perfect(T.@E, D, u) == True{} : Bool}))
          rd_eq(q, (i + 1 : U32), off, D, F.array__upd(T.@E, D, t, U32.to_nat(i), v), T.@E_read(b, (off + (i + 1 : U32) * @SZ : U32), @SZ), hD,
            F.array__upd_perfect(T.@E, D, t, U32.to_nat(i), v, pf), CA.bump(i, 1n+q, F.spec_common__pow2(D), ei, hk))

def cover(+n: U32, +k: Nat, +hk: {Nat.is_le(k, 30n) == True{} : Bool}, +hn: {Nat.is_le(U32.to_nat(n), O.pow2n(k)) == True{} : Bool})
    -> {Nat.is_le(U32.to_nat(n), F.spec_common__pow2(B.words_depth(n))) == True{} : Bool}:
  %Equal.sym(Nat, F.spec_common__pow2(B.words_depth(n)), O.pow2n(B.words_depth(n)), CT.pow2_eq(B.words_depth(n))) : {Nat.is_le(U32.to_nat(n), _) == True{} : Bool}
  WS2.wd_cover(n, k, F.nat__le_trans(k, 30n, 32n, hk, {==}), hn)

# Positions 0 .. n - 1 fit depth D, for 1 <= n <= 2^D.
def start_bound(+n: U32, +D: Nat, +h1: {Nat.is_le(1n, U32.to_nat(n)) == True{} : Bool},
    +hcov: {Nat.is_le(U32.to_nat(n), F.spec_common__pow2(D)) == True{} : Bool})
    -> {Nat.is_le(Nat.add(U32.to_nat(0), 1n+U32.to_nat((n - 1 : U32))), F.spec_common__pow2(D)) == True{} : Bool}:
  %Equal.sym(Nat, U32.to_nat(U32.sub(n, 1)), Nat.sub(U32.to_nat(n), U32.to_nat(1)), F.u32__sub_nat(n, 1, h1)) :
    {Nat.is_le(Nat.add(U32.to_nat(0), 1n+_), F.spec_common__pow2(D)) == True{} : Bool}
  %Equal.sym(Nat, Nat.add(1n, Nat.sub(U32.to_nat(n), 1n)), U32.to_nat(n), F.nat__sub_add(U32.to_nat(n), 1n, h1)) :
    {Nat.is_le(_, F.spec_common__pow2(D)) == True{} : Bool}
  hcov

def read_fin(+n: U32, +D: Nat, +s: S.Schema, -RD: B.Buf & Array<T.@E>, -B0: B.Buf,
    +ex: DK.Ex(F.array__Tree<T.@E>, u => DK.P2({RD == (B0, F.array__thaw(T.@E, u)) : B.Buf & Array<T.@E>}, {F.array__perfect(T.@E, D, u) == True{} : Bool})),
    +hD: {Nat.is_lt(D, 32n) == True{} : Bool},
    +hcov: {Nat.is_le(U32.to_nat(n), F.spec_common__pow2(D)) == True{} : Bool},
    +hlim: {Nat.is_le(U32.to_nat(n), SH.ListOf_limit(s)) == True{} : Bool})
    -> RT.rep_@L(sqr(T.@L_rd_fin(n, RD)), s):
  (+TT, w) = ex
  (+e, +pt) = w
  %Equal.sym(B.Buf & Array<T.@E>, RD, (B0, F.array__thaw(T.@E, TT)), e) : RT.rep_@L(sqr(T.@L_rd_fin(n, _)), s)
  ((TT, (D, (n, ({==}, (pt, (hD, hcov)))))), hlim)

# A nonempty list field of n = len / @SZ >= 1 elements, n <= 2^k (k <= 30) and
# n <= the schema limit: the decoder's value satisfies the representation invariant.
law read_rep:
  for buf: B.Buf
  for +off: U32
  for +len: U32
  for +s: S.Schema
  for +k: Nat
  for +hk: {Nat.is_le(k, 30n) == True{} : Bool}
  for +hne: {U32.is_eq(len, 0) == False{} : Bool}
  for +h1: {Nat.is_le(1n, U32.to_nat(U32.div(len, @SZ))) == True{} : Bool}
  for +hn: {Nat.is_le(U32.to_nat(U32.div(len, @SZ)), O.pow2n(k)) == True{} : Bool}
  for +hlim: {Nat.is_le(U32.to_nat(U32.div(len, @SZ)), SH.ListOf_limit(s)) == True{} : Bool}
  RT.rep_@L(sqr(T.@L_read(buf, off, len)), s)
def read_rep(buf, off, len, s, k, hk, hne, h1, hn, hlim):
  +n = U32.div(len, @SZ)
  +D = B.words_depth(n)
  +t0 = F.array__trep(T.@E, D, T.@E_default())
  +hD = F.nat__le_lt_trans(D, 30n, 32n, F.nat__le_trans(D, k, 30n, WS2.wd_min(n, k, hn), hk), {==})
  +hcov = cover(n, k, hk, hn)
  %Equal.sym(Bool, U32.is_eq(len, 0), False{}, hne) : RT.rep_@L(sqr(T.@L_rd_start(_, off, n, buf)), s)
  %Equal.sym(Array<T.@E>, Array.new(T.@E, D, T.@E_default()), F.array__thaw(T.@E, t0), F.array__new(T.@E, D, T.@E_default())) :
    RT.rep_@L(sqr(T.@L_rd_fin(n, T.@L_rd(U32.to_nat((n - 1 : U32)), 0, off, _, T.@E_read(buf, off, @SZ)))), s)
  read_fin(n, D, s,
    T.@L_rd(U32.to_nat((n - 1 : U32)), 0, off, F.array__thaw(T.@E, t0), T.@E_read(buf, off, @SZ)),
    rbo(U32.to_nat((n - 1 : U32)), 0, off, T.@E_read(buf, off, @SZ)),
    rd_eq(U32.to_nat((n - 1 : U32)), 0, off, D, t0, T.@E_read(buf, off, @SZ), hD, F.array__trep_perfect(T.@E, D, T.@E_default()), start_bound(n, D, h1, hcov)),
    hD, hcov, hlim)

# The empty list field (len = 0).
law read_empty_rep:
  for -buf: B.Buf
  for +off: U32
  for +len: U32
  for +s: S.Schema
  for +heq: {U32.is_eq(len, 0) == True{} : Bool}
  RT.rep_@L(sqr(T.@L_read(buf, off, len)), s)
def read_empty_rep(buf, off, len, s, heq):
  %Equal.sym(Bool, U32.is_eq(len, 0), True{}, heq) : RT.rep_@L(sqr(T.@L_rd_start(_, off, U32.div(len, @SZ), buf)), s)
  default_rep(s)
"""


def app_guard(name):
    types = RR.mono_text('fulu')
    m = re.search(rf'^def {name}_append\(.*\n.*\n.*_app_in\(U32\.is_le\(\(n \+ 1 : U32\), (\d+)\), arr, n, v\)', types, re.M)
    return m.group(1) if m else None


def elem_size(name, elem):
    types = RR.mono_text('fulu')
    m = re.search(rf'^def {name}_read\(.*U32\.div\(len, (\d+)\)', types, re.M)
    rd = re.search(rf'^def {name}_rd\((?:.*\n){{1,8}}?.*{elem}_read\(buf, \(off \+ \(i \+ 1 : U32\) \* (\d+) : U32\), (\d+)\)', types, re.M)
    if not m or not rd or not (m.group(1) == rd.group(1) == rd.group(2)):
        raise SystemExit(f'{name}: element read loop not in the expected form')
    return m.group(1)


def build_seq(name, elem, guard):
    return PSEQ.replace('@L', name).replace('@E', elem).replace('@G', guard).replace('@SZ', elem_size(name, elem))


def merge(a, b):
    """One file with a's and b's definitions (imports merged): the pair shares
    its expensive imports, so it is checked once."""
    la, lb = a.split('\n'), b.split('\n')
    ia = [l for l in la if l.startswith('import')]
    ib = [l for l in lb if l.startswith('import') and l not in ia]
    body_a = [l for l in la if not l.startswith('import')]
    body_b = [l for l in lb if not l.startswith('import') and not l.startswith('# GENERATED')]
    return '\n'.join(ia + ib + body_a + ['# ==== producers ' + '=' * 60] + body_b)


def spec_eq(name):
    rt = (OBJ / 'root_types.bend').read_text()
    m = re.search(rf'^def rs_{name}\(.*\+eq: (\{{SH\.ListOf_element\(s\) == .*? : S\.Schema\}})\)\s*$', rt, re.M)
    return m.group(1) if m else None


def build_spec(name, elem, depth, eq):
    return SPEC.replace('@EQ', eq).replace('@L', name).replace('@E', elem).replace('@D', str(depth))


def app_guard_cached(name):
    types = RR.mono_text('fulu')
    m = re.search(rf'^def {name}_capp\(.*\n.*\n.*_capp_in\(U32\.is_le\(\(n \+ 1 : U32\), (\d+)\), arr', types, re.M)
    if not m:
        raise SystemExit(f'{name}: capp guard not in the expected form')
    return m.group(1)


def targets():
    out, skipped = [], []
    for name, elem, depth in cached_lists():
        if name == T_LIST:
            continue
        (out if data_kind(elem) else skipped).append((name, elem, depth))
    return out, skipped


def main():
    out, skipped = targets()
    if '--status' in sys.argv:
        print(f'{T_LIST}: the checked instance')
        for name, elem, depth in out:
            link = 'with spec link' if spec_eq(name) else 'no uncached law to link'
            print(f'{name}: generated (element {elem}, depth {depth}; {link})')
        for name, elem, depth in skipped:
            print(f'{name}: not generated (element {elem} is a Type-kind name)')
        return 0
    stale = []
    for name, elem, depth in out:
        outs = [(OBJ / f'cached_{name}.bend', build(name, elem, depth))]
        eq = spec_eq(name)
        if eq:
            outs.append((OBJ / f'cspec_{name}.bend', build_spec(name, elem, depth, eq)))
            guard = app_guard(name)
            if guard is None:
                raise SystemExit(f'{name}: append guard not found')
            outs[-1] = (outs[-1][0], merge(outs[-1][1], build_seq(name, elem, guard)))
        outs = RR.rewire_out(outs)
        for path, text in outs:
            if '--check' in sys.argv:
                if not path.exists() or path.read_text() != text:
                    stale.append(str(path))
            else:
                if not path.exists() or path.read_text() != text:
                    path.write_text(text)
    if stale:
        print('stale: ' + ', '.join(stale))
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
