#!/usr/bin/env python3
"""ok_eval and decode_reject for the FIXED-SIZE names whose validator checks only the
length (T.<p>_ok_at is (buf, True{})): every Fulu name and generic form of that kind.

    python3 codegen/proofs/laws/length_only_reject_laws.py [--check]

For a name X of fixed size N whose decoder is X_built(size, T.<p>_ok(buf, 0, size)):
  <X>_ok_eval(buf, off, len)      : {T.<p>_ok(buf, off, len) == (buf, U32.is_eq(len, N))}
      the validator returns exactly the length check, for every buffer and offset;
  <X>_decode_reject(bs, hn)       : Decoding.outside_image(<schema of X>, bs)
      for every byte list bs whose length is not N (for names of SOLO bytes or more: not
      VRF.SZ(<schema>), the spec's fixed size of the schema, which is N) (the only buffers the decoder
      refuses): no spec value has bs as its encoding.
decode_reject goes through proofs/obj/vrejf.bend `lo`: the spec parts of any value at a
fixed-size schema are one fixed part of the schema's size (decode_shape.facts), so an
encoding has exactly N bytes. The names are read from the runtime (types/*_obj.bend: the
decoder's validator, its length, a trivial ok_at), not listed by hand.

Writes proofs/obj/vrejf.bend and proofs/obj/fixrej_{f,g}<k>.bend (Fulu / generic, in
chunks of CHUNK names).
"""
import sys as _sys
import pathlib as _pathlib
_sys.path.insert(0, str(_pathlib.Path(__file__).resolve().parents[3]))  # the repository root: `codegen` is importable when this file runs as a script
import re
import sys
from codegen.impl import runtime_file_split as RR  # noqa: E402  the runtime split: the monoliths' text, the split files' imports

from codegen.core.repository_paths import ROOT  # noqa: E402
from codegen.core.law_module_helpers import finish  # noqa: E402
CHUNK = 16
SOLO = 8192     # names this large get a module of their own
TRUE = 'True{} : Bool'

LIB = """import Base
import ../../types/schema.bend as S
import ../../spec/codec.bend as Codec
import ../../spec/schema.bend as SS
import ../../proofs/decode_facts.bend as DF
import ../compact/found.bend as FD

# GENERATED by length_only_reject_laws (codegen). Do not edit.
# An encoding at a fixed-size schema has the schema's size: a byte list of another length
# is no encoding (the per-name decode_reject laws of proofs/obj/fixrej_*.bend).

def lp(+w: Maybe<&2, Nat>, +N: Nat, +bs: +List<U32>, +ps: +List<S.Part>, hf: DF.single(w, ps),
    +hw: {w == Some{N} : Maybe<&2, Nat>}, +e: {Codec.bytes(Some{ps}) == Some{bs} : Maybe<&2, +List<U32>>},
    +hn: {Nat.is_eq(List.length(&2, U32, bs), N) == False{} : Bool}) -> Empty:
  match ps:
    case Nil{}: hf
    case Con{S.Fixed{+xs}, Nil{}}:
      +ex = FD.logic__some_inj(+List<U32>, xs, bs, e)
      +en = FD.logic__some_inj(Nat, N, List.length(&2, U32, xs), Equal.trans(Maybe<&2, Nat>, Some{N}, w, Some{List.length(&2, U32, xs)}, Equal.sym(Maybe<&2, Nat>, w, Some{N}, hw), hf))
      +ht = FD.logic__subst(+List<U32>, z => {Nat.is_eq(List.length(&2, U32, z), N) == True{} : Bool}, xs, bs, ex,
        FD.logic__subst(Nat, z => {Nat.is_eq(List.length(&2, U32, xs), z) == True{} : Bool}, List.length(&2, U32, xs), N, Equal.sym(Nat, N, List.length(&2, U32, xs), en), FD.nat__is_eq_refl(List.length(&2, U32, xs))))
      FD.logic__true_false(Equal.trans(Bool, True{}, Nat.is_eq(List.length(&2, U32, bs), N), False{}, Equal.sym(Bool, Nat.is_eq(List.length(&2, U32, bs), N), True{}, ht), hn))
    case Con{S.Variable{+xs}, Nil{}}: FD.logic__none_some(Nat, N, Equal.trans(Maybe<&2, Nat>, None{}, w, Some{N}, Equal.sym(Maybe<&2, Nat>, w, None{}, hf), hw))
    case Con{S.Fixed{+xs}, Con{+a, +b}}: hf
    case Con{S.Variable{+xs}, Con{+a, +b}}: hf

# The fixed size of a schema, as the spec computes it (0 for a variable-size one); the large
# names state their length condition with it, so no closed size is compared in unary.
def SZm(+m: Maybe<&2, Nat>) -> Nat:
  match m:
    case Some{n}: n
    case None{}: 0n
def SZ(+s: S.Schema) -> Nat: SZm(SS.fixed_size(s))
def SOMEm(+m: Maybe<&2, Nat>) -> Bool:
  match m:
    case Some{n}: True{}
    case None{}: False{}
# m is Some{SZm(m)} once it is known to be a Some: the width premise of lo for a schema whose size is
# only named (VRF.SZ), without comparing two evaluations of the size (a closed Nat, in unary).
def some_sz(+m: Maybe<&2, Nat>, +h: {SOMEm(m) == True{} : Bool}) -> {m == Some{SZm(m)} : Maybe<&2, Nat>}:
  match m:
    case Some{n}: {==}
    case None{}: Empty.absurd({None{} == Some{SZm(None{})} : Maybe<&2, Nat>}, FD.logic__false_true(h))
# The same at a schema, with the size named SZ(s) as the reject laws state it (for a symbolic s,
# SZ(s) and SZm(SS.fixed_size(s)) meet without evaluating either).
def some_szs(+s: S.Schema, +h: {SOMEm(SS.fixed_size(s)) == True{} : Bool}) -> {SS.fixed_size(s) == Some{SZ(s)} : Maybe<&2, Nat>}:
  some_sz(SS.fixed_size(s), h)
# m is Some{k} for a literal k, from evaluating SZIS (the checker's machine loops over the unary size
# without recursing), never by a conversion that would recurse once per unit of k (near the stack limit).
def SZIS(+m: Maybe<&2, Nat>, +k: Nat) -> Bool:
  match m:
    case Some{n}: Nat.is_eq(n, k)
    case None{}: False{}
def some_is(+m: Maybe<&2, Nat>, +k: Nat, +h: {SZIS(m, k) == True{} : Bool}) -> {m == Some{k} : Maybe<&2, Nat>}:
  match m:
    case Some{n}: Equal.cong(Nat, Maybe<&2, Nat>, z => Some{z}, n, k, FD.nat__eq_from_is_eq(n, k, h))
    case None{}: Empty.absurd({None{} == Some{k} : Maybe<&2, Nat>}, FD.logic__false_true(h))

# m: the spec parts of a value at a schema of width w = Some{N} (decode_shape.facts: one
# fixed part of w bytes); its bytes are bs, whose length is not N: impossible.
def lo(+w: Maybe<&2, Nat>, +N: Nat, +bs: +List<U32>, +m: Maybe<&2, +List<S.Part>>, hf: DF.single_result(w, m),
    +hw: {w == Some{N} : Maybe<&2, Nat>}, +e: {Codec.bytes(m) == Some{bs} : Maybe<&2, +List<U32>>},
    +hn: {Nat.is_eq(List.length(&2, U32, bs), N) == False{} : Bool}) -> Empty:
  match m:
    case None{}: FD.logic__none_some(+List<U32>, bs, e)
    case Some{+ps}: lp(w, N, bs, ps, hf, hw, e, hn)
"""


def runtime_fixed():
    """[(X, p, N)] for every name whose decoder's validator is a length check at a
    trivial ok_at."""
    out = {}
    for f, tag in (('fulu', 'f'), ('generic', 'g')):
        src = RR.mono_text(f)
        for m in re.finditer(r'^def (\w+)_decode_in\(buf: B\.Buf, \+size: U32\)[^\n]*\n  \w+\(size, (\w+)_ok\(buf, 0, size\)\)', src, re.M):
            X, P = m.group(1), m.group(2)
            ok = re.search(rf'^def {P}_ok\(buf: B\.Buf, \+off: U32, \+len: U32\) -> B\.Buf & Bool: {P}_ok_len\(U32\.is_eq\(len, (\d+)\), buf, off\)$', src, re.M)
            at = re.search(rf'^def {P}_ok_at\(buf: B\.Buf, \+off: U32\) -> B\.Buf & Bool: \(buf, True\{{\}}\)$', src, re.M)
            if ok and at:
                out[X] = (tag, P, int(ok.group(1)))
    return out


def names():
    from codegen.core import fulu_schema_loader as schema
    from codegen.core import generic_form_schemas as generic
    fulu = list(schema.load(ROOT / 'codegen/fulu.yaml'))
    gen = [n for n, t, e in generic.inventory_all() if e is None]
    rt = runtime_fixed()
    return [(X,) + rt[X] for X in fulu + gen if X in rt]


def chunk_text(tag, rows, solo=False):
    T = '../../types/fulu_obj.bend' if tag == 'f' else '../../types/generic_obj.bend'
    SCH = 'Spec' if tag == 'f' else 'GS'
    L = ['import Base', 'import ../../src/buffer.bend as B', f'import {T} as T', 'import ../../types/schema.bend as S',
         'import ../../spec/codec.bend as Codec', 'import ../../spec/decoding_relation.bend as Decoding',
         'import ../../spec/schema.bend as SS', 'import ../../proofs/decode_shape.bend as DS',
         'import ../../spec/fulu_schemas.bend as Spec' if tag == 'f' else 'import ./generic_specs.bend as GS',
         'import ./vrejf.bend as VRF', '',
         '# GENERATED by length_only_reject_laws (codegen). Do not edit.',
         '# Fixed-size names whose validator checks only the length: ok_eval and decode_reject', '# (see codegen/proofs/laws/length_only_reject_laws.py).', '']
    for X, _, P, N in rows:
        s = f'{SCH}.{X}()'
        NN = f'VRF.SZ({s})' if solo else f'{N}n'
        HW = f'VRF.some_szs({s}, {{==}})' if solo else (f'VRF.some_is(SS.fixed_size({s}), {N}n, {{==}})' if N >= 1024 else '{==}')
        L.append(f'''# ---- {X} ({N} bytes; validator T.{P}_ok) ----
def {X}_okb(buf: B.Buf, +off: U32, +b: Bool) -> {{T.{P}_ok_len(b, buf, off) == (buf, b) : B.Buf & Bool}}:
  match b:
    case True{{}}: {{==}}
    case False{{}}: {{==}}
def {X}_ok_eval(buf: B.Buf, +off: U32, +len: U32) -> {{T.{P}_ok(buf, off, len) == (buf, U32.is_eq(len, {N})) : B.Buf & Bool}}:
  {X}_okb(buf, off, U32.is_eq(len, {N}))
def {X}_rj(+bs: +List<U32>, +hn: {{Nat.is_eq(List.length(&2, U32, bs), {NN}) == False{{}} : Bool}}, +v: S.Value, e: Decoding.decodes({s}, bs, v)) -> Empty:
  VRF.lo(SS.fixed_size({s}), {NN}, bs, Codec.parts(v, {s}), DS.facts(v, {s}, {{==}}), {HW}, e, hn)
def {X}_decode_reject(+bs: +List<U32>, +hn: {{Nat.is_eq(List.length(&2, U32, bs), {NN}) == False{{}} : Bool}}) -> Decoding.outside_image({s}, bs):
  v => e => {X}_rj(bs, hn, v, e)
''')
    return '\n'.join(L) + '\n'


def outputs():
    rows = names()
    out = {ROOT / 'proofs/obj/vrejf.bend': LIB}
    for r in rows:
        if r[3] >= SOLO:
            out[ROOT / f'proofs/obj/fixrej_{r[0]}.bend'] = chunk_text(r[1], [r], solo=True)
    for tag in ('f', 'g'):
        rs = [r for r in rows if r[1] == tag and r[3] < SOLO]
        for k in range(0, len(rs), CHUNK):
            out[ROOT / f'proofs/obj/fixrej_{tag}{k // CHUNK}.bend'] = chunk_text(tag, rs[k:k + CHUNK])
    return out


def main():
    out = outputs()
    if finish(RR.rewire_out(out), ('fixrej_*.bend',), 'stale: ', 'fixed-size reject laws are current', '--check' in sys.argv):
        print(f'{len(out)} files')


if __name__ == '__main__':
    main()
