#!/usr/bin/env python3
"""e2e/e2e_dbs_BlobSidecar.bend: the premises of the composed decode;encode / decode;root theorems of FuluBlobSidecar, proved of the
decoder's object DB.OWd(15n, bs) (e2e/FuluBlobSidecar_e2e_dec_generated.bend):

    bs_rep(bs)   RT.rep_BlobSidecar(OWd(15n, bs), Spec.BlobSidecar())
    bs_hcb(bs)   E3.at_depth(RT.pj_BlobSidecar_1(OWd(15n, bs)), 16n)
    bs_hcp(bs)   E3.at_depth(RT.pj_BlobSidecar_5(OWd(15n, bs)), 8n)

The blob of the object is the canonical tree of its 2^15 words (AH.bq) beside a zero half: perfect by e2e_dec's bperf, its bytes counted by
e2e_wit like FuluBlob's (fixed_size_composed_theorems.build_tree). The header, the two commitments and the proof words are written out (their facts are
by computation); the object's own fields are the witnesses of the existential parts.

Usage: python3 codegen/proofs/decoded/blob_sidecar_decoded_premises.py [--check]"""
import sys as _sys
import pathlib as _pathlib
_sys.path.insert(0, str(_pathlib.Path(__file__).resolve().parents[3]))  # the repository root: `codegen` is importable when this file runs as a script
import re
import sys

from codegen.core.repository_paths import ROOT  # noqa: E402
from codegen.core.text_scanning_helpers import close_paren  # noqa: E402
E2E = ROOT / 'e2e'


def text():
    dec = (E2E / 'FuluBlobSidecar_e2e_dec_generated.bend').read_text()
    i = dec.index('def OWd(')
    owd = dec[i:dec.index('\n\n', i)]
    k = owd.index('AH.bq(')
    bq = owd[k:close_paren(owd, k + 5) + 1]
    m = re.match(r"AH\.bq\(15n, (AH\.tk\(AH\.dp\(FD\.array__slots\(U32, TGTd\(dd, bs\)\), 2n\), 32768n\)), (.*)\)$", bq, re.S)
    assert m, bq[:200]
    XS = m.group(1).replace('TGTd(dd, bs)', 'DB.TGTd(15n, bs)')
    Z = m.group(2).replace('dd', '15n')
    OB = 'DB.OWd(15n, bs)'
    SBS = 'Spec.BlobSidecar()'
    S1 = 'SH.Chain_head(SH.Chain_tail(SH.Container_fields(%s)))' % SBS
    S5 = 'SH.Chain_head(SH.Chain_tail(SH.Chain_tail(SH.Chain_tail(SH.Chain_tail(SH.Chain_tail(SH.Container_fields(%s)))))))' % SBS
    BLW = 'O.Words{ANode{FD.array__thaw(U32, AH.bq(15n, xs, T)), Array.new(U32, 15n, 0)}, 131072}'
    TT = 'FD.TNode{AH.bq(15n, xs, T), FD.array__trep(U32, 15n, 0)}'
    NW = 'FD.u32__pow2u(17n)'
    out = f'''import Base
import ../src/obj.bend as O
import ../types/schema.bend as S
import ../types/FuluBlobSidecar_def_generated.bend as FuluBlobSidecar_d
import ../types/FuluBytes48_def_generated.bend as FuluBytes48_d
import ../types/FuluSignedBeaconBlockHeader_def_generated.bend as FuluSignedBeaconBlockHeader_d
import ../spec/fulu_schemas.bend as Spec
import ../proofs/compact/found.bend as FD
import ../proofs/obj/arr_copy.bend as AC
import ../proofs/obj/arr_shift.bend as AH
import ../proofs/obj/repr.bend as R
import ../proofs/obj/schema_shapes.bend as SH
import ../proofs/obj/words_obj_light.bend as WO
import ../proofs/obj/pv_obj_light.bend as PV
import ../proofs/obj/root_types_light.bend as RT
import ./FuluBlobSidecar_e2e_dec_generated.bend as DB
import ./e2e_fixdw.bend as XW
import ./e2e_load.bend as L
import ./e2e_tree.bend as E3
import ./e2e_wit.bend as WT

# GENERATED by blob_sidecar_decoded_premises (codegen). Do not edit.
# FuluBlobSidecar: the premises of the composed theorems, proved of the decoder's object DB.OWd(15n, bs).

# ---- the blob: the canonical tree of its words beside a zero half (the tree argument of AH.bq is ignored) ----
def bl_oeq(+xs: List<&2, U32>, +T: FD.array__Tree<U32>) -> {{{BLW} == O.Words{{FD.array__thaw(U32, {TT}), {NW}}} : O.Words}}:
  %FD.array__new(U32, 15n, 0) : {{{BLW} == O.Words{{ANode{{FD.array__thaw(U32, AH.bq(15n, xs, T)), _}}, {NW}}} : O.Words}}
  {{==}}

def bl_pft(+xs: List<&2, U32>, +T: FD.array__Tree<U32>) -> {{FD.array__perfect(U32, 16n, {TT}) == True{{}} : Bool}}:
  %Equal.sym(FD.array__Tree<U32>, AH.bq(15n, xs, T), R.build(15n, xs), AH.bq_build(15n, xs, T)) : {{FD.array__perfect(U32, 16n, FD.TNode{{_, FD.array__trep(U32, 15n, 0)}}) == True{{}} : Bool}}
  %Equal.sym(Bool, FD.array__perfect(U32, 15n, R.build(15n, xs)), True{{}}, DB.bperf(15n, xs)) : {{Bool.and(_, FD.array__perfect(U32, 15n, FD.array__trep(U32, 15n, 0))) == True{{}} : Bool}}
  FD.array__trep_perfect(U32, 15n, 0)

def bl_rep(+xs: List<&2, U32>, +T: FD.array__Tree<U32>) -> WO.rep_bv({BLW}, {S1}):
  (({TT}, (16n, ({NW}, (WT.QP(12n), (32n, (bl_oeq(xs, T), (bl_pft(xs, T), ({{==}}, (WT.eN(12n, 17n, {{==}}, {NW}, FD.u32__pow2u_value(17n, {{==}})), ({{==}}, ({{==}}, (WT.eQ(12n, 16n, {{==}}), {{==}})))))))))))),
    FD.logic__subst(Nat, z => {{Nat.is_eq(U32.to_nat({NW}), z) == True{{}} : Bool}}, U32.to_nat({NW}), SH.ByteVector_length({S1}), XW.nk(17n, {{==}}, {NW}, {{==}}, SH.ByteVector_length({S1}), {{==}}), FD.nat__is_eq_refl(U32.to_nat({NW}))))

def bl_hc(+xs: List<&2, U32>, +T: FD.array__Tree<U32>) -> {{E3.at_depth({BLW}, 16n) == True{{}} : Bool}}:
  FD.logic__subst(O.Words, z => {{E3.at_depth(z, 16n) == True{{}} : Bool}}, O.Words{{FD.array__thaw(U32, {TT}), {NW}}}, {BLW}, Equal.sym(O.Words, {BLW}, O.Words{{FD.array__thaw(U32, {TT}), {NW}}}, bl_oeq(xs, T)),
    FD.logic__subst(FD.array__Tree<U32>, z => {{FD.array__perfect(U32, 16n, z) == True{{}} : Bool}}, {TT}, FD.array__freeze(U32, FD.array__thaw(U32, {TT})),
      Equal.sym(FD.array__Tree<U32>, FD.array__freeze(U32, FD.array__thaw(U32, {TT})), {TT}, FD.array__freeze_thaw(U32, {TT})), bl_pft(xs, T)))

# ---- the object's fields: the witnesses of the existential parts ----
def f0(o: FuluBlobSidecar_d.BlobSidecar) -> O.U64:
  match o:
    case FuluBlobSidecar_d.BlobSidecar{{+x0, x1, +x2, +x3, x4, x5}}: x0
def f2(o: FuluBlobSidecar_d.BlobSidecar) -> FuluBytes48_d.Bytes48:
  match o:
    case FuluBlobSidecar_d.BlobSidecar{{+x0, x1, +x2, +x3, x4, x5}}: x2
def f3(o: FuluBlobSidecar_d.BlobSidecar) -> FuluBytes48_d.Bytes48:
  match o:
    case FuluBlobSidecar_d.BlobSidecar{{+x0, x1, +x2, +x3, x4, x5}}: x3
def f4(o: FuluBlobSidecar_d.BlobSidecar) -> FuluSignedBeaconBlockHeader_d.SignedBeaconBlockHeader:
  match o:
    case FuluBlobSidecar_d.BlobSidecar{{+x0, x1, +x2, +x3, x4, x5}}:
      match x4:
        case O.BSome{{+v, nx}}: v
        case O.BNone{{}}: FuluSignedBeaconBlockHeader_d.SignedBeaconBlockHeader_default()
def tw5(o: FuluBlobSidecar_d.BlobSidecar) -> FD.array__Tree<U32>:
  match o:
    case FuluBlobSidecar_d.BlobSidecar{{+x0, x1, +x2, +x3, x4, x5}}:
      match x5:
        case O.Words{{ws, +n}}: FD.array__freeze(U32, ws)

# ---- the three premises ----
def bs_rep(+bs: +List<U32>) -> RT.rep_BlobSidecar({OB}, {SBS}):
  (f0({OB}), (f2({OB}), (f3({OB}), ({{==}},
    (bl_rep({XS}, {Z}),
      ((f4({OB}), {{==}}),
        ((tw5({OB}), (8n, (544, (16n, ({{==}}, ({{==}}, ({{==}}, ({{==}}, {{==}})))))))), {{==}})))))))

def bs_hcb(+bs: +List<U32>) -> {{E3.at_depth(RT.pj_BlobSidecar_1({OB}), 16n) == True{{}} : Bool}}:
  bl_hc({XS}, {Z})

def bs_hcp(+bs: +List<U32>) -> {{E3.at_depth(RT.pj_BlobSidecar_5({OB}), 8n) == True{{}} : Bool}}:
  {{==}}
'''
    return out


def main():
    p = E2E / 'e2e_dbs_BlobSidecar.bend'
    t = text()
    if '--check' in sys.argv:
        if not p.exists() or p.read_text() != t:
            print('stale: ' + p.name)
            sys.exit(1)
        print('blob_sidecar_decoded_premises: up to date')
        return
    if not p.exists() or p.read_text() != t:
        p.write_text(t)
    print('blob_sidecar_decoded_premises: 1 file')


if __name__ == '__main__':
    main()
