#!/usr/bin/env python3
"""Generates e2e/e2e_dbb.bend: facts about a decoded BeaconBlockBody (proofs/obj/var_winx_BeaconBlockBody.bend at word 0)
that its composed theorems need beside the per-field storage laws: each of its 9 variable windows [O_i, O_{i+1}) inside the
input (YL bounds), and the encode law's size premise RB.SZW (a witness n<j> per window, each the window's length, and the
total below 2^31). The equalities of the lists' encoded sizes with their windows' lengths are hypotheses of szw (the lists'
libraries; the payload's and the requests' sums).

Usage: python3 codegen/proofs/decoded/block_body_decoded_facts.py [--check]"""
import sys as _sys
import pathlib as _pathlib
_sys.path.insert(0, str(_pathlib.Path(__file__).resolve().parents[3]))  # the repository root: `codegen` is importable when this file runs as a script
import re
import sys

from codegen.core.repository_paths import ROOT  # noqa: E402
OUT = ROOT / 'e2e' / 'e2e_dbb.bend'
REC = ROOT / 'e2e' / 'e2e_rec_BeaconBlockBody.bend'

NW = 9
O = lambda i: f'W.O{i}(t, x)' if i < NW else 'n'
L = lambda i: f'W.LJ{i}(t, x)' if i < NW - 1 else f'W.LJ{NW - 1}(t, x, n)'
TN = lambda x: f'U32.to_nat({x})'
HS = '+hS: {U32.is_le(n, VB.NMAX()) == True{} : Bool}'
H31 = '+h31: {Nat.is_lt(U32.to_nat(n), VB.pw(31n)) == True{} : Bool}'
HC = '+hchk: {W.CHKw(t, x, off, n) == True{} : Bool}'
TP = '+t: FD.array__Tree<U32>, +x: Nat, +off: U32, +n: U32'
OBJ = 'W.OBJw(d, t, x, off, n)'
F0 = 'U32.to_nat(396)'
FIELD = [3, 4, 5, 6, 7, 9, 10, 11, 12]
IMP = ['PS3', 'AS4', 'AT5', 'DP6', 'VE7', 'RC9', 'BC10', 'WO', 'DQ0', 'DQ1', 'DQ2']


def szw_parts():
    s = REC.read_text()
    line = [l for l in s.split('\n') if l.startswith('def SZW(')][0]
    ps = re.findall(r'\{n(\d+) == (.+?) : Nat\}', line)
    assert [int(a) for a, _ in ps] == FIELD, ps
    imps = []
    for l in s.split('\n'):
        m = re.match(r'import (\S+) as (\w+)$', l)
        if m and m.group(2) in IMP:
            imps.append(l)
    return [e for _, e in ps], imps


def sub_o(e):
    return re.sub(r'(?<![\w.])o(?![\w{(])', OBJ, e)


def text():
    parts, imps = szw_parts()
    out = ['import Base', 'import ../src/obj.bend as O', 'import ../proofs/compact/found.bend as FD', 'import ../proofs/compact/arith.bend as A',
           'import ../proofs/nat_order.bend as Order', 'import ../proofs/obj/dk.bend as DK', 'import ../proofs/obj/vbuf.bend as VB', 'import ../proofs/obj/vcopy.bend as VC',
           'import ../proofs/obj/root_types_light.bend as RT', 'import ../proofs/obj/var_winx_BeaconBlockBody.bend as W',
           'import ./e2e_rec_BeaconBlockBody.bend as RB'] + imps
    t = '\n'.join(out) + '\n'
    t += '''
# GENERATED by block_body_decoded_facts (codegen). Do not edit.
# A decoded BeaconBlockBody: its 9 variable windows inside the input and the size premise RB.SZW (the fixed part and the
# windows add up to n < 2^31).

def u2n(+a: U32, +b: U32, +h: {U32.is_le(a, b) == True{} : Bool}) -> {Nat.is_le(U32.to_nat(a), U32.to_nat(b)) == True{} : Bool}:
  FD.logic__subst(Bool, z => {z == True{} : Bool}, U32.is_le(a, b), Nat.is_le(U32.to_nat(a), U32.to_nat(b)), VB.le_u32n(a, b), h)
'''
    for i in range(NW - 1):
        it = f'W.it{2 + i}(t, x, off, n, hchk)'
        a, b = f'U32.is_le({O(i)}, {O(i + 1)})', f'U32.is_le({O(i + 1)}, n)'
        t += (f'def ord{i}({TP}, {HC}) -> {{Nat.is_le({TN(O(i))}, {TN(O(i + 1))}) == True{{}} : Bool}}: u2n({O(i)}, {O(i + 1)}, FD.logic__and_left({a}, {b}, {it}))\n'
              f'def top{i}({TP}, {HC}) -> {{Nat.is_le({TN(O(i + 1))}, U32.to_nat(n)) == True{{}} : Bool}}: u2n({O(i + 1)}, n, FD.logic__and_right({a}, {b}, {it}))\n')
    for i in range(NW):
        ordi = f'ord{i}(t, x, off, n, hchk)' if i < NW - 1 else f'top{NW - 2}(t, x, off, n, hchk)'
        topi = f'top{i}(t, x, off, n, hchk)' if i < NW - 1 else 'FD.nat__le_refl(U32.to_nat(n))'
        t += (f'def lsum{i}({TP}, {HC}) -> {{Nat.add({TN(O(i))}, {TN(L(i))}) == {TN(O(i + 1))} : Nat}}:\n'
              f'  Equal.trans(Nat, Nat.add({TN(O(i))}, {TN(L(i))}), Nat.add({TN(O(i))}, Nat.sub({TN(O(i + 1))}, {TN(O(i))})), {TN(O(i + 1))},\n'
              f'    Equal.cong(Nat, Nat, z => Nat.add({TN(O(i))}, z), {TN(L(i))}, Nat.sub({TN(O(i + 1))}, {TN(O(i))}), FD.u32__sub_nat({O(i + 1)}, {O(i)}, {ordi})),\n'
              f'    FD.nat__sub_add({TN(O(i + 1))}, {TN(O(i))}, {ordi}))\n'
              f'def lwn{i}({TP}, {HC}) -> {{Nat.is_le({TN(L(i))}, U32.to_nat(n)) == True{{}} : Bool}}:\n'
              f'  FD.nat__le_trans({TN(L(i))}, {TN(O(i + 1))}, U32.to_nat(n), FD.logic__subst(Nat, z => {{Nat.is_le({TN(L(i))}, z) == True{{}} : Bool}}, Nat.add({TN(O(i))}, {TN(L(i))}), {TN(O(i + 1))}, lsum{i}(t, x, off, n, hchk), A.le_skip({TN(O(i))}, {TN(L(i))})), {topi})\n'
              f'def hy{i}({TP}, {HS}, {HC}) -> {{Nat.is_le(VC.YL({L(i)}), U32.to_nat(VB.UMAX())) == True{{}} : Bool}}:\n'
              f'  VC.hyW({TN(O(i))}, {L(i)}, FD.logic__subst(Nat, z => {{Nat.is_le(z, U32.to_nat(VB.NMAX())) == True{{}} : Bool}}, {TN(O(i + 1))}, Nat.add({TN(O(i))}, {TN(L(i))}), Equal.sym(Nat, Nat.add({TN(O(i))}, {TN(L(i))}), {TN(O(i + 1))}, lsum{i}(t, x, off, n, hchk)),\n'
              f'    FD.nat__le_trans({TN(O(i + 1))}, U32.to_nat(n), U32.to_nat(VB.NMAX()), {topi}, u2n(n, VB.NMAX(), hS))))\n')
    # the payload window (field 5) as an ExecutionPayload window of its own: its length below 2^31 and below NMAX (Nat and U32 forms)
    t += (f'\n# the nested payload window\'s length facts\n'
          f'def n2u(+a: U32, +b: U32, +h: {{Nat.is_le(U32.to_nat(a), U32.to_nat(b)) == True{{}} : Bool}}) -> {{U32.is_le(a, b) == True{{}} : Bool}}:\n'
          f'  FD.logic__subst(Bool, z => {{z == True{{}} : Bool}}, Nat.is_le(U32.to_nat(a), U32.to_nat(b)), U32.is_le(a, b), Equal.sym(Bool, U32.is_le(a, b), Nat.is_le(U32.to_nat(a), U32.to_nat(b)), VB.le_u32n(a, b)), h)\n'
          f'def pay_h31({TP}, {H31}, {HC}) -> {{Nat.is_lt({TN(L(5))}, VB.pw(31n)) == True{{}} : Bool}}:\n'
          f'  FD.nat__le_lt_trans({TN(L(5))}, U32.to_nat(n), VB.pw(31n), lwn5(t, x, off, n, hchk), h31)\n'
          f'def pay_hSN({TP}, {HS}, {HC}) -> {{Nat.is_le({TN(L(5))}, U32.to_nat(VB.NMAX())) == True{{}} : Bool}}:\n'
          f'  FD.nat__le_trans({TN(L(5))}, U32.to_nat(n), U32.to_nat(VB.NMAX()), lwn5(t, x, off, n, hchk), u2n(n, VB.NMAX(), hS))\n'
          f'def pay_hS({TP}, {HS}, {HC}) -> {{U32.is_le({L(5)}, VB.NMAX()) == True{{}} : Bool}}:\n'
          f'  n2u({L(5)}, VB.NMAX(), pay_hSN(t, x, off, n, hS, hchk))\n')
    # the size: 396 + L_0 + ... + L_8 = n, then SZW
    lens = [TN(L(i)) for i in range(NW)]
    lines = []
    e0 = f'Equal.cong(U32, Nat, z => U32.to_nat(z), {O(0)}, 396, FD.u32alg__eq_of({O(0)}, 396, W.it1(t, x, off, n, hchk)))'
    sz = lambda args, first: _sz(args, first)
    lines.append(f'  %{e0} : {{{sz(lens, "_")} == U32.to_nat(n) : Nat}}')
    acc = TN(O(0))
    for k in range(NW):
        inner = f'Nat.add({acc}, {lens[k]})'
        lines.append(f'  %Equal.sym(Nat, {inner}, {TN(O(k + 1))}, lsum{k}(t, x, off, n, hchk)) : {{{sz(lens[k + 1:], "_")} == U32.to_nat(n) : Nat}}')
        acc = TN(O(k + 1))
    lines.append('  {==}')
    t += (f'\n# the fixed part and the windows add up to n\n'
          f'def tot({TP}, {HC}) -> {{{sz(lens, F0)} == U32.to_nat(n) : Nat}}:\n' + '\n'.join(lines) + '\n')
    # SZW: the witnesses are the windows' lengths; the equalities are hypotheses
    FLIP = (3, 4, 5, 6, 9, 12)   # the lists' libraries state {sum == length}; the byte-list windows' {length == sum}
    eqs = [(f'+e{FIELD[i]}: {{{sub_o(parts[i])} == {lens[i]} : Nat}}' if FIELD[i] in FLIP else f'+e{FIELD[i]}: {{{lens[i]} == {sub_o(parts[i])} : Nat}}') for i in range(NW)]
    SZ = sz([f'U32.to_nat({L(i)})' for i in range(NW)], F0)
    tup = ''
    comps = [L(i) for i in range(NW)]
    comps = [lens[i] for i in range(NW)] + [(f'Equal.sym(Nat, {sub_o(parts[i])}, {lens[i]}, e{FIELD[i]})' if FIELD[i] in FLIP else f'e{FIELD[i]}') for i in range(NW)]
    bound = (f'FD.logic__subst(Nat, z => {{Nat.is_lt(z, VB.pw(31n)) == True{{}} : Bool}}, U32.to_nat(n), {SZ}, Equal.sym(Nat, {SZ}, U32.to_nat(n), tot(t, x, off, n, hchk)), h31)')
    r = bound
    for c in reversed(comps):
        r = f'({c}, {r})'
    t += (f'\n# the encode law\'s size premise\n'
          f'def szw(+d: Nat, {TP}, {", ".join(eqs)}, {H31}, {HC}) -> RB.SZW({OBJ}):\n  {r}\n')
    return t


def _sz(args, first):
    s = first
    for a in args:
        s = f'Nat.add({s}, {a})'
    return s


def main():
    t = text()
    if '--check' in sys.argv:
        if not OUT.exists() or OUT.read_text() != t:
            print('stale: e2e/e2e_dbb.bend')
            sys.exit(1)
        print('block_body_decoded_facts: up to date')
        return
    OUT.write_text(t)
    print('block_body_decoded_facts: wrote e2e/e2e_dbb.bend')


if __name__ == '__main__':
    main()
