#!/usr/bin/env python3
"""Decoded byte storage (for the composed theorems of variable-size names): e2e/e2e_dz.bend.

The words a decoder copies into an object (VB.mone over a zero tree, then VY.MK masking the last
word) are zero past the copied bytes: the zero tail wf1 / sdk1 ask of byte storage
(WS.bdrop(r, WS.cb(slots, q)) == zero_bytes(32 - r) for a length 32 q + r). The lemma zb<r>
turns word and byte facts into that tail, one per r = 1..31 (32 needs none).

    python3 codegen/proofs/decoded/decoded_byte_storage_facts.py            # write
    python3 codegen/proofs/decoded/decoded_byte_storage_facts.py --check    # nonzero exit if stale
"""
import sys as _sys
import pathlib as _pathlib
_sys.path.insert(0, str(_pathlib.Path(__file__).resolve().parents[3]))  # the repository root: `codegen` is importable when this file runs as a script
import sys

from codegen.core.repository_paths import ROOT  # noqa: E402
OUT = ROOT / 'e2e/e2e_dz.bend'

IMPORTS = """import Base
import ../src/obj.bend as O
import ../spec/primitives.bend as SP
import ../proofs/compact/found.bend as FD
import ../proofs/obj/vbuf.bend as VB
import ../proofs/obj/vbytes.bend as VY
import ../proofs/obj/vcopy.bend as VC
import ../proofs/obj/words_spec.bend as WS
import ../proofs/obj/mtree_run.bend as MR
import ../proofs/obj/vdepth.bend as VD
import ../proofs/compact/arith.bend as A
import ../proofs/nat_order.bend as Order
import ./e2e_tz.bend as TZ
import ./e2e_blist.bend as BL
import ../proofs/obj/vlist.bend as VLS
import ../proofs/obj/vua_copy.bend as UC
import ../proofs/obj/vua.bend as UAx
import ../proofs/obj/vua_ct.bend as UCT
import ../proofs/obj/vbrt.bend as VR
import ../proofs/compact/reads.bend as RD
"""

BASE = "\n# GENERATED by decoded_byte_storage_facts (codegen). Do not edit.\n# Decoded byte storage: the words a decoder copies (VB.mone over a zero tree, VY.MK masking the last word)\n# are zero past the copied bytes.\n\n# ---- a word ANDed with a mask whose high bits are clear has those bits clear ----\ndef band_false(+x: Bool) -> {Bool.and(x, False{}) == False{} : Bool}:\n  match x:\n    case False{}: {==}\n    case True{}: {==}\n\nlaw wand_zero:\n  for +n: Nat\n  for +a: Word(n)\n  {Word.and(n, a, Word.zero(n)) == Word.zero(n) : Word(n)}\ndef wand_zero(n, a):\n  match n a:\n    case 0n WNil{}: {==}\n    case 1n+ +p WCon{+x, +s}:\n      %Equal.sym(Bool, Bool.and(x, False{}), False{}, band_false(x)) : {WCon{_, Word.and(p, s, Word.zero(p))} == WCon{False{}, Word.zero(p)} : Word(1n+p)}\n      %Equal.sym(Word(p), Word.and(p, s, Word.zero(p)), Word.zero(p), wand_zero(p, s)) : {WCon{False{}, _} == WCon{False{}, Word.zero(p)} : Word(1n+p)}\n      {==}\n\ndef and_zero(+y: U32) -> {U32.and(y, 0) == 0 : U32}:\n  match y:\n    case U32{+w}:\n      %Equal.sym(Word(32n), Word.and(32n, w, Word.zero(32n)), Word.zero(32n), wand_zero(32n, w)) : {U32{_} == 0 : U32}\n      {==}\n\n# (x & M) >> k is zero when M >> k is\ndef shz(+x: U32, +M: U32, +k: Nat, +h: {U32.shrn(M, k) == 0 : U32}) -> {U32.shrn(U32.and(x, M), k) == 0 : U32}:\n  %Equal.sym(U32, U32.shrn(U32.and(x, M), k), U32.and(U32.shrn(x, k), U32.shrn(M, k)), VY.shrn_and(k, x, M)) : {_ == 0 : U32}\n  %Equal.sym(U32, U32.shrn(M, k), 0, h) : {U32.and(U32.shrn(x, k), _) == 0 : U32}\n  and_zero(U32.shrn(x, k))\n\n# ---- the copied tree past its copies ----\nlaw lm_out:\n  for +n: Nat\n  for +i: Nat\n  for +j: Nat\n  for +L: List<&2, U32>\n  for +SL: List<&2, U32>\n  for +x: Nat\n  for +hx: {Nat.is_le(Nat.add(n, j), x) == True{} : Bool}\n  {FD.flat__nthc(VB.lm(n, i, j, L, SL), x) == FD.flat__nthc(L, x) : U32}\ndef lm_out(n, i, j, L, SL, x, hx):\n  match n:\n    case 0n: {==}\n    case 1n+ +p:\n      +h1 = FD.logic__subst(Nat, z => {Nat.is_le(z, x) == True{} : Bool}, 1n+Nat.add(p, j), Nat.add(p, 1n+j), Equal.sym(Nat, Nat.add(p, 1n+j), 1n+Nat.add(p, j), FD.nat__add_succ(p, j)), hx)\n      +hjx = FD.nat__lt_le_trans(j, 1n+j, x, FD.nat__lt_succ(j), FD.nat__le_trans(1n+j, Nat.add(p, 1n+j), x, FD.logic__subst(Nat, z => {Nat.is_le(1n+j, z) == True{} : Bool}, Nat.add(1n+j, p), Nat.add(p, 1n+j), FD.nat__add_comm(1n+j, p), FD.nat__le_add_right(1n+j, p)), h1))\n      Equal.trans(U32, FD.flat__nthc(VB.lm(p, 1n+i, 1n+j, FD.spec_common__update(U32, L, j, FD.flat__nthc(SL, i)), SL), x),\n        FD.flat__nthc(FD.spec_common__update(U32, L, j, FD.flat__nthc(SL, i)), x), FD.flat__nthc(L, x),\n        lm_out(p, 1n+i, 1n+j, FD.spec_common__update(U32, L, j, FD.flat__nthc(SL, i)), SL, x, h1),\n        FD.flat__nthc_other(L, j, x, FD.flat__nthc(SL, i), FD.nat__is_eq_lt(j, x, hjx)))\n\n# a word the copy did not write is the zero tree's\ndef mone_out(+n: Nat, +i: Nat, +dd: Nat, +S: FD.array__Tree<U32>, +x: Nat, +hn: {Nat.is_le(n, VB.pw(dd)) == True{} : Bool}, +hx: {Nat.is_le(n, x) == True{} : Bool})\n    -> {VB.slot(VB.mone(n, i, 0n, dd, VC.ZT(dd), S), x) == 0 : U32}:\n  %Equal.sym(List<&2, U32>, FD.array__slots(U32, VB.mone(n, i, 0n, dd, VC.ZT(dd), S)), VB.lm(n, i, 0n, FD.array__slots(U32, VC.ZT(dd)), FD.array__slots(U32, S)),\n      VB.slots_mone(n, i, 0n, dd, VC.ZT(dd), S, FD.array__trep_perfect(U32, dd, 0), FD.logic__subst(Nat, z => {Nat.is_le(z, VB.pw(dd)) == True{} : Bool}, n, Nat.add(n, 0n), Equal.sym(Nat, Nat.add(n, 0n), n, FD.nat__add_zero(n)), hn))) :\n    {FD.flat__nthc(_, x) == 0 : U32}\n  %Equal.sym(U32, FD.flat__nthc(VB.lm(n, i, 0n, FD.array__slots(U32, VC.ZT(dd)), FD.array__slots(U32, S)), x), FD.flat__nthc(FD.array__slots(U32, VC.ZT(dd)), x),\n      lm_out(n, i, 0n, FD.array__slots(U32, VC.ZT(dd)), FD.array__slots(U32, S), x, FD.logic__subst(Nat, z => {Nat.is_le(z, x) == True{} : Bool}, n, Nat.add(n, 0n), Equal.sym(Nat, Nat.add(n, 0n), n, FD.nat__add_zero(n)), hx))) :\n    {_ == 0 : U32}\n  %Equal.sym(List<&2, U32>, FD.array__slots(U32, VC.ZT(dd)), FD.spec_common__replicate(U32, FD.spec_common__pow2(dd), 0), FD.array__trep_slots(U32, dd, 0)) : {FD.flat__nthc(_, x) == 0 : U32}\n  FD.flat__nthc_rep(FD.spec_common__pow2(dd), x)\n"

BASE2 = "\n# ---- the masked tree (VY.MK) ----\ndef mko_go(+b: Bool, +L: U32, +dz: Nat, +M: FD.array__Tree<U32>, +x: Nat, +eb: {U32.is_eq(VY.RM(L), 0) == b : Bool},\n    +pf: {FD.array__perfect(U32, dz, M) == True{} : Bool}, +hk: {Nat.is_lt(VY.KW(L), VB.pw(dz)) == True{} : Bool},\n    +ne: {Nat.is_eq(VY.KW(L), x) == False{} : Bool}) -> {VB.slot(VY.mk(b, L, dz, M), x) == VB.slot(M, x) : U32}:\n  match b:\n    case True{}: {==}\n    case False{}:\n      %Equal.sym(List<&2, U32>, FD.array__slots(U32, FD.array__upd(U32, dz, M, VY.KW(L), O.keep(VY.RM(L), VB.slot(M, VY.KW(L))))),\n          FD.spec_common__update(U32, FD.array__slots(U32, M), VY.KW(L), O.keep(VY.RM(L), VB.slot(M, VY.KW(L)))),\n          FD.array__upd_slots(U32, dz, M, VY.KW(L), O.keep(VY.RM(L), VB.slot(M, VY.KW(L))), hk, pf)) :\n        {FD.flat__nthc(_, x) == VB.slot(M, x) : U32}\n      FD.flat__nthc_other(FD.array__slots(U32, M), VY.KW(L), x, O.keep(VY.RM(L), VB.slot(M, VY.KW(L))), ne)\n\n# a word of the masked tree other than the masked one is the tree's\ndef mk_out(+L: U32, +dz: Nat, +M: FD.array__Tree<U32>, +x: Nat, +pf: {FD.array__perfect(U32, dz, M) == True{} : Bool},\n    +hk: {Nat.is_lt(VY.KW(L), VB.pw(dz)) == True{} : Bool}, +ne: {Nat.is_eq(VY.KW(L), x) == False{} : Bool})\n    -> {VB.slot(VY.MK(L, dz, M), x) == VB.slot(M, x) : U32}:\n  mko_go(U32.is_eq(VY.RM(L), 0), L, dz, M, x, {==}, pf, hk, ne)\n\n# the masked word: its first RM(L) bytes kept\ndef mk_at(+L: U32, +dz: Nat, +M: FD.array__Tree<U32>, +pf: {FD.array__perfect(U32, dz, M) == True{} : Bool},\n    +hk: {Nat.is_lt(VY.KW(L), VB.pw(dz)) == True{} : Bool}, +hb: {U32.is_eq(VY.RM(L), 0) == False{} : Bool})\n    -> {VB.slot(VY.MK(L, dz, M), VY.KW(L)) == O.keep(VY.RM(L), VB.slot(M, VY.KW(L))) : U32}:\n  %Equal.sym(Bool, U32.is_eq(VY.RM(L), 0), False{}, hb) : {VB.slot(VY.mk(_, L, dz, M), VY.KW(L)) == O.keep(VY.RM(L), VB.slot(M, VY.KW(L))) : U32}\n  %Equal.sym(List<&2, U32>, FD.array__slots(U32, FD.array__upd(U32, dz, M, VY.KW(L), O.keep(VY.RM(L), VB.slot(M, VY.KW(L))))),\n      FD.spec_common__update(U32, FD.array__slots(U32, M), VY.KW(L), O.keep(VY.RM(L), VB.slot(M, VY.KW(L)))),\n      FD.array__upd_slots(U32, dz, M, VY.KW(L), O.keep(VY.RM(L), VB.slot(M, VY.KW(L))), hk, pf)) :\n    {FD.flat__nthc(_, VY.KW(L)) == O.keep(VY.RM(L), VB.slot(M, VY.KW(L))) : U32}\n  FD.flat__nthc_same(FD.array__slots(U32, M), VY.KW(L), O.keep(VY.RM(L), VB.slot(M, VY.KW(L))),\n    FD.logic__subst(Nat, z => {Nat.is_lt(VY.KW(L), z) == True{} : Bool}, FD.spec_common__pow2(dz), FD.spec_common__length(U32, FD.array__slots(U32, M)),\n      Equal.sym(Nat, FD.spec_common__length(U32, FD.array__slots(U32, M)), FD.spec_common__pow2(dz), FD.array__slots_length(U32, dz, M, pf)), hk))\n\n# a length of whole words: the mask keeps the tree\ndef mk_id(+L: U32, +dz: Nat, +M: FD.array__Tree<U32>, +h: {U32.is_eq(VY.RM(L), 0) == True{} : Bool}) -> {VY.MK(L, dz, M) == M : FD.array__Tree<U32>}:\n  %Equal.sym(Bool, U32.is_eq(VY.RM(L), 0), True{}, h) : {VY.mk(_, L, dz, M) == M : FD.array__Tree<U32>}\n  {==}\n\n# the bytes a mask of k bytes clears\ndef kb1_1(+w: U32) -> {U32.and(U32.shrn(U32.and(w, 255), 8n), 255) == 0 : U32}:\n  %Equal.sym(U32, U32.shrn(U32.and(w, 255), 8n), 0, shz(w, 255, 8n, {==})) : {U32.and(_, 255) == 0 : U32}\n  {==}\ndef kb1_2(+w: U32) -> {U32.and(U32.shrn(U32.and(w, 255), 16n), 255) == 0 : U32}:\n  %Equal.sym(U32, U32.shrn(U32.and(w, 255), 16n), 0, shz(w, 255, 16n, {==})) : {U32.and(_, 255) == 0 : U32}\n  {==}\ndef kb1_3(+w: U32) -> {U32.shrn(U32.and(w, 255), 24n) == 0 : U32}: shz(w, 255, 24n, {==})\ndef kb2_2(+w: U32) -> {U32.and(U32.shrn(U32.and(w, 65535), 16n), 255) == 0 : U32}:\n  %Equal.sym(U32, U32.shrn(U32.and(w, 65535), 16n), 0, shz(w, 65535, 16n, {==})) : {U32.and(_, 255) == 0 : U32}\n  {==}\ndef kb2_3(+w: U32) -> {U32.shrn(U32.and(w, 65535), 24n) == 0 : U32}: shz(w, 65535, 24n, {==})\ndef kb3_3(+w: U32) -> {U32.shrn(U32.and(w, 16777215), 24n) == 0 : U32}: shz(w, 16777215, 24n, {==})\n"

BASE3 = r"""
# the shifted copy (UC.smone) past its copies
law slm_out:
  for +s: Nat
  for +n: Nat
  for +i: Nat
  for +j: Nat
  for +L: List<&2, U32>
  for +ds: Nat
  for +S: FD.array__Tree<U32>
  for +x: Nat
  for +hx: {Nat.is_le(Nat.add(n, j), x) == True{} : Bool}
  {FD.flat__nthc(UC.slm(s, n, i, j, L, ds, S), x) == FD.flat__nthc(L, x) : U32}
def slm_out(s, n, i, j, L, ds, S, x, hx):
  match n:
    case 0n: {==}
    case 1n+ +p:
      +v = UAx.jn(s, UC.RS(ds, S, i), UC.RS(ds, S, 1n+i))
      +h1 = FD.logic__subst(Nat, z => {Nat.is_le(z, x) == True{} : Bool}, 1n+Nat.add(p, j), Nat.add(p, 1n+j), Equal.sym(Nat, Nat.add(p, 1n+j), 1n+Nat.add(p, j), FD.nat__add_succ(p, j)), hx)
      +hjx = FD.nat__lt_le_trans(j, 1n+j, x, FD.nat__lt_succ(j), FD.nat__le_trans(1n+j, Nat.add(p, 1n+j), x, FD.logic__subst(Nat, z => {Nat.is_le(1n+j, z) == True{} : Bool}, Nat.add(1n+j, p), Nat.add(p, 1n+j), FD.nat__add_comm(1n+j, p), FD.nat__le_add_right(1n+j, p)), h1))
      Equal.trans(U32, FD.flat__nthc(UC.slm(s, p, 1n+i, 1n+j, FD.spec_common__update(U32, L, j, v), ds, S), x),
        FD.flat__nthc(FD.spec_common__update(U32, L, j, v), x), FD.flat__nthc(L, x),
        slm_out(s, p, 1n+i, 1n+j, FD.spec_common__update(U32, L, j, v), ds, S, x, h1),
        FD.flat__nthc_other(L, j, x, v, FD.nat__is_eq_lt(j, x, hjx)))

def smone_out(+s: Nat, +n: Nat, +i: Nat, +dd: Nat, +ds: Nat, +S: FD.array__Tree<U32>, +x: Nat, +hn: {Nat.is_le(n, VB.pw(dd)) == True{} : Bool}, +hx: {Nat.is_le(n, x) == True{} : Bool})
    -> {VB.slot(UC.smone(s, n, i, 0n, dd, ds, VC.ZT(dd), S), x) == 0 : U32}:
  %Equal.sym(List<&2, U32>, FD.array__slots(U32, UC.smone(s, n, i, 0n, dd, ds, VC.ZT(dd), S)), UC.slm(s, n, i, 0n, FD.array__slots(U32, VC.ZT(dd)), ds, S),
      UC.slots_smone(s, n, i, 0n, dd, ds, VC.ZT(dd), S, FD.array__trep_perfect(U32, dd, 0), FD.logic__subst(Nat, z => {Nat.is_le(z, VB.pw(dd)) == True{} : Bool}, n, Nat.add(n, 0n), Equal.sym(Nat, Nat.add(n, 0n), n, FD.nat__add_zero(n)), hn))) :
    {FD.flat__nthc(_, x) == 0 : U32}
  %Equal.sym(U32, FD.flat__nthc(UC.slm(s, n, i, 0n, FD.array__slots(U32, VC.ZT(dd)), ds, S), x), FD.flat__nthc(FD.array__slots(U32, VC.ZT(dd)), x),
      slm_out(s, n, i, 0n, FD.array__slots(U32, VC.ZT(dd)), ds, S, x, FD.logic__subst(Nat, z => {Nat.is_le(z, x) == True{} : Bool}, n, Nat.add(n, 0n), Equal.sym(Nat, Nat.add(n, 0n), n, FD.nat__add_zero(n)), hx))) :
    {_ == 0 : U32}
  %Equal.sym(List<&2, U32>, FD.array__slots(U32, VC.ZT(dd)), FD.spec_common__replicate(U32, FD.spec_common__pow2(dd), 0), FD.array__trep_slots(U32, dd, 0)) : {FD.flat__nthc(_, x) == 0 : U32}
  FD.flat__nthc_rep(FD.spec_common__pow2(dd), x)
"""

BYTE = ['U32.and({w}, 255)', 'U32.and(U32.shrn({w}, 8n), 255)', 'U32.and(U32.shrn({w}, 16n), 255)', 'U32.shrn({w}, 24n)']


def zb(r):
    """zb<r>: the bytes of chunk q past its first r are zero, from its words (whole words past ceil(r / 4) zero,
    the bytes of word r / 4 past r % 4 zero)"""
    a, b = divmod(r, 4)
    first_zero = a + (1 if b else 0)
    W = lambda j: f'MR.wd(W, Nat.add(O.e8(Nat.add(q, 0n)), {j}n))'
    ps = ['+W: List<&2, U32>', '+q: Nat']
    ps += [f'+hw{j}: {{{W(j)} == 0 : U32}}' for j in range(first_zero, 8)]
    if b:
        ps += [f'+hb{k}: {{{BYTE[k].format(w=W(a))} == 0 : U32}}' for k in range(b, 4)]
    cur = [BYTE[p % 4].format(w=W(p // 4)) for p in range(32)]
    lines = []
    for p in range(r, 32):
        j, k = divmod(p, 4)
        motive = ', '.join('_' if i == p else cur[i] for i in range(32))
        P = f'{{WS.bdrop({r}n, [{motive}]) == SP.zero_bytes(Nat.sub(32n, {r}n)) : +List<U32>}}'
        if j >= first_zero:
            z = BYTE[k].format(w='0')
            e = f'Equal.cong(U32, U32, z => {BYTE[k].format(w="z")}, {W(j)}, 0, hw{j})'
            lines.append(f'  %Equal.sym(U32, {cur[p]}, {z}, {e}) :\n    {P}')
            cur[p] = z
        else:
            lines.append(f'  %Equal.sym(U32, {cur[p]}, 0, hb{k}) :\n    {P}')
            cur[p] = '0'
    return (f'def zb{r}(' + ', '.join(ps) + f')\n    -> {{WS.bdrop({r}n, WS.cb(W, Nat.add(q, 0n))) == SP.zero_bytes(Nat.sub(32n, {r}n)) : +List<U32>}}:\n'
            + '\n'.join(lines) + '\n  {==}\n')

KINDS = {
    'm': dict(M='VB.mone(VC.NW(L), i, 0n, dz, VC.ZT(dz), S)', ps='', a='', sfx='',
              pf='VB.mone_perfect(VC.NW(L), i, 0n, dz, VC.ZT(dz), S, FD.array__trep_perfect(U32, dz, 0))',
              out=lambda x: f'mone_out(VC.NW(L), i, dz, S, {x}, hn, hx)'),
    's': dict(M='UC.smone(sh, VC.NW(L), i, 0n, dz, ds, VC.ZT(dz), S)', ps=', +sh: Nat, +ds: Nat', a=', sh, ds', sfx='s',
              pf='UC.smone_perfect(sh, VC.NW(L), i, 0n, dz, ds, VC.ZT(dz), S, FD.array__trep_perfect(U32, dz, 0))',
              out=lambda x: f'smone_out(sh, VC.NW(L), i, dz, ds, S, {x}, hn, hx)'),
}


MASK = {1: '255', 2: '65535', 3: '16777215'}


def sdkr(R, kind='m'):
    K = KINDS[kind]
    """sdk<R>: decoded byte storage of a length L = 32 q + R (the words VB.mone copied from S over a zero tree, the last
    one masked by VY.MK) is BL.sdk1 at any bound k above its depth"""
    a, b = divmod(R, 4)
    c = a + (1 if b else 0)
    Y = 'O.e8(q)'
    X = f'Nat.add({a}n, {Y})'
    M = K['M']
    T = f'VY.MK(L, dz, {M})'
    IDX = lambda j: f'Nat.add(O.e8(Nat.add(q, 0n)), {j}n)'
    NWv = f'Nat.add({c}n, {Y})'
    KWv = f'Nat.add({c - 1}n, {Y})'
    L_ = []
    L_.append(f'  +eL4 = Equal.trans(Nat, U32.to_nat(L), Nat.add(WS.e32(q), {R}n), Nat.add({b}n, A.quad({X})), eN,\n'
              f'    Equal.trans(Nat, Nat.add(WS.e32(q), {R}n), Nat.add({R}n, WS.e32(q)), Nat.add({b}n, A.quad({X})), FD.nat__add_comm(WS.e32(q), {R}n), {{==}}))')
    L_.append(f'  +eQL = Equal.trans(Nat, VY.QL(L), VD.s_rng(2n, U32.to_nat(L)), {X}, VD.shrk(2n, L),\n'
              f'    Equal.trans(Nat, VD.s_rng(2n, U32.to_nat(L)), VD.s_rng(2n, Nat.add({b}n, A.quad({X}))), {X}, Equal.cong(Nat, Nat, z => VD.s_rng(2n, z), U32.to_nat(L), Nat.add({b}n, A.quad({X})), eL4), TZ.hq{b}({X})))')
    L_.append(f'  +e1 = FD.logic__subst(Nat, z => {{U32.to_nat(L) == Nat.add(A.quad(z), U32.to_nat(U32.and(L, 3))) : Nat}}, VY.QL(L), {X}, eQL, VC.split4(L))')
    L_.append(f'  +eR = FD.lru_subtraction_bounds__cancel_left(A.quad({X}), U32.to_nat(U32.and(L, 3)), {b}n,\n'
              f'    Equal.trans(Nat, Nat.add(A.quad({X}), U32.to_nat(U32.and(L, 3))), U32.to_nat(L), Nat.add(A.quad({X}), {b}n), Equal.sym(Nat, U32.to_nat(L), Nat.add(A.quad({X}), U32.to_nat(U32.and(L, 3))), e1),\n'
              f'      Equal.trans(Nat, U32.to_nat(L), Nat.add({b}n, A.quad({X})), Nat.add(A.quad({X}), {b}n), eL4, FD.nat__add_comm({b}n, A.quad({X})))))')
    L_.append(f'  +eRM = FD.u32__injective(U32.and(L, 3), {b}, eR)')
    hq = f'TZ.hq3({X})' if b == 0 else f'TZ.hq{b - 1}(1n+{X})'
    L_.append(f'  +eNW = Equal.trans(Nat, VC.NW(L), VD.s_rng(2n, 3n+U32.to_nat(L)), {NWv}, VC.eNWu(L, hy),\n'
              f'    Equal.trans(Nat, VD.s_rng(2n, 3n+U32.to_nat(L)), VD.s_rng(2n, 3n+Nat.add({b}n, A.quad({X}))), {NWv}, Equal.cong(Nat, Nat, z => VD.s_rng(2n, 3n+z), U32.to_nat(L), Nat.add({b}n, A.quad({X})), eL4), {hq}))')
    L_.append(f'  +h1 = VY.FD_le1(VC.NW(L), {KWv}, eNW)')
    L_.append(f'  +eKW = Equal.trans(Nat, VY.KW(L), Nat.sub(VC.NW(L), 1n), {KWv}, FD.u32__sub_nat(VC.nwu(L), 1, h1),\n'
              f'    Equal.trans(Nat, Nat.sub(VC.NW(L), 1n), Nat.sub({NWv}, 1n), {KWv}, Equal.cong(Nat, Nat, z => Nat.sub(z, 1n), VC.NW(L), {NWv}, eNW), FD.nat__sub_zero({KWv})))')
    L_.append(f'  +kwlt = FD.logic__subst(Nat, z => {{Nat.is_lt(z, VC.NW(L)) == True{{}} : Bool}}, {KWv}, VY.KW(L), Equal.sym(Nat, VY.KW(L), {KWv}, eKW),\n'
              f'    FD.logic__subst(Nat, z => {{Nat.is_lt({KWv}, z) == True{{}} : Bool}}, {NWv}, VC.NW(L), Equal.sym(Nat, VC.NW(L), {NWv}, eNW), FD.nat__lt_succ({KWv})))')
    L_.append(f'  +hk = FD.nat__lt_le_trans(VY.KW(L), VC.NW(L), VB.pw(dz), kwlt, hn)')
    L_.append(f"  +pfM = {K['pf']}")
    hws = []
    for j in range(c, 8):
        L_.append(f'  +eI{j} = Equal.trans(Nat, {IDX(j)}, Nat.add({Y}, {j}n), Nat.add({j}n, {Y}), Equal.cong(Nat, Nat, z => Nat.add(O.e8(z), {j}n), Nat.add(q, 0n), q, FD.nat__add_zero(q)), FD.nat__add_comm({Y}, {j}n))')
        L_.append(f'  +hx{j} = FD.logic__subst(Nat, z => {{Nat.is_le(VC.NW(L), z) == True{{}} : Bool}}, Nat.add({j}n, {Y}), {IDX(j)}, Equal.sym(Nat, {IDX(j)}, Nat.add({j}n, {Y}), eI{j}),\n'
                  f'    FD.logic__subst(Nat, z => {{Nat.is_le(z, Nat.add({j}n, {Y})) == True{{}} : Bool}}, {NWv}, VC.NW(L), Equal.sym(Nat, VC.NW(L), {NWv}, eNW), Order.add_right({c}n, {j}n, {Y}, {{==}})))')
        L_.append(f'  +hw{j} = Equal.trans(U32, VB.slot({T}, {IDX(j)}), VB.slot({M}, {IDX(j)}), 0,\n'
                  f'    mk_out(L, dz, {M}, {IDX(j)}, pfM, hk, FD.nat__is_eq_lt(VY.KW(L), {IDX(j)}, FD.nat__lt_le_trans(VY.KW(L), VC.NW(L), {IDX(j)}, kwlt, hx{j}))),\n'
                  "    " + K['out'](IDX(j)).replace(', hx)', f', hx{j})') + ')')
        hws.append(f'hw{j}')
    hbs = []
    if b:
        L_.append(f'  +eIa = Equal.trans(Nat, {IDX(a)}, Nat.add({Y}, {a}n), VY.KW(L), Equal.cong(Nat, Nat, z => Nat.add(O.e8(z), {a}n), Nat.add(q, 0n), q, FD.nat__add_zero(q)),\n'
                  f'    Equal.trans(Nat, Nat.add({Y}, {a}n), Nat.add({a}n, {Y}), VY.KW(L), FD.nat__add_comm({Y}, {a}n), Equal.sym(Nat, VY.KW(L), {KWv}, eKW)))')
        L_.append(f'  +hbz = FD.logic__subst(U32, z => {{U32.is_eq(z, 0) == False{{}} : Bool}}, {b}, VY.RM(L), Equal.sym(U32, VY.RM(L), {b}, eRM), {{==}})')
        L_.append(f'  +eW0 = FD.logic__subst(U32, z => {{VB.slot({T}, VY.KW(L)) == O.keep(z, VB.slot({M}, VY.KW(L))) : U32}}, VY.RM(L), {b}, eRM, mk_at(L, dz, {M}, pfM, hk, hbz))')
        L_.append(f'  +eWa = FD.logic__subst(Nat, z => {{VB.slot({T}, z) == U32.and(VB.slot({M}, VY.KW(L)), {MASK[b]}) : U32}}, VY.KW(L), {IDX(a)}, Equal.sym(Nat, {IDX(a)}, VY.KW(L), eIa), eW0)')
        for k in range(b, 4):
            byte = BYTE[k]
            L_.append(f'  +hb{k} = FD.logic__subst(U32, z => {{{byte.format(w="z")} == 0 : U32}}, U32.and(VB.slot({M}, VY.KW(L)), {MASK[b]}), VB.slot({T}, {IDX(a)}),\n'
                      f'    Equal.sym(U32, VB.slot({T}, {IDX(a)}), U32.and(VB.slot({M}, VY.KW(L)), {MASK[b]}), eWa), kb{b}_{k}(VB.slot({M}, VY.KW(L))))')
            hbs.append(f'hb{k}')
    if R == 32:
        tail = '{==}'
        body = []
    else:
        tail = f'zb{R}(FD.array__slots(U32, {T}), q' + ''.join(', ' + h for h in hws + hbs) + ')'
        body = L_
    pfT = f"VY.mk_perfect(L, dz, {M}, {K['pf']})"
    tup = f'({T}, (dz, (L, (q, ({R}n, ({{==}}, ({pfT}, (hdk, (eN, ({{==}}, ({{==}}, (hroom, {tail}))))))))))))'
    sig_ = (f"def sdk{K['sfx']}{R}(+L: U32, +dz: Nat, +i: Nat, +S: FD.array__Tree<U32>{K['ps']}, +k: Nat," f' +q: Nat, +eN: {{U32.to_nat(L) == Nat.add(WS.e32(q), {R}n) : Nat}},\n'
            f'    +hdk: {{Nat.is_lt(dz, k) == True{{}} : Bool}}, +hn: {{Nat.is_le(VC.NW(L), VB.pw(dz)) == True{{}} : Bool}}, +hy: {{Nat.is_le(VC.YL(L), U32.to_nat(VB.UMAX())) == True{{}} : Bool}},\n'
            f'    +hroom: {{Nat.is_le(O.e8(1n+q), FD.spec_common__pow2(dz)) == True{{}} : Bool}})\n'
            f'    -> BL.sdk1(O.Words{{FD.array__thaw(U32, {T}), L}}, k):\n')
    return sig_ + '\n'.join(body) + ('\n' if body else '') + f'  {tup}\n'


def hq5(rr):
    """s_rng(5, rr + 32 X) = X for rr < 32"""
    bits = [(rr >> i) & 1 for i in range(5)]
    B = lambda v: 'True{}' if v else 'False{}'
    F = ['X']
    for i in reversed(range(5)):
        F.insert(0, f'Nat.add(FD.spec_numeric__bit_value({B(bits[i])}), Nat.double({F[0]}))')
    lines = []
    for i in range(5):
        mot = '_'
        for _ in range(4 - i):
            mot = f'VD.s_h2({mot})'
        lines.append(f'  %Equal.sym(Nat, VD.s_h2({F[i]}), {F[i + 1]}, VD.s_h2_bit({B(bits[i])}, {F[i + 1]})) : {{{mot} == X : Nat}}')
    return f'def hq5_{rr}(+X: Nat) -> {{VD.s_rng(5n, Nat.add({rr}n, WS.e32(X))) == X : Nat}}:\n' + '\n'.join(lines) + '\n  {==}\n'


def room(R):
    """the decoder's storage depth dz (its WZ(L) words fit) has room for the chunks of L = 32 q + R"""
    return (f'def room{R}(+L: U32, +q: Nat, +eN: {{U32.to_nat(L) == Nat.add(WS.e32(q), {R}n) : Nat}}, +dz: Nat,\n'
            f'    +hy: {{Nat.is_le(VC.YL(L), U32.to_nat(VB.UMAX())) == True{{}} : Bool}}, +hwc: {{Nat.is_le(U32.to_nat(VC.WZ(L)), O.pow2n(dz)) == True{{}} : Bool}})\n'
            f'    -> {{Nat.is_le(O.e8(1n+q), FD.spec_common__pow2(dz)) == True{{}} : Bool}}:\n'
            f'  +eY = Equal.trans(Nat, VC.YL(L), Nat.add(31n, Nat.add(WS.e32(q), {R}n)), Nat.add({R - 1}n, WS.e32(1n+q)), Equal.cong(Nat, Nat, z => Nat.add(31n, z), U32.to_nat(L), Nat.add(WS.e32(q), {R}n), eN),\n'
            f'    Equal.trans(Nat, Nat.add(31n, Nat.add(WS.e32(q), {R}n)), Nat.add(31n, Nat.add({R}n, WS.e32(q))), Nat.add({R - 1}n, WS.e32(1n+q)), Equal.cong(Nat, Nat, z => Nat.add(31n, z), Nat.add(WS.e32(q), {R}n), Nat.add({R}n, WS.e32(q)), FD.nat__add_comm(WS.e32(q), {R}n)), {{==}}))\n'
            f'  +eS = Equal.trans(Nat, VD.s_rng(5n, VC.YL(L)), VD.s_rng(5n, Nat.add({R - 1}n, WS.e32(1n+q))), 1n+q, Equal.cong(Nat, Nat, z => VD.s_rng(5n, z), VC.YL(L), Nat.add({R - 1}n, WS.e32(1n+q)), eY), hq5_{R - 1}(1n+q))\n'
            f'  +eW = Equal.trans(Nat, U32.to_nat(VC.WZ(L)), Nat.add(VB.d3(VD.s_rng(5n, VC.YL(L))), 8n), Nat.add(O.e8(1n+q), 8n), VC.eWZu(L, hy), Equal.cong(Nat, Nat, z => Nat.add(VB.d3(z), 8n), VD.s_rng(5n, VC.YL(L)), 1n+q, eS))\n'
            f'  FD.nat__le_trans(O.e8(1n+q), U32.to_nat(VC.WZ(L)), FD.spec_common__pow2(dz),\n'
            f'    FD.logic__subst(Nat, z => {{Nat.is_le(O.e8(1n+q), z) == True{{}} : Bool}}, Nat.add(O.e8(1n+q), 8n), U32.to_nat(VC.WZ(L)), Equal.sym(Nat, U32.to_nat(VC.WZ(L)), Nat.add(O.e8(1n+q), 8n), eW), FD.nat__le_add_right(O.e8(1n+q), 8n)),\n'
            f'    FD.logic__subst(Nat, z => {{Nat.is_le(U32.to_nat(VC.WZ(L)), z) == True{{}} : Bool}}, O.pow2n(dz), FD.spec_common__pow2(dz), Equal.sym(Nat, FD.spec_common__pow2(dz), O.pow2n(dz), VD.s_pow2_eq(dz)), hwc))\n')


def dispatch(kind='m'):
    K = KINDS[kind]
    sf = K['sfx']
    """sdk_dec: the length's low five bits pick the lemma sdk<R> (R = 32 when they are zero: then the high bits are not)"""
    M = K['M']
    ps = ('+dz: Nat, +i: Nat, +S: FD.array__Tree<U32>' + K['ps'] + ', +k: Nat, +hdk: {Nat.is_lt(dz, k) == True{} : Bool}, '
          '+hy: {Nat.is_le(VC.YL(L), U32.to_nat(VB.UMAX())) == True{} : Bool}, +hwc: {Nat.is_le(U32.to_nat(VC.WZ(L)), O.pow2n(dz)) == True{} : Bool}')
    goal = f'BL.sdk1(O.Words{{FD.array__thaw(U32, VY.MK(L, dz, {M})), L}}, k)'
    hn = (f'FD.nat__le_trans(VC.NW(L), U32.to_nat(VC.WZ(L)), VB.pw(dz), VC.nw_le_wzu(L, hy), '
          f'FD.logic__subst(Nat, z => {{Nat.is_le(U32.to_nat(VC.WZ(L)), z) == True{{}} : Bool}}, O.pow2n(dz), VB.pw(dz), Equal.sym(Nat, VB.pw(dz), O.pow2n(dz), VD.s_pow2_eq(dz)), hwc))')
    out = []
    # R = 32 (low bits zero): q = X - 1, X >= 1 as L is not zero
    out.append(f'def sdz{sf}_go(+L: U32, +X: Nat, +eX: {{U32.to_nat(L) == WS.e32(X) : Nat}}, +hL: {{Nat.is_eq(U32.to_nat(L), 0n) == False{{}} : Bool}}, {ps})\n    -> {goal}:\n'
               f'  match X:\n    case 0n: Empty.absurd({goal}, FD.logic__true_false(FD.logic__subst(Nat, z => {{Nat.is_eq(z, 0n) == False{{}} : Bool}}, U32.to_nat(L), 0n, eX, hL)))\n'
               f'    case 1n+ +p:\n'
               f'      +eN = Equal.trans(Nat, U32.to_nat(L), WS.e32(1n+p), Nat.add(WS.e32(p), 32n), eX, Equal.trans(Nat, WS.e32(1n+p), Nat.add(32n, WS.e32(p)), Nat.add(WS.e32(p), 32n), {{==}}, FD.nat__add_comm(32n, WS.e32(p))))\n'
               f'      sdk{sf}32(L, dz, i, S' + K['a'] + f', k, p, eN, hdk, {hn}, hy, room32(L, p, eN, dz, hy, hwc))')
    rows = []
    for v in range(32):
        bits = [(v >> j) & 1 for j in range(5)]
        pat = '+r'
        for b_ in reversed(bits):
            pat = f'WCon{{{"True{}" if b_ else "False{}"}, {pat}}}'
        Lp = f'U32{{{pat}}}'
        Lc = Lp.replace('+r', 'r')
        X = 'Word.to_nat(27n, r)'
        if v == 0:
            rows.append(f'    case {Lp}:\n      sdz{sf}_go({Lc}, {X}, {{==}}, FD.logic__subst(Bool, z => {{z == False{{}} : Bool}}, U32.is_eq({Lc}, 0), Nat.is_eq(U32.to_nat({Lc}), 0n), VD.eq0({Lc}), hL), dz, i, S' + K['a'] + ', k, hdk, hy, hwc)')
        else:
            eN = (f'Equal.trans(Nat, U32.to_nat({Lc}), Nat.add({v}n, WS.e32({X})), Nat.add(WS.e32({X}), {v}n), {{==}}, FD.nat__add_comm({v}n, WS.e32({X})))')
            hnc = hn.replace('(L', f'({Lc}').replace(' L)', f' {Lc})').replace(', L,', f', {Lc},')
            rows.append(f'    case {Lp}:\n      +eN = {eN}\n      sdk{sf}{v}({Lc}, dz, i, S' + K['a'] + f', k, {X}, eN, hdk, {hnc}, hy, room{v}({Lc}, {X}, eN, dz, hy, hwc))')
    out.append(f'def sdk{sf}_dec(+L: U32, +hL: {{U32.is_eq(L, 0) == False{{}} : Bool}}, {ps})\n    -> {goal}:\n  match L:\n' + '\n'.join(rows))
    return '\n\n'.join(out) + '\n'


def wrappers(kind='m'):
    K = KINDS[kind]
    sf = K['sfx']
    """byte storage of any length (zero or not): BL.sdk (Or2 of sdk0 / sdk1) and the root invariant's LO.wfl"""
    M = K['M']
    T = f'VY.MK(L, dz, {M})'
    O_ = f'O.Words{{FD.array__thaw(U32, {T}), L}}'
    ps = ('+dz: Nat, +i: Nat, +S: FD.array__Tree<U32>' + K['ps'] + ', +k: Nat, +hdk: {Nat.is_lt(dz, k) == True{} : Bool}, '
          '+hy: {Nat.is_le(VC.YL(L), U32.to_nat(VB.UMAX())) == True{} : Bool}, +hwc: {Nat.is_le(U32.to_nat(VC.WZ(L)), O.pow2n(dz)) == True{} : Bool}')
    args = 'dz, i, S' + K['a'] + ', k, hdk, hy, hwc'
    pf = f"VY.mk_perfect(L, dz, {M}, {K['pf']})"
    zero = (f'({T}, (dz, (L, ({{==}}, ({pf}, (hdk, FD.nat__eq_from_is_eq(U32.to_nat(L), 0n, '
            f'FD.logic__subst(Bool, z => {{z == True{{}} : Bool}}, U32.is_eq(L, 0), Nat.is_eq(U32.to_nat(L), 0n), VD.eq0(L), ec))))))))')
    t = (f'def sdk{sf}_go(+L: U32, +c: Bool, +ec: {{U32.is_eq(L, 0) == c : Bool}}, {ps})\n    -> BL.sdk({O_}, k):\n'
            f'  match c:\n    case True{{}}: Inl{{{zero}}}\n    case False{{}}: Inr{{sdk{sf}_dec(L, ec, {args})}}\n\n'
            f'# decoded byte storage (the copy of L bytes from word i of S into a zero tree of depth dz, the last word masked)\n'
            f'def sdk{sf}_any(+L: U32, {ps})\n    -> BL.sdk({O_}, k):\n  sdk{sf}_go(L, U32.is_eq(L, 0), {{==}}, {args})\n')
    if kind == 's':
        return t
    return t + (
            f'# the decoders\' byte storage: the depth VLS.DZ(L) of their zero tree (at most 30), for any bound k above 30\n'
            f'def dec_bytes(+L: U32, +i: Nat, +S: FD.array__Tree<U32>, +k: Nat, +hk: {{Nat.is_lt(30n, k) == True{{}} : Bool}},\n'
            f'    +hy: {{Nat.is_le(VC.YL(L), U32.to_nat(VB.UMAX())) == True{{}} : Bool}})\n'
            f'    -> BL.sdk(O.Words{{FD.array__thaw(U32, VY.MK(L, VLS.DZ(L), VB.mone(VC.NW(L), i, 0n, VLS.DZ(L), VC.ZT(VLS.DZ(L)), S))), L}}, k):\n'
            f'  sdk_any(L, VLS.DZ(L), i, S, k, FD.nat__le_lt_trans(VLS.DZ(L), 30n, k, VC.dz30(L, hy), hk), hy, VD.wd_cover(VC.WZ(L), 30n, {{==}}, VC.wz30(L, hy)))\n')


CT_TEXT = """
# ---- the decoders' copies at any byte offset (UCT.CT: aligned, VB.mone; unaligned, UC.smone) ----
def ct_go(+d: Nat, +t: FD.array__Tree<U32>, +off: U32, +L: U32, +dz: Nat, +k: Nat, +c: Nat, +ec: {VR.RX(off) == c : Nat},
    +hdk: {Nat.is_lt(dz, k) == True{} : Bool}, +hy: {Nat.is_le(VC.YL(L), U32.to_nat(VB.UMAX())) == True{} : Bool},
    +hwc: {Nat.is_le(U32.to_nat(VC.WZ(L)), O.pow2n(dz)) == True{} : Bool})
    -> BL.sdk(O.Words{FD.array__thaw(U32, UCT.CT(d, t, off, L, dz)), L}, k):
  match c:
    case 0n:
      %Equal.sym(Nat, VR.RX(off), 0n, ec) : BL.sdk(O.Words{FD.array__thaw(U32, UCT.cts(_, d, t, off, L, dz)), L}, k)
      sdk_any(L, dz, VR.QX(off), t, k, hdk, hy, hwc)
    case 1n+ +p:
      %Equal.sym(Nat, VR.RX(off), 1n+p, ec) : BL.sdk(O.Words{FD.array__thaw(U32, UCT.cts(_, d, t, off, L, dz)), L}, k)
      sdks_any(L, dz, VR.QX(off), t, 1n+p, d, k, hdk, hy, hwc)

def ct_any(+d: Nat, +t: FD.array__Tree<U32>, +off: U32, +L: U32, +dz: Nat, +k: Nat,
    +hdk: {Nat.is_lt(dz, k) == True{} : Bool}, +hy: {Nat.is_le(VC.YL(L), U32.to_nat(VB.UMAX())) == True{} : Bool},
    +hwc: {Nat.is_le(U32.to_nat(VC.WZ(L)), O.pow2n(dz)) == True{} : Bool})
    -> BL.sdk(O.Words{FD.array__thaw(U32, UCT.CT(d, t, off, L, dz)), L}, k):
  ct_go(d, t, off, L, dz, k, VR.RX(off), {==}, hdk, hy, hwc)

# the decoders' variable-length byte storage: depth VLS.DZ(L) (at most 30), for any bound k above 30
def ct_dec(+d: Nat, +t: FD.array__Tree<U32>, +off: U32, +L: U32, +k: Nat, +hk: {Nat.is_lt(30n, k) == True{} : Bool},
    +hy: {Nat.is_le(VC.YL(L), U32.to_nat(VB.UMAX())) == True{} : Bool})
    -> BL.sdk(O.Words{FD.array__thaw(U32, UCT.CT(d, t, off, L, VLS.DZ(L))), L}, k):
  ct_any(d, t, off, L, VLS.DZ(L), k, FD.nat__le_lt_trans(VLS.DZ(L), 30n, k, VC.dz30(L, hy), hk), hy, VD.wd_cover(VC.WZ(L), 30n, {==}, VC.wz30(L, hy)))
"""


def text():
    t = IMPORTS + BASE + BASE2 + BASE3
    t += '\n# ---- the zero tail of chunk q, from its words ----\n'
    for r in range(1, 32):
        t += '\n' + zb(r)
    t += '\n# ---- decoded byte storage of a length 32 q + r ----\n'
    for r in range(1, 33):
        t += '\n' + sdkr(r)
    for r in range(1, 33):
        t += '\n' + sdkr(r, 's')
    t += '\n# ---- the decoder depth has room for the chunks ----\n'
    for rr in range(32):
        t += '\n' + hq5(rr)
    for r in range(1, 33):
        t += '\n' + room(r)
    t += '\n# ---- any nonzero length ----\n\n' + dispatch() + '\n' + dispatch('s')
    t += '\n# ---- any length ----\n\n' + wrappers() + '\n' + wrappers('s')
    t += CT_TEXT
    return t


def main():
    t = text()
    if '--check' in sys.argv:
        if not OUT.exists() or OUT.read_text() != t:
            print('stale: e2e/e2e_dz.bend')
            sys.exit(1)
        print('decoded_byte_storage_facts: up to date')
        return
    OUT.write_text(t)
    print('decoded_byte_storage_facts: wrote e2e/e2e_dz.bend')


if __name__ == '__main__':
    main()
