#!/usr/bin/env python3
"""Generates e2e/e2e_dbs.bend: facts about a decoded BeaconState (proofs/obj/var_winx_BeaconState.bend at word 0)
that its composed theorems need beside the per-field storage laws: its check split into the 26 items, each of its
12 variable windows [O_i, O_{i+1}) inside the input (their YL bounds and lengths), the encode laws' length premises
hm (a window's length below 2^31, from the input's n < 2^31) and the size premise hZ (the fixed part and the windows
add up to n: the offsets telescope).

Usage: python3 codegen/proofs/decoded/e2e_decbs.py [--check]"""
import sys as _sys
import pathlib as _pathlib
_sys.path.insert(0, str(_pathlib.Path(__file__).resolve().parents[3]))  # the repository root: `codegen` is importable when this file runs as a script
import sys

from codegen.core.paths import ROOT  # noqa: E402
OUT = ROOT / 'e2e' / 'e2e_dbs.bend'

NW = 12
A_ = 't, x, off, n'
O = lambda i: f'W.O{i}(t, x)' if i < NW else 'n'
L = lambda i: f'W.LJ{i}(t, x)' if i < NW - 1 else f'W.LJ{NW - 1}(t, x, n)'
TN = lambda x: f'U32.to_nat({x})'
HS = '+hS: {U32.is_le(n, VB.NMAX()) == True{} : Bool}'
H31 = '+h31: {Nat.is_lt(U32.to_nat(n), VB.pw(31n)) == True{} : Bool}'
HC = '+hchk: {W.CHKw(t, x, off, n) == True{} : Bool}'
TP = '+t: FD.array__Tree<U32>, +x: Nat, +off: U32, +n: U32'
OBJ = 'W.OBJw(d, t, x, off, n)'
# the size premise's parts, in the windows' order: (term, proof that it is the window's length)
RL = {1: ('l2048_Eth1Data', 72, 'q'), 2: ('l1099511627776_Validator', 121, 'm'), 8: ('l16777216_HistoricalSummary', 64, 'q'),
      9: ('l134217728_PendingDeposit', 192, 'q'), 10: ('l134217728_PendingPartialWithdrawal', 24, 'q'), 11: ('l262144_PendingConsolidation', 16, 'q')}
FIELD = {0: 7, 1: 9, 2: 11, 3: 12, 4: 15, 5: 16, 6: 21, 7: 24, 8: 27, 9: 34, 10: 35, 11: 36}


def X(i):
    return f'W.XJ{i}(t, x)', f'W.FJ{i}(off, t, x)', L(i)


def parts():
    ts, es = [], []
    for i in range(NW):
        pj = f'ST.pj_BeaconState_{FIELD[i]}({OBJ})'
        if i in RL:
            stem, esz, kind = RL[i]
            x, f, l = X(i)
            ts.append(f'RLS.WLL_{stem}({pj})')
            es.append(f'Equal.trans(Nat, RLS.WLL_{stem}({pj}), Nat.mul(U32.to_nat(ST.xlen_o_{stem}({pj})), {esz}n), {TN(l)}, wq_{stem}({pj}), R{i}.ln(d, t, {x}, {f}, {l}, it{14 + i}(t, x, off, n, hchk)))')
        elif i == 7:
            ts.append(f'EB.LNEH({pj})')
            es.append(f'eh(d, t, x, off, n, hchk)')
        else:
            ts.append(TN(f'WO_L.len({pj})'))
            es.append('{==}')
    return ts, es


def text():
    out = ['import Base', 'import ../src/obj.bend as O', 'import ../proofs/compact/found.bend as FD', 'import ../proofs/compact/arith.bend as A',
           'import ../proofs/nat_order.bend as Order', 'import ../proofs/obj/dk.bend as DK', 'import ../proofs/obj/vbuf.bend as VB', 'import ../proofs/obj/vcopy.bend as VC',
           'import ../proofs/obj/words_obj_light.bend as WO_L', 'import ../proofs/obj/root_state_light.bend as ST',
           'import ../proofs/obj/var_codec_BeaconState.bend as DC', 'import ../proofs/obj/var_winx_BeaconState.bend as W',
           'import ../proofs/obj/var_bytesx_ExecutionPayloadHeader.bend as HX', 'import ./e2e_rls.bend as RLS', 'import ./FuluBeaconState_e2e_generated.bend as EB']
    for i, (stem, esz, kind) in RL.items():
        out.append(f'import ./e2e_drl_{stem}.bend as R{i}')
        m = {'l2048_Eth1Data': 'Eth1Data_2048', 'l1099511627776_Validator': 'Validator_1099511627776', 'l16777216_HistoricalSummary': 'HistoricalSummary_16777216',
             'l134217728_PendingDeposit': 'PendingDeposit_134217728', 'l134217728_PendingPartialWithdrawal': 'PendingPartialWithdrawal_134217728',
             'l262144_PendingConsolidation': 'PendingConsolidation_262144'}[stem]
        out.append(f'import ../types/Fulu_list_{m}_def_generated.bend as Fulu_list_{m}_d')
    rtl = {}
    for i, (stem, esz, kind) in RL.items():
        out.append(f'import ../proofs/obj/root_state_light.bend as RTL_{i}') if False else None
    t = '\n'.join(out) + '\n'
    for i in RL:
        t = t.replace(f'RTL_{i}.', 'ST.')
    t += '''
# GENERATED by e2e_decbs (codegen). Do not edit.
# A decoded BeaconState: its check's 26 items, its 12 variable windows inside the input, the length premises hm
# (n < 2^31) and the size premise hZ (the fixed part and the windows add up to n).

def u2n(+a: U32, +b: U32, +h: {U32.is_le(a, b) == True{} : Bool}) -> {Nat.is_le(U32.to_nat(a), U32.to_nat(b)) == True{} : Bool}:
  FD.logic__subst(Bool, z => {z == True{} : Bool}, U32.is_le(a, b), Nat.is_le(U32.to_nat(a), U32.to_nat(b)), VB.le_u32n(a, b), h)

# double and quadruple distribute over sums; 4 (n k) = n (4 k)
law dadd:
  for +a: Nat
  for +b: Nat
  {Nat.double(Nat.add(a, b)) == Nat.add(Nat.double(a), Nat.double(b)) : Nat}
def dadd(a, b):
  match a:
    case 0n: {==}
    case 1n+ +p: Equal.cong(Nat, Nat, z => 2n+z, Nat.double(Nat.add(p, b)), Nat.add(Nat.double(p), Nat.double(b)), dadd(p, b))

law qmul:
  for +n: Nat
  for +k: Nat
  {A.quad(Nat.mul(n, k)) == Nat.mul(n, A.quad(k)) : Nat}
def qmul(n, k):
  match n:
    case 0n: {==}
    case 1n+ +p:
      +e1 = Equal.trans(Nat, Nat.double(Nat.double(Nat.add(k, Nat.mul(p, k)))), Nat.double(Nat.add(Nat.double(k), Nat.double(Nat.mul(p, k)))), Nat.add(A.quad(k), A.quad(Nat.mul(p, k))),
        Equal.cong(Nat, Nat, z => Nat.double(z), Nat.double(Nat.add(k, Nat.mul(p, k))), Nat.add(Nat.double(k), Nat.double(Nat.mul(p, k))), dadd(k, Nat.mul(p, k))), dadd(Nat.double(k), Nat.double(Nat.mul(p, k))))
      Equal.trans(Nat, A.quad(Nat.mul(1n+p, k)), Nat.add(A.quad(k), A.quad(Nat.mul(p, k))), Nat.mul(1n+p, A.quad(k)), e1,
        Equal.cong(Nat, Nat, z => Nat.add(A.quad(k), z), A.quad(Nat.mul(p, k)), Nat.mul(p, A.quad(k)), qmul(p, k)))
'''
    # the record lists' byte counts
    for i, (stem, esz, kind) in RL.items():
        seq_mod = {'l2048_Eth1Data': 'Fulu_list_Eth1Data_2048_d', 'l1099511627776_Validator': 'Fulu_list_Validator_1099511627776_d',
                   'l16777216_HistoricalSummary': 'Fulu_list_HistoricalSummary_16777216_d', 'l134217728_PendingDeposit': 'Fulu_list_PendingDeposit_134217728_d',
                   'l134217728_PendingPartialWithdrawal': 'Fulu_list_PendingPartialWithdrawal_134217728_d', 'l262144_PendingConsolidation': 'Fulu_list_PendingConsolidation_262144_d'}[stem]
        ST_ = f'{seq_mod}.{stem}_Seq'
        if kind == 'm':
            body = '{==}'
        else:
            body = f'qmul(U32.to_nat(nn), {esz // 4}n)'
        t += (f'\ndef wq_{stem}(w: {ST_}) -> {{RLS.WLL_{stem}(w) == Nat.mul(U32.to_nat(ST.xlen_o_{stem}(w)), {esz}n) : Nat}}:\n'
              f'  match w:\n    case {ST_}{{arr, +nn}}: {body}\n')
    t += '\n# ---- the check, item by item (the reader\'s own it<j>) ----\n'
    for j in range(26):
        t += f'def it{j}({TP}, {HC}) -> {{W.IT{j}({A_}) == True{{}} : Bool}}: W.it{j}(t, x, off, n, hchk)\n'
    t += '\n# ---- the windows: O_i <= O_{i+1} <= n, O_i + L_i = O_{i+1}; L_i fits the input ----\n'
    for i in range(NW - 1):
        it = f'it{2 + i}(t, x, off, n, hchk)'
        a, b = f'U32.is_le({O(i)}, {O(i + 1)})', f'U32.is_le({O(i + 1)}, n)'
        t += (f'def ord{i}({TP}, {HC}) -> {{Nat.is_le({TN(O(i))}, {TN(O(i + 1))}) == True{{}} : Bool}}: u2n({O(i)}, {O(i + 1)}, FD.logic__and_left({a}, {b}, {it}))\n'
              f'def top{i}({TP}, {HC}) -> {{Nat.is_le({TN(O(i + 1))}, U32.to_nat(n)) == True{{}} : Bool}}: u2n({O(i + 1)}, n, FD.logic__and_right({a}, {b}, {it}))\n')
    for i in range(NW):
        ordi = f'ord{i}(t, x, off, n, hchk)' if i < NW - 1 else 'top10(t, x, off, n, hchk)'
        topi = f'top{i}(t, x, off, n, hchk)' if i < NW - 1 else 'FD.nat__le_refl(U32.to_nat(n))'
        t += (f'def lsum{i}({TP}, {HC}) -> {{Nat.add({TN(O(i))}, {TN(L(i))}) == {TN(O(i + 1))} : Nat}}:\n'
              f'  Equal.trans(Nat, Nat.add({TN(O(i))}, {TN(L(i))}), Nat.add({TN(O(i))}, Nat.sub({TN(O(i + 1))}, {TN(O(i))})), {TN(O(i + 1))},\n'
              f'    Equal.cong(Nat, Nat, z => Nat.add({TN(O(i))}, z), {TN(L(i))}, Nat.sub({TN(O(i + 1))}, {TN(O(i))}), FD.u32__sub_nat({O(i + 1)}, {O(i)}, {ordi})),\n'
              f'    FD.nat__sub_add({TN(O(i + 1))}, {TN(O(i))}, {ordi}))\n'
              f'def lwn{i}({TP}, {HC}) -> {{Nat.is_le({TN(L(i))}, U32.to_nat(n)) == True{{}} : Bool}}:\n'
              f'  FD.nat__le_trans({TN(L(i))}, {TN(O(i + 1))}, U32.to_nat(n), FD.logic__subst(Nat, z => {{Nat.is_le({TN(L(i))}, z) == True{{}} : Bool}}, Nat.add({TN(O(i))}, {TN(L(i))}), {TN(O(i + 1))}, lsum{i}(t, x, off, n, hchk), A.le_skip({TN(O(i))}, {TN(L(i))})), {topi})\n'
              f'def hy{i}({TP}, {HS}, {HC}) -> {{Nat.is_le(VC.YL({L(i)}), U32.to_nat(VB.UMAX())) == True{{}} : Bool}}:\n'
              f'  VC.hyW({TN(O(i))}, {L(i)}, FD.logic__subst(Nat, z => {{Nat.is_le(z, U32.to_nat(VB.NMAX())) == True{{}} : Bool}}, {TN(O(i + 1))}, Nat.add({TN(O(i))}, {TN(L(i))}), Equal.sym(Nat, Nat.add({TN(O(i))}, {TN(L(i))}), {TN(O(i + 1))}, lsum{i}(t, x, off, n, hchk)),\n'
              f'    FD.nat__le_trans({TN(O(i + 1))}, U32.to_nat(n), U32.to_nat(VB.NMAX()), {topi}, u2n(n, VB.NMAX(), hS))))\n'
              f'def hm{i}({TP}, {H31}, {HC}) -> {{Nat.is_lt({TN(L(i))}, VB.pw(31n)) == True{{}} : Bool}}:\n'
              f'  FD.nat__le_lt_trans({TN(L(i))}, U32.to_nat(n), VB.pw(31n), lwn{i}(t, x, off, n, hchk), h31)\n')
    # the header's window: 584 + (L7 - 584) = L7
    x7, f7, l7 = X(7)
    a7, b7, c7 = f'U32.is_le(584, {l7})', f'U32.is_eq(HX.SPOw(t, {x7}), 584)', f'HX.BLW(U32.sub({l7}, HX.SPOw(t, {x7})))'
    t += (f'\ndef eh(+d: Nat, {TP}, {HC}) -> {{EB.LNEH(ST.pj_BeaconState_24(W.OBJw(d, t, x, off, n))) == {TN(l7)} : Nat}}:\n'
          f'  +h = u2n(584, {l7}, HX.chk_a({a7}, {b7}, {c7}, it21(t, x, off, n, hchk)))\n'
          f'  Equal.trans(Nat, Nat.add(584n, {TN(f"U32.sub({l7}, 584)")}), Nat.add(584n, Nat.sub({TN(l7)}, 584n)), {TN(l7)},\n'
          f'    Equal.cong(Nat, Nat, z => Nat.add(584n, z), {TN(f"U32.sub({l7}, 584)")}, Nat.sub({TN(l7)}, 584n), FD.u32__sub_nat({l7}, 584, h)), FD.nat__sub_add({TN(l7)}, 584n, h))\n')
    # the header's extra data: LL(L7) <= 32, so its YL fits
    t += (f'\n# the header window\'s extra data holds at most 32 bytes\n'
          f'def ehl({TP}, {HC}) -> {{Nat.is_le(U32.to_nat(HX.LL({l7})), U32.to_nat(32)) == True{{}} : Bool}}:\n'
          f'  +hb = HX.chk_b({a7}, {b7}, {c7}, it21(t, x, off, n, hchk))\n'
          f'  +hc = HX.chk_c({a7}, {b7}, {c7}, it21(t, x, off, n, hchk))\n'
          f'  +h = FD.logic__subst(U32, z => {{HX.BLW(U32.sub({l7}, z)) == True{{}} : Bool}}, HX.SPOw(t, {x7}), 584, FD.u32alg__eq_of(HX.SPOw(t, {x7}), 584, hb), hc)\n'
          f'  u2n(HX.LL({l7}), 32, h)\n'
          f'def ehy({TP}, {HC}) -> {{Nat.is_le(VC.YL(HX.LL({l7})), U32.to_nat(VB.UMAX())) == True{{}} : Bool}}:\n'
          f'  FD.nat__le_trans(VC.YL(HX.LL({l7})), Nat.add(31n, U32.to_nat(32)), U32.to_nat(VB.UMAX()), Order.add_left(31n, U32.to_nat(HX.LL({l7})), U32.to_nat(32), ehl(t, x, off, n, hchk)), {{==}})\n')
    # the size: F + L_0 + ... + L_11 = n
    ts, es = parts()
    lens = [TN(L(i)) for i in range(NW)]

    def sz(args, first):
        s = first
        for a in args:
            s = f'Nat.add({s}, {a})'
        return s
    F0 = 'U32.to_nat(2737225)'
    lines = []
    cur = list(ts)
    for k in range(NW):
        hole = cur[:k] + ['_'] + cur[k + 1:]
        lines.append(f'  %Equal.sym(Nat, {ts[k]}, {lens[k]}, {es[k]}) : {{{sz(hole, F0)} == U32.to_nat(n) : Nat}}')
        cur[k] = lens[k]
    # O_0 = 2737225
    e0 = f'Equal.cong(U32, Nat, z => U32.to_nat(z), {O(0)}, 2737225, FD.u32alg__eq_of({O(0)}, 2737225, it1(t, x, off, n, hchk)))'
    lines.append(f'  %{e0} : {{{sz(lens, "_")} == U32.to_nat(n) : Nat}}')
    acc = TN(O(0))
    for k in range(NW):
        inner = f'Nat.add({acc}, {lens[k]})'
        rest = lens[k + 1:]
        lines.append(f'  %Equal.sym(Nat, {inner}, {TN(O(k + 1))}, lsum{k}(t, x, off, n, hchk)) : {{{sz(rest, "_")} == U32.to_nat(n) : Nat}}')
        acc = TN(O(k + 1))
    lines.append('  {==}')
    SZR = f'EB.SZR({F0}, {", ".join(ts)})'
    t += (f'\n# the fixed part and the windows add up to n: F = O_0, and O_i + L_i = O_(i+1)\n'
          f'def szr(+d: Nat, {TP}, {HC}) -> {{{SZR} == U32.to_nat(n) : Nat}}:\n' + '\n'.join(lines) + '\n'
          f'\n# the size premise hZ, from n < 2^31\n'
          f'def hz(+d: Nat, {TP}, {H31}, {HC}) -> {{Nat.is_lt({SZR}, VB.pw(31n)) == True{{}} : Bool}}:\n'
          f'  FD.logic__subst(Nat, z => {{Nat.is_lt(z, VB.pw(31n)) == True{{}} : Bool}}, U32.to_nat(n), {SZR}, Equal.sym(Nat, {SZR}, U32.to_nat(n), szr(d, t, x, off, n, hchk)), h31)\n')
    return t


def main():
    t = text()
    if '--check' in sys.argv:
        if not OUT.exists() or OUT.read_text() != t:
            print('stale: e2e/e2e_dbs.bend')
            sys.exit(1)
        print('e2e_decbs: up to date')
        return
    OUT.write_text(t)
    print('e2e_decbs: wrote e2e/e2e_dbs.bend')


if __name__ == '__main__':
    main()
