#!/usr/bin/env python3
"""Generates e2e/e2e_dep.bend: facts about a decoded ExecutionPayload (proofs/obj/var_winx_ExecutionPayload.bend at word 0)
that its composed theorems need beside the per-field storage laws: its check split into items, each of its 3 variable
windows [O_i, O_{i+1}) (extra data, transactions, withdrawals) inside the input (YL bounds, lengths below 2^31 from
n < 2^31), the extra data's length (at most 32 bytes) and the encode law's size premise hZ (528 and the windows'
encodings add up to n). The transactions' encoded size TXL is the window's length by a hypothesis (etx: the transactions
library's lemma).

Usage: python3 codegen/proofs/decoded/execution_payload_decoded_facts.py [--check]"""
import sys as _sys
import pathlib as _pathlib
_sys.path.insert(0, str(_pathlib.Path(__file__).resolve().parents[3]))  # the repository root: `codegen` is importable when this file runs as a script
import sys

from codegen.core.repository_paths import ROOT  # noqa: E402
OUT = ROOT / 'e2e' / 'e2e_dep.bend'

NW = 3
A_ = 't, x, off, n'
O = lambda i: f'W.O{i}(t, x)' if i < NW else 'n'
L = lambda i: f'W.L{i}(t, x)' if i < NW - 1 else f'W.L{NW - 1}(t, x, n)'
TN = lambda x: f'U32.to_nat({x})'
HS = '+hS: {Nat.is_le(U32.to_nat(n), U32.to_nat(VB.NMAX())) == True{} : Bool}'
H31 = '+h31: {Nat.is_lt(U32.to_nat(n), VB.pw(31n)) == True{} : Bool}'
HC = '+hchk: {W.CHKw(t, x, off, n) == True{} : Bool}'
TP = '+t: FD.array__Tree<U32>, +x: Nat, +off: U32, +n: U32'
OBJ = 'W.OBJw(d, t, x, off, n)'
F0 = 'U32.to_nat(528)'
PJ = lambda k: f'RT.pj_ExecutionPayload_{k}({OBJ})'
IMPORTS = """import Base
import ../src/obj.bend as O
import ../proofs/compact/found.bend as FD
import ../proofs/compact/arith.bend as A
import ../proofs/nat_order.bend as Order
import ../proofs/obj/vbuf.bend as VB
import ../proofs/obj/vcopy.bend as VC
import ../proofs/obj/words_obj_light.bend as WO_L
import ../proofs/obj/root_types_light.bend as RT
import ../proofs/obj/var_winx_ExecutionPayload.bend as W
import ../proofs/obj/vvlb_bl32.bend as C0
import ./e2e_drl_l16_Withdrawal.bend as R2
import ./e2e_eptx.bend as TX
import ../types/Fulu_list_Withdrawal_16_def_generated.bend as Fulu_list_Withdrawal_16_d
"""


def _sz(args, first):
    s = first
    for a in args:
        s = f'Nat.add({s}, {a})'
    return s


def text():
    t = IMPORTS
    t += '''
# GENERATED by execution_payload_decoded_facts (codegen). Do not edit.
# A decoded ExecutionPayload: its check's items, its 3 variable windows inside the input, the length premises hm
# (n < 2^31) and the size premise hZ (528 and the windows' encodings add up to n).

def u2n(+a: U32, +b: U32, +h: {U32.is_le(a, b) == True{} : Bool}) -> {Nat.is_le(U32.to_nat(a), U32.to_nat(b)) == True{} : Bool}:
  FD.logic__subst(Bool, z => {z == True{} : Bool}, U32.is_le(a, b), Nat.is_le(U32.to_nat(a), U32.to_nat(b)), VB.le_u32n(a, b), h)

# double and quadruple distribute over sums; 4 (n k) = n (4 k)
law dadd:
  for +a: Nat
  for +b: Nat
  {Nat.double(Nat.add(a, b)) == Nat.add(Nat.double(a), Nat.double(b)) : Nat}
def dadd(a, b):
  match a:
    case 0n: {==}
    case 1n+ +p: Equal.cong(Nat, Nat, z => 2n+z, Nat.double(Nat.add(p, b)), Nat.add(Nat.double(p), Nat.double(b)), dadd(p, b))

law qmul:
  for +n: Nat
  for +k: Nat
  {A.quad(Nat.mul(n, k)) == Nat.mul(n, A.quad(k)) : Nat}
def qmul(n, k):
  match n:
    case 0n: {==}
    case 1n+ +p:
      +e1 = Equal.trans(Nat, Nat.double(Nat.double(Nat.add(k, Nat.mul(p, k)))), Nat.double(Nat.add(Nat.double(k), Nat.double(Nat.mul(p, k)))), Nat.add(A.quad(k), A.quad(Nat.mul(p, k))),
        Equal.cong(Nat, Nat, z => Nat.double(z), Nat.double(Nat.add(k, Nat.mul(p, k))), Nat.add(Nat.double(k), Nat.double(Nat.mul(p, k))), dadd(k, Nat.mul(p, k))), dadd(Nat.double(k), Nat.double(Nat.mul(p, k))))
      Equal.trans(Nat, A.quad(Nat.mul(1n+p, k)), Nat.add(A.quad(k), A.quad(Nat.mul(p, k))), Nat.mul(1n+p, A.quad(k)), e1,
        Equal.cong(Nat, Nat, z => Nat.add(A.quad(k), z), A.quad(Nat.mul(p, k)), Nat.mul(p, A.quad(k)), qmul(p, k)))
'''

    t += ('\ndef wq(w: Fulu_list_Withdrawal_16_d.l16_Withdrawal_Seq) -> {TX.WLL(w) == Nat.mul(U32.to_nat(RT.xlen_o_l16_Withdrawal(w)), 44n) : Nat}:\n'
          '  match w:\n    case Fulu_list_Withdrawal_16_d.l16_Withdrawal_Seq{arr, +nn}: qmul(U32.to_nat(nn), 11n)\n')
    t += '\n# ---- the check, item by item ----\n'
    items = [('cb', 'W.CB(t, x)', 'W.KC2(t, x, off, n)', 'W.kk1'), ('cc1', 'W.CC1(t, x, n)', 'W.KC3(t, x, off, n)', 'W.kk2'), ('cc2', 'W.CC2(t, x, n)', 'W.KC4(t, x, off, n)', 'W.kk3'),
             ('ce0', 'W.CE0(t, x, off, n)', 'W.KC5(t, x, off, n)', 'W.kk4'), ('ce1', 'W.CE1(t, x, off, n)', 'W.KC6(t, x, off, n)', 'W.kk5')]
    for nm, a, b, kk in items:
        t += f'def {nm}({TP}, {HC}) -> {{{a} == True{{}} : Bool}}: FD.logic__and_left({a}, {b}, {kk}(t, x, off, n, hchk))\n'
    t += f'def ce2({TP}, {HC}) -> {{W.CE2(t, x, off, n) == True{{}} : Bool}}: W.kk6(t, x, off, n, hchk)\n'
    ci = {0: 'cc1', 1: 'cc2'}
    for i in range(NW - 1):
        it = f'{ci[i]}(t, x, off, n, hchk)'
        a, b = f'U32.is_le({O(i)}, {O(i + 1)})', f'U32.is_le({O(i + 1)}, n)'
        t += (f'def ord{i}({TP}, {HC}) -> {{Nat.is_le({TN(O(i))}, {TN(O(i + 1))}) == True{{}} : Bool}}: u2n({O(i)}, {O(i + 1)}, FD.logic__and_left({a}, {b}, {it}))\n'
              f'def top{i}({TP}, {HC}) -> {{Nat.is_le({TN(O(i + 1))}, U32.to_nat(n)) == True{{}} : Bool}}: u2n({O(i + 1)}, n, FD.logic__and_right({a}, {b}, {it}))\n')
    for i in range(NW):
        ordi = f'ord{i}(t, x, off, n, hchk)' if i < NW - 1 else f'top{NW - 2}(t, x, off, n, hchk)'
        topi = f'top{i}(t, x, off, n, hchk)' if i < NW - 1 else 'FD.nat__le_refl(U32.to_nat(n))'
        t += (f'def lsum{i}({TP}, {HC}) -> {{Nat.add({TN(O(i))}, {TN(L(i))}) == {TN(O(i + 1))} : Nat}}:\n'
              f'  Equal.trans(Nat, Nat.add({TN(O(i))}, {TN(L(i))}), Nat.add({TN(O(i))}, Nat.sub({TN(O(i + 1))}, {TN(O(i))})), {TN(O(i + 1))},\n'
              f'    Equal.cong(Nat, Nat, z => Nat.add({TN(O(i))}, z), {TN(L(i))}, Nat.sub({TN(O(i + 1))}, {TN(O(i))}), FD.u32__sub_nat({O(i + 1)}, {O(i)}, {ordi})),\n'
              f'    FD.nat__sub_add({TN(O(i + 1))}, {TN(O(i))}, {ordi}))\n'
              f'def lwn{i}({TP}, {HC}) -> {{Nat.is_le({TN(L(i))}, U32.to_nat(n)) == True{{}} : Bool}}:\n'
              f'  FD.nat__le_trans({TN(L(i))}, {TN(O(i + 1))}, U32.to_nat(n), FD.logic__subst(Nat, z => {{Nat.is_le({TN(L(i))}, z) == True{{}} : Bool}}, Nat.add({TN(O(i))}, {TN(L(i))}), {TN(O(i + 1))}, lsum{i}(t, x, off, n, hchk), A.le_skip({TN(O(i))}, {TN(L(i))})), {topi})\n'
              f'def hy{i}({TP}, {HS}, {HC}) -> {{Nat.is_le(VC.YL({L(i)}), U32.to_nat(VB.UMAX())) == True{{}} : Bool}}:\n'
              f'  VC.hyW({TN(O(i))}, {L(i)}, FD.logic__subst(Nat, z => {{Nat.is_le(z, U32.to_nat(VB.NMAX())) == True{{}} : Bool}}, {TN(O(i + 1))}, Nat.add({TN(O(i))}, {TN(L(i))}), Equal.sym(Nat, Nat.add({TN(O(i))}, {TN(L(i))}), {TN(O(i + 1))}, lsum{i}(t, x, off, n, hchk)),\n'
              f'    FD.nat__le_trans({TN(O(i + 1))}, U32.to_nat(n), U32.to_nat(VB.NMAX()), {topi}, hS)))\n'
              f'def hm{i}({TP}, {H31}, {HC}) -> {{Nat.is_lt({TN(L(i))}, VB.pw(31n)) == True{{}} : Bool}}:\n'
              f'  FD.nat__le_lt_trans({TN(L(i))}, U32.to_nat(n), VB.pw(31n), lwn{i}(t, x, off, n, hchk), h31)\n')
    t += (f'\ndef hl0({TP}, {HC}) -> {{Nat.is_le({TN(L(0))}, 32n) == True{{}} : Bool}}: C0.hB(t, W.X0(t, x), W.F0(off, t, x), {L(0)}, ce0(t, x, off, n, hchk))\n')
    ts = [TN(f'WO_L.len({PJ(10)})'), f'TX.TXL({PJ(13)})', f'TX.WLL({PJ(14)})']
    lens = [TN(L(i)) for i in range(NW)]
    es = ['{==}', 'etx', f'Equal.trans(Nat, TX.WLL({PJ(14)}), Nat.mul(U32.to_nat(RT.xlen_o_l16_Withdrawal({PJ(14)})), 44n), {TN(L(2))}, wq({PJ(14)}), R2.ln(d, t, W.X2(t, x), W.F2(off, t, x), {L(2)}, ce2(t, x, off, n, hchk)))']
    lines = []
    cur = list(ts)
    for k in range(NW):
        hole = cur[:k] + ['_'] + cur[k + 1:]
        lines.append(f'  %Equal.sym(Nat, {ts[k]}, {lens[k]}, {es[k]}) : {{{_sz(hole, F0)} == U32.to_nat(n) : Nat}}')
        cur[k] = lens[k]
    e0 = f'Equal.cong(U32, Nat, z => U32.to_nat(z), {O(0)}, 528, FD.u32alg__eq_of({O(0)}, 528, cb(t, x, off, n, hchk)))'
    lines.append(f'  %{e0} : {{{_sz(lens, "_")} == U32.to_nat(n) : Nat}}')
    acc = TN(O(0))
    for k in range(NW):
        inner = f'Nat.add({acc}, {lens[k]})'
        rest = lens[k + 1:]
        lines.append(f'  %Equal.sym(Nat, {inner}, {TN(O(k + 1))}, lsum{k}(t, x, off, n, hchk)) : {{{_sz(rest, "_")} == U32.to_nat(n) : Nat}}')
        acc = TN(O(k + 1))
    lines.append('  {==}')
    SZ = _sz(ts, F0)
    etxT = f'+etx: {{{ts[1]} == {TN(L(1))} : Nat}}'
    t += (f'\n# 528 and the windows\' encodings add up to n\n'
          f'def szr(+d: Nat, {TP}, {etxT}, {HC}) -> {{{SZ} == U32.to_nat(n) : Nat}}:\n' + '\n'.join(lines) + '\n'
          f'\n# the size premise hZ (RC.SZOK), from n < 2^31\n'
          f'def hz(+d: Nat, {TP}, {etxT}, {H31}, {HC}) -> {{Nat.is_lt({SZ}, VB.pw(31n)) == True{{}} : Bool}}:\n'
          f'  FD.logic__subst(Nat, z => {{Nat.is_lt(z, VB.pw(31n)) == True{{}} : Bool}}, U32.to_nat(n), {SZ}, Equal.sym(Nat, {SZ}, U32.to_nat(n), szr(d, t, x, off, n, etx, hchk)), h31)\n')
    return t


def main():
    t = text()
    if '--check' in sys.argv:
        if not OUT.exists() or OUT.read_text() != t:
            print('stale: e2e/e2e_dep.bend')
            sys.exit(1)
        print('execution_payload_decoded_facts: up to date')
        return
    OUT.write_text(t)
    print('execution_payload_decoded_facts: wrote e2e/e2e_dep.bend')


if __name__ == '__main__':
    main()
