#!/usr/bin/env python3
"""e2e/e2e_hkp.bend: the element hooks of a ProgressiveVarTestStruct window for the progressive lists of ProgressiveVarTestStruct
(pl_ProgressiveVarTestStruct: e2e_dvp_pl_ProgressiveVarTestStruct.bend), in the root_gtypes2_light mirrors (RT = RT2 of e2e_encld.bend). The element at
the window (x, off, len) (var_winx_ProgressiveVarTestStruct: WN; OBJw) has, with WF = eo, hd, hw, hw32, pfw, h31 (hw32 here is x + len <= NMAX, the decoder's hwN;
h31: len < 2^29, the decoder's own bound of e2e_dpe_ProgressiveVarTestStruct.bend; progressive_variable_list_decoded_facts.py's lists derive both for each element):

    repT(d, t, x, off, len, hchk, WF, sE, ee)     RT.rep_ProgressiveVarTestStruct_bx(th_bx(MSome{fz(OBJw)}), sE)
    sde(d, t, x, off, len, hchk, WF)              EL.EPB_pl_ProgressiveVarTestStruct(MSome{fz(OBJw)})
    sz(d, t, x, off, len, hchk, WF)               the encoder's bytes of the element are the window's: length(XC.YE(EL.fbx_pl_ProgressiveVarTestStruct(MSome{fz(OBJw)}))) == len
    canon(d, t, x, off, len, hchk, WF)            th_bx(MSome{fz(OBJw)}) == BSome{OBJw, BNone}

The lemmas are e2e_dpe_ProgressiveVarTestStruct.bend's p_rep / p_hs (the decoder's, at the window), the valid-element law of e2e_encld.bend
(ef_ProgressiveVarTestStruct), the encoder's length law (lenEW) with the list's and the bit list's own (eL), and the window's layout (9 + the list's
bytes + the bit list's bytes: e2e_hk_Attestation.bend's nkq for the progressive bit list).

Usage: python3 codegen/progressive_struct_list_element_hooks.py [--check]"""
import sys as _sys
import pathlib as _pathlib
_sys.path.insert(0, str(_pathlib.Path(__file__).resolve().parents[3]))  # the repository root: `codegen` is importable when this file runs as a script
import sys
from pathlib import Path

from codegen.proofs.decoded import variable_vector_decoded_facts as DV2

ROOT = Path(__file__).resolve().parents[3]
E2E = ROOT / 'e2e'
WIN = DV2.WIN
H31T = '+h31: {Nat.is_lt(U32.to_nat(len), VB.pw(29n)) == True{} : Bool}'
WF_SIG = DV2.WF_SIG.replace('Nat.is_lt(Nat.add(x, U32.to_nat(len)), FD.spec_common__pow2(32n))', 'Nat.is_le(Nat.add(x, U32.to_nat(len)), U32.to_nat(VB.NMAX()))') + ', ' + H31T
WF_ARG = DV2.WF_ARG + ', h31'


def text():
    imports = ['import Base', 'import ../src/obj.bend as O', 'import ../types/schema.bend as S', 'import ../proofs/obj/generic_specs.bend as Spec',
               'import ../types/ProgressiveVarTestStruct_def_generated.bend as ProgressiveVarTestStruct_d', 'import ../proofs/compact/found.bend as FD',
               'import ../proofs/compact/arith.bend as A', 'import ../proofs/nat_order.bend as Order', 'import ../proofs/obj/vbuf.bend as VB',
               'import ../proofs/obj/vbyte.bend as VY', 'import ../proofs/obj/vspec.bend as VSP', 'import ../proofs/obj/vdepth.bend as VD',
               'import ../proofs/obj/vbitcore.bend as CO', 'import ../proofs/obj/vua_ct.bend as UCT', 'import ../proofs/obj/vlist.bend as VLS',
               'import ../proofs/obj/vua_lay.bend as LY', 'import ../proofs/obj/dk.bend as DK', 'import ../proofs/obj/vfx_u8.bend as FX_u8',
               'import ../proofs/obj/root_gtypes2_light.bend as RT', 'import ../proofs/obj/var_winx_ProgressiveVarTestStruct.bend as WN',
               'import ../proofs/obj/var_winp_pbits.bend as PBW', 'import ./e2e_dpe_ProgressiveVarTestStruct.bend as DPE', 'import ./e2e_gpb.bend as GPB',
               'import ./e2e_bview.bend as BV', 'import ./e2e_bvw.bend as BVW', 'import ./e2e_encld.bend as EL', 'import ./e2e_encrd.bend as ER', 'import ./e2e_encqd.bend as EQ',
               'import ../proofs/obj/encx_pl_ProgressiveVarTestStruct.bend as XC', 'import ../proofs/obj/encx_ProgressiveVarTestStruct_iface.bend as CIG',
               'import ../proofs/obj/encx_l123_u16.bend as Xl123', 'import ../proofs/obj/encx_l123_u16_d.bend as Xl123D', 'import ../proofs/obj/encx_pbits.bend as EXP']
    PV = 'ProgressiveVarTestStruct_d.ProgressiveVarTestStruct'
    SCH = 'Spec.ProgressiveVarTestStruct()'
    OW = 'WN.OBJw(d, t, x, off, len)'
    FZ = f'RT.fz_ProgressiveVarTestStruct({OW})'
    TH = f'RT.th_ProgressiveVarTestStruct({FZ})'
    HCK = '+hchk: {WN.CHKw(t, x, off, len) == True{} : Bool}'
    DW = 'd, t, x, off, len, pfw, hd, eo, hw, hw32, h31, hchk'
    X0 = 'FX_u8.OBJ(d, t, Nat.add(x, U32.to_nat(0)))'
    CT0 = 'UCT.CT(d, t, WN.FJ0(off, t, x), WN.LJ0(t, x), VLS.DZ(WN.LJ0(t, x)))'
    CT1 = 'UCT.CT(d, t, WN.FJ1(off, t, x), WN.LJ1(t, x, len), VLS.DZ(WN.LJ1(t, x, len)))'
    NB = 'PBW.NB(t, WN.FJ1(off, t, x), WN.LJ1(t, x, len))'
    A0 = f'FD.array__thaw(U32, {CT0})'
    A1 = f'O.clear_bit(FD.array__thaw(U32, {CT1}), {NB})'
    WORDS = f'O.Words{{{A0}, WN.LJ0(t, x)}}'
    BITS = f'O.Bits{{{A1}, {NB}}}'
    o = []
    A_ = o.append
    A_('\n'.join(imports))
    A_('')
    A_('# GENERATED by progressive_struct_list_element_hooks (codegen). Do not edit.')
    A_('# The hooks of a ProgressiveVarTestStruct window as an element of the progressive lists (root_gtypes2_light mirrors): see the generator.')
    A_('')
    A_('def PA(-X: Data, -Y: Data, +p: DK.P2(X, Y)) -> X:\n  (+a, +b) = p\n  a')
    A_('')
    A_('def thfr(a: Array<U32>) -> {FD.array__thaw(U32, FD.array__freeze(U32, a)) == a : Array<U32>}:\n'
       '  match a:\n    case ALeaf{+v}: {==}\n    case ANode{l, r}:\n'
       '      %Equal.sym(Array<U32>, FD.array__thaw(U32, FD.array__freeze(U32, l)), l, thfr(l)) : {ANode{_, FD.array__thaw(U32, FD.array__freeze(U32, r))} == ANode{l, r} : Array<U32>}\n'
       '      %Equal.sym(Array<U32>, FD.array__thaw(U32, FD.array__freeze(U32, r)), r, thfr(r)) : {ANode{l, _} == ANode{l, r} : Array<U32>}\n'
       '      {==}')
    A_('')
    A_('# an element\'s frozen-and-thawed object is the object (its words and bit list are thawed storage)')
    A_(f'def thfz({WIN}) -> {{{TH} == {OW} : {PV}}}:\n'
       f'  Equal.trans({PV}, {TH}, {PV}{{{X0}, {WORDS}, O.Bits{{FD.array__thaw(U32, FD.array__freeze(U32, {A1})), {NB}}}}}, {OW},\n'
       f'    Equal.cong(Array<U32>, {PV}, z => {PV}{{{X0}, O.Words{{z, WN.LJ0(t, x)}}, O.Bits{{FD.array__thaw(U32, FD.array__freeze(U32, {A1})), {NB}}}}}, FD.array__thaw(U32, FD.array__freeze(U32, {A0})), {A0}, thfr({A0})),\n'
       f'    Equal.cong(Array<U32>, {PV}, z => {PV}{{{X0}, {WORDS}, O.Bits{{z, {NB}}}}}, FD.array__thaw(U32, FD.array__freeze(U32, {A1})), {A1}, thfr({A1})))')
    A_('')
    A_('# ---- the element at its window (the decoder\'s own lemmas, at the window) ----')
    A_(f'def el_rep_th({WIN}, {HCK}, {WF_SIG}) -> RT.rep_ProgressiveVarTestStruct({TH}, {SCH}):\n'
       f'  FD.logic__subst({PV}, z => RT.rep_ProgressiveVarTestStruct(z, {SCH}), {OW}, {TH}, Equal.sym({PV}, {TH}, {OW}, thfz(d, t, x, off, len)), DPE.p_rep({DW}))')
    A_('')
    A_(f'def el_hs_th({WIN}, {HCK}, {WF_SIG}) -> EL.EP_ProgressiveVarTestStruct({FZ}):\n'
       f'  FD.logic__subst({PV}, z => EQ.PREM_ProgressiveVarTestStruct(z), {OW}, {TH}, Equal.sym({PV}, {TH}, {OW}, thfz(d, t, x, off, len)), DPE.p_hs({DW}))')
    A_('')
    A_('# ---- the hooks ----')
    A_(f'def repT({WIN}, {HCK}, {WF_SIG}, +sE: S.Schema, +ee: {{sE == {SCH} : S.Schema}})\n'
       f'    -> RT.rep_ProgressiveVarTestStruct_bx(RT.th_ProgressiveVarTestStruct_bx(RT.MSome{{{FZ}}}), sE):\n'
       f'  ({{==}}, FD.logic__subst(S.Schema, z => RT.rep_ProgressiveVarTestStruct({TH}, z), {SCH}, sE, Equal.sym(S.Schema, sE, {SCH}, ee), el_rep_th(d, t, x, off, len, hchk, {WF_ARG})))')
    A_('')
    A_(f'def sde({WIN}, {HCK}, {WF_SIG}) -> EL.EPB_pl_ProgressiveVarTestStruct(RT.MSome{{{FZ}}}):\n  el_hs_th(d, t, x, off, len, hchk, {WF_ARG})')
    A_('')
    A_(f'def canon({WIN}, {HCK}, {WF_SIG}) -> {{RT.th_ProgressiveVarTestStruct_bx(RT.MSome{{{FZ}}}) == O.BSome{{{OW}, O.BNone{{}}}} : O.Boxed<{PV}>}}:\n'
       f'  Equal.cong({PV}, O.Boxed<{PV}>, z => O.BSome{{z, O.BNone{{}}}}, {TH}, {OW}, thfz(d, t, x, off, len))')
    A_('')
    A_('# ---- the encoder\'s bytes of the element: the window\'s ----')
    A_(f'def efv({WIN}, {HCK}, {WF_SIG}) -> EL.EF_ProgressiveVarTestStruct({FZ}):\n'
       f'  EL.ef_ProgressiveVarTestStruct({FZ}, {SCH}, el_rep_th(d, t, x, off, len, hchk, {WF_ARG}), el_hs_th(d, t, x, off, len, hchk, {WF_ARG}), {{==}})')
    A_('')
    A_(f'def okw({WIN}, {HCK}, {WF_SIG}) -> {{CIG.OKW(EL.fE_ProgressiveVarTestStruct({FZ})) == True{{}} : Bool}}:\n'
       f'  PA({{CIG.OKW(EL.fE_ProgressiveVarTestStruct({FZ})) == True{{}} : Bool}}, {{CIG.VAL(EL.fE_ProgressiveVarTestStruct({FZ})) == RT.v_ProgressiveVarTestStruct(RT.th_ProgressiveVarTestStruct({FZ})) : S.Value}}, efv(d, t, x, off, len, hchk, {WF_ARG}))')
    A_('')
    A_('def szm(+f_A: U32, +dw: Nat, +T: FD.array__Tree<U32>, +N: U32, +mb: EXP.MB, +hok: {CIG.OKW(CIG.MW{f_A, Xl123.MW{dw, T, N}, mb}) == True{} : Bool})\n'
       '    -> {List.length(&2, U32, CIG.ENC(CIG.MW{f_A, Xl123.MW{dw, T, N}, mb})) == Nat.add(Nat.add(9n, U32.to_nat(N)), LY.LN(EXP.ENC(mb))) : Nat}:\n'
       '  Equal.trans(Nat, List.length(&2, U32, CIG.ENC(CIG.MW{f_A, Xl123.MW{dw, T, N}, mb})), CIG.ENDC(f_A, Xl123.MW{dw, T, N}, mb), Nat.add(Nat.add(9n, U32.to_nat(N)), LY.LN(EXP.ENC(mb))),\n'
       '    CIG.lenEW(f_A, Xl123.MW{dw, T, N}, mb, hok),\n'
       '    Equal.cong(Nat, Nat, z => Nat.add(Nat.add(9n, z), LY.LN(EXP.ENC(mb))), LY.LN(Xl123.ENC(Xl123.MW{dw, T, N})), U32.to_nat(N), Xl123D.eL(dw, T, N, CIG.ok_hok_f_BW(f_A, Xl123.MW{dw, T, N}, mb, hok))))')
    A_('')
    A_('def szb(+f_A: U32, +m1: Xl123.MW, +dw: Nat, +T: FD.array__Tree<U32>, +K: U32, +B: Nat, +kb: Nat, +KY: Nat, +hok: {CIG.OKW(CIG.MW{f_A, m1, EXP.MB{dw, T, K, B, kb, KY}}) == True{} : Bool})\n'
       '    -> {LY.LN(EXP.ENC(EXP.MB{dw, T, K, B, kb, KY})) == U32.to_nat(CO.NK(K)) : Nat}:\n'
       '  EXP.eL(dw, T, K, B, kb, KY, CIG.ok_hok_f_CW(f_A, m1, EXP.MB{dw, T, K, B, kb, KY}, hok))')
    A_('')
    A_('def NBo(o: ' + PV + ') -> U32:\n  match o:\n    case ' + PV + '{+x0, x1, x2}:\n      match x2:\n        case O.Bits{ws, +k}: k')
    A_('')
    A_('def NWo(o: ' + PV + ') -> U32:\n  match o:\n    case ' + PV + '{+x0, x1, x2}:\n      match x1:\n        case O.Words{ws, +n}: n')
    A_('')
    MWB = 'EXP.MB{ER.LDEP(U32, TB), TB, K, U32.to_nat(K), 32n, 30n}'
    MWW = 'Xl123.MW{ER.LDEP(U32, T), T, N}'
    A_('# the encoder\'s bytes of the element with the trees of its words and bits: 9 + the list\'s bytes + the bit list\'s\n'
       f'def szo2(+x0: U32, +T: FD.array__Tree<U32>, +N: U32, +TB: FD.array__Tree<U32>, +K: U32, +hok: {{CIG.OKW(CIG.MW{{x0, {MWW}, {MWB}}}) == True{{}} : Bool}})\n'
       f'    -> {{List.length(&2, U32, CIG.ENC(CIG.MW{{x0, {MWW}, {MWB}}})) == Nat.add(Nat.add(9n, U32.to_nat(N)), U32.to_nat(CO.NK(K))) : Nat}}:\n'
       f'  Equal.trans(Nat, List.length(&2, U32, CIG.ENC(CIG.MW{{x0, {MWW}, {MWB}}})), Nat.add(Nat.add(9n, U32.to_nat(N)), LY.LN(EXP.ENC({MWB}))), Nat.add(Nat.add(9n, U32.to_nat(N)), U32.to_nat(CO.NK(K))),\n'
       f'    szm(x0, ER.LDEP(U32, T), T, N, {MWB}, hok),\n'
       f'    Equal.cong(Nat, Nat, z => Nat.add(Nat.add(9n, U32.to_nat(N)), z), LY.LN(EXP.ENC({MWB})), U32.to_nat(CO.NK(K)), szb(x0, {MWW}, ER.LDEP(U32, TB), TB, K, U32.to_nat(K), 32n, 30n, hok)))')
    A_('')
    A_(f'def szo(o: {PV}, +hok: {{CIG.OKW(EL.fE_ProgressiveVarTestStruct(RT.fz_ProgressiveVarTestStruct(o))) == True{{}} : Bool}})\n'
       f'    -> {{List.length(&2, U32, XC.YE(EL.fbx_pl_ProgressiveVarTestStruct(RT.MSome{{RT.fz_ProgressiveVarTestStruct(o)}}))) == Nat.add(Nat.add(9n, U32.to_nat(NWo(o))), U32.to_nat(CO.NK(NBo(o)))) : Nat}}:\n'
       f'  match o:\n    case {PV}{{+x0, x1, x2}}:\n      match x1:\n        case O.Words{{ws, +n}}:\n          match x2:\n            case O.Bits{{bs, +k}}: szo2(x0, FD.array__freeze(U32, ws), n, FD.array__freeze(U32, bs), k, hok)')
    A_('')
    A_('# the bit list of K = 8 m + h bits (the window of 1 + m bytes) has K / 8 + 1 = len bytes')
    A_('def nkp(+t: FD.array__Tree<U32>, +x: Nat, +off: U32, +len: U32, +hchk: {PBW.CHKw(t, x, off, len) == True{} : Bool})\n'
       '    -> {U32.to_nat(CO.NK(PBW.NB(t, off, len))) == U32.to_nat(len) : Nat}:\n'
       '  +e1 = PBW.cE(t, x, off, len, hchk)\n'
       '  +h1 = PBW.c1(t, x, off, len, hchk)\n'
       '  +nz = PBW.cB(t, off, len, h1)\n'
       '  +m = PBW.M1(len)\n'
       '  +h29 = FD.logic__subst(Bool, z => {O.bsel(z, False{}, O.bsel(True{}, U32.is_lt(U32.sub(len, 1), 536870912), Nat.is_le(PBW.BD(t, off, len), U32.to_nat(0)))) == True{} : Bool},\n'
       '    U32.is_eq(PBW.V(t, off, len), 0), False{}, nz, h1)\n'
       '  +eNB = GPB.nb(t, off, len, m, e1, h29)\n'
       '  +V = PBW.V(t, off, len)\n'
       '  +h = VY.hb(V)\n'
       '  +hh = BV.hb7(V)\n'
       '  +e3 = Equal.trans(Nat, U32.to_nat(U32.shrn(PBW.NB(t, off, len), 3n)), VD.s_rng(3n, U32.to_nat(PBW.NB(t, off, len))), m, VD.shrk(3n, PBW.NB(t, off, len)),\n'
       '    Equal.trans(Nat, VD.s_rng(3n, U32.to_nat(PBW.NB(t, off, len))), VD.s_rng(3n, Nat.add(VSP.x8(m), h)), m, Equal.cong(Nat, Nat, z => VD.s_rng(3n, z), U32.to_nat(PBW.NB(t, off, len)), Nat.add(VSP.x8(m), h), eNB), BVW.s3h(m, h, hh)))\n'
       '  +hm1 = FD.logic__subst(Nat, z => {Nat.is_le(Nat.add(m, 1n), z) == True{} : Bool}, 1n+m, U32.to_nat(len), Equal.sym(Nat, U32.to_nat(len), 1n+m, e1),\n'
       '    FD.logic__subst(Nat, z => {Nat.is_le(Nat.add(m, 1n), z) == True{} : Bool}, Nat.add(m, 1n), 1n+m, FD.nat__add_comm(m, 1n), Order.reflexive(Nat.add(m, 1n))))\n'
       '  +hm2 = FD.logic__subst(Nat, z => {Nat.is_le(Nat.add(z, U32.to_nat(1)), U32.to_nat(len)) == True{} : Bool}, m, U32.to_nat(U32.shrn(PBW.NB(t, off, len), 3n)), Equal.sym(Nat, U32.to_nat(U32.shrn(PBW.NB(t, off, len), 3n)), m, e3), hm1)\n'
       '  Equal.trans(Nat, U32.to_nat(CO.NK(PBW.NB(t, off, len))), Nat.add(U32.to_nat(U32.shrn(PBW.NB(t, off, len), 3n)), U32.to_nat(1)), U32.to_nat(len), A.add_le(U32.shrn(PBW.NB(t, off, len), 3n), 1, len, hm2),\n'
       '    Equal.trans(Nat, Nat.add(U32.to_nat(U32.shrn(PBW.NB(t, off, len), 3n)), U32.to_nat(1)), Nat.add(m, 1n), U32.to_nat(len), Equal.cong(Nat, Nat, z => Nat.add(z, 1n), U32.to_nat(U32.shrn(PBW.NB(t, off, len), 3n)), m, e3),\n'
       '      Equal.trans(Nat, Nat.add(m, 1n), 1n+m, U32.to_nat(len), FD.nat__add_comm(m, 1n), Equal.sym(Nat, U32.to_nat(len), 1n+m, e1))))')
    A_('')
    A_('# the window\'s layout: 9 + the list\'s bytes + the bit list\'s bytes')
    A_(f'def ln9({WIN}, {HCK})\n'
       f'    -> {{Nat.add(Nat.add(9n, U32.to_nat(WN.LJ0(t, x))), U32.to_nat(WN.LJ1(t, x, len))) == U32.to_nat(len) : Nat}}:\n'
       f'  +e0 = WN.eO0(t, x, off, len, hchk)\n'
       f'  +e1 = WN.eE0(t, x, off, len, hchk)\n'
       f'  +e2 = WN.eE1(t, x, off, len, hchk)\n'
       f'  Equal.trans(Nat, Nat.add(Nat.add(9n, U32.to_nat(WN.LJ0(t, x))), U32.to_nat(WN.LJ1(t, x, len))), Nat.add(U32.to_nat(WN.O1(t, x)), U32.to_nat(WN.LJ1(t, x, len))), U32.to_nat(len),\n'
       f'    Equal.cong(Nat, Nat, z => Nat.add(z, U32.to_nat(WN.LJ1(t, x, len))), Nat.add(9n, U32.to_nat(WN.LJ0(t, x))), U32.to_nat(WN.O1(t, x)),\n'
       f'      Equal.sym(Nat, U32.to_nat(WN.O1(t, x)), Nat.add(9n, U32.to_nat(WN.LJ0(t, x))), Equal.trans(Nat, U32.to_nat(WN.O1(t, x)), Nat.add(U32.to_nat(WN.O0(t, x)), U32.to_nat(WN.LJ0(t, x))), Nat.add(9n, U32.to_nat(WN.LJ0(t, x))), e1,\n'
       f'        Equal.cong(Nat, Nat, z => Nat.add(z, U32.to_nat(WN.LJ0(t, x))), U32.to_nat(WN.O0(t, x)), 9n, e0)))),\n'
       f'    Equal.sym(Nat, U32.to_nat(len), Nat.add(U32.to_nat(WN.O1(t, x)), U32.to_nat(WN.LJ1(t, x, len))), e2))')
    A_('')
    A_(f'def sz({WIN}, {HCK}, {WF_SIG})\n    -> {{List.length(&2, U32, XC.YE(EL.fbx_pl_ProgressiveVarTestStruct(RT.MSome{{{FZ}}}))) == U32.to_nat(len) : Nat}}:\n'
       f'  Equal.trans(Nat, List.length(&2, U32, XC.YE(EL.fbx_pl_ProgressiveVarTestStruct(RT.MSome{{{FZ}}}))), Nat.add(Nat.add(9n, U32.to_nat(WN.LJ0(t, x))), U32.to_nat(WN.LJ1(t, x, len))), U32.to_nat(len),\n'
       f'    Equal.trans(Nat, List.length(&2, U32, XC.YE(EL.fbx_pl_ProgressiveVarTestStruct(RT.MSome{{{FZ}}}))), Nat.add(Nat.add(9n, U32.to_nat(NWo({OW}))), U32.to_nat(CO.NK(NBo({OW})))), Nat.add(Nat.add(9n, U32.to_nat(WN.LJ0(t, x))), U32.to_nat(WN.LJ1(t, x, len))),\n'
       f'      szo({OW}, okw(d, t, x, off, len, hchk, {WF_ARG})),\n'
       f'      Equal.cong(Nat, Nat, z => Nat.add(Nat.add(9n, U32.to_nat(WN.LJ0(t, x))), z), U32.to_nat(CO.NK({NB})), U32.to_nat(WN.LJ1(t, x, len)), nkp(t, WN.XJ1(t, x), WN.FJ1(off, t, x), WN.LJ1(t, x, len), WN.itD1(t, x, off, len, hchk)))),\n'
       f'    ln9(d, t, x, off, len, hchk))')
    return '\n'.join(o) + '\n'


def main():
    p = E2E / 'e2e_hkp.bend'
    t = text()
    if '--check' in sys.argv:
        if not p.exists() or p.read_text() != t:
            print('stale: ' + p.name)
            sys.exit(1)
        print('progressive_struct_list_element_hooks: up to date')
        return
    if not p.exists() or p.read_text() != t:
        p.write_text(t)
    print('progressive_struct_list_element_hooks: 1 file')


if __name__ == '__main__':
    main()
