#!/usr/bin/env python3
"""Crash hunt round 5 (a): TWIN lists of boxed elements for the kinds without a cache (progressive lists, the vector of VarTestStruct).
L1 and L2 get the same appends / sets; L1 additionally gets a take(i) right before each set(i) (L2 does not), and both are rooted after
every step (the root of a list returns the list: an element lost by the root would show). Roots must agree at every step, and the final
serializations too. Prints `bad=<steps whose roots differ> first=<first> ser_eq=<final bytes equal> valid=<L1 valid at the end>`.

    python3 tools/crash_hunt/r5/gen_twin.py      (writes tools/crash_hunt/r5/twin/tw_<id>.bend)"""
import os
HERE = os.path.dirname(os.path.abspath(__file__))
VT = ('import ../../../../types/VarTestStruct_def_generated.bend as Ev',
      'Ev.VarTestStruct_set_f_B(fa(Ev.VarTestStruct_set_f_A(Ev.VarTestStruct_default(), (x .&. 65535 : U32))), O.Words{Array.new(U32, 2n, x), (4 * U32.mod(x, 4) : U32)})',
      'Ev.VarTestStruct')
KINDS = {
 'proglist_VarTestStruct': dict(P='pl_VarTestStruct', E=VT[2], imp=VT[0], mk=VT[1], fa='Ev.VarTestStruct', APP=1),
 'proglist_ProgressiveVarTestStruct': dict(P='pl_ProgressiveVarTestStruct', E='Ev.ProgressiveVarTestStruct',
     imp='import ../../../../types/ProgressiveVarTestStruct_def_generated.bend as Ev', fa='Ev.ProgressiveVarTestStruct', APP=1,
     mk='Ev.ProgressiveVarTestStruct_set_f_B(fa(Ev.ProgressiveVarTestStruct_set_f_A(Ev.ProgressiveVarTestStruct_default(), (x .&. 255 : U32))), O.Words{Array.new(U32, 2n, x), (4 * U32.mod(x, 4) : U32)})'),
 'proglist_proglist_VarTestStruct': dict(P='pl_pl_VarTestStruct', E='Pv.pl_VarTestStruct_Seq', fa='Ev.VarTestStruct', APP=1,
     imp=VT[0] + '\nimport ../../../../types/proglist_VarTestStruct_def_generated.bend as Pv',
     mk='ia(Pv.pl_VarTestStruct_append(Pv.pl_VarTestStruct_default(), ' + VT[1] + '))'),
 'vec_VarTestStruct_2': dict(P='v2_VarTestStruct', E=VT[2], imp=VT[0], mk=VT[1], fa='Ev.VarTestStruct', APP=0),
}
PROG = '''import Base
import ../../../../src/buffer.bend as B
import ../../../../src/digest.bend as D
import ../../../../src/obj.bend as O
import ../../../../types/%(F)s_def_generated.bend as L
import ../../../../types/%(F)s_hashtreeroot_generated.bend as LH
import ../../../../types/%(F)s_encode_ssz_generated.bend as LE
%(imp)s
import ../../../../benchmarks/compact/objio.bend as IOx

# GENERATED by tools/crash_hunt/r5/gen_twin.py: twin %(F)s lists, one with a take before every set

def nx(+x: U32) -> U32: (x * 1664525 + 1013904223 : U32)

def fa(pair: %(fa)s & Bool) -> %(fa)s:
  (o, ok) = pair
  o

def ia(pair: Pv.pl_VarTestStruct_Seq & Bool) -> Pv.pl_VarTestStruct_Seq:
  (o, ok) = pair
  o

def mk(+x: U32) -> %(E)s: %(mk)s

type S is Type:
  S{a: L.%(P)s_Seq, b: L.%(P)s_Seq, x: U32, bad: U32, first: U32, j: U32}

def deqv(+a: D.Digest, +b: D.Digest) -> U32:
  match a b:
    case D.D{+a0, +a1, +a2, +a3, +a4, +a5, +a6, +a7} D.D{+b0, +b1, +b2, +b3, +b4, +b5, +b6, +b7}:
      O.pick(Bool.and(Bool.and(Bool.and(U32.is_eq(a0, b0), U32.is_eq(a1, b1)), Bool.and(U32.is_eq(a2, b2), U32.is_eq(a3, b3))),
               Bool.and(Bool.and(U32.is_eq(a4, b4), U32.is_eq(a5, b5)), Bool.and(U32.is_eq(a6, b6), U32.is_eq(a7, b7)))), 1, 0)

def eqb(a: Bool, b: Bool) -> U32:
  match a:
    case True{}: O.pick(b, 1, 0)
    case False{}: O.pick(b, 0, 1)

def mark(a: L.%(P)s_Seq, b: L.%(P)s_Seq, +x: U32, +bad: U32, +first: U32, +j: U32, +ok: U32) -> S:
  S{a, b, x, O.pick(U32.is_eq(ok, 1), bad, (bad + 1 : U32)), O.pick(Bool.and(U32.is_eq(ok, 0), U32.is_eq(first, 4294967295)), j, first), (j + 1 : U32)}

def rc2(+x: U32, +bad: U32, +first: U32, +j: U32, +okf: U32, pa: B.Buf & (L.%(P)s_Seq & D.Digest), pb: B.Buf & (L.%(P)s_Seq & D.Digest)) -> S:
  (h1, r1) = pa
  (a, d1) = r1
  (h2, r2) = pb
  (b, d2) = r2
  mark(a, b, x, bad, first, j, (okf .&. deqv(d1, d2) : U32))

def rootcmp(a: L.%(P)s_Seq, b: L.%(P)s_Seq, +x: U32, +bad: U32, +first: U32, +j: U32, +okf: U32) -> S:
  rc2(x, bad, first, j, okf, LH.%(P)s_root(64n, O.hasher(), a, 0), LH.%(P)s_root(64n, O.hasher(), b, 0))

def flagf(+x: U32, +bad: U32, +first: U32, +j: U32, pa: L.%(P)s_Seq & Bool, pb: L.%(P)s_Seq & Bool) -> S:
  (a, p) = pa
  (b, q) = pb
  rootcmp(a, b, x, bad, first, j, eqb(p, q))

def dropm(pair: L.%(P)s_Seq & Maybe<&1, %(E)s>) -> L.%(P)s_Seq:
  (a, m) = pair
  a

def app(+x: U32, +bad: U32, +first: U32, +j: U32, a: L.%(P)s_Seq, b: L.%(P)s_Seq) -> S:
  %(APPBODY)s

def dispatch(+op: U32, +i: U32, a: L.%(P)s_Seq, b: L.%(P)s_Seq, +x: U32, +bad: U32, +first: U32, +j: U32) -> S:
  match op:
    case 0: app(x, bad, first, j, a, b)
    case 1: app(x, bad, first, j, a, b)
    case 2: flagf(x, bad, first, j, L.%(P)s_set(dropm(L.%(P)s_take(a, i)), i, mk(x)), L.%(P)s_set(b, i, mk(x)))
    case 3: flagf(x, bad, first, j, L.%(P)s_set(a, i, mk(x)), L.%(P)s_set(b, i, mk(x)))
    case _: rootcmp(a, b, x, bad, first, j, 1)

def stp(s: S) -> S:
  match s:
    case S{a, b, +x, +bad, +first, +j}: dispatch(U32.mod(U32.shrn(x, 16n), 5), U32.mod(U32.shrn(x, 8n), 12), a, b, nx(x), bad, first, j)

def run(k: Nat, s: S) -> S:
  match k:
    case 0n: s
    case 1n+q: run(q, stp(s))

def ser_b(e: O.Encoded) -> B.Buf:
  match e:
    case O.Encoded{ok, b}: b
def ser_of(pair: L.%(P)s_Seq & O.Encoded) -> B.Buf:
  (o, e) = pair
  ser_b(e)
def beq(pa: B.Buf & U32, pb: B.Buf & U32) -> U32:
  (a, +x) = pa
  (b, +y) = pb
  O.pick(U32.is_eq(x, y), 1, 0)
def vflag(pair: L.%(P)s_Seq & Bool) -> String:
  (o, ok) = pair
  O.pick_str(ok)
def fin(s: S) -> IO(Unit):
  match s:
    case S{a, b, +x, +bad, +first, +j}: IO.print("bad=" ++ U32.show(bad) ++ " first=" ++ U32.show(first) ++ " valid_a=" ++ vflag(LE.%(P)s_valid(a)) ++ " valid_b=" ++ vflag(LE.%(P)s_valid(b)))

def main() -> IO(Unit):
  do IO<Unit>:
    +steps : U32 <- IOx.env_u32("SSZ_STEPS")
    +seed : U32 <- IOx.env_u32("SSZ_SEED")
    fin(run(U32.to_nat(steps), S{L.%(P)s_default(), L.%(P)s_default(), nx(seed), 0, 4294967295, 0}))
'''
APP1 = 'flagf(x, bad, first, j, L.%(P)s_append(a, mk(x)), L.%(P)s_append(b, mk(x)))'
APP0 = 'rootcmp(a, b, x, bad, first, j, 1)'
def main():
    od = os.path.join(HERE, 'twin'); os.makedirs(od, exist_ok=True)
    for f, k in KINDS.items():
        body = (APP1 if k['APP'] else APP0) % k
        src = PROG % dict(F=f, APPBODY=body, **k)
        if 'Pv.' not in k['E'] and 'Pv.' not in k['mk']:
            src = src.replace('def ia(pair: Pv.pl_VarTestStruct_Seq & Bool) -> Pv.pl_VarTestStruct_Seq:\n  (o, ok) = pair\n  o\n\n', '')
        open(os.path.join(od, 'tw_%s.bend' % f), 'w').write(src)
    print('generated', len(KINDS))
if __name__ == '__main__':
    main()
