#!/bin/bash
# tools/check_fast.sh [--jobs N] [--target S] [--out DIR] [--files LIST] [--no-localize]: the full
# check. Checks every .bend file outside tools/ and vendor/ (or those in LIST, with their imports)
# through umbrellas: files that only import a group of root files, so one Bend run checks each
# module of the group's closure once instead of once per importing file (tools/umbrellas.py
# explains the soundness argument). Same pinned checker and cgroup limits as tools/check.sh, but
# each umbrella gets a larger heap: UMB_MEMMAX (default 16G), UMB_RAM (JSC forceRAMSize, default
# 12e9; the 8e9 of single files makes a big umbrella collect constantly), UMB_TIMEOUT (default
# 1200 s).
#
# Failures are localized: each failed umbrella is bisected into sub-umbrellas (still import-only,
# so every file is checked exactly as in the full run) until single roots remain, and the failing
# root files are printed with the definition the checker names. Writes DIR/<n>.log,
# DIR/summary.tsv (umbrella, exit, ok, seconds, peak MB, roots), DIR/bisect/*.log and
# DIR/failed.tsv (root file, log, first Location line), and DIR/stamp.json (tools/check_stamp.py:
# commit, checker, lock, source, harness and plan hashes, per-umbrella results, totals); a full run
# (no --files) also copies the stamp to benchmarks/evidence/check_fast.json. Exits nonzero if any
# umbrella fails, or if any planned umbrella has no result row (its run died without a verdict).
# First, tools/verify_pins.py checks the toolchain and the SHA-256 package against
# toolchain.lock.json, tools/verify_frozen.py the frozen statements against frozen.lock.json, and
# tools/verify_no_escapes.py bans @unsafe / def f?( / foreign bodies, and tools/verify_schemas.py
# cross-checks fulu_mainnet.py, the JSON, spec/fulu_schemas.bend and the generic schemas (exit 3 on any failure).
# Run from the repository root.
set -u
J=20; T=120; OUT=build/check_fast; FILES=""; LOC=1
while [ $# -gt 0 ]; do
  case $1 in
    --jobs) J=$2; shift 2;;
    --target) T=$2; shift 2;;
    --out) OUT=$2; shift 2;;
    --files) FILES=$2; shift 2;;
    --no-localize) LOC=0; shift;;
    *) echo "usage: tools/check_fast.sh [--jobs N] [--target S] [--out DIR] [--files LIST] [--no-localize]" >&2; exit 2;;
  esac
done
t0=$(date +%s)
rm -rf "$OUT"; mkdir -p "$OUT/bisect"; : > "$OUT/summary.tsv"; : > "$OUT/failed.tsv"
T0=${BEND_TOOLCHAIN:-/srv/ssz-optimization/toolchain-2.0.28}
python3 tools/verify_pins.py --lock "${BEND_LOCK:-toolchain.lock.json}" --toolchain "$T0" --lib "${BEND_LIB:-vendor/bendhub}" || exit 3
python3 tools/verify_frozen.py || exit 3
python3 tools/verify_no_escapes.py || exit 3
python3 tools/verify_schemas.py || exit 3
export CHECK_PINS_VERIFIED=1
python3 tools/umbrellas.py --target "$T" --out "$OUT/umb" ${FILES:+--files "$FILES"} || exit 2

# run(umbrella file, log): check one umbrella; 0 iff it exits 0 and prints exactly the line
# "ALL PROOFS CHECK" (Bend 2.0.34; "All terms check." on 2.0.28, not "All terms check, but N defs
# rely on unsafe or foreign code") (else the checker's exit code, or 1)
run() {
  CHECK_MEMMAX=${UMB_MEMMAX:-16G} CHECK_TIMEOUT=${UMB_TIMEOUT:-1200} \
    BUN_JSC_forceRAMSize=${UMB_RAM:-12000000000} tools/check.sh "$1" > "$2" 2>&1
  local rc=$?; [ $rc != 0 ] && return $rc
  grep -qx -e 'ALL PROOFS CHECK' -e 'All terms check\.' "$2" || return 1
}
one() {
  u=$1; out=$2
  lg=$out/${u%.bend}.log
  run "$out/umb/$u" "$lg"; rc=$?
  ok=$(grep -cx -e 'ALL PROOFS CHECK' -e 'All terms check\.' "$lg")
  tl=$(grep '^CHECK_TIME' "$lg" | tail -n 1)
  s=$(echo "$tl" | awk '{print $2}'); kb=$(echo "$tl" | awk '{print $3}')
  roots=$(awk -F'\t' -v u="$u" '$1 == u {print $4}' "$out/umb/plan.tsv")
  printf '%s\t%s\t%s\t%s\t%s\t%s\n' "$u" "$rc" "$ok" "${s:-0}" "$(( ${kb:-0} / 1024 ))" "$roots" >> "$out/summary.tsv"
}
# umb(file, roots...): write an import-only umbrella over these roots
umb() {
  local f=$1 i=0 r; shift
  { echo '# generated by tools/check_fast.sh: part of a failed umbrella, bisected'; echo 'import Base'
    for r in "$@"; do echo "import $UP/$r as U$i"; i=$((i+1)); done; } > "$f"
}
# bisect(tag, log, roots...): the umbrella over these roots failed with this log; split it in
# halves, check both (in parallel), recurse into the failing ones. A single failing root, or a
# group whose halves both pass, is recorded in failed.tsv.
bisect() {
  local tag=$1 lg=$2 loc h pa pb ra rb; shift 2
  loc=$(grep -m1 -A1 '^Location' "$lg" | tr '\n' ' ' | sed 's/  */ /g')
  if [ $# -eq 1 ]; then
    printf '%s\t%s\t%s\n' "$1" "$lg" "$loc" >> "$OUT/failed.tsv"; return
  fi
  h=$(( $# / 2 ))
  local a=("${@:1:h}") b=("${@:h+1}")
  umb "$OUT/umb/bis_${tag}a.bend" "${a[@]}"; umb "$OUT/umb/bis_${tag}b.bend" "${b[@]}"
  run "$OUT/umb/bis_${tag}a.bend" "$OUT/bisect/${tag}a.log" & pa=$!
  run "$OUT/umb/bis_${tag}b.bend" "$OUT/bisect/${tag}b.log" & pb=$!
  wait $pa; ra=$?; wait $pb; rb=$?
  [ $ra != 0 ] && bisect "${tag}a" "$OUT/bisect/${tag}a.log" "${a[@]}"
  [ $rb != 0 ] && bisect "${tag}b" "$OUT/bisect/${tag}b.log" "${b[@]}"
  if [ $ra = 0 ] && [ $rb = 0 ]; then
    printf '%s\t%s\t%s\n' "$*" "$lg" "(fails only together) $loc" >> "$OUT/failed.tsv"
  fi
}
localize() {
  local u=$1 rs
  read -r -a rs <<< "$(awk -F'\t' -v u="$u" '$1 == u {print $4}' "$OUT/umb/plan.tsv")"
  bisect "${u%.bend}_" "$OUT/${u%.bend}.log" "${rs[@]}"
}
UP=$(python3 -c 'import os, sys; print(os.path.relpath(".", sys.argv[1]))' "$OUT/umb")
export OUT UP
export -f run one umb bisect localize
cut -f1 "$OUT/umb/plan.tsv" | xargs -P "$J" -I{} bash -c 'one "$@"' _ {} "$OUT"
n=$(wc -l < "$OUT/summary.tsv")
echo "checked $n umbrellas in $(( $(date +%s) - t0 )) s; slowest:"
sort -t$'\t' -k4 -g -r "$OUT/summary.tsv" | head -n 5 | awk -F'\t' '{printf "  %7.1f s %6d MB  %s  %.60s\n", $4, $5, $1, $6}'
CHECK_FAST_FILES=$FILES python3 tools/check_stamp.py write "$OUT" "$OUT/stamp.json"; stamp_rc=$?
# a full run records its stamp in the tree: benchmarks/evidence/check_fast.json
[ -z "$FILES" ] && cp "$OUT/stamp.json" benchmarks/evidence/check_fast.json
bad=$(awk -F'\t' '$2 != 0 || $3 == 0 {print $1}' "$OUT/summary.tsv")
# every planned umbrella must have exactly one result row: one whose run died before writing it
# (killed, out of memory in the shell, ...) fails the check instead of silently vanishing
missing=$(cut -f1 "$OUT/umb/plan.tsv" | sort | comm -23 - <(cut -f1 "$OUT/summary.tsv" | sort))
[ $stamp_rc != 0 ] && [ -z "$missing" ] && { echo "FAILED: the stamp's plan/summary comparison failed"; exit 1; }
if [ -n "$missing" ]; then
  echo "FAILED: planned umbrellas with no result row (their run died without a verdict):"
  for u in $missing; do echo "  $u  $OUT/${u%.bend}.log"; done
  exit 1
fi
if [ -z "$bad" ]; then
  [ -z "$FILES" ] && echo "all files check (stamp: $OUT/stamp.json, benchmarks/evidence/check_fast.json)" \
    || echo "listed files check (stamp: $OUT/stamp.json)"
  exit 0
fi
echo "FAILED umbrellas:"
for u in $bad; do echo "  $OUT/${u%.bend}.log"; grep -m1 -A1 '^Location' "$OUT/${u%.bend}.log" | sed 's/^/    /'; done
if [ $LOC = 1 ]; then
  echo "localizing (bisecting each failed umbrella's roots)..."
  echo "$bad" | xargs -P $(( J > 1 ? J / 2 : 1 )) -I{} bash -c 'localize "$@"' _ {}
  echo "FAILED root files (root, log, location) after $(( $(date +%s) - t0 )) s:"
  sort "$OUT/failed.tsv" | awk -F'\t' '{printf "  %s\n    %s\n    %s\n", $1, $2, $3}'
fi
exit 1
