#!/usr/bin/env python3
"""Generate proofs/compact/bits_generated.bend: bit-level facts about the byte readers
of src/buffer.bend (`byte_sel`, `join_sel`).

Base's U32 operations are defined bit by bit (Word.and / Word.or / shifts), and
`Bool.and` / `Bool.or` reduce only on their first argument, so on a word of
symbolic bits a mask or a shift leaves terms such as `Bool.and(x, True{})`
stuck. Each lemma here therefore (1) states the reader applied to a word of 32
symbolic bits, (2) lists the stuck normal form of every result bit, obtained
by simulating Base's reduction rules in this script, and (3) discharges each bit
with a two-case cleanup lemma. The simulation only chooses which cleanup lemma
to cite; Bend re-checks every statement, so a wrong simulation fails the check.

    python3 tools/generate_compact_bits.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'proofs/compact/bits_generated.bend'
F, T = 'False{}', 'True{}'


def band(a, b):
    if a == F:
        return F
    if a == T:
        return b
    return f'Bool.and({a}, {b})'


def bor(a, b):
    if a == F:
        return b
    if a == T:
        return T
    return f'Bool.or({a}, {b})'


def lit(n):
    return [T if (n >> i) & 1 else F for i in range(32)]


def wand(a, b):
    return [band(x, y) for x, y in zip(a, b)]


def wor(a, b):
    return [bor(x, y) for x, y in zip(a, b)]


def shr(w, k):
    return w[k:] + [F] * k


def shl(w, k):
    return [F] * k + w[:32 - k]


def byte_sel(k, w):
    if k == 0:
        return wand(w, lit(255))
    if k == 3:
        return shr(w, 24)
    return wand(shr(w, 8 * k), lit(255))


def join_sel(j, lo, hi):
    return wor(shr(lo, 8 * j), shl(hi, 32 - 8 * j))


def clean(x):
    """(clean bit, proof of {x == clean})"""
    if x in (F, T) or x.isidentifier():
        return x, '{==}'
    for pat, target, lemma in [
        ('Bool.and({v}, True{{}})', '{v}', 'and_true'),
        ('Bool.and({v}, False{{}})', 'False{{}}', 'and_false'),
        ('Bool.or({v}, False{{}})', '{v}', 'or_false'),
        ('Bool.and(Bool.or({v}, False{{}}), True{{}})', '{v}', 'or_and_true'),
        ('Bool.and(Bool.or({v}, False{{}}), False{{}})', 'False{{}}', 'or_and_false'),
    ]:
        # match with a single identifier v
        head, tail = pat.split('{v}')
        head, tail = head.replace('{{', '{').replace('}}', '}'), tail.replace('{{', '{').replace('}}', '}')
        if x.startswith(head) and x.endswith(tail):
            v = x[len(head):len(x) - len(tail)]
            if v.isidentifier():
                return target.replace('{{', '{').replace('}}', '}').replace('{v}', v), f'{lemma}({v})'
    raise SystemExit('no cleanup for ' + x)


def word(bits):
    s = 'WNil{}'
    for b in reversed(bits):
        s = f'WCon{{{b}, {s}}}'
    return s


def u32(bits):
    return f'U32{{{word(bits)}}}'


def pattern(names):
    return word(names)


def eq_proof(xs):
    ys, ps = zip(*[clean(x) for x in xs])
    return list(ys), f'word32_eq({", ".join(xs)}, {", ".join(ys)}, {", ".join(ps)})'


def main():
    a = [f'a{i}' for i in range(32)]
    b = [f'b{i}' for i in range(32)]
    out = ['import Base', '',
           '# GENERATED by tools/generate_compact_bits.py - do not edit.',
           '# Bit-level facts about the byte readers of src/buffer.bend.',
           'import ../../src/buffer.bend as B',
           'import ../power_division.bend as D',
           'import ../byte_arithmetic.bend as A',
           'import ../integer_decoding.bend as ID', '']
    out += ['''def and_true(+x: Bool) -> {Bool.and(x, True{}) == x : Bool}:
  match x:
    case False{}: {==}
    case True{}: {==}

def and_false(+x: Bool) -> {Bool.and(x, False{}) == False{} : Bool}:
  match x:
    case False{}: {==}
    case True{}: {==}

def or_false(+x: Bool) -> {Bool.or(x, False{}) == x : Bool}:
  match x:
    case False{}: {==}
    case True{}: {==}

def or_and_true(+x: Bool) -> {Bool.and(Bool.or(x, False{}), True{}) == x : Bool}:
  match x:
    case False{}: {==}
    case True{}: {==}

def or_and_false(+x: Bool) -> {Bool.and(Bool.or(x, False{}), False{}) == False{} : Bool}:
  match x:
    case False{}: {==}
    case True{}: {==}
''']
    xs = [f'x{i}' for i in range(32)]
    ys = [f'y{i}' for i in range(32)]
    es = [f'e{i}' for i in range(32)]
    params = ', '.join([f'+{v}: Bool' for v in xs + ys] + [f'+e{i}: {{x{i} == y{i} : Bool}}' for i in range(32)])
    out.append(f'# Bitwise congruence of U32 words.\ndef word32_eq({params}) -> {{{u32(xs)} == {u32(ys)} : U32}}:')
    for i in range(32):
        cur = ys[:i] + ['_'] + xs[i + 1:]
        out.append(f'  %Equal.sym(Bool, x{i}, y{i}, e{i}) : {{{u32(cur)} == {u32(ys)} : U32}}')
    out.append('  {==}\n')

    # byte_sel k of a symbolic word
    for k in range(4):
        xs = byte_sel(k, a)
        ys, proof = eq_proof(xs)
        want = a[8 * k:8 * k + 8] + [F] * 24
        assert ys == want, (k, ys)
        params = ', '.join(f'+{v}: Bool' for v in a)
        out.append(f'# Byte {k} of a word is its bits {8 * k}..{8 * k + 7}, zero-extended.')
        out.append(f'def sel{k}({params}) -> {{B.byte_sel({k}, {u32(a)}) == {u32(want)} : U32}}:')
        out.append(f'  {proof}\n')

    # join_sel j of two symbolic words: bytes j..3 of lo, then bytes 0..j-1 of hi
    for j in (1, 2, 3):
        xs = join_sel(j, a, b)
        ys, proof = eq_proof(xs)
        want = a[8 * j:] + b[:8 * j]
        assert ys == want, (j, ys)
        params = ', '.join(f'+{v}: Bool' for v in a + b)
        out.append(f'# An unaligned read at offset {j} inside a word joins bytes {j}..3 of it with bytes 0..{j - 1} of the next.')
        out.append(f'def join{j}({params}) -> {{B.join_sel({j}, {u32(a)}, {u32(b)}) == {u32(want)} : U32}}:')
        out.append(f'  {proof}\n')

    # The spec's little-endian assembly of four bytes (spec/primitives.bend
    # limb_value on a four-byte list computes to exactly this).
    out.append('''# The spec's uint32 assembly of four bytes: S.limb_value([a, b, c, d], 0n)
# computes to exactly this term.
def asm(+a: U32, +b: U32, +c: U32, +d: U32) -> U32:
  U32.add(a, U32.add(U32.mul(256, b), U32.add(U32.mul(65536, c), U32.mul(16777216, d))))

def asm_cong(+a: U32, +b: U32, +c: U32, +d: U32, +a2: U32, +b2: U32, +c2: U32, +d2: U32,
    +ea: {a == a2 : U32}, +eb: {b == b2 : U32}, +ec: {c == c2 : U32}, +ed: {d == d2 : U32})
    -> {asm(a, b, c, d) == asm(a2, b2, c2, d2) : U32}:
  %Equal.sym(U32, a, a2, ea) : {asm(_, b, c, d) == asm(a2, b2, c2, d2) : U32}
  %Equal.sym(U32, b, b2, eb) : {asm(a2, _, c, d) == asm(a2, b2, c2, d2) : U32}
  %Equal.sym(U32, c, c2, ec) : {asm(a2, b2, _, d) == asm(a2, b2, c2, d2) : U32}
  %Equal.sym(U32, d, d2, ed) : {asm(a2, b2, c2, _) == asm(a2, b2, c2, d2) : U32}
  {==}
''')

    def w8(bits):
        return word(bits)

    def embed(bits):
        return u32(bits + [F] * 24)

    def assembled(bits32):
        # {U32{bits32} == asm(embed8 of its four bytes)} from pack_or4 / assembly_bytes
        q = [w8(bits32[8 * k:8 * k + 8]) for k in range(4)]
        orasm = (f'U32.or(D.embed8({q[0]}), U32.or(U32.shln(D.embed8({q[1]}), 8n), '
                 f'U32.or(U32.shln(D.embed8({q[2]}), 16n), U32.shln(D.embed8({q[3]}), 24n))))')
        addasm = f'asm({", ".join(embed(bits32[8 * k:8 * k + 8]) for k in range(4))})'
        return (f'Equal.trans(U32, {u32(bits32)}, {orasm}, {addasm}, '
                f'Equal.sym(U32, {orasm}, {u32(bits32)}, A.pack_or4({", ".join(q)})), '
                f'ID.assembly_bytes({", ".join(q)}))'), addasm

    # A word is the assembly of its four bytes.
    params = ', '.join(f'+{v}: Bool' for v in a)
    wa = u32(a)
    sels = [f'B.byte_sel({k}, {wa})' for k in range(4)]
    proof, addasm = assembled(a)
    out.append('# A word is the spec assembly of its own four bytes.')
    out.append(f'def reassemble_bits({params}) -> {{{wa} == asm({", ".join(sels)}) : U32}}:')
    out.append(f'  Equal.trans(U32, {wa}, {addasm}, asm({", ".join(sels)}), {proof},')
    out.append(f'    Equal.sym(U32, asm({", ".join(sels)}), {addasm}, asm_cong({", ".join(sels)}, '
               f'{", ".join(embed(a[8 * k:8 * k + 8]) for k in range(4))}, '
               f'{", ".join(f"sel{k}({chr(44).join(a)})" for k in range(4))})))\n')
    out.append('''def reassemble(+w: U32) -> {w == asm(B.byte_sel(0, w), B.byte_sel(1, w), B.byte_sel(2, w), B.byte_sel(3, w)) : U32}:
  match w:
    case U32{''' + word(a) + '''}: reassemble_bits(''' + ', '.join(a) + ''')
''')

    # An unaligned join is the assembly of bytes j..3 of lo and 0..j-1 of hi.
    for j in (1, 2, 3):
        params = ', '.join(f'+{v}: Bool' for v in a + b)
        lo, hi = u32(a), u32(b)
        joined = a[8 * j:] + b[:8 * j]
        srcs = [(lo, k) for k in range(j, 4)] + [(hi, k) for k in range(0, j)]
        sels = [f'B.byte_sel({k}, {w})' for w, k in srcs]
        sel_proofs = [f'sel{k}({", ".join(a if w == lo else b)})' for w, k in srcs]
        proof, addasm = assembled(joined)
        out.append(f'def join_asm{j}_bits({params}) -> {{B.join_sel({j}, {lo}, {hi}) == asm({", ".join(sels)}) : U32}}:')
        out.append(f'  Equal.trans(U32, B.join_sel({j}, {lo}, {hi}), {u32(joined)}, asm({", ".join(sels)}), join{j}({", ".join(a + b)}),')
        out.append(f'    Equal.trans(U32, {u32(joined)}, {addasm}, asm({", ".join(sels)}), {proof},')
        out.append(f'      Equal.sym(U32, asm({", ".join(sels)}), {addasm}, asm_cong({", ".join(sels)}, '
                   f'{", ".join(embed(joined[8 * k:8 * k + 8]) for k in range(4))}, {", ".join(sel_proofs)}))))\n')
        sels_w = [f'B.byte_sel({k}, {"lo" if w == lo else "hi"})' for w, k in srcs]
        out.append(f'''def join_asm{j}(+lo: U32, +hi: U32) -> {{B.join_sel({j}, lo, hi) == asm({", ".join(sels_w)}) : U32}}:
  match lo hi:
    case U32{{{word(a)}}} U32{{{word(b)}}}: join_asm{j}_bits({", ".join(a + b)})
''')

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text('\n'.join(out) + '\n')
    print(OUT.relative_to(ROOT), len(out), 'lines')


if __name__ == '__main__':
    main()
