"""Generate proofs/decode_inverse.bend.

Enumerates Schema/Value representation constructors only, because the Bend
checker needs concrete constructors to reduce the independent encoder, the
actual decoder and the actual validator. No protocol inputs, test values or
fixture data are enumerated.
"""
from pathlib import Path

SCHEMAS = [("Boolean", 0), ("Unsigned", 1), ("ByteVector", 1), ("ByteList", 1), ("BitVector", 1), ("BitList", 1),
           ("Vector", 2), ("ListOf", 2), ("Container", 2), ("Union", 1), ("Null", 0), ("Chain", 2), ("End", 0),
           ("Repeat", 1), ("Named", 2), ("ProgressiveList", 1), ("ProgressiveBits", 0), ("ProgressiveContainer", 3),
           ("CompatibleUnion", 2)]
VALUES = [("BooleanValue", 1), ("UnsignedValue", 1), ("BytesValue", 1), ("BitsValue", 1), ("Sequence", 1),
          ("Items", 2), ("EmptyItems", 0), ("Selected", 2), ("NullValue", 0)]
WIDTHS = ["U8", "U16", "U32Width", "U64", "U128", "U256"]
FORESTS = ("Chain", "End", "Repeat")


def pat(name, n, p):
    return "T.%s{%s}" % (name, ", ".join("%s%d" % (p, i) for i in range(n)))


def absurd(goal, proof="legal"):
    return "Empty.absurd(%s, W.false_true(%s))" % (goal, proof)


def union_forest_absurd(goal_of, indent="      "):
    lines = [indent + "match u0:"]
    for n, k in SCHEMAS:
        if n == "Chain":
            lines.append(indent + "  case T.Chain{c0, c1}:")
            lines.append(indent + "    match c0:")
            for m, j in SCHEMAS:
                lines.append(indent + "      case %s: %s" % (pat(m, j, "d"), absurd(goal_of("T.Union{T.Chain{%s, c1}}" % pat(m, j, "d")))))
        else:
            lines.append(indent + "  case %s: %s" % (pat(n, k, "o"), absurd(goal_of("T.Union{%s}" % pat(n, k, "o")))))
    return "\n".join(lines)


HEADER = '''import Base
import ../types/schema.bend as T
import ../types/primitive.bend as Prim
import ../src/decode.bend as D
import ../src/schema.bend as I
import ../src/codec.bend as C
import ../src/lists.bend as Lists
import ../spec/codec.bend as S
import ../spec/schema.bend as SS
import ../spec/primitives.bend as SP
import ../spec/bytes.bend as SBytes
import ../spec/byte_list.bend as SByteList
import ../spec/bitfields.bend as SBits
import ./decode_facts.bend as F
import ./decode_shape.bend as Shape
import ./decode_goal.bend as G
import ./schema.bend as Sch
import ./codec_helpers.bend as Helpers
import ./primitive_invariants.bend as V
import ./word_facts.bend as W

# Generated by tools/generate_decode_inverse.py (constructor enumeration only).
# Canonical decoding completeness at the recursive level: for every value
# whose independent normative encoding exists at a validated schema, the
# actual decoder, with a finite traversal budget computed from the VALUE,
# returns exactly that value; every successful single encoding is in the
# byte domain. decode_budget.accepts_finite moves the witness to the actual
# public budget.
'''


def main():
    out = [HEADER]
    # widths_correct
    out.append('''law widths_correct:
  for +fields: T.Schema
  {I.widths(fields) == F.widths(fields) : +List<Maybe<&2, Nat>>}
def widths_correct(fields):
  match fields:''')
    for n, k in SCHEMAS:
        p = pat(n, k, "s")
        if n == "Chain":
            out.append('''    case T.Chain{s0, s1}:
      %Equal.sym(Maybe<&2, Nat>, I.fixed_size(s0), SS.fixed_size(s0), Sch.fixed_size_correct(s0)) : {_ <> I.widths(s1) == SS.fixed_size(s0) <> F.widths(s1) : +List<Maybe<&2, Nat>>}
      %Equal.sym(+List<Maybe<&2, Nat>>, I.widths(s1), F.widths(s1), widths_correct(s1)) : {SS.fixed_size(s0) <> _ == SS.fixed_size(s0) <> F.widths(s1) : +List<Maybe<&2, Nat>>}
      {==}''')
        else:
            out.append("    case %s: {==}" % p)
    # width_positive
    out.append('''
law width_positive:
  for +schema: T.Schema
  for +legal: {I.valid_go(schema, False{}) == True{} : Bool}
  G.positive(SS.fixed_size(schema))
def width_positive(schema, legal):
  match schema:''')
    NAMED = "Bool.and(Nat.is_lt(0n, I.count(%s)), Bool.and(Nat.is_eq(Lists.length(String, %s), I.count(%s)), I.unique_names(%s)))"
    PROG_REST = "Bool.and(Nat.is_le(Lists.length(Bool, s2), 256n), Bool.and(I.ends_active(s2, False{}), Nat.is_eq(I.active_count(s2, 0n), I.count(s1))))"

    def fields_case(pos_expr, valid_expr, goal_schema):
        lines = ["      match s1:"]
        for n, k in SCHEMAS:
            p = pat(n, k, "f")
            g = "G.positive(SS.fixed_size(%s))" % goal_schema.replace("s1", p)
            if n == "Chain":
                lines.append("        case T.Chain{f0, f1}: G.sum_positive(SS.fixed_size(f0), SS.fixed_size(f1), width_positive(f0, V.and_left(I.valid_go(f0, False{}), I.valid_go(f1, True{}), %s)))" % valid_expr.replace("s1", p))
            elif n == "End":
                lines.append("        case T.End{}: %s" % absurd(g, pos_expr.replace("s1", "T.End{}")))
            elif n in ("Boolean", "Unsigned", "ByteVector", "BitVector", "Vector", "Container", "Null", "ProgressiveContainer"):
                lines.append("        case %s: %s" % (p, absurd(g, valid_expr.replace("s1", p))))
            else:
                lines.append("        case %s: Unit{}" % p)
        return "\n".join(lines)

    for n, k in SCHEMAS:
        p = pat(n, k, "s")
        goal = "G.positive(SS.fixed_size(%s))" % p
        if n == "Boolean":
            out.append("    case %s: {==}" % p)
        elif n == "Unsigned":
            out.append("    case T.Unsigned{s0}:\n      match s0:")
            for w in WIDTHS:
                out.append("        case Prim.%s{}: {==}" % w)
        elif n == "ByteVector":
            out.append("    case %s: legal" % p)
        elif n == "BitVector":
            out.append("    case %s: G.bit_bytes_positive(s0, legal)" % p)
        elif n == "Vector":
            out.append("    case %s: G.times_positive(s1, SS.fixed_size(s0), V.and_left(Nat.is_lt(0n, s1), I.valid_go(s0, False{}), legal), width_positive(s0, V.and_right(Nat.is_lt(0n, s1), I.valid_go(s0, False{}), legal)))" % p)
        elif n == "Container":
            named = NAMED % ("s1", "s0", "s1", "s0")
            pos = "V.and_left(Nat.is_lt(0n, I.count(s1)), Bool.and(Nat.is_eq(Lists.length(String, s0), I.count(s1)), I.unique_names(s0)), V.and_left(%s, I.valid_go(s1, True{}), legal))" % named
            valid = "V.and_right(%s, I.valid_go(s1, True{}), legal)" % named
            out.append("    case T.Container{s0, s1}:")
            out.append(fields_case(pos, valid, "T.Container{s0, s1}"))
        elif n == "ProgressiveContainer":
            named = NAMED % ("s1", "s0", "s1", "s0")
            rest = "Bool.and(I.valid_go(s1, True{}), %s)" % PROG_REST
            pos = "V.and_left(Nat.is_lt(0n, I.count(s1)), Bool.and(Nat.is_eq(Lists.length(String, s0), I.count(s1)), I.unique_names(s0)), V.and_left(%s, %s, legal))" % (named, rest)
            valid = "V.and_left(I.valid_go(s1, True{}), %s, V.and_right(%s, %s, legal))" % (PROG_REST, named, rest)
            out.append("    case T.ProgressiveContainer{s0, s1, s2}:")
            out.append(fields_case(pos, valid, "T.ProgressiveContainer{s0, s1, s2}"))
        elif n in ("Null", "Chain", "End"):
            out.append("    case %s: %s" % (p, absurd(goal)))
        else:
            out.append("    case %s: Unit{}" % p)

    # views
    def view(name, statement, cases):
        out.append(statement)
        out.append("def %s:" % name)
        out.append("  match schema:")
        out.extend(cases)

    cases = []
    for n, k in SCHEMAS:
        p = pat(n, k, "s")
        if n in FORESTS:
            cases.append("    case %s: %s" % (p, absurd("G.single_result(%s, value, result)" % p)))
        else:
            cases.append("    case %s: known" % p)
    view("head_view(schema, value, result, legal, known)", '''
law head_view:
  for +schema: T.Schema
  for +value: T.Value
  for +result: Maybe<&2, +List<T.Part>>
  for legal: {I.valid_go(schema, False{}) == True{} : Bool}
  for known: G.inverse_result(schema, value, result)
  G.single_result(schema, value, result)''', cases)

    cases = []
    for n, k in SCHEMAS:
        p = pat(n, k, "s") if n != "Union" else "T.Union{u0}"
        if n in ("Chain", "End"):
            cases.append("    case %s: known" % p)
        elif n == "Union":
            cases.append("    case %s:" % p)
            cases.append(union_forest_absurd(lambda s: "G.forest_result(%s, value, result)" % s))
        else:
            cases.append("    case %s: %s" % (p, absurd("G.forest_result(%s, value, result)" % p)))
    view("forest_view(schema, value, result, legal, known)", '''
law forest_view:
  for +schema: T.Schema
  for +value: T.Value
  for +result: Maybe<&2, +List<T.Part>>
  for legal: {I.valid_go(schema, True{}) == True{} : Bool}
  for known: G.inverse_result(schema, value, result)
  G.forest_result(schema, value, result)''', cases)

    cases = []
    for n, k in SCHEMAS:
        p = pat(n, k, "s")
        if n in FORESTS:
            cases.append("    case %s: %s" % (p, absurd("G.single_result(%s, value, result)" % p)))
        else:
            cases.append("    case %s: known" % p)
    view("option_view(schema, value, result, legal, known)", '''
law option_view:
  for +schema: T.Schema
  for +value: T.Value
  for +result: Maybe<&2, +List<T.Part>>
  for legal: {G.option_ok(schema) == True{} : Bool}
  for known: G.inverse_result(schema, value, result)
  G.single_result(schema, value, result)''', cases)

    cases = []
    for n, k in SCHEMAS:
        p = pat(n, k, "s")
        if n in FORESTS:
            cases.append("    case %s: %s" % (p, absurd("{F.ok(%s) == True{} : Bool}" % p)))
        elif n == "Null":
            cases.append("    case %s: {==}" % p)
        else:
            cases.append("    case %s: legal" % p)
    view("ok_of_option(schema, legal)", '''
law ok_of_option:
  for +schema: T.Schema
  for legal: {G.option_ok(schema) == True{} : Bool}
  {F.ok(schema) == True{} : Bool}''', cases)

    cases = []
    for n, k in SCHEMAS:
        p = pat(n, k, "s")
        if n == "Null":
            cases.append("    case %s: {==}" % p)
        else:
            cases.append("    case %s: legal" % p)
    view("single_option_ok(schema, legal)", '''
law single_option_ok:
  for +schema: T.Schema
  for legal: {I.valid_go(schema, False{}) == True{} : Bool}
  {G.option_ok(schema) == True{} : Bool}''', cases)

    # forest lookup
    out.append('''
law forest_lookup:
  for +schema: T.Schema
  for +j: Nat
  for +legal: {I.valid_go(schema, True{}) == True{} : Bool}
  G.index_fact(j, I.count(schema), SS.option(schema, j))
def forest_lookup(schema, j, legal):
  match schema:''')
    for n, k in SCHEMAS:
        p = pat(n, k, "s")
        if n == "Chain":
            out.append('''    case T.Chain{s0, s1}:
      match j:
        case 0n: (single_option_ok(s0, V.and_left(I.valid_go(s0, False{}), I.valid_go(s1, True{}), legal)), {==})
        case 1n+q: G.index_shift(q, I.count(s1), SS.option(s1, q), forest_lookup(s1, q, V.and_right(I.valid_go(s0, False{}), I.valid_go(s1, True{}), legal)))''')
        else:
            out.append("    case %s: Unit{}" % p)

    # union lookup
    out.append('''
law union_lookup:
  for +options: T.Schema
  for +i: Nat
  for +legal: {I.valid_go(T.Union{options}, False{}) == True{} : Bool}
  G.index_fact(i, 128n, SS.option(options, i))
def union_lookup(options, i, legal):
  match options:''')
    for n, k in SCHEMAS:
        p = pat(n, k, "o")
        if n != "Chain":
            out.append("    case %s: Unit{}" % p)
            continue
        out.append("    case T.Chain{o0, o1}:")
        out.append("      match o0:")
        for m, j in SCHEMAS:
            h = pat(m, j, "h")
            out.append("        case %s:" % h)
            out.append("          match i:")
            if m == "Null":
                out.append("            case 0n: ({==}, {==})")
                inner = "Bool.and(Nat.is_le(I.count(o1), 127n), I.valid_go(o1, True{}))"
                rest = "V.and_right(Nat.is_lt(0n, I.count(o1)), %s, legal)" % inner
                bound = "V.and_left(Nat.is_le(I.count(o1), 127n), I.valid_go(o1, True{}), %s)" % rest
                valid = "V.and_right(Nat.is_le(I.count(o1), 127n), I.valid_go(o1, True{}), %s)" % rest
            else:
                inner = "Bool.and(I.valid_go(%s, False{}), I.valid_go(o1, True{}))" % h
                head_valid = "V.and_left(I.valid_go(%s, False{}), I.valid_go(o1, True{}), V.and_right(Nat.is_le(I.count(o1), 127n), %s, legal))" % (h, inner)
                out.append("            case 0n: (%s, {==})" % head_valid)
                bound = "V.and_left(Nat.is_le(I.count(o1), 127n), %s, legal)" % inner
                valid = "V.and_right(I.valid_go(%s, False{}), I.valid_go(o1, True{}), V.and_right(Nat.is_le(I.count(o1), 127n), %s, legal))" % (h, inner)
            out.append("            case 1n+q: G.index_widen(q, I.count(o1), SS.option(o1, q), forest_lookup(o1, q, %s), %s)" % (valid, bound))

    # compatible lookup
    out.append('''
law compatible_lookup:
  for +selectors: +List<U32>
  for +options: T.Schema
  for +sel: U32
  for +seen: +List<U32>
  for +valid_selectors: {I.selectors_valid(selectors, seen) == True{} : Bool}
  for +valid_options: {I.valid_go(options, True{}) == True{} : Bool}
  G.selection(sel, SS.compatible_option(selectors, options, sel))
def compatible_lookup(selectors, options, sel, seen, valid_selectors, valid_options):
  match selectors:
    case Nil{}: Unit{}
    case Con{h, hs}:
      match options:''')
    RANGE = "Bool.and(U32.is_lt(0, h), U32.is_lt(h, 128))"
    REST = "Bool.and(Bool.not(I.has_selector(h, seen)), I.selectors_valid(hs, h <> seen))"
    for n, k in SCHEMAS:
        p = pat(n, k, "o")
        if n != "Chain":
            out.append("        case %s: Unit{}" % p)
            continue
        small = "G.u32_widen(h, V.and_right(U32.is_lt(0, h), U32.is_lt(h, 128), V.and_left(%s, %s, valid_selectors)))" % (RANGE, REST)
        tail_sel = "V.and_right(Bool.not(I.has_selector(h, seen)), I.selectors_valid(hs, h <> seen), V.and_right(%s, %s, valid_selectors))" % (RANGE, REST)
        ook = "single_option_ok(o0, V.and_left(I.valid_go(o0, False{}), I.valid_go(o1, True{}), valid_options))"
        tail_opt = "V.and_right(I.valid_go(o0, False{}), I.valid_go(o1, True{}), valid_options)"
        out.append("        case T.Chain{o0, o1}: G.compat_select(U32.is_eq(h, sel), h, sel, o0, SS.compatible_option(hs, o1, sel), {==}, %s, %s, compatible_lookup(hs, o1, sel, h <> seen, %s, %s))" % (small, ook, tail_sel, tail_opt))

    # main induction
    out.append('''
law inverse:
  for +value: T.Value
  for +schema: T.Schema
  for +legal: {F.ok(schema) == True{} : Bool}
  G.inverse_result(schema, value, S.parts(value, schema))
def inverse(value, schema, legal):
  match value:''')
    NAMED2 = NAMED % ("s1", "s0", "s1", "s0")
    CU = ["Nat.is_lt(0n, I.count(s1))", "Nat.is_eq(Lists.length(U32, s0), I.count(s1))", "I.selectors_valid(s0, [])",
          "I.valid_go(s1, True{})", "I.compatible_go(Nat.mul(1024n, 1n+I.weight(s1)), 1, s1, s1)"]

    def conj(xs):
        e = xs[-1]
        for x in reversed(xs[:-1]):
            e = "Bool.and(%s, %s)" % (x, e)
        return e

    def pick(xs, idx, proof):
        # proof : {conj(xs) == True}; returns proof of xs[idx]
        for i in range(idx):
            proof = "V.and_right(%s, %s, %s)" % (xs[i], conj(xs[i + 1:]), proof)
        if idx < len(xs) - 1:
            proof = "V.and_left(%s, %s, %s)" % (xs[idx], conj(xs[idx + 1:]), proof)
        return proof

    for vn, vk in VALUES:
        out.append("    case %s:" % pat(vn, vk, "v"))
        out.append("      match schema:")
        for sn, sk in SCHEMAS:
            p = pat(sn, sk, "s")
            proof = "Unit{}"
            if vn == "BooleanValue" and sn == "Boolean":
                proof = "G.boolean_leaf(v0)"
            elif vn == "UnsignedValue" and sn == "Unsigned":
                proof = "G.one_leaf(T.Unsigned{s0}, T.UnsignedValue{v0}, SP.uint_encoding(s0, v0), Some{SP.byte_width(s0)}, xs => e => G.uint_leaf(s0, v0, xs, e))"
            elif vn == "BytesValue" and sn == "ByteVector":
                proof = "G.one_leaf(T.ByteVector{s0}, T.BytesValue{v0}, SBytes.vector_encoding(s0, v0), Some{s0}, xs => e => G.byte_vector_leaf(s0, v0, xs, e))"
            elif vn == "BytesValue" and sn == "ByteList":
                proof = "G.one_leaf(T.ByteList{s0}, T.BytesValue{v0}, SByteList.encoding(s0, v0), None{}, xs => e => G.byte_list_leaf(s0, v0, xs, e))"
            elif vn == "BitsValue" and sn == "BitVector":
                proof = "G.one_leaf(T.BitVector{s0}, T.BitsValue{v0}, SBits.vector_encoding(s0, v0), Some{Nat.div(Nat.add(s0, 7n), 8n)}, xs => e => G.bit_vector_leaf(s0, v0, xs, e))"
            elif vn == "BitsValue" and sn == "BitList":
                proof = "G.one_leaf(T.BitList{s0}, T.BitsValue{v0}, SBits.list_encoding(s0, v0), None{}, xs => e => G.bit_list_leaf(s0, v0, xs, e))"
            elif vn == "BitsValue" and sn == "ProgressiveBits":
                proof = "G.one_leaf(T.ProgressiveBits{}, T.BitsValue{v0}, SBits.list_encoding(List.length(&2, Bool, v0), v0), None{}, xs => e => G.progressive_bits_leaf(v0, xs, e))"
            elif vn == "NullValue" and sn == "Null":
                proof = "({==}, {==})"
            elif vn == "EmptyItems" and sn in ("End", "Repeat"):
                proof = "acc => {==}"
            elif vn == "Items" and sn == "Chain":
                vs = "V.and_left(I.valid_go(s0, False{}), I.valid_go(s1, True{}), legal)"
                vr = "V.and_right(I.valid_go(s0, False{}), I.valid_go(s1, True{}), legal)"
                proof = ("G.chain_inverse(s0, s1, v0, v1, S.parts(v0, s0), S.parts(v1, s1), "
                         "Shape.head_single(s0, v0, S.parts(v0, s0), %s, Shape.facts(v0, s0, Shape.ok_single(s0, %s))), "
                         "head_view(s0, v0, S.parts(v0, s0), %s, inverse(v0, s0, Shape.ok_single(s0, %s))), "
                         "forest_view(s1, v1, S.parts(v1, s1), %s, inverse(v1, s1, Shape.ok_forest(s1, %s))))" % (vs, vs, vs, vs, vr, vr))
            elif vn == "Items" and sn == "Repeat":
                proof = ("G.repeat_inverse(s0, v0, v1, S.parts(v0, s0), S.parts(v1, T.Repeat{s0}), "
                         "Shape.head_single(s0, v0, S.parts(v0, s0), legal, Shape.facts(v0, s0, Shape.ok_single(s0, legal))), "
                         "head_view(s0, v0, S.parts(v0, s0), legal, inverse(v0, s0, Shape.ok_single(s0, legal))), "
                         "inverse(v1, T.Repeat{s0}, legal))")
            elif vn == "Sequence" and sn == "Vector":
                ve = "V.and_right(Nat.is_lt(0n, s1), I.valid_go(s0, False{}), legal)"
                proof = ("G.vector_inverse(s0, s1, v0, Bool.and(Nat.is_lt(0n, s1), Nat.is_eq(S.count(v0), s1)), S.parts(v0, T.Repeat{s0}), {==}, "
                         "width_positive(s0, %s), Shape.facts(v0, T.Repeat{s0}, %s), inverse(v0, T.Repeat{s0}, %s))" % (ve, ve, ve))
            elif vn == "Sequence" and sn == "ListOf":
                proof = ("G.list_inverse(s0, s1, v0, Nat.is_le(S.count(v0), s1), S.parts(v0, T.Repeat{s0}), {==}, "
                         "width_positive(s0, legal), Shape.facts(v0, T.Repeat{s0}, legal), inverse(v0, T.Repeat{s0}, legal))")
            elif vn == "Sequence" and sn == "ProgressiveList":
                proof = ("G.progressive_list_inverse(s0, v0, S.parts(v0, T.Repeat{s0}), "
                         "width_positive(s0, legal), Shape.facts(v0, T.Repeat{s0}, legal), inverse(v0, T.Repeat{s0}, legal))")
            elif vn == "Sequence" and sn in ("Container", "ProgressiveContainer"):
                if sn == "Container":
                    vf = "V.and_right(%s, I.valid_go(s1, True{}), legal)" % NAMED2
                else:
                    rest = "Bool.and(I.valid_go(s1, True{}), %s)" % PROG_REST
                    vf = "V.and_left(I.valid_go(s1, True{}), %s, V.and_right(%s, %s, legal))" % (PROG_REST, NAMED2, rest)
                proof = ("G.container_inverse(%s, s1, v0, S.parts(v0, s1), widths_correct(s1), cps => bytes => d => d, "
                         "Shape.forest_view(s1, v0, S.parts(v0, s1), %s, Shape.facts(v0, s1, Shape.ok_forest(s1, %s))), "
                         "forest_view(s1, v0, S.parts(v0, s1), %s, inverse(v0, s1, Shape.ok_forest(s1, %s))))" % (p, vf, vf, vf, vf))
            elif vn == "Selected" and sn == "Union":
                proof = ("G.union_found(T.Union{s0}, v0, v1, SS.option(s0, U32.to_nat(v0)), "
                         "G.index_selection(v0, SS.option(s0, U32.to_nat(v0)), union_lookup(s0, U32.to_nat(v0), legal)), "
                         "s => f => xs => d => G.selected_decodes(I.get(s0, U32.to_nat(v0)), v0, v1, s, xs, Equal.trans(Maybe<&2, T.Schema>, I.get(s0, U32.to_nat(v0)), SS.option(s0, U32.to_nat(v0)), Some{s}, Sch.option_correct(s0, U32.to_nat(v0)), f), d), "
                         "s => ok => option_view(s, v1, S.parts(v1, s), ok, inverse(v1, s, ok_of_option(s, ok))))")
            elif vn == "Selected" and sn == "CompatibleUnion":
                vsel = pick(CU, 2, "legal")
                vopt = pick(CU, 3, "legal")
                proof = ("G.union_found(T.CompatibleUnion{s0, s1}, v0, v1, SS.compatible_option(s0, s1, v0), "
                         "compatible_lookup(s0, s1, v0, [], %s, %s), "
                         "s => f => xs => d => G.selected_decodes(C.selected_schema(s0, s1, v0), v0, v1, s, xs, Equal.trans(Maybe<&2, T.Schema>, C.selected_schema(s0, s1, v0), SS.compatible_option(s0, s1, v0), Some{s}, Helpers.selected_schema_correct(s0, s1, v0), f), d), "
                         "s => ok => option_view(s, v1, S.parts(v1, s), ok, inverse(v1, s, ok_of_option(s, ok))))" % (vsel, vopt))
            out.append("        case %s: %s" % (p, proof))
    Path("proofs/decode_inverse.bend").write_text("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
