"""Generate proofs/root_total.bend: valid-value totality of actual roots.

Every value that has an independent normative encoding at a validated schema
and whose uint256 length mixes are representable (spec/value_domain) has an
actual root. Constructor enumeration only; no protocol inputs or fixtures.
"""
from pathlib import Path

SCHEMAS = [("Boolean", 0), ("Unsigned", 1), ("ByteVector", 1), ("ByteList", 1), ("BitVector", 1), ("BitList", 1),
           ("Vector", 2), ("ListOf", 2), ("Container", 2), ("Union", 1), ("Null", 0), ("Chain", 2), ("End", 0),
           ("Repeat", 1), ("Named", 2), ("ProgressiveList", 1), ("ProgressiveBits", 0), ("ProgressiveContainer", 3),
           ("CompatibleUnion", 2)]
VALUES = [("BooleanValue", 1), ("UnsignedValue", 1), ("BytesValue", 1), ("BitsValue", 1), ("Sequence", 1),
          ("Items", 2), ("EmptyItems", 0), ("Selected", 2), ("NullValue", 0)]
WIDTHS = ["U8", "U16", "U32Width", "U64", "U128", "U256"]
FORESTS = ("Chain", "End", "Repeat")
NAMED = "Bool.and(Nat.is_lt(0n, IS.count(s1)), Bool.and(Nat.is_eq(Lists.length(String, s0), IS.count(s1)), IS.unique_names(s0)))"
PROG_REST = "Bool.and(Nat.is_le(Lists.length(Bool, s2), 256n), Bool.and(IS.ends_active(s2, False{}), Nat.is_eq(IS.active_count(s2, 0n), IS.count(s1))))"


def pat(name, n, p):
    return "T.%s{%s}" % (name, ", ".join("%s%d" % (p, i) for i in range(n)))


def absurd(goal, proof="legal"):
    return "Empty.absurd(%s, W.false_true(%s))" % (goal, proof)


def conj(xs):
    e = xs[-1]
    for x in reversed(xs[:-1]):
        e = "Bool.and(%s, %s)" % (x, e)
    return e


def pick(xs, idx, proof):
    for i in range(idx):
        proof = "V.and_right(%s, %s, %s)" % (xs[i], conj(xs[i + 1:]), proof)
    if idx < len(xs) - 1:
        proof = "V.and_left(%s, %s, %s)" % (xs[idx], conj(xs[idx + 1:]), proof)
    return proof


HEADER = '''import Base
import ../types/schema.bend as T
import ../types/primitive.bend as Prim
import ../src/root.bend as IR
import ../src/cached_tree.bend as Cache
import ../src/schema.bend as IS
import ../src/codec.bend as IC
import ../src/lists.bend as Lists
import ../src/primitives.bend as IP
import ../src/byte_root.bend as IByteRoot
import ../src/byte_list.bend as IByteList
import ../src/bit_root.bend as IBits
import ../src/bitfields.bend as IFields
import ../src/packing.bend as IPack
import ../spec/root_relation.bend as R
import ../spec/codec.bend as SC
import ../spec/schema.bend as SS
import ../spec/type_legality.bend as TL
import ../spec/primitives.bend as SP
import ../spec/bytes.bend as SBytes
import ../spec/byte_list.bend as SByteList
import ../spec/bitfields.bend as SBits
import ../spec/nat_bytes.bend as SLen
import ../spec/layout.bend as E
import ../spec/value_domain.bend as VD
import ./root_steps.bend as G
import ./root_sound.bend as RS
import ./root_total_steps.bend as TS
import ./root_scope.bend as Scope
import ./decode_facts.bend as F
import ./decode_shape.bend as Shape
import ./decode_goal.bend as DG
import ./decode_inverse.bend as Lookups
import ./layout_image_headers.bend as H
import ./schema.bend as Sch
import ./schema_forest.bend as Forest
import ./codec_composition.bend as Composition
import ./codec_helpers.bend as Helpers
import ./codec_count.bend as Counts
import ./validator_metadata.bend as Metadata
import ./integer_encoding.bend as IntegerEnc
import ./byte_root.bend as ByteRootLaws
import ./byte_list.bend as ByteListLaws
import ./bit_root.bend as BitRoot
import ./bit_list_root.bend as BitListRoot
import ./bit_vector_inverse.bend as Eq
import ./nat_order.bend as Order
import ./primitive_invariants.bend as V
import ./lists.bend as L
import ./word_facts.bend as W

# Generated by tools/generate_root_total.py (constructor enumeration only).
'''

HELPERS = r'''
law one_present:
  for +enc: Maybe<&2, +List<U32>>
  for +width: Maybe<&2, Nat>
  for +e: {TS.parts_present(SC.one(enc, width)) == True{} : Bool}
  {IP.is_some(enc) == True{} : Bool}
def one_present(enc, width, e):
  match enc:
    case None{}: e
    case Some{x}: {==}

law checked_present:
  for +x: Maybe<&2, +List<U32>>
  for +e: {IP.is_some(x) == True{} : Bool}
  {IP.is_some(IP.root_checked(x)) == True{} : Bool}
def checked_present(x, e):
  match x:
    case None{}: e
    case Some{y}: {==}

law optional_true:
  for +ok: Bool
  for +xs: +List<U32>
  for +e: {IP.is_some(SP.optional(ok, xs)) == True{} : Bool}
  {ok == True{} : Bool}
def optional_true(ok, xs, e):
  match ok:
    case False{}: e
    case True{}: {==}

law bits_true:
  for +ok: Bool
  for +bits: +List<Bool>
  for +e: {IP.is_some(SBits.encoding(ok, bits)) == True{} : Bool}
  {ok == True{} : Bool}
def bits_true(ok, bits, e):
  match ok:
    case False{}: e
    case True{}: {==}

law uint_present:
  for +w: Prim.Width
  for +v: Prim.UInt
  for +e: {TS.parts_present(SC.one(SP.uint_encoding(w, v), Some{SP.byte_width(w)})) == True{} : Bool}
  {TS.present(IR.single(IP.uint_root(w, v))) == True{} : Bool}
def uint_present(w, v, e):
  TS.single_present(IP.uint_root(w, v), checked_present(IP.uint_serialize(w, v),
    %Equal.sym(Maybe<&2, +List<U32>>, IP.uint_serialize(w, v), SP.uint_encoding(w, v), IntegerEnc.uint_serialize_correct(w, v)) : {IP.is_some(_) == True{} : Bool}
    one_present(SP.uint_encoding(w, v), Some{SP.byte_width(w)}, e)))

law bytevector_present:
  for +n: Nat
  for +xs: +List<U32>
  for +e: {TS.parts_present(SC.one(SBytes.vector_encoding(n, xs), Some{n})) == True{} : Bool}
  {TS.present(IR.single(IByteRoot.hash_tree_root(n, xs))) == True{} : Bool}
def bytevector_present(n, xs, e):
  TS.single_present(IByteRoot.hash_tree_root(n, xs), Equal.trans(Bool, IP.is_some(IByteRoot.hash_tree_root(n, xs)), SBytes.vector_domain(n, xs), True{}, ByteRootLaws.hash_tree_root_rejection(n, xs), optional_true(SBytes.vector_domain(n, xs), xs, one_present(SBytes.vector_encoding(n, xs), Some{n}, e))))

law bytelist_present:
  for +n: Nat
  for +xs: +List<U32>
  for +e: {TS.parts_present(SC.one(SByteList.encoding(n, xs), None{})) == True{} : Bool}
  {TS.present(IR.single(IByteList.hash_tree_root(n, xs))) == True{} : Bool}
def bytelist_present(n, xs, e):
  TS.single_present(IByteList.hash_tree_root(n, xs), Equal.trans(Bool, IP.is_some(IByteList.hash_tree_root(n, xs)), IByteList.valid(n, xs), True{}, ByteListLaws.root_exact_acceptance(n, xs), Equal.trans(Bool, IByteList.valid(n, xs), SByteList.domain(n, xs), True{}, ByteListLaws.domain_correct(n, xs), optional_true(SByteList.domain(n, xs), xs, one_present(SByteList.encoding(n, xs), None{}, e)))))

law bitvector_present:
  for +n: Nat
  for +bits: +List<Bool>
  for +e: {TS.parts_present(SC.one(SBits.vector_encoding(n, bits), Some{Nat.div(Nat.add(n, 7n), 8n)})) == True{} : Bool}
  {TS.present(IR.single(IBits.bitvector_hash_tree_root(n, bits))) == True{} : Bool}
def bitvector_present(n, bits, e):
  TS.single_present(IBits.bitvector_hash_tree_root(n, bits), Equal.trans(Bool, IP.is_some(IBits.bitvector_hash_tree_root(n, bits)), IFields.vector_valid(n, bits), True{}, BitRoot.bitvector_root_exact_acceptance(n, bits), DG.vector_valid_of(n, bits, bits_true(SBits.vector_domain(n, bits), bits, one_present(SBits.vector_encoding(n, bits), Some{Nat.div(Nat.add(n, 7n), 8n)}, e)))))

law bitlist_present:
  for +n: Nat
  for +bits: +List<Bool>
  for +e: {TS.parts_present(SC.one(SBits.list_encoding(n, bits), None{})) == True{} : Bool}
  for +fits: {SLen.fits(32n, List.length(&2, Bool, bits)) == True{} : Bool}
  {TS.present(IR.single(IBits.bitlist_hash_tree_root(n, bits))) == True{} : Bool}
def bitlist_present(n, bits, e, fits):
  TS.single_present(IBits.bitlist_hash_tree_root(n, bits), Equal.trans(Bool, IP.is_some(IBits.bitlist_hash_tree_root(n, bits)), Bool.and(IFields.list_valid(n, bits), SLen.fits(32n, List.length(&2, Bool, bits))), True{}, BitListRoot.bitlist_root_acceptance(n, bits), V.and_true(IFields.list_valid(n, bits), SLen.fits(32n, List.length(&2, Bool, bits)), bits_true(SBits.list_domain(n, bits), List.append(&2, Bool, bits, [True{}]), one_present(SBits.list_encoding(n, bits), None{}, e)), fits)))

law progressive_bits_present:
  for +bits: +List<Bool>
  for +size: Nat
  for +fits: {SLen.fits(32n, List.length(&2, Bool, bits)) == True{} : Bool}
  {TS.present(IR.single(IR.length_mix(Cache.progressive(IBits.chunks(bits), Cache.zeros(size)), Some{Lists.length(Bool, bits)}))) == True{} : Bool}
def progressive_bits_present(bits, size, fits):
  %Equal.sym(Nat, Lists.length(Bool, bits), List.length(&2, Bool, bits), L.length_correct(Bool, bits)) : {TS.present(IR.single(IR.length_mix(Cache.progressive(IBits.chunks(bits), Cache.zeros(size)), Some{_}))) == True{} : Bool}
  TS.single_present(IR.length_mix(Cache.progressive(IBits.chunks(bits), Cache.zeros(size)), Some{List.length(&2, Bool, bits)}), TS.mixed_present(Cache.progressive(IBits.chunks(bits), Cache.zeros(size)), Some{List.length(&2, Bool, bits)}, TS.progressive_present(IBits.chunks(bits), size, BitRoot.chunks_domain(bits)), Scope.merkle_scope(Some{IBits.chunks(bits)}, 0n, True{}, size), fits))

law accumulate_present:
  for +hr: Maybe<&2, +List<+List<U32>>>
  for +acc: +List<+List<U32>>
  for next: +List<+List<U32>> -> Maybe<&2, +List<+List<U32>>>
  for +hp: {TS.present(hr) == True{} : Bool}
  for tp: @+prior: +List<+List<U32>> -> {TS.present(next(prior)) == True{} : Bool}
  {TS.present(IR.accumulate(hr, acc, next)) == True{} : Bool}
def accumulate_present(hr, acc, next, hp, tp):
  match hr:
    case None{}: hp
    case Some{hs}: tp(List.reverse.go(&2, +List<U32>, hs, acc))

law concat_left:
  for +a: Maybe<&2, +List<T.Part>>
  for +b: Maybe<&2, +List<T.Part>>
  for +e: {TS.parts_present(SC.concatenate(a, b)) == True{} : Bool}
  {TS.parts_present(a) == True{} : Bool}
def concat_left(a, b, e):
  match a b:
    case None{} _: e
    case Some{x} _: {==}

law concat_right:
  for +a: Maybe<&2, +List<T.Part>>
  for +b: Maybe<&2, +List<T.Part>>
  for +e: {TS.parts_present(SC.concatenate(a, b)) == True{} : Bool}
  {TS.parts_present(b) == True{} : Bool}
def concat_right(a, b, e):
  match a b:
    case None{} None{}: e
    case None{} Some{y}: {==}
    case Some{x} None{}: e
    case Some{x} Some{y}: {==}

law aggregate_parts:
  for +r: Maybe<&2, +List<T.Part>>
  for +width: Maybe<&2, Nat>
  for +e: {TS.parts_present(SC.aggregate(r, width)) == True{} : Bool}
  {TS.parts_present(r) == True{} : Bool}
def aggregate_parts(r, width, e):
  match r:
    case None{}: e
    case Some{ps}: {==}

law require_ok:
  for +ok: Bool
  for +r: Maybe<&2, +List<T.Part>>
  for +e: {TS.parts_present(SC.require(ok, r)) == True{} : Bool}
  {ok == True{} : Bool}
def require_ok(ok, r, e):
  match ok:
    case False{}: e
    case True{}: {==}

law require_body:
  for +ok: Bool
  for +r: Maybe<&2, +List<T.Part>>
  for +e: {TS.parts_present(SC.require(ok, r)) == True{} : Bool}
  {TS.parts_present(r) == True{} : Bool}
def require_body(ok, r, e):
  match ok:
    case False{}: Empty.absurd({TS.parts_present(r) == True{} : Bool}, W.false_true(e))
    case True{}: e

law mixing_selected:
  for +found: Maybe<&2, T.Schema>
  for -next: T.Schema -> Bool
  for +s: T.Schema
  for +same: {found == Some{s} : Maybe<&2, T.Schema>}
  for +m: {VD.selected(found, next) == True{} : Bool}
  {next(s) == True{} : Bool}
def mixing_selected(found, next, s, same, m):
  match found:
    case None{}: Empty.absurd({next(s) == True{} : Bool}, W.false_true(m))
    case Some{t}:
      %Equal.cong(Maybe<&2, T.Schema>, T.Schema, RS.found_value, Some{t}, Some{s}, same) : {next(_) == True{} : Bool}
      m

law len_rewrite:
  for +rs: +List<+List<U32>>
  for +mine: +List<+List<U32>>
  for +n: Nat
  for +same: {rs == List.reverse.go(&2, +List<U32>, [], mine) : +List<+List<U32>>}
  for +length: {List.length(&2, +List<U32>, mine) == n : Nat}
  {List.length(&2, +List<U32>, rs) == n : Nat}
def len_rewrite(rs, mine, n, same, length):
  %Equal.sym(+List<+List<U32>>, rs, mine, same) : {List.length(&2, +List<U32>, _) == n : Nat}
  length

law pair_fst:
  for +n: Nat
  for +outs: +List<+List<U32>>
  for -X: Type
  for pair: {List.length(&2, +List<U32>, outs) == n : Nat} & X
  {List.length(&2, +List<U32>, outs) == n : Nat}
def pair_fst(n, outs, X, pair):
  (length, rest) = pair
  length

law repeat_pair:
  for +h: T.Value
  for +t: T.Value
  for +e: T.Schema
  for +mine: +List<+List<U32>>
  for +head: +List<+List<U32>>
  for +tail: +List<+List<U32>>
  for same: {mine == List.append(&2, +List<U32>, head, tail) : +List<+List<U32>>}
  for first: G.one(head) & R.roots(h, e, head)
  for second: {List.length(&2, +List<U32>, tail) == SC.count(t) : Nat} & R.roots(t, T.Repeat{e}, tail)
  {List.length(&2, +List<U32>, mine) == SC.count(T.Items{h, t}) : Nat} & R.roots(T.Items{h, t}, T.Repeat{e}, mine)
def repeat_pair(h, t, e, mine, head, tail, same, first, second):
  (one, rh) = first
  (length, rt) = second
  repeat_pair_eq(h, t, e, mine, head, tail, same, one, length, rh, rt)

law repeat_pair_eq:
  for +h: T.Value
  for +t: T.Value
  for +e: T.Schema
  for +mine: +List<+List<U32>>
  for +head: +List<+List<U32>>
  for +tail: +List<+List<U32>>
  for +same: {mine == List.append(&2, +List<U32>, head, tail) : +List<+List<U32>>}
  for +one: {List.length(&2, +List<U32>, head) == 1n : Nat}
  for +length: {List.length(&2, +List<U32>, tail) == SC.count(t) : Nat}
  for rh: R.roots(h, e, head)
  for rt: R.roots(t, T.Repeat{e}, tail)
  {List.length(&2, +List<U32>, mine) == SC.count(T.Items{h, t}) : Nat} & R.roots(T.Items{h, t}, T.Repeat{e}, mine)
def repeat_pair_eq(h, t, e, mine, head, tail, same, one, length, rh, rt):
  (RS.chain_length(head, tail, mine, SC.count(t), one, length, same), (head, (tail, (rh, (rt, same)))))

law count_map:
  for +r: Maybe<&2, +List<+List<U32>>>
  for +n: Nat
  for +limit: Nat
  for +bound: {Nat.is_le(n, limit) == True{} : Bool}
  for known: G.rel_single(outs => {List.length(&2, +List<U32>, outs) == n : Nat}, r)
  G.rel_single(outs => {Nat.is_le(List.length(&2, +List<U32>, outs), limit) == True{} : Bool}, r)
def count_map(r, n, limit, bound, known):
  match r:
    case None{}: Unit{}
    case Some{outs}:
      %Equal.sym(Nat, List.length(&2, +List<U32>, outs), n, known) : {Nat.is_le(_, limit) == True{} : Bool}
      bound

law unit_rel:
  for +r: Maybe<&2, +List<+List<U32>>>
  G.rel_single(outs => Unit, r)
def unit_rel(r):
  match r:
    case None{}: Unit{}
    case Some{outs}: Unit{}

law single_ok_list:
  for +rs: +List<+List<U32>>
  for scope: {SPack.chunks_domain(rs) == True{} : Bool}
  for one: G.one(rs)
  TS.single_ok(Some{rs})
def single_ok_list(rs, scope, one):
  match rs:
    case Nil{}: Empty.absurd(TS.single_ok(Some{[]}), W.false_true(Equal.cong(Nat, Bool, x => Nat.is_eq(x, 0n), 1n, 0n, Equal.sym(Nat, 0n, 1n, one))))
    case Con{root, rest}:
      match rest:
        case Nil{}: V.and_left(SP.byte_scope(32n, root), True{}, scope)
        case Con{a, b}: Empty.absurd(TS.single_ok(Some{root <> a <> b}), W.false_true(Equal.cong(Nat, Bool, x => Nat.is_eq(x, 1n), 2n+List.length(&2, +List<U32>, b), 1n, one)))

law single_ok_of:
  for +r: Maybe<&2, +List<+List<U32>>>
  for +exists: {TS.present(r) == True{} : Bool}
  for scope: Scope.roots_scope(r)
  for one: G.rel_single(outs => G.one(outs), r)
  TS.single_ok(r)
def single_ok_of(r, exists, scope, one):
  match r:
    case None{}: Empty.absurd(TS.single_ok(None{}), W.false_true(exists))
    case Some{rs}: single_ok_list(rs, scope, one)

law one_map:
  for +v: T.Value
  for +s: T.Schema
  for +r: Maybe<&2, +List<+List<U32>>>
  for +legal: {IS.valid_go(s, False{}) == True{} : Bool}
  for known: G.rel_single(outs => R.roots(v, s, outs), r)
  G.rel_single(outs => G.one(outs), r)
def one_map(v, s, r, legal, known):
  match r:
    case None{}: Unit{}
    case Some{outs}: one_fst(outs, R.roots(v, s, outs), RS.one_root(v, s, outs, legal, known))

law one_fst:
  for +outs: +List<+List<U32>>
  for -X: Type
  for pair: G.one(outs) & X
  G.one(outs)
def one_fst(outs, X, pair):
  (one, rest) = pair
  one

law vector_bound:
  for +count: Nat
  for +n: Nat
  for +ok: {Bool.and(Nat.is_lt(0n, n), Nat.is_eq(count, n)) == True{} : Bool}
  {Nat.is_le(count, n) == True{} : Bool}
def vector_bound(count, n, ok):
  %Eq.nat_equal_sound(count, n, V.and_right(Nat.is_lt(0n, n), Nat.is_eq(count, n), ok)) : {Nat.is_le(count, _) == True{} : Bool}
  Order.reflexive(count)

law shape_of:
  for +e: T.Schema
  for +count: Nat
  for +r: Maybe<&2, +List<T.Part>>
  for +cps: +List<T.Part>
  for +w: Nat
  for facts: F.repeat_fact(List.replicate(Maybe<&2, Nat>, count, SS.fixed_size(e)), r)
  for +same: {r == Some{cps} : Maybe<&2, +List<T.Part>>}
  for +fixed: {SS.fixed_size(e) == Some{w} : Maybe<&2, Nat>}
  {H.widths(cps) == List.replicate(Maybe<&2, Nat>, count, Some{w}) : +List<Maybe<&2, Nat>>}
def shape_of(e, count, r, cps, w, facts, same, fixed):
  %fixed : {H.widths(cps) == List.replicate(Maybe<&2, Nat>, count, _) : +List<Maybe<&2, Nat>>}
  shape_known(count, SS.fixed_size(e), r, cps, facts, same)

law shape_known:
  for +count: Nat
  for +width: Maybe<&2, Nat>
  for +r: Maybe<&2, +List<T.Part>>
  for +cps: +List<T.Part>
  for facts: F.repeat_fact(List.replicate(Maybe<&2, Nat>, count, width), r)
  for +same: {r == Some{cps} : Maybe<&2, +List<T.Part>>}
  {H.widths(cps) == List.replicate(Maybe<&2, Nat>, count, width) : +List<Maybe<&2, Nat>>}
def shape_known(count, width, r, cps, facts, same):
  match r:
    case None{}: Empty.absurd({H.widths(cps) == List.replicate(Maybe<&2, Nat>, count, width) : +List<Maybe<&2, Nat>>}, W.false_true(Equal.cong(Maybe<&2, +List<T.Part>>, Bool, TS.parts_present, None{}, Some{cps}, same)))
    case Some{ps}:
      %Equal.cong(Maybe<&2, +List<T.Part>>, +List<T.Part>, part_contents, Some{ps}, Some{cps}, same) : {H.widths(_) == List.replicate(Maybe<&2, Nat>, count, width) : +List<Maybe<&2, Nat>>}
      facts

def part_contents(r: Maybe<&2, +List<T.Part>>) -> +List<T.Part>:
  match r:
    case None{}: []
    case Some{ps}: ps

law sequence_present:
  for +size_b: Maybe<&2, Nat>
  for -enc: Unit -> Maybe<&2, +List<U32>>
  for comp: Unit -> Maybe<&2, +List<+List<U32>>>
  for +ok: Bool
  for +r: Maybe<&2, +List<T.Part>>
  for +width: Maybe<&2, Nat>
  for +limit: Nat
  for +prog: Bool
  for +length: Maybe<&2, Nat>
  for +size: Nat
  for +enc_eq: {enc(Unit{}) == SC.bytes(SC.require(ok, SC.aggregate(r, width))) : Maybe<&2, +List<U32>>}
  for +encodable: {TS.parts_present(SC.require(ok, SC.aggregate(r, width))) == True{} : Bool}
  for +comp_present: {TS.present(comp(Unit{})) == True{} : Bool}
  for comp_scope: Scope.roots_scope(comp(Unit{}))
  for comp_count: G.rel_single(outs => TS.limit_ok(prog, outs, limit), comp(Unit{}))
  for basic_count: @+w: Nat -> @+eq: {size_b == Some{w} : Maybe<&2, Nat>} -> @+cps: +List<T.Part> -> @+req: {r == Some{cps} : Maybe<&2, +List<T.Part>>} -> @+bytes: +List<U32> -> @+eb: {E.encoding(cps) == Some{bytes} : Maybe<&2, +List<U32>>} -> TS.limit_ok(prog, IPack.scan(bytes, 31n, [], []), IR.count_limit(Some{w}, limit))
  for fits: TS.fits_length(length)
  {TS.present(IR.single(IR.length_mix(IR.merkle(IR.choose_chunks(size_b, enc, comp), IR.count_limit(size_b, limit), prog, Cache.zeros(size)), length))) == True{} : Bool}
def sequence_present(size_b, enc, comp, ok, r, width, limit, prog, length, size, enc_eq, encodable, comp_present, comp_scope, comp_count, basic_count, fits):
  match size_b:
    case None{}: TS.composite_present(comp(Unit{}), limit, prog, length, size, comp_present, comp_scope, comp_count, fits)
    case Some{w}:
      %Equal.sym(Maybe<&2, +List<U32>>, enc(Unit{}), SC.bytes(SC.require(ok, SC.aggregate(r, width))), enc_eq) : {TS.present(IR.single(IR.length_mix(IR.merkle(IR.packed(_), IR.count_limit(Some{w}, limit), prog, Cache.zeros(size)), length))) == True{} : Bool}
      TS.basic_present(w, ok, r, width, 0n, limit, prog, length, size, encodable, cps => req => basic_count(w, {==}, cps, req), fits)
'''


def main():
    out = [HEADER, HELPERS]
    out.insert(1, "import ../spec/packing.bend as SPack\n")
    # repeat_length
    out.append('''
law repeat_length:
  for +value: T.Value
  for +e: T.Schema
  for +mine: +List<+List<U32>>
  for +legal: {IS.valid_go(e, False{}) == True{} : Bool}
  for rel: R.roots(value, T.Repeat{e}, mine)
  {List.length(&2, +List<U32>, mine) == SC.count(value) : Nat} & R.roots(value, T.Repeat{e}, mine)
def repeat_length(value, e, mine, legal, rel):
  match value:''')
    for vn, vk in VALUES:
        p = pat(vn, vk, "v")
        if vn == "Items":
            out.append("    case T.Items{v0, v1}:")
            out.append("      (+head, (+tail, (first, (rest, same)))) = rel")
            out.append("      repeat_pair(v0, v1, e, mine, head, tail, same, RS.one_root(v0, e, head, legal, first), repeat_length(v1, e, tail, legal, rest))")
        elif vn == "EmptyItems":
            out.append("    case T.EmptyItems{}: RS.empty_length(mine, rel)")
        else:
            out.append("    case %s:" % p)
            out.append("      match rel:")
    # counts from soundness
    out.append('''
law repeat_count_go:
  for +items: T.Value
  for +e: T.Schema
  for +r: Maybe<&2, +List<+List<U32>>>
  for +legal: {IS.valid_go(e, False{}) == True{} : Bool}
  for known: G.forest_sound(items, T.Repeat{e}, [], r)
  G.rel_single(outs => {List.length(&2, +List<U32>, outs) == SC.count(items) : Nat}, r)
def repeat_count_go(items, e, r, legal, known):
  match r:
    case None{}: Unit{}
    case Some{rs}:
      (+mine, (rel, same)) = known
      len_rewrite(rs, mine, SC.count(items), same, pair_fst(SC.count(items), mine, R.roots(items, T.Repeat{e}, mine), repeat_length(items, e, mine, legal, rel)))

law repeat_count:
  for +items: T.Value
  for +e: T.Schema
  for +size: Nat
  for +legal: {IS.valid_go(e, False{}) == True{} : Bool}
  G.rel_single(outs => {List.length(&2, +List<U32>, outs) == SC.count(items) : Nat}, IR.roots_go(items, T.Repeat{e}, [], Cache.zeros(size)))
def repeat_count(items, e, size, legal):
  repeat_count_go(items, e, IR.roots_go(items, T.Repeat{e}, [], Cache.zeros(size)), legal, RS.sound(items, T.Repeat{e}, [], size, legal))

law fields_count_go:
  for +items: T.Value
  for +fields: T.Schema
  for +r: Maybe<&2, +List<+List<U32>>>
  for +legal: {IS.valid_go(fields, True{}) == True{} : Bool}
  for known: G.forest_sound(items, fields, [], r)
  G.rel_single(outs => {List.length(&2, +List<U32>, outs) == TL.field_count(fields) : Nat}, r)
def fields_count_go(items, fields, r, legal, known):
  match r:
    case None{}: Unit{}
    case Some{rs}:
      (+mine, (rel, same)) = known
      len_rewrite(rs, mine, TL.field_count(fields), same, pair_fst(TL.field_count(fields), mine, R.roots(items, fields, mine), RS.forest_length(items, fields, mine, legal, rel)))

law fields_count:
  for +items: T.Value
  for +fields: T.Schema
  for +size: Nat
  for +legal: {IS.valid_go(fields, True{}) == True{} : Bool}
  G.rel_single(outs => {List.length(&2, +List<U32>, outs) == TL.field_count(fields) : Nat}, IR.roots_go(items, fields, [], Cache.zeros(size)))
def fields_count(items, fields, size, legal):
  fields_count_go(items, fields, IR.roots_go(items, fields, [], Cache.zeros(size)), legal, RS.forest_view(fields, items, [], IR.roots_go(items, fields, [], Cache.zeros(size)), legal, RS.sound(items, fields, [], size, Shape.ok_forest(fields, legal))))

law container_count:
  for +items: T.Value
  for +fields: T.Schema
  for +size: Nat
  for +legal: {IS.valid_go(fields, True{}) == True{} : Bool}
  G.rel_single(outs => {Nat.is_le(List.length(&2, +List<U32>, outs), IS.count(fields)) == True{} : Bool}, IR.roots_go(items, fields, [], Cache.zeros(size)))
def container_count(items, fields, size, legal):
  count_map(IR.roots_go(items, fields, [], Cache.zeros(size)), TL.field_count(fields), IS.count(fields),
    %Equal.sym(Nat, IS.count(fields), TL.field_count(fields), Metadata.field_count(fields)) : {Nat.is_le(TL.field_count(fields), _) == True{} : Bool}
    Order.reflexive(TL.field_count(fields)),
    fields_count(items, fields, size, legal))
''')
    # basic_fixed
    out.append('''
law basic_fixed:
  for +schema: T.Schema
  for +w: Nat
  for +eq: {IS.basic_size(schema) == Some{w} : Maybe<&2, Nat>}
  {SS.fixed_size(schema) == Some{w} : Maybe<&2, Nat>}
def basic_fixed(schema, w, eq):
  match schema:''')
    for n, k in SCHEMAS:
        p = pat(n, k, "s")
        if n == "Boolean":
            out.append("    case T.Boolean{}: eq")
        elif n == "Unsigned":
            out.append("    case T.Unsigned{s0}:\n      match s0:")
            for wd in WIDTHS:
                out.append("        case Prim.%s{}: eq" % wd)
        else:
            out.append("    case %s: Empty.absurd({SS.fixed_size(%s) == Some{w} : Maybe<&2, Nat>}, W.false_true(Equal.cong(Maybe<&2, Nat>, Bool, nat_present, None{}, Some{w}, eq)))" % (p, p))
    out.insert(len(out) - 1 - 0, "")
    # one_single
    out.append('''
law one_single:
  for +schema: T.Schema
  for +value: T.Value
  for +size: Nat
  for +legal: {DG.option_ok(schema) == True{} : Bool}
  G.rel_single(outs => G.one(outs), IR.roots_go(value, schema, [], Cache.zeros(size)))
def one_single(schema, value, size, legal):
  match schema:''')
    for n, k in SCHEMAS:
        p = pat(n, k, "s")
        goal = "G.rel_single(outs => G.one(outs), IR.roots_go(value, %s, [], Cache.zeros(size)))" % p
        if n in FORESTS:
            out.append("    case %s: %s" % (p, absurd(goal)))
        elif n == "Null":
            out.append("    case T.Null{}:\n      match value:")
            for vn, vk in VALUES:
                out.append("        case %s: %s" % (pat(vn, vk, "v"), "{==}" if vn == "NullValue" else "Unit{}"))
        else:
            out.append("    case %s: one_map(value, %s, IR.roots_go(value, %s, [], Cache.zeros(size)), legal, RS.option_view(%s, value, IR.roots_go(value, %s, [], Cache.zeros(size)), legal, RS.sound(value, %s, [], size, Lookups.ok_of_option(%s, legal))))" % (p, p, p, p, p, p, p))
    # main induction
    out.append('''
law total:
  for +value: T.Value
  for +schema: T.Schema
  for +acc: +List<+List<U32>>
  for +size: Nat
  for +legal: {F.ok(schema) == True{} : Bool}
  for +encodable: {TS.parts_present(SC.parts(value, schema)) == True{} : Bool}
  for +mixing: {VD.mixing_lengths(value, schema) == True{} : Bool}
  {TS.present(IR.roots_go(value, schema, acc, Cache.zeros(size))) == True{} : Bool}
def total(value, schema, acc, size, legal, encodable, mixing):
  match value:''')
    CU = ["Nat.is_lt(0n, IS.count(s1))", "Nat.is_eq(Lists.length(U32, s0), IS.count(s1))", "IS.selectors_valid(s0, [])",
          "IS.valid_go(s1, True{})", "IS.compatible_go(Nat.mul(1024n, 1n+IS.weight(s1)), 1, s1, s1)"]
    TABLE = "Cache.zeros(size)"
    for vn, vk in VALUES:
        out.append("    case %s:" % pat(vn, vk, "v"))
        out.append("      match schema:")
        for sn, sk in SCHEMAS:
            p = pat(sn, sk, "s")
            goal = "{TS.present(IR.roots_go(%s, %s, acc, %s)) == True{} : Bool}" % (pat(vn, vk, "v"), p, TABLE)
            proof = None
            if vn == "BooleanValue" and sn == "Boolean":
                proof = "{==}"
            elif vn == "UnsignedValue" and sn == "Unsigned":
                proof = "uint_present(s0, v0, encodable)"
            elif vn == "BytesValue" and sn == "ByteVector":
                proof = "bytevector_present(s0, v0, encodable)"
            elif vn == "BytesValue" and sn == "ByteList":
                proof = "bytelist_present(s0, v0, encodable)"
            elif vn == "BitsValue" and sn == "BitVector":
                proof = "bitvector_present(s0, v0, encodable)"
            elif vn == "BitsValue" and sn == "BitList":
                proof = "bitlist_present(s0, v0, encodable, mixing)"
            elif vn == "BitsValue" and sn == "ProgressiveBits":
                proof = "progressive_bits_present(v0, size, mixing)"
            elif vn == "NullValue" and sn == "Null":
                proof = "{==}"
            elif vn == "EmptyItems" and sn in ("End", "Repeat"):
                proof = "{==}"
            elif vn == "Items" and sn in ("Chain", "Repeat"):
                if sn == "Chain":
                    rest = "s1"
                    vs = "V.and_left(IS.valid_go(s0, False{}), IS.valid_go(s1, True{}), legal)"
                    vr = "Shape.ok_forest(s1, V.and_right(IS.valid_go(s0, False{}), IS.valid_go(s1, True{}), legal))"
                    ok_h = "Shape.ok_single(s0, %s)" % vs
                else:
                    rest = "T.Repeat{s0}"
                    vr = "legal"
                    ok_h = "Shape.ok_single(s0, legal)"
                ph = "SC.parts(v0, s0)"; pt = "SC.parts(v1, %s)" % rest
                mh = "VD.mixing_lengths(v0, s0)"; mt = "VD.mixing_lengths(v1, %s)" % rest
                proof = ("accumulate_present(IR.roots_go(v0, s0, [], %s), acc, next => IR.roots_go(v1, %s, next, %s), "
                         "total(v0, s0, [], size, %s, concat_left(%s, %s, encodable), V.and_left(%s, %s, mixing)), "
                         "prior => total(v1, %s, prior, size, %s, concat_right(%s, %s, encodable), V.and_right(%s, %s, mixing)))"
                         % (TABLE, rest, TABLE, ok_h, ph, pt, mh, mt, rest, vr, ph, pt, mh, mt))
            elif vn == "Sequence" and sn in ("Vector", "ListOf", "ProgressiveList"):
                if sn == "Vector":
                    ve = "V.and_right(Nat.is_lt(0n, s1), IS.valid_go(s0, False{}), legal)"
                    schema_expr = "T.Vector{s0, s1}"; limit = "s1"; prog = "False{}"; length = "None{}"
                    okx = "Bool.and(Nat.is_lt(0n, s1), Nat.is_eq(SC.count(v0), s1))"
                    width = "SS.times(s1, SS.fixed_size(s0))"
                    bound = "vector_bound(SC.count(v0), s1, require_ok(%s, SC.aggregate(SC.parts(v0, T.Repeat{s0}), %s), encodable))" % (okx, width)
                    mix_items = "mixing"
                    fits = "Unit{}"
                elif sn == "ListOf":
                    ve = "legal"; schema_expr = "T.ListOf{s0, s1}"; limit = "s1"; prog = "False{}"; length = "Some{SC.count(v0)}"
                    okx = "Nat.is_le(SC.count(v0), s1)"; width = "None{}"
                    bound = "require_ok(%s, SC.aggregate(SC.parts(v0, T.Repeat{s0}), None{}), encodable)" % okx
                    mix_items = "V.and_right(SLen.fits(32n, SC.count(v0)), VD.mixing_lengths(v0, T.Repeat{s0}), mixing)"
                    fits = "V.and_left(SLen.fits(32n, SC.count(v0)), VD.mixing_lengths(v0, T.Repeat{s0}), mixing)"
                else:
                    ve = "legal"; schema_expr = "T.ProgressiveList{s0}"; limit = "0n"; prog = "True{}"; length = "Some{SC.count(v0)}"
                    okx = "True{}"; width = "None{}"; bound = None
                    mix_items = "V.and_right(SLen.fits(32n, SC.count(v0)), VD.mixing_lengths(v0, T.Repeat{s0}), mixing)"
                    fits = "V.and_left(SLen.fits(32n, SC.count(v0)), VD.mixing_lengths(v0, T.Repeat{s0}), mixing)"
                r = "SC.parts(v0, T.Repeat{s0})"
                enc = "u => IC.unwrap(IC.encode(T.Sequence{v0}, %s))" % schema_expr
                comp = "u => IR.roots_go(v0, T.Repeat{s0}, [], %s)" % TABLE
                enc_eq = ("Equal.trans(Maybe<&2, +List<U32>>, IC.unwrap(IC.encode(T.Sequence{v0}, %s)), SC.bytes(IC.encode(T.Sequence{v0}, %s)), SC.encoding_for_legal_type(%s, T.Sequence{v0}), "
                          "G.unwrap_bytes(IC.encode(T.Sequence{v0}, %s)), Equal.cong(Maybe<&2, +List<T.Part>>, Maybe<&2, +List<U32>>, r => SC.bytes(r), IC.encode(T.Sequence{v0}, %s), SC.parts(T.Sequence{v0}, %s), "
                          "Composition.parts_correct(T.Sequence{v0}, %s, Forest.valid_well_formed(%s, False{}, legal))))" % (schema_expr, schema_expr, schema_expr, schema_expr, schema_expr, schema_expr, schema_expr, schema_expr))
                enc_items = "require_body(%s, SC.aggregate(%s, %s), encodable)" % (okx, r, width)
                enc_items = "aggregate_parts(%s, %s, %s)" % (r, width, enc_items)
                comp_present = "total(v0, T.Repeat{s0}, [], size, %s, %s, %s)" % (ve, enc_items, mix_items)
                comp_scope = "Scope.roots_go_scope(v0, T.Repeat{s0}, [], size, {==})"
                if bound is None:
                    comp_count = "unit_rel(IR.roots_go(v0, T.Repeat{s0}, [], %s))" % TABLE
                    basic_count = "w => eq => cps => req => bytes => eb => Unit{}"
                else:
                    comp_count = "count_map(IR.roots_go(v0, T.Repeat{s0}, [], %s), SC.count(v0), %s, %s, repeat_count(v0, s0, size, %s))" % (TABLE, limit, bound, ve)
                    basic_count = ("w => eq => cps => req => bytes => eb => TS.packed_count(cps, bytes, SC.count(v0), w, %s, eb, shape_of(s0, SC.count(v0), %s, cps, w, Shape.facts(v0, T.Repeat{s0}, %s), req, basic_fixed(s0, w, eq)), %s)"
                                   % (limit, r, ve, bound))
                seq = ("sequence_present(IS.basic_size(s0), %s, %s, %s, %s, %s, %s, %s, %s, size, %s, encodable, %s, %s, %s, %s, %s)"
                       % (enc, comp, okx, r, width, limit, prog, length, enc_eq, comp_present, comp_scope, comp_count, basic_count, fits))
                lines = []
                if sn in ("ListOf", "ProgressiveList"):
                    ilimit = "0n" if sn == "ProgressiveList" else "IR.count_limit(IS.basic_size(s0), %s)" % limit
                    g = "{TS.present(IR.single(IR.length_mix(IR.merkle(IR.choose_chunks(IS.basic_size(s0), %s, %s), %s, %s, %s), Some{_}))) == True{} : Bool}" % (enc, comp, ilimit, prog, TABLE)
                    lines.append("%%Equal.sym(Nat, IC.count(v0), SC.count(v0), Counts.count_correct(v0)) : %s" % g)
                if sn == "ProgressiveList":
                    g = "{TS.present(IR.single(IR.length_mix(IR.merkle(IR.choose_chunks(IS.basic_size(s0), %s, %s), _, %s, %s), Some{SC.count(v0)}))) == True{} : Bool}" % (enc, comp, prog, TABLE)
                    lines.append("%%RS.zero_limit(IS.basic_size(s0)) : %s" % g)
                lines.append(seq)
                out.append("        case %s:" % p)
                for l in lines:
                    out.append("          " + l)
                continue
            elif vn == "Sequence" and sn == "Container":
                vf = "V.and_right(%s, IS.valid_go(s1, True{}), legal)" % NAMED
                proof = ("TS.composite_present(IR.roots_go(v0, s1, [], %s), IS.count(s1), False{}, None{}, size, total(v0, s1, [], size, Shape.ok_forest(s1, %s), aggregate_parts(SC.parts(v0, s1), SS.fixed_size(s1), encodable), mixing), "
                         "Scope.roots_go_scope(v0, s1, [], size, {==}), container_count(v0, s1, size, %s), Unit{})" % (TABLE, vf, vf))
            elif vn == "Sequence" and sn == "ProgressiveContainer":
                rest = "Bool.and(IS.valid_go(s1, True{}), %s)" % PROG_REST
                vf = "V.and_left(IS.valid_go(s1, True{}), %s, V.and_right(%s, %s, legal))" % (PROG_REST, NAMED, rest)
                proof = ("TS.active_present(IR.roots_go(v0, s1, [], %s), s2, size, total(v0, s1, [], size, Shape.ok_forest(s1, %s), aggregate_parts(SC.parts(v0, s1), SS.fixed_size(s1), encodable), mixing), "
                         "Scope.roots_go_scope(v0, s1, [], size, {==}))" % (TABLE, vf))
            elif vn == "Selected" and sn in ("Union", "CompatibleUnion"):
                if sn == "Union":
                    found = "SS.option(s0, U32.to_nat(v0))"
                    impl = "IS.get(s0, U32.to_nat(v0))"
                    corr = "Sch.option_correct(s0, U32.to_nat(v0))"
                    facts = "Lookups.union_lookup(s0, U32.to_nat(v0), legal)"
                    small = "DG.index_selection(v0, %s, %s)" % (found, facts)
                    okfn = "RS.index_ok(U32.to_nat(v0), 128n, %s, %s, s, same)" % (found, facts)
                    schema_expr = "T.Union{s0}"
                else:
                    found = "SS.compatible_option(s0, s1, v0)"
                    impl = "IC.selected_schema(s0, s1, v0)"
                    corr = "Helpers.selected_schema_correct(s0, s1, v0)"
                    facts = "Lookups.compatible_lookup(s0, s1, v0, [], %s, %s)" % (pick(CU, 2, "legal"), pick(CU, 3, "legal"))
                    small = facts
                    okfn = "RS.selection_ok(v0, %s, %s, s, same)" % (found, facts)
                    schema_expr = "T.CompatibleUnion{s0, s1}"
                g = "{TS.present(IR.with_schema(_, s => IR.selector_mix(IR.unwrap(IR.roots_go(v1, s, [], %s)), v0))) == True{} : Bool}" % TABLE
                recur = ("s => same => enc_s => single_ok_of(IR.roots_go(v1, s, [], %s), total(v1, s, [], size, Lookups.ok_of_option(s, %s), enc_s, mixing_selected(%s, t => VD.mixing_lengths(v1, t), s, same, mixing)), "
                         "Scope.roots_go_scope(v1, s, [], size, {==}), one_single(s, v1, size, %s))" % (TABLE, okfn, found, okfn))
                out.append("        case %s:" % p)
                out.append("          %%Equal.sym(Maybe<&2, T.Schema>, %s, %s, %s) : %s" % (impl, found, corr, g))
                out.append("          TS.union_present(%s, v1, v0, size, encodable, %s, %s)" % (found, small, recur))
                continue
            if proof is None:
                proof = absurd(goal, "encodable")
            out.append("        case %s: %s" % (p, proof))
    text = "\n".join(out) + "\n"
    text = text.replace("law basic_fixed:", '''def nat_present(r: Maybe<&2, Nat>) -> Bool:
  match r:
    case None{}: False{}
    case Some{n}: True{}

law basic_fixed:''')
    # order: helpers referencing later lemmas
    import re
    def move_before(text, name, before):
        a = text.index("\nlaw %s:" % name)
        d = text.index("\ndef %s(" % name, a)
        m = re.search(r"\n(law |def |# )", text[d + 1:])
        end = d + 1 + (m.start() if m else len(text) - d - 1)
        block = text[a:end]
        text = text[:a] + text[end:]
        i = text.index("\nlaw %s:" % before)
        return text[:i] + block + text[i:]
    text = move_before(text, "repeat_pair_eq", "repeat_pair")
    text = move_before(text, "one_fst", "one_map")
    text = move_before(text, "shape_known", "shape_of")
    a = text.index("\ndef part_contents"); b = text.index("\nlaw sequence_present")
    blk = text[a:b]; text = text[:a] + text[b:]
    i = text.index("\nlaw shape_known:")
    text = text[:i] + blk + text[i:]
    text = move_before(text, "single_ok_list", "single_ok_of")
    Path("proofs/root_total.bend").write_text(text)


if __name__ == "__main__":
    main()
